### ISSUE TITLE
内置的插件socks5是不是不支持udp呢？

### ISSUE THREAD

**Issue by tanpengsccd** [fatedier/frp#1001]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc 0.22
frps 0.20

**What operating system and processor architecture are you using (`go env`)?**
CentOS 7

**Configures you used:**
frpc.int
[common]
server_addr = XXX
server_port =7000
token = XXX

[http_proxy]
type = tcp
remote_port =8010
plugin = socks5
**Steps to reproduce the issue:**
None

**Describe the results you received:**
None

**Describe the results you expected:**
我已经尝试tcp已经可以 内网穿透了。但是frp没看到可以设置udp的配置项。readme里也没找到
那么frp内置的socks5是不是不支持udp，可以请求支持吗？
**Additional information you deem important (e.g. issue happens only occasionally):**
None

**Can you point out what caused this issue (optional)**
看到是 http_proxy 我想应该是不支持udp了吧？

那么是不是我只能有在内网frpc端再开个proxy 使用frp中转一次？
因为家里是电信玩游戏（有UDP流量）访问某些网站（公网）延迟较高200ms左右，公司是联通宽带，访问延迟比较低50ms左右，但是在内网，所以只能内网穿透如使用frp等工具。

**Comment by fatedier** [comment]
不支持，建议另外起一个 socks5 服务，再通过端口转发出去。

**Comment by websecer** [comment]
frp 是一个专注于内网穿透的高性能的反向代理应用，支持 TCP、**UDP**、HTTP、HTTPS 等多种协议。可以将内网服务以安全、便捷的方式通过具有公网 IP 节点的中转暴露到公网
