### ISSUE TITLE
关于UDP传输，单个包无法超过1500bytes，否则包数据不全

### ISSUE THREAD

**Issue by ruixiaozi** [fatedier/frp#1005]
frps,frpc 版本号:v0.22.0
centos6.8服务器.

问题描述:
在frpc的服务器上传输UDP数据回去的时候，用户接受到的udp数据包大小最大只有1500bytes，但是UDP协议能够携带更大的数据包，希望能够让传输带更大的数据包，因为存在视频图片通过UDP传输，可以忍受丢包，但是自己切块，再分包传输，需要写组包的内容

**Configures you used:**
frps.ini：
[common]
bind_port = 17
max_pool_count = 5

frpc.ini:
[common]
server_addr = x.x.x.x
server_port = 17
pool_count = 3
admin_addr = 127.0.0.1
admin_port = 7401
[ujk]
type = udp
local_ip = 127.0.0.1
local_port = 14
remote_port = 14

**Comment by ruixiaozi** [comment]
希望能够有一个配置项：设置UDP单个包的大小

**Comment by fatedier** [comment]
通常来说，超过 1500 的话，在公网传输中的效果可能得不到保证，最好还是自己做分片。在 frp 中设置超过 1500 的配置可能会占用更多的内存，对于大部分用户来说没有必要。
如果有特殊需求，还是自行修改相关参数编译源码吧。
