### ISSUE TITLE
不知道为什么udp转发不成功

### ISSUE THREAD

**Issue by zhuwei** [fatedier/frp#1011]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.22.0

**What operating system and processor architecture are you using (`go env`)?**
frps---centos6.5 64bit
frpc---windows7 sp1 64bit

**Configures you used:**
frps:
[common]
bind_port = 7000

frpc:
[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 7000

[http]
type = tcp
local_ip = 192.168.1.138
local_port = 80
remote_port = 80

[range:udp1]
type = udp
local_ip = 192.168.1.138
local_port = 10000-10001
remote_port = 10000-10001
use_encryption = false
use_compression = false

[range:udp2]
type = udp
local_ip = 192.168.1.138
local_port = 20000-20001
remote_port = 20000-20001
use_encryption = false
use_compression = false

**Steps to reproduce the issue:**
1../frps -c ./frps.ini
2.frpc.exe -c frpc.ini
3.通过工具发送udp数据

**Describe the results you received:**
frps只有http记录，没有udp的请求记录
我的工具没有接收到任何udp返回的数据

**Describe the results you expected:**
我感觉udp转发没有成功

**Additional information you deem important (e.g. issue happens only occasionally):**
无，一直都不成功。tcp很正常。
我是下载的release，不是自己编译的

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
请使用文档示例中的配置进行测试，再确认具体问题的原因是什么。

**Comment by zhuwei** [comment]
@fatedier 谢谢回复。
文档中dns是测试成功的。
不过我udp是10000负责发送、10001负责接收。

**Comment by fatedier** [comment]
DNS 测试成功，那么就说明和你的程序是相关的，需要自己排查下程序的逻辑，是不是不能简单转发出去。
