### ISSUE TITLE
在每一个HTTP/HTTPS请求中添加X-Forwarded-For 和 X-Real-IP

### ISSUE THREAD

**Issue by outtimes** [fatedier/frp#1012]
不清楚是否这样会加大消耗，而导致作者选择了只在首次连接中加入这两个头。
因实际环境有需要，还是希望能开放此功能。

另外希望能支持子域名/泛域名的泛解析，FRPS能够处理 *.frp.com直接转发到frp中。
(目前是有一台处于内网的服务器，内部署了20多个网站，外一台FRPS服务器，希望能一次性转发）

**Comment by fatedier** [comment]
已支持，https 由于不会在服务器上存放证书，不会修改用户请求，无法支持。
