### ISSUE TITLE
薛定谔的穿透失败

### ISSUE THREAD

**Issue by icy2003** [fatedier/frp#1013]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps v-)?**
0.20.0

**What operating system and processor architecture are you using (`go env`)?**
frps --- CentOS Linux release 7.5.1804 (Core)
frpc --- windows7、10（试了各种版本的windows7和10，似乎和windows没关系）

**Configures you used:**
frps

[common]
bind_port = 7000
vhost_http_port = 10080

frpc

[common]
server_addr = xxx.xx.xx.xxx
server_port = 7000

[ssh]
type = http
local_ip = 127.0.0.1
local_port = 8080
custom_domains = xx.com

**Steps to reproduce the issue:**
1../frps -c ./frps.ini
2.frpc.exe -c frpc.ini

**Describe the results you received:**
这是服务端的输出

2018/12/18 10:47:13 [1;34m[I] [proxy.go:87] [fb7126d667f0a1ef] [ssh] get a new work connection: [xxx.xx.xx.xxx:xxxxx][0m
2018/12/18 10:47:13 [1;33m[W] [newhttp.go:202] http: proxy error: EOF[0m
2018/12/18 10:47:13 [1;33m[W] [newhttp.go:202] httputil: ReverseProxy read error during body copy: unexpected EOF[0m

反复出现上面的错误

**Describe the results you expected:**

应该这样说，一样的配置，两个月前是完全不会报错的，是最近一段时间开启之后出现的，表现是，页面上比如有10个请求，刷新，5个成功，刷新，3个成功，刷新，7个成功……这些请求可能是用ajax遍历发送的相同请求（只是数据不同）

报错的请求返回的是frp的404页面

配置应该没有错，之前都好好的，会不会是服务器环境问题，比如权限之类的，frp报的几个错不清楚怎么引起的。或者说是不是网络原因？

**Comment by fatedier** [comment]
传输数据的过程中连接被对方终端。

**Comment by fatedier** [comment]
原因你只能自己调试排查，和服务器环境，网络状况，防火墙，等等都是相关的。
