### ISSUE TITLE
二级域名不同用户配置参数问题

### ISSUE THREAD

**Issue by brealin** [fatedier/frp#1015]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frps->frp_0.22.0_linux_amd64
frpc->frp_0.22.0_windows_amd64

**What operating system and processor architecture are you using (`go env`)?**
frps->ubuntu16.04
frpc->windows7/windows10

**Configures you used:**
frps:
[common]
bind_port = 7000
subdomain_host =xxxxx.cn
vhost_http_port = 8080

frpc-1:
[web]
type = http
local_port = 81
subdomain = test

frpc-2:
[web01]
type = http
local_port = 8080
subdomain = test1

**Steps to reproduce the issue:**
1.使用二级域名功能已可以正常访问，但每一个frpc配置都需要使用不同的web配置项名称。
2.比如frpc-1这台终端配置名称使用了[web]，第二台终端就不能再使用[web]而要使用[web001]，最大这个配置项只能到999即[web0]----[web999]，这样多人使用的时候还需要人工去分配这个配置项名称就比较麻烦。

**Describe the results you received:**
这个[web]配置项目名不能重名，[webxxx]这个配置项目里面的“xxx”只能带0-999，如果多人使用还要协商好这一块，很不方便。

**Describe the results you expected:**
个人认为这个[web]配置项名使用二级域名配置时，要么多个用户之间都能使用相同的配置项目名通过subdomain配置的二级域名来区分不同用户，要么这个[webxxx]中xxx可以使用任意字符。使用另外一个单独参数来控制这个二级域名解析的总数，不要限制死999个。

**Additional information you deem important (e.g. issue happens only occasionally):**
持续发生

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
不知道你的结论是如何得出的，名字不能重复是 frp 的规则，如何分配可以自行设置，你甚至可以把机器的 mac 地址加上作为名字的一部分。

**Comment by fatedier** [comment]
不知道你的结论是如何得出的，名字不能重复是 frp 的规则，如何分配可以自行设置，你甚至可以把机器的 mac 地址加上作为名字的一部分。
