### ISSUE TITLE
port unavailable

### ISSUE THREAD

**Issue by afreetgo** [fatedier/frp#1016]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frps version:0.22.0

**What operating system and processor architecture are you using (`go env`)?**
operating system: CentOS 7.3

**Configures you used:**
10.10.10.88 frps.ini
[common]
bind_port = 7000

192.168.1.2 frpc.ini
[common]
server_addr = 10.10.10.88
server_port = 7000

[ssh]
type = tcp
local_ip = 192.168.1.2
local_port = 22
remote_port = 6000
use_encryption=true
use_compression=true

192.168.1.3 frpc.ini
[common]
server_addr = 10.10.10.88
server_port = 7000

[ssh]
type = tcp
local_ip = 192.168.1.3
local_port = 22
remote_port = 6000
use_encryption=true
use_compression=true

**Steps to reproduce the issue:**
1. start 10.10.10.88 frps
2. start 192.168.1.2 frpc
3. start 192.168.1.3 frpc

**Describe the results you received:**
[W] [control.go:141] [ssh] start error: port unavailable

I hope that one service port can support SSH access to multiple client ports. But at present, it does not support it.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
`remote_port` should be different.

**Comment by afreetgo** [comment]
192.168.1.2 frpc.ini
[common]
server_addr = 10.10.10.88
server_port = 7000

[ssh]
type = tcp
local_ip = 192.168.1.2
local_port = 22
remote_port = 6000
use_encryption=true
use_compression=true

192.168.1.3 frpc.ini
[common]
server_addr = 10.10.10.88
server_port = 7000

[ssh1]
type = tcp
local_ip = 192.168.1.3
local_port = 22
remote_port = 6001
use_encryption=true
use_compression=true

That's not going to work either.
192.168.1.3 log
[W] [control.go:141] [ssh1] start error: port unavailable
10.10.10.88 log
[W] [control.go:332] [d3e17f9c23f4d0ac] new proxy [ssh1] error: port unavailable

i change remote_port 
192.168.1.3 frpc.ini
[common]
server_addr = 10.10.10.88
server_port = 7000

[ssh1]
type = tcp
local_ip = 192.168.1.3
local_port = 22
remote_port = 16000
use_encryption=true
use_compression=true

Replacing port 6001 with port 16000 was successful.
192.168.1.3 log
2018/12/20 09:55:29 [I] [service.go:205] login to server success, get run id [c1450ff7d161fdd0], server udp port [0]
2018/12/20 09:55:29 [I] [proxy_manager.go:136] [c1450ff7d161fdd0] proxy added: [ssh1]
2018/12/20 09:55:29 [I] [control.go:143] [ssh1] start proxy success
10.10.10.88 log
2018/12/20 09:46:02 [I] [proxy.go:217] [91786185d4a75687] [ssh] tcp proxy listen port [6000]
2018/12/20 09:46:02 [I] [control.go:335] [91786185d4a75687] new proxy [ssh] success
2018/12/20 09:50:31 [I] [proxy.go:217] [c1450ff7d161fdd0] [ssh1] tcp proxy listen port [16000]
2018/12/20 09:50:31 [I] [control.go:335] [c1450ff7d161fdd0] new proxy [ssh1] success

**Comment by afreetgo** [comment]
Port 6001 is occupied. The problem has been solved. thanks
