### ISSUE TITLE
间歇性断流问题

### ISSUE THREAD

**Issue by Creling** [fatedier/frp#1017]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
客户端/服务端均为 0.22.0

**What operating system and processor architecture are you using (`go env`)?**
inter处理器 amd64架构

**Configures you used:**
```
#frps.ini
[common]
bind_port = 7000
privilege_token = xxx
dashboard_port = 7500
dashboard_user = xxx
dashboard_pwd = xxx

#frpc.ini
[common]
server_addr = xxx
server_port = 7000
protocol = tcp
privilege_token = xxx

[range:seafile]
[common]
server_addr = xxx
server_port = 7000
protocol = tcp
privilege_token = xxx

[range:seafile]
type = tcp
local_ip = 127.0.0.1
local_port = 8000,8082
remote_port = 80,8082

```
用frp反代了内网的seafile网盘服务器，经常出现文件无法下载的现象，查询frp日志后发现日志中由大量“端口已被占用”的警告，但是frp server仅仅只为网盘服务器这一台服务器提供服务，所以说对中国问题的出现百思不得解。

![](https://i.loli.net/2018/12/19/5c191a091058f.png)

**Comment by fatedier** [comment]
proxy 命名不要重复。

**Comment by Creling** [comment]
抱歉，issue中的配置文件排版错了
frpc.ini如下
[common]
server_addr = xxx
server_port = 7000
protocol = tcp
privilege_token = xxx

[range:seafile]
type = tcp
local_ip = 127.0.0.1
local_port = 8000,8082
remote_port = 80,8082

似乎并没有proxy name重复的问题

**Comment by fatedier** [comment]
请把服务端和客户端的日志都贴出来。

**Comment by Creling** [comment]
占位
中午来贴配置

**Comment by Creling** [comment]
配置已贴

**Comment by fatedier** [comment]
port 从 7000 换一个端口，确认下是否多起了其他的进程，有冲突。

**Comment by Creling** [comment]
> port从7000换一个端口，确认下是否多起了其他的进程，有冲突。

好的，我试一下，晚上反馈
