### ISSUE TITLE
服务端跟客户端连接了，但是客户端就是数据转不出来

### ISSUE THREAD

**Issue by lumeiyu01** [fatedier/frp#1019]
1.我看的服务端连接
![cc](https://user-images.githubusercontent.com/46044471/50333442-58f4e100-0540-11e9-9305-f749bf7f5ba0.png)

2.我的客户端也连接上我的服务了65530
![bb](https://user-images.githubusercontent.com/46044471/50332849-627d4980-053e-11e9-8781-9978b542943d.png)

看了很多别人的错误，就是没看到我的错误，我的服务端应该是正确的。配置文件我都复制别人的，出错率应该很低。

**Comment by lumeiyu01** [comment]
具体要实现的是域名端口号访问到我本机起的服务。

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
