### ISSUE TITLE
frp http能否绑定多个端口

### ISSUE THREAD

**Issue by biless** [fatedier/frp#102]
vhost_http_port = 8080
在配置中这样就绑定了8080端口
但是在我的应用中 我希望不同的web配置绑定不同的端口

**Comment by biless** [comment]
@fatedier

**Comment by fatedier** [comment]
那直接使用 tcp 的代理类型就可以了。

**Comment by biless** [comment]
@fatedier 搜嘎 我试试

**Comment by openmynet** [comment]
@biless frp+nginx 可以完美解决你的问题

**Comment by biless** [comment]
@openmynet 利用tcp代理就可以 达到要求了

**Comment by biless** [comment]
@fatedier 麻烦大大  可以关闭了~

**Comment by 51xpage** [comment]
如何绑定多个端口呢，现在用tcp只能绑定一个，已经可以sql server转发进来了，想弄个3389的转发，不知道咋配置，试了几种方案都不行。


1、
[tcp]
vhost_tcp_port = 8433
[tcp]
vhost_tcp_port = 9389

2、
[tcp]
vhost_tcp_port = 8433
[my]
vhost_tcp_port = 9389

3、
[tcp]
vhost_tcp_port = 8433
[tcp1]
vhost_3389_port = 9389 @fatedier 

多谢
