### ISSUE TITLE
内网下面的内网用BT下载能用这个工具穿透出去吗？

### ISSUE THREAD

**Issue by klxq520** [fatedier/frp#1021]
大局域网下面又有局域网，我就在好几级局域网里，平时BT下载比较多，现在想穿透出去有没有什么办法啊？

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
