### ISSUE TITLE
xtcp点对点穿透失败

### ISSUE THREAD

**Issue by yqchen14** [fatedier/frp#1022]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc 0.22.0
frps 0.22.0

**What operating system and processor architecture are you using (`go env`)?**
Server Debian 9
Client  Win10 64bit

**Configures you used:**
Home-Computer(Win10 64bit)
[p2p_home]
type = xtcp
sk = lucienhome
local_ip = 127.0.0.1
local_port = 3389
-----------------------
Office-Computer(Win10 64bit)
[p2p_home_visitor]
type = xtcp
role = visitor
server_name = p2p_home
sk = lucienhome
bind_addr = 127.0.0.1
bind_port = 5000
-----------------------
Server(Debian 9 on Aliyun)
bind_port = 7000
bind_udp_port = 7001

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
Run frpc.exe -c frpc.ini on Office-Computer, got the following error:
2018/12/26 14:27:12 [W] [visitor.go:287] [p2p_home_visitor] get sid from client error: read udp 10.0.0.107:55097: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/README_zh.md#%E7%82%B9%E5%AF%B9%E7%82%B9%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F
