### ISSUE TITLE
win10下客户端连接出错

### ISSUE THREAD

**Issue by xinjiayu** [fatedier/frp#1024]
在win10家庭版运行frpc客户端。报以下错误。而在mac系统下同样的配置就没有问题。

D:\tools>frpc
2018/12/25 19:34:31 [W] [service.go:73] login to server failed: dial tcp 0.0.0.0:7000: connectex: No connection could be made because the target machine actively refused it.
dial tcp 0.0.0.0:7000: connectex: No connection could be made because the target machine actively refused it.

请问谁遇到这个情况？

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

**Comment by talway** [comment]
确实有这个问题，win7没问题，win10报错
