### ISSUE TITLE
custom_domain 是否支持正则表达式

### ISSUE THREAD

**Issue by v7lin** [fatedier/frp#1026]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**
希望 custom_domain 是否支持正则表达式，我的想法是，外网服务器上在 traefik 集群下部署一台 frps，内网服务器 frpc 下部署 traefik 集群，将多个二级域名内网穿透分配给内网 traefik 集群。

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
没有计划支持，请配合其他工具使用。
