### ISSUE TITLE
http_proxy 和 SwitchyOmega 无法使用，会导致frpc断开

### ISSUE THREAD

**Issue by flykarry** [fatedier/frp#1032]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.22.0

**What operating system and processor architecture are you using (`go env`)?**
frps ubuntu 16.04 aliyun hongkong
frpc win7

**Configures you used:**

frpc.ini如下
[desktop]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 10001
use_encryption = true
use_compression = true

[plugin_http_proxy]
type = tcp
remote_port = 9000
plugin = http_proxy
plugin_http_user = admin
plugin_http_passwd = 123456

**Steps to reproduce the issue:**
1. chrome 配置 SwitchyOmega代理
2. 打开局域网内部任意地址，如192.168.1.3:8080
3. 无法打开网页，且frpc控制台得到如下信息，且如果连接着远程桌面会被断开
2019/01/03 20:58:06 [I] [control.go:216] control writer is closing
2019/01/03 20:58:06 [I] [service.go:118] try to reconnect to server...
2019/01/03 20:58:06 [E] [control.go:126] work connection closed, EOF
4. 用火狐浏览器在浏览器内部配置代理，一般没有问题，偶尔也会出现这个情况

**Describe the results you received:**
无法通过SwitchyOmega设置http_proxy代理

添加连接池后
偶尔会出现400错误
页面上偶尔会有部分内容不现实

**Describe the results you expected:**
可以通过 SwitchyOmega 动态修改代理

**Comment by fatedier** [comment]
请提供更详细的错误信息？

**Comment by flykarry** [comment]
在哪里可以看到更详细的错误信息？我目前只知道在frpc的控制台可以看错误信息

**Comment by fatedier** [comment]
更多的日志错误信息。

**Comment by xuexiaokang** [comment]
SwitchyOmega 不背这个锅，这个问题应该是你的客户端到服务端延迟过大，导致frps和frpc握手的过程频繁断开，和我遇到的问题一样，可能frps和frpc之间通讯如果延迟超过90ms就会自动断开，这个不知道怎么增加允许的延迟时间

**Comment by flykarry** [comment]
首先一个，我并没有说这是SwitchyOmega的锅，我只是把我使用时看到的现象在这做一个陈述，具体是哪的问题，我并不知道
第二，我的这个http反向代理端口被阿里的云盾认为是危险端口，警告我了，所以我把这个功能给关了，毕竟不是刚需，只是玩玩，可能不能提供更多的信息了

**Comment by fatedier** [comment]
有足够信息时可以再提 issue 反馈。
