### ISSUE TITLE
udp端口可以配置点对点传输吗？

### ISSUE THREAD

**Issue by fofocx** [fatedier/frp#1034]
建立的xtcp的visitor，只监听了tcp端口，现在的版本有没有配置能使用类似xtcp一样的直连方式直连udp端口。我的情况使用udp的传输量远大于tcp，服务器的流量消耗太快了，xtcp的tcp端口都可以点对点，希望udp的端口也能直连。

Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
目前不支持 udp，使用场景相对少一些。而且 xtcp 也不完善，目前只是试验性质。
