### ISSUE TITLE
go get 安装失败

### ISSUE THREAD

**Issue by lgmcode** [fatedier/frp#104]
你好，
我想用下面的命令下载程序编译
`go get github.com/fatedier/frp`
但是提示错误
`can't load package: package github.com/fatedier/frp: no buildable Go source files in /home/webadmin/golang_work/src/github.com/fatedier/frp`
之前用这种方式安装的，挺方便的，现在是不支持这种安装方式了吗？

**Comment by fatedier** [comment]
`go get` 只能下载，无法自动编译安装到 `$GOPATH/bin` 下，需要你手动进入 `/home/webadmin/golang_work/src/github.com/fatedier/frp` 目录，执行 `make` 命令编译，编译好的程序在 `bin` 目录下。

**Comment by lgmcode** [comment]
这个过程明白，上一次就是先`go get`下载之后进到目录里`make`的，这次的问题是下载失败了，代码没有更新，所以想问一下是不是不支持这种方式下载代码了，还是说不能覆盖旧的代码

**Comment by fatedier** [comment]
试试 `go get -u github.com/fatedier/frp`

**Comment by lgmcode** [comment]
查了一下，说是因为我修改了目录下的某些文件（只修改了配置文件）导致无法merge，我把整个目录删了重新`go get` `make`就可以了。算了，下次还是用你编译好的二进制文件吧。thanks！
