### ISSUE TITLE
[需求]能否提供服务端api控制客户端上的应用的状态的接口

### ISSUE THREAD

**Issue by gilbertchenzhe** [fatedier/frp#1040]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.22.0

**What operating system and processor architecture are you using (`go env`)?**
Win10 x64

**Configures you used:**
无

**Steps to reproduce the issue:**
1.能否提供 服务端api控制客户端上的应用的状态的接口

**Describe the results you received:**
无

**Describe the results you expected:**
frps.exe 中，在dashboard_api中提供client status 管理

**Additional information you deem important (e.g. issue happens only occasionally):**
无

**Can you point out what caused this issue (optional)**
在./server/dashboard_api.go中增加接口

**Comment by fatedier** [comment]
client 的 status 只在 client 端有，服务端是没有这个数据的，所以也不能提供接口。
如果你有需求，可以将 client 端的 admin port 通过服务端暴露出去访问。

**Comment by gilbertchenzhe** [comment]
@fatedier 客户端的admin_api 我也看了，没有对client进行状态管理的接口- -

**Comment by fatedier** [comment]
目前只能查询，不能操作。

**Comment by gilbertchenzhe** [comment]
@fatedier  行吧
