### ISSUE TITLE
unix domain socket支持

### ISSUE THREAD

**Issue by lgmcode** [fatedier/frp#105]
请问在客户端能不能增加对unix domain socket的支持，这样如果frpc和服务器程序在同一个主机上的话很多时候就不用开端口了，而且性能也会有一些提升。

**Comment by fatedier** [comment]
我觉得一个启用了 unix 域套接字的服务，本身就不应该对外暴露吧。而且如果提供这个转发的话，在 frps 上肯定也是暴露一个 tcp 端口，就是说你需要用 tcp socket 去访问，你原来客户端的代码肯定就需要修改了，实际使用起来并不见得方便。

实现并不难，但是是否有这个必要还是需要考虑的。

**Comment by lgmcode** [comment]
嗯，同意你的观点，这个必要性确实没那么大。之所以会想到这个是因为我自己的主机上有几个gunicorn的服务器通过unix域套接字被nginx反向代理，再通过frpc暴露到外网（frps运行在租的服务器上），所以就想如果frpc直接就能转发到unix域套接字的话就不需要nginx了，省掉一个配置省点麻烦。不过现在这样用的也很舒服，还是你来决定加不加这个功能吧。

**Comment by fatedier** [comment]
你这个其实是指后端 web 服务是 fastcgi 之类的协议吧？比如 php 之类，这个有考虑会支持。

**Comment by lgmcode** [comment]
对，我是用python的wsgi。总之你这个项目太酷了，会一直关注的，强烈支持！

**Comment by fengqi** [comment]
也正想问, 因为也有类似的只有套接字但是没有端口的服务器, 想省掉 nginx 这一层

**Comment by fatedier** [comment]
@fengqi 有这方面的计划的，是想要实现部分 nginx 的简单的功能，让用户可以选择去掉 nginx 这一层，包括静态页面，php，其他支持 fastcgi 的应用。还有 nginx 的 url 路由，这个比较关键。

**Comment by fengqi** [comment]
赞

**Comment by yougg** [comment]
替代nginx推荐参考这个：https://github.com/azer/boxcars

**Comment by fengqi** [comment]
不是要代替，是省掉一层

发自我的 iPhone

**Comment by yougg** [comment]
@fengqi   
我知道啊, 所以我说的是参考boxcars, 不是使用boxcars.   
因为boxcars也是`Go`编写的, 并且实现了nginx的功能,  
可以直接把其功能整合到frp里面来.

**Comment by fatedier** [comment]
@yougg 感谢推荐，初步看了下，url 路由那块好像没有 nginx 那么强大。其他的我会参考一下。

**Comment by fatedier** [comment]
0.11.0 版本已支持  unix域套接字。
