### ISSUE TITLE
p2p_visitor从0.20.0开始就不能用了

### ISSUE THREAD

**Issue by xiaozonglong** [fatedier/frp#1052]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc 0.20.0   frps 0.23.1

**What operating system and processor architecture are you using (`go env`)?**
windows 10

**Configures you used:**

**Steps to reproduce the issue:**
1.client 0.20.0 visitor connect to server 0.23.1 is normal for p2p_visitor (type = stcp)
2.client since 0.20.0 can not connect to the server

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
