### ISSUE TITLE
关于 user 详细设置的建议

### ISSUE THREAD

**Issue by BingFenghan** [fatedier/frp#1053]
尊敬的 fatedier ，非常抱歉百忙中打扰您。
由于该 Issues 为建议类，故不按照您提供的排版提交了。

### 1、关于 User
尽管 Frp 已经做了 token 进行限制，但我对于 user 设置的功能方面还是要提一个比较小的建议。
希望在 frps 的配置文件里提供 user 白名单功能。

缘由：假设有多人使用 Frp，但其中有一个 user 达到使用期限，想要禁止该 user 使用。在目前的版本中，唯一的解决方案就是修改token，然后通知每一位 user 更新 token，这样无疑会增加很多的麻烦。

### 2、关于 frps 配置热更新
这个建议与上一条建议也是相关联的，既然 frps 配置中支持了 user 白名单，希望能够增加 frps 配置热更新功能。

缘由：或许可能会觉得这个建议没有必要，这个只需要重新启动 frps，frpc 端也会自动连接。但是，这当中会造成的一个问题就是，重启后 dashboard 中的数据也会被清空。在很多情况下，我们是希望 dashboard 中的数据保留下来的。

备选方案：将 dashboard 中的数据储存在本地文件或 log 中，下次启动时仍然加载该数据，并且为用户提供清空 dashboard 中数据的配置选项或指令。

### 尾声
鄙人是做 Python 和 Java 语言的，对 go 语言并不了解，对此如何解决不能给出细化方案，望您谅解。
第一条建议希望您能够采纳，第二条建议您可以稍作斟酌。

此致

**Comment by fatedier** [comment]
user 的配置可能会在将来的版本中移除。

账户管理等功能将不在开源项目的计划中。开源版本主要供个人用户学习，调试使用，侧重点是内网穿透。
其他的一些高级需求，例如运维，账户管理等会在不开源的 pro 版本中提供。

**Comment by cancundeyingzi** [comment]
所以Pro版本在哪
