### ISSUE TITLE
[web] start error: type [http] not support when vhost_http_port is not set

### ISSUE THREAD

**Issue by gococ** [fatedier/frp#1054]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
服务端frp_0.23.1_windows_386，客户端frp_0.23.1_linux_386

**What operating system and processor architecture are you using (`go env`)?**
服务端为阿里云windows 2012  64位版本，客户端为黑群晖主机（linux）

**Configures you used:**
#frps.ini
[common]
bind_port = 7000
vhost_http_port = 8080

#frpc.ini
[common]
server_addr = 47.104.xxx.xx
server_port = 7000

[web]
type = http
local_port = 80
custom_domains = nas.xxx.cn

**Steps to reproduce the issue:**
1.配置服务端，按照code说明进行配置，未进行任何修改
2.配置客户端，按照code说明进行配置，仅修改IP地址和域名。
3.对服务器开启7000端口和8080端口
4.开启服务端和客户端，提示“[control.go:141] [web] start error: type [http] not support when vhost_http_port is not set”错误，实际服务端有对vhost_http_port进行配置

**Describe the results you received:**
[control.go:141] [web] start error: type [http] not support when vhost_http_port is not set

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
请按照说明文档中的描述一步一步操作，仔细查看日志确认。

https://github.com/fatedier/frp/blob/master/README_zh.md#%E9%80%9A%E8%BF%87%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9F%9F%E5%90%8D%E8%AE%BF%E9%97%AE%E9%83%A8%E7%BD%B2%E4%BA%8E%E5%86%85%E7%BD%91%E7%9A%84-web-%E6%9C%8D%E5%8A%A1

**Comment by amanoooooooooooooooo** [comment]
Maybe you should use same frps version, frpc version  
Suggest using https://hub.docker.com/r/amanohikaru/frp-docker  
My test is Ok

**Comment by lee86** [comment]
你可能需要在启动frp的时候，把你的新配置加载进去，linux下是./fprs -c frps.ini，windows不知道该怎么加载，但确确实实0.20的时候我遇到了[nas] start error: type [http] not support when vhost_http_port is not set。
然后我尝试使用了vhost_https_port，再次运行frps的时候还是这个错误，所以我尝试了./fprs -c frps.ini，surprise！显示的是成功启动3个监听端口，分别思tcp http https，所以你可能需要重新试一试了

**Comment by xinqinglhj** [comment]
Windos服务器，启动服务端请尝试下面的命令：
frps.exe -c frps.ini
不要直接双击 frps.exe
我的是这样解决的。

**Comment by zuosc** [comment]
我的更诡异  我是在windows启动的frps

用cmd正常，用powershell就这个错误。

也是坑

**Comment by bestboy** [comment]
服务器指定配置文件启动解决问题 ./frps -c frps.ini 不然就各种幺蛾子

**Comment by liyunhui-1** [comment]
> 服务器指定配置文件启动解决问题 ./frps -c frps.ini 不然就各种幺蛾子

确实是这个原因，有知道具体情况嘛？

**Comment by jiusiguer** [comment]
It could be a server vendor firewall problem.
