### ISSUE TITLE
功能建议：增加FRPS群组功能

### ISSUE THREAD

**Issue by linfengde20099** [fatedier/frp#1057]
功能建议：
       如果有两台阿里云服务器，我想同时运行【frps】服务端互为备份，那我需要在内网客户端运行两个【frpc】进程吗？如果是这样的话，我建议在【frpc】客户端上增加【frps】服务器群组的功能。

**Comment by fatedier** [comment]
如果能用两个 frpc 做到的事情，就用两个 frpc 来做。
