### ISSUE TITLE
功能建议： 建议添加一键安装脚本（主要方便部署linux服务器）

### ISSUE THREAD

**Issue by snowdream** [fatedier/frp#1058]
功能建议： 建议添加一键安装脚本（主要方便部署linux服务器）

**Comment by yunnl** [comment]
解压 设置权限 运行，这种还要一键脚本？

**Comment by fatedier** [comment]
可以提供一些规范化的例如支持 systemctl 的配置，TODO

**Comment by flykarry** [comment]
我觉着这个已经属于非常简单的东西了

**Comment by suojiang** [comment]
可以像ss、v2ray写个sh脚本，安装、更新、重启、开机启动等服务，这样更容易上手

**Comment by lyin888** [comment]
> 可以像SS，v2ray写个SH脚本，安装，更新，重启，开机启动等服务，这样更容易上手

使用supervisor来守护frps

sudo apt-get update

sudo apt-get install supervisor

vi /etc/supervisor/conf.d/frps.conf

[program:frps]
command = /root/frps/frps -c /root/frps/frps.ini  # frps存放路径
autostart = true

# 重启supervisor
sudo systemctl restart supervisor
# 查看supervisor运行状态
sudo supervisorctl status

**Comment by MvsCode** [comment]
Frps 一键安装脚本&管理脚本 for Linux，frp：v0.23.3  https://github.com/MvsCode/frp-onekey

**Comment by a-wing** [comment]
为什么不考虑把软件推到 linux 发行版的官方仓库中

archlinux 的 AUR 上有人打了这个包
不过按规范这种应该算 bin 包

https://aur.archlinux.org/packages/frp/

目前 archlinuxcn 软件仓库中有一共有三个 frp 的包

最近准备合并成一个然后 `split package`

https://github.com/archlinuxcn/repo/issues/1083

**Comment by fatedier** [comment]
@a-wing 不是很了解相关的东西，你能提供一些帮助？

**Comment by kantkong** [comment]
参考这个 https://github.com/clangcn/onekey-install-shell

**Comment by funnypro** [comment]
话说日志的话

会在相关的服务管理程序提供的日志功能上吗

**Comment by chronicom** [comment]
> 为什么不考虑把软件推到 linux 发行版的官方仓库中
> 
> archlinux 的 AUR 上有人打了这个包
> 不过按规范这种应该算 bin 包
> 
> https://aur.archlinux.org/packages/frp/
> 
> 目前 archlinuxcn 软件仓库中有一共有三个 frp 的包
> 
> 最近准备合并成一个然后 `split package`
> 
> [archlinuxcn/repo#1083](https://github.com/archlinuxcn/repo/issues/1083)

frps.service 中 
User=nobody  
好像在ubuntu 下有问题   nobody 没有绑定80端口的权限

**Comment by a-wing** [comment]
> 好像在ubuntu 下有问题 nobody 没有绑定80端口的权限

正常的发行版。 1024 以下的端口当然都不行。

特权端口 你自己用 `nginx` 或 `iptables` 转一下。

**Comment by funnypro** [comment]
> > 好像在ubuntu 下有问题 nobody 没有绑定80端口的权限
> 
> 正常的发行版。 1024 以下的端口当然都不行。
> 
> 特权端口 你自己用 `nginx` 或 `iptables` 转一下。

不过为什么要用 nobody 用户来启动 frp 呢？

**Comment by Athenacle** [comment]
话说为啥没有官方docker啊，去[DockerHub](https://hub.docker.com/search?q=frp&type=image)逛了一圈，找了个`xddxdd/frps`两个月前更新的。。

客户端使用的时候一直是说`[W] [service.go:82] login to server failed: session shutdown`

服务器端`[D] [service.go:304] Accept new mux stream error: invalid protocol version`

一看服务器版本0.22，客户端版本0.26。。不得不自己FROM scratch做一个。。~为啥不能向后兼容~

**Comment by snowdream** [comment]
新增docker版本，请大家帮忙review一下。
https://github.com/fatedier/frp/pull/1291

**Comment by funnypro** [comment]
可以在[这里](https://github.com/gofrp/deploy)提交相关的东西了

**Comment by ttimasdf** [comment]
我是从google过来的，简单搜一下能搜到好多……给后来的人汇总一下。
没营养的： #1302 #902 #1474 
一些解决方案： #1058 （本贴）
作者说明不维护service脚本（包括Dockerfile）的原因： https://github.com/fatedier/frp/pull/1291#issuecomment-502966225

建议加到项目FAQ里。

**Comment by dzcpy** [comment]
建议还是做个 debian 包，直接安装的话还是多少省点事

**Comment by donmor** [comment]
挖一下，看没什么人给Debian打包就搓了一套，常见架构都有，欢迎帮忙测试🙂
[![Debian Build Bot](https://github.com/donmor/frp-debian/actions/workflows/dpkg-buildpackage.yml/badge.svg?event=release)](https://github.com/donmor/frp-debian/actions/workflows/dpkg-buildpackage.yml)
