### ISSUE TITLE
能用ipv6公网地址来做穿透吗？

### ISSUE THREAD

**Issue by aiyolo** [fatedier/frp#1059]
如题

_Sent from my MI 8 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by Faithful-Mind** [comment]
赞同，现在中国小县城办宽带送的光猫都有IPv6地址块用作分发公网IP了，建议通过只有IPv4地址的服务器做P2P穿透时可以带上IPv6地址试试
