### ISSUE TITLE
frpc v0.23.2 开机启动出错，但 v0.22 正常！

### ISSUE THREAD

**Issue by wang20150419** [fatedier/frp#1062]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.23.2

**What operating system and processor architecture are you using (`go env`)?**
ubuntu 16.04 32bit

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

设置 systemd 开机启动，无法登陆 frps ( v0.23.2)，更换为 v0.22 版本后正常。

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
