### ISSUE TITLE
使用http未开启压缩、未加密，连接非常慢，5s左右打开http

### ISSUE THREAD

**Issue by yongliangliu** [fatedier/frp#1063]
frps:Frps On Docker 
frpc:0.20.0 arm
使用http未开启压缩、未加密，连接非常慢，5s左右打开http

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
