### ISSUE TITLE
frp dashboard bug

### ISSUE THREAD

**Issue by shzchina** [fatedier/frp#1065]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.23.2

**What operating system and processor architecture are you using (`go env`)?**
arm linux 32

**Configures you used:**
[common]
server_addr = my server ip
server_port = 7000

[range:mc813东方农业园]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 10000
use_encryption = true
use_compression = true

frps config
[common]
bind_port = 7000

# set dashboard_addr and dashboard_port to view dashboard of frps
# dashboard_addr's default value is same with bind_addr
# dashboard is available only if dashboard_port is set
dashboard_addr = 0.0.0.0
dashboard_port = 7500

# dashboard user and passwd for basic auth protect, if not set, both default value is admin
dashboard_user = admin
dashboard_pwd = admin

**Steps to reproduce the issue:**
1. 使用0.20.0 版本的服务端和客户端时 服务端dashboard ，connections traffic in /out都正常
2.  使用0.23.2 版本时，当传输数据时connections 增加 ，而 traffic in /out始终为零，感觉这里有bug
3. 所有版本都是保持一致测试的，没有进行交叉测试

**Describe the results you received:**
traffic in /out 都是0 ，connections = 7

**Describe the results you expected:**
使用0.23.2 版本时，传输数据traffic in /out 应该增加

**Additional information you deem important (e.g. issue happens only occasionally):**
测试了windows平台和arm，都存在这个问题，怀疑frps部分的代码问题

**Can you point out what caused this issue (optional)**
暂时没有进行深入分析和测试

**Comment by fatedier** [comment]
目前流量统计是在连接断开后增加的，所以连接建立中时流量为0，可以等连接断开后再刷新看看。

**Comment by fatedier** [comment]
本地测试 tcp 和 http 类型统计都正常。

**Comment by shzchina** [comment]
按照断开后 测试正常
