### ISSUE TITLE
能否实现外网服务器端口映射到本地内网的服务器？

### ISSUE THREAD

**Issue by Michael2008S** [fatedier/frp#1066]
我想内网服务器访问外网的对应端口的非公开，但有不想建立正向的隧道。

请问 frp 能否实现外网服务器的内部服务端口映射到本地？
我看了文档好像没找到这方面。找到的都是本地端口映射到外网服务器。

**Comment by fatedier** [comment]
可以采用 stcp 的方式，但是还是需要通过一台有公网 IP 的中间节点中转。

假设 A 是本地，B 是外网某个机器，C 可以是另外一台有公网 IP 的机器或者就是 B。
采用 stcp 方式，A 和 B 都部署 frpc，A 绑定本地一个端口映射到 B 的一个端口，访问 A 的本地端口即访问 B 的对应端口。

**Comment by Michael2008S** [comment]
试了一下，解决了。
谢谢
