### ISSUE TITLE
web代理问题建议

### ISSUE THREAD

**Issue by yutent** [fatedier/frp#107]
1、 vhost_http_port = 8080  这一项配置,我觉得应该放到「web」里面 而不是「common」里, 这样我可以指定多个web端口使用;

2、custom_domains = abc.com 这一项配置,不应该强制要求吧。默认通过127.0.0.1:8080这样子就好了,然后使用nginx作个反向代理, 这样就不需要每次都加个端口去访问  abc.com:8080 , 看着不舒服啊

3、nginx反向代理的问题, 这个应该是上面第2点的延续; 因为当我的custom_domains设置为一个域名的时候, 我发现服务启动后 127.0.0.1:8080 这个是无法访问的, 导致nginx反向代理的时候 proxy_pass 不能指向127.0.0.1:8080,只能指向 abc.com:8080; 如些一来, 又要走多一次dns解析了。所以我建议考虑上面第2点, 直接取消 域名绑定这个配置吧, 只留一个端口转发就好了,剩下的交给nginx去做(花生棒就是这样子的)。

**Comment by fatedier** [comment]
你说的这些都 ok 啊，你把和 `web` 相关的配置全都去掉，直接使用 tcp 的类型就可以啦，因为你根本不需要根据域名进行路由，也不需要考虑多个客户端同时连接的问题，就怎么简单怎么来。

其他的功能，有需要的人自然会去用。我的考虑是提供全面的功能，然后通过配置来决定是否启用。就好比有的人希望 frp 把 nginx 的部分功能也替代了，可以开箱即用。而你的需求是只做端口转发，其他交给 nginx 来做。没有什么矛盾的，都支持。

**Comment by yutent** [comment]
哦,我再看看文档。
----------
把nginx取代我觉得不太现实, 毕竟nginx发展了那么久,性能和稳定性都是经的住考验的, 易用性也好。

**Comment by fatedier** [comment]
不是要把 nginx 取代。。。

frp 和 nginx 是两个用途不同的应用，nginx 适用于生产环境，frp 更多的时候是用于测试和个人应用，实现部分 nginx 的功能可以让用户更快捷方便的使用，减少部署的复杂度。而不是说要重新创造一个可以完全替代 nginx 的 web server。
