### ISSUE TITLE
Allow dashboard over same port

### ISSUE THREAD

**Issue by luckydonald** [fatedier/frp#1071]
Feature Request.

Currently, we can [already](https://github.com/fatedier/frp#port-reuse) combine `vhost_http_port` and `bind_port`, as the websocket uses `/~!frp` as route.
It would be great to be able to attach the admin interface to the same port at e.g. `/dashboard`.

It could look like the following:

```ini
[common]
# The API port of frp
bind_port = 80

# The HTTP port (proxy to you)
vhost_http_port = 80

# dashboard
dashboard_port = 80
dashboard_route = /admin
dashboard_user = admin_user
dashboard_pwd = security_sausage
```

Notice the new `dashboard_route` element.
Also a `dashboard_host` could be helpful, to use the `Host` header.

#### My current config
You know, for completeness sake.
`server.ini`:
```ini
[common]
# The API port of frp
bind_port = {{ .Envs.PORT }}

# The HTTP port (proxy to you)
vhost_http_port = {{ .Envs.PORT }}

# whitelist ports
# allow_ports={{ .Envs.PORT }}

# security token
token =  {{ .Envs.TOKEN }}

# dashboard
dashboard_port = 12314
# dashboard's username and password are both optional，if not set, default is admin.
dashboard_user = admin_user
dashboard_pwd = security_sausage
``` 

`client.ini`:
```ini
[common]
server_addr = {{ .Envs.SERVER_HOST }}
server_port = {{ .Envs.SERVER_PORT }}
token =  {{ .Envs.TOKEN }}
login_fail_exit = false
protocol = websocket

[web]
type = http
local_ip = {{ .Envs.LOCAL_HOST }}
local_port = {{ .Envs.LOCAL_PORT }}
remote_port = {{ .Envs.SERVER_PORT }}
locations = /
custom_domains = {{ .Envs.SERVER_HOST }}
```

<sup><sub>Obviously the used password is fake :D<br>But it would be so cool!</sub></sup>

**Comment by fatedier** [comment]
I have considered this feature and the problem is how to distinguish dashboard requests from `v_host_http` port requests. Your proposal with `dashboard_route` will affect the dashboard api prefix which is `/api/xxx` now. I'm not sure if it's simple and stable to allow users redefine it. As you know, dashboard js code will call these apis with hardcode api prefix.

Also in some cases, owners only want to bind dashboard port with a local address such as `127.0.0.1`。`dashboard_addr` can be different with `bind_addr`.

We may need a more reliable solution.

**Comment by luckydonald** [comment]
Maybe we could change the API endpoint to `/~!api/` to minimize collision.

The javascript could define and use a global variable `var API_URL = 'http://example.com/~!api'`. This could be a server template.

Another idea would be virtual hosts.

**Comment by luckydonald** [comment]
An alternative to rendering a template with the dashboard url could be asking the already existing `/~!frp` websocket for it.

**Comment by fatedier** [comment]
The websocket url prefix `/~!frp` is only used between frpc and frps, no one will see that.

`/ ~!api/` looks strange for users that they will used it to call the apis.

**Comment by ogimenezb** [comment]
How about using a config like:

```
[common]
# The API port of frp
bind_port = 80

# The HTTP port (proxy to you)
vhost_http_port = 80

# dashboard
dashboard_port = 80
dashboard_vhost = admin
dashboard_user = admin_user
dashboard_pwd = security_sausage
```

best of both worlds
