### ISSUE TITLE
on centos7, the loading frpc will stop the mariadb starting.

### ISSUE THREAD

**Issue by michaelhsucn** [fatedier/frp#1072]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.23.2

**What operating system and processor architecture are you using (`go env`)?**
Centos7 amd64

**Configures you used:**
[common]
server_addr = xxx.xxx.xxx
server_port = 5443
token = xxxxxxxxxxxxxxxxxxxxx
login_fail_exit = false
log_file = /dev/null
log_level = info
log_max_days = 3
tcp_mux = true
protocol = kcp

[test]
type = http
local_ip = 127.0.0.1
local_port = 80
use_encryption = false
use_compression = true
subdomain = test

**Steps to reproduce the issue:**
1.   configure a mariadb running it on the centos7, it works fine and after rebooting it also works fine.
2.  setup a frpc.service for auto start on centos, and it works fine.
3.  reboot the centos7 or try to reboot the mariadb, you will see it can not be started.

**Describe the results you received:**
systemctl start mariadb.service
Job for mariadb.service failed because the control process exited with error code. See "systemctl status mariadb.service" and "journalctl -xe" for details.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
You need to provide:
1. frpc.service configure file.
2. systemctl status mariadb.service info.

Try to solve your problem by yourself first until you are sure it's a bug.

**Comment by fatedier** [comment]
Paste complete logs? You should check why your mysql start failed.

**Comment by michaelhsucn** [comment]
[root@localhost ~]# systemctl status -l mariadb.service
● mariadb.service - MariaDB database server
   Loaded: loaded (/usr/lib/systemd/system/mariadb.service; enabled; vendor pres                                            et: disabled)
   Active: failed (Result: exit-code) since Fri 2019-02-01 19:22:21 HKT; 18min a                                            go
  Process: 6343 ExecStartPost=/usr/libexec/mariadb-wait-ready $MAINPID (code=exi                                            ted, status=1/FAILURE)
  Process: 6342 ExecStart=/usr/bin/mysqld_safe --basedir=/usr (code=exited, stat                                            us=1/FAILURE)
  Process: 6311 ExecStartPre=/usr/libexec/mariadb-prepare-db-dir %n (code=exited                                            , status=0/SUCCESS)
 Main PID: 6342 (code=exited, status=1/FAILURE)

Feb 01 19:22:21 localhost.localdomain mysqld_safe[6342]: /usr/bin/mysqld_safe: l                                            ine 696: /dev/null: Permission denied
Feb 01 19:22:21 localhost.localdomain mysqld_safe[6342]: /usr/bin/mysqld_safe: l                                            ine 727: /dev/null: Permission denied
Feb 01 19:22:21 localhost.localdomain mysqld_safe[6342]: 190201 19:22:21 mysqld_                                            safe Starting mysqld daemon with databases from /var/lib/mysql
Feb 01 19:22:21 localhost.localdomain mysqld_safe[6342]: /usr/bin/mysqld_safe: l                                            ine 867: /dev/null: Permission denied
Feb 01 19:22:21 localhost.localdomain mysqld_safe[6342]: /usr/bin/mysqld_safe: l                                            ine 871: /dev/null: Permission denied
Feb 01 19:22:21 localhost.localdomain systemd[1]: mariadb.service: main process                                             exited, code=exited, status=1/FAILURE
Feb 01 19:22:21 localhost.localdomain systemd[1]: mariadb.service: control proce                                            ss exited, code=exited status=1
Feb 01 19:22:21 localhost.localdomain systemd[1]: Failed to start MariaDB databa                                            se server.
Feb 01 19:22:21 localhost.localdomain systemd[1]: Unit mariadb.service entered f                                            ailed state.
Feb 01 19:22:21 localhost.localdomain systemd[1]: mariadb.service failed.

**Comment by fatedier** [comment]
The error info is `Permission denied` with `/dev/null`, it's not a bug about frp.

You can google for it to find more information.

**Comment by michaelhsucn** [comment]
Let me try, Really Appreciate, Thumbs UP!
