### ISSUE TITLE
Could not get some modules.

### ISSUE THREAD

**Issue by kuoruan** [fatedier/frp#1075]
**What version of frp are you using (./frpc -v or ./frps -v)?**

...

**What operating system and processor architecture are you using (`go env`)?**

OSX

**Configures you used:**

...

**Steps to reproduce the issue:**

```go list -m all```

**Describe the results you received:**

```
go: finding github.com/hashicorp/yamux v0.0.0-20180314200745-2658be15c5f0
go: github.com/hashicorp/yamux@v0.0.0-20180314200745-2658be15c5f0: unknown revision 2658be15c5f0
go: error loading module requirements
```

**Describe the results you expected:**

Download all the modules and build.

**Additional information you deem important (e.g. issue happens only occasionally):**

```
go version  
go version go1.11.5 darwin/amd64
```

**Can you point out what caused this issue (optional)**

Bad module version?

**Comment by ogimenezb** [comment]
Hi, 

Add this to your mod file at the end:

replace github.com/hashicorp/yamux => github.com/hashicorp/yamux v0.0.0-20181012175058-2f1d1f20f75d

replace github.com/templexxx/reedsolomon => github.com/templexxx/reedsolomon v0.0.0-20170927015403-7092926d7d05

**Comment by kuoruan** [comment]
Thanks.

**Comment by Mewster** [comment]
I think this bug should be addressed in the readme or in the branch, I would't be able to compile without this fix.

**Comment by kuoruan** [comment]
```
go get github.com/hashicorp/yamux@master
go get github.com/templexxx/reedsolomon@master
```

**Comment by jinmiaoluo** [comment]
> go get github.com/hashicorp/yamux@master

refer: https://golang.org/cmd/go/#hdr-Module_queries
