### ISSUE TITLE
frp 如何实现单服务器多代理用户的条件下限制每个用户网络流量的需求？

### ISSUE THREAD

**Issue by pokon548** [fatedier/frp#1076]
我目前是在阿里云有每月网络流量限制的服务器上使用frp。由于服务器需要在公网环境下接受多个代理用户的连接请求，故需要一种可以限制每个用户流量配额的方法，以防止服务器每月流量超额
目前frp的设置项可以实现这种功能吗？或者说，CentOS的一些工具可以实现这种功能？

**Comment by iBug** [comment]
Nothing specific to frp, but have you tried common solution with `iptables`? It seems to work very well with arbitrary software. Just make sure you set the rules correctly for each port.

**Comment by snowdream** [comment]
关注

**Comment by git8154** [comment]
github.com/cnlh/nps 有你说的功能
