### ISSUE TITLE
frp connection interrupted, while n2n work well.

### ISSUE THREAD

**Issue by yidizhun** [fatedier/frp#1077]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frps -v 0.23.3 and frpc -v0.23.3

**What operating system and processor architecture are you using (`go env`)?**
frps - linux and frpc windows 2008 R2

**Configures you used:**
[common]
server_addr = x.x.x.x (server IP)
server_port = xxx
[web]
type = http
local_port = xxx
custom_domains = my domain

**Steps to reproduce the issue:**
2019/02/04 20:48:20 [I] [control.go:143] [web] start proxy success
2019/02/05 20:09:13 [E] [control.go:126] work connection closed, EOF
2019/02/05 20:09:13 [E] [control.go:126] work connection closed, EOF
2019/02/05 20:09:13 [E] [control.go:126] work connection closed, EOF
2019/02/05 20:09:13 [I] [control.go:217] control writer is closing
2019/02/05 20:09:13 [I] [service.go:118] try to reconnect to server...
2019/02/05 20:09:13 [E] [control.go:126] work connection closed, EOF
2019/02/05 20:09:13 [I] [service.go:206] login to server success, get run id [2c
58d7fa434cb61f], server udp port [0]
2019/02/05 20:09:13 [I] [proxy_manager.go:137] [2c58d7fa434cb61f] proxy added: [
web]
2019/02/05 20:09:14 [I] [control.go:143] [web] start proxy success
2019/02/05 20:22:02 [E] [control.go:126] work connection closed, EOF
2019/02/05 20:22:02 [I] [control.go:217] control writer is closing
2019/02/05 20:22:02 [I] [service.go:118] try to reconnect to server....

**Describe the results you received:**
Connection was interrupted everyday.

**Describe the results you expected:**
Update the frp thus connection will not be interrupted.

**Additional information you deem important (e.g. issue happens only occasionally):**
frp was disconnected everyday.

**Can you point out what caused this issue (optional)**

**Comment by aimuch** [comment]
**同样的问题**
服务端提示：
2019/02/13 06:26:32 [I] [control.go:274] [76d25415845e0eea] control writer is closing
2019/02/13 06:26:32 [I] [control.go:349] [76d25415845e0eea] client exit success
2019/02/13 06:26:32 [I] [service.go:317] client login info: ip [180.167.178.250:2076] version [0.24.1] hostname [] os [linux] arch [amd64]
2019/02/13 06:27:02 [I] [control.go:274] [76d25415845e0eea] control writer is closing
2019/02/13 06:27:02 [I] [control.go:349] [76d25415845e0eea] client exit success
2019/02/13 06:27:02 [I] [service.go:317] client login info: ip [180.167.178.250:2077] version [0.24.1] hostname [] os [linux] arch [amd64]
2019/02/13 06:27:32 [I] [control.go:274] [76d25415845e0eea] control writer is closing
2019/02/13 06:27:32 [I] [control.go:349] [76d25415845e0eea] client exit success
2019/02/13 06:27:32 [I] [service.go:317] client login info: ip [180.167.178.250:2078] version [0.24.1] hostname [] os [linux] arch [amd64]
客户端提示跟你一模一样

**Comment by iniwf** [comment]
@aimuch 我用v0.24.1也出现这样的问题，你换成哪个旧版本也出现？用0.1几版本的会不会出现？

**Comment by aimuch** [comment]
> ### **同样的问题**
> **服务端提示**：
> 
> ```
> 2019/02/13 06:26:32 [I] [control.go:274] [76d25415845e0eea] control writer is closing
> 2019/02/13 06:26:32 [I] [control.go:349] [76d25415845e0eea] client exit success
> 2019/02/13 06:26:32 [I] [service.go:317] client login info: ip [ip:2076] version [0.24.1] hostname [] os [linux] arch [amd64]
> 2019/02/13 06:27:02 [I] [control.go:274] [76d25415845e0eea] control writer is closing
> 2019/02/13 06:27:02 [I] [control.go:349] [76d25415845e0eea] client exit success
> 2019/02/13 06:27:02 [I] [service.go:317] client login info: ip [ip:2077] version [0.24.1] hostname [] os [linux] arch [amd64]
> 2019/02/13 06:27:32 [I] [control.go:274] [76d25415845e0eea] control writer is closing
> 2019/02/13 06:27:32 [I] [control.go:349] [76d25415845e0eea] client exit success
> 2019/02/13 06:27:32 [I] [service.go:317] client login info: ip [ip:2078] version [0.24.1] hostname [] os [linux] arch [amd64]
> ```
> **客户端提示:**
> 
> ```
> 2019/02/13 14:36:08 [I] [service.go:214] login to server success, get run id [041f847], server udp port [0]
> 2019/02/13 14:36:08 [I] [proxy_manager.go:137] [041f847] proxy added: [ssh]
> 2019/02/13 14:36:38 [I] [control.go:217] control writer is closing
> 2019/02/13 14:36:38 [E] [control.go:126] work connection closed, EOF
> 2019/02/13 14:36:38 [I] [service.go:126] try to reconnect to server...
> 2019/02/13 14:36:38 [I] [service.go:214] login to server success, get run id [041f847], server udp port [0]
> 2019/02/13 14:36:38 [I] [proxy_manager.go:137] [041f847] proxy added: [ssh]
> 2019/02/13 14:37:08 [I] [control.go:217] control writer is closing
> 2019/02/13 14:37:08 [I] [service.go:126] try to reconnect to server...
> 2019/02/13 14:37:08 [E] [control.go:126] work connection closed, EOF
> 2019/02/13 14:37:08 [I] [service.go:214] login to server success, get run id [041f847], server udp port [0]
> 2019/02/13 14:37:08 [I] [proxy_manager.go:137] [041f847] proxy added: [ssh]
> ```
> 开始以为是版本问题，换成旧版本也这样，换服务器试问题依旧。

底层协议改成KCP，目前可以用了。

**Comment by fatedier** [comment]
连接被断开，很大可能是网络环境问题，比如公司防火墙禁止使用 frp 的协议等等。

相同配置，在同一台机器上启动 frpc 和 frps，如果连接没有问题，那么基本上就是上面说的问题。

**Comment by fatedier** [comment]
v0.25.0 版本新增了 TLS 的支持，在 frpc 中配置 `tls_enable = true` 来启用，服务端也需要更新到最新版本。

启用 TLS 后，报文特征就不明显了，可能可以避免一些这样的问题。
