### ISSUE TITLE
经常输入某些异常指令导致关闭

### ISSUE THREAD

**Issue by chaoyueziji** [fatedier/frp#1079]
版本为：0.21.0_linux_amd64.
配置详情：服务端与客户端同版本号,配置采用原始配置，服务端为阿里云服务器。
问题：输入某些 nvidia-smi 需要返回GPU利用率，或者top需要实时更新CPU利用率的导致客户端异常崩掉。
详细：
客户端：
[E] [control.go:152] [b7020102258947d5] work connection closed, EOF
2019/02/07 16:14:31 [I] [control.go:308] [b7020102258947d5] control writer is closing
2019/02/07 16:14:31 [I] [control.go:407] [b7020102258947d5] try to reconnect to server...
服务端：
[I] [control.go:220] [b7020102258947d5] control writer is closing
2019/02/08 00:14:31 [I] [proxy.go:73] [b7020102258947d5] [ssh] proxy closing
2019/02/08 00:14:31 [I] [proxy.go:119] [b7020102258947d5] [ssh] listener is closed
2019/02/08 00:14:31 [I] [control.go:292] [b7020102258947d5] client exit success

是阿里云问题嘛？还是？我看两台电脑的时间不匹配，是否传输的时候也会因为这个缘由。

**Comment by fatedier** [comment]
你换一个环境用同样的配置测试，就可以知道是否是由于特定的环境问题引起的。

**Comment by chaoyueziji** [comment]
> 你换一个环境用同样的配置测试，就可以知道是否是由于特定的环境问题引起的。

emmm,同样也会出现。。。

**Comment by fatedier** [comment]
那就把服务端和客户端都放在本地测试，你需要自行验证你的命令对 cpu 或网络的影响。

**Comment by ssuhvs** [comment]
用了一段时间的v0.21.0,最近突然无法正常使用了，本地服务也是正常的，重启也没用，偶尔有一个请求可以正常连接，刷新就提示 The page you visit not found.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

The server is powered by frp.

Faithfully yours, frp.

**Comment by ssuhvs** [comment]
不知道有没有人遇到过， 是否是阿里云的问题？？？ 服务 器端 linux v0.21.0 客户端windows

**Comment by chaoyueziji** [comment]
> 不知道有没有人遇到过， 是否是阿里云的问题？？？ 服务 器端 linux v0.21.0 客户端windows

我是重启能撑一会，但是如果继续使用则挂掉，之前没有出现。

**Comment by aimuch** [comment]
2019/02/13 06:26:32 [I] [control.go:274] [76d25415845e0eea] control writer is closing
2019/02/13 06:26:32 [I] [control.go:349] [76d25415845e0eea] client exit success
2019/02/13 06:26:32 [I] [service.go:317] client login info: ip [180.167.178.250:2076] version [0.24.1] hostname [] os [linux] arch [amd64]
2019/02/13 06:27:02 [I] [control.go:274] [76d25415845e0eea] control writer is closing
2019/02/13 06:27:02 [I] [control.go:349] [76d25415845e0eea] client exit success
2019/02/13 06:27:02 [I] [service.go:317] client login info: ip [180.167.178.250:2077] version [0.24.1] hostname [] os [linux] arch [amd64]
2019/02/13 06:27:32 [I] [control.go:274] [76d25415845e0eea] control writer is closing
2019/02/13 06:27:32 [I] [control.go:349] [76d25415845e0eea] client exit success
2019/02/13 06:27:32 [I] [service.go:317] client login info: ip [180.167.178.250:2078] version [0.24.1] hostname [] os [linux] arch [amd64]
