### ISSUE TITLE
Close client through inactivity?

### ISSUE THREAD

**Issue by Mewster** [fatedier/frp#1090]
**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc, 0.24.1

**What operating system and processor architecture are you using (`go env`)?**
Linux ARM

**Question:**
Is it possible to auto-close the client if no operation have been made for a certain amount of time? Is it doable directly through the client, or can an external script read the status of the client to check that nothing has been made on the past [time] and kill the process?

**Comment by fatedier** [comment]
Set `admin_addr` and `admin_port`.

GET /api/status
