### ISSUE TITLE
2019/02/16 01:37:42 [W] [control.go:141] [web] start error: type [http] not support when vhost_http_port is not set

### ISSUE THREAD

**Issue by HoneyLeee** [fatedier/frp#1092]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.24.1

**What operating system and processor architecture are you using (`go env`)?**
### the client get wrong on debian9 but work well on centos 7

**Configures you used:**
#frps.ini
[common]
bind_port = 7000
vhost_http_port = 80

#frpc.ini
[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 7000
[web]
type = http
local_port = 80
custom_domains = www.google.com

**Describe the results you received:**
2019/02/16 01:37:42 [W] [control.go:141] [web] start error: type [http] not support when vhost_http_port is not set

**Comment by fatedier** [comment]
./frps -c ./frps.ini

**Comment by imaskm** [comment]
@fatedier how did this issue get resolved?
