### ISSUE TITLE
windows远程桌面断开后，client连接server不成功

### ISSUE THREAD

**Issue by shixy163** [fatedier/frp#1093]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.24.1

**What operating system and processor architecture are you using (`go env`)?**
Linux & Windows

**Configures you used:**
[common]
server_addr = xxx.xxx.xxx.xx
server_port = 7000
token = xxx
protocol = kcp

[rdp]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 3389

**Steps to reproduce the issue:**
None

**Describe the results you received:**
每次windows远程桌面连接使用后断开，client就会一直连不上server

**Describe the results you expected:**
希望不要断

**Additional information you deem important (e.g. issue happens only occasionally):**
2019/02/16 19:09:40 [I] [service.go:214] login to server success, get run id [88b43cc18690411f], server udp port [7001]
2019/02/16 19:09:40 [I] [proxy_manager.go:137] [88b43cc18690411f] proxy added: [rdp]
2019/02/16 19:09:40 [I] [control.go:143] [rdp] start proxy success
2019/02/16 19:12:31 [I] [control.go:217] control writer is closing
2019/02/16 19:12:31 [E] [control.go:126] work connection closed, EOF
2019/02/16 19:12:31 [I] [service.go:126] try to reconnect to server...
2019/02/16 19:12:41 [W] [service.go:129] reconnect to server error: i/o deadline reached
2019/02/16 19:12:42 [I] [service.go:126] try to reconnect to server...
2019/02/16 19:12:52 [W] [service.go:129] reconnect to server error: i/o deadline reached
2019/02/16 19:12:54 [I] [service.go:126] try to reconnect to server...

**Can you point out what caused this issue (optional)**
None

**Comment by lovean** [comment]
我也遇到相同问题，断开来就一直是这个错误。

**Comment by tobyqin** [comment]
same problem.

**Comment by fatedier** [comment]
kcp 有问题就使用 tcp，确保自己的网络环境正常。
