### ISSUE TITLE
如何实现多个子域名对应不同的本地服务端口。

### ISSUE THREAD

**Issue by snowdream** [fatedier/frp#1096]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
Frps version 0.20.0
Frpc version 0.20.0

**What operating system and processor architecture are you using (`go env`)?**
Frps   CentOS 7
Frps    meilin kooleshare

**Configures you used:**
```
# frpc.ini
[common]
server_addr = **********
server_port = 1986
token = 12213212121
log_file = /dev/null
log_level = info
log_max_days = 3
subdomain_host = gogogo.tech

[snowdream-ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 1986
remote_port = 2048
use_encryption = true
use_compression = true

[snowdream-router-http]
type = http
local_port = 80
remote_port = 8080
custom_domains = gogogo.tech

[snowdream-router-https]
type = https
local_port = 8443
remote_port = 8443
custom_domains = gogogo.tech

[snowdream-nodejs-test]
type = http
local_port = 3000
remote_port = 8081
subdomain = nodejs
```

**Steps to reproduce the issue:**
1. start frps frpc
2. check http://gogogo.tech:8080
3. check http://nodejs.gogogo.tech:8081

**Describe the results you received:**
http://gogogo.tech:8080   it does work great.
http://nodejs.gogogo.tech:8081    it does not work.  

**Describe the results you expected:**
http://gogogo.tech:8080    it shows   https://127.0.0.1:80
http://nodejs.gogogo.tech:8081     it shows   https://127.0.0.1:3000

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
https://github.com/fatedier/frp#visit-your-web-service-in-lan-by-custom-domains

Read docs first.
