### ISSUE TITLE
frp 与 systemd 协调问题

### ISSUE THREAD

**Issue by funnypro** [fatedier/frp#1097]
目前我在阿里的主机上部署了一个 frps 并
使用 systemd 的服务启动它

frps 版本：0.22.0

在使用当中，我遇到了一些与 systemd 不太协调的问题（虽然说时间不长）

我个人认为一些问题可能在 frpc 上也会出现

1.frps 的日志输出接入（注释 frp 所有日志相关选项） systemd 提供的的日志后，frp 由于不知道 systemd 已经接管 frps 的日志输出导致出现多余的时间

2.目前 frps 想要重载配置只能杀掉再重启，不过 frpc 重载配置相比 frps 对 systemd 更加友好

目前就这两点

希望会出现类似 `frps --systemd-service（配置文件在这个参数添加时在 /etc/frps.conf）` 之类的参数来启用对 systemd 更友好的特性（例如说服务单元的类型可以成为 notify 还有ExecReload 之类可以不用额外指定什么的）

**Comment by fatedier** [comment]
应用和 systemd 无关，不会专门适配各种服务管理的组件。建议借助其他方式来完成。

**Comment by funnypro** [comment]
自己处理吗？
