### ISSUE TITLE
多个域名对应多个http远程端口怎么实现？

### ISSUE THREAD

**Issue by snowdream** [fatedier/frp#1098]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.20.0
**What operating system and processor architecture are you using (`go env`)?**

mac

**Configures you used:**
```
# frpc.ini
[web01]
type = http
local_port = 80
remote_port = 80
custom_domains = a.yourdomain.com

[web02]
type = http
local_port = 81
remote_port = 81
custom_domains = b.yourdomain.com
```

**Describe the results you received:**
a.yourdomain.com:80  == > 192.168.1.1:80
b.yourdomain.com:80  == > 192.168.1.1:81

**Describe the results you expected:**
a.yourdomain.com:80  == > 192.168.1.1:80
b.yourdomain.com:81  == > 192.168.1.1:81

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by broven** [comment]
nginx 反向代理
