### ISSUE TITLE
Proxy by host-header

### ISSUE THREAD

**Issue by rmchale** [fatedier/frp#1099]
I am looking to setup two endpoints on port 80 but different by host header / domain name.  

I get this error
```
2019/02/24 20:18:47 [W] [control.go:391] [f70d3e6dd2b31258] new proxy [test1] error: port already used                          
```

```
[test1]
type = tcp
local_ip = 10.10.0.100
local_port = 3000
remote_port = 80
custom_domains=test1.domain.com

[test1]
type = tcp
local_ip = 10.10.0.100
local_port = 3001
remote_port = 80
custom_domains=test2.domain.com
```

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Read doc first.

**Comment by rmchale** [comment]
Ok this is a feature request.  Proxy by host header use the domain to direct traffic to a the appropriate backend.

If I try this currently it says the port is already used.

**Comment by fatedier** [comment]
https://github.com/fatedier/frp#visit-your-web-service-in-lan-by-custom-domains
