### ISSUE TITLE
关于服务器流量问题

### ISSUE THREAD

**Issue by yi-ge** [fatedier/frp#110]
我研究了文档，但是没弄明白一个问题。如果用frp进行内网穿透，那么内网服务器的流量会像VPN那样全部转发到外网服务器吗？如果我在内网假设了服务器，客户端下载这个服务器的资源。流量会全部经传外网服务器吗？还是说只是端口转发的流量经传，实际文件大小的流量不经过外网服务器？

**Comment by fatedier** [comment]
和 vpn 不同，不是所有流量都经过外网服务器转发，只有你配置了的本地端口的流量才会经过服务器转发。

**Comment by wy373226722** [comment]
那加入说我配置了本地80端口做静态资源服务器，外网服务器中的frps绑定域名abc.com和8080到本地80端口，我通过外网访问abc.com:8080下载静态资源服务器中的100M视频。这个视频所有流量都会经过外网服务器转发吗？

**Comment by fatedier** [comment]
是的。

**Comment by wy373226722** [comment]
那有没有什么办法让外网服务器只做搭桥作用，不实际承担流量呢？如果能解决这个问题，想必frp能创造更大价值。

**Comment by JimLee1996** [comment]
那必须有路由功能支持；或者支持udp打洞之类的吧。。。

**Comment by wy373226722** [comment]
@JimLee1996 恩。理论上是这样，但是如果HTTP协议就不好做。

**Comment by wy373226722** [comment]
我将会参与到frp的开发，争取实现我说这个功能。

**Comment by JimLee1996** [comment]
嗯嗯！非常支持！我也要向你们这些大神学习
;-)

**Comment by lnzoro** [comment]
支持udp就行吧

**Comment by Foristkirito** [comment]
所以这个功能最后解决了吗 @yi-ge

**Comment by liunianbanbo** [comment]
同想实现外网服务器不承担实际流量的需求
