### ISSUE TITLE
TCP端口映射会导致http认证失败

### ISSUE THREAD

**Issue by arkerwu** [fatedier/frp#1100]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.21.0
**What operating system and processor architecture are you using (`go env`)?**
centos 7.4

**Configures you used:**
映射一个特殊应用到外网出现的问题，这个软件一个端口有http、tcp、udp的3种请求包，只设置tcp、udp映射不设置http就无法通过这个软件的http认证；映射http和udp能通过http认证但走tcp的数据库又用不了；
所以是不是用只用tcp映射会导致的http认证不通过？
然而这个版本的frp，服务端http和tcp不能同一端口，望解决~

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by wisecsj** [comment]
一个端口不可能既走tcp又走udp协议吧？

**Comment by fatedier** [comment]
HTTP 底层基于 tcp 请求，直接使用 tcp 即可。
