### ISSUE TITLE
release 里  mips 编译的frpc 版本为 0.20.0，不兼容新版frps 0.24.1

### ISSUE THREAD

**Issue by jayagami** [fatedier/frp#1101]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

mips 版的 frpc 版本为 0.20.0
**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
请同步更新到最新版本。

**Comment by jayagami** [comment]
> 请同步更新到最新版本。

抱歉，检查很多次后发现参数填写错误(使用一个错误的配置文件)，mipsle的0,20,0   frpc能连上 0.24.1的 frps

但是最新版的 miple(64)中的 frpc 版本均为 0.20.0

```
[RT/home/root/card/frp_0.24.1_linux_mipsle]# frpc -v
0.20.0
```

**Comment by fatedier** [comment]
编译都是脚本自动编译，不太可能会打包错，建议你重新在 github release 页面下载最新版本测试一下。

**Comment by jayagami** [comment]
mips(64) frpc的版本应该是0.20.0

```shell
BusyBox v1.29.3 (2018-12-10 05:22:08 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

[RT-N56U_B1 /home/root]# cd card/test/
[RT-N56U_B1 /home/root/card/test]# ls
frp_0.24.1_linux_mipsle.tar.gz
[RT-N56U_B1 /home/root/card/test]# rm *
[RT-N56U_B1 /home/root/card/test]# wget https://github.com/fatedier/frp/rele
ases/download/v0.24.1/frp_0.24.1_linux_mipsle.tar.gz
Connecting to github.com (52.74.223.119:443)
Connecting to github-production-release-asset-2e65be.s3.amazonaws.com (52.216.232.67:443)
frp_0.24.1_linux_mip 100% |*************************************************************************************************************| 6433k  0:00:00 ETA
[RT-N56U_B1 /home/root/card/test]# tar zvxf frp_0.24.1_linux_mipsle.tar.gz 
frp_0.24.1_linux_mipsle/
frp_0.24.1_linux_mipsle/frps_full.ini
frp_0.24.1_linux_mipsle/frps.ini
frp_0.24.1_linux_mipsle/frpc
frp_0.24.1_linux_mipsle/frpc_full.ini
frp_0.24.1_linux_mipsle/frps
frp_0.24.1_linux_mipsle/LICENSE
frp_0.24.1_linux_mipsle/frpc.ini
[RT-N56U_B1 /home/root/card/test]# frpc -v
0.20.0
[RT-N56U_B1 /home/root/card/test]# 
```
