### ISSUE TITLE
subdomain中有大写字母会导致子域名解析失效

### ISSUE THREAD

**Issue by StarMX** [fatedier/frp#1102]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.24.1

**What operating system and processor architecture are you using (`go env`)?**
windows386 arm

**Configures you used:**

**Steps to reproduce the issue:**
1. frpc.ini中subdomain 后如果有大写字母导致 http: proxy error: no such domain

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
请按照格式完整填写 issue。
