### ISSUE TITLE
希望在dashboard中能显示客户端版本

### ISSUE THREAD

**Issue by wolfgangsk07** [fatedier/frp#1105]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
24.1

**What operating system and processor architecture are you using (`go env`)?**
x86_64/windows;arm/linux

**Configures you used:**
无需

**Steps to reproduce the issue:**
无需

**Describe the results you received:**
无

**Describe the results you expected:**
无

**Additional information you deem important (e.g. issue happens only occasionally):**

frp每次的更新都非常棒，所以经常需要随着frp的更新去更新客户端版本，但是并不知道没个客户端的版本号，逐一查看很费力。希望能再dashboard增加版本显示。
**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
新版本已支持

**Comment by yangjieshao** [comment]
新的版本 v0.67.0 不显示客户端版本号了
