### ISSUE TITLE
custom_domains设置不同域名问题

### ISSUE THREAD

**Issue by gouez** [fatedier/frp#1106]
我有两个域名a.com和b.com  启动两个frpc, 第一个frpc将a.com的请求都转发到nginx，可以正常工作。但是第二个frpc的custom_domains设置为*.b.com或者b.com始终都不行？ 设置成*.a.com就可以正常访问第二个web服务。 请问这个该配置啊？

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

请按照格式提供完整的信息。
