### ISSUE TITLE
v0.24.1的FRPC端管理面板密码问题

### ISSUE THREAD

**Issue by mybove** [fatedier/frp#1109]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
./frpc v0.24.1
**What operating system and processor architecture are you using (`go env`)?**
CentOS 6.5 (Final)

**Configures you used:**
admin_addr = 127.0.0.1
admin_port = 7400
admin_user = admin
admin_pwd = abcd+efg

**Steps to reproduce the issue:**
1.开启frpc管理面板
2.密码设置成aa@bb或aa+bb类似的格式
3.登录的时候密码只要输入aabb就可以直接登录

**Describe the results you received:**
？

**Describe the results you expected:**
修正bug

**Additional information you deem important (e.g. issue happens only occasionally):**
无

**Can you point out what caused this issue (optional)**
可能是正则匹配问题

**Comment by fatedier** [comment]
本地无法复现。

**Comment by darkengine** [comment]
应该是urlencode的问题，特别是aa+bb这个密码，其中的额“+”号在某些语言（在php的后端遇到过）/库里边会被转义成空格或者直接去掉。
