### ISSUE TITLE
点对点内网穿透成功,流量为啥还是通过服务器中转?

### ISSUE THREAD

**Issue by yuhuan21** [fatedier/frp#1110]
frp版本是0.24.1.
服务器是linux
两台客户机是:win74_x64

XTCP失败,但STCP成功,可是流量为什么还是通过服务器中转呢?

![image](https://user-images.githubusercontent.com/10203925/53709155-b034fd00-3e71-11e9-8aea-c7cf0b6a236a.png)
![image](https://user-images.githubusercontent.com/10203925/53709161-bb882880-3e71-11e9-94db-c68aaf5ea1b1.png)

1.Frps服务器运行在香港,只有1M的速度.
2.两台需要对接的客户机都是对等50M的电信内网主机
3.在进行文件传输的时候,速度也只有1M,因为能传输文件,所以链接是成功的,但流量应该还是通过服务器中转的.

**Comment by fatedier** [comment]
[stcp](https://github.com/fatedier/frp/blob/master/README_zh.md#%E5%AE%89%E5%85%A8%E5%9C%B0%E6%9A%B4%E9%9C%B2%E5%86%85%E7%BD%91%E6%9C%8D%E5%8A%A1)
[xtcp](https://github.com/fatedier/frp/blob/master/README_zh.md#%E7%82%B9%E5%AF%B9%E7%82%B9%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F)

两者完全不同。

**Comment by mike07026** [comment]
我也测试过p2p，关掉服务器端程序，连接就中断了，感觉还是经过服务器的

**Comment by topillar** [comment]
> 我也测试过p2p，关掉服务器端程序，连接就中断了，感觉还是经过服务器的
p2p也是要经过服务器建立连接和保持连接的吧
