### ISSUE TITLE
XTCP get sid from client ERROR

### ISSUE THREAD

**Issue by yuhuan21** [fatedier/frp#1111]
用XTCP,错误是获取不到SID,这个有办法解决吗?
难道我这个是NAT设备不支持?
![image](https://user-images.githubusercontent.com/10203925/53715770-c9e43d80-3e8d-11e9-8440-8a8776d7f138.png)
![image](https://user-images.githubusercontent.com/10203925/53715788-d5376900-3e8d-11e9-9861-0a65a08203b5.png)
![image](https://user-images.githubusercontent.com/10203925/53715814-f13b0a80-3e8d-11e9-8cbd-ebcf89870f45.png)

**Comment by fatedier** [comment]
[点对点穿透](https://github.com/fatedier/frp/blob/master/README_zh.md#%E7%82%B9%E5%AF%B9%E7%82%B9%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F) 

请先仔细阅读文档。
