### ISSUE TITLE
远程连接windows时被拒绝

### ISSUE THREAD

**Issue by daheyinyin** [fatedier/frp#1113]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.24.1

**What operating system and processor architecture are you using (`go env`)?**
Linux & Windows

**Configures you used:**
[common]
server_addr = xxx.xxx.xxx.xx
server_port = 7000
[rdp]
type = tcp
local_ip = 127.0.1.44
local_port = 2222
remote_port = 6000

**Steps to reproduce the issue:**
none

**Describe the results you received:**
J019/03/06 20:11:18 [I] [service, go:214] login to server success, get run id [***** ], server udp port [0]
J019/03/06 20:11:18 [I] [proxy.manager. go:137] [*****] proxy added： [rdp]
J019/03/06 20:11:18 [I] [control, go：143] [rdp] start proxy success
J019/03/06 20:11:47 [E] [proxy, go:446] [rdp] connect to local service [127.0.1.44:2222] error： dial top 127.0.1.44:2222connectex： No connection could be made because the target machine actively refused it.
J019/03/06 20:11:57 [E] [proxy, go:446] [rdp] connect to local service [127.0.1.44:2222] error： dial top 127.0.1.44:2222connectex： No connection could be made because the target machine actively refused it.
J019/03/06 20:13:38 [E] [proxy, go:446] [rdp] connect to local service [127.0.1.44:2222] error： dial top 127.0.1.44:2222connectex： No connection could be made because the target machine actively refused it.

**Describe the results you expected:**
正常连接

**Additional information you deem important (e.g. issue happens only occasionally):**
none

**Can you point out what caused this issue (optional)**
none

**Comment by kybom** [comment]
检查一下你的代理有没有问题

**Comment by kybom** [comment]
你的本地rdp服务配置正确吗？内网地址可以访问吗？

**Comment by daheyinyin** [comment]
> 你的本地rdp服务配置正确吗？内网地址可以访问吗？

可以

**Comment by hianghokung** [comment]
请再次确认你的服务器防火墙是否放行了6000端口。

**Comment by here2011** [comment]
我也遇到这个问题，一直连接RDP正常，偶然出现无法建立连接，因为目标机器积极拒绝它。

**Comment by daheyinyin** [comment]
> 请再次确认你的服务器防火墙是否放行了6000端口。

Netstat -an 没有发现6000端口
防火墙是全部关闭的

**Comment by fatedier** [comment]
日志提示很清楚了，从你的机器无法和 127.0.1.44:2222 建立连接，只能自行排查下相关的网络环境和服务是否正常。

**Comment by flyarong** [comment]
我的windows7环境，127.0.0.1:22端口没开启，什么情况？

**Comment by zhang14725804** [comment]
检查frp server和frp client启动没有，相应端口开启没有，配置是否正确，还有可能事多个代理冲突呢
