### ISSUE TITLE
FRP not connecting to upstream server

### ISSUE THREAD

**Issue by jobs-git** [fatedier/frp#1114]
I used the default configuration frps_full for frps then used frpc_full for frpc. I modified it a bit to help me expose my upstream server:

```bash
[web]
type = http
local_ip = 127.0.0.2
local_port = 4567

use_encryption = false
use_compression = false
#subdomain = web01
custom_domains = testing.com
```

However, I dont seem to connect to my upstream. What is the proper way of configuring w/ upstream server?

**Comment by fatedier** [comment]
Do not use frps_full.ini and frpc_full.ini. They are only example files to show supported params.

Read document first https://github.com/fatedier/frp#visit-your-web-service-in-lan-by-custom-domains .

**Comment by jobs-git** [comment]
You were right! Thank man!
