### ISSUE TITLE
服务端一直显示 control writer is closing

### ISSUE THREAD

**Issue by Lijunjie9502** [fatedier/frp#1115]
2019/03/08 01:53:04 [I] [control.go:274] [d594a47f7c1688bb] control writer is closing
2019/03/08 01:53:04 [I] [control.go:349] [d594a47f7c1688bb] client exit success
2019/03/08 01:53:05 [I] [service.go:317] client login info: ip [xxx.xxx.xxx.xxx:port] version [0.22.0] hostname [] os [

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
