### ISSUE TITLE
frp配合jupyter notebook连接失败

### ISSUE THREAD

**Issue by starfish55555** [fatedier/frp#1116]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.22.0
**What operating system and processor architecture are you using (`go env`)?**
服务端 (Server)：Ubuntu 18.04
客户端(Client)：Ubuntu 18.04
**Configures you used:**

**服务端 (Server):**
[common]
bind_port = 7000
vhost_http_port = 8888
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin

**客户端(Client)：**
[common]
server_addr = xxx.xxx.xxx.xxx #公网服务器IP
server_port = 7000

[ssh1]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 2019

[jupyter]
type = http
local_port = 8888
custom_domains = xxx.xxx.xxx.xxx #公网服务器IP

**jupyter notebook配置文件~/.jupyter/jupyter_notebook_config.py**
c.NotebookApp.ip = '0.0.0.0' 
c.NotebookApp.password = 'sha1:870aa8e039cd:74aa3d7ef50031510f3b5b403328260b108fcf95'
c.NotebookApp.allow_root = True
c.NotebookApp.open_browser = False  
c.NotebookApp.port = 8888 

**Steps to reproduce the issue:**
1. ssh正常访问
2. jupyter 通过127.0.0.1:8888本地访问正常
3. xxx.xxx.xxx.xxx:7500正常访问
4. 但是远程通过xxx.xxx.xxx.xxx:8888无法访问

**Describe the results you received:**

浏览器地址栏输入xxx.xxx.xxx.xxx:8888出现
The page you visit not found.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

The server is powered by frp.

Faithfully yours, frp.

frps服务端提示 [newhttp.go:209] http: proxy error: no such domain

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
我的服务端和客户端防火墙全部打开，相应的端口全部放行。觉得应该是哪配置错了，搞了一下午都没连上。有没有哪位用过frp+jupyter，请各位大佬帮帮忙，衷心感谢

**Comment by fatedier** [comment]
frp 的配置没什么问题，确认 custom_domains  和在浏览器中访问的一致？

**Comment by starfish55555** [comment]
> frp 的配置没什么问题，确认 custom_domains 和在浏览器中访问的一致？
> 
> 在 frps 的日志文件中查找 `http proxy listen for host [127.0.0.1] location []` 这样的日志，看 host 是否正确。

是我配置错了，现在可以连上了

**Comment by Miaotxy** [comment]
@starfish55555  请问哪儿配置错了啊，我跟你现在配置的是一样的， 遇到的问题也是一样的。

**Comment by starfish55555** [comment]
> @starfish55555 请问哪儿配置错了啊，我跟你现在配置的是一样的， 遇到的问题也是一样的。
c.NotebookApp.ip = '0.0.0.0'改为c.NotebookApp.ip = '*'试试，具体可参见我写过的一篇教程
https://blog.csdn.net/starfish55555/article/details/96788672
