### ISSUE TITLE
可以实现frps服务端热更新配置吗？

### ISSUE THREAD

**Issue by MrJCJC** [fatedier/frp#1119]
更新frps.ini后需要把服务断掉然后再次启动使配置生效，这种终端服务的形式不是很好，如果支持已启动的服务热更新配置，那是极好的。

**Comment by fatedier** [comment]
所有的代理配置都在客户端，服务端的配置几乎不用变更，热更新没有太大意义，且增加复杂度。

**Comment by MrJCJC** [comment]
没别的意思，只是提个建议。服务端配置热更新个人觉得还是可以做一下的，比如更新一个allow_ports，就要把现有的服务中断再重新起来，这个终端会影响到现有的连接。辛苦作者

**Comment by fatedier** [comment]
就比如 allow_ports 的更新，port 的管理是有状态的，动态的变更需要做复杂的状态管理，检索之前允许的 port，将其释放。

还有一些绑定地址，端口之类的配置，动态更新的话也需要考虑类似的问题，增加复杂度。

你这个需求转换一下思路，改成停止 frps 时，其他资源全部释放，但是等待当前已有的连接全部断开后再退出，或延迟一段时间后退出。这样新的 frps 服务可以用新的配置运行，且原来的连接也不会断开。

**Comment by Jexbat** [comment]
其实可以参考[nps](https://github.com/cnlh/nps)的下发配置的模式。这种方式应用场景还是比较广泛的。

**Comment by fatedier** [comment]
@Jexbat 之前的 issue 已经有回复类似的问题，不在此项目的规划内，如果有需求可尝试其他项目。

**Comment by inkstoner** [comment]
哈哈 在20年改源码自己实现了一个 从服务端去配客户端的
