### ISSUE TITLE
use_encryption 和 tls_enable 可以同时使用不？

### ISSUE THREAD

**Issue by xiaopiao5789** [fatedier/frp#1126]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.25.0

**What operating system and processor architecture are you using (`go env`)?**
Linux

偶尔使用 frp 加密链接某款代理软件实现绕过某东西，今天看到更新日志增加 tls_enable 支持，立马给两端都更新了 frp，可以连上但是过不了多久似乎开始被某东西给你懂的，现在已经改回去之前的配置。所以就想问问能否两个同时启用（是否会同时生效）。

**Comment by fatedier** [comment]
可以同时使用，相当于做了两次加密，所以并不是很有必要。

只使用 use_encryption 的话，login 信息是明文的，也就是说根据连接建立后发送的报文就可以识别到其中的内容，login 完成后的通信内容都是加密的。

tls_enable 启用的话，所有 frpc 和 frps 之间的流量都会经过加密。倾向于使用这个参数取代 use_encryption。

至于启用 TLS 后被拦截之类的，这方面我不是很了解。

**Comment by MvsCode** [comment]
> 可以同时使用，相当于做了两次加密，所以并不是很有必要。
> 
> 只使用 use_encryption 的话，login 信息是明文的，也就是说根据连接建立后发送的报文就可以识别到其中的内容，login 完成后的通信内容都是加密的。
> 
> tls_enable 启用的话，所有 frpc 和 frps 之间的流量都会经过加密。倾向于使用这个参数取代 use_encryption。
> 
> 至于启用 TLS 后被拦截之类的，这方面我不是很了解。

启用tls，速度会有所下降吗

**Comment by fatedier** [comment]
@MvsCode 会下降，就像 http 和 https 的差距一样，牺牲效率，提高安全性。

**Comment by xiaopiao5789** [comment]
> @MvsCode 会下降，就像 http 和 https 的差距一样，牺牲效率，提高安全性。

use_encryption 也会降低速度吗？相对 tls 这个应该会增加少许负载。

**Comment by fatedier** [comment]
需要加密，必然会牺牲性能，但是如果 CPU 资源足够，影响应该可以忽略。和启用 TLS 的消耗类似。

**Comment by vmvz** [comment]
@fatedier 请问开启了 tls_enable 是不是在控制台看不到状态

![image](https://user-images.githubusercontent.com/1652700/57186213-7c2b9600-6f0d-11e9-956c-2dad33be198c.png)

显示 Encryption false

**Comment by fatedier** [comment]
@vmvz tls_enable 是全局的，启用了之后，此 frpc 和 frps 之间的流量都是加密的，和 `use_encryption` 这个参数无关了，所以不显示在具体的某个 proxy 上了。
