### ISSUE TITLE
打开http网页时，能不能先弹出用户和密码进行认证，通过后再打开页面？

### ISSUE THREAD

**Issue by zyy111999** [fatedier/frp#113]
打开http网页时，能不能先弹出用户和密码进行认证，通过后再打开页面？

**Comment by fatedier** [comment]
#101 dev 分支已支持，下个版本发布。

**Comment by zyy111999** [comment]
什么时候出下个版本啊？frp比ngrok方便多了，资源也节省

**Comment by fatedier** [comment]
预计要到下个月底了，你可以先自己编译一下 dev 分支的版本使用。

**Comment by lu4kyd0y** [comment]
很喜欢你们的项目 有联系方式吗 群什么的 这个反向代理支持高并发不 是否有内存泄漏 参考ngrok的源码？

**Comment by fatedier** [comment]
@lu4kyd0y 没有群，有什么问题都可以在 issues 里提，另外和这个 issue 无关的话题建议另开一个 issue 讨论。

**Comment by yi-ge** [comment]
不建议直接添加这个功能，或者说这个功能可以做成插件或模块 @fatedier

**Comment by fatedier** [comment]
@yi-ge 这个功能比较常用，我也有这个需求，通过配置可以决定是否启用。

插件的功能还不在近期的规划。短期来说，还没有那种互相冲突或者特别复杂的对性能有影响的需求，这部分可能之后再考虑。

**Comment by yi-ge** [comment]
@fatedier 我建议涉及webserver的内容最好作为可选部分单独打包，这样安全性、稳定性、软件大小都有帮助。

**Comment by fatedier** [comment]
@yi-ge 个人更倾向于简单，方便，易于部署使用，也是这个项目的初衷。

**Comment by yi-ge** [comment]
分离一个简单的web认证页面相对于整体岂不更简单，需要的放在同一目录，不需要的不用下载。:)

**Comment by yi-ge** [comment]
@fatedier 
分离一个简单的web认证页面相对于整体岂不更简单，需要的放在同一目录，不需要的不用下载。:)

**Comment by zyy111999** [comment]
@fatedier dev分支版本是开发版吗？哪有下载？

**Comment by fatedier** [comment]
@zyy111999 `go get github.com/fatedier/frp` 下载源码，切到 dev 分支，执行 `make` 命令编译。

需要 >= go1.5 的环境。

**Comment by w12928293** [comment]
客户端需要同步不？因为是远端管理路由，这个功能太实用了

**Comment by fatedier** [comment]
@w12928293 客户端需要同步更新，因为增加了在客户端通过配置文件配置用户名和密码的功能。

**Comment by fatedier** [comment]
Supported in v0.9.0.
