### ISSUE TITLE
v0.25.0在XP系统下面不能使用

### ISSUE THREAD

**Issue by fe6520** [fatedier/frp#1131]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc v0.25.0
frps v0.25.0

**What operating system and processor architecture are you using (`go env`)?**
XP

**Configures you used:**
v0.24.1以下版本使用正常

**Steps to reproduce the issue:**
1.客户端Windows XP从V0.24.0升成v0.25.0后启动报错：panic: Failed to find GetFileInformationByHandleEx procedure in kernel32.dll: Th
e specified procedure could not be found.如果再换成v0.24.1可以正常使用。
2.
3.

**Describe the results you received:**

**Describe the results you expected:**
希望后续版本继续对老系统的支持。

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
Go 在新版本中将不会再支持 win7 以前的系统，所以后续的 frp release 版本也不兼容这些系统。

如果有特殊需求，可以自行使用 Go1.10 编译此项目。

**Comment by fe6520** [comment]
> Go 在新版本中将不会再支持 win7 以前的系统，所以后续的 frp release 版本也不兼容这些系统。
> 
> 如果有特殊需求，可以自行使用 Go1.10 编译此项目。

知道了。谢谢！
