### ISSUE TITLE
希望增加泛域名解析对多级子域名支持

### ISSUE THREAD

**Issue by mybove** [fatedier/frp#1132]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
./frpc -v0.25.0

**What operating system and processor architecture are you using (`go env`)?**
centos6.5

**Configures you used:**
custom_domains = *.a.com

**Steps to reproduce the issue:**
1.custom_domains = *.a.com
2.打开a.a.com正常，但是打开多级子域名a.a.a.com的时候就会不会解析
3.

**Describe the results you received:**
打开多级子域名a.a.a.com的时候就会不会解析，会出现404错误页面。
只有添加custom_domains = *.a.a.com后才能解析到正常结果
**Describe the results you expected:**
希望配置custom_domains = *.a.com能够自动匹配到该域名的无限级子域名

**Additional information you deem important (e.g. issue happens only occasionally):**
无

**Can you point out what caused this issue (optional)**
无

**Comment by hianghokung** [comment]
这个已经超出frp的职责范围了......
　　*.*.a.com这种两级通配子域名存在亿万兆种可能，而且如果你要配HTTPS SSL证书的话，也不可能会有这种万能证书。
　　个人建议是DNS提供商解析那里添加CNAME记录+Nginx正则匹配转发。

　　以下是Nginx正则判断跳转的一些参考，可以*.a.com和*.a.a.com分离转发到服务器本地frps对应端口。
-----------------------------------------------------------------------------------------
location / {
        proxy_ssl_server_name    on;
        #$remote_addr;$clientRealip;
        proxy_set_header X-Real-IP    $clientRealip;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto    $scheme;
        proxy_set_header    Host $host;
        resolver 127.0.0.1;    #内网穿透域名解析

        root   html;
        index  index.html index.htm;
    
            if ( $host ~ (abc|ed|openwrt).demo.com ) {        
                proxy_pass    http://127.0.0.1:7000;
            }

            if ( $host = qwe.demo.com ) {
                proxy_pass    https://$host:8000;
            } 
            
            if ( $host ~ (?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z].https.demo.com ) {
                proxy_pass    https://$host:8000;
            }
        
            if ( $host ~ (?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z].http.demo.com ) {
                proxy_pass http://127.0.0.1:7000;
            }     

        
        }
        
#-------------------------------------
#        https内网穿透额外事项

#        1.安装dnsmasq
#        yum -y install dnsmasq

#        2.编辑dnsmasq.conf
#        vim /etc/dnsmasq.conf

#        添加内容：
#        address=/.demo.com/127.0.0.1
#        address=/.https.demo.com/127.0.0.1

#        3.重启dnsmasq服务
#        systemctl restart dnsmasq

#        4.dnsmasq开机自启
#        systemctl enable dnsmasq
#-------------------------------------

**Comment by fatedier** [comment]
下个版本支持。
