### ISSUE TITLE
If client side IP will changes every few hours due to unstable internet connection, will server can't recognize client anymore?

### ISSUE THREAD

**Issue by jerrychong25** [fatedier/frp#1133]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.24.1

**What operating system and processor architecture are you using (`go env`)?**
Raspbian OS (Raspberry Pi) ARM architecture

**Configures you used:**
*Client side*
[common]
server_addr = XXX.XXX.XXX.XXX
server_port = 7000
admin_addr = 127.0.0.1
admin_port = 7400
token=111111

[test20000]
type = tcp
local_ip = 127.0.0.1
local_port = 20000
remote_port = 20000

*Server side*
[common]
bind_addr = 0.0.0.0
bind_port = 7000
vhost_http_port = 8080
dashboard_user = admin
dashboard_pwd  = 111111
dashboard_port = 7500
allow_ports = 20000
token = 111111

**Steps to reproduce the issue:**
1. Client side (Raspberry Pi) disconnect from LAN cable
2. Wait for 30 seconds
3. Reconnects LAN cable to Raspberry Pi
4. Raspberry Pi should connect to server again

**Describe the results you received:**
So far I only tested under stable connection on client side, so no connection issue with server side so far. As I don't the environment of unstable internet connection to test this scenario.

**Describe the results you expected:**
To confirm on the server side behavior when client side IP changes every few hours due to unstable internet connection, will server can't recognize client anymore?

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Can you point out what caused this issue (optional)**
N/A

**Comment by fatedier** [comment]
Just test, not a issue.

**Comment by jerrychong25** [comment]
@fatedier,

Tested frp library with very unstable internet condition.

**Conclusion: frp client able to connect frp server despite very unstable internet condition.**

Below are time log for our frp client with very unstable internet condition:

1) 16 March 2019 
```
01:51 internet down
02:31 connect frp server back successfully
08:53 internet down
08:59 connect frp server back successfully
```

2) 17 March 2019
```
00:31 internet down
00:33 connect frp server back successfully
01:40 internet down
01:41 connect frp server back successfully
05:25 internet down
05:30 connect frp server back successfully
16:11 internet down
16:13 connect frp server back successfully
```

3) 18 March 2019
```
02:12 internet down
02:12 connect frp server back successfully
```

Thanks for great and useful frp library.
