### ISSUE TITLE
custom_domains无法使用中文域名，但是英文域名可以？

### ISSUE THREAD

**Issue by devarZeng** [fatedier/frp#1135]
如图所示，三个域名，只有中文的无法访问，希望尽快支持一下中文域名

![图片](https://user-images.githubusercontent.com/20607991/54332820-eb49e400-465a-11e9-94df-10c568abe978.png)

**Comment by mybove** [comment]
中文域名需要转换过才能用吧？

**Comment by mybove** [comment]
中文域名转换比如：
我爱你.中国
应该转换成：
xn--6qq986b3xl.xn--fiqs8s

**Comment by fatedier** [comment]
@devarZeng 请按照上面同学说的，自行搜索相关的知识来解决这个问题。
