### ISSUE TITLE
frpc客户端在无网络情况下的重连机制

### ISSUE THREAD

**Issue by vanshu** [fatedier/frp#1136]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.25

**What operating system and processor architecture are you using (`go env`)?**
nexus5x arm64-v7

**Configures you used:**
```shell
[common]
token = 12345678
server_addr = x.x.x.x
server_port = 7000
log_file = ./frpc.log
log_level = info
log_max_days = 3
admin_addr = 127.0.0.1
admin_port = 7400
admin_user = admin
admin_pwd = admin

login_fail_exit = false

```

**Steps to reproduce the issue:**
开启网络的情况下frpc客户端一直可以正常上线，偶尔断线会自动重连，因为有重试机制，貌似是20秒重连一次，如果一直无法连上网络，一直connection time out，frpc客户端会一直重连下去吗？还是会再重试多少次后失败会自动退出frpc服务？

**Comment by fatedier** [comment]
一直间隔重连。
