### ISSUE TITLE
无法自动连接

### ISSUE THREAD

**Issue by caoailin** [fatedier/frp#114]
服务端好像自动挂了，再启动后，客户端没有自动连接上。

**Comment by fatedier** [comment]
需要问题描述的更详细一些，比如一些系统环境，版本信息，日志信息等。

**Comment by caoailin** [comment]
服务端frps 版本0.8.1
服务器系统 centos 6
服务端日志没有显示，只显示重启后的成功日志，没看到客户端有连接上来
客户端 路由器系统padavan，版本号和日志现在没法看，晚点回家看下。

**Comment by wxyzh** [comment]
@fatedier 应该是没有网络的时候，客户端会自动退出，没有重连机制
