### ISSUE TITLE
服务器端添加客户端的连接端口

### ISSUE THREAD

**Issue by AaronLeong** [fatedier/frp#1142]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
无

**What operating system and processor architecture are you using (`go env`)?**

无
**Configures you used:**
无

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
无

**Describe the results you expected:**
需求场景： 我在客户端新开一个服务（端口随机），希望在服务器端添加客户端的连接端口。
目前是：需要重新配置frpc的端口然后重启服务，感觉有点麻烦，而且客户端重启报错的话其他服务也用不了了

解决方案：客户端（client）定义一个端口（manager port）和服务器（server）连接用于管理服务，当需要增加映射端口（target port）时，选择通过（manager port）发送事件信息到客户端（client）添加一条映射，映射信息保存在一个管理池（pool）中，当需要删除端口时去掉

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/README_zh.md#admin-ui
