### ISSUE TITLE
【新功能建议】客户端Web页面

### ISSUE THREAD

**Issue by xxzj990** [fatedier/frp#1144]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
All

**What operating system and processor architecture are you using (`go env`)?**
All

**Configures you used:**
All

**Steps to reproduce the issue:**
配置客户端端口映射

**Describe the results you received:**
目前只有命令行修改配置文件，然后重新加载配置

**Describe the results you expected:**
希望可以直接在web配置，并生效

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by xxzj990** [comment]
查了下0.24.0以后已经有这个功能了，现在去试试

**Comment by almas1992** [comment]
要是客户端web页面能查看请求信息，能重播请求就更好了
