### ISSUE TITLE
frps 是否会增加类似 frpc 的 reload 功能

### ISSUE THREAD

**Issue by funnypro** [fatedier/frp#1145]
如题  
有这个功能的话在调整 frps 配置后应该更加方便

**Comment by fatedier** [comment]
frpc 的 common 中的配置也不能 reload，frps 只有 common 配置，这些配置涉及到一些初始化的资源，不太容易动态变更，例如绑定端口之类，所以不会有相关的 reload 功能。

**Comment by funnypro** [comment]
> frpc 的 common 中的配置也不能 reload，frps 只有 common 配置，这些配置涉及到一些初始化的资源，不太容易动态变更，例如绑定端口之类，所以不会有相关的 reload 功能。

所以在近期是不会存在 reload 相关实现，是吗？

**Comment by fatedier** [comment]
不在规划中。

**Comment by funnypro** [comment]
> 不在规划中。

那未来会有吗？

**Comment by a-wing** [comment]
frps reload 感觉意义不大， reload 主要的功能是保持端口连接（配置端口都变了 x），你需要的大概是 `restart`

**Comment by funnypro** [comment]
> frps reload 感觉意义不大， reload 主要的功能是保持端口连接（配置端口都变了 x），你需要的大概是 `restart`

如果只是加端口呢？？

**Comment by fatedier** [comment]
增加复杂度带来的收益不是那么大，所以目前不考虑。
