### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by a-wing** [fatedier/frp#1146]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.25.1

**What operating system and processor architecture are you using (`go env`)?**
amd64

```
$ go version
go version go1.12.1 linux/amd64

$ export GOPATH=`pwd`"/build"

$ make all  
go fmt ./...
go: finding github.com/fatedier/kcp-go v0.0.0-20171023144637-cd167d2f15f4
go: github.com/fatedier/kcp-go@v0.0.0-20171023144637-cd167d2f15f4: unknown revision cd167d2f15f4
go: error loading module requirements
make: *** [Makefile:18: fmt] Error 1
```

**Comment by fatedier** [comment]
这个 repo 的 commit log 有改动，可以使用 go build -mod=vendor 来编译，依赖包都在 vendor 目录下。
下个版本会同步这一修改。
