### ISSUE TITLE
readme request : add docker img  configuration session

### ISSUE THREAD

**Issue by cwt0490** [fatedier/frp#1148]
I am using a synology nas w/ docker. I want to use frp in docker. I downloaded frp image but had no idea how to configure it like it is describe in README page. I would like to specify different ports and use privilige_togen.
Can anyone help me?

**Comment by Melody999** [comment]
Synology needs to get root first.

**Comment by snowdream** [comment]
https://github.com/fatedier/frp/pull/1291   it is a pull request about docker frp.
