### ISSUE TITLE
connect: no route to host

### ISSUE THREAD

**Issue by snowdream** [fatedier/frp#1149]
使用的是 frp_0.25.1版本， 服务器和客户端均在64位Linux系统中运行
服务器端启动了服务后，在客户端中启动服务时，报出
[root@snowdream frp_0.25.1_linux_amd64]# ./frpc -c frpc.ini 
dial tcp 119.90.100.53:2048: connect: no route to host

从客户端可以ping通服务端：
[root@snowdream frp_0.25.1_linux_amd64]# ping 119.90.100.53
PING 119.90.100.53 (119.90.100.53) 56(84) bytes of data.
64 bytes from 119.90.100.53: icmp_seq=2 ttl=49 time=224 ms
64 bytes from 119.90.100.53: icmp_seq=3 ttl=49 time=232 ms
64 bytes from 119.90.100.53: icmp_seq=5 ttl=49 time=226 ms
64 bytes from 119.90.100.53: icmp_seq=6 ttl=49 time=254 ms
64 bytes from 119.90.100.53: icmp_seq=7 ttl=49 time=224 ms
64 bytes from 119.90.100.53: icmp_seq=8 ttl=49 time=228 ms
64 bytes from 119.90.100.53: icmp_seq=10 ttl=49 time=227 ms

这个是服务端的ifconfig:
[root@localhost bin]# ifconfig
eth0      Link encap:Ethernet  HWaddr 00:15:5D:01:84:56  
          inet addr:10.199.2.4  Bcast:10.199.2.255  Mask:255.255.255.0
          inet6 addr: fe80::215:5dff:fe01:8456/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1344701 errors:0 dropped:0 overruns:0 frame:0
          TX packets:15290 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:177510406 (169.2 MiB)  TX bytes:3182471 (3.0 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:100 (100.0 b)  TX bytes:100 (100.0 b)

这个是frps启动成功的日志：

[root@localhost bin]# cat frps.log
2019/03/21 22:41:27 [I] [service.go:136] frps tcp listen on 0.0.0.0:2048
2019/03/21 22:41:27 [I] [service.go:145] frps kcp listen on udp 0.0.0.0:2048
2019/03/21 22:41:27 [I] [service.go:178] http service listen on 0.0.0.0:8080
2019/03/21 22:41:27 [I] [service.go:199] https service listen on 0.0.0.0:8443
2019/03/21 22:41:27 [I] [service.go:229] Dashboard listen on 0.0.0.0:6443
2019/03/21 22:41:27 [I] [root.go:204] Start frps success

**Comment by fatedier** [comment]
网络问题请先自行排查解决。

**Comment by hust-kevin** [comment]
@snowdream 请问你解决这个问题了嘛？

**Comment by snowdream** [comment]
> @snowdream 请问你解决这个问题了嘛？

网络不稳定造成的，自行排查。
