### ISSUE TITLE
高并发,内存泄漏的疑问

### ISSUE THREAD

**Issue by lu4kyd0y** [fatedier/frp#115]
这个反向代理支持高并发不 是否有内存泄漏。不考虑带宽的情况下 frp反向代理能否稳定承载10W次每秒请求的短链接 代理池和连接池 是否能真正起到作用捏？在线等大神回复，偶没怎么接触go 不知道并发怎么样

**Comment by fatedier** [comment]
1. 目前并没有针对高并发连接进行优化，不推荐用于并发量较高的生产环境，建议个人测试使用。
2. 目前的连接池主要是为了缩短连接建立需要通过 frps 中转的消耗。
3. 内存泄漏可自行测试，有问题再提出，会优先解决。

**Comment by lu4kyd0y** [comment]
多谢回答~我测试看看吧0 0 嘿嘿

**Comment by yi-ge** [comment]
高并发可以尝试使用ss，目前来看frps可优化空间很大。

**Comment by lu4kyd0y** [comment]
ss=Shadowsocks?
经过压力测试 连通率100%掉线奔溃了0% 不清楚大神是怎样维护链接的,建议可以指定连接池的时间 超时就断开所有链接 释放资源 
测试如下还是比较OK的 
![image](http://i2.buimg.com/1949/805120f7b34670bd.png)

**Comment by yi-ge** [comment]
我看过代码，确实写得很不错。你这测试方式不太科学哟！！

**Comment by lu4kyd0y** [comment]
嘎嘎 就简单的测试迸发了 - -嘎嘎 已star 跟进项目 要去恶补go语言去了 - -
