### ISSUE TITLE
使用DDNS无二级域名如何配置多个HTTP的WEB端口？ How to configure multiple HTTP WEB ports using DDNS no secondary domain?

### ISSUE THREAD

**Issue by ZhanRu** [fatedier/frp#1151]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frp_0.25.1

**What operating system and processor architecture are you using (`go env`)?**
CentOS 7.6 x64

**Configures you used:**
frps.ini
[common]
bind_port = 31200
bind_udp_port = 31201
vhost_http_port = 31280
vhost_https_port = 31281
allow_ports = 31200-31299
dashboard_port = 31275
dashboard_user = xxxxxx
dashboard_pwd = xxxx
token = xxxx

frpc.ini
[common]
server_addr = xxxx.asuscomm.com
server_port = 31100
token = xxxx
[lkj-nas-ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 31122
[lkj-nas-web]
type = http
local_port = 5000
custom_domains = xxxx.asuscomm.com
[two-web]
type = http
local_port = 5000
remote_port = 31188
custom_domains = xxxx.asuscomm.com

**Steps to reproduce the issue:**
1.vi /etc/rc.d/rc.local
2.nohup ./usr/frp/frp_0.25.1_linux_amd64/frpc -c ./usr/frp/frp_0.25.1_linux_amd64/frpc.ini > /dev/null 2>&1 &
3.chmod +x /etc/rc.d/rc.local
4.reboot

**Describe the results you received:**
我可以用xxxx.asuscomm.com:31280来访问[lkj-nas-web]（I can access [lkj-nas-web] with xxxx.asuscomm.com:31280）；
但是我不可以用xxxx.asuscomm.com:31188来访问[two-web]（But I can't access [two-web] with xxxx.asuscomm.com:31188）；
我是用的DDNS绑定我的IP，我没有静态IP，我没有办法使用二级域名的方式设置多个WEB（I use DDNS to bind my IP, I do not have static IP, I can not use the secondary domain name way to set up multiple WEB）；

**Describe the results you expected:**
我希望我可以通过不同的端口访问我不同的WEB页面，至少多于2个（I wish I could access my different WEB pages on different ports, at least two）；

**Additional information you deem important (e.g. issue happens only occasionally):**
null

**Can you point out what caused this issue (optional)**
null

**Comment by ZhanRu** [comment]
类似的issues没能解决我的问题：https://github.com/fatedier/frp/issues/914
Similar issues have not been able to solve my problem: https://github.com/fatedier/frp/issues/914

**Comment by Braver-Exun** [comment]
你可以在服务器上同时配置frps和frpc来实现代理，我在CSDN上有个类似的方法:
https://blog.csdn.net/ADimple/article/details/88385831

**Comment by ZhanRu** [comment]
> 你可以在服务器上同时配置frps和frpc来实现代理，我在CSDN上有个类似的方法:
> https://blog.csdn.net/ADimple/article/details/88385831

我没能理解这个文章.....我看了好几遍

**Comment by Braver-Exun** [comment]
我在文章上的方法是使用frp的subdmain来代理的，用它可以自定制二级域名，在这官方文档上很明了，当然在使用subdmain之前需要确保subdmain_host绑定的服务域名设置了泛解析，且依赖于vhost_http_port绑定的服务端口。这样你已经可以为其他客户端代理http了。下面是进阶：若你不想要输入端口号来访问被代理的web服务，请把vhost_http_port绑定为80，这会导致服务器的其他程序无法使用80端口，因此你可在服务器再多上添加一个客户端来代理自己，解决端口冲突。在此为您尚未解决感到同情，并且在我的知识范围内，很乐意为您效劳。

**Comment by ZhanRu** [comment]
> 我在文章上的方法是使用frp的subdmain来代理的，用它可以自定制二级域名，在这官方文档上很明了，当然在使用subdmain之前需要确保subdmain_host绑定的服务域名设置了泛解析，且依赖于vhost_http_port绑定的服务端口。这样你已经可以为其他客户端代理http了。下面是进阶：若你不想要输入端口号来访问被代理的web服务，请把vhost_http_port绑定为80，这会导致服务器的其他程序无法使用80端口，因此你可在服务器再多上添加一个客户端来代理自己，解决端口冲突。在此为您尚未解决感到同情，并且在我的知识范围内，很乐意为您效劳。

非常感谢您的回复。
我是个人宽带拥有公网IP，但是没有80端口，所以用其他端口的。由于我不是固定IP，用了华硕的DDNS服务，所以我不拥有自己的二级域名。我自己的域名也无法指向我的公网IP，因为它不是固定的。

**Comment by Braver-Exun** [comment]
我为自己的莽撞感到抱歉，很明显我之前没能完全考虑到您的处境，对此深感愧疚。

**Comment by ZhanRu** [comment]
> 我为自己的莽撞感到抱歉，很明显我之前没能完全考虑到您的处境，对此深感愧疚。

(lll￢ω￢)........

**Comment by Braver-Exun** [comment]
233~

**Comment by ZhanRu** [comment]
已经解决：https://github.com/fatedier/frp/issues/1189
Has been resolved ：https://github.com/fatedier/frp/issues/1189
