### ISSUE TITLE
Can't run in winxp x86 

### ISSUE THREAD

**Issue by mrshelly** [fatedier/frp#1152]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.25.0

**What operating system and processor architecture are you using (`go env`)?**
winxp x86

**Configures you used:**
default frpc.ini

**Steps to reproduce the issue:**
1. run in cmd line
2.
3.

**Describe the results you received:**

D:\Program Files\FRP>frpc -c frpc.ini
panic: Failed to find GetFileInformationByHandleEx procedure in kernel32.dll: Th
e specified procedure could not be found.

goroutine 1 [running]:
syscall.(*LazyProc).mustFind(0x1183f9c0)
        /home/wcl/.gvm/gos/go1.12/src/syscall/dll_windows.go:287 +0x42
syscall.(*LazyProc).Addr(0x1183f9c0, 0xc53300)
        /home/wcl/.gvm/gos/go1.12/src/syscall/dll_windows.go:294 +0x21
internal/syscall/windows.GetFileInformationByHandleEx(0x77c, 0x9, 0x11869dc0, 0x
8, 0x3, 0x1181c048)
        /home/wcl/.gvm/gos/go1.12/src/internal/syscall/windows/zsyscall_windows.
go:353 +0x27
os.newFileStatFromGetFileInformationByHandle(0x1184c090, 0x8, 0x77c, 0x0, 0x1184
c090, 0x8)
        /home/wcl/.gvm/gos/go1.12/src/os/types_windows.go:52 +0x135
os.(*File).Stat(0x11806270, 0x8e2174, 0x11806270, 0x0, 0x11806270)
        /home/wcl/.gvm/gos/go1.12/src/os/stat_windows.go:55 +0x133
io/ioutil.ReadFile(0x1184c090, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/wcl/.gvm/gos/go1.12/src/io/ioutil/ioutil.go:62 +0xac
github.com/fatedier/frp/models/config.GetRenderedConfFromFile(0x1184c090, 0x8, 0
x3, 0x3, 0x3, 0x2)
        /home/wcl/go_projects/src/github.com/fatedier/frp/models/config/value.go
:56 +0x2d
github.com/fatedier/frp/cmd/frpc/sub.runClient(0x1184c090, 0x8, 0x118d4600, 0x81
92c5)
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:1
73 +0x2d
github.com/fatedier/frp/cmd/frpc/sub.glob..func4(0xc4f660, 0x118041c0, 0x0, 0x2,
 0x0, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:9
2 +0x40
github.com/fatedier/frp/vendor/github.com/spf13/cobra.(*Command).execute(0xc4f66
0, 0x1183fa48, 0x2, 0x3, 0xc4f660, 0x1183fa48)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/spf1
3/cobra/command.go:762 +0x337
github.com/fatedier/frp/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4f6
60, 0x0, 0xc4fca0, 0x755764)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/spf1
3/cobra/command.go:852 +0x225
github.com/fatedier/frp/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/spf1
3/cobra/command.go:800
github.com/fatedier/frp/cmd/frpc/sub.Execute()
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:1
02 +0x24
main.main()
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frpc/main.go:27 +0
x37

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
Duplication of #1131 .

不再支持 windows XP 系统。
