### ISSUE TITLE
能否在Makefile.cross-compiles中提供一个将frp编译成Windows系统的.dll文件的命令？

### ISSUE THREAD

**Issue by hank1yh** [fatedier/frp#1158]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.25.1

**What operating system and processor architecture are you using (`go env`)?**
win7 x64

**Configures you used:**
N/A

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**
自己试了将frp编译成dll文件，但是调用生成的dll文件时总是调不起来，请问怎样正确的将frp生成dll文件呢？

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
不清楚，可以自行搜索相关的资料学习，目前不提供这一能力。
