### ISSUE TITLE
tls crash on reconnection

### ISSUE THREAD

**Issue by steom** [fatedier/frp#1159]
# frps.ini
[common]
bind_port = 7000

# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000
login_fail_exit = false
tls_enable = true

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

frpc.exe crash on failed reconnection with:

"panic: runtime error: invalid memory address or nil pointer dereference"

with no tls or tls_enable = false 
reconnections is always fine

frp_0.25.2_windows_amd64

**Comment by fatedier** [comment]
请按照格式贴完整的日志。

**Comment by steom** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0x7d8d4b]

goroutine 1 [running]:
github.com/fatedier/frp/utils/net.WrapTLSClientConn(0x0, 0x0, 0xc00004a780, 0x0,
 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/utils/net/tls.go:29 +0
x4b
github.com/fatedier/frp/utils/net.ConnectServerByProxyWithTLS(0x0, 0x0, 0xc00006
283b, 0x3, 0xc000060e80, 0x13, 0xc00004a780, 0x0, 0x787a00be, 0x0, ...)
        /home/wcl/go_projects/src/github.com/fatedier/frp/utils/net/conn.go:218
+0xe2
github.com/fatedier/frp/client.(*Service).login(0xc0000e0a10, 0x0, 0x0, 0x0, 0x0
, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/service.go:161
+0x18f
github.com/fatedier/frp/client.(*Service).Run(0xc0000e0a10, 0xc000077ec0, 0xc000
0e0a10)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/service.go:80 +
0x5c
github.com/fatedier/frp/cmd/frpc/sub.startService(0xc000077e90, 0xc000077ec0, 0x
c000048700, 0xf3)
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:2
19 +0xf8
github.com/fatedier/frp/cmd/frpc/sub.runClient(0x920688, 0xa, 0xc0000dac00, 0x91
eed0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:1
89 +0x13e
github.com/fatedier/frp/cmd/frpc/sub.glob..func4(0xdd2ce0, 0xdf45b8, 0x0, 0x0, 0
x0, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:9
2 +0x51
github.com/fatedier/frp/vendor/github.com/spf13/cobra.(*Command).execute(0xdd2ce
0, 0xc00004e260, 0x0, 0x0, 0xdd2ce0, 0xc00004e260)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/spf1
3/cobra/command.go:762 +0x46c
github.com/fatedier/frp/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xdd2c
e0, 0x0, 0x0, 0x82456b)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/spf1
3/cobra/command.go:852 +0x2f3
github.com/fatedier/frp/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/spf1
3/cobra/command.go:800
github.com/fatedier/frp/cmd/frpc/sub.Execute()
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:1
02 +0x35
main.main()
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frpc/main.go:27 +0
x49
