### ISSUE TITLE
frp穿透不成功

### ISSUE THREAD

**Issue by wangshengfeng** [fatedier/frp#1162]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?frpc

**What operating system and processor architecture are you using (`go env`)?Linux

**Configures you used:  0.24.1

*Steps to reproduce the issue
给公司所有路由器配置了frp，远程服务器用的谷歌云

**Describe the results you received:**
在线的都显示online，但目前只有一台能正常穿透，其他都穿透失败

**Describe the results you expected:**
希望解答其他机器穿透失败是因为8081端口是被能穿透的那台占用，还是和把版本更新有关

**Additional information you deem important (e.g. issue happens only occasionally):**
用的都是8081端口，vps安装的时0.24.1版本，路由器有的是0.24.1，有的是0.25.1

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

请按照 issue 提供能够帮助解决问题的详细内容。
