### ISSUE TITLE
功能建议：增加日志时间戳关闭功能

### ISSUE THREAD

**Issue by funnypro** [fatedier/frp#1163]
似乎又问了一次这个问题  
这个问题一直在深深困扰着我  
也许是我太菜了，一直不知道怎么裁掉时间戳那部分
大概是因为我总是想把frp日志放进/dev/log里吧

希望能加上这个开关什么的

**Comment by fatedier** [comment]
frp 本身不会做这样的事情，有需要的话就自己尝试解决，你不可能要求所有的程序都按照你的需要输出日志，但是你的日志你可以自己做主，awk, sed, 或者 python 脚本，没有什么做不到的。

**Comment by funnypro** [comment]
> frp 本身不会做这样的事情，有需要的话就自己尝试解决，你不可能要求所有的程序都按照你的需要输出日志，但是你的日志你可以自己做主，awk, sed, 或者 python 脚本，没有什么做不到的。
那我再看看怎么搞吧
