### ISSUE TITLE
同一个路由器下多个机器分别映射不同的子域名不生效，只有第一个注册上的生效  

### ISSUE THREAD

**Issue by lingdu0001** [fatedier/frp#1165]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

**What version of frp are you using (./frpc -v or ./frps -v)?**
frp 2.5.3

**What operating system and processor architecture are you using (`go env`)?**
centos 7.4

**Configures you used:**
frps的配置:

[common]
bind_addr = 0.0.0.0
bind_port = 2000
bind_udp_port = 2001
kcp_bind_port = 2004
vhost_http_port = 2002
dashboard_addr = 0.0.0.0
dashboard_port = 2003
dashboard_user = admin
dashboard_passwd = admin
log_file = ./frps.log
log_level = info
log_max_days = 3
token = 2017
# heartbeat_timeout = 90
max_pool_count = 5
max_ports_per_client = 0
authentication_timeout = 90
subdomain_host = utchu.com.cn
tcp_mux = true

**Steps to reproduce the issue:**
已经泛域名解析*.utchu.com.cn 到frps的服务器对应的IP上

1. 机器A  执行  ./frpc http -s utchu.com.cn:2000  -n 15900001 --sd 15900001 -i 127.0.0.1 -l 80 -t 2017  ，可以通过 15900001.utchu.com.cn:2002 访问到web页面，穿透成功。
2. 机器B执行 ./frpc http -s utchu.com.cn:2000  -n 15900002 --sd 15900002 -i 127.0.0.1 -l 80 -t 2017    报错  [W] [control.go:142] [15900002 ] start error: router config conflict
3. 将机器A的frpc关闭 ，先在机器b执行上述命令， 1590002穿透成功， 在机器A执行命令  A也会报错 [W] [control.go:142] [15900001 ] start error: router config conflict

**Describe the results you expected:**
期望机器A和B都能穿透成功

**Comment by ssqf** [comment]
应该是你的frpc配置错了，我也遇到这样的问题，看一下服务端和客户端日子就能发现问题
![image](https://user-images.githubusercontent.com/13485967/55123545-024e0300-513e-11e9-98d9-8aed40087890.png)

**Comment by lingdu0001** [comment]
./frpc http -s utchu.com.cn:2000 -n 15900002 --sd 15900002 -i 127.0.0.1 -l 80 -t 2017

-n 那个命令就是指定这个名字  --sd 是指定子域名   我这两个都指定了不一样的啊。。

**Comment by fatedier** [comment]
这个是一个 bug，使用命令行方式启动会有这个问题，通过配置文件应该没问题，下个版本修复。

**Comment by lingdu0001** [comment]
> 这个是一个 bug，使用命令行方式启动会有这个问题，通过配置文件应该没问题，下个版本修复。

是的。配置文件没问题的

**Comment by fatedier** [comment]
v0.26.0 已 fix。

**Comment by yuanzhiroc** [comment]
我用配置文件启动也碰到了这个问题。。
