### ISSUE TITLE
25.3 kcp >> login to server failed: i/o deadline reached

### ISSUE THREAD

**Issue by status301** [fatedier/frp#1168]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
D:\>frpc -v
0.25.3
[root@HK home]# ./frps -v
0.25.3

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**
`
[root@HK home]# cat ~/frps.ini 
[common]
bind_addr = 0.0.0.0
bind_port = 80
bind_udp_port = 81
kcp_bind_port = 80
vhost_http_port = 80
vhost_https_port = 443
vhost_http_timeout = 60
token = HK-Frp-Ali

#dashboard_addr = 0.0.0.0
dashboard_port = 65534
dashboard_user = HK-Frp-Ali
dashboard_pwd = HK-Frp-Ali
heartbeat_timeout = 60

log_file = /var/log/frps.log
# trace, debug, info, warn, error
log_level = trace
log_max_days = 1

#allow_ports = 2000-3000,3001,3003,4000-50000
#max_pool_count = 5
max_ports_per_client = 0
tcp_mux = true
`

**Steps to reproduce the issue:**
1.D:\>frpc tcp -l 3389 -p kcp -n winh  -r 3389 -s service_ip:80 -t HK-Frp-Ali
2019/03/29 22:41:59 [W] [service.go:82] login to server failed: i/o deadline reached

2.D:\>frpc tcp -l 3389  -n winh  -r 3389 -s service_ip:80 -t HK-Frp-Ali
2019/03/29 22:47:37 [I] [service.go:221] login to server success, get run id [30***4c086], server udp port [81]
2019/03/29 22:47:37 [I] [proxy_manager.go:137] [3020d119e2c4c086] proxy added: [winh]
2019/03/29 22:47:37 [I] [control.go:144] [winh] start proxy success

3.

**Describe the results you received:**
2019/03/29 22:41:59 [W] [service.go:82] login to server failed: i/o deadline reached

**Describe the results you expected:**
25.1使用kcp没有问题，没试过25.2

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by status301** [comment]
**服务器执行结果**
[root@HK packages]# /home/frpc tcp -l 3389 -p tcp -n winh -r 33890 -s 127.0.0.1:80 -t HK-Frp-Ali
2019/03/29 23:32:10 [I] [service.go:221] login to server success, get run id [9a2851849516a566], server udp port [81]
2019/03/29 23:32:10 [I] [proxy_manager.go:137] [9a2851849516a566] proxy added: [winh]
2019/03/29 23:32:10 [I] [control.go:144] [winh] start proxy success
^C
[root@HK packages]# /home/frpc tcp -l 3389 -p kcp -n winh -r 33890 -s 127.0.0.1:80 -t HK-Frp-Ali
2019/03/29 23:32:23 [W] [service.go:82] login to server failed: i/o deadline reached
^Cpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7d4fd2]

goroutine 7 [running]:
github.com/fatedier/frp/client.(*Control).Close(0x0, 0x758c01, 0xc000020101)
	/root/go/src/github.com/fatedier/frp/client/control.go:149 +0x22
github.com/fatedier/frp/client.(*Service).Close(0xc0000e2f50)
	/root/go/src/github.com/fatedier/frp/client/service.go:236 +0x37
github.com/fatedier/frp/cmd/frpc/sub.handleSignal(0xc0000e2f50)
	/root/go/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:111 +0xc4
created by github.com/fatedier/frp/cmd/frpc/sub.startService
	/root/go/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:216 +0x186
[root@HK packages]# 

**服务器使用配置文件结果**
[root@HK ~]# cat test.ini 
[common]
server_addr = 127.0.0.1
server_port = 80
protocol = kcp
token = HK-Frp-Ali

[test]
type = tcp
local_ip = baidu.com
local_port = 80
remote_port = 0
[root@HK ~]# /home/frpc -c test.ini
2019/03/29 23:42:10 [W] [service.go:82] login to server failed: i/o deadline reached

**Comment by 779505388** [comment]
试一试安装bbr吧。
我之前tcp协议端口经常出问题，给服务端安装bbr之后基本上不出问题了

**Comment by status301** [comment]
@779505388 是使用KCP有问题，安装bbr可以解决这个问题吗

**Comment by 779505388** [comment]
不清楚，但我使用kcp经常突然断开连接，装了bbr情况就好多了。
我推测，你是不是在服务端装了类似ssr的软件，我的vps装上ssr后frpc就连接不了frps

**Comment by status301** [comment]
服务端我用docker起的v2，应该不会污染宿主环境的吧。
你用kcp可以连上吗？我没其他vps无法确认是不是环境问题。

**Comment by 779505388** [comment]
emmm，我想我大概知道问题了，关闭防火墙就行了。
我安装ssr的时候重启了vps，防火墙又开启了，关了防火墙之后就没有问题了。

**Comment by status301** [comment]
环境原因，重装service后kcp成功。。。
