### ISSUE TITLE
make file 的时候 

### ISSUE THREAD

**Issue by LamTech** [fatedier/frp#1171]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.25.3

mac os

1、在web里面分别npm install ，npm run build 生成dist文件。
2、在frp根目录make file，报错了。报错内容：
![image](https://user-images.githubusercontent.com/46949682/55372907-e67ba000-5535-11e9-94b9-2c22a52f29cd.png)

**Comment by fatedier** [comment]
需要安装 static 这个工具。

**Comment by fatedier** [comment]
后面修改成 make file 的时候检查是否有安装这个工具，没有的话自动安装。

**Comment by LamTech** [comment]
> 后面修改成 make file 的时候检查是否有安装这个工具，没有的话自动安装。
我发现个问题，是在安装了statik工具并且成功 make file之后，就是生成frps和frpc之后运行，并没有按照dist里面的来展示。我的步骤是这样的：
1、我把/web/frps/index.html 的title改成了 testFrp ,然后 npm run build 生成dist文件。
2、到根目录，make file，成功，并且替换了/assets/frps/static 里面的文件，确认里面的index.html 标题已经变为 testFrp。

3、然后我到根目录，make ，再交叉编译，运行frps。访问 dashboard ，标题仍然是 frp，并没有发生任何改变。

4、我到/assets/frps/statik/statik.go 文件去搜索 testFrp ,搜索结果为空。（因为我从git上直接拉取这个文件出来的时候是可以搜索到frp这个标题的，现在重新生成后，frp也搜索不到了）。所以我就怀疑 statik.go 这个文件生成可能有问题，或者这个文件根本就不是 ui 用到的。

5、我删掉了/assets/frps/statik/statik.go 这个文件，到根目录make ,再交叉编译，运行。dashboard 访问没有任何问题。所以我更加怀疑，更改 UI 不是这么一个套路。

目前主要的疑问就是：我不知道如何去更改这个frp 的 ui，还请多多指教，谢谢！

**Comment by LamTech** [comment]
> > 后面修改成 make file 的时候检查是否有安装这个工具，没有的话自动安装。
> 
> 我发现个问题，是在安装了statik工具并且成功 make file之后，就是生成frps和frpc之后运行，并没有按照dist里面的来展示。我的步骤是这样的：
> 1、我把/web/frps/index.html 的title改成了 testFrp ,然后 npm run build 生成dist文件。
> 2、到根目录，make file，成功，并且替换了/assets/frps/static 里面的文件，确认里面的index.html 标题已经变为 testFrp。
> 
> 3、然后我到根目录，make ，再交叉编译，运行frps。访问 dashboard ，标题仍然是 frp，并没有发生任何改变。
> 
> 4、我到/assets/frps/statik/statik.go 文件去搜索 testFrp ,搜索结果为空。（因为我从git上直接拉取这个文件出来的时候是可以搜索到frp这个标题的，现在重新生成后，frp也搜索不到了）。所以我就怀疑 statik.go 这个文件生成可能有问题，或者这个文件根本就不是 ui 用到的。
> 
> 5、我删掉了/assets/frps/statik/statik.go 这个文件，到根目录make ,再交叉编译，运行。dashboard 访问没有任何问题。所以我更加怀疑，更改 UI 不是这么一个套路。
> 
> 目前主要的疑问就是：我不知道如何去更改这个frp 的 ui，还请多多指教，谢谢！

懂了，还是得看源码，这里引用的是线上的。
