### ISSUE TITLE
内网穿透做微信公众号开发，如果使用「Http Basic Auth」，会被微信阻止弹框

### ISSUE THREAD

**Issue by rainjm** [fatedier/frp#1172]
**Describe the results you received:**
内网穿透做微信公众号开发，如果使用「Http Basic Auth」，会被微信阻止弹框

**Describe the results you expected:**
期望可以用页面的形式登陆；公众号需要80端口，为了安全，想使用「Http Basic Auth」的方式使用内网穿透，可以方便测试、开发。

> 或者有其他方案解决安全问题？希望有朋友分享一下。

**Comment by fatedier** [comment]
HTTP Basic Auth 是一种基础的身份验证方式，至于微信公众号的问题，和 frp 这个项目无关，你应该在其他地方寻求帮助，比如自己的网站上直接加上用户登录的功能，而不是借助于 HTTP Basic Auth。

**Comment by rainjm** [comment]
@fatedier 公众号主要是开放的，不会进来就设置登录。使用「HTTP Basic Auth 」主要是为了开发环境的源码安全，如果要加一个登陆功能做开发环境限制，会比较麻烦。
如果能把账号密码访问弹框形式，改为页面形式，做新项目或者其他公众号开发者也能方便很多。

我看看还有没有其他方案。

**Comment by rainjm** [comment]
我其实还用到nginx，nginx也支持「HTTP Basic Auth 」，看看能不能统一在nginx上设置页面式登录

**Comment by fatedier** [comment]
因为这个是一个和 frp 本身无关的事情，可以去微信公众号开发相关的论坛之类的地方看看。
