### ISSUE TITLE
尝试了去自己修改frp的UI，但是都不成功。

### ISSUE THREAD

**Issue by LamTech** [fatedier/frp#1173]
我用的版本是 0.25.3。
我的用的是macOS 10.13。
自己的项目在 $GOPATH/useFrp。
想要把dashboard和admin这些 UI 换成中文的。

于是我尝试去修改 /useFrp/cmd/frps/main.go。
里面的import原来是：
`import (
	"github.com/fatedier/golib/crypto"

	_ "github.com/fatedier/frp/assets/frps/statik"
)`

那么我就把下面那行改成：

 "useFrp/assets/frps/statik"

然后 make file，成功。
make 成功。
但是当我到bin目录，运行：
`./frps -c frps.ini`
之后报错了：

![image](https://user-images.githubusercontent.com/46949682/55446574-ca8a0400-55f2-11e9-8b7c-481f375455da.png)

感觉只差一个点化。真的希望能把这个突破一下，真的只想改一个 UI。还望高手指教，感激不尽！

**Comment by fatedier** [comment]
如果不熟悉代码的话，直接在 frps 的配置文件加上 `assets_dir = ./static` ，指定 web 资源的文件夹，然后把你修改后的 web 资源放到这个文件夹里就可以了。

**Comment by LamTech** [comment]
> assets_dir = ./static

谢谢你的解答，我这么尝试是可以的。但是在部署的时候，就需要把static资源 一起放进去了，不如直接一个frps来的简洁。

能否指导一下如何import的方法，把这个statik.go 用起来，挑你有时间的时候回复就行，谢谢！

**Comment by fatedier** [comment]
你之前的步骤没什么大问题，但是不要修改代码。

其他的暂时也看不来原因，你自己再摸索下。

**Comment by LamTech** [comment]
> 你之前的步骤没什么大问题，但是不要修改代码。
> 
> 其他的暂时也看不来原因，你自己再摸索下。

好的，谢谢！
