### ISSUE TITLE
windows server 2003 32位 启动panic

### ISSUE THREAD

**Issue by lweijin** [fatedier/frp#1174]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frp_0.25.3_windows_386

**What operating system and processor architecture are you using (`go env`)?**
windows server 2003 32

**Configures you used:**

**Steps to reproduce the issue:**
1.启动后panic

**Describe the results you received:**
frp_0.16.0_windows_386 这个版本是正常的,最新版本有问题

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

![image](https://user-images.githubusercontent.com/3378293/55461534-38502300-5627-11e9-8775-62569c669769.png)

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
新版本 Go 已经不再支持此系统，请使用旧版本或更新系统。
