### ISSUE TITLE
login to server failed

### ISSUE THREAD

**Issue by zhfnjust** [fatedier/frp#1175]
我使用相同的frpc.ini ，在我的PC 就能成功连接上frps， 但是当我把frpc 的arm版push 到手机，使用相同的frpc.ini，就会无法连接上frps，下面是报错:

[W] [service.go:82] login to server failed: dial tcp: lookup xx.xx.com on [::1]:53: read udp [::1]:37354->[::1]:53: read: connection refused

用的是 frp_0.25.3_linux_arm64 这个版本

**Comment by fatedier** [comment]
配置文件里自行设置 DNS

`dns_server = 8.8.8.8`
