### ISSUE TITLE
公司电脑启用客户端后能连上服务端，但每隔30秒就断开重连，也无法远程接入

### ISSUE THREAD

**Issue by wpok** [fatedier/frp#1178]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frp_0.25.3_windows_amd64

**What operating system and processor architecture are you using (`go env`)?**
Win10

**Configures you used:**
[common]
server_addr = x.x.x.x
server_port = 7000

[RDP-corp]
type = tcp
local_ip = 0.0.0.0
local_port = 3389
remote_port = 6000

**Steps to reproduce the issue:**
1. 客户端启动后，能正常连接上服务端，服务端的dashboard上也看到该客户端已经online
2. 看屏幕输出每隔30秒就会提示 control writer is closing，work connection closed, EOF，之后就会重新连接服务端成功，再哥30秒断开重连一直反复
3. 尝试使用RDP工具远程连接客户端所在机器，可以看到服务端输出提示有新连接进入，但客户端输出一直没有提示有连接进入，还是继续每隔30秒就断开重连
4. 同样一份客户端配置，在家里的电脑（WIN7）客户端启动后，手机使用4G和RDP工具是可以接入远程的

**Describe the results you received:**
这是客户端的输出内容：
2019/04/05 09:08:18 [I] [service.go:127] try to reconnect to server...
2019/04/05 09:08:18 [I] [service.go:221] login to server success, get run id [0fea65e65c19893c], server udp port [0]
2019/04/05 09:08:18 [I] [proxy_manager.go:137] [0fea65e65c19893c] proxy added: [RDP-corp]
2019/04/05 09:08:18 [I] [control.go:144] [RDP-corp] start proxy success
2019/04/05 09:08:48 [I] [control.go:224] control writer is closing
2019/04/05 09:08:48 [E] [control.go:127] work connection closed, EOF
2019/04/05 09:08:48 [I] [service.go:127] try to reconnect to server...
2019/04/05 09:08:48 [I] [service.go:221] login to server success, get run id [0fea65e65c19893c], server udp port [0]
2019/04/05 09:08:48 [I] [proxy_manager.go:137] [0fea65e65c19893c] proxy added: [RDP-corp]
2019/04/05 09:08:48 [I] [control.go:144] [RDP-corp] start proxy success
2019/04/05 09:09:18 [I] [control.go:224] control writer is closing
2019/04/05 09:09:18 [E] [control.go:127] work connection closed, EOF
2019/04/05 09:09:18 [I] [service.go:127] try to reconnect to server...
2019/04/05 09:09:18 [I] [service.go:221] login to server success, get run id [0fea65e65c19893c], server udp port [0]
2019/04/05 09:09:18 [I] [proxy_manager.go:137] [0fea65e65c19893c] proxy added: [RDP-corp]
2019/04/05 09:09:18 [I] [control.go:144] [RDP-corp] start proxy success
2019/04/05 09:09:48 [E] [control.go:127] work connection closed, EOF
2019/04/05 09:09:48 [I] [control.go:224] control writer is closing
2019/04/05 09:09:48 [I] [service.go:127] try to reconnect to server...
2019/04/05 09:09:48 [I] [service.go:221] login to server success, get run id [0fea65e65c19893c], server udp port [0]
2019/04/05 09:09:48 [I] [proxy_manager.go:137] [0fea65e65c19893c] proxy added: [RDP-corp]
2019/04/05 09:09:48 [I] [control.go:144] [RDP-corp] start proxy success
2019/04/05 09:10:18 [E] [control.go:127] work connection closed, EOF
2019/04/05 09:10:18 [I] [control.go:224] control writer is closing
2019/04/05 09:10:36 [I] [service.go:127] try to reconnect to server...
2019/04/05 09:10:36 [I] [service.go:221] login to server success, get run id [0fea65e65c19893c], server udp port [0]
2019/04/05 09:10:36 [I] [proxy_manager.go:137] [0fea65e65c19893c] proxy added: [RDP-corp]
2019/04/05 09:10:36 [I] [control.go:144] [RDP-corp] start proxy success

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
可以咨询公司的网络拦截策略。

**Comment by fatedier** [comment]
可以咨询公司的网络拦截策略。

**Comment by LamTech** [comment]
确实存在这个情况，很高频的。

**Comment by 92ewing** [comment]
我也碰到这个问题 远程桌面反复断开再反复连接

**Comment by phtwo** [comment]
我反馈一个相关，不类似的问题

同一个 client 有两个 tcp 的 `proxy` ，其中一个 `ph2_home.rdp` 是转发 window 的远程桌面 `3389` 的，在服务端一直打印下面的日志，但客户端除了偶然网络不好时的重连外，没有对应的日志。奇怪的是，另一个 tcp 的 proxy 不会。

这个蛮夸张的，今天的服务端日志一直有，从客户端连接上后一直输出。回看了最近十天的，也不是一直这样，有几天客户端连接上后没有这些输出的。

```
...
2019/04/21 07:07:09 [I] [proxy.go:82] [91861b77babf1fd7] [ph2_home.rdp] get a new work connection: [x.x.x.x:52151]
2019/04/21 07:11:17 [I] [proxy.go:82] [91861b77babf1fd7] [ph2_home.rdp] get a new work connection: [x.x.x.x:52151]
2019/04/21 07:11:17 [I] [proxy.go:82] [91861b77babf1fd7] [ph2_home.rdp] get a new work connection: [x.x.x.x:52151]
2019/04/21 07:12:56 [I] [proxy.go:82] [91861b77babf1fd7] [ph2_home.rdp] get a new work connection: [x.x.x.x:52151]
2019/04/21 07:12:56 [I] [proxy.go:82] [91861b77babf1fd7] [ph2_home.rdp] get a new work connection: [x.x.x.x:52151]
...
```

**Comment by yuanxy** [comment]
我也遇到这样的情况

**Comment by reece15** [comment]
我也遇到这样的情况

**Comment by LIUJINGQING** [comment]
我也是这样的情况，最后发现是我的主机有多个网口。网口启动多个后就会发生这样的情况。之启用一个网口就没有问题。不知道对你们有没有帮助。
目前还不知道有没有什么办法在启用多个网口的情况下解决这个问题。希望有大神指点。
