### ISSUE TITLE
Windows Server 2019客户端设置开机自启动后不能访问

### ISSUE THREAD

**Issue by so1999** [fatedier/frp#1179]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.25.3
frpc
**What operating system and processor architecture are you using (`go env`)?**
Windows Server 2019 

**Configures you used:**
[common]
server_addr = xxxxxxx
server_port = 7000
token = xxxxxxx

admin_addr = 127.0.0.1
admin_port = 7400
admin_user = admin
admin_pwd = admin

log_file =./frpc.log

[qb]
type = http
local_ip = 127.0.0.1
local_port = 9999
use_encryption = false
use_compression = true
subdomain = ab

**Steps to reproduce the issue:**
1.开机后可以启动，但是不能访问，必须登录进系统以后才能访问

2019/04/05 12:24:35 [I] [service.go:221] login to server success, get run id [3cf887b619f0ead2], server udp port [0]
2019/04/05 12:24:35 [I] [proxy_manager.go:137] [3cf887b619f0ead2] proxy added: [qb]
2019/04/05 12:24:35 [I] [service.go:109] admin server listen on 127.0.0.1:7400
2019/04/05 12:24:35 [I] [control.go:144] [qb] start proxy success
2019/04/05 12:27:31 [E] [proxy.go:515] [qb] connect to local service [127.0.0.1:9999] error: dial tcp 127.0.0.1:9999: connectex: No connection could be made because the target machine actively refused it.
2019/04/05 12:27:33 [E] [proxy.go:515] [qb] connect to local service [127.0.0.1:9999] error: dial tcp 127.0.0.1:9999: connectex: No connection could be made because the target machine actively refused it.
2019/04/05 12:28:30 [E] [proxy.go:515] [qb] connect to local service [127.0.0.1:9999] error: dial tcp 127.0.0.1:9999: connectex: No connection could be made because the target machine actively refused it.
2019/04/05 12:28:33 [E] [proxy.go:515] [qb] connect to local service [127.0.0.1:9999] error: dial tcp 127.0.0.1:9999: connectex: No connection could be made because the target machine actively refused it.
2019/04/05 12:41:37 [E] [proxy.go:515] [qb] connect to local service [127.0.0.1:9999] error: dial tcp 127.0.0.1:9999: connectex: No connection could be made because the target machine 
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
`connect to local service [127.0.0.1:9999] error: dial tcp 127.0.0.1:9999: connectex: No connection could be made because the target machine actively refused it.`

日志提示很清晰，请自行排查下本地的此服务是否异常。

**Comment by so1999** [comment]
应该是它依赖的某个服务需要windows登陆才会启动吧，还是frpc的问题

**Comment by zhang14725804** [comment]
检查frp server和frp client启动没有，相应端口开启没有，配置是否正确，还有可能事多个代理冲突呢
