### ISSUE TITLE
何时切到go1.7，以便提高10%左右性能？

### ISSUE THREAD

**Issue by chmis8000** [fatedier/frp#118]
如题，不是go1.7版本提升性能大约 10% 了么？为何不切到1.7版本编译？

**Comment by fatedier** [comment]
0.8.1 的 release 包已经是使用 go1.7 编译了。

**Comment by soulteary** [comment]
to @chmis8000  ref https://github.com/fatedier/frp/commit/2d30a6e8a7e2e285c04d18ba319994a3d6a4f936

@fatedier 你好，我对go不熟悉，请问1.4和1.7相比，frp性能提高明显嘛

**Comment by fatedier** [comment]
@soulteary 相比较而言，在执行效率，gc 等方面都有所提升。当然，性能的提高也不能全指望 go 的提升，更多的还是依赖于优化已有的代码。

frp 目前主要侧重于完善功能，大多数人应该也只是用于个人测试，性能方面的优化会放到后面去做。功能迭代多了代码也有些混乱，当初设计的时候也没考虑到这么多，还是有很大的优化空间，差不多的时候会彻底重构一下代码。
