### ISSUE TITLE
建议把FRPS的ProxyBindAddr区别一下

### ISSUE THREAD

**Issue by kasuganosora** [fatedier/frp#1180]
建议区分下
和frpc 通信绑定地址和frpc代理出来的绑定地址,
场景:
如果把frps搭设在路由里, 把远程的服务暴露给内网使用,如果有这个配置会更方便一些,
虽然有代替方案:使用iptable来屏蔽外网访问.

**Comment by fatedier** [comment]
你已经提到了 `proxy_bind_addr` ，其用途就是如你所说，目前已经支持，和 `bind_addr` 是区分的。
