### ISSUE TITLE
建议改进教程中有关udp的示例

### ISSUE THREAD

**Issue by sueccku** [fatedier/frp#1182]
0.25.3
debian 9 amd64

建议改进教程中有关udp的示例，教程中以dns为例过于费解，建议改成以普通的udp为例

**Comment by fatedier** [comment]
因为 UDP 服务本身不多，DNS 是一个很容易在本地模拟和测试的常见的 UDP 服务。

普通的 UDP 服务，还有什么在各个环境下都方便测试验证的服务吗？

**Comment by fatedier** [comment]
游戏服务器并不能像 DNS 服务一样让每个人都能够很轻易的做验证，对于普通用户而言反而更不友好。

DNS 作为每一台机器上都必备的功能，我觉得作为 UDP 的示例反而是更加合适的。

**Comment by sueccku** [comment]
关键是用dns的举例有误导性，会让人以为udp和tcp配置方法不同，建议保留dns，加一个普通的udp，程序也不用具体程序，说某程序就行了，需要的人自然懂
