### ISSUE TITLE
Proxy plugin

### ISSUE THREAD

**Issue by steom** [fatedier/frp#1183]
Feature request:
Local port in http, socks5 plugins.

tunneling via frpC.exe plugin SOCKS5 and HTTP protocols.

For configure applications and other LAN devices to connect to internet through the frpS.exe public IP.

Point HTTP/SOCKS5 clients (e.g. OS/Browser) to:
frpC:localport

**Comment by fatedier** [comment]
All your need is an independent http or socks5 proxy.

This is not the purpose of frp.
