### ISSUE TITLE
希望能早日支持http的负载均衡。

### ISSUE THREAD

**Issue by ssdphp** [fatedier/frp#1185]
做项目的时候，内网全是http的。但是目前仅仅支持tcp的group负载均衡，如果做了http的负载均衡，配合自己go本地的项目，我就可以无论在哪里只要有台电脑，有网。公司的内部服务挂了，随时随地就可以保证高可用。就好好了

**Comment by fatedier** [comment]
TODO

**Comment by BigBigBIgMan** [comment]
这个功能很实用，期待大神早日实现

**Comment by fatedier** [comment]
v0.28.0 support http load balancing.
