### ISSUE TITLE
同时配置2个frpc，不同顶级域下的域名无法同时访问

### ISSUE THREAD

**Issue by wxjback** [fatedier/frp#1187]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frps 24.1 frpc1  24.1 frpc2 24.1

**What operating system and processor architecture are you using (`go env`)?**
frps centos7.4
frpc1 merlin on rt-ac87u
frpc2 Padavan on newifi

**Configures you used:**
frps:
```ini
vhost_http_port = 80
token = ****
subdomain_host = AAA.com
```

frpc1:
```ini
# frpc configuration
[common]
server_addr = *.*.*.*
server_port = 7000
token = ****

[aweb]
type = http
local_ip = 192.168.*.*
local_port = 80
subdomain s  = aweb

frpc2:
[common]
server_addr = *.*.*.*
server_port = 7000
token = ****

[bweb]
type = http
local_ip = 192.168.*.*
local_port = 80
subdomain = bweb
custom_domains  = bweb.BBB.com
```

**Steps to reproduce the issue:**
1.frps 配置subdomain_host = AAA.COM后，frpc1 及 frpc2 的 *.AAA.com 均可正常访问，但是 bweb.BBB.com 无法访问 [bweb]
2.frps 不配置 subdomain_host ，frpc1 及 frpc2 在配置了 不同的custom_domains后，只有 frpc1或frpc2 其中的一个能够访问，貌似是不能同时存在一样，因为如果配置相同的sub 或者 custom后，只要 相同域名，都能正常访问。

**Describe the results you expected:**
希望将AAA/BBB都解析到 frps 服务器后，给不同frpc 配置 不同 顶级域，让custom_domains 起作用。

**Comment by fatedier** [comment]
本地无法复现这个问题，同样的配置，测试正常。

**Comment by wxjback** [comment]
访问 失败后，查看日志，日志报有

`[newhttp.go:209] http: proxy error: EOF`

访问成功URL的 日志里 无此内容

**Comment by fatedier** [comment]
日志说明你的本地服务连接中断。
