### ISSUE TITLE
建议 - 增加https转发http 功能

### ISSUE THREAD

**Issue by status301** [fatedier/frp#1188]
参考已有的模板，可以在https配置中增加https_crt和https_key，便捷的将本地的https化http服务
[s1]
type = https
local_port = 80
local_ip = 127.0.0.1
custom_domains = yourdomain.com
https_crt = /home/server.crt
https_key = /home/server.key

go get github.com/ossrs/go-oryx
/home/httpx-static -https 444 -proxy http://127.0.0.1:80 -ssc /home/fullchain.pem -ssk /home/privkey.pem

**Comment by fatedier** [comment]
@status301 你这个需求好像并不一样，是将证书放在了 frpc 端，是可以考虑的一个点。

我想问的是，这个和本地服务前通过 nginx 将 https 转成 http 有什么不同？因为通常 web 服务前部署一个 nginx 是比较常规的需求。且加入这个功能，可能会导致 frpc 的体积增大，对于不关心这个功能的用户来说，就没有意义了。

frpc 有一个 plugin 的机制，可以用来实现这个功能，需要验证下对于客户端体积的影响。

先 reopen。

**Comment by status301** [comment]
在一部分frpc运行环境中没有安装nginx，也希望能减少一点配置步骤，降低配置的复杂度。

**Comment by fatedier** [comment]
v0.26.0 已支持。
