### ISSUE TITLE
xtcp穿透失败

### ISSUE THREAD

**Issue by thorisme** [fatedier/frp#1197]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.16.1

**What operating system and processor architecture are you using (`go env`)?**
客户端：windows10
vps：linux
客户端：Windows10

**Configures you used:**
server：
[common]
bind_port = 7010
bind_udp_port = 7011
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd =xxx
vhost_http_port = 85
vhost_https_port = 443
privilege_mode = true
tcp_mux = true
privilege_token = aaaaaa
max_pool_count = 50
log_file = ./frps.log
log_level = info
log_max_days = 3

[ssh]
type= tcp
auth_token = aaaaaa
listen_port = 6000

[ssh]
type= tcp
auth_token = aaaaaa
listen_port = 61111

被控端：
[common]
server_addr = xxx.cc
server_port = 7010
privilege_token = xxx
auth_token = aaaaaa
login_fail_exit = false
tcp_mux = true

[p2p_mstsc_1]
type = xtcp
sk = aaaaaa
local_ip = 127.0.0.1
local_port = 12345

控制端：
[common]
server_addr = xxx.cc
server_port = 7010
privilege_token = xxx
auth_token = aaaaaa
login_fail_exit = false
tcp_mux = true

[p2p_mstsc_1]
type = xtcp
role = visitor
server_name = p2p_mstsc_1
sk = aaaaaa
bind_addr = 127.0.0.1
bind_port = 6003

日志：
2019/04/13 19:20:43 [I] [proxy_manager.go:298] proxy removed: []
2019/04/13 19:20:43 [I] [proxy_manager.go:308] proxy added: []
2019/04/13 19:20:43 [I] [proxy_manager.go:331] visitor removed: []
2019/04/13 19:20:43 [I] [proxy_manager.go:340] visitor added: [p2p_mstsc_1 p2p_mstsc_2]
2019/04/13 19:20:43 [I] [control.go:240] [c48da460adc927db] login to server success, get run id [c48da460adc927db], server udp port [7011]
2019/04/13 19:20:43 [I] [proxy_manager.go:244] [c48da460adc927db] try to start visitor [p2p_mstsc_1]
2019/04/13 19:20:43 [I] [proxy_manager.go:252] [p2p_mstsc_1] start visitor success
2019/04/13 19:20:43 [I] [proxy_manager.go:244] [c48da460adc927db] try to start visitor [p2p_mstsc_2]
2019/04/13 19:20:43 [I] [proxy_manager.go:252] [p2p_mstsc_2] start visitor success
2019/04/13 19:20:59 [W] [visitor.go:224] [p2p_mstsc_1] get natHoleRespMsg error: read udp 192.168.1.172:65325->xxx.cc:7011: i/o timeout
2019/04/13 19:21:15 [W] [visitor.go:224] [p2p_mstsc_oa1] get natHoleRespMsg error: read udp 192.168.1.172:64069->xxx.cc:7011: i/o timeout
2019/04/13 19:24:34 [W] [visitor.go:224] [p2p_mstsc_oa1] get natHoleRespMsg error: read udp 192.168.1.172:62778->xxx.cc:7011: i/o timeout

同样的配置，在一台windowsxp上测试成功

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/README_zh.md#%E7%82%B9%E5%AF%B9%E7%82%B9%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F
