### ISSUE TITLE
能否增加映射指定IP端口的功能

### ISSUE THREAD

**Issue by 512557852** [fatedier/frp#120]
如映射192.168.1.10:22。
现在只能映射本机的端口，希望能增加映射其他设备端口的功能。谢谢~

**Comment by fatedier** [comment]
这个目前已经支持了，`local_ip` 可以填任意可访问到的 IP 地址，文档里没有说明，后续补上。

**Comment by 512557852** [comment]
0.8.1版本已经支持了吗？目前我在 local_port = 里填 X.X.X.X:X 还是 X.X.X.X X 两种格式都会报 local_port error

**Comment by wxyzh** [comment]
请参考配置示例
>[web02]
>type = http
>local_ip = 127.0.0.1
>local_port = 8000

[frpc.ini](https://github.com/fatedier/frp/blob/master/conf/frpc.ini)
