### ISSUE TITLE
Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s

### ISSUE THREAD

**Issue by WXinFfly** [fatedier/frp#1200]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.26.0

**What operating system and processor architecture are you using (`go env`)?**
linux amd64

**Configures you used:**
[common]
bind_port = 7000
kcp_bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
custom_domains = amz-hsunter.com,amz-shunter.cn,winonly-idirect.com,amz-markerting.com
dashboard_port = 4561
dashboard_user = admin
dashboard_pwd = admin
token = Abcd567800

**Steps to reproduce the issue:**
服务器和客户端连接一段时间会出现frp的仪表盘看不到信息，并且所有连接frp发客户端都无法访问

**Describe the results you received:**
2019/04/16 15:07:35 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:36 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:37 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:38 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:39 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:40 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:41 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:42 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:43 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:44 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:45 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:46 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:47 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:48 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:49 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:50 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:51 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:52 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:53 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:54 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:55 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:56 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:57 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:58 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:07:59 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:08:00 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:08:01 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/04/16 15:08:02 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s

**Describe the results you expected:**
这种问题怎么解决

**Comment by fatedier** [comment]
连接数过多，优化系统参数，关闭 dashboard

**Comment by WXinFfly** [comment]
现在又出现这种closing的情况


2019/04/16 16:26:53 [I] [control.go:274] [5e9fcac262e257d7] control writer is closing
2019/04/16 16:26:53 [W] [newhttp.go:209] http: proxy error: EOF
2019/04/16 16:26:53 [W] [newhttp.go:209] http: proxy error: EOF
2019/04/16 16:26:53 [I] [proxy.go:67] [5e9fcac262e257d7] [web11114] proxy closing
2019/04/16 16:26:53 [W] [newhttp.go:209] http: proxy error: EOF
2019/04/16 16:26:53 [I] [proxy.go:67] [5e9fcac262e257d7] [web04] proxy closing
2019/04/16 16:26:53 [I] [proxy.go:67] [5e9fcac262e257d7] [web01] proxy closing
2019/04/16 16:26:53 [I] [proxy.go:67] [5e9fcac262e257d7] [web03 https] proxy closing
2019/04/16 16:26:53 [I] [proxy.go:67] [5e9fcac262e257d7] [web03] proxy closing
2019/04/16 16:26:53 [W] [newhttp.go:209] http: proxy error: EOF
2019/04/16 16:26:53 [I] [proxy.go:112] [5e9fcac262e257d7] [web03 https] listener is closed
2019/04/16 16:26:53 [I] [proxy.go:67] [5e9fcac262e257d7] [router02] proxy closing
2019/04/16 16:26:53 [I] [proxy.go:67] [5e9fcac262e257d7] [web11113] proxy closing
2019/04/16 16:26:53 [I] [proxy.go:67] [5e9fcac262e257d7] [router01] proxy closing
2019/04/16 16:26:53 [I] [control.go:349] [5e9fcac262e257d7] client exit success
2019/04/16 16:26:53 [W] [newhttp.go:209] httputil: ReverseProxy read error during body copy: snappy: corrupt input
2019/04/16 16:26:53 [I] [service.go:317] client login info: ip [183.17.127.110:16803] version [0.26.0] hostname [] os [windows] arch [amd64]
2019/04/16 16:26:53 [I] [http.go:67] [5e9fcac262e257d7] [web04] http proxy listen for host [api.ngrok.amz-hunter.com] location []
2019/04/16 16:26:53 [I] [control.go:397] [5e9fcac262e257d7] new proxy [web04] success
2019/04/16 16:26:53 [I] [http.go:67] [5e9fcac262e257d7] [web11114] http proxy listen for host [erp.amz-marketing.com] location []
2019/04/16 16:26:53 [I] [control.go:397] [5e9fcac262e257d7] new proxy [web11114] success
2019/04/16 16:26:53 [I] [https.go:43] [5e9fcac262e257d7] [web03 https] https proxy listen for host [www.amz-hunter.cn]
2019/04/16 16:26:53 [I] [control.go:397] [5e9fcac262e257d7] new proxy [web03 https] success
2019/04/16 16:26:53 [I] [http.go:67] [5e9fcac262e257d7] [router02] http proxy listen for host [www.winonly-direct.com] location []
2019/04/16 16:26:53 [I] [control.go:397] [5e9fcac262e257d7] new proxy [router02] success
2019/04/16 16:26:53 [I] [http.go:67] [5e9fcac262e257d7] [web03] http proxy listen for host [www.amz-hunter.cn] location []
2019/04/16 16:26:53 [I] [control.go:397] [5e9fcac262e257d7] new proxy [web03] success
2019/04/16 16:26:53 [I] [http.go:67] [5e9fcac262e257d7] [router01] http proxy listen for host [ep.amz-hunter.cn] location []
2019/04/16 16:26:53 [I] [control.go:397] [5e9fcac262e257d7] new proxy [router01] success
2019/04/16 16:26:53 [I] [http.go:67] [5e9fcac262e257d7] [web01] http proxy listen for host [a.amz-hunter.cn] location []2019/04/16 16:26:53 [I] [control.go:397] [5e9fcac262e257d7] new proxy [web01] success
2019/04/16 16:26:53 [I] [http.go:67] [5e9fcac262e257d7] [web11113] http proxy listen for host [www.amz-hunter.com] location []
2019/04/16 16:26:53 [I] [control.go:397] [5e9fcac262e257d7] new proxy [web11113] success
2019/04/16 16:26:54 [I] [proxy.go:80] [5e9fcac262e257d7] [web04] get a new work connection: [183.17.127.110:16803]
2019/04/16 16:27:04 [W] [control.go:237] [5e9fcac262e257d7] timeout trying to get work connection
2019/04/16 16:27:04 [W] [proxy.go:77] [5e9fcac262e257d7] [web04] failed to get work connection: timeout trying to get work connection
2019/04/16 16:27:04 [W] [newhttp.go:209] http: proxy error: timeout trying to get work connection
2019/04/16 16:27:04 [W] [control.go:237] [5e9fcac262e257d7] timeout trying to get work connection
2019/04/16 16:27:04 [W] [proxy.go:77] [5e9fcac262e257d7] [web04] failed to get work connection: timeout trying to get work connection
2019/04/16 16:27:04 [W] [newhttp.go:209] http: proxy error: timeout trying to get work connection
2019/04/16 16:27:04 [W] [control.go:237] [5e9fcac262e257d7] timeout trying to get work connection
2019/04/16 16:27:04 [W] [proxy.go:77] [5e9fcac262e257d7] [web04] failed to get work connection: timeout trying to get work connection
2019/04/16 16:27:04 [W] [newhttp.go:209] http: proxy error: timeout trying to get work connection
2019/04/16 16:27:04 [W] [control.go:237] [5e9fcac262e257d7] timeout trying to get work connection
2019/04/16 16:27:04 [W] [proxy.go:77] [5e9fcac262e257d7] [web11114] failed to get work connection: timeout trying to get work connection
2019/04/16 16:27:04 [W] [newhttp.go:209] http: proxy error: timeout trying to get work connection
2019/04/16 16:27:05 [W] [control.go:237] [5e9fcac262e257d7] timeout trying to get work connection
2019/04/16 16:27:05 [W] [proxy.go:77] [5e9fcac262e257d7] [web04] failed to get work connection: timeout trying to get work connection
2019/04/16 16:27:05 [W] [newhttp.go:209] http: proxy error: timeout trying to get work connection
2019/04/16 16:27:08 [W] [newhttp.go:209] http: proxy error: no such domain

**Comment by fatedier** [comment]
先按照上面说的进行参数优化，然后你单个机器配置的 proxy 可能太多？

**Comment by umena337** [comment]
accept4: too many open files; retrying in 1s    
v0.27.0
