### ISSUE TITLE
Authorization failed win 10 

### ISSUE THREAD

**Issue by tao96** [fatedier/frp#1201]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
26.0   26.0

**What operating system and processor architecture are you using (`go env`)?**
win10  Ubuntu18.04 cent os

**Configures you used:**
Client
[common]
server_addr = **
server_port = 2025

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

token = **

admin_addr = **
admin_port = 2020
dashboard_user = **
dashboard_pwd = **

Server
//# [common] is integral section
[common]
//# A literal address or host name for IPv6 must be enclosed
//# in square brackets, as in "[::1]:80", "[ipv6-host]:http" or "[ipv6-host%zone]:80"
bind_addr = **
bind_port = 2025
//# udp port used for kcp protocol, it can be same with 'bind_port'
//# if not set, kcp is disabled in frps
kcp_bind_port = 2025
//# if you want to configure or reload frps by dashboard, dashboard_port must be set
dashboard_port = 2020
//# dashboard assets directory(only for debug mode)
dashboard_user = **
dashboard_pwd = **
//# assets_dir = ./static
vhost_http_port = 2021
vhost_https_port = 2022
//# console or real logFile path like ./frps.log
log_file = ./frps.log
//# debug, info, warn, error
log_level = debug
log_max_days = 3
//# auth token
token = **
//# It is convenient to use subdomain configure for http、https type when many people use one frps server together.
subdomain_host = **
//# only allow frpc to bind ports you list, if you set nothing, there won't be any limit
//#allow_ports = 1-65535
//# pool_count in each proxy will change to max_pool_count if they exceed the maximum value
max_pool_count = 50
//# if tcp stream multiplexing is used, default is true
tcp_mux = true

**Steps to reproduce the issue:**
1.https://github.com/MvsCode/frp-onekey
2.
3.

**Describe the results you received:**
2019/04/17 02:30:05 [I] [service.go:337] client login info: ip [**:15314] version [0.26.0] hostname [] os [windows] arch [amd64]
2019/04/17 02:30:05 [W] [service.go:279] authorization failed
2019/04/17 02:39:03 [I] [service.go:337] client login info: ip [**:44687] version [0.26.0] hostname [] os [windows] arch [amd64]
2019/04/17 02:39:03 [W] [service.go:279] authorization failed
2019/04/17 02:45:48 [I] [service.go:337] client login info: ip [**:12308] version [0.26.0] hostname [] os [linux] arch [amd64]
2019/04/17 02:45:48 [W] [service.go:279] authorization failed

**Describe the results you expected:**
Successful connect

**Additional information you deem important (e.g. issue happens only occasionally):**
使用阿里云 谷歌云 内网win10交叉连接，错误类型雷同

**Can you point out what caused this issue (optional)**
疑似脚本更改ini不兼容

**Comment by tao96** [comment]
经过测试，删除token后可以正常连接

**Comment by qwxren** [comment]
我也映到同样的问题：
经过测试 ，删除 客户端 frpc里面的token配置就可以成功（服务端token配置有值）

**Comment by schunlei** [comment]
是不是服务端没有用 -c 指定配置文件？我如果直接启动服务端，客户端只有删除token才可以链上。如果指定了配置文件就没有问题了。
