### ISSUE TITLE
[W] [service.go:82] login to server failed: dial tcp xxx.xxx.xxx.xxx:7000: connect: connection timed out

### ISSUE THREAD

**Issue by jingangdidi** [fatedier/frp#1202]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frp_0.26.0

**What operating system and processor architecture are you using (`go env`)?**
Centos7
amd64

**Configures you used:**
Server:
[common]
bind_port = 7000

client:
[common]
server_addr = XXX.XXX.XXX.XXX
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

**Steps to reproduce the issue:**
1.内网服务器（Centos7）：./frps -c ./frps.ini，显示：
[I] [service.go:136] frps tcp listen on 0.0.0.0:7000
[I] [root.go:204] Start frps success
2.client端： XXX.XXX.XXX.XXX改为内网IP，./frpc -c ./frpc.ini，显示：
[W] [service.go:82] login to server failed: dial tcp  XXX.XXX.XXX.XXX:7000: connect: connection timed out

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by xiuluo211314** [comment]
如果能保证端口通，其他网络没问题的话，查看是不是阿里云服务器（如果你是）的安全组规则有没有加入7000端口，这个问题坑了好久！

**Comment by jingangdidi** [comment]
这个问题困扰好久，一直没解决，服务器在公司（不是云服务器），22、7000、6000端口已全开。是服务端的问题？

**Comment by LuckyMango** [comment]
防火墙关闭试一下？ systemctl stop firewalld.service

**Comment by Bryce1010** [comment]
阿里云服务器建议添加对应的端口的防火墙管理里面，好坑啊。

**Comment by chengziqaq** [comment]
> 防火墙关闭试一下？ systemctl stop firewalld.service

今天遇到这个问题 你说的这个方法有效 linux系统有防火墙 阿里云又带一层防火墙 ..多谢啦

**Comment by Heqiaomu** [comment]
我这边遇到这个问题主要是在使用 docker 部署客户端的时候出现，我现在是一个服务端，会存在多个客户端进行连接，为了方便，我会在每个服务内都使用一个frpc的客户端来进行透传。但是这几天一直出现这个问题：`[W] [service.go:134] login to server failed: dial tcp ip:7011: i/o timeout ` ， 当前的端口是开放了的，使用二进制的 frpc 客户端没有问题，使用 容器化就存在问题。这个是应该怎么排查呢？
frpc -v  0.47.0
