### ISSUE TITLE
Bind FRP client to a specific network adapter

### ISSUE THREAD

**Issue by pablozzz** [fatedier/frp#1205]
How to bind FRP client to a specific network adapter on Windows?
Great job, btw!

**Comment by fatedier** [comment]
You can't do that but you can set `local_ip` to connect.

**Comment by pablozzz** [comment]
> You can't do that but you can set `local_ip` to connect.

Hi @fatedier thanks for your response. I've tried use this config:

[http_proxy]
type = tcp
remote_port = 8080
plugin = http_proxy
plugin_http_user = abc
plugin_http_passwd = abc
local_ip = 192.168.0.1

But it doesn't help. The main thing which I need that if my PC connected to VPN I would like FRP local proxy works to bypass VPN. 

How do you think is it possible?

**Comment by fatedier** [comment]
Update your route  table ?

**Comment by pablozzz** [comment]
@fatedier  Thank you. Yes, I've tired this way:  I add  in my win10 route table new route

139.xxx.xxx.xxx  255.255.255.255      192.168.1.1       192.168.1.3 

where 139.xxx.xxx.xxx  - is FRP server IP, but it doesn't help. 

Proxy still use VPN connection (I see VPN IP instead real IP on IP detection services).
Do you have any more idea what can I do to bypass VPN connection?

**Comment by ChenWenBrian** [comment]
希望能有个全局参数，例如客户端连接服务器时，可以指定出口的网卡。

类似curl命令的interface参数，如：`curl --interface eth0 whatismyip.akamai.com`
