### ISSUE TITLE
【声音】希望支持 visit not found 页面的自定义

### ISSUE THREAD

**Issue by BI7PRK** [fatedier/frp#1207]
希望支持转发失败的页面内容自定义。
在自定义内容后附加 frp 的版本信息。

[/utils/vhost/resource.go#L26](https://github.com/fatedier/frp/blob/6a7efc81c9fcd410ba603573cdbe501056b1b04a/utils/vhost/resource.go#L26)

**Comment by fatedier** [comment]
v0.27.0 已支持。
