### ISSUE TITLE
特权模式privilege_mode的疑似bug

### ISSUE THREAD

**Issue by xcorp1986** [fatedier/frp#121]
服务端frps开启了privilege_mode，然后我修改了frps privilege_token的值，frps reload之后不能加载后来设置的privilege_token。另外release包里的初始privilege_token值太简单了，对于没详细看文档的童鞋来说是一个隐藏的隐患。

**Comment by 512557852** [comment]
privilege_token 是在 common 里的，作者说了reload不能加载common里修改的内容
