### ISSUE TITLE
将内网打印机映射出去，打印机可以被添加，但实际无法打印

### ISSUE THREAD

**Issue by miws** [fatedier/frp#1210]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
从v0.25.2 到 v0.26.0 这几个版本都试过。

**What operating system and processor architecture are you using (`go env`)?**
我将打印机的两种协议均映射出去，实际观察走的是631端口，然后使用远程打印机，在dashboard中观察，有数据交换，但打印机并没有打印。
再尝试选择9100协议端口，同样数据发送过去，打印机并没有打印。

**Configures you used:**
#frpc.ini
[p_9100]
type = tcp
local_ip = 192.168.0.104
local_port = 9100
remote_port = 9100
[p_631]
type = tcp
local_ip = 192.168.0.104
local_port = 631
remote_port = 631

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by nexw** [comment]
这个牵涉的问题会不会太广了，打印机型号和协议都很多。

**Comment by xiaopiao5789** [comment]
不一定只有 TCP 协议，可能有 UDP 协议。这个不一定好弄

**Comment by saonian** [comment]
你在浏览器中访问本地打印机，比如：localhost:631，在管理界面中找到防火墙的页面打开，里面会告诉你应该开放哪些端口
