### ISSUE TITLE
FRPS如何高可用？

### ISSUE THREAD

**Issue by fcatat** [fatedier/frp#1214]
已将FRPC用于生产，需要做HA，好像传统的运维手段，都不太适用，烦请建议，谢谢
1.frpc 重连机制是怎样的？（断开后几秒重连，重试几次）
2.frpc的配置能否注册到多台frps

**Comment by status301** [comment]
问题1:见文档 https://github.com/fatedier/frp/blob/master/conf/frpc_full.ini
```
# decide if exit program when first login failed, otherwise continuous relogin to frps
# default is true
login_fail_exit = true
```
问题2 :1个frpc在运行中只能注册到1个frps中，要想注册到另一个frps，你可以再修改配置文件，起另一个frpc。

没看懂用于生产是什么意思，要做HA你可以将frpc运行在多个docker中。

**Comment by bood** [comment]
@status301 HA的意思是高可用，即多个节点形成某种frps集群（至少两个frps服务器），单个frps断线不影响整个系统运行

**Comment by victor23d** [comment]
FRP-Docker-K8S
https://github.com/victor23d/frp-docker-k8s
把FRP运行在 Kubernetes 集群上，外面加一层LoadBalancer即可，HA高可用应该不是问题。

**Comment by hulucc** [comment]
> FRP-Docker-K8S
> https://github.com/victor23d/frp-docker-k8s
> 把FRP运行在 Kubernetes 集群上，外面加一层LoadBalancer即可，HA高可用应该不是问题。

真的吗？假如链路是 frpc -- loadbalancer -- frps1/frps2 -- loadbalancer -- user
frpc 实际连接的是frps1，user 实际连接的是 frps2，能通？

**Comment by edenlong2006** [comment]
loadbalancer 采用主备模式即可。至于扩展性则需要让客户端按region 划分，每个region使用这个独立域名，每个域名对应一组loadbalancer 。

**Comment by BoomChao** [comment]
能详细说说么
