### ISSUE TITLE
How to implement HTTPS SSL connection for multiple frp wildcard subdomains with wildcard SSL certificates?

### ISSUE THREAD

**Issue by jerrychong25** [fatedier/frp#1218]
Hi,

Currently I have implemented frp communication between 5 clients and 1 server, with **subdomain_host = abc.com** in **frps.ini**

I saw number of methods for implementing HTTPS  SSL connection between 1 client and 1 server, but can't find a way to implement HTTPS SSL connection between 5 clients and 1 server.

Is it possible to implement wildcard SSL certificates for multiple sub domains?

If yes, how to implement this?

Thanks.

**Comment by MHgit01** [comment]
1.First to nginx
2.nginx to FRPs

**Comment by jerrychong25** [comment]
> 1.First to nginx
> 2.nginx to FRPs

You means following flow?
Public internet traffic -> Nginx Server (Server 1) -> FRP Server (Server 2) -> FRP Client

Can Server 1 and Server 2 on same server?

**Comment by sucotronic** [comment]
> Can Server 1 and Server 2 on same server?

Yes

**Comment by logoove** [comment]
https://www.kancloud.cn/logoove/we7/1108072

**Comment by jerrychong25** [comment]
After tried several method, only following is working:
1) Setup FRP Client & Server For Wildcard Domains
https://www.cnblogs.com/damnedmoon/p/10357033.html
2) Generate Wildcard SSL Certificate & Nginx HTTPS Setup Tutorial
https://segmentfault.com/a/1190000017194280
3) Generate Wildcard SSL Certificate Using Cloudflare DNS Plugin
https://certbot.eff.org/lets-encrypt/centosrhel7-nginx.html
https://certbot.eff.org/docs/using.html#dns-plugins
https://certbot-dns-cloudflare.readthedocs.io/en/stable/

**Comment by jerrychong25** [comment]
Since it is working now, I will close this issue.
