### ISSUE TITLE
frps 能否增加 根据子域名转向不同的端口的问题

### ISSUE THREAD

**Issue by schunlei** [fatedier/frp#1219]
因为我的frps安装在防火墙后，目前7000端口是打开的。
我在一台机器上部置了一个带plugin_socks5的frpc，远程端口是 frps公网ip的端口8001(防火墙没有打开这个端口,以后可能会有更多的frpc链到这个frps上,因此在防火墙上放开端口不是太方便).
想着 能否在frps上增加一个根据域名(或子域名)转到不同端口的功能.
感觉与 http差不多,只不过那个是外面用的是http代理,但是走到后段变成了socks代理了.

不知道我讲明白没有.

**Comment by Villivateur** [comment]
TCP 是没有域名的概念的，如果是 TCP 代理，那么服务端是不知道你访问他的域名是什么的，故不能通过域名转发端口

**Comment by nexw** [comment]
同上，在只有NGINX的HTTP反向代理才可以做到的。

**Comment by schunlei** [comment]
前面两位好像没有明白我的意思。如下图中链路二是访问者在自己电脑上设置http代理访问的。链路一是frps 与frpc之间的用plugin_socks插件建立的。
![111](https://user-images.githubusercontent.com/48410012/56877298-8f5ae380-6a7f-11e9-9e57-dd482169c22b.jpg)

**Comment by schunlei** [comment]
实际上就是frps能不能增加 http代理转 socks5代理的功能

**Comment by czb1994** [comment]
我也想问类似这个问题,就是我在路由器上面布了frpc,然后加入局域网内有3台电脑,我想外部进行远程必须用不同的端口,而不可类似的 a1.rt.***.com; a2.rt.***.com; a2.rt.***.com,毕竟文字比端口好记住

**Comment by almas1992** [comment]
> 实际上就是frps能不能增加 http代理转 socks5代理的功能

FRPC 端
```
[common]
server_addr = x.x.x.x
server_port = 7000

[web]
type = http
local_ip = 127.0.0.1
local_port = 5050
subdomain = web

[web2]
type = http
local_ip = 127.0.0.1
local_port = 4040 
subdomain = web2
```
这样不就不同子域名转向不同的端口，不知我理解的对不对

安装一个nginx，做反向代理，然后就如下配置
```
[web3]
type = http
local_ip = 127.0.0.1
local_port = 80
subdomain = web2
host_header_rewrite = xxxx.test  // nginx配置中自定义的域名

```

**Comment by fatedier** [comment]
不能。
