### ISSUE TITLE
frps 经常断开

### ISSUE THREAD

**Issue by bigbigbigfish** [fatedier/frp#1220]
2019/04/25 07:48:43 [I] [control.go:274] [f2994c03a9e77f05] control writer is closing
2019/04/25 07:48:43 [I] [proxy.go:69] [f2994c03a9e77f05] [p2p_ssh] proxy closing
2019/04/25 07:48:43 [I] [proxy.go:69] [f2994c03a9e77f05] [ssh] proxy closing
2019/04/25 07:48:43 [I] [proxy.go:135] [f2994c03a9e77f05] [ssh] listener is closed
2019/04/25 07:48:43 [I] [proxy.go:69] [f2994c03a9e77f05] [xdp] proxy closing
2019/04/25 07:48:43 [I] [proxy.go:135] [f2994c03a9e77f05] [xdp] listener is closed
2019/04/25 07:48:43 [I] [control.go:350] [f2994c03a9e77f05] client exit success

出现上面的信息就不行了，必须重启frps才能ssh 连接frpc.

版本 0.26.0

**Comment by mengpengfei** [comment]
遇到同样问题

**Comment by bsharkl** [comment]
根本无法用于生产环境！稳定性有待提示。
