### ISSUE TITLE
kcp 工作不正常

### ISSUE THREAD

**Issue by tao96** [fatedier/frp#1222]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
26

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**
[common]
server_addr = 34.9*****
server_port = 2025

[RDP]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 2026

[RDP_kcp]
protocol = kcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 2027

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
kcp用不了，服务器日志
2019/04/27 12:05:04 [I] [service.go:136] frps tcp listen on 0.0.0.0:2025
2019/04/27 12:05:04 [I] [service.go:145] frps kcp listen on udp 0.0.0.0:2024
2019/04/27 12:05:04 [I] [service.go:229] Dashboard listen on 0.0.0.0:2020
2019/04/27 12:05:04 [I] [root.go:204] Start frps success
本地common配置2025端口一切正常，2024端口就actively refuse，求解决，谢谢！

**Comment by status301** [comment]
frpc的配置文件已经说清楚了，用别人的东西，一定要看清文档。
# [common] is integral section
[common]
# communication protocol used to connect to server
# now it supports tcp and kcp and websocket, default is tcp
protocol = tcp

# 'ssh' is the unique proxy name
# if user in [common] section is not empty, it will be changed to {user}.{proxy} such as 'your_name.ssh'
[ssh]
# tcp | udp | http | https | stcp | xtcp, default is tcp
type = tcp

**Comment by tao96** [comment]
好的，感谢，也就是底层使用kcp，在云端看到的类型还是tcp是吗？目前这个问题已经解决，但是存在使用kcp时rdp连接被拒绝的情况，切换为tcp又可以使用，另外请问，websocket有何特性？win10如何使用让frpc同时运行两个实例连接不同的服务器？谢谢！

**Comment by phtwo** [comment]
1. [底层通信可选 kcp 协议](https://github.com/fatedier/frp/blob/master/README_zh.md#%E5%BA%95%E5%B1%82%E9%80%9A%E4%BF%A1%E5%8F%AF%E9%80%89-kcp-%E5%8D%8F%E8%AE%AE)
1. 复制一份，在不同的目录运行就行了
