### ISSUE TITLE
kcp 协议被运营商限制，是否可以升级kcp的UDP伪装成tcp报文进行传输避免被运营商qos

### ISSUE THREAD

**Issue by xyb401** [fatedier/frp#1223]
1、kcp 协议被运营商限制，是否可以升级kcp的UDP伪装成tcp报文进行传输避免被运营商qos
2、是否可以配置限制frp的传输速度

**Comment by Zxilly** [comment]
UDP 伪装成TCP。。。。目测提问的没学过网络结构

**Comment by JimLee1996** [comment]
二楼应该学过，但是学的不好，哈哈哈

**Comment by Zxilly** [comment]
> 二楼应该学过，但是学的不好，哈哈哈

@JimLee1996 查了下才知道有改包头的操作。。。但这样改了不就是TCP吗，UDP over TCP.

**Comment by JimLee1996** [comment]
对的。
其实还可以用raw socket伪造，甚至还可以模拟三次握手，不过必须得绕过内核的协议栈

**Comment by chquse** [comment]
udp2raw实测好用。

**Comment by fatedier** [comment]
建议自行研究其他方式，不在本项目讨论范围内。
