### ISSUE TITLE
从0.25.0这个版本开始，客户端报错login to server failed: i/o deadline reached

### ISSUE THREAD

**Issue by keeno1982** [fatedier/frp#1225]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.27.0

**What operating system and processor architecture are you using (`go env`)?**
debian,arm7

**Configures you used:**
FRPS:
[common]
bind_addr = 0.0.0.0
bind_port = 1113
kcp_bind_port = 1113
bind_udp_port = 1114
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = 123
vhost_http_port = 88
vhost_https_port = 89
token = 123
max_pool_count = 50
tcp_mux = true
subdomain_host = demodomin.tk

FRPC:
[common]
server_addr = demodomin.tk
server_port = 1113
user = test
tcp_mux = true
protocol = kcp
token = 123
login_fail_exit = false

[NET]
type = http
local_ip = 192.168.196.1
local_port = 80
remote_port = 88
subdomain = net
use_encryption = false
use_compression = true

**Steps to reproduce the issue:**
1.安装从0.25.0开始的版本直到最新版本0.27.0
2.只要过一段时间，大概半小时或一小时后，具体时间没算，
frpc这端就自动断开了，客户端报错 
2019/04/29 22:18:27 [W] [service.go:82] login to server failed: i/o deadline reached
此时必须重启服务端才能连上，然后隔一段时间又自动断开了
4.如果是安装0.24.1和之前的版本就可以一直稳定工作从不断线

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
是不是从0.25.0这个版本开始做了什么重要的调整？导致一直报错 login to server failed: i/o deadline reached？

**Comment by ssdphp** [comment]
我也是遇到这样的问题。看来要用之前的版本。稳定些

**Comment by zqlanly** [comment]
我也是遇到这样的问题。要用0.24之前的版本稳定

**Comment by snowdream** [comment]
关注，同样遇到类似问题，经常断开连接。

**Comment by levinit** [comment]
protocol = kcp去掉

**Comment by fatedier** [comment]
在 #1267 下继续跟踪此问题。

**Comment by jiqing112** [comment]
遇到了类似的问题，0.24的版本不会出现这个问题吗

**Comment by ailuoy** [comment]
0.33.0  在运行了1个月之后 也出现了这个问题..

**Comment by feehoo** [comment]
0.37.0也有同样的问题

**Comment by jiqing112** [comment]
我是找了以前的一个版本解决的。后来换了最新的没问题了。
