### ISSUE TITLE
内存用的比较多

### ISSUE THREAD

**Issue by yingnierxiao** [fatedier/frp#123]
树莓派上面内存用到20几M  看看不能再优化下   压到10M一下

**Comment by wxyzh** [comment]
跑在R6300v2 的客户端大概用的8M的内存
跑在UBUNTU 16.04 amd64上的 服务端 大概用了 15M的内存
我的使用量不大

**Comment by yydcool** [comment]
Would like to try go build with setting GOGC=20 and report here?
