### ISSUE TITLE
【安全建议】frps.ini可以新增客户端登陆失败频率限制。以及登陆失败日志，监听事件，发送邮件

### ISSUE THREAD

**Issue by king192** [fatedier/frp#1231]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
latest

**What operating system and processor architecture are you using (`go env`)?**
go env

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
登录失败的日志，目前是已经有的。

其他的，过于复杂，目前不考虑直接加这些功能。

考虑之后通过插件的方式来提供，有需要的话自己按需写相应的插件即可。

**Comment by hzlmy2002** [comment]
可以用fail2ban配合登陆失败的日志来防止暴力破解，并且fail2ban也可以实现发邮件的功能。

**Comment by fatedier** [comment]
#1403 中做了关于服务端管理插件的设计，后续这一类能力可以通过插件来自行实现。
