### ISSUE TITLE
线程稍微多点就挂

### ISSUE THREAD

**Issue by mengpengfei** [fatedier/frp#1232]
**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.27.0

**What operating system and processor architecture are you using (`go env`)?**
server centos7.5  client win10

**Configures you used:**
client:
[common]
token = xxxxx
server_addr = xxxxx
server_port = 7000
log_file = console
log_level = info

log_max_days = 3

admin_addr = 127.0.0.1
admin_port = 7400
admin_user = xxxx
admin_pwd = xxxxx
pool_count = 5000
tcp_mux = true
login_fail_exit = true
protocol = tcp
tls_enable = true

[webhttp]
type = http
local_port = 9090
local_ip = 127.0.0.1
custom_domains = test.damagou.top

#[web]
#type = tcp
#local_port = 9090
#local_ip = 127.0.0.1
#remote_port = 6000

[webssl]
type = https
local_port = 8443
local_ip = 127.0.0.1
custom_domains = test.damagou.top

server:
[common]
bind_port = 7000

bind_udp_port = 7001

kcp_bind_port = 7000

vhost_http_port = 80
vhost_https_port = 443

dashboard_addr = 0.0.0.0
dashboard_port = 7500

dashboard_user = xxxx
dashboard_pwd = xxxx

log_file = /data/soft/frp_0.27.0_linux_amd64/frps.log

log_level = info

log_max_days = 3

token = xxxx

max_pool_count = 5000

tcp_mux = true

custom_404_page = /data/soft/frp_0.27.0_linux_amd64/404.html

**Steps to reproduce the issue:**
1.部署server端
2.部署client端 映射出来一个网页
3.100线程访问网页
4.网页挂掉，服务报错

server 端日志：
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled
2019/05/05 19:11:50 [W] [http.go:223] http: proxy error: context canceled

client 端日志：
2019/05/05 19:06:23 [W] [control.go:168] start new connection to server error: session shutdown
2019/05/05 19:06:23 [W] [control.go:168] start new connection to server error: session shutdown
2019/05/05 19:06:23 [W] [control.go:168] start new connection to server error: session shutdown
2019/05/05 19:06:23 [W] [control.go:168] start new connection to server error: session shutdown
2019/05/05 19:06:23 [W] [control.go:168] start new connection to server error: session shutdown
2019/05/05 19:06:23 [W] [control.go:168] start new connection to server error: session shutdown
2019/05/05 19:06:23 [W] [control.go:168] start new connection to server error: session shutdown
2019/05/05 19:06:23 [W] [control.go:168] start new connection to server error: session shutdown
2019/05/05 19:06:23 [W] [control.go:168] start new connection to server error: session shutdown
2019/05/05 19:06:23 [W] [control.go:168] start new connection to server error: session shutdown
2019/05/05 19:06:23 [W] [control.go:168] start new connection to server error: session shutdown
2019/05/05 19:06:23 [W] [control.go:168] start new connection to server error: session shutdown
2019/05/05 19:06:23 [W] [control.go:168] start new connection to server error: session shutdown
2019/05/05 19:06:23 [W] [control.go:168] start new connection to server error: session shutdown

**Comment by Nemo1986** [comment]
用什么东西可以进行压力测试呢
[wx_htts2http]
type = https
subdomain = wx
plugin = https2http
plugin_local_addr = 127.0.0.1:8080
我用https做的，经常报404，关键是员工手机上报出来的，没办法追踪，随机报出来，没发追踪。

**Comment by fatedier** [comment]
@mengpengfei 这个要考虑到你的网络环境，带宽，服务器的配置，你可以排查下具体的瓶颈在哪里。
@Nemo1986 可以查看服务端的对应日志，是超时，还是和客户端的连接网络不稳定。

**Comment by vritser** [comment]
调整了系统参数还是不行，线程一多就挂
