### ISSUE TITLE
能否让我入群？想学习学习！

### ISSUE THREAD

**Issue by jobsgxx** [fatedier/frp#1233]
大神，我刚刚捐献了我的money，能否让我入群？想学习学习！ @fatedier

**Comment by fatedier** [comment]
QQ 群目前有两个，都可以加，申请回答问题即可。

**Comment by jobsgxx** [comment]
能发一下具体的群号吗？我至少加的那个是在github上的那个群，加不进去，直接提示管理员拒绝？麻烦您帮忙再提供一下群号谢谢！

Frome  Jobs_iPhone
Mobile Phone : 18516152026
Email: jobs_gxx@163.com

**Comment by fatedier** [comment]
那个群的说明里就有二群的群号: 112321385

**Comment by jobsgxx** [comment]
我加了，麻烦管理员审核一下，谢谢

Frome  Jobs_iPhone
Mobile Phone : 18516152026
Email: jobs_gxx@163.com

> 在 2019年5月7日，15:44，fatedier <notifications@github.com> 写道：
> 
> 112321385

**Comment by jobsgxx** [comment]
管理员拒绝让我加群呀？？？咋回事儿？

Frome  Jobs_iPhone
Mobile Phone : 18516152026
Email: jobs_gxx@163.com
