### ISSUE TITLE
server add. 可以用域名替代IP地址设置吗？如何实现局域网内自动分配IP和端口？

### ISSUE THREAD

**Issue by kentcc88** [fatedier/frp#1238]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

你好，我想问问，服务器端的ini配置里，server add 选项可以用域名替代IP地址设置吗？
另外，假设我局域网上有n个pi，可以用什么方法让他们每次启动之后，可以自动分配IP和端口与服务器端那边匹配，要实现的话困不困难？

**Comment by xxsq** [comment]
可以使用自定义二级域名进行配置，参考：https://github.com/fatedier/frp/blob/master/README_zh.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8C%E7%BA%A7%E5%9F%9F%E5%90%8D

**Comment by fatedier** [comment]
* 服务器端没有什么 server add 选项。
* 自动分配 IP 是你自己的事情。
