### ISSUE TITLE
如果服务器上80端口被占用的话 只能选择别的端口吗?

### ISSUE THREAD

**Issue by iscraft** [fatedier/frp#124]
想通过服务器的80做内网的微信开发相关
但服务器的80端口已经被占用
那么无论在iis里新建站点并绑定测试域名
是否都无法通过测试域名:80来访问到内网web呢
log为Create vhost http listener error,......bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by JimLee1996** [comment]
by using nginx reverse proxy

**Comment by mbj2014** [comment]
nginx反向代理是不是要做到IIS和frp前面？即由nginx来监听80端口，根据域名的不同，分到IIS或者frep。这样公网服务器既可以自己做网站服务，又可以提供穿透内网发布Web？

这样原来的IIS主机头就不用了，而是由ngnix来实现？

**Comment by JimLee1996** [comment]
嗯嗯，非常对

**Comment by iscraft** [comment]
iis下已解决 @JimLee1996 谢谢 改天找nginx环境测试

**Comment by tt2014** [comment]
iis下是怎么解决的，我也遇到这个问题

**Comment by iscraft** [comment]
@tt2014 时间有点久 具体操作忘记了 是通过iis的url重写规则做的

**Comment by tt2014** [comment]
> @tt2014 时间有点久 具体操作忘记了 是通过iis的url重写规则做的

url重写规则具体是怎么填写参数，我弄的不成功，大佬方便详细讲下吗

**Comment by Thyiad** [comment]
@tt2014 老板搞定了没？因为我发现iis就算rewirte之后，还是只能通过frp绑定的端口访问，而不是80端口

**Comment by Thyiad** [comment]
搞定了，match规则里面正则验证{HTTP_HOST}，Rewrite Url配置成：
http://{C:0}:【frp端口】
就OK了
哎，nginx配置一条
proxy_set_header    Host            $host:80;
就行了，大把资料，IIS就是没啥用人，得多尝试，才搞清楚。
如果直接访问127.0.0.1，不属于指定的域名，访问会失败的。猜测nginx这是直接改变请求的Host，而IIS找不到这种配置，目测还是通过外网访问的HOST:【frp端口】

**Comment by chenjunyi88** [comment]
IIS的规则如下：			
                <rule name="r.mydoname.com" stopProcessing="false">
                    <match url="(.*)" />
                    <action type="Rewrite" url="http://{C:0}:8080/{R:1}" />
                    <conditions>
                        <add input="{HTTP_HOST}" pattern="^.*.r.mydoname.com$" />
                    </conditions>
                </rule>
@Thyiad 受你启发，http://{C:0}:【frp端口】后再加上/{R:1}，IIS的配置就完美了

**Comment by 1115284051** [comment]
> ```
> IIS的规则如下：			
>             <rule name="r.mydoname.com" stopProcessing="false">
>                 <match url="(.*)" />
>                 <action type="Rewrite" url="http://{C:0}:8080/{R:1}" />
>                 <conditions>
>                     <add input="{HTTP_HOST}" pattern="^.*.r.mydoname.com$" />
>                 </conditions>
>             </rule>
> ```
> 
> @Thyiad 受你启发，http://{C:0}:【frp端口】后再加上/{R:1}，IIS的配置就完美了

的确是这样

**Comment by Thyiad** [comment]
@chenjunyi88 @1115284051 我最终是这样配置的，比你们贴的更简洁，仅供参考：
```
<rule name="frp" stopProcessing="true">
    <match url=".*" />
    <action type="Rewrite" url="http://{HTTP_HOST}:7000{REQUEST_URI}" appendQueryString="false" />
</rule>
```
