### ISSUE TITLE
使用0.27.0版本的自定义404页面，404页面会按照txt解析出来，而不是html

### ISSUE THREAD

**Issue by ooiuv** [fatedier/frp#1240]
使用0.27.0版本的自定义404页面，404页面会按照txt解析出来，而不是html

就是把原本html页面的内容，完整的以文本格式展示出来了。

**Comment by ooiuv** [comment]
对比了自带404页面，发现html的head元素里面，没有加下面配置，所以造成以text打开！
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

**Comment by li-xunhuan** [comment]
emmmmmm
下面配置是啥配置啊？？

**Comment by ooiuv** [comment]
指定当前的页面是html 浏览器就会按照html的格式去解析

李寻欢 <notifications@github.com> 于2019年7月13日周六 上午9:28写道：

**Comment by qqq1162934083** [comment]
> 对比了自带404页面，发现html的head元素里面，没有加下面配置，所以造成以text打开！

没有加下面配置，到底是什么配置能方便说一下啊

**Comment by ooiuv** [comment]
就是字head里面声明html类型

qqq1162934083 <notifications@github.com> 于2020年2月22日周六 下午1:15写道：

**Comment by adi291** [comment]
同一个问题另一个原因。html是正确的，如果用notepad++这类编辑器，文件不能用utf-8 BOM 编码，必须用 utf-8 编码。
