### ISSUE TITLE
希望支持多服务器的负载均衡

### ISSUE THREAD

**Issue by jsjcjsjc** [fatedier/frp#1244]
希望可以增加多服务器的负载均衡,因为有时候一台服务器会挂掉,这样可以增加稳定性
感谢

**Comment by yi-ge** [comment]
可以同时部署两台服务器作为网关服务器，然后使用DNS做负载均衡临时解决。

**Comment by snowdream** [comment]
希望一台服务器也不会挂掉，或者挂掉会自动重连。

**Comment by fatedier** [comment]
可以通过冗余的部署来解决这个问题，比如多个 frpc 进程分别连接不同的 frps 服务。
