### ISSUE TITLE
关于服务端多IP问题

### ISSUE THREAD

**Issue by Sunser** [fatedier/frp#125]
bind_addr = 0.0.0.0 的话所有公网IP都可以访问就是有一个问题使用
./frps -c --reload 会提示无法访问http://0.0.0.0:7500/api 的错误，

请问关于服务端多IP如何处理且支持./frps -c --reload 命令

**Comment by fatedier** [comment]
执行命令后提示什么错误？

**Comment by Sunser** [comment]
frps reload error: Get http://0.0.0.0:7500/api/reload: dial tcp 0.0.0.0:7500: co
nnectex: The requested address is not valid in its context.

**Comment by fatedier** [comment]
在 centos 和 mac 上测试正常，你这个是 windows 环境的问题吧？
