### ISSUE TITLE
我发现使用FRP的SOCKS5插件无法支持FTP服务

### ISSUE THREAD

**Issue by Andxa** [fatedier/frp#1251]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.27

**What operating system and processor architecture are you using (`go env`)?**
WIN10_x6464

**Configures you used:**
[ss5]
type = tcp
remote_port = 6666
plugin = socks5
plugin_user = frp
plugin_passwd = 123456
use_encryption = true
use_compression = true

**Steps to reproduce the issue:**
1.直接用FRP创建任何一个SOCKS5代理，是否有密码或端口不影响结果。
2.使用支持SOCKS5的软件，例如Maxthon浏览器，配制好SOCKS5代理并访问www.ip.cn确认代理有效。
3.将同样的SOCKS5代理配置到FTP客户端，这里试了WINSCP、FLASHFXP、FileZilla并连接任意FTP站点。

**Describe the results you received:**
通过客户端日志发现，在获取文件列表这一步卡住，并且永远在这一步。进而导致无法下一步操作。

**Describe the results you expected:**
同样的FTP客户端软件选用其它第三方SOCSK5代理配置后发现并无此问题。

**Additional information you deem important (e.g. issue happens only occasionally):**
反复尝试后，大概有1/20的概率突然正常了。断开后再使用再次不正常。

**Can you point out what caused this issue (optional)**
猜测是SOCKS5代理后传递给FTP服务端的IP地址不对？

**Comment by fatedier** [comment]
frp 自带的 socks5 代理只是一个简单的版本，如果需要复杂的需求，还是建议使用其他更专业的 socks5 的代理工具。
