### ISSUE TITLE
 求助：怎么通过不同的虚拟目录访问内网不同的http服务

### ISSUE THREAD

**Issue by woniuyangwang** [fatedier/frp#1252]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.27.0

**What operating system and processor architecture are you using (`go env`)?**
windows arm64

**Configures you used:**

**Steps to reproduce the issue:**
1.当前frp通过设置子域名并进行泛解析来访问内部http服务，能否通过不同的虚拟目录来访问内部http服务？

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by keeno1982** [comment]
我也想知道，有答案了麻烦告知一下

**Comment by baomanxi** [comment]
nginx 代理啊

**Comment by woniuyangwang** [comment]
@baomanxi 感谢回复！主要是不太想再部署一个nginx，太麻烦了。如果在frp中实现就完美了！

**Comment by fatedier** [comment]
frp 是反向代理，不是 web 服务器。
