### ISSUE TITLE
Accept new mux stream error: broken pipe

### ISSUE THREAD

**Issue by wigginskuang** [fatedier/frp#1253]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frp_0.16.0_linux_amd64

**What operating system and processor architecture are you using (`go env`)?**
centos7

**Configures you used:**
[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 7000

[ssh5]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6003

**Steps to reproduce the issue:**
1.I did nothing
2.
3.

**Describe the results you received:**
网络无异常的情况下，客户端自动关闭连接

**Describe the results you expected:**
客户端不应该会自动断开连接

**Additional information you deem important (e.g. issue happens only occasionally):**
2019/05/17 00:36:19 [W] [service.go:247] Accept new mux stream error: broken pipe
2019/05/17 00:36:19 [W] [control.go:241] [db0809784cab3431] read error: broken pipe
2019/05/17 00:36:19 [I] [control.go:213] [db0809784cab3431] control writer is closing
2019/05/17 00:36:19 [I] [proxy.go:71] [db0809784cab3431] [ssh5] proxy closing
2019/05/17 00:36:19 [I] [proxy.go:117] [db0809784cab3431] [ssh5] listener is closed
2019/05/17 00:36:19 [I] [control.go:282] [db0809784cab3431] client exit success

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
这个日志表示网络异常。

**Comment by JX-Wang** [comment]
2019/11/10 19:32:25 [I] [proxy.go:192] [82f547da76ad7d3f] [ssh] tcp proxy listen port [6000]
2019/11/10 19:32:25 [I] [control.go:320] [82f547da76ad7d3f] new proxy [ssh] success
2019/11/10 19:33:16 [W] [service.go:247] Accept new mux stream error: broken pipe
2019/11/10 19:33:53 [W] [service.go:247] Accept new mux stream error: broken pipe
