### ISSUE TITLE
type 为 http和  type 为tcp 对于同样80端口的服务有啥区别吗？

### ISSUE THREAD

**Issue by duanzan** [fatedier/frp#1259]
我看 还有个 vhost port 8080 然后可以用域名 www.yourname.com:8080 访问 http类型的服务

那和 直接把 www.yourname.com A记录到frps服务器上 然后 浏览器 访问www.yourname.com:8080 这个被转发的tcp类型的服务    有啥区别呢

**Comment by fatedier** [comment]
没有太多的区别，vhost 是为了复用端口，包括提供针对 HTTP 协议的一些特殊能力。
