### ISSUE TITLE
如何用Windows  Service wrapper注册成服务运行？

### ISSUE THREAD

**Issue by mbj2014** [fatedier/frp#126]
这个需要用命令行方式启动，尝试用WSW注册成服务，但启动后报错意外终止。

还有没有停止运行的命令行。

WSW配置如下：
`<?xml version="1.0" encoding="UTF-8" ?>
<service>
  <id>frps</id>
  <name>frpServer</name>
  <description>frp内网发布服务</description>
  <executable>D:\VPN\frps.exe</executable>
  <logpath>D:\VPN\</logpath>
  <logmode>roll</logmode>
  <depend></depend>
  <startargument></startargument>
  <stopargument></stopargument>
</service>`

**Comment by chmis8000** [comment]
windows，请用 NSSM - the Non-Sucking Service Manager http://www.nssm.cc/
举例：
安装服务： nssm install frpc c:\Tools\frpc.exe
移除服务： nssm remove frpc
修改服务： nssm edit frpc
启动服务： nssm start frpc
停止服务：nssm stop frpc

**Comment by mbj2014** [comment]
谢谢！NSSM比WSW好用些，图形化配置界面的。

**Comment by lotc** [comment]
@chmis8000 frpc v1.2 win64 注册的服务好像会报错, 请问可以提供一下你设置的具体参数吗?
