### ISSUE TITLE
能否支持自动remote配置端口?

### ISSUE THREAD

**Issue by nkbai** [fatedier/frp#1263]
就像DHCP类似的工作原理
frpc.ini中
```
[ssh-meshboxcq]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = auto
```
1. remote_port配置为auto 
2.然后frps指定一段可用的端口,
3. frpc 向服务器请求的时候带上一个可以指定的id信息
4. 通过frps 对外暴露的服务查询,分配了哪些端口
5. frps可以根据配置文件建立静态绑定关系

**Comment by status301** [comment]
@nkbai 使用前请看文档
https://github.com/fatedier/frp/blob/master/README_zh.md
https://github.com/fatedier/frp/blob/master/conf/frpc_full.ini
```
[ssh_random]
type = tcp
local_ip = 127.0.0.1
local_port = 22
# if remote_port is 0, frps will assign a random port for you
remote_port = 0
```

**Comment by nkbai** [comment]
thanks, perfect! @status301
