### ISSUE TITLE
希望添加防火墙功能和来源ip记录

### ISSUE THREAD

**Issue by zhu-ty** [fatedier/frp#1264]
Issue is only used for submitting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
 0.25.3

**What operating system and processor architecture are you using (`go env`)?**
 Ubuntu16.04

**Configures you used:**

**Steps to reproduce the issue:**
1.2.3.
**Describe the results you received:**
**Describe the results you expected:**
**Additional information you deem important (e.g. issue happens only occasionally):**
**Can you point out what caused this issue (optional)**

This IS A FEATURE REQUEST:
1.希望能添加每个客户端自由配置的防火墙功能，比如一个frps下有两个frpc，每个frpc有自己的白名单iplist，只有该list的ip能通过frps访问这个frpc
2.frps的log我有点看不太懂……，似乎只写了frpc的ip而不是访问frps的ip，希望log能记录一下访问frps的源ip

近期感觉自己挂出来的windows 远程桌面有被黑客破解的大量记录（无数的重复connection），不知道怎么处置最为科学？我没有frps所在服务器的sudo权限，因此只能开端口，没有改路由表的权限……

**Comment by fatedier** [comment]
以后会考虑通过插件的方式来开放接入这些功能的能力，但是近期不会直接实现这样的功能。

**Comment by zhu-ty** [comment]
> 以后会考虑通过插件的方式来开放接入这些功能的能力，但是近期不会直接实现这样的功能。

好的，谢谢~

**Comment by sfsdacp19** [comment]
开放本地API就很强了啊，我倒是希望可以出一个修改默认404页面的插件

**Comment by 0312birdzhang** [comment]
最近发现不管是ssh还是rdp都被扫了，关键是看不到来源ip，相当尴尬

**Comment by ifu25** [comment]
> 最近发现不管是ssh还是rdp都被扫了，关键是看不到来源ip，相当尴尬

同样的问题，windows 系统日志中出现大量登录失败的记录，来源ip看着就想哭，全是 127.0.0.1~

**Comment by 0312birdzhang** [comment]
@ifu25 看看我的😂，准备用二步认证工具了

![图片](https://user-images.githubusercontent.com/1762041/77393894-06f0da00-6dd9-11ea-9218-48d13b971fcc.png)

**Comment by ifu25** [comment]
> @ifu25 看看我的😂，准备用二步认证工具了
> 
> ![图片](https://user-images.githubusercontent.com/1762041/77393894-06f0da00-6dd9-11ea-9218-48d13b971fcc.png)

哈哈，就是这个样子，有什么好用的工具分享下哈~

**Comment by fatedier** [comment]
服务端插件的功能已经开放，近期会基于插件的能力实现一个简单的防火墙的能力。
后续可以关注 https://github.com/gofrp/plugin 这个 repo。

**Comment by 0312birdzhang** [comment]
@ifu25 之前用duo security, 有时候网络不好二步认证弹不出来。现在也在找其他的方法。
或者曲线救国，用netstat -tn 找出尝试连接的ip，然后iptables drop掉。

**Comment by arugal** [comment]
![image](https://user-images.githubusercontent.com/26432832/78144869-c3464200-7462-11ea-8e6b-f8f7974bea47.png)

@fatedier 我在我fork的仓库上拓展了服务端插件, 支持记录访问代理的源IP, 截图中的TraceAccessIp就是通过我拓展的功能实现的。不知道对于你有没有意义？我可以发起一个合并请求reviewy一下代码 :)

**Comment by fatedier** [comment]
@arugal 欢迎贡献相关的代码，不过我们最好另外开一个 feature issue，经过充分讨论和设计后再开始编码，避免之后意见不一致需要频繁改动。

**Comment by arugal** [comment]
> @arugal 欢迎贡献相关的代码，不过我们最好另外开一个 feature issue，经过充分讨论和设计后再开始编码，避免之后意见不一致需要频繁改动。

好的，在这几天我会开一个相关的ISSUSE，描述以下大概的实现逻辑

**Comment by fatedier** [comment]
@arugal 如果可以的话，feature issue 尽量用英文，可以让更多的人参与进来。

**Comment by bearkr** [comment]
> > @ifu25 看看我的joy，准备用二步认证工具了
> > ![图片](https://user-images.githubusercontent.com/1762041/77393894-06f0da00-6dd9-11ea-9218-48d13b971fcc.png)
> 
> 哈哈，就是这个样子，有什么好用的工具分享下哈~

我使用的stcp方式，不存在你们说的问题！

**Comment by bearkr** [comment]
也可以试试frp的stcp方式加TV的LAN呼入，提高安全性和远程体验！

**Comment by xqzr** [comment]
> 开放本地API就很强了啊，我倒是希望可以出一个修改默认404页面的插件

https://github.com/fatedier/frp/blob/8668fef136baceacf974f7ef4859d108d413a42e/conf/frps_full.ini#L114

**Comment by rozbo** [comment]
mark， 今天同遇这个问题。静待进一步的解决方案

**Comment by busymx** [comment]
cat /var/log/frps.log | grep "get a user connection" | grep -v "127.0.0.1"

**Comment by LiuTianyouOnLuogu** [comment]
@fatedier 想问下防火墙这个问题解决了吗，是如何解决的

**Comment by LiuTianyouOnLuogu** [comment]
我可以用fail2ban生成一个IP禁止列表，问题是能否直接禁止某个IP访问

**Comment by kgggggb** [comment]
> 也可以试试frp的stcp方式加TV的LAN呼入，提高安全性和远程体验！

增加个锤子远程体验，我移动端不要用吗😅
