### ISSUE TITLE
[Feature Request] Adding tracking and saving of all traffics logging info on frps server

### ISSUE THREAD

**Issue by jerrychong25** [fatedier/frp#1265]
Hi all,

I would like to check is it possible to add tracking and saving of all traffics logging into **frps** server?

When there is public coming to **frps** server, then **frps** server save these traffics information with additional parameters:
-Country
-Device IP
-Device Category (PC or Mobile)
-Device Brand (Apple, Huawei, etc)
-Device Model (iPhone 5s)
-OS Version
-Language

After logging, user could easily review traffic history for past 7 days via browser.

If this features is not available very soon, could advise any alternatives library on this?

Thanks.

**Comment by fatedier** [comment]
You mean TCP or HTTP traffic ?

I think nginx or other proxy is good at doing this.

**Comment by jerrychong25** [comment]
> You mean TCP or HTTP traffic ?
> 
> I think nginx or other proxy is good at doing this.

I mean HTTP traffic.

**Comment by fatedier** [comment]
Try to do what you what with nginx before frp.
