### ISSUE TITLE
websocket 如何配置

### ISSUE THREAD

**Issue by zjxpcyc** [fatedier/frp#1266]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.21.0

**What operating system and processor architecture are you using (`go env`)?**

没有 go

**Configures you used:**

frps.ini

```[common]
bind_port = 7000
vhost_http_port = 8001
```

frpc.ini

```
[common]
server_addr = x.x.x.x
server_port = 7000
protocol = websocket

[yansen-wss]
type = tcp
local_port = 8080
custom_domains = pawoma
locations = /wx/chat
remote_port = 55555
```

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
websocket 正常

**Describe the results you expected:**
报错  501

**Additional information you deem important (e.g. issue happens only occasionally):**

no

**Can you point out what caused this issue (optional)**

no

**Comment by fatedier** [comment]
不需要任何配置，如果有异常，请先检查自身的服务。
