### ISSUE TITLE
修改issue模板以隐藏注释

### ISSUE THREAD

**Issue by Milokita** [fatedier/frp#1268]
在原issue模板下会显示以下内容：
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
但是通过添加
`

`
则不会最终显示

**Comment by fatedier** [comment]
这个问题不大，鉴于经常有人看不到，多展示一些也好。
