### ISSUE TITLE
如何把客户IP地址转发给frp后面的网站？

### ISSUE THREAD

**Issue by mbj2014** [fatedier/frp#127]
因为是代理机制，所以有没有什么办法可以让后台程序可以拿到客户端IP？

**Comment by fatedier** [comment]
目前还不能，不过 http 的话可以考虑通过 header 字段的 X-Forwarded-For 和 x-real-ip 来传递这些信息。

**Comment by yydcool** [comment]
越来越像Nginx了

**Comment by fatedier** [comment]
应该是越来越像一个反向代理了。

**Comment by xhinker** [comment]
@fatedier http 拿不到ip 地址，那么tcp 呢? response 是怎么知道 返回给那个ip 地址的呢
