### ISSUE TITLE
frpc启动就panic

### ISSUE THREAD

**Issue by ssqf** [fatedier/frp#1270]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
版本：0.24.1

**What operating system and processor architecture are you using (`go env`)?**
使用环境：arm  linux   树莓派3B+

**Configures you used:**
配置文件：
![image](https://user-images.githubusercontent.com/13485967/58632195-7f048580-8317-11e9-9e51-064f465750c9.png)

**Steps to reproduce the issue:**
1.一直正常使用三五个月了，突然发现这个问题。
2. 有30+个设备正常使用，就这一个有问题，执行文件和配置文件是直接打包进img中的，所有都是相同的
3. 异常崩溃会用go supervisord 重新拉起，不知道什么时候发生的，全是相同的错误日志，最终发生问题时日志已经找不到

**Describe the results you received:**

错误日志如下：

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

goroutine 1 [running]:
encoding/json.(*decodeState).object(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/wcl/.gvm/gos/go1.11.4/src/encoding/json/decode.go:741 +0x320
runtime: unexpected return pc for github.com/fatedier/frp/vendor/github.com/fatedier/beego/logs.init called from 0x0
stack: frame={sp:0x1c7b0b4, fp:0x1c7b108} stack=[0x1c7a000,0x1c7b000)

**Describe the results you expected:**
可正常远程访问定义的web页面，并通过mac地址区分不同设备

**Additional information you deem important (e.g. issue happens only occasionally):**
1. 手动执行依旧报错
2. 执行 frpc --version都会出错
3. 重启树莓派单板依旧出错

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
panic 日志能再多提供一些吗

**Comment by fatedier** [comment]
看起来可能还不是代码问题，是系统问题，或者也有可能是 go 程序的处理在你这台机器上有问题。

你可以尝试更新版本来测试下是否仍然有问题。

**Comment by ssqf** [comment]
@fatedier 
日志内容是相同的，就那段一直在重复
这个问题现在就出现一例，我同时升级go版本和frp的版本试试

**Comment by wsgfz** [comment]
我在AC86U上也出现了类似的问题, 但我重新换了frpc执行文件就好了, 但这两个执行文件都是0.27.0, 从同一个地方下的, md5也一样... 但mv frpc frpc.bak后, 重新wget... 居然就好了

**Comment by funnypro** [comment]
> 我在AC86U上也出现了类似的问题, 但我重新换了frpc执行文件就好了, 但这两个执行文件都是0.27.0, 从同一个地方下的, md5也一样... 但mv frpc frpc.bak后, 重新wget... 居然就好了

那么文件能保证完全一致吗？

**Comment by wsgfz** [comment]
MD5摘要是一样的
应该就是一样的吧


是很奇怪



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 滑稽Pro <notifications@github.com&gt;
发送时间: 2019年10月22日 20:55
收件人: fatedier/frp <frp@noreply.github.com&gt;
抄送: wsgfz <wsgfz@foxmail.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[fatedier/frp] frpc启动就panic (#1270)



 
我在AC86U上也出现了类似的问题, 但我重新换了frpc执行文件就好了, 但这两个执行文件都是0.27.0, 从同一个地方下的, md5也一样... 但mv frpc frpc.bak后, 重新wget... 居然就好了
  
那么文件能保证完全一致吗？
