### ISSUE TITLE
custom_404_page

### ISSUE THREAD

**Issue by liangguohun** [fatedier/frp#1278]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

v0.27.0

**What operating system and processor architecture are you using (`go env`)?**

centos 7.3

**Configures you used:**

**Steps to reproduce the issue:**
1.  404页面能正常提示，但是显示的是html文本在浏览器上不是编写的页面

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
