### ISSUE TITLE
[建议]UDP能不能做类似STCP的功能

### ISSUE THREAD

**Issue by WolfCanglong** [fatedier/frp#1280]
有时候UDP也有需要穿透又不直接暴露的安全需求，能否做个类似stcp的sudp呢？十分感谢

另外UDP的例子我觉得真的可以改进下，用了很久一直以为是不支持UDP的后来看到https://github.com/fatedier/frp/issues/1182 说的认真想了一阵 才反应过来原来是可以的，主要是虽然例子本身是对的而且方便测试，但举的谷歌给人第一眼的感觉是反过来用服务器代理，像我这种沙雕网友有时候脑子会转不过来，或者
通过 dig 测试 UDP 包转发是否成功，预期会返回 www.google.com 域名的解析结果
改成
通过 dig 测试 UDP 包转发是否成功，预期会通过客户端机器查询并返回 www.google.com 域名的解析结果

建议可以用SNMP作例子 虽然这玩意用的人少但是感觉用来举例会清晰点而且实际确实有这个用途

比如这样
服务端
#frps.ini
[common]
bind_port = 7000

客户端
#frpc.ini
[common]
server_addr = 服务器ip
server_port = 7000

[snmp]
type = udp
local_ip = 内网snmp设备ip
local_port = 161
remote_port = 161

连接服务端ip:161即可访问内网snmp设备

**Comment by anythinging** [comment]
远程端

**Comment by anythinging** [comment]
如果实现类似stcp的sudp用处很大，希望能以后支持。
如远程端通过frpc端连接到server后，才能访问frps端的服务器udp端口，理论上更加安全。

**Comment by jiangzhou9** [comment]
使用过程中出现运营商屏蔽udp现象，sudp作用很大，自己根据stcp代码尝试修改了下，但无奈本身不会go，最后在修改proxy.go的时候出现很多问题，忘大佬对该功能多上心。

**Comment by zphiliam** [comment]
刚好我也有这个需求
- sudp 功能
- 就是udp 能像 stcp 一样安全暴露端口
- 感谢大佬 ！

**Comment by lazy-luo** [comment]
@zphiliam sudp容易被Qos，可以参考我的方案

**Comment by QQ2017** [comment]
原来有人提过了，顶一下~

**Comment by wyaode** [comment]
支持一下，也有这个需求！

**Comment by bingtianbaihua** [comment]
基本功能实现了， 需要再系统性的测试一下。

**Comment by bingtianbaihua** [comment]
@WolfCanglong 可以拉下我的 pr， 出个包去测试一下，看看能不能满足你的需求。
