### ISSUE TITLE
Dynamic linking error with -linkshared.

### ISSUE THREAD

**Issue by TesleYoung** [fatedier/frp#1282]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
panic: runtime error: slice bounds out of range

goroutine 1 [running]:cmd/go/internal/load.(*Package).load(0xc0001cc480, 0xc00012d970, 0xc000243880, 0x0, 0x0)

run ./package.sh

**What version of frp are you using (./frpc -v or ./frps -v)?**
version:v0.27.0.tar.gz

**What operating system and processor architecture are you using (`go env`)?**
GOARCH="arm"
GOBIN=""
GOCACHE="/home/tesle/frp/frp/.go_work/cache"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tesle/frp/frp/.go_work/build"
GOPROXY=""
GORACE=""
GOROOT="/home/tesle/go-cross"
GOTMPDIR="/home/tesle/frp/frp/.go_work/tmp"
GOTOOLDIR="/home/tesle/go-cross/pkg/tool/linux_amd64"
GCCGO="gccgo"
GOARM="5"
CC="arm-linux-gcc"
CXX="arm-linux-g++"
CGO_ENABLED="0"
GOMOD="/home/tesle/frp/frp-0.27.0/go.mod"
CGO_CFLAGS="-Os -pipe -mno-branch-likely -shared -fPIC"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -fmessage-length=0 -fdebug-prefix-map=/home/tesle/apps/frp/frp/.go_work/tmp/go-build928933629=/tmp/go-build -gno-record-gcc-switches"

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
Please send PR to [golang](https://github.com/golang/go) repo, not frp.
