### ISSUE TITLE
端口数据多路复用

### ISSUE THREAD

**Issue by zhangchuan6000** [fatedier/frp#1286]
我将一个摄像头的rtsp端口映射到了我的服务器,通过访问主站端口能够直接实现视频查看.

现在遇到了一个问题,每多存在一个用户访问该摄像头时,frpc的负载就会升高一些,我在想是否可以增加端口类型,使端口支持数据复用,只需要在服务端进行数据转发即可.

**Comment by fatedier** [comment]
只有 http 支持复用端口，其他协议不支持。
