### ISSUE TITLE
same port different domain (vhost)

### ISSUE THREAD

**Issue by adisis** [fatedier/frp#1287]
I'm using frps & frpc version 0.23.1 on linux Ubuntu AMD64
I'm curious is it possible to use single bind http/https port to serve many domain --> vhost ?

**Comment by fatedier** [comment]
https://github.com/fatedier/frp#visit-your-web-service-in-lan-by-custom-domains

**Comment by adisis** [comment]
my point is many domain (not only single domain), is it possible to address many domain into single client ? 

custom_domains = www.yourdomain.com, example.com, xyz.com

**Comment by walejandromt** [comment]
if need multiple custom_domains and subdomains same:

![image](https://github.com/fatedier/frp/assets/14278594/523ef8e4-d138-40b2-9f6c-14dcb8699cad)

frpc.ini
```xml
[web-myhost-http]
type = http
local_ip = {{ .Envs.HTTP_LOCAL_IP }}
local_port = {{ .Envs.HTTP_LOCAL_PORT }}
custom_domains = myhost.com,domains.com

[www-web-http]
type = http
local_ip = {{ .Envs.HTTP_LOCAL_IP }}
local_port = {{ .Envs.HTTP_LOCAL_PORT }}
subdomain = www
```

i need conecte with [www.myhost.com](www.myhost.com) and [www.domains.com](www.domains.com), is it possible?
