### ISSUE TITLE
How to configure frpc.ini if my VPS without domains?

### ISSUE THREAD

**Issue by NightMarcher** [fatedier/frp#1288]
Version: 0.27.0

I got a web server within LAN, which is wanted to be accessed from outer network. I deployed frps on my vps without domains. It can be connected by frpc on my web server, but not correctly.

If custom_domains and subdomain were not set, `custom_domains and subdomain should set at least one of them` will be raised. If I set any of them, when I browse `x.x.x.x:8080` (server_addr:vhost_http_port) in chrome, I got `[W] [http.go:223] http: proxy error: no such domain: x.x.x.x`.

So if my VPS without domains, frp cannot work? I am confused, please help!

**Comment by fatedier** [comment]
Use type `tcp`.

Or set `custom_domains = { server_addr }`.

**Comment by NightMarcher** [comment]
Problem solved, mush appreciated!

**Comment by ihmc3jn09hk** [comment]
Setting the domain to the server ip is not working, e.g. `custom_domains = 1.1.1.1`.
Any help ?
