### ISSUE TITLE
Windows身份认证的网站不能登录

### ISSUE THREAD

**Issue by mbj2014** [fatedier/frp#129]
内网的网站是用AD身份认证的，通过frp暴露出去后，填写用户名密码正确也一样无法通过验证。

**Comment by fatedier** [comment]
不了解什么是 AD 身份认证，windows 不熟，你可以自行研究下...

**Comment by tanshanli** [comment]
> 内网的网站是用AD身份认证的，通过frp暴露出去后，填写用户名密码正确也一样无法通过验证。

我也遇到了一样的问题，如果网站需要windows验证，就登录不上去，你这边解决了没？还是说无解？

**Comment by tanshanli** [comment]
> > 内网的网站是用AD身份认证的，通过frp暴露出去后，填写用户名密码正确也一样无法通过验证。
> 
> 我也遇到了一样的问题，如果网站需要windows验证，就登录不上去。
> 
> @fatedier 我看问题已经过去很久了，我目前用最新版本（frp_0.39.1）好像也不行。不知道这个问题是否有解？


映射后的网站是可以打开的，只是登录无法成功（网站用的是windwos身份认证）
