### ISSUE TITLE
tcp转发实现ip:port访问内网web方式出现login to server failed : EOF

### ISSUE THREAD

**Issue by Retrochet** [fatedier/frp#1295]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.21 (both)  

**What operating system and processor architecture are you using (`go env`)?**
debian 9  

**Configures you used:**
frps  
```
[common]
bind_port = 7000
token = fdasfse343rw35t3ew2rffsd3
```
frpc  
![pic](https://i.loli.net/2019/06/25/5d1228fb82ef238171.png)

**Describe the results you received:**
login to server failed  
login to server failed: dial tcp ip:7000: connect: connection refused  
**Describe the results you expected:**
使用tcp转发实现ip:port访问内网web
**Additional information you deem important (e.g. issue happens only occasionally):**
systemctl status frps显示正常云行

**Comment by Retrochet** [comment]
亦尝试使用tcp转发实现ip:port访问内网web

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.21 (both)  

**What operating system and processor architecture are you using (`go env`)?**
debian 9  

**Configures you used:**
frps  
```
[common]
bind_port = 7000
token = fdasfse343rw35t3ew2rffsd3
```
frpc  
![pic](https://i.loli.net/2019/06/25/5d1224f08f16e96081.png)

**Describe the results you received:**
错误依旧存在
login to server failed  
login to server failed: dial tcp 188.119.64.98:7000: connect: connection refused

**Comment by chavyleung** [comment]
表示遇到同样问题，dashboard显示client已经连接上
client端每隔几秒种打印：
```
work connection closed, EOF
control writer is closing
try to reconnect to server...
login to server success, get run id [xxxxxxxxxx], server udp port [0]
```

**Comment by fatedier** [comment]
`login to server failed: dial tcp ip:7000: connect: connection refused` 表示对端 7000 端口没有监听。

**Comment by chavyleung** [comment]
@fatedier 老大，二楼的问题有解吗？同样的client端在我pc上（连公司的网络）能正常运行
所以配置上应该不存在问题，但一旦放在放在公司的服务器运行，就是无限重复打印这段日志：
```bash
work connection closed, EOF
control writer is closing
try to reconnect to server...
login to server success, get run id [xxxxxxxxxx], server udp port [0]
```

**Comment by chavyleung** [comment]
`version:0.27.0`

`client`
```ini
[common]
server_addr = xx.xx.com
server_port = 7000
token = xx.com

[mstsc_214]
type = tcp
local_ip = 0.0.0.0
local_port = 3389
remote_port = 50001
custom_domains = xx.xx.xx.com
```

`server`
```bash
[common]
bind_addr = 0.0.0.0
bind_port = 7000
kcp_bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
token = xx.com

dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = xx
```

**Comment by ZehuanZhang** [comment]
我也遇到了这种问题，服务器和客户端的版本均为0.27.0，部分局域网段客户端可以正常连接，但在校区内部的局域网，无论centos、ubuntu和windows，均无法正常与服务端建立连接，返回错误：
[W] [service.go:82] login to server failed: EOF

**Comment by fatedier** [comment]
不明原因的情况下被断开连接，一般是你的网络环境问题，比如 frp 相关的内容被屏蔽了。

建议可以尝试多换一些协议，protocol 可以为 tcp、 kcp 或者 websocket。然后 frpc 还可以通过 http proxy 或 socks5 proxy 连接 frps。
