### ISSUE TITLE
多客户端连接同一服务端问题

### ISSUE THREAD

**Issue by yqhwd** [fatedier/frp#1296]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.27.0

**What operating system and processor architecture are you using (`go env`)?**
CentOs6.5

**Configures you used:**
[root@iz8vb7e9cy868xk3zcbs8bz frp]# cat frps.ini
# frps.ini
[common]
bind_port = 7000
vhost_http_port = 7080
vhost_https_port = 443
# dashboard 用户名密码，默认都为 admin
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = XXXXXXXXXX

log_file = /frp/log/frps.log
log_level = trace
log_max_days = 60

privilege_token = kysoftadmin123

max_pool_count = 100
authentication_timeout = 0
subdomain_host = dlkysoft.cn

客户端配置
[common]
server_addr = XXX.XXX.XXX.XXX
server_port = 7000

log_file = frpc.log
log_level = trace
log_max_days = 60

privilege_token = XXXXXXXXXXXX

pool_count = 30

#通过自定义域名访问部署于内网的 web 服务
[web-180-nksp180]
type = http
local_ip = 192.168.5.180
local_port = 8081
#custom_domains 不能重复
subdomain = nksp180
custom_domains = nksp180
use_encryption = true
use_compression = true

**Steps to reproduce the issue:**
1.有多台客户端连接到同一个服务端，客户端配置模式都一样
2.有两个客户端机器能成功连接到服务端HTTP服务，能成功穿透到客户端机器。但是第三个服务端同样连接服务端HTTP服务，服务端日志能显示正常连接，但是不能穿透
3.

**Describe the results you received:**
穿透失败

**Describe the results you expected:**
穿透成功

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
请先自行定位问题再提 issue。
