### ISSUE TITLE
服务端支持配置多个 token 

### ISSUE THREAD

**Issue by HydrogenPan19** [fatedier/frp#1298]
希望服务端支持配置多个 token ，这样可以比较自由管理客户端

因为有时需要临时给别人用，现在事后无法限制，更换 token 话，全部的客户端配置都得更改。

**Comment by status301** [comment]
你可以再给他起一个临时的frps，全默认不带token都可以，他用完直接杀进程。ps:多token和多用户貌似要自己二次开发，作者不支持。

**Comment by funnypro** [comment]
用systemd带@的
