### ISSUE TITLE
是否可以集成 dog-tunnel 他们已经做了打洞，但不支持压缩

### ISSUE THREAD

**Issue by chmis8000** [fatedier/frp#130]
狗洞： https://github.com/vzex/dog-tunnel
我windows 服务端、远端、近端 测试ok，只是他们不支持压缩

**Comment by fatedier** [comment]
你去给这个项目提 issue 加入压缩的功能要更方便一些。

**Comment by chmis8000** [comment]
不是的，frp优势是 客户端直接访问中转服务器，客户端无需安装程序。而p2p的，要求客户端也装，就限制了某些使用场景。若都能支持就好了

**Comment by fatedier** [comment]
因为这两种方式的原理不同，即使都支持也很难完美的结合在一起，如果你有需求可以同时使用 frp 和 dog-tunnel。对于 frp 来说，这个功能的优先级不是很高，因为限制比较多，会受到 NAT 类型，防火墙等等的影响，比如有的防火墙会只允许对外的 tcp 连接，udp 包就无法通过。
