### ISSUE TITLE
使用stcp安全地暴露内网服务方式时，被访问端能否同时支持多个端口让访问端连接？

### ISSUE THREAD

**Issue by anythinging** [fatedier/frp#1303]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frps,frpc 0.27

**What operating system and processor architecture are you using (`go env`)?**
win7

**Configures you used:**
# frpc.ini被访问端
[common]
server_addr = 192.168.11.21
server_port = 7000
token= abcdefg

[test21]
type = stcp
sk = abcdefg
local_ip = 127.0.0.1
local_port = 21

[test20]
type = stcp
sk = abcdefg
local_ip = 127.0.0.1
local_port = 20

# frpc.ini访问端
[common]
server_addr = 192.168.11.21
server_port = 7000
token= abcdefg

[ftp21]
type = stcp
role = visitor
server_name =test21
sk = abcdefg
bind_addr = 127.0.0.1
bind_port = 21

[ftp20]
type = stcp
role = visitor
server_name = test20
sk = abcdefg
bind_addr = 127.0.0.1
bind_port = 20

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by anythinging** [comment]
我在测试连接ftp时不能成功连接到ftp server。

**Comment by anythinging** [comment]
还有一个建议，能否支持类似stcp的sudp方式，有些程序连接时需要tcp和udp端口同时都可被访问。

**Comment by fatedier** [comment]
不能支持，需要自行配置多个端口。
