### ISSUE TITLE
FRPC Proxy 出现高CPU卡死现象

### ISSUE THREAD

**Issue by musicking** [fatedier/frp#1305]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.26.0

**What operating system and processor architecture are you using (`go env`)?**
CentOS release 6.5 (Final)

**Configures you used:**
Server：
[common]
bind_port = 6xxx
vhost_http_port = 80
Client：
[common]
server_addr = ***.***.***.***
server_port = 6xxx

[http_proxy]
type = tcp
remote_port = 2xxxx
plugin = http_proxy

**Steps to reproduce the issue:**
1.正常启动运行一段时间
2.服务突然连接不上
3.

**Describe the results you received:**
运行一段时候后，服务连接失败。
服务器负载：
![4G S$1UD6I7D{ANKD A(7KD](https://user-images.githubusercontent.com/8167146/60655760-e797d280-9e80-11e9-8adf-66cbcf0bfda6.png)
输出的日志:

![09A57UHO2)@V3MRX APEQ J](https://user-images.githubusercontent.com/8167146/60655921-22016f80-9e81-11e9-888b-1486994170e8.png)

查看打开文件：
# lsof -p 14598

![)ZC0HT9}` A 7J3V@V18QI](https://user-images.githubusercontent.com/8167146/60656085-6bea5580-9e81-11e9-9c4a-1c11d1c48096.png)

出现这个情况后必须重启服务端才恢复正常！

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

高并发下代理必触发！

**Can you point out what caused this issue (optional)**

**Comment by ai371908858** [comment]
到同样的问题，版本是最新的0.27.0,如果楼主解决后，麻烦分享一下

**Comment by musicking** [comment]
@ai371908858 我也解决不了，等作者看看吧！

**Comment by ai371908858** [comment]
> @ ai371908858我也解决不了，等作者看看吧！

你主机上有没有安装过宝塔面板？会不会是面板的坑？

**Comment by musicking** [comment]
@ai371908858 没有的！

**Comment by yekai1024** [comment]
遇到同样的问题，grep -i error frps.log 结果如下

> frps.2019-12-22.log:2019/12/22 16:59:09 [W] [http.go:223] http: proxy error: context canceled
> frps.2019-12-22.log:2019/12/22 16:59:09 [W] [http.go:223] http: proxy error: context canceled
> frps.2019-12-22.log:2019/12/22 16:59:09 [W] [http.go:223] http: proxy error: context canceled
> frps.2019-12-22.log:2019/12/22 16:59:09 [W] [http.go:223] http: proxy error: context canceled
> frps.2019-12-22.log:2019/12/22 16:59:09 [W] [http.go:223] http: proxy error: context canceled
> frps.2019-12-22.log:2019/12/22 16:59:09 [W] [http.go:223] http: proxy error: context canceled
