### ISSUE TITLE
【make error】- (*Cipher).XORKeyStream redeclared in this block 

### ISSUE THREAD

**Issue by Mason613** [fatedier/frp#1306]
60 $> go version
go version go1.12.5 linux/amd64
root@admin ~/go-project/frp  15:37:06
61 $> make
go fmt ./...
go build -o bin/frps ./cmd/frps
# runtime
/usr/local/go/src/runtime/lfstack_amd64.go:16:6: lfstackPack redeclared in this block
	previous declaration at /usr/local/go/src/runtime/lfstack_64bit.go:41:45
/usr/local/go/src/runtime/lfstack_amd64.go:20:6: lfstackUnpack redeclared in this block
	previous declaration at /usr/local/go/src/runtime/lfstack_64bit.go:48:33
/usr/local/go/src/runtime/map.go:65:2: bucketCntBits redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:64:18
/usr/local/go/src/runtime/map.go:66:2: bucketCnt redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:65:23
/usr/local/go/src/runtime/map.go:77:2: maxKeySize redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:74:17
/usr/local/go/src/runtime/map.go:78:2: maxValueSize redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:75:17
/usr/local/go/src/runtime/map.go:83:2: dataOffset redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:83:4
/usr/local/go/src/runtime/map.go:94:2: evacuatedX redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:91:19
/usr/local/go/src/runtime/map.go:95:2: evacuatedY redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:92:19
/usr/local/go/src/runtime/map.go:96:2: evacuatedEmpty redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:90:19
/usr/local/go/src/runtime/map.go:96:2: too many errors
# crypto/rc4
/usr/local/go/src/crypto/rc4/rc4_asm.go:13:18: (*Cipher).XORKeyStream redeclared in this block
	previous declaration at /usr/local/go/src/crypto/rc4/rc4.go:61:6
make: *** [frps] 错误 2

**go1.12.5 linux/amd64  报错
go1.12.1 linux/amd64 却成功了**

**Comment by fatedier** [comment]
请自行解决 golang 编译相关问题，和此项目无关。
