### ISSUE TITLE
隔一段时间会自动掉线，不知道为什么，求大神指导。。。。

### ISSUE THREAD

**Issue by jobsgxx** [fatedier/frp#1307]
2019/06/20 13:04:51 [I] [control.go:246] [86a0362b4732b036] login to server success, get run id [86a0362b4732b036], server udp port [7001]
2019/06/20 13:04:51 [I] [control.go:169] [86a0362b4732b036] [tcp_port1_0] start proxy success
2019/06/20 13:04:51 [I] [control.go:169] [86a0362b4732b036] [tcp_port1_1] start proxy success
2019/06/20 13:04:51 [I] [control.go:169] [86a0362b4732b036] [tcp_port1_2] start proxy success
2019/06/20 13:04:51 [I] [control.go:169] [86a0362b4732b036] [tcp_port1_3] start proxy success
2019/06/20 13:05:31 [I] [control.go:308] [86a0362b4732b036] control writer is closing
2019/06/20 13:05:31 [I] [control.go:407] [86a0362b4732b036] try to reconnect to server...
2019/06/20 13:05:31 [E] [control.go:152] [86a0362b4732b036] work connection closed, EOF
2019/06/20 13:05:31 [E] [control.go:152] [86a0362b4732b036] work connection closed, EOF
2019/06/20 13:05:31 [E] [control.go:152] [86a0362b4732b036] work connection closed, EOF
2019/06/20 13:05:31 [E] [control.go:152] [86a0362b4732b036] work connection closed, EOF
2019/06/20 13:05:31 [E] [control.go:152] [86a0362b4732b036] work connection closed, EOF

**Comment by vritser** [comment]
看日志是 frps 挂掉了， 可以起个daemon，或者使用docker image

**Comment by jobsgxx** [comment]
> 看日志是 frps 挂掉了， 可以起个daemon，或者使用docker image: https://hub.docker.com/r/vritser/frps

之前用的是kcp协议，后来非常不稳定就用了tcp，稍微好点了，但是看日志记录，还是存在这个问题。我之前用的是docker，现在改成了官方命令启动了，还在观察中。。。。

**Comment by wwqgtxx** [comment]
在我的移动宽带下出现过类似情况，将配置文件中的启用加密打开之后就稳定了，而在电信宽带下就无该问题，具体原因不明

**Comment by jobsgxx** [comment]
> 在我的移动宽带下出现过类似情况，将配置文件中的启用加密打开之后就稳定了，而在电信宽带下就无该问题，具体原因不明

我的就是在移动快带下出现这个情况的，加密也启用了但是还是很不稳定！

**Comment by jobsgxx** [comment]
@fatedier  观察了一段时间，目前还是会出现掉线不稳定的情况，能够优化做个类似ping的探测之类模块，能够解决中间网络传输问题？

**Comment by jobsgxx** [comment]
@fatedier 
2019/07/11 08:26:56 [I] [control.go:274] [112383f4b813a6fe] control writer is closing
2019/07/11 08:26:56 [I] [proxy.go:69] [112383f4b813a6fe] [tcp_port5_0] proxy closing
2019/07/11 08:26:56 [I] [proxy.go:135] [112383f4b813a6fe] [tcp_port5_0] listener is closed
2019/07/11 08:26:56 [I] [control.go:350] [112383f4b813a6fe] client exit success
2019/07/11 08:27:00 [I] [control.go:274] [bb5a05a01597f29e] control writer is closing
2019/07/11 08:27:00 [I] [proxy.go:69] [bb5a05a01597f29e] [tcp_port1_1] proxy closing
2019/07/11 08:27:00 [I] [proxy.go:135] [bb5a05a01597f29e] [tcp_port1_1] listener is closed
2019/07/11 08:27:00 [I] [proxy.go:69] [bb5a05a01597f29e] [tcp_port1_2] proxy closing
2019/07/11 08:27:00 [I] [proxy.go:135] [bb5a05a01597f29e] [tcp_port1_2] listener is closed
2019/07/11 08:27:00 [I] [proxy.go:69] [bb5a05a01597f29e] [tcp_port1_3] proxy closing
2019/07/11 08:27:00 [I] [proxy.go:135] [bb5a05a01597f29e] [tcp_port1_3] listener is closed
2019/07/11 08:27:00 [I] [proxy.go:69] [bb5a05a01597f29e] [tcp_port1_0] proxy closing
2019/07/11 08:27:00 [I] [proxy.go:135] [bb5a05a01597f29e] [tcp_port1_0] listener is closed
2019/07/11 08:27:00 [I] [control.go:350] [bb5a05a01597f29e] client exit success
2019/07/11 08:27:06 [I] [control.go:274] [43f670e0cbb041a3] control writer is closing
2019/07/11 08:27:06 [I] [proxy.go:69] [43f670e0cbb041a3] [tcp_port6_0] proxy closing
2019/07/11 08:27:06 [I] [proxy.go:135] [43f670e0cbb041a3] [tcp_port6_0] listener is closed
2019/07/11 08:27:06 [I] [control.go:350] [43f670e0cbb041a3] client exit success

**Comment by fatedier** [comment]
网络问题还是自行想其他解决方案，每个项目都有自己的侧重点，可以尝试结合其他项目解决。

另外，试试 `protocol = websocket`，如果不行就不行了，不用再继续在这里提了。

**Comment by jobsgxx** [comment]
> 网络问题还是自行想其他解决方案，每个项目都有自己的侧重点，可以尝试结合其他项目解决。
> 
> 另外，试试 `protocol = websocket`，如果不行就不行了，不用再继续在这里提了。

好的，我再试试，感谢！！

**Comment by jobsgxx** [comment]
> 网络问题还是自行想其他解决方案，每个项目都有自己的侧重点，可以尝试结合其他项目解决。
> 
> 另外，试试 `protocol = websocket`，如果不行就不行了，不用再继续在这里提了。

@fatedier  大神，想咨询一下，FRP自带的有重连机制吗？如果发生断开多久会重连？这个重连机制时间是否能够修改？如何修改？

**Comment by fatedier** [comment]
有，可以搜以前的 issue。

**Comment by laoyao11** [comment]
和楼主有一样的问题，要按回车才可以重新连接

**Comment by jobsgxx** [comment]
> 有，可以搜以前的 issue。

@fatedier  大神，我收了一下貌似没看到有类似重连机制的设置？下面是调整为websocket之后也报错。有方法排查是什么原因吗？
2019/07/13 09:45:59 [I] [control.go:274] [0d181298512fc597] control writer is closing
2019/07/13 09:45:59 [I] [proxy.go:69] [0d181298512fc597] [tcp_port5_0] proxy closing
2019/07/13 09:45:59 [I] [proxy.go:135] [0d181298512fc597] [tcp_port5_0] listener is closed
2019/07/13 09:45:59 [I] [control.go:350] [0d181298512fc597] client exit success
2019/07/13 09:46:11 [I] [control.go:274] [d2a78885c18c7bab] control writer is closing
2019/07/13 09:46:11 [I] [proxy.go:69] [d2a78885c18c7bab] [tcp_port1_0] proxy closing
2019/07/13 09:46:11 [I] [proxy.go:135] [d2a78885c18c7bab] [tcp_port1_0] listener is closed
2019/07/13 09:46:11 [I] [proxy.go:69] [d2a78885c18c7bab] [tcp_port1_1] proxy closing
2019/07/13 09:46:11 [I] [proxy.go:135] [d2a78885c18c7bab] [tcp_port1_1] listener is closed
2019/07/13 09:46:11 [I] [proxy.go:69] [d2a78885c18c7bab] [tcp_port1_2] proxy closing
2019/07/13 09:46:11 [I] [proxy.go:135] [d2a78885c18c7bab] [tcp_port1_2] listener is closed
2019/07/13 09:46:11 [I] [proxy.go:69] [d2a78885c18c7bab] [tcp_port1_3] proxy closing
2019/07/13 09:46:11 [I] [proxy.go:135] [d2a78885c18c7bab] [tcp_port1_3] listener is closed
2019/07/13 09:46:11 [I] [control.go:350] [d2a78885c18c7bab] client exit success
2019/07/13 09:46:12 [I] [control.go:274] [d5b81d54e6513e73] control writer is closing
2019/07/13 09:46:12 [I] [proxy.go:69] [d5b81d54e6513e73] [tcp_port6_0] proxy closing
2019/07/13 09:46:12 [I] [proxy.go:135] [d5b81d54e6513e73] [tcp_port6_0] listener is closed
2019/07/13 09:46:12 [I] [control.go:350] [d5b81d54e6513e73] client exit success

**Comment by fatedier** [comment]
建议更换其他宽带，或自行研究其他中间加密方案，环境问题还是请自行解决。

**Comment by wwqgtxx** [comment]
> 网络问题还是自行想其他解决方案，每个项目都有自己的侧重点，可以尝试结合其他项目解决。
> 
> 另外，试试 `protocol = websocket`，如果不行就不行了，不用再继续在这里提了。

提个问题，这里写了支持`websocket`协议，那么请问目前的版本支持`wss`么，能否使用`nginx`进行基于`vhost`的`proxy_pass`呢，这样可能可以看起来更像普通的https流量吧

**Comment by fatedier** [comment]
@wwqgtxx 直接测试一下不就知道了？
