### ISSUE TITLE
STCP XTCP 最终visitor的servername不能正确取值

### ISSUE THREAD

**Issue by sosyxg** [fatedier/frp#1309]
frpc1
user = u1

frpc2
user = u2
[secret_stcp_visitor]
type = stcp
role = visitor
server_name = secret_stcp
sk = Abap!321
bind_addr = 127.0.0.1
bind_port = 6001
use_encryption = true
use_compression = true

server_name最终显示的是 u2.secret_stcp
实际上应该是u1.secret_stcp

如果配置成：
server_name = u1.secret_stcp

或被识别成： u2.u1.secret_stcp

请确实是否bug

**Comment by fatedier** [comment]
Dumplicate of #1301
