### ISSUE TITLE
真正内网环境无法打洞

### ISSUE THREAD

**Issue by JaneCC** [fatedier/frp#131]
大局域网，100开头的ip，frp无法链接上服务端

**Comment by fatedier** [comment]
你这样的问题无法给予回复，请注意提问时需要提供的信息。

**Comment by JaneCC** [comment]
电信分配的内网ip，无法穿透

**Comment by wxyzh** [comment]
没道理的，服务端在是公网的ip，然后客户端是内外的ip，可以连接的。
你要检查下你的防火墙设置了
