### ISSUE TITLE
如何代理第三方提供HTTP_PROXY中

### ISSUE THREAD

**Issue by itenl** [fatedier/frp#1314]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc frps
v0.27.0

**What operating system and processor architecture are you using (`go env`)?**
macos 10.14.4

**Configures you used:**
[charles_proxy]
type = http
######### charles 默认端口 8888
local_port = 8888
custom_domains = charles.proxy.xxx.com

[http_proxy]
type = tcp
remote_port = 6000
plugin = http_proxy

**Steps to reproduce the issue:**
前置：因为公司内网屏蔽了各个设备之间的网络，无法相互通信，故需要VPS通过FRPS桥，让手机设备能够访问公司内网电脑并能够在Charles能够抓到包；
1. shadows*** 避免和谐 与 抓包工具Charles 都提供了http_proxy，前者代理了可以翻墙，后者代理后流量走了Charles可以看到http/https的请求进行抓包，然而通过咱们的frp进行上面的配置文件 [charles_proxy] 进行配置无法使用，然而下面的 [http_proxy]走的是frp的代理无法达到我的预期

**Describe the results you received:**
在手机WIFI代理填写  [charles_proxy]  所配置的信息 
域名/IP：charles.proxy.xxx.com
端口：80
无法在Charles代理

**Describe the results you expected:**
预期是希望能够在手机WIFI代理中能使用Charles所提供的端口走Charles代理，通过FRP搭建VPN走隧道 ？端口转发(FRP的6000端口转发到Charles的8888)？

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by ChenWenBrian** [comment]
你是想让FRPC通过Charles提供的http proxy链接到FRPS端？
手机 -> frpc -> charles -> frps -> target

如果是这种case，readme里已有说明：
https://github.com/fatedier/frp#connect-frps-by-http-proxy
