### ISSUE TITLE
http/https服务可选择外网端口

### ISSUE THREAD

**Issue by mistzzt** [fatedier/frp#132]
**不知道这个功能有没有，若有请告知。**

现在我只能使用统一的端口。可不可以支持各个转发设定端口？

**Comment by fatedier** [comment]
所有 http/https 服务分别共用一个端口，如果你需要开另外的端口请使用 tcp 的方式。

**Comment by mistzzt** [comment]
直接转发对应的端口就可以了?

**Comment by fatedier** [comment]
是的，参考文档里有说明，参照 ssh 服务的转发方式。

**Comment by mistzzt** [comment]
好，谢了。
