### ISSUE TITLE
mac 下启动提示 -bash: ./frpc: Operation not permitted

### ISSUE THREAD

**Issue by rohsuton** [fatedier/frp#1321]
我在mac下使用客户端启动是提示：-bash: ./frpc: Operation not permitted，使用sudo也一样，请问一下是什么远影

mac系统版本：10.14.4
frp版本：frp_0.27.0_darwin_amd64
frp在本地所在的目录为：/Users/当前用户/frp下，所以不存在是Rootless问题

frpc.ini配置如下：
[common]
server_addr = 173.82.226.252
server_port = 7000

[web]
type = http
local_port = 8080
custom_domains = frp.xx.com

**Comment by fatedier** [comment]
请使用搜索引擎解决问题。

**Comment by zhongshankaka** [comment]
请问这个问题你怎么解决的呢
