### ISSUE TITLE
https2http插件，首先提示未注册，后提示域名is already registered（已经注册）

### ISSUE THREAD

**Issue by 1599947920** [fatedier/frp#1329]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.刚完成配置并刷新，30秒内显示`plugin [https2http] is not registered`
2.过一段时间后，提示`hostname [域名] location [] is already registered`
3.为了测试是否跟我的http转发冲突，特地将http转发给删掉了：
`[域名]
type = http
local_ip = IP
local_port = 50000
use_encryption = false
use_compression = false
host_header_rewrite = 域名
custom_domains = 域名`

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/38677638/61503861-d5cf3700-aa0b-11e9-932d-d4371173a2bb.png)

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by 1599947920** [comment]
编辑了版本，不知道为什么发出来没了，重新发下

What version of frp are you using (./frpc -v or ./frps -v)?
frpc与frps均为0.25.0

What operating system and processor architecture are you using (go env)?
frpc与frps均为centos7X64

Configures you used:

[域名_https2http]
type = https
custom_domains = 域名
plugin = https2http
plugin_local_addr = IP:50000 #50000为容器提供的http服务
plugin_crt_path = ./server.crt
plugin_key_path = ./server.key
plugin_host_header_rewrite = 127.0.0.1

**Comment by fatedier** [comment]
请使用最新版本测试。
