### ISSUE TITLE
7500端口的那个监控界面在重启后历史数据没有了

### ISSUE THREAD

**Issue by mbj2014** [fatedier/frp#133]
之前配置文件设置的是3天的数据，看7500端口的界面也有3天的情况。

然后我改了配置，加了站点，重启了服务。

发现文件目录下历史记录的log文件还在，但界面上显示的数据只有重启后的了，之前的没显示了。

**Comment by fatedier** [comment]
目前为了使用方便，统计数据是直接存在内存中的，并没有持久化到磁盘，保留7天的数据，重启后就没了。这部分之后会考虑改进。

**Comment by ghsa1994** [comment]
保存在文件中就可以  ，要是保存在数据库中还必须安装mysql，就不方便了，

**Comment by ivancxj** [comment]
用sqlite 也方便的
