### ISSUE TITLE
希望增加frpc中能随机使用部分远程端口，而不是全部

### ISSUE THREAD

**Issue by wolfgangsk07** [fatedier/frp#1333]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.27.1

**What operating system and processor architecture are you using (`go env`)?**
openwrt   X86

**Configures you used:**
frpc.ini:
[common]
server_addr = ********
server_port = 7000
token = ********
user = noone
admin_addr = 0.0.0.0
admin_port = 7400
admin_user = *********
admin_pwd = *********
tcp_mux = true

[rdp]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
use_encryption = false
use_compression = true
remote_port = 0

**Steps to reproduce the issue:**
无需

**Describe the results you received:**
无需

**Describe the results you expected:**
上述例子中，我使用了随机端口0，但是实际上我并不希望他的随机范围是我frps上指定的全部端口（30000-40000）。比如我想frpc在39000-40000之间随机一个（其余的端口留别别的frpc使用了），就无法办到了。逻辑上应该填写remote_port=39000-40000，但是目前还不支持这样定义。希望增加

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
特殊需求可以考虑自己通过外部脚本或其他形式来组合实现，frp 本身不会在这方面做太多额外的特殊实现。
