### ISSUE TITLE
frpc 在login登录失败时，连接关不掉

### ISSUE THREAD

**Issue by luyaotang** [fatedier/frp#1335]
问题描述：
frpc 在login登录失败时，连接关不掉，通过netstat -anp来查看还是维持着Established。这就会导致登录失败时，会创建了1000多个连接，状态还是Established。

版本：
目前用的是0.22.0,但对比了最新的0.27.2发现在相关的业务处理上代码并未变更

分析：
代码所有文件 server\service.go: Line 273。
conn.Close()这个动作并不能关掉连接，释放掉。
分析如下：在关闭前输出Remoaddr,LocalAddr,然后netsta -anp|grep portxxxx ，发现还是存在的，状态为Established。尝试使用frpConn.Close()就可以。
然后解决上面所说的连接没有关掉并释放的问题。

func (svr *Service) HandleListener(l frpNet.Listener) {
	// Listen for incoming connections from client.
	for {
		c, err := l.Accept()
		if err != nil {
			log.Warn("Listener for incoming connections from client closed")
			return
		}

		// Start a new goroutine for dealing connections.
		go func(frpConn frpNet.Conn) {
			dealFn := func(conn frpNet.Conn) {
				var rawMsg msg.Message
				conn.SetReadDeadline(time.Now().Add(connReadTimeout))
				if rawMsg, err = msg.ReadMsg(conn); err != nil {
					log.Trace("Failed to read message: %v", err)
					conn.Close()
					return
				}
				conn.SetReadDeadline(time.Time{})

				switch m := rawMsg.(type) {
				case *msg.Login:
					err = svr.RegisterControl(conn, m)
					// If login failed, send error message there.
					// Otherwise send success message in control's work goroutine.
					if err != nil {
						conn.Warn("%v", err)
						msg.WriteMsg(conn, &msg.LoginResp{
							Version: version.Full(),
							Error:   err.Error(),
						})
						//log.Error("msg.Login RegisterControl fail,%s",conn.RemoteAddr().String())
						conn.Close()
						//不知道为什么，好像关不掉，netstat -anp还是维持着establised
						frpConn.Close()
					}
				case *msg.NewWorkConn:
					svr.RegisterWorkConn(conn, m)

**Comment by fatedier** [comment]
无法复现这个问题，建议更新版本在本地重新尝试验证一下。

**Comment by luyaotang** [comment]
用了最新的release 0.27.1版本。复现流程

**Comment by fatedier** [comment]
`login_fail_exit = false` 去掉这行

**Comment by fatedier** [comment]
问题不在你指出的代码段，和 `login_fail_exit` 的处理有关，如果你有兴趣可以看一下这部分的逻辑然后提个 PR fix。

**Comment by luyaotang** [comment]
请教一下，比较疑惑的时为什么代码conn.Close()主动断开，那个连接还是可以维持在Estableshed。

**Comment by luyaotang** [comment]
好的。谢谢

**Comment by fatedier** [comment]
@luyaotang Can you fix it? Or i will fix it by myself.

**Comment by luyaotang** [comment]
能力不足，不知道怎么修。还是麻烦大神你修复。
