### ISSUE TITLE
ab -n400 -c 40 http://xxx.xxx.com/my/api 

### ISSUE THREAD

**Issue by epiphyllum** [fatedier/frp#1336]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
都是  0.27.1

**What operating system and processor architecture are you using (`go env`)?**
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Configures you used:**
frpc:
```
[common]
# venus 服务器
server_addr = 127.0.0.1
server_port = 7000
token = zhrmghgws

[mcht]
type = http
local_port = 3010
custom_domains= mcht.taotaole.mydomain.cn
```
frps:
```
[common]
bind_port = 7000
vhost_http_port = 8080
token = zhrmghgws
use_compression = true

# log_file = ./frps.log
log_level = error
```

**Steps to reproduce the issue:**
1.   为了测试性能， frpc, frps都是在同一台服务器上
2.  在本地执行:  ab -n400 -c 40 http://xxx.xxx.com/my/api  

**Describe the results you received:**
出现`2019/07/24 09:58:16 [E] [control.go:127] work connection closed, EOF`

**Describe the results you expected:**
应该没有错误才对

**Additional information you deem important (e.g. issue happens only occasionally):**
并发10， 20， 30测试没有出现问题。 并发40才出错。 

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
测试应该看响应结果，而不是日志内容，这个日志内容符合预期，是正常连接正常断开。

**Comment by epiphyllum** [comment]
work connection closed   这个日志是正常情况对吧？

**Comment by fatedier** [comment]
测试是测试返回结果是否符合你的预期，以及响应时间，资源消耗，可以通过搜索引擎学习一些相关知识。
