### ISSUE TITLE
是否提供了让frpc下线的方法

### ISSUE THREAD

**Issue by dearpeach** [fatedier/frp#1337]
想有个管理后台，能够实现强制让连接下线，frp是否提供了这个功能，请大佬帮忙解答？

还有查看单个name的状态是我调用方式不对吗？求解答
![image](https://user-images.githubusercontent.com/8085417/61760027-c16caf00-adfc-11e9-8724-750f9e470ed9.png)
![image](https://user-images.githubusercontent.com/8085417/61760152-38a24300-adfd-11e9-97af-5d05aba3b766.png)

@fatedier

**Comment by fatedier** [comment]
没有提供，可以自己实现。

**Comment by fatedier** [comment]
问题反馈可以按 issue 模版重新提交。
