### ISSUE TITLE
在linux系统使用syslog输出日志

### ISSUE THREAD

**Issue by kery** [fatedier/frp#1340]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.27.1

**What operating system and processor architecture are you using (`go env`)?**
Linux x86-64

**Configures you used:**
NA

**Steps to reproduce the issue:**
NA

**Describe the results you received:**
日志只能输出到指定文件或者console

**Describe the results you expected:**
在Linux系统下可以使用syslog输出日志

**Additional information you deem important (e.g. issue happens only occasionally):**
NA

**Can you point out what caused this issue (optional)**
NA

**Comment by fatedier** [comment]
自己写一个 wrapper 接管 console 日志，然后根据你自己的需求，可以随便转发到哪或者调整成任意格式。
