### ISSUE TITLE
socks5不能代理IE 11

### ISSUE THREAD

**Issue by ChenWenBrian** [fatedier/frp#1341]
**What version of frp are you using (./frpc -v or ./frps -v)?**
服务端与客户端都是0.27

**What operating system and processor architecture are you using (`go env`)?**
FRPS运行在路由器梅林固件上，ARM v7；客户端跑在Cent OS 7.5上，AMD 64架构

**Configures you used:**
[my-socks5]
type = tcp
remote_port = 1080
plugin = socks5
use_compression = true

**Steps to reproduce the issue:**
1.  frpc正确连接到frps
2. IE 11设置socks5 的地址与端口（路由器IP，与frpc端设置的1080端口）
3. IE无法正常访问网络
4. 用v2ray把该socks5转一下，依然使用socks5输出，然后IE配置V2RAY的socks5，则可以正常代理

不能work： PC端IE 11 => 路由器frps socks5 => linux frpc => 公司网络
可以work： PC端Chrome => 路由器frps socks5 => linux frpc => 公司网络
可以work： PC端IE 11 => 路由器v2ray socks5 =>  路由器frps socks5 => linux frpc => 公司网络

**Describe the results you received:**
感觉frp生成的socks5不能在IE上正确识别，但是用其他工具都能正确识别。譬如Chrome，Firefox，qq，v2ray等都可以，唯独IE不行。

**Describe the results you expected:**
希望IE上也能正确识别。虽然IE很少用了，但是有些工作环境死活非IE不可，无奈。
虽然现在用其他工具将frp映射出来的socks5转一下，就能让IE识别，但是还是希望frp本身就可以做到。

**Comment by fatedier** [comment]
frp 暂时不对 socks5 提供更多的支持，不是主要方向且没有这个精力。如果有更多的需求，还是使用专业的提供 socks5 的应用，再通过 frp 反代出来。
