### ISSUE TITLE
连接上服务器但代理失败

### ISSUE THREAD

**Issue by onlyJinx** [fatedier/frp#1342]
服务端提示成功了，但是访问http时却无法访问，是不是配置文件错了?
用IP和域名都无法访问
![file](https://user-images.githubusercontent.com/21324835/61993921-d324af80-b0a5-11e9-9d15-3e51ae102c09.png)

**Comment by SeaHOH** [comment]
你确定启动了 http 服务器？？建议好好看一遍 readme。

**Comment by onlyJinx** [comment]
> 你确定启动了 http 服务器？？建议好好看一遍 readme。

哈哈，我用那个本地配置打不开，用哪个域名或者ip打不开我那个测试网页，加上vhost(88)端口号也打不开…

**Comment by SeaHOH** [comment]
你 80 端口的服务器呢？

**Comment by onlyJinx** [comment]
> 你 80 端口的服务器呢？
我的http是监听在88端口的，如下图
![无标题](https://user-images.githubusercontent.com/21324835/61994883-58fb2780-b0b3-11e9-940d-b69814e77ef0.png)

**Comment by SeaHOH** [comment]
你还是没懂，这个是反向代理工具，你需要在 frpc 一侧启动你自己的服务器。

**Comment by onlyJinx** [comment]
> 你还是没懂，这个是反向代理工具，你需要在 frpc 一侧启动你自己的服务器。

我知道这是反向代理，我用ngrok可以代理出去，用frp的话开启80和3389(远程桌面)，3389可以正常转发，但80端口不行，还有我本地电脑已经开了http服务器了(看截图背后那个127.0.0.1)

**Comment by SeaHOH** [comment]
如果你确定有开本地服务器，那我就看不明白了。

**Comment by yflwz** [comment]
用域名加88端口试一下能不能访问

**Comment by onlyJinx** [comment]
> 用域名加88端口试一下能不能访问

试过域名加端口和ip加端口都不行，不知道是我是我配置文件写错了

**Comment by yflwz** [comment]
知道问题了，是时区的原因，时间相差太大了

**Comment by yflwz** [comment]
改服务器的时区就好了

**Comment by onlyJinx** [comment]
> 知道问题了，是时区的原因，时间相差太大了

恩，我去试试看

**Comment by onlyJinx** [comment]
> 改服务器的时区就好了

还是搞不定，改成和电脑同时区(亚洲上海)也不行，两边防火墙也都关了

**Comment by yflwz** [comment]
telnet 88端口看通不通

**Comment by onlyJinx** [comment]
> telnet 88端口看通不通

能通，但就是连接不上，我只能把占用80端口的程序改成其他的然后vhost_http_port 改成80了

**Comment by SeaHOH** [comment]
检查 frps 和 frpc 的版本是否一致。

你只是说无法访问，具体是个什么样的反馈？
使用代理访问域名 + vhost_http_port，以确定不是其它问题。

你的本地服务器是否有产生日志？如果没有，着重检查 frps 和所在机器的配置。

**Comment by SeaHOH** [comment]
顺便说下，你的 IP 和 token 都暴露了。

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)
