### ISSUE TITLE
XTCP 无法启用 use_encryption = true？

### ISSUE THREAD

**Issue by Xeath** [fatedier/frp#1347]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
客户端 1 的 ./frpc -v
0.27.0
客户端 2 的 ./frpc -v
0.27.0
服务端的 ./frps -v
0.27.0

**What operating system and processor architecture are you using (`go env`)?**
从 GitHub 下载的二进制文件

**Configures you used:**
客户端1
```
[Frp_SSH]
type = xtcp
sk = abc
local_ip = 127.0.0.1
local_port = 22
use_encryption = true
```
客户端2
```
[Frp_SSH]
type = xtcp
role = visitor
sk = abc
server_name = Frp_SSH
bind_addr = 127.0.0.1
bind_port = 2222
use_encryption = true
```

**Steps to reproduce the issue:**
1.客户端 1 的 frpc.ini 配置文件对 xtcp 设置了 `use_encryption = true`；
2.客户端 2 的 frpc.ini 配置文件对 xtcp 设置了 `use_encryption = true`。

**Describe the results you received:**
客户端 1 提示
```
2019/07/31 03:44:50 [I] [proxy.go:331] [Frp_SSH] nat hole connection make success, sid [15645446904d5f719b92ce2a09]
2019/07/31 03:44:50 [E] [proxy.go:352] [Frp_SSH] accept for yamux connection error: invalid protocol version
2019/07/31 03:45:10 [I] [proxy.go:331] [Frp_SSH] nat hole connection make success, sid [1564544710ab33bbf7fa5afcd7]
2019/07/31 03:45:10 [E] [proxy.go:352] [Frp_SSH] accept for yamux connection error: invalid protocol version
```
客户端 2 提示
```
2019/07/31 03:45:50 [I] [visitor.go:286] [Frp_SSH] nat hole connection make success, sid [15645446904d5f719b92ce2a09]
2019/07/31 03:46:11 [I] [visitor.go:286] [Frp_SSH] nat hole connection make success, sid [1564544710ab33bbf7fa5afcd7]
```

**Describe the results you expected:**
可以使用 use_encryption 对 xtcp 流量进行加密

**Additional information you deem important (e.g. issue happens only occasionally):**
None

**Can you point out what caused this issue (optional)**
None

**Comment by xiaopiao5789** [comment]
测试了一下客户端 1 设置 `use_encryption = true`，客户端 2 设置 `use_encryption = false` 能链接成功，但是不能正常使用，客户端 1 不设置而客户端 2 设置报相同的错误信息。如果两边都不进行设置，则可以正常使用

**Comment by Hurricanezwf** [comment]
发现在visitor的发送端，用了compression和encryption去包裹kcp协议，而在接收端没有去解析，导致协议无法识别。

发送端源码：
![image](https://user-images.githubusercontent.com/7840122/64059686-08b43f80-cbf4-11e9-935d-1cf8ee7a7f03.png)

接收端源码：
![image](https://user-images.githubusercontent.com/7840122/64059700-300b0c80-cbf4-11e9-91c3-f995fdc2ecf3.png)
