### ISSUE TITLE
hhtp穿透成功，tcp穿透失败，请教

### ISSUE THREAD

**Issue by chuyinluotian01** [fatedier/frp#1352]
0.27.0
BindPort 6666
BindUdpPort6667

frpc.ini配置文件如下
[common]
server_addr = ****
server_port = 6666
token = ****
log_file = frpc.log 
log_level = info 
log_max_days = 7 

[chuyin]
type = http
privilege_mode = true 
local_ip = 192.168.1.29
local_port = 5000
custom_domains = ***
use_encryption = true
use_gzip = true

[chuyintcp]
type = tcp
privilege_mode = true 
local_ip = 192.168.1.29
local_port = 51413
remote_port = 51413
use_encryption = true
use_gzip = true

查看服务端能看到http ，但是看不到tcp，请问到底是哪里设置错误了？

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)
