### ISSUE TITLE
Bind port issue

### ISSUE THREAD

**Issue by alpharde** [fatedier/frp#1356]
I would like to be able to make the frps service to listen on localhost, then make the proxies listen on my external IP.
How could this be done? Could not find this anywhere on the docs.

**Comment by fatedier** [comment]
`proxy_bind_addr = 127.0.0.1` will help you.

**Comment by alpharde** [comment]
Actually the other way arround:
``proxy_bind_addr = externip``
``bind_addr = 127.0.0.1``
But that did help! Thanks.
