### ISSUE TITLE
[feature request] support prometheus

### ISSUE THREAD

**Issue by jeffrey4l** [fatedier/frp#1357]
frp should export an url like `/metrics`, which can be scraped by prometheus server. In this way we can monitor whether frp or the clients works properly.

**Comment by zyfdegh** [comment]
There's a typo, corrected: `/metrics`

**Comment by fatedier** [comment]
#1668

**Comment by jeffrey4l** [comment]
Thanks for the implementation.

I just check the new release binary, seem only some common process metric is exported. Could we add metrics related to each proxy statistics? like tcp traffic in and out in dashboard.

**Comment by fatedier** [comment]
@jeffrey4l https://github.com/fatedier/frp/blob/master/models/metrics/prometheus/server.go#L58
All metrics registered here including net traffic.

**Comment by jeffrey4l** [comment]
yeah, i found it.
seems when the metrics value is 0, it is not show up in `/metrics` url. 

thanks.
