### ISSUE TITLE
可以多域名根据域名路由大到不同的应用吗？

### ISSUE THREAD

**Issue by mengpengfei** [fatedier/frp#1361]
# frpc.ini
[web01]
type = http
local_port = 80
custom_domains = web.yourdomain.com
locations = /

[web02]
type = http
local_port = 81
custom_domains = web.yourdomain.com
locations = /news,/about

这个能不能配置两个不同的域名，路由到具体的 web01或者web02

**Comment by fatedier** [comment]
可以

**Comment by mengpengfei** [comment]
> 可以
经常报
work connection closed

然后reconnect是怎么回事啊

**Comment by mengpengfei** [comment]
2019/08/07 19:55:59 [W] [http.go:223] http: proxy error: no such domain: www.damagou.top /apiv1/jiyanRecognize.html
2019/08/07 19:56:00 [I] [service.go:349] client login info: ip [223.72.48.65:25307] version [0.27.0] hostname [] os [windows] arch [amd64]
2019/08/07 19:56:01 [I] [http.go:72] [6d7d84e8f2b09ce7] [webhttp] http proxy listen for host [www.damagou.top] location []
2019/08/07 19:56:01 [I] [control.go:398] [6d7d84e8f2b09ce7] new proxy [webhttp] success
2019/08/07 19:56:01 [I] [tcp.go:66] [6d7d84e8f2b09ce7] [mysql] tcp proxy listen port [43306]
2019/08/07 19:56:01 [I] [control.go:398] [6d7d84e8f2b09ce7] new proxy [mysql] success
2019/08/07 19:56:01 [I] [tcp.go:66] [6d7d84e8f2b09ce7] [remote-desktop] tcp proxy listen port [43389]
2019/08/07 19:56:01 [I] [control.go:398] [6d7d84e8f2b09ce7] new proxy [remote-desktop] success
2019/08/07 19:56:01 [I] [https.go:47] [6d7d84e8f2b09ce7] [webssl] https proxy listen for host [www.damagou.top]
2019/08/07 19:56:01 [I] [control.go:398] [6d7d84e8f2b09ce7] new proxy [webssl] success
2019/08/07 19:56:08 [I] [proxy.go:82] [6d7d84e8f2b09ce7] [webhttp] get a new work connection: [223.72.48.65:25307]
2019/08/07 19:56:11 [I] [proxy.go:82] [6d7d84e8f2b09ce7] [webhttp] get a new work connection: [223.72.48.65:25307]
2019/08/07 19:56:29 [W] [control.go:395] [6d7d84e8f2b09ce7] new proxy [mysql] error: port already used
2019/08/07 19:56:29 [W] [control.go:395] [6d7d84e8f2b09ce7] new proxy [remote-desktop] error: port already used
2019/08/07 19:56:29 [W] [control.go:278] [6d7d84e8f2b09ce7] write message to control connection error: session shutdown
2019/08/07 19:56:29 [I] [proxy.go:69] [6d7d84e8f2b09ce7] [mysql] proxy closing
2019/08/07 19:56:29 [I] [proxy.go:135] [6d7d84e8f2b09ce7] [mysql] listener is closed
2019/08/07 19:56:29 [I] [proxy.go:69] [6d7d84e8f2b09ce7] [remote-desktop] proxy closing
2019/08/07 19:56:29 [I] [proxy.go:135] [6d7d84e8f2b09ce7] [remote-desktop] listener is closed
2019/08/07 19:56:29 [I] [proxy.go:69] [6d7d84e8f2b09ce7] [webssl] proxy closing
2019/08/07 19:56:29 [I] [proxy.go:69] [6d7d84e8f2b09ce7] [webhttp] proxy closing
2019/08/07 19:56:29 [I] [control.go:350] [6d7d84e8f2b09ce7] client exit success
2019/08/07 19:56:29 [W] [http.go:223] http: proxy error: EOF
2019/08/07 19:56:29 [W] [http.go:223] http: proxy error: EOF
2019/08/07 19:56:29 [I] [proxy.go:135] [6d7d84e8f2b09ce7] [webssl] listener is closed
2019/08/07 19:56:31 [I] [service.go:349] client login info: ip [223.72.48.65:25312] version [0.27.0] hostname [] os [windows] arch [amd64]
2019/08/07 19:56:38 [W] [http.go:223] http: proxy error: no such domain: www.damagou.top /apiv1/userInfo.html
2019/08/07 19:56:38 [I] [tcp.go:66] [6d7d84e8f2b09ce7] [remote-desktop] tcp proxy listen port [43389]
2019/08/07 19:56:38 [I] [control.go:398] [6d7d84e8f2b09ce7] new proxy [remote-desktop] success
2019/08/07 19:56:38 [I] [https.go:47] [6d7d84e8f2b09ce7] [webssl] https proxy listen for host [www.damagou.top]
2019/08/07 19:56:38 [I] [control.go:398] [6d7d84e8f2b09ce7] new proxy [webssl] success
2019/08/07 19:56:38 [I] [tcp.go:66] [6d7d84e8f2b09ce7] [mysql] tcp proxy listen port [43306]
2019/08/07 19:56:38 [I] [control.go:398] [6d7d84e8f2b09ce7] new proxy [mysql] success
2019/08/07 19:56:38 [I] [http.go:72] [6d7d84e8f2b09ce7] [webhttp] http proxy listen for host [www.damagou.top] location []
2019/08/07 19:56:38 [I] [control.go:398] [6d7d84e8f2b09ce7] new proxy [webhttp] success

**Comment by mengpengfei** [comment]
什么情况？
