### ISSUE TITLE
一直报错怎么回事

### ISSUE THREAD

**Issue by mengpengfei** [fatedier/frp#1362]
2019/08/07 21:54:09 [W] [control.go:395] [68a4788d5a2c845e] new proxy [webhttp] error: router config conflict
2019/08/07 21:54:09 [W] [control.go:395] [68a4788d5a2c845e] new proxy [remote-desktop] error: port already used
2019/08/07 21:54:09 [W] [control.go:395] [68a4788d5a2c845e] new proxy [webssl] error: hostname [www.damagou.top] location [] is already registered
2019/08/07 21:54:09 [W] [control.go:395] [68a4788d5a2c845e] new proxy [mysql] error: port already used
2019/08/07 21:54:17 [I] [control.go:274] [68a4788d5a2c845e] control writer is closing
2019/08/07 21:54:17 [I] [proxy.go:69] [68a4788d5a2c845e] [webhttp] proxy closing
2019/08/07 21:54:17 [I] [proxy.go:69] [68a4788d5a2c845e] [webssl] proxy closing
2019/08/07 21:54:17 [I] [proxy.go:69] [68a4788d5a2c845e] [mysql] proxy closing
2019/08/07 21:54:17 [I] [proxy.go:135] [68a4788d5a2c845e] [mysql] listener is closed
2019/08/07 21:54:17 [W] [http.go:223] http: proxy error: EOF
2019/08/07 21:54:17 [W] [http.go:223] http: proxy error: EOF
2019/08/07 21:54:17 [I] [proxy.go:135] [68a4788d5a2c845e] [webssl] listener is closed
2019/08/07 21:54:17 [I] [proxy.go:69] [68a4788d5a2c845e] [remote-desktop] proxy closing
2019/08/07 21:54:17 [I] [proxy.go:135] [68a4788d5a2c845e] [remote-desktop] listener is closed
2019/08/07 21:54:17 [I] [control.go:350] [68a4788d5a2c845e] client exit success

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)
