### ISSUE TITLE
[Document improvement request] Add installation guide in README.md

### ISSUE THREAD

**Issue by recolic** [fatedier/frp#1366]
I'm trying to setup frp server on my vps.

It would be really helpful if frp/README.md contains a `Installation` section like other open source project does.

The installation guide should mention at least the following: 

1. How to install go dependencies (in one command: `go get ./...`. Chinese user may have to break the fucking government wall)

2. How to build the package. Should I use `Makefile` or `package.sh` or `go build`?

> by the way, PLEASE add `#!/bin/bash` into package.sh, else do not let package.sh executable.

3. How to install the package. Should I use `Makefile` or `go install`?

4. Additional information for distribution-specific installation guide. For example, frpc and frps are already available on ArchLinux AUR repo. It's better to let user know it.

Thanks for your awesome work.

**Comment by fatedier** [comment]
Yes, do you want to contribute to this?

**Comment by recolic** [comment]
I'll do it this weekend.

**Comment by recolic** [comment]
This is just a note. never mind...

```
> not tested yet!
## non-root user
just git clone and make

## root user
mkdir -p $GOPATH/src/github.com/fatedier
git clone https://github.com/fatedier/frp $GOPATH/src/github.com/fatedier/frp
cd $GOPATH/src/github.com/fatedier/frp
make # `go get ./...` If fails.

```

**Comment by fatedier** [comment]
`GOPATH` is deprecated.

Requried Go version >= go1.12

If the network is no problem to get third packages, just run `GO111MODULE=on make`, it will build with go mod.

Or using `GOPROXY` to download third packages such as `GOPROXY=https://goproxy.io GO111MODULE=on make`.

**Comment by recolic** [comment]
> `GOPATH` is deprecated.
> 
> Requried Go version >= go1.12
> 
> If the network is no problem to get third packages, just run `GO111MODULE=on make`, it will build with go mod.
> 
> Or using `GOPROXY` to download third packages such as `GOPROXY=https://goproxy.io GO111MODULE=on make`.

I have successfully built the package under go1.10 with [this method](https://github.com/recolic/frp#build-from-source)

**Comment by fatedier** [comment]
It's deprecated and not maintained.

**Comment by recolic** [comment]
> It's deprecated and not maintained.

I know. but I think it's better to provide some help... I'll mark go<1.12 as deprecated in the document.

**Comment by recolic** [comment]
@fatedier Please check Pull request #1417

**Comment by killerthief** [comment]
how do i  get elite proxies i am learning to crack so ya
