### ISSUE TITLE
centos7如何安装？

### ISSUE THREAD

**Issue by kingimg** [fatedier/frp#137]
centos 新手，应该如何安装frpc呢?3Q

**Comment by LiHaoGit** [comment]
直接下载[linux_386.tar.gz](https://github.com/fatedier/frp/releases/download/v0.8.1/frp_0.8.1_linux_386.tar.gz)

按照[中文说明](https://github.com/fatedier/frp/blob/master/README_zh.md)使用即可

**Comment by kingimg** [comment]
感谢楼上。。昨天不知道选哪个包。最后装了go语言，go build -o bin/frpc ./src/cmd/frpc 成功了。。
