### ISSUE TITLE
服务端的web默认页面修改

### ISSUE THREAD

**Issue by mengdodo** [fatedier/frp#1370]
正常搭建完成后,服务端80端口访问显示

### The page you visit not found.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

The server is powered by frp.

Faithfully yours, frp.

感觉这么大摇大摆的告诉别人自己服务器的状态总觉得不太安全,

请问可以修改这个默认页面的文字吗

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/conf/frpc_full.ini#L135
