### ISSUE TITLE
关于 端口700 能否改成udp传输

### ISSUE THREAD

**Issue by onlineyh** [fatedier/frp#1371]
版本：frp_0.28.2_linux_amd64.tar.gz
# frps.ini
[common]
bind_port = 7000  如何修改成udp端口

# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000 如何修改成udp端口

[openvpn]
type = udp
local_ip = 127.0.0.1
local_port = 9194
remote_port = 9194

上面这个端口7000 能否改成udp？

**Comment by fatedier** [comment]
不能，但是可以更换 protocol 为 kcp。
