### ISSUE TITLE
frps dashboard 打不开

### ISSUE THREAD

**Issue by googlehim** [fatedier/frp#1375]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.28.2

**What operating system and processor architecture are you using (`go env`)?**
server: debian9_amd64
client: win10_ chrome 版本 76.0.3809.100（正式版本） （64 位）

**Configures you used:**
dashboard_addr = 0.0.0.0
dashboard_port = 7500
dashboard_usr =  xxx
dashboard_pwd = xxx

**Steps to reproduce the issue:**
1.外网访问内网路由器ssh和web配置可用
2.chrome打开外网ip   xxx.xxx.xxx.xxx:7500
3.http://xxx.xxx.xxx.xxx:7500/static/#/

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/9864527/62831175-a9df5400-bc4d-11e9-8c2e-29b2fac1230c.png)

**Describe the results you expected:**
查看dashboard页面

**Additional information you deem important (e.g. issue happens only occasionally):**
![image](https://user-images.githubusercontent.com/9864527/62831185-ced3c700-bc4d-11e9-9c8e-18ca977a5d2e.png)

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
本地无法复现这个问题。

可以：
1. 尝试更换浏览器测试。
2. 在本地电脑启动服务端客户端，本地浏览器访问测试，避免受到网络环境的干扰。

**Comment by googlehim** [comment]
在公司电信网络下能打开dashboard,  家里移动宽带下win10电脑打仍然打不开，手机(同路由器wifi)可以打开。 看起来应该是笔记本电脑软件环境问题了
![image](https://user-images.githubusercontent.com/9864527/62868307-ea22fd00-bd47-11e9-9ea2-8fc3872d42ed.png)
![image](https://user-images.githubusercontent.com/9864527/62868375-163e7e00-bd48-11e9-9dfb-107efdd152c0.png)
![image](https://user-images.githubusercontent.com/9864527/62868468-5140b180-bd48-11e9-8e33-4ddfaa84653a.png)
