### ISSUE TITLE
[求助]关于http页面js调用内部ip端口的情况如何做穿透

### ISSUE THREAD

**Issue by wadeLouis** [fatedier/frp#1381]
我有上千台的设备，使用4G卡连接网络，网络服务商给分配的是内网的IP。每个设备上面有一套web服务，web服务的js调用都是填写了内网的ip和端口。这种情况下，我想通过外网直接访问这个web服务进行设备的配置升级，frb是否能给我帮助呢？

**Comment by fatedier** [comment]
frp 提供了内网穿透的基础能力，你可以结合具体的场景自行研究下。
