### ISSUE TITLE
是否可以针对 remote_port 设置密码

### ISSUE THREAD

**Issue by wangliang1989** [fatedier/frp#1383]
是否可以针对 remote_port 设置密码？也就是不同的 remote_port 有不同的密码，而不是一个统一的token，这样便于为每个用户提供服务

**Comment by fatedier** [comment]
参考 #1378  中的回复，近期会设计一下 server plugin 的功能。
此类需求以及针对一些不同场景的使用姿势，都通过 plugin 的能力来扩展。通过自行安装不同的 plugin 来实现各自的需求。
