### ISSUE TITLE
关于 TLS 的问题

### ISSUE THREAD

**Issue by Hapoa** [fatedier/frp#1386]
我是最近才开始了解 TLS/SSL 这块的，我发现我们的 frp 在启用 TLS 的时候，并未指定公私钥，证书之类的。

看了下整个源码结构，并未找到相关的文件，所以我推测是写死在代码里的，但是我找了一下没找到。

所以我的问题是：

1. 如果是写死的话，写死在哪个地方了？
2. 用的对称加密，还是非对称加密？
3. 如果问题 1 成立，那以后的版本会更换密钥么？

**Comment by fatedier** [comment]
目前内置的 tls 的目的是加密，而非身份验证，所以暂时不可指定证书，之后可能会增加指定自己证书的功能。

1. 证书是通过代码自动生成的，用户无需感知。客户端不会对证书的有效性做校验。
2. 两者都会用，具体建议阅读 TLS 相关的文档。
3. 密钥是通过握手生成的，证书是自动生成的，用户都不需要关注，这里只是用来做加密。

**Comment by Hapoa** [comment]
谢谢你的回答，明白了。
