### ISSUE TITLE
能否像ngrok那样，由服务端挂载证书？

### ISSUE THREAD

**Issue by cnluzhang** [fatedier/frp#139]
这样能解决一部分强制需要https，但是本地挂载证书又不方便的问题...

谢谢啦。

**Comment by cnluzhang** [comment]
我目前是又启动了一个nginx专门listen 443，由nginx处理证书，然后把请求和HOST转发到80端口上

**Comment by fatedier** [comment]
这个就涉及到安全性的问题了，不过也是可以考虑的，目前你的方法就挺好的。

**Comment by cnluzhang** [comment]
但是这样会引入一个问题，就是frp服务端拿到的IP不是真实IP，我不知道目前frp服务端能接收Forwarded-For或者Real-IP这种头么？
如果今后frp增加统计功能，那么这个IP可能是需要的...

**Comment by fatedier** [comment]
#127 ，之后可以考虑。

**Comment by StevenLiSiwei** [comment]
@cnluzhang 请问能否分享一下你 NGINX 的配置信息，谢谢！！
