### ISSUE TITLE
frps和frpc多对一（智能解析、线路优化）

### ISSUE THREAD

**Issue by lgmcode** [fatedier/frp#140]
不知道现在支不支持多个frps对应一个frpc，即一个frpc连接到多个frps上。应用场景可能是在需要优化不同线路的场合，比如电信用户连接到电信线路上的frps服务器，网通用户连接到网通线路的frps服务器上，但是它们最终都连接到一个frpc上提供服务。一个简单的办法是在内网的机器上运行多个frpc进程，和frps仍然保持一对一关系。但是不知道能不能更酷一点，直接支持。

**Comment by wxyzh** [comment]
开多个frpc不就行了吗？

**Comment by fatedier** [comment]
考虑过多个 frps，主要用于容灾。

线路的话，因为现在云服务提供商的网络基本都是 BGP 线路，问题不是很大。
