### ISSUE TITLE
Make authentication system customizable through server plugins

### ISSUE THREAD

**Issue by velovix** [fatedier/frp#1406]
Edit: This behavior is expected to be implemented using server plugins. This issue is re-purposed as a feature request to allow this customization using server plugins.

# Original Proposal

I'm integrating FRP into a larger system with a pre-existing authentication mechanism. It would be great if I could customize the way FRP generates and checks privilege keys by, for example, providing callback functions. Perhaps it could look like this:

```go
// client/service.go
func (svr *Service) SetKeyGenerator(generator func() string) {
    svr.keyGenerator = generator
}
```

```go
// server/service.go
func (svr *Service) SetKeyChecker(keyChecker func(privilegeKey string) bool) {
    svr.keyChecker = keyChecker
}
```

If these methods are not called, the client and server fall back to using the current key generation and checking system.

This feature would be exposed only through the library. I imagine that custom authentication is out of the scope of FRP when used as a command line tool.

If this looks good, I would be happy to send a pull request to implement this.

**Comment by fatedier** [comment]
I want to expose some features by `server plugin`, you can see #1378 and #1403.

Not only the `token or privilegeKey` need to check, but also the `user` or other meta info. We should implement this in a general method.

The `plugin` feature need detailed design and will not be provided soon.

**Comment by fatedier** [comment]
v0.31.0 support server manage plugin.
