### ISSUE TITLE
Package naming is too generic for a library

### ISSUE THREAD

**Issue by velovix** [fatedier/frp#1407]
Package names like `server`, `client`, and `config` make a lot of sense for internal development of FRP, but are too generic when FRP is used as a library in another system. When reading non-FRP code, it's not clear that these names are related to FRP. 

To address this, a new package could be created, maybe named `frp`, where all interfaces intended to be used as a library are stored. Code could be migrated to this new package or we could use type aliases, like this:

```go
package frp

import (
    "github.com/fatedier/frp/server"
    "github.com/fatedier/frp/client"
    "github.com/fatedier/frp/models/config"
)

type Server = server.Service
type ServerCommonConf = config.ServerCommonConf

func NewServer(cfg ServerCommonConf) (*Server, error) {
    return server.NewService(cfg)
}

type Client = client.Service
type ClientCommonConf = config.ClientCommonConf
type ProxyConf = config.ProxyConf
type VisitorConf = config.VisitorConf

func NewClient(cfg ClientCommonConfig, pxyCfgs map[string]ProxyConf, visitorCfgs map[string]config.VisitorConf, cfgFile string) (*Client, error) {
    return client.NewService(cfg)
}
```

This would give us a lot of control over which APIs should be exposed for library usage and which should not, and would lead to less ambiguous naming for users. Compare `server.Service` to `frp.Server`.

I'm not sure whether type aliasing or code migration is more preferable. My first impression is that I would rather migrate the code as I think it would lead to more code clarity. Internal types like `server.Control` would stay where they are, as I don't think there's any reason why a library user would need them.

If this or an alternative proposal that addresses the same problem looks good, I would be happy to send a pull request.

**Comment by fatedier** [comment]
I think it's common to import `github.com/fatedier/frp/server` and call `server.NewService` 
or import `github.com/fatedier/frp/client` and call `client.NewService`。

`frp` is included in the import path, you know it when you import this package.

You can also change import path to this format:

```golang
import (
    frps "github.com/fatedier/frp/server"
    frpc "github.com/fatedier/frp/client"
)
```

So it looks like `frps.NewService` and `frpc.NewService`。

I prefer not to affect current code structure.

**Comment by fatedier** [comment]
OK. Maybe we can create a new package `sdk/frp` with `client.go`, `server.go` and `config.go`.

Type alias and nested structs are all optional.

**Comment by fatedier** [comment]
Just keep it open, it may help other peoples with same requirement.

Thanks for all your contribution.

**Comment by ScorpioRen** [comment]
支持 go mod 模式引入吗
