### ISSUE TITLE
无法启动多docker 客户端

### ISSUE THREAD

**Issue by kpeng2016** [fatedier/frp#1412]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.28.2

**What operating system and processor architecture are you using (`go env`)?**
centos7

**Configures you used:**
server
===frps.ini===
[common]
bind_port = 7000
vhost_http_port = 80

client
 ===frpc.ini===
[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 7000

[web]
type = http
local_port = 7009
custom_domains = xxx.xxx.com
两个客户端服务器中的frpc.ini配置的内容仅custom_domains不同

**Steps to reproduce the issue:**
1. 下载wget frp_0.28.2_linux_amd64.tar.gz ,解压，服务端端启动服务,将上面服务端的配置内容，设置到服务端服务器中，然后执行./frps -c ./frps.ini
2. 下载wget frp_0.28.2_linux_amd64.tar.gz ,解压，客户端服务器端启动服务,将上面客户端的配置内容，设置到客户端服务器中，然后执行./frpc -c ./frpc.ini
3. 另一个客户端参考第2步

**Describe the results you received:**
后启动的那个客户端，不能远程访问

**Describe the results you expected:**
希望都能启动

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
看日志排查错误，proxy name 不能重复。
