### ISSUE TITLE
请问如何关闭https的443端口？

### ISSUE THREAD

**Issue by xuzhibin** [fatedier/frp#1413]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.28.1

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
请问如何关闭https的443端口？frp服务端会自动启用443端口，试过设置vhost_https_port，但是依然会占用443端口。

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
不设置 `vhost_https_port`。

**Comment by xuzhibin** [comment]
试过不设置vhost_https_port，或者设置vhost_https_port为别的端口，frps都会占用443端口

**Comment by fatedier** [comment]
你自己在本地，更换绑定端口先测试一下。
有问题先尽量自己排查，你的环境，使用姿势，都有影响，能确定问题后再提 issue。
