### ISSUE TITLE
[Feature Request] Token for client only or no token required for clients

### ISSUE THREAD

**Issue by scegg** [fatedier/frp#1416]
In case for publishing service through xtcp, server token need to be disclosed to all users which is not safe.
Please consider to add a token in common for client only, or ignore token check for xtcp client side users.
Thanks.

**Comment by fatedier** [comment]
xtcp is not provided for different user now.

**Comment by scegg** [comment]
> xtcp is not provided for different user now.

Yes, currently, there is no user separate function on server. If the server has a token set in common block, all users who know this token on the same server will share all function.
The feature requested is: if some client is created only for accessing a specified xtcp service, through there is a key for each xtcp service already, why the token for the whole server is required in this client config?

**Comment by fatedier** [comment]
Token is used to check if frpc have permission to login to frps.
I know your demand and it can't be satisfied now. It requires more time to redesign with a low priority. I will first do the server plugin feature.

**Comment by funnypro** [comment]
Try creating a new separate configuration?

**Comment by zhaoyc1990** [comment]
@scegg   If you will use the golang development language, you can use the 'user' item under the configuration [common] of FRPC. Then modify FRPs to judge when FRPC logs in, so as to achieve the purpose.

**Comment by scegg** [comment]
If I were able to use golang, there will be a pull request instead of this issue lol.

**Comment by fatedier** [comment]
Since v0.31.0, you can implement this feature by server manage plugin.
And if you do that, you can share your plugin in https://github.com/gofrp/plugin (create an issue).
