### ISSUE TITLE
proxy type http subdomain_host/subdomain doesnt work

### ISSUE THREAD

**Issue by pepitefr** [fatedier/frp#1418]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frps : 0.27.1
frps : 0.27.1

**What operating system and processor architecture are you using (`go env`)?**
debian 9.4

**Configures you used:**
frps 
```
vhost_http_port = 8383
#vhost_https_port = 2443
subdomain_host = mydomain.fr
```

frpc
```
[omv_http]
type = http
local_ip = 192.168.2.xxx
local_port = 80
subdomain = omv_http
```

**Steps to reproduce the issue:**
1. mydomain.fr resolve ip of frps server
2.
3.

**Describe the results you received:**

this site doesnt exist, i try every days during 7 days

all proxies with tcp are OK

**Describe the results you expected:**
i try to get proxy [omv_http] with this url
http://omv_http.mydomain.fr:8383

i don't understand whats wrong
thank's a lot

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
DNS config `*.mydomain.fr` not `mydomain.fr`.

**Comment by pepitefr** [comment]
Yes, all is good, that's work very well !!

Thanks a lot 
Amazing fro. Thanks for the job
