### ISSUE TITLE
请问有现成能用的公网服务吗

### ISSUE THREAD

**Issue by Qquanwei** [fatedier/frp#142]
RT

**Comment by maodanp** [comment]
目前还没有，只能个人租用公网服务器。后续会考虑搭建公网平台

**Comment by deyiouyj** [comment]
在阿里云上申请域名和ECS服务期，现在很便宜了。
搭建也很简单，我按照官方说明，几分钟就把frp搭好。运行了几天，目前为止是稳定的

**Comment by Qquanwei** [comment]
只是想代理一下ssh ，不是跑服务，所以想即开即用的

**Comment by cnluzhang** [comment]
@Qquanwei 

[common]
server_addr = 123.57.213.147
server_port = 4443
privilege_token = M2u49iNLeuadr6
[自定义内容]
type = http
local_ip = 127.0.0.1
local_port = 4000
use_gzip = true
use_encryption = true
pool_count = 20
privilege_mode = true
custom_domains = 自定义内容.tunnel.mobi

没有HTTPS，默认在HTTP域名前面加HTTPS即可访问HTTPS

**Comment by cnluzhang** [comment]
@Qquanwei 才发现你要SSH，那么开一堆高端口吧

**Comment by Qquanwei** [comment]
@cnluzhang 只要一个就行了 另外感谢提供主机 :)  等我编译好试试

**Comment by Qquanwei** [comment]
@cnluzhang 连接不上。
按照上面的地址我的配置如下
```
[common]
server_addr = 123.57.213.147
server_port = 4443
privilege_token = M2u49iNLeuadr6

[ssh]
local_port = 3000
```

本地开启
` echo 'hello' | nc -l 3000 `

启动frpc

`./frpc -c ./config.ini`

然后执行
`nc  123.57.213.147 4443`

没反应 (我给一个失败的地址也是没反应,所以应该是服务器连接失败?)

**Comment by cnluzhang** [comment]
[common]
server_addr = 123.57.213.147
server_port = 4443
privilege_token = M2u49iNLeuadr6

[sshxxxxx]
privilege_mode = true
local_port = 22
remote_port = 55555

感觉应该这样写，然后用55555去访问。

**Comment by Qquanwei** [comment]
@cnluzhang 远程主机积极断开 
去连接55555了，结果 refuse

**Comment by cnluzhang** [comment]
@Qquanwei  try again?

输出如果没有以下三行，就有问题
2016/10/21 16:56:44 [main.go:109] [I] Start frpc success
2016/10/21 16:56:44 [control.go:185] [I] ProxyName [xxxxxxxxxx], connect to server [123.57.213.147:4443] success!
2016/10/21 16:56:44 [control.go:193] [I] Start to send heartbeat to frps

**Comment by Qquanwei** [comment]
@cnluzhang  谢谢，可以了

**Comment by roadom** [comment]
@cnluzhang 请问 frps 是要放在自己的云主机上么？

**Comment by zzjin** [comment]
@cnluzhang 使用web代理还是出问题,卡在第一行,只输出了[main.go:109] [I] Start frpc success

**Comment by cnluzhang** [comment]
@fatedier 第三次遇到这种问题了，怎么排故障比较合适？
通常重启服务端就正常了

**Comment by fatedier** [comment]
@cnluzhang 可以单独开个 issue 描述一下现象，再出现问题时最好用客户端连接的同时抓一下服务器端的 tcp包，看一下交互的过程。

**Comment by Mika1992** [comment]
配置内网的web服务器无法访问    web服务器是windows10 系统  配置  信息如下 
# frpc.ini
[common]
server_addr = 123.56.251.141
server_port = 5443
auth_token = 123

[web]
type = http
local_port = 8080

# frps.ini
公网服务器配置是
[common]
bind_port = 5443
vhost_http_port = 6000

[web]
type = http
custom_domains = www.lpf710282897.com
auth_token = 123

www.lpf710282897.com:6000  访问失败   大家是怎么配置的呢？  我是新手，端口都是打开的,内网启动后显示的ProxyName [web], connect to server[123.56.251.141:5443] success!
