### ISSUE TITLE
http reverse proxy with NTLM authentication support

### ISSUE THREAD

**Issue by hez2010** [fatedier/frp#1421]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.27.1

**What operating system and processor architecture are you using (`go env`)?**
Windows 10 x64 1903 18362.295

**Configures you used:**
frpc.ini:
```
[common]
server_addr = xxxx
server_port = 7000

[devops]
type = http
local_port = 80
custom_domains = xxxx.com
host_header_rewrite = xxxx.com

```

**Steps to reproduce the issue:**
1. setup a website using NTLM authentication
2. setup http proxy with frp
3. access your service via proxy

**Describe the results you received:**
cannot authenticate.

**Describe the results you expected:**
authenticate successfully

**Can you point out what caused this issue (optional)**
After searching I found the [reason](https://stackoverflow.com/questions/4368453/how-to-enable-windows-authentication-through-a-reverse-proxy):
NTLM won't work if the TCP packets are not forwarded exactly as the reverse proxy received > them. And that's why many reverse proxy doesn't work with NTLM authentication. (like nginx) > They forward HTTP requests correcty but not the TCP packets.

To solve this, you need to create a keepalive agent.

**Comment by fatedier** [comment]
It can't supported now, you can try tcp type instead.

**Comment by hez2010** [comment]
Tcp type proxy do can pass the NTLM Authentication, however while using tcp type proxy, all resources in the website will load from wrong locations. 
Is there any plan to support NTLM Authentication in http proxy?

**Comment by fatedier** [comment]
If tcp doesn't work, no other method can help.

**Comment by hez2010** [comment]
I hope that frp can provide an option to create a keepalive agent(in frps), then the problem can be solved.

**Comment by fatedier** [comment]
It can't supported now, maybe future. It's cpmplicated.
You can try tcp type instead, if it doesn't work, frp is not suitable for you.
