### ISSUE TITLE
stcp用户名异常或空缺

### ISSUE THREAD

**Issue by wzxyisme** [fatedier/frp#1423]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.29.0

**What operating system and processor architecture are you using (`go env`)?**
服务端：cnetOS7
客户端：Windows 10
**Configures you used:**

**Steps to reproduce the issue:**
1服务端frps.ini
[common]
bind_port = 7000
token = 1925
dashboard_port = 7500
dashboard_user = admin
 dashboard_pwd = admin
2.服务端frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000
token = 1925
admin_addr = 127.0.0.1
 admin_port = 7400
 admin_user = admin
 admin_pwd = 1925349617
protocol = tcp
user = admin

[secret_ssh]
type = stcp
sk = 1925
 local_ip = 127.0.0.1
 local_port = 81
use_encryption = true
use_compression = true
3.客户端frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000
token = 1925
protocol = tcp
user = admin

[secret_ssh_visitor] 
type = stcp
role = visitor
secret_name = secret_ssh
SK = 1925
 bind_addr = 127.0.0.1
 bind_port = 81

 `![IMG_20190903_121756_LI](https://user-images.githubusercontent.com/45878990/64145589-04825f00-ce4c-11e9-84b3-0374dbf6e107.jpg)`

**Describe the results you received:**
加上user=admin：2019/09/03 12:47:16 [W] [visitor.go:138] [admin.secret_ssh_visitor] start new visitor connection error: custom listener for [admin.] doesn't exist
不加user：2019/09/03 12:50:34 [W] [visitor.go:138] [secret_ssh_visitor] start new visitor connection error: custom listener for [] doesn't exist
不管在user加什么，在都会在用户名后多一个点，导致的自定义侦听器不存在，不加user，就会找不该到用户
**Describe the results you expected:**
在本地打开frp的Admin UI

**Additional information you deem important (e.g. issue happens only occasionally):**
我按照README_zh.md的安全地暴露内网服务配置依然无效

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/README_zh.md#%E5%AE%89%E5%85%A8%E5%9C%B0%E6%9A%B4%E9%9C%B2%E5%86%85%E7%BD%91%E6%9C%8D%E5%8A%A1

不是 `secret_name`。
