### ISSUE TITLE
[Feature Request] show custom domains and service description on dashboard ui

### ISSUE THREAD

**Issue by mcxiaoke** [fatedier/frp#1426]
1. show custom domain or sub domain for http service on dashboard ui.
2. set servicde description in frpc.ini and show it on dashboard ui.
3. show last active time of service on dashboard ui. 
4. show local_port:remote_port, not only remote_port on dashboard ui.
5. show service last visitor ip on dashboard ui.

t's convenient for people who have a lot of services, thanks.

**Comment by fatedier** [comment]
1. Already exist
2. Meta info for proxy, TODO
3. Already exist
4. local port not send to frps, so we can't display it on server dashboard but you can see it on client dashboard.
5. No plan now.
