### ISSUE TITLE
能否支持tcp的正向代理

### ISSUE THREAD

**Issue by vinkdong** [fatedier/frp#1428]
Hi, 服务器中有两个数据库地址， 服务器对外开放了一个端口，frp能否将本地的两个端口与服务器上的两个数据库地址做映射呢。

自己在服务器上和本机都起了frps和frpc实现了这个效果，但是感觉有些麻烦
![image](https://user-images.githubusercontent.com/10599904/64318954-db013900-cfed-11e9-986a-231d2350aab7.png)

**Comment by weinre** [comment]
### ### ### ### ### **_[](url)_**

**Comment by fatedier** [comment]
可以尝试 stcp。

**Comment by vinkdong** [comment]
@fatedier 了解了 👍
