### ISSUE TITLE
How to exit when there is no internet connection

### ISSUE THREAD

**Issue by luo3300612** [fatedier/frp#1430]
Firstly, thank you for your repo,
I found that frp will continue to reconnect when internet connection failed
However, I don't want it to reconnect, instead, I want the process will end in this situation
And I could't find this option in `--help`
how to achieve this?

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/conf/frpc_full.ini#L46

`login_fail_exit = true` can only decide if exit program when first login failed.

After login succeed, it will always reconnect to server when failed. You can stop it manually.

**Comment by luo3300612** [comment]
thanks
