### ISSUE TITLE
无法启动服务

### ISSUE THREAD

**Issue by MuMu360121** [fatedier/frp#1431]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
26.0

**What operating system and processor architecture are you using (`go env`)?**
Ubuntu 18.04 Amd64

**Configures you used:**
`[common]
bind_addr = 0.0.0.0
bind_port = 7000
bind_udp_port = 7001
kcp_bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
dashboard_addr = 0.0.0.0
dashboard_port = 7034
dashboard_user = admin
dashboard_pwd = lisong@2019     //这里设置你的管理面板密码
log_file = ./frps.log
log_level = info
log_max_days = 3
token = lisong@2019       //这里设置你的frp token
allow_ports = 2000-3000,3001,3003,4000-50000
max_pool_count = 50
max_ports_per_client = 0
subdomain_host = frps.com
tcp_mux = true
`

**Steps to reproduce the issue:**
sudo systemctl status frps

**Describe the results you received:**
`root@xiaolee:~#sudo systemctl status frps
● frps.service - frps service
   Loaded: loaded (/lib/systemd/system/frps.service; enabled; vendor preset: ena
   Active: failed (Result: exit-code) since Fri 2019-09-06 12:46:36 UTC; 10s ago
  Process: 15328 ExecStart=/usr/local/frps/frps -c /root/frps/frps.ini //启动服
 Main PID: 15328 (code=exited, status=203/EXEC)

Sep 06 12:46:36 xiaolee.ml systemd[1]: Started frps service.
Sep 06 12:46:36 xiaolee.ml systemd[1]: frps.service: Main process exited, code=e
Sep 06 12:46:36 xiaolee.ml systemd[1]: frps.service: Failed with result 'exit-co
lines 1-9/9 (END)...skipping...
● frps.service - frps service
   Loaded: loaded (/lib/systemd/system/frps.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-09-06 12:46:36 UTC; 10s ago
  Process: 15328 ExecStart=/root/frps/frps -c /root/frps/frps.ini //启动服务的命令（此处写你的frps的实际安装目录） (code=exited, status=203/EXEC)
 Main PID: 15328 (code=exited, status=203/EXEC)

Sep 06 12:46:36 xiaolee.ml systemd[1]: Started frps service.
Sep 06 12:46:36 xiaolee.ml systemd[1]: frps.service: Main process exited, code=exited, status=203/EXEC
Sep 06 12:46:36 xiaolee.ml systemd[1]: frps.service: Failed with result 'exit-code'.`

**Describe the results you expected:**
服务正常启动

**Additional information you deem important (e.g. issue happens only occasionally):**
试过很多次都无效

**Comment by MuMu360121** [comment]
it's solved by edit again

**Comment by ZyanWlayor** [comment]
???
