### ISSUE TITLE
Dashboard 的认证是否可以关闭？

### ISSUE THREAD

**Issue by Yrr0r** [fatedier/frp#1433]
访问frps的dashboard的时候会要求HTTP认证，这个功能用在希望反向代理dashboard页面的时候比较麻烦，是否可以直接不认证就进入dashboard页面，以方便反向代理该页面？

PS：折腾好久了也没法用nginx反代frps的dashbaord，有人弄成功了可以上传一个示例配置吗
#1262

**Comment by fatedier** [comment]
```ini
dashboard_user =
dashboard_pwd =
```

这两个都设置为空就没有鉴权。

nginx 反代 Basic Auth 服务: [google](https://www.google.com/search?newwindow=1&sxsrf=ACYBGNRkDdBw9ltoMYAzGMMH3Nd9VCVC1w%3A1567997747200&source=hp&ei=M791XcryCcHJ-gS_66HoBA&q=nginx+反向代理+auth&oq=nginx+反向代理+auth&gs_l=psy-ab.3...224.4162..4586...0.0..1.491.5645.2-9j8j1......0....1..gws-wiz.......0j35i39j0i203j0i12j0i30j0i4i30.5WHs_7C9Rm4&ved=0ahUKEwiK2Onl3sLkAhXBpJ4KHb91CE0Q4dUDCAU&uact=5)

多利用搜索引擎，学习了解下 nginx 的相关用法以及 Basic Auth 的原理，磨刀不误砍柴工。

**Comment by Yrr0r** [comment]
多谢指教
