### ISSUE TITLE
自写windows客户端脚本工具

### ISSUE THREAD

**Issue by bajins** [fatedier/frp#1434]
- 会判定本地`frpc.exe`是否为最新版本，如果不是或不存在会自动下载
- 只需输入自定义二级域名和本地端口即可映射

> 免费使用！禁止用于非法用途！

https://www.bajins.com/files/frpc.bat

**Comment by zhoujie123** [comment]
访问404

**Comment by woytu** [comment]
部署gihub page时部署错误，已修正

**Comment by vc1** [comment]
> 部署 gihub page 时部署错误，已修正

还是404

**Comment by woytu** [comment]
> > 部署 gihub page 时部署错误，已修正
> 
> 还是404

已迁移页面到VPS菜单下 https://www.bajins.com/VPS/%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F.html#%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%84%9A%E6%9C%AC

**Comment by QQ2017** [comment]
这个BAT在Windows下根本无法执行，是使用姿势错误吗？

**Comment by woytu** [comment]
> 这个BAT在Windows下根本无法执行，是使用姿势错误吗？

由于git会在提交时更改换行符，Windows系统使用的换行符是CRLF ,UNIX/LINUX系统使用的换行符是LF，当你在提交文件时，它又试图将 CRLF 替换为 LF。

综合上述，下载下来的bat脚本需要自己更改换行符格式

**Comment by QQ2017** [comment]
> > 这个BAT在Windows下根本无法执行，是使用姿势错误吗？
> 
> 由于git会在提交时更改换行符，Windows系统使用的换行符是CRLF ,UNIX/LINUX系统使用的换行符是LF，当你在提交文件时，它又试图将 CRLF 替换为 LF。
> 
> 综合上述，下载下来的bat脚本需要自己更改换行符格式


谢谢 可以运行
