### ISSUE TITLE
frps单服务器最多可以支持多少个frpc客户端同时连接啊？

### ISSUE THREAD

**Issue by lingdu0001** [fatedier/frp#1437]
如题

**Comment by funnypro** [comment]
为啥不好好看文档

**Comment by lingdu0001** [comment]
> 为啥不好好看文档

文档里面没有的啊 文档我看过好多次的

**Comment by funnypro** [comment]
> > 为啥不好好看文档
> 
> 文档里面没有的啊 文档我看过好多次的

假设是理论的最多客户端可能真的没有记录
似乎也不能指定客户端上限？

**Comment by funnypro** [comment]
我个人建议先开一下
或许往后有支持设置最多连接客户端？

**Comment by funnypro** [comment]
我个人认为这个也算是一个很重要的功能了
就像客户端不能改配置的需求一样

**Comment by fatedier** [comment]
无数个，没有限制。
