### ISSUE TITLE
connect to server failed!

### ISSUE THREAD

**Issue by 13141113876** [fatedier/frp#144]
2016/10/24 18:42:06 [main.go:109] [I] Start frpc success
2016/10/24 18:42:06 [control.go:181] [E] ProxyName [web], start proxy error, ProxyName [web], authorization timeout
2016/10/24 18:42:06 [control.go:39] [E] ProxyName [web], connect to server failed!
2016/10/24 18:42:06 [main.go:112] [W] All proxy exit!

**Comment by fatedier** [comment]
服务器和客户端上的时间相差超过了15分钟，会报这个错。

**Comment by 13141113876** [comment]
问题已经解决，多谢
