### ISSUE TITLE
如何实现本地端口转发的功能

### ISSUE THREAD

**Issue by djerrystyle** [fatedier/frp#1440]
1. 内网主机A能访问外网主机B的FRP监听端口
2. A希望走FRP(利用加密和压缩的功能)的通道访问B的另外多个端口
3. 实现效果, (1) 减少B对外的暴露端口面 (2) 防止中间人对流量协议的识别

thanks

**Comment by funnypro** [comment]
多创建几个连接试试？

**Comment by funnypro** [comment]
再看了下，我个人推荐使用 stcp 来处理

**Comment by djerrystyle** [comment]
> 再看了下，我个人推荐使用 stcp 来处理

感谢,相当于在服务器上启用 FRPS+FRPC ,然后客户端启用FRPC, 实现点对点的访问

**Comment by funnypro** [comment]
> > 再看了下，我个人推荐使用 stcp 来处理
> 
> 感谢,相当于在服务器上启用 FRPS+FRPC ,然后客户端启用FRPC, 实现点对点的访问

假设临时使用的话，似乎可以通过 ssh 的端口转发来处理的样子

**Comment by djerrystyle** [comment]
> > > 再看了下，我个人推荐使用 stcp 来处理
> > 
> > 
> > 感谢,相当于在服务器上启用 FRPS+FRPC ,然后客户端启用FRPC, 实现点对点的访问
> 
> 假设临时使用的话，似乎可以通过 ssh 的端口转发来处理的样子

ssh的重拨不是很方便,而且在路由器上frp运行的更兼容
