### ISSUE TITLE
frps0.29,ftpc0.29  windows x64 start error: xtcp is not supported in frps,login to server failed: authorization failed authorization failed

### ISSUE THREAD

**Issue by xiaoconsh** [fatedier/frp#1441]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frps0.29,ftpc0.29

**What operating system and processor architecture are you using (`go env`)?**
windows 8.1 X64 frps 

windows 10 ltsb x64 frpc

**Configures you used:**

```ini
[common]
# A literal address or host name for IPv6 must be enclosed
# in square brackets, as in "[::1]:80", "[ipv6-host]:http" or "[ipv6-host%zone]:80"
server_addr = ****
server_port = 7000

# for authentication
token = 12345678

# enable health check for the backend service, it support 'tcp' and 'http' now
# frpc will connect local service's port to detect it's healthy status
health_check_type = tcp
# health check connection timeout
health_check_timeout_s = 3
# if continuous failed in 3 times, the proxy will be removed from frps
health_check_max_failed = 3
# every 10 seconds will do a health check
health_check_interval_s = 10

[tcp]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 6000
[secret_tcp]
# If the type is secret tcp, remote_port is useless
# Who want to connect local port should deploy another frpc with stcp proxy and role is visitor
type = stcp
# sk used for authentication for visitors
sk = abcdefg
local_ip = 127.0.0.1
local_port = 3389
use_encryption = false
use_compression = false
[p2p_tcp]
type = xtcp
sk = abcdefg
local_ip = 127.0.0.1
local_port = 4899
use_encryption = false
use_compression = false

[common]
# A literal address or host name for IPv6 must be enclosed
# in square brackets, as in "[::1]:80", "[ipv6-host]:http" or "[ipv6-host%zone]:80"
bind_addr = *.*.*.*
bind_port = 7000

# udp port to help make udp hole to penetrate nat
bind_udp_port = 7001

# udp port used for kcp protocol, it can be same with 'bind_port'
# if not set, kcp is disabled in frps
kcp_bind_port = 7000

# auth token
token = 12345678

# set dashboard_addr and dashboard_port to view dashboard of frps
# dashboard_addr's default value is same with bind_addr
# dashboard is available only if dashboard_port is set
dashboard_addr = *.*.*.*
dashboard_port = 7500

# dashboard user and passwd for basic auth protect, if not set, both default value is admin
dashboard_user = admin
dashboard_pwd = admin
```

**Steps to reproduce the issue:**
1.    frps.exe frps_full.ini
2.    .\frpc.exe -c .\frpc_full.ini
3.

**Describe the results you received:**
2019/09/19 10:34:27 [I] [service.go:139] frps tcp listen on 0.0.0.0:7000
2019/09/19 10:34:27 [I] [root.go:205] Start frps success

**Describe the results you expected:**
2019/09/19 10:34:52 [E] [service.go:228] authorization failed
2019/09/19 10:34:52 [W] [service.go:86] login to server failed: authorization failed
authorization failed

然后把frpc里的
# for authentication
#token = 12345678
密码注释掉
再启动，显示
    2019/09/19 10:36:06 [I] [service.go:234] login to server success, get run id [f337e01248ea45a2], server udp port [0]
2019/09/19 10:36:06 [I] [proxy_manager.go:144] [f337e01248ea45a2] proxy added: [tcp secret_tcp p2p_tcp]
2019/09/19 10:36:06 [I] [control.go:153] [tcp] start proxy success
2019/09/19 10:36:06 [I] [control.go:153] [secret_tcp] start proxy success
2019/09/19 10:36:06 [W] [control.go:151] [p2p_tcp] start error: xtcp is not supported in frps
frps 端显示
2019/09/19 10:36:03 [I] [service.go:356] client login info: ip [*.*.*.*:5
8895] version [0.29.0] hostname [] os [windows] arch [amd64]
2019/09/19 10:36:03 [I] [tcp.go:65] [f337e01248ea45a2] [tcp] tcp proxy listen po
rt [6000]
2019/09/19 10:36:03 [I] [control.go:406] [f337e01248ea45a2] new proxy [tcp] succ
ess
2019/09/19 10:36:03 [I] [stcp.go:34] [f337e01248ea45a2] [secret_tcp] stcp proxy
custom listen success
2019/09/19 10:36:03 [I] [control.go:406] [f337e01248ea45a2] new proxy [secret_tc
p] success
2019/09/19 10:36:03 [E] [xtcp.go:35] [f337e01248ea45a2] [p2p_tcp] udp port for x
tcp is not specified.
2019/09/19 10:36:03 [W] [control.go:403] [f337e01248ea45a2] new proxy [p2p_tcp]
error: xtcp is not supported in frps
2019/09/19 10:36:33 [E] [xtcp.go:35] [f337e01248ea45a2] [p2p_tcp] udp port for x
tcp is not specified.
2019/09/19 10:36:33 [W] [control.go:403] [f337e01248ea45a2] new proxy [p2p_tcp]
error: xtcp is not supported in frps

frpc设置了密码，不能启动，不设置密码，能启动，也能使用，等于服务端密码没起作用
frpc xtcp不能用
dashboard 7500 端口用浏览器不能登录，显示连接被拒绝，防火墙都是设置了通行的
端口设置问题：local_port = 3389,4899
                         remote_port = 6000,6001
Parse conf error: proxy [tcp] local_port error
多端口设置不能启动，用(-)或者(,)都不能启动，一启动就报错，以上设置测试frps一致

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
* 请按照说明文档使用、调试、测试。
* 先使用最简单的配置测试，逐渐试验新功能，不熟悉的配置先不要添加。
* frps.exe 需要通过 -c 参数指定配置文件。
