### ISSUE TITLE
frpc在32位xp系统不能正常运行的问题

### ISSUE THREAD

**Issue by anythinging** [fatedier/frp#1442]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.25-0.29 i386版

**What operating system and processor architecture are you using (`go env`)?**
xp 32bit sp3

**Configures you used:**
直接运行frpc.exe，使用官方fprc.ini

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
运行后的提示信息
panic: Failed to find GetFileInformationByHandleEx procedure in kernel32.dll: Th
e specified procedure could not be found.

goroutine 1 [running]:
syscall.(*LazyProc).mustFind(0x118358e0)
        /home/wcl/.gvm/gos/go1.12.7/src/syscall/dll_windows.go:311 +0x42
syscall.(*LazyProc).Addr(0x118358e0, 0xcbba00)
        /home/wcl/.gvm/gos/go1.12.7/src/syscall/dll_windows.go:318 +0x21
internal/syscall/windows.GetFileInformationByHandleEx(0x78c, 0x9, 0x1185bdc0, 0x
8, 0x3, 0x1181a048)
        /home/wcl/.gvm/gos/go1.12.7/src/internal/syscall/windows/zsyscall_window
s.go:385 +0x27
os.newFileStatFromGetFileInformationByHandle(0x84fc56, 0xa, 0x78c, 0x0, 0x84fc56
, 0xa)
        /home/wcl/.gvm/gos/go1.12.7/src/os/types_windows.go:52 +0x135
os.(*File).Stat(0x11806a90, 0x9184b8, 0x11806a90, 0x0, 0x11806a90)
        /home/wcl/.gvm/gos/go1.12.7/src/os/stat_windows.go:55 +0x133
io/ioutil.ReadFile(0x84fc56, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/wcl/.gvm/gos/go1.12.7/src/io/ioutil/ioutil.go:62 +0xac
github.com/fatedier/frp/models/config.GetRenderedConfFromFile(0x84fc56, 0xa, 0x3
, 0x3, 0x3, 0x2)
        /home/wcl/go_projects/src/github.com/fatedier/frp/models/config/value.go
:56 +0x2d
github.com/fatedier/frp/cmd/frpc/sub.runClient(0x84fc56, 0xa, 0x11862a80, 0x84e3
23)
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:1
73 +0x2d
github.com/fatedier/frp/cmd/frpc/sub.glob..func4(0xcb7700, 0xccc188, 0x0, 0x0, 0
x0, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:9
2 +0x40
github.com/fatedier/frp/vendor/github.com/spf13/cobra.(*Command).execute(0xcb770
0, 0x11806160, 0x0, 0x0, 0xcb7700, 0x11806160)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/spf1
3/cobra/command.go:762 +0x337
github.com/fatedier/frp/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xcb77
00, 0x0, 0xcb7d40, 0x780a24)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/spf1
3/cobra/command.go:852 +0x244
github.com/fatedier/frp/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/spf1
3/cobra/command.go:800
github.com/fatedier/frp/cmd/frpc/sub.Execute()
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:1
02 +0x24
main.main()
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frpc/main.go:27 +0
x37
**Can you point out what caused this issue (optional)**

**Comment by anythinging** [comment]
我想是否系统缺少某种必要的运行库？还请指点，谢谢！

**Comment by ysc3839** [comment]
https://github.com/golang/go/wiki/MinimumRequirements#windows
Golang 1.11 开始已不支持 XP。

**Comment by lbbboy** [comment]
[支持XP 2003](https://www.lanzous.com/i7cq1wd
)
我也有需求，同步最新源码编译的。

**Comment by uziyuan** [comment]
那最新的版本,是无法使用XP ro 2003 系统了么

**Comment by zzzshanghai** [comment]
同样的问题，我用的是win2003，0.25版开始无法正常使用。
