### ISSUE TITLE
[FEATURE REQUEST] ipv6 support

### ISSUE THREAD

**Issue by qiangbro** [fatedier/frp#1444]
希望配置参数中的 server_addr 支持ipv6格式的地址

**Comment by fatedier** [comment]
请先测试能否支持。

**Comment by qiangbro** [comment]
已测试。
目前不支持在配置文件中配置ipv6格式的ip地址。
读取配置文件时会直接报错：
![image](https://user-images.githubusercontent.com/4646469/67255953-3c566c00-f4b7-11e9-8ae8-4bb397a968fd.png)

**Comment by fatedier** [comment]
示例配置中有格式说明，可以从文档中找到详细配置说明的链接查看。

**Comment by qiangbro** [comment]
按照格式配置，测试通过。

**Comment by fangzy97** [comment]
> 按照格式配置，测试通过。

老哥，能问下你是怎么配置的吗，我在实例里没有找到例子

**Comment by qiangbro** [comment]
注意格式的说明
看frpc-full.ini
A literal address or host name for IPv6 must be enclosed in square brackets
![image](https://user-images.githubusercontent.com/4646469/211955538-c7d283b4-a11c-4a81-896d-3b2b1a917c6c.png)

**Comment by fangzy97** [comment]
感谢，已经解决了
