### ISSUE TITLE
frp 0.29.0 打开页面问题

### ISSUE THREAD

**Issue by ausers** [fatedier/frp#1445]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.29.0

**What operating system and processor architecture are you using (`go env`)?**
server：CentOS 7.6 64位
PC：Windows 10

**Configures you used:**
frps.ini:
[common]
bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443

frpc.ini:
[common]
server_addr = ip
server_port = 7000

[web]
type = http
local_ip = 127.0.0.1
local_port = 8096
custom_domains = xxx.xxx

[web2]
type = https
local_ip = 127.0.0.1
local_port = 8096
custom_domains = xxx.xxx

**Steps to reproduce the issue:**
1. 根据以上配置启动服务端和客户端
2. 在浏览器分别以IP和域名方式访问
3. 均返回frp404，其中域名不加主机名www时（强制https了），连接会被重置

**Describe the results you received:**
访问时提示frp的404页

**Describe the results you expected:**
正常访问位于8096端口的Emby服务

**Additional information you deem important (e.g. issue happens only occasionally):**
一些一键化工具（如花生壳）是能成功建立连接的，所以，我确定这应该是我的配置问题
由于先前对此了解不多，相关配置很多概念目前还较模糊

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
你 http 和 https 服务都是一个本地端口？

https 服务就用 https，http 服务就用 http，不用配两个。

**Comment by ausers** [comment]
通过IP打开仍为404
服务端提示：
[W] [http.go:95] do http proxy request error: no such domain: 服务器IP /

设置已简化到
frps：
[common]
bind_port = 7000
vhost_http_port = 80

frpc：
[common]
server_addr = 服务器IP
server_port = 7000
[web]
type = http
local_ip = 127.0.0.1
local_port = 8096
custom_domains = 我的域名

**Comment by ausers** [comment]
> 你 http 和 https 服务都是一个本地端口？
> 
> https 服务就用 https，http 服务就用 http，不用配两个。

通过IP打开仍为404
服务端提示：
[W] [http.go:95] do http proxy request error: no such domain: 服务器IP /

设置已简化到
frps：
[common]
bind_port = 7000
vhost_http_port = 80

frpc：
[common]
server_addr = 服务器IP
server_port = 7000
[web]
type = http
local_ip = 127.0.0.1
local_port = 8096
custom_domains = 我的域名

**Comment by fatedier** [comment]
HTTP 请求不能通过 IP 访问，需要用你设置的域名来访问。
