### ISSUE TITLE
Https does not work in reverse proxy

### ISSUE THREAD

**Issue by ilyaborodin** [fatedier/frp#1447]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.29 both

**What operating system and processor architecture are you using (`go env`)?**
server- ubuntu
client - windows 10

**Configures you used:**
frps
[common]
bind_port = 7000
vhost_http_port = 7001
vhost_https_port = 7002

frpc
[common]
server_addr = 217.61.xxx.xxx
server_port = 7000
protocol = tcp

[web02]
type = https
local_port = 443
local_ip = vk.com
use_encryption = false
use_compression = true
custom_domains = vk.com
proxy_protocol_version = v2

**Steps to reproduce the issue:**
1. ./frps -c frps.ini on server
2. frpc -c frpc.ini on client
3. connect to vhost_https from browser using 7002 port

**Describe the results you received:**
2019/09/26 13:52:19 [W] [vhost.go:134] get hostname from http/https request error: readHandshake: type[67] is not clientHello
2019/09/26 13:52:19 [W] [vhost.go:134] get hostname from http/https request error: readHandshake: type[67] is not clientHello
2019/09/26 13:52:19 [W] [vhost.go:134] get hostname from http/https request error: readHandshake: type[67] is not clientHello
2019/09/26 13:52:19 [W] [vhost.go:134] get hostname from http/https request error: readHandshake: type[67] is not clientHello

**Describe the results you expected:**
good work

**Additional information you deem important (e.g. issue happens only occasionally):**
I need to reverse the proxy server. Http sites works well, but with https sites there is a problem. Help is needed

**Can you point out what caused this issue (optional)**
--

**Comment by fatedier** [comment]
Which browser and version ?
