### ISSUE TITLE
客户端无法开启自启动

### ISSUE THREAD

**Issue by ghsa1994** [fatedier/frp#145]
树莓派平台，无论是在rc.local中还是init.d中写脚本都是无法正常启动，服务端在vps的 Centos 6 x86上的rc.local就能成功自启动，树莓派在家里，没有保证的7*24小时供电！求协助！

**Comment by jiangchao0304** [comment]
`#!/bin/sh
### BEGIN INIT INFO
# Provides:          frpc
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: frpc
# Description:
# https://github.com/fatedier/frp 
# 保存为 frpc 到/etc/init.d
# 注册为服务 update-rc.d frpc defaults
### END INIT INFO


NAME=frpc
DAEMON=/opt/frp/$NAME
CONFIG=/opt/frp/myfrpc.ini

[ -x "$DAEMON" ] || exit 0

case "$1" in
  start)
    echo "Starting $NAME..."
   start-stop-daemon --start --chuid pi --exec $DAEMON --quiet --oknodo --background -- -c $CONFIG  || return 2
    ;;
  stop)
    echo "Stopping $NAME..."
    start-stop-daemon --stop --exec $DAEMON --quiet --oknodo --retry=TERM/30/KILL/5 || return 2
    ;;
  restart)
    $0 stop && sleep 2 && $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
exit 0
`

自己pi用的 拿走不谢

**Comment by DDelon** [comment]
sudo -u 用户名 再加命令也可以
