### ISSUE TITLE
https2http返回header里的Location 值没有将http改为 https 的问题

### ISSUE THREAD

**Issue by schunlei** [fatedier/frp#1450]
使用版本：V0.29

部分配置如下：
[httpssss]
type=https
subdomain=nc
header_security=https
plugin=https2http
plugin_local_addr= 127.0.0.1:80
plugin_crt_path = *******
plugin_key_path= ******
plugin_header_X-From-Where = frp

情况说明：

使用docker上的安装的nextcloud，访问时，会首先使用返回302状态，返回的header里有location,如下：
Location:**http**://nc.*******/apps/files/
上面应该 是 https 而不应该出现 http

这种情况有办法解决么？

**Comment by fatedier** [comment]
如果本地服务是你自己的，你自己可以修改这个 location 的内容为 https。

还可以将访问 http 的内容再重新 302 到 https。
