### ISSUE TITLE
Compression and encryption not functioning on OpenWRT device

### ISSUE THREAD

**Issue by AngelFalse** [fatedier/frp#1454]
**What version of frp are you using (./frpc -v or ./frps -v)?**
frp server: 0.28.x (unknown/升级之前没注意) - 0.29.0
frp client 1: 0.28.2-0.29.0
frp client 2: 0.28.2

**What operating system and processor architecture are you using (`go env`)?**
frp server: unknown (irrelevant/应该与此无关), probably a vps.
frp client 1: OpenWRT Barrier Breaker 14.07 (go isn't installed) / ARMv7l
frp client 2: a Debian derivative based on debian 9/ ARMv7l / Raspberry Pi

**Configures you used:**
client 1: https://www.verybin.com/?7b1951d8ef9deef3#L6hs6jQIQa/YxUudkwu7rJHnShR/y+VSoowHY5p1MRE=
client 2: https://www.verybin.com/?47975707d961b0de#OHplqXJq8vglylmBUhdqTB4L7J3GsTcCL5a/3DaDG7g=
(Both of these two pastebin links expires in one month)

**Steps to reproduce the issue:**
Just the normal step to set up a frp client on both device

**Describe the results you received:**
On the server panel, shows client 1 and 2, but status of client 1's port forwarding shows "Compression" and "Encryption" as false (though enabled explicitly in the config file), client 2 shows both as true, as expected.

**Describe the results you expected:**
Both of the client has Compression and Encryption enabled, as written in the config file.

**Screenshots**
Client 1 on server panel:
https://s2.ax1x.com/2019/10/05/usjHJJ.png
Client 2 on server panel:
https://s2.ax1x.com/2019/10/05/usvkQI.png

**Comment by fatedier** [comment]
I have no device to test this problem. Can you build the source code and debug where is the problem ?

**Comment by qiang-yu** [comment]
应该是你的路由器没有FPU单元（浮点运算单元），你的 OpenWrt 系统没有编译 模拟FPU计算模块，只是弄了个空的FPU模拟，所以没法做加密运算， 低端路由器不带FPU的都有类似的问题

要么，你重新编译OpenWrt系统，记得勾选上内核FPU模拟，这样任何需要做加密的运算由内核模拟完成

要么，你重新编译frp，采用 softfloat，让 frp 自己模拟 FPU运算，不需要系统的FPU支持

建议，自己重新编译 frp ，go里面打开softfloat， 这比你去编译 OpenWrt 要容易很多

你可以参考另外一个开源项目 v2ray 的编译说明，也是要做数据加密，它们release专门为路由器发布了 softfloat 版本

**Comment by AngelFalse** [comment]
好的，谢谢告知
