### ISSUE TITLE
内网centos7搭建nextcloud,通过frp穿透,nextcloud安卓手机上传权限错误

### ISSUE THREAD

**Issue by shadoweb** [fatedier/frp#1456]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
使用的为frp_0.29.0_linux_amd64.tar.gz

**What operating system and processor architecture are you using (`go env`)?**
服务端和客户端环境均为centos7

**Configures you used:**
配置均为默认的,只更改了服务端的IP和客户端的端口

**Steps to reproduce the issue:**
1.内网centos7搭建nextcloud,
2.VPS中安装frp服务端,内网安装frp客户端,进行http穿透
3.nextcloud安卓版手机APP配置登录(分两种情况)
3.1手机使用内网或外网,APP通过FRP穿透的域名,上传提示权限错误,无法上传成功
3.2手机使用内网网络,APP通过内网IP地址可以正常上传成功

**Describe the results you received:**
**nextcloud安卓版手机APP,同样情况,在内网通过IP可以上传,在内网或外网通过穿透的域名不能上传.**
**网页方式都可以上传,没有问题.**

**Describe the results you expected:**
希望能解决"通过FRP穿透的域名上传提示权限错误,无法上传成功"这个问题

**Additional information you deem important (e.g. issue happens only occasionally):**
在nextcloud中可以看到连接日志中有这一句
127.0.0.1 - 用户名 [10/Oct/2019:08:17:28 +0800] "GET /remote.php/webdav/Photos/2019/10/IMG_20191010_075831.jpg HTTP/1.1" 404 233 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.8.0"
这是我测试上传的文件时产生的对应日志.
**Can you point out what caused this issue (optional)**
可以看出nextcloud安卓版手机APP是通过webdav上传文件的.
怀疑是通过FRP穿透的域名使用webdav时,权限有问题.

**Comment by fatedier** [comment]
这种问题一般和应用自身的安全策略有关，比如仅允许内网直接访问等，可以尝试研究下 nextcloud 有无这方面的配置项。

**Comment by shadoweb** [comment]
> 这种问题一般和应用自身的安全策略有关，比如仅允许内网直接访问等，可以尝试研究下 nextcloud 有无这方面的配置项。

感谢回复,
我也考虑过这个问题.
目前的情况理一下就几种情况
1.FRP穿透
1.1内网--APP--IP登录--内网--成功
1.2内网/外网--APP--域名登录--FRPS--FRPC--内网--失败
2.服务器搭建
内网/外网--APP--域名登录--成功

从日志中可以看出
nextcloud安卓版手机APP是通过webdav上传文件的.

然后可以简单理解成这样
1.FRP穿透
1.1内网--webdav--IP登录--内网--成功
1.2内网/外网--webdav--域名登录--FRPS--FRPC--内网--失败

只是感觉是不是跟webdav有关,因为APP上传的信息已经通过FRP到达了,只是经过FRP时,会没有权限.

不知道是不是可以这样理解.

我再单独测试一下webdav,看会不会有权限问题.

还有个情况,我是通过http连接的,我再测试一下https会不会有这情况.

以上,感谢.
后续情况我再写进来.

**Comment by WatsonWangSZ** [comment]
留意frp的域名与内网都要配置到nextcloud的配置内

**Comment by shadoweb** [comment]
> 留意frp的域名与内网都要配置到nextcloud的配置内

感谢,这个是配置过的.

经过近期的测试.没发现具体原因.
配置的自动上传的图片和视频可以正常自动上传.
部分文件有时候会出错.
暂时先这样使用了.
不再细究.

**Comment by Milokita** [comment]
> 
> 
> > 留意frp的域名与内网都要配置到nextcloud的配置内
> 
> 感谢,这个是配置过的.
> 
> 经过近期的测试.没发现具体原因.
> 配置的自动上传的图片和视频可以正常自动上传.
> 部分文件有时候会出错.
> 暂时先这样使用了.
> 不再细究.

你这个应该不会是frp的问题，我一直用的是FRP暴露NEXTCLOUD没有出现问题。 你的配置文件看看

**Comment by shadoweb** [comment]
> > > 留意frp的域名与内网都要配置到nextcloud的配置内
> > 
> > 
> > 感谢,这个是配置过的.
> > 经过近期的测试.没发现具体原因.
> > 配置的自动上传的图片和视频可以正常自动上传.
> > 部分文件有时候会出错.
> > 暂时先这样使用了.
> > 不再细究.
> 
> 你这个应该不会是frp的问题，我一直用的是FRP暴露NEXTCLOUD没有出现问题。 你的配置文件看看

感谢回复.
我的配置没有问题.上面有说过,内网进行上传没有问题的.内网使用web方式也没问题.经测试使用webdav的连接方式,部分nextcloud的客户端版本有问题(nextcloud的客户端就是使用webdav连接的).
经过一段时间使用.
现可以得出结论.跟frp无关.
使用foldersync同步正常.
使用nextcloud的客户端
在F-Droid里最新版有问题.
换回3.3.1版可以使用.
经测试,软件都是使用webdav方式连接的.

然后我家里的路由器换成两个H3C B5进行组网,稳定网速.

现在体验良好.没发现问题.

可以得出结论.nextcloud的部分版本的兼容性不太好.

**Comment by shadoweb** [comment]
这个结贴.这个问题的主要点是通过frp后的域名,使用nextcloud安卓客户端进行连接,有上传权限错误的问题.
然后通过更换nextcloud安卓客户端低版本解决问题.
使用foldersync同步也可解决问题.

给有兴趣或相关问题的同学作参考.

最后,感谢FRP开发人员.
致敬.
