### ISSUE TITLE
有没办法在KCP模式上增加一个tcp伪装

### ISSUE THREAD

**Issue by keeno1982** [fatedier/frp#1461]
最近国内运营商对UDP实在QOS太厉害了，就算国内的电信对移动的传输也会一直中断，只要把protocol = kcp禁用掉就正常了，显然是QOS在作祟。
如果能用到类似udp2raw这类的伪装逃过QOS，那就太好了

**Comment by lazy-luo** [comment]
udp2raw-tunnel不是太稳定性，而且极大降低传输速率，还不如直接tcp。

**Comment by keeno1982** [comment]
@lazy-luo 实际上我只是想要一个tcp的伪装效果并非真要套udp2raw，就像最新版的kcptun有个tcp模式，类似这个效果。我这边套了udp2raw确实会损失部分速度，不过对于直接被QOS还是强百倍，不至于从frp穿透的服务器上下载个文件要断个十几次

**Comment by qiang-yu** [comment]
udp被QOS是个普遍现象， kcptun 很多地方也一样用不了

建议用 websocket （HTTP 协议不会被 QOS），服务器上 BBR 或者 锐速来解决丢包速度慢的问题

**Comment by keeno1982** [comment]
@qiang-yu BBR/锐速和kcptun不是一个级别，我这边小鸡开了BBR或锐速连SSH都费劲，开kcp后就跟打了鸡血一样，下载速度能达到4M，前提必须套udp2raw，不套的话就是下个几秒就断流，非常烦，我觉得这个伪装还是非常有必要的

**Comment by fatedier** [comment]
frp 本身不考虑这些事，可以搭配你想要的其他 proxy 共同使用来完成。
