### ISSUE TITLE
CentOS作为服务端，映射Windows10远程桌面，PC端登录失败，手机端登录正常

### ISSUE THREAD

**Issue by HongLiangGong1990** [fatedier/frp#1463]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.29.0

**What operating system and processor architecture are you using (`go env`)?**
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/gowork"
GOPROXY="https://goproxy.io"
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ghl/goremote/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build880123427=/tmp/go-build -gno-record-gcc-switches"

**Configures you used:**
#frps.ini
[common]
bind_port = 7000

#frpc.ini
[common]
server_addr = 192.168.0.106
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

[rdp]
type = tcp
local_ip = 127.0.0.1
local_port = 8110
remote_port = 8110

**Steps to reproduce the issue:**
1.在CentOS-A上运行./frps -c ./frps.ini后，在同一个局域网的win10-B上运行frpc
2.然后在局域网内的第三台设备C上连接远程桌面，如果C是电脑设备登录远程桌面能进入B桌面，但是卡顿后出现断开连接，C设备卡顿的同时，CentOS-A也出现卡顿，无法输入命令
3.但是如果设备C是iPhone6S时，iPhone 6s能正常远程登录B
4.升级CentOS也会出现同样的问题，但是如果在win10上运行frps，则一切正常
**Describe the results you received:**
添加日志打印后，发现卡顿和断开连接出现在下面这个打印出现之后，
[control.go:190]  RegisterWorkConn

2019/10/14 20:30:33 [I] [service.go:356] client login info: ip [192.168.0.106:6500] version [0.29.0] hostname [] os [windows] arch [amd64]
2019/10/14 20:30:33 [I] [control.go:190]  RegisterWorkConn
2019/10/14 20:30:33 [I] [tcp.go:65] [90eebafc022884df] [ssh] tcp proxy listen port [6000]
2019/10/14 20:30:33 [I] [control.go:406] [90eebafc022884df] new proxy [ssh] success
2019/10/14 20:30:33 [I] [tcp.go:65] [90eebafc022884df] [rdp] tcp proxy listen port [8110]
2019/10/14 20:30:33 [I] [control.go:406] [90eebafc022884df] new proxy [rdp] success
2019/10/14 20:30:49 [I] [proxy.go:84] [90eebafc022884df] [rdp] get a new work connection: [192.168.0.107:6500]
2019/10/14 20:31:03 [I] [control.go:282] [90eebafc022884df] control writer is closing
2019/10/14 20:31:03 [I] [proxy.go:69] [90eebafc022884df] [ssh] proxy closing
2019/10/14 20:31:03 [I] [proxy.go:137] [90eebafc022884df] [ssh] listener is closed
2019/10/14 20:31:03 [I] [proxy.go:69] [90eebafc022884df] [rdp] proxy closing
2019/10/14 20:31:03 [I] [proxy.go:137] [90eebafc022884df] [rdp] listener is closed
2019/10/14 20:31:03 [I] [control.go:358] [90eebafc022884df] client exit success
2019/10/14 20:31:06 [I] [service.go:356] client login info: ip [192.168.0.106:6530] version [0.29.0] hostname [] os [windows] arch [amd64]
2019/10/14 20:31:06 [I] [tcp.go:65] [90eebafc022884df] [rdp] tcp proxy listen port [8110]

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
猜测和机器性能，网络环境有关。

**Comment by Xeath** [comment]
我之前这样映射也没有问题，还试过 CentOS 映射内网主机到 CentOS 服务端上呢

**Comment by xx299x** [comment]
1. `windows`远程桌面的端口如果自己没有更改过应该是`3389`
2. 网络不稳定应该是网络环境的问题。如果服务器是国外服务器，8成就是网络问题了。
```
如果C是电脑设备登录远程桌面能进入B桌面，但是卡顿后出现断开连接，C设备卡顿的同时，CentOS-A也出现卡顿，无法输入命令
```
我觉得应该是显示`A`卡顿，然后才导致设备`C`连接设备`A`卡顿。

3. 可以尝试使用p2p点对点的协议，可以在一定程度内(取决于`B宽带`的上行速度和`C宽带`的下行速度）提高速度。
