### ISSUE TITLE
Windows版frpc最新版本使用代理服务器的问题

### ISSUE THREAD

**Issue by greatbody** [fatedier/frp#1466]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc 0.29.0

**What operating system and processor architecture are you using (`go env`)?**
windows 10

**Configures you used:**

**Steps to reproduce the issue:**

```
[common]
server_addr = xxx.xxx.com
server_port = 8080
http_proxy = http://xxx:pass@xxxxx.com:8123

token = xxxxxxxxxxxxxxxxxx==

[webs]
type = tcp
local_ip = 127.0.0.1
local_port = 8080
remote_port = 8087
```

**Describe the results you received:**
连接异常
login to server failed. service.go(86)

**Describe the results you expected:**

连接正常
**Additional information you deem important (e.g. issue happens only occasionally):**

机器：windows机器，连接在域里面
域账户：ABC/EFG
密码: 1qaz2wsx
代理服务器：abc.xxx.com:8123

已知如果通过IE上网，配置代理地址：abc.xxx.com，端口：8123
可以正常连接外网。

**上述描述的域名，地址，端口，账户，密码均虚构**

**Can you point out what caused this issue (optional)**

**Comment by greatbody** [comment]
Update
我移除了 http_proxy 的配置行
然后执行，报错信息经过脱敏后：
```
2019/10/16 08:55:08 [W] [service.go:86] login to server failed: parse ABCD%5cUSERNAME:12345678%25666@a.b.c.com:4123: first path segment in URL cannot contain colon
parse ABCD%5cUSERNAME:12345678%25666@a.b.c.com:4123: first path segment in URL cannot contain colon
```

**Comment by qiang-yu** [comment]
你是配置信息里面有什么是  中文汉字 吧？
这看着就像是解析出错，应该是中文编码的解析出错，windows中文的编码和 linux 不一样

把所有中文都删除， 如果你的代理账号 XXX 本身就是中文的，那就悲剧了

**Comment by greatbody** [comment]
> 你是配置信息里面有什么是 中文汉字 吧？
> 这看着就像是解析出错，应该是中文编码的解析出错，windows中文的编码和 linux 不一样
> 
> 把所有中文都删除， 如果你的代理账号 XXX 本身就是中文的，那就悲剧了

更新下，前面的报错是缓存的信息，后面尝试后报错不一样。

加上http_proxy 的配置，现在报错是

```
2019/10/16 15:12:32 [W] [service.go:86] login to server failed: DialTcpByHttpProxy error, StatusCode [407]
DialTcpByHttpProxy error, StatusCode [407]
```

Windows通过域账号登录的系统，系统的代理并未配置用户名密码，猜测是否是通过windows独特的方式进行的认证。
请问frp目前支持哪些代理认证协议？
谢谢！

**Comment by fatedier** [comment]
407 是 http proxy 的鉴权失败了。

**Comment by greatbody** [comment]
> 407 是 http proxy 的鉴权失败了。

对，但是windows配置是ok的。我用VB写的一个简单的程序，使用XmlHttp组件，设置使用系统默认代理，可以发出请求。

请问是否可以支持windows的默认代理。而不是现在的显式配置，谢谢！
辛苦了大佬！

**Comment by greatbody** [comment]
> 407 是 http proxy 的鉴权失败了。

另外，支付宝支持了大佬5元，不成敬意。

**Comment by zhaoyc1990** [comment]
> > 407 是 http proxy 的鉴权失败了。
> 
> 另外，支付宝支持了大佬5元，不成敬意。

5元就想贿赂大佬，改变开发进度？

**Comment by fatedier** [comment]
@greatbody 目前支持环境变量和配置文件两种代理设置方式，和具体操作系统无关，不太了解 windows 默认代理是什么。
