### ISSUE TITLE
WIN2003X32系统运行FRPS29.0涉及GetFileInformationByHandleEx错误

### ISSUE THREAD

**Issue by MxCen** [fatedier/frp#1468]
CMD下直接运行FRPS不加任何命令可以启动；

CMD下运行FRPS -c frps.ini就会报如下错误；

已经核实配置文件在win7下正常；

错误内容：

panic: Failed to find GetFileInformationByHandleEx procedure in kernel32.dll: Th
e specified procedure could not be found.

goroutine 1 [running]:
syscall.(*LazyProc).mustFind(0x11845a40)
        /home/wcl/.gvm/gos/go1.12.9/src/syscall/dll_windows.go:311 +0x42
syscall.(*LazyProc).Addr(0x11845a40, 0xd6ea40)
        /home/wcl/.gvm/gos/go1.12.9/src/syscall/dll_windows.go:318 +0x21
internal/syscall/windows.GetFileInformationByHandleEx(0x764, 0x9, 0x11873c64, 0x
8, 0x3, 0x1181b348)
        /home/wcl/.gvm/gos/go1.12.9/src/internal/syscall/windows/zsyscall_window
s.go:385 +0x27
os.newFileStatFromGetFileInformationByHandle(0x1184a088, 0x8, 0x764, 0x0, 0x1184
a088, 0x8)
        /home/wcl/.gvm/gos/go1.12.9/src/os/types_windows.go:52 +0x135
os.(*File).Stat(0x1183aa30, 0x9c1f68, 0x1183aa30, 0x0, 0x1183aa30)
        /home/wcl/.gvm/gos/go1.12.9/src/os/stat_windows.go:55 +0x133
io/ioutil.ReadFile(0x1184a088, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/wcl/.gvm/gos/go1.12.9/src/io/ioutil/ioutil.go:62 +0xac
github.com/fatedier/frp/models/config.GetRenderedConfFromFile(0x1184a088, 0x8, 0
x1f, 0x67e3b5, 0x1185c3c0, 0x1ffffff)
        /home/wcl/go_projects/src/github.com/fatedier/frp/models/config/value.go
:56 +0x2d
main.glob..func1(0xd6adc0, 0x11842610, 0x0, 0x2, 0x0, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frps/root.go:104 +
0x6b
github.com/fatedier/frp/vendor/github.com/spf13/cobra.(*Command).execute(0xd6adc
0, 0x11845aa8, 0x2, 0x3, 0xd6adc0, 0x11845aa8)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/spf1
3/cobra/command.go:762 +0x337
github.com/fatedier/frp/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xd6ad
c0, 0xc83c6fd0, 0x15ce06d0, 0x11844018)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/spf1
3/cobra/command.go:852 +0x244
github.com/fatedier/frp/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/spf1
3/cobra/command.go:800
main.Execute()
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frps/root.go:126 +
0x24
main.main()
        /home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frps/main.go:30 +0
xe6

**Comment by qiang-yu** [comment]
这是找不到系统调用，系统太老了，go 语言都不支持这个系统，

**Comment by ysc3839** [comment]
https://github.com/golang/go/wiki/MinimumRequirements#windows
Golang 1.11 开始已不支持 Windows Server 2003。

**Comment by lazy-luo** [comment]
如需考虑xp-win10全系兼容，估计只能找其它工具了。话说现在仍在使用win7以下系统的还真不多。。。

**Comment by MxCen** [comment]
主要单位的环境必须采用win2003 Server系统。更高系统空间有兼容性问题。看来是没解了。我去测试了下NPS貌似可以，但是NPS太复杂了。

**Comment by funnypro** [comment]
> 主要单位的环境必须采用win2003 Server系统。更高系统空间有兼容性问题。看来是没解了。我去测试了下NPS貌似可以，但是NPS太复杂了。

要不要试试用虚拟机来“绕过”这个问题？

**Comment by lbbboy** [comment]
[https://www.lanzous.com/i7cq1wd
](url)

我也有这样的需求，自己编了最新的。
