### ISSUE TITLE
如何为iOS编译

### ISSUE THREAD

**Issue by the-eric-kwok** [fatedier/frp#1469]
手头有一台iPhone 6s，打算做一个远程下载服务器，发现没有适合在iOS上面运行的二进制文件，直接修改Makefile.cross-compile试着生成 Darwin Arm64 的二进制文件，结果报错：
```
env CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o ./frps_darwin_arm64 ./cmd/frpc# github.com/fatedier/frp/cmd/frpc
/usr/lib/go-1.12/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld：无法识别的选项‘-pagezero_size’
/usr/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status

make: *** [Makefile.cross-compiles:11：app] 错误 2
```

也试过用iOS来编译但是iOS上面的go版本太低了……

**Comment by HaidyCao** [comment]
iOS可以在App Store下载，搜索FRP即可

**Comment by the-eric-kwok** [comment]
我的是越狱的iOS，希望把frp做成一个daemon放在后台运行

**Comment by fatedier** [comment]
可以尝试下 gomobile 这个项目。

**Comment by oliverck** [comment]
> iOS可以在App Store下载，搜索FRP即可

你好，现在在App Store搜不到FRP了，请问是国区下架了吗？请问还能在哪里下载吗？

**Comment by davidoffxw** [comment]
> > iOS可以在App Store下载，搜索FRP即可
> 
> 
> 
> 你好，现在在App Store搜不到FRP了，请问是国区下架了吗？请问还能在哪里下载吗？

我最近也想搞一下iPhone6s的frpc 请问你有编译好嘛？
我在issue里面找到几年前一位用户编译的朋友，但是我运行依旧killed 9
