### ISSUE TITLE
能像ngrok那样显示每个http请的信息吗？

### ISSUE THREAD

**Issue by dxvgef** [fatedier/frp#147]
我是用来做微信端web开发的，需要知道微信服务端和用户都请求了什么，ngrok就可以通过客户端的一个本地端口来显示这些信息，并向内网模拟重新发起请求

**Comment by fatedier** [comment]
后面考虑支持。

**Comment by itcbx** [comment]
不知这么功能实现了没有，对于本地调试开发公众号或微信小程序还是非常有用的

**Comment by vc1** [comment]
可以用frpc的前置代理功能结合whistle/fiddler等抓包工具达到同样的效果
whistle是web gui，还能用另一个frpc转发出去

https://github.com/fatedier/frp/blob/master/README_zh.md#%E9%80%9A%E8%BF%87%E4%BB%A3%E7%90%86%E8%BF%9E%E6%8E%A5-frps
https://github.com/avwo/whistle/blob/master/README-zh_CN.md

**Comment by lunfangyu** [comment]
同样期待此功能

**Comment by natsupan** [comment]
十分期待官方能出此功能

**Comment by loveyu** [comment]
觉得这类功能更适合添加一个HTTP代理服务器来实现，比如：
weixin--->frps---->frpc---->http-proxy--->http-source

这样frpc只要能够支持http的代理服务即可，而http-proxy你就有N总成熟的方案可以选择

**Comment by almas1992** [comment]
> 觉得这类功能更适合添加一个HTTP代理服务器来实现，比如：
> weixin--->frps---->frpc---->http-proxy--->http-source
> 
> 这样frpc只要能够支持http的代理服务即可，而http-proxy你就有N总成熟的方案可以选择

N种成熟的方案能否推荐一二？

**Comment by loveyu** [comment]
> > 觉得这类功能更适合添加一个HTTP代理服务器来实现，比如：
> > weixin--->frps---->frpc---->http-proxy--->http-source
> > 这样frpc只要能够支持http的代理服务即可，而http-proxy你就有N总成熟的方案可以选择
> 
> N种成熟的方案能否推荐一二？

filldder, charles, 这两个可能是用的最多的，其他的实现也有很多

**Comment by kunrui** [comment]
> 可以用frpc的前置代理功能结合whistle/fiddler等抓包工具达到同样的效果
> whistle是web gui，还能用另一个frpc转发出去
> 
> https://github.com/fatedier/frp/blob/master/README_zh.md#%E9%80%9A%E8%BF%87%E4%BB%A3%E7%90%86%E8%BF%9E%E6%8E%A5-frps
> https://github.com/avwo/whistle/blob/master/README-zh_CN.md

这是怎么实现的，不知道怎么配置。没能配置出来。

**Comment by yangguangwuwu** [comment]
这个有计划吗 ？ 四年了

**Comment by CzBiX** [comment]
这个功能交给专业的 HTTP Proxy 工具好了，没必要重复造轮子。
Python 用 mitmproxy，nodejs 用 anyproxy。

**Comment by n0thing2speak** [comment]
> 这个功能交给专业的 HTTP Proxy 工具好了，没必要重复造轮子。
> Python 用 mitmproxy，nodejs 用 anyproxy。

请问如何使用frp转发内网的一个mitmproxy的，手机使用frp的子域名代理，内网就可以进行抓包

**Comment by ryouaki** [comment]
我觉得没必要加这种功能。frp就是单纯的穿透模块。而现实请求信息的功能完全可以借助其他后端的相关组件实现。
