### ISSUE TITLE
请问默认的7000端口，是否可以进行加密传输？

### ISSUE THREAD

**Issue by amd5** [fatedier/frp#1470]
请问默认的7000端口，是否可以进行加密传输？

**Comment by fatedier** [comment]
frpc 和 frps 之间的控制通信本身已加密，如果连接开始的登录信息需要加密，需要启用 TLS。

**Comment by amd5** [comment]
我这边默认走7000  被拦截了。 在frpc.ini 的 common 中配置 tls_enable = true
结果也是失败
提示
2019/10/21 23:19:32 [W] [service.go:82] login to server failed: dial tcp 8.8.8.8:7000: connect: connection timed out


以下是nmap扫描结果
Starting Nmap 6.40 ( http://nmap.org ) at 2019-10-21 23:17 EDT
Nmap scan report for ss3.19aq.com (47.244.90.129)
Host is up (0.16s latency).
PORT     STATE SERVICE
7000/tcp open  afs3-fileserver


Nmap done: 1 IP address (1 host up) scanned in 1.00 seconds





------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年10月22日(星期二) 中午11:03
收件人: "fatedier/frp"<frp@noreply.github.com>; 
抄送: "System"<amd5@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [fatedier/frp] 请问默认的7000端口，是否可以进行加密传输？ (#1470)




Closed #1470.
 
&mdash;

**Comment by fatedier** [comment]
你访问 8.8.8.8 怎么可能成功，server_add 配置有问题。

**Comment by amd5** [comment]
我是假设    8.8.8.8 是我的服务器的外网IP



------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年10月22日(星期二) 中午11:53
收件人: "fatedier/frp"<frp@noreply.github.com>; 
抄送: "System"<amd5@qq.com>; "Manual"<manual@noreply.github.com>; 
主题: Re: [fatedier/frp] 请问默认的7000端口，是否可以进行加密传输？ (#1470)




你访问 8.8.8.8 怎么可能成功，server_add 配置有问题。

**Comment by amd5** [comment]
frpc这台server被FGW封了，能用这个方式绕过么。



------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年10月22日(星期二) 中午11:53
收件人: "fatedier/frp"<frp@noreply.github.com>; 
抄送: "System"<amd5@qq.com>; "Manual"<manual@noreply.github.com>; 
主题: Re: [fatedier/frp] 请问默认的7000端口，是否可以进行加密传输？ (#1470)




你访问 8.8.8.8 怎么可能成功，server_add 配置有问题。

**Comment by fatedier** [comment]
不能。

**Comment by amd5** [comment]
tks




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年10月22日(星期二) 中午12:05
收件人: "fatedier/frp"<frp@noreply.github.com>; 
抄送: "System"<amd5@qq.com>; "Manual"<manual@noreply.github.com>; 
主题: Re: [fatedier/frp] 请问默认的7000端口，是否可以进行加密传输？ (#1470)




不能。
 
&mdash;
