### ISSUE TITLE
arm v7的包怎么下载

### ISSUE THREAD

**Issue by CaiJinHao** [fatedier/frp#1471]
我用的是arm64的包，提示bash: ./frpc: cannot execute binary file: Exec format error

**Comment by ysc3839** [comment]
试试 ARM 的包？

**Comment by CaiJinHao** [comment]
@ysc3839 ARM的包下载地址在哪，我在release里面没有找到ARM的包

**Comment by CaiJinHao** [comment]
@ysc3839 我用arm64的包也不行，提示格式错误

**Comment by ysc3839** [comment]
https://github.com/fatedier/frp/releases/download/v0.29.0/frp_0.29.0_linux_arm.tar.gz

**Comment by CaiJinHao** [comment]
thanks
