### ISSUE TITLE
tcp建议可以配置域名和子域名

### ISSUE THREAD

**Issue by silverspray** [fatedier/frp#1472]
建议tcp可以向http一样可以配置域名和子域名，这样在远程的时候可以用不同的子域名和默认的远程端口（例如：22，3389）

**Comment by qiang-yu** [comment]
http 协议支持域名，每一个 http 链接里面都会带上域名，所以可以识别

tcp 协议本身是不带域名的，无法实现

**Comment by Quaking** [comment]
> http 协议支持域名，每一个 http 链接里面都会带上域名，所以可以识别
> 
> tcp 协议本身是不带域名的，无法实现

像花生壳之类的tcp也可以映射成域名加端口的方式的工作的；后面能配置tcp为域名是最好的了，继续支持。

**Comment by zhaoyc1990** [comment]
没用过花生壳，但frp 也可以域名加端口访问tcp 端口，并且在tcp协议上的http 或https 等都可以使用

**Comment by fatedier** [comment]
TCP 无法支持，域名加端口，也是通过端口来路由，不是通过域名。
只有使用特殊协议通信的 TCP 才能支持，例如 HTTP/HTTPS，或者支持 SNI 协议。
