### ISSUE TITLE
服务器运行一段时间后，出现了大量的端口冲突错误

### ISSUE THREAD

**Issue by f8q8** [fatedier/frp#1473]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frp_0.29.0_linux_amd64

**What operating system and processor architecture are you using (`go env`)?**
CentOS Linux release 7.5.1804 (Core)

**Configures you used:**
[common]
bind_addr = 0.0.0.0
bind_port = xxxx

kcp_bind_port = xxxx

dashboard_port = xxxs

dashboard_user = xxxxxx
dashboard_pwd = xxxxxxxx

vhost_http_port = 11xx
vhost_https_port = 22xx

log_file = ../logs/frps.log
log_level = info
log_max_days = 3

token = xxxxxxxxx

max_pool_count = 50

tcp_mux = true

**Steps to reproduce the issue:**
1.运行了一段时间之后，（所有客户端没有做过任何的变化）服务端出现了大量的端口冲突错误日志，客户端已经无法链接服务端。重启服务端后正常了
2.这种情况无法重现，但是出现过好几次了
3.错误信息

**Describe the results you received:**
2019/09/19 00:00:17 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.docker-enddemo-ssh] error: port already used
2019/09/19 00:00:17 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.pm-web] error: router config conflict
2019/09/19 00:00:17 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.server-backup-ssh] error: port already used
2019/09/19 00:00:17 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.router1-web] error: router config conflict
2019/09/19 00:00:17 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.mqtt-tcp] error: port already used
2019/09/19 00:00:17 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.frpc-web] error: router config conflict
2019/09/19 00:00:17 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.mqtt-test-web] error: router config conflict
2019/09/19 00:00:17 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.fix-web] error: router config conflict
2019/09/19 00:00:17 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.docker-enddemo-pg] error: port already used
2019/09/19 00:00:19 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.mqtt-5883-tcp] error: port already used
2019/09/19 00:00:20 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.davinci-web] error: router config conflict
2019/09/19 00:00:20 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.ac66u-ssh] error: port already used
2019/09/19 00:00:50 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.docker-enddemo-ssh] error: port already used
2019/09/19 00:00:50 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.pm-web] error: router config conflict
2019/09/19 00:00:50 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.server-backup-ssh] error: port already used
2019/09/19 00:00:50 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.router1-web] error: router config conflict
2019/09/19 00:00:50 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.frpc-web] error: router config conflict
2019/09/19 00:00:50 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.mqtt-tcp] error: port already used
2019/09/19 00:00:50 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.mqtt-test-web] error: router config conflict
2019/09/19 00:00:50 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.fix-web] error: router config conflict
2019/09/19 00:00:50 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.docker-enddemo-pg] error: port already used
2019/09/19 00:00:52 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.mqtt-5883-tcp] error: port already used
2019/09/19 00:00:53 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.davinci-web] error: router config conflict
2019/09/19 00:00:53 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.ac66u-ssh] error: port already used
2019/09/19 00:01:15 [I] [proxy.go:87] [48406b8765f2819c] [jyzm.gitlab-ssh] get a new work connection: [114.220.109.177:51536]
2019/09/19 00:01:23 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.docker-enddemo-ssh] error: port already used
2019/09/19 00:01:23 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.pm-web] error: router config conflict
2019/09/19 00:01:23 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.server-backup-ssh] error: port already used
2019/09/19 00:01:23 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.router1-web] error: router config conflict
2019/09/19 00:01:23 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.mqtt-tcp] error: port already used
2019/09/19 00:01:23 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.frpc-web] error: router config conflict
2019/09/19 00:01:23 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.mqtt-test-web] error: router config conflict
2019/09/19 00:01:23 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.fix-web] error: router config conflict
2019/09/19 00:01:23 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.docker-enddemo-pg] error: port already used
2019/09/19 00:01:25 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.mqtt-5883-tcp] error: port already used
2019/09/19 00:01:26 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.davinci-web] error: router config conflict
2019/09/19 00:01:26 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.ac66u-ssh] error: port already used
2019/09/19 00:01:56 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.docker-enddemo-ssh] error: port already used
2019/09/19 00:01:56 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.pm-web] error: router config conflict
2019/09/19 00:01:56 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.server-backup-ssh] error: port already used
2019/09/19 00:01:56 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.router1-web] error: router config conflict
2019/09/19 00:01:56 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.mqtt-tcp] error: port already used
2019/09/19 00:01:56 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.frpc-web] error: router config conflict
2019/09/19 00:01:56 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.mqtt-test-web] error: router config conflict
2019/09/19 00:01:56 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.fix-web] error: router config conflict
2019/09/19 00:01:56 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.docker-enddemo-pg] error: port already used
2019/09/19 00:01:58 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.mqtt-5883-tcp] error: port already used
2019/09/19 00:01:59 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.davinci-web] error: router config conflict
2019/09/19 00:01:59 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.ac66u-ssh] error: port already used
2019/09/19 00:02:29 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.docker-enddemo-ssh] error: port already used
2019/09/19 00:02:29 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.pm-web] error: router config conflict
2019/09/19 00:02:29 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.server-backup-ssh] error: port already used
2019/09/19 00:02:29 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.router1-web] error: router config conflict
2019/09/19 00:02:29 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.mqtt-tcp] error: port already used
2019/09/19 00:02:29 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.frpc-web] error: router config conflict
2019/09/19 00:02:29 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.mqtt-test-web] error: router config conflict
2019/09/19 00:02:29 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.fix-web] error: router config conflict
2019/09/19 00:02:29 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.docker-enddemo-pg] error: port already used
2019/09/19 00:02:31 [W] [control.go:332] [48406b8765f2819c] new proxy [jyzm.mqtt-5883-tcp] error: port already used

**Describe the results you expected:**
不知道这个是什么导致的

**Additional information you deem important (e.g. issue happens only occasionally):**
我有两个环境都装有frps，一个环境使用频率很高，每天都有将近1G的流量交互，没有出过问题。出问题的这个环境，平时用的不是太多，每天数据量平均有20M左右。到目前为止，出现过3次这样的问题了。

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
可能是重复启动了多个相同配置的 frpc，导致配置冲突。
