### ISSUE TITLE
auth failed 0.29

### ISSUE THREAD

**Issue by littlesum** [fatedier/frp#1475]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.29

**What operating system and processor architecture are you using (`go env`)?**
ubuntu 18.04
freebsd 12.0

**Configures you used:**
frps token impkt13
frpc token impkt13

**Steps to reproduce the issue:**
1. 我检查了 token 都一致啊 比如全部是数字 或者就是一个1 
2. 咋改token 都说认证失败 
3.是配置文件有问题么？

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
注意配置和启动命令，是否正确指定了配置文件。

**Comment by littlesum** [comment]
没有啊 是不是frps 配置应该是 privilege_token = 
frpc 端是 token = 
这么写？
 

不是写法错误的话 我还真没找出来错误 我看配置文件说明是写token = 但看其他人的报告 有这种privilege_token = 的写法 到底应该咋写呢？

**Comment by fatedier** [comment]
参考文档和示例配置文件。

**Comment by littlesum** [comment]
怎么关闭啊？不太会弄
