### ISSUE TITLE
在配置好frps.ini登陆不上frp网页后台

### ISSUE THREAD

**Issue by blankmiss** [fatedier/frp#1476]
如题所示 
我的frps.ini中配置
[common]

bind_port = 7000

vhost_http_port =88

dashboard_port = 8000

dashboard_user = blankmiss

dashboard_pwd = 597091

privilege_token = qwe
 然后执行了  ./frps -c ./frps.ini
服务正常启动 
我在浏览器里输入了 ip:7000
却打不开后台 显示无法访问
此时我继续配置客户端
客户端配置完
运行frpc后
返回

 [W] [control.go:121] login to server failed: dial tcp 47.94.195.210:7000: getsockopt: connection timed out

**Comment by fatedier** [comment]
dashboard_port = 8000
