### ISSUE TITLE
客户端连接服务器端时，反复退出，重新连接，自动重新连接有时要花好近10分钟

### ISSUE THREAD

**Issue by FrankLiu007** [fatedier/frp#1479]
软件版本：服务器端和客户端均为 0.28.2或者0.29.0
客户端日志：
--------------------------------------------------------------------
2019/10/24 14:17:47 [I] [service.go:137] try to reconnect to server...
2019/10/24 14:17:47 [I] [service.go:234] login to server success, get run id [ac9ffc88de14fb0a], server udp port [0]
2019/10/24 14:17:47 [I] [proxy_manager.go:144] [ac9ffc88de14fb0a] proxy added: [sp4]
2019/10/24 14:18:06 [E] [control.go:136] work connection closed, EOF
2019/10/24 14:18:06 [I] [control.go:237] control writer is closing
2019/10/24 14:18:06 [I] [service.go:137] try to reconnect to server...
2019/10/24 14:18:07 [I] [service.go:234] login to server success, get run id [ac9ffc88de14fb0a], server udp port [0]
2019/10/24 14:18:07 [I] [proxy_manager.go:144] [ac9ffc88de14fb0a] proxy added: [sp4]
2019/10/24 14:18:26 [E] [control.go:136] work connection closed, EOF
2019/10/24 14:18:26 [I] [control.go:237] control writer is closing
2019/10/24 14:18:26 [I] [service.go:137] try to reconnect to server...
2019/10/24 14:18:26 [I] [service.go:234] login to server success, get run id [ac9ffc88de14fb0a], server udp port [0]
2019/10/24 14:18:26 [I] [proxy_manager.go:144] [ac9ffc88de14fb0a] proxy added: [sp4]
2019/10/24 14:18:45 [I] [control.go:237] control writer is closing
2019/10/24 14:18:45 [E] [control.go:136] work connection closed, EOF
2019/10/24 14:18:45 [I] [service.go:137] try to reconnect to server...
2019/10/24 14:18:45 [I] [service.go:234] login to server success, get run id [ac9ffc88de14fb0a], server udp port [0]
2019/10/24 14:18:45 [I] [proxy_manager.go:144] [ac9ffc88de14fb0a] proxy added: [sp4]
2019/10/24 14:19:04 [E] [control.go:136] work connection closed, EOF
2019/10/24 14:19:04 [I] [control.go:237] control writer is closing
2019/10/24 14:19:04 [I] [service.go:137] try to reconnect to server...
2019/10/24 14:19:04 [I] [service.go:234] login to server success, get run id [ac9ffc88de14fb0a], server udp port [0]
2019/10/24 14:19:04 [I] [proxy_manager.go:144] [ac9ffc88de14fb0a] proxy added: [sp4]
2019/10/24 14:19:06 [I] [control.go:153] [sp4] start proxy success

服务端日志：
--------------------------------------------------
2019/10/24 14:17:34 [I] [control.go:274] [a626e01ecda2f6c8] control writer is closing
2019/10/24 14:17:34 [I] [control.go:350] [a626e01ecda2f6c8] client exit success
2019/10/24 14:17:34 [I] [service.go:356] client login info: ip [27.17.13.150:40138] version [0.29.0] hostname [] os [linux] arch [amd64]
2019/10/24 14:17:46 [I] [service.go:356] client login info: ip [202.127.146.219:52917] version [0.29.0] hostname [] os [windows] arch [amd64]
2019/10/24 14:17:46 [I] [control.go:250] [ac9ffc88de14fb0a] Replaced by client [ac9ffc88de14fb0a]
2019/10/24 14:17:46 [I] [control.go:274] [ac9ffc88de14fb0a] control writer is closing
2019/10/24 14:17:46 [I] [control.go:350] [ac9ffc88de14fb0a] client exit success
2019/10/24 14:17:47 [I] [dashboard_api.go:173] Http request: [/api/proxy/tcp]
2019/10/24 14:17:47 [I] [dashboard_api.go:167] Http response [/api/proxy/tcp]: code [200]
2019/10/24 14:17:50 [I] [dashboard_api.go:173] Http request: [/api/proxy/tcp]
2019/10/24 14:17:50 [I] [dashboard_api.go:167] Http response [/api/proxy/tcp]: code [200]
2019/10/24 14:18:04 [I] [control.go:274] [a626e01ecda2f6c8] control writer is closing
2019/10/24 14:18:04 [I] [control.go:350] [a626e01ecda2f6c8] client exit success
2019/10/24 14:18:05 [I] [service.go:356] client login info: ip [27.17.13.150:40140] version [0.29.0] hostname [] os [linux] arch [amd64]
2019/10/24 14:18:06 [I] [service.go:356] client login info: ip [202.127.146.219:52927] version [0.29.0] hostname [] os [windows] arch [amd64]
2019/10/24 14:18:06 [I] [control.go:250] [ac9ffc88de14fb0a] Replaced by client [ac9ffc88de14fb0a]
2019/10/24 14:18:06 [I] [control.go:274] [ac9ffc88de14fb0a] control writer is closing
2019/10/24 14:18:06 [I] [control.go:350] [ac9ffc88de14fb0a] client exit success
2019/10/24 14:18:25 [I] [service.go:356] client login info: ip [202.127.146.219:52934] version [0.29.0] hostname [] os [windows] arch [amd64]
2019/10/24 14:18:25 [I] [control.go:250] [ac9ffc88de14fb0a] Replaced by client [ac9ffc88de14fb0a]
2019/10/24 14:18:25 [I] [control.go:274] [ac9ffc88de14fb0a] control writer is closing
2019/10/24 14:18:25 [I] [control.go:350] [ac9ffc88de14fb0a] client exit success
2019/10/24 14:18:34 [I] [control.go:274] [a626e01ecda2f6c8] control writer is closing
2019/10/24 14:18:34 [I] [control.go:350] [a626e01ecda2f6c8] client exit success
2019/10/24 14:18:35 [I] [service.go:356] client login info: ip [27.17.13.150:40142] version [0.29.0] hostname [] os [linux] arch [amd64]
2019/10/24 14:18:35 [I] [http.go:92] [a626e01ecda2f6c8] [jupyter] http proxy listen for host [jupyter.luke123.cn] location [] group []
2019/10/24 14:18:35 [I] [control.go:398] [a626e01ecda2f6c8] new proxy [jupyter] success
2019/10/24 14:18:35 [I] [tcp.go:66] [a626e01ecda2f6c8] [dell-t630] tcp proxy listen port [6010]
2019/10/24 14:18:35 [I] [control.go:398] [a626e01ecda2f6c8] new proxy [dell-t630] success
2019/10/24 14:18:44 [I] [service.go:356] client login info: ip [202.127.146.219:52937] version [0.29.0] hostname [] os [windows] arch [amd64]
2019/10/24 14:18:44 [I] [control.go:250] [ac9ffc88de14fb0a] Replaced by client [ac9ffc88de14fb0a]
2019/10/24 14:18:44 [I] [control.go:274] [ac9ffc88de14fb0a] control writer is closing
2019/10/24 14:18:44 [I] [control.go:350] [ac9ffc88de14fb0a] client exit success
2019/10/24 14:19:04 [I] [service.go:356] client login info: ip [202.127.146.219:52941] version [0.29.0] hostname [] os [windows] arch [amd64]
2019/10/24 14:19:04 [I] [control.go:250] [ac9ffc88de14fb0a] Replaced by client [ac9ffc88de14fb0a]
2019/10/24 14:19:04 [I] [control.go:274] [ac9ffc88de14fb0a] control writer is closing
2019/10/24 14:19:04 [I] [control.go:350] [ac9ffc88de14fb0a] client exit success
2019/10/24 14:19:05 [I] [tcp.go:66] [ac9ffc88de14fb0a] [sp4] tcp proxy listen port [6000]
2019/10/24 14:19:05 [I] [control.go:398] [ac9ffc88de14fb0a] new proxy [sp4] success

**Comment by FrankLiu007** [comment]
服务器位于香港，但是frps的dashboard一直都是正常的，我是从dashboard里面看状态的

**Comment by ofexe** [comment]
我也碰到此问题，所有端口都是放行的。配置是最简单的默认配置，只开启SSH服务。

**Comment by FrankLiu007** [comment]
基本确定，是由于香港服务器受到干扰导致的，http非常稳定，可能是因为http是无连接的
