### ISSUE TITLE
链接了一会儿就自己断了

### ISSUE THREAD

**Issue by aliqingyun** [fatedier/frp#148]
server端在ubuntu上，腾讯云的机器。
client端在windows 32位，
正在使用远程桌面，用着用着，就断了，服务端：
2016/10/31 16:59:46 [control.go:138] [E] ProxyName [privilege_ssh], client heartbeat timeout
2016/10/31 16:59:46 [control.go:149] [W] ProxyName [privilege_ssh], client connection is closed
2016/10/31 16:59:46 [control.go:111] [I] ProxyName [privilege_ssh], I'm dead!
2016/10/31 16:59:46 [server.go:159] [I] ProxyName [privilege_ssh], listener is closed

不知道是不是网络不好。

**Comment by fatedier** [comment]
断开之后过一会儿看 frpc 的日志里有没有自动重连？

**Comment by aliqingyun** [comment]
没有重连，我感觉像是那个cmd窗口挂了。

**Comment by fatedier** [comment]
连接断开后会尝试自动重连，如果 cmd 窗口挂了进程就退出了，可以查下是什么原因导致的。
