### ISSUE TITLE
一个客户端能否同时连接两个服务端

### ISSUE THREAD

**Issue by wideweide** [fatedier/frp#1480]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

一个客户端能否同时连接两个服务端，如下：客户端文件frpc.ini配置多个server信息
[common]
server_addr = 1...
server_port = 7080

server_addr1 = 2...
server_port1 = 7080

或其它形式？

还是可以复制一份，启动两个实例？

**Comment by fatedier** [comment]
启动两个实例。

**Comment by zhaoyc1990** [comment]
例来版本没有这个功能

**Comment by NameLessKnight** [comment]
多跑几个程序就可以，使用不同的配置文件
