### ISSUE TITLE
How to use load balancing?

### ISSUE THREAD

**Issue by keyoti** [fatedier/frp#1482]
I would like to contribute documentation for the load balancing, but before I do, I need to understand it myself :)

It seems like Load Balancing is implemented so that one FRPS server balances load between multiple FRPC clients in a group.  In other words, more than one machine connects to the FRPS server, each machine has the same website, and then the incoming web requests are distributed evenly to the client machines.  Is that correct?

I was hoping that load balancing was different, what I wanted was the opposite; multiple servers running FRPS and only one FRPS client to each.  So, that the FRPS is load balanced, not FRPC.  I need to do that because there will be lots of FRPC connections.  Do you have any idea how to do this?  Would it work with a HTTP load balancer like AWS Application Load Balancer?  
I think not because there needs to be a route from the HTTP request to the correct server running with the connection to the intended FRPC client.  I don't expect you to answer that unless you have some experience or thoughts, thanks!

**Comment by fatedier** [comment]
A simple way to implement FRPS load balancing is that one FRPC(or multiple FRPC in one machine with different server_addr) connects to multiple FRPS.

So you can deploy an HTTP load balancer in front of FRPS.

Another way: divide FRPCs by domain, *.cluster1.xxx.com, *.cluster2.xxx.com, *.cluster3.xxx.com ...
One FRPS is reponsible for specified domains. HTTP load balancer route requests to different FRPS by host.

**Comment by yashodhank** [comment]
I recently found project called [Keepalived](https://github.com/acassen/keepalived) basically it provides loadbalancing and high-availability with server pool according their health can efficiently help us in such cases.
I am yet to test this hypothesis out..

**Comment by Nour963** [comment]
> I recently found project called [Keepalived](https://github.com/acassen/keepalived) basically it provides loadbalancing and high-availability with server pool according their health can efficiently help us in such cases. I am yet to test this hypothesis out..

Any news of that ?

**Comment by HenAmar** [comment]
@fatedier I don't see an option today to connect single frpc to multipile servers. is that supported ?

**Comment by yashodhank** [comment]
it is not supported out of box but one can use floating IP, keepalived and loadbalancer to make fault tolerant FRPS.
Apart from how to install FRPS, all other steps documented here:
https://community.hetzner.com/tutorials/howto-highly-available-load-balancer-hetzner-cloud-ansible
