### ISSUE TITLE
README中的ssh用例是否错误？

### ISSUE THREAD

**Issue by XiaoGe2030** [fatedier/frp#1483]
- 按照README中ssh的配置，配置了两台云主机（同一子网），但是一直不通，且提示‘公网ip和6000端口不通。

- 后猜想是frpc.ini中的server_addr配置项有问题，故改成了具有公网ip云主机的内网ip，frps的日志显示login 正常。所以更加确认是，README中的案例有错误。

![image](https://user-images.githubusercontent.com/22184388/67741301-a2ad3280-fa53-11e9-85d3-faf8d4f3d09f.png)

如有理解错误，还请批评指正!
🏃

**Comment by fatedier** [comment]
根据自己的需求进行配置，只需要能连通即可，公网地址是常规情况下的配置。
