### ISSUE TITLE
vhost_http_port模式无法访问IIS Express托管的站点

### ISSUE THREAD

**Issue by adeewu** [fatedier/frp#1484]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.29

**What operating system and processor architecture are you using (`go env`)?**
Window 10 X64

**Configures you used:**
### frps
```
[common]
bind_port = 7200
vhost_http_port = 7200
vhost_https_port = 7200
```

### frpc
``` 
[common]
server_addr = www.xxx.cn
server_port = 7200

[web]
type = http
local_port = 63243
custom_domains = web.xxx.cn
host_header_rewrite = web.xxx.cn
header_X-From-Where = frp
```

**Steps to reproduce the issue:**
使用Visual Studio 2019的IIS Express 托管AspNetCore项目
本地访问地址为：http://localhost:1234， 浏览器能正常访问这个地址
frp访问地址为：http://web.xxx.cn:7200， 访问报Http 400错误

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/5095500/67744415-67633180-fa5c-11e9-924a-0b57021347fe.png)

**Comment by ysc3839** [comment]
试试把 `host_header_rewrite` 改成 `localhost:1234`

**Comment by adeewu** [comment]
感谢@ysc3839 ，问题已经解决
