### ISSUE TITLE
名称已被使用！！

### ISSUE THREAD

**Issue by lbbboy** [fatedier/frp#1485]
[ssh] - 这个名称不能都用这个？NPS可以全用一个。如果这样。那一台客户端就要换个名称！很是不便。
type = tcp
local_port = 22
remote_port = 6000
use_encryption = true
use_compression = true

**Comment by fatedier** [comment]
不支持，名称必须唯一，会用于统计数据以及 API 接口。

参考配置文件中的 user 参数
https://github.com/fatedier/frp/blob/master/conf/frpc_full.ini

以及
https://github.com/fatedier/frp#configuration-file-template
配置文件环境变量渲染实现复杂的需求。
