### ISSUE TITLE
FRPC的体积问题

### ISSUE THREAD

**Issue by QQ2017** [fatedier/frp#1489]
**What version of frp are you using (./frpc -v or ./frps -v)?**
all

**What operating system and processor architecture are you using (`go env`)?**
win64

**Configures you used:**
-

**Steps to reproduce the issue:**
客户端程序体积过大，我相信有一些人和我一样希望将FRP集成到自己的软件中（非商业用途）。能否新开一个分支，称为 frpc_lite，只做单纯的TCP和stcp类型支持，客户端程序的体积应该可以缩小相当多~

**Comment by hjthjthjt** [comment]
![image](https://user-images.githubusercontent.com/3889846/67852879-38c28500-fb48-11e9-997a-16a76cc6b5b4.png)

**Comment by qiang-yu** [comment]
go 开发的程序都是这么大的，没办法，除非你自己用 C重写一个

**Comment by Xeath** [comment]
好想 Go 编译后就是这么大吧……

**Comment by lazy-luo** [comment]
c++实现类似的功能，静态联编gcc依赖库后大约为1M左右，也不小。参见 github.com/lazy-luo/smarGate，如果静态编译openssl大小会增大到2M+

**Comment by Yrr0r** [comment]
用upx压一下的话，体积可以缩小将近一半，不过upx适用平台有限。
如果能手动裁剪功能的话，不知道体积可不可以小一点。
但是体积最小的应该还是用C/C++重构。毕竟ss-libev也就差不多1MB大，而去掉web和其他所有功能只留tcp的话应该也可以很小。

**Comment by ntgeralt** [comment]
的确，只需要在便携路由穿透22和80，想找一款理想的最轻便的版本
