### ISSUE TITLE
关于frps和frpc之间通信协议的问题

### ISSUE THREAD

**Issue by IITII** [fatedier/frp#1490]
* 我已经查看过 README，未查到结果
* 我已经查看过所有相关 issues，无相关回答

> frp version: 以最新稳定版为例

疑问：

1. **frps** 和 **frpc** 之间的通信，是以什么方式进行交互的？tcp？udp？http？或者说取决与 **frpc.ini** 配置文件里面的 **type** (如 ssh：type=tcp) ？
2. 如果启用了 **加密** ，那通讯协议的类型会不会变？

> 如果表诉不清楚, 请 @IITII ，我会及时补充，谢谢！
> @fatedier Can you help me ?

**Comment by zhaoyc1990** [comment]
@IITII 
frps 和 frpc 之间的通信用的 tcp 协议, frpc.ini 配置文件的type 比如:tcp http https stcp 是访问者和frps 通信的协议，也可以理解为访问者和frpc 通信的协议，frps 只是中间的桥梁，桥梁结构是tcp协议
 哪里表不达意，请指出  @fatedier

**Comment by fatedier** [comment]
@zhaoyc1990 描述的基本差不多，目前是分为两种连接，控制连接和工作连接，控制连接是传输 frpc 和 frps 自身的控制协议，主要基于 tcp。工作连接是转发用户的请求，那么用户请求是什么样，协议就是什么样，加密之类的只是在这个上面包了一层，对请求方和接收方无感。

**Comment by IITII** [comment]
@zhaoyc1990 @fatedier 
所以具体的话，应该更类似与下面的哪一种工作方式？（配置的话，采取最简单的 http 内网穿透，不考虑其他异常）
![image](https://user-images.githubusercontent.com/33705067/68044450-52afc380-fd12-11e9-9ef6-4693055ec6ff.png)
![image](https://user-images.githubusercontent.com/33705067/68044838-1b8de200-fd13-11e9-9f6f-8d74561c1154.png)

> 加密和解密的话，是在 frpc 和 frps 完成的，对用户透明，对吗？

**Comment by fatedier** [comment]
第一种，因为 HTTP 底层还是 TCP，对于 frp 来说，其实在 frpc 和 frps 之间传输数据是不需要感知到协议的。

加密和解密，对用户透明，你的理解没问题。

**Comment by IITII** [comment]
那行，非常感谢!
@fatedier @zhaoyc1990
