### ISSUE TITLE
希望实现功能:  tcp模式下使用 自定义域名访问

### ISSUE THREAD

**Issue by qq405165798** [fatedier/frp#1497]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frp_0.29.1

**What operating system and processor architecture are you using (`go env`)?**
没有go环境
windows serer 2013 datacenter
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=5e03

**Configures you used:**
 tcp模式下使用 自定义域名访问

**Steps to reproduce the issue:**
frps.ini中
[common]
bind_addr = 0.0.0.0
bind_port = 17000
subdomain_host = tx.DDDD.top
....

frpc.ini中
....
[RDP1]
type = http
local_ip = 127.0.0.1
local_port = 3389
subdomain = rdp

**Describe the results you received:**
远程连接 rdp.tx.DDDD.top  报错
Parse conf error: proxy [RDP1] remote_port not found

**Describe the results you expected:**
能够连接到 用RDP协议连接 rdp.tx.DDDD.top 

**Additional information you deem important (e.g. issue happens only occasionally):**
现在是没有这个功能,并不是BUG.
有了这个功能以后有两个好处:
1. 用不同自定义域名区分,就不用再操心不同的client主机是不是采用了冲突的 remote_port了.
2. 安全性高. 端口不会直接暴露在公网上, 自定义域名也算秘密的一部分.

**Can you point out what caused this issue (optional)**
需要增加功能.

**Comment by fatedier** [comment]
见 #1472 。
