### ISSUE TITLE
用frp连接内网的 aria2 服务，连接失败

### ISSUE THREAD

**Issue by niluanxy** [fatedier/frp#150]
连接不上，然后用 frp 查看，状态显示的是： idle ，不知道该如何解决

**Comment by jiangchao0304** [comment]
我也卡在这里 不知道是不是nginx配置不对 无法转发到  localhost:6800/jsonrpc
我是转发到树莓派的80 然后80是一个nginx在转发到6800 ,然后就不同了 yaaw网页可以正常转发浏览

**Comment by fatedier** [comment]
显示 idle 说明 frpc 连接 frps 失败了，两端的日志里都显示什么错误？
