### ISSUE TITLE
AdminUI 功能无法启用

### ISSUE THREAD

**Issue by wylyeak** [fatedier/frp#1501]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

```0.29.1```

frps.ini
```
admin_addr = 127.0.0.1
admin_port = 7400
admin_user = admin
admin_pwd = admin
```

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

配置了启用`Dashboard`， 也配置了启用`Admin UI `
但是`Admin UI`的7400端口没有被打开，日志上也没有任何异常信息。

**Describe the results you expected:**

确认下 AdminUI 和 Dashboard 有什么区别？ 如何正常开启 AdminUI

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
可以通过一些工具检查下端口是否正常打开了，以及确认配置参数是否正确。

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/README_zh.md#dashboard

**Comment by wylyeak** [comment]
以下是我所有的配置， 删除了密码，token 等敏感配置。
```
[common]
bind_port = 7000
token = token
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin
admin_addr = 127.0.0.1
admin_port = 7400
admin_user = admin
admin_pwd = admin
vhost_http_port = 7080
vhost_https_port = 7443

# console or real logFile path like ./frps.log
log_file = ./frps.log

# trace, debug, info, warn, error
log_level = trace

log_max_days = 3
```

一下是日志输出
```
2019/11/08 14:07:14 [I] [service.go:141] frps tcp listen on 0.0.0.0:7000
2019/11/08 14:07:14 [I] [service.go:183] http service listen on 0.0.0.0:7080
2019/11/08 14:07:14 [I] [service.go:204] https service listen on 0.0.0.0:7443
2019/11/08 14:07:14 [I] [service.go:240] Dashboard listen on 0.0.0.0:7500
2019/11/08 14:07:14 [I] [root.go:205] start frps success
```

以上，没看到7400端口的日志

`ps -ef | grep frps | awk '{print $2}' | xargs -i lsof -p {} -i -Pan`命令输出如下
```
COMMAND   PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
frps    22791 yeak    5u  IPv6 28617526      0t0  TCP *:7000 (LISTEN)
frps    22791 yeak    6u  IPv6 28617527      0t0  TCP *:7080 (LISTEN)
frps    22791 yeak    7u  IPv6 28617528      0t0  TCP *:7443 (LISTEN)
frps    22791 yeak    8u  IPv6 28617532      0t0  TCP *:7500 (LISTEN)
```

以上设置， 结果就是7400端口没正常打开， 并且也用命令确认过，  7400 端口并未被别的应用占用。

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/README_zh.md#dashboard

**Comment by wylyeak** [comment]
> https://github.com/fatedier/frp/blob/master/README_zh.md#dashboard

这个页面上 dashboard 和 adminui 是两个端口， 没大明白是哪里的问题。

**Comment by lianggui102** [comment]
admin ui 是配置在client端的，不是server端
