### ISSUE TITLE
怎样监听frp断开

### ISSUE THREAD

**Issue by Knisy** [fatedier/frp#1504]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

因为一些因素  需要知道frp断开了 好切换到备用服务器

官方有提供什么方法监听吗

**Comment by fatedier** [comment]
frps 和 frpc 的 API 都提供了查询接口，dashboard 上能看到的通过 API 都可以拿到。
