### ISSUE TITLE
Connection closed unexpectedly and stuck in a disconnect-reconnect loop

### ISSUE THREAD

**Issue by Yirain** [fatedier/frp#1508]
Issue is only used for submitting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frps: 0.29.0
frpc: 0.27.1

**What operating system and processor architecture are you using (`go env`)?**
frps: Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64
frpc: Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64

**Configures you used:**
frps.ini
```
[common]
bind_port = 7000
bind_udp_port = 7001
token = ********
dashboard_addr = 0.0.0.0
dashboard_port = 16666
dashboard_user = ****
dashboard_pwd = ********
```
frpc.ini
```
[common]
server_addr = x.x.x.x
server_port = 7000
token = ********


[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 2222
use_encryption = true
use_compression = true

[bitcoin]
type = tcp
local_ip = 127.0.0.1
local_port = 8333
remote_port = 8333
use_encryption = true
use_compression = true
```
**Steps to reproduce the issue:**
1. At first, it performs well and everything is working properly then the connection was unexpectedly closed.
2. Then a loop of reconnecting happened, the client tries to reconnect every 30 seconds.
3. Sometimes it backs to normal after a while but sometimes I have to restart both the server and client to solve it.

**Describe the results you received:**
Unreliable connections between server-side and client-side

**Describe the results you expected:**
More stability and no more disconnect-reconnect loop.

**Additional information you deem important (e.g. issue happens only occasionally):**
Logs of client
```
Nov 10 23:36:42 Laptop frpc[1432]: 2019/11/10 23:36:42 [I] [service.go:221] login to server success, get run id [45a96bbb1c09c5a3], server udp port [7001]
Nov 10 23:36:42 Laptop frpc[1432]: 2019/11/10 23:36:42 [I] [proxy_manager.go:137] [45a96bbb1c09c5a3] proxy added: [ssh]
Nov 10 23:37:12 Laptop frpc[1432]: 2019/11/10 23:37:12 [E] [control.go:127] work connection closed, EOF
Nov 10 23:37:12 Laptop frpc[1432]: 2019/11/10 23:37:12 [I] [control.go:228] control writer is closing
Nov 10 23:37:12 Laptop frpc[1432]: 2019/11/10 23:37:12 [I] [service.go:127] try to reconnect to server...
Nov 10 23:37:15 Laptop frpc[1432]: 2019/11/10 23:37:15 [I] [service.go:221] login to server success, get run id [45a96bbb1c09c5a3], server udp port [7001]
Nov 10 23:37:15 Laptop frpc[1432]: 2019/11/10 23:37:15 [I] [proxy_manager.go:137] [45a96bbb1c09c5a3] proxy added: [ssh]
Nov 10 23:37:43 Laptop frpc[1432]: 2019/11/10 23:37:43 [I] [control.go:228] control writer is closing
Nov 10 23:37:43 Laptop frpc[1432]: 2019/11/10 23:37:43 [E] [control.go:127] work connection closed, EOF
Nov 10 23:37:43 Laptop frpc[1432]: 2019/11/10 23:37:43 [I] [service.go:127] try to reconnect to server...
```

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
Any log of frps?

Maybe it's disconnected by the fireware.

**Comment by i542873057** [comment]
我也出现了相同的错误
![image](https://user-images.githubusercontent.com/16971894/68558453-59f27200-0474-11ea-8c13-cf57ff803211.png)
运行一段时间儿会突然出现 这个错误，然后重连又好了，但是会很卡，然后过会儿又断了

**Comment by Yirain** [comment]
@fatedier Unfortunately, I forgot to set the log path on the server-side, but according to the output of "systemctl status frps" while the bug is happening, the situation is quite the same as the client, it just repeats "client login" and "client disconnect success".
It seems like its a bug since 0.24.1, After research on google I switch back to 0.24.0 on both server and client and the bug doesn't show up again (frps0.29.0+frpc0.24.0 still has the problem).
I guess it might be caused by a large amount of invalid TCP requests. The client-side works 7x24, just before the bug happens, my bitcoin service on the client-side was down 2-days ago before the bug happened and I didn't notice, so the local port 8333 was closed, meanwhile, frps is still listening and a lot of TCP request was received, so that cause the crash?
It could be a kind of possibility, but this bug used to happen more than once without a situation like this.

**Comment by fatedier** [comment]
You should find why the client is closed from server. frps's log may have some info about it. Try to reproduce it and paste the frps log.

It's better use same version frpc and frps.

**Comment by Yirain** [comment]
@fatedier I can not find out a way to reproduce the bug, I will post the logs here when it happens again.

**Comment by AuroraDysis** [comment]
same problem

frpc.ini
```
[common]
server_addr = xx.xx.xx.xx
server_port = 7700
token = xxxx

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 7001

[nx]
type = tcp
local_ip = 127.0.0.1
local_port = 4000
remote_port = 7002

[rdp]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 7003
```

frps.ini
```
[common]
bind_port = 7700
bind_udp_port = 7701
token = xxxx

dashboard_port = 7500
dashboard_user = xxxx
dashboard_pwd = xxxx
```

client side log
```
-- Logs begin at Fri 2019-11-15 12:21:06 GMT, end at Fri 2019-11-15 15:04:41 GMT. --
Nov 15 15:01:01 dell-t430 frpc[3090]: 2019/11/15 15:01:01 [I] [control.go:251] [e182b201dcac590b] control writer is closing
Nov 15 15:01:01 dell-t430 frpc[3090]: 2019/11/15 15:01:01 [I] [service.go:148] [e182b201dcac590b] try to reconnect to server...
Nov 15 15:01:01 dell-t430 frpc[3090]: 2019/11/15 15:01:01 [I] [service.go:249] [e182b201dcac590b] login to server success, get run id [e182b201dcac590b], server udp port [7701]
Nov 15 15:01:01 dell-t430 frpc[3090]: 2019/11/15 15:01:01 [I] [proxy_manager.go:144] [e182b201dcac590b] proxy added: [p2p_nx p2p_rdp ssh nx rdp p2p_ssh]
Nov 15 15:01:31 dell-t430 frpc[3090]: 2019/11/15 15:01:31 [I] [control.go:251] [e182b201dcac590b] control writer is closing
Nov 15 15:01:31 dell-t430 frpc[3090]: 2019/11/15 15:01:31 [E] [control.go:147] [e182b201dcac590b] work connection closed before response StartWorkConn message: EOF
Nov 15 15:01:31 dell-t430 frpc[3090]: 2019/11/15 15:01:31 [I] [service.go:148] [e182b201dcac590b] try to reconnect to server...
Nov 15 15:01:31 dell-t430 frpc[3090]: 2019/11/15 15:01:31 [I] [service.go:249] [e182b201dcac590b] login to server success, get run id [e182b201dcac590b], server udp port [7701]
Nov 15 15:01:31 dell-t430 frpc[3090]: 2019/11/15 15:01:31 [I] [proxy_manager.go:144] [e182b201dcac590b] proxy added: [p2p_nx p2p_rdp ssh nx rdp p2p_ssh]
Nov 15 15:02:01 dell-t430 frpc[3090]: 2019/11/15 15:02:01 [E] [control.go:147] [e182b201dcac590b] work connection closed before response StartWorkConn message: EOF
Nov 15 15:02:01 dell-t430 frpc[3090]: 2019/11/15 15:02:01 [I] [control.go:251] [e182b201dcac590b] control writer is closing
Nov 15 15:02:01 dell-t430 frpc[3090]: 2019/11/15 15:02:01 [I] [service.go:148] [e182b201dcac590b] try to reconnect to server...
Nov 15 15:02:01 dell-t430 frpc[3090]: 2019/11/15 15:02:01 [I] [service.go:249] [e182b201dcac590b] login to server success, get run id [e182b201dcac590b], server udp port [7701]
```
server side log
```
2019/11/15 22:53:49 [I] [service.go:372] [e182b201dcac590b] client login info: ip [114.255.218.20:10140] version [0.29.1] hostname [] os [linux] arch [amd64]
2019/11/15 22:54:19 [I] [control.go:293] [e182b201dcac590b] control writer is closing
2019/11/15 22:54:19 [I] [control.go:371] [e182b201dcac590b] client exit success
2019/11/15 22:54:19 [I] [service.go:372] [e182b201dcac590b] client login info: ip [114.255.218.20:21759] version [0.29.1] hostname [] os [linux] arch [amd64]
2019/11/15 22:54:49 [I] [control.go:293] [e182b201dcac590b] control writer is closing
2019/11/15 22:54:49 [I] [control.go:371] [e182b201dcac590b] client exit success
2019/11/15 22:54:49 [I] [service.go:372] [e182b201dcac590b] client login info: ip [114.255.218.20:22230] version [0.29.1] hostname [] os [linux] arch [amd64]
2019/11/15 22:55:19 [I] [control.go:293] [e182b201dcac590b] control writer is closing
```

**Comment by fatedier** [comment]
@AuroraDysis set `tls_enable = true` or `protocol = kcp`.

Maybe it's block by the network provider.

**Comment by AuroraDysis** [comment]
@fatedier This error happens by chance. I can fix it by restarting my frps docker when it happens. Anyway, I will try the configs you suggested and see if the error still exists. Thanks for your help.

**Comment by befantasy** [comment]
很早之前就发现了这个问题。。。感觉好像是被GFW干扰了。
不访问FRP服务的话，一般不会出这个error。经常一访问立即就出。

**Comment by fatedier** [comment]
@befantasy 外层再套一层加密工具中转- -

**Comment by befantasy** [comment]
没注意最近的版本增加了tls_enable = true这个功能。
刚才试了试，好像开了以后好了很多。
> @befantasy 外层再套一层加密工具中转- -
