### ISSUE TITLE
frps auto exit at sometimes

### ISSUE THREAD

**Issue by fr0zenrain** [fatedier/frp#1509]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.29.1

**What operating system and processor architecture are you using (`go env`)?**
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build414051050=/tmp/go-build -gno-record-gcc-switches"

**Configures you used:**
log_file = ./frps.log
bind_addr = 0.0.0.0
bind_port = 7000
bind_udp_port = 7001
kcp_bind_port = 7000
log_level = warn
log_max_days = 3
disable_log_color = false
allow_ports = 2000-3000,3001,3003,4000-50000
max_ports_per_client = 0
subdomain_host = xxx.com
tcp_mux = true

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

the last log as follows
2019/11/11 11:25:27 [I] [root.go:205] start frps success
2019/11/11 13:35:55 [W] [http.go:95] do http proxy request error: no such domain: xxx.dev.xxx.com /
2019/11/11 13:35:55 [W] [http.go:95] do http proxy request error: no such domain: aaa.111.xxx.com /favicon.ico

**Describe the results you expected:**

do not auto exit

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
No exit log here. You can start with simple configure.
