### ISSUE TITLE
小白求protocol = websocket 使用教程

### ISSUE THREAD

**Issue by zqlanly** [fatedier/frp#1511]
小白求protocol = websocket 使用教程

**Comment by qiang-yu** [comment]
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 80,
      "listen": null,
      "protocol": "vmess",
      "sniffing": null,
      "settings": {
        "auth": null,
        "udp": false,
        "ip": null,
        "clients": [
          {
            "id": "3XXXX7e6a-93f0-4b57-9b43-bXXXXXXXXd5d59",
            "alterId": 16,
            "email": "t@t.tt",
            "security": null
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": null
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "",
          "headers": {
            "Host": ""
          }
        },
        "httpSettings": null
      }
    }
  ],
  "outbounds": null,
  "dns": null,
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": null,
      "rules": []
    }
  }
}

**Comment by fatedier** [comment]
frpc.ini 设置这个参数即可，只是在 frpc 和 frps 建立连接时会使用 websocket 协议来建立连接。

**Comment by litongjava** [comment]
@fatedier 
客户端需要经过下面的配置
```
[001-22]
type = tcp
protocol = websocket
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000
```
这配置之后 frpc和frps第一次通讯,仍然会使用tcp,不会使用websocket,
可以修改后成frpc和frps自己的所有通讯都使用websocket传输吗?

为什么要这样修改?
因为这样修改可以使用nginx代理websocket到到frps,可以继续使用nginx的原有的80端口

**Comment by litongjava** [comment]
启动客户端,出现错误如下
```
2019/11/15 00:26:47 [W] [service.go:97] login to server failed: EOF
```
测试失败,frpc和frps第一次连接时使用依旧是tcp协议吗?

**Comment by fatedier** [comment]
配置在 [common] 下面。

**Comment by litongjava** [comment]
测试成功
