### ISSUE TITLE
FRP能不能用HTTP模式转发所有访问?

### ISSUE THREAD

**Issue by yuhuan21** [fatedier/frp#1512]
因为我只有一台内网主机,我想用HTTP模式把内网主机的80端口映射到外网的80端口,而不是像现在80端口是通过域名来识别主机的,如果单纯用TCP模式映射,我就获取不到客户端的真实IP了,谢谢
这样应该怎么设置,谢谢

**Comment by fatedier** [comment]
可以试下把 HTTP 的 custom_domains 设置为泛域名。

**Comment by tonyctp** [comment]
如果你有外网主机给你个思路。
1. 内网主机映射到外网主机的非80端口例如 81/8080 
2. 防火墙上面开启端口映射 将 80 映射到81/8080
备注： frp不能直接映射服务端的80/443端口
