### ISSUE TITLE
如何通过HTTP访问HTTPS的服务

### ISSUE THREAD

**Issue by 502647092** [fatedier/frp#1513]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.27.0

**What operating system and processor architecture are you using (`go env`)?**
```
[root@2-5 ~]# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/yumc/app/go/go-1-17-2"
GOTMPDIR=""
GOTOOLDIR="/yumc/app/go/go-1-17-2/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build103567390=/tmp/go-build -gno-record-gcc-switches"
```

**Configures you used:**
[common]
server_addr = 192.168.2.111
server_port = 7000
token = xxxxxx

[esxi]
type = http
local_ip = 192.168.2.6
local_port = 443
subdomain = esxi

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
```
2019/11/13 19:20:15 [I] [proxy.go:82] [10cfbbd99a12e11f] [esxi] get a new work connection: [192.168.2.5:35328]
2019/11/13 19:20:15 [W] [http.go:223] http: proxy error: EOF
2019/11/13 19:20:16 [I] [proxy.go:82] [10cfbbd99a12e11f] [esxi] get a new work connection: [192.168.2.5:35328]
2019/11/13 19:20:16 [W] [http.go:223] http: proxy error: EOF
```

**Describe the results you expected:**
本地的服务是HTTPS
FRPS上的是用了HTTP服务
然后在最外面挂了一个Nginx 反向代理到FRPS的HTTP端口上 (同时加了证书)
能不能这样访问 客户端=>https->Nginx=>http->frps=>http->frpc=>https->目标网站

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
v0.30.0 可以尝试 https2http 的 plugin。
