### ISSUE TITLE
其他协议走443或者80端口

### ISSUE THREAD

**Issue by gnightboy** [fatedier/frp#1515]
单位防火墙做了非常严格的端口限制，访问外面的地址，如果服务器不是443或者80端口，均不给通过。

目前想使用如下功能：

- RDP控制单位电脑
- WebDriver访问单位文件服务
- HttpProxy代理查看指定单位域网站内容

**Comment by fatedier** [comment]
那就把 frps 绑定在服务器的 443 或者 80 端口。
