### ISSUE TITLE
修改frps http访问的默认界面

### ISSUE THREAD

**Issue by litongjava** [fatedier/frp#1516]
在浏览器使用ip访问frps的vhost端口,返回如下
![image](https://user-images.githubusercontent.com/31761981/68878104-1cc30400-0742-11ea-86d5-70aff60a61c7.png)
如何自定义这个界面的内容

**Comment by fatedier** [comment]
frps.ini 增加

`custom_404_page = /path/to/404.html`

**Comment by imyubao** [comment]
![image](https://user-images.githubusercontent.com/41062250/68930502-7cb0bd80-07c9-11ea-9ec0-2fb1c8e5c176.png)
html不解析，变成了纯文本
![image](https://user-images.githubusercontent.com/41062250/68930655-cc8f8480-07c9-11ea-9c61-bf202c81e63f.png)
