### ISSUE TITLE
login to server failed: authorization timeout

### ISSUE THREAD

**Issue by piduser** [fatedier/frp#1517]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc -v .16

**What operating system and processor architecture are you using (`go env`)?**
Windows 64 - KVM

**Configures you used:**
[common]
server_addr = XXXXXXXXXXX
server_port = 7000
protocol =  tcp

[XXXXXXXXX]
type = http
local_port = 80
custom_domains = xxxx.com
locations = /XXXXXXXXXX

**Steps to reproduce the issue:**
1. Tried to restart FRPC and getting above error
2.
3.

**Describe the results you received:**

11/14/2019 9:31:21 PM : FRP LOG 2019/11/14 21:31:21 [I] [proxy_manager.go:298] proxy removed: []

11/14/2019 9:31:21 PM : FRP LOG 2019/11/14 21:31:21 [I] [proxy_manager.go:308] proxy added: [XXXXXXXX]

11/14/2019 9:31:21 PM : FRP LOG 2019/11/14 21:31:21 [I] [proxy_manager.go:331] visitor removed: []

11/14/2019 9:31:21 PM : FRP LOG 2019/11/14 21:31:21 [I] [proxy_manager.go:340] visitor added: []

11/14/2019 9:31:21 PM : FRP LOG 2019/11/14 21:31:21 [E] [control.go:230] authorization timeout

11/14/2019 9:31:21 PM : FRP LOG 2019/11/14 21:31:21 [W] [control.go:109] login to server failed: authorization timeout

11/14/2019 9:31:21 PM : FRP LOG authorization timeout

**Describe the results you expected:**
Instead of Failure looking for success

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue only on this computer. 

**Can you point out what caused this issue (optional)**

**Comment by piduser** [comment]
Any idea - why it fails on this if condition and throwing "authorization timeout"
	if config.ServerCommonCfg.AuthTimeout != 0 && nowTime-loginMsg.Timestamp > config.ServerCommonCfg.AuthTimeout {
		err = fmt.Errorf("authorization timeout")
		return
	}

**Comment by fatedier** [comment]
Please upgrade to the latest version.
