### ISSUE TITLE
frp http: proxy error: EOF

### ISSUE THREAD

**Issue by huiyuye** [fatedier/frp#1518]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
version of frp is 0.27.0

**What operating system and processor architecture are you using (`go env`)?**
system of server is freeBSD
system of client is Ubuntu 18.04.2 LTS
had go 

**Configures you used:**
in server
frps.ini

![image](https://user-images.githubusercontent.com/13378079/68994782-cc72b000-08c1-11ea-8163-be740899f1a7.png)

nginx.conf
![image](https://user-images.githubusercontent.com/13378079/68994844-5c185e80-08c2-11ea-9f77-6f691feeeda6.png)

in client
frpc.ini

![image](https://user-images.githubusercontent.com/13378079/68994864-8833df80-08c2-11ea-8773-1e1a59e15ab6.png)

nginx.conf
![image](https://user-images.githubusercontent.com/13378079/68994882-bb766e80-08c2-11ea-9fdb-c7a45861f05b.png)

**Steps to reproduce the issue:**
1.正常启动frps  ：  nohup ./frps -c ./frps.ini &
2.正常启动frpc  ：  nohup ./frpc -c ./frpc.ini &
3.已确保各个端口在防火墙已启用，两边Nginx正常运行

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/13378079/68994943-53745800-08c3-11ea-871e-34cde611620a.png)

in frps.log
![image](https://user-images.githubusercontent.com/13378079/68994955-71da5380-08c3-11ea-8fd4-869470f570cf.png)

**Describe the results you expected:**
I hope that the frp http can use 

**Additional information you deem important (e.g. issue happens only occasionally):**
1、ssh可以正常连接
2、上次使用的时候，一切正常，另外当时的网速较快
3、这次使用仅ssh正常连接，http报上述错误，另外这次的网速都较慢

**Can you point out what caused this issue (optional)**
我不知道是不是网速的原因

**Comment by fatedier** [comment]
可以先在客户端以一个简单的 static file 的 plugin 通过 http 暴露出去，做一下测试，如果可以可能是本地服务的问题，再排查下本地服务的连通性。

另外调用本地的 http 服务可能需要加上 `host_header_rewrite = frp.codemojos.com`
