### ISSUE TITLE
身份安全设置在 V0.29.1 配置以后 两端启动无法认证通过

### ISSUE THREAD

**Issue by Rambo1203** [fatedier/frp#1523]
**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc 0.29.1
frps 0.29.1

**What operating system and processor architecture are you using (`go env`)?**
add the token into the frpc.ini and frps.ini , and the value is 12345678

**Configures you used:**

frps.ini
[common]
token = 12345678

frpc.ini
[common]
token = 12345678

**Start the app , and the console is :**
frps
2019/11/18 15:53:40 [W] [service.go:302] register control error: authorization failed

frpc
2019/11/18 03:53:40 [W] [service.go:151] [2b4cff0e4e1f810b] reconnect to server error: authorization failed

**解决访问未能解决**
使用过以下解决方案未能解决上述问题

客户端连接失败，提示 authorization failed
出现这种情况说明鉴权失败，检查 frps 和 frpc 的配置文件中的 token 是否一致。

客户端连接失败，提示 authorization timeout
出现这种情况是因为 frps 所在服务器和 frpc 所在服务器的系统时间相差较大。如果不希望在身份校验时加入系统时间，可以将 frps 配置文件中的 authentication_timeout 设置为 0 来解决这个问题。

**Comment by fatedier** [comment]
启动时都通过 `frpc -c ./frpc.ini` 和 `frps -c ./frps.ini` 来启动，避免使用了默认的配置。

**Comment by Rambo1203** [comment]
启动的时候是通过 frpc -c ./frpc.ini 和 frps -c ./frps.ini 来启动的。不知道为何，未能解决此问题

**Comment by 8546KB** [comment]
不应该前面加./吗從我的華為手機傳送-------- 原始郵件 --------寄件者： Rambo <notifications@github.com>日期： 2019年11月19日 週二 12:02收件人： fatedier/frp <frp@noreply.github.com>副本： Subscribed <subscribed@noreply.github.com>主旨： Re: [fatedier/frp] 身份安全设置在 V0.29.1 配置以后 两端启动无法认证通过 (#1523)启动的时候是通过 frpc -c ./frpc.ini 和 frps -c ./frps.ini 来启动的。不知道为何，未能解决此问题

**Comment by Rambo1203** [comment]
启动方式：
1. 进入 frps frpc 的解压缩目录
2. ./frps -c ./frps.ini   &  ./frpc -c ./frpc.ini 来启动的

**Comment by fatedier** [comment]
自行排查下吧，一般是自身使用姿势问题。
