### ISSUE TITLE
https多端口监听代理

### ISSUE THREAD

**Issue by jobsgxx** [fatedier/frp#1524]
想咨询一下如何通过https同一个域名不同端口实现代理？
配置如下：
frpc：
#[web01]
#type = https
#local_ip = 127.0.0.1
#local_port = 6690
#use_encryption = true
#use_compression = true
#custom_domains = www.test.cn

#[web02]
#type = https
#local_ip = 127.0.0.1
#local_port = 9898
#use_compression = true
#custom_domains = www.test.cn

**Comment by jobsgxx** [comment]
@fatedier  领导麻烦帮忙看一下呗，感谢！

**Comment by fatedier** [comment]
同一域名，不同的本地服务，如果是同样的服务，想做负载均衡，可以尝试 [负载均衡示例](https://github.com/fatedier/frp/blob/master/README_zh.md#%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1) 。

如果是不同服务，建议还是通过域名或者端口区分开，可以直接做 tcp 类型的映射。
