### ISSUE TITLE
连接Ubuntu frpc，速度极慢

### ISSUE THREAD

**Issue by doyou** [fatedier/frp#1527]
环境：
最新版的frps和frpc v0.29.1
-------------------------------------------------

软件：

frps
公网frps运行在阿里云ECS，Windows2016平台

frpc
1.有Win10平台
用来转发rdp数据
性能稳定，速度快（连接者来自另外的网络，Windows远程桌面）
#1514 
2.有Ubuntu18.04平台
用来转发ssh和xrdp数据
与Win10平台在同一个内网
（内外网情况相同：外网连接者与连接Win10者相同）
frps dashboard上能显示所有ssh,rdp正常连接
c/s端的LOG都显示无异常

-------------------------------------------------
问题：
连接Ubuntu平台，速度极慢，ssh可忍受，xrdp延时达10秒左右。
-------------------------------------------------
请问这是什么原因，是否与客户、服务器端平台不同有关？有解决办法吗？

**Comment by doyou** [comment]
是不是xrdp的锅？
公网服务器带宽升级后，有所改善，仍比Windows的远程桌面慢了起码一个数量级。
局域网连接Ubuntu的延时感觉不明显。

xrdp.ini中，位图压缩选项是默认的
bitmap_compression=true

**Comment by fatedier** [comment]
可能是 windows 连接 windows 和 windows 连接 linux 有带宽方面的差异，可以参考 #662 ，暂无明确的解决方案。

**Comment by doyou** [comment]
> 可能是 windows 连接 windows 和 windows 连接 linux 有带宽方面的差异，可以参考 #662 ，暂无明确的解决方案。

:)

**Comment by doyou** [comment]
又做了下测试，同一台电脑进行远端xrdp连接，
不用mstsc，换成MobaXterm(v12.0)，
结果速度快多了，居然达到了流畅的程度！

看来mstsc连接非微软的远程桌面xrdp，需求的带宽相差很大，
把图像质量降到16位色又有所改善，仍与MobaXterm有较大的差距。
