### ISSUE TITLE
阿里云香港和腾讯云香港均无法使用frp(同样配置在国内云可以)

### ISSUE THREAD

**Issue by zhoufann9188** [fatedier/frp#1528]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.27  0.29

**What operating system and processor architecture are you using (`go env`)?**
centos

**Configures you used:**
frps:
[common]
bind_port = 7000
vhost_http_port=80

frpc:
[common]
server_addr = XXXX
server_port = 7000

[web]
type = http
local_port = 32254
custom_domains = www.xxx.com

**Steps to reproduce the issue:**
1. 启动frps  ,启动frpc
2. 
3.

**Describe the results you received:**
1、no such domain
2、每隔一分钟断线重连

**Describe the results you expected:**
能够在阿里云或腾讯云的香港云主机上用上frp的高性能穿透

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
这个应该给阿里云和腾讯云提工单。

**Comment by EthsonLiu** [comment]
最近香港服务器确实是有这种情况，我的 ss/ssr 也是经常掉线，不关 frp 的问题。
