### ISSUE TITLE
能否是想sftp的转发

### ISSUE THREAD

**Issue by ghsa1994** [fatedier/frp#153]
有没有人做成sftp转发的  求解答

**Comment by fatedier** [comment]
我测试了一下是ok的，sftp 就是用的 ssh 的端口，和转发 ssh 的配置和流程是一样的。

**Comment by ghsa1994** [comment]
这是我的配置信息
![45xyc f6zzqy wrdt k43](https://cloud.githubusercontent.com/assets/23058912/20058224/ddebeeb2-a52a-11e6-88e9-2613ff46864f.png)
经测试，使用putty远程连接树莓派的SSH是没有问题的！
但是使用filezilla连接就会出现意外断开连接的情况
![mghnrysr3oyy r dzl6o68](https://cloud.githubusercontent.com/assets/23058912/20058300/3962b1cc-a52b-11e6-9ffd-5ed45d2fecf5.png)
状态界面显示是正常的！
![lt5317em rz_ u 4b76 8q](https://cloud.githubusercontent.com/assets/23058912/20058320/56e19e70-a52b-11e6-84a5-006d2e6651eb.png)

**Comment by fatedier** [comment]
服务器端有错误日志吗？

**Comment by ghsa1994** [comment]
服务端没有任何错误提示，我怀疑是VPS主机网络设置有问题

![1](https://cloud.githubusercontent.com/assets/23058912/20084068/16f5a94e-a59b-11e6-9a67-1209b924b6e6.jpg)
