### ISSUE TITLE
https穿透失败

### ISSUE THREAD

**Issue by imyubao** [fatedier/frp#1530]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.29.1

**What operating system and processor architecture are you using (`go env`)?**
centos

**Configures you used:**
frps:
[common]
bind_port = 6998
vhost_http_port = 80
vhost_https_port = 443
log_file = /var/log/frp/frps.log
log_level = info
dashboard_addr = 0.0.0.0
dashboard_port = 7500
log_max_days = 30
max_pool_count = 1000
subdomain_host = imyoubo.cn

frpc:
[jumpserver-https]
type = https
local_ip = 192.168.1.101
local_port = 443
subdomain = jumpserver

[esxi_web_ui]
type = https
local_ip = 192.168.1.100
local_port = 443
subdomain = esxi

[iredmail-https]
type = https
local_ip = 192.168.1.102
local_port = 443
subdomain = mail

http部分配置：
[httpd]
type = http
local_ip = 192.168.1.103
local_port = 80
subdomain = archive

[seafile-webui]
type = http
local_ip = 192.168.1.103
local_port = 8000
subdomain = seafile
use encryption = true
use compression = true

**Steps to reproduce the issue:**
1.启动frps ,启动frpc
2.
3.

**Describe the results you received:**
1.https的穿透不成功，其他http的配置可以访问，服务端报错：
 get hostname from http/https request error: readHandshake: extensionsLen[1378] is not equal to dataLen[908]
![image](https://user-images.githubusercontent.com/41062250/69307332-39d96480-0c65-11ea-8921-4d3c8db3ea5d.png)

**Describe the results you expected:**
之前使用0.24版本的时候没有这个问题，前两天换了0.29.1也没问题，但今早重启了服务器，就报错了

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by AlainLam** [comment]
最终有找到原因吗，我也是忽然有这个问题，而且是chrome访问才会，火狐不会

**Comment by yaoqianZ** [comment]
遇到同样问题，chrome不行手机浏览器可以，想问怎么解决的？

**Comment by AlainLam** [comment]
> 遇到同样问题，chrome不行手机浏览器可以，想问怎么解决的？

升级

**Comment by yaoqianZ** [comment]
感谢，之前一直用0.27，现在升级到0.61，解决问题
________________________________
