### ISSUE TITLE
建议frpc type=http client端能自定义remote_port

### ISSUE THREAD

**Issue by Safircn** [fatedier/frp#1531]
**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**
希望多站点能绑定不同的端口,配置server端vhost_http_port 太局限了, custom_domains一定是必填吗

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
可以搜以前的 issue，不支持，直接用 tcp。
