### ISSUE TITLE
Windows XP 下的 Bug报告

### ISSUE THREAD

**Issue by jurey-github** [fatedier/frp#1533]
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.29.0-windows-i386

**What operating system and processor architecture are you using (`go env`)?**
OS: Windows XP
Arch: x86 
CPU: Pentium M

**Configures you used:**
见附件。（已隐藏服务器地址、密码等敏感信息）
[frpc.ini.txt](https://github.com/fatedier/frp/files/3882708/frpc.ini.txt)

**Steps to reproduce the issue:**
1. cd c:\
2. frpc -c .\frpc.ini
3.

**Describe the results you received:**
报错，错误信息详见附件。
[Error Msg.txt](https://github.com/fatedier/frp/files/3882694/Error.Msg.txt)

**Describe the results you expected:**
消除Bug，在32位Windows XP上跑起frpc

**Additional information you deem important (e.g. issue happens only occasionally):**
同样的环境，跑0.29.1-windows-i386，提示“不是有效的Win32应用程序”，点击确认后，cmd窗口返回“拒绝访问“。（备注：已确认下载的不是amd64版）

**Can you point out what caused this issue (optional)**

**Comment by ysc3839** [comment]
https://github.com/golang/go/wiki/MinimumRequirements#windows
Golang 1.11 开始已不支持 Windows XP。
