### ISSUE TITLE
既然已经那么像nginx了,为什么不实现http缓存呢

### ISSUE THREAD

**Issue by zhoufann9188** [fatedier/frp#1534]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**
经测试，http代理性能居然比nginx还要出色和稳定； 既然域名解析、反向代理、负载均衡都实现了，如果可以实现http缓存,我就可以直接抛弃nginx了。为什么不直接替代nginx呢

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
性能不会比 nginx 好的，你列举的一些功能是在做内网反向代理中不太容易绕过的，所以在 frp 中实现。

http server ，反向代理的通用需求太多了，不只有 nginx，还有其他的比较好的 golang 实现，想要替代，成本太高，且重复造轮子的意义也不大，还是倾向于组合工具来使用。

**Comment by zhoufann9188** [comment]
> 性能不会比 nginx 好的，你列举的一些功能是在做内网反向代理中不太容易绕过的，所以在 frp 中实现。
> 
> http server ，反向代理的通用需求太多了，不只有 nginx，还有其他的比较好的 golang 实现，想要替代，成本太高，且重复造轮子的意义也不大，还是倾向于组合工具来使用。

我的测试环境：
本地机器(外网可通过域名+端口访问 www.abc.com:8080)+腾讯云VPS；  
1、nginx代理腾讯云80端口，通过www.server.com访问后转发至本地 www.abc.com:8080服务
2、使用FRP代理腾讯云80端口, 直接穿透本地8080服务,和www.abc.com域名没有关系。
经测试,确实利用FRP直接穿透性能比nginx转发要快很多,且非常稳定。感谢作者开发如此性能优异的软件，只是作者说性能不会比nginx是否过于绝对了，哈哈
