### ISSUE TITLE
在黑群里运行frpc会重启？

### ISSUE THREAD

**Issue by yunsile023** [fatedier/frp#1535]
比如我从aria2下载页面切换到完成页面，有时候就会掉线
还有拷贝大点的文件就会掉线？
请教有什么好的方法不掉线？

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)
