### ISSUE TITLE
访问不存在得路由会导致正常的tcp http被关掉

### ISSUE THREAD

**Issue by gdpancheng** [fatedier/frp#1539]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

问题：当host路由不存在得时候会返回not found页面，这个时候已经存在得http或则tcp会全部被关掉
日志：
2019/11/26 17:20:29 [I] [proxy.go:84] [88586126c4843973] [BC000002_75a6fd3d5709c97d.web] get a new work connection: [211.161.167.108:49703]
2019/11/26 17:20:30 [I] [dashboard_api.go:171] Http request: [/api/proxy/http]
2019/11/26 17:20:30 [I] [dashboard_api.go:165] Http response [/api/proxy/http]: code [200]
2019/11/26 17:20:30 [I] [dashboard_api.go:171] Http request: [/api/proxy/tcp]
2019/11/26 17:20:30 [I] [dashboard_api.go:165] Http response [/api/proxy/tcp]: code [200]
2019/11/26 17:20:30 [I] [control.go:282] [88586126c4843973] control writer is closing
2019/11/26 17:20:30 [W] [http.go:95] do http proxy request error: EOF
2019/11/26 17:20:30 [I] [proxy.go:69] [88586126c4843973] [BC000002_75a6fd3d5709c97d.ftpdata] proxy closing
2019/11/26 17:20:30 [I] [proxy.go:137] [88586126c4843973] [BC000002_75a6fd3d5709c97d.ftpdata] listener is closed
2019/11/26 17:20:30 [I] [proxy.go:69] [88586126c4843973] [BC000002_75a6fd3d5709c97d.mysql] proxy closing
2019/11/26 17:20:30 [I] [proxy.go:137] [88586126c4843973] [BC000002_75a6fd3d5709c97d.mysql] listener is closed
2019/11/26 17:20:30 [I] [proxy.go:69] [88586126c4843973] [BC000002_75a6fd3d5709c97d.remote] proxy closing
2019/11/26 17:20:30 [I] [proxy.go:137] [88586126c4843973] [BC000002_75a6fd3d5709c97d.remote] listener is closed
2019/11/26 17:20:30 [I] [proxy.go:69] [88586126c4843973] [BC000002_75a6fd3d5709c97d.api] proxy closing
2019/11/26 17:20:30 [I] [proxy.go:69] [88586126c4843973] [BC000002_75a6fd3d5709c97d.web] proxy closing
2019/11/26 17:20:30 [I] [proxy.go:69] [88586126c4843973] [BC000002_75a6fd3d5709c97d.jfool] proxy closing
2019/11/26 17:20:30 [I] [proxy.go:69] [88586126c4843973] [BC000002_75a6fd3d5709c97d.ftp] proxy closing
2019/11/26 17:20:30 [I] [proxy.go:137] [88586126c4843973] [BC000002_75a6fd3d5709c97d.ftp] listener is closed
2019/11/26 17:20:30 [I] [control.go:358] [88586126c4843973] client exit success

**Comment by fatedier** [comment]
日志里看不出来关闭原因，如果稳定复现建议可以提供一下可以复现的配置和步骤。

**Comment by gdpancheng** [comment]
我设置的http路由为 aaac.xxx.cn 指向的locations为/web 本地端口为8080 
当我开启本地端口8080的web服务器 访问aaac.xxx.cn/web 正常
当我关闭8080的web服务器后，显示如下
The page you visit not found.
Sorry, the page you are looking for is currently unavailable.
Please try again later.
The server is powered by frp.
Faithfully yours, frp.
然后当前路由的所有连接全部下线，30秒后 自动又连上 
当前情况100%重现

**Comment by gdpancheng** [comment]
后台日志就是上面发的那部分

**Comment by fatedier** [comment]
需要提供具体的复现配置和详细的操作步骤，否则也无法排查这个问题。
