### ISSUE TITLE
local_port 和 remote_port能支持多端口吗？

### ISSUE THREAD

**Issue by evilkong** [fatedier/frp#154]
local_port 和 remote_port能支持多端口吗？一对一，比如

[etg]
privilege_mode = true
type = tcp
local_ip = 10.0.0.1
local_port = 22,80-88,5000
use_encryption = true
use_gzip = false
remote_port = 2022,80-88,5000

远端和客户端是一一对应的，目前这样的配置就要做10个区块。。。

**Comment by fatedier** [comment]
参考 #149 ， 后续考虑支持。

**Comment by ererermao** [comment]
@fatedier  你好，现在加入了吗？

**Comment by xinqiu** [comment]
同希望早点加入> <
