### ISSUE TITLE
大流量马上出现断线，客户端需要重连

### ISSUE THREAD

**Issue by yingnierxiao** [fatedier/frp#1540]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.29.1 版本

**What operating system and processor architecture are you using (`go env`)?**

机器在linode机房   
**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
客户端输出
2019/11/26 21:31:56 [E] [control.go:147] [fe167d2e94b4410e] work connection closed before response StartWorkConn message: EOF
2019/11/26 21:31:56 [E] [control.go:147] [fe167d2e94b4410e] work connection closed before response StartWorkConn message: EOF
2019/11/26 21:31:56 [E] [control.go:147] [fe167d2e94b4410e] work connection closed before response StartWorkConn message: EOF
2019/11/26 21:31:56 [E] [control.go:147] [fe167d2e94b4410e] work connection closed before response StartWorkConn message: EOF
2019/11/26 21:31:56 [I] [control.go:251] [fe167d2e94b4410e] control writer is closing
2019/11/26 21:31:56 [I] [service.go:148] [fe167d2e94b4410e] try to reconnect to server...
2019/11/26 21:31:56 [E] [control.go:147] [fe167d2e94b4410e] work connection closed before response StartWorkConn message: EOF
2019/11/26 21:31:56 [I] [service.go:249] [fe167d2e94b4410e] login to server success, get run id [fe167d2e94b4410e], server udp port [7001]

**Describe the results you expected:**

服务器端
2019/11/26 13:58:16 [I] [service.go:372] [fe167d2e94b4410e] client login info: ip [117.28.225.9:45926] version [0.29.1] hostname [] os [linux] arch [amd64]
2019/11/26 13:58:46 [I] [control.go:293] [fe167d2e94b4410e] control writer is closing
2019/11/26 13:58:46 [I] [control.go:371] [fe167d2e94b4410e] client exit success
2019/11/26 13:58:46 [I] [service.go:372] [fe167d2e94b4410e] client login info: ip [117.28.225.9:36845] version [0.29.1] hostname [] os [linux] arch [amd64]
2019/11/26 13:59:16 [I] [control.go:293] [fe167d2e94b4410e] control writer is closing
2019/11/26 13:59:16 [I] [control.go:371] [fe167d2e94b4410e] client exit success
2019/11/26 13:59:16 [I] [service.go:372] [fe167d2e94b4410e] client login info: ip [117.28.225.9:44436] version [0.29.1] hostname [] os [linux] arch [amd64]
2019/11/26 13:59:46 [I] [control.go:293] [fe167d2e94b4410e] control writer is closing
2019/11/26 13:59:46 [I] [control.go:371] [fe167d2e94b4410e] client exit success
2019/11/26 13:59:46 [I] [service.go:372] [fe167d2e94b4410e] client login info: ip [117.28.225.9:34670] version [0.29.1] hostname [] os [linux] arch [amd64]
2019/11/26 14:00:16 [I] [control.go:293] [fe167d2e94b4410e] control writer is closing
2019/11/26 14:00:16 [I] [control.go:371] [fe167d2e94b4410e] client exit success
2019/11/26 14:00:17 [I] [service.go:372] [fe167d2e94b4410e] client login info: ip [117.28.225.9:49030] version [0.29.1] hostname [] os [linux] arch [amd64]
**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
请按照 issue 格式提供详细的信息。

**Comment by johnrosen1** [comment]
国外线路被掐线不是很正常的吗
