### ISSUE TITLE
求教如何自定义三级、四级域名？

### ISSUE THREAD

**Issue by tomalloc** [fatedier/frp#1541]
我定义了1个一级域名，如何在frpc中配置三级或四级域名？

**Comment by RayXu14** [comment]
你首先要把三级、四级域名映射到你对应的服务器IP地址，这和frpc无关，在frpc中只需要把对应域名写对就行，参见frp的文档中的样例。

以aws为例，你需要在 https://console.aws.amazon.com/route53/home#hosted-zones: 中选择对应域名进行管理，创建一个记录集，填入你希望设置的多级域名和希望映射的IP就好

**Comment by gdpancheng** [comment]
在解析里面添加*.aa a记录 然后在你对于的frps.ini中 域名设置为 aa.host.com
