### ISSUE TITLE
frps 服务端支持热加载吗？

### ISSUE THREAD

**Issue by AzazelX5** [fatedier/frp#1546]
如题。   

比如修改了配置文件，能不重启frps服务，做到不中断已连接的frpc客户端，热加载新的配置文件吗？

场景：修改fprs 配置文件，添加允许访问的端口； 希望不断开已经连接的frpc客户端，热加载新的配置文件后，新的frpc客户端可以通过新端口连接到 fprs 服务端。

**Comment by fatedier** [comment]
目前不支持。
