### ISSUE TITLE
错误提示：frpc reload error: admin_port shoud be set if you want to use reload feature

### ISSUE THREAD

**Issue by talway** [fatedier/frp#1548]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

配置如下:
# set admin address for control frpc's action by http api such as reload
admin_addr = 127.0.0.1
admin_port = 7400
admin_user = admin
admin_pwd = admin

使用命令
frpc status -c ./frpc.ini
frpc reload -c ./frpc.ini

提示
frpc reload error: admin_port shoud be set if you want to use reload feature

**Comment by talway** [comment]
frpc get status error: admin_port shoud be set if you want to get proxy status

frpc reload error: admin_port shoud be set if you want to use reload feature

**Comment by fatedier** [comment]
正确指定配置文件启动，启动后观察是否有 `admin server listen on xxx` 的日志，如果没有，就继续检查配置文件 `frpc.ini`。

**Comment by talway** [comment]
重新换个配置文件就可以了，但是不知道是那里出错的

**Comment by funnypro** [comment]
有个问题，未来会考虑使用 HUP 信号重载 frpc 配置吗？

**Comment by fatedier** [comment]
@funnypro 不会，但是会考虑监测到文件变化后自动重载。
