### ISSUE TITLE
请求分享一下 ios设备上 fra app的代码

### ISSUE THREAD

**Issue by lizhouhua** [fatedier/frp#1549]
你好，
     fra 项目实在是很好，可以分享一下 app store 上ios设备上 fra app上的代码吗？
     我正在实现手机上的 webserver, 因为应用切到后台关闭 socket 的原因不可能做到 nat 穿透和 webserver 两个功能在两个不同的应用，所以我打算把你的代码集成到我的应用中，希望你考虑能共享这都分代码，万分感谢。

**Comment by fatedier** [comment]
请自行联系相关开发者。
