### ISSUE TITLE
windows的frp 是要如何运行？ 且Linux服务器端后台运行

### ISSUE THREAD

**Issue by jetbdy** [fatedier/frp#155]
如下是后台运行后的结果，正常运行的话也没有日志显示
[root@xxx frps ]# ./frps -c ./frps.ini&
[1] 14205
服务器端就算是运行成功了？

要停止只能终止进程吗。

**Comment by fatedier** [comment]
windows 和 linux 上的运行和其他程序一样，并没有什么特殊之处。

日志默认在当前路径下的 frps.log 中。进程的起停在 linux 下可以自己写 service 脚本来控制。

**Comment by jetbdy** [comment]
我还是对windows下，是否成功运行客户端不能判断，，frpc.exe  是应该在配置好.ini后直接运行吗？双击后出现cmd 窗口，确是空白，过段时间窗口后自己消失，是我缺少配置了什么环境还是启动方式不对？？

**Comment by zhfish** [comment]
linux下用systemd控制应该会更好
win下`frpc -c frpc.ini` 即可
[我的配置文件](https://gist.github.com/zhfish/c13df1b3ace50bfb1ba34a7db380bbfb) 仅供参考

**Comment by ibolee** [comment]
> linux下用systemd控制应该会更好
> win下`frpc -c frpc.ini` 即可，一闪而过说明没启动成功。最好先打开cmd，在cmd里面执行，能看到错误原因
> [我的配置文件](https://gist.github.com/zhfish/c13df1b3ace50bfb1ba34a7db380bbfb) 仅供参考

很无私啊，谢谢老铁。
