### ISSUE TITLE
希望可以在客户端加上出口网关的相关配置以解决负载

### ISSUE THREAD

**Issue by hzexe** [fatedier/frp#1550]
对于多wan口用于负载或容灾的情形，frpc通常是期望同一服务同时走多个wan口做服务。
比如adsl多拨的情况下，当前frp只能使用其中一个出口，其它多拨出来的上行白白浪费无法使用。
一是浪费上行；
二是假设ADSL其中一个掉线或断线，其它工作正常，多出口就切换到正常工作的连接上来，起到容灾的作用

当然对于上行浪费，心是疼的

**Comment by hzexe** [comment]
想了想，应用层不容易 实现，需要路由器配合。需要特定的tcp标志以区分，  有点高深了。

**Comment by fatedier** [comment]
这一类问题可能比较通用，最好是有一个解决这一类问题的方案，可以作用在每一个应用上，由应用来感知这个问题不是太合适。

**Comment by hzexe** [comment]
我觉得frpc的使用的民用网络环境，可靠性是个硬伤。如果在网络上有冗余的方案，会很大提高frp的使用场景。也是优于vpn的一种方案。
虽然应用层受限于使用者复杂网络结构，但软件上如果使用冗余网络功能可以对网络提要求也算是一个方案，比如当前机器需要存在多网卡，多网段等要求。
提这个需求也算是抛砖引玉，看是否有比较合适的办法
