### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by 3469644172** [fatedier/frp#1552]
I suggest that you cooperate with https://github.com/cnlh/nps/ to Frp supporting advanced tokens and panels. Thanks

**Comment by 3469644172** [comment]
Downloading in China is particularly slow, so set up a Chinese mirror site http://d-frp.liuruilin.

**Comment by fatedier** [comment]
It's not the main aim of this project.
But #1403 `server manage plugin` will provide the possibility to extend frp's ability without modifing it's code. Everyone can implement his own plugin to meet his need and contribute to others.

Users can combine multiple plugins they want.
