### ISSUE TITLE
使用域名80端口代理后使用使用宝塔面板里面的webssh终端显示无法连接，自己搭建webssh测试也同样无法登陆

### ISSUE THREAD

**Issue by mybove** [fatedier/frp#1555]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.29.1

**What operating system and processor architecture are you using (`go env`)?**
centos 7

**Configures you used:**
[ssh01]
type = http
privilege_mode = true
local_ip = 192.168.1.2
local_port = 8888
custom_domains = ssh.bbb.com

**Steps to reproduce the issue:**
1.宝塔面板里面的ssh终端在通过frp穿透代理后显示无法连接服务器
2.直接单独搭建webssh后穿透代理能打开页面，但是登陆无反应。
3.

**Describe the results you received:**
无

**Describe the results you expected:**
希望能够得到解决，或者解决方案

**Additional information you deem important (e.g. issue happens only occasionally):**
一直没有解决

**Can you point out what caused this issue (optional)**
不知道什么原因导致这个结果

**Comment by funnypro** [comment]
这个问题我建议你问宝塔

**Comment by fatedier** [comment]
这类问题和具体的应用相关，涉及到这些应用功能的实现原理。
