### ISSUE TITLE
远程配置客户端

### ISSUE THREAD

**Issue by mesoar** [fatedier/frp#1557]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

我想问下，很奇怪为什么需要客户端配置呢？
如果在客户端与服务端建立连接后，
在服务端可以进行操作客户端相关的配置不是更友好吗？
类似客户端就像一个服务，而服务的配置可以在服务端进行分发这样不是更方便吗？

**Comment by fatedier** [comment]
你认为的方便也不一定是别人认为的方便，各自需求不同，还有一些安全性方面的考虑。
另外需要配置的话，可以通过将客户端的 admin UI 暴露出去达到一样的效果。
