### ISSUE TITLE
节省流量的问题

### ISSUE THREAD

**Issue by 344640891** [fatedier/frp#1561]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
V:0.29.1

**What operating system and processor architecture are you using (`go env`)?**
OS:linux-arm;CPU:A7;

**Configures you used:**

[common]
user = XXXXXXXXX
server_addr = XXXXXXXXX
server_port = 7000
login_fail_exit = false
admin_addr = 127.0.0.1
admin_port = 7001
token = XXXXXXXXX
heartbeat_interval = 180
heartbeat_timeout = 1080
[secret_tcp]
type = stcp
local_ip = 127.0.0.1
local_port = 22
sk = XXXXXXXXX

**Steps to reproduce the issue:**
1.无

**Describe the results you received:**
1、客户端为嵌入式设备，通过物联网卡上网，默认心跳间隔10S、心跳超时90S，每日消耗流量3.5M（测试期间无其它多余操作与连接，客户端仅待机）；改为心跳间隔180S、心跳超时1080S后，每日消耗流量3.0M（测试期间无其它多余操作与连接，客户端仅待机）。

**Describe the results you expected:**
正常使用没有问题，对于流量消耗有个疑问：客户端待机状态下，心跳不是主要消耗流量的动作吗？但是我加长心跳间隔后，流量节省并不明显。请问除此之外，还有什么配置可以节省流量呢？

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
因为底层有一层 TCP 连接的多路复用，有另外一种心跳机制，大概是10s，这个目前还没开放出来给用户修改，如果你把服务端和客户端的 tcp_mux 改为 false，应该就没有这个心跳了。

**Comment by 344640891** [comment]
好的，我试一下，谢谢
