### ISSUE TITLE
frps能否支持热加载配置修改token

### ISSUE THREAD

**Issue by QQ2017** [fatedier/frp#1566]
frps能否支持热加载配置修改token，其他参数无所谓，但是token如果被人知道后，就一直可以免费使用服务器了。
如果要修改token，目前只能修改配置文件重新打开frps，会导致连接的frpc断开。
如果可以支持热加载配置来修改token，那么已连接的frpc就不会断开了，而新连接的frpc则需要新的token才能连接到frps。

或者是否有其他方法防止盗用frps？

**Comment by fatedier** [comment]
不支持，v0.31.0 版本支持服务端插件，如果有类似的需求可以通过自己写插件来实现。
