### ISSUE TITLE
xtcp 超时 get sid from client error: read udp 192.168.3.226:59797->59.108.60.59:42869: i/o timeout

### ISSUE THREAD

**Issue by muziyongshixin** [fatedier/frp#1567]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.30.0

**What operating system and processor architecture are you using (`go env`)?**
frps ：ubuntu （腾讯云服务器）
frpc： ubuntu（服务端），windows（访问端）

**Configures you used:**
服务端frpc.ini配置
[panda5-ssh-p2p]
type = xtcp
sk = panda5
local_ip = 172.31.32.55
local_port = 22

客户端frpc.ini配置：
[panda5-p2p-ssh-visitor]
type = xtcp
role = visitor
server_name = panda5-ssh-p2p
sk = panda5
bind_addr = 127.0.0.1
bind_port = 10055

**Steps to reproduce the issue:**
1. 当使用内网的一个机器作为frps的时候可以打洞成功
2.使用腾讯云公网服务器作为frps的时候，打洞失败，stcp可用
3.

**Describe the results you received:**
客户端:2019/12/16 22:50:52 [W] [visitor.go:281] [8ae7245e673f1817] [panda5-p2p-ssh-visitor] get sid from client error: read udp 192.168.3.226:59797->59.108./o timeout

服务端：2019/12/16 22:51:26 [W] [proxy.go:339] [b7548477022bffb8] [panda5-ssh-p2p] get sid from visitor error: read udp 172.31.32.55:36014: i/o timeout

**Describe the results you expected:**
NAT打洞成功

**Additional information you deem important (e.g. issue happens only occasionally):**
客户端:2019/12/16 22:50:52 [W] [visitor.go:281] [8ae7245e673f1817] [panda5-p2p-ssh-visitor] get sid from client error: read udp 192.168.3.226:59797->59.108./o timeout

服务端：2019/12/16 22:51:26 [W] [proxy.go:339] [b7548477022bffb8] [panda5-ssh-p2p] get sid from visitor error: read udp 172.31.32.55:36014: i/o timeout

**Can you point out what caused this issue (optional)**
客户端:2019/12/16 22:50:52 [W] [visitor.go:281] [8ae7245e673f1817] [panda5-p2p-ssh-visitor] get sid from client error: read udp 192.168.3.226:59797->59.108./o timeout

服务端：2019/12/16 22:51:26 [W] [proxy.go:339] [b7548477022bffb8] [panda5-ssh-p2p] get sid from visitor error: read udp 172.31.32.55:36014: i/o timeout

**Comment by oolott** [comment]
我遇到同样问题，后来把被连接的客户端所在内网路由器远程连接功能打开后就可以了。你的frpc： ubuntu（服务端）是不是在内网啊？

**Comment by muziyongshixin** [comment]
> 我遇到同样问题，后来把被连接的客户端所在内网路由器远程连接功能打开后就可以了。你的frpc： ubuntu（服务端）是不是在内网啊？

我的frpc 服务端 和 frpc客户端都是在不同的内网里。
如果我用的frps是frpc那个内网里的一台有公网ip的机器的话是可以用的，但是如果frps部署在腾讯云上就会打洞超时。

**Comment by fatedier** [comment]
目前 xtcp 的功能成功率还不高，如果无法成功，属于正常现象。

**Comment by pcl-aacin** [comment]
I think you should open the DMZ function in the router
