### ISSUE TITLE
what this error means [E] [proxy.go:581]  socket: too many open files

### ISSUE THREAD

**Issue by godcong** [fatedier/frp#1569]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc: 0.30.0
frps: 0.30.0
**What operating system and processor architecture are you using (`go env`)?**
server :Ubuntu 16.04.5 LTS
clinet:  Ubuntu 18.04.2 LTS
**Configures you used:**
[ipfs14001]
type = tcp
local_ip = 192.168.1.13
local_port = 14001
remote_port = 14001
use_encryption = true
use_compression = true

**Steps to reproduce the issue:**
1. use  `nohup ./frpc -c frpc.ini &` to run the frp client
2. wait some minutes
3. see `nohup.out` log

**Describe the results you received:**
2019/12/17 06:20:11 ^[[1;34m[I] [service.go:221] login to server success, get run id [f569192072a0db37], server udp port [0]^[[0m
2019/12/17 06:20:11 ^[[1;34m[I] [proxy_manager.go:137] [f569192072a0db37] proxy added: [ipfs14001 xbw13_9000 ssh16004]^[[0m
2019/12/17 06:20:11 ^[[1;34m[I] [control.go:144] [ssh16004] start proxy success^[[0m
2019/12/17 06:20:11 ^[[1;34m[I] [control.go:144] [xbw13_9000] start proxy success^[[0m
2019/12/17 06:20:11 ^[[1;34m[I] [control.go:144] [ipfs14001] start proxy success^[[0m
2019/12/17 06:27:49 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:49 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:50 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:50 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:50 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:50 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:50 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:50 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:50 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:50 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:50 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:50 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:50 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:51 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:51 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:51 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:51 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:51 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:51 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:51 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:52 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:52 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:52 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:52 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:52 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:52 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:52 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:52 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:52 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:53 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:53 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:53 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:53 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:53 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:53 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
2019/12/17 06:27:54 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m

**Describe the results you expected:**
no errors to run,corret to connect

**Additional information you deem important (e.g. issue happens only occasionally):**
two computer in the same LAN, one computer has this log, other computer was ok(no error logs).

**Comment by keyoti** [comment]
In linux open sockets equate to open files.  Linux has quotas for the number of open files allowed for a user, so you need to increase it (I believe the default is typically 1024)

See https://serverfault.com/questions/649577/how-can-i-permanently-set-ulimit-n-8192-in-centos-7

**Comment by godcong** [comment]
thanks,@keyoti
```
*    soft    nofile 8192
*    hard    nofile 8192
```
but i changed the it, and reset the machine:
```
2019/12/17 06:27:54 ^[[1;31m[E] [proxy.go:549] [ipfs14001] connect to local service [192.168.1.13:14001] error: dial tcp 192.168.1.13:14001: socket: too many open files^[[0m
```
the error is still exist

**Comment by godcong** [comment]
It became this exception:
```
2019/12/24 03:38:05 [E] [control.go:147] [14ed16bf1a273541] work connection closed before response StartWorkConn message: EOF
```
