### ISSUE TITLE
群晖arm版有成功的吗？

### ISSUE THREAD

**Issue by Anyfc** [fatedier/frp#157]
# frps.ini
[common]
bind_port = 7000
vhost_http_port = 8081

[web]
type = http
custom_domains = www.yourdomain.com
auth_token = 123

# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000
auth_token = 123

[web]
type = http
local_port = 80

服务端和客户端都运行起来了，

2016/11/15 10:45:44 [main.go:182] [I] Start frps success
2016/11/15 10:46:05 [control.go:314] [I] ProxyName [web], start proxy success

2016/11/15 10:55:59 [main.go:109] [I] Start frpc success
2016/11/15 10:56:00 [control.go:185] [I] ProxyName [web], connect to server [192.243.119.117:7000] success!
2016/11/15 10:56:00 [control.go:193] [I] Start to send heartbeat to frps

打开地址提示： www.yourdomain.com：8081 ：拒绝了我们的连接请求。

**Comment by maodanp** [comment]
1. 确认下访问`www.yourdomain.com`的域名对应IP是否是frps所在的ip?
2. 如果是frps的ip，那frps端口的8081监听端口是否打开了，是否存在端口冲突？

**Comment by Anyfc** [comment]
@maodanp 
1.域名对应的ip是我vps的ip，这个没有填错。因为在打开www.yourdomain.com：8081的时候，会自动跳为群晖本地的5000端口  www.yourdomain.com：5000
2.如果 frps监听端口冲突的话，frp应该是运行不起来的吧？
这是访问 dashboard 界面（我把8081换成了8000）：
![qq](https://cloud.githubusercontent.com/assets/9066926/20305222/73c0618a-ab6f-11e6-809d-d64296677c5d.jpg)
