### ISSUE TITLE
the client can not connect to the server.

### ISSUE THREAD

**Issue by shougao** [fatedier/frp#1572]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.29.1， all of the is 0.29.1 release.

**What operating system and processor architecture are you using (`go env`)?**
[root@robot-test frp_0.29.1_linux_amd64]# env 
XDG_SESSION_ID=11770
HOSTNAME=robot-test
ANDROID_HOME=/data/androidsdk
TERM=xterm
SHELL=/bin/bash
HISTSIZE=1000
SSH_CLIENT=114.242.249.31 61413 12288
SSH_TTY=/dev/pts/2
USER=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
MAVEN_HOME=/usr/local/maven
MAIL=/var/spool/mail/root
PATH=/data/androidsdk/tools:/data/androidsdk/tools/bin:/data/androidsdk/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/maven/bin:/root/bin
PWD=/data/frps/frp_0.29.1_linux_amd64
LANG=en_US.UTF-8
HISTCONTROL=ignoredups
SHLVL=1
HOME=/root
LOGNAME=root
SSH_CONNECTION=114.242.249.31 61413 172.31.236.200 12288
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_RUNTIME_DIR=/run/user/0
_=/usr/bin/env
OLDPWD=/data/frps

client :

rk3399_mid:/ $ env 
_=/system/bin/env
ANDROID_DATA=/data
RK_ADEPT_ACTIVATION_FILE=/mnt/sdcard/.adobe-digital-editions/activation.xml
RK_ADOBE_DE_DOC_FOLDER=/mnt/sdcard/Digital Editions
HOME=/
RK_ADEPT_DEVICE_TYPE=mobile
RK_ADEPT_DEVICE_SALT_FILE=/mnt/sdcard/.adobe-digital-editions/devicesalt
EBOOK_PAGE_VISIBLE_NUMBER=2　
ANDROID_ASSETS=/system/app
BOOTCLASSPATH=/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar
ANDROID_SOCKET_adbd=9
ANDROID_BOOTLOGO=1
ANDROID_STORAGE=/storage
DOWNLOAD_CACHE=/data/cache
LOGNAME=shell
SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar
TERM=xterm-256color
SHELL=/system/bin/sh
RK_ADOBE_DE_MOBILE=1
ADOBE_FONTS_DIR=/system/fonts/adobefonts/
RK_ADEPT_DEVICE_FILE=/mnt/sdcard/.adobe-digital-editions/device.xml
ASEC_MOUNTPOINT=/mnt/asec
HOSTNAME=rk3399_mid
EXTERNAL_STORAGE=/sdcard
USER=shell
TMPDIR=/data/local/tmp
PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
ANDROID_ROOT=/system

**Configures you used:**

**Steps to reproduce the issue:**
1.android platform is frcp, using command : frpc -c frpc.ini & 
2.centos os server, using command : frps -c frps.ini &
3.look at the server side log output. and the frp web side.

**Describe the results you received:**

2019/12/19 11:51:51 [I] [service.go:372] [eaaa72cb5b7cccfd] client login info: ip [117.132.195.61:13882] version [0.29.1] hostname [] os [linux] arch [arm64]
2019/12/19 11:51:51 [I] [control.go:293] [eaaa72cb5b7cccfd] control writer is closing
2019/12/19 11:51:51 [I] [control.go:371] [eaaa72cb5b7cccfd] client exit success
2019/12/19 11:51:55 [I] [dashboard_api.go:171] Http request: [/api/proxy/tcp]
2019/12/19 11:51:55 [I] [dashboard_api.go:165] Http response [/api/proxy/tcp]: code [200]

**Describe the results you expected:**
frpc device show at the frp web page.

**Additional information you deem important (e.g. issue happens only occasionally):**
the android using the 上网卡 to connect to the internel。

**Can you point out what caused this issue (optional)**
may be , the server side has bug, or not support network connection issue.

**Comment by fatedier** [comment]
Checkout the network problem by youself first.
