### ISSUE TITLE
Feature suggestion: should FRPC report its version to FRPS for compatibility check?

### ISSUE THREAD

**Issue by keyoti** [fatedier/frp#1574]
For my use it would be helpful if FRPC sent its version to FRPS.  If the FRPC version is too old, then FRPS sends a message back like "Your FRPC client is too old, please update it".

I would suggest in frps.ini

```
[common]
oldest_supported_client_version = 0.30
```

I guess you don't want to do a lot of backwards compatibility testing, which is fine, but at least this would provide a way to force clients to update.

Should I try to do a PR?

**Comment by fatedier** [comment]
We already have the check on https://github.com/fatedier/frp/blob/master/utils/version/version.go#L50

It's compatible since v0.18.0 and i will keep it backwards compatible as far as possible.
