### ISSUE TITLE
Sync logger with upstream

### ISSUE THREAD

**Issue by Peter2121** [fatedier/frp#1576]
The logger, used in frps was not updated with the upstream [https://github.com/astaxie/beego/logs](https://github.com/astaxie/beego/logs) for a while. In the meantime, several new loggers were added upstream (especially ElasticSearch).
Please, update the logger so it would be possible to send frps logs to all loggers, supported in `astaxie/beego/logs`

**Comment by fatedier** [comment]
It's not stable and maybe import more bugs. I prefer not to change the log module.
If you want to send logs to ElasticSearch, try filebeat. Include it in log module is not suitable.
