### ISSUE TITLE
I wanna know the reason why we should turn all TCP ports in Ali cloud?

### ISSUE THREAD

**Issue by rinabell** [fatedier/frp#1579]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

我就是好奇，为什么现在在阿里云里必须把所有 TCP 端口打开才能 FRP 内网穿透成功，而早期的教程里（https://blog.csdn.net/cao0507/article/details/82758288） 只开对应端口就行。
如果作者觉得这个问题跟 FRP 本身无关，请随意关闭这个话题，这样我至少能得到一个答案。

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.28.0

**What operating system and processor architecture are you using (`go env`)?**
ubuntu 16.04

**Configures you used:**
non

**Steps to reproduce the issue:**
1. 开启对应端口，无效
2. 在控制台开启所有 TCP 端口，有效
3. 只开启对应波段端口，无效

**Comment by wxlg1117** [comment]
自己tcp ping端口一下不久知道了么

**Comment by fatedier** [comment]
如果你确认你打开了所有你需要用到的端口，还是有问题，就需要给阿里云提工单。
