### ISSUE TITLE
dashboard页面不需要密码验证就能打开？

### ISSUE THREAD

**Issue by seeingrain** [fatedier/frp#158]
你这工具真的很棒！！！
我就想问问dashboard上面有所有端口的信息，那如果不需要密码就能打开的话，会不会让所有人都很轻松的就看到所有目前配置的端口啦？我就问问……大不了关了dashboard，哈哈

**Comment by fatedier** [comment]
1. dashboard 会加入账号密码验证。
2. http 类型的反向代理也可以在 frpc 端配置账号和密码。

上述功能在下个版本中提供。

**Comment by wxyzh** [comment]
dev版有的

fatedier <notifications@github.com>于2016年11月15日周二 13:56写道：
