### ISSUE TITLE
安卓7.0运行arm64版本提示Illegal instruction

### ISSUE THREAD

**Issue by squallxgithub** [fatedier/frp#1580]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 加1，我也是 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

What version of frp are you using (./frpc -v or ./frps -v)?
arm64版的frpc 0.29.1
What operating system and processor architecture are you using (go env)?
Android 7.0，cpu arm64_v8a
Configures you used:

Steps to reproduce the issue:
1.运行./frpc ,直接提示Illegal instruction
2.
3.

Describe the results you received:

Describe the results you expected:

Additional information you deem important (e.g. issue happens only occasionally):

Can you point out what caused this issue (optional)

**Comment by funnypro** [comment]
要不要换个同是 arm64 手机试试？

**Comment by fatedier** [comment]
可以自行尝试从源码交叉编译一下？arm 好像有多个版本。

**Comment by squallxgithub** [comment]
@funnypro @fatedier 
很奇怪啊，两位，情况是我有2台一模一样的乐视2手机，刷的rom版本也一样，frpc的版本也一样，一台能运行，另一台却提示Illegal instruction
PS：怎么交叉编译，有文档吗？实在是小白

**Comment by squallxgithub** [comment]
@funnypro @fatedier
感谢，ubuntu环境下重新编译了arm64版本的，可以用啦
