### ISSUE TITLE
Client 端 nginx 提供的 web 服务可以访问，javaweb 提供的 web 服务则无法访问

### ISSUE THREAD

**Issue by flanliulf** [fatedier/frp#1582]
**What version of frp are you using (./frpc -v or ./frps -v)?**
frp_0.30.0

**What operating system and processor architecture are you using (`go env`)?**
server: aliyun CentOS 7.7 64位
client: macOS Catalina 10.15.2

**Configures you used:**
Server:
[common]
bind_port = 7100
vhost_http_port = 8080

Client：
[common]
server_addr = xx.xx.xx.xx
server_port = 7100

[web]
type = http
local_port = 9090
custom_domains = www.domain.com

**Steps to reproduce the issue:**
1. Client 端启动 nginx 应用程序，端口号为 9090，本地访问 http://localhost:9090， 可以正常返回 nginx 主页面；
2. 访问 http://www.domain.com:8080， 也可以正常返回 nginx 主页面；
3. 如果 client 端换做启动 java web 应用程序(springboot 2.1.x)， 端口号仍然使用 9090，本地访问 http://localhost:9090/ok， 可以正常返回对应页面结果；
4. 访问 http://www.domain.com:8080/ok， 则报错；

**Describe the results you received:**
本地如果是 nginx 的 web 服务可以正常访问，但是 java web 程序的 web 服务无法访问。

报错信息：
do http proxy request error: net/http: timeout awaiting response headers

**Describe the results you expected:**
希望能够访问到 java web 程序提供的 web 服务。

**Additional information you deem important (e.g. issue happens only occasionally):**
Client 端本地防火墙已关闭，阿里云对应入方向安全组端口 8080 已设置。

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
这个问题应该自行检查自己的 nginx web 服务和 java web 服务的区别，用排除法定位问题，简单猜测是 host 的问题，可尝试 host_header_rewrite 参数。
