### ISSUE TITLE
在做https代理时候，微信公众号无法验证。

### ISSUE THREAD

**Issue by kkstun** [fatedier/frp#159]
在做https代理时候，微信公众号无法验证。不知道其他人有没有出现这个情况。不用可以验证。看上去似乎是微信服务器访问过来到frps就终止了。

**Comment by kkstun** [comment]
即使先验证通过，换代理也不通了。微信检测到了什么嘛。

**Comment by fatedier** [comment]
直接访问的时候可以？

**Comment by kkstun** [comment]
当然，直接访问没有任何问题的。我想应该是微信服务器做了什么验证

**Comment by xuebing1110** [comment]
微信公众号肯定验证不通过，微信公众平台的服务器又没有配置的你的域名到你的frps机器上

**Comment by lookas2001** [comment]
wireshark远程抓包看看。
抓包可以看这里https://www.wudew.com/posts/54
远程的话，可以用ssh来中转流量

**Comment by zhfish** [comment]
去年的问题还开着。。
一般用frp代理http流量，用nginx反代+ssl
没直接代理过ssl流量
