### ISSUE TITLE
Feature: Support packages for Linux distros

### ISSUE THREAD

**Issue by zyfdegh** [fatedier/frp#1590]
Any idea on building `.deb`, `.rpm` packages for popular Linux distros such as Debian/Ubuntu, CentOS/Fedora, ArchLinux etc. It would be easier to obtain the binaries like

```sh
$ sudo apt-get install frp
```

**Comment by fatedier** [comment]
I create the repo https://github.com/gofrp/deploy.
Anyone can help write the install scripts.

**Comment by donmor** [comment]
> I saw [gofrp/deploy#1](https://github.com/gofrp/deploy/pull/1) What i need is dnf rpm package instead of wget to download and run a bash file. I think we do not need to check arch or os. All packages like that are have different .rpm file from package repo. I didn't check how repos works(because of lazy), but i think it may let create a lot of rpm files to submit. So,... And, during my linux life, i think the old linux releases should not be supported at all. I like fedora, it is one of few distroses that which has no rolling updates. And, they will be more newer, more bug fixes, more safety.

Sry for necrobumping, but I'd like to introduce my [unofficial frp repository for debian](https://github.com/donmor/frp-debian) :-)
