### ISSUE TITLE
frpc是不是不能转发上级路由的web？

### ISSUE THREAD

**Issue by fengchen-github** [fatedier/frp#1593]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.16.1

**What operating system and processor architecture are you using (`go env`)?**
Linux 4.9.184 #0 Thu Jun 27 12:18:52 2019 mips GNU/Linux

**Configures you used:**
frpc.ini
`
[common]
server_addr = fengchenww.z
server_port = 7777

privilege_token = no@NO
login_fail_exit = false

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 22222

[web01]
type = http
local_ip = 192.168.8.254
local_port = 80
custom_domains = fengchenww.z

[web02]
type = http
local_ip = 192.168.9.1
local_port = 80
custom_domains = test.net
`

frps.ini
`
[common]
bind_port = 7777
vhost_http_port = 8888

privilege_token = no@NO
authentication_timeout = 0
`

**Steps to reproduce the issue:**
1.client的网段是192.168.8.0/24
2.web01正常
3.web02报[W] [newhttp.go:189] http: proxy error: EOF

**Describe the results you received:**
[W] [newhttp.go:189] http: proxy error: EOF

**Describe the results you expected:**
web02在client上一级路由，希望也能正常代理

**Additional information you deem important (e.g. issue happens only occasionally):**
web02与client不在同一网段，但client可以访问web02网段

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
1. 更新到最新版本。
2. 通过一些调试排查方法先自行排查下问题。
