### ISSUE TITLE
windows版本frpc，使用stcp协议，无法在0.0.0.0开端口

### ISSUE THREAD

**Issue by jasonto87** [fatedier/frp#1594]
windows版本frpc，使用stcp协议，无法在0.0.0.0开端口。只能够通过localhost:port访问，无法通过ip:port访问  netstat看到监听只能开在127.0.0.1

**Comment by QQ2017** [comment]
**私密代理客户端A**
local_ip = 192.168.100.100
local_port = 22

**私密代理客户端B(查看端)**
bind_addr = 0.0.0.0
bind_port = 2222

测试私密代理客户端B是可以监听2222，并且访问2222能连上私密代理客户端A的22端口。
所以你是不是搞错？

**Comment by jasonto87** [comment]
确实没有，用开启了加密和tls,在客户端B这里，netstat -ano|findstr "2222" 只有127.0.01:2222在listen

**Comment by jasonto87** [comment]
补充一下。这个问题在linux上不存在，使用sudo权限启动frpc即能在0.0.0.0上监听。 但是win7下只能在127.0.0.1上监听

**Comment by QQ2017** [comment]
你是不是应该把完整的配置文件传上来
