### ISSUE TITLE
Why server shows that "package github.com/fatedier/frp: no Go files in /home/lgy/go/src/github.com/fatedier/frp"  when I use GoLang to build frp???

### ISSUE THREAD

**Issue by LiuGaoyong** [fatedier/frp#1600]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
latest version 0.29

**What operating system and processor architecture are you using (`go env`)?**
centos 7

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by QQ2017** [comment]
#go get github.com/fatedier/frp
#cd /root/project/src/github.com/fatedier/frp
#make -f Makefile.cross-compiles

在go环境配置正确的情况下，以上命令可以编译成功，
go get github.com/fatedier/frp 会提示“package github.com/fatedier/frp: no Go files in /root/project/src/github.com/fatedier/frp” ，但是不影响编译.

**Comment by zp0605** [comment]
root@ubuntu:~# go get github.com/fatedier/frp              
can't load package: package github.com/fatedier/frp: no Go files in /root/gocode/src/github.com/fatedier/frp
root@ubuntu:~# 
root@ubuntu:~# cd  /root/gocode/src/github.com/fatedier/frp
root@ubuntu:~/gocode/src/github.com/fatedier/frp# 
root@ubuntu:~/gocode/src/github.com/fatedier/frp# make -f Makefile.cross-compiles
env CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o ./release/frpc_darwin_amd64 ./cmd/frpc
pkg/plugin/client/socks5.go:25:2: cannot find package "github.com/armon/go-socks5" in any of:
        /usr/local/go/src/github.com/armon/go-socks5 (from $GOROOT)
        /root/gocode/src/github.com/armon/go-socks5 (from $GOPATH)
pkg/auth/oidc.go:23:2: cannot find package "github.com/coreos/go-oidc" in any of:
        /usr/local/go/src/github.com/coreos/go-oidc (from $GOROOT)
        /root/gocode/src/github.com/coreos/go-oidc (from $GOPATH)

为啥还是提示找不到包

**Comment by QQ2017** [comment]
> root@ubuntu:~# go get github.com/fatedier/frp can't load package: package github.com/fatedier/frp: no Go files in /root/gocode/src/github.com/fatedier/frp root@ubuntu:~#
> root@ubuntu:~# cd /root/gocode/src/github.com/fatedier/frp root@ubuntu:~/gocode/src/github.com/fatedier/frp#
> root@ubuntu:~/gocode/src/github.com/fatedier/frp# make -f Makefile.cross-compiles
> env CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o ./release/frpc_darwin_amd64 ./cmd/frpc
> pkg/plugin/client/socks5.go:25:2: cannot find package "github.com/armon/go-socks5" in any of:
> /usr/local/go/src/github.com/armon/go-socks5 (from $GOROOT)
> /root/gocode/src/github.com/armon/go-socks5 (from $GOPATH)
> pkg/auth/oidc.go:23:2: cannot find package "github.com/coreos/go-oidc" in any of:
> /usr/local/go/src/github.com/coreos/go-oidc (from $GOROOT)
> /root/gocode/src/github.com/coreos/go-oidc (from $GOPATH)
> 
> 为啥还是提示找不到包

go get -u github.com/fatedier/frp

然后看看github.com/armon/go-socks5文件夹有没有内容，如果没有的话，再 go get -u github.com/armon/go-socks5
