### ISSUE TITLE
frps management page

### ISSUE THREAD

**Issue by hehaibo123** [fatedier/frp#1601]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
./frps-v0.31.0  ./frpc-v0.31.0

**What operating system and processor architecture are you using (`go env`)?**
frps:linux_386  frpc:linux_arm

**Configures you used:**

**Steps to reproduce the issue:**

**Describe the results you received:**
1.Frps listens to frpc state delay
2.After the frpc successfully connected another frpc, the number of connections to the frpc on the frps page monitored was 0

**Describe the results you expected:**
Frps management page provides timely feedback on the up and down line status of frpc

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by QQ2017** [comment]
配置文件和截图都上传下.

**Comment by hehaibo123** [comment]
[
![frpc](https://user-images.githubusercontent.com/46660105/71945270-4c056700-3201-11ea-9dbd-6bd99c43d1ea.jpg)
](url)[
![frps](https://user-images.githubusercontent.com/46660105/71945275-50ca1b00-3201-11ea-938f-b43d907825c7.png)
](url)

**Comment by hehaibo123** [comment]
frps dashboard  
1.frpc presence delayed
2.frpc has a successful connection, the number of connections is 0

**Comment by QQ2017** [comment]
frps dashboard貌似在Overview下的connections确实不显示任何值，
Proxies下的的connections可以正常显示connections，
![image](https://user-images.githubusercontent.com/23667705/71945842-d69a9600-3202-11ea-8df2-a01db0e1ad1c.png)
![image](https://user-images.githubusercontent.com/23667705/71945859-e6b27580-3202-11ea-9dcf-268f1951bc18.png)

**Comment by hehaibo123** [comment]
> frps仪表盘貌似在概述下的连接确实不显示任何值，
> 代理下的连接可以正常显示连接，
> ![图片](https://user-images.githubusercontent.com/23667705/71945842-d69a9600-3202-11ea-8df2-a01db0e1ad1c.png)
> ![图片](https://user-images.githubusercontent.com/23667705/71945859-e6b27580-3202-11ea-9dcf-268f1951bc18.png)

[
![1578452491(1)](https://user-images.githubusercontent.com/46660105/71947001-5aa24d00-3206-11ea-96d0-b1ac43501b96.jpg)
](url) I refresh sometimes come out, and after this state update has a delay can be set?

**Comment by hehaibo123** [comment]
> > frps仪表盘貌似在概述下的连接确实不显示任何值，
> > 代理下的连接可以正常显示连接，
> > ![图片](https://user-images.githubusercontent.com/23667705/71945842-d69a9600-3202-11ea-8df2-a01db0e1ad1c.png)
> > ![图片](https://user-images.githubusercontent.com/23667705/71945859-e6b27580-3202-11ea-9dcf-268f1951bc18.png)
> 
> [ ![1578452491（1）](https://user-images.githubusercontent.com/46660105/71947001-5aa24d00-3206-11ea-96d0-b1ac43501b96.jpg) ](url) 有时我会刷新，而在此状态更新后可以设置延迟吗？
Number of connections occasionally appear

**Comment by QQ2017** [comment]
> > > frps仪表盘貌似在概述下的连接确实不显示任何值，
> > > 代理下的连接可以正常显示连接，
> > > ![图片](https://user-images.githubusercontent.com/23667705/71945842-d69a9600-3202-11ea-8df2-a01db0e1ad1c.png)
> > > ![图片](https://user-images.githubusercontent.com/23667705/71945859-e6b27580-3202-11ea-9dcf-268f1951bc18.png)
> > 
> > 
> > [ ![1578452491（1）](https://user-images.githubusercontent.com/46660105/71947001-5aa24d00-3206-11ea-96d0-b1ac43501b96.jpg) ](url) 有时我会刷新，而在此状态更新后可以设置延迟吗？
> > Number of connections occasionally appear

你截图的这个值，应该是需要应用通过frpc建立连接之后才会有值。

**Comment by hehaibo123** [comment]
> > > > frps仪表盘貌似在概述下的连接确实不显示任何值，
> > > > 代理下的连接可以正常显示连接，
> > > > ![图片](https://user-images.githubusercontent.com/23667705/71945842-d69a9600-3202-11ea-8df2-a01db0e1ad1c.png)
> > > > ![图片](https://user-images.githubusercontent.com/23667705/71945859-e6b27580-3202-11ea-9dcf-268f1951bc18.png)
> > > 
> > > 
> > > [ ![1578452491（1）](https://user-images.githubusercontent.com/46660105/71947001-5aa24d00-3206-11ea-96d0-b1ac43501b96.jpg) ](url) 有时我会刷新，而在此状态更新后可以设置延迟吗？
> > > Number of connections occasionally appear
> 
> 你截图的这个值，应该是需要应用通过frpc建立连接之后才会有值。

s

> > > > frps仪表盘貌似在概述下的连接确实不显示任何值，
> > > > 代理下的连接可以正常显示连接，
> > > > ![图片](https://user-images.githubusercontent.com/23667705/71945842-d69a9600-3202-11ea-8df2-a01db0e1ad1c.png)
> > > > ![图片](https://user-images.githubusercontent.com/23667705/71945859-e6b27580-3202-11ea-9dcf-268f1951bc18.png)
> > > 
> > > 
> > > [ ![1578452491（1）](https://user-images.githubusercontent.com/46660105/71947001-5aa24d00-3206-11ea-96d0-b1ac43501b96.jpg) ](url) 有时我会刷新，而在此状态更新后可以设置延迟吗？
> > > Number of connections occasionally appear
> 
> 你截图的这个值，应该是需要应用通过frpc建立连接之后才会有值。

是的  我这边 是启了另一个frpc 端连接了这个代理 ，也处于交互状态 有时候刷新会出现

**Comment by hehaibo123** [comment]
另一个问题就是代理上线离线状态有延迟，不能及时更新状态

**Comment by QQ2017** [comment]
> 另一个问题就是代理上线离线状态有延迟，不能及时更新状态

上线延迟没遇到过，离线延迟可能是TCP异常断开，不是经过四次挥手断开的，状态无法及时同步，这只是猜测

**Comment by hehaibo123** [comment]
嗯嗯  谢谢  我看了 你的截图 代理连接上后，能正常检测到frpc连接啊
