### ISSUE TITLE
请问frpc里面可以设置多个server_addr吗？

### ISSUE THREAD

**Issue by qqlovekerry** [fatedier/frp#1607]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.30.0

**What operating system and processor architecture are you using (`go env`)?**
Ubuntu 18.04

**Configures you used:**
[common]
server_addr = XXXXXXX
server_port = XXXX

[ssh]
type = tcp 
local_ip = 127.0.0.1
local_port = 22
remote_port = XXXX

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**
可以在frpc.ini中设置多个`server_addr`和`server_port`，这样可以通过多个有公网IP的服务器实现内网穿透，以防单个IP被Q时仍然可以访问服务

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by xqzr** [comment]
请写多份配置文件
./frpc -c frpc1.ini
./frpc -c frpc2.ini
./frpc -c frpc3.ini
...
./frpc -c frpc10.ini

**Comment by qqlovekerry** [comment]
> 请写多份配置文件
> ./frpc -c frpc1.ini
> ./frpc -c frpc2.ini
> ./frpc -c frpc3.ini
> ...
> ./frpc -c frpc10.ini

谢谢您的回复！我现在使用的是软件包里给的`frpc.service`通过systemd来实现开机启动，请问`frpc.service`里面可以写多行
```
ExecStart=/usr/bin/frpc -c /etc/frp/frpc1.ini
ExecReload=/usr/bin/frpc reload -c /etc/frpc1.ini
ExecStart=/usr/bin/frpc -c /etc/frp/frpc2.ini
ExecReload=/usr/bin/frpc reload -c /etc/frpc2.ini
```
来实现多个frpc开机启动吗？

**Comment by Fisherworks** [comment]
> > 请写多份配置文件
> > ./frpc -c frpc1.ini
> > ./frpc -c frpc2.ini
> > ./frpc -c frpc3.ini
> > ...
> > ./frpc -c frpc10.ini
> 
> 谢谢您的回复！
> 我现在使用的是软件包里给的`frpc.service`通过systemd来实现开机启动，请问`frpc.service`里面可以写多行
> 
> ```
> ExecStart=/usr/bin/frpc -c /etc/frp/frpc1.ini
> ExecReload=/usr/bin/frpc reload -c /etc/frpc1.ini
> ExecStart=/usr/bin/frpc -c /etc/frp/frpc2.ini
> ExecReload=/usr/bin/frpc reload -c /etc/frpc2.ini
> ```
> 
> 来实现多个frpc开机启动吗？

那就把ExecStart写成运行一个shell script呗？

**Comment by qqlovekerry** [comment]
> > > 请写多份配置文件
> > > ./frpc -c frpc1.ini
> > > ./frpc -c frpc2.ini
> > > ./frpc -c frpc3.ini
> > > ...
> > > ./frpc -c frpc10.ini
> > 
> > 
> > 谢谢您的回复！
> > 我现在使用的是软件包里给的`frpc.service`通过systemd来实现开机启动，请问`frpc.service`里面可以写多行
> > ```
> > ExecStart=/usr/bin/frpc -c /etc/frp/frpc1.ini
> > ExecReload=/usr/bin/frpc reload -c /etc/frpc1.ini
> > ExecStart=/usr/bin/frpc -c /etc/frp/frpc2.ini
> > ExecReload=/usr/bin/frpc reload -c /etc/frpc2.ini
> > ```
> > 
> > 
> > 来实现多个frpc开机启动吗？
> 
> 那就把ExecStart写成运行一个shell script呗？

谢谢！
写多个`frpc1.service`，`frpc2.service`等等是不是也可以？

**Comment by xqzr** [comment]
> > > > 请写多份配置文件
> > > > ./frpc -c frpc1.ini
> > > > ./frpc -c frpc2.ini
> > > > ./frpc -c frpc3.ini
> > > > ...
> > > > ./frpc -c frpc10.ini
> > > 
> > > 
> > > 谢谢您的回复！
> > > 我现在使用的是软件包里给的`frpc.service`通过systemd来实现开机启动，请问`frpc.service`里面可以写多行
> > > ```
> > > ExecStart=/usr/bin/frpc -c /etc/frp/frpc1.ini
> > > ExecReload=/usr/bin/frpc reload -c /etc/frpc1.ini
> > > ExecStart=/usr/bin/frpc -c /etc/frp/frpc2.ini
> > > ExecReload=/usr/bin/frpc reload -c /etc/frpc2.ini
> > > ```
> > > 
> > > 
> > > 来实现多个frpc开机启动吗？
> > 
> > 
> > 那就把ExecStart写成运行一个shell script呗？
> 
> 谢谢！
> 写多个`frpc1.service`，`frpc2.service`等等是不是也可以？

可以的，我就是这样做的

**Comment by qqlovekerry** [comment]
> > > > > 请写多份配置文件
> > > > > ./frpc -c frpc1.ini
> > > > > ./frpc -c frpc2.ini
> > > > > ./frpc -c frpc3.ini
> > > > > ...
> > > > > ./frpc -c frpc10.ini
> > > > 
> > > > 
> > > > 谢谢您的回复！
> > > > 我现在使用的是软件包里给的`frpc.service`通过systemd来实现开机启动，请问`frpc.service`里面可以写多行
> > > > ```
> > > > ExecStart=/usr/bin/frpc -c /etc/frp/frpc1.ini
> > > > ExecReload=/usr/bin/frpc reload -c /etc/frpc1.ini
> > > > ExecStart=/usr/bin/frpc -c /etc/frp/frpc2.ini
> > > > ExecReload=/usr/bin/frpc reload -c /etc/frpc2.ini
> > > > ```
> > > > 
> > > > 
> > > > 来实现多个frpc开机启动吗？
> > > 
> > > 
> > > 那就把ExecStart写成运行一个shell script呗？
> > 
> > 
> > 谢谢！
> > 写多个`frpc1.service`，`frpc2.service`等等是不是也可以？
> 
> 可以的，我就是这样做的

明白了，非常非常感谢！马上就去试一下
