### ISSUE TITLE
支持websocket长连接吗？

### ISSUE THREAD

**Issue by ne1000** [fatedier/frp#1609]
下一版本可以支持吗？

**Comment by sesamefly** [comment]
当前这个版本不支持么？我去年就开始用websocket了啊

**Comment by quickhot** [comment]
用TCP

**Comment by quickhot** [comment]
websocket
![image](https://user-images.githubusercontent.com/5475712/72674132-50a60700-3aae-11ea-8353-2475f6975ce5.png)
