### ISSUE TITLE
是否可以客户端等待service上线?

### ISSUE THREAD

**Issue by yizems** [fatedier/frp#1612]
我的应用场景是这样的,有时候从公司出去,到家才能开电脑起 服务端服务,到家基本就没有途径远程客户端了,因为公司有加密策略,直接封禁第三方远程工具,公司带的又特别坑,贼麻烦

**Comment by fatedier** [comment]
frpc.ini 中设置 `login_fail_exit = false`，这样启动失败之后不会退出，会间隔时间重试。
