### ISSUE TITLE
服务器上如何编译

### ISSUE THREAD

**Issue by jinfagang** [fatedier/frp#1614]
```
➜  frp git:(master) make
go fmt ./...
go build -o bin/frps ./cmd/frps
cmd/frps/main.go:21:2: cannot find package "github.com/fatedier/golib/crypto" in any of:
	/usr/lib/go-1.10/src/github.com/fatedier/golib/crypto (from $GOROOT)
	/root/go/src/github.com/fatedier/golib/crypto (from $GOPATH)
cmd/frps/root.go:21:2: cannot find package "github.com/spf13/cobra" in any of:
	/usr/lib/go-1.10/src/github.com/spf13/cobra (from $GOROOT)
	/root/go/src/github.com/spf13/cobra (from $GOPATH)
Makefile:21: recipe for target 'frps' failed
make: *** [frps] Error 1

```

**Comment by QQ2017** [comment]
> ```
> ➜  frp git:(master) make
> go fmt ./...
> go build -o bin/frps ./cmd/frps
> cmd/frps/main.go:21:2: cannot find package "github.com/fatedier/golib/crypto" in any of:
> 	/usr/lib/go-1.10/src/github.com/fatedier/golib/crypto (from $GOROOT)
> 	/root/go/src/github.com/fatedier/golib/crypto (from $GOPATH)
> cmd/frps/root.go:21:2: cannot find package "github.com/spf13/cobra" in any of:
> 	/usr/lib/go-1.10/src/github.com/spf13/cobra (from $GOROOT)
> 	/root/go/src/github.com/spf13/cobra (from $GOPATH)
> Makefile:21: recipe for target 'frps' failed
> make: *** [frps] Error 1
> ```

https://github.com/fatedier/frp/issues/1600#issuecomment-571859560
