### ISSUE TITLE
will it upload to apt-get for convinience install?

### ISSUE THREAD

**Issue by jinfagang** [fatedier/frp#1616]
Will it upload to apt-get?

**Comment by QQ2017** [comment]
You can manually upload files to the server, perform installation or run.

**Comment by jinfagang** [comment]
@QQ2017  thanks for your reply.

I have only 1 question.

It seems every client will have a port, does this port number can be infinite?
If I opened my server only 7000-7005 port, will it only can limited clients to 5?

Can I using every client port num from 0~100000?

**Comment by QQ2017** [comment]
> 100



> @QQ2017 thanks for your reply.
> 
> I have only 1 question.
> 
> It seems every client will have a port, does this port number can be infinite?
> If I opened my server only 7000-7005 port, will it only can limited clients to 5?
> 
> Can I using every client port num from 0~100000?

The correct port range should be：1-65535
If the port is allocated, it should not be able to continue to allocate the port, which also indirectly limits the number of clients.
