### ISSUE TITLE
bandwith_limit 参数无效

### ISSUE THREAD

**Issue by QQ2017** [fatedier/frp#1620]
bandwith_limit 参数无效
frp版本：frp_0.31.1，Windows
代理配置：

[rdp9]
type=tcp
local_ip=192.168.1.5
local_port=3389
remote_port=0
use_encryption=true
use_compression=true
meta_id=5555555
bandwith_limit=200KB

使用以上配置连接服务器后，RDP上传速度依然不变（可以达到600KB/S）

**Comment by fatedier** [comment]
配置是 `bandwidth_limit=200KB`，文档中有一些错误。
