### ISSUE TITLE
[Feature Request] Better KCP protocol support please.

### ISSUE THREAD

**Issue by gubiao** [fatedier/frp#1622]
KCP协议受网络环境影响非常大, 在不同网络环境下通常都需要调整KCP协议的相关参数才能实现较好的加速效果, 目前版本的FRP中KCP协议底层相关参数是对终端用户屏蔽的, 用户无法调整KCP参数进行加速优化, 查看代码（utils/net/kcp.go#ListenKcp）后发现目前使用的KCP参数如下:

- MTU: 1350
- 发送窗口: 1024
- 接收窗口: 1024
- 缓冲区: 4194304
- 工作模式: 1, 20, 2, 1

请把以上5个KCP协议关键配置项开放给最终用户, 使用户可以在不同的网络环境下对使用KCP协议的FRP两端进行优化调整, 谢谢.

**Comment by sqliuchang** [comment]
我最近刚尝试使用kcp协议避免被墙，才发现没法手动调整kcp的参数
的确应该考虑开放这个参数，否则很容易出现过度发包导致流量暴涨的情况

**Comment by fatedier** [comment]
建议这样的需求可以自己另外部署 kcp 程序，可以根据自己的需求使用不同的版本或参数，更加灵活。frp 内置的功能只是方便使用，也不会同步版本更新，不过多地在这方面增加复杂度。

**Comment by sqliuchang** [comment]
> 建议这样的需求可以自己另外部署 kcp 程序，可以根据自己的需求使用不同的版本或参数，更加灵活。frp 内置的功能只是方便使用，也不会同步版本更新，不过多地在这方面增加复杂度。

只需要对bind_port套一层kcptun就可以了吗？

**Comment by fatedier** [comment]
@sqliuchang 可以，frpc 和 frps 之间只通过这一个端口通信，除了 xtcp 比较特殊。
