### ISSUE TITLE
报404错误的页面可否自定义

### ISSUE THREAD

**Issue by zhoufann9188** [fatedier/frp#1624]
网站有问题时报404错误的页面需带网站特殊标识的报错页面，可否自定义呢？

**Comment by quickhot** [comment]
![image](https://user-images.githubusercontent.com/5475712/72674079-a3cb8a00-3aad-11ea-9e72-fb772c30b499.png)
frps.ini里面
>custom_404_page = <404页面绝对路径>

**Comment by zhoufann9188** [comment]
> ![image](https://user-images.githubusercontent.com/5475712/72674079-a3cb8a00-3aad-11ea-9e72-fb772c30b499.png)
> frps.ini里面
> 
> > custom_404_page = <404页面绝对路径>

非常感谢！
