### ISSUE TITLE
frp real ip

### ISSUE THREAD

**Issue by leezp** [fatedier/frp#1626]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.31.1  v 0.31.1

**What operating system and processor architecture are you using (`go env`)?**
server  centos7
client  window10 64bit

**Configures you used:**
[common]
	bind_port = 7000
	dashboard_port = 7500
	dashboard_user = admin
	dashboard_pwd = admin
	vhost_http_port = 8080
	vhost_https_port = 10443

[common]
server_addr = vpsip
server_port = 7000
[web]
type=tcp
local_ip=127.0.0.1
local_port=9000

proxy_protocol_version=v2
[ssh]
type=tcp
local_ip=127.0.0.1
local_port=22

proxy_protocol_version=v2

**Steps to reproduce the issue:**
1. 本地蜜罐 （https://github.com/hacklcx/HFish ）+ frp 代理到 公网vps
2.
3.

**Describe the results you received:**
访问网站的来源ip都是本地 127.0.0.1

**Describe the results you expected:**
访问网站的来源ip是真实ip

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
https://github.com/fatedier/frp/blob/master/README_zh.md#%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E7%9C%9F%E5%AE%9E-ip

**Comment by fatedier** [comment]
proxy protocol 是一个代理协议，需要你本地的服务能够解析这个协议获取真实 IP 地址。

**Comment by cnyasin** [comment]
> proxy protocol 是一个代理协议，需要你本地的服务能够解析这个协议获取真实 IP 地址。

我经过各种尝试！依然无法获取真实IP！请问有没有成功案例呢？

**Comment by birdxs** [comment]
> > proxy protocol 是一个代理协议，需要你本地的服务能够解析这个协议获取真实 IP 地址。
> 
> 我经过各种尝试！依然无法获取真实IP！请问有没有成功案例呢？

大佬成功了没？网上搜半天也没找到tcp协议ssh访问获取真实ip的方法
