### ISSUE TITLE
FRP有没有可能做到像LVS DR模式那样，流量不经过服务器从而提高性能

### ISSUE THREAD

**Issue by zjb9151** [fatedier/frp#1627]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

![image](https://user-images.githubusercontent.com/60088468/72705317-20d22e80-3b96-11ea-8858-8ac2c24bc983.png)

**Comment by ysc3839** [comment]
https://github.com/fatedier/frp/blob/master/README_zh.md#点对点内网穿透

**Comment by zjb9151** [comment]
> [https://github.com/fatedier/frp/blob/master/README_zh.md#点对点内网穿透](https://github.com/fatedier/frp/blob/master/README_zh.md#%E7%82%B9%E5%AF%B9%E7%82%B9%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F)

这个模式需要客户端都安装FRP，我的意思是能不能实现LVS DR那种三角传输的方式，比如客户端访问一个Web服务，公网服务端接收到请求后转发给内网服务端，然后内网服务端直接在链路层修改报文数据，直接将数据返回给客户端，而不再经过公网服务端中继

**Comment by ysc3839** [comment]
@zjb9151 不可行，因为内网服务器 (frpc 所在服务器) 发送的数据包在经过 NAT 之后，source ip 会变成 NAT 路由的公网 IP。而客户端期待的是公网服务器 (frps 所在服务器) 发回的数据。

**Comment by zjb9151** [comment]
@ysc3839 通过linux的iptables报文转发功能应该能实现修改报文的源IP、目的IP以及端口号的吧

**Comment by ysc3839** [comment]
@zjb9151 是可以，但不管怎么改，在经过 NAT 路由的时候还是会被改掉呀。

**Comment by open-trade** [comment]
做不到的，lvs-dr也是有限制的

> 这种方式需要所有的DIR和RIP都在同一广播域；不支持异地容灾
