### ISSUE TITLE
如何让frps信任自签名的https证书？

### ISSUE THREAD

**Issue by jueljust** [fatedier/frp#1630]
我内网网站https，使用自签名的证书
公网搭建的frps无法被nginx反向代理 因为https证书无认证的关系
但我将这张证书加入公网服务器的信任证书，还是无法正确的反向代理
怎样才能使frps忽略这个问题呢？

**Comment by fatedier** [comment]
frps 不需要信任证书，只提供转发功能，如果无法转发可能是其他的错误。

**Comment by zeronchen** [comment]
不过frpc的日志会打印认证错误

**Comment by zeronchen** [comment]
考虑下能不能让frps添加信任证书的配置。我还试了一下用自签名的CA生成自签名的frpc https证书，然后把CA加入到frps的tls信任证书里面，同样还是不行。

> frps 不需要信任证书，只提供转发功能，如果无法转发可能是其他的错误。
