### ISSUE TITLE
http和https混合使用时https的端口无效

### ISSUE THREAD

**Issue by ghsa1994** [fatedier/frp#164]
原来用frp用来树莓派的内网穿透，这几天和别人一起做个项目，svn服务器在我的电脑上，windows的svn是https的，所以混合使用，但是自己怎么搞也不行，知道也许是哪里配错了，自己实在技术比较白，希望大家指正！
服务器配置

![k x96 1r r5wic 0 04p r](https://cloud.githubusercontent.com/assets/23058912/20485817/3f8b2b20-b038-11e6-810e-9e9b6154c396.png)

windows电脑客户端配置

![3lufd bmgjl98_05s s2c8](https://cloud.githubusercontent.com/assets/23058912/20485830/4c8cbdd4-b038-11e6-88fe-eaed2d14e180.png)

信息显示页面

![0 cj timwi7_sgs 2b0u t](https://cloud.githubusercontent.com/assets/23058912/20485846/5f30fc7a-b038-11e6-89e1-e56963133448.png)

windows客户端保存信息

![0y1bkn48j jc msw n4xct](https://cloud.githubusercontent.com/assets/23058912/20485868/7308ac70-b038-11e6-9579-2fe2a2c15ae3.png)

服务器是自动启动的，所以我没有截图服务器的信息，我觉得这个问题应该是配置问题 ，有必要我在去找报错信息

**Comment by fatedier** [comment]
错误信息提示你需要在 frps.ini 上另外配置一个专门用于 https 服务的端口 `vhost_https_port`。

**Comment by ghsa1994** [comment]
OK
感谢大牛指导，vhost_https_port和vhost_http_port看混淆了，所以之前一直弄错，现在已经可以正常使用了  ！
