### ISSUE TITLE
TCP服务，服务端出现大量SNY_RECV

### ISSUE THREAD

**Issue by SeanDemo2017** [fatedier/frp#1640]
有大佬遇到过吗，我使用tcp类型访问window上的某个端口的tcp类型的固定端口授权，local_port和 remote_port 相同。出现Time_Wait,但一段时间后，出现大量SNY_RECV

**Comment by SeanDemo2017** [comment]
我查了好像是SIGPIPE信号导致tcp中断的，有人知道如何忽略吗，以下意思是要写进frps吗，有从linux系统层面忽略“SIGPIPE信号”的操作吗？

“为了避免进程退出, 可以捕获SIGPIPE信号, 或者忽略它, 给它设置SIG_IGN信号处理函数:

signal(SIGPIPE, SIG_IGN);”

**Comment by funnypro** [comment]
> 我查了好像是SIGPIPE信号导致tcp中断的，有人知道如何忽略吗，以下意思是要写进frps吗，有从linux系统层面忽略“SIGPIPE信号”的操作吗？
> 
> “为了避免进程退出, 可以捕获SIGPIPE信号, 或者忽略它, 给它设置SIG_IGN信号处理函数:
> 
> signal(SIGPIPE, SIG_IGN);”

你是怎么启动的？
