### ISSUE TITLE
使用git clone时报错context canceled 500

### ISSUE THREAD

**Issue by yizems** [fatedier/frp#1641]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.29

**What operating system and processor architecture are you using (`go env`)?**
 win7 客户端 win10 服务端

**Configures you used:**

正常的tcp映射，跟readme中最简单的一样

**Steps to reproduce the issue:**
1.映射 gitlab 服务 到 服务端
2.然后服务端 访问 gitlab网页，正常
3.当 用git clone 的时候就会报500错误，提示context canceled

必现

我的 远程桌面是可以用的

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by yizems** [comment]
我哭的可能是请求头不一样，我还未找到原因

**Comment by yizems** [comment]
![Screenshot_20200206_220618_com microsoft rdc android](https://user-images.githubusercontent.com/16949474/73944345-08615400-48b8-11ea-9789-28d4af4251bb.png)
![Screenshot_20200206_220734](https://user-images.githubusercontent.com/16949474/73944363-0e573500-48b8-11ea-8034-192b8d2e0f71.png)

补充下配置，因为是用手机开操作的，不太好截图

**Comment by fatedier** [comment]
错误日志。

为什么是 http_proxy，不是简单映射 gitlab 的端口？
