### ISSUE TITLE
点对点内网穿透，流量还是会经过服务端，占用带宽

### ISSUE THREAD

**Issue by golfrey-dev** [fatedier/frp#1646]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
客户端和服务端都是0.31.2

**What operating system and processor architecture are you using (`go env`)?**
服务端Linux64位，客户端是Windows64位

**Configures you used:**
frps.ini
[common]
bind_port = 8100
bind_udp_port = 8102
dashboard_port = 8500
token = admin
dashboard_user = admin
dashboard_pwd = admin
vhost_http_port = 8180
vhost_https_port = 8143
disable_log_color = true
log_file = ./frps.log
log_level = info
log_max_days = 7 

frpc.ini
[common]
server_addr = X.X.X.X
server_port = 8100
token = admin
login_fail_exit = false
[p2p_191ssh]
type = stcp
sk = abcdefg
local_ip = 192.168.1.191    
local_port = 22
use_encryption = true
use_compression = true

frpc.ini
[common]
server_addr = X.X.X.X
server_port = 8100
token = admin
login_fail_exit = false
[p2p_191ssh_visitor]
type = stcp
role = visitor
server_name = p2p_191ssh
sk = abcdefg
bind_addr = 127.0.0.1
bind_port = 8104
use_encryption = true
use_compression = true

**Steps to reproduce the issue:**
1.在visitor的主机ssh到内网主机
2.下载文件到visitor主机
3.占用了frps主机带宽

**Describe the results you received:**

**Describe the results you expected:**
点对点内网穿透的情况，大流量不经过服务端，不占用服务端主机带宽

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by ysc3839** [comment]
你配置文件里 type 是 stcp，但是文档里写的是 xtcp。
https://github.com/fatedier/frp/blob/master/README_zh.md#%E7%82%B9%E5%AF%B9%E7%82%B9%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F

**Comment by golfrey-dev** [comment]
> 
> 
> 你配置文件里 type 是 stcp，但是文档里写的是 xtcp。
> https://github.com/fatedier/frp/blob/master/README_zh.md#%E7%82%B9%E5%AF%B9%E7%82%B9%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F

type为xtcp时连不通，所以使用的stcp

**Comment by ysc3839** [comment]
你用了 stcp，所以就经过服务器了呀。

**Comment by fatedier** [comment]
xtcp 成功率和网络环境相关，准备的说是设备 NAT 类型，目前成功率不高。
stcp 是 secret tcp，是提高安全性，防止任何人都能访问到自己的服务。
