### ISSUE TITLE
连接成功 但是无法访问此网站

### ISSUE THREAD

**Issue by EasonApolo** [fatedier/frp#1649]
**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc 0.31.2
frps 0.31.2

**What operating system and processor architecture are you using (`go env`)?**
公网机器ubuntu
内网机器windows
机器都在国内

**Configures you used:**
（公网防火墙6000-10000端口已开，验证比如8080端口的服务可以访问。）
公网frps.init内容：
[common]
bind_port = 7000

（内网机器服务已开，127.0.0.1:80可以看到网页。）
内网frpc.init内容（x.x.x.x代指IP）：
[common]
server_addr = x.x.x.x
server_port = 7000
[http]
type = tcp
local_ip = 127.0.0.1
local_port = 80
remote_port = 6000

**Describe the results you received:**
内网启动后：
login to server success, get run id [def3b7a7f482ab4c], server udp port [0]
proxy added: [http]
[http] start proxy success

公网连接后：
[tcp.go:63] [aaa223afbb738ac3] [http] tcp proxy listen port [6000]
[control.go:445] [aaa223afbb738ac3] new proxy [http] success

结果：
似乎连接已经建立成功了，但外边打开x.x.x.x:6000还是显示“无法访问此网站”。
（另外我也尝试过内网用22端口用来ssh。但ssh -p 6000 user@x.x.x.x 也没有任何输出，和ssh -p +任意一个端口 的情况是一样的）
请问这种情况可能是什么原因？可能是因为内网的7000端口被封了吗？
本人比较小白，还请各位大佬指点。

**Comment by fatedier** [comment]
把你的 frps 和 frpc 用相同的配置，都部署在内网那台机器上，然后看下 ssh 能不能访问，如果可以，可能还是中间网络的问题。

**Comment by EasonApolo** [comment]
内网换了一台ubuntu服务器穿透成功了，虽然没明白为什么…
然后查到无域名tcp穿透[不能用6000端口](https://github.com/fatedier/frp/issues/75#issuecomment-421796361)，这似乎是chrome的安全设定。
感谢作者这么好的工具，现在疫情在家办公，远程桌面真顶不住。
