### ISSUE TITLE
关于数据转发速度

### ISSUE THREAD

**Issue by ghsa1994** [fatedier/frp#165]
今天搞了一个可以远程下载的工程，使用了frp进行了内网穿透数据转发，经测试下载速度只有20K到30K，太慢了，我的VPS是搬瓦工19刀的套餐，使用SSR翻墙可以达到下行2m/s+的速度,内网使用的树莓派。在内网测试，下载速度10m/s+，完全不受影响，所以不是树莓派的性能的问题。

想问问大家frp的转发性能到底是多少，不知道是不是配置的问题。

**Comment by ghsa1994** [comment]
补充一下我内网使用的是20M的移动宽带，也许是受限于移动宽带的上行速度垃圾，大家报一下大家的frp是什么样的转发速度，我好做个参考。谢谢

**Comment by wdc63** [comment]
用Ngrok转发移动20M，服务器是Vultr东京10M，用了速锐加速，看youtube 5000kbs，OWNCLOUD上传速度1M/S，差不多达到10M带宽，frp没用过，给你参考。

**Comment by mbj2014** [comment]
移动宽带不垃圾吧，你要在相似的价格上去比较。我的移动光宽带是100M的，赶上活动了，899两年。上行可以到20M的。

不过我也关心你这个问题，我只是用来做内网发布，应用压力不大，但也想知道这个转发会到怎样的水平。

**Comment by brucehelen** [comment]
确实，移动的上行还是挺良心的，我家100M，上行也能到20M

**Comment by Ivan-cn** [comment]
@wdc63
ngrok用的是哪个服务器？
另，你们做免流的？分享来用下
