### ISSUE TITLE
ssh 打开日志文件会断开重连，tcp打开数据量大的网页会断开重连

### ISSUE THREAD

**Issue by redrainz** [fatedier/frp#1651]
**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc frp_0.31.2_linux_arm
frps frp_0.31.2_linux_amd64

**What operating system and processor architecture are you using (go env)?**
公网机器ubuntu
内网机器raspbian
机器都在国内

**Configures you used:**

frps.init：
[common]
bind_port = 7000
dashboard_port = 7500
dashboard_user = xxx
dashboard_pwd = xxxx
max_pool_count = 50
             

内网frpc.init内容（x.x.x.x代指IP）：
[common]
server_addr = x.x.x.x
server_port = 7000
pool_count = 20

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000
tcp_mux = true

[web]
type = tcp
local_ip =127.0.0.1
local_port = 18080
remote_port = 18083
tcp_mux = true
use_compression = true

[front]
type = tcp
local_ip =127.0.0.1
local_port = 13000
remote_port = 18085
tcp_mux = true
use_compression = true

[boot]
type = tcp
local_ip =127.0.0.1
local_port = 8080
remote_port = 18084
tcp_mux = true
use_compression = true

**Steps to reproduce the issue:**
1.frp连接
2.用ssh执行 cat myout.file |grep '2/14 10:45'报错  myout.file文件64K

**Describe the results you received:**
链接中断并报错，可重连

frps报错信息：
2020/02/14 10:44:03 [I] [proxy.go:92] [f8d30c46b23a0682] [front] get a new work connection: [x.x.x.x:38134]
2020/02/14 10:45:04 [I] [control.go:305] [f8d30c46b23a0682] control writer is closing
2020/02/14 10:45:04 [I] [proxy.go:76] [f8d30c46b23a0682] [boot] proxy closing
2020/02/14 10:45:04 [I] [proxy.go:147] [f8d30c46b23a0682] [boot] listener is closed
2020/02/14 10:45:04 [I] [proxy.go:76] [f8d30c46b23a0682] [front] proxy closing
2020/02/14 10:45:04 [I] [proxy.go:147] [f8d30c46b23a0682] [front] listener is closed
2020/02/14 10:45:04 [I] [proxy.go:76] [f8d30c46b23a0682] [web] proxy closing
2020/02/14 10:45:04 [I] [proxy.go:147] [f8d30c46b23a0682] [web] listener is closed
2020/02/14 10:45:04 [I] [proxy.go:76] [f8d30c46b23a0682] [ssh] proxy closing
2020/02/14 10:45:04 [I] [proxy.go:147] [f8d30c46b23a0682] [ssh] listener is closed
2020/02/14 10:45:04 [I] [control.go:383] [f8d30c46b23a0682] client exit success
2020/02/14 10:45:04 [I] [service.go:392] [f8d30c46b23a0682] client login info: ip [x.x.x.x:38152] version [0.31.2] hostname [] os [linux] arch [arm]
2020/02/14 10:45:04 [I] [tcp.go:63] [f8d30c46b23a0682] [ssh] tcp proxy listen port [6000]
2020/02/14 10:45:04 [I] [control.go:445] [f8d30c46b23a0682] new proxy [ssh] success
2020/02/14 10:45:04 [I] [tcp.go:63] [f8d30c46b23a0682] [web] tcp proxy listen port [18083]
2020/02/14 10:45:04 [I] [control.go:445] [f8d30c46b23a0682] new proxy [web] success
2020/02/14 10:45:04 [I] [tcp.go:63] [f8d30c46b23a0682] [front] tcp proxy listen port [18085]
2020/02/14 10:45:04 [I] [control.go:445] [f8d30c46b23a0682] new proxy [front] success
2020/02/14 10:45:04 [I] [tcp.go:63] [f8d30c46b23a0682] [boot] tcp proxy listen port [18084]
2020/02/14 10:45:04 [I] [control.go:445] [f8d30c46b23a0682] new proxy [boot] success
2020/02/14 10:45:04 [I] [proxy.go:92] [f8d30c46b23a0682] [front] get a new work connection: [x.x.x.x:38152]
2020/02/14 10:45:11 [I] [proxy.go:92] [a354049e88c0870b] [gitea] get a new work connection: [x.x.x.x:44618]
2020/02/14 10:45:30 [I] [proxy.go:92] [f8d30c46b23a0682] [front] get a new work connection: [x.x.x.x:38152]

frpc报错信息：
2020/02/14 10:45:04 [E] [control.go:147] [f8d30c46b23a0682] work connection closed before response StartWorkConn message: EOF
2020/02/14 10:45:04 [E] [control.go:147] [f8d30c46b23a0682] work connection closed before response StartWorkConn message: EOF
2020/02/14 10:45:04 [I] [control.go:251] [f8d30c46b23a0682] control writer is closing
2020/02/14 10:45:04 [I] [service.go:148] [f8d30c46b23a0682] try to reconnect to server...
2020/02/14 10:45:04 [E] [control.go:147] [f8d30c46b23a0682] work connection closed before response StartWorkConn message: EOF
2020/02/14 10:45:04 [E] [control.go:147] [f8d30c46b23a0682] work connection closed before response StartWorkConn message: EOF

**Describe the results you expected:**
正常访问

**Additional information you deem important (e.g. issue happens only occasionally):**

几乎每次都能复现，访问网站也会出现这个情况，麻烦大佬的帮助啦

**Can you point out what caused this issue (optional)**
可能是因为链接超时？？

**Comment by fatedier** [comment]
尝试设置 protocl=kcp
