### ISSUE TITLE
go1.10.8自行编译frpc，启动后报stream closed及message type error

### ISSUE THREAD

**Issue by corychen2012** [fatedier/frp#1652]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
服务端及客户端均为0.31.2

**What operating system and processor architecture are you using (`go env`)?**
服务端 centos7.3    客户端  winxp sp3

**Configures you used:**
[common]
server_addr = x,x,x,x
server_port = 7000

[rd]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 12345

**Steps to reproduce the issue:**
1.在winxp安装go1.10.8，添加依赖库。编译生成frpc。编写frpc.ini。
2.运行frpc -c frpc.ini
3.日志刷屏报错

**Describe the results you received:**
2020/02/14 03:47:11 [I] [service.go:250] [87734f1762c80b61] login to server succ
ess, get run id [87734f1762c80b61], server udp port [0]
2020/02/14 03:47:11 [I] [proxy_manager.go:144] [87734f1762c80b61] proxy added: [
rd]
2020/02/14 03:47:11 [W] [control.go:229] [87734f1762c80b61] read error: message
type error
2020/02/14 03:47:11 [W] [control.go:255] [87734f1762c80b61] write message to con
trol connection error: stream closed
2020/02/14 03:47:11 [I] [service.go:148] [87734f1762c80b61] try to reconnect to
server...

**Describe the results you expected:**
frpc正常运行，已在另一macos环境使用release版本搭建frpc客户端，连接同一服务端可正常穿透。但自行编译的winxp版本就报这个错误，无法启动服务。

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by corychen2012** [comment]
补充：自行编译frps。并在同一台机器上运行frps，将frpc连到本机服务端，frpc可正常运行。

**Comment by corychen2012** [comment]
补充：centos服务端frps日志连接winxp客户端日志如下：
2020/02/14 13:54:37 [W] [control.go:335] [c43a814df1b9faf1] read error: message type error
2020/02/14 13:54:37 [I] [control.go:305] [c43a814df1b9faf1] control writer is closing
2020/02/14 13:54:37 [I] [control.go:383] [c43a814df1b9faf1] client exit success

**Comment by fatedier** [comment]
最好都在同一台机器上编译，可以交叉编译出不同系统的二进制文件。可以参考 Makefile.cross-compiles 中的命令。

另外最好使用最新的 go 版本编译。

**Comment by corychen2012** [comment]
在现有环境编译centos使用的linux/amd64版本frps服务端，部署后，服务端与客户端日志均显示正常，dashboard中也显示正常online，但内网穿透无效。
我的客户端是winxp环境，能用的最高go版本就是1.10.8了

**Comment by QQ2017** [comment]
> 在现有环境编译centos使用的linux/amd64版本frps服务端，部署后，服务端与客户端日志均显示正常，dashboard中也显示正常online，但内网穿透无效。
> 我的客户端是winxp环境，能用的最高go版本就是1.10.8了

你尝试下给XP更新下所有系统补丁。
另外在WIN10上也可以安装1.10.8的。
先用 go get -u 把frp源码down下来；然后下载绿色版go1.10.8，随便放个目录，然后使用bat命令编译。下面是我自己使用的bat命令可以编译成功：
D:\MyGopath\go1.10.8.windows-amd64\bin\go.exe build -a -ldflags "-s -w" -o ./bin/frpc_windows_386_XP.exe ./cmd/frpc/main.go
