### ISSUE TITLE
客户端配置文件能否自动从服务器端下载和热加载？

### ISSUE THREAD

**Issue by netyuchangfa** [fatedier/frp#1654]
一直是FRP的老用户，主要也是用于测试和学习之用。很方便很实用。感谢！
最近我发现NPS这款与FRP类似的工具，有个功用很方便易用：服务器端通过WEB管理方式做配置，客户端启动时只需要指定 一个key来连接服务器，后面，所有的配置只需要在服务器WEB上管理，客户端能自动热加载，当然，同时也支持本地的配置文件，非常不错。

既然是做远程穿透，客户端一般都是很分散或不方便现场去维护的情况就使用这款工具，如果FRP能远程集中管理自己，那也就能更好的远程管理各种需要管理的终端了。

感谢！！

**Comment by netyuchangfa** [comment]
这是一个非常不错的主意，望能增加上来。
FRT先能远程的集中管理好自己，再通过它去连接设备实现远程的维护和管理。

非常感谢！！！

**Comment by fatedier** [comment]
管理功能不在开源版本的计划中了，之后会有 Pro 版本，提供类似的集群管理能力。
