### ISSUE TITLE
使用frp的xtcp进行内网穿透，mjpg-screamer无法正常使用

### ISSUE THREAD

**Issue by hxan** [fatedier/frp#1656]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frp 0.27.0

**What operating system and processor architecture are you using (`go env`)?**
被访问主机Ubuntu 16.04   frp服务器Centos 7.5  客户端Centos7 

**Configures you used:**
被访问主机
[common]
server_addr = xxx
server_port = 8888
[p2p_ssh]
type = xtcp
sk = abcdefg
local_ip = 127.0.0.1
local_port = 22
##########################################

frp服务器
bind_port=8888
bind_udp_port=7001
##########################################
客户端
[common]
server_addr =xxx
server_port = 8888

[p2p_ssh_visitor]
type = xtcp
role = visitor
server_name = p2p_ssh
sk = abcdefg
bind_addr = 127.0.0.1
bind_port = 8080
######################
**Steps to reproduce the issue:**
1.在frp服务器开启frp
2.在客户端开启frp
3.在被访问主机开启frp以及mjpg-screamer

**Describe the results you received:**
当我在客户端浏览器访问127.0.0.1:8080
没有任何显示，但是通过telnet 可以检测到8080端口畅通
ssh的xtcp使用正常
**Describe the results you expected:**
在客户端浏览器正常显示mjpg-screamer传来的视频

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
和具体服务相关的问题还请自行调试，排查问题，无法一一解决。
