### ISSUE TITLE
How does frps and frpc authenticate each other? 

### ISSUE THREAD

**Issue by ofer-dev** [fatedier/frp#1659]
Issue is only used for submitting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.31.2

**What operating system and processor architecture are you using ('go env')?**
Ubuntu linux 18.04 & 19.10

**Configures you used:**

**frpc**

[common]
server_addr = *.*.*.*
server_port = 7000
log_file = ./frpc.log
protocol = kcp
token = *****
tls_enable = true

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000
use_encryption = true

**frps**

[common]
bind_port = 7000
kcp_bind_port = 7000
token = *****

**Steps to reproduce the issue:**
question, not an issue

How does frps and frpc authenticate each other? Is there some kind of Password-authenticated key agreement or shared key derived from supplied token?

**Comment by fatedier** [comment]
Hash(token + timestamp)

**Comment by ofer-dev** [comment]
OK, is there an option to use certificate(or any public key with mutual authentication) based authentication in order to prevent man in the middle and reply attacks?
thx

**Comment by fatedier** [comment]
Not support, maybe future.

**Comment by ofer-dev** [comment]
Ok, closing
