### ISSUE TITLE
frp 流量消耗怎么样？

### ISSUE THREAD

**Issue by Jexbat** [fatedier/frp#166]
空载状态下 frp 和服务器通信一天会消耗多少流量？与服务器的通信周期可以用配置文件修改么？应为可能会用在 iot设备上，用的无线网络，所以需要有流量方面的考虑。

**Comment by fatedier** [comment]
空闲状态下只有心跳包的消耗，每隔20s一次，目前是代码中写死的。
出流量，一天970KB。
入流量，一天125KB。

这部分是可优化的。
