### ISSUE TITLE
server with domain

### ISSUE THREAD

**Issue by galenzhao** [fatedier/frp#167]
在client的配置里，如果server是个domain，在log里边总会报错nslookup timeout，
我看请求的dns server地址并不是resov.conf里边配置的，而是一个同网段的ip，
可是这个ip的server并不存在，所以肯定是timeout的，
这个是bug，还是有什么需要配置的

**Comment by fatedier** [comment]
执行 `nslookup {your domain}` 结果如何？

**Comment by goer99** [comment]
确实在client的配置里，填写server的域名，是无法工作的，希望可以解决这个问题，谢谢。

**Comment by fatedier** [comment]
@goer99 请提供更详细的信息，比如配置文件，以及通过 dig 正常解析域名时使用的 dns server，可能相关的系统环境。

**Comment by goer99** [comment]
我又重新验证了一遍，没有这个问题了。如此看来上一次我遇到的问题，其原因并不出在域名解析上，只是被我误以为是dns解析问题了。

现在用域名写server地址是没问题的，工作正常。

**Comment by goer99** [comment]
btw, 下午试用了一下dog-tunnel，那个项目并不完整，很不好用。还是等frp的udp打洞吧。:)
