### ISSUE TITLE
BBR会影响kcp功能？

### ISSUE THREAD

**Issue by roiwk** [fatedier/frp#1672]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc  0.31.1
frps  0.31.1

**What operating system and processor architecture are you using (`go env`)?**
frpc  win10
frps  ubuntu18.04

**Configures you used:**
frpc.ini

```
[common]
server_addr = xxx
server_port = 8080
protocol = kcp
pool_count = 4
tcp_mux = true

... 

```

frps.ini

```
[common]
bind_port = 8080
kcp_bind_port = 8080
max_pool_count = 5
tcp_mux = true


```

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

`i/o deadline reached`

**Describe the results you expected:**

成功连接

**Additional information you deem important (e.g. issue happens only occasionally):**

server做了BBR加速

**Can you point out what caused this issue (optional)**

期间添加了BBR,  导致kcp连接报错。  不用kcp即可成功

**Comment by fatedier** [comment]
理论上不影响，bbr 只针对 tcp，开启之后建议不需要用 kcp 了，效果一样的。
