### ISSUE TITLE
心态爆炸！单机连不上，求帮助。

### ISSUE THREAD

**Issue by thatseason** [fatedier/frp#1675]
frps.ini
```
[common]
bind_port = 20443
kcp_bind_port = 20443
token = 123456
authentication_timeout = 60
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = 123456
vhost_http_port = 10080
vhost_https_port = 10443
subdomain_host = 123.com
```

frpc.ini
```
[common]
server_addr = 127.0.0.1
server_port = 20443
token = 123456
log_file = ./frpc.log
log_level = trace

[web]
type = http
local_ip = 127.0.0.1
local_port = 80
use_encryption = true
use_compression = true
subdomain = www
```

服务端：
启动命令：frps.exe -c frps.ini
![image](https://user-images.githubusercontent.com/25434493/75096468-d8fe5700-55da-11ea-920f-3ba3d3d88266.png)

客户端：
启动命令：frpc.exe -c frpc.ini
![image](https://user-images.githubusercontent.com/25434493/75096498-0b0fb900-55db-11ea-93be-4d5fad080b47.png)

不知道哪出错了，心态炸了

**Comment by thatseason** [comment]
最新版本：windows_0.31.2，X86和AMD64都是这样

**Comment by calidion** [comment]
是代码问题吗？我这里也无法转发。

**Comment by calidion** [comment]
ssh转发正常

**Comment by xqzr** [comment]
frps.ini
`[common]
bind_port = 20443
token = 123456
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = 123456
vhost_http_port = 10080
vhost_https_port = 10443
subdomain_host = 123.com`
frpc.ini
`[common]
server_addr = 127.0.0.1
server_port = 20443
token = 123456
log_file = ./frpc.log
log_level = trace

[web]
type = http
local_ip = 127.0.0.1
local_port = 80
use_encryption = true
use_compression = true
subdomain = www`

**Comment by fatedier** [comment]
按照 issue 格式，提供更多详细的信息。

**Comment by calidion** [comment]
@fatedier  能实现纯端口转发吗？不限TCP还是UDP。

**Comment by DGideas** [comment]
你的issue除了截图没有任何可以提供帮助的额外信息，目前的状况没有人能帮到你

考虑添加更多信息
