### ISSUE TITLE
纯TCP转发的配置？

### ISSUE THREAD

**Issue by calidion** [fatedier/frp#1676]
目前看到有ssh, web的配置。

不知道是不是可以配置成纯TCP转发？

无论什么上层协议都只做转发？

**Comment by ysc3839** [comment]
`ssh`只是个名称，`type = tcp` 即是“纯TCP转发”。

**Comment by calidion** [comment]
@ysc3839 多谢，我试试。

如果我只是想把端口转发到内网的nginx，是不是就可以实现多个域名了呢？

**Comment by calidion** [comment]
@ysc3839 太感谢了。

非常完美。

http, https的转发都非常的好。
