### ISSUE TITLE
我添加了dashboard，但是他并没有开启此功能（我无法访问)。

### ISSUE THREAD

**Issue by LiusCraft** [fatedier/frp#1678]
我添加了dashboard，但是他并没有开启此功能（我无法访问)。
![frps.ini配置信息](https://i.loli.net/2020/03/01/ej8FbM7HgmDKh46.png)
![启动frps信息](https://i.loli.net/2020/03/01/OVIaoMthzNfqWcw.png)

**Comment by Cyclonekid** [comment]
表示你启动有问题，根本就没有使用配置文件启动，使用配置文件启动的命令

./frps -c frps.ini

**Comment by fatedier** [comment]
和上面说的问题一样，后面如果没有用配置文件启动，我加一个日志提示吧，避免参数错误后不知道什么原因。
