### ISSUE TITLE
您好,可不可以不使用域名(即通过访问ip:port的形式)直接访问?

### ISSUE THREAD

**Issue by fengkaiwhu** [fatedier/frp#168]
目前配置文件frps.ini中custom_domains字段必须进行设置,设置之后必须通过域名访问吗?通过直接公网服务器的ip访问不可以吗?

**Comment by fatedier** [comment]
可以，使用 tcp 的转发类型。

设置域名是为了支持路由转发，这样多个域名都可以同时使用 80 端口。如果只有你一个人的一个客户端用的话，可以在 custom_domains 中填 ip，之后通过 ip 访问。
