### ISSUE TITLE
转发UDP端口只监听ipv6不监听ipv4

### ISSUE THREAD

**Issue by Cathgao** [fatedier/frp#1680]
客户端配置:
type = udp
local_ip = 127.0.0.1
remote_port = 27015
local_port = 27015

服务器与客户端均没有开启ipv6
服务器端使用netstat -ano查看只有UDP6 :::27015没有UDP 0.0.0.0:27015
![frps](https://user-images.githubusercontent.com/21031564/75668088-b7286280-5cb3-11ea-8303-13fa8dc75e37.png)

**Comment by QQ2017** [comment]
换一个端口试试呢？

**Comment by ouxlwhu** [comment]
服务端也遇到这个问题，换过端口，都起作用
只能监听ipv6的，ipv4的没有，导致客户端连不上服务端
[root@linux_amd64]# netstat -nap | grep 56000
tcp6       0      0 :::56000                :::*                    LISTEN      18652/./frps
[root@linux_amd64]# cat frps.ini
[common]
bind_port = 56000

使用release中的v0.32.0和v0.21.0都是这样，其他版本没试过
在两种环境中试过：
1.
sonic@aster241:~$ uname -a
Linux aster241 4.15.0-66-generic #75~16.04.1-Ubuntu SMP Tue Oct 1 14:01:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
2.
[root@linux_amd64]# uname -a
Linux iZm5e97u0ftapn9pk5ul65Z 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ouxlwhu** [comment]
找到一个文档描述，认为这种情况不是问题
https://blog.csdn.net/weixin_30662011/article/details/95843673?depth_1-utm_source=distribute.pc_relevant.none-task&utm_source=distribute.pc_relevant.none-task

**Comment by Cathgao** [comment]
> 找到一个文档描述，认为这种情况不是问题
> https://blog.csdn.net/weixin_30662011/article/details/95843673?depth_1-utm_source=distribute.pc_relevant.none-task&utm_source=distribute.pc_relevant.none-task

但我的事实上就是ipv4对这个端口没法连上

**Comment by fatedier** [comment]
Maybe not a problem about frp, search google for more info.

**Comment by jackluo2012** [comment]
遇到了同样的问题，怎么解决的

**Comment by ZeddShi** [comment]
一般是因为服务器端口没开，例如阿里云安全组没配
