### ISSUE TITLE
在客户端能否添加命令模式，或者web模式，查看连接到真实ip，目前都只看到127.0.0.1

### ISSUE THREAD

**Issue by hktalent** [fatedier/frp#1683]
在客户端能否添加命令模式，或者web模式，查看连接到真实ip，目前都只看到127.0.0.1
思路：

- 1、服务端得到真实IP，和临时的port，和客户端连接port形成对应关系
- 2、客户端通过临时port对应关系知道哪些真实ip连接上来了

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/README_zh.md#%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E7%9C%9F%E5%AE%9E-ip

参考文档说明，在自己的服务里获取到真实 IP。

**Comment by hktalent** [comment]
@fatedier 我当前转发的是tcp不是http呢
算了，我还是自己开发代码来实现这个关联关系吧

**Comment by fatedier** [comment]
Proxy Protocol
