### ISSUE TITLE
login to server failed: dial tcp: missing address

### ISSUE THREAD

**Issue by lyh543** [fatedier/frp#1684]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
`0.31.2`

**What operating system and processor architecture are you using (`go env`)?**
```
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\liu\AppData\Local\go-build
set GOENV=C:\Users\liu\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\liu\go
set GOPRIVATE=
set GOPROXY=off
set GOROOT=D:\Documents\Tools\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Documents\Tools\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\liu\AppData\Local\Temp\go-build147432250=/tmp/go-build -gno-record-gcc-switches
```

**Configures you used:**
以下两个版本均报相同错误：
```ini
# frpc.ini
[common]
server_addr = x.x.x.x # mydomain
server_port = 7000

[rdp]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 6000
```

```ini
# frpc.ini
[common]
# server_addr = 127.0.0.1
# server_port = 7000
```

**Steps to reproduce the issue:**
1. 服务器 `./frps -c frps.ini`
2. 客户端 `frpc -c frpc.ini`

**Describe the results you received:**

```cmd
>frpc -c frpc.ini
2020/03/05 09:50:47 [W] [service.go:97] login to server failed: dial tcp: missing address
dial tcp: missing address
```

**Describe the results you expected:**

成功链接（一个星期前还可以正常连接，现在突然连接不了）

**Additional information you deem important (e.g. issue happens only occasionally):**

最近在本机安装了Docker Desktop（不过安装以后一段时间仍然是可以使用 frpc 的，应该不是它的问题）  
关闭防火墙后仍然不行  
把 `frpc.exe` 和 `frpc.ini` 复制到别的电脑运行，均不会报这个错误

**Can you point out what caused this issue (optional)**

可能是本机的网络问题

~~我知道网络环境等相关的求助问题请转至其他论坛，但是百度Google都没有类似的问题，只能发这里了，希望作者大大能给一点debug的方向~~

**Comment by fatedier** [comment]
可能是 DNS 的异常导致的，可以 1. 修复 DNS 的异常。 2. 直接使用 IP 地址连接。

**Comment by lyh543** [comment]
今天测试了一下，发现又好了。。。迷惑bug
