### ISSUE TITLE
frps无响应

### ISSUE THREAD

**Issue by zxysm** [fatedier/frp#169]
使用0.81在阿里云香港centos6上运行服务端，输入
./frps -c ./frps.ini
后就没有提示了，控制台处于挂起状态，LOG如下：
2016/12/02 04:44:03 [main.go:182] [I] Start frps success
2016/12/02 04:44:03 [main.go:184] [I] PrivilegeMode is enabled, you should pay more attention to security issues
2016/12/02 05:00:18 [main.go:182] [I] Start frps success
2016/12/02 05:00:18 [main.go:184] [I] PrivilegeMode is enabled, you should pay more attention to security issues
2016/12/02 05:08:28 [main.go:182] [I] Start frps success
2016/12/02 05:08:28 [main.go:184] [I] PrivilegeMode is enabled, you should pay more attention to security issues
尝试使用客户端连接不成功，LOG如下（服务器IP已隐去）：
2016/12/02 05:06:22 [main.go:109] [I] Start frpc success
2016/12/02 05:06:23 [control.go:135] [E] ProxyName [privilege_tcp14662], connect to server [x.x.x.x:7000] error, dial tcp x.x.x.x:7000: connectex: No connection could be made because the target machine actively refused it.
2016/12/02 05:06:23 [control.go:39] [E] ProxyName [privilege_tcp14662], connect to server failed!
2016/12/02 05:06:24 [control.go:135] [E] ProxyName [privilege_tcp54310], connect to server [x.x.x.x:7000] error, dial tcp x.x.x.x:7000: connectex: No connection could be made because the target machine actively refused it.
2016/12/02 05:06:24 [control.go:39] [E] ProxyName [privilege_tcp54310], connect to server failed!
2016/12/02 05:06:24 [main.go:112] [W] All proxy exit!
请问是哪里出了问题？

**Comment by fatedier** [comment]
尝试使用其他系统的客户端连接试试。

**Comment by alexanderhsiang** [comment]
可能原因是你只在ini文件中只配置7000端口，没有配置http端口，http默认是80，所以触发了linux的PrivilegeMode模式。

如果是这样的话：
只需要把http端口配置为8080端口，然后使用nginx做反向代理即可。
