### ISSUE TITLE
在client(vistor)添加user属性时，无法正常访问，去掉user属性能正常访问

### ISSUE THREAD

**Issue by teote300** [fatedier/frp#1691]
## 版本及环境
frpc:0.31.2
frps:0.31.2
services:Windows Server 2016 数据中心版
client a:Windows Server 2008 R2 企业版
client b:Windows 10 10.0.18363.657

## client a frpc.ini
```
[common]
server_addr = x.x.x.x
server_port = n
user = LG

[xtcp_rdp]
type = xtcp
sk = 12345678
local_ip = 127.0.0.1
local_port = 3389
```

## client b frpc.ini
```
[common]
server_addr = x.x.x.x
server_port = n
user = SW

[LG_xtcp_rdp]
type = xtcp
role = visitor
server_name = LG.xtcp_rdp
sk = 12345678
bind_addr = 127.0.0.1
bind_port = 3390
```
## 说明
1.client b存在user属性时，无法访问，后台日志报错如下：

> 2020/03/09 23:04:01 [E] [visitor.go:251] [3cefb169b837c8bd] [SW.LG_xtcp_rdp] natHoleRespMsg get error info: xtcp server for [SW.LG.xtcp_rdp] doesn't exist

2.client b注释user属性时，成功

不知这是否为一个bug，感觉client b加上user属性时也应该能成功访问才对。

**Comment by deadlineOvO** [comment]
换个名字可以吗

**Comment by fatedier** [comment]
使用相同的 user。

**Comment by teote300** [comment]
> 换个名字可以吗

换名字不行，日志中是

> natHoleRespMsg get error info: xtcp server for [**newname**.LG.xtcp_rdp] doesn't exist

**Comment by teote300** [comment]
> 使用相同的 user。

谢谢大大回复，我试了下相同的user，日志中变成了这样
> 2020/03/12 21:45:00 [E] [visitor.go:251] [692363544970d16b] [LG.LG_xtcp_rdp] natHoleRespMsg get error info: xtcp server for [LG.LG.xtcp_rdp] doesn't exist

**Comment by fatedier** [comment]
相同的 user，server_name 只需要写 `xtcp_rdp` 就可以了，user 这个字段是自动加上的，这个本意是只能访问自己用户下的代理，只是目前还没有做严格限制。

**Comment by teote300** [comment]
> 相同的 user，server_name 只需要写 `xtcp_rdp` 就可以了，user 这个字段是自动加上的，这个本意是只能访问自己用户下的代理，只是目前还没有做严格限制。

谢谢大大回复，`user`字段原来是这样用的啊，问题总算解决了。
