### ISSUE TITLE
再次请求为htts2http插件添加中间证书支持

### ISSUE THREAD

**Issue by wlmqpsc** [fatedier/frp#1692]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.31.2

**What operating system and processor architecture are you using (`go env`)?**
Raspbian

**Configures you used:**
```
[common]
server_addr = xxx.xxx.xxx
server_port = 7000

[web]
type = http
local_port = 8123
custom_domains = xxxx.example.com

[test_htts2http]
type = https
custom_domains = xxxx.example.com
plugin = https2http
plugin_local_addr = 127.0.0.1:8123
plugin_crt_path = /home/pi/.acme.sh/xxxx/xxxxx.cer
plugin_key_path = /home/pi/.acme.sh/xxxx/xxxxx.key
plugin_host_header_rewrite = 127.0.0.1
plugin_header_X-From-Where = frp

```
**Steps to reproduce the issue:**
1.使用树莓派，搭建了home assistant，使用frp穿透，http可正常访问，遂修改配置如上，使用acme.sh配置ssl证书。
2.打开chrome浏览器，发现https不受信任，但证书有效，可正常访问。使用[sslchecker](https://www.sslshopper.com)进行测试（讲道理我好像应该使用443端口然后用更详细的ssl测试网站）
3.得知缺少证书链的支持

**Describe the results you received:**
https不受信任

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
替代方案是使用Caddy/Nginx/Apache等配置好SSL，且不开启htts2http插件（但是树莓派的内存要被榨干了，就很淦！）

**Can you point out what caused this issue (optional)**

**Comment by xqzr** [comment]
中间证书也写在“/home/pi/.acme.sh/xxxx/xxxxx.cer”里
