### ISSUE TITLE
Number Of Processes is high

### ISSUE THREAD

**Issue by tian-le** [fatedier/frp#1693]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.31.2

**What operating system and processor architecture are you using (`go env`)?**
Linux version 2.6.32-954.3.5.lve1.4.71.el6.x86_64 (mockbuild@buildfarm03.cloudlinux.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC) ) #1 SMP Fri Sep 6 06:22:16 EDT 2019

**Configures you used:**
frps.ini
[common]
bind_port = 17178
bind_udp_port = 17179
kcp_bind_port = 17178
log_file = xxxxx
log_level = error
dashboard_port = 17180
dashboard_user = xxxxx

frpc.ini
[common]
server_addr = tian-le.com
server_port = 17178
log_file = xxxxx
log_level = error
login_fail_exit = false

[sin_http_proxy]
type = tcp
remote_port = 17160
plugin = http_proxy
plugin_http_user = xxxxx
plugin_http_passwd = xxxxx

**Steps to reproduce the issue:**
1. Use crontab a job to schedule frps/frpc, the job would ensure only one instance of frps/frpc is scheduled
2. frps/frpc will run in background
3. The number of processes comes unusually high

**Describe the results you received:**
The number of processes would growing, and would reach 40 after few days, which is the system limitation of my shared host. If I kill the processes by run pkill frps and pkill frpc, the number of processes would go back to zero. After rerun frps and frpc in the backend, the number of processes would grow gradually again.

**Describe the results you expected:**
Both frps/frpc would create only one process, or only one process should be created for one TCP/UDP connection.

**Additional information you deem important (e.g. issue happens only occasionally):**
The number of processes is weird. For example, I was told there are more than 30 processes running, however, there are only 7 TCP connections + 1 UDP connection + 3 STCP connections get connected to the frp server.

**Can you point out what caused this issue (optional)**
The process/thread is not closed properly?

**Comment by fatedier** [comment]
Maybe fixed in #1668 , it will be released next version.

**Comment by tian-le** [comment]
> Maybe fixed in #1668 , it will be released next version.

Thanks for your reply, but I am afraid the problem is not resolved in version 0.32.0.

**Comment by fatedier** [comment]
Sorry, i misunderstand your issue. 

frp is writted in go, so it will always run as one single process. Maybe you should check your crontab job ?
