### ISSUE TITLE
连接的时候经常出现ProxyName [ssh], timeout trying to get work connection

### ISSUE THREAD

**Issue by fcying** [fatedier/frp#170]
远程客户端的log是
`connect to server [xxx.com:7000] error, lookup xxx.com on 223.5.5.5:53: dial udp 223.5.5.5:53: i/o timeout'

多连几次又正常了? 这是什么原因引起的问题?

**Comment by fatedier** [comment]
DNS 解析失败，阿里的 DNS 服务不稳定？

**Comment by fcying** [comment]
@fatedier  估计是....我换114后好多了...
