### ISSUE TITLE
新增的OIDC使用疑问

### ISSUE THREAD

**Issue by House-Men** [fatedier/frp#1701]
阅读了README关于OIDC的配置说明之后了解了
服务端需配置参数为
authentication_method = OIDC
oidc_issuer ，oidc_audience
客户端需配置参数为
authentication_method = OIDC
oidc_client_id，oidc_client_secret，oidc_audience，oidc_token_endpoint_url

疑问A：在v0.32.0的frpc_full.ini中并未看到关于oidc的相关参数示例与说明，而在frps_full.ini中看到了依据README说明应该配置在客户端的相关参数示例与说明。

疑问B：如果依据README中的说明客户端配置oidc_audience与oidc_token_endpoint_url，那么是否存在因防火墙原因客户端无法请求这个URL参数，还是说客户端只是需要配置oidc_client_id和oidc_client_secret，最终由服务端根据URL请求认证服务？

疑问C：因为初次接触搭建SSO OIDC认证，请问我是否可以通过搭建CAS或IdentityServer4来完成？

**Comment by fatedier** [comment]
配置文件中的示例应该是我写错了，以 README 中的为准。

这个功能是微软的同学贡献的，我还不是很熟悉，等有时间的时候需要研究下，再写一些详细的说明文档。
