### ISSUE TITLE
[建议]希望服务端Dashboard支持配置https

### ISSUE THREAD

**Issue by xqzr** [fatedier/frp#1704]
如题

**Comment by House-Men** [comment]
感觉你这个提议没啥实际意义。因为在实际生产环境中关闭反而会让frps更快更稳定，而且该功能目前并不能存储统计,当出现frps意外崩溃或重启操作时数据会重置，Dashboard本身功能也较为单一目前仅能观察运行状况 并非特别敏感的功能，增加https也只是加密状态数据的传输并不能增强访问安全性，为了提高安全性还是建议你 不要允许公网访问Dashboard 如果一定要开启公网访问 建议防火墙特定允许某个固定IP访问 个人电脑通过更加安全的VPN或自建代理服务认证接入代理固定IP后访问Dashboard会更加安全。况且你一定要Dashboard支持https同样可以使用frpc对Dashboard端口做https代理或者用nginx反向代理成https 总之方法很多。
