### ISSUE TITLE
How to get mini frpc(frp_0.10.0_linux_arm)

### ISSUE THREAD

**Issue by loveminisun** [fatedier/frp#1706]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
   frp_0.10.0_linux_arm

**What operating system and processor architecture are you using (`go env`)?**
  linux arm

**Configures you used:**
   common configure

**Steps to reproduce the issue:**
1.  befor upx :The  size of  frp_0.10.0_linux_arm-frpc is about 3.8MB. @ "https://github.com/fatedier/frp/releases/tag/v0.10.0 ",
2.  I get the the codes of the veison 0.10.0, compile this version, by package.sh, go build -ldflags -w -s. the size larger than 5MB

**Describe the results you received:**
the compile frpc size is larger than 5MB
**Describe the results you expected:**
 I want to get the size , smaller than 3.8MB
**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by blizard863** [comment]
https://github.com/gofrp/tiny-frpc/releases
