### ISSUE TITLE
求胜：frp支持创建2个vhost_http_port 吗

### ISSUE THREAD

**Issue by man2018** [fatedier/frp#1708]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.31.2

**What operating system and processor architecture are you using (`go env`)?**
群晖NAS
CentOS

**Configures you used:**
[common]
tcp_mux = true
token = nas
use_compression = true
use_encryption = true
bind_port = 7000
subdomain_host = xxx.com
vhost_http_port = 5000
vhost_https_port = 5001

# frpc.ini
[common]
tcp_mux = true
use_compression = true
use_encryption = true
token = nas
server_addr = x.x.x.x
server_port = 7000
admin_addr = 127.0.0.1
admin_port = 7400

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

[nas http]
type = http
local_ip = 127.0.0.1
local_port = 5000
subdomain = nas
use_compression = true
use_encryption = true

[nas https]
type = https
local_ip = 127.0.0.1
local_port = 5001
subdomain = nas
use_compression = true
use_encryption = true

**Steps to reproduce the issue:**
1.目前我能实现nas.xxx.com:5000访问NAS，会自动进入到https 这步是正常的
2.
3.

**Describe the results you received:**
能正常进入NAS

**Describe the results you expected:**
我想再加个web，就是访问NAS里面的plex，我发现只能在服务端配置一个vhost_http_port ,我要实现的是plex.xxx.com:32400可以进入到plex

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by kirahartman** [comment]
不需要建两个vhost http port 这个subdomain可以端口复用的。只要在frpc里面再加一项
[plex]
type = http
local_ip = 127.0.0.1
local_port = 2400
subdomain = plex
use_compression = true
use_encryption = true

=============
这样可以通过http://plex.xxx.cpm:5000 访问到2400端口

**Comment by fatedier** [comment]
直接使用 tcp 或者向楼上说的一样。
