### ISSUE TITLE
如何最小化编译frpc

### ISSUE THREAD

**Issue by loveminisun** [fatedier/frp#1709]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frp_0.10.0_linux_arm

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**
就是普通的最小配置ini

**Steps to reproduce the issue:**
1.从github frp 0.10.0版本，找到发布在frphttps://github.com/fatedier/frp/releases/download/v0.10.0/frp_0.10.0_linux_arm.tar.gz
这个压缩包，解压后，用upx对frpc进行压缩，可以到1.29M
2.但是用对应分支的代码进行下载，并用package,sh进行打包编译，这个打包编译出来的结果，然后，再用upx,进行压缩，实际上却只能导1,9M
3.内含有package,sh 这个打包编译方式，已经含有-ldfalg -w -s.

**Describe the results you received:**
v0.10.0版本实际根据对应分支源代码，frpc编译出来并压缩有1.9MB
**Describe the results you expected:**
因为我的arm主板flash空间有限，希望编译出来的frpc，在支持tcp,http的基础上尽可能的小。

**Additional information you deem important (e.g. issue happens only occasionally):**

寻求各位专家的支持，在线急等。
**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
使用旧版本 golang 编译。
