### ISSUE TITLE
类似花生壳的域名绑定

### ISSUE THREAD

**Issue by zlhdd108** [fatedier/frp#171]
你好，请问这个能实现类似花生壳外网的ddns么，就是如果我的路由是运营商的NAT，那么我直接在路由上运行frp的客户端，然后只需要在路由上配置要转发的端口来完成内网穿透

**Comment by fatedier** [comment]
不是很理解，和花生壳外网的 ddns 不是一个原理。frp 是需要有一台公网服务器做流量转发的。
