### ISSUE TITLE
Dashboard anti-brute force

### ISSUE THREAD

**Issue by befantasy** [fatedier/frp#1712]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
FRP 0.32.0

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**
dashboard可否加入brute force机制？本打算使用nginx反代frp 7500端口，借助fail2ban和ngixn来实现。但搞了半天，反代不成功。不知道有什么办法可以解决dashboard的brute force破解？

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by befantasy** [comment]
补充一下，刚才用nginx反代，防火墙只允许localhost连接7500端口，搞定了。
但还是希望FRP能原生支持时间窗口内密码重试次数限制。

**Comment by mmiker** [comment]
搭车提个建议， 客户端的static_file 的显示格式可否美化一下，比如加个html的<table>.,现在这样看着有点丑。

**Comment by botsphp** [comment]
再搭个车吧，assets下的 html 源文件在哪个 repo，想改一下源文件

**Comment by fatedier** [comment]
可以看出来，这方面类似的通用需求很多，每个人都有自己的想法，如果一一实现，相当于本末倒置。最好还是组合其他专业工具一起使用。
