### ISSUE TITLE
Port Restricted Cone的NAT网络类型XTCP点对点穿透远程桌面失败

### ISSUE THREAD

**Issue by bigbryant** [fatedier/frp#1713]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
均为0.32.0

**What operating system and processor architecture are you using (`go env`)?**
服务器端：VPS Ubuntu 16.04 LTS 64bit
被访问端：Windows10 LTSC2019 64bit，x64 CPU
访问端：Windows10 Professional 64bit，x64 CPU

**Configures you used:**
【服务器端】
[common]
bind_port = 47000
bind_udp_port = 47001

log_file = ./frps.log
log_level = info
log_max_days = 7

authentication_method = token
token = xxxxx

【被访问端】
[common]
server_addr = xx.xx.xx.xx
server_port = 47000

log_file = ./logs/frpc.log
log_level = info
log_max_days = 7

token = xxxxx
// 点对点映射远程桌面
[p2p_RDP]
type = xtcp
sk = xxxxxx
local_ip = 127.0.0.1
local_port = 43389

【访问端】
[common]
server_addr = xx.xx.xx.xx
server_port = 47000

log_file = ./logs/frpc.log
log_level = info
log_max_days = 7

token = xxxxx
// 点对点映射远程桌面
[p2p_RDP_visitor]
type = xtcp
role = visitor
server_name = p2p_RDP
sk = xxxxxx
bind_ip = 127.0.0.1
bind_port = 6000

**Steps to reproduce the issue:**
网络NAT类型为Port Restricted Cone
在访问端使用远程桌面连接localhost:6000，连接失败，弹出提示“内部错误”。

**Describe the results you received:**
服务端的log里面好像看不出什么信息
服务端：
2020/03/21 00:36:02 [I] [service.go:420] [7ed36de6dc0a4ee1] client login info: ip [访问端外网IP:27353] version [0.32.0] hostname [] os [windows] arch [amd64]
2020/03/21 00:36:16 [I] [proxy.go:91] [1038c9f4c4663ff1] [p2p_RDP] get a new work connection: [访问端外网IP:27432]
2020/03/21 00:39:10 [I] [control.go:308] [7ed36de6dc0a4ee1] control writer is closing
2020/03/21 00:39:10 [I] [control.go:383] [7ed36de6dc0a4ee1] client exit success
被访问端：
2020/03/21 00:36:22 [W] [proxy.go:373] [1038c9f4c4663ff1] [p2p_RDP] get sid from visitor error: read udp 局域网IP:60411: i/o timeout
访问端：
2020/03/21 00:36:03 [I] [service.go:257] [7ed36de6dc0a4ee1] login to server success, get run id [7ed36de6dc0a4ee1], server udp port [47001]
2020/03/21 00:36:03 [I] [visitor_manager.go:74] [7ed36de6dc0a4ee1] start visitor success
2020/03/21 00:36:03 [I] [visitor_manager.go:118] [7ed36de6dc0a4ee1] visitor added: [p2p_RDP_visitor]
2020/03/21 00:36:25 [W] [visitor.go:281] [7ed36de6dc0a4ee1] [p2p_RDP_visitor] get sid from client error: read udp 局域网IP:58150->访问端外网IP:27561: i/o timeout

**Describe the results you expected:**
成功穿透

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by lazy-luo** [comment]
额，非NAT-4网络，P2P可以尝试一下我的TCP方案。xtcp本身有可能被Qos

**Comment by bigbryant** [comment]
> 额，非NAT-4网络，P2P可以尝试一下我的TCP方案。xtcp本身有可能被Qos

大佬，可否请教如何使用tcp实现点对点穿透么？

**Comment by fatedier** [comment]
xtcp 目前缺少精力优化维护，成功率不高，无法穿透时可使用 stcp。
