### ISSUE TITLE
能否增加frpc对应多个frps的功能

### ISSUE THREAD

**Issue by Felix-Bao** [fatedier/frp#1715]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc 0.32    fprs 0.32

**What operating system and processor architecture are you using (`go env`)?**
OpenWRT  MIPS

**Configures you used:**
希望增加单个frpc对应两个或多个frps的功能

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
我曾尝试在frpc的路由器上手动输入命令开启第二个frpc进程，虽然成功了，但是15分钟左右就断开连接了，不知道什么原因。

**Describe the results you expected:**
希望在下一个版本中增加对应多个frps的功能。这其实很有用的，当一个frps出现问题无法访问时，需要有个备用的。

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
> 我曾尝试在frpc的路由器上手动输入命令开启第二个frpc进程，虽然成功了，但是15分钟左右就断开连接了，不知道什么原因。

找到根本原因比较好。

**Comment by bigbryant** [comment]
这个功能我在win环境下实现了，两套frps两套配置分别启动，运行良好，不知道是不是其他平台版本有什么限制

**Comment by Blichus** [comment]
我在linux版本实现是可行的，放置两个不同的frpc二进制执行文件路径和两个不同的frpc.ini配置文件，两个进程可以同时正常工作。

**Comment by Felix-Bao** [comment]
> 我在linux版本实现是可行的，放置两个不同的frpc二进制执行文件路径和两个不同的frpc.ini配置文件，两个进程可以同时正常工作。

二进制执行文件也要不同路径吗？直接将/usr/bin/frpc复制到其他目录似乎无法执行，我把它复制到同目录下并改名叫frpc2，然后执行  frpc2 -c /etc/config/fprc2.ini ，可以运行，但还是15分钟后断开。你是怎么做的？

**Comment by xqzr** [comment]
多开解决
./frpc -c ./frpc1.ini
./frpc -c ./frpc2.ini
./frpc -c ./frpc3.ini
...
./frpc -c ./frpc10.ini

**Comment by Felix-Bao** [comment]
看来差不多啊，看来我的15分钟断开的问题另有原因。
