### ISSUE TITLE
frp_0.32.0_windows_386.zip 下载被windows10报特洛伊木马

### ISSUE THREAD

**Issue by tldzyx** [fatedier/frp#1719]
![image](https://user-images.githubusercontent.com/5987706/77754378-38320a00-7066-11ea-875b-b4ff9bfc8d82.png)

**Comment by fatedier** [comment]
golang 编译应用正常现象，不放心建议自行源码编译。

**Comment by QQ2017** [comment]
误报是所有杀毒软件的通病，好在wd是可以提交误报的。
