### ISSUE TITLE
服务器连接失败。我两台机的时间分秒不差。一模一样的

### ISSUE THREAD

**Issue by fyhong** [fatedier/frp#172]
2016/12/10 21:47:58 [main.go:109] [I] Start frpc success
2016/12/10 21:47:58 [control.go:181] [E] ProxyName [ssh], start proxy error, ProxyName [ssh], authorization timeout
2016/12/10 21:47:58 [control.go:39] [E] ProxyName [ssh], connect to server failed!
2016/12/10 21:47:58 [main.go:112] [W] All proxy exit!
2016/12/10 21:55:27 [main.go:109] [I] Start frpc success
2016/12/10 21:55:27 [control.go:181] [E] ProxyName [ssh], start proxy error, ProxyName [ssh], authorization timeout
2016/12/10 21:55:27 [control.go:39] [E] ProxyName [ssh], connect to server failed!
2016/12/10 21:55:27 [main.go:112] [W] All proxy exit!

我的服务器是linux,客户端是window,会报上面错误。
客户端换成是linux就不会出错。什么原因

**Comment by fatedier** [comment]
时区问题？

**Comment by fyhong** [comment]
服务器和客户端时间分秒不差

**Comment by fatedier** [comment]
v0.9.0 的版本中可以在 frps 的配置文件中将 authentication_timeout 设置为 0，将不会进行超时校验。
