### ISSUE TITLE
连接数过多的一点问题

### ISSUE THREAD

**Issue by yuxuechao** [fatedier/frp#1720]
目前我使用了一台云服务器代理了大概1000多台机器，有500linux500window，目前只能使用一半数量，如果开启全部代理 大约有100多连不上，还有云服务器的连接数过多，导致dashboard加载不出来的问题

**Comment by QQ2017** [comment]
云服务器是什么操作系统版本
连接数最多是多少

**Comment by yuxuechao** [comment]
云服务器Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-72-generic x86_64)
连接数最多892

**Comment by yuxuechao** [comment]
我这个连接数问题不是frp问题，是系统/etc/security/limits.conf，最大进程数和最大文件打开数默认限制了，修改开放到需要的数量接好了，谢谢大佬
