### ISSUE TITLE
you can't open the application "frpc@.service.app"

### ISSUE THREAD

**Issue by kuyu132** [fatedier/frp#1724]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.32.0

**What operating system and processor architecture are you using (`go env`)?**
MacOS 10.14.6 i7 7920hq

**Configures you used:**
default config

**Steps to reproduce the issue:**
download the release package and open the systemd folder, then click the app program

**Describe the results you received:**
you can't open the application "frpc@.service.app"

**Describe the results you expected:**

**Comment by fatedier** [comment]
Search [google](https://www.google.com/search?newwindow=1&sxsrf=ALeKk03n7olToBfWndGT0YMl4yMHEK_mgg%3A1585727823958&ei=T0mEXq-SOpb9-gSpnr7wDA&q=how+to+execute+a+binary+program+in+macos&oq=how+to+execute+a+binary+program+in+macos&gs_lcp=CgZwc3ktYWIQAzoECCMQJ1CcEVi5F2CkGWgAcAB4AIABhgKIAfIRkgEEMi0xMJgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwjv9aC94MboAhWWvp4KHSmPD84Q4dUDCAs&uact=5) for more info.
