### ISSUE TITLE
Brother this FRPS I was in win2003 is directly run no problem, command line and configuration file on the wrong

### ISSUE THREAD

**Issue by henry3695** [fatedier/frp#1725]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
vesion 0.32

**What operating system and processor architecture are you using (`go env`)?**
win2003  x86

**Configures you used:**
# frps.ini
[common]
bind_port = 10005

**Steps to reproduce the issue:**
1.Brother this FRPS I was in win2003 is directly run no problem, command line and configuration file on the wrong
2.
3.

**Describe the results you received:**
D:\frps>frps.exe -c d:\frps\frps.ini
panic: Failed to find GetFileInformationByHandleEx procedure in kernel32.dll: Th
e specified procedure could not be found.

goroutine 1 [running]:
syscall.(*LazyProc).mustFind(0x11849a00)
        /usr/local/go/src/syscall/dll_windows.go:311 +0x42
syscall.(*LazyProc).Addr(0x11849a00, 0xee6320)
        /usr/local/go/src/syscall/dll_windows.go:318 +0x21
internal/syscall/windows.GetFileInformationByHandleEx(0x75c, 0x9, 0x11877c04, 0x
8, 0x3, 0x1181e048)
        /usr/local/go/src/internal/syscall/windows/zsyscall_windows.go:353 +0x27

os.newFileStatFromGetFileInformationByHandle(0x1184e0a0, 0x10, 0x75c, 0x0, 0x118
4e0a0, 0x10)
        /usr/local/go/src/os/types_windows.go:52 +0x135
os.(*File).Stat(0x11806608, 0xa963d4, 0x11806608, 0x0, 0x11806608)
        /usr/local/go/src/os/stat_windows.go:55 +0x133
io/ioutil.ReadFile(0x1184e0a0, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:62 +0xac
github.com/fatedier/frp/models/config.GetRenderedConfFromFile(0x1184e0a0, 0x10,
0x118d81e0, 0x1191e150, 0x14ac5d8, 0x8a3800)
        /root/frp/frp-0.32.0/models/config/value.go:56 +0x2d
main.glob..func1(0xee2160, 0x11804c10, 0x0, 0x2, 0x0, 0x0)
        /root/frp/frp-0.32.0/cmd/frps/root.go:105 +0x6b
github.com/spf13/cobra.(*Command).execute(0xee2160, 0x11849a68, 0x2, 0x3, 0xee21
60, 0x11849a68)
        /root/gopkg/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x337
github.com/spf13/cobra.(*Command).ExecuteC(0xee2160, 0xa7242280, 0x16019ad5, 0x1
1848018)
        /root/gopkg/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x244
github.com/spf13/cobra.(*Command).Execute(...)
        /root/gopkg/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.Execute()
        /root/frp/frp-0.32.0/cmd/frps/root.go:127 +0x24
main.main()
        /root/frp/frp-0.32.0/cmd/frps/main.go:31 +0xe6

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
No support for win2003 any more since frp is written in go.  See here https://golang.org/doc/install#requirements .
