### ISSUE TITLE
what if ssh port on serverA is different and not default 22

### ISSUE THREAD

**Issue by Harsharma2308** [fatedier/frp#1727]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frps and frpc both 0.32.0

**What operating system and processor architecture are you using (`go env`)?**
ubuntu 16.04 ; amd64

**Configures you used:**
Current frps.ini-
```
[common]
bind_port = 7000
```

frpc.ini-
```
[common]
server_addr = 128.2.178.3
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000
```

**Describe the results you received:**
1. i can't ssh my pc (serverB) on editing frpc files.
2. The system on which frps is running(serverA) has default ssh port as 17219. What changes should i make

On running frps, iget the message- 
```
2020/04/02 02:13:34 [I] [service.go:157] frps tcp listen on 0.0.0.0:7000
2020/04/02 02:13:34 [I] [root.go:209] start frps success
```

But no message on starting frpc.

**Comment by fatedier** [comment]
```ini
[common]
server_addr = 128.2.178.3
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 17219
remote_port = 6000
```
