### ISSUE TITLE
[DISCUSS]Trace access IP and notify

### ISSUE THREAD

**Issue by arugal** [fatedier/frp#1731]
### Motivation

Trace the source IP of the access proxy, and notify other software.
    
### Modification
    
+ Add [TraceAccessIp(pxyName string, userRemoteAddr string)](https://github.com/arugal/frp/blob/89d5f73c8c74f77bf4bac955fd12af96d52c47e4/models/plugin/server/manager.go#L125-L133) method to the server manage plugins,  used to record the address of the access proxy
+ Call `TraceAccessIp` method in [HandleUserTcpConnection(pxy Proxy, userConn net.Conn, serverCfg config.ServerCommonConf)](https://github.com/arugal/frp/blob/89d5f73c8c74f77bf4bac955fd12af96d52c47e4/server/proxy/proxy.go#L252)
+ [Notify](https://github.com/arugal/frp/blob/89d5f73c8c74f77bf4bac955fd12af96d52c47e4/models/plugin/server/manager.go#L136-L160) other software
    
### Result
Based on the above ideas and [manager-plugin](https://github.com/arugal/frp-manager), I can quickly see who is accessing the proxy.

![image](https://user-images.githubusercontent.com/26432832/78455215-8b900200-76cf-11ea-983e-d984f2e81d74.png)

**Comment by fatedier** [comment]
1. We should define a new operation for this like `NewUserConn`.
2. Define a content struct like other operations.

```go
type NewUserConn struct {
    User UserInfo

    ProxyName string
    RemoteAddr string
}
```

3. `HandleUserTcpConnection` maybe not suitable to inject plugin opeartion. Not all proxy type will call this function such as http, udp.

**Comment by arugal** [comment]
> We may need to refctor code If we want to implement this plugin in a graceful way.

Hi @fatedier thank you for your quick reply. Do we need to discuss the details of refactoring through WeChat?

**Comment by fatedier** [comment]
@arugal It's convenient for others to track the issue if we discuss here. 

I consider that you can first implement this plugin API in your way and describe which proxy types it supports in document, since refactoring is a complex work and i will take much time to redesign it. WDYT?

**Comment by arugal** [comment]
>  @arugal It's convenient for others to track the issue if we discuss here.

Agreed

> I consider that you can first implement this plugin API in your way and describe which proxy types it supports in document

I will initiate a PR based on the comments.
