### ISSUE TITLE
静态文件插件如何同时使用xtcp p2p穿透模式

### ISSUE THREAD

**Issue by carlsue** [fatedier/frp#1734]
按照官方文档，这里必修指定服务器的远程端口，这个是正常的服务器转发模式，请问如何在使用p2p模式下使用静态文件插件？

# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[test_static_file]
type = tcp
remote_port = 6000
plugin = static_file
# 要对外暴露的文件目录
plugin_local_path = /tmp/file
# 访问 url 中会被去除的前缀，保留的内容即为要访问的文件路径
plugin_strip_prefix = static
plugin_http_user = abc
plugin_http_passwd = abc

**Comment by fatedier** [comment]
结合以下两个文档配置。

[点对点内网穿透](https://github.com/fatedier/frp/blob/master/README_zh.md#%E7%82%B9%E5%AF%B9%E7%82%B9%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F)
[客户端插件](https://github.com/fatedier/frp/blob/master/README_zh.md#%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8F%92%E4%BB%B6)
