### ISSUE TITLE
ssh: connect to host 218.xx.xxx.xxx port 6000: Connection timed out

### ISSUE THREAD

**Issue by chenzeng11** [fatedier/frp#1737]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.32.1

**What operating system and processor architecture are you using (`go env`)?**
天翼云服务器：Linux 6p3uujyo2lv1e3ox-0407868 4.4.0-151-generic #178-Ubuntu SMP Tue Jun 11 08:30:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
内网服务器：Linux wu-ThinkStation-P720 4.15.0-91-generic #92~16.04.1-Ubuntu SMP Fri Feb 28 14:57:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
测试机：windows 10
**Configures you used:**
一、天翼云服务器：
vim frps.ini
[common]
bind_port = 7000
二、内网服务器
[common]
server_addr = 218.xx.xx.xxx
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

**Steps to reproduce the issue:**
1.天翼云服务器开启：./frps -c ./frps.ini
2.内网服务器开启：./frpc -c ./frpc.ini
3.测试机连接：ssh -oPort=6000 wu@218.xx.xx.xxx

**Describe the results you received:**
1.天翼云服务器：2020/04/08 12:51:37 [I] [service.go:420] [b5a1ac64f02392c6] client login info: ip [211.165.128.35:41434] version [0.32.1] hostname [] os [linux] arch [amd64]
2020/04/08 12:51:37 [I] [tcp.go:63] [b5a1ac64f02392c6] [ssh] tcp proxy listen port [6000]
2020/04/08 12:51:37 [I] [control.go:445] [b5a1ac64f02392c6] new proxy [ssh] success
2. 内网服务器：2020/04/08 12:51:37 [I] [service.go:282] [b5a1ac64f02392c6] login to server success, get run id [b5a1ac64f02392c6], server udp port [0]
2020/04/08 12:51:37 [I] [proxy_manager.go:144] [b5a1ac64f02392c6] proxy added: [ssh]
2020/04/08 12:51:38 [I] [control.go:179] [b5a1ac64f02392c6] [ssh] start proxy success
3. 测试机：ssh: connect to host 218.xx.xx.xxx port 6000: Connection timed out

**Describe the results you expected:**
ssh success

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by Rambo1203** [comment]
1. 从你服务器和客户端的启动注册情况可以看出，配置没有问题

2. 检查 6000 7000 端口在服务器是否已经开启
firewall-cmd --zone=public --list-ports
firewall-cmd --zone=public --add-port=6000/tcp --permanent
firewall-cmd --zone=public --add-port=7000/tcp --permanent
firewall-cmd --reload

3. 采用 ssh -oPort=6000 wu@218.x.x.x 进行访问即可
