### ISSUE TITLE
我想了解一下frp的设计架构图

### ISSUE THREAD

**Issue by magicdogs** [fatedier/frp#174]
![image](https://cloud.githubusercontent.com/assets/22540413/21102627/e686e13a-c0b9-11e6-86ff-f972034a1378.png)
我有个疑惑，希望得到您的解答，在此非常感谢。
1.所有的frpc 与 frps 都是通过 frps 的7000 端口进行反向代理传递数据的吗？ 还是直接通过 指定的映射端口进行代理的？假设我需要映射本地的3306端口到远程8099 端口，frpc 连接 frps 7000 端口，通过协议 来动态开启8099 端口 并将8099 端口的所有数据都转发到7000 ，再由7000 转发给 frpc  还是 在frps 启动的时候就已经开启了8099 端口， 再由frpc 直接连接到8099 端口进行身份认证，认证通过后，将8099 号端口的所有数据直接转发到认证的socket上呢？ 我是java 方向的，最近在研究反向代理，使用netty框架，思路有点乱。:( ...

**Comment by fatedier** [comment]
你的流程图大致上是 ok 的，frpc 和 frps 之间全部都通过 7000 端口通信。

frpc 在启动时会向 frps（通过 7000 端口） 发送注册信息，成功后，frps 就已经开始监听 8099 端口。

**Comment by magicdogs** [comment]
那如果 有 10 connect 链接到8099 端口， 这 10 个的请求数据 都转发到 7000 ， 那7000端口又如何区分 同一个管道过来的数据是 属于哪一个connect 发送的呢？ @fatedier

**Comment by fatedier** [comment]
这个你就自己好好考虑吧😁

**Comment by fatedier** [comment]
@magicdogs 之后有时间会写一些文章介绍一下整体的架构以及一些实现细节，最近比较忙，空闲时间不多。

**Comment by magicdogs** [comment]
@fatedier  哦哦，好的 ，期待 ing ...  😄

**Comment by magicdogs** [comment]
为啥不拉一个群 ， 有时间可以让对 frp 感兴趣的用户一起交流 @fatedier  ❓

**Comment by fatedier** [comment]
可以考虑，但是暂时还没有这部分精力。

**Comment by fatedier** [comment]
@magicdogs 建了一个 qq 群，606194980，方便大家反馈一些问题。
