### ISSUE TITLE
frps在美国，frpc在中国，时间都设成当地时间吗？

### ISSUE THREAD

**Issue by stingwan** [fatedier/frp#1741]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frps 0.30.0 at centos7.5
frpc 0.30.0 at NAS

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**
[common]
bind_port=7000
vhost_http_port=80
vhost_https_port=443
token=12345678
--------
[common]
server_addr=my real IP
server_port=7000
auth_token=12345678
[nas]
type=http
local_ip=my nas IP
local_port=5000
custom_domains=my applied domain main 

**Steps to reproduce the issue:**
1.running ./frps  -c ./frps.ini
2.running ./frpc -c ./frpc.ini
3.

**Describe the results you received:**
after running frps, I see :start frps success
After running frpc,I see: authorization failed ;on the server side ,I see:register control error :authorization failed

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
I think the time on  server and client is not the same .So I submit the issue.

**Comment by fatedier** [comment]
[客户端连接失败，提示 authorization failed](https://github.com/fatedier/frp/wiki#%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%BF%9E%E6%8E%A5%E5%A4%B1%E8%B4%A5%E6%8F%90%E7%A4%BA-authorization-failed)
