### ISSUE TITLE
win服务端+linux386客户端 持续传输速度正常 唤其新的链接需要等待10s左右。

### ISSUE THREAD

**Issue by sunxiaoyou** [fatedier/frp#1744]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc + frps

**What operating system and processor architecture are you using (`go env`)?**
windows frps + linux frpc

**Configures you used:**
最基础的配置

**Steps to reproduce the issue:**
1.每次开启一个新的链接就会重现，穿透的网页需要转10s才能打开。

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
请按照 issue 格式提供足够的信息。
