### ISSUE TITLE
【建议】服务端兼容客户端&安装成为系统服务的建议

### ISSUE THREAD

**Issue by Hokia** [fatedier/frp#1745]
1、内网主机通过DMZ暴露于公网，可以安装Frps提供服务。此时要转发内网的其他主机，便需要再启动Frpc指向其他内网IP。是否可以增加通过如下方式，解决在该场景下S/C需要同时启动的不便。
# frps.ini
>[common]
bind_port = 7000
[ssh]
type = tcp
local_ip = 192.168.1.78
local_port = 22
remote_port = 6000

2、Frp的windows版本可以配合winsw软件实现开机启动。是否可以增加通过如下方式，解决安装第三方软件的不便。
#CMD
>frps -service install -c frps.ini

*Frp对我很有帮助，希望功能可以不断完善，越做越好。

**Comment by fatedier** [comment]
1. 这种反向代理的场景可以直接使用 nginx 或 haproxy，frp 本身是 c/s 的架构，有自身适合的场景，不能为了使用上的一些简化而让项目本身变复杂，变成一个大杂烩。单纯部署，运维上的简化是可以由外部工具来完成。
2. 二进制文件中不会包含和某个系统或架构绑定的内容，部署上的优化是计划放在 [deploy](https://github.com/gofrp/deploy) 这个 repo 中来进行，但是目前没有志愿者负责。
