### ISSUE TITLE
frp 的网站没有自动获取logo  favicon.ico

### ISSUE THREAD

**Issue by androiddisk** [fatedier/frp#1746]
我内网搭建的网站 根目录有 favicon.ico 文件
正常访问是会有网站logo的

但是通过frp访问的网站 没有添加logo 请问怎么办

**Comment by AntiverX** [comment]
在浏览器的开发者工具里的network看下favicon.ico的加载情况，最好截个图

![image](https://user-images.githubusercontent.com/22369960/79040507-8ffe7280-7c1b-11ea-9bea-86746811f40d.png)

**Comment by androiddisk** [comment]
> 在浏览器的开发者工具里的网络看下favicon.ico的加载情况，最好截个图
> 
> ![图片](https://user-images.githubusercontent.com/22369960/79040507-8ffe7280-7c1b-11ea-9bea-86746811f40d.png)

![1](https://user-images.githubusercontent.com/11062371/79040571-ff746200-7c1b-11ea-9bc8-93a0da408170.png)
![2](https://user-images.githubusercontent.com/11062371/79040573-00a58f00-7c1c-11ea-9bff-c728a720c620.png)
端口转发的
http://server.kooapk.com:81/
frp穿透的
http://demo.kooapk.com:81/

感谢解答

**Comment by fatedier** [comment]
请按照格式提交 issue。

**Comment by androiddisk** [comment]
> 请按照格式提交 issue。

格式在哪里
