### ISSUE TITLE
frp 的网站没有自动获取logo favicon.ico

### ISSUE THREAD

**Issue by androiddisk** [fatedier/frp#1749]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.32.1

**What operating system and processor architecture are you using (`go env`)?**
centos8.1

**Configures you used:**

**Steps to reproduce the issue:**
访问frp穿透的网站
http://demo.kooapk.com:81/

**Describe the results you received:**
没有自动加载网站logo

**Describe the results you expected:**
希望和普通网站一样能自动加载logo

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by shenlijun** [comment]
我的可以，直接开80，443端口，不是http那种

**Comment by BecodReyes** [comment]
请手动修改模板
https://github.com/fatedier/frp/blob/master/utils/vhost/resource.go#L31
