### ISSUE TITLE
域名不存在时返回404状态码

### ISSUE THREAD

**Issue by fengqi** [fatedier/frp#175]
测试环境: frpc->frps->nginx
自定义域名模式下, 如监听 *.example.com 如果二级域 abc 没有配置的时候, 访问是会返回502, 
其实这个域名还没有配置

**Comment by fatedier** [comment]
域名没有配置时，当前的状态是会直接断开连接，后续可以优化。

**Comment by fatedier** [comment]
v0.12 发布后将会支持。

**Comment by fengqi** [comment]
赞
