### ISSUE TITLE
frp转发http, frp控制面板上http线路已经在线了，但是还是进不去网站

### ISSUE THREAD

**Issue by bruceluo111** [fatedier/frp#1751]
接上次的公网访问本地博客，我已经研究明白了，然后给国外VPS绑了个域名www.brucelog.club. 
然后更改了frps_full.ini, 开启了vhost_http_port=8080，然后，运行frps, 再修改frpc_full.ini, 修改【web01】,以下内容取消注释符号，更改为以下内容：
type =http
local_ip=127.0.0.1
local_port=8080  (本地博客端口8080)
custom_domains= www.brucelog.club
然后运行frpc, 看了vps ip:7500, http开通一条线路，并且是online状态。
然后浏览器输入www.brucelog.club, 确实进到了我的树莓派安装wordpress博客和phpmyadmin数据库管理工具的目录，然后我点击phpmyadmin，可以进入登录页面，但是我点wordpress，却一直进不了博客页面，是我设置错了，还是树莓派3B+性能有限？

**Comment by BCCC0** [comment]
wordpress不支持多域名访问，你应该在wordpress数据库把原有域名修改成新域名

**Comment by bruceluo111** [comment]
> 
> 
> wordpress不支持多域名访问，你应该在wordpress数据库把原有域名修改成新域名

能说下是修改哪个文件吗？还是直接在http://本地IP:8080/wordpress/wp-admin/仪表盘里的用户，把站点地址改成我VPS绑定的域名？指定地址不是本来就是IP加端口吗也没有域名啊？
本人小白，只是入坑了树莓派才研究了下Linux, 望解答，谢谢！

**Comment by BCCC0** [comment]
wp把http请求改到了vps的8080端口。8080是你博客运行端口，跳转是强制的，是根据你在wp后台定义的域名跳转的，因此无法访问wp。
你可以尝试把内网的8080端口映射到vps的8080端口。

**Comment by bruceluo111** [comment]
> 
> 
> wp把http请求改到了vps的8080端口。8080是你博客运行端口，跳转是强制的，是根据你在wp后台定义的域名跳转的，因此无法访问wp。
> 你可以尝试把内网的8080端口映射到vps的8080端口。访问vps的8080端口应该可以看到主页面，但是所有链接都是失效的。然后搜索一下”wordpress更改域名“，照着做就可以了

我有点蒙，我现在用frp做的不就是端口映射吗？
VPS服务端frps_full.ini里的vhost_http_port就是8080，然后树莓派客户端frpc_full.ini，【web01】local_port也设置成8080，这个不就是映射到8080端口了吗？
麻烦大神说下怎么映射8080端口，我这个不算是映射到了吗？

**Comment by BCCC0** [comment]
可以尝试把wp站点改为 http://www.brucelog.club/wordpress
改域名有风险，如果失败需要把域名改回 http://本地IP:8080/wordpress （我猜你现在应该是这个）

**Comment by bruceluo111** [comment]
> 
> 
> 可以尝试把wp站点改为 http://www.brucelog.club/wordpress
> 改域名有风险，如果失败需要把域名改回 [http://本地IP:8080/wordpress](http://%E6%9C%AC%E5%9C%B0IP:8080/wordpress) （我猜你现在应该是这个）

感谢大神！改了本地域名后确实可以公网访问，但是只成功了两次，而且都是用手机流量登的，如果用电脑登www.brucelog.club/wordpress, 就会显示：

连接被重置
载入页面时与服务器的连接被重置。
  此站点暂时无法使用或者太过忙碌。请过几分钟后再试。
  如果您无法载入任何网页，请检查您计算机的网络连接状态。
  如果您的计算机或网络受到防火墙或者代理服务器的保护，请确认 Firefox 已被授权访问网络。

是不是因为树莓派性能不行或者网络不稳定？
还有我怎么把www.brucelog.club后面的/wordpress去掉，直接输www.brucelog.club就可以访问我的博客？
是不是还是在仪表盘里，把地址URL改成www.brucelog.club就行了？ frps_full.in和frpc_full.ini不需要做什么更改吗？
感谢回答！

**Comment by BCCC0** [comment]
连接被重置有可能是墙的行为，也可能是浏览器缓存导致跳转到www.brucelog.club:8080/wordpress/，我这里宽带是可以连上的。检查访问的地址是否在8080端口，并清除浏览器缓存。

站点访问太慢有很多原因1.图片太多，2.路径太长，一次请求需要多次横跨太平洋。建议使用图床，并把站点搬到vps上。

把/wordpress去掉需要先修改仪表盘里的站点名称，再修改apache2的根目录。

**再多说一句国内的域名不能绑定国外的vps，想要用国内的域名建站必须用国内的主机并且备案**

**Comment by bruceluo111** [comment]
> 
> 
> 连接被重置有可能是墙的行为，也可能是浏览器缓存导致跳转到www.brucelog.club:8080/wordpress/，我这里宽带是可以连上的。检查访问的地址是否在8080端口，并清除浏览器缓存。
> 
> 站点访问太慢有很多原因1.图片太多，2.路径太长，一次请求需要多次横跨太平洋。建议使用图床，并把站点搬到vps上。
> 
> 把/wordpress去掉需要先修改仪表盘里的站点名称，再修改apache2的根目录。
> 
> **再多说一句国内的域名不能绑定国外的vps，想要用国内的域名建站必须用国内的主机并且备案**

非常感谢！
