### ISSUE TITLE
deepin-Linux  15.11无法使用frp 无法执行二进制文件: 可执行文件格式错误

### ISSUE THREAD

**Issue by qiaoliangXgamemode** [fatedier/frp#1752]
[我之前百度过，我换成amd64都不行我查看看我的框架去下载frp_0.32.1_linux_386也不行都显示无法执行二进制文件: 可执行文件格式错误，这是arm和amd框架的测试，我给个GIF给你这些，之前我爷测试过386的也不行. https://c-t.work/s/040f89b28bf741         zperva

**Comment by qiaoliangXgamemode** [comment]
牛奶快传 ：https://c-t.work/s/040f89b28bf741 
zperva

**Comment by fatedier** [comment]
可以自行下载源码编译。

**Comment by qiaoliangXgamemode** [comment]
好的谢谢
