### ISSUE TITLE
连接的客户端较多的情况下，在服务端如何快速查询某个客户端所使用的端口？

### ISSUE THREAD

**Issue by landswim** [fatedier/frp#1753]
默认客户端使用随机端口，管理端UI虽然很方便，但无法进行自动化，连接的客户端比较多的时候，每次都要登录管理端去查看，比较繁琐。
请问有什么办法能快速地查询某个客户端所使用的端口吗？比如API接口之类的。
谢谢

**Comment by xqzr** [comment]
CTRL+F

**Comment by fatedier** [comment]
Dashboard 本身就是通过 frps 的 API 接口查询代理信息，只是目前还不支持分页，数量太多的情况下性能不好，你可以自己调用这个 API 查询。只是这个 API 之前是为 Dashboard 设计的，也不是很规范，后续会提供更规范一些的 API。

**Comment by landswim** [comment]
> Dashboard 本身就是通过 frps 的 API 接口查询代理信息，只是目前还不支持分页，数量太多的情况下性能不好，你可以自己调用这个 API 查询。只是这个 API 之前是为 Dashboard 设计的，也不是很规范，后续会提供更规范一些的 API。

感谢您的回复，但我翻了下没找到相关API的文档，是否方便指个路？谢谢~

**Comment by fatedier** [comment]
目前没有文档，没有正式对外暴露。如果需要可以自行阅读源码，或根据 dashboard 调用的接口获取相关信息。

**Comment by landswim** [comment]
好的谢谢
