### ISSUE TITLE
The best way to reduce server network traffic ?

### ISSUE THREAD

**Issue by tineprogramming** [fatedier/frp#1755]
First I though p2p mode will establish connection between client to client and will not take any server resources but why data still transfer though the server ?

**Comment by qiaoliangXgamemode** [comment]
Try to optimize the server core, including Google ’s BBR to achieve better results. The system ’s TCP congestion control has a relatively large delay, and why the data is transmitted through the server. Is it an anti-proxy data or should it be transferred through the server To the client

**Comment by tineprogramming** [comment]
anti-proxy data ? What is it ? My server has BBR enable for a long time. I was thinking to use this as a solution for ip camera. If there is alot of camera will it take alot of bandwidth ? How is ip camera handle p2p traffic for people around the world ?

**Comment by qiaoliangXgamemode** [comment]
I'm wrong, I'm not very familiar with P2p, sorry

**Comment by fatedier** [comment]
xtcp only cost a few network traffic before connections have been established.

**Comment by tineprogramming** [comment]
> xtcp only cost a little network traffic before connections have been established.

xtcp usually not working but stcp works. stcp use bandwidth on the server too.

**Comment by tineprogramming** [comment]
![Screenshot (384)](https://user-images.githubusercontent.com/18547587/79421956-23ea8880-7fe6-11ea-8801-03cf421341b8.png)
Even in the admin page show the stat

**Comment by fatedier** [comment]
Read documents first.

**Comment by tineprogramming** [comment]
> Read documents first.

I read it here is how I did it. Frps run on vps. Frpc on the client 1 at the office forward the local port. Frpc on the client 2 at my house then bind the local port. Then I try to iperf the local port of client 2 that it bind. The bandwidth taken from the server as the traffic run though the server
