### ISSUE TITLE
[建议]服务端增加客户端验证，避免客户端被随便复制滥用

### ISSUE THREAD

**Issue by Cyclonekid** [fatedier/frp#1756]
1、内网主机通过Frp转发服务，最近发现Frp上的服务端端口越来越多，检查发现其他人员人为复制Frpc配置文件到其他计算机修改相关配置就可以直接使用
2、建议frpc启动时获取计算机cpuid作为认证ID，该ID可以配置在服务端配置文件内，使用token 和客户端ID双重认证
3、客户端增加   frpc -id   获取本机的id   这样防止frpc客户端被随便复制滥用。
如：
`

> [common]
> bind_addr = 0.0.0.0
>bind_port = 12345
>bind_udp_port = 7001
>token = XXXXXXXXXXX
>client1= 客户端ID1
>client2= 客户端ID2
>tls_only = true

`

**Comment by fatedier** [comment]
https://github.com/gofrp/fp-multiuser
