### ISSUE TITLE
fp-multiuser问题反馈

### ISSUE THREAD

**Issue by Cyclonekid** [fatedier/frp#1758]
**What version of frp are you using (./frpc -v or ./frps -v)?**
frps   0.32.1
frpc   0.32.1
windows平台测试
frps配置如下：
>[common]
>bind_addr = 0.0.0.0
>bind_port = 32252
>bind_udp_port = 7001 
>tcp_mux = true
>tls_only = true

>log_level = trace 
>[plugin.multiuser]
>addr = 127.0.0.1:7200
>path = /handler
>ops = Login

fp-multiuser的token如下：
>GT_Client1=111111
>GT_Client2=222222
>GT_Client3=333333

frpc1配置如下：
>[common]
>server_addr = 127.0.0.1
>server_port = 32252
>tls_enable = true
>login_fail_exit = false

>user = GT_Client1
>meta_token = 111111

>log_level = trace

>[Dashboard]
>type = stcp
>local_ip =  127.0.0.1
>local_port = 7500

frpc2配置如下：
>[common]
>server_addr = 127.0.0.1
>server_port = 32252
>tls_enable = true
>login_fail_exit = false 

>user = GT_Client1
>meta_token = 111111

>log_level = trace

>[Dashboard_visitor]
>type = stcp
>role = visitor
>server_name = Dashboard
>bind_addr = 127.0.0.1
>bind_port = 12808

>[Dashboard1]
>type = stcp
>local_ip =  127.0.0.1
>local_port = 7500

发现问题：
1、两个客户端配置成一样的user和token可以同时登陆，不能限制一个USER只能登陆一次。
2、上面的配置因为增加了user会将proxy转变成user.proxy，对于stcp安全穿透来说定义名称变化，无法连接。
![image](https://user-images.githubusercontent.com/17697818/79303886-9eea6b00-7f22-11ea-9c0c-110f841a3184.png)
frps可以显示同时登陆了两个同样user的客户端，不能规避客户端配置被复制后随便使用的问题。

![image](https://user-images.githubusercontent.com/17697818/79304289-8d559300-7f23-11ea-9bef-0d8909e87c07.png)

如果user不一致，登陆，会导致stcp的proxy转变成user.proxy，第二个frpc会连不上正确的proxy而无法穿透。

**Comment by fatedier** [comment]
1. 有特殊需求可以自行开发自定义插件，可以满足任意的鉴权需求。
2. 之前 issue 有说过，目前 stcp 仅限于同一用户访问，不支持跨用户。
