### ISSUE TITLE
frp服务启动失败，请检查服务端 “TCP多路复用(tcp_mux)”设置，确保与客户端完全一致！

### ISSUE THREAD

**Issue by gujiys** [fatedier/frp#1766]
![QQ截图20200419031523](https://user-images.githubusercontent.com/50275040/79669286-17844c80-81ed-11ea-91a5-d4b2a8213640.png)
![QQ截图20200419031509](https://user-images.githubusercontent.com/50275040/79669290-194e1000-81ed-11ea-9e71-4228c7b85059.png)
![QQ截图20200419031719](https://user-images.githubusercontent.com/50275040/79669292-1b17d380-81ed-11ea-948d-a3d424843a44.png)
![QQ截图20200419031731](https://user-images.githubusercontent.com/50275040/79669295-1ce19700-81ed-11ea-8eb2-04dbb8f37752.png)

**Comment by gujiys** [comment]
help

**Comment by gujiys** [comment]
![QQ截图20200419031452](https://user-images.githubusercontent.com/50275040/79669331-66ca7d00-81ed-11ea-94ca-dcc31dc38885.png)
漏了一张图

**Comment by bingtianbaihua** [comment]
先看下 issue 提问的规范，方便高效解决问题。

**Comment by fatedier** [comment]
如果使用了第三方的管理界面，请向第三方管理界面的提供者寻求帮助。

或者使用命令行的方式测试配置后，按照 issue 格式贴出相关内容，版本，日志等。
