### ISSUE TITLE
Request: option to not modify X-Forwarded-For header

### ISSUE THREAD

**Issue by delfer** [fatedier/frp#1767]
Hello!

@fatedier Thank you very much for this beautiful software!!!
I'm using a reverse proxy (https://github.com/containous/traefik) in the front of FRPS and header `X-Forwarded-For` is already set.
But FRPS always adds a new entry into the list at https://github.com/fatedier/frp/blob/master/utils/vhost/reverseproxy.go#L248
And I have this:

```
X-Forwarded-For: 3.95.2.106, 127.0.0.1
```

But my endpoint server (https://github.com/home-assistant/core) does not recognize the list in this header.

Please, add an option to leave `X-Forwarded-For` header as-is. Thank you!

**Comment by fatedier** [comment]
I'm confused why https://github.com/home-assistant/core can't support this format?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

```
X-Forwarded-For: <client>, <proxy1>, <proxy2>
```

ReverseProxy codes are copied from go standard library. I prefer not to modify it.

Maybe you can create an issue of https://github.com/home-assistant/core to solve this problem.

**Comment by CzBiX** [comment]
https://github.com/home-assistant/core/issues/29868
