### ISSUE TITLE
P2P-xtcp-Error：get sid from client error

### ISSUE THREAD

**Issue by FannyTony** [fatedier/frp#1769]
frpc xtcp Error：get sid from client error
frpc xtcp 报错：get sid from client error
Different ports report errors
不同的端口报告错误
Note：Send and receive （frpc）Prompt the same error
注：发送端和接收端都提示相同的错误

Server（frps）No error message
服务端（frps）无错误信息

环境：内网frps服务器可正常访问，切换至腾讯云报错
服务器：腾讯云
被访问端：内网NAS
访问端：内网/外网Win7/10-x64/

2020/04/19 13:34:18 [I] [service.go:282] [dae5b41c905f6fe7] login to server success, get run id [dae5b41c905f6fe7], server udp port [9809]
2020/04/19 13:34:18 [I] [visitor_manager.go:86] [dae5b41c905f6fe7] start visitor success
2020/04/19 13:34:18 [I] [visitor_manager.go:86] [dae5b41c905f6fe7] start visitor success
2020/04/19 13:34:18 [I] [visitor_manager.go:86] [dae5b41c905f6fe7] start visitor success
2020/04/19 13:34:18 [I] [visitor_manager.go:130] [dae5b41c905f6fe7] visitor added: [P2P_NAS_5000_Visitor P2P_NAS_5001_Visitor P2P_Drive_Visitor]
2020/04/19 13:34:32 [W] [visitor.go:281] [dae5b41c905f6fe7] [P2P_NAS_5001_Visitor] get sid from client error: read udp *.*.*.*:58454->*.*.*.*:46493: i/o timeout

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/README_zh.md#%E7%82%B9%E5%AF%B9%E7%82%B9%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F

目前处于开发的初级阶段，并不能穿透所有类型的 NAT 设备，所以穿透成功率较低。穿透失败时可以尝试 stcp 的方式。

**Comment by zhuwei** [comment]
@fatedier 这个功能以后还会完善吗？
