### ISSUE TITLE
connection  problem

### ISSUE THREAD

**Issue by orangeshu** [fatedier/frp#177]
2016/12/14 15:22:16 [main.go:109] [I] Start frpc success
2016/12/14 15:22:16 [control.go:135] [E] ProxyName [web01], connect to server [xx.xx.xx.xx:7000] error, dial tcp xx.xx.xx.xx:7000: getsockopt: connection refused
2016/12/14 15:22:16 [control.go:39] [E] ProxyName [web01], connect to server failed!
2016/12/14 15:22:16 [control.go:135] [E] ProxyName [web02], connect to server [xx.xx.xx.xx:7000] error, dial tcp 115.28.150.131:7000: getsockopt: connection refused
2016/12/14 15:22:16 [control.go:39] [E] ProxyName [web02], connect to server failed!
2016/12/14 15:22:16 [control.go:135] [E] ProxyName [ssh], connect to server [xx.xx.xx.xx:7000] error, dial tcp 115.28.150.131:7000: getsockopt: connection refused
2016/12/14 15:22:16 [control.go:39] [E] ProxyName [ssh], connect to server failed!
2016/12/14 15:22:16 [control.go:135] [E] ProxyName [privilege_web], connect to server [xx.xx.xx.xx:7000] error, dial tcp xx.xx.xx.xx:7000: getsockopt: connection refused
2016/12/14 15:22:16 [control.go:39] [E] ProxyName [privilege_web], connect to server failed!
2016/12/14 15:22:16 [main.go:112] [W] All proxy exit!
这个也是客服端和服务器端的连接超过15分钟的原因吗？

**Comment by fatedier** [comment]
不是，连接被拒绝了，可能是防火墙等其他因素导致的。
