### ISSUE TITLE
在一台具有两个IP的服务器如何搭建FRP并且设置为副IP防止

### ISSUE THREAD

**Issue by qiaoliangXgamemode** [fatedier/frp#1772]
其实我主要是想FRP加入个自定义服务器IP的功能我服务器上面有两个IP，可是FRP默认127.0.0.1不支持设置为另一个私有网络

**Comment by QQ2017** [comment]
[common]
bind_addr = 0.0.0.0
bind_port = 7000

上面的FRP服务端配置文件中，0.0.0.0 改为你想要绑定的服务端IP就行了。

**Comment by qiaoliangXgamemode** [comment]
这是frps的配置吗?
