### ISSUE TITLE
【建议】客户端 增加 计算机名 访问

### ISSUE THREAD

**Issue by Nieg** [fatedier/frp#1774]
内网不一定会有固定IP。我们经常都是通过计算机名访问。。。

例如从：
`[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000
`
变为：
`[ssh]
type = tcp
#local_ip = 127.0.0.1
local_addr= PC-XXXXXX
local_port = 22
remote_port = 6000
`
虽然可以在本地再弄个nigix 转发解决问题，但感觉功能改动不大，效果良好。

**Comment by glzjin** [comment]
其实是支持的，目前我这里的用法都是用主机名进行通讯。

**Comment by Nieg** [comment]
请问是先把 主机名转成 IP 后再 转发吗？
能加个选项，转发时，“是否把主机名转换为IP” 吗？ 

微信开发的时候，需要连接外网，而且是80端口。因为win10非管理员用户，用vs调试，设置 IIS express 允许0.0.0.0:port 端口访问太麻烦了。(要设置防火墙，用管理员模式打开VS，还要设置一个系统设置)我本身在用内网穿透，我有点希望可以一步到位。

我现在的解决方案是 先在外网 用frp把 80转进来 127.0.0.1:3179 然后用ngnix 监听3179端口，再转一次到 localhost:3178 。
如果直接用frp转到 3178端口 会报：
Bad Request - Invalid Hostname
HTTP Error 400. The request hostname is invalid.
我还没看代码，就猜测是直接转成 IP访问了。。。

**Comment by fatedier** [comment]
@Nieg https://github.com/fatedier/frp/blob/master/README_zh.md#%E4%BF%AE%E6%94%B9-host-header
