### ISSUE TITLE
【讨论】自动封禁恶意爆破ssh的方案

### ISSUE THREAD

**Issue by rozbo** [fatedier/frp#1777]
在常规模式下，我们的ssh可以封禁在N秒内失败M次的IP，以保证服务的安全。但这一切在使用frp内网穿透ssh的情况下变得复杂。因为frp穿透后的ip在ssh服务中看来，来源均为`127.0.0.1`。    
因此，有没有一种方案，能够实现类似自动封禁的功能？
ps，已尝试`proxy_protocol_version v2`，直接会导致
```
Bad packet length 1349676916.
```
猜测前置代理头ssh service 无法识别。

**Comment by fatedier** [comment]
在 #1264 中跟踪此问题。
