### ISSUE TITLE
xtcp问题

### ISSUE THREAD

**Issue by TomLiu-GitHub** [fatedier/frp#1778]
xtcp现在可用性已经很好了
我提两个问题
1. user参数后无法连接其他user的，比如去掉user参数，因为指定的server_name会被带上user。
2. 家里的路由和公司的路由都能穿透了，但是不能穿透移动热点，每次在外出差没外网用移动热点就无法穿透。

> 非常感谢frp作者，给我工作生活带来了很多便利。

**Comment by TomLiu-GitHub** [comment]
2020/04/26 14:20:06 [W] [visitor.go:281] [1e2671f079a1ca5d] [p2p_ssh_toMyBook] get sid from client error: read udp 192.168.1.112:54722->113.118.116.5:22769: i/o timeout
2020/04/26 14:29:25 [W] [visitor.go:281] [1e2671f079a1ca5d] [p2p_ssh_toMyBook] get sid from client error: read udp 192.168.1.112:63865->113.118.116.5:23663: i/o timeout
2020/04/26 14:29:33 [W] [visitor.go:281] [1e2671f079a1ca5d] [p2p_ssh_toMyBook] get sid from client error: read udp 192.168.1.112:57179->113.118.116.5:23676: i/o timeout
2020/04/26 17:02:15 [W] [visitor.go:281] [1e2671f079a1ca5d] [p2p_ssh_toMyBook] get sid from client error: read udp 192.168.1.112:62000->113.118.116.5:23118: i/o timeout
2020/04/26 17:02:25 [E] [visitor.go:251] [1e2671f079a1ca5d] [p2p_ssh_toMyPc] natHoleRespMsg get error info: xtcp server for [TomLiuPC.p2p_Mstsc] doesn't exist
2020/04/26 17:02:27 [W] [visitor.go:281] [1e2671f079a1ca5d] [p2p_ssh_toMyBook] get sid from client error: read udp 192.168.1.112:57186->113.118.116.5:23133: i/o timeout

**Comment by TomLiu-GitHub** [comment]
昨天一天一直成功
今天一天各种环境一次都不成功

**Comment by fatedier** [comment]
1. 目前的设计是这样，只能连接同一个用户的服务，如果确实有较多这方面的需求，可以考虑开放这个限制。
2. xtcp 成功率较低和网络环境相关，目前没有太多精力去优化这块。

**Comment by TomLiu-GitHub** [comment]
我觉得xtcp是趋势,点对点传输带宽最优.

**Comment by TomLiu-GitHub** [comment]
昨天下午一直连接不成功,今天突然就连接成功了.
连接成功后,带宽利用率高.远程办公体验非常好.

**Comment by fatedier** [comment]
支持跨用户访问 @yuyulei

**Comment by TomLiu-GitHub** [comment]
xtcp很难成功,偶尔成功一次连接上,但是一段断开,然后就要看运气了.

**Comment by lurry71** [comment]
> xtcp现在可用性已经很好了
> 我提两个问题
> 
> 1. user参数后无法连接其他user的，比如去掉user参数，因为指定的server_name会被带上user。
> 2. 家里的路由和公司的路由都能穿透了，但是不能穿透移动热点，每次在外出差没外网用移动热点就无法穿透。
> 
> > 非常感谢frp作者，给我工作生活带来了很多便利。

我在家就一直不能穿透，我家用的是宽带通，华为拨号器。你的配置是什么样的？

**Comment by aoinokodou** [comment]
我现在也遇到了和你一样的问题，我服务器端frps搭建在阿里云服务器端，frpc服务端在家里，visitor在公司放着，xtcp从来就没有失败过...然后最近要给朋友搞，怎么设置都是超时的...我拿家里另一台设备做frpc visitor也是超时的，连的都是同一个frpc服务端，但是放公司这台从来没有失败过，太迷了，我现在觉得可能还是路由器的问题

**Comment by TomLiu-GitHub** [comment]
我改用ZeroTier了

**Comment by lurry71** [comment]
> 我改用ZeroTier了

广告？？？

**Comment by TomLiu-GitHub** [comment]
> > 我改用ZeroTier了
> 
> 广告？？？
工具而已.
我用windows,是不是说给微软打广告?

感谢frp,非常好用!同时我也是go语言爱好者.

**Comment by TomLiu-GitHub** [comment]
> 我现在也遇到了和你一样的问题，我服务器端frps搭建在阿里云服务器端，frpc服务端在家里，visitor在公司放着，xtcp从来就没有失败过...然后最近要给朋友搞，怎么设置都是超时的...我拿家里另一台设备做frpc visitor也是超时的，连的都是同一个frpc服务端，但是放公司这台从来没有失败过，太迷了，我现在觉得可能还是路由器的问题

你和我一样,服务器端frps搭建在阿里云,公司和家里都是电信,公司路由h3c家里华为,这几个月基本上都在家,用远程桌面连接成功的时候一直连着,断开后怎么都连接不上,貌似和公司多wlan有关,看日志貌似是因为没有及时更新ip

**Comment by Alex-Beng** [comment]
我也遇到这个问题了，改了下frpc服务端的frpc.service 的User=nobody为User=root就解决了。。。还挺玄学的。
