### ISSUE TITLE
推荐一下自己开发的 Android 客户端

### ISSUE THREAD

**Issue by JKXY** [fatedier/frp#1779]
- 实现frp客户端功能，可基于模板配置（by v0.31.1）
- 注：还包含实现本地web服务功能
- 下载地址：1. [https://play.google.com/store/apps/details?id=com.jkxy.jsend](https://play.google.com/store/apps/details?id=com.jkxy.jsend)
2.[https://jkxy.lanzous.com/ibyfwre](https://jkxy.lanzous.com/ibyfwre)

**Comment by fatedier** [comment]
非开源项目，考虑到安全风险，不推荐在这里宣传。
