### ISSUE TITLE
frp在特权模式下ssh支持IP地址转发？

### ISSUE THREAD

**Issue by idoall** [fatedier/frp#178]
就是转发到别的机器上的ssh 22端口上，而不是frpc的22端口

**Comment by fatedier** [comment]
通过 `local_ip` 设置，参考 #146

**Comment by idoall** [comment]
谢谢，已经解决了，是使用local_ip
有个建议，内网的时候可能做了映射 到其他机器 ，如果机器名是xxx.xxx.com的话，就解析不了，估计是羞了是否包含"."，建议后面版本可以同时增加一个域名的转发就好了

**Comment by fatedier** [comment]
local_ip 配置成域名也是可以的。
