### ISSUE TITLE
RUN FRP in Background

### ISSUE THREAD

**Issue by gvsurenderreddy** [fatedier/frp#1783]
Hello sir 
Thank you for the software how can i run always on background 
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
https://www.google.com/search?newwindow=1&sxsrf=ALeKk01-kS8GNsRvU_UdsCgL2DJaXMlSnw%3A1588151078459&ei=JkOpXrq9G6bP0PEP0PizuAU&q=how+to+run+a+golang+problem+in+background&oq=how+to+run+a+golang+problem+in+background&gs_lcp=CgZwc3ktYWIQAzIHCCEQChCgAToFCCEQoAFQN1i_CmCuDGgAcAB4AIABygKIAbAHkgEFMi0xLjKYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwi66IXno43pAhWmJzQIHVD8DFcQ4dUDCAw&uact=5
