### ISSUE TITLE
什么时候打算支持按照url路径来做代理？也就是类似根据nginx的location配置

### ISSUE THREAD

**Issue by xuebing1110** [fatedier/frp#179]
目前是根据custom_domains来做反向代理，能否考虑根据请求url来做映射并代理到frpc上？

**Comment by xuebing1110** [comment]
1.registryMap更换成独立的router，根据域名+配置的location来映射Listen对象；
2.另外，是否考虑把ProxyServer的配置和ServerMetric的字段合并一下，把公共字段合并到config包中
在dev的基础上写完了，并且测试也跑通了

**Comment by fatedier** [comment]
@xuebing1110 
1. 0.9.0 版本暂时不加上这个功能，应该会在下一次小更新的时候加上，我会找时间 review 下代码。
2. 建议最好兼容 nginx 的 url 路由格式，这个可以之后再做。
3. 由于不断的加功能，代码结构上已经有些混乱，新版本发布之后会进行一次重构。

**Comment by xuebing1110** [comment]
@fatedier 
OK，期待下一个小版本
兼容nginx的url可以在router.go里实现，后面如果路由复杂可以考虑router作为单独的package

**Comment by wanminxg** [comment]
同期待这个功能。希望可以尽快加上。

**Comment by xuebing1110** [comment]
@wanminxg 
想尝鲜的可以用一下我的版本：http://download.bingbaba.com/frp_0.9.0_linux_amd64.tar.gz

**Comment by wanminxg** [comment]
@xuebing1110 
server和client的配置可以发一下吗？为啥我没跑起来..

**Comment by fatedier** [comment]
0.9.1 版本已支持。
