### ISSUE TITLE
frp的xtcp和stcp都无法连接的问题

### ISSUE THREAD

**Issue by IT-moke** [fatedier/frp#1790]
今天试着使用xtcp链接另个一电脑 但是结果很糟糕 一直链接超时，然后又使用stcp还是不行，请大牛指定：
配置如下：
客户端A：
[stcp]
type = stcp
sk = moke
local_ip = 127.0.0.1
local_port = 6000
use_encryption = false
use_compression = false

[p2p_ssh]
type = xtcp
sk = p2p_ssh
local_ip = 127.0.0.1
local_port = 2222
use_encryption = false
use_compression = false
客户端b：
[stcp-visitor]
type = stcp
role = visitor
server_name = stcp
sk = moke
bind_addr = 127.0.0.1
bind_port = 6000
use_encryption = false
use_compression = false

[p2p_ssh_visitor]
type = xtcp
role = visitor
server_name = p2p_ssh
sk = p2p_ssh
bind_addr = 127.0.0.1
bind_port = 2222
use_encryption = false
use_compression = false
错误日志如下：

2020/05/02 18:27:44 [I] [control.go:179] [94eb791e68840705] [p2p_ssh] start proxy success
2020/05/02 18:27:44 [I] [control.go:179] [94eb791e68840705] [stcp] start proxy success
2020/05/02 18:28:15 [W] [proxy.go:379] [94eb791e68840705] [p2p_ssh] get sid from visitor error: read udp 192.168.0.105:53669: i/o timeout
2020/05/02 18:28:32 [E] [proxy.go:766] [94eb791e68840705] [stcp] connect to local service [127.0.0.1:6000] error: dial tcp 127.0.0.1:6000: connectex: No connection could be made because the target machine actively refused it.

**Comment by xhiscl** [comment]
使用的版本是最新版0.33，http和https都可以正常使用

**Comment by ActonMartin** [comment]
我的连鉴权都不行，你的鉴权连接上服务器了吗？

**Comment by IT-moke** [comment]
你客户端日志是什么？

**Comment by ActonMartin** [comment]
> 你客户端日志是什么？
2020/05/05 08:24:09 [E] [service.go:273] authorization failed
2020/05/05 08:24:09 [W] [service.go:101] login to server failed: authorization failed
authorization failed
日志是上面的，使用的XTCP方式。
[common]
server_addr = cn-zj-dx.sakurafrp.com
server_port = 7000
token = 自己的密钥
user = 用户ID

[RDP_KK90]
type = xtcp 
local_ip = 127.0.0.1
local_port = 3389
sk = 新建隧道时填写的密码

这个端都没能鉴权成功。另外一个客户端也是一样的情况。
