### ISSUE TITLE
感觉配置文件的语法缺少必要的解释

### ISSUE THREAD

**Issue by eyeloveu** [fatedier/frp#1792]
[common]
[xxxx] 这些括号里的名字是有要求么还是随便写？必须要有还是只是个注释？看例子写的有的写的很随意，有的又写的和用途非常直接的对应。新手搜了一遍还没找到答案，表示很疑惑，希望作者可以详细说明一下，thanks

**Comment by Arvintian** [comment]
common是server和client的基本配置，这个section是必须的，其他的section名字大部分可以随便取，除了特殊语法比如"range:"，client主要区分字段是type。

**Comment by eyeloveu** [comment]
@Arvintian Thanks~
