### ISSUE TITLE
FRPC stops working after sometime

### ISSUE THREAD

**Issue by gvsurenderreddy** [fatedier/frp#1793]
Hello sir 
FRPC stops working after sometime time and I need to start the session again .Is there anyway it gets connected automatic when FRPC gets disconnected please 
thanks for the software 
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
Please follow the issue template and provide more info.

**Comment by byzhao** [comment]
login_fail_exit = false

Read the manual

**Comment by gvsurenderreddy** [comment]
Thanks sir I"ll add to FRPC.ini thanks sir
