### ISSUE TITLE
关于被代理服务方便打开的问题

### ISSUE THREAD

**Issue by alex1528** [fatedier/frp#1796]
已启用了dashborad,如何界面上方便快捷地打开被代理的服务?
比方说, 被代理服务到frps端后是随机的一个端口:8280
有没有方案或启用哪个配置项,以超链接的形式, 点击超链接,可以快速通过浏览器访问此端口对应的服务呢?

**Comment by BecodReyes** [comment]
可通过修改源码中dashborad的样式文件实现
