### ISSUE TITLE
server adder error

### ISSUE THREAD

**Issue by maplewizard** [fatedier/frp#18]
I set server adderess in frpc.ini, and run frpc -c frpc.ini
the log show:
2016/04/07 09:00:48 [main.go:101] [I] Start frpc success
2016/04/07 09:00:48 [control.go:130] [E] ProxyName [ssh], connect to server [0.0.0.0:7000] error, dial tcp 0.0.0.0:7000: connection refused
2016/04/07 09:00:48 [control.go:39] [E] ProxyName [ssh], connect to server failed!
2016/04/07 09:00:48 [main.go:104] [W] All proxy exit!

It seems it also use 0.0.0.0 as server. Please help me to tackle this problem. Thanks

**Comment by fatedier** [comment]
Can you show me your [common] section in frpc.ini?

**Comment by maplewizard** [comment]
# [common] is integral section
[common]
SERVER_ADDR = my.server.ip.adder
server_port = 7000
# console or real logFile path like ./frpc.log
log_file = ./frpc.log
# debug, info, warn, error
log_level = debug
# for authentication
auth_token = mypassword

# test1 is the proxy name same as server's configuration
[ssh]
local_ip = 127.0.0.1
local_port = 22
# true or false, if true, messages between frps and frpc will be encrypted, default is false
use_encryption = true

**Comment by fatedier** [comment]
server_addr is case-sensitive, you can try to use lower-case letters.

**Comment by fatedier** [comment]
I will let it be compatible with uppercase letters soon.
