### ISSUE TITLE
panic: unreachable

### ISSUE THREAD

**Issue by qiaoliangXgamemode** [fatedier/frp#1800]
error:
panic: unreachable

goroutine 19 [running]:
github.com/klauspost/reedsolomon.reedSolomon.codeSomeShardsAvx512(...)
        /home/wcl/go_projects/pkg/mod/github.com/klauspost/reedsolomon@v1.9.1/galois_noasm.go:33
github.com/klauspost/reedsolomon.reedSolomon.codeSomeShards(0xa, 0x3, 0xd, 0x9134780, 0xd, 0xd, 0x9116d00, 0x911d080, 0xa, 0xa, ...)
        /home/wcl/go_projects/pkg/mod/github.com/klauspost/reedsolomon@v1.9.1/reedsolomon.go:441 +0x3cb
github.com/klauspost/reedsolomon.reedSolomon.Encode(0xa, 0x3, 0xd, 0x9134780, 0xd, 0xd, 0x9116d00, 0x911d080, 0xa, 0xa, ...)
        /home/wcl/go_projects/pkg/mod/github.com/klauspost/reedsolomon@v1.9.1/reedsolomon.go:313 +0x133
github.com/fatedier/kcp-go.(*fecEncoder).encode(0x9126af0, 0x935c580, 0x59, 0x546, 0x901b0e0, 0x809e97e, 0xe01d03b)
        /home/wcl/go_projects/pkg/mod/github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/fec.go:281 +0x2d8
github.com/fatedier/kcp-go.(*UDPSession).output(0x9354000, 0x935c580, 0x59, 0x546)
        /home/wcl/go_projects/pkg/mod/github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/sess.go:515 +0x5bd
github.com/fatedier/kcp-go.newUDPSession.func1(0x935c580, 0x546, 0x546, 0x59)
        /home/wcl/go_projects/pkg/mod/github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/sess.go:169 +0x46
github.com/fatedier/kcp-go.(*KCP).flush.func2(...)
        /home/wcl/go_projects/pkg/mod/github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/kcp.go:685
github.com/fatedier/kcp-go.(*KCP).flush(0x912a300, 0x0, 0x8b3c2c0)
        /home/wcl/go_projects/pkg/mod/github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/kcp.go:842 +0xc27
github.com/fatedier/kcp-go.(*UDPSession).update(0x9354000, 0xbfa61939, 0xe16c8c5)
        /home/wcl/go_projects/pkg/mod/github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/sess.go:556 +0x52
github.com/fatedier/kcp-go.(*updateHeap).updateTask(0x8b3bf20)
        /home/wcl/go_projects/pkg/mod/github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/updater.go:91 +0xfd
created by github.com/fatedier/kcp-go.init.2
        /home/wcl/go_projects/pkg/mod/github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/updater.go:13 +0x5f

我使用的是最新版本的FRP我是不是要退到新版以下呢 ?

**Comment by bingtianbaihua** [comment]
看不出什么错误，希望提供更加详细的信息， 按照规范提问。

**Comment by qiaoliangXgamemode** [comment]
我已经卸载了frp目前无法提供日志,;w;
