### ISSUE TITLE
[Plugin idea] realtime notification and authoriztion

### ISSUE THREAD

**Issue by NoCLin** [fatedier/frp#1801]
I am going to develop a simple authentication system based on the server-side plugin. The main idea is to send an email (or other methods) to notify the developer in real time when an event is received, and developer can jump to the web interface to authorize the corresponding event.

So, I need the Login event to provide as much information as possible, such as the `frpc` address and port, and what is the meaning of privilege_key?

Also, there is a problem with the NewWorkConn event registration: 
https://github.com/fatedier/frp/blob/1ab23b5e0e73709451510cd96ddde6286bc875e7/models/plugin/server/manager.go#L54-L56

**Comment by bingtianbaihua** [comment]
> what is the meaning of privilege_key
The privilege_key just for auth.
you can see  frp/models/auth/ to get more information.

**Comment by bingtianbaihua** [comment]
https://github.com/fatedier/frp/blob/master/doc/server_plugin_zh.md
