### ISSUE TITLE
frpc 前置代理+Fiddler：为什么无法跟踪到http请求？

### ISSUE THREAD

**Issue by idragonet** [fatedier/frp#1802]
frpc能正常工作，Fiddler就是跟踪不到请求的HTTP

![image](https://user-images.githubusercontent.com/9882118/81499531-e20be400-92fe-11ea-8e40-20416394c1df.png)

**Comment by TomLiu-GitHub** [comment]
Fiddler很多协议跟踪不到的,比如socket协议就跟踪不到.
用Wireshark吧

**Comment by idragonet** [comment]
> Fiddler很多协议跟踪不到的,比如socket协议就跟踪不到.
> 用Wireshark吧

谢谢，Wireshark可以。
