### ISSUE TITLE
Potential bugs on old cores: using 64-bit functions sync/atomic

### ISSUE THREAD

**Issue by BurtonQin** [fatedier/frp#1804]
**What version of frp are you using (./frpc -v or ./frps -v)?**
master branch
commit: 2406ecdfea62567a576bdb71e38adbafa3b4814a

**What operating system and processor architecture are you using (`go env`)?**

--

**Configures you used:**

--

**Steps to reproduce the issue:**

--

**Describe the results you received:**
I noticed that there are usages of atomic.LoadInt64, atomic.AddInt64, etc.
These 64-bit functions in sync/atomic can cause errors on old cores. Please see: https://golang.org/pkg/sync/atomic/#pkg-note-BUG
I am not sure if some users are running frp on these old cores.

I reported this bug because I saw grpc-go developers viewed the usage of atomic64 functions as a bug and they easily fixed it in this [pull](https://github.com/grpc/grpc-go/pull/1411).
Maybe it is not a problem for frp if users rarely use [those old cores](https://golang.org/pkg/sync/atomic/#pkg-note-BUG) mentioned by golang. Feel free to close this issue if you want.

Usage Position: (There may be more)
https://github.com/fatedier/frp/blob/2406ecdfea62567a576bdb71e38adbafa3b4814a/utils/metric/counter.go#L39-L60

**Describe the results you expected:**

--

**Additional information you deem important (e.g. issue happens only occasionally):**

--

**Can you point out what caused this issue (optional)**

--

**Comment by fatedier** [comment]
Thanks for your report!

It's not essential to use atomic.AddInt64 in metrics package. We'd better use atomic32 instead.

@bingtianbaihua
