### ISSUE TITLE
请问，为什么我搭的frp总是过一段时间断开，然后又重新连上

### ISSUE THREAD

**Issue by Chinajuedui** [fatedier/frp#1813]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.33.0

**What operating system and processor architecture are you using (`go env`)?**
ubuntu16

**Configures you used:**
[common]
server_addr = 47.102.200.64
server_port = 7000

[ssh6001]
type = tcp
local_port = 22
local_add = 127.0.0.1
remote_port = 6001

[common]
bind_port = 7000
vhost_http_port = 5000
vhost_https_port = 5001
dashboard_port = 7500
dashboard_user = ***
dashboard_pwd = ***

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by Chinajuedui** [comment]
![image](https://user-images.githubusercontent.com/27952522/82283864-27e53e00-99ca-11ea-90dd-405173fcf380.png)
这是日志  ssh6001是以前的  现在的端口设置成了6000   但是ssh6001总是出黄色的那个错误，远程连的主机也不知道在哪关

**Comment by Chinajuedui** [comment]
![image](https://user-images.githubusercontent.com/27952522/82286851-4bf84d80-99d1-11ea-98b0-b705bd00c4cf.png)
把端口换成10000/12000了 就是这个输出日志

**Comment by bingtianbaihua** [comment]
frpc 的日志也提供下。

**Comment by Chinajuedui** [comment]
> frpc 的日志也提供下。

frpc没有用service启动，用得nohup ./frpc -c ./frpc.ini 怎么看日志呢

**Comment by bingtianbaihua** [comment]
> > frpc 的日志也提供下。
> 
> frpc没有用service启动，用得nohup ./frpc -c ./frpc.ini 怎么看日志呢

最简单的办法， 不用 nohup ，直接运行 frpc，看输出的什么日志。 
建议先熟悉下命令行，shell ，Linux 这些基本概念， 不然沟通效率比较低。

**Comment by Chinajuedui** [comment]
> > > frpc 的日志也提供下。
> > 
> > 
> > frpc没有用service启动，用得nohup ./frpc -c ./frpc.ini 怎么看日志呢
> 
> 最简单的办法， 不用 nohup ，直接运行 frpc，看输出的什么日志。
> 建议先熟悉下命令行，shell ，Linux 这些基本概念， 不然沟通效率比较低。

![image](https://user-images.githubusercontent.com/27952522/82313183-9c37d580-99fa-11ea-90f9-9145e7c72a00.png)
这是这次断开frpc的日志
![image](https://user-images.githubusercontent.com/27952522/82313282-b7a2e080-99fa-11ea-815e-ad88fc0d632a.png)
这是这次断开frps的日志

**Comment by bingtianbaihua** [comment]
错误很详细了， 换个端口试试。

**Comment by Chinajuedui** [comment]
> 错误很详细了， 换个端口试试。

换了个端口还是一样
![image](https://user-images.githubusercontent.com/27952522/82327912-b4ffb580-9a11-11ea-88ee-c6374c7aa743.png)
这个是frpc的日志
![image](https://user-images.githubusercontent.com/27952522/82327972-cea0fd00-9a11-11ea-809a-f9f0ee00b77a.png)
这个是frps的日志

**Comment by bingtianbaihua** [comment]
我当前比较怀疑是防火墙导致的， 因为 frpc 是登录了frps 的，可以检查下。 
如果发现不出来， 可以在 frpc 和 frps 两台机器分别 tcpdump/wireshark 抓包看下。

**Comment by Chinajuedui** [comment]
防火墙应该不会，因为之前用过还挺稳定的，就是实验室停了一次电，再用就出现这个问题了
![image](https://user-images.githubusercontent.com/27952522/82329514-014bf500-9a14-11ea-830b-8e13170fbf84.png)
这是正常的frps的连接状态
![image](https://user-images.githubusercontent.com/27952522/82329686-47a15400-9a14-11ea-87df-411b940ee53c.png)
断了之后就这样了

我在想是不是我之前设置的frpc开机自启动然后占用了啥的的问题，因为我在连接上的时候pkill -9 frpc的时候出现这个情况(下图)
![image](https://user-images.githubusercontent.com/27952522/82329879-92bb6700-9a14-11ea-8548-109e9bf15ec6.png)

**Comment by Chinajuedui** [comment]
> 我当前比较怀疑是防火墙导致的， 因为 frpc 是登录了frps 的，可以检查下。
> 如果发现不出来， 可以在 frpc 和 frps 两台机器分别 tcpdump/wireshark 抓包看下。

这台机器只有我一个人在用frpc，frpc只可能是我创建的

**Comment by Chinajuedui** [comment]
可能真是我校园网的问题  我在我本地搭建穿透完全没问题

**Comment by Chinajuedui** [comment]
> 我当前比较怀疑是防火墙导致的， 因为 frpc 是登录了frps 的，可以检查下。
> 如果发现不出来， 可以在 frpc 和 frps 两台机器分别 tcpdump/wireshark 抓包看下。

感谢回复

**Comment by bingtianbaihua** [comment]
建议还是在两边抓个包分析下， 看看是两端的问题，还是中间链路出了问题。

**Comment by Chinajuedui** [comment]
> 建议还是在两边抓个包分析下， 看看是两端的问题，还是中间链路出了问题。

真的很奇妙，学校的是电信网，然后我这边也换成了电信网就好了，我之前连的这边是移动的网，测速各种都没问题，也没丢包，网速也有10几M；大佬下次遇到这个提问不妨让换成同一个运营商的网试试

**Comment by Chinajuedui** [comment]
高兴得太早了。。。还是一样

**Comment by fatedier** [comment]
可以尝试更换 protocol 为 kcp，以及开启 TLS 看是否有效果。

**Comment by Chinajuedui** [comment]
> 可以尝试更换 protocol 为 kcp，以及开启 TLS 看是否有效果。

还是没用  可能是两会校园网的缘故
