### ISSUE TITLE
port unavailable

### ISSUE THREAD

**Issue by swhoro** [fatedier/frp#1814]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
服务器上的为frps 0.33.0
路由器openwrt上的为frpc 0.32.1

**What operating system and processor architecture are you using (`go env`)?**
路由器上的为openwrt aarch64
服务器上的为Ubuntu x86_64

**Configures you used:**
服务端：
![image](https://user-images.githubusercontent.com/34229589/82321252-20905580-9a07-11ea-96e4-805afb560523.png)

客户端：
![image](https://user-images.githubusercontent.com/34229589/82321235-1b330b00-9a07-11ea-89fa-a1b671bcca8c.png)
![image](https://user-images.githubusercontent.com/34229589/82323419-9b0ea480-9a0a-11ea-94e8-26295df5ab39.png)

**Steps to reproduce the issue:**
1.服务端frps start启动服务
2.客户端（路由器）在frpc界面中配置相关选项，打勾启动
3.日志中显示port unavailable

**Describe the results you received:**
只有udp的7777端口proxy打开，tcp未打开

**Describe the results you expected:**
打开7777端口的tcp和udp proxy

**Additional information you deem important (e.g. issue happens only occasionally):**
日志文件：
![image](https://user-images.githubusercontent.com/34229589/82321469-736a0d00-9a07-11ea-8f8b-9a4e4d8f6b97.png)

**Can you point out what caused this issue (optional)**

**Comment by bingtianbaihua** [comment]
如果你把 frpc 配置里的 protocol  = tcp  改为  kcp ，应该就 OK 了。 

建议仔细看文档，什么参数是两边需要一致的。 
https://github.com/fatedier/frp/blob/master/conf/frpc_full.ini
https://github.com/fatedier/frp/blob/master/conf/frps_full.ini

**Comment by swhoro** [comment]
> 如果你把 frpc 配置里的 protocol = tcp 改为 kcp ，应该就 OK 了。
> 
> 建议仔细看文档，什么参数是两边需要一致的。
> https://github.com/fatedier/frp/blob/master/conf/frpc_full.ini
> https://github.com/fatedier/frp/blob/master/conf/frps_full.ini

如果使用kcp的话会报错i/o deadline reached，issues里面好像没有解决方案
把frps中的kcp_bind_port去掉的话依然会有同样的错误

**Comment by swhoro** [comment]
对不起，麻烦close一下吧，找到原因了，服务器上已经有程序占用7777端口了

**Comment by bingtianbaihua** [comment]
嗯， 下次遇到这些问题， 多尝试一下， ps ，lsof，ss，netstat， nc，tcpdump 这些瑞士军刀都可以试试。
