### ISSUE TITLE
使用最新版0.33.0后无法连接 报错[service.go:101] login to server failed: EOFEOF

### ISSUE THREAD

**Issue by mtkj123** [fatedier/frp#1816]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.33.0

**What operating system and processor architecture are you using (`go env`)?**

服务端：WindowsServer2008
客户端：WIN10

**Configures you used:**

**Steps to reproduce the issue:**
1.
frps.ini
`[common]
bind_addr = 0.0.0.0
bind_port = 7000
bind_udp_port = 7001 
kcp_bind_port = 7000
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin
privilege_allow_ports = 1-65535
privilege_mode = true
auto_token= frp888
privilege_token = frp888
token= frp888
log_max_days = 7 
max_pool_count = 100 
log_level = info 
vhost_http_port = 80

# 设置域名（保证此域名可用）
subdomain_host = frp.vipsystem.top
`
frpc.ini
`[common]
server_addr = 111.67.204.102
server_port = 7000
log_level = info 
log_max_days = 7 
privilege_token = frp888
token= frp888

[rcpda]
privilege_mode = true
type = http
local_ip = 10.6.45.42
local_port = 10086
subdomain = rcpda

[aioonline]
privilege_mode = true
type = http
local_ip = 10.6.1.39
local_port = 8090
subdomain = aioonline

[xuexiguanjia]
privilege_mode = true
type = http
local_ip = 34.80.112.36
local_port = 80
subdomain = xuexiguanjia

[RDP]
privilege_mode = true
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 6001`
2.启动服务端
3.启动客户端
**如果服务端和客户端都在一个机器上则可以，不在一个机器上则无法连接，已经确保服务端防火墙全部关闭，依然无法连接**
**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by bingtianbaihua** [comment]
贴一下 详细日志。

**Comment by mtkj123** [comment]
很高心收到你的回信，
如下图错误日志和我贴的均是此提示




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tank"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 下午2:46
收件人:&nbsp;"fatedier/frp"<frp@noreply.github.com&gt;;
抄送:&nbsp;"寻缘天地"<503559568@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fatedier/frp] 使用最新版0.33.0后无法连接 报错[service.go:101] login to server failed: EOFEOF (#1816)





 
贴一下 详细日志。

**Comment by mtkj123** [comment]
下图是服务器端截图




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tank"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 下午2:46
收件人:&nbsp;"fatedier/frp"<frp@noreply.github.com&gt;;
抄送:&nbsp;"寻缘天地"<503559568@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fatedier/frp] 使用最新版0.33.0后无法连接 报错[service.go:101] login to server failed: EOFEOF (#1816)





 
贴一下 详细日志。

**Comment by bingtianbaihua** [comment]
所以图是丢了是吗 。。。。。。。

**Comment by mtkj123** [comment]
看不到图吗？




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tank"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 下午4:35
收件人:&nbsp;"fatedier/frp"<frp@noreply.github.com&gt;;
抄送:&nbsp;"寻缘天地"<503559568@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fatedier/frp] 使用最新版0.33.0后无法连接 报错[service.go:101] login to server failed: EOFEOF (#1816)





 
所以图是丢了是吗 。。。。。。。
