### ISSUE TITLE
使用同样的proxy名称连接会报错

### ISSUE THREAD

**Issue by yanjieee** [fatedier/frp#1817]
服务端和客户端程序都是：0.20
有没有一种办法，客户端的frpc.ini可以用同样的proxy_name，比如ssh，在服务端这里不冲突？

**Comment by bingtianbaihua** [comment]
当前是通过 proxyname 去索引具体的 proxy。 同一个 frpc 下面的 proxyname 需要保证唯一。 

可以说一下你的具体问题，想解决什么问题，有什么场景，是否是一个通用的需求。

**Comment by yanjieee** [comment]
我试了一下proxy_name用同样的，remote_port设置为0，让sever分配，会出现这样的错误提示：
> start error: proxy name [ssh] is already in use

**Comment by fatedier** [comment]
https://gofrp.org/docs/reference/client-configures/#%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE

`user = xxx`
