### ISSUE TITLE
Port Mapping 

### ISSUE THREAD

**Issue by gvsurenderreddy** [fatedier/frp#1819]
Hello sir 
How can i do Portmapping of Server on Client is this possible please 

Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by bingtianbaihua** [comment]
I don't know what is your problem. please follow the official document.

**Comment by gvsurenderreddy** [comment]
Sorry to ask much my question is can do port mapping of my Server to Local host ie 

SSH of Server access on my local host machine on other Port say 2222

**Comment by fatedier** [comment]
@gvsurenderreddy Run another frpc with your frps together.

**Comment by gvsurenderreddy** [comment]
Sir is it not possible only with FrpS and FRPC without other FRPC sir

**Comment by fatedier** [comment]
frp is not designed for this scenario, you can choose other tools.
