### ISSUE TITLE
通过frp转发内网博客，必须域名+端口8080才能访问

### ISSUE THREAD

**Issue by bruceluo111** [fatedier/frp#1824]
**What version of frp are you using (./frpc -v or ./frps -v)?**
客户端：0.29.1
服务端：0.29.1

**What operating system and processor architecture are you using (`go env`)?**
客户端：树莓派Raspbian armv71
服务端：搬瓦工Debian9 amd64

**Configures you used:**

frps_full.ini:
vhost_http_port=8080

frpc_full.ini:
[web01]
type=http
local ip=127.0.0.1
local port=8080
custom_domains=www.brucelog.club

终于知道输域名为啥不显示了，加了8080就好了，但是我之前也是这个配置，用的也是8080端口直接输域名就可以访问博客，为啥这次必须加，还是说之前浏览器可能因为某种原因自己默认为8080端口，但我之前用手机也不用加8080端口，不知道是什么原因。

还有域名检测显示：
http 80端口检测
网站访问异常，请联系您的网站管理员，HTTP状态码详情
HTTP状态码：503
备案检测
未备案（您的域名没有备案，可能会影响您的网站使用，如果您使用的是海外主机，可以忽略本提示）

是因为我把80端口改成8080端口，80端口无法访问才显示503错误的吗，我不想用80端口就不用管吧

如果我把vhost_htttp_port改回80, 就不用了加8080端口了吧？

**Comment by bruceluo111** [comment]
@BCCC0 就跟issue #1751 里的设置的一模一样，为什么之前域名不用加:8080?

**Comment by BCCC0** [comment]
要么都是8080，vhost_http_port=8080，域名是www.brucelog.club:8080/wordpress。要么都是80，vhost_http_port=80，域名是www.brucelog.club/wordpress。frpc中的local port和树莓派apache的监听端口一致。上次你说能够用www.brucelog.club访问phpmyadmin，说明http转发到了vps的80端口。

**Comment by bruceluo111** [comment]
> 要么都是8080，vhost_http_port=8080，域名是www.brucelog.club:8080/wordpress。要么都是80，vhost_http_port=80，域名是www.brucelog.club/wordpress。frpc中的local port和树莓派apache的监听端口一致。上次你说能够用www.brucelog.club访问phpmyadmin，说明http转发到了vps的80端口。

我把vhost_http_port改成80了现在输www.brucelog.club可以进到/var/www/html
点phpmyadmin可以正常登录, 点wordpress地址变成www.brucelog.club:8080/wordpress无法访问，现在只需要把站点URL改成www.brucelog.club/wordpress就可以了吗，还是www.brucelog.club:8080/wordpress?

去掉8080还需要把local port和apache listen port都改成80吗？

**Comment by BCCC0** [comment]
1. 在wp后台需要改成`www.brucelog.club/wordpress`，如不能访问需要直接修改数据库
2. apache listen port 不用改
如果之后不需要frp转发，wp后台域名改回`http://ip:8080/wordpress`即可在内网通过ip访问

**Comment by bruceluo111** [comment]
> 
> 
>     1. 在wp后台需要改成`www.brucelog.club/wordpress`，如不能访问需要直接修改数据库
> 
>     2. apache listen port 不用改
>        如果之后不需要frp转发，wp后台域名改回`http://ip:8080/wordpress`即可在内网通过ip访问

万分感谢！正常了，之前估计直接改的vhost_http_port=8080，没有重新启动frps, 所以端口还是默认的80
