### ISSUE TITLE
希望加一种方式，使相同配置的第二个frpc启动时能把第一个frpc顶掉。

### ISSUE THREAD

**Issue by leicheng6563** [fatedier/frp#1825]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.33.0

**What operating system and processor architecture are you using (`go env`)?**
centos7 
3.10.0-1062.4.3.el7.x86_64

**Configures you used:**
````
[common]
server_addr = xxx.xxx.com
server_port = 5817
token = xxxxxxx

[tomcat-dev2]
type = tcp
local_ip = core-dev2
local_port = 8080
remote_port = 5844
````

**Steps to reproduce the issue:**
1.启动第一个frpc 
2.以同样配置启动第二个frpc

**Describe the results you received:**
第一个正常运行，第二个报错

**Describe the results you expected:**
希望加一种方式，使相同配置的第二个frpc启动时能把第一个frpc顶掉。也就是说第二个启动成功，第一个报错(退出）。

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
不会支持这个能力，避免正常启动的服务被意外关闭。
