### ISSUE TITLE
windows下本项目自带的test,发现跑不通，也编译不通过呢

### ISSUE THREAD

**Issue by ruixiwu** [fatedier/frp#1831]
今天试着跑了一下自带的test，  没跑通, 编译都不通过
windows10
goland IDE
![image](https://user-images.githubusercontent.com/9555002/83332451-df812680-a2cd-11ea-8d67-71546016bb15.png)
![image](https://user-images.githubusercontent.com/9555002/83332476-fd4e8b80-a2cd-11ea-879b-536bad9e1fe3.png)

说的很清楚： systemcall.Umask(0) 是unix下的， 在这里是windows，我应该怎么办？？

**Comment by fatedier** [comment]
注释掉不跑这个。

**Comment by ruixiwu** [comment]
ok, thanks
