### ISSUE TITLE
Stcp怎么获取客户端地址

### ISSUE THREAD

**Issue by wangwanzhong** [fatedier/frp#1832]
我在局域网有一个web服务，为了只有内部人可以使用，我启用了stcp，这种情况可以获取到客户端真实 IP地址吗

**Comment by fatedier** [comment]
目前获取到的也是 frpc 所在机器的 IP（还有可能是外网 NAT 转换过的）。你这种场景如果真的需要严格的管理，还是在 web 服务上加上权限验证的机制比较合适。
