### ISSUE TITLE
咨询下关于frps的并发量和性能问题

### ISSUE THREAD

**Issue by ivanhxq** [fatedier/frp#1838]
关注frps有段时间了，想用frps做个流量转发，用户连接大于5000以上，不知道frps是否扛得住？谁有类似的案例或者测试数据，可以交流下。

**Comment by kratos9394** [comment]
一百个客户端连总部数据库，白天开单大的时候，相关端口代理必死，其它流量小的端口没事，只能反复重启客户端，服务端。自己用的动态域名一直连接着没事，负载均衡也用过了，该关的也关了。用在生产环境要三思

**Comment by bugmeng** [comment]
> 一百个客户端连总部数据库，白天开单大的时候，相关端口代理必死，其它流量小的端口没事，只能反复重启客户端，服务端。自己用的动态域名一直连接着没事，负载均衡也用过了，该关的也关了。用在生产环境要三思

有日志么？
