### ISSUE TITLE
http_proxy插件鉴权失败

### ISSUE THREAD

**Issue by jl0x61** [fatedier/frp#1848]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.31.1

**What operating system and processor architecture are you using (`go env`)?**
ubuntu 18.04.3 LTS amd64

**Configures you used:**
`frpc.ini`:
[common]
server_addr = x.x.x.x
server_port = 7000

[http_proxy]
type = tcp
remote_port = 7999
plugin = http_proxy
plugin_http_user = user
plugin_http_password = user
`frps.ini`:
[common]
 bind_port = 7000
**Steps to reproduce the issue:**
1. ./frps -c ./frpc.ini
2. ./frpc -c ./frpc.ini

**Describe the results you received:**
`curl --proxy http://x.x.x.x:7999 --proxy-user user:user -I www.baidu.com`
得到结果:
```
HTTP/1.1 407 Proxy Authentication Required
Proxy-Authenticate: Basic
Date: Tue, 09 Jun 2020 17:19:17 GMT
```
**Describe the results you expected:**
200 OK

**Additional information you deem important (e.g. issue happens only occasionally):**

当去掉配置文件中的 `plugin_http_user` 和 `plugin_http_password` 之后，可以返回200 OK。

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
https://gofrp.org/docs/features/common/client-plugin/#http_proxy

参考这里的配置，`plugin_http_passwd`
