### ISSUE TITLE
frp/utils/vhost/https.go下的描述改进

### ISSUE THREAD

**Issue by Zalberth** [fatedier/frp#1849]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.33.0

**What operating system and processor architecture are you using (`go env`)?**
amd64

**Steps to reproduce the issue:**
查看```frp/utils/vhost/https.go```中第180行的代码：```err = fmt.Errorf("Unknow error")```

**Describe the results you expected:**
需要改成```err = fmt.Errorf("Unknown error")```更好

**Comment by fatedier** [comment]
Can you submit a PR to improve it?

**Comment by Zalberth** [comment]
OK
