### ISSUE TITLE
frp可以支持服务注册 服务发现功能吗？

### ISSUE THREAD

**Issue by luoxue2017** [fatedier/frp#1853]
背景：
微服务过程中，很多服务都是动态启动的，服务启动的时候可以向frpc注册服务，服务之间相互调用时，可以向frpc获取其他服务的请求地址发起请求。

建议：
frpc提供2个api，服务注册，服务发现
服务注册：通过http 向frpc 注册单个服务
服务发现：可以通过http 向frpc 获取所有frps中注册的服务和请求地址

目的：
开发者 在写程序时可以 调用api来注册服务，和请求其它已注册服务（只需要知道服务名即可）

**Comment by sshuangliu** [comment]
这两个需求，如果能原生支持确实很方便，即使不能原生支持，自己也可以写个对frpc配置文件分析功能的函数，然后搭建个api吧
