### ISSUE TITLE
使用stcp ssh提示Could not connect to '127.0.0.1' (port 22): Connection failed

### ISSUE THREAD

**Issue by PalaChen** [fatedier/frp#1858]
使用stcp,  然后输入 ssh -oPort=6000 test@127.0.0.1被ssh提示
Connecting to 127.0.0.1:22...
Could not connect to '127.0.0.1' (port 22): Connection failed
版本为：v0.33.0

各部分的配置如下：

# 服务器中转 frps.ini
[common]
bind_port = 7000

#远程目标配置（办公）  frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[secret_ssh]
type = stcp
sk = abcdefg
local_ip = 127.0.0.1
local_port = 22

#操作客户端（家庭，远程访问办公电脑） frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[secret_ssh_visitor]
type = stcp
role = visitor
server_name = secret_ssh
sk = abcdefg
bind_addr = 127.0.0.1
bind_port = 6000

服务端显示信息
```
2020/06/16 11:02:39 [I] [service.go:178] frps tcp listen on 0.0.0.0:7000
2020/06/16 11:02:39 [I] [root.go:209] start frps success
2020/06/16 11:02:39 [I] [service.go:432] [661198d263674797] client login info: ip [192.168.1.126:55329] version [0.33.0] hostname [] os [windows] arch [amd64]
2020/06/16 11:02:39 [I] [service.go:432] [d63c92112ef5b1d7] client login info: ip [192.168.1.123:47098] version [0.33.0] hostname [] os [linux] arch [amd64]
2020/06/16 11:02:39 [I] [stcp.go:34] [d63c92112ef5b1d7] [ssh] stcp proxy custom listen success
2020/06/16 11:02:39 [I] [control.go:445] [d63c92112ef5b1d7] new proxy [ssh] success
2020/06/16 11:06:41 [I] [control.go:308] [d63c92112ef5b1d7] control writer is closing
2020/06/16 11:06:41 [I] [proxy.go:87] [d63c92112ef5b1d7] [ssh] proxy closing
2020/06/16 11:06:41 [I] [control.go:383] [d63c92112ef5b1d7] client exit success
2020/06/16 11:06:41 [I] [proxy.go:159] [d63c92112ef5b1d7] [ssh] listener is closed
2020/06/16 11:06:43 [I] [service.go:432] [00f8c7b425f94807] client login info: ip [192.168.1.123:47100] version [0.33.0] hostname [] os [linux] arch [amd64]
2020/06/16 11:06:43 [I] [stcp.go:34] [00f8c7b425f94807] [ssh] stcp proxy custom listen success
2020/06/16 11:06:43 [I] [control.go:445] [00f8c7b425f94807] new proxy [ssh] success
2020/06/16 11:07:14 [I] [control.go:308] [661198d263674797] control writer is closing
2020/06/16 11:07:14 [I] [control.go:383] [661198d263674797] client exit success
2020/06/16 11:07:15 [I] [service.go:432] [f72cb1450acc59dc] client login info: ip [192.168.1.126:55495] version [0.33.0] hostname [] os [windows] arch [amd64]
```
远程目标配置（办公）显示信息
```
2020/06/16 11:06:43 [I] [service.go:282] [00f8c7b425f94807] login to server success, get run id [00f8c7b425f94807], server udp port [0]
2020/06/16 11:06:43 [I] [proxy_manager.go:144] [00f8c7b425f94807] proxy added: [ssh]
2020/06/16 11:06:43 [I] [control.go:179] [00f8c7b425f94807] [ssh] start proxy success
```
操作客户端（家庭，远程访问办公电脑）显示信息
```
2020/06/16 11:07:14 [I] [service.go:282] [f72cb1450acc59dc] login to server success, get run id [f72cb1450acc59dc], server udp port [0]
2020/06/16 11:07:14 [I] [visitor_manager.go:86] [f72cb1450acc59dc] start visitor success
2020/06/16 11:07:14 [I] [visitor_manager.go:130] [f72cb1450acc59dc] visitor added: [secret_ssh_visitor]
```

**Comment by Erik-37** [comment]
尝试修改下test@127.0.0.1 中的test为root或平时较常使用的用户名称

**Comment by PalaChen** [comment]
> 尝试修改下test@127.0.0.1 中的test为root或平时较常使用的用户名称

我已经替换了test为我平时使用ssh登陆的账号

**Comment by fatedier** [comment]
frp 的日志里没有显示出错误，感觉大概率是你的 ssh 的配置问题。通过 ssh -vvv 可以显示具体的错误内容。

**Comment by PalaChen** [comment]
> 我查了下 ssh -vvv 没找到对应的用法，可以稍微详细下吗？谢谢。

**Comment by PalaChen** [comment]
> frp 的日志里没有显示出错误，感觉大概率是你的 ssh 的配置问题。通过 ssh -vvv 可以显示具体的错误内容。
···
ssh -vvv zhangmeijie@192.168.1.123
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to 192.168.1.123 [192.168.1.123] port 22.
debug1: Connection established.
debug1: identity file /home/chenxinming/.ssh/id_rsa type -1
debug1: identity file /home/chenxinming/.ssh/id_rsa-cert type -1
debug1: identity file /home/chenxinming/.ssh/id_dsa type -1
debug1: identity file /home/chenxinming/.ssh/id_dsa-cert type -1
debug1: identity file /home/chenxinming/.ssh/id_ecdsa type -1
debug1: identity file /home/chenxinming/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/chenxinming/.ssh/id_ed25519 type -1
debug1: identity file /home/chenxinming/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.10
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.10
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.10 pat OpenSSH_6.6.1* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug3: load_hostkeys: loading entries for host "192.168.1.123" from file "/home/chenxinming/.ssh/known_hosts"
debug3: load_hostkeys: loaded 0 keys
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,ssh-rsa,ssh-dss
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: mac_setup: setup hmac-md5-etm@openssh.com
debug1: kex: server->client aes128-ctr hmac-md5-etm@openssh.com none
debug2: mac_setup: setup hmac-md5-etm@openssh.com
debug1: kex: client->server aes128-ctr hmac-md5-etm@openssh.com none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA 83:54:f5:4d:d3:4f:39:91:ce:06:50:df:7e:f4:e5:d7
debug3: load_hostkeys: loading entries for host "192.168.1.123" from file "/home/chenxinming/.ssh/known_hosts"
debug3: load_hostkeys: loaded 0 keys
The authenticity of host '192.168.1.123 (192.168.1.123)' can't be established.
ECDSA key fingerprint is 83:54:f5:4d:d3:4f:39:91:ce:06:50:df:7e:f4:e5:d7.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.1.123' (ECDSA) to the list of known hosts.
debug1: ssh_ecdsa_verify: signature correct
debug2: kex_derive_keys
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /home/chenxinming/.ssh/id_rsa ((nil)),
debug2: key: /home/chenxinming/.ssh/id_dsa ((nil)),
debug2: key: /home/chenxinming/.ssh/id_ecdsa ((nil)),
debug2: key: /home/chenxinming/.ssh/id_ed25519 ((nil)),
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /home/chenxinming/.ssh/id_rsa
debug3: no such identity: /home/chenxinming/.ssh/id_rsa: No such file or directory
debug1: Trying private key: /home/chenxinming/.ssh/id_dsa
debug3: no such identity: /home/chenxinming/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /home/chenxinming/.ssh/id_ecdsa
debug3: no such identity: /home/chenxinming/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /home/chenxinming/.ssh/id_ed25519
debug3: no such identity: /home/chenxinming/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
zhangmeijie@192.168.1.123's password: 

···

**Comment by fatedier** [comment]
通过 frp 连接的时候，ssh -vvv 的内容是什么样的？

**Comment by PalaChen** [comment]
> 通过 frp 连接的时候，ssh -vvv 的内容是什么样的？


Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Tue Jun 16 10:22:15 CST 2020

  System load:  0.0               Processes:          244
  Usage of /:   75.1% of 3.46TB   Users logged in:    1
  Memory usage: 0%                IP address for em2: 192.168.1.123
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

Last login: Mon Jun 15 19:20:44 2020 from 192.168.1.126
-bash: /usr/local/bin/virtualenvwrapper.sh: No such file or directory

**Comment by fatedier** [comment]
这里是已经连接成功。
