### ISSUE TITLE
open ./frpc.ini: The system cannot find the file specified.

### ISSUE THREAD

**Issue by mumu0v0** [fatedier/frp#1859]
open ./frpc.ini: The system cannot find the file specified.

**Comment by Jessie-Cheng1** [comment]
I also faced thisi problem,and did not solve it.

**Comment by BecodReyes** [comment]
Please make sure the current directory exists frpc.ini file

**Comment by mumu0v0** [comment]
有的

**Comment by BecodReyes** [comment]
请检查是否使用了`frpc -c ./frpc.ini`指定frpc.ini文件
