### ISSUE TITLE
Windows 客户端 能否最小化到任务栏？

### ISSUE THREAD

**Issue by sshuangliu** [fatedier/frp#1861]
内网穿透的场景中，Windows系统 RDP等等服务应该很多，但是目前Windows客户端只能以cmd方式启动，且不能完全后台运行，
能否实现一个简单的GUI，展示下状态，且能**最小化到右下角任务栏**

**Comment by Jamy325** [comment]
通关任务计划开机启动,完全就是后台

**Comment by coderhh** [comment]
可以将frpc 封装成一个windows service, 开机自启动，后台运行。

**Comment by sshuangliu** [comment]
> 可以将frpc 封装成一个windows service, 开机自启动，后台运行。

got it
