### ISSUE TITLE
能否针对单独client 认证？

### ISSUE THREAD

**Issue by sshuangliu** [fatedier/frp#1862]
例如 我有一个vps，我分享**转发服务**给我的多个朋友使用，假如某天我要踢掉某一个朋友，目前情况是需要server client 认证秘钥全部更换，太不方便了吧，而且如果能针对多个client分别认证授权，感觉这个里商业化进了一大步，说不定能更加壮大这个开源项目的影响力，就像v2ray一样（但是这个是合规的哈）

**Comment by fatedier** [comment]
https://github.com/gofrp/fp-multiuser
