### ISSUE TITLE
我现在有100个硬件设备需要做映射到阿里的服务器时，我需要每个客户端配置一个端口？然后云服务器再去配置安全组开放对应端口吗？

### ISSUE THREAD

**Issue by zesongHuang** [fatedier/frp#1863]
有多个设备的时候 每个设备都会占用服务器的一个端口吗?  那如果是云服务器 我还需要每增加一个设备 我就得开放出一个端口吗？

**Comment by eddyyuen** [comment]
昨天我们也遇到这个情况。有同事提出曾经看到某个类似的工具，能提供动态绑定端口的功能。
即 服务端可以指定如 3001为客户端SSH01的远程端口。待SSH01处理完以后，再设置3001为客户端SSH02的远程端口。
这样的好处是，只需少数几个端口就能服务很多客户端。

**Comment by coderhh** [comment]
通过openvpn和frp配合可以实现一个端口访问整个内网的所有设备。

**Comment by sshuangliu** [comment]
你的这一百个设备是在一个内网可以互访吗？ 如果是，单独弄一台作为FRP client ，通过client去访问其他的。
端口太多，就不用端口转发了，直接代理搞定（FRP支持代理），或者放开SSH服务， 启用动态端口转发也行（类似代理），
或者楼上说的VPN最方便，

**Comment by sshuangliu** [comment]
> 昨天我们也遇到这个情况。有同事提出曾经看到某个类似的工具，能提供动态绑定端口的功能。
> 即 服务端可以指定如 3001为客户端SSH01的远程端口。待SSH01处理完以后，再设置3001为客户端SSH02的远程端口。
> 这样的好处是，只需少数几个端口就能服务很多客户端。

你说的应该是 SSH动态端口转发，SSH服务自带

**Comment by fatedier** [comment]
https://gofrp.org/docs/examples/stcp/
https://gofrp.org/docs/features/tcpmux/

**Comment by eddyyuen** [comment]
> https://gofrp.org/docs/examples/stcp/
> https://gofrp.org/docs/features/tcpmux/

tcpmux如果支持 tcp 的话，就是我们之前想做到的
