### ISSUE TITLE
do http proxy request error: context canceled

### ISSUE THREAD

**Issue by wangdaofu** [fatedier/frp#1864]
0.32,0.33版本一直这个问题，连不上；
] [control.go:308] [44d4814cf64b9325] control writer is closing
2020/06/17 16:13:19 [I] [control.go:383] [44d4814cf64b9325] client exit success
2020/06/17 16:13:19 [I] [service.go:420] [44d4814cf64b9325] client login info: ip [39.78.9.XX:51342] version [0.21.0] hostname [] os [linux] arch [mipsle]
2020/06/17 16:13:19 [I] [http.go:92] [44d4814cf64b9325] [web] http proxy listen for host [k2p.wangdaofu.xyz] location [] group []
2020/06/17 16:13:19 [I] [control.go:444] [44d4814cf64b9325] new proxy [web] success
2020/06/17 16:13:38 [I] [control.go:308] [44d4814cf64b9325] control writer is closing
2020/06/17 16:13:38 [I] [proxy.go:75] [44d4814cf64b9325] [web] proxy closing
2020/06/17 16:13:38 [I] [control.go:383] [44d4814cf64b9325] client exit success
2020/06/17 16:13:42 [I] [service.go:420] [74b7113ba6029bee] client login info: ip [39.78.9.XX:51343] version [0.21.0] hostname [] os [linux] arch [mipsle]
2020/06/17 16:13:42 [I] [http.go:92] [74b7113ba6029bee] [web] http proxy listen for host [k2p.wangdaofu.xyz] location [] group []
2020/06/17 16:13:42 [I] [control.go:444] [74b7113ba6029bee] new proxy [web] success
2020/06/17 16:13:42 [I] [proxy.go:91] [74b7113ba6029bee] [web] get a new work connection: [39.78.9.11:51343]
2020/06/17 16:13:46 [W] [http.go:86] do http proxy request error: context canceled
2020/06/17 16:13:46 [I] [proxy.go:91] [74b7113ba6029bee] [web] get a new work connection: [39.78.9.11:51343]
2020/06/17 16:14:46 [W] [http.go:86] do http proxy request error: net/http: timeout awaiting response headers

**Comment by fatedier** [comment]
客户端尽量使用相同的版本。

换一个 web 服务测试，尽量用静态页面，看上去是接口耗时太长。

**Comment by dbgee** [comment]
### 同样出现这个问题，本地访问web 服务正常，通过代理访问就报这个 `context canceled` 错误
```bash
2023/02/15 16:08:21 [W] [http.go:119] do http proxy request [host: admin.xxxx.com:9090] error: context canceled
2023/02/15 16:08:44 [W] [http.go:119] do http proxy request [host: admin.xxxx.com:9090] error: context canceled
2023/02/15 16:08:56 [W] [http.go:119] do http proxy request [host: admin.xxxx.com:9090] error: context canceled
2023/02/15 16:08:56 [W] [http.go:119] do http proxy request [host: admin.xxxx.com:9090] error: context canceled
```

**Comment by dbgee** [comment]
@wangdaofu 你的这个报错解决了没

**Comment by wangdaofu** [comment]
早解决了，升级版本，尽量保持frpc frps版本一致， 多试试几次
