### ISSUE TITLE
以命令行方式运行参数缺失问题

### ISSUE THREAD

**Issue by m2acgi** [fatedier/frp#1865]
以命令行方式运行相比以配置文件运行时存在以下问题:

1.  server 端少了 `max_pool_count`, `tcp_mux` 这两个参数。client 端少了  `pool_count`, `tcp_mux`, `login_fail_exit`, `tls_enable` 这 4 个参数。请问这此在命令行中缺少的参数如何启用、默认值是多少？

2. 以命令行方式运行时，如果同时穿透同一个端口的 tcp 和 udp 时，client 端是否要执行两条命令 `frpc tcp XXX && frpc udp XXX` ? 一条命令能否实现？

**Comment by fatedier** [comment]
命令行参数只是简化某些场景下的使用，并不能提供完整的功能，表达能力有限。

**Comment by m2acgi** [comment]
@fatedier 如果能在命令行下支持所有参数就好了，在 docker container 中运行或者临时使用内网穿透时很方便，直接运行就行了，不用传配置文件。

**Comment by fatedier** [comment]
提供这个的目的就是一些临时使用的场景，但是很多复杂的配置参数不太适合通过命令行参数维护，所以也就没有提供完全的能力。

容器场景下可以通过目录映射来使用配置文件。
