### ISSUE TITLE
the system cannot find the path specified

### ISSUE THREAD

**Issue by opz20** [fatedier/frp#1868]
同目录下frps没有问题 配置文件没有更改 之前都没问题的

**Comment by opz20** [comment]
将目录下frpc更新到最新版本后问题解决，原因未知，从始至终也没有更改frps配置和更新frps。

**Comment by opz20** [comment]
![QQ截图20200621231336](https://user-images.githubusercontent.com/47137779/85228236-f28e9e80-b414-11ea-9a28-090fe61fcdd6.png)
问题复现，frpc和对端frps都是目前最新v0.33.0

**Comment by BecodReyes** [comment]
请确保命令行当前目录下有相应的配置文件
**而不是frp目录下的配置文件**
