### ISSUE TITLE
通过域名访问frps 失败

### ISSUE THREAD

**Issue by hujiachun** [fatedier/frp#1869]
**What version of frp are you using (./frpc -v or ./frps -v)?**
frp_0.33.0_linux_amd64

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**
**frps:**
[common]
bind_port = 7000

**frpc:**
[common]
server_addr = xxx.com
server_port = 80

*[range:tcp_port]
type = tcp
local_ip = 30.35.108.20
local_port = 15000-17700
remote_port = 15000-17700

这里域名映射至frps部署的服务端ip+端口

启动frpc时连接异常
./frpc -c ./frpc.ini

2020/06/19 16:04:53 [W] [service.go:101] login to server failed: EOF
EOF

**Comment by Winter-233** [comment]
不能开CDN，不然找不到源IP

**Comment by BecodReyes** [comment]
请确保域名正确解析至目标服务器上
