### ISSUE TITLE
[已解决]Admin UI 如何添加 外网环境访问端口映射 , [BUG]Admin UI Configure 脏数据

### ISSUE THREAD

**Issue by freshgeek** [fatedier/frp#1872]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.33.0

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**
```
# server.ini
[common]
bind_port = 7000
dashboard_port = 7500
# dashboard 用户名密码，默认都为 admin
dashboard_user = admin
dashboard_pwd = 
authentication_method = token

token = cccc

```

```
#client.ini

[common]
server_addr = 
server_port = 7000

token = cccc

admin_addr = 0.0.0.0
admin_port = 7400
admin_user = admin
admin_pwd = admin
remote_port = 7400

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000


```

**Steps to reproduce the issue:**
1.启动服务端
2.启动客户端
3.本地访问客户端,校验正常
4.外网访问失败

**Describe the results you received:**

**Describe the results you expected:**
在 文档中写道:

打开浏览器通过 http://127.0.0.1:7400 访问 Admin UI，用户名密码默认为 admin。

如果想要在外网环境访问 Admin UI，将 7400 端口映射出去即可，但需要重视安全风险。

但是没有示例,如何添加映射,尝试tcp方法添加无果,求助

**Additional information you deem important (e.g. issue happens only occasionally):**
同时,在我这个配置情况下,发现在本地访问 Admin UI ,Configure 下,得到结果为:
**注意**:我在客户端中有配置token,但是网页上面没有显示,也就是脏数据现象
```
[common]
server_addr =  
server_port = 7000


admin_addr = 0.0.0.0
admin_port = 7400
admin_user = admin
admin_pwd = admin
remote_port = 7400

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

```

**Can you point out what caused this issue (optional)**

**Comment by freshgeek** [comment]
可以通过添加 [ssh] 节点映射


```

[common]
server_addr = 
server_port = 7000

token = cccc

admin_addr = 0.0.0.0
admin_port = 7400
admin_user = admin
admin_pwd = admin
#remote_port = 7400

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 7400
remote_port = 7400


```

**Comment by fatedier** [comment]
注意代理名称 [ssh] 不要重复。

token 不显示是故意为之，不允许修改 token，也防止 token 泄漏。

**Comment by freshgeek** [comment]
好的
