### ISSUE TITLE
What's the security model of frp?

### ISSUE THREAD

**Issue by zzh1996** [fatedier/frp#1873]
I run frpc on computer A and frps on computer B. If one of them is fully controlled by a hacker (so that the config file including the token is leaked), what can the hacker do to the other computer? Is it possible that the hacker can listen on any port or send arbitrary network packets on the other machine?

**Comment by fatedier** [comment]
One frpc only expose your services by your configure file, not controlled by others. So it won't be affected if frps or anothor frpc has been hacked.

**Comment by zzh1996** [comment]
> One frpc only expose your services by your configure file, not controlled by others. So it won't be affected if frps or anothor frpc has been hacked.

What if frpc is hacked and the hacker can compose arbitrary config file?

**Comment by fatedier** [comment]
It's just a common client. You can limit this client by yourself.
