### ISSUE TITLE
公司局域网被禁用frp

### ISSUE THREAD

**Issue by LuckyMango** [fatedier/frp#1874]
在家使用客户端连接服务端都没什么问题，但是到了公司启动客户端的时候就会被报错。
2020/06/21 16:00:48 [W] [service.go:101] login to server failed: EOF
EOF
看到issues有人跟我遇到的问题类似 `版本使用0.33，客户端配置common下面加入tls_enable = true即可`但是还是会爆login to server failed: EOF EOF。通过设置`use_encryption = true`还是不行。请教一下各位大佬，该如何解决。 配置如下：、

[common]
server_addr = xxxx
token =xxxxx
server_port = 5443
	

[http_web]
type = tcp
local_ip = 127.0.0.1
local_port = 8200
remote_port = 80
use_encryption = true
use_compression = true
custom_domains = xxxx.xxxx.xxxx

**Comment by fatedier** [comment]
`tls_enable` 需要在客户端和服务端都增加。

另外，既然公司禁用，建议走正规渠道经过允许后再使用，否则有安全风险可能需要承担一定后果。

**Comment by LuckyMango** [comment]
> `tls_enable` 需要在客户端和服务端都增加。
> 
> 另外，既然公司禁用，建议走正规渠道经过允许后再使用，否则有安全风险可能需要承担一定后果。

嗯嗯，蟹蟹大佬~
