### ISSUE TITLE
关于FRPC 客户端断电自启动配置请教

### ISSUE THREAD

**Issue by wangdaofu** [fatedier/frp#1876]
frpc.service文件路径应如何设置？
/root/frp_0.33.0_linux_mipsle/frpc -c/systemd/frpc.service
/etc/systemd/system/frpc.service

 frpc.service 如何设置？ExecStart 路径如何配置？

[Unit]
Description=Frp Client Service
After=network.target

[Service]
Type=simple
Restart=on-failure
RestartSec=5s
ExecStart=/root/frp_0.33.0_linux_mipsle/frpc -c /root/frp_0.33.0_linux_mipsle/frpc.ini
ExecReload=/root/frp_0.33.0_linux_mipsle/frpc reload -c /root/frp_0.33.0_linux_mipsle/frpc.ini

[Install]
WantedBy=multi-user.target

**Comment by Comaxim** [comment]
尝试 ```systemctl enable frpc``` 。

**Comment by wangdaofu** [comment]
感谢。解决了，不用这么复杂了，开机时添加自动执行的命令就行

**Comment by Comaxim** [comment]
cron？

**Comment by wangdaofu** [comment]
rc.local
