### ISSUE TITLE
mysql数据库端口对外暴露

### ISSUE THREAD

**Issue by pangh-space** [fatedier/frp#1877]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1. 麻烦问一下，是否暴露内网数据库端口，然后通过外网访问，类似访问web 服务一样
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by BecodReyes** [comment]
可以通过tcp映射内网数据库端口至外网实现
**注意使用强密码，防止数据库遭受爆破**
