### ISSUE TITLE
两步验证问题 求助！

### ISSUE THREAD

**Issue by sshuangliu** [fatedier/frp#1882]
对Internet开放的服务，安全性很重要，为防止扫描 暴力破解，计划开启两步验证2FA，已经成功部署，但是 有个疑问：以SSH服务为例，能否验证的时候只输入APP上的动态口令，即‘一步验证’，bypass掉输入本地密码。 或者说有什么对应的其他方案推荐？ 

thanks

**Comment by lyh543** [comment]
我的想法是从iptables进行防护，屏蔽掉访问频繁的链接。可参考
https://lyh543.github.io/Linux/use-iptables-to-protect-ssh-from-brute-force-attack/
不过我还没有进行实现。

**Comment by fatedier** [comment]
如果是类似 iptables 这种方式的话，但是可以通过开发自定义插件来解决。比如限制单个 ip 每分钟的连接次数之类的。

**Comment by sshuangliu** [comment]
> 如果是类似 iptables 这种方式的话，倒是可以通过开发自定义插件来解决。比如限制单个 ip 每分钟的连接次数之类的。

Linux有个这种的方案：Fail2Ban，部署这个服务即可，但是还是没有达到动态密码这种方式来的靠谱

**Comment by sshuangliu** [comment]
> 我的想法是从iptables进行防护，屏蔽掉访问频繁的链接。可参考
> https://lyh543.github.io/Linux/use-iptables-to-protect-ssh-from-brute-force-attack/
> 不过我还没有进行实现。

Fail2Ban可以了解下
