### ISSUE TITLE
例如我有个站点是X-Frame-Options: SAMEORIGIN可以用frp改吗？

### ISSUE THREAD

**Issue by suyuan168** [fatedier/frp#1887]
例如我有个站点是X-Frame-Options: SAMEORIGIN可以用frp改吗？
我看示例有修改head 。是web服务。可以用frpc配置文件替换修改成可以iframe了吗

**Comment by fatedier** [comment]
目前替换的是用户请求的 Request 的 header，而不是你的服务响应的 header。

因为你自己的站点，响应内容是自己可控的，不需要借助 frp 来修改。

**Comment by suyuan168** [comment]
相应内容有办法替换吗。哎 改不了

**Comment by Juli1546** [comment]
前面再挂一个nginx改
