### ISSUE TITLE
win10y远程桌面连接问题

### ISSUE THREAD

**Issue by unstoppableking** [fatedier/frp#1889]
使用frp进行代理后win10被连接端端只能使用相同的local_port 和 remote_port，设置成不同就连接不上

**Comment by sshuangliu** [comment]
没有这种事，你再看看readme

**Comment by WolfCanglong** [comment]
并没有这个问题，一直用的不同端口连的很正常，检查下配置吧

**Comment by ddao** [comment]
@unstoppableking 一直在用，没有这个问题。
如果说使用远程桌面存在问题，应该是使用stcp时，远程桌面不允许连接本地地址，好郁闷！这就产生一个问题，远程桌面无法使用frp的stc模式。

**Comment by fatedier** [comment]
@ddao `远程桌面不允许连接本地地址` ，这种应该和具体的远程桌面应用相关？通常不应该会有这样的限制，可以看是否有什么配置参数可以修改。

或者，可以尝试通过修改 hosts 文件，将 127.0.0.1 映射一个域名，通过域名访问本地地址尝试。
