### ISSUE TITLE
How to install on Linux?

### ISSUE THREAD

**Issue by amiroff157** [fatedier/frp#1892]
There's no info whatsoever on how to build and install this on Ubuntu for example...

what are these supposed to mean:

`./frps -c ./frps.ini`

how to build and run this tunnel server?

**Comment by fatedier** [comment]
You can download binary files from release page https://github.com/fatedier/frp/releases.

Or just exeute `make` to build like other golang projects.

**Comment by amiroffme** [comment]
> You can download binary files from release page https://github.com/fatedier/frp/releases.
> 
> Or just exeute `make` to build like other golang projects.

aren't there any prerequisites for building a goland project? say on a Ubuntu server 20.04 for example?

because out of the box I receive this

`ubuntu@192.168.1.10:/home/frp# make  `
`go fmt ./...  `
`make: go: Command not found  `
`Makefile:19: recipe for target 'fmt' failed  `
`make: *** [fmt] Error 127  `
`ubuntu@192.168.1.10:/home/frp#  `

**Comment by alterhu2020** [comment]
linux is a bit same as other platform, https://code.pingbook.top/blog/setup/frp-linux-setup.html

**Comment by amiroff157** [comment]
> linux is a bit same as other platform, https://code.pingbook.top/blog/setup/frp-linux-setup.html

I see many examples like setting logs that are missing from the docs of this repository. The link you sent is in Chinese. Is there any documentation in English? with all the API?

**Comment by fatedier** [comment]
https://github.com/fatedier/frp#example-usage

@amiroff157 Try this documents.

**Comment by amiroff157** [comment]
> https://github.com/fatedier/frp#example-usage
> 
> @amiroff157 Try this documents.

Any examples on how logging work? I can't find any

For example:

log_file = ./frps.log
log_level = info
log_max_days = 30
token = 1

I want to know how these work

**Comment by antonioribeiro** [comment]
# frp quick install guide (ubuntu + macOS)

## install go
```
apt-get install golang
```

## clone the repo
```
git clone https://github.com/fatedier/frp.git
cd frp
```

## compile it
```
make
```

## put your frps.toml file on the server

```
## frps.toml
bindPort = 7000
```

## then run it

```
./bin/frps -c ./frps.toml
```

## you should see something like this
```
2025-08-04 09:36:04.499 [I] [frps/root.go:108] frps uses config file: ./frps.toml
2025-08-04 09:36:04.656 [I] [server/service.go:237] frps tcp listen on 0.0.0.0:7000
2025-08-04 09:36:04.656 [I] [frps/root.go:117] frps started successfully
```

## install the client on macOS 

brew install fprc


## put your frpc.toml file on the client

```
## frpc.toml
serverAddr = "x.x.x.x"
serverPort = 7000

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000
```

## you should see something like this

```
2025-08-04 11:52:57.876 [I] [sub/root.go:149] start frpc service for config file [frpc.toml]
2025-08-04 11:52:57.877 [I] [client/service.go:314] try to connect to server...
2025-08-04 11:52:57.941 [I] [client/service.go:306] [44010f04a487b443] login to server success, get run id [44010f04a487b443]
2025-08-04 11:52:57.941 [I] [proxy/proxy_manager.go:177] [44010f04a487b443] proxy added: [ssh]
2025-08-04 11:52:57.962 [I] [client/control.go:172] [44010f04a487b443] [ssh] start proxy success
```

**Comment by amir0ff** [comment]
@antonioribeiro my dude it's been 5 years and already using FRPS on all my servers 😉
