### ISSUE TITLE
[udp.go:99]  [UDP] read from workConn for udp error: EOF[0m

### ISSUE THREAD

**Issue by KonpakuSyl** [fatedier/frp#1893]
[udp.go:99] [UDP] read from workConn for udp error: EOF[0m

> 2020/07/07 17:44:34 [1;34m[I] [control.go:445] [a9c2926e1530b484] new proxy [UDP] success[0m
2020/07/07 17:44:35 [1;34m[I] [proxy.go:103] [a9c2926e1530b484] [UDP] get a new work connection: [myIP:5056][0m
2020/07/07 17:44:53 [1;34m[I] [dashboard_api.go:180] Http request: [/api/proxy/tcp][0m
2020/07/07 17:44:53 [1;34m[I] [dashboard_api.go:174] Http response [/api/proxy/tcp]: code [200][0m
2020/07/07 17:44:53 [1;34m[I] [dashboard_api.go:180] Http request: [/api/proxy/udp][0m
2020/07/07 17:44:53 [1;34m[I] [dashboard_api.go:174] Http response [/api/proxy/udp]: code [200][0m
2020/07/07 17:44:54 [1;34m[I] [dashboard_api.go:180] Http request: [/api/proxy/tcp][0m
2020/07/07 17:44:54 [1;34m[I] [dashboard_api.go:174] Http response [/api/proxy/tcp]: code [200][0m
2020/07/07 17:44:54 [1;34m[I] [dashboard_api.go:180] Http request: [/api/proxy/udp][0m
2020/07/07 17:44:54 [1;34m[I] [dashboard_api.go:174] Http response [/api/proxy/udp]: code [200][0m
2020/07/07 17:44:55 [1;34m[I] [dashboard_api.go:65] Http request: [/api/serverinfo][0m
2020/07/07 17:44:55 [1;34m[I] [dashboard_api.go:58] Http response [/api/serverinfo]: code [200][0m
2020/07/07 18:37:24 [1;34m[I] [dashboard_api.go:180] Http request: [/api/proxy/tcp][0m
2020/07/07 18:37:24 [1;34m[I] [dashboard_api.go:174] Http response [/api/proxy/tcp]: code [200][0m
2020/07/07 18:37:25 [1;34m[I] [dashboard_api.go:180] Http request: [/api/proxy/udp][0m
2020/07/07 18:37:25 [1;34m[I] [dashboard_api.go:174] Http response [/api/proxy/udp]: code [200][0m
2020/07/07 18:37:25 [1;34m[I] [dashboard_api.go:180] Http request: [/api/proxy/tcp][0m
2020/07/07 18:37:25 [1;34m[I] [dashboard_api.go:174] Http response [/api/proxy/tcp]: code [200][0m
2020/07/07 18:37:26 [1;34m[I] [dashboard_api.go:65] Http request: [/api/serverinfo][0m
2020/07/07 18:37:26 [1;34m[I] [dashboard_api.go:58] Http response [/api/serverinfo]: code [200][0m
2020/07/07 19:45:00 [1;33m[W] [udp.go:99] [a9c2926e1530b484] [UDP] read from workConn for udp error: EOF[0m
2020/07/07 19:45:00 [1;34m[I] [proxy.go:103] [a9c2926e1530b484] [UDP] get a new work connection: [myIP:5056][0m
2020/07/07 19:45:00 [1;33m[W] [proxy.go:133] [a9c2926e1530b484] [UDP] failed to send message to work connection from pool: stream closed, times: 0[0m
2020/07/07 19:45:00 [1;33m[W] [control.go:312] [a9c2926e1530b484] write message to control connection error: stream closed[0m
2020/07/07 19:45:00 [1;34m[I] [proxy.go:87] [a9c2926e1530b484] [RDP] proxy closing[0m
2020/07/07 19:45:00 [1;34m[I] [proxy.go:159] [a9c2926e1530b484] [RDP] listener is closed[0m
2020/07/07 19:45:00 [1;34m[I] [proxy.go:87] [a9c2926e1530b484] [UDP] proxy closing[0m
2020/07/07 19:45:00 [1;34m[I] [control.go:383] [a9c2926e1530b484] client exit success[0m
2020/07/07 19:45:00 [1;34m[I] [udp.go:155] [a9c2926e1530b484] [UDP] sender goroutine for udp work connection closed[0m
2020/07/07 19:45:00 [1;33m[W] [control.go:263] [a9c2926e1530b484] no work connections avaiable, control is closed[0m
2020/07/07 19:45:00 [1;33m[W] [proxy.go:100] [a9c2926e1530b484] [UDP] failed to get work connection: control is closed[0m
2020/07/07 19:45:04 [1;34m[I] [service.go:432] [a9c2926e1530b484] client login info: ip [myIP:6529] version [0.33.0] hostname [] os [windows] arch [amd64][0m
2020/07/07 19:45:04 [1;34m[I] [tcp.go:63] [a9c2926e1530b484] [RDP] tcp proxy listen port [8777][0m
2020/07/07 19:45:04 [1;34m[I] [control.go:445] [a9c2926e1530b484] new proxy [RDP] success[0m
2020/07/07 19:45:04 [1;34m[I] [udp.go:81] [a9c2926e1530b484] [UDP] udp proxy listen port [8777][0m
2020/07/07 19:45:04 [1;34m[I] [control.go:445] [a9c2926e1530b484] new proxy [UDP] success[0m
2020/07/07 19:45:04 [1;34m[I] [proxy.go:103] [a9c2926e1530b484] [UDP] get a new work connection: [myIP:6529][0m

**Comment by Scorpio-ljc** [comment]
我也遇到这个问题了，请问你解决了吗？

**Comment by KonpakuSyl** [comment]
> 我也遇到这个问题了，请问你解决了吗？

没，查了下没找到原因是啥

**Comment by Scorpio-ljc** [comment]
> > 我也遇到这个问题了，请问你解决了吗？
> 
> 
> 
> 没，查了下没找到原因是啥

我看了一下，我这边是因为阿里云没开对应端口udp，你那边可以看一下是不是MTU设置大小问题
