### ISSUE TITLE
是否能在插件模式中加入bandwidth_limit字段的传输

### ISSUE THREAD

**Issue by allanpk716** [fatedier/frp#1894]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.33

**What operating system and processor architecture are you using (`go env`)?**
windows 10

**Configures you used:**
# frpc.ini
[common]
server_addr = 127.0.0.1
server_port = 7000
user = user_00
meta_token = 123
meta_sign = 26887e50ad3c2366db1a63c05a6fef50

[ssh]
type = tcp
local_port = 22
remote_port = 6000
bandwidth_limit = 200KB
use_encryption = true
use_compression = true

# frps.ini
[common]
bind_port = 7000

[plugin.multiuser]
addr = 127.0.0.1:5000
path = /handler
ops = Login,NewProxy,Ping,NewWorkConn,NewUserConn

**Steps to reproduce the issue:**
使用最新的 0.33 的插件模式，希望能够自己做 Client 的配置的简单验证（从服务器下发 Client 的配置，然后防止恶意修改）。目前账号密码以及代理的部分配置都可以完成想要的功能。但是想在 Client 这一边做限速，看文档可以使用 bandwidth_limit  做到。那么就需要能在插件模式的时候，发送的数据结构中包含这个配置信息。

**Describe the results you received:**
在代理模式中 NewProxy 、Ping 拿到的数据没有包含 bandwidth_limit 这个字段的配置信息

**Describe the results you expected:**
希望插件模式中，在 NewProxy 或者是 Ping 的时候拿到 bandwidth_limit  这个字段，以便能够在插件代理端进行解析。

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
这个配置是客户端自己做的主动限速，所以不会上传到服务端，插件中也就拿不到这个配置。目前插件只能修改在服务端生效的配置。

**Comment by allanpk716** [comment]
> 这个配置是客户端自己做的主动限速，所以不会上传到服务端，插件中也就拿不到这个配置。目前插件只能修改在服务端生效的配置。

是否后续考虑能留选择性的配置，传输客户端的配置信息给服务器呢？这样插件能额外做一些功能。

**Comment by fatedier** [comment]
@allanpk716 这些信息只在客户端使用，传输上来会增加成本，并不是很合适，插件只能修改针对服务端起作用的参数。或者说，即使修改了，因为是在客户端生效，客户端也完全可以不遵循修改后的内容。

**Comment by allanpk716** [comment]
> @allanpk716 这些信息只在客户端使用，传输上来会增加成本，并不是很合适，插件只能修改针对服务端起作用的参数。或者说，即使修改了，因为是在客户端生效，客户端也完全可以不遵循修改后的内容。

好的
