### ISSUE TITLE
[feature request] fastcgi support

### ISSUE THREAD

**Issue by frankli0324** [fatedier/frp#1896]
有没有可能添加fastcgi->http 根据server name复用端口的功能？

给frps添加类似vhost_http_port的vhost_fcgi_port，frpc添加fcgi type，配置类似http这样？

**Comment by fatedier** [comment]
从你上面的请求路径里，对外暴露的还是 http 的接口，内部 fastcgi 建议还是通过 nginx 来转发，frp 只负责将请求转发给 nginx。

否则感觉类似的需求需要将整个 nginx 的功能再实现一遍了，有些臃肿了。

**Comment by frankli0324** [comment]
并不需要实现nginx的整个功能吧emmmm既然能通过HTTP Host来判断走哪个代理。。原理应该是一样的
我有一大堆web服务，藏在frpc后面，目前是我得给每个web应用都开一个nginx去fastcgi_pass
然后现在想的是，有一个nginx会fastcgi_pass到一个frps的端口，frps通过cgi请求中的参数将tcp流原模原样代理到相应的应用，这样应该也不会出现需要X-Forwarded-For来判断远程ip的情况了

**Comment by frankli0324** [comment]
我试试吧，顺便学一学go

**Comment by fatedier** [comment]
对于这一类 nginx 能解决的需求，加了一个，就会有另外一个。既然 nginx 提供了这样丰富的能力，就尽量组合来用，会减少很多复杂度。

**Comment by frankli0324** [comment]
emmmmm好吧
