### ISSUE TITLE
i cant view my web server from frp

### ISSUE THREAD

**Issue by vay3t** [fatedier/frp#1897]
**What version of frp are you using (./frpc -v or ./frps -v)?**

* frpc `0.33.0`
* frps `0.33.0`

**What operating system and processor architecture are you using (`go env`)?**

* AMD64

**Configures you used:**

```
[common]
bind_addr = 0.0.0.0
bind_port = 7000
bind_udp_port = 7001
kcp_bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
dashboard_addr = 127.0.0.1
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin
enable_prometheus = false
log_file = /path/for/logs/frp_0.33.0_linux_amd64/frps.log
log_level = info
log_max_days = 3
disable_log_color = false
detailed_errors_to_client = true
authentication_method = token
authenticate_heartbeats = false
authenticate_new_work_conns = false
token = tokenstring
oidc_client_id =
oidc_client_secret = 
oidc_audience = 
oidc_token_endpoint_url = 
allow_ports = 2000-3000,3001,3003,4000-50000
max_pool_count = 5
max_ports_per_client = 0
tls_only = false
subdomain_host = 
tcp_mux = true
```

**Steps to reproduce the issue:**
* 1:  `python3 -m http.server`

* 2: `./frpc http -s x.x.x.x:7000 -t tokenstring -l 8000`

**Describe the results you received:**

```
The page you requested was not found.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

The server is powered by frp.

Faithfully yours, frp.
```

**Describe the results you expected:**
View my files shared by python http server

**Additional information you deem important (e.g. issue happens only occasionally):**

```
2020/07/10 23:41:03 [I] [service.go:432] [34223cf508ecbc85] client login info: ip [myip:47298] version [0.33.0] hostname [] os [linux] arch [amd64]
2020/07/10 23:41:04 [I] [control.go:445] [34223cf508ecbc85] new proxy [] success
2020/07/10 23:41:07 [W] [http.go:86] do http proxy request error: no such domain: x.x.x.x /

```

**Can you point out what caused this issue (optional)**

**Comment by frankli0324** [comment]
you need to specify the domain (-d option) or subdomain (-sd option) on frpc
since you didn't set the subdomain on frps, you should use -d option.

**Comment by girishbin** [comment]
on you local machine where you run frp client i.e frpc -c frpc.ini make a entry of the  frp server ( frps) address in "/etc/hosts".  This works for both mac and linux.
