### ISSUE TITLE
tls开启后慢

### ISSUE THREAD

**Issue by PHCSJC** [fatedier/frp#1899]
2边的版本都是v0.32.1，昨天试了下这个参数tls_enable = true

发现非常的慢，我用frp连接远程桌面，发现远程桌面非常的卡，把这个参数去掉后就好了，不知道啥原因。

**Comment by PHCSJC** [comment]
另外，请问如果不开启加密use_compression = true，那防火墙里识别到的是什么流量呢？

**Comment by fatedier** [comment]
TLS 会启用加密传输，需要消耗额外的 CPU 资源来加密，机器性能不好的话就不要加了。

`use_compression = true` 用的是 AES 加密。
