### ISSUE TITLE
X86 Windows server 无法运行386.zip

### ISSUE THREAD

**Issue by Alan996** [fatedier/frp#1900]
你好，开发者。下载了frp_0.33.0_windows_386.zip，但提示非32位程序。 这是什么问题呢。
![image](https://user-images.githubusercontent.com/41531958/87426336-95e86300-c611-11ea-8355-a0c557abfda4.png)

**Comment by ysc3839** [comment]
看了下可执行文件，要求的最低系统版本是 6.1，即 Windows 7 或者 Windows Server 2008 R2。你用的可能是 Windows Server 2008，所以无法运行。
至于“不是有效的 Win32 应用程序”，这是 Windows 文案的问题，意思是这个程序不能在这个系统上运行。
