### ISSUE TITLE
Is it possible to run frpc client as a service in Windows 10 ?

### ISSUE THREAD

**Issue by burkifaso** [fatedier/frp#1901]
Is it possible to run frpc client as a service in Windows 10 ? how to do it ? 

thx

**Comment by John-Chan** [comment]
You may use some service wrapper to let it run as a windows service , e.g.  [winsw](https://github.com/winsw/winsw)

**Comment by John-Chan** [comment]
http://note.eta.pub/2020/07/21/frp-windows-service/

**Comment by inter1965** [comment]
srvman
