### ISSUE TITLE
Remdme.md 建议

### ISSUE THREAD

**Issue by DevSoft2016** [fatedier/frp#1902]
在腾讯云的 Centos  中 直接运行提示 没有找到命令行
在 给了 可执行权限 解决  可以加到说明文档里吗
加入开机启动 和后台运行的命令

**Comment by fatedier** [comment]
可以加到 FAQ 中，属于一些常识性的问题。

**Comment by DevSoft2016** [comment]
FAQ 哪里看, 我才用这个

**Comment by BecodReyes** [comment]
https://gofrp.org/docs/faq/

你可以为此文档提交[Pull requests](https://github.com/gofrp/frp-doc/edit/master/content/zh/docs/FAQ/_index.md)
