### ISSUE TITLE
How to get list of connected clients ?

### ISSUE THREAD

**Issue by burkifaso** [fatedier/frp#1905]
Hey, I would like to get list of all clients connected to server via api

like 

proxy1:port
proxy2:port

how to do it ? thanks

**Comment by BecodReyes** [comment]
You can add content by editing the source code

Or through get dashboard content, through regular implementation

**Comment by ErixWong** [comment]
Hi, buddy

try this:

http://127.0.0.1:7500/api/proxy/tcp
http://127.0.0.1:7500/api/proxy/udp
http://127.0.0.1:7500/api/proxy/http
http://127.0.0.1:7500/api/proxy/https
