### ISSUE TITLE
Permission denied, please try again

### ISSUE THREAD

**Issue by 649459021** [fatedier/frp#1906]
我用来内网穿透，都配置好之后，内网主机与公网主机也已经连接成功，但在本地ssh输入密码显示错误
ssh -p 6000 root@ip
_return:_
Permission denied, please try again.

我直接ssh root@ip输入密码是正确的，加上端口后就不正确了

不知该如何解决

**Comment by yilong877** [comment]
把root换成内网主机的其它用户试试

**Comment by 649459021** [comment]
> 把root换成内网主机的其它用户试试

太关键了兄弟，非常感谢

**Comment by Sberm** [comment]
@yilong877 完美解决问题，原来是我电脑上root密码不对，感谢！

**Comment by Sberm** [comment]
> 把root换成内网主机的其它用户试试
完美解决问题，原来是我电脑上root密码不对，感谢！

**Comment by Sberm** [comment]
> 把root换成内网主机的其它用户试试

完美解决问题，原来是我电脑上root密码不对，换成其他用户就可以了，感谢！

**Comment by withhaotian** [comment]
> 把root换成内网主机的其它用户试试

Cool！感谢~

**Comment by Iron-LYK** [comment]
nb!
