### ISSUE TITLE
Max ports per client issue ?

### ISSUE THREAD

**Issue by burkifaso** [fatedier/frp#1911]
I have specified in the server config file : 

max_ports_per_client = 1

but I can still run few instances of frp clients on my windows machine and connect to the server..

as a client I'm running http proxy plugin .. below is client config

```
[common]
server_addr = xxxxxxxxx
server_port = 8200
protocol = tcp
token = 'xxxx'

[http_proxy]
type = tcp
remote_port = 0
plugin = http_proxy
plugin_http_user = xxxx
plugin_http_passwd = xxxx
```

why ?

**Comment by fatedier** [comment]
`max_ports_per_client` means limit the max ports one frpc can use.

**Comment by burkifaso** [comment]
thanks, but how to do it on the server side, allow client to made max one connection to server.

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/doc/server_plugin.md

You can achieve more custom features by `frp server plugin`.
