### ISSUE TITLE
[RFC] frp should have TLS certificate auth

### ISSUE THREAD

**Issue by netroby** [fatedier/frp#1913]
https://golang.org/src/crypto/tls/auth.go

<img width="627" alt="微信图片_20200722165213" src="https://user-images.githubusercontent.com/66301650/88156532-24756980-cc3c-11ea-8659-cb19359f5a2d.png">

As a sad story said. the FRP token base auth may be a bit weakness.

So please provided us the TLS certificate auth.

User must have the valid private cert , to pass the auth progress.

**Comment by fatedier** [comment]
We have already planned to support the certificate auth for TLS.

But maybe it's doesn't solve the problem in the image you paste.  [stcp](https://github.com/fatedier/frp#expose-your-service-privately) is designed to avoid this security issue.

**Comment by netroby** [comment]
I am using sctp already, but the authenticated really really need to improve. Not just by token. it's short and may be crack . 
The certificate may be harder to crack

**Comment by limaofu** [comment]
你这个情况和frp有什么关系吗？

**Comment by QQ2017** [comment]
你这个是应用本身的安全问题，并不是网络代理软件的问题。你应该使用STCP模式。

**Comment by fatedier** [comment]
Supported in v0.34.0
