### ISSUE TITLE
想获取下请求的url

### ISSUE THREAD

**Issue by quliting** [fatedier/frp#1921]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

在C端，想获取下请求的URL
查看有没有通知到；

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by BecodReyes** [comment]
可在后端响应日志中查找到

**Comment by quliting** [comment]
# console or real logFile path like ./frps.log
log_file = ./frps.log

# trace, debug, info, warn, error
log_level = info
是这个吗？

https://github.com/fatedier/frp/blob/master/conf/frps_full.ini；
47行；

**Comment by BecodReyes** [comment]
> console or real logFile path like ./frps.log
> log_file = ./frps.log
> 
> trace, debug, info, warn, error
> log_level = info
> 是这个吗？
> 
> [https://github.com/fatedier/frp/blob/master/conf/frps_full.ini；](https://github.com/fatedier/frp/blob/master/conf/frps_full.ini%EF%BC%9B)
> 47行；

并不是frps
而且frpc代理后的服务端
例如nginx/apache/caddy的日志

**Comment by quliting** [comment]
我只是在linux 上面运行下frpc；其他的啥都没用；

**Comment by BecodReyes** [comment]
> 我只是在linux 上面运行下frpc；其他的啥都没用；

frp只是一个代理软件，并不处理http请求内容

**Comment by quliting** [comment]
嗯，明白了你的意思；
但是，按照逻辑来说，所有的请求都通过他，他应该知道是哪些请求；谢谢；

**Comment by BecodReyes** [comment]
> 嗯，明白了你的意思；
> 但是，按照逻辑来说，所有的请求都通过他，他应该知道是哪些请求；谢谢；

阅读源码或wiki，你将会发现更多

**Comment by quliting** [comment]
谢谢；
