### ISSUE TITLE
代理https出错

### ISSUE THREAD

**Issue by muyen2** [fatedier/frp#1922]
版本
frp_0.33.0_windows_amd64 ， 
windows 10 (6.1.7601)

服务器
WINDOWS SERVER 2016

frps配置

[common]
bind_addr = 0.0.0.0
bind_port = 8449
#log_file = ./frps.log

dashboard_addr = 0.0.0.0
dashboard_port = 7500
vhost_https_port = 8443
subdomain_host =XXX.xyz

dashboard_user = XXXX
dashboard_pwd = XXXX

authentication_method = token
authenticate_heartbeats = true
token = XXXX

frpc配置

[common]
server_addr =XXXX
server_port =8449
token =XXXX
authentication_method = token
authenticate_heartbeats = true
#log_file = ./frpc.log

[myweb]
type = https
subdomain = dev
local_ip = 127.0.0.1
local_port = 8443
use_encryption = false
use_compression = true

问题

1. 从安装 frps服务器上面请求https 链接 正常显示。
2. 无论是从本地，或者 手机，都显示无法连接。
    电脑上显示ERR_CONNECTION_CLOSED
    手机上面显示 ERR_SL_PROTOCOL_ERROR

抓包，看到区别是 Client Hello 不行的是TLSV1，，正常的是TLS1.2

或者在本地修改hosts文件
127.0.0.1 XXX.COM
都能正常使用，请大家多多赐教，不胜感激！

**Comment by BecodReyes** [comment]
请在客户端进行绑定域名操作
请描述得更清楚些（使用模板）
