### ISSUE TITLE
代理有时出现错误，frps重启错误又消失

### ISSUE THREAD

**Issue by mengpengfei** [fatedier/frp#1923]
我用的版本是：frp_0.27.1

2020/07/30 10:04:55 [W] [http.go:223] http: proxy error: context canceled
2020/07/30 10:04:58 [W] [http.go:223] http: proxy error: context canceled
2020/07/30 10:05:00 [W] [http.go:223] http: proxy error: context canceled
2020/07/30 10:05:03 [W] [http.go:223] http: proxy error: context canceled
2020/07/30 10:05:04 [W] [http.go:223] http: proxy error: context canceled
2020/07/30 10:05:08 [W] [http.go:223] http: proxy error: context canceled
2020/07/30 10:05:09 [W] [http.go:223] http: proxy error: context canceled
2020/07/30 10:05:15 [W] [http.go:223] http: proxy error: context canceled
2020/07/30 10:05:18 [W] [http.go:223] http: proxy error: context canceled
2020/07/30 10:05:19 [W] [http.go:223] http: proxy error: context canceled
2020/07/30 10:05:27 [W] [http.go:223] http: proxy error: context canceled
2020/07/30 10:05:27 [W] [control.go:395] [f667bd56635ef140] new proxy [webhttp] error: router config conflict
2020/07/30 10:05:27 [W] [control.go:395] [f667bd56635ef140] new proxy [webssl] error: hostname [www.***.***] location [] is already registered
2020/07/30 10:05:27 [W] [control.go:395] [f667bd56635ef140] new proxy [mysql] error: port already used
2020/07/30 10:05:27 [W] [control.go:395] [f667bd56635ef140] new proxy [remote-desktop] error: port already used

**Comment by BecodReyes** [comment]
端口已被使用，请检查相应端口是否已被占用

**Comment by mengpengfei** [comment]
没解决问题，一直运行好好的，时不时的就端口冲突

**Comment by BecodReyes** [comment]
路由冲突，请附上frpc配置文件

**Comment by MicyToy** [comment]
frps: 2021/11/15 10:28:21 #033[1;33m[W] [http.go:92] do http proxy request error: context canceled#033[0m
frps: 2021/11/15 10:28:21 #033[1;33m[W] [http.go:92] do http proxy request error: context canceled#033[0m
frps: 2021/11/15 10:28:21 #033[1;33m[W] [http.go:92] do http proxy request error: context canceled#033[0m
frps: 2021/11/15 10:28:23 #033[1;33m[W] [http.go:92] do http proxy request error: context canceled#033[0m
frps: 2021/11/15 10:28:24 #033[1;33m[W] [http.go:92] do http proxy request error: context canceled#033[0m
frps: 2021/11/15 10:28:24 #033[1;33m[W] [http.go:92] do http proxy request error: context canceled#033[0m
frps: 2021/11/15 10:28:25 #033[1;33m[W] [http.go:92] do http proxy request error: context canceled#033[0m


同遇到，代理的网页有时能刷出来，有时刷不出来。
0.37.1
