### ISSUE TITLE
http proxy doesn't supprt NTLM authentication

### ISSUE THREAD

**Issue by laodu0** [fatedier/frp#1924]
it's not an issue in face, frp doesn't support NTLM authentication http proxy, can you add NTLM authentication support?

**Comment by fatedier** [comment]
What's your usage scenario?

**Comment by laodu0** [comment]
In out company internal network, if you want to connect internet you have to use our company internal http proxy server. This http proxy server using domain user authentication, 

Proxy IP : 172.24.249.180
Port : 80
Domain : PSZ
UserName : Paul_Di
Password : @*c1234

It's NTLM protocol. I cannot use http://user:pwd@proxy:port to access NTLM authentication http server. Is is possible to add NTLM authentication support?

https://docs.microsoft.com/zh-cn/windows/win32/secauthn/microsoft-ntlm?redirectedfrom=MSDN

**Comment by laodu0** [comment]
look at this repo

https://github.com/Azure/go-ntlmssp

**Comment by fatedier** [comment]
I will do a research on it when i have time.
