### ISSUE TITLE
websocket 支持域名

### ISSUE THREAD

**Issue by gdpancheng** [fatedier/frp#1925]
怎么样可以让websocket 支持域名，小程序中得websocket需要域名才可以访问

**Comment by Kabieee** [comment]
加个subdomain或者custom_domains就行了

**Comment by gdpancheng** [comment]
我知道type = http是支持域名的 但是type = http走不了websocket 
protocol = websocket 可以支持websocket 但是没办法使用subdomain

**Comment by Kabieee** [comment]
> 我知道type = http是支持域名的 但是type = http走不了websocket
> protocol = websocket 可以支持websocket 但是没办法使用subdomain

如果小程序用websocket，直接用type=tcp就可以啊

[my_websocket]
type = tcp
local_ip = 127.0.0.1
local_port = 50075
remote_port = 33035
//我感觉tcp这里配不配域名都行, dns能把域名解析成ip就可以
custom_domains= tcp.xxx.com

**Comment by fatedier** [comment]
`type = http走不了websocket`，websocket 不是 HTTP 协议吗？
