### ISSUE TITLE
长时间重启FRPS服务，dashboard 界面会显示不全或者不显示。

### ISSUE THREAD

**Issue by 932279632** [fatedier/frp#1928]
长时间重启FRPS服务，dashboard 界面会显示不全或者不显示。因为需要dashboard界面看设备在线和流量使用情况。设备增多流量突涨dashboard界面就会出现好多设备不显示，请问有什么好的解决方案吗？
Prometheus已经开启，但不直观。

**Comment by BecodReyes** [comment]
启用DevTools，查看是否有资源因为服务器/网络问题导致加载失败

**Comment by fatedier** [comment]
@932279632 现在的 proxy 的数量是多少？如果太多的话，目前没有分页确实会有问题。之后会重构这部分的 API ，然后支持分页显示。

**Comment by 932279632** [comment]
> @ 932279632现在的proxy的数量是多少？如果太多的话，目前没有分页确实会有问题。之后会转换这部分的API，然后支持分页显示。

proxy的数量保持在30-50左右，协议几乎都是TCO，流量每天约5G左右，一个月到两个月会出现机器显示不全概率很大。重启后恢复正常。

**Comment by 932279632** [comment]
> 启用DevTools，查看是否有资源因为服务器/网络问题导致加载失败

服务器资源足够用，连接数也不多30-50左右，麻烦问下DevTools怎么启用呢？

**Comment by fatedier** [comment]
这个数量不多，不会有问题，可以按照 issue 模版，详细描述你遇到的问题。

**Comment by BecodReyes** [comment]
> > 启用DevTools，查看是否有资源因为服务器/网络问题导致加载失败
> 
> 服务器资源足够用，连接数也不多30-50左右，麻烦问下DevTools怎么启用呢？

F12



> > @ 932279632现在的proxy的数量是多少？如果太多的话，目前没有分页确实会有问题。之后会转换这部分的API，然后支持分页显示。
> 
> proxy的数量保持在30-50左右，协议几乎都是TCO，流量每天约5G左右，一个月到两个月会出现机器显示不全概率很大。重启后恢复正常。

建议目前还是先写一个定期重启的脚本吧
也不费时间

**Comment by 932279632** [comment]
> 这个数量不多，不会有问题，可以按照问题模版，详细描述你遇到的问题。

嗯。好的

**Comment by 932279632** [comment]
> > > 启用DevTools，查看是否有资源因为服务器/网络问题导致加载失败
> > 
> > 
> > 服务器资源足够用，连接数也不多30-50左右，麻烦问下DevTools怎么启用呢？
> 
> F12
> 
> > > @ 932279632现在的代理的数量是多少？如果太多的话，目前没有分页确实会有问题。之后会转换这部分的API，然后支持分页显示。
> > 
> > 
> > proxy的数量保持在30-50左右，协议几乎都是TCO，流量每天约5G左右，一个月到两个月会出现机器显示不全概率很大。重启后恢复正常。
> 
> 建议当前还是先写一个定期重启的脚本吧
> 也不费时间
嗯谢谢额

**Comment by penguin806** [comment]
我也遇到了这个问题，客户端数5，代理数20。现在情况是dashboard只显示5个客户端中其中2的proxy，更新frps到0.33后出现的情况，之前0.26没有这个问题。

**Comment by harmy** [comment]
请升级到0.34.1版本之后再验证是否还有这个情况，之前我的一次PR（#2008 ）也许修复了该问题。
