### ISSUE TITLE
[FEATURE] vhost_http_port支持独立设置监听地址

### ISSUE THREAD

**Issue by easyjack** [fatedier/frp#1929]
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
[root@frps ]# ./frps -v
0.33.0

希望能够提供参数设置指定vhost_http_port 和 vhost_https_port 的监听地址
方便设置port为8080 和 8443 监听在127.0.0.1
然后由nginx转发流量到frps

**Comment by easyjack** [comment]
# specify which address proxy will listen for, default value is same with bind_addr
# proxy_bind_addr = 127.0.0.1
proxy_bind_addr 虽然支持修改proxy的监听地址，但是会影响全部proxy

**Comment by BecodReyes** [comment]
看你的描述，你的环境应该是多ip吧
开启多个frps服务，各自绑定ip即可
Tips: 看见右上那三个点了吗，里边有Edit，可以直接编辑原issue

**Comment by easyjack** [comment]
> 看你的描述，你的环境应该是多ip吧
> 开启多个frps服务，各自绑定ip即可
> 当然bind_port就不能相同了
> Tips: 看见右上那三个点了吗，里边有Edit，可以直接编辑原issue

看你的描述，你是没理解我的意思
让vhost_http_port 和 vhost_https_port 监听在127.0.0.1，不直接对外提供服务，由nginx对外提供服务，再由nginx将外部流量转发到vhost_http_port / vhost_https_port

**Comment by fatedier** [comment]
Try `proxy_bind_addr = 127.0.0.1`

https://github.com/fatedier/frp/blob/master/conf/frps_full.ini#L16

**Comment by BecodReyes** [comment]
> > 看你的描述，你的环境应该是多ip吧
> > 开启多个frps服务，各自绑定ip即可
> > 当然bind_port就不能相同了
> > Tips: 看见右上那三个点了吗，里边有Edit，可以直接编辑原issue
> 
> 看你的描述，你是没理解我的意思
> 让vhost_http_port 和 vhost_https_port 监听在127.0.0.1，不直接对外提供服务，由nginx对外提供服务，再由nginx将外部流量转发到vhost_http_port / vhost_https_port

我的理解是http/https单独监听127.0.0.1
其他映射绑定其他IP
不知对否

**Comment by easyjack** [comment]
> > > 看你的描述，你的环境应该是多ip吧
> > > 开启多个frps服务，各自绑定ip即可
> > > 当然bind_port就不能相同了
> > > Tips: 看见右上那三个点了吗，里边有Edit，可以直接编辑原issue
> > 
> > 
> > 看你的描述，你是没理解我的意思
> > 让vhost_http_port 和 vhost_https_port 监听在127.0.0.1，不直接对外提供服务，由nginx对外提供服务，再由nginx将外部流量转发到vhost_http_port / vhost_https_port
> 
> 我的理解是http/https单独监听127.0.0.1
> 其他映射绑定其他IP
> 不知对否

是的嘞，开多个frps就要多个frpc了

**Comment by BecodReyes** [comment]
> > > > 看你的描述，你的环境应该是多ip吧
> > > > 开启多个frps服务，各自绑定ip即可
> > > > 当然bind_port就不能相同了
> > > > Tips: 看见右上那三个点了吗，里边有Edit，可以直接编辑原issue
> > > 
> > > 
> > > 看你的描述，你是没理解我的意思
> > > 让vhost_http_port 和 vhost_https_port 监听在127.0.0.1，不直接对外提供服务，由nginx对外提供服务，再由nginx将外部流量转发到vhost_http_port / vhost_https_port
> > 
> > 
> > 我的理解是http/https单独监听127.0.0.1
> > 其他映射绑定其他IP
> > 不知对否
> 
> 是的嘞，开多个frps就要多个frpc了

是的
但是在FEATURE未实现/自己魔改的情况下这是最优解
或者可以再加多一层转发，将本地回环的特定端口转发至其他IP

**Comment by fatedier** [comment]
先想一想这是不是一个伪需求，是不是真的必须要这么做才能解决问题。

**Comment by septs** [comment]
@fatedier `vhost_http_port` / `vhost_https_port` 监听 `0.0.0.0` 确实不合理
对于一个部署在公网的 frps，此时将完全对外暴露

**Comment by fatedier** [comment]
@septs `proxy_bind_addr = 127.0.0.1`

https://github.com/fatedier/frp/blob/master/conf/frps_full.ini#L16

可以使用以上配置实现你的需求。

使用 frp 的目的通常是将服务暴露在公网供其他人访问。所以默认状态不会只监听 `127.0.0.1` ，这种做法有点本末倒置。通过上面的配置可以实现你的特殊需求。

**Comment by septs** [comment]
> 使用 frp 的目的通常是将服务暴露在公网供其他人访问。

从 by default security 原则上来说这并不合适

**Comment by easyjack** [comment]
从一些场景来说，为了安全起见，还有让nginx充当前置的缓存加速组件
所以建议能够单独设置参数让 vhost_http_port / vhost_https_port 监听在特定的地址（127.0.0.1）
当然这也是建议而已
毕竟程序不实现的话，另外配置一下firewalld就好了，没啥

**Comment by fatedier** [comment]
@septs frp 不是为了满足某一个特定场景或需求的项目，在你需要绝对安全的时候目前也不建议使用内网穿透的工具，只能说尽量对有类似需求的用户提供这样的选择。如果对这方面有疑问，可以单独另外开一个 issue 描述你的问题。

还有就是，这个项目的描述 `A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet`，这个是最初也是最核心的能力和目标。

**Comment by fatedier** [comment]
@easyjack 
从需求的角度出发，什么场景下需要严格去要求只有 HTTP/HTTPS 的服务要监听在 `127.0.0.1` ，而其他的服务都可以监听在其他地址?

从做产品的角度:
1. 这样的需求是否是通用的需求，能够解决大多数人的问题。
2. 是否是一个不可替代的需求，不能通过其他方式来完成。
3. 解决这个需求的成本有多大，更多的参数配置，可能潜在地提高了用户的使用成本和上手的复杂度。

从我个人的角度而言，这个阶段不太希望引入各种琐碎的 feature，很容易让项目成为一个大杂烩，既提高开发者的维护成本，也增加了用户的使用成本。最终某些功能可能只有几个人使用，甚至没有人用，但是持续的维护却需要耗费很多精力。

所以，目前可能更多的是希望做减法，专注核心能力，做一些重构。之后能通过插件的方式开放更多的扩展能力出来，可以由有需求的人来完善。
