### ISSUE TITLE
能否二级域名映射，同一端口支持多个域名，服务端暴露过多端口网络安全不允许

### ISSUE THREAD

**Issue by qianlei33** [fatedier/frp#1933]
能否二级域名映射，同一端口支持多个域名，服务端暴露过多端口网络安全不允许，谢谢

**Comment by BecodReyes** [comment]
多域名：
https://github.com/fatedier/frp/blob/master/conf/frps_full.ini#L20
https://github.com/fatedier/frp/blob/master/conf/frps_full.ini#L21
二级域名：
https://github.com/fatedier/frp/blob/master/conf/frps_full.ini#L108

建议看完wiki再来问

**Comment by jiangyan33** [comment]
服务器端和客户端都配置成功了，控制台打印出来的信息也是提示成功，但是二级域名映射到本地服务就是访问不了，我还差点什么吗？
![service](https://user-images.githubusercontent.com/35300813/93563029-b3db9680-f9b9-11ea-93ef-441f4ce2e6eb.png)
![client](https://user-images.githubusercontent.com/35300813/93563035-b63df080-f9b9-11ea-8aa4-10fbbe2bec6f.png)
域名解析我也配置了
