### ISSUE TITLE
能否多台机器的同一端口分别绑定到不同二级域名上（只有一台云服务器）

### ISSUE THREAD

**Issue by flymyd** [fatedier/frp#1934]
有一组程序分为服务端和客户端，在局域网环境下使用相同的端口（12345，TCP）进行直连。当我仅有一台云服务器且需要创建多组服务端——客户端的实例时能否通过vhost等方式进行端口复用？
例：
内网环境下：
服务端A 192.168.10.10:12345——客户端A连接此端口
服务端B 192.168.10.11:12345——客户端B连接此端口
有没有方法实现下述需求？
云服务器（FRP服务端） frp.xxx.com
服务端A使用FRPC连接：servera.frp.xxx.com——客户端A连接servera.frp.xxx.com或servera.frp.xxx.com:12345
服务端B使用FRPC连接：serverb.frp.xxx.com——客户端B连接serverb.frp.xxx.com或serverb.frp.xxx.com:12345

不胜感激！

**Comment by BecodReyes** [comment]
后端负载均衡吧
参见[#端口复用](https://github.com/fatedier/frp/blob/master/README_zh.md#端口复用)&[#负载均衡](https://github.com/fatedier/frp/blob/master/README_zh.md#负载均衡)

**Comment by mbj2014** [comment]
这个问题我也遇到了，没找到文档中介绍端口复用的说明。

另外，这个应该不是负载均衡解决的。因为AB两个是相同的应用程序，但服务的客户是不同的，上面的数据也是不同的。
