### ISSUE TITLE
socks5使用udp的问题

### ISSUE THREAD

**Issue by wanghailin06** [fatedier/frp#1937]
使用socks5插件的时候，在sstap上无法使用udp转发，TCP是可以的，这个是不可以还是我配置有问题啊

**Comment by fatedier** [comment]
目前 socks5 插件只是一个简单的实现，不支持 UDP 转发。

**Comment by wanghailin06** [comment]
好吧，我自己这边实现试下吧

**Comment by fatedier** [comment]
内置插件一般都是比较简单，便于使用，如果需要比较丰富的能力，最好还是自己本地起一个 socks5 代理程序。

**Comment by aa51513** [comment]
> 目前 socks5 插件只是一个简单的实现，不支持 UDP 转发。

原来如此，解决了我的困扰
