### ISSUE TITLE
请问privilege_mode 不支持https吗

### ISSUE THREAD

**Issue by wdc63** [fatedier/frp#194]
frps.ini:
[common]
bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
dashboard_port = 7500
log_file = ./frps.log
log_level = info
log_max_days = 3
subdomain_host = *****.com
privilege_mode = true
privilege_token = 12345678
max_pool_count = 100

frpc.ini
[common]
server_addr = *********
server_port = 7000

log_file = D:/frpc.log

log_level = info
log_max_days = 3

privilege_token = 12345678

[privilege_web1]
privilege_mode = true
type = http
local_port = 80
use_gzip = true
subdomain = www
pool_count = 5

[privilege_web2]
privilege_mode = true
type = https
local_port = 443
use_gzip = true
subdomain = blog
pool_count = 5

frpc是win版的，这样直接秒退，连报错是什么都看不到，如果把[privilege_web2]删掉，就可以正常连接，如果把[privilege_web2]的https改成http，也可以正常连接。

难道是privilege_mode 不支持https吗？？

求解

**Comment by fatedier** [comment]
和 privilege_mode 没有关系，应该是 subdomain 的问题，对于 https 的类型有 bug，我 fix 一下。

在 windows 上可以先开一个 cmd 窗口，再运行 frpc，这样出现异常时不会直接退出，能看到错误信息，这个错误是有错误提示的。

**Comment by wdc63** [comment]
谢谢您，我看到错误提示了
Parse conf error: proxy [privilege_web2] custom_domains and subdomain should set at least one of them when type is https

**Comment by wdc63** [comment]
大概是一个bug吧，因为按照它的错误提示，我已经设置了一个subdomain

**Comment by inke3c** [comment]
@wdc63 @fatedier 
我在 mac 上也遇到了这个问题：
Parse conf error: proxy [web01] custom_domains and subdomain should set at least one of them
