### ISSUE TITLE
https不支持URL路由到不同的客户端

### ISSUE THREAD

**Issue by MasamiYui** [fatedier/frp#1940]
版本
frp_0.32.0_windows_amd64
问题
请问https代理不支持 不同的URL 路由到不同的客户端吗？  http是可以的，如果不可以原因是什么呢？

**Comment by 1-v-1** [comment]
用http  外面套个Nginx+tls

**Comment by xqzr** [comment]
https路径是加密的

**Comment by MasamiYui** [comment]
> https路径是加密的

嗯，谢啦，(*^▽^*)， 我就是说为啥http做了URL匹配而https未做这块呢，建议可以在文档中再写清楚一点

**Comment by MasamiYui** [comment]
> 用http 外面套个Nginx+tls

好的，多谢啦
