### ISSUE TITLE
gofrp.org jquery bootstrap 导致页面访问慢 请更换国内cdn

### ISSUE THREAD

**Issue by xuntee** [fatedier/frp#1941]
gofrp.org jquery bootstrap 导致页面访问慢 请更换国内cdn

**Comment by BecodReyes** [comment]
打钱就有
能用就行，不要太挑剔

**Comment by fatedier** [comment]
jquery bootstrap 加载一次后应该都是有缓存的？

**Comment by fatedier** [comment]
看了下 jqeury 貌似被墙了，我把 jquery 放到到了网站本地，应该会好一些。
