### ISSUE TITLE
让frp流量走v2ray的通道，v2ray使用websocket伪装，超安全

### ISSUE THREAD

**Issue by limaofu** [fatedier/frp#1943]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by limaofu** [comment]
或者说，能否给frp的流量增加websocket伪装，我们指定它的tls证书，类似v2ray那样的，可以隐藏frp承载流量的协议特征。 对外表现为客户端frpc在访问frps端的某个https网站。

**Comment by fatedier** [comment]
frp 只是一个内网穿透项目，不涉及流量伪装和去特征等能力，如果有需要，可以结合其他工具使用。frp 本身不会内置这些能力。

在需要伪装的场景下，也请谨慎考虑使用，避免不必要的安全风险。

**Comment by limaofu** [comment]
明白了，功能简单反而稳定。目前的问题只有一个了：7000端口的token验证太简单了，需要提高安全性，比如frpc和frps之间 通信之前可用ssl证书进行验证，可为单向的证书，也可为双向的证书。类似openVpn的验证。

**Comment by fatedier** [comment]
这个还在开发，可以关注 https://github.com/fatedier/frp/pull/1918 这个 PR，预计下个版本可以加入。

**Comment by limaofu** [comment]
🤝握手
