### ISSUE TITLE
建议：http_proxy服务器失联时暂时不使用代理隧道/切换至备选代理服务器

### ISSUE THREAD

**Issue by Becods** [fatedier/frp#1947]
## 需求
http_proxy服务器断开时暂时不使用代理隧道，待proxy服务器恢复后重新使用
或
http_proxy多备选服务器，若均失联则不使用http_proxy

## 功能
1. 定期检测http_proxy服务器存活状态 (现貌似已有)
2. 若当前http_proxy服务器失联，则暂时禁用http_proxy/切换下一个http_proxy服务器
3. 待http_proxy服务器恢复后，则使用http_proxy (依优先级而定)

##使用场景
frps服务器连接质量差 (高丢包率，并不是完全不可用)，需要使用http_proxy减缓

**Comment by fatedier** [comment]
这个感觉是一种通用的需求。比较适合单独去实现一个这样的通用库，然后 frp 里可以 import ，不光支持 http proxy，也可以支持其他的代理类型。目前看上去优先级不高。

高丢包率可以考虑下开启 kcp。
