### ISSUE TITLE
关于cloudreve使用功能方面的一些建议

### ISSUE THREAD

**Issue by fuckxiaoo** [fatedier/frp#1948]
1.外部导入文件希望能够有撤回功能，或者是删除外部导入文件时有一个选择是否删除本地文件的选项，不然删除云盘文件时本地文件也会连带删除
2.希望能添加一个多选文件一键操作（分享链接）功能

**Comment by BecodReyes** [comment]
你好，这里是frp项目仓库
关于cloudreve的建议请提交到此：[cloudreve/Cloudreve](https://github.com/cloudreve/Cloudreve/issues)

**Comment by fuckxiaoo** [comment]
sorry 哈哈哈搞错了
