### ISSUE TITLE
希望尽快支持UDP打洞（两台设备P2P直连）

### ISSUE THREAD

**Issue by goer99** [fatedier/frp#195]
目前的转发模式效率比较低，如果是直连就好了。大量的UDP通信需要P2P直连，例如视频监控等等。希望能尽快实现，谢谢。

**Comment by fatedier** [comment]
这个不在近期的计划内，如果有需求推荐这个项目 [dog-tunnel](https://github.com/vzex/dog-tunnel)。

**Comment by goer99** [comment]
收到，谢谢

**Comment by goer99** [comment]
dog-tunnel并不完整，很不好用。还是等frp吧。

**Comment by fatedier** [comment]
那可能在两三个版本之后。
