### ISSUE TITLE
log or system time?

### ISSUE THREAD

**Issue by liiloo100** [fatedier/frp#1953]
Log and system time are different。

2020/08/22 23:59:44 [I] [proxy.go:82] [32555cbb75250a02] [3389] get a new work connection: [1.9.7.9:20907]
root@XiaoQiang:/tmp# date
Sun Aug 23 07:59:54 CST 2020

**Comment by liiloo100** [comment]
我的时间是北京时间，+8，我想FRP是不是能有一个时间设置，让他和我的时区是一样的

**Comment by liiloo100** [comment]
还有这个错误，每分钟要产生几个记录，我看以前有回答过，但我没有找到。
2020/08/26 09:38:41 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
2020/08/26 09:38:59 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
2020/08/26 09:39:03 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
2020/08/26 09:39:59 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
2020/08/26 09:40:05 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
2020/08/26 09:40:19 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
2020/08/26 09:41:11 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
2020/08/26 09:41:13 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
2020/08/26 09:41:33 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
2020/08/26 09:42:16 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
2020/08/26 09:42:25 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
2020/08/26 09:42:45 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
2020/08/26 09:43:23 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
2020/08/26 09:43:36 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
2020/08/26 09:43:56 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
2020/08/26 09:44:29 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]

**Comment by xqzr** [comment]
> 还有这个错误，每分钟要产生几个记录，我看以前有回答过，但我没有找到。
> 2020/08/26 09:38:41 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 2020/08/26 09:38:59 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 2020/08/26 09:39:03 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 2020/08/26 09:39:59 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 2020/08/26 09:40:05 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 2020/08/26 09:40:19 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 2020/08/26 09:41:11 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 2020/08/26 09:41:13 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 2020/08/26 09:41:33 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 2020/08/26 09:42:16 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 2020/08/26 09:42:25 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 2020/08/26 09:42:45 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 2020/08/26 09:43:23 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 2020/08/26 09:43:36 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 2020/08/26 09:43:56 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 2020/08/26 09:44:29 [I] [proxy.go:82] [90fc961ad823a73d] [188-3389] get a new work connection: [116.9.72.249:33419]
> 会不会是有人在攻击，或尝试密码

尝试密码无视就好 除非你端口不暴露在公网

**Comment by liiloo100** [comment]
终于找到原因了，我的ftpc是建立在Docker下面的，由于docker容器的时间是美国时间，所以Frpc就默认是容器的时间，现在把容器的时间改成shanghai时间就可以了
