### ISSUE TITLE
建议在配置文件里增加自定义“错误页面提示语”

### ISSUE THREAD

**Issue by benson-album** [fatedier/frp#1954]
现有错误页面提示语:
```
The page you requested was not found.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

The server is powered by frp.

Faithfully yours, frp.
```
中会留下服务器指纹，有一定的安全隐患。虽然可下载源码进行修改再编译，遇到版本升级却是不便，建议在配置文件中增加自定义项。

**Comment by BecodReyes** [comment]
建议不错
更新前推荐使用github action云编译

**Comment by fatedier** [comment]
Duplicate of https://github.com/fatedier/frp/issues/1624

**Comment by smallfish01** [comment]
目前临时解决办法是，修改/opt/frp/pkg/util/vhost/resource.go文件内容，然后再make一次即可。
