### ISSUE TITLE
功能需求：反向端口映射（服务端某功能端口映射到客户端监听）

### ISSUE THREAD

**Issue by Arthur2012** [fatedier/frp#1958]
场景：
3台主机，连接关系：A机（公网国内） <-> B机（私网） <-> C（公网国外）。其中B机私网有国内国外2个出口。C机上具有代理服务功能。
国内客户机M要访问海外网站N，即M->A->B->C->N

功能要求：
通常A机安装frps，B机安装2个frpc，C机安装frps。但目前只有frpc的端口映射到frps上，没有**端口反向映射**功能，造成C机代理服务端口无法传递到B机。所以**希望增加此功能**。不想用SSH port forwarding方法，或加装其它软件来实现。

临时措施：
目前解决B-C之间端口映射的workaround是B机上增加运行1个frps，C机上增加运行一个frpc，利用已有的B frpc -> C frps通道把B frps通信端口映射到C机，C机frpc再连本机这个端口(即到B frps)，把C代理功能端口映射到了B机某端口上。这个临时方法虽然可行，但看上去很不优美。

**Comment by fatedier** [comment]
目前没有这方面的计划，和现在的架构不同，强行加进来会显得比较奇怪，并且也有 stcp 这样的解决方案，并不是完全不能实现。可以等现有的功能完善了之后再来讨论这个问题。
