### ISSUE TITLE
客户端是否支持多个服务端

### ISSUE THREAD

**Issue by la0wei** [fatedier/frp#196]
服务端在国外，线路也不同，连接质量不稳定，想知道在客户端是否支持连接到多个服务端，这样可以自己选择质量较好的线路连接。
google了下，也看了issue，没有注意到有相关问题，特此提问。谢谢。

**Comment by la0wei** [comment]
sorry,刚刚找到解答了。
https://github.com/fatedier/frp/issues/140

**Comment by fatedier** [comment]
感觉这一类的需求不是很多，而且也可以通过起两个 frpc 连接不同的服务器来解决这个问题。

**Comment by la0wei** [comment]
@fatedier 看到客户端可以多开，这个问题就好解决了

**Comment by eddy0425** [comment]
我最近也遇到了这个问题，只能客户端多开了

**Comment by T-Atlas** [comment]
> 我最近也遇到了这个问题，只能客户端多开了

请问如何客户端多开，谢谢

**Comment by eddy0425** [comment]
> > 我最近也遇到了这个问题，只能客户端多开了
> 
> 请问如何客户端多开，谢谢

复制多几个文件夹，并且分配不同的参数就能多开了

![](https://easyimage1.ghuang.top/i/2024/04/18/090333-1.webp)
