### ISSUE TITLE
nohup方式启动frps，dashboard无记录

### ISSUE THREAD

**Issue by Arthur2012** [fatedier/frp#1960]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.33.0

**What operating system and processor architecture are you using (`go env`)?**
ubuntu 14.04.1

**Configures you used:**
[common]
bind_port = xxx
dashboard_port = yyy
dashboard_user = admin
dashboard_pwd = zzz
token = ***

**Steps to reproduce the issue:**
1. **nohup /usr/bin/frps -c /etc/frp/frps.ini >/dev/null 2>&1 &**
2. open web browser to check dashboard

**Describe the results you received:**
traffic in/out are always 0.

**Describe the results you expected:**
traffic in/out should be real value, not always 0.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
应该是nohup frps启动方式的原因，但如何解决呢？因为ubuntu 14.04下建立service(systemd)启动失败(CentOS7下是成功的)，用非nohup方式启动frps会在SSH断开后frps进程退出。

**Comment by HinxVietti** [comment]
建议检查下log看看客户端是否连接上了服务器, 或者防火墙是否开放.
先直接使用./frps -v ./frps.ini 运营测试OK了再进行操作.
后台运行建议:  nohup &配合使用
` nohup ./frp -c ./frp.ini & `
测试OK可以注册到系统服务替代nohup运行.
不介意你传个log一起看看发生了啥 :-)

**Comment by Arthur2012** [comment]
> 建议检查下log看看客户端是否连接上了服务器, 或者防火墙是否开放.
> 先直接使用./frps -v ./frps.ini 运营测试OK了再进行操作.
> 后台运行建议: nohup &配合使用
> `nohup ./frp -c ./frp.ini &`
> 测试OK可以注册到系统服务替代nohup运行.
> 不介意你传个log一起看看发生了啥 :-)

nohup /usr/bin/frps -c /etc/frp/frps.ini >/dev/null 2>&1 &
后台是运行成功的，frps工作正常，映射的端口工作正常，dashboard能打开，但流量始终是0字节。
services方式如果能成功，不会去用后台方式运行的。

**Comment by bingtianbaihua** [comment]
可以提供更多的日志看下， 目前盲猜也不知道是什么错误。

**Comment by mxdlzg** [comment]
我用centos7+service启动也没记录
