### ISSUE TITLE
是否支持代理多个HTTP端口

### ISSUE THREAD

**Issue by NGLSL** [fatedier/frp#1963]
外网服务器将不同的端口转发到内网服务器的端口，是否支持这么做？

文档里面没有说明是否支持多个端口

![image](https://user-images.githubusercontent.com/40338580/91791656-43591980-ec46-11ea-88ef-9b024197bb9b.png)

**Comment by fatedier** [comment]
HTTP 和 HTTPS 不支持，TCP 支持。
