### ISSUE TITLE
frps 端，如何查看frpc  连上来的ip?

### ISSUE THREAD

**Issue by matrix-core** [fatedier/frp#1964]
frps 端，如何查看frpc  连上来的ip?

**Comment by HinxVietti** [comment]
进入Dashboard, 查看链接情况, 或者看看log , 或服务端的bind port.

**Comment by BecodReyes** [comment]
https://github.com/fatedier/frp/issues/1130
>看起来并不是一个通用的需求，暂时不考虑加入。

**Comment by huanglvmin** [comment]
> 
> 
> frps 端，如何查看frpc 连上来的ip?

直接用系统自己的ss或者netstat看不就行了

**Comment by HinxVietti** [comment]
> 
> 
> frps 端，如何查看frpc 连上来的ip?

对于很多人来说, 客户端都是不固定ip的.  如果是自己的服务器, 完全可以写个服务,cs连接的时候,客户端往里面发请求数据就好了. 如果你想拒绝, 就刷新服务端配置文件就可以了.

**Comment by haiking419** [comment]
> frps 端，如何查看frpc 连上来的ip?

我也有同样的问题，既然frps admin页面可以查看已经建立的代理连接，为什么就不能支持查看确认具体的客户端IP

**Comment by haiking419** [comment]
> #1130
> 
> > 看起来并不是一个通用的需求，暂时不考虑加入。

我也有同样的问题，既然frps admin页面可以查看已经建立的代理连接，为什么就不能支持查看确认具体的客户端IP

**Comment by haiking419** [comment]
> > frps 端，如何查看frpc 连上来的ip?
> 
> 直接用系统自己的ss或者netstat看不就行了



> > frps 端，如何查看frpc 连上来的ip?
> 
> 直接用系统自己的ss或者netstat看不就行了

我的客户端比较多，不方便确认每个客户端分别映射了哪些端口
