### ISSUE TITLE
frp内网穿透的问题

### ISSUE THREAD

**Issue by yangyayu-last** [fatedier/frp#1965]
frp内网穿透，远程连接时，显示：此计算机无法连接到远程计算机。
客户端frp显示错误日志：2020/09/02 14:54:39 [E] [proxy.go:581] [f93d468f23aee706] [ssh] connect to local service [192.168.25.41:6002] error: dial tcp 192.168.25.41:6002: connectex: No connection could be made because the target machine actively refused it.

**Comment by HinxVietti** [comment]
你的服务器是: 192.168.25.41 ? 局域网内吗?
请确认一下内容:

- 可以ping通192.168.25.41
- 服务端已经开启
- 服务端端口已经开放(防火墙)

**Comment by yangyayu-last** [comment]
> 
> 
> 你的服务器是: 192.168.25.41 ? 局域网内吗?
> 请确认一下内容:
> 
>     * 可以ping通192.168.25.41
>        公网服务器是ping不通内网的
>     * 服务端已经开启
>         服务端开启了
>     * 服务端端口已经开放(防火墙)
            防火墙已经关闭

**Comment by HinxVietti** [comment]
> 
> 
> > 你的服务器是: 192.168.25.41 ? 局域网内吗?
> > 请确认一下内容:
> > ```
> > * 可以ping通192.168.25.41
> >    公网服务器是ping不通内网的
> > * 服务端已经开启
> >     服务端开启了
> > * 服务端端口已经开放(防火墙)
> > ```
> 
> ```
>         防火墙已经关闭
> ```

我是说你内网要ping得到外网啊; 
192.168.25.41 这个机子拒绝了链接,  如果你是A机器替B机器代理到服务器C, 那你就要确保, AB 和AC都是可以互通的.
放配置文件出来看看吧

**Comment by yangyayu-last** [comment]
> 
> 
> > > 你的服务器是: 192.168.25.41 ? 局域网内吗?
> > > 请确认一下内容:
> > > ```
> > > * 可以ping通192.168.25.41
> > >    公网服务器是ping不通内网的
> > > * 服务端已经开启
> > >     服务端开启了
> > > * 服务端端口已经开放(防火墙)
> > > ```
> > 
> > 
> > ```
> >         防火墙已经关闭
> > ```
> 
> 我是说你内网要ping得到外网啊;
> 192.168.25.41 这个机子拒绝了链接, 如果你是A机器替B机器代理到服务器C, 那你就要确保, AB 和AC都是可以互通的.
> 放配置文件出来看看吧

都是可以互通的。请求已经从内网A服务，经过云服务器，到了内网B服务，内网B服务，frc控制台显示不能连接自己的6002端口，被拒绝。此时内网A 服务远程桌面连接显示【此计算机无法连接到远程计算机】

**Comment by HinxVietti** [comment]
你是不是AB两个机子都绑定服务器的6002端口啊?

**Comment by yangyayu-last** [comment]
> 
> 
> 你是不是AB两个机子都绑定服务器的6002端口啊?

不是，问题已经解决了。
解决方法：AB内网服务器的端口，本地端口只能绑定3389，其他端口无效

**Comment by HinxVietti** [comment]
囧 我还以为你改了注册表默认的远程端口, 你这样很容易被扫描吧, 一般开放的机器都不使用默认端口, 建议改掉3389 .
那你上方报错应该就是远程的对象6002端口没有被绑定监听了.

无意外可以关闭这个issue了 |ू･ω･` )

**Comment by yangyayu-last** [comment]
> 
> 
> 囧 我还以为你改了注册表默认的远程端口, 你这样很容易被扫描吧, 一般开放的机器都不使用默认端口, 建议改掉3389 .
> 那你上方报错应该就是远程的对象6002端口没有被绑定监听了.
> 
> 无意外可以关闭这个issue了 |ू･ω･` )

是的，搞忘了，没用过这个，还以为是其它原因，谢谢啦
