### ISSUE TITLE
[control.go:177] [c545b8079b8375a0] [rdp] start error: port unavailable

### ISSUE THREAD

**Issue by a1542360** [fatedier/frp#1967]
frp版本:frp_0.33.0_windows_amd64
frpc.ini配置：

[rdp]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 7080

本机防火墙已关闭，同事电脑使用内网ip直接windows远程工具能连上我电脑，但是使用frpc -c frpc.ini命令启动客户端时提示：
[control.go:177] [c545b8079b8375a0] [rdp] start error: port unavailable

**Comment by BecodReyes** [comment]
https://github.com/fatedier/frp/issues/1239
请善用搜索
调整max_pool_count或allow_ports
