### ISSUE TITLE
建议添加gui，纯配置的对于小白来讲还是稍显复杂了。

### ISSUE THREAD

**Issue by xxl-cc** [fatedier/frp#1970]
nps用过，感觉nps适合有自己的主机的情况，而frp更适合普罗大众，如果能加上gui配置管理就更好了。

**Comment by fatedier** [comment]
目前没有太多精力做这个事情，frp 的定位还是一个提供丰富能力的工具，提供更多的扩展能力给需要定制，有特殊需求的用户。据我了解，阿里和微软都有通过修改代码在自己的项目中使用，微软也将部分修改反馈给了社区。

易用性，GUI 等直接面向希望开箱即用的用户来说比较重要，这方面可能花生壳之类的成熟产品是更好的选择。以后如果我有足够的空闲时间，或者有这方面的专家愿意贡献自己的力量，会在这一方面投入更多的精力。

**Comment by QQ2017** [comment]
> nps用过，感觉nps适合有自己的主机的情况，而frp更适合普罗大众，如果能加上gui配置管理就更好了。

其实就是改下配置文件，稍微学下编程吧。

**Comment by zhaokai5520** [comment]
圈内人都不需要gui吧
