### ISSUE TITLE
Wrong TimeZone/TimeStamp in LogFile at Android/iOS Platform

### ISSUE THREAD

**Issue by Droid-MAX** [fatedier/frp#1972]
https://github.com/golang/go/issues/20455

**Comment by fatedier** [comment]
Thanks for your report. It seems not fixed by golang. Keep this issue open to track this issue.

**Comment by Droid-MAX** [comment]
建议更新到go1.15以上版本

**Comment by fatedier** [comment]
The issue is not closed. Are you sure go1.15 fixed this?

**Comment by Droid-MAX** [comment]
还没，不过可以测试一下这个方法看看
import _ "time/tzdata"
-tags timetzdata

**Comment by fatedier** [comment]
It will increase the compiled binary file size, it maybe not worth to do so.

**Comment by Droid-MAX** [comment]
好像这么做并不能解决问题
