### ISSUE TITLE
how to ban client?

### ISSUE THREAD

**Issue by burkifaso** [fatedier/frp#1976]
I'm using frp as a http proxy client in my proxy software , client is setup as http proxy (using proxy plugin) and then connect to the server

how to ban client if he does not share his internet connection as a http proxy ? how to detect it at the server side and ban IP without ability to connect to the server next time?

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/dev/doc/server_plugin.md

You can write your own plugin to ban client that you don't allowed.

**Comment by burkifaso** [comment]
it will be hard since I have never coded in golang..

**Comment by fatedier** [comment]
You can write plugin with any language, frp will call this plugin by HTTP.
