### ISSUE TITLE
Multi Tenant problem

### ISSUE THREAD

**Issue by northerndeveloper** [fatedier/frp#1977]
hello

I am having difficulties with multi tenants at FRP . I am using the latest version of FRP.

Does FRP supports Multi Tenancy and do you have a documentation for that ?

Thank you for your kindest helps.

Best Regards

**Comment by fatedier** [comment]
You can try this plugin https://github.com/gofrp/fp-multiuser

It's based on [server plugin](https://github.com/fatedier/frp/blob/master/doc/server_plugin.md) feature.
