### ISSUE TITLE
multi tenant problem about multiple remote ports

### ISSUE THREAD

**Issue by northerndeveloper** [fatedier/frp#1978]
Hello

I already asked a question about FRP supports Multi Tenant problem and I was told yes it does by the plugin fp-multiuser. But there is still a problem that **we have to make sure if one customer can only access one remote port**.  It seems that every customer should have the same remote port which is not good for security.

So we need to know if one customer can access to one customer with fp-multiuser plugin ? IF not , is there any extra plugin or way to accomplish this ?

Thank you for your kindest helps.

Regards
Alper

**Comment by fatedier** [comment]
There are no such plugin now. But you can write your own plugin with any language.

https://github.com/fatedier/frp/blob/master/doc/server_plugin.md

**Comment by northerndeveloper** [comment]
Hello

Thank you for your answer

In order to clarify it, it means it supports multi tenant with one remote port. Every customer will have only one remote port.

But it can support multiple remote port as well as we need to make a development and create a plugin for it or may be we have to extend the plugin frp_multiser ? 

Thank you for your helps

**Comment by fatedier** [comment]
@northerndeveloper Write your own plugin is a good idea.
