### ISSUE TITLE
http header的自定义字段是否支持动态内容呢？

### ISSUE THREAD

**Issue by hr0109** [fatedier/frp#1979]
比如nginx反向代理，是支持将$host作为自定义header的内容的，请问frp目前是否具有类似的功能呢？

**Comment by bingtianbaihua** [comment]
![image](https://user-images.githubusercontent.com/4812302/93034801-e14cdb00-f66d-11ea-9727-c58a76fd6a0b.png)

**Comment by bingtianbaihua** [comment]
https://gofrp.org/docs/features/http-https/header/

**Comment by hr0109** [comment]
> https://gofrp.org/docs/features/http-https/header/

请注意是**动态**内容
比如我用127.0.0.1访问，这个字段就是127.0.0.1。我用外网ip访问，那这个字段就应该是对应的外网ip。而不是一直不变的frp或者其它什么。
有一些服务器需要根据自定义字段返回资源的绝对url，静态的header内容无法兼容不同来源（内网、外网）的访问请求

**Comment by bingtianbaihua** [comment]
![image](https://user-images.githubusercontent.com/4812302/93042904-e5cfbe80-f682-11ea-84ea-0feabb6e8d78.png)

这个勒 ？

**Comment by fatedier** [comment]
@hr0109 这是一个相对来说复杂的 HTTP server 的需求，建议在前面挡一层 nginx 来实现此能力。
