### ISSUE TITLE
OpenWrt15.05 ar71xx应该使用哪个版本？

### ISSUE THREAD

**Issue by Anyfc** [fatedier/frp#198]
下载了最新的frp_0.9.0_linux_mips.tar.gz 无论是输入 ./frpc_linux_mips -h  还是./frpc_linux_mips -c ./frpc.ini 都提示 Illegal instruction ，
而下载frp_0.9.0_linux_mipsle.tar.gz ，输入./frpc_linux_mipsle: line 1: syntax error: unexpected "("
时则提示 ./frpc_linux_mipsle: line 1: syntax error: unexpected "("

**Comment by fatedier** [comment]
具体我不是很了解，mips 是 32 位的，如果是 64 位系统的就用 mips64，是否有 le 取决于系统是大端还是小端模式。

**Comment by lotc** [comment]
@Anyfc ar71xx 是另外一种架构，不可使用 mips 版本，需要另外编译。

**Comment by Anyfc** [comment]
@lotc 搜了一圈好像ar71xx的很多都不能正常的运行mips，需要重新编译，
https://github.com/xtaci/kcptun/issues/308

**Comment by fatedier** [comment]
应该目前 go1.8 对 mips 的支持还不是很好，有 bug 吧。

**Comment by lotc** [comment]
在 AR7161 的平台上测试了一下
mips 是 `Illegal instruction`
mipsle 是 `./frpc: line 1: syntax error: unexpected "("`

**Comment by Anyfc** [comment]
@lotc 提示 Illegal instruction 好像是因为内核中没有开启FPU
这个教程是这样说的： http://iytc.net/wordpress/?p=1564

**Comment by lotc** [comment]
@Anyfc 我这里测试的是 frps, 不是 kcptun.

**Comment by Anyfc** [comment]
@lotc 我刚编译了个OpenWrt15.05 ar71xx可用的frpc
你试试
https://pan.baidu.com/s/1dFcIWUH 密码: 4fvz

**Comment by lotc** [comment]
可以运行.
最好给出编译的环境和步骤, 这样也方便作者和其他用户自行修正.

**Comment by Anyfc** [comment]
@lotc  @fatedier 
根据搜索到的资料，在运行时提示：  Illegal instruction  是因为内核中没有开启FPU 

这个时候可以用gomini编译，我的编译系统是debian7.5 64位

步骤：
编译go-mips32

`git clone https://github.com/gomini/go-mips32.git
cd go-mips32/src
export GOOS=linux
export GOARCH=mips32
./make.bash`

下载frp

`git clone https://github.com/fatedier/frp.git
cd frp`

保存下面的命令到build.sh，运行成功即可在bin目录看到frpc

`#GOROOT指向编译完成的go-mips32代码
export GOPATH=~/go-mips32/src/gocode
export GOOS=linux
export GOARCH=mips32
export GOROOT=~/go-mips32
export PATH=~/go-mips32/bin:$PATH

go get -v  github.com/docopt/docopt-go
go get -v  github.com/fatedier/frp/src/models/client
go get -v  github.com/fatedier/frp/src/utils/log
go get -v  github.com/fatedier/frp/src/utils/version
go get -v  github.com/mitchellh/gox
go get -v  github.com/rakyll/statik

go fmt ./src/...
go fmt ./test/echo_server.go
go fmt ./test/http_server.go
go fmt ./test/func_test.go
go build -o bin/frps ./src/cmd/frps
go build -o bin/frpc ./src/cmd/frpc
go build -o test/bin/echo_server ./test/echo_server.go
go build -o test/bin/http_server ./test/http_server.go`

参考：http://www.jianshu.com/p/e6e354cd7bc1
          http://www.jianshu.com/p/e83223af906a

**Comment by lotc** [comment]
@Anyfc 编译完 go-mips32 后 /bin 只有 gofmt
平台 Ubuntu 16.04 x32
先用你的好了.
