### ISSUE TITLE
关于frps TCP问题

### ISSUE THREAD

**Issue by sleepyeyes79** [fatedier/frp#1980]
大神你好，frpc客户端太多而导致tcp连接太慢甚至too many  files错误，同时http连接稳定正常。请问有没有办法在frps服务器端只开放指定客服端的tcp连接。这样我们每次操作只tcp连接需要操作的那几个客服端就好？谢谢！

Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
[端口白名单](https://gofrp.org/docs/features/common/server-manage/#%E7%AB%AF%E5%8F%A3%E7%99%BD%E5%90%8D%E5%8D%95)

或者通过 [服务端插件](https://gofrp.org/docs/features/common/server-plugin/) 的功能自己开发插件来实现自己所需的定制化能力。
