### ISSUE TITLE
关于映射网站子目录的问题

### ISSUE THREAD

**Issue by umeoy** [fatedier/frp#1981]
我安装了frp在我的树莓派和服务器上并成功启用，但我在配置内网82端口映射到服务器8080端口时，发现了一个问题，当我访问 域名:8080/ng时，网页显示找不到界面
以下为配置文件

frps
[common]
bind_port = 7000
vhost_http_port = 8080

[web]
type = http
local_port = 82
custom_domains = 域名

我想在公网访问树莓派上的 82端口下的ng目录(内网路径http://树莓派IP:82/ng)，应该怎样设置?

**Comment by bingtianbaihua** [comment]
你访问服务器的路径 URL 是啥？

**Comment by rorizhang** [comment]
你试试最后加一个/试试。
