### ISSUE TITLE
0.33版本stcp模式下，如何设置代理节点上限（总数）？

### ISSUE THREAD

**Issue by ivanhxq** [fatedier/frp#1982]

**Comment by bingtianbaihua** [comment]
没太明白意思， 可以描述的详细点？

**Comment by ivanhxq** [comment]
![image](https://user-images.githubusercontent.com/11866438/93159800-99978380-f741-11ea-9f5d-cbe0cd0cc127.png)



如图，希望设置Proxy Counts为固定某个数据，或者通过其他方式限制代理节点数量也行。

应用场景：
在有限带宽的frps服务器下，限制frpc  在sctp模式下过多frpc代理节点连接frp，防止过度连接导致服务器过载。

**Comment by bingtianbaihua** [comment]
这个需求可以用端口白名单来做。 或者自己根据 frps 的服务端插件，自己去实现。 frps 与 plugin 的通信协议已定，是走 http。 具体你可以看下文档。

**Comment by bingtianbaihua** [comment]
https://github.com/fatedier/frp/issues/1976 @ivanhxq  参考这个。
