### ISSUE TITLE
frp代理插件无法使用

### ISSUE THREAD

**Issue by magellan-99** [fatedier/frp#1983]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frp_0.33.0_linux_arm
frp_0.33.0_windows_amd64

**What operating system and processor architecture are you using (`go env`)?**
utermux、windows10（防火墙全部关闭，路由器设置端口转发）

**Configures you used:**
frps：
[common]
bind_port = 7000

frpc:
[common]
server_addr = 公网地址
server_port = 7000

[plugin_http_proxy]
type = tcp

plugin = http_proxy
plugin_http_user = abc
plugin_http_passwd = abc
remote_port = 20524

[plugin_socks5]
type = tcp
remote_port = 6005
plugin = socks5
plugin_user = abc
plugin_passwd = abc

**Steps to reproduce the issue:**
1.代理设置为：127.0.0.1:20524
2.Edge访问结果：dial tcp: lookup www.baidu.com on [::1]:53: read udp [::1]:37250->[::1]:53: read: connection refused
3.

**Describe the results you received:**
frps:
2020/09/15 16:56:39 [I] [proxy.go:103] [7bbe1e9edfa8ccda] [plugin_http_proxy] get a new work connection: [手机IP:21753]

**Describe the results you expected:**
我想用手机流量做一个代理服务器

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by magellan-99** [comment]
在手机端安装privoxy再使用frpc加上local_port，这种方法就可以做代理访问网站。但是privoxy不能设置用户名和密码，麻烦。请大神们看看我哪里设置错了？

**Comment by bingtianbaihua** [comment]
我理解你的 frps 是放在手机端？ 然后 frpc 是在某个内网的服务？ 你想用手机的 ip 去访问内网的服务？

**Comment by magellan-99** [comment]
> 我理解你的 frps 是放在手机端？ 然后 frpc 是在某个内网的服务？ 你想用手机的 ip 去访问内网的服务？

windows端是frps、手机端是frpc

**Comment by bingtianbaihua** [comment]
可以提供更丰富的日志？ 目前来看比较难以确定哪里的问题。

**Comment by magellan-99** [comment]
没问题，请问如何看日志？要frps还是frpc？

**Comment by bingtianbaihua** [comment]
> 没问题，请问如何看日志？要frps还是frpc？

都提供吧，主要是报错的那行日志，还有上下 10-20 行日志。

**Comment by magellan-99** [comment]
> > 没问题，请问如何看日志？要frps还是frpc？
> 
> 都提供吧，主要是报错的那行日志，还有上下 10-20 行日志。

我已经找到问题原因了，是手机防火墙阻止了端口，请问如何设置frpc的http_proxy插件的端口？

**Comment by bingtianbaihua** [comment]
> > > 没问题，请问如何看日志？要frps还是frpc？
> > 
> > 
> > 都提供吧，主要是报错的那行日志，还有上下 10-20 行日志。
> 
> 我已经找到问题原因了，是手机防火墙阻止了端口，请问如何设置frpc的http_proxy插件的端口？

建议自己看文档，文档已经写的很全了。
