### ISSUE TITLE
可以自己整一个GUI界面吗

### ISSUE THREAD

**Issue by sbchong** [fatedier/frp#1984]
使用了一下内网穿透代理，体验很好，想借着搞一个GUI来进一步简化配置并分发给朋友用，看了一下开源许可是Apache的，那表明这应该是可以的吧😀

**Comment by bingtianbaihua** [comment]
可以， 可以提个 proposal， 看下你的设计，给作者等几个人 review 下？

**Comment by bingtianbaihua** [comment]
https://github.com/fatedier/frp/issues/1970
