### ISSUE TITLE
login to server failed: EOF

### ISSUE THREAD

**Issue by xueyuanl** [fatedier/frp#1986]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.33.0/ 0.33.0

**What operating system and processor architecture are you using (`go env`)?**
service: centOS x86_64(VPS on linode in Japan)
client: macOS i386 (macbook pro catalina, zsh)

**Configures you used:**
service: one VPS server on linode, base in Japan.
```
[common]
bind_port = 7000
```

client: macbook in china mainland 电信 (actually I still tried on a raspberry pi with same comfig)

```
[common]
server_addr = x.x.x.x
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_post = 22
remote_port = 6000
```

**Steps to reproduce the issue:**
1. config as above
2.run `./frps -c frps.ini `on server side
3.run `.frpc -c frpc.ini `on client side

**Describe the results you received:**
```
[W] [service.go:101] login to server failed: EOF
```

**Describe the results you expected:**
run success

**Additional information you deem important (e.g. issue happens only occasionally):**
`I tried it on my private LAN, this can work. So obviously, this is not the problem of the software itself.`

telnet result:
```
$: telnet x.x.x.x 7000
Trying x.x.x.x
Connected to x
Escape character is '^]'.
Connection closed by foreign host.
```
And I just search on google and baidu, found lots of solution but did not work for me,
for example:
[记一次frp的被阻断的问题](https://blog.phpgao.com/frp_tcp_reset.html)
[issue 1249 frpc提示login to server failed: EOF](https://github.com/fatedier/frp/issues/1249)
[issue 1836 疑似被局域网禁用连接](https://github.com/fatedier/frp/issues/1836)

or some solution did not work because of the older version like this,
[issue 810](https://github.com/fatedier/frp/issues/810)
[frp启动报错“[W] [control.go:113] login to server failed: EOF”](https://www.codeleading.com/article/53751252444/)

**Can you point out what caused this issue (optional)**
我个人觉得和国内的防火墙有关，希望有类似问题的同学给点意见。
I suspect that this problem is related to the china GFW.
Yes, this is not an issue, but I still hope someone can help me on this.

Thanks

**Comment by bingtianbaihua** [comment]
可以尝试开启下 kcp看下效果。

**Comment by bingtianbaihua** [comment]
或者开下 tls 试试。 后续应该会支持自定义的 tls config https://github.com/fatedier/frp/pull/1974

**Comment by xueyuanl** [comment]
> 可以尝试开启下 kcp看下效果。

server side:
```
[common]
bind_port = 7000
kcp_bind_port = 7000
```
client side:
```
[common]
server_addr = x.x.x.x
server_port = 7000
protocol = kcp

[ssh]
type = tcp
local_ip = 127.0.0.1
local_post = 22
remote_port = 6000
```

error 报错：
`[service.go:101] login to server failed: i/o deadline reached`

但局域网测试依然可以。

**Comment by xueyuanl** [comment]
> 或者开下 tls 试试。 后续应该会支持自定义的 tls config #1974

add `tls_enable = true` in client's (or in both server and client side) `common` section, still does not work.

get error: `[service.go:101] login to server failed: session shutdown`

**Comment by bingtianbaihua** [comment]
frpc 和 frps 的日志可以多提供一点。

**Comment by jaredyam** [comment]
一模一样的问题，请问解决了吗？

**Comment by xueyuanl** [comment]
> 一模一样的问题，请问解决了吗？

还没有解决 : (
still not figure it out

**Comment by mouyong** [comment]
注释掉 server 端的插件，然后用 frps_full.ini 启动，客户端就可以连接了。

@xueyuanl @jaredyam

**Comment by trulyliu** [comment]
`authentication_method = token`

注意server端的这个选项

**Comment by progerchai** [comment]
> `authentication_method = token`
> 
> 注意server端的这个选项

在frps_full.ini 中这个默认是开启的，和楼上的相同没有解决

**Comment by jackxuexue** [comment]
亲测：frpc.ini 加上  tls_enable = true 即可
`[common]
server_addr = 47.106.182.221
server_port = 7000
tls_enable = true

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000`
版本：frp_0.38.0_linux_amd64

**Comment by bithaoya** [comment]
具体看这篇博客https://blog.phpgao.com/frp_tcp_reset.html
你的网络可能把frp屏蔽了，换0.25.0以上的frp，开通tls传输
