### ISSUE TITLE
stcp sk with special char auth fail

### ISSUE THREAD

**Issue by HinxVietti** [fatedier/frp#1987]
```
#client a
[stcp-ssh]
type = stcp
sk = user@192.x.x.x
local_ip = 192.168.x.x
local_port = 22

#client b visitor
[stcp-ssh]
type = stcp
role = visitor
server_name = stcp-ssh
sk = user@192.x.x.x
bind_ip = 127.0.x.x
bind_port = xxxx
```

auth failed while visitor start connect to frps;

> #change sk to another plain string like 'abcdef'
> sk = qwert

√ connection pass.

Please update docs or make sure config with special chars not effect task running.

**Comment by bingtianbaihua** [comment]
I will try it to test.

**Comment by bingtianbaihua** [comment]
When I use  sk = !@#$%^&*() ， it also be trully work.  And I read the code, it may be your config is wrong ?
Please show me how to reproduce this problem.

**Comment by HinxVietti** [comment]
> When I use sk = !@#$%^&*() ， it also be trully work. And I read the code, it may be your config is wrong ?
> Please show me how to reproduce this problem.

老哥是中国的? 请稍待, 我再测试一波. 可是无疑问当时是改了sk之后就可以正常运行了的.

**Comment by HinxVietti** [comment]
> When I use sk = !@#$%^&*() ， it also be trully work. And I read the code, it may be your config is wrong ?
> Please show me how to reproduce this problem.

不好意思, 我的锅, 经过多次尝试和交叉替换配置, 这些特殊字符都是可以正常使用的. 那次可能是偶然原因导致了这个问题

**Comment by bingtianbaihua** [comment]
> > When I use sk = !@#$%^&*() ， it also be trully work. And I read the code, it may be your config is wrong ?
> > Please show me how to reproduce this problem.
> 
> 老哥是中国的? 请稍待, 我再测试一波. 可是无疑问当时是改了sk之后就可以正常运行了的.

恩，中国土著
