### ISSUE TITLE
window10系统下frpc.exe运行时会被联想自带的McAfee给kill掉

### ISSUE THREAD

**Issue by xiong114** [fatedier/frp#1989]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.31.2

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**
frpc config
   [common]
    server_addr = xxxx
    server_port = 9090
   log_file = ./frpc.log
   log_level = debug
   token = xxxxx
  [web]
   type = https
   local_ip = 127.0.0.1
   local_port = 8070
   remote_port =  9090
   subdomain = mmm

**Steps to reproduce the issue:**
1.联想自带的杀毒软件默认运行
2.启动frpc进程，运行一会就会被kill掉（最近才出来，以前相同环境没有被杀掉）
3.提示PUP/Frproxy.a有威胁
 
![1600411959(1)](https://user-images.githubusercontent.com/61447115/93566219-47fc2c80-f9bf-11ea-9fb8-a59e7d1bc885.png)

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
其他杀毒软件没有问题（卡巴、360等）

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
白名单 or 卸载杀毒软件 or 不使用 frpc。

**Comment by kktt007** [comment]
> 白名单 or 卸载杀毒软件 or 不使用 frpc。

白名单和卸载都不行，mcafee是域管理员部署的，只能临时禁用几分钟，有其他方案吗
