### ISSUE TITLE
不能创建2个ssh代理么？

### ISSUE THREAD

**Issue by loveFeng** [fatedier/frp#199]
用最新版本 服务端设了2个ssh 代理，第一个可以。第二个连不上，只能代理一个么？

**Comment by fatedier** [comment]
可以，连不上的那个可以看下是否是 #193 中同样的问题。

**Comment by loveFeng** [comment]
今天重新试验了一下,可以连接2个ssh了.但是不知道之前是什么原因(没有保存当时的log),可能是网络问题或者路由器转发问题
