### ISSUE TITLE
frp被上级网络监控识别流量并封杀端口

### ISSUE THREAD

**Issue by DingdingLuan** [fatedier/frp#1992]
呜呜呜   frp使用了encrypt 依旧还是能被识别出来 ，单位禁止这种穿透服务，内网ban了我好几次了，有没有啥办法解决呀

**Comment by BecodReyes** [comment]
https://github.com/fatedier/frp/blob/1e420cc7667397082109571560fadd82b85fa9d6/models/msg/msg.go#L64-L194

特征基本上均在这里，自己修改打包一下应该就可以使用了

**Comment by fatedier** [comment]
建议不要在公司禁止的情况下使用，安全风险和后果需要自负。

**Comment by DingdingLuan** [comment]
> https://github.com/fatedier/frp/blob/1e420cc7667397082109571560fadd82b85fa9d6/models/msg/msg.go#L64-L194
> 
> 特征基本上均在这里，自己修改打包一下应该就可以使用了

谢谢谢谢

**Comment by DingdingLuan** [comment]
> 建议不要在公司禁止的情况下使用，安全风险和后果需要自负。

好- - 谢谢
