### ISSUE TITLE
Windows10客户端无法启动

### ISSUE THREAD

**Issue by luoyu124578** [fatedier/frp#1996]
![SharedScreenshot](https://user-images.githubusercontent.com/44193242/93709996-8a676a00-fb75-11ea-87f1-a79427ac9295.jpg)
如图 无论是0.27版还是0.34版，都无反应

**Comment by luoyu124578** [comment]
> ![共享屏幕截图](https://user-images.githubusercontent.com/44193242/93709996-8a676a00-fb75-11ea-87f1-a79427ac9295.jpg)
> 如果曾经是0.27版还是0.34版，都无反应

![SharedScreenshot2](https://user-images.githubusercontent.com/44193242/93710051-05c91b80-fb76-11ea-948c-65a9d32c795e.jpg)

**Comment by bingtianbaihua** [comment]
检查一下 frps 是否启动了， 配置文件是否配对了。 日志级别调整到 trace 看下错误。

**Comment by luoyu124578** [comment]
frps已启动，相同配置文件相同版本的情况下，有的电脑能够启动并连接成功，有的电脑无法启动
![FZFF@_I6%`D_0X9W(TPS45U](https://user-images.githubusercontent.com/44193242/93732395-b16c7d00-fc03-11ea-94dd-552acf23efa2.png)
。

**Comment by bingtianbaihua** [comment]
> frps已启动，相同配置文件相同版本的情况下，有的电脑能够启动并连接成功，有的电脑无法启动.
> ![b76a170a0b4335b384e6e1ac9cd24d7](https://user-images.githubusercontent.com/44193242/93732461-04463480-fc04-11ea-8846-2bb8f6793fc2.png)
> 成功的页面
> ![FZFF@_I6%`D_0X9W(TPS45U](https://user-images.githubusercontent.com/44193242/93732395-b16c7d00-fc03-11ea-94dd-552acf23efa2.png)

那看下不能成功的电脑网络配置，是否跟成功的电脑有差别。

**Comment by bingtianbaihua** [comment]
这种有的能成功， 有的不能成功这种大概率不是 frp 的问题， 需要自己去定位或者提供更多丰富的信息。

**Comment by fatedier** [comment]
检查日志配置，确认是不是日志转存到其他路径了。

**Comment by luoyu124578** [comment]
[service.go:102] login to server failed: dial tcp 49.102.206.109:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 
端口已经开放，仍无法连接，是否是网络问题
