### ISSUE TITLE
映射微软rdp服务时可以使用域名访问吗？

### ISSUE THREAD

**Issue by justcode288** [fatedier/frp#1999]
今天第一次使用frp，感觉很好用！

我家里电信宽带，有公网ip，但是是动态的，并且已通过QNAP实现了DDNS域名解析。
我单位有一台windows桌面版，均没有公网ip。
我需要在单位外面用微软rdp(域名+端口号)连接单位的windows桌面。

我按网上的教程，在家里openwrt路由器搭建了frps，在单位openwrt路由器搭建了frpc，并成功实现在单位外通过公网ip地址+端口号访问单位的机器。

但问题是我家里的公网ip是动态的，ip变了之后，需要重新配置单位frpc配置文件的服务器ip。我看到网上的subdomain都是用于web服务，没有看到域名用于微软rdp服务的，我自己尝试了几次没有成功，请问大佬我该如何操作呢？

**Comment by justcode288** [comment]
已解决。

**Comment by saixin** [comment]
> 已解决。

哥们，怎么解决的？我也遇到这个问题了

**Comment by justcode288** [comment]
有人问我是怎么解决的，我回复一下：
按照没有域名只有ip地址的教程正常配置好frps和frpc，假如此时你已经可以使用ip地址+端口号使用微软rdp服务访问内网windows主机了；然后配置好ddns，意思是让你的动态公网ip有一个固定的域名(我使用阿里云的ddns因为快、稳定)，这时你就可以使用域名+端口号使用微软rdp服务了。就这么简单。
