### ISSUE TITLE
开启tls only失败，读取证书问题

### ISSUE THREAD

**Issue by limaofu** [fatedier/frp#2000]
C:\Users\Administrator\Documents\frp_0.34.0_windows_amd64>frpc.exe -c frpc.ini

2020/09/22 09:53:17 [W] [service.go:102] login to server failed: x509: certificate 
relies on legacy Common Name field, use SANs or temporarily enable 
Common Name matching with GODEBUG=x509ignoreCN=0

x509: certificate relies on legacy Common Name field, use SANs or temporarily
enable Common Name matching with GODEBUG=x509ignoreCN=0

**Comment by limaofu** [comment]
客户端：
[common]
server_addr =s.qq.com
server_port = 9833
token = 18xxxx6xx
tls_enable = true
tls_cert_file = c.qq.com.crt
tls_key_file = c.qq.com.key
tls_trusted_ca_file = frp_ca.crt

[testTls]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 9844

**Comment by limaofu** [comment]
0.34.0的新版本，

**Comment by limaofu** [comment]
客户端证书
![image](https://user-images.githubusercontent.com/54393027/93838006-c9530800-fcba-11ea-9c42-a87c4b36ab41.png)

**Comment by limaofu** [comment]
证书都是v3的版本，客户端和服务端的证书都是由同一ca去签名的。客户端本地也做了hosts指向s.qq.com到服务端ip，但服务端没有指向c.qq.com到客户端ip,因为客户端没有公网ip

**Comment by bingtianbaihua** [comment]
这个我测试下。

**Comment by bingtianbaihua** [comment]
可以提供下 frps 的日志。

**Comment by limaofu** [comment]
客户端日志：
 [W] [service.go:102] login to server failed: x509: certificate
relies on legacy Common Name field, use SANs or temporarily enable
Common Name matching with GODEBUG=x509ignoreCN=0

x509: certificate relies on legacy Common Name field, use SANs or temporarily
enable Common Name matching with GODEBUG=x509ignoreCN=0

**Comment by fatedier** [comment]
@limaofu 执行 frpc 的时候加上提示的环境变量吧，`GODEBUG=x509ignoreCN=0`，这个是 go1.15 的变化。`relies on legacy Common Name field` 这个方式后面会逐渐废弃。

**Comment by fatedier** [comment]
@yuyulei

**Comment by limaofu** [comment]
OK了，加了环境变量名GODEBUG值为x509ignoreCN=0然后就行了。
![image](https://user-images.githubusercontent.com/54393027/93840699-e213eb80-fcc3-11ea-9be1-e135ff11b92d.png)
不过要求使用证书里的域名，然后不是真实的域名的话，要在本地添加hosts文件解析

**Comment by fatedier** [comment]
@limaofu 恩，这个问题我们再看一下，感觉可能是之前签证书的方法不规范，在新版本 go 里面开始不支持了。

**Comment by zzustu** [comment]
![2020-09-22-134803_844x265_scrot](https://user-images.githubusercontent.com/17822281/93847716-45107d00-fcda-11ea-869a-e071123e63b5.png)
如果不配环境变量，自签证书，怎么签才不报错呀

**Comment by yuyulei** [comment]
CommonName 在 2000 年的时候已经开始废弃。RFC 6125 把 CommonName 作为一个可选项，关于使用方式详见：https://tools.ietf.org/html/rfc6125#section-6.4.4，与之前 go 版本处理方式是一致的。如果生成证书的时候没有提供其他Identity信息（比如说，DNS-ID, SRV-ID, URI-ID等），最后会选取 CommonName。

但是在最新 1.15 版本里面，官方正式废弃了 CommonName，也正是因此出现了上述报错。

`
x509: certificate relies on legacy Common Name field, use SANs or temporarily
enable Common Name matching with GODEBUG=x509ignoreCN=0
`
最简单的解决办法就是生成 SAN 证书， 可参考：http://liaoph.com/openssl-san/，这里就不展开了。

剩下做了些 SAN 的调研：

- SAN 作为一个扩展， 现在已经普及了，当今正常机构发布的实际上都是 SAN 证书。

- 从技术观点上看，一般 CA 要求 CommonName 添加到 SAN 里。换言之，没有 SAN 的证书在实际**正式**场景下是非法证书。详见：https://support.dnsimple.com/articles/what-is-ssl-san/


稍后，我们会在文档中心给一个证书生成示例。

**Comment by zzustu** [comment]
> CommonName 在 2000 年的时候已经开始废弃。RFC 6125 把 CommonName 作为一个可选项，关于使用方式详见：[https://tools.ietf.org/html/rfc6125#section-6.4.4，与之前](https://tools.ietf.org/html/rfc6125#section-6.4.4%EF%BC%8C%E4%B8%8E%E4%B9%8B%E5%89%8D) go 版本处理方式是一致的。如果生成证书的时候没有提供其他Identity信息（比如说，DNS-ID, SRV-ID, URI-ID等），最后会选取 CommonName。
> 
> 但是在最新 1.15 版本里面，官方正式废弃了 CommonName，也正是因此出现了上述报错。
> 
> `x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0`
> 
> 1. 临时方案是配置环境变量  GODEBUG=x509ignoreCN=0
> 2. 推荐解决办法就是生成 SAN 证书， 可参考：[http://liaoph.com/openssl-san/，这里就不展开了。](http://liaoph.com/openssl-san/%EF%BC%8C%E8%BF%99%E9%87%8C%E5%B0%B1%E4%B8%8D%E5%B1%95%E5%BC%80%E4%BA%86%E3%80%82)
> 
> 稍后，我们会在文档中心给一个证书生成示例。

NICE

**Comment by yuyulei** [comment]
文档链接：https://gofrp.org/docs/features/common/network/network-tls/

**Comment by limaofu** [comment]
![image](https://user-images.githubusercontent.com/54393027/93972898-d862b480-fda5-11ea-825d-37e5580c6bfd.png)
使用了带san扩展的证书后，去掉GODEBUG环境变量，也成功了
