### ISSUE TITLE
Frpc will be killed in windows 10 2004

### ISSUE THREAD

**Issue by minskiter** [fatedier/frp#2003]
![image](https://user-images.githubusercontent.com/23184022/93890307-cb4db300-fd1c-11ea-99bb-ac2a4ddd174e.png)

**Comment by limaofu** [comment]
Holy win 10 shit

**Comment by bingtianbaihua** [comment]
https://github.com/fatedier/frp/issues/1989

**Comment by bingtianbaihua** [comment]
try to close the firewall.

**Comment by minskiter** [comment]
https://s.tencent.com/research/report/1060.html

**Comment by fatedier** [comment]
> 腾讯安全威胁情报中心检测到针对MSSQL服务器攻击的挖矿木马，该挖矿木马主要针对MS SQL服务进行爆破弱口令攻击，爆破成功后会植入门罗币挖矿木马进行挖矿。同时攻击者下载frpc内网穿透工具安装后门，并会添加用户以方便入侵者远程登录该服务器。

你贴的新闻，翻译一下，是因为 MSSQL 弱口令，导致被攻击者植入木马，攻击者会下载 frpc 工具来做远程控制。

攻击者下载的 frpc 没有被查杀，可能是做过了加壳等其他消除特征的处理。

从 github 下载的 frpc，是原生 go 编译的二进制文件，没有做过特殊处理，如果被查杀，建议:
1. 添加白名单。
2. 不使用 frpc。
3. 自己从源码编译。

是否报毒取决于 go 编译的一些行为特征，windows 平台的二进制也是在 linux 平台上交叉编译出来。这一类问题之后不会再继续回复。

**Comment by huruka** [comment]
备注：自带防火墙（Windows 安全中心）添加白名单
病毒和威胁防护 - 管理设置 - （下滚）添加或删除排除项 - 添加排除项

**Comment by ckmark** [comment]
自己编译防止被查杀的话，具体需要增加什么编译选项么？还是直接下源码来编译就行？

**Comment by yzkj-tom** [comment]
自己编译的没有问题, 从release 下载的会报毒
