### ISSUE TITLE
FRPC_v0.34.0_反向代理发出故障

### ISSUE THREAD

**Issue by gbh19930406** [fatedier/frp#2007]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.34.0

**What operating system and processor architecture are you using (`go env`)?**

Linux arm64 & Windows amd64

**Configures you used:**

I used http and stcp to make the connect, it works perfect with FRPC 0.33.0

**Steps to reproduce the issue:**

1. Upgrade frps from 0.33.0 to 0.34.0
2. Upgrade frpc from 0.33.0 to 0.34.0
3. Failed to use rdp and http to make the connect
4. Downgrade frpc from 0.34.0 to 0.33.0
5. Succeed to use rdp and http to make the connect

**Describe the results you received:**

With FRPS 0.34.0 & FRPC 0.34.0

1. RDP with internal error
2. HTTP with error as well

With FRPS 0.34.0 & FRPC 0.33.0

Error Not found

**Describe the results you expected:**

Fix the issue of FRPC 0.34.0 cannot transfer the proxy data 

**Additional information you deem important (e.g. issue happens only occasionally):**

FRPC file size about 0.34.0 is smaller than 0.33.0

**Can you point out what caused this issue (optional)**

Unknown root cause of this issue, may be changed or replaced or missed some core functions between these two versions.

**Comment by bingtianbaihua** [comment]
please show more logs.

**Comment by gbh19930406** [comment]
Hello, below is the error which shows on FRPC v0.34.0.

work connection write to server error: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config

**Comment by gbh19930406** [comment]
Seems I must be specific a Cert and Key in it. There has no default Cert and Key inside of Client 0.34.0, am I right?

**Comment by fatedier** [comment]
Please follow the issue template to paste your configrues so others can reproduce your problem.
