### ISSUE TITLE
frpc cannot connect, log as  "send Login request to plugin error"

### ISSUE THREAD

**Issue by MicyToy** [fatedier/frp#2011]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.34.0

**What operating system and processor architecture are you using (`go env`)?**
Server is CentOS 7.8
Client Windows 10

**Configures you used:**
frps.ini

**Steps to reproduce the issue:**
1. Configure a server listen on 7000, check 7000 is open.
2. Configure a client web
3. 

frps.ini
bind_addr = 0.0.0.0
bind_port = 7000
kcp_bind_port = 7000
[plugin.user-manager]
addr = 127.0.0.1:9000
path = /handler
ops = Login

[plugin.port-manager]
addr = 127.0.0.1:9001
path = /handler
ops = NewProxy

**Describe the results you received:**
 [E] [service.go:279] send Login request to plugin error
 [W] [service.go:102] login to server failed: send Login request to plugin error
send Login request to plugin error

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
Try this simple configures: https://github.com/fatedier/frp#access-your-computer-in-lan-by-ssh

**Comment by MicyToy** [comment]
It worked, and also I can add "token" . It seems like the "plugin" issue.

**Comment by fatedier** [comment]
You can find how to use plugins on https://github.com/fatedier/frp/blob/dev/doc/server_plugin.md

**Comment by khs1994** [comment]
`frps.ini` 中的 plugin 相关配置注释掉，因为你没有启动插件，所以 frps 连接不到插件，就报错了。

```ini
#[plugin.user-manager]
#addr = 127.0.0.1:9000
#path = /handler
#ops = Login

#[plugin.port-manager]
#addr = 127.0.0.1:9001
#path = /handler
#ops = NewProxy
```

**Comment by MicyToy** [comment]
Thanks to @khs1994 , comment it and it worked.
Might add plugin configuration before `[plugin.user-manager]`, or comment it as default.
For user first use might be more kindly.

**Comment by fatedier** [comment]
@MicyToy Follow the document, not the full example configure file.
