### ISSUE TITLE
Configuration to disable system proxy

### ISSUE THREAD

**Issue by zssng** [fatedier/frp#2012]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.34.0

**What operating system and processor architecture are you using (`go env`)?**
 Windows 10 2004

**Configures you used:**
[RDP3] 
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 7002

**Steps to reproduce the issue:**
1. start frpc before login
2. frpc use system proxy but system proxy not start until user logged in

**Describe the results you received:**
2020/09/28 11:09:43 [W] [service.go:102] login to server failed: dial tcp 127.0.0.1:57890: connectex: No connection coul
d be made because the target machine actively refused it.
dial tcp 127.0.0.1:57890: connectex: No connection could be made because the target machine actively refused it.

**Describe the results you expected:**
Is there any configuration  can ignore system proxy setting ?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by bingtianbaihua** [comment]
you can try to login to server by http_proxy or other proxy, if your system proxy is http_proxy ？

**Comment by BecodReyes** [comment]
[#Connecting to frps via HTTP PROXY](https://github.com/fatedier/frp#connecting-to-frps-via-http-proxy)
Please use the http_proxy that comes with the frpc
