### ISSUE TITLE
能否提供一种通道能力，连接上之后可以双向的访问。

### ISSUE THREAD

**Issue by xiaofeige** [fatedier/frp#2015]
client 连接上 server打通了通道之后，visitor 和source角色感觉不是很重要。我这边倒是有个场景，client连接上server之后，需要互相访问对方的资源。
通道打通之后，双方的角色都退化为一个agent，可以互相访问对方的资源。

**Comment by fatedier** [comment]
你的需求，在需要互相访问的客户端上安装 frpc 分别启动 STCP 模式的访问端和服务端的代理可以实现一样的效果。

frps 从设计的安全角度来说不会提供暴露自身网络访问的能力。
