### ISSUE TITLE
Can we merge the multiple line log into just one?

### ISSUE THREAD

**Issue by return2alfred** [fatedier/frp#2017]
Dear @fatedier:

```
> Please have a look at this common log format below:
> # Sep 30 06:34:59 HOSTNAME frps[713]: 2020/09/30 06:34:59 #033[1;34m[I] [service.go:432] [a0fbd19ad1ff876f]  client login info: ip [xxx:xxx:xxx:xxx:7853] version [0.30.0] hostname [] os [windows] arch [amd64]#033[0m
> # Sep 30 06:34:59 HOSTNAME frps[713]: 2020/09/30 06:34:59 #033[1;33m[W] [service.go:334] register control error: token in login doesn't match token from configuration#033[0m
> # Sep 30 06:34:59 HOSTNAME frps[713]: 2020/09/30 06:34:59 #033[1;34m[D] [service.go:405] Accept new mux stream error: EOF#033[0m
```

The original log event gives the same time label, and if we can merge the 3 lines log into just one, we can make debug much more accurate.
And expecially for integration like fail2ban would be much easier, in terms of the log parse feature provided by such programs.

Would this be a good advise?
Thank you!

**Comment by fatedier** [comment]
It's logged in different functions, we can't merge it into one. 

You'd better not rely on logs.
