### ISSUE TITLE
v0.34.1 没有发布各个CPU 架构的软件包？

### ISSUE THREAD

**Issue by snowdream** [fatedier/frp#2019]
v0.34.1 没有发布各个CPU 架构的软件包？

**Comment by BecodReyes** [comment]
可以自行编译
嫌麻烦请用回v0.34.0

**Comment by snowdream** [comment]
这...

**Comment by aueu** [comment]
> 可以自行编译
> 嫌麻烦请用回v0.34.0

你的意思是，后面不在提供各平台的二进制文件了？

**Comment by BecodReyes** [comment]
> > 可以自行编译
> > 嫌麻烦请用回v0.34.0
> 
> 你的意思是，后面不在提供各平台的二进制文件了？

并无此意
请勿以一概全
也许只是这次发布匆忙来不及/忘记提供
具体还是要看fatedier

**Comment by MvsCode** [comment]
> > > 可以自行编译
> > > 嫌麻烦请用回v0.34.0
> > 
> > 
> > 你的意思是，后面不在提供各平台的二进制文件了？
> 
> 并无此意
> 请勿以一概全
> 也许只是这次发布匆忙来不及/忘记提供
> 具体还是要看fatedier

可以用GitHub Action 编译吗

**Comment by hanjianwei** [comment]
是否考虑用[GoReleaser + Github Actions自动发布](https://goreleaser.com/ci/actions/)？

**Comment by fatedier** [comment]
已添加，后面会尝试使用 Github Actions。
