### ISSUE TITLE
frpc私有模式，配置服务器端口已被占用，仍旧正常启动的问题

### ISSUE THREAD

**Issue by chmis8000** [fatedier/frp#202]
frpc配置比如：
[common]
server_addr = *******

[5062245541A]
local_port=7789
remote_port =80
privilege_mode = true
use_gzip = true

如上，远程端口80是被占用的，但frpc仍旧正常启动，无任何错误。最新0.9版，我记得0.7版都能报错退出的。

**Comment by fatedier** [comment]
很奇怪，release 里下载的确实有问题，不过我重新编译出来的程序是正常的，我把 0.9.1 重新编译一遍再上传新的你再试试。
