### ISSUE TITLE
frp服务端管理界面反代出错

### ISSUE THREAD

**Issue by yaott2020-666** [fatedier/frp#2020]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.34.0

就是无法反代dashboard，会出错404

**Comment by BecodReyes** [comment]
请提供相应的配置及logs

提问不截图，你我都糊涂，截图截一半，神仙都难办

**Comment by yaott2020-666** [comment]
用的是宝塔面板frp插件

配置放百度盘，全是图片

链接：https://pan.baidu.com/s/10dWqeLSuRPUl128bxEBspw 
提取码：6ycb 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by BecodReyes** [comment]
宝塔问题，不建议使用宝塔

具体问题疑似为宝塔反代至frps:7500/frps
自己重写下反代配置
```
location /frps/ {
	proxy_http_version 1.1;
	proxy_set_header Host $host;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
	proxy_pass http://127.0.0.1:7500/;
}
```

**Comment by yaott2020-666** [comment]
测试不通过，还是会url指向错误，本来想把管理界面和web一同放在一个站点的反代，行不通，只能设置另外一个站点独立反代dashboard
