### ISSUE TITLE
[W] [service.go:102] login to server failed: dial tcp 127.0.0.1:7000: connect: connection refused

### ISSUE THREAD

**Issue by danielpmc** [fatedier/frp#2021]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.34.0

**What operating system and processor architecture are you using (`go env`)?**
Linux Debian 9, AMD64

**Configures you used:**
example one in readme

**Steps to reproduce the issue:**
1. Follow steps on readme https://github.com/fatedier/frp/blob/dev/README.md#access-your-computer-in-lan-by-ssh

**Describe the results you received:**
[W] [service.go:102] login to server failed: dial tcp 127.0.0.1:7000: connect: connection refused
dial tcp 127.0.0.1:7000: connect: connection refused

**Describe the results you expected:**
to connect. (Done configs correctly)

**Comment by BecodReyes** [comment]
The problem cannot be judged according to the content provided
More profiles required

**Please check that the firewall / port is unobstructed**

**Comment by ChiragSukhala** [comment]
Please ssh on frps machine and do
`curl 127.0.0.1:7000`

if they output is same 
```
'[W] [service.go:102] login to server failed: dial tcp 127.0.0.1:7000: connect: connection refused
dial tcp 127.0.0.1:7000: connect: connection refused'
```
 its an issue with FRP otherwise as @BecodReyes  said your firewall / port is unobstructed.

**Comment by bingtianbaihua** [comment]
nc -zv 127.0.0.1  7000 

to check the port is active.

**Comment by sqvictory** [comment]
I solved this problem after downloading Go with: `apt-get install gccgo-go`

**Comment by mkamalkayani** [comment]
> I solved this problem after downloading Go with: `apt-get install gccgo-go`

@sqvictory  Where did you install the Go package, on the client or server?

**Comment by sqvictory** [comment]
> > I solved this problem after downloading Go with: `apt-get install gccgo-go`
> 
> @sqvictory Where did you install the Go package, on the client or server?

both

**Comment by Yunuuuu** [comment]
the same problem, and gccgo-go didn't solved it

**Comment by Yunuuuu** [comment]
I just tested the raw file, I downloaded frp file in https://github.com/fatedier/frp/releases/download/v0.35.1/frp_0.35.1_linux_arm64.tar.gz and uncompressed it, then I run 
```
/frpc -c /frpc.ini
```
it gave this error
```
[W] [service.go:103] login to server failed: dial tcp 127.0.0.1:7000: connect: connection refused
```
and I also tested frp version 0.35.0, the same error returned.

my OS version is here
```
Linux version 5.8.0-44-generic (buildd@lgw01-amd64-054) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021
```
I also tried apt-get install gccgo-go, and the go version is below
```
go version go1.12.2 gccgo (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 linux/amd64
```

the error remained here after installing go

**Comment by Parmicciano** [comment]
I'm experiencing the same problem, have you found a solution since ?

**Comment by fleame** [comment]
> Delete the annotation and space after the script "server_addr = nas.frpxx.com **# 服务器IP或者地址**"

yes! this works for me.

**Comment by beautyhansonboy** [comment]
> 我已经关闭防火墙了
> 
> ```
> sudo ufw status
> 
> Status: inactive
> ```
> 
> 我刚刚测试了原始文件，我在https://github.com/fatedier/frp/releases/download/v0.35.1/frp_0.35.1_linux_arm64.tar.gz下载了frp文件并解压缩，然后运行
> 
> ```
> /frpc -c /frpc.ini
> ```
> 
> 它给出了这个错误
> 
> ```
> [W] [service.go:103] login to server failed: dial tcp 127.0.0.1:7000: connect: connection refused
> ```
> 
> 我还测试了frp版本0.35.0，返回了相同的错误。
> 
> 我的操作系统版本在这里
> 
> ```
> Linux version 5.8.0-44-generic (buildd@lgw01-amd64-054) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021
> ```
> 
> 我也尝试了 apt-get install gccgo-go，go 版本如下
> 
> ```
> go version go1.12.2 gccgo (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 linux/amd64
> ```
> 
> 安装go后，错误依然存在
I also encountered this problem on the Linux system. How can I solve it
2024/01/10 09:46:34 [W] [service.go:132] login to server failed: dial tcp 44.237.78.176:7000: connect: connection refused

**Comment by beautyhansonboy** [comment]
> Please ssh on frps machine and do `curl 127.0.0.1:7000`
> 
> if they output is same
> 
> ```
> '[W] [service.go:102] login to server failed: dial tcp 127.0.0.1:7000: connect: connection refused
> dial tcp 127.0.0.1:7000: connect: connection refused'
> ```
> 
> its an issue with FRP otherwise as @BecodReyes said your firewall / port is unobstructed.

How was it resolved in the end
