### ISSUE TITLE
binaries for 0.34.1 are missing

### ISSUE THREAD

**Issue by liranms** [fatedier/frp#2022]
The binaries for 0.34.1 is missing from the release page - the expected link also does not exist: 
https://github.com/fatedier/frp/releases/download/v0.34.1/frp_0.34.1_linux_amd64.tar.gz

**Comment by ChiragSukhala** [comment]
:+1:  +1 I was looking for linux_amd64 && linux_arm.
Please add build instructions to doc :smile:

**Comment by BecodReyes** [comment]
https://github.com/fatedier/frp/issues/2019

Maybe it's just this release that you forgot to provide

You can compile it yourself

**Comment by fatedier** [comment]
@liranms @ChiragSukhala Thanks for you feedback. I have upload the binary files.
