### ISSUE TITLE
请教一下，请问是否支持 socket.io 服务的代理？

### ISSUE THREAD

**Issue by linwenchao** [fatedier/frp#2026]
客户端与服务器的 socket.io 服务连接，直连应用服务或者用Nginx代理时正常成功连接，
加上 frp 后一直失败，无论是 frp 反代到 Nginx 或者直接反代到应用服务器都无法成功。

> 经测试，socket.io连接时只使用polling进行握手能成功，使用websocket就会失败

frpc / frps 均是最新 0.34 版本

frps 跑在 Ubuntu，frpc 跑在Mac（也有其它Go应用在跑）

**Comment by linwenchao** [comment]
单独设了一个tcp端口供websocket握手，问题解决

**Comment by chengfeng311** [comment]
能详细讲下配置吗？最近也碰到了这个问题 @linwenchao
