### ISSUE TITLE
能否把配置写到命令行里而不是单纯写在文件里，方便其他语言调用？

### ISSUE THREAD

**Issue by 1021683053** [fatedier/frp#203]
我想用node去调用，必须生成一个.ini配置文件这样尤其麻烦，当一个ndoe服务硬性两个frp服务，就需要生成两份！如果终止服务还需要删除文件！
能不能方便扩展一点！
比如 frp --server=127.0.0.1 --port=333 这种方式！
（我感觉不能，因为噢诶之文件里的信息太多，能不能给我一个好一点的替代方案）

**Comment by fatedier** [comment]
命令行会支持一些基本的功能，优先级应该不是太高。

**Comment by 1021683053** [comment]
哦哦那只能生成缓存文件了

**Comment by fatedier** [comment]
你这样的需求应该比较少…

**Comment by 1021683053** [comment]
![image](https://cloud.githubusercontent.com/assets/7711802/21541034/852f2068-cdee-11e6-95a8-6dd7f8e20d61.png)
能不能把这些状态码，列出来，方便正则匹配，判断运行状态！

**Comment by fatedier** [comment]
根据日志来判断不是很好，日志内容随时可能会更改。你需要判断的运行状态是指进程是否正常，还是每一个 proxy 的状态信息？

**Comment by 1021683053** [comment]
进程是否正常，或者说是否可用的状态!没事不用了，我做个简单的用用就OK了！

**Comment by 1021683053** [comment]
其实想做一个NPM使用的，
功能项做成自动下载最近的版本，切换版本，Gulp前端开发时调用，命令行根据json文件启动，在加上进程监控工具，防止进程终止！
我是做前端的，系统一块不是很熟！

**Comment by fatedier** [comment]
v0.17.0 版本优化了命令行参数，可以不使用配置文件运行。
运行状态可以通过 api 接口在 frpc 端获取。
