### ISSUE TITLE
安全地暴露内网服务能否通过配置IP来保证安全？

### ISSUE THREAD

**Issue by WuDg** [fatedier/frp#2030]
前言：我比较喜欢内网穿透带来的前后端接口测试便利，尤其是不在同一局域网时
问题：希望能通过在服务端配置IP限制，来保证内网服务的安全性
目前解决方案：暂时你们提供的方案是对应机器也需要安装frp客户端才能保证内网服务安全
不足：个人感觉比较麻烦，毕竟内网穿透是个人提供的一种接口测试解决方案，强加对方也要安装这个客户端会很尴尬。

希望大佬能听到我的声音，感谢。

**Comment by BecodReyes** [comment]
按照题主的理解应该是 只允许白名单ip访问 吧
这项可以通过配置防火墙实现

**Comment by WuDg** [comment]
> 
> 
> 按照题主的理解应该是 只允许白名单ip访问 吧
> 这项可以通过配置防火墙实现

这样就涉及到云主机层面了，感觉可以在frp另加一个ip限制来解决这个问题，这样会更加便捷轻量吧，个人感觉

**Comment by BecodReyes** [comment]
防火墙不涉及云主机
需求也许会被驳回或者列为低优先级，请悉知

**Comment by fatedier** [comment]
@WuDg 这方面的需求，后续都会考虑通过服务端插件的方式来支持，目前已有的一些插件 https://github.com/gofrp/plugin

这里有一个第三方开发的插件可以支持类似 IP 过滤的需求： https://github.com/zfb132/frp_info

frp 自身的核心代码不会再引入过多的这一类的能力，而是更多的以框架的形式来提供基础能力，通过插件来完善整体生态和满足部分用户的定制化需求。
