### ISSUE TITLE
A problem about "kex_exchange_identification: Connection closed by remote host"

### ISSUE THREAD

**Issue by xiaohan23** [fatedier/frp#2031]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.30.0

**What operating system and processor architecture are you using (`go env`)?**
Linux

**Configures you used:**
normal

**Describe the results you received:**
When I run ssh, the result is that "kex_exchange_identification: Connection closed by remote host". How could I solve this problem?

**Comment by BecodReyes** [comment]
Unable to determine the problem, please provide the implementation process.
In addition, FRP will not modify the traffic
