### ISSUE TITLE
新功能建议：请增加类似linux的hotplug热插拔功能

### ISSUE THREAD

**Issue by tinyfen** [fatedier/frp#2032]
建议增加类似openwrt中hot plug那样的功能，比如当客户端上线或下线时可以执行外部脚本的功能。谢谢

**Comment by BecodReyes** [comment]
使用场景？
此外更适合的解释应该为“钩子”

**Comment by fatedier** [comment]
同 @BecodReyes 的说法，可以通过 https://gofrp.org/docs/features/common/server-plugin/ 服务端插件来实现你所需要的能力。
