### ISSUE TITLE
[plugin_socks5] control connection closed

### ISSUE THREAD

**Issue by ffcommax** [fatedier/frp#2033]
Server:
[common]
server_addr = 0.0.0.0
bind_port = 443

Client:
[common]
server_addr = serverip
server_port = 443

[plugin_socks5]
type = tcp
remote_port = 6005
plugin = socks5

**info log**

frps tcp listen on 0.0.0.0:443
start frps success
client login info: ip [:65384] version [0.34.1] hostname [] os [windows] arch [amd64]
control writer is closing
client exit success
client login info: ip [:65384] version [0.34.1] hostname [] os [windows] arch [amd64]
control writer is closing
client exit success

**debug log:**

client login info: ip [:65384] version [0.34.1] hostname [] os [windows] arch [amd64]
control connection closed
control writer is closing
client exit success
Accept new mux stream error: read tcp :443->:65408: read: connection reset by peer
client login info: ip [:65384] version [0.34.1] hostname [] os [windows] arch [amd64]
control connection closed
control writer is closing
client exit success
Accept new mux stream error: read tcp :443->:65408: read: connection reset by peer

**Comment by fatedier** [comment]
Can you show logs in frpc?
