### ISSUE TITLE
使用frp0.33版本， 在设置use_compression = true后 ，限速不准

### ISSUE THREAD

**Issue by ivanhxq** [fatedier/frp#2034]
使用frp0.33版本， 在设置use_compression = true后 ，限速不准，工作在sctp模式， 配置为1280KB,即10Mbps，但使用iperf跑流出来的速度不是10Mbps，远高过10Mbps；在设置use_compression = false就在预期限速范围内

**Comment by BecodReyes** [comment]
use_compression会压缩流量，stcp仅限速压缩后的流量，实际解压后流量速度会大于限速，请悉知

**Comment by ivanhxq** [comment]
> use_compression会压缩流量，stcp仅限速压缩后的流量，实际解压后流量速度会大于限速，请悉知
能在发送端压缩前或者在接收端解压后限速吗？

**Comment by BecodReyes** [comment]
> > use_compression会压缩流量，stcp仅限速压缩后的流量，实际解压后流量速度会大于限速，请悉知
> > 能在发送端压缩前或者在接收端解压后限速吗？

请问你的需求是？
个人认为这样没有必要

**Comment by ivanhxq** [comment]
> > > use_compression会压缩流量，stcp仅限速压缩后的流量，实际解压后流量速度会大于限速，请悉知
> > > 能在发送端压缩前或者在接收端解压后限速吗？
> 
> 请问你的需求是？
> 个人认为这样没有必要
我这边应用有点特殊：流量速度过大导致CPU使用过高，从而导致流量上下波动很多，很不稳定，所以想进行限速，从而把CPU使用率降下来。

**Comment by BecodReyes** [comment]
> > > > use_compression会压缩流量，stcp仅限速压缩后的流量，实际解压后流量速度会大于限速，请悉知
> > > > 能在发送端压缩前或者在接收端解压后限速吗？
> > 
> > 
> > 请问你的需求是？
> > 个人认为这样没有必要
> > 我这边应用有点特殊：流量速度过大导致CPU使用过高，从而导致流量上下波动很多，很不稳定，所以想进行限速，从而把CPU使用率降下来。

应该是性能很低的CPU才会有这种顾忌吧
建议还是将压缩关闭
压缩解压过程中需要占用CPU
压缩占用的量会比大流量占用高是正常的
