### ISSUE TITLE
frps crashing, freezing when 300 + clients connected

### ISSUE THREAD

**Issue by jembem** [fatedier/frp#2036]
frps crashing when there is 300 - 400 + and more clients connecting to frps

I'm using vps with 1 GB of RAM

all clients got enabled http proxy plugin

I have specified in frps config max_pool_count=100000, because there is alot of connections is it good ?

why it is crashing ?

and when there is not specified max_pool_count in frps config then I'm unable to connect with client proxies

if 50 - 100 clients are connected then all seems to working good, but when 300 + clients are connected then it crashing or it is not possible to connect.

**Comment by halk947** [comment]
"By default, frps creates a new frpc connection to the backend service upon a user request. With connection pooling, frps keeps a certain number of pre-established connections, reducing the time needed to establish a connection."

**Comment by fatedier** [comment]
1. Do not set too many pool count.
2. Monitor your VPS for cpu and memory info.

**Comment by nlvedwin** [comment]
hi @fatedier do you think frps can take thousands of clients? but of course with good server specs.

**Comment by fatedier** [comment]
> hi @fatedier do you think frps can take thousands of clients? but of course with good server specs.

Yes.

**Comment by landrix** [comment]
What are good server specs for 300+ clients?

**Comment by fatedier** [comment]
> What are good server specs for 300+ clients?

@landrix This is difficult to estimate, I suggest you actually test it. 300 clients with empty loads cannot be compared to 300 clients with full loads.
