### ISSUE TITLE
在特权模式下多个vhost端口如何配置

### ISSUE THREAD

**Issue by idoall** [fatedier/frp#204]
在frps，中如果设置多个vhost_http_port的话，只有最后一个起作用
而在frpc使用特权模式，有多个站点时，无法分配不同的端口号。

比如，期望在一个frpc中，即可配置a.xx.com:80访问，又可以配置a.xx.com:5000访问到另外一个地址

**Comment by fatedier** [comment]
vhost 的作用就是使不同的域名可以共用同一个 80 端口对外提供服务，会根据域名路由到后端不同的服务。

你的这个需求可以使用 tcp 类型，不需要使用 vhost。

**Comment by idoall** [comment]
使用tcp的话，整个frpc都出问题了，请帮忙看下我的配置是否有问题
[web01]
privilege_mode = true
type = tcp
local_ip = 172.17.0.10
local_port = 5000
use_encryption = true
use_gzip = true
custom_domains = a.xx.com

下面是frpc的日志错误信息
2016/12/29 07:09:32 [client.go:42] [E] ProxyName [a.xx.com], connect to local port error, dial tcp 172.17.0.10:5000: getsockopt: no route to host
2016/12/29 07:10:11 [client.go:42] [E] ProxyName [a.xx.com], connect to local port error, dial tcp 172.17.0.10:5000: getsockopt: no route to host

**Comment by fatedier** [comment]
frpc 所在服务器无法连接到 172.17.0.10，另外 tcp 类型不用配 custom_domains。

**Comment by idoall** [comment]
如果不配置TCP是http的话是可以连接的，看来TCP是不起作用

**Comment by fatedier** [comment]
你配置中是 web01，日志里是 a.xx.com，这个配置是否有问题？
