### ISSUE TITLE
能否添加frpc向frps反向注册端口的功能？

### ISSUE THREAD

**Issue by badgv** [fatedier/frp#2040]
添加开关允许frpc将自己端口往frps所在的网络环境转发
在自己控制的frps和frpc的环境状态下，也不存在其它安全性问题

**Comment by BecodReyes** [comment]
https://github.com/fatedier/frp/issues/1958

>目前没有这方面的计划，和现在的架构不同，强行加进来会显得比较奇怪，并且也有 stcp 这样的解决方案，并不是完全不能实现。可以等现有的功能完善了之后再来讨论这个问题。
