### ISSUE TITLE
希望server端增加一个本地http反代功能

### ISSUE THREAD

**Issue by woshiniming007** [fatedier/frp#2042]
例如
bind_port=7000
vhost_https_port=443

但是我这个server自己也有一个nginx的服务在443

目前我是通过nginx->frp c->frp s的方法实现
但是经过这么多层转发性能可能会下降，而且需要本地额外启动一个frp c。

能否在frp s上直接集成一个反代功能？根据域名分流到本地nginx的流量。

**Comment by BecodReyes** [comment]
建议直接使用nginx代理frps的https流量
有合适的替代方法可能会导致该issue被列为低优先级甚至被驳回

>frp 自身的核心代码不会再引入过多的这一类的能力，而是更多的以框架的形式来提供基础能力，通过插件来完善整体生态和满足部分用户的定制化需求

>从我个人的角度而言，这个阶段不太希望引入各种琐碎的 feature，很容易让项目成为一个大杂烩，既提高开发者的维护成本，也增加了用户的使用成本。最终某些功能可能只有几个人使用，甚至没有人用，但是持续的维护却需要耗费很多精力。

>所以，目前可能更多的是希望做减法，专注核心能力，做一些重构。之后能通过插件的方式开放更多的扩展能力出来，可以由有需求的人来完善。

**Comment by fatedier** [comment]
你说的不就是 haproxy/nginx 的功能吗？
