### ISSUE TITLE
Just a quick question if possible, thank you for writing this excellent code.

### ISSUE THREAD

**Issue by jreiners** [fatedier/frp#2043]
Hello, just a quick general question, how is it handled if 

OTHERPC-A  & ClientB | server

I've got it all working great for localhost ports on ClientB

if I wanted to host OTHERPC-A:8080 over client b's config, is this possible?

I tried setting `local_ip = OTHERPC-A's` IP and it didn't seem to work for me. I looked at the go source a bit, was just curious if possible without adding a socat on localhost forwarding to OTHERPC-A?

**Comment by kingwilliam** [comment]
If you use same config file (just changed local ip) the "remote port" will conflict at server side(like ftp port 21, you can crwate ftp server at pcA and pcB but server side only 1 port 21)

**Comment by fatedier** [comment]
You should make sure ClientB can connect to OTHERPC-A:8080.

**Comment by jreiners** [comment]
@fatedier clientb can access otherpc-a:8080 no problem, they are behind the same firewall at that location, and on the same subnet, I ended up adding a temporary localhost port forward for 127:0.0.1:8080 >> otherpc-a:8080 and it worked, but I'd like to have frp just connect to the other host which would skip a step in setup for a bunch of users, and I could get rid of a bunch of services.

You have a great program, with a really nice interface thank you.

**Comment by jreiners** [comment]
So local_ip can be other-machine-a's ip if it's on the same network?

**Comment by fatedier** [comment]
Follow the issue template to show more info?
