### ISSUE TITLE
Windows Defender 报毒Worm:Win32/Yuner.A

### ISSUE THREAD

**Issue by oO0oO0oO0o0o00** [fatedier/frp#2046]
**What version of frp are you using (./frpc -v or ./frps -v)?**
`.\frpc.exe -v` 0.33.0

**What operating system and processor architecture are you using (`go env`)?**
Windows 10 2004  
Not using Golang

**Steps to reproduce the issue:**
1. `frpc -c frpc.ini`;
2. Created startup shortcut in `shell:startup`;
3. It ran for ~1 month and eventually got deleted by Windows Defender.

**Describe the results you received:**
Detected as `Worm:Win32/Yuner.A`

**Describe the results you expected:**
N/A

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Can you point out what caused this issue (optional)**
Microshit is a piece of soft.

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/issues/1204

**Comment by devmolv** [comment]
同0.33版本报毒，exe文件被删除了

**Comment by ErixWong** [comment]
Operation System Edition: Windows 10 Pro
Operation System Version: 2004 (OS Build 19041.572)
Security Intelligence update: 11/2/2020
Threats: Worm:Win32/Yuner.A

**Comment by wuqiangcpp** [comment]
same problem.

**Comment by SuperXiaoxiong** [comment]
I also met the problem 
maybe the us-cert report https://us-cert.cisa.gov/ncas/analysis-reports/ar20-259a

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/issues/2003
https://github.com/fatedier/frp/issues/1989
https://github.com/fatedier/frp/issues/1829
https://github.com/fatedier/frp/issues/1827
https://github.com/fatedier/frp/issues/1719
https://github.com/fatedier/frp/issues/1204

提问前先搜索历史 issue，不要再重复的创建完全重复的 issue，每次要重复回答一遍很累。#1204 中是最开始的回复，基本上就是原因。

https://golang.org/doc/faq#virus

**Comment by yangguangwuwu** [comment]
我是今天 报的  昨天 还没  腾讯管家 报 的 
0.33版本报毒
