### ISSUE TITLE
ubuntu server 18 上  运行出错

### ISSUE THREAD

**Issue by sinoll** [fatedier/frp#2047]
ubuntu server 18.04 system

ubuntu@ip-172-26-2-224:~/frp$ sudo ./frps
./frps: 1: ./frps:ELF?°3@?@8@@@@ddpeMpeMNOOR2gR2g????hF: not found
./frps: 2: ./frps: Syntax error: ")" unexpected

看起来用的人挺多的，准备下载自己编译 ，结果GO语言还是第一次看代码#83

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/releases
下载对应系统的二进制。
