### ISSUE TITLE
router config conflict

### ISSUE THREAD

**Issue by zhanghu663** [fatedier/frp#2048]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by BecodReyes** [comment]
Description information?
Please provide detailed questions according to the template, or even God can't help you

**Comment by zhanghu663** [comment]
**why router config conflict？**

### server frps.ini：
[common]
bind_port = 7000
token = *****
dashboard_port = 7500
dashboard_user = ****
dashboard_pwd = ****
vhost_http_port = 9000

### server frps log：
2020/11/04 10:57:02 [I] [service.go:152] frps tcp listen on 0.0.0.0:7000
2020/11/04 10:57:02 [I] [service.go:194] http service listen on 0.0.0.0:9000
2020/11/04 10:57:02 [I] [service.go:251] Dashboard listen on 0.0.0.0:7500
2020/11/04 10:57:02 [I] [root.go:205] start frps success
2020/11/04 10:57:06 [I] [service.go:392] [e7ffd7cec30c36c3] client login info: ip [116.*******] version [0.31.2] hostname [] os [linux] arch [amd64]
2020/11/04 10:57:06 [I] [http.go:92] [e7ffd7cec30c36c3] [web1] http proxy listen for host [120.******] location [] group []
2020/11/04 10:57:06 [I] [control.go:445] [e7ffd7cec30c36c3] new proxy [web1] success
2020/11/04 10:57:06 [I] [tcp.go:63] [e7ffd7cec30c36c3] [web2] tcp proxy listen port [45635]
2020/11/04 10:57:06 [I] [control.go:445] [e7ffd7cec30c36c3] new proxy [web2] success
2020/11/04 10:57:26 [I] [service.go:392] [79388bb79d31a836] client login info: ip [116.******] version [0.31.2] hostname [] os [linux] arch [amd64]
2020/11/04 10:57:27 [W] [control.go:442] [79388bb79d31a836] new proxy [web6] error: port already used
2020/11/04 10:57:27 [I] [proxy.go:76] [79388bb79d31a836] [web5] proxy closing
2020/11/04 10:57:27 [W] [control.go:442] [79388bb79d31a836] new proxy [web5] error: router config conflict
2020/11/04 10:58:00 [W] [control.go:442] [79388bb79d31a836] new proxy [web6] error: port already used

### client frpc.ini
[common]
server_addr = 120.*****
server_port = 7000
token = *****

[web5]
type = http
local_port = 9000
custom_domains = 120.*****

[web6]
type = tcp
local_port = 9000
custom_domains = 120.******
remote_port = 45635

### client frpc log：
2020/11/03 18:57:26 [I] [service.go:250] [79388bb79d31a836] login to server success, get run id [79388bb79d31a836], server udp port [0]
2020/11/03 18:57:26 [I] [proxy_manager.go:144] [79388bb79d31a836] proxy added: [web5 web6]
2020/11/03 18:57:27 [W] [control.go:162] [79388bb79d31a836] [web6] start error: port already used
2020/11/03 18:57:27 [W] [control.go:162] [79388bb79d31a836] [web5] start error: router config conflict

**Comment by BecodReyes** [comment]
>2020/11/04 10:58:00 [W] [control.go:442] [79388bb79d31a836] new proxy [web6] error: port already used

Port conflict, please change port.
If you read the logs carefully, you don't need to turn on this issue.
