### ISSUE TITLE
请问我有很多local_port和remote_port端口需要一一对应，是否有不用写很多行只写一行的简单写法？

### ISSUE THREAD

**Issue by Hiyokunotori** [fatedier/frp#2049]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
https://gofrp.org/docs/features/common/range/

可以支持，但是不建议使用太多端口，会有性能问题。
