### ISSUE TITLE
后续能支持websocketsecure(wss)吗？

### ISSUE THREAD

**Issue by badgv** [fatedier/frp#2050]
以便将frp流量套进HTTPS连接中，加强连接安全性，比如CDN等应用

**Comment by fatedier** [comment]
https://gofrp.org/docs/features/common/network/network-tls/

**Comment by badgv** [comment]
> https://gofrp.org/docs/features/common/network/network-tls/

这样frp能使用cdn中转加速吗？如果是wss，可以用nginx apache2等进行反向代理处理

**Comment by fatedier** [comment]
没有计划支持，如果想要通过其他应用中转，建议结合其他工具一起使用。

**Comment by badgv** [comment]
> 没有计划支持，如果想要通过其他应用中转，建议结合其他工具一起使用。

现在主要就是卡在使用其它工具结合使用上，不能使用https的web反代+frp组合，跨Q使用frp只能使用IP直连，虽然能用TLS加密，但是如果IP被封了就用不了，只有CDN能解决这种问题

**Comment by fatedier** [comment]
这一类的问题并不是 frp 这个项目要去解决的需求。这一类需求甚至可以抽象出一个 tunnel 的代理工具，负责将标准的 TCP 协议，转换成任何其他协议来传输，给这样的项目提支持 WSS 的需求比较合理。

**Comment by badgv** [comment]
主要是想着目前也是支持websocket的，也有人提交了更新wss的请求，后续不支持实在可惜了-_-#

**Comment by fatedier** [comment]
这个也是原因之一，一旦提供了某些支持，就会有更多这方面的需求和改动，维护也是有成本的，但这些并不是这个项目的核心能力，希望能把精力更多的分配在核心的功能上。有其他方式能实现的能力，就尽量通过组合的方式来使用。

**Comment by kingwilliam** [comment]
> > https://gofrp.org/docs/features/common/network/network-tls/
> 
> 这样frp能使用cdn中转加速吗？如果是wss，可以用nginx apache2等进行反向代理处理
> 比如IP被封的时候，还是可以走CDN连接，直接连接就不行了

可以试试 frp配合gost

**Comment by badgv** [comment]
> > > https://gofrp.org/docs/features/common/network/network-tls/
> > 
> > 
> > 这样frp能使用cdn中转加速吗？如果是wss，可以用nginx apache2等进行反向代理处理
> > 比如IP被封的时候，还是可以走CDN连接，直接连接就不行了
> 
> 可以试试 frp配合gost

谢谢大佬指点，使用gost走cdn端口转发成功了

**Comment by Limour-dev** [comment]
[proxynt](https://github.com/sazima/proxynt)就挺好，wss连接，[简单的使用记录](https://limour-blog.github.io/WebSocket-based-intranet-penetration-tool)。
