### ISSUE TITLE
v0.34.1  work connection closed before response StartWorkConn message: EOF

### ISSUE THREAD

**Issue by kiok1210** [fatedier/frp#2055]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
 frp_0.33.0_linux_amd64

**What operating system and processor architecture are you using (`go env`)?**
CentOs 7.8

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
 log：
` 2020/11/05 21:52:41 [D] [proxy_wrapper.go:231] [3bab2c638e7c3870] [ssh1] start a new work connection, localAddr: 192.168.1.208:44676 remoteAddr: 123.56.94.254:7000
2020/11/05 21:52:41 [T] [proxy.go:735] [3bab2c638e7c3870] [ssh1] handle tcp work connection, use_encryption: false, use_compression: false
2020/11/05 21:52:41 [D] [proxy.go:797] [3bab2c638e7c3870] [ssh1] join connections, localConn(l[127.0.0.1:44062] r[127.0.0.1:22]) workConn(l[192.168.1.208:44676] r[123.56.94.254:7000])
2020/11/05 21:52:46 [D] [control.go:309] [3bab2c638e7c3870] send heartbeat to server
2020/11/05 21:52:46 [E] [control.go:158] [3bab2c638e7c3870] work connection closed before response StartWorkConn message: EOF`

观察：
root     17206 14505  0 09:41 ?        00:00:00 sshd: frpc [priv]
frpc     17208 17206  0 09:41 ?        00:00:00 sshd: frpc@pts/4
这两个起穿透作用的服务会自动关闭

**Describe the results you expected:**
frp 连接正常不掉线

**Additional information you deem important (e.g. issue happens only occasionally):**
0.34.1版本这个问题在我机器上是一直出现的

**Can you point out what caused this issue (optional)**
退回到0.33版本后，这个问题ok了

**Comment by yuyulei** [comment]
could u provide your frp config file(frpc.ini & frps.ini) ?

**Comment by kiok1210** [comment]
frps配置：
`[common]
bind_port = 7000
# 监听地址
bind_addr = 0.0.0.0


# 监听web
vhost_http_port = 10080
vhost_https_port = 10443

# frp控制面板
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin

# 默认日志输出位置
log_file = /opt/frp/frps/logs/frps.log
# 日志级别 trace, debug, info, warn, error
log_level = info
# 保留3天
log_max_day = 3

# 鉴权方式 [token, oidc]
authentication_method = token
# 开启鉴权
authenticate_heartbeats = true
# 开启建立工作连接的鉴权
authenticate_new_work_conns = false
# auth token
token = M78xycatm
`

将参数项`authenticate_heartbeats`注释，
或者设为`false`，已经正常
