### ISSUE TITLE
服务端的一个端口可以实现websocket多路复用么

### ISSUE THREAD

**Issue by zhanghu663** [fatedier/frp#2056]
现在有个场景，我有多个内网服务，都是通过websocket通信，可以实现服务端的一个端口多路复用么，如果可以，烦请给上示例，谢谢

**Comment by shenlijun** [comment]
nginx反向代理给不同内网服务不同的路径可不可以？

**Comment by BecodReyes** [comment]
NGINX了解一下
或者通过编写插件完成

>frp 自身的核心代码不会再引入过多的这一类的能力，而是更多的以框架的形式来提供基础能力，通过插件来完善整体生态和满足部分用户的定制化需求

>从我个人的角度而言，这个阶段不太希望引入各种琐碎的 feature，很容易让项目成为一个大杂烩，既提高开发者的维护成本，也增加了用户的使用成本。最终某些功能可能只有几个人使用，甚至没有人用，但是持续的维护却需要耗费很多精力。

>所以，目前可能更多的是希望做减法，专注核心能力，做一些重构。之后能通过插件的方式开放更多的扩展能力出来，可以由有需求的人来完善。

**Comment by XieB** [comment]
有同样需求，楼主是否解决？
