### ISSUE TITLE
请教一下，如何裁剪这个源码，只留下socks插件的功能，让可执行文件控制在3-5兆左右

### ISSUE THREAD

**Issue by Ygrittevictorlee** [fatedier/frp#2059]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by QQ2017** [comment]
我甚至想裁剪下只保留TCP和STCP功能，一直没时间下手，我的思路是对比不同版本的源码，看看每加一个功能，都是加了哪些内容

**Comment by chenxudong2020** [comment]
Do you know go language？
