### ISSUE TITLE
关于n2n vpn穿透问题

### ISSUE THREAD

**Issue by 2726266496** [fatedier/frp#206]
n2n vpn的udp包穿透不了吗？

**Comment by fatedier** [comment]
vpn 为什么还需要穿透？具体不是很了解，能否描述一下详细的流程？

**Comment by 2726266496** [comment]
n2n vpn拓扑图如下，其中supernode搭建需要有公网IP，我在局域网内搭建了supernode，同时使用frp来做穿透，资料上说edge node使用UDP协议进行封装，结果连接不成功。
![](http://uploads.shuyz.com/2014/08/3448697635.png)

**Comment by fatedier** [comment]
有时间的时候我研究下。

**Comment by fatedier** [comment]
简单看了下，n2n 的原理应该也是 NAT 穿透，Super node 需要感知到连接上来的 Edge Node 的 udp 的 ip 和端口，之后尝试让两台 Edge Node 直连。

而如果 Super Node 的 udp 端口通过 frp 来转发，Super Node 拿到的 Edge Node 的 ip 和端口其实是本地的，将这个 ip 和 port 转发给 Edge Node 并不能起作用。

目前看来是不支持这样的应用的。
