### ISSUE TITLE
你好请问linux上使用哪个版本的go才能正常编译？我用1.14版的go执行make命令报错

### ISSUE THREAD

**Issue by rong280** [fatedier/frp#2062]
[root@Centos8-NO frp-0.34.2]# make
go fmt ./...
go: github.com/armon/go-socks5@v0.0.0-20160902184237-e75332964ef5: Get "https://proxy.golang.org/github.com/armon/go-socks5/@v/v0.0.0-20160902184237-e75332964ef5.mod": dial tcp 172.217.24.17:443: connect: connection refused
make: *** [Makefile:20: fmt] Error 1

一直提示这个

**Comment by EacoChen** [comment]
这个是go代理的问题，国内被墙了
