### ISSUE TITLE
0.34.1

### ISSUE THREAD

**Issue by gzqxlb** [fatedier/frp#2066]
不好意思，英文不好。
0.34.1
WOL-->udp-->*.*.255:9 fail(失败）

0.33.0(OK)

**Comment by BecodReyes** [comment]
你的问题？
是说0.34.1不支持wol的magisk包？
请使用模板！

**Comment by gzqxlb** [comment]
谢谢你的回复。不好意思，目前我是用回了0.33版了。作为一个爱好者，我只能说，可能也不是0.34.1不支持WOL。感觉好像是我开启了WOL包连接时的“压缩”和“加密”功能的原因，现在针对WOL包，我已经关闭了这两个功能，反正0.33使用是正常的。

&nbsp;

惜缘...久长。


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "蓝云Reyes"<notifications@github.com&gt;; 
发送时间: 2020年11月9日(星期一) 晚上6:27
收件人: "fatedier/frp"<frp@noreply.github.com&gt;; 
抄送: "惜缘"<gzqxlb@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fatedier/frp] 0.34.1 (#2066)





 
你的问题？
 是说0.34.1不支持wol的magisk包？
 请使用模板！
