### ISSUE TITLE
0.34.1 发生错误无法连接服务端 [control.go:178] [91777bf74d8e7b2f] start error: port unavailable

### ISSUE THREAD

**Issue by XYZliang** [fatedier/frp#2067]
服务端配置（云服务器Ubuntu18.04，相关端口已开）：
[common]
##服务器端口号
bind_port = 1234
max_pool_count = 40
##可视化界面
dashboard_addr = 0.0.0.0
dashboard_port = 8080
dashboard_user = admin
dashboard_pwd = 123456
token=123456
##日记
log_file = /home/ubuntu/frps/frps.log
log_level = info
log_max_days = 15

客户端配置（Macos BigSur）
[common]
server_addr = XXX.XX.XX.XX(我服务器ip)
server_port = 1234
token=zhangliang
[macOS Local VNC]
type = tcp
local_ip = 127.0.0.1
local_port = 5900
remote_port = 659
[macOS Local SSH]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 622
[macOS Local MySQL]
type = tcp
local_ip = 127.0.0.1
local_port = 3306
remote_port = 633

客户端运行发生以下错误
2020/11/09 15:12:38 [I] [service.go:288] [78940c414347b5f9] login to server success, get run id [78940c414347b5f9], server udp port [0]
2020/11/09 15:12:38 [I] [proxy_manager.go:144] [78940c414347b5f9] proxy added: [macOS Local VNC macOS Local SSH macOS Local MySQL]
2020/11/09 15:12:38 [W] [control.go:178] [78940c414347b5f9] [macOS Local VNC] start error: port unavailable
2020/11/09 15:12:38 [W] [control.go:178] [78940c414347b5f9] [macOS Local MySQL] start error: port unavailable
2020/11/09 15:12:38 [W] [control.go:178] [78940c414347b5f9] [macOS Local SSH] start error: port unavailable
并且不断重读后三行错误

服务器日志
2020/11/09 15:12:38 [I] [service.go:444] [78940c414347b5f9] client login info: ip [223.104.170.163:38860] version [0.34.1] hostname [] os [darwin] arch [amd64]
2020/11/09 15:12:38 [W] [control.go:442] [78940c414347b5f9] new proxy [macOS Local VNC] error: port unavailable
2020/11/09 15:12:38 [W] [control.go:442] [78940c414347b5f9] new proxy [macOS Local MySQL] error: port unavailable
2020/11/09 15:12:38 [W] [control.go:442] [78940c414347b5f9] new proxy [macOS Local SSH] error: port unavailable
并且不断重读后三行错误

**Comment by BecodReyes** [comment]
```start error: port unavailable```
请检测frps的相关端口是否已被占用

**Comment by fatedier** [comment]
`port unavailable` means frps can't bind this port.

The reason maybe:
1. The port is listened by other process.
2. frps has no enough permissions, try to give it root permission.

**Comment by llwq123456** [comment]
windows how to give it root permission
