### ISSUE TITLE
The same port of FRP client cannot use TCP and UDP at the same time

### ISSUE THREAD

**Issue by abotaku** [fatedier/frp#2068]
因游戏服务器需要 同一端口 TCP和UDP都要做映射，但是发现 客户端同一端口不能同时转发TCP和UDP

**Comment by abotaku** [comment]
log提示：start error: port already used

**Comment by BecodReyes** [comment]
**请使用模板**

**Comment by tecnicosya** [comment]
I have the same problem. Need tcp/udp in same port. 😕😕😕
