### ISSUE TITLE
 How to forward all ports instead of single port forwarding

### ISSUE THREAD

**Issue by jacky869869** [fatedier/frp#2069]
怎么进行全端口转发，而不是单个端口转发
你好，我想把内网主机192.168.1.2通过FRP进行全部端口或端口范围转发，而不是单个端口的转发，frp能不能做到呢？如果能做到，我应该怎么配置呢？frps跟frpc需要一起重新配置，还是原frps不动，只添加frpc配置？

**Comment by huanglvmin** [comment]
全端口转发，这看着总感觉是为难人家胖虎

**Comment by fatedier** [comment]
Try VPN instead, frp is'n designed for this scenario.
