### ISSUE TITLE
穿透功能缺失重要场景

### ISSUE THREAD

**Issue by WJME** [fatedier/frp#2070]
穿透功能缺失重要场景：
如在固定公网的阿里云上有个127.0.0.1的6001内部A服务端口，想在无固定公网的家庭网络环境中访问这个A服务就不行，期望应该是可以在frpc端的配置文件中可以配置一个远程端口6001，然后再配置一个本地端口8001，效果就是把远程的6001拉到本地为8001。就是现在的穿透过程的反向流程，重点就是要把frps端的服务端口拉到frpc端本地。
功能很简单，但是超级实用啊，望尽快出版本

**Comment by sbaa2014** [comment]
stcp 模式不就是干这个的么？
