### ISSUE TITLE
0.34.1版本，完全按照说明设置了，但是报http: proxy error: no such domain

### ISSUE THREAD

**Issue by hiprrrr** [fatedier/frp#2072]
0.34.1版本，完全按照说明设置了。启动也成功了。但http访问的时候报如题的错误，一直没办法找到原因。
1、配置正确
2、启动正常
3、通过TCP访问内网网站可以

就是改成http就不行了。

**Comment by BecodReyes** [comment]
**请提供frps.ini文件**
**请在issue模板上编辑**

**Comment by fatedier** [comment]
@BecodReyes 不用回复不按格式填写的 issue 了，后面 github action 上考虑加个过滤功能，不按格式填写的 issue 自动 close

**Comment by hiprrrr** [comment]
> @BecodReyes 不用回复不按格式填写的 issue 了，后面 github action 上考虑加个过滤功能，不按格式填写的 issue 自动 close

抱歉，并没有看到对格式的强制性要求，我会重新按新格式重新提的。再次感谢你们的软件。

**Comment by sora158** [comment]
谢谢qwq不看格式的傻子就是我
我直接复制粘贴csdn，# %都没去
