### ISSUE TITLE
0.34.1版本在http时报错，tcp是正常的

### ISSUE THREAD

**Issue by hiprrrr** [fatedier/frp#2074]
**[REQUIRED] hat version of frp are you using** 

Version:0.34.1

**[REQUIRED] What operating system and processor architecture are you using**
OS: 服务器端：CentOS 7.6，客户端：Debian 10
CPU architecture:x86_64（服务器端与客户端一致）

**[REQUIRED] description of errors**
访问的时候WEB页报如下错误（服务端的防火墙已经完全打开，TCP是可以正常穿透的，就是http报如下错误）：
The page you requested was not found.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

The server is powered by frp.

Faithfully yours, frp.

**confile**

frps.ini
[common]
bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
dashboard_port = 7500
token = zhejiushitoken
dashboard_user = admin
dashboard_pwd = woyebuzhidaomima

frpc.ini
[common]
server_addr = X.X.X.X（我临时掩码）
server_port = 7000
token = zhejiushitoken

[web]
type = http
local_ip = 127.0.0.1
local_port = 80
custom_domains = nextcloud.XXX.com（我临时掩码)

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

**log file**

服务端的LOG信息如下：
2020/11/12 22:28:45 [I] [service.go:190] frps tcp listen on 0.0.0.0:7000
2020/11/12 22:28:45 [I] [service.go:232] http service listen on 0.0.0.0:80
2020/11/12 22:28:45 [I] [service.go:253] https service listen on 0.0.0.0:443
2020/11/12 22:28:45 [I] [service.go:289] Dashboard listen on 0.0.0.0:7500
2020/11/12 22:28:45 [I] [root.go:212] start frps success
2020/11/12 22:29:36 [I] [service.go:444] [32894e244c8fdd17] client login info: ip [X.X.X.X:48910] version [0.34.1] hostname [] os [linux] arch [amd64]
2020/11/12 22:29:36 [I] [http.go:92] [32894e244c8fdd17] [web] http proxy listen for host [nextcloud.XXX.com] location [] group []
2020/11/12 22:29:36 [I] [control.go:446] [32894e244c8fdd17] new proxy [web] success
2020/11/12 22:29:36 [I] [tcp.go:63] [32894e244c8fdd17] [ssh] tcp proxy listen port [6000]
2020/11/12 22:29:36 [I] [control.go:446] [32894e244c8fdd17] new proxy [ssh] success
2020/11/12 22:30:00 [W] [http.go:86] do http proxy request error: no such domain: nextcloud.XXX.cn /

客户端LOG信息如下：
2020/11/12 22:29:36 [I] [service.go:288] [32894e244c8fdd17] login to server success, get run id [32894e244c8fdd17], server udp port [0]
2020/11/12 22:29:36 [I] [proxy_manager.go:144] [32894e244c8fdd17] proxy added: [ssh web]
2020/11/12 22:29:36 [I] [control.go:180] [32894e244c8fdd17] [web] start proxy success
2020/11/12 22:29:36 [I] [control.go:180] [32894e244c8fdd17] [ssh] start proxy success

**Steps to reproduce the issue**
1. 按以上配置修改完成
2. 启动服务端
3. 启动客户端
4.使用域名访问

**Supplementary information**
无

**Can you guess what caused this issue**
没有头绪

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by hiprrrr** [comment]
补充一下，服务端在腾讯云上，客户端在家庭网内。

**Comment by yuyulei** [comment]
try
```
curl -v "http://<tengxun_cloud_public_ip>" -H "Host: nextcloud.XXX.com" 
```

or try this [DEMO](https://gofrp.org/docs/examples/vhost-http/) carefully.

**Comment by fox-ghost** [comment]
遇到一样的问题,怎么解决的
