### ISSUE TITLE
源码无法编译

### ISSUE THREAD

**Issue by sairsonblog** [fatedier/frp#2075]
**[REQUIRED] hat version of frp are you using** 

Version:

**[REQUIRED] What operating system and processor architecture are you using**
OS:
CPU architecture:

**[REQUIRED] description of errors**

**confile**

**log file**

**Steps to reproduce the issue**
1. 
2. 
3. 

**Supplementary information**

**Can you guess what caused this issue**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by BecodReyes** [comment]
**Please complete the issue
Otherwise even God won’t know what your problem is**
