### ISSUE TITLE
配置tls双向验证出错

### ISSUE THREAD

**Issue by lim-wei** [fatedier/frp#2077]
按照文档生成对应文件，并修改相关配置后无法连接
配置如下
frpc.ini
`
[common]
server_addr = 
server_port = 7000
tls_enable = true
tls_cert_file = /usr/local/frp/client.crt
tls_key_file = /usr/local/frp/client.key
tls_trusted_ca_file = /usr/local/frp/ca.crt
`
frps.ini
`[common]
bind_port = 7000
vhost_http_port = 8084
tls_cert_file = /usr/local/frp/server.crt
tls_key_file = /usr/local/frp/server.key
tls_trusted_ca_file = /usr/local/frp/ca.crt
`
报错信息
客户端：[W] [service.go:102] login to server failed: session shutdown
session shutdown

**Comment by shenlijun** [comment]
Let's Encrypt申请的证书遇到同样的问题

**Comment by ppllpig** [comment]
我是通过KCP解决的
