### ISSUE TITLE
frpc is virus

### ISSUE THREAD

**Issue by ml232528** [fatedier/frp#2079]
用的是0.34.2版本，有人种勒索病毒了，怀疑是frpc泄露了远程密码。
frp_0.34.2_windows_amd64.zip
作者出来解释下。

**Comment by fatedier** [comment]
1. Please take a look at source code to find where is the problem. This is an open source project which you can build the sofeware by yourself.
2. I'm really surprised that you published comments without responsibility and any evidence.
3. I have no duty to help you solve your problem if you can't provide any detail info.

**Comment by WITCHERMASTER3** [comment]
> 用的是0.34.2版本，有人种勒索病毒了，怀疑是frpc泄露了远程密码。
> frp_0.34.2_windows_amd64.zip
> 作者出来解释下。

**Comment by WITCHERMASTER3** [comment]
frpc.exe被杀毒软件查杀了

**Comment by jasonhuxz** [comment]
![scan](https://user-images.githubusercontent.com/51232861/99661402-bd0edf80-2a9e-11eb-9c63-96a077ac2bcd.png)
I have the same problem.

**Comment by fatedier** [comment]
@WITCHERMASTER3 @jasonhuxz  https://github.com/fatedier/frp/issues/2046#issuecomment-720919285

Search issue history first to find if there are already same issues. It will save your and my time.

I have no so mach time to awnser the same question repeatedly, repeatedly, repeatedly...

There are almost 10 repeat issues about this, try to solve it by yourself first.

**Comment by jasonhuxz** [comment]
@fatedier  Got it. Thanks.
I just searched the open issues but forgot the closed one.

**Comment by WITCHERMASTER3** [comment]
@fatedier 我换回旧版本没有杀毒警报。软件很好用，谢谢！

**Comment by weiwangda2014** [comment]
我的也被病毒中招了，所有的文件都被加密了，并留了一个邮箱【squadhack@email.tg】，给他支付比特币，给你解密密钥。

**Comment by nxuu** [comment]
诺顿曾经把windows的explorer.exe杀掉的新闻  可以了解一下。  如果你不相信这个开源软件 那么就专心用杀毒软件来实现你想要的功能。
为什么那么信任杀毒软件呢？因为杀毒软件是付费的么？杀毒软件就不会报错么？
如果是病毒，这里早就炸锅了。并且github的工程师也不会坐视不理。

> frpc.exe被杀毒软件查杀了



> 用的是0.34.2版本，有人种勒索病毒了，怀疑是frpc泄露了远程密码。
> frp_0.34.2_windows_amd64.zip
> 作者出来解释下。

**Comment by WITCHERMASTER3** [comment]
@nxuu explorer.exe真的很搞事情

**Comment by witer55** [comment]
![QQ截图20210119163226](https://user-images.githubusercontent.com/60841619/105009394-5fcee480-5a75-11eb-912e-5058f80def79.jpg)
0.34.3 版本，微软自带的杀毒软件报说有毒，查杀了
