### ISSUE TITLE
使用http_proxy无法连接到frp服务端

### ISSUE THREAD

**Issue by nicholasdrag** [fatedier/frp#2080]
**[REQUIRED] hat version of frp are you using** 

Version:0.34.2

**[REQUIRED] What operating system and processor architecture are you using**
OS:Win10

**[REQUIRED] description of errors**

**confile**

[common]
server_addr = frps服务器的公网ip
server_port = 37000
http_proxy = http://[用户名]:[密码]@[公司浏览器代理ip]:[端口]

[RDP]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 3389

**log file**

2020/11/18 14:41:43 [W] [service.go:102] login to server failed: DialTcpByHttpProxy error, StatusCode [403]
DialTcpByHttpProxy error, StatusCode [403]

**Steps to reproduce the issue**
1.使用环境：win10主机作为frpc客户端，在公司内网环境中必须要通过浏览器代理才能访问外网，不设置代理就无法访问vps上的frps服务端。
2. win10主机cmd执行frpc.exe -c frpc.ini
3. 执行后报错：[service.go:102] login to server failed: DialTcpByHttpProxy error, StatusCode [403]
DialTcpByHttpProxy error, StatusCode [403]。如果我把配置文件中http_proxy中的密码替换成错误的，报错信息是DialTcpByNTLMHttpProxy error, StatusCode [407]
4.PS：不使用公司的网络，并删除配置文件中的http_proxy，是可以成功连上frps服务器的。

请问大佬，这种情况是不是被公司网络限制了？

**Comment by fatedier** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/403
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/407

To search for code 403, it means your username or password not correct.

**Comment by nicholasdrag** [comment]
> https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/403
> https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/407
> 
> To search for code 403, it means your username or password not correct.

可能是我的密码里有个特殊字符@ ，请问要怎么处理呢？我将它转化成%40试了一下也还是报403

**Comment by fatedier** [comment]
Please make sure all special characters are escaped?

**Comment by nicholasdrag** [comment]
> Please make sure all special characters are escaped?

密码中只有一个@是特殊字符哈，比如Ab@12，请问我该如何正确转义，Ab%4012这样对吗？

**Comment by fatedier** [comment]
@nicholasdrag I'm not sure what's wrong with you case. 

@yuyulei Can you validate if it's a problem when the password has `@`.
