### ISSUE TITLE
FRP ssh service with fail2ban

### ISSUE THREAD

**Issue by troyliu0105** [fatedier/frp#2084]
VERSION: frps:0.34.2, frpc:0.34.2
OS: frps: Archlinux x64, frpc: Ubuntu x64

Description: 

When I use the frpc config to expose a local ssh service to public network, config like below:
```
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 12345
use_compression = true
use_encryption = true
```
it forwards incoming connections to 127.0.0.1:22, and the auth.log show that remote IP address is 127.0.0.1.
So fail2ban could not find the correct public IP address. 🙃

**Comment by fatedier** [comment]
You can try `proxy protocol` https://github.com/fatedier/frp#proxy-protocol.

But i'm not sure if fail2ban can support this protocol.

On the other hand, if you are care about security, do not expose your ssh port to public network directly. Try `stcp` https://github.com/fatedier/frp#expose-your-service-privately instead.
