### ISSUE TITLE
token 不正确

### ISSUE THREAD

**Issue by libra1010** [fatedier/frp#2090]
[REQUIRED] hat version of frp are you using

Version:
0.34.2
0.34.3

[REQUIRED] What operating system and processor architecture are you using
OS:
server: centos7
client: macos 10.15.2

[REQUIRED] description of errors

confile
server

[common]
bind_addr = 0.0.0.0
bind_port = 7000
vhost_http_port = 7001
authentication_method = token
token = 123456

client
[common]
server_addr = 服务端ip
server_port = 7000
authentication_method = token
token = 123456

[nas1]
type = http
local_ip = 192.168.3.200
local_port = 5000
remote_port = 7001
custom_domains = xxx.com

log file

2020/11/20 22:06:23 [I] [service.go:444] [c63f9da59d413f8e] client login info: ip [171.212.254.60:62769] version [0.34.2] hostname [] os [darwin] arch [amd64]
2020/11/20 22:06:23 [W] [service.go:346] register control error: token in login doesn't match token from configuration

Steps to reproduce the issue
1:配置服务端
2:启动服务端
3:配置客户端
4: 启动客户端

尝试多个版本，
authentication_method = token 移除加入，都还是有问题

**Comment by libra1010** [comment]
可能是复制配置的原因
去掉 authentication_method = token
去掉 token = 123456
保存
重新编辑配置文件
手动加入 token = 123456
启动，就完全OK

**Comment by jjqtony** [comment]
根据上面的做法，我怎么都是不对，以前用老版本0.29是ok的，肯定是新版的锅。

**Comment by z0ow** [comment]
我也不能解决这个问题 😭

**Comment by kittysmith5** [comment]
把服务端token改成12345678试试,那默认密码是12345678,客户端就可以把token删掉

**Comment by sidpku** [comment]
同样的问题。
将客户端和服务器端的`authentication_method = token`都删掉后，将`token = mypassword`删掉重新输入，解决掉了问题。
