### ISSUE TITLE
请问http映射的时候把ip映射出去而不是映射域名

### ISSUE THREAD

**Issue by szw1026** [fatedier/frp#2092]
请问http映射的时候把ip映射出去而不是映射域名

**Comment by zsinba** [comment]
当然不行了。。。

**Comment by xqzr** [comment]
不行 可以使用tcp类型来映射

**Comment by szw1026** [comment]
> 不行 可以使用tcp类型来映射

![image](https://user-images.githubusercontent.com/61342636/99958113-c0b6a500-2dc3-11eb-87f3-a9b194d5c96b.png)
这种可以
