### ISSUE TITLE
0.34.3 doesn't recognize token in ini, but only use the token in cli arg.

### ISSUE THREAD

**Issue by wxiaoguang** [fatedier/frp#2099]
**[REQUIRED] hat version of frp are you using** 

Version: 0.34.3

**[REQUIRED] What operating system and processor architecture are you using**
OS: linux (possible all)
CPU architecture: amd64 (possible all)

**[REQUIRED] description of errors**

**confile**

```
[common]
bind_port = 7000
bind_udp_port = 7001

authentication_method = token
token = 1548730981638475
```

**log file**

```
2020/11/23 15:40:42 [I] [service.go:190] frps tcp listen on 0.0.0.0:7000
2020/11/23 15:40:42 [I] [root.go:215] start frps success
2020/11/23 15:40:45 [I] [service.go:444] [61969eb534133aa3] client login info: ip [x.x.x.x:63145] version [0.34.3] hostname [] os [darwin] arch [amd64]
2020/11/23 15:40:45 [W] [service.go:346] register control error: token in login doesn't match token from configuration
```

**Steps to reproduce the issue**
1.  set `token` in `[common].[token]` for both frpc and frps
2. run frpc
3. frpc can not connect to frps

INSTEAD, if I use `frps -t TheToken`, then frpc can connect.

**Supplementary information**

**Can you guess what caused this issue**

Wrong config & cli-argument logic

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by wxiaoguang** [comment]
Sorry but I think the problem is caused by the linux frps doesn't use `frps.ini` in `$PWD`.

**Comment by fatedier** [comment]
Yes, it will start with default configures if you not specified config file path.

`frps -c ./frps.ini`

**Comment by wxiaoguang** [comment]
Well, a little misleading .... IMO it's better to tell users which config file they are using ...

And `frpc`'s behavior is different from `frps`, it seems that `frpc` respects `$PWD/frpc.ini`.

**Comment by fatedier** [comment]
I keep the way just for compatible reason since `frpc` can't start without any cmd parameters.
