### ISSUE TITLE
StatusCode [403]

### ISSUE THREAD

**Issue by JulianZhao** [fatedier/frp#210]
我在Releases里下载了最新的0.9.1版本，完全按照   [中文文档](https://github.com/fatedier/frp/blob/master/README_zh.md) 一开始的说明做了以下配置，启动报403，请问是哪里配置不对吗？

（其中x.x.x.x是我的公网服务器IP，frps启动后，telnet x.x.x.x 7000是ok的）

./frps -c ./frps_min.ini

./frpc -c ./frpc_min.ini
2017/01/03 13:15:31 [main.go:109] [I] Start frpc success
2017/01/03 13:15:31 [control.go:139] [E] ProxyName [ssh], connect to server [x.x.x.x:7000] error, ConnectServer using proxy error, StatusCode [403]
2017/01/03 13:15:31 [control.go:39] [E] ProxyName [ssh], connect to server failed!
2017/01/03 13:15:31 [main.go:112] [W] All proxy exit!

# frps_min.ini
[common]
bind_port = 7000

[ssh]
listen_port = 6000
auth_token = 123

# frpc_min.ini
[common]
server_addr = x.x.x.x
server_port = 7000
auth_token = 123

[ssh]
local_ip = 127.0.0.1
local_port = 22

**Comment by fatedier** [comment]
检查下你是否设置了环境变量 `HTTP_PROXY`，可以把这个去掉再试。

**Comment by JulianZhao** [comment]
@fatedier 试了，`http_proxy="" ./frpc -c frpc_min.ini` 可以的，感谢。

**Comment by JermaHuang** [comment]
我在frpc.ini 配置了http_proxy，也是报错403
![image](https://user-images.githubusercontent.com/26479972/69774540-25e7b280-11d1-11ea-80f5-ec41b6b564f3.png)
