### ISSUE TITLE
frpc在win10下报病毒

### ISSUE THREAD

**Issue by wangzhengzhen** [fatedier/frp#2104]
frp 0.34.2，0.34.3版本在win10自带杀毒软件中被报病毒。frpc.exe会报，frps.exe正常

![pic](https://s3.ax1x.com/2020/11/24/DtCe4e.png)

**Comment by 4615** [comment]
同报

**Comment by liangshi036** [comment]
same here

**Comment by JackyNiu** [comment]
一样报毒，就算还原回来还是会被不停的删除

**Comment by liangshi036** [comment]
加入白名单就好了。误报。

**Comment by fatedier** [comment]
Duplicate of #2095 #1204
