### ISSUE TITLE
frp监控页面流量不显示

### ISSUE THREAD

**Issue by lwx2615** [fatedier/frp#2112]
**[REQUIRED] hat version of frp are you using** 

Version:0.34.3

**[REQUIRED] What operating system and processor architecture are you using**
OS:centos7
CPU architecture:x86_64

**[REQUIRED] description of errors**
frp监控页面监控了2天后，流量统计失效。出入流量都为 0 bytes。但是能确定有流量，因为是通过p2p的映射进行日志采集，日志有增长

**confile**

```
[common]
# A literal address or host name for IPv6 must be enclosed
# in square brackets, as in "[::1]:80", "[ipv6-host]:http" or "[ipv6-host%zone]:80"
bind_addr = 0.0.0.0
bind_port = 7000

# udp port to help make udp hole to penetrate nat
bind_udp_port = 7001

# udp port used for kcp protocol, it can be same with 'bind_port'
# if not set, kcp is disabled in frps
kcp_bind_port = 7000
dashboard_addr = 114*****.114
dashboard_pwd = 123456
enable_prometheus = true
log_file = /data/logs/frp/frps.log
log_level = info

log_max_days = 3

# disable log colors when log_file is console, default is false
disable_log_color = false

# DetailedErrorsToClient defines whether to send the specific error (with debug info) to frpc. By default, this value is true.
detailed_errors_to_client = true
authentication_method = token

# AuthenticateHeartBeats specifies whether to include authentication token in heartbeats sent to frps. By default, this value is false.
authenticate_heartbeats = false

# AuthenticateNewWorkConns specifies whether to include authentication token in new work connections sent to frps. By default, this value is false.
authenticate_new_work_conns = false

# auth token
token = '21312432423'
allow_ports = 2000-3000,3001,3003,4000-50000

# pool_count in each proxy will change to max_pool_count if they exceed the maximum value
max_pool_count = 5

# max ports can be used for each client, default value is 0 means no limit
max_ports_per_client = 0

# TlsOnly specifies whether to only accept TLS-encrypted connections. By default, the value is false.
tls_only = false
subdomain_host = frps.com

# if tcp stream multiplexing is used, default is true
tcp_mux = true

# custom 404 page for HTTP requests
# custom_404_page = /path/to/404.html

# specify udp packet size, unit is byte. If not set, the default value is 1500.
# This parameter should be same between client and server.
# It affects the udp and sudp proxy.
udp_packet_size = `1500`
```

**log file**

2020/12/01 11:57:30 [I] [dashboard_api.go:180] Http request: [/api/proxy/tcp]
2020/12/01 11:57:30 [I] [dashboard_api.go:174] Http response [/api/proxy/tcp]: code [200]
2020/12/01 11:57:31 [I] [dashboard_api.go:314] Http request: [/api/traffic/flume1]
2020/12/01 11:57:31 [I] [dashboard_api.go:308] Http response [/api/traffic/flume1]: code [200]

服务端日志正常，没有error日志，但是客户端的日志为空。
**Steps to reproduce the issue**
1. 
2. 
3. 

**Supplementary information**

**Can you guess what caused this issue**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by fatedier** [comment]
> 因为是通过p2p的映射进行日志采集

根据 issue 模版提供必要的配置和日志，可以有效减少沟通成本。

xtcp 类型目前不包含在流量统计中，不知道你用的是不是这个类型。

**Comment by lwx2615** [comment]
配置和日志已经贴上。用的是tcp类型的，开始的时候是有流量统计显示。点开trafic statistic按钮能到流量显示，但是也是有的没有。页面上显示的trafic in和out都是0.
