### ISSUE TITLE
使用frp的连接内网机器，不到一分钟就自己断开，大佬们觉得可能是哪里的原因

### ISSUE THREAD

**Issue by umena337** [fatedier/frp#2117]
frp 0.27
frpc端：
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

![image](https://user-images.githubusercontent.com/44667665/100494648-7f851300-317e-11eb-8ced-edb4292c6175.png)
xshell试验了能连上内网机器，连上不到一分钟就自己断开了！！！！
》》》
[root@localhost frp_0.27.0_linux_amd64]# Connection closing...Socket close.
Connection closed by foreign host.
Disconnected from remote host(内网2xx) at 13:36:01.

**Comment by umena337** [comment]
真是难顶

**Comment by umena337** [comment]
我更新到最新的 frp0.34.3   依然这样！
大佬们看看这个功能有啥问题
[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 7000
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

**Comment by umena337** [comment]
更新0.34.3正常

**Comment by HellowBoy** [comment]
我是这样解决的，目前测试没问题了。
客户端和服务器端关闭端口复用，客户端注册间隔时间设置为0
