### ISSUE TITLE
frp配置一切正常，但是无法穿透，甚至无法通过7500端口访问dashboard

### ISSUE THREAD

**Issue by kalonezero87** [fatedier/frp#2118]
**[REQUIRED] hat version of frp are you using** 

Version:0.34.3

**[REQUIRED] What operating system and processor architecture are you using**
OS:Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-124-generic x86_64)

CPU architecture:AMD64

**[REQUIRED] description of errors**
我之前在另外一台服务器部署过frp,一切正常。各方面考虑，我把frp部署在腾讯云 香港服务器（不用备案）。我基本上照搬了之前vps的设置。发现新部署的frp客户端无法连接服务器端。甚至无法通过7500端口访问dashboard。
**confile**

server：
[common]
bind_addr = 0.0.0.0

bind_port = 7000

token = 

vhost_http_port = 8080

vhost_https_port = 443

dashboard_addr = 0.0.0.0

dashboard_port = 7500

dashboard_user = admin

dashboard_pwd = 

client：
common]

server_addr = 

server_port = 7000

token = 

[DSM]

type = tcp

local_ip = 127.0.0.1

local_port = 5000

remote_port = 6001

[Jellyfin]

type = tcp

local_ip = 127.0.0.1

local_port = 8096

remote_port = 7001

[Tinymediamanger]

type = tcp

local_ip = 127.0.0.1

local_port = 5800

remote_port = 8001

[Qbittorrent]

type = tcp

local_ip = 127.0.0.1

local_port = 8989

remote_port = 9010

[NextCloud]

type = tcp

local_ip = 127.0.0.1

local_port = 8888

remote_port = 9888
[Onlyoffice]

type = tcp

local_ip = 127.0.0.1

local_port = 8002

remote_port = 8003

[SSH]

type = tcp

local_ip = 127.0.0.1

local_port = 22

remote_port = 6006

root@ubuntu:~/frp# systemctl status frps
● frps.service - fraps service
   Loaded: loaded (/lib/systemd/system/frps.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-11-28 07:59:15 EST; 3min 52s ago
 Main PID: 3709 (frps)
    Tasks: 3 (limit: 1128)
   CGroup: /system.slice/frps.service
           └─3709 /root/frp/frps -c /root/frp/frps.ini

Nov 28 07:59:15 ubuntu systemd[1]: Started fraps service.
Nov 28 07:59:15 ubuntu frps[3709]: 2020/11/28 07:59:15 [I] [service.go:190] frps tcp listen on 0.0.0.0:7000
Nov 28 07:59:15 ubuntu frps[3709]: 2020/11/28 07:59:15 [I] [service.go:232] http service listen on 0.0.0.0:8080
Nov 28 07:59:15 ubuntu frps[3709]: 2020/11/28 07:59:15 [I] [service.go:253] https service listen on 0.0.0.0:443
Nov 28 07:59:15 ubuntu frps[3709]: 2020/11/28 07:59:15 [I] [service.go:289] Dashboard listen on 0.0.0.0:7500
Nov 28 07:59:15 ubuntu frps[3709]: 2020/11/28 07:59:15 [I] [root.go:215] start frps success

root@ubuntu:~/frp# ./frps -c ./frps.ini
2020/11/28 07:58:12 [I] [service.go:190] frps tcp listen on 0.0.0.0:7000
2020/11/28 07:58:12 [I] [service.go:232] http service listen on 0.0.0.0:8080
2020/11/28 07:58:12 [I] [service.go:253] https service listen on 0.0.0.0:443
2020/11/28 07:58:12 [I] [service.go:289] Dashboard listen on 0.0.0.0:7500
2020/11/28 07:58:12 [I] [root.go:215] start frps success

**log file**

**Steps to reproduce the issue**
1. 
2. 
3. 

**Supplementary information**

**Can you guess what caused this issue**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by kalonezero87** [comment]
忘记说了，端口都在防火墙那里已经打开了

**Comment by qsc4442** [comment]
解决了嘛
