### ISSUE TITLE
服务器端 common 可以设置 auth_token 吗?

### ISSUE THREAD

**Issue by lotc** [fatedier/frp#212]
说明文档里面这样介绍

> 服务器端可以在 frps.ini 中为每一个代理设置一个 auth_token 用于对客户端连接进行身份验证

示例文件里面 frps.ini 的 common 没有 auth_token，但 frpc.ini 的 common 有 auth_token
1) 如果 frps.ini 的 common 设置了 auth_token，会否影响每一个代理的 auth_token？
2) 如果 frps.ini 没有设置 auth_token，frpc.ini 是保持 auth_token = 123 还是删除该行？

**Comment by fatedier** [comment]
1. 目前需要为每一个 proxy 指定 auth_token，common 中配置的不会起作用。
2. frps 中配置的 proxy 必须有 auth_token，不存在会报错退出。

**Comment by lotc** [comment]
也就是说 frpc 的 common 里面的不需要填写 auth_token
我这样的说法对吗?

**Comment by fatedier** [comment]
只有你一个人用的话是的，当你需要让其他人使用时，可以为他用的 proxy 设置另一个 auth_token。

**Comment by lotc** [comment]
完全明白你的思路了。
frps 里面根据不同用户需求，将用户1需要的服务全部设置成 auth_token1，用户2的设置成 auth_token2，用户3就 auth_token3。
然后用户1使用需要的服务，全部使用 auth_token1；用户2就用 auth_token2，以此类推。
