### ISSUE TITLE
OIDC 总是会有各种问题

### ISSUE THREAD

**Issue by lelouch-star** [fatedier/frp#2121]
OIDC只是一种协议。我试了几家的Server都没有成功。我查阅了OIDC文档，但是代码中的OIDC验证好像不是和标准完全一致的。比如标准中有个idtoken的东西。代码中取的好像并不是idtoken
能否说下具体的验证 的请求报文和返回报文例子

或者能否直接留个 用户验证接口  
配置项1：http/https的验证接口地址 （内定用户名、密码参数名，返回boolean）
配置项2：用户名
配置项3：密码

**Comment by ripgyxcy** [comment]
签名没问题，jwks_uri接口也配置了
但是却返回了这个报错
invalid OIDC token in login: failed to verify signature: failed to verify id token signature

**Comment by liyi830** [comment]
关注此问题，我也碰到这种情况了。

**Comment by liyi830** [comment]
签名算法提供个例子吧

**Comment by huanghe-1** [comment]
@ripgyxcy 你用的什么OIDC 服务器

**Comment by imarkofu** [comment]
关注一下，不知道该如何搭建一个OIDC服务

**Comment by bingtianbaihua** [comment]
方便起见，可以去申请 auth0 or 国内的 authing 来验证，都是免费的。

**Comment by huanghe-1** [comment]
frp可以使用authing吗？稳定吗
