### ISSUE TITLE
windows server 2012 : parse ini conf file error

### ISSUE THREAD

**Issue by wy1037** [fatedier/frp#2126]
version 0.34.3

frpc.exe -c frpc.ini
parse ini conf file error: invalid INI syntax on line 1: ﻿# [common] is integral

同样的文件，win7 可以执行，
windows server 2008 r2
windows server 2012 r2
都是报错的，
为了避免其他影响：
frpc.ini 文件 只写了2行内容：

> 

`# [common] is integral
[common]
server_addr=172.16.1.117
server_port=7000`

**Comment by BecodReyes** [comment]
注释问题
```
[common]
server_addr=172.16.1.117
server_port=7000
```

**Comment by wy1037** [comment]
不是注释问题。

后来发现，frpc.ini 文件格式用记事本改为ANSI 就可以了。
文件内容没有任何问题。

**Comment by wy1037** [comment]
frpc.ini 文件格式用记事本改为ANSI 就可以了
