### ISSUE TITLE
FRP是如何解析https的呢

### ISSUE THREAD

**Issue by lim-wei** [fatedier/frp#2127]
**The solution you want**
我想要了解一下，frp是否有解析https的过程，我能否把信息放入https的报文中使frp获取到。我翻看了所有文档，没有发现类似的功能配置，所以想要咨询一下。

**Application scenarios of this function**
我使用frp进行内网的穿透，通过域名访问frp代理的一个端口之后可以跳转到不同的服务上。我在tcp报文中加入信息，使frp可以根据这个信息选择跳转哪一个服务。现在我希望把这个信息放入https的报文而不是tcp报文中。

**Comment by BecodReyes** [comment]
https为加密报文，frp无能力解析
仅提供类似vhost的功能
如需可通过tcp+frpc端的vhost实现

**Comment by lim-wei** [comment]
收到，感谢回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "蓝云Reyes"<notifications@github.com&gt;; 
发送时间: 2020年12月3日(星期四) 下午5:56
收件人: "fatedier/frp"<frp@noreply.github.com&gt;; 
抄送: "☀️"<2911455371@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fatedier/frp] FRP是如何解析https的呢 (#2127)





 
https为加密报文，frp无能力解析
 仅提供类似vhost的功能
 如需可通过tcp+frpc端的vhost实现

**Comment by lim-wei** [comment]
对不起我想再次询问一下，对于网络这方面了解较少，我这个信息是放在tcp的额外字段中，理论上放在http协议的host中也是可以获取到的。那么我想询问下frp使用tls加密的原理是什么，是将tls的四次握手这一完整的请求进行转发吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fatedier/frp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 下午5:56
收件人:&nbsp;"fatedier/frp"<frp@noreply.github.com&gt;;
抄送:&nbsp;"☀️"<2911455371@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fatedier/frp] FRP是如何解析https的呢 (#2127)





 
https为加密报文，frp无能力解析
 仅提供类似vhost的功能
 如需可通过tcp+frpc端的vhost实现

**Comment by fatedier** [comment]
关键字: SNI

**Comment by yuxuechao** [comment]
配合nginx再代理一层
