### ISSUE TITLE
如果frps.ini服务器的每个anth_token都配置的不一样,客户端怎么配置

### ISSUE THREAD

**Issue by xjl456852** [fatedier/frp#213]
如果frps.ini服务器的每个服务的anth_token都配置的不一样,客户端怎么配置.才能同时连接.
如果服务端配置的
[ssh]
anth_token=12345
[web01]
anth_token=0123
等等

我看示例中客户端frpc.ini只有common中有一个anth_token配置.
即使我为每个服务增加anth_token配置,我看了客户端的日志,它连接的时候还是只使用客户端的frpc.ini的common中的anth_token配置,各个服务中的anth_token是无效的.
客户端的怎么配置才能同时认证连接这些服务?

**Comment by fatedier** [comment]
`anth_token` 这个参数一开始设计是针对用户的，一个 frpc 上的所有 proxy 被认为是属于同一个用户，所以采用相同的 `auth_token`。
