### ISSUE TITLE
reduce the log level to info/trace [W] [vhost.go:147] get hostname from http/https request error: readHandshake: there is no extension data to get servername

### ISSUE THREAD

**Issue by Milokita** [fatedier/frp#2131]
**The solution you want**

the log now is filled with the warning bellow,  but it won't affect the program if the https is served under apache/nginx so change it to info/debug would be better
`
[W] [vhost.go:147] get hostname from http/https request error: readHandshake: there is no extension data to get servername
`
**Alternatives considered**

add auto supress function
**How to implement this function**

change the log level this warning belong to
**Application scenarios of this function**

prevent log is filled with this warning

**Comment by fatedier** [comment]
@Milokita Can you submit a PR to change the log level to `debug`?

**Comment by Milokita** [comment]
Pull request submitted
