### ISSUE TITLE
Not support IPV6.

### ISSUE THREAD

**Issue by 378978764** [fatedier/frp#2132]
The config file:
```
[gpustaker]
type = http
local_port = 8000
local_ip = [2001:da8:204:1043:f393:7869:xxxx:c9]
custom_domains = example.com
```
However, when connected to my domain, the following error occurs:
```
2020/12/05 10:13:27 [E] [proxy.go:793] [4c5a274fae2a860a] [gpustaker] connect to local service [2001:da8:204:1043:f393:7869:1dd3:c9:8000] error: dial tcp: address 2001:da8:204:1043:f393:7869:xxxx:c9:8000: too many colons in address
```

**Comment by BecodReyes** [comment]
If the FRPC is deployed locally, do not add `local_ip`.

If you have an IPv4 intranet address, use IPv4.

FRP may not support IPv6 completely.

**Comment by fatedier** [comment]
@BecodReyes There is no difference between IPv4 and IPv6, golang net package support them default.

@378978764 Your IP address is not correct format detect by golang net package.

**Comment by 378978764** [comment]
> @BecodReyes There is no difference between IPv4 and IPv6, golang net package support them default.
> 
> @378978764 Your IP address is not correct format detect by golang net package. Make sure your have `[` `]` in both side of `local_ip`. It's not seen in log.

The IP address is indeed enclosed in square brackets, both in the configuration file and log. This ip address is copied from the `ipconfig` command.

**Comment by 378978764** [comment]
> If the FRPC is deployed locally, do not add `local_ip`.
> 
> If you have an IPv4 intranet address, use IPv4.
> 
> FRP may not support IPv6 completely.

Unfortunately, the service is deployed in a local area network, and this machine can only be accessed through an IPv6 address.

**Comment by fatedier** [comment]
`2020/12/05 10:13:27 [E] [proxy.go:793] [4c5a274fae2a860a] [gpustaker] connect to local service [2001:da8:204:1043:f393:7869:1dd3:c9:8000] error: dial tcp: address 2001:da8:204:1043:f393:7869:xxxx:c9:8000: too many colons in address`

@378978764 From the log your pasted, there are no brackets. `2001:da8:204:1043:f393:7869:xxxx:c9:8000` is not correct address, it should be `[2001:da8:204:1043:f393:7869:xxxx:c9]:8000`.

I test the correct adrress and it's all right.
