### ISSUE TITLE
是否服务器只能架设frps，我把自己博客放在上面就不行？

### ISSUE THREAD

**Issue by sxyh2020** [fatedier/frp#2133]
我的服务器上有我的博客和邮箱，看到r2s上有个Frp，就想搞一搞内网穿透，没想到按教程上设置，访问frp.xxxx.com，居然也是访问到我博客的，这让我很费解。
我服务器是用宝塔管理的，上面有三个网站，默认www前缀的是去博客，roobt的前缀是去爬虫，我解析了一个frp记录到服务器上，并且在安全设置中开放了7000端口，希望通过访问frp.xxxx.com，然后就进入r2s的后台管理页面。测试成功后，还希望能够访问家里联想个人云的文件，联想自带的文件分享功能会限速到1Mb/s，话说这一操作是否本身就不可行？我按文档配置的参数，启动Frps和Frpc之后，有时候是跳转到博客主页，有时候是就直接不通。

**Comment by yuyulei** [comment]
第一段说，“访问frp.xxxx.com，居然也是访问到我博客的”
第二段说，“希望通过访问frp.xxxx.com，然后就进入r2s的后台管理页面。测试成功后”，
感觉你前后矛盾，我疑惑的是，你访问 frp.xxx.com 到底得到的是什么页面？
----------------------------------
能否提供下:
1. frp 的配置
2. frps 和 frpc 是部署在同一台服务器上吗？
3. 你的这些 web 服务部署在该服务器上，分别监听哪些端口？
4. 描述下触发异常的步骤，比如说从浏览器访问 xxx，预期是 yyy，但是却是 zzz 等。

**Comment by sxyh2020** [comment]
> 第一段说，“访问frp.xxxx.com，居然也是访问到我博客的”
> 第二段说，“希望通过访问frp.xxxx.com，然后就进入r2s的后台管理页面。测试成功后”，
> 感觉你前后矛盾，我疑惑的是，你访问 frp.xxx.com 到底得到的是什么页面？
> 
> 能否提供下:
> 
> 1. frp 的配置
> 2. frps 和 frpc 是部署在同一台服务器上吗？
> 3. 你的这些 web 服务部署在该服务器上，分别监听哪些端口？
> 4. 描述下触发异常的步骤，比如说从浏览器访问 xxx，预期是 yyy，但是却是 zzz 等。


frps.ini 配置信息（部署腾讯云的服务器上，宝塔开放了7000端口，访问pan.XXX.top 到的是  www.XXX.top 即我的博客主页）

[common]
bind_addr = 0.0.0.0
bind_port = 7000
dashboard_port = 7500
token = 10XXX70
subdomain_host = pan.XXX.top
dashboard_user = admin
dashboard_pwd = 10XXX70
vhost_http_port = 10080
vhost_https_port = 10443

r2s 配置信息（见截图）

https://wx2.sinaimg.cn/mw690/9c4ea27dgy1glfonztrowj20oa0lkh9d.jpg
https://wx4.sinaimg.cn/mw690/9c4ea27dgy1glfonzw56gj20p80nn1kx.jpg

我希望在外网能通过访问  pan.XXX.top：7000  到  内网的  http://192.168.2.1/

**Comment by BecodReyes** [comment]
是否配置了nginx反代？
是否使用了泛匹配到博客的vhost？
是否正确配置frpc？

7000端口为frp的通信端口！
请确认看完手册后尝试重新配置！
不要使用新浪图床，这会被403！

**Comment by sxyh2020** [comment]
终于弄通了

frps.ini 配置信息

[common]
bind_port = 7000
vhost_http_port = 10080
vhost_https_port = 10443
dashboard_port = 7001
dashboard_user = admin
dashboard_pwd = 10XXXX70
token = 100XXXX70
subdomain_host = yun.XXXX.top

r2s 配置信息

服务器 123.XXX.XXX.211 # 服务器的ip
端口 7000
令牌 10XXXX70  # token的参数
HTTP穿透服务端口10080
HTTPS穿透服务端口10443
服务注册间隔15

Frp 协议类型 http
域名类型：自定义域名
自定义域名：yun.XXXX.top
内网主机地址：192.168.2.1
内网主机端口：80
Proxy-Protocol 版本：停用
开启数据加密 √
使用压缩 √

访问
yun.XXXX.top：10080

就到了

192.168.2.1：80


之前不行可能是我啥参数没用对

**Comment by yuyulei** [comment]
@sxyh2020 你现在 frps 和 r2s 是部署在同台服务器上吗？看你配置都是监听的 7000 端口。

**Comment by rhwong** [comment]
@sxyh2020 frps的vhost_http_port项配置到了10080
你访问frp.xxx.top是相当于访问了80端口，而你的frp代理监听的端口是10080
改成80就解决了

**Comment by rhwong** [comment]
没用过r2s，你那个图也打不开
如果是普通的frpc配置应该这样写

```
[r2s]
type = http
local_port = 80 #本地需要穿透的端口
remote_port = 80 #在远程访问时的端口
custom_domains = frp.xxx.top #绑定的域名
```
所以你在frps中应该配置
vhost_http_port = 80
vhost_https_port = 443

r2s配置里

HTTP穿透服务端口80
HTTPS穿透服务端口443

Frp 协议类型 http
域名类型：自定义域名
自定义域名：yun.XXXX.top
内网主机地址：192.168.2.1
内网主机端口：80

**Comment by rhwong** [comment]
所以你访问80，应该是被nginx给优先了
如果还是不行，那你可以试试不改变你现有的配置情况下（即vhost_http_port = 10080）
在nginx里添加对yun.xxx.top的反向代理到127.0.0.1:10080
