### ISSUE TITLE
Client 端提供 WEB GUI，用户可以在其中动态增加、修改配置。

### ISSUE THREAD

**Issue by HaujetZhao** [fatedier/frp#2134]
**The solution you want**

Client 端提供 WEB GUI，用户可以在其中动态增加、修改配置。

目前所有的配置都要手动修改文件，一个字的偏差都可能让某项发生错误。为了方便新手上手以及用户维护，建议在 Client 端提供一个 WEB GUI，可以方便地填写配置、动态修改配置。

（不重启就动态修改配置好像有些困难）

**Alternatives considered**

**How to implement this function**

**Application scenarios of this function**

**Comment by fatedier** [comment]
Try this
https://github.com/fatedier/frp#admin-ui

**Comment by HaujetZhao** [comment]
> Try this
> https://github.com/fatedier/frp#admin-ui

这只是 server 端的吧，有监控作用。希望有 client 端的可以增、修、减配置文件的 web gui。

**Comment by saixin** [comment]
[web1]
type = http
local_ip = 127.0.0.1
local_port = 1111
locations = /
客户端配置文件可以用其它程序语言动态添加修改站点吗？是通过查找匹配字符串方式去修改吗？

**Comment by ZhangJiaLei123** [comment]
我在仓库的/web目录下看到了frpc,是有客户端的面板么?但是不知道怎么启动和入口

**Comment by fatedier** [comment]
@ZhangJiaLei123 
Try this
https://github.com/fatedier/frp#admin-ui

**Comment by ZhangJiaLei123** [comment]
@fatedier 这个我看到了,是服务端的面板,请问知道frpc客户端的面板么?

**Comment by ZhangJiaLei123** [comment]
@fatedier 谢谢，server和客户端的配置是一样的，已经测试通过

**Comment by ZhangJiaLei123** [comment]
我将frpc的面板做以下设置：穿透后，无法通过外网访问frpc的面板
```
admin_addr = 0.0.0.0
```
