### ISSUE TITLE
可以支持M1芯片的MacBook吗？

### ISSUE THREAD

**Issue by jimmyqum** [fatedier/frp#2135]
macOS ARM64架构

**The solution you want**

**Alternatives considered**

**How to implement this function**

**Application scenarios of this function**

**Comment by fatedier** [comment]
It can be supported when go1.16 is released.

**Comment by witer55** [comment]
go1.16 would not release until 2021-02.

**Comment by YUX** [comment]
Go 1.16 Beta 1 is released with apple m1 supported 
https://groups.google.com/g/golang-announce/c/2-Rj3P5uRLs/m/mYxD2RJkAQAJ?pli=1

**Comment by YUX** [comment]
#2158
