### ISSUE TITLE
这个开源项目就是一个勒索病毒，我的服务器已经中招，请大家不要使用。

### ISSUE THREAD

**Issue by weiwangda2014** [fatedier/frp#2139]
昨天开始中毒，所有文件名称含有squadhack@email.tg，造成重大损失。

**Comment by fatedier** [comment]
麻烦请理解一下什么叫做开源项目。

如果开源项目是一个勒索病毒，还会有这么多人用，这么多人看着这些代码都没法发现？Fork 了 接近 8000 次，得有多么强大的能力才能做到让别人发现不了？

开放平台，每个人都要对自己的发言负责任。如果你受到了重大损失，我个人表示理解，但是也请不要随意诋毁别人的成果，先尝试从自己身上找一找是否存在其他原因，是否在没有安全防护的情况下暴露了内网的其他服务，而不是没有任何依据的情况下就先怀疑一个已经持续开发迭代了五年的开源项目。就和自己写应用，出现了问题，先怀疑是否是内核 bug 一样。

**Comment by kenser** [comment]
楼主，你是真的欠喷，说话不经过大脑思考吗？你这样的issues真的很low唉，能别给中国人丢脸吗？

**Comment by 1265578519** [comment]
不帮人家排查问题还说给中国人丢脸？我看你才是吧

**Comment by fatedier** [comment]
![image](https://user-images.githubusercontent.com/7346661/101757474-2b7d1580-3b12-11eb-9ba1-eced97fd0dab.png)

@1265578519 在开源社区，还是遵守开源社区的规范，本项目使用 APLv2 的协议分发。此协议不限制商业用途，也没有责任和义务保证使用者如何使用此项目，对因此造成的后果，也不由此项目维护社区承担。

欢迎友好的提出问题，共同探讨解决问题。但是在不搞清楚背景，缺乏一些开源基础知识的情况下，发表一些不适当的言论，我个人觉得没有必要再去热情地沟通，帮助其解决问题。

**Comment by zchazc** [comment]
这种没有给出任何信息且看起来有点蠢的话语，感觉更像是单纯的泼脏水行为，会不会是利益相关方做的？

**Comment by fatedier** [comment]
言尽于此。
