### ISSUE TITLE
http 连接除了 8080 端口外均不可连接

### ISSUE THREAD

**Issue by lotc** [fatedier/frp#214]
（我也不知道问题出现在哪里，极有可能无法重现）
- 服务器：Ubuntu 16.04 x64
- 客户端：Windows 10 x64
- 访问测试环境：Windows 10 x64 chrome 电信线路，Android 6.0 opera mini 联通 lte 线路

服务器 ini 内容：
```
[common]
bind_port = 7000
vhost_http_port = 8081
[web]
type = http
custom_domains = frp.我的域名.com
auth_token = 123
```

客户端 ini 内容：
```
[common]
server_addr = 我服务器的IP
server_port = 7000
auth_token = 123
[web]
type = http
local_port = 80
```

此时两方终端均显示连接成功。
但访问 frp.我的域名.com:8081 时无法显示客户端 80 端口 host 的一个网页。

当服务器端 ini 下的 vhost 端口改成 8080，然后再访问 frp.我的域名.com:8080 则可以显示。

**Comment by fatedier** [comment]
先检查下是否是防火墙的原因，然后使用 8081 启动时看下日志中是否有报错信息。

**Comment by lotc** [comment]
添加了 dashboard 项，dashboard 无论设置任何端口都可以访问，而且 dashboard 里面也显示 http working。同时，两方日志完全均没有报错。
应该是个别问题，机器上安装软件也很多，无法一一排查，可能要换一台客户端或者换成 Linux 平台再测试了。

谢谢你开发如此优秀的软件！

**Comment by qimo2020** [comment]
刚测试了下，我的也是这种情况，除8080端口，其它端口均失败

**Comment by qimo2020** [comment]
> 刚测试了下，我的也是这种情况，除8080端口，其它端口均失败

已解决！总结导致此问题出现的原因有:
1. 服务器端口未放行（防火墙）；
2. 非8080端口，type参数值必须填写！（比如我用域名访问，必须为http）
