### ISSUE TITLE
客户端报这个错

### ISSUE THREAD

**Issue by 2019jack** [fatedier/frp#2142]
2020/12/09 14:29:08 [E] [control.go:147] [4d7215d96cb6c603] work connection closed before response StartWorkConn message: EOF
2020/12/09 14:29:08 [E] [control.go:147] [4d7215d96cb6c603] work connection closed before response StartWorkConn message: EOF
2020/12/09 14:29:08 [E] [control.go:147] [4d7215d96cb6c603] work connection closed before response StartWorkConn message: EOF
2020/12/09 14:29:08 [E] [control.go:147] [4d7215d96cb6c603] work connection closed before response StartWorkConn message: EOF
2020/12/09 14:29:08 [E] [control.go:147] [4d7215d96cb6c603] work connection closed before response StartWorkConn message: EOF
2020/12/09 14:29:08 [E] [control.go:147] [4d7215d96cb6c603] work connection closed before response StartWorkConn message: EOF
2020/12/09 14:29:08 [E] [control.go:147] [4d7215d96cb6c603] work connection closed before response StartWorkConn message: EOF
2020/12/09 14:29:08 [E] [control.go:147] [4d7215d96cb6c603] work connection closed before response StartWorkConn message: EOF
2020/12/09 14:29:08 [E] [control.go:147] [4d7215d96cb6c603] work connection closed before response StartWorkConn message: EOF
2020/12/09 14:29:08 [E] [control.go:147] [4d7215d96cb6c603] work connection closed before response StartWorkConn message: EOF
2020/12/09 14:29:08 [E] [control.go:147] [4d7215d96cb6c603] work connection closed before response StartWorkConn message: EOF

@fatedier 你好我客户端报这个错，是什么什么原因？

**Comment by yuyulei** [comment]
请参考 issue 模板提供更详细的说明。

**Comment by 2019jack** [comment]
好滴

**Comment by shenlijun** [comment]
PHP相关的问题，作者好像说要把这些log去掉了
实际不影响使用

**Comment by 2019jack** [comment]
是滴，不怎么影响使用
