### ISSUE TITLE
在路由器上运行frps出现错误

### ISSUE THREAD

**Issue by shech25** [fatedier/frp#2146]
# ./frps -c ./frps.ini
futexwakeup addr=0xc16354 returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc160d8 returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc160d8 returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc160d8 returned -89
fatal error: unexpected signal during runtime execution
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
fatal error: unexpected signal during runtime execution
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc16354 returned -89
fatal error: unexpected signal during runtime execution
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
fatal error: unexpected signal during runtime execution
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
fatal error: unexpected signal during runtime execution
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
fatal error: unexpected signal during runtime execution
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
fatal error: unexpected signal during runtime execution
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
futexwakeup addr=0xc27a8c returned -89
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violationfutexwakeup addr=0xc27a8c returned -89
fatal error: unexpected signal during runtime execution
panic during panic
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x4b194]

runtime stack:
runtime.throw(0x6fb6de, 0x2a)
        runtime/panic.go:1116 +0x60
runtime.sigpanic()
        runtime/signal_unix.go:726 +0x554
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:69 +0x8c
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.dopanic_m(0xc15fe0, 0x4ed8c, 0x7fef5648, 0x51078)
        runtime/panic.go:1299 +0xa4
runtime.fatalthrow.func1()
        runtime/panic.go:1171 +0x6c
runtime.fatalthrow()
        runtime/panic.go:1168 +0x48
runtime.throw(0x6fb6de, 0x2a)
        runtime/panic.go:1116 +0x60
runtime.sigpanic()
        runtime/signal_unix.go:726 +0x554
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:69 +0x8c
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.futexwakeup.func1()
        runtime/os_linux.go:66 +0xb4
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:65 +0x84
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.futexwakeup.func1()
        runtime/os_linux.go:66 +0xb4
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:65 +0x84
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.futexwakeup.func1()
        runtime/os_linux.go:66 +0xb4
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:65 +0x84
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.futexwakeup.func1()
        runtime/os_linux.go:66 +0xb4
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:65 +0x84
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.futexwakeup.func1()
        runtime/os_linux.go:66 +0xb4
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:65 +0x84
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.throw.func1()
        runtime/panic.go:1110 +0x88
runtime.throw(0x6fb6de, 0x2a)
        runtime/panic.go:1109 +0x40
runtime.sigpanic()
        runtime/signal_unix.go:726 +0x554
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:69 +0x8c
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.futexwakeup.func1()
        runtime/os_linux.go:66 +0xb4
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:65 +0x84
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.futexwakeup.func1()
        runtime/os_linux.go:66 +0xb4
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:65 +0x84
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.futexwakeup.func1()
        runtime/os_linux.go:66 +0xb4
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:65 +0x84
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.futexwakeup.func1()
        runtime/os_linux.go:66 +0xb4
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:65 +0x84
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.futexwakeup.func1()
        runtime/os_linux.go:66 +0xb4
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:65 +0x84
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.futexwakeup.func1()
        runtime/os_linux.go:66 +0xb4
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:65 +0x84
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.futexwakeup.func1()
        runtime/os_linux.go:66 +0xb4
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:65 +0x84
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.futexwakeup.func1()
        runtime/os_linux.go:66 +0xb4
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:65 +0x84
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.throw.func1()
        runtime/panic.go:1110 +0x88
runtime.throw(0x6fb6de, 0x2a)
        runtime/panic.go:1109 +0x40
runtime.sigpanic()
        runtime/signal_unix.go:726 +0x554
runtime.futexwakeup(0xc27a8c, 0x1)
        runtime/os_linux.go:69 +0x8c
runtime.unlock2(0xc27a8c)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.printunlock()
        runtime/print.go:80 +0x74
runtime.futexwakeup.func1()
        runtime/os_linux.go:66 +0xb4
runtime.futexwakeup(0xc160d8, 0x1)
        runtime/os_linux.go:65 +0x84
runtime.unlock2(0xc160d8)
        runtime/lock_futex.go:120 +0xc4
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:37
runtime.unlock(...)
        runtime/lock_futex.go:111
runtime.exitsyscallfast_pidle(0x775b2f48)
        runtime/proc.go:3371 +0xd0
runtime.exitsyscallfast.func1()
        runtime/proc.go:3322 +0x4c
runtime.systemstack(0x8a380)
        runtime/asm_mipsx.s:207 +0x9c
runtime.mstart()
        runtime/proc.go:1116

goroutine 1 [syscall, locked to thread]:
syscall.Syscall6(0x10ca, 0xffffff9c, 0x10a4000, 0x10a2000, 0x80, 0x0, 0x0, 0x22, 0x2, 0x0)
        syscall/asm_linux_mipsx.s:43 +0x10 fp=0x102a6c8 sp=0x102a6b0 pc=0xa3c40
syscall.readlinkat(0xffffff9c, 0x6e9529, 0xe, 0x10a2000, 0x80, 0x80, 0x9bd1c, 0x8, 0x66c100)
        syscall/zsyscall_linux_mips.go:90 +0xb8 fp=0x102a708 sp=0x102a6c8 pc=0xa089c
syscall.Readlink(...)
        syscall/syscall_linux.go:164
os.Readlink(0x6e9529, 0xe, 0x11337c, 0x66c100, 0x10820d8, 0x10820d0)
        os/file_unix.go:368 +0x94 fp=0x102a740 sp=0x102a708 pc=0x11177c
os.glob..func1(0x6f1b6e, 0x1c, 0x8e3b50, 0x10820d8)
        os/executable_procfs.go:29 +0x48 fp=0x102a75c sp=0x102a740 pc=0x1131b4
os.init()
        os/executable_procfs.go:30 +0x1c8 fp=0x102a770 sp=0x102a75c pc=0x1133ac
runtime.doInit(0xbb4e60)
        runtime/proc.go:5646 +0xcc fp=0x102a784 sp=0x102a770 pc=0x61c94
runtime.doInit(0xbb5e60)
        runtime/proc.go:5641 +0x80 fp=0x102a798 sp=0x102a784 pc=0x61c48
runtime.doInit(0xbb2be0)
        runtime/proc.go:5641 +0x80 fp=0x102a7ac sp=0x102a798 pc=0x61c48
runtime.doInit(0xbb56e0)
        runtime/proc.go:5641 +0x80 fp=0x102a7c0 sp=0x102a7ac pc=0x61c48
runtime.main()
        runtime/proc.go:191 +0x1f4 fp=0x102a7ec sp=0x102a7c0 pc=0x524ac
runtime.goexit()
        runtime/asm_mipsx.s:651 +0x4 fp=0x102a7ec sp=0x102a7ec pc=0x8c7b4
futexwakeup addr=0xc27afc returned -89
fatal error: unexpected signal during runtime execution
stack trace unavailable

**Comment by kangyasong** [comment]
老哥是mips架构么？我也遇到这个问题，本来想做插件在网关上跑使用这个frp做个内网穿透，死活跑不起来，，，是环境问题吧？

**Comment by yuyulei** [comment]
不是很懂这一块，有操作教程吗？我也了解和学习下。

**Comment by ywz978020607** [comment]
> 老哥是mips架构么？我也遇到这个问题，本来想做插件在网关上跑使用这个frp做个内网穿透，死活跑不起来，，，是环境问题吧？

路由器跑frpc还是server啊，server的话，你们有公网ip？

**Comment by zsinba** [comment]
不建议你在路由上面跑. 会出问题.
我在openwrt上面跑了一段时间,老是出问题.
要么把路由搞死子.要么FRPS死了.
猜测原因应该是路由器的配置比较弱,造成负载过大.

我尝试了lede和luc.都是一样的结果 .
