### ISSUE TITLE
shh连接 输入密码后access denied

### ISSUE THREAD

**Issue by liuzhaoo** [fatedier/frp#2151]
**[REQUIRED] hat version of frp are you using** 

Version:0.34.3

**[REQUIRED] What operating system and processor architecture are you using**
OS:ubuntu
CPU architecture:xeon

**[REQUIRED] description of errors**
服务器端和本地都配置好了文件，使用ssh连接本地机器时在输入密码后提示access denied

**confile**

**log file**

**Steps to reproduce the issue**
1. 
2. 
3. 

**Supplementary information**

**Can you guess what caused this issue**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by yuyulei** [comment]
请提供你的配置和你执行的操作，甚至日志。
