### ISSUE TITLE
支持相同域名不同端口的配置嘛?

### ISSUE THREAD

**Issue by openbytes** [fatedier/frp#2154]
`[example]
type = http
local_port = 80
custom_domains = www.example.com

[example2]
type = http
local_port = 20030
custom_domains =  www.example.com`

**Comment by yuyulei** [comment]
目前针对 http 形式的 proxy，通过共用端口（vhost_port）并以域名来做路由实现，暂时支持不了你这种需求。如果你不需要 http 层面的特性，可以同 tcp 来代替，tcp 支持自己指定端口。

**Comment by openbytes** [comment]
好的.谢谢您.大佬.我目前是启用两个配置文件,启动两个frpc进程来进行同域名代理的.
