### ISSUE TITLE
frp native build on Apple M1 (go1.16beta1 )

### ISSUE THREAD

**Issue by YUX** [fatedier/frp#2158]
download link [frp_0.34.3_darwin_arm64.tar.gz](https://drive.google.com/file/d/1MUoTgMiEzM_prA06vkk5jeurk9EEsiLW/view?usp=sharing)

ref: https://groups.google.com/g/golang-announce/c/2-Rj3P5uRLs/m/mYxD2RJkAQAJ

**Comment by shenlijun** [comment]
很少有反向代理到笔记本的需求吧

**Comment by YUX** [comment]
> 很少有反向代理到笔记本的需求吧

可以共享本地的minecraft😂 也可以远程访问

**Comment by shenlijun** [comment]
> > 很少有反向代理到笔记本的需求吧
> 
> 可以共享本地的minecraft😂 也可以远程访问

笔记本不是经常带在身边么？
何不在家里直接专门放个不是M1的机器搞

**Comment by Codle** [comment]
> > > 很少有反向代理到笔记本的需求吧
> > 
> > 
> > 可以共享本地的minecraft😂 也可以远程访问
> 
> 笔记本不是经常带在身边么？
> 何不在家里直接专门放个不是M1的机器搞

stcp 需要本地也运行一个 frpc 呀

**Comment by neatstudio** [comment]
确实需要，有时候给客户演示的时候，就是共享在本地了、
