### ISSUE TITLE
frp 能否http代理

### ISSUE THREAD

**Issue by youerning** [fatedier/frp#216]
比如有两台机器，a不能上网，b能上网但是，b能连接a。
我试了下面的方式。
a机器作为frp server。
[common]
bind_port = 7000

[f]
type = tcp
listen_port = 60000
auth_token = 123

b作为frp client。
[common]
server_addr = xxx.x.x.x
server_port = 7000
auth_token = 123

[f]
type = tcp
local_ip = mirrors.aliyun.com
local_port = 80
在本机上测试有问题，telnet能访问，但是浏览器不能访问。
虽然可以通过VPN或者其他代理的方式，但是frp看起来更简单，所以问问^_^

**Comment by fatedier** [comment]
阿里云的服务器可能会检查 host 之类的，直接用 tcp 转发不一定可以。

你这个需求是需要在 b 服务器上部署一个正向的 http 代理，目前还不支持。

**Comment by fatedier** [comment]
可能之后在 frpc 上会集成一个简单的 http 代理，也能用来翻墙。

**Comment by Yovanchen** [comment]
希望可以集成一个简单的HTTP代理，翻墙更容易。

**Comment by fatedier** [comment]
会有的。另外我把关键字删了，感觉最好不要出现关键字，避免被和谐~

**Comment by yydcool** [comment]
@fatedier 感觉这个功能有点多余
可以直接在tcp转发的基础上加一层shadowsocks，这样既有了http代理又有socks5代理

**Comment by fatedier** [comment]
从我个人的角度考虑，这个需求还是很明显的。

我在考虑用什么方式来实现一种插件机制，不止是 http 代理，可能是一个 web server 或者其他的处理插件。简单的代码量不大的插件可以内置。

**Comment by yydcool** [comment]
是要在frpc上（client端）实现插件机制吗？
我的理解是，现在tcp请求发起的方向是 A -> frps -> NAT Network -> frpc ->B
路径终点B可以是任何服务，可以是shadowsocks server或http proxy server或web server。
因此只要tcp可以建立，这些上层的服务都可以套在frp上

**Comment by fatedier** [comment]
是的，这样的话，需要部署另外的服务，然后通过 tcp 通信。如果是插件机制的话，就不用走 tcp 了，直接处理网络请求就可以。

**Comment by yydcool** [comment]
还好吧，我现在嵌套了shadowsocks+frp+kcptun。其实本地进程间用socket通信效率很高的。

**Comment by fatedier** [comment]
这个效率其实很低，一个需要 io，且需要走内核 tcp/ip 协议栈，封包拆包，一个直接处理数据~ 当然对大多数人来说可能无所谓。插件的机制就是提供一种选择，我的目的是尽量让使用简单化，也并不强制去如何使用，你还是可以按照现有的方式运行你的服务。

**Comment by Yovanchen** [comment]
如果一个frp就可以实现所需要的基本代理，那我也不用折腾了。像我这种小白，只要frpc打开，随便设置一下，什么都搞定了，安安稳稳用。我是小白，我考虑最便捷的使用。

**Comment by fatedier** [comment]
0.11.0 版本支持了内置的 http_proxy。
