### ISSUE TITLE
服务端为啥拒绝客户端连接？connectex:No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by mmmyoung** [fatedier/frp#2161]
之前还能好好使用内网穿透，突然就不能访问web服务了，然后客户端报错：connectex:No connection could be made because the target machine actively refused it，有大佬知道为啥服务端会拒绝请求吗。

**Comment by nxuu** [comment]
难道是frps所在服务器的服务商搞的鬼？还是安全策略的问题？

**Comment by mmmyoung** [comment]
发现是我的web服务死了，无响应




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mosike"<notifications@github.com&gt;; 
发送时间: 2020年12月24日(星期四) 上午7:38
收件人: "fatedier/frp"<frp@noreply.github.com&gt;; 
抄送: "??当你老了??"<1272209008@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fatedier/frp] 服务端为啥拒绝客户端连接？connectex:No connection could be made because the target machine actively refused it (#2161)





 
难道是frps所在服务器的服务商搞的鬼？还是安全策略的问题？

**Comment by Yuanlaishiaqi** [comment]
问一下问什么我ssh连接都设置好了  还是提示拒绝连接 端口也放行了 大佬方便吗

**Comment by DingPlaysMC** [comment]
我也是frp出问题了，同样报错，有没有大佬教我如何设置
