### ISSUE TITLE
frpc.exe被ESET识别为木马

### ISSUE THREAD

**Issue by masterclock** [fatedier/frp#2162]
﻿时间;扫描程序;对象类型;对象;检测;操作;用户;信息;哈希;此处首次所见
2020/10/29 8:18:22;文件系统实时防护;文件;D:\tmp\frp_0.33.0_windows_amd64\frpc.exe;Win64/HackTool.Agent.AM 特洛伊木马 的变量;已通过删除清除;NT AUTHORITY\SYSTEM;尝试通过应用程序访问文件时发生事件: C:\Windows\System32\CompatTelRunner.exe (D562D36F3F1AB5F1C96D6532DFDBEEDC12491CE1).;C94A0F902B3B8CC4CA5E4CC9004AC9EAA4614699;2020/8/22 21:50:26

**Comment by fatedier** [comment]
Duplicate of https://github.com/fatedier/frp/issues/2095
