### ISSUE TITLE
如何删除服务器dashboard里失效的内网穿透

### ISSUE THREAD

**Issue by zhengfan2014** [fatedier/frp#2164]
**The solution you want**

删除frp dashboard里失效的穿透
**Alternatives considered**

**How to implement this function**

加个删除按钮
**Application scenarios of this function**

治疗强迫症

**Comment by yuyulei** [comment]
一方面，因为失效的代理是 frpc 发起的，担心出现，在 frps 端删除了代理，但是 frpc 端因为重启或者 reload 等又将删除的代理加了回来，造成一种明明刚删又回来了的现象。

另一方面，现在对代理的管理还处于比较简单的方式，如果以后有了统一管理的地方，可能会考虑做这类功能，但是近期内应该没有计划。

**Comment by fatedier** [comment]
It will be auto deleted after 7 days.

**Comment by zngw** [comment]
强迫症+1，每次都是restart frps

**Comment by i-iooi-i** [comment]
确实，在7500管理页面看到了一长串失效的端口。。。。。难受

**Comment by baymax55** [comment]
> It will be auto deleted after 7 days.

can I customize the settings?
