### ISSUE TITLE
阿里云报恶意进程（云查杀）-黑客工具

### ISSUE THREAD

**Issue by siwliwuhen** [fatedier/frp#2171]
描述: 检测到服务器上存在可疑黑客工具，可能是黑客入侵过程中用于权限提升、窃取敏感数据的工具，或用于卸载安全软件的程序，或入侵后植入系统的后门程序。

**Comment by fatedier** [comment]
你希望能够怎么处理？为什么不是给阿里云提工单？

**Comment by cuichaohui** [comment]
> 你希望能够怎么处理？为什么不是给阿里云提工单？

没有别的意思，我是想说这个问题是软件得问题还是阿里云限制这个程序

**Comment by fatedier** [comment]
你购买了阿里云的服务，遇到的任何问题是否应该给阿里云提工单或者要求他们给你提供服务解决你的问题？
