### ISSUE TITLE
下载大文件阻塞其它传输，导致其它网页响应变慢，有偿请求解答

### ISSUE THREAD

**Issue by fycatfan** [fatedier/frp#2172]
如果内网穿透下载一个比较大的文件，发现同一个网站别的网页的访问速度就会变慢。停止下载后速度明显又上来了，请问怎么设置可以缓解这个问题？

**Comment by qianyuqianhe** [comment]
吃掉上传导致其他变慢？依据带宽限速不知道能不能缓解。

**Comment by yuyulei** [comment]
frps 所在机器是怎么样的？它的网络有监控吗？那段时间的出入带宽如何？

**Comment by fatedier** [comment]
@fycatfan frp 层面无法有效解决这个问题，对于同一个网站，没法做到根据不同的请求路径来进行限速。如果有可能的话，还是需要你在自己的内网服务里去做这个事情，比如提供下载大文件的限速能力。

**Comment by fycatfan** [comment]
后来我找到原因了，是因为我上下行下行用的都是家里的wifi，是无线信号形成了阻塞

**Comment by fycatfan** [comment]
不是软件的原因，谢谢大家
