### ISSUE TITLE
Webserver Reachable Locally but not over Proxy Adress

### ISSUE THREAD

**Issue by Blizzard929** [fatedier/frp#2173]
**[REQUIRED] hat version of frp are you using** 

Version: v0.34.3

**[REQUIRED] What operating system and processor architecture are you using**
OS: Linux ubuntu 20.04
CPU architecture: AMD Ryzen

**[REQUIRED] description of errors**
Website is locally reachable over 192.168.0.51 without problems
but when trying to reach the website over the proxys ipadress it doesnt work at all
no errors are givin in the proxy console

**confile**

[web]
type = tcp
local_ip = 192.168.0.51
local_port = 80
remote_port = 80

**log file**

https://pastebin.com/XVuH19a7

**Supplementary information**
I used Apache2 and Nginx but issue on both
There is also currently a netdata server online what is also a webserver on port 19999 what works partally 
http://www.auroraserver.de is the website that doesnt work
netdata with the same options just port 19999 work partially
http://www.auroraserver.de:19999

**Can you guess what caused this issue**
Maybe bad configuration or a port misunderstanding

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by fatedier** [comment]
Your configures make a port forwarder from `frps ip:80` to `192.168.0.51:80`.

When you visit `frps ip:80`, the network traffic will be transfered to local service.

**Comment by Blizzard929** [comment]
Yes thats sure and its configures correctly like that.

But, i can reach my Webserver on 192.168.0.51:80 , but i cant reach it over the frps ip:80
so somethings seems wrong and i dont know what.

**Comment by fatedier** [comment]
I haven't seen your error log. Did you paste all your logs?

**Comment by fatedier** [comment]
You can deploy frpc and frps in the same machine to test if you have an mistake in your configures.

**Comment by Blizzard929** [comment]
Issue Finnaly Resolved after reinstalling the whole server os....
