### ISSUE TITLE
请教大家一个问题

### ISSUE THREAD

**Issue by kiligao** [fatedier/frp#2174]
本地服务器配置了https证书，3个服务，不同https端口
使用frp，配置不同二级域名
出现的情况是：浏览器先打开一个https二级域名，再打开另一个不同的https二级域名，但是两个页面显示的是同一个网页。
http就不会出现这种状况。
现在想请教大家怎么处理，能指定端口访问https吗？或者有其他的方法吗？
谢谢大家！！！

**Comment by yuyulei** [comment]
方便贴下配置文件吗？
