### ISSUE TITLE
udp proxy在空闲一段时间之后，无法正常工作。

### ISSUE THREAD

**Issue by goer99** [fatedier/frp#218]
过程描述：

1. 启动frps；
2. 启动frpc；查看frps 和frpc的log，确认已经连上；
3. 第三方使用udp proxy，工作正常；
4. 以上3步骤都是接连进行的，间隔时间不超过5分钟；
5. 第三方停止使用udp proxy；
6. 过20分钟。
7. 第三方使用udp proxy，无响应；

建议：

log记录中增加proxy（frps，frpc）对第三方（proxy使用方）的消息处理记录，例如收/发情况，转发情况等。

**Comment by goer99** [comment]
回看frps的log，在维持heartbeat期间，有数次如下记录：

2017/01/08 19:29:58 [control.go:163] [D] ProxyName [abc], get heartbeat
2017/01/08 19:30:05 [server.go:368] [W] ProxyName [abc], work connection for udp closed
2017/01/08 19:30:08 [control.go:163] [D] ProxyName [abc], get heartbeat
2017/01/08 19:30:12 [server.go:395] [D] ProxyName [abc], write to work connection for udp error: write tcp x.x.x.x:6000->y.y.y.y:33836: write: broken pipe
2017/01/08 19:30:18 [control.go:163] [D] ProxyName [openvpn], get heartbeat

**Comment by fatedier** [comment]
参考 #206，感觉这样的应用并不适用。

**Comment by goer99** [comment]
我的应用场景和#206完全不同。我的使用场景是frp + vpn

#206 的 n2n 其实是一个udp打洞工具 + vpn。这个n2n需要每个使用者都安装n2n的节点。

而frp是一个多协议反向proxy，并不带vpn功能。frp不需要每个使用者都安装frp。

另外，#206的用法应该是错的。如果用了n2n，就根本用不着frp。n2n的supernode貌似也必须是公网ip。

我单独试试n2n看看。

**Comment by fatedier** [comment]
我的意思是如果 openVPN 使用 UDP 的方式，可能也需要感知到连接的 ip 和端口，而中间加了 frp 这个代理之后，这些信息会丢失，导致不能正常工作。

完全是猜测，因为不确定 openVPN 的具体工作原理。

**Comment by goer99** [comment]
frpc和frps刚刚连接上时，openVPN工作完全正常。只是当frpc和fprs之间idle一段时间，没有数据交换之后，再使用openVPN就无法连上了。

**Comment by fatedier** [comment]
因为 udp 是没有连接的，所以 frp 并不知道你发送的 udp 包之后，要多长时间才不需要继续读取数据。所以目前转发 udp 包时设置了一个超时，超过 2 分钟之后，仍然没有读取到对方发送的数据就会退出。这样对方就无法再主动给你发送数据。

不知道是不是这个地方有影响，通常要维护 udp 的 ”连接“，需要主动发送心跳，因为 NAT 设备上的 UDP 转发表应该也会定期清除的。

你可以把 openVPN 的部署方式发我，我有时间可以测试下。

**Comment by goer99** [comment]
估计就是这个2分钟超时机制的设定引起的问题，无udp数据传输2分钟之后，判定为超时，udp proxy关闭。下次第三方想再次使用udp proxy时，就无法连接成功。

几点建议：

1. 能否将这个udp proxy超时退出的参数放到conf文件里呢？这样可以进一步测试验证。

2. 这个udp proxy的超时退出机制，不应该根据无upd数据传输的时间而判定超时，而应该根据无连接的时间判定超时。这意味着即使frpc和frps失去udp数据传输超过一定时间（使用udp proxy的第三方关闭连接），如果frpc和frps的心跳正常，那么这个udp proxy也不会超时退出，而继续活着，等待udp proxy使用方的下一次连接请求。

如果不是根据无连接时间来判定超时，而是根据无udp数据传输的时间来判定超时，则这个udp proxy必须在每次使用时重启，那么就失去其意义了。

**Comment by goer99** [comment]
frpc与frps之间的认证和心跳都是用的tcp协议，所以tcp proxy没有这个问题。只要有心跳存在，tcp proxy就会一直生存，而不会判定超时退出。即便出现网络问题连接不上，也会重连之后激活tcp proxy。

upd proxy也应该根据tcp心跳情况来决定udp proxy的生死，而不应该根据有无udp数据传输来决定udp proxy的生死。否则，udp proxy的心跳就没有任何意义。

**Comment by fatedier** [comment]
你这里有个问题理解错了，超时不是针对 udp proxy，而是单个 udp 请求。

比如 dns 查询，发送查询请求，客户端收到数据包之后就结束了，tcp 的话这里会主动发起关闭连接的操作。但是对于 udp 来说，你不 read 就行了，是没有连接的。这个操作交给 frp 中转的话，frp 不能感知到什么时候结束，所以必须要有超时机制来释放这部分资源。

**Comment by goer99** [comment]
对于udp proxy，看来需要有一个frps对frpc的唤醒机制。

当frpc 睡眠时（无udp连接时），若frps 收到第三方发起的udp数据请求，frps应立即唤醒frpc，frpc向frps重建udp通道，frps转发frpc与第三方的udp数据。

如果frp 在udp proxy上无法维持这种随时接收和响应第三方udp请求的状态，那么这个udp proxy的实用意义就没有了。

**Comment by fatedier** [comment]
1. 目前主动发起的 udp 请求在任何时候都应该正常。
2. 某次发送的 udp 请求，过了一段时间后，想继续接收到对方回复的消息，必须由客户端自己实现心跳。这个是 udp 的特点决定的。

你可以整理一下思路，目前你的理解和实际的问题并不一致，openVPN 的问题也不需要光猜测，还是复现定位问题比较方便。

**Comment by goer99** [comment]
你可以安装一下openVPN看看是否有这个问题。

openVPN的安装可以参考：

CenTos OpenVpn 一键安装包
http://www.myzhenai.com/thread-17453-1-1.html

如果脚本里面的资源包下载地址不可用，可能需要更换所需资源包的下载地址。

**Comment by 2726266496** [comment]
我也发现这个问题了，OpenVPN使用udp方式刚开始没有问题，过一段时间连接会超时，目前解决方法是使用**OpenVPN的tcp模式，frp也使用tcp方式**。使用了两三天了，没出现什么问题。
PS：原issue已关闭，在此感谢作者回复

**Comment by goer99** [comment]
没错。tcp proxy没有这个问题，只有udp proxy有这个问题。

frp作为tcp proxy非常不错，期待udp也能一样出色。

to 2726266496：
n2n你试验成功了吗？我做了若干次实验，edge们都可以成功连上supernode，但是无法做到network 2 network；各个edge上的路由表似乎都不生效。是tun的问题吗？

**Comment by luhanglei** [comment]
我也遇到了同样的问题，每次请求就是需要在公网发送一条UDP到我的内网里的某台设备，然后在很短的时间内，内网的设备回复回去。frpc刚运行的时候很稳定的可以使用。但隔了一晚上没有任何操作之后，TCP仍然正常，UDP就连接不上了。要重启frpc才可以。

**Comment by fatedier** [comment]
@goer99 可以尝试下 v0.10.0 版本，这个 issue 暂时关闭，如果新版本还有问题，麻烦另开 issue 反馈。
