### ISSUE TITLE
dashboard能否支持https？

### ISSUE THREAD

**Issue by wengzuyang** [fatedier/frp#2185]
目前dashboard用的是http，用户名和密码容易泄漏，能否支持https？

**Comment by yuyulei** [comment]
可能近期不支持。临时简单的做法有，可能前面架个 Nginx 接收 https，代理到 frp dashboard，你看是否可以？

**Comment by ax2009live** [comment]
你可以在服务器创建一个frpc客户端，
[common]
server_addr =  服务器的ip
server_port = 7000
token = 密码

[www.examda.com-443]
type = https
custom_domains = www.examda.com
#你的域名
plugin = https2http
plugin_local_addr = 服务器的ip:7500
#dashboard服务器的IP和端口
plugin_crt_path = /root/nginx/certs/fullchain.pem
plugin_key_path = /root/nginx/certs/key.pem
#证书位置，
#可以通过docker申请安装，可以通过crontab -e 增加每月定时执行这个动作；
plugin_host_header_rewrite = 127.0.0.1
plugin_header_X-From-Where = frp

https://www.examda.com 就可以访问 http://www.examda.com:7500

**Comment by wengzuyang** [comment]
> 你可以在服务器创建一个frpc客户端，（用docker安装一个frpc客户端）
> [common]
> server_addr = 服务器的ip
> server_port = 7000
> token = 密码
> 
> [www.examda.com-443]
> type = https
> custom_domains = [www.examda.com](http://www.examda.com)
> #你的域名
> plugin = https2http
> plugin_local_addr = 服务器的ip:7500
> #dashboard服务器的IP和端口
> plugin_crt_path = /root/nginx/certs/fullchain.pem
> plugin_key_path = /root/nginx/certs/key.pem
> #证书位置，
> #可以通过docker申请安装，可以通过crontab -e 增加每月定时执行这个动作；
> plugin_host_header_rewrite = 127.0.0.1
> plugin_header_X-From-Where = frp
> 
> https://www.examda.com 就可以访问 http://www.examda.com:7500

好主意，可以作为临时解决方案
