### ISSUE TITLE
An option to enable TCP KeepAlived for HTTP?

### ISSUE THREAD

**Issue by LauTrond** [fatedier/frp#2188]
**The solution you want**

Offer an option of type=http, enable TCP KeepAlived for HTTP

**Alternatives considered**

I found frps make every HTTP request with a single connection, even if both HTTP client and server support `Connection: keep-alive`
Then I look into vhost/http.go, looks like the vhost disable keep-alived for all requests: 
```
proxy := &ReverseProxy{
    ...
    Transport: &http.Transport{
        ...
        DisableKeepAlives: true
```

**How to implement this function**

**Application scenarios of this function**

We want FRP works faster of HTTP, don't we?

**Comment by fatedier** [comment]
It can't be supported now.

Go http package reuse connections by host. However, frp can route request by host and location(url path). If `DisableKeepAlives` is false, it will cause mistakes.

Leave this issue open here and we can consider how to achieve it later.

**Comment by LauTrond** [comment]
> It can't be supported now.
> 
> Go http package reuse connections by host. However, frp can route request by host and location(url path). If `DisableKeepAlives` is false, it will cause mistakes.
> 
> Leave this issue open here and we can consider how to achieve it later.

Thanks. Sounds like we need multiple *http.ReverseProxy for multiple destination?

**Comment by fatedier** [comment]
@LauTrond I have submited a PR https://github.com/fatedier/frp/pull/2199 about to fix this issue, you can try it now and help find if it has bug.
