### ISSUE TITLE
FRPC启动不了

### ISSUE THREAD

**Issue by Mrlinzh** [fatedier/frp#2190]
系统：Linux xuedinger 3.10.102 #15047 SMP Sat Feb 18 17:34:10 CST 2017 x86_64 GNU/Linux synology_bromolow_3615xs
用frp_0.31.2_linux_386或者frp_0.31.2_linux_amd64都是Segmentation fault

**Comment by Mrlinzh** [comment]
已解决

**Comment by BoneAsh** [comment]
群晖是吧，可以尝试使用docker的方式安装
