### ISSUE TITLE
更改监听地址

### ISSUE THREAD

**Issue by cloudwindy** [fatedier/frp#2191]
我需要把被代理的tcp监听地址从0.0.0.0调整为127.0.0.1（不对外公开），但我必须把frp协议对外公开，该如何操作？

**Comment by cloudwindy** [comment]
也就是说，我要从公网能访问frp的端口，但不能访问frp转发的端口，请问怎么实现？

**Comment by skyline20** [comment]
修改frps配置文件
bind_addr=0.0.0.0
proxy_bind_addr=127.0.0.1

**Comment by cloudwindy** [comment]
proxy_bind_addr居然没有在文档中出现诶，不打算做一个完整的配置文件参考手册吗

**Comment by fatedier** [comment]
@cloudwindy https://gofrp.org/docs/reference/server-configures/#%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE

**Comment by cloudwindy** [comment]
天，我居然没看到，是我的锅，抱歉
