### ISSUE TITLE
必须要配合nginx才能对服务器里的websocket进行内网穿透吗？
以下报错跟这点有关系吗？求指点

### ISSUE THREAD

**Issue by RussiaVk** [fatedier/frp#2193]
do http proxy request error: no such domain

do http proxy request error: backend tried to switch protocol "" when "websocket" was requested

**Comment by fatedier** [comment]
需要按照 Websocket 的请求方式发送请求，报错信息已经提示你了，需要 switch 的 protocol 是 websocket，但是你请求你传的是空值。

**Comment by fatedier** [comment]
Duplicate of #2189
