### ISSUE TITLE
在腾讯云服务器centos7上，添加service运行启动不了

### ISSUE THREAD

**Issue by alair074** [fatedier/frp#2197]
报错内容如下，网上找了下无果，个人觉得是不是网卡的问题。
```shell
● frps.service - Frp Server Service
   Loaded: loaded (/usr/lib/systemd/system/frps.service; disabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2021-01-18 09:50:18 CST; 3s ago
  Process: 29012 ExecStart=/usr/bin/frps -c /etc/frp/frps.ini (code=exited, status=1/FAILURE)
 Main PID: 29012 (code=exited, status=1/FAILURE)

Jan 18 09:50:18 VM-0-17-centos systemd[1]: frps.service: main process exited, code=exited, status=1/FAILURE
Jan 18 09:50:18 VM-0-17-centos systemd[1]: Unit frps.service entered failed state.
Jan 18 09:50:18 VM-0-17-centos systemd[1]: frps.service failed.
```
配置文件是使用frp安装包里带的，也修改了相应的路径配置，命令运行可以成功，但是用systemd不可以

**Comment by xiaobaozi233** [comment]
你是不是下错版本了。。。amd64下成arm64了？

**Comment by alair074** [comment]
> 你是不是下错版本了。。。amd64下成arm64了？

是amd64的

**Comment by alair074** [comment]
> > 你是不是下错版本了。。。amd64下成arm64了？
> 
> 是amd64的

客户端可以使用systemd管理，服务端不行

**Comment by xiaobaozi233** [comment]
那我只能建议你检查一下systemd用户和frps.ini是不是写的有问题了...

**Comment by BoneAsh** [comment]
是用户的问题，默认是nobody，可以改成有权限的用户，如root，本人腾讯云centos8，亲测成功 @alair074 ，你也可以试试

**Comment by hyh6622** [comment]
端口占用了吧

**Comment by magellan-99** [comment]
我遇到了相同的错误，不过我的vps在搬瓦工上面，如果端口换为8080就行能正确启动，端口如果是80就会和楼主报同样的错误，请问大家如何破？使用的用户是root

**Comment by magellan-99** [comment]
我的frps.ini文件
[common]
bind_port = 7000
vhost_http_port = 8080
token = *****

**Comment by magellan-99** [comment]
vps上面都虚拟的cpu也不知道我下载的frp版本对不对：wget https://github.com/fatedier/frp/releases/download/v0.38.0/frp_0.38.0_linux_amd64.tar.gz
