### ISSUE TITLE
HTTP Status 403 

### ISSUE THREAD

**Issue by RyzeZR** [fatedier/frp#2200]
### frps.ini的配置
```
[common]
server_addr = 1x.xx.2x1.2xx
server_port = 7000
token = hxxxxxx02
pool_count = 0
tcp_mux = true
login_fail_exit = false
protocol = tcp
tls_enable = false
heartbeat_interval = 30
heartbeat_timeout = 90
[http_web]
type = http
local_ip = 172.31.0.232
local_port = 80
use_encryption = false
use_compression = true
custom_domains = jw.ryzezr.com
locations = /
proxy_protocol_version = v2
```
其中 172.31.0.232为校园网教务系统的地址，客户端WAN 172.28.146.xxx ,LAN ip 192.168.1.1
这里教务系统的网纸：`http://172.31.0.233/cas/login.action`
登录进去后的url：`http://172.31.0.233/MainFrm.html?random=0.2859765568160182`
###frps.ini配置
```
[common]
bind_port = 7000
token = hexxxx2
vhost_http_port = 54321
vhost_https_port = 54322

dashboard_addr =  0.0.0.0
dashboard_port = 5555
dashboard_user =  admin
dashboard_pwd = admin
```
![image](https://user-images.githubusercontent.com/21257485/104949376-d29a7a00-59f9-11eb-925b-2a0dc60f7fc5.png)

请问上述问题该如何解决？或者说这个功能本身就是不能实现的？
期待您的回答，Thanks♪(･ω･)ﾉ

**Comment by fatedier** [comment]
可能你的网站不允许外部访问，你可以联系网站管理员咨询，403 表示访问被禁止。
