### ISSUE TITLE
映射内网anydesk端口的小问题

### ISSUE THREAD

**Issue by jearol** [fatedier/frp#2203]
版本：0.34.1

客户端配置：
[common]
server_addr = *.*.*.*
server_port = 7000
token = ******
pool_count = 16

[anydesk-10]
type = tcp
local_ip = 10.0.0.10
local_port = 7070
remote_port = 7070
use_encryption = false
use_compression = true

[anydesk-40]
type = tcp
local_ip = 10.0.0.40
local_port = 7080
remote_port = 7080
use_encryption = false
use_compression = true

服务端配置：
[common]
bind_port = 7000
token = *******
max_pool_count = 16
vhost_http_port = 8080
vhost_https_port = 4433

问题描述：
如果首次连接的是服务端7070端口的话，那么之后无论连接7070还是7080，则都连接到10.0.0.10:7070；
反之首次连接服务端7080端口的话，那么之后无论连接7070还是7080，则都连接到10.0.0.40:7080

没有具体测试多久可以重置连接，每次第二天首次连接的时候就决定了一天能连到.10的机器还是.40的机器
也不清楚是frp的问题还是anydesk的问题

**Comment by yuyulei** [comment]
最好提供下 frpc，frps 的 debug 日志。
