### ISSUE TITLE
use_encryption = true -> SSH fails

### ISSUE THREAD

**Issue by asheroto** [fatedier/frp#2207]
Version: 0.3.0
OS: Win 10
CPU architecture: 64-bit

FRPS config:
```
[common]
bind_port = 7000

```
FRPC config:
```
[common]
server_addr = utilities
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000
use_encryption = true
```

I have an SSH server on my client at port 22.  I cannot connect over port 6000 on my server. If I take out use_encryption it works fine. 

- Does use_encryption relate to the TLS setting tls_enable or is that totally different?
- To use TLS encryption, do I have to have certificates on both client and server?

**Comment by yuyulei** [comment]
`use_encryption` and `tls_enable` are totally different. `tls_enable` is applied to workConn, `use_encryption` is applied to proxy.

I have tried your configs, but it works no matter what `use_encryption` is. So may you provide more details(cmd, log, etc.) ?

**Comment by asheroto** [comment]
Thanks for the info.  Would it be fair to say that using ```use_encryption``` is sufficient enough to prevent against bad actors?

For some reason it's working now, I must have had a typo.  I'll close this after your reply.

**Comment by fatedier** [comment]
@asheroto `use_encryption` only encrypt your proxy connection data with `aes-128-cfb`, not including `Login` message.

Use `tls_enable` instead if you want to encrypt all data between frpc and frps. It supports public key encryption.

**Comment by asheroto** [comment]
@fatedier thank you

I'll close this request.
