### ISSUE TITLE
darwin版本会出现./frpc: line 2: syntax error: unexpected "("  问题

### ISSUE THREAD

**Issue by lnzoro** [fatedier/frp#221]
路由为r7000 版本为frp9.2

./frpc: line 1: Ϻ: not found
./frpc: line 2: syntax error: unexpected "("

**Comment by fatedier** [comment]
确认下你下的版本是否正确。

**Comment by cloverzrg** [comment]
我在路由器上也遇到了同样的问题，路由器上`uname -m`显示为mips架构，但是下载mips版本是不行的，mipsle才行
