### ISSUE TITLE
在NetBSD下无法运行

### ISSUE THREAD

**Issue by 236212005** [fatedier/frp#2211]
操作系统为NetBSD-i386-9.1，下载frp_0.35.0_freebsd_386.tar.gz并解压，运行提示错误：

> localhost# cd frp_0.35.0_freebsd_386/
localhost# ll
total 28098
-rw-r--r--  1 1001  116     11358 Jan 19 13:35 LICENSE
-rwxr-xr-x  1 1001  116   8335360 Jan 19 13:31 frpc
-rw-r--r--  1 1001  116       126 Jan 19 13:35 frpc.ini
-rw-r--r--  1 1001  116      9056 Jan 19 13:35 frpc_full.ini
-rwxr-xr-x  1 1001  116  20353024 Jan 19 13:31 frps
-rw-r--r--  1 1001  116        26 Jan 19 13:35 frps.ini
-rw-r--r--  1 1001  116      4971 Jan 19 13:35 frps_full.ini
drwxr-xr-x  2 1001  116       512 Jan 19 13:35 systemd
localhost# vi frpc.ini 
localhost# ./frpc -c frpc.ini 
-sh: Cannot execute ELF binary ./frpc

请问我是不是需要在netbsd下自己使用golong和frp的源码进行编译？

**Comment by fatedier** [comment]
You can try to compile it by yourself and better paste `go env` result here?

**Comment by 236212005** [comment]
Okay, I’ll try it.Thanks.
