### ISSUE TITLE
The binary size of frps nearly doubled in 0.35.0

### ISSUE THREAD

**Issue by xlfjn** [fatedier/frp#2212]
Version: 0.35.0

OS: Linux
CPU architecture: arm

**Steps to reproduce the issue**
1. Download the prebuilt binaries of version [0.35.0](https://github.com/fatedier/frp/releases/download/v0.35.0/frp_0.35.0_linux_arm.tar.gz) and [0.34.3](https://github.com/fatedier/frp/releases/download/v0.34.3/frp_0.34.3_linux_arm.tar.gz)
2. `tar -tvf frp_0.35.0_linux_arm.tar.gz && tar -tvf frp_0.34.3_linux_arm.tar.gz`
3. Compare the size of binaries
```
-rwxr-xr-x runner/docker  8454144 2021-01-19 21:32 frp_0.35.0_linux_arm/frpc
-rwxr-xr-x runner/docker 20316160 2021-01-19 21:32 frp_0.35.0_linux_arm/frps
```
```
-rwxr-xr-x runner/docker  8454144 2020-11-20 17:16 frp_0.34.3_linux_arm/frpc
-rwxr-xr-x runner/docker 11272192 2020-11-20 17:16 frp_0.34.3_linux_arm/frps
```
Notice that the size of `frpc` remains the same between versions, however `frps` ballooned by more than 80%.
In 0.34.3, `frps` is larger than `frpc` by 1/3 or 33% . In 0.35.0 it becomes 140% .

**Can you guess what caused this issue**
#2101 might be the cause, since only `frps` is affected. However I have not tried compiling frp without that.

**Comment by fatedier** [comment]
Thanks for your report. Your guess is right, i will try to fix it and release a new version.
