### ISSUE TITLE
How to get the VirtualHost serverName of local Apache in PHP using https2http plug-in

### ISSUE THREAD

**Issue by php4world** [fatedier/frp#2213]
###  **When I use PHP to get the protocol://serverName, the result is http://127.0.0.1. I want to get https://www.xxx.com how to do it?**

`frps.ini`
```
[common]
bind_port = 7000
vhost_https_port = 443
```

`frpc.ini`
```
[common]
server_addr = x.x.x.x
server_port = 7000

[www]
type = https
custom_domains = www.xxx.com

plugin = https2http
plugin_local_addr = 127.0.0.1:80

# HTTPS 证书相关的配置
plugin_crt_path = ./xxx.crt
plugin_key_path = ./xxx.key
plugin_host_header_rewrite = 127.0.0.1
plugin_header_X-From-Where = frp
```

windows
`hosts`
```
127.0.0.1 www.xxx.com
```

`httpd-vhosts.conf` with `wampserver`
```
<VirtualHost *:80>
    ServerName www.xxx.com
    DocumentRoot "e:/uimb/public"
    <Directory  "e:/uimb/public/">
        Options +Indexes +Includes +FollowSymLinks +MultiViews
        AllowOverride All
        Require local
    </Directory>
</VirtualHost>
```

**Comment by fatedier** [comment]
Remove `plugin_host_header_rewrite = 127.0.0.1`

**Comment by php4world** [comment]
> Remove `plugin_host_header_rewrite = 127.0.0.1`

Thank you! finally, I understand.
However, for the `protocol` issue, my local must also be `https`. Like `https2https`, otherwise the `protocol` obtained in PHP is still `http`.

**Comment by fatedier** [comment]
You can just use `https` without `https2http` plugin.
