### ISSUE TITLE
Failed to execute command: Permission denied

### ISSUE THREAD

**Issue by yuxiaoleipeng** [fatedier/frp#2214]
systemd[43196]: frpc.service: Failed to execute command: Permission denied
systemd[43196]: frpc.service: Failed at step EXEC spawning /root/frp/frp_0.34.3_linux_amd64/frpc: Permission denied
我已经给了chmod 777权限，但是设置开机自启动的时候会报这个错误，手动启动没有问题可以正常使用，请问大神们这个是怎么回事呀

**Comment by duocang** [comment]
@yuxiaoleipeng 

frps 的 systemd 配置里面的 “User=nobody” 注释掉。
