### ISSUE TITLE
the fastest and lightweight protocol to use with communication with the server ?

### ISSUE THREAD

**Issue by jembem** [fatedier/frp#2217]
which are the fastest and the lightweight protocol to use with communication with the frps server ? because I will be having more than 1000 clients connected at the same time , clients only using socks5 plugin .. 

now it supports tcp, kcp and websocket, default is tcp

?

**Comment by fatedier** [comment]
TCP is alright in most common scenario.

**Comment by jembem** [comment]
why not to use websocket in my scenario?

**Comment by jembem** [comment]
can you expalin which one is better ? and why ? .. in which circumstances different protocol is better :) it would be nice to explain this by the creator of this project  .. and I'm pretty sure it's going to be helpfull for other users
