### ISSUE TITLE
win2003系统 特权模式下 服务端经常自动关闭

### ISSUE THREAD

**Issue by dsf848dfgvs** [fatedier/frp#222]
特权模式下，tcp协议，反复打开关闭客户端4到5次，服务端就会自动退出。经过测试，发现特权模式下服务端很不稳定。只能转回正常模式使用了。不知道大家有没有和我碰到一样的问题呢。

**Comment by fatedier** [comment]
提交问题请提供版本信息 & 配置信息 & 日志。
