### ISSUE TITLE
连接frps服务突然 `invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by intern** [fatedier/frp#2225]
已经允许好几天了, 上午起来突然发现不能用了, 结果是服务端空指针异常了.
<pre>
2021/01/27 23:24:43 [I] [proxy.go:92] [acea0c754e3f5ac7] [web-code] get a new work connection: [171.88.169.80:9345]
2021/01/27 23:24:45 [I] [proxy.go:92] [07c9f5934a181f11] [dsm-web] get a new work connection: [171.88.169.80:9666]
2021/01/27 23:24:45 [W] [http.go:214] httputil: ReverseProxy read error during body copy: unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4dfea0]

goroutine 8190634 [running]:
bufio.(*Reader).Read(0xc000862c00, 0xc000172000, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000)
        /home/wcl/.gvm/gos/go1.13.4/src/bufio/bufio.go:212 +0x130
io.(*LimitedReader).Read(0xc000730a60, 0xc000172000, 0x8000, 0x8000, 0x0, 0x0, 0xc000267ee0)
        /home/wcl/.gvm/gos/go1.13.4/src/io/io.go:448 +0x63
net/http.(*body).readLocked(0xc0002991c0, 0xc000172000, 0x8000, 0x8000, 0x0, 0x0, 0xc0002679a0)
        /home/wcl/.gvm/gos/go1.13.4/src/net/http/transfer.go:847 +0x5f
net/http.(*body).Read(0xc0002991c0, 0xc000172000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /home/wcl/.gvm/gos/go1.13.4/src/net/http/transfer.go:839 +0x102
io.(*LimitedReader).Read(0xc000730b20, 0xc000172000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
        /home/wcl/.gvm/gos/go1.13.4/src/io/io.go:448 +0x63
io.copyBuffer(0x7f5a28ddd318, 0xc000a63a10, 0xb5bd80, 0xc000730b20, 0xc000172000, 0x8000, 0x8000, 0x8f9640, 0x1, 0x7f5a28ddd2f8)
        /home/wcl/.gvm/gos/go1.13.4/src/io/io.go:402 +0x122
io.Copy(...)
        /home/wcl/.gvm/gos/go1.13.4/src/io/io.go:364
net/http.persistConnWriter.ReadFrom(0xc00016bc20, 0xb5bd80, 0xc000730b20, 0x7f5a28ddd2f8, 0xc00016bc20, 0x1)
        /home/wcl/.gvm/gos/go1.13.4/src/net/http/transport.go:1599 +0x85
bufio.(*Writer).ReadFrom(0xc000299340, 0xb5bd80, 0xc000730b20, 0x7f5a28ddd2d8, 0xc000299340, 0x1)
        /home/wcl/.gvm/gos/go1.13.4/src/bufio/bufio.go:713 +0x34a
io.copyBuffer(0xb5b860, 0xc000299340, 0xb5bd80, 0xc000730b20, 0x0, 0x0, 0x0, 0xc000267c38, 0x40c8b8, 0x20)
        /home/wcl/.gvm/gos/go1.13.4/src/io/io.go:388 +0x2ed
io.Copy(...)
        /home/wcl/.gvm/gos/go1.13.4/src/io/io.go:364
net/http.(*transferWriter).doBodyCopy(0xc0000da960, 0xb5b860, 0xc000299340, 0xb5bd80, 0xc000730b20, 0x0, 0xc000267cc0, 0x6f5eb2)
        /home/wcl/.gvm/gos/go1.13.4/src/net/http/transfer.go:400 +0x6a
net/http.(*transferWriter).writeBody(0xc0000da960, 0xb5b860, 0xc000299340, 0x2, 0x2)
        /home/wcl/.gvm/gos/go1.13.4/src/net/http/transfer.go:359 +0x6da
net/http.(*Request).write(0xc000125600, 0xb5b860, 0xc000299340, 0x0, 0xc000a63a40, 0x0, 0x0, 0x0)
        /home/wcl/.gvm/gos/go1.13.4/src/net/http/request.go:682 +0x6d3
net/http.(*persistConn).writeLoop(0xc00016bc20)
        /home/wcl/.gvm/gos/go1.13.4/src/net/http/transport.go:2207 +0x1c8
created by net/http.(*Transport).dialConn
        /home/wcl/.gvm/gos/go1.13.4/src/net/http/transport.go:1575 +0xb23
</pre>

**[REQUIRED] hat version of frp are you using** 

Version:  frp_0.30.0_linux_amd64

**[REQUIRED] What operating system and processor architecture are you using**
OS: Linux
CPU architecture: x86_64

**Comment by fatedier** [comment]
Can upgrade to latest release version and try again?
