### ISSUE TITLE
搭建socks5 服务器遇到的问题

### ISSUE THREAD

**Issue by huangzanrong** [fatedier/frp#2228]
用firefox 浏览器，连接sockets5服务器。上google，返回：
read tcp 192.168.1.22:12759->59.24.3.174:80: wsarecv: An existing connection was forcibly closed by the remote host.

服务端配置
[common]
bind_port = 7000
bind_addr =0.0.0.0
token=pass

客户端配置：
[common]
server_addr=X.X.X.X
server_port=7000
token=pass
[socks5]
type=tcp
remote_port=8020
plugin=socks5

不知道是配置问题还是设置问题。就是上socks5用不了

**Comment by fondoger** [comment]
同.
http代理正常，socks5不行。
