### ISSUE TITLE
how to run on Windows arm64

### ISSUE THREAD

**Issue by YeautyYE** [fatedier/frp#2229]
I run Windows 10 on the Raspberry Pi, and want to perform intranet penetration through frp.
I try to execute `CGO_ENABLED = 0 GOOS = windows GOARCH = arm go build main.go` in the frpc directory of the source code to compile
But put it in windows, it can't run, and there is no log
Is my compilation method wrong?
Is there a compiled package provided
---
我目前将Windows10运行在树莓派上，想通过frp进行内网穿透。
我尝试在源码的frpc目录下执行 `CGO_ENABLED=0 GOOS=windows GOARCH=arm go build main.go` 进行编译
但是放到windows中，无法运行，且没有日志
请问是我的编译方式不对吗
是否有编译好的包提供

**Comment by yuyulei** [comment]
try https://github.com/fatedier/frp/releases/tag/v0.35.1 frp_0.35.1_windows_386.zip or frp_0.35.1_windows_amd64.zip

**Comment by YeautyYE** [comment]
> try https://github.com/fatedier/frp/releases/tag/v0.35.1 frp_0.35.1_windows_386.zip or frp_0.35.1_windows_amd64.zip

useless

**Comment by fatedier** [comment]
https://github.com/golang/go/issues/36439

It's not supported now, maybe in future golang release.

**Comment by YeautyYE** [comment]
OK
