### ISSUE TITLE
建议配置文件可以给目录或者*.ini一类的方式

### ISSUE THREAD

**Issue by jonozw** [fatedier/frp#2232]
**The solution you want**

当前的配置文件是单文件ini, 命令行是frpc -c config.ini
但是实际使用中会经常增删设置, 而主配置不变, 这样每次修改配置文件很麻烦. 一不小心改错了还得debug. 

是否能将配置调整成v2ray那样的 exec -confdir config_dir
或者类似nginx那样主配置文件里可以写一句
include /single.conf/*.ini

**Alternatives considered**

**How to implement this function**

N/A
**Application scenarios of this function**

startup

**Comment by fatedier** [comment]
Good idea

**Comment by zsinba** [comment]
顺便提一下: 
修改配置文件,期望能热加载. 
像nginx -s reload这样.
或像srs那样 , killall -9 srs

**Comment by fatedier** [comment]
@zsinba `./frpc -c ./frpc.ini reload`

**Comment by zsinba** [comment]
哎呦我靠,有这个命令?

**Comment by zsinba** [comment]
frps可以吗?

**Comment by zsinba** [comment]
![image](https://user-images.githubusercontent.com/890157/107002035-a175c400-67c5-11eb-9fe4-f2f2426ff7f8.png)

的确有.谢谢老板.

**Comment by dudebing99** [comment]
> **The solution you want**
> 
> 当前的配置文件是单文件ini, 命令行是frpc -c config.ini
> 但是实际使用中会经常增删设置, 而主配置不变, 这样每次修改配置文件很麻烦. 一不小心改错了还得debug.
> 
> 是否能将配置调整成v2ray那样的 exec -confdir config_dir
> 或者类似nginx那样主配置文件里可以写一句
> include /single.conf/*.ini
> 
> **Alternatives considered**
> 
> **How to implement this function**
> 
> N/A
> **Application scenarios of this function**
> 
> startup

单个配置文件足够简洁了，而且完全能够覆盖你的场景吧？
frpc -c config-dev.ini 
frp -c config-prod.ini

**Comment by fatedier** [comment]
@dudebing99 这个功能已经在开发中了，作为可选的能力，某些场景下可能要根据不同的用途对 proxy 的配置进行分类，分别管理，批量删除等等。

**Comment by jonozw** [comment]
如果个人用, 的确自己配置几个文件切换就好了.

如果在公司, 哪怕小公司商用, 配置文件管理就需要了

> 
> 
> > **The solution you want**
> > 当前的配置文件是单文件ini, 命令行是frpc -c config.ini
> > 但是实际使用中会经常增删设置, 而主配置不变, 这样每次修改配置文件很麻烦. 一不小心改错了还得debug.
> > 是否能将配置调整成v2ray那样的 exec -confdir config_dir
> > 或者类似nginx那样主配置文件里可以写一句
> > include /single.conf/*.ini
> > **Alternatives considered**
> > **How to implement this function**
> > N/A
> > **Application scenarios of this function**
> > startup
> 
> 单个配置文件足够简洁了，而且完全能够覆盖你的场景吧？
> frpc -c config-dev.ini
> frp -c config-prod.ini

如果个人用, 的确自己配置几个文件切换就好了.

如果在公司, 哪怕小公司商用, 配置文件管理就需要了

**Comment by dudebing99** [comment]
我觉得，配置文件管理方式跟应用场景大小没有啥关系，跟软件本身的功能特点有关。frp 目前的配置文件看起来是通过不同的 section 来支持不同的模块，对标 frp，nginx 这种配置文件方式是为了更好地支持多个相同的 section （例如，多个 http/server）。

不过，期待看到这个新功能，或许确实会带来我没理解到的便捷之处。
