### ISSUE TITLE
Parse conf error: proxy [] remote_port not found

### ISSUE THREAD

**Issue by dingliguo-github** [fatedier/frp#2233]
**[REQUIRED] hat version of frp are you using** 

Version: 0.16.1

**[REQUIRED] What operating system and processor architecture are you using**
OS: Windows64
CPU architecture: AMD64

**[REQUIRED] description of errors**
in proxy networks, frpc start error:
"Parse conf error: proxy [] remote_port not found"
**confile**

**log file**

**Steps to reproduce the issue**
1. 
2. 
3. 

**Supplementary information**

**Can you guess what caused this issue**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by yuyulei** [comment]
two things to do:
1. use latest version
2. add `remote_port` to `frpc.ini`

**Comment by dingliguo-github** [comment]
Thanks.
When ping to frps server, Just found can not connect to frps.
Maybe net admin  has done some restricts.
