### ISSUE TITLE
某些客户端通过frp远程连接服务器后30s掉线的问题

### ISSUE THREAD

**Issue by shminer** [fatedier/frp#2235]
**[REQUIRED] hat version of frp are you using** 

Version: 0.35.1

**[REQUIRED] What operating system and processor architecture are you using**
OS: server is windows server 2019 and client  is windows 7
CPU architecture: amd64

**[REQUIRED] description of errors**
* frp基本环境说明：服务器a使用frpc进行穿透，通过外网登录到服务器b。之后将自己130端口映射到服务器b上。
* 内网状态说明：内网状态下客户端a通过服务器130端口登录到服务器a进行通信，之后服务器a可以看到客户端a，同时可以使用130端口对其服务进行操作，通过netstat查看双方只建立1个连接。暂时不太清楚服务器a是如何获得客户端a在线状态的。
* 问题说明：客户端a通过服务器b访问服务器a，刚开始时一切正常，经过30s（多次测试），frps和frpc同时显示 join connections closed，服务器a的frpc直接释放了端口，客户端a通过netstat显示close_wait, 服务器b显示 
FIN_WAIT_2。

**confile**

**log file**

**Steps to reproduce the issue**
1. 
2. 
3. 

**Supplementary information**
* 服务器b仍然使用frps代理其他tcp服务，其他服务均正常。另外客户端a和服务端a的软件是第三方开发的，有些东西无法了解。
**Can you guess what caused this issue**
* 经测试客户端和服务端在内网状态下都正常，只有经过frp才会30s断线，30s正好是一个报文的寿命，但是目前仍然不知道为什么在内网下就没事。
**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by zsinba** [comment]
是不是你使用的移动的网络,他是共享外网ip,造成了你的对外ip一直在变化 .

电信的adsl试试尼.

**Comment by shminer** [comment]
> 是不是你使用的移动的网络,他是共享外网ip,造成了你的对外ip一直在变化 .
> 
> 电信的adsl试试尼.

双方都是固定IP，看了源码应该是作者30s中断一次链接防止长连接。

**Comment by HellowBoy** [comment]
客户端和服务端在配置文件中都把端口复用关了试试，默认是开启的，transport.tcpMux = false ，两端都要关闭，不然用不了

**Comment by HellowBoy** [comment]
我是这样解决的，目前测试没问题了。
客户端和服务器端关闭端口复用，客户端注册间隔时间设置为0

**Comment by dream-one** [comment]
> 我是这样解决的，目前测试没问题了。 1、客户端和服务器端关闭端口复用，下面只给出了服务端的配置，客户端也有相应的设置 transport.tcpMux = false transport.tcpMuxKeepaliveInterval = 60
> 
> transport.heartbeatTimeout = 60
> 
> 2、部分客户端插件注册间隔时间设置为0。如openwrt中
> 
> 大家可以试试，有用点赞呢

加上第一点配置之后可以多连接几秒，但是还是会断线，第二点怎么设置？
