### ISSUE TITLE
关于给frp两边加速的问题

### ISSUE THREAD

**Issue by dsf848dfgvs** [fatedier/frp#224]
想用kcptun给frp的tcp端口加速，因为frp下面使用了多个tcp端口，不知道怎么加速。是只给7000加速就行了呢，还是说分别给7000、xx1、xx2、xx3.......加速呢？
frps.ini
`[common]
bind_port = 7000
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin
log_file = ./frps.log
log_level = error
log_max_days = 1

[y1]
type = tcp
listen_port = 5673
auth_token = 123
authentication_timeout = 0

[y2]
type = tcp
listen_port = 8349
auth_token = 123
authentication_timeout = 0`

**Comment by fatedier** [comment]
只需要给 7000 端口加速，之后会内置此功能。

**Comment by dsf848dfgvs** [comment]
好的，非常期待内置的tcp加速功能。

**Comment by dsf848dfgvs** [comment]
客户端这样就对了吧？
`[common]
server_addr = x.x.x.x
server_port = 7000
auth_token = 123
log_file = ./frpc.log
log_level = error
log_max_days = 1
authentication_timeout = 0

[y1]
type = tcp
local_ip = 127.0.0.1
local_port = 5673

[y2]
type = tcp
local_ip = 127.0.0.1
local_port = 8349`
authentication_timeout = 0  客户端我也放到全局里面了。

**Comment by fatedier** [comment]
`authentication_timeout` 涉及到安全性，只能在 frps.ini 中设置。
