### ISSUE TITLE
Aliyun Linux 搭建FRP玩Minecraft 1.16.5出现错误

### ISSUE THREAD

**Issue by qiaoliangXgamemode** [fatedier/frp#2242]
2021/02/10 22:15:16 [I] [root.go:108] frps uses config file: frps.ini
Create server listener error, listen tcp 0.0.0.0:1337: bind: address already in use
[root@iZ7xverrl64hvb62ofk431Z frp]# ./frps -c frps.ini 
2021/02/10 22:15:17 [I] [root.go:108] frps uses config file: frps.ini
2021/02/10 22:15:17 [I] [service.go:137] tcpmux httpconnect multiplexer listen on 0.0.0.0:1337
2021/02/10 22:15:17 [I] [service.go:190] frps tcp listen on 0.0.0.0:7000
2021/02/10 22:15:17 [I] [service.go:199] frps kcp listen on udp 0.0.0.0:7000
2021/02/10 22:15:17 [I] [service.go:271] nat hole udp service listen on 0.0.0.0:7001
2021/02/10 22:15:17 [I] [root.go:217] frps started successfully
2021/02/10 22:15:27 [W] [service.go:395] CheckAndEnableTLSServerConnWithTimeout error: timeout
2021/02/10 22:15:27 [I] [service.go:444] [e322cadb647e560d] client login info: ip [113.16.89.131:54044] version [0.35.1] hostname [] os [windows] arch [386]
2021/02/10 22:15:27 [I] [tcp.go:63] [e322cadb647e560d] [loanmsnn] tcp proxy listen port [3846]
2021/02/10 22:15:27 [I] [control.go:446] [e322cadb647e560d] new proxy [loanmsnn] success
2021/02/10 22:15:32 [I] [proxy.go:162] [e322cadb647e560d] [loanmsnn] get a user connection [113.16.89.131:57226]
panic: unreachable

goroutine 25 [running]:
github.com/klauspost/reedsolomon.reedSolomon.codeSomeShardsAvx512(...)
        github.com/klauspost/reedsolomon@v1.9.1/galois_noasm.go:33
github.com/klauspost/reedsolomon.reedSolomon.codeSomeShards(0xa, 0x3, 0xd, 0x90cea00, 0xd, 0xd, 0x9093a60, 0x90ad480, 0xa, 0xa, ...)
        github.com/klauspost/reedsolomon@v1.9.1/reedsolomon.go:441 +0x3ba
github.com/klauspost/reedsolomon.reedSolomon.Encode(0xa, 0x3, 0xd, 0x90cea00, 0xd, 0xd, 0x9093a60, 0x90ad480, 0xa, 0xa, ...)
        github.com/klauspost/reedsolomon@v1.9.1/reedsolomon.go:313 +0x138
github.com/fatedier/kcp-go.(*fecEncoder).encode(0x90a0f00, 0x9072b00, 0x20, 0x546, 0x809e051, 0xd186aca8, 0x3)
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/fec.go:281 +0x2d1
github.com/fatedier/kcp-go.(*UDPSession).output(0x922c000, 0x9072b00, 0x20, 0x546)
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/sess.go:515 +0x5ba
github.com/fatedier/kcp-go.newUDPSession.func1(0x9072b00, 0x546, 0x546, 0x20)
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/sess.go:169 +0x46
github.com/fatedier/kcp-go.(*KCP).flush.func2(...)
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/kcp.go:685
github.com/fatedier/kcp-go.(*KCP).flush(0x90eefc0, 0x0, 0x8b45da0)
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/kcp.go:842 +0xc37
github.com/fatedier/kcp-go.(*UDPSession).update(0x922c000, 0xc0011881, 0xd1a1b241)
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/sess.go:556 +0x52
github.com/fatedier/kcp-go.(*updateHeap).updateTask(0x8b45860)
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/updater.go:91 +0xfd
created by github.com/fatedier/kcp-go.init.2
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/updater.go:13 +0x5f

由于不知道FRPS是否会生成日志，我只给出这些错误

**Comment by qiaoliangXgamemode** [comment]
环境是在Alinyun Linux情况下，也就是阿里将Centos改过来的版本

**Comment by qiaoliangXgamemode** [comment]
版本是v0.35.0

**Comment by qiaoliangXgamemode** [comment]
IP公布了没有关系，主要IP不是我家

**Comment by qiaoliangXgamemode** [comment]
阿里云的Centos 7.8版本:
goroutine 31 [running]:
github.com/klauspost/reedsolomon.reedSolomon.codeSomeShardsAvx512(...)
        github.com/klauspost/reedsolomon@v1.9.1/galois_noasm.go:33
github.com/klauspost/reedsolomon.reedSolomon.codeSomeShards(0xa, 0x3, 0xd, 0x90ce820, 0xd, 0xd, 0x9095840, 0x90af280, 0xa, 0xa, ...)
        github.com/klauspost/reedsolomon@v1.9.1/reedsolomon.go:441 +0x3ba
github.com/klauspost/reedsolomon.reedSolomon.reconstruct(0xa, 0x3, 0xd, 0x90ce820, 0xd, 0xd, 0x9095840, 0x90af280, 0xa, 0xa, ...)
        github.com/klauspost/reedsolomon@v1.9.1/reedsolomon.go:763 +0x73f
github.com/klauspost/reedsolomon.reedSolomon.ReconstructData(...)
        github.com/klauspost/reedsolomon@v1.9.1/reedsolomon.go:643
github.com/fatedier/kcp-go.(*fecDecoder).decode(0x90a2f50, 0x9020600, 0x1d7, 0x5dc, 0x85f41e7, 0x1, 0x901c798)
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/fec.go:155 +0x69a
github.com/fatedier/kcp-go.(*UDPSession).kcpInput(0x923a000, 0x9020600, 0x1d7, 0x5dc)
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/sess.go:628 +0x74
github.com/fatedier/kcp-go.(*Listener).packetInput(0x90976c0, 0x9020600, 0x1d7, 0x5dc, 0x8819080, 0x9016920)
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/sess.go:780 +0x2d7
github.com/fatedier/kcp-go.(*Listener).monitor(0x90976c0)
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/readloop_linux.go:99 +0x202
created by github.com/fatedier/kcp-go.ServeConn
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/sess.go:947 +0x1b8

**Comment by qiaoliangXgamemode** [comment]
我发现我腾讯云机子可以开FRP，而且游玩1.16.5版本没有什么问题，我怀疑阿里云机制限制了FRP

**Comment by fatedier** [comment]
从日志看是使用的 kcp-go 触发的异常，也可能是我用的这个库的问题，我之后同步更新到最新版本试试看。

**Comment by qiaoliangXgamemode** [comment]
好的
