### ISSUE TITLE
set frpc to access two local nginx virtual servers with different ports

### ISSUE THREAD

**Issue by klikdadang** [fatedier/frp#2245]
**[REQUIRED] hat version of frp are you using** 

Version: frp_0.33.0_linux_amd64

**[REQUIRED] What operating system and processor architecture are you using**
OS: ubuntu 18
CPU architecture: 64

**[REQUIRED] description of errors**
i tried to set frpc.ini to access my local virtual web server using different port, but i only can access my 80 port. i can't access my 8821 port
1. https://mydomain.com --> worked
2. https://mydoman.com:8821 --> not worked

**confile**

**log file**

**Steps to reproduce the issue**
1. my frpc.ini
....
[web01]
type : http
local_port : 80
custom_domains : mydomain.com
location : /

[web01]
type : http
local_port : 80
custom_domains : mydomain.com:8821
location : /8821

2. restarting frpc service
3. restarting nginx service

**Supplementary information**
I have tried to find a solution from the issues page but I couldn't find it
please forgive me if this has been discussed before

**Can you guess what caused this issue**

**Checklist**:

- [X] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by klikdadang** [comment]
sorry, this is my frpc configuration:

[web01]
type : http
local_port : 80
custom_domains : mydomain.com
location : /

[web02]
type : http
local_port : 8821
custom_domains : mydomain.com:8821
location : /8821

**Comment by fatedier** [comment]
You can't do that since you can only set one vhost_http_port in frps.ini.
