### ISSUE TITLE
能否在设置里提供对kcp相关参数的微调设置,谢谢！

### ISSUE THREAD

**Issue by listenfree** [fatedier/frp#2246]
如题目，比如snd rcv的大小的可调等等，
另外好象包里的kcp模块不是最新的。

**Comment by fatedier** [comment]
这一部分暂时不打算开放配置，如果有需要精确配置的能力，建议还是结合 kcp-tunnel 一起使用，在 frp 里配置这一块内容过于复杂。

kcp 模块的代码因为倾向于稳定，在可用没有明显问题的情况下一般不会主动跟进更新，如果新版本有优化，我之后也会同步更新一下。

**Comment by listenfree** [comment]
谢谢亲！
