### ISSUE TITLE
use_encryption功能的安全性

### ISSUE THREAD

**Issue by hbinzn** [fatedier/frp#2248]
use_encryption=true过后看到frps与frpc间的明文数据确实是被加密了，这个加密是通过何种方式来实现，相对TLS有没有被破解的风险？

**[REQUIRED] hat version of frp are you using** 

Version:

**[REQUIRED] What operating system and processor architecture are you using**
OS:
CPU architecture:

**[REQUIRED] description of errors**

**confile**

**log file**

**Steps to reproduce the issue**
1. 
2. 
3. 

**Supplementary information**

**Can you guess what caused this issue**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by dksslq** [comment]
https://github.com/fatedier/frp/blob/127a31ea6a1a5d3f0ce3d9c2b9ec6776b1732cde/server/control.go#L300

**Comment by fatedier** [comment]
在可以的情况下尽量使用 TLS ，这样可以全局加密。use_encryption 只对通过代理传输的内容加密。
