### ISSUE TITLE
FRPC 提示 port not allowed

### ISSUE THREAD

**Issue by xukecheng** [fatedier/frp#2252]
Version: 0.34.3

OS:  Openwrt
CPU architecture: ARMv8

**[REQUIRED] description of errors**

**confile**
![image](https://user-images.githubusercontent.com/29099863/108670231-802d0b80-7519-11eb-8941-5c05b3d400ed.png)

**log file**
2021/02/22 14:23:39 [I] [proxy_manager.go:144] [543191d03372e531] proxy added: [download tcp]
2021/02/22 14:23:39 [W] [control.go:178] [543191d03372e531] [download tcp] start error: port not allowed

**Steps to reproduce the issue**
1.  想转发局域网内的 BT 下载上传监听端口到服务器
2.  设置了服务器的 65117 端口和本地的 65117 转发，但是 FRPC 报错，FRPS 没有 Log 提示
3.  尝试了其他的 TCP 端口转发是正常的，比如说 22

**Comment by yuyulei** [comment]
@xukecheng, can you check the remotePort if has been used?

**Comment by xukecheng** [comment]
@yuyulei No, it is available. And I has used NPS, it work well.

**Comment by Co2333** [comment]
检查一下服务器端配置。。。我犯傻了

`allow_ports = 50000-60000`
