### ISSUE TITLE
HTTP_PROXY on Windows 10

### ISSUE THREAD

**Issue by tuqu0** [fatedier/frp#2257]
Hi

I am running frpc on Windows 10 x64 and set http_proxy=http://127.0.0.1:8080 from the configuration file.
Then I start Burp (local proxy interceptor) to see if it works but it didn't. I got the error : "session shutdown".

Without the http_proxy line I can connect to my frps server without any problem.
So does use of http_proxy works on Windows ?

Thx

**Comment by fatedier** [comment]
It should work on any os.

Make sure you don't set any other system proxies?

**Comment by tuqu0** [comment]
No, I have not other system proxy.

Config:

frps.ini
```
[common]
bind_port = 8888
```

frpc.ini
```
[common]
server_addr = <public_ip>
server_port = 8888
http_proxy = http://127.0.0.1:8080

[socks5]
type = tcp
remote_port = 1080
plugin = socks5
```

Message error on frpc side:

```
2021/02/26 15:31:40 [W] [service.go:104] login to server failed: write tcp 127.0.0.1:55738->127.0.0.1:8080: wsasend: An established connection was aborted by the software in your host machine.
write tcp 127.0.0.1:55738->127.0.0.1:8080: wsasend: An established connection was aborted by the software in your host machine.
```

**Comment by fatedier** [comment]
It seems connection to `127.0.0.1:8080` was aborted by your service.

**Comment by tuqu0** [comment]
Yes but it doesn't make sense, it is my local proxy (Burp) running on this port so I should see the request from it.

**Comment by tuqu0** [comment]
I set up a VM A, with the firewall blocking everything except TCP port 8080 where frpc is running.
On a VM B,  I set up a proxy running on port 8080, so VM A can go reach Internet through VM B proxy and finally join VM C where frps is running.

Using the configuration above in this scenario, does not work. FRPC on VM A is not sending any request to the proxy server running on VM B (they are on the same network, so that's not a network issue).

On VM A, if the firewall is allowing all connections and if I remove the http_proxy from FRPC configuration file, I can connect to the FRPS server. So it does not seem a configuration issue, but that the http_proxy option is not working.

**Comment by fatedier** [comment]
Captura packages to `127.0.0.1:8080` by tcpdump?

**Comment by tuqu0** [comment]
Okay, I ran Wireshark and packets are sent to the VM B where the proxy is running.
Somehow, the proxy (Burp) says : "Unsuported or unrecognized SSL message".

However, if I look at the packets captured with wireshark I can see the data with info about the FRPC host.

I tried with a public HTTP proxy available online and it works.

Any idea about this SSL issue ?

Thank you

**Comment by fatedier** [comment]
I'm not familiar with Burp. I'm not sure if it supports HTTP PROXY? Maybe you have not used it in a correct way.
