### ISSUE TITLE
login to server failed: dial tcp 121.61.63.38:7000: connectex: No connection could be made because the target machine actively refused it. dial tcp 121.61.63.38:7000: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by FrankZhou-jun** [fatedier/frp#2261]
login to server failed: dial tcp 121.61.63.38:7000: connectex: No connection could be made because the target machine actively refused it.
dial tcp 121.61.63.**:7000: connectex: No connection could be made because the target machine actively refused it.

**Comment by micky2333** [comment]
请关闭系统防火墙
