### ISSUE TITLE
frpc无法使用kcp连接

### ISSUE THREAD

**Issue by yaott2020-666** [fatedier/frp#2266]
frpc两端都是openwrt-armv8

frps是阿里云轻量ubuntu18.04

frpc两端使用tcp协议连接正常，xtcp正常，反正一切正常

但是两端换成kcp协议后连接不正常，xtcp无法连接

frps防火墙已打开

frps配置文件部分：
[common]
bind_addr = 0.0.0.0
bind_port = 7000
bind_udp_port = 7000
kcp_bind_port = 7001

frpc配置文件部分：
[common]
server_addr = XXX
server_port = XXXX
token = XXXXXXX
protocol = kcp

frpc日志提示：[W] [service.go:102] login to server failed: i/o deadline reached

frps无日志提示

**Comment by fatedier** [comment]
`server_port` 和 `kcp_bind_port` 需要一致。

**Comment by yaott2020-666** [comment]
已解决，感谢大佬！！！
