### ISSUE TITLE
求助：UDP转发 proxy [UDP47998] type [UDP] error

### ISSUE THREAD

**Issue by Miuzarte** [fatedier/frp#2271]
frps.ini
[common]
bind_port = 19999
bind_udp_port = 19999
token = 1

frpc.ini
[common]
server_addr = miuzarte.hk.sinu.ltd
server_port = 19999
token = 1
[UDP47998]
type = UDP
local_ip = 0.0.0.0
local_port = 47998
remote_port = 47998

运行之后
![image](https://user-images.githubusercontent.com/66856838/109753756-b3f4e900-7c1d-11eb-8a42-19e2ba28096f.png)

不知道是frps还是frpc哪里填错，如果错的很低级还请指教一下

**Comment by Miuzarte** [comment]
我设置了info的log，但是没输出

**Comment by fatedier** [comment]
UDP 小写
