### ISSUE TITLE
set multi listen port for http & HTTPS

### ISSUE THREAD

**Issue by Milokita** [fatedier/frp#2274]
**The solution you want**

FRPS able to listen to multi ports for both HTTP & HTTPS 
**Alternatives considered**

Set up an apache/nginx reverse proxy to listen to ports other than TCP 80 443
**How to implement this function**

Change how frps.ini interpreted, allowing config such as
`vhost_https_port = 443,123`
**Application scenarios of this function**

it will provide some flexibility for configuring proxy

**Comment by jingmouren** [comment]
这条有进展吗？
URL路由的方案，如果两个web的location项有相同的，会有冲突
如果每个web再对应不同的port，就解决了

**Comment by fatedier** [comment]
@jingmouren 你的需求更适合使用 TCP 类型的端口映射来解决。

**Comment by Milokita** [comment]
但是我记得如果对HTTPS使用 TCP转发浏览器是会报错的

Sincerely
XINGZ

________________________________

**Comment by fatedier** [comment]
@Milokita TCP 已经是比较底层的协议了，和应用层无关，如果报错，可以具体排查一下是哪方面的问题。
