### ISSUE TITLE
[W] [http.go:92] do http proxy request error: no such domain: any url

### ISSUE THREAD

**Issue by dodois** [fatedier/frp#2276]
**[REQUIRED] hat version of frp are you using** 

### Version: 0.35.1

**[REQUIRED] What operating system and processor architecture are you using**
### CPU architecture: x64

**[REQUIRED] description of errors**
### I want frpC to forward external http requests to socks5
```
2021/03/04 13:30:21 [W] [http.go:92] do http proxy request error: no such domain: 112.46.25.179
2021/03/04 13:30:21 [W] [http.go:92] do http proxy request error: no such domain: 120.241.139.207
2021/03/04 13:30:22 [W] [http.go:92] do http proxy request error: no such domain: 2402
2021/03/04 13:30:22 [W] [http.go:92] do http proxy request error: no such domain: 36.155.233.222
2021/03/04 13:30:23 [W] [http.go:92] do http proxy request error: no such domain: 112.46.25.226
2021/03/04 13:30:24 [W] [http.go:92] do http proxy request error: no such domain: 120.232.33.235
2021/03/04 13:30:24 [W] [http.go:92] do http proxy request error: no such domain: 112.46.25.165
2021/03/04 13:30:25 [W] [http.go:92] do http proxy request error: no such domain: 112.46.25.236
....
```

**confile**

Client :
```
[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 8809

[socks5]
type = http
plugin = socks5
use_encryption = true
use_compression = true
local_ip = 127.0.0.1
local_port = 1080
subdomain = v2
```
Server: 
```
[common]
bind_port = 8809
vhost_http_port = 8809
subdomain_host = domian.com
```
**log file**

omit
**Steps to reproduce the issue**
1. omit
2. omit
3. omit

**Supplementary information**
omit
**Can you guess what caused this issue**
omit
**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by yuyulei** [comment]
ref: https://gofrp.org/docs/features/http-https/subdomain/

**Comment by dodois** [comment]
@yuyulei 
Thanks for your reply, but it's not what I was looking for
![image](https://user-images.githubusercontent.com/73285310/110068884-9bb5d300-7db1-11eb-94d4-3f93d3669ed7.png)

**Comment by yuyulei** [comment]
@dodois, two things：

1. the host "v2.domian.com" is expected, but logs show that frps receive request host like："112.46.25.179", "36.155.233.222", .... So you can capture network packages，make sure that what the request domain or host(http header).
2.  `socks5` belongs to TCP/IP protocol family, `subdomain` belongs to HTTP protocal, conflict!
