### ISSUE TITLE
FRPC: admin user & pwd will not refresh after changed in AdminUI

### ISSUE THREAD

**Issue by Military-Doctor** [fatedier/frp#2281]
**[REQUIRED] hat version of frp are you using** 

Version: 0.35.1

**[REQUIRED] What operating system and processor architecture are you using**
OS: Raspberry Pi 4b
CPU architecture: aarch64-linux-gnu

**[REQUIRED] description of errors**

The username and password of admin UI will not updated while click the "Upload" button in admin UI

**Steps to reproduce the issue**
1. Login the admin UI
2. Change `admin_user` and `admin_user` in Configure
3. Click the "Upload" button

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by fatedier** [comment]
It's designed as a feature for security issue.

**Comment by Military-Doctor** [comment]
could you please explain why this is a security feature?
