### ISSUE TITLE
双栈ipv6下连接服务端监听端口提示出错

### ISSUE THREAD

**Issue by Hokia** [fatedier/frp#2282]
> root@ecs:/frp# ./frpc -c ./frpc.ini
> dial tcp [fe80::26b:eaff:fad2:867c]:7000: connect: invalid argument
> [2]+  已终止               nohup ./frpc -c ./frpc.ini
> root@ecs:/frp# nohup ./frpc -c ./frpc.ini&

=====================================
frps.ini已经添加bind_addr = [::]
想询问一下在双栈环境下是否可以通过v6连接监听端口，谢谢！

**Comment by yuyulei** [comment]
@Hokia next release will be ok.
