### ISSUE TITLE
建议增加 DNS 隧道和 ICMP 隧道传输数据

### ISSUE THREAD

**Issue by haodiao** [fatedier/frp#2283]
在一些网络中要各种验证信息才能免费上，实在太烦了   
特别是一些公共的WIFI，要填写手机号、关注公众号等等，之后就是各种硬广   
但这类的WIFI一般 DNS 通道和 ICMP 的通道都基本上是正常的，    
所以建议 Frp 添加模拟 dns 请求 和 ping 命令请求来建立隧道传输数据

**Comment by kissingers** [comment]
你把服务器的UDP用端口53就可以实现第一个方案。

**Comment by haodiao** [comment]
@kissingers 想太多了吧，不是标准的DNS查询根本行不通，  
有的还不能使用第三方DNS，只能通过路由的DNS来递归到目标服务器
