### ISSUE TITLE
客户端配置文件修改api

### ISSUE THREAD

**Issue by saixin** [fatedier/frp#2287]
[web]
type = http
local_port = 80
custom_domains = www.example.com
frpc.ini里的配置，如上网站配置项目，有api接口可以增删改查frpc.ini吗？而不是手工修改frpc.ini

**Comment by fatedier** [comment]
https://gofrp.org/docs/features/common/ui/#%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%AE%A1%E7%90%86%E7%95%8C%E9%9D%A2

目前可以配置 frpc 端的 Web 页面来动态修改
