### ISSUE TITLE
Consider support X-Forwarded-Host and X-Forwarded-Proto?

### ISSUE THREAD

**Issue by xfan1024** [fatedier/frp#2293]
I setup the Jenkins in private network and expose the http port by frp.

[Jenkins](https://www.jenkins.io/) told me “[It appears that your reverse proxy set up is broken](https://www.jenkins.io/doc/book/system-administration/reverse-proxy-configuration-troubleshooting)” 

In order to solve this problem I made a [draft](https://github.com/xfan1024/frp/commit/3e4b61fe6edebbb85f7fd18a724234d74c1f592a), it's works.
I'm not familiar with the Go and I have no idea how to correctly add X-Forwarded-Proto field. Can you provide a solution?

**Comment by fatedier** [comment]
Try this feature https://github.com/fatedier/frp#setting-other-http-headers ?

**Comment by xfan1024** [comment]
I had enabled this option, but Jenkins always need X-Forwarded-Host and X-Forwarded-Proto, because Jenkins want know original host and proto from user's browser.

pleause refer to: https://www.jenkins.io/doc/book/system-administration/reverse-proxy-configuration-troubleshooting

**Comment by fatedier** [comment]
I think it's ok when you set `X-Forwarded-Host ` the value of `custom_domains` . It's just the host users should visit.

**Comment by xfan1024** [comment]
Agree, do you have plan ro support it?

**Comment by fatedier** [comment]
A sample configure

```ini
[test-web]
type = http
local_ip = 127.0.0.1
local_port = 80
custom_domains = web.yourdomain.com
header_X-Forwarded-Host = web.yourdomain.com
header_X-Forwarded-Proto = http
```

**Comment by xfan1024** [comment]
Thanks, I got it wrong.😂
