### ISSUE TITLE
forward proxy (not reverse) for SOCKS5 relay

### ISSUE THREAD

**Issue by asheroto** [fatedier/frp#2296]
Hey there,

I'd like to use frp but in reverse, ha!  I use frp for several reverse proxies, but for this task I need a forward proxy.

Can frps accept incoming SOCKS5 connections and forward its traffic out 80/443 from an frpc connection?

Computer1 has a VPN connection
Computer2 is my computer

Computer1 needs to listen for incoming SOCKS5 connections on port 1080 (login abc/abc)
Computer2 needs to connect to Computer1 over SOCKS5, then Computer1 needs to relay traffic through ports 80/443

Computer2-->SOCKS5-->Computer1-->Outbound 80/443-->VPN Software Handles WAN Connectivity

Is that possible, or is this a feature request?  😁😂

**Comment by fatedier** [comment]
Can computer2 connect to computer1 directly?

**Comment by asheroto** [comment]
Right. Using the SOCKS5 plugin...

**Comment by fatedier** [comment]
frp is not designed for this scenario.

But you can try it, deploy frps and frpc on c1 and another frpc on c2 with [stcp](https://github.com/fatedier/frp#expose-your-service-privately) proxy .

**Comment by asheroto** [comment]
Thank you
