### ISSUE TITLE
重大BUG，严重的性能问题，内存泄露

### ISSUE THREAD

**Issue by niluanxy** [fatedier/frp#23]
用了一段时间，并通过验证，确认 FRP 有严重的性能问题，和 ngrok 一样，用一段时间后，服务器的性能会严重下降，最终导致 服务 crash 掉。我的服务器上就装了 nginx，gogs（go语言编写的一个git服务端），然后如果开了 frp ，不到三天就会服务器反应缓慢，frp 直接 crash 掉。我担心是 gogs 影响的，然后就单独开了 gogs ，结果跑了好几天，一致很稳定，所以确认是 frp 的代码问题，希望作者尽快解决看看，还是很喜欢 frp 的，但是如果这个问题不解决，就不敢用了。

**Comment by maplewizard** [comment]
我也遇到了crash的问题，但是原因不明。

**Comment by fatedier** [comment]
能否多反馈一些信息，比如用的配置文件，系统版本，日志等。毕竟还在前期开发阶段，就是需要收集反馈来解决问题，通常发布的 release 版本都是在我自己稳定使用几天之后。

![image](https://cloud.githubusercontent.com/assets/7346661/14661754/cd4210dc-06e2-11e6-8283-1d1e37cde9df.png)

![image](https://cloud.githubusercontent.com/assets/7346661/14661779/f9157a82-06e2-11e6-9a35-98003cc22e31.png)

我服务器上两个 v0.3.0 版本的 frps 已经稳定运行一个星期了，不过个人能力毕竟有限，未必每种情况都能考虑到，还是希望能多提供一些改进与反馈，谢谢。

**Comment by niluanxy** [comment]
@fatedier 我的环境是 centos7 64，服务器上软件有 nginx, gogs（个人感觉这个的可能性较大）， 配置文件文件如下，日志文件我这几天再运行几天，给你产生新的日志吧。

```C
[common]
bind_addr = 0.0.0.0
# 用于接收 frpc 连接的端口
bind_port = 7000
log_file = ./frps.log
log_level = info

# 代理的自定义名称，可以有多个，不能重复，和frpc中名称对应
[nas]
auth_token = adfkowehGJWE
bind_addr = 0.0.0.0
# 最后将通过此端口访问后端服务
listen_port = 9090
```

**Comment by fatedier** [comment]
@niluanxy master 分支后来有一次hotfix，最好用最新的代码编译。你反向代理的后端运行的什么服务？我看看我这边能不能复现。

**Comment by niluanxy** [comment]
@fatedier 反向代理我用的 nginx 做的，我现在下得是你编译好的 0.3 版本，没自己编译，这个是最新的吗？

**Comment by fatedier** [comment]
@niluanxy 是最新的，我指的是通过 9090 端口访问到的是什么服务。

**Comment by niluanxy** [comment]
哦，那个是我群辉的nas，我是白群辉，ns214play，主要用反向代理主要是为了用下 P2P 同步的那个软件，结果升级后不能用了。。。现在群辉是最新的系统，好像是6.0吧

**Comment by fatedier** [comment]
@niluanxy 之前的问题有复现吗？

**Comment by niluanxy** [comment]
@fatedier 恩，测试了情况依旧，不过现在还在测试到底是那个引起的，因为最近没开 frp，但是 gogs  今天出现反应慢的问题了，还在排查是不是 gogs 自己也有问题。

**Comment by fatedier** [comment]
@niluanxy 可以用 `top -p [pid]` 观察一下

**Comment by niluanxy** [comment]
已经确认是 MySql 的问题了，不是 frp 导致的，内存加到 2G ，然后服务器就稳定正常了。。。

**Comment by fatedier** [comment]
@niluanxy 推荐一下我们开发的系统监控服务，[http://www.mmtrix.com/system#/list](http://www.mmtrix.com/system#/list)，个人用户免费使用，可以查看到哪些进程占用 cpu 和 内存过高，以及对其他网络，磁盘等全方位的监控。可配置短信邮件告警，及时发现问题。
