### ISSUE TITLE
腾讯云centos7.8无法正常穿透

### ISSUE THREAD

**Issue by l2weekly** [fatedier/frp#2315]
这两天在折腾去年买了吃灰的腾讯云，发现正常安装frps及配置好frpc后无法穿透，服务端和客户端的日志都正常，但dashboard上面显示连接的subdomain为undefined。
相同的配置在经常使用的搬瓦工上面一切正常，
起初以为是系统安装了GNOME导致的，重新安装操作系统后问题依旧，Google了很久也没找到相似的问题，特来请教！
frps.ini
![a003e4253934e75db43535aaa2911fb](https://user-images.githubusercontent.com/713333/111757931-d2720a00-88d6-11eb-92ab-9fa06a7d242c.png)

frpc.ini
![e50087fee31d5c85ce5f6c0b075cf6c](https://user-images.githubusercontent.com/713333/111757951-daca4500-88d6-11eb-81a9-9f11b5971836.png)

frps.log
![34a9635ed3c571f26038bdd1ce9fe9e](https://user-images.githubusercontent.com/713333/111758070-00efe500-88d7-11eb-99a2-67ce58871e5a.png)

frpc.log
![4a86d0b836e5797a4f367c0722f96b7](https://user-images.githubusercontent.com/713333/111759888-1239f100-88d9-11eb-8ded-252e49ec7e05.png)

dashboard
![383018c2f982d08e459407f3d561684](https://user-images.githubusercontent.com/713333/111758157-1bc25980-88d7-11eb-867c-bf2d6c583a54.png)

**Comment by l2weekly** [comment]
今天把搬瓦工也重装系统后，发现也出现了相同的问题，现在就更不明白了。

**Comment by bingtianbaihua** [comment]
@l2weekly 可以提供下 frp 的版本

**Comment by l2weekly** [comment]
腾讯云上版本0.36.0 搬瓦工0.36.1都出现了相同的问题 @bingtianbaihua
