### ISSUE TITLE
frps 0.36.1 vhost_http_port默认绑定0.0.0.0，不能指定绑定哪个IP

### ISSUE THREAD

**Issue by h3110w0r1d-y** [fatedier/frp#2317]
在0.35版本中vhost_http_port绑定的IP与bind_addr一致，
但在0.36中默认绑定所有，不能指定绑定哪个IP。
希望可以改回去或者增加可以自定义绑定哪个IP的功能！
![image](https://user-images.githubusercontent.com/52311174/111774632-b1b3af80-88ea-11eb-9d8f-2f43ebca8a2c.png)
![image](https://user-images.githubusercontent.com/52311174/111774763-e1fb4e00-88ea-11eb-9dde-e3bd6a59117c.png)

**Comment by h3110w0r1d-y** [comment]
我是在下面这种情景下使用的，如果不能自定义vhost_http_port绑定的ip，只能修改nginx的端口，但是修改nginx端口后，从http强制跳转到https就会出错，比如nginx绑定了81（http）和442（https）端口，访问http://abc.com，nginx会重定向到https://abc.com:442。
![image](https://user-images.githubusercontent.com/52311174/111777587-761ae480-88ee-11eb-8077-43b9ef9d1702.png)
建议大佬添加一个自定义vhost_http_port绑定的IP的功能，谢谢

**Comment by fatedier** [comment]
这是一个配置解析的 bug，之后会发布 v0.36.2 版本修复这个问题
