### ISSUE TITLE
是否有ban掉多次登陆尝试失败ip的feature

### ISSUE THREAD

**Issue by tcqiuyu** [fatedier/frp#2318]
最近发现我的主机经常被攻击，如下图
![image](https://user-images.githubusercontent.com/6031166/111861792-f5122a80-898b-11eb-8d21-c19a80700339.png)

虽然好像并没有登陆成功，但是总是让人不放心，有没有功能可以支持尝试多少次登陆失败后把ip加入黑名单的功能？我找了一下好像没有找到，谢谢。

**Comment by fatedier** [comment]
可以尝试其他 linux 防火墙的工具，或者通过 [服务端插件](https://gofrp.org/docs/features/common/server-plugin/) 来实现这个扩展能力

**Comment by yaott2020-666** [comment]
我这里也是这样，莫名其妙就被扫了端口。

**Comment by hehh2001** [comment]
@yaott2020-666   stcp使用的方便性又打折扣了，我的做法是服力端添加“allow_ports =” 参数， 只开放我转发要用的端口，并且服务端安装fail2ban来处理端口扫问题，这样能安静很多
