### ISSUE TITLE
日志是否可以过滤写入？

### ISSUE THREAD

**Issue by tudnew** [fatedier/frp#2319]
我需要保存连入IP，但发现需要 debug 才能显示，但这个级别日志太多了，心跳包都算。

比如日志级别 info ， 过滤 [proxy.go:273] 整行写入。

**Comment by fatedier** [comment]
`./frpc | grep -v 'proxy\.go:273'`

**Comment by tudnew** [comment]
@fatedier 
大佬，你的docker镜像我该怎么加呀😥。
docker run -d --name frp -v /mnt/sda3/user/frp/frps.ini:/frps.ini  --network host --restart=always fatedier/frp

[common] 
log_file = /frps.log
log_level = info
log_max_days = 3

把proxy.go:273写入frps.log，或者debug不写入心跳包也行。
