### ISSUE TITLE
作者是否有打算开发动态端口的支持 ~

### ISSUE THREAD

**Issue by ruan11223344** [fatedier/frp#232]
server_port = 7000 据统计运营商会阻断流量过多的固定端口。
第一次连接7000端口后，客户端会定时GET到服务器端的推送动态端口的更新，
客户端收到更新后的端口内部则自动连接到新的动态端口进行数据传输？

这个无缝对接好像比较麻烦。

以上是建议。

**Comment by fatedier** [comment]
可以试着将 7000 端口改为 443 或者 80 等一些其他用途的端口。

这种问题不适合放在内部解决。
