### ISSUE TITLE
Error occurs with TLS encryption: [W] [service.go:103] login to server failed: session shutdown

### ISSUE THREAD

**Issue by Villivateur** [fatedier/frp#2320]
Version: 0.35.1

OS: Ubuntu 18.04 LTS
CPU architecture: AMD64

Everything went well until I want to change my FRP service to TLS enctrypted mode.
I started frps in server A, then start frpc in server B. server B shows the following log:

```
$ frpc -c /etc/frp/frpc.ini
2021/03/21 13:54:24 [W] [service.go:103] login to server failed: session shutdown
session shutdown
```

But nothing in server A:
```
$ frps -c /etc/frp/frps.ini
2021/03/21 22:01:22 [I] [root.go:108] frps uses config file: /etc/frp/frps.ini
2021/03/21 22:01:23 [I] [service.go:190] frps tcp listen on 0.0.0.0:8877
2021/03/21 22:01:23 [I] [root.go:217] frps started successfully
```

I promise that before I add the TLS function, the frps and frpc worked well.

No more logs are available.

**confile**

```ini
# frps.ini
[common]
bind_port = 8877
#log_file = /var/log/frp/frps.log
token = 1230456
tls_enable = true
tls_cert_file = /etc/frp/frp.crt
tls_key_file = /etc/frp/frp.key
tls_trusted_ca_file = /etc/frp/ca.pem
```

```ini
# frpc.ini
[common]
server_addr = frp.example.com
server_port = 8877
token = 1230456
tls_enable = true
tls_cert_file = /etc/frp/frp.crt
tls_key_file = /etc/frp/frp.key
tls_trusted_ca_file = /etc/frp/ca.pem

[proxy]
type = tcp
local_ip = 127.0.0.1
local_port = 443
remote_port = 2133
use_encryption = true
use_compression = true
```

The `frp.crt` and `ca.pem` are self-signed using openssl. I'm sure the `CN` in `frp.crt` is `frp.example.com`.

**Can you guess what caused this issue**

I've tryed removing `tls_trusted_ca_file = /etc/frp/ca.pem` line in `frpc.ini`. The frpc worked. But it seems that it does not work in TLS mode.

So, I guess that frpc had errors in processing ca.pem. Did I do something wrong?

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by yuyulei** [comment]
can you follow [tls_demo](https://github.com/fatedier/frp#tls) and try it again, I want to make sure whether some mistake happens when generating the certificates.

**Comment by Villivateur** [comment]
> can you follow [tls_demo](https://github.com/fatedier/frp#tls) and try it again, I want to make sure whether some mistake happens when generating the certificates.

@yuyulei Thank you for your reply. I followed the tls_demo exactly and it worked (only replaced the `example.ca.com` when generating the ca cert and `server.com` when genarate the server cert).

But I still want to know where I missed for generating the certs. I've followed [this](https://blog.vvzero.com/2021/01/24/Become-a-CA-and-generate-self-signed-certificate/) link (language: zh-cn) to do that, and set my frps server's hostname to `Common Name` field.

Am I wrong? Or, how can I figure out where I am wrong? How can I debug in frpc? `session shutdown` means nothing to me.

**Comment by Villivateur** [comment]
BTW, the certificates I used for frps and frpc are the same one. Will it cause session shutdown?

**Comment by ZeddG93** [comment]
我也是同样的问题，多次连接的话可以看到提示是时间认证不通过：
```
❯ frpc -c $HOME/.local/etc/frpc.ini
2021/04/29 12:00:08 [W] [service.go:102] login to server failed: x509: certificate has expired or is not yet valid: current time 2021-04-29T12:00:08+08:00 is after 0001-01-01T00:00:00Z
x509: certificate has expired or is not yet valid: current time 2021-04-29T12:00:08+08:00 is after 0001-01-01T00:00:00Z
```
但是两个证书通过openssl和windows的证书查看都是在有效期内的。

server.crt
![image](https://user-images.githubusercontent.com/7886856/116501866-88704100-a8e4-11eb-81b0-e22a8a01c192.png)

ca.crt
![image](https://user-images.githubusercontent.com/7886856/116501880-932ad600-a8e4-11eb-8c29-47c5c31ceff3.png)

我的证书也是根据TLS章节的内容生成的，只不过把CA的CN换成了别的名字，server证书的CN换成了我公网的IP。

**Comment by zhanghe1993** [comment]
> can you follow [tls_demo](https://github.com/fatedier/frp#tls) and try it again, I want to make sure whether some mistake happens when generating the certificates.

![image](https://user-images.githubusercontent.com/65702058/119117931-29b16980-ba43-11eb-8210-b68637b29616.png)
When FRPS and FRPC are in different countries, is it useful to create a certificate by way of [tls_demo](https://github.com/fatedier/frp#tls)? According to the method [tls_demo](https://github.com/fatedier/frp#tls), my host in China can connect normally, but the host abroad cannot. Fortunately, it is working to copy the ca and client files of the domestic client host to a foreign host.

**Comment by shagunkam** [comment]
2024/01/11 12:03:03 [I] [root.go:141] start frpc service for config file [frpc.toml]
2024/01/11 12:03:03 [I] [service.go:287] try to connect to server...
2024/01/11 12:03:04 [W] [service.go:290] connect to server error: session shutdown
2024/01/11 12:03:04 [I] [root.go:159] frpc service for config file [frpc.toml] stopped
login to the server failed: session shutdown. With loginFailExit enabled, no additional retries will be attempted

serverAddr = "127.0.0.1"
serverPort = 7000

[[proxies]]
name = "test-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000
How i resolve this session shutdown. error?? anyone @villivateur

**Comment by anthony-dl** [comment]
have you been able to solve it ? @shagunkam

**Comment by xici** [comment]
Same error as @shagunkam. Anyone solve it?
