### ISSUE TITLE
HTTP subdomain show "undefine" .

### ISSUE THREAD

**Issue by zsinba** [fatedier/frp#2321]
**[REQUIRED] hat version of frp are you using** 

Version:

**[REQUIRED] What operating system and processor architecture are you using**
OS:
CPU architecture:

**[REQUIRED] description of errors**

**confile**

**log file**

**Steps to reproduce the issue**
1. FRPC使用HTTP客户端,上线后,在服务端显示的子域名都为undefined
2.这是一个必现的问题.
3.这在HTTP代码的时候出现 的这个问题
![image](https://user-images.githubusercontent.com/890157/111935704-016ac480-8aff-11eb-9259-521c47902425.png)

**Supplementary information**

**Can you guess what caused this issue**
I don't konw. may be the loss.
**Checklist**:

- [*] I included all information required in the sections above
- [*] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by fatedier** [comment]
It will be fixed in v0.36.2

**Comment by zsinba** [comment]
老板你真快.
