### ISSUE TITLE
能不能新增服务器统一管理功能

### ISSUE THREAD

**Issue by zengxiao2009** [fatedier/frp#2322]
是这样的 我一直使用FRP很久了 而且映射有十来台主机,但在管理方面很不方便,如要增加或修改都要到现应远程到现应的机子操作,而且修改配置错误后,导致连不上现应的机子,反而要跑到现应机子电脑旁操作,加上备份frpc.ini配置也麻,烦,最近发现了NPS这个软件,对方服务统一在服务端上,客 户端只要连接一条命令就可以,所以端口改动和配置都在服务端上,我想FRP是不是也能添加这一功能,只要FRPS上配置就可以了

**Comment by zengxiao2009** [comment]
就算端口配置出错了,也不会导玫客户端无法连接,重新配置服务端就可以了

**Comment by bingtianbaihua** [comment]
这个好像会在 frp pro 版本里提供吧。

**Comment by zsinba** [comment]
还有pro版本了？
 这个功能挺需求
