### ISSUE TITLE
启用https2https/https2http插件，大概率报400 bad request

### ISSUE THREAD

**Issue by h3110w0r1d-y** [fatedier/frp#2326]
启用插件时，访问网站，大概率会有几个请求时返回400，严重影响网页正常功能。这个400好像是frp直接返回的，nginx日志里没有请求的记录
![image](https://user-images.githubusercontent.com/52311174/112168161-04af9e80-8c2c-11eb-81de-ed3a5eb03c10.png)

之前用https2http插件也有这个情况

**Comment by fatedier** [comment]
有的网站不是简单映射下就能访问了，你的网站里的链接可能千奇百怪，需要保证所有的链接地址都会转发到 frps 所在的服务器才可以。

**Comment by ax2009live** [comment]
@h3110w0r1d-y   https2http 插件用于一些比较私人的简单网站，还能用用，( 静态网站是比较合适的 )
用于正规网站有些不合适，建议 frp 只 TCP 转发即可；frp 转发 TCP 是非常成熟的；
