### ISSUE TITLE
frps  运行报错 listen tcp 0.0.0.0:80: bind: permission denied

### ISSUE THREAD

**Issue by ChinaParrot** [fatedier/frp#2330]
frps版本：0.35.1

frps.ini 配置添加vhost_http_port = 80

[common]
#must
bind_addr = 0.0.0.0
bind_port = 50001
vhost_http_port = 80
vhost_https_port = 443
vhost_http_timeout = 120

运行：[root@ecs-6b63 frp]# systemctl  start frps

Mar 25 00:30:37 ecs-6b63 frps: Create vhost http listener error, listen tcp 0.0.0.0:80: bind: permission denied

**Comment by bingtianbaihua** [comment]
看下是否端口被占用，或者 改下其他的端口试试？

**Comment by yaott2020-666** [comment]
看看frps权限够不够

**Comment by ChinaParrot** [comment]
感谢大家，我找到问题了，frps.service  的用户有问题User=nobody

**Comment by stop-coding** [comment]
> 

改成啥才可以？

**Comment by heathcliff-hu** [comment]
> > 
> 
> 改成啥才可以？

```bash
User = root
```
