### ISSUE TITLE
127.0.0.1本地测试connect refused

### ISSUE THREAD

**Issue by ufoozhenghao** [fatedier/frp#2331]
**[REQUIRED] hat version of frp are you using** 

Version:0.36.2

**[REQUIRED] What operating system and processor architecture are you using**
OS:ubuntu 16.04 server
CPU architecture:intel E3

**[REQUIRED] description of errors**
使用127.0.0.1本地ssh远程端口提示connect refused
**confile**

frps.ini
[common]
bind_port = 7000

frpc.ini
[common]
server_addr = 127.0.0.1
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

**log file**

**Steps to reproduce the issue**
下载frp_0.36.2_linux_amd64.tar.gz
1. 在ubuntu上执行 `./frps -c ./frps.ini`与`./frpc -c ./frpc.ini`后都提示proxy success
2. 本地终端执行 `ssh -oPort=6000 dell@127.0.0.1`提示connect refused
3. ufw disable后错误仍然存在
4. 启用ufw后`ufw allow 6000`无法连接
5. ufw status 显示 6000 anywhere
6. lsof -i:6000 无返回，端口没有被占用
6. nelnet 127.0.0.1 6000无响应

**Supplementary information**

**Can you guess what caused this issue**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by bingtianbaihua** [comment]
1. 换个机器，用同样的配置试一下？ 
2. ss -alpn|grep frp 一下？

**Comment by ufoozhenghao** [comment]
> 1. 换个机器，用同样的配置试一下？
> 2. ss -alpn|grep frp 一下？

感谢帮忙 我在虚拟机中用同样的配置可以实现   第二个步骤我明天去公司看看

127.0.0.1不通是啥问题啊？服务器是Dell PowerEdge R230 安装的是ubuntu 16.04 server

**Comment by bingtianbaihua** [comment]
> > 1. 换个机器，用同样的配置试一下？
> > 2. ss -alpn|grep frp 一下？
> 
> 感谢帮忙 我在虚拟机中用同样的配置可以实现 第二个步骤我明天去公司看看
> 
> 127.0.0.1不通是啥问题啊？服务器是Dell PowerEdge R230 安装的是ubuntu 16.04 server

问题原因可能是多方面的，当前无法判断，建议 tcpdump 抓个包看看。
