### ISSUE TITLE
为 https 网站设置 BasicAuth 鉴权  Require https Basic Auth (Password) for Web Services 

### ISSUE THREAD

**Issue by ax2009live** [fatedier/frp#2332]
<pre>
[web]
type = https
local_ip = 127.0.0.1
local_port = 443
custom_domains = test.example.com
http_user = abc
http_pwd = abc</pre>

用在 https 代理上，没有作用; 

希望增加 " 支持 https 网站设置 BasicAuth 鉴权 " 这个功能 ;  可以对一些网站加密访问 ( 比如一些反代网站 )，又不需要太多设置；
https_user = abc
https_pwd = abc

<pre> #frpc.ini
[web]
type = https
local_ip = 127.0.0.1
local_port = 443
custom_domains = test.example.com
https_user = abc
https_pwd = abc </pre>

**Comment by fatedier** [comment]
frp 不解析 HTTPS 协议内容，所以无法支持

**Comment by ax2009live** [comment]
好的，谢谢回复！
那我通过 nginx 实现！
