### ISSUE TITLE
使用Frp的SSL连接代理Jupyter Notebook服务，无法连接Python服务

### ISSUE THREAD

**Issue by StevendeLiu** [fatedier/frp#2333]
**[REQUIRED] hat version of frp are you using** 

Version:0.33.0

**[REQUIRED] What operating system and processor architecture are you using**
OS:Windows 10
CPU architecture:x64

**[REQUIRED] description of errors**

**confile**

**log file**

**Steps to reproduce the issue**
1. 使用https2http服务代理Jupyter Notebook的Web服务
2. 可以访问文件管理页面，但是打开Jupyter笔记本后一直提示Python服务正忙，若不使用SSL代理而进行普通的穿透则没有这个问题

**Supplementary information**

**Can you guess what caused this issue**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by bingtianbaihua** [comment]
没有特别理解， 可以贴一些关键日志。

**Comment by badgv** [comment]
你可以考虑使用frp转发至apache2或nginx，再做反代连接至jupyter，这样应该没问题
