### ISSUE TITLE
能够做成.Net类库,方便进行二次开发

### ISSUE THREAD

**Issue by cngege** [fatedier/frp#2335]
就像标题说的那样，将客户端做出dll类库，比如我的服务器或者本地电脑的某一个程序、游戏需要端口映射到外网，如果frp有类库版本，这样我就可以直接将frp做到该程序之中，而不需要另外运行一个frp程序进行端口映射

**Comment by fatedier** [comment]
这样的需求你可以自己调研下如何去实现？

**Comment by bingtianbaihua** [comment]
可以阅读项目的源码然后翻译成其他语言。

**Comment by cngege** [comment]
> 
> 
> 可以阅读项目的源码然后翻译成其他语言。

我只会C#语言啊

**Comment by haochen233** [comment]
> > 可以阅读项目的源码然后翻译成其他语言。
> 
> 我只会C#语言啊
理不直，气也壮

**Comment by Shijf** [comment]
https://zhuanlan.zhihu.com/p/46721768
看下这个
