### ISSUE TITLE
frps端开放所有端口是否安全?

### ISSUE THREAD

**Issue by andywang1011** [fatedier/frp#2337]
如题.

**Comment by andywang1011** [comment]
> 如题.

已使用安全暴露的方式stcp

**Comment by sillyguy2021** [comment]
安不安全，跟你怎麼用有關係，跟frps和開放什麼端口沒關係；
frps不是有密碼嗎？

**Comment by andywang1011** [comment]
> 安不安全，跟你怎麼用有關係，跟frps和開放什麼端口沒關係；
> frps不是有密碼嗎？

那你说错了。
一台公共vps配置了frps，我想暴露内网1433端口。VPS就需要开放防火墙1433端口。
黑客扫描到VPS开放了1433端口，就可以穷举sa密码
现在已经改成stcp协议了
