### ISSUE TITLE
logs.BeeLogger.SetLogger: open ./frps.log: permission denied 怎么解决

### ISSUE THREAD

**Issue by aisyun** [fatedier/frp#2338]
版本：0.36.2
frps.service - Frp Server Service
   Loaded: loaded (/usr/lib/systemd/system/frps.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2021-04-02 20:11:26 CST; 3s ago
 Main PID: 1441 (frps)
    Tasks: 4
   Memory: 13.9M
   CGroup: /system.slice/frps.service
           └─1441 /usr/bin/frps -c /etc/frp/frps.ini

Apr 02 20:11:26 HK-Quick systemd[1]: Stopping Frp Server Service...
Apr 02 20:11:26 HK-Quick frps[1441]: logs.BeeLogger.SetLogger: open ./frps.log: permission denied

但是访问不了web查看页面

**Comment by bingtianbaihua** [comment]
看下目录权限是否成功赋予。

**Comment by Xipren** [comment]
这个就是目录权限问题

**Comment by aisyun** [comment]
Thank you It does working well now



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: github-actions[bot] ***@***.***&gt;
发送时间: 2021年6月1日 08:44
收件人: fatedier/frp ***@***.***&gt;
抄送: aisyun ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[fatedier/frp] logs.BeeLogger.SetLogger: open ./frps.log: permission denied 怎么解决 (#2338)





 
Closed #2338.
