### ISSUE TITLE
代理POST时BODY超过1MiB报EOF错

### ISSUE THREAD

**Issue by shinoyasan** [fatedier/frp#2339]
**[REQUIRED] hat version of frp are you using** 

Version:0.35.1

**[REQUIRED] What operating system and processor architecture are you using**
OS:Windows Server 2019 Datacenter
CPU architecture:x64

**[REQUIRED] description of errors**

**confile**

**log file**

**Steps to reproduce the issue**
1. 我使用FRP代理HTTP请求
2. POST请求body小于1兆时不会报错。检查了Nginx，client_body_size没有问题
3. FRP直接输出错误：do http proxy request error: unexpected EOF和do http proxy request error: context canceled

**Supplementary information**

**Can you guess what caused this issue**

**Checklist**:

- [ ] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by bingtianbaihua** [comment]
1. 可以简单提供一下配置。
2. 可以提供更多的日志信息。

**Comment by shinoyasan** [comment]
谢谢帮助，frp没有问题，错的还是nginx，它配置的client_body_size仍旧没有生效
