### ISSUE TITLE
Help Help

### ISSUE THREAD

**Issue by yimisiyang** [fatedier/frp#2340]
my frp server is a Vultr host ，my frp client is a RespbearryPi4. when I satart my frp client , It tell me
**[W] [service.go:104] login to server failed: parse "127.0.0.1:8123": first path segment in URL cannot contain colon**
my RespbearryPi4 have proxy. how to fix this problem.

**Comment by bingtianbaihua** [comment]
Can you show the frpc and frps config ?

**Comment by bingtianbaihua** [comment]
I have a  test demo.  It can reproduce this problem. 

```
package main

import (
	"fmt"
	"net/url"
)

func main() {

	url, err := url.Parse("127.0.0.1:8080")
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(url.Host, url.Port())
}

```

parse "127.0.0.1:8080": first path segment in URL cannot contain colon
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x10b025a]

goroutine 1 [running]:
net/url.(*URL).Port(...)
      go1.15.3/src/net/url/url.go:1120
main.main()
       main.go:14 +0xba
exit status 2

--- 

You should provide more message.
