### ISSUE TITLE
关于内网穿透80端口不知道是不是bug

### ISSUE THREAD

**Issue by txke** [fatedier/frp#2342]
我内网服务器和公网服务器都是CentOS7.9系统
内网搭建环境php5.6+tengine+mysql,web环境开放80端口，内网环境web项目访问正常，同时frpc客户端同时代理ssh,mysql和web三个。
公网只有frps做服务器穿透。
不管公网服务器设置vhost_http_port为任何端口都只能访问内网环境安装时的tengine默认欢迎页面，不是访问到我内网的web项目页面，但是内网把80改成81端口就能正常内网穿透访问，不知道是什么原因。
frp版本是0.35.1390625

**Comment by bingtianbaihua** [comment]
80 端口不能访问，有什么报错日志么 ？

**Comment by bingtianbaihua** [comment]
可以提供一些access日志， 方便排查。

**Comment by txke** [comment]
是frpc的log日志还是frps的log日志?
我没保存日志，只是看了一下，从日志上看不到什么东西，都是0000000正常的，但是我内网测试192.168.56.101:80访问的是我搭建的测试页面，而不是Tengine默认的欢迎访问页面，但是穿透之后就变成欢迎页面了。

至于搭建的Tengine里面，我搭建的测试项目的log就没有访问到，也就没有日志了。
你们可以自己搭建测试一下，全部是Tengine的默认设置，只需要内网端口从80改为其他端口就可以正常外网服务器80端口穿透了

**Comment by bingtianbaihua** [comment]
> 是frpc的log日志还是frps的log日志?
> 我没保存日志，只是看了一下，从日志上看不到什么东西，都是0000000正常的，但是我内网测试192.168.56.101:80访问的是我搭建的测试页面，而不是Tengine默认的欢迎访问页面，但是穿透之后就变成欢迎页面了。
> 
> 至于搭建的Tengine里面，我搭建的测试项目的log就没有访问到，也就没有日志了。
> 你们可以自己搭建测试一下，全部是Tengine的默认设置，只需要内网端口从80改为其他端口就可以正常外网服务器80端口穿透了

恩，有空我去复现一下。 也不复杂。
