### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by steom** [fatedier/frp#2345]
Connecting to frps via HTTP PROXY with frpc v0.36.2 websocket protocol does not work.
Not connect.
Successfull, all ok with frpc protocol set to tcp.
Set to websocket does not work.

I thought it was fixed in v0.35.0 (HTTP type proxy can't handle websocket protocol due to error Connection header value) but not, i think the Connection header still needs some fix.

**Comment by bingtianbaihua** [comment]
Please support error log.

**Comment by steom** [comment]
[W] [service.go:104] login to server failed: websocket.Dial
ws://my.site.com:80/~!frp: dial tcp 11.22.33.44:80: i/o timeout
websocket.Dial ws://my.site.com:80/~!frp: dial tcp 11.22.33.44:80: i/o timeout

**Comment by bingtianbaihua** [comment]
you can try  nc -zv 11.22.33.44 80

**Comment by steom** [comment]
ncat -zv www.google.com or my.frpsserver.com is the same
Ncat: Version 7.80 ( https://nmap.org/ncat )
Ncat: Connection to 142.250.184.35 failed: TIMEOUT.
Ncat: Trying next address...

**Comment by bingtianbaihua** [comment]
Maybe your http proxy cannot work.

**Comment by steom** [comment]
Http proxy with frpc protocol = tcp works fine
Http proxy with frpc protocol = websocket no connection

**Comment by bingtianbaihua** [comment]
OK，I will try to test it locally.
