### ISSUE TITLE
frpc@.service 和frpc.service区别

### ISSUE THREAD

**Issue by LaogouWang** [fatedier/frp#2348]
如题

**Comment by Xipro** [comment]
@LaogouWang 一个是带置换符的模版，一个是直接编辑用于系统服务的。
两种都可以用。
二选一即可。

**Comment by w0ngzz** [comment]
大佬可以说说frpc@.service具体怎么用吗，谢谢大佬###

**Comment by w0ngzz** [comment]
> Issues go stale after 45d of inactivity. Stale issues rot after an additional 10d of inactivity and eventually close.

大佬可以说说frpc@.service具体怎么用吗，谢谢大佬
