### ISSUE TITLE
希望能够自定义管理页面的title和映射端口描述

### ISSUE THREAD

**Issue by wangzhengzhen** [fatedier/frp#2349]
我使用frp有两多了，感谢作者开发的这款软件。在此有两个建议：

1.希望能够定义管理页面的title。我把公司和家分别用不同的frps服务端，本地会有两个frpc。同时打开管理页面时，不易直观的区分。

2.当端口映射较多时，希望在frps查看时，增加端口描述。

**Comment by fatedier** [comment]
Dashboard 页面的内容和 frp 本身其实是独立的，可以自行编写这部分的页面内容，通过在配置文件中指定 `assets_dir = ./static` 指定自己编写的前端页面来替换。
