### ISSUE TITLE
请问在阿里云如何部署服务端

### ISSUE THREAD

**Issue by ztj1993** [fatedier/frp#235]
[common]
bind_addr = 127.0.0.1

导致 x.x.x.x:7500 无法访问
-------------------------------------------------
如果
[common]
bind_addr = 0.0.0.0

导致 绑定到 ipv6 上
-------------------------------------------------
请问如何绑定到 ipv4上并且部署成功使用。

**Comment by recall704** [comment]
你可以直接写 ipv4 的地址啊

**Comment by ztj1993** [comment]
找到问题了，iptables 防火墙的问题，万恶的防火墙

**Comment by mindfocus** [comment]
说一下怎么配置的呗 我的也绑定在ipv6上 @ztj1993

**Comment by ztj1993** [comment]
@mindfocus 我的是直接按照官网的设置的，我的原有问题产生的原因是防火墙的问题；你要看哪个配置，晚上到家我看一下后，给你发下

**Comment by mindfocus** [comment]
就转HTTP的就行 谢谢啦 现在只要绑定到00 就是ipv6 @ztj1993

**Comment by ztj1993** [comment]
@mindfocus 我主要使用 ssh，这是我的配置，version 0.9.3 的。你可以参考一下，

![1](https://cloud.githubusercontent.com/assets/13493380/26529479/ffc9685e-43f2-11e7-96d6-c6ad8a9781b1.png)
![2](https://cloud.githubusercontent.com/assets/13493380/26529480/00089da8-43f3-11e7-80c9-01a2e3f361c0.png)
![3](https://cloud.githubusercontent.com/assets/13493380/26529481/0030a23a-43f3-11e7-8022-7e2c8ab083d4.png)
