### ISSUE TITLE
在 http&https 设置 BasicAuth 鉴权 里增加一个请求过滤设置功能

### ISSUE THREAD

**Issue by static7** [fatedier/frp#2351]
大部分情况下 OPTIONS 是浏览器发送的预检请求 而非项目里代码发送的请求. 因此不能携带BasicAuth鉴权参数
只能从BasicAuth鉴权功能里下手
希望增加一个BasicAuth鉴权自定义过滤请求的功能 使 OPTIONS 请求跳过通过鉴权

**Comment by fatedier** [comment]
有相关的 RFC 文档对这方面有定义吗？不太倾向于通过增加配置来引入更多的复杂度，过多的参数会让用户需要理解更多的内容。如果有标准说明 OPTIONS 请求不需要鉴权，可以忽略，那么就作为默认的设置，否则不太倾向于设立这样的特殊配置，而是在自己的 web 服务里去做这个鉴权。
