### ISSUE TITLE
关于xtcp通信加密问题

### ISSUE THREAD

**Issue by AlexYe233** [fatedier/frp#2352]
xtcp visitor与xtcp server的通信是否会加密

**Comment by fatedier** [comment]
https://gofrp.org/docs/features/common/network/

参考文档中的配置可以启用加密。

**Comment by AlexYe233** [comment]
在xtcp-server和xtcp-client的配置文件中均设置：
[common]
tls_enable = true 
是否会加密xtcp-server和xtcp-client之间的流量，还是只加密两个frpc与frps之间的流量

还是在xtcp-server的配置文件设置：
[xtcp_server]
use_encryption = true
和
在xtcp-client的配置文件设置：
[xtcp_client]
use_encryption = true
才会加密xtcp-server和xtcp-client之间的流量
