### ISSUE TITLE
frpc能否对 需要的穿透后端服务伪造来源IP 或者获取用户真实IP，后端不支持protocol proxy

### ISSUE THREAD

**Issue by hyird** [fatedier/frp#2354]
最近需要用frp 来穿透jellyfin 来远程播放我Nas里面的视频，但是由于frpc请求是来自局域网 所以并不会触发自动转码，一些码率很高的视频播放起来就会非常卡顿。
so，需要伪造一个非局域网ip 或者获取客户真实ip 来触发jellyfin的解码功能，不知道是否有办法可以实现。

**Comment by 940842546** [comment]
你找到解决方案了？？

**Comment by hyird** [comment]
> 你找到解决方案了？？目前能获取frps服务器的ip 反正能自动转码了  剩下的不强求
