### ISSUE TITLE
FRP报错: connect: no route to host

### ISSUE THREAD

**Issue by jhbrokeygmail** [fatedier/frp#2357]
Frpc报错
dial tcp 39.96.52.60:7000: connect: no route to host
Frps是阿里云，但所有端口都打开了，

**Comment by jhbrokeygmail** [comment]
[W] [service.go:104] login to server failed: dial tcp 39.96.52.60:7000: connect: no route to host
dial tcp 39.96.52.60:7000: connect: no route to host

**Comment by kissingers** [comment]
你这个是客户端连不到服务器，检查自己的网络。可以通过ping以及  telnet 服务器ip 端口  方式诊断是否正常开放

**Comment by CodeDreamfy** [comment]
> 你这个是客户端连不到服务器，检查自己的网络。可以通过ping以及 telnet 服务器ip 端口 方式诊断是否正常开放

可能是host没配吧，我也遇到了，不是网络问题

**Comment by caexy** [comment]
我也是

**Comment by liyinxin** [comment]
解决了吗，我最近也遇到这个问题了！！
