### ISSUE TITLE
A functional appeal.

### ISSUE THREAD

**Issue by SusuDOS** [fatedier/frp#2358]
A functional appeal: whether such a scenario can be considered. That is, computers a and B that have already run FRP clients need to use a to access B, but this function cannot be realized at present.
For example, a:
# custom <-> visitor,this is a config of custom!
[common]
server_ addr = 43.248.*.*
server_ port = 20514
token=0228bc66-23c6-4210-992c-ab5e1cb9
[p2p_ rdp]
type = stcp
sk = 329416525
local_ ip = 127.0.0.1
local_ port = 3389
For example, B:
# custom <-> visitor,this is a config of custom!
[common]
server_ addr = 43.248.*.*
server_ port = 20514
token=0228bc66-23c6-4210-992c-ab5e1cb9
[p2p_ rdp]
type = stcp
sk = 329416525
local_ ip = 127.0.0.1
local_ port = 3389
For example, a-visit:
# custom <-> visitor,this is a config of visit
[common]
server_ addr = 43.248.*.*
server_ port = 20514
token=0228bc66-23c6-4210-992c-ab5e1cb9
[rdp_ visitor]
type = stcp
role = visitor
server_ name = p2p_ rdp
sk = 329416
bind_ addr = 127.0.0.1
bind_ port = 13389
At this time, a will report an error.

**Comment by SusuDOS** [comment]
Using different service names can achieve similar functions, but it is possible that the service has the same name. Using different key values to judge the server name may be more user-friendly.

**Comment by fatedier** [comment]
What's the feature do you want? Can you show me a example configures?
