### ISSUE TITLE
做HTTP file server时，浏览器显示的文件和目录名可以修改显示格式吗？

### ISSUE THREAD

**Issue by mmiker** [fatedier/frp#2359]
比如放在一个表格里，每个文件或目录占表格的一行。或用css控制输出格式。
现在的显示貌似太简陋了点 ，如果自己修改的话？该改哪里？

**Comment by fatedier** [comment]
目前不能，当前是使用的 golang 原生的 HTTP File Server。如果有定制的需求，其实可以直接使用 nginx 或者其他的 web server，自己编写网页内容来展示。
