### ISSUE TITLE
关于局部代理和全局代理的问题

### ISSUE THREAD

**Issue by dsf848dfgvs** [fatedier/frp#236]
目前使用的是TCP协议，客户端和服务端都正常通讯。客户端百度查IP地址，显示的是本地IP。目前来看，frp应该是局部代理。可以同时加个全局代理的选项吗？比如客户端连接服务端之后，客户端百度查IP，变成服务器那边的IP。

**Comment by fatedier** [comment]
你的这个需求并不是 frp 的功能点，并不是一个正向的代理。
