### ISSUE TITLE
想知道xtcp是如何实现的呢?

### ISSUE THREAD

**Issue by Li-Lian1069** [fatedier/frp#2365]
我猜大概的原理是:
假设我的电脑被 NAT 之后的内网IP 是 10.0.0.11,  顶层IP是 120.120.120.120
我在我的电脑上打开了一个1234端口用来访问远程主机 (123.123.123.123), 这个端口在我的电脑上是 1234, 而在顶层路由可能是 5678
frp 通过某种方式获取到与之对应的顶层路由端口, 即可实现流量不经服务器.

如果是这样的话, 细节上如何实现呢?

**Comment by fatedier** [comment]
http://xdxd.love/2016/10/18/%E5%AF%B9%E7%A7%B0NAT%E7%A9%BF%E9%80%8F%E7%9A%84%E4%B8%80%E7%A7%8D%E6%96%B0%E6%96%B9%E6%B3%95/

主要参考了这篇文章。

**Comment by Li-Lian1069** [comment]
万分感谢！
