### ISSUE TITLE
pick interface for http proxy

### ISSUE THREAD

**Issue by SemanticInheritance** [fatedier/frp#2367]
Hi,

I have multiple interfaces that i wish to create http proxy for, my basic config is:
```
[eth0-proxy]
type = tcp
remote_port = 6330
plugin = http_proxy

[eth1-proxy]
type = tcp
remote_port = 6330
plugin = http_proxy

```
i tried: local_addr, plugin_local_addr, local_ip, plugin_local_ip with eth0/1 interface ip hoping it would use it, but the endpoints keep returning the main server/interface ip.

Thanks.

**Comment by fatedier** [comment]
You can't do that now since frpc can't specify net interface. Maybe you can try to modify route tables to achieve the same thing.
