### ISSUE TITLE
frps运行一段时间后会自动退出

### ISSUE THREAD

**Issue by diannaobos** [fatedier/frp#237]
以下是错误信息
[root@OpenVZVPS-2016105652 frp]# ./frps -c ./frps.ini
panic: send on closed channel

goroutine 4774 [running]:
panic(0x764840, 0xc4203c5580)
        /home/wcl/.gvm/gos/go1.7.4/src/runtime/panic.go:500 +0x1a1
github.com/fatedier/frp/src/models/server.(*ProxyServer).connectionPoolManager(0xc4203d1340, 0xc4206dc720)
        /home/wcl/go_projects/src/github.com/fatedier/frp/src/models/server/server.go:458 +0x134
created by github.com/fatedier/frp/src/models/server.(*ProxyServer).Start
        /home/wcl/go_projects/src/github.com/fatedier/frp/src/models/server/server.go:235 +0x223

错误日志
2017/01/17 12:53:46 [control.go:212] [W] ProxyName [syncz] is not exist
2017/01/17 12:53:46 [control.go:212] [W] ProxyName [syncz] is not exist
2017/01/17 12:53:46 [control.go:212] [W] ProxyName [syncz] is not exist
2017/01/17 12:53:46 [control.go:212] [W] ProxyName [syncz] is not exist
2017/01/17 12:53:46 [control.go:212] [W] ProxyName [syncz] is not exist
2017/01/17 12:53:46 [control.go:212] [W] ProxyName [syncz] is not exist
2017/01/17 12:53:46 [control.go:212] [W] ProxyName [syncz] is not exist
2017/01/17 12:53:46 [control.go:343] [W] ProxyName [syncz], is not working when it gets one new work connnection
2017/01/17 12:53:46 [control.go:343] [W] ProxyName [syncz], is not working when it gets one new work connnection
2017/01/17 12:53:46 [control.go:343] [W] ProxyName [syncz], is not working when it gets one new work connnection
2017/01/17 12:53:46 [control.go:343] [W] ProxyName [syncz], is not working when it gets one new work connnection
2017/01/17 12:53:46 [control.go:343] [W] ProxyName [syncz], is not working when it gets one new work connnection
2017/01/17 12:53:46 [server.go:159] [I] ProxyName [syncz], type http listen for host [syncz.ml] location []
2017/01/17 12:53:46 [server.go:159] [I] ProxyName [syncz], type http listen for host [www.syncz.ml] location []
2017/01/17 12:53:46 [control.go:336] [I] ProxyName [syncz], start proxy success
2017/01/17 12:53:46 [control.go:338] [I] ProxyName [syncz], created by PrivilegeMode
2017/01/17 12:53:46 [control.go:343] [W] ProxyName [syncz], is not working when it gets one new work connnection
2017/01/17 12:55:57 [server.go:246] [I] ProxyName [syncz], listener is closed
2017/01/17 12:55:57 [server.go:246] [I] ProxyName [syncz], listener is closed
2017/01/17 12:55:57 [control.go:133] [E] ProxyName [syncz], client heartbeat timeout
2017/01/17 12:55:57 [control.go:185] [W] ProxyName [syncz], write to client error, proxy exit

我的frps.ini配置文件
[common]
bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
dashboard_port = 7500
log_file = ./frps.log
log_level = info
log_max_days = 3
privilege_mode = true
privilege_token = frp888
max_pool_count = 10000

麻烦您提示一下我该怎么解决。

**Comment by fatedier** [comment]
开启连接池之后，有一定几率会发生这个问题，可以先不启用连接池。

正在重构代码，这部分就不单独修复了。

**Comment by diannaobos** [comment]
不启用连接池后不自动退出了，感谢！解决方法：将服务器max_pool_count注释 ，客户端pool_count注释
