### ISSUE TITLE
一个客户端能连接多个服务端

### ISSUE THREAD

**Issue by kingtu** [fatedier/frp#2370]
希望实现一个客户端能连接多个服务端，省得再开一个客户端。
# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[server1-service1]
server_addr = 8.8.8.2
server_port = 7000

type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

[server2-service1]
server_addr = 8.8.8.3
server_port = 7000

type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

**Comment by cl000282** [comment]
用不同的配置文件，多开一个进程就好了
