### ISSUE TITLE
Show client login IP and run ID on dashboard

### ISSUE THREAD

**Issue by TwintailFD** [fatedier/frp#2371]
**The solution you want**

Show client login IP and run ID on dashboard
**Alternatives considered**

Maybe this is the simplest solution
**How to implement this function**

Update dashboard
**Application scenarios of this function**

Easy to monitor client (public FRP service)

**Comment by fatedier** [comment]
You can set `user = xxx` in each frpc's config file to distinguish them. Every proxy name has user name prefix.
