### ISSUE TITLE
Logging stopped working (log_file)

### ISSUE THREAD

**Issue by amiroff157** [fatedier/frp#2375]
**[REQUIRED] hat version of frp are you using** 

Version: 0.36.0

**[REQUIRED] What operating system and processor architecture are you using**
OS: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1034-raspi)
CPU architecture: aarch64

**[REQUIRED] description of errors**

**confile**
server_addr = ****
server_port = ****
protocol = tcp
tls_enable = true

log_file = /etc/frp/frpc.log
log_level = info
log_max_days = 7

frp doesn't write logs anymore, there's no error it just doesn't write to "/etc/frp/frpc.log".

**Comment by fatedier** [comment]
Can you try another `log_file` path?

**Comment by amiroff157** [comment]
> Can you try another `log_file` path?

trying on the usual `/home/ubuntu/user` path, will check within a day or so and see if it works 👍🏼

**Comment by amiroff157** [comment]
> Can you try another `log_file` path?

tried creating a file on path `/home/ubuntu/frps.log` the file is there but remains empty
