### ISSUE TITLE
解压密码 

### ISSUE THREAD

**Issue by Yofo-me** [fatedier/frp#2377]
解压密码 多少啊

**Comment by Yofo-me** [comment]
![image](https://user-images.githubusercontent.com/55388087/116805278-d5a81900-ab57-11eb-9e78-63659d671591.png)
用命令从github下载的文件一直报毒，chrome也报毒直接不让下载

**Comment by sorahen** [comment]
怎么会有解压密码呢, 不会是被劫持下载到错误文件了吧

**Comment by cl000282** [comment]
自己编译吧
