### ISSUE TITLE
Certificate handling as it would do a tunneling service

### ISSUE THREAD

**Issue by hons82** [fatedier/frp#2378]
**The solution you want**
I've been exploring frp to use basically as a tunnel service. This means, I'd need a way to have a valid certificate on the server through which I can connect internally to my clients which are on http or https with a self signed certificate. The https2http plugin does exactly that, but from what I understood in the documentation it is required that every client has a copy of the server certificate and the private server key.

That's not what I need, as I do not want the server certificate spread over my clients.

**Alternatives considered**

Of course I did check the https2htto plugin for this.

**Comment by fatedier** [comment]
You can deploy a nginx before frps to handle certificate and redirect HTTP requests to frp.
