### ISSUE TITLE
Optional basic auth for admin UI

### ISSUE THREAD

**Issue by bngabor** [fatedier/frp#2381]
If admin username and password is empty, then turn off the http basic auth for admin UI.

Alternatives:
- empty username and password
- new config record for auth turn on/off

admin_user = ""
admin_pwd = ""
or
admin_auth=false

If if could be optional, then we can use external authentication, with two factor, etc.

**Comment by fatedier** [comment]
Duplicate of https://github.com/fatedier/frp/issues/2344
