### ISSUE TITLE
frp支持多路聚合实现带宽叠加的效果吗？

### ISSUE THREAD

**Issue by chenbihao** [fatedier/frp#2384]
rt，比如我想把本地一台没有公网IP的端口穿透出来，
现在有好多台空闲的云主机，但是每台的带宽都挺小，

目前版本可以1台 client 连到N台 server 实现带宽聚合吗

**Comment by fatedier** [comment]
之前有过这样的想法，也在文件传输这个方向上做了一些验证，目前有一些带宽相关的算法问题需要优化，一直没有时间跟进，后续有空了会继续这方面的研究

https://github.com/fatedier/fft
