### ISSUE TITLE
【感谢大神做出的贡献】ssh 内网机器求教

### ISSUE THREAD

**Issue by gamelife1314** [fatedier/frp#239]
#### 我在我的具有公网ip的服务器上搭建了**frp server（139.149.218.126【假设】）**，简单配置如下：
[common]  
bind_port = 7000  
dashboard_port = 7500  
dashboard_user = gamelife  
dashboard_pwd = nopassword  

[ssh]  
listen_port = 6000  
auth_token = noauthtoken  

启动正常：
>     [root@server-241 frp]# ./frps -c ./frps.ini  
>     2017/01/21 16:38:02 [main.go:194] [I] Start frps success  
>     2017/01/21 16:41:47 [control.go:338] [I] ProxyName [ssh], start proxy succes  

#### 我的内网frpc配置如下：  
[common]  
server_addr = 139.149.218.126  
server_port = 7000  
auth_token = noauthtoken  

[ssh]  
local_ip = 192.168.153.130  
local_port = 22  
use_encryption = true  
use_gzip = true  

启动正常：
>     [root 16:40:44 frp]:./frpc -c ./frpc.ini
>     2017/01/21 16:40:50 [main.go:109] [I] Start frpc success
>     2017/01/21 16:40:50 [control.go:206] [I] ProxyName [ssh], connect to server [139.129.237.241:7000] success!
>     2017/01/21 16:40:50 [control.go:220] [I] Start to send heartbeat to frps

我在其他机器上该如何ssh到我的内网机器（192.168.153.130），**假设我的内网机器用户名：root，密码：root**？？？

**Comment by fatedier** [comment]
文档中有说明 [通过 ssh 访问公司内网机器](https://github.com/fatedier/frp/blob/master/README_zh.md#%E9%80%9A%E8%BF%87-ssh-%E8%AE%BF%E9%97%AE%E5%85%AC%E5%8F%B8%E5%86%85%E7%BD%91%E6%9C%BA%E5%99%A8)

**Comment by gamelife1314** [comment]
#### 我看了这个但是没配置成功  
文档里面是这样写的：  

>     5. 通过 ssh 访问内网机器，假设用户名为 test：
>
>     ssh -oPort=6000 test@x.x.x.x

这里的**test**是frps的用户名还是frpc的，**x.x.x.x**是谁的IP？我把它改成frpc的连接不上

**Comment by fatedier** [comment]
去掉错误的答案剩下的就是正确的。

**Comment by gamelife1314** [comment]
我弄好了，初出茅庐，谢谢

**Comment by endokai** [comment]
ssh的连接信息当然是ssh的...难道映射了还会顺便改掉ssh的密码不成
