### ISSUE TITLE
STCP preshared key authentication for one server and one client? 

### ISSUE THREAD

**Issue by yuis-ice** [fatedier/frp#2390]
I saw "Expose your service privately" on the README. In the section, it's explained that client B as a SSH server and client C as a SSH client, so there are "server", "client", "client", right? But here what I want to do is, server A as a SSH client and client B as a SSH server. This structure. Just like "Access your computer in LAN by SSH" on the README. Basically client will be required to set "sk" preshared key in order to connect to the frp server's port 7000. 

So, I wonder I can or cannot do something like this? :

```
# frps.ini  
[common]
bind_port = 7000
sk = abcdefg
```

```
# frpc.ini
[common]
server_addr = 220.xx.xx.xx
server_port = 7000
sk = abcdefg

[ssh]
type = stcp
local_ip = 127.0.0.1
local_port = 2222
remote_port = 6001
```

**Comment by fatedier** [comment]
Not support. You should deploy frps and one frpc in the same machine.
