### ISSUE TITLE
怎么远程关闭FRPC端？

### ISSUE THREAD

**Issue by shadow1ng** [fatedier/frp#2391]
能否加个功能，可以通过frps的web面板，关闭某些frpc？   
有些frpc用不到了，但还一直连着，能否远程关闭？

**Comment by fatedier** [comment]
通过 frps 来关闭不是很好，有一定风险。

目前可以通过将 frpc 的 admin 界面通过 frps 代理出来，然后通过这个代理的界面来操作 frpc。这样这个需求就变成 frpc 的管理界面提供一个关闭自身的方法，这个是可以考虑的。

**Comment by shadow1ng** [comment]
那如果是  
1. frps可以提供一个关闭按钮，然后发出exit信号。  
2. 当frpc 遇到exit 信息，则进行退出操作   
这样的话，更好批量管理吧。  

或者把frpc的管理界面的部分内容映射到frps的管理界面(可能比较难实现）

**Comment by fatedier** [comment]
1. 不太想在 frps 的 Dashboard 中提供直接修改，关闭客户端的能力，有一定风险，使用不当可能会造成用户和公司损失。目前是只读，如果某个用户只想暴露 80 端口，是没有其他途径由服务端管理人员进行修改从而扩大暴露范围的。
2. frpc 的管理界面映射到 frps，这个可能会考虑，这样的话 frps Dashboard 相当于一个管控界面的路由，frpc 的配置中通过简单配置可以选择是否将管理界面暴露到 frps 的 Dashboard，并且需要设置自己的用户名密码或者 token。在 frps 的 Dashboard 页面，想要查看某个 frpc 的管理界面，需要输入正确的鉴权信息。

**Comment by shadow1ng** [comment]
> 是否会考虑这样的一种实现方式 在资源受限的linux arm上运行frpc与服务端frps连接，frpc用不到了，退出让出资源，可不可以实现一种frpc超时机制，当一段时间内没有数据交互，主动断开与frps的连接

我后面自行修改了一下，心跳包的时候验证token，如果token不正确，就退出

**Comment by shaojs321** [comment]
> 在资源受限的linux arm上运行frpc与服务端frps连接，frpc用不到了，退出让出资源，可不可以实现一种frpc超时机制，当一段时间内没有数据交互，主动断开与frps的连接

针对风险问题，是否能将风险功能单独为组件或者插件，选择性安装。看了项目的issues，很多功能请求是有风险的，但有些人也需要，作为组件或者插件安装就可以避免此问题。

**Comment by yinlsea** [comment]
> 

确实需要这样的功能

**Comment by fatedier** [comment]
> 通过 frps 来关闭不是很好，有一定风险。
> 
> 目前可以通过将 frpc 的 admin 界面通过 frps 代理出来，然后通过这个代理的界面来操作 frpc。这样这个需求就变成 frpc 的管理界面提供一个关闭自身的方法，这个是可以考虑的。

新版本 frpc admin api 提供了 stop 接口用于关闭客户端。
