### ISSUE TITLE
frpc连接失败的时候能否执行一个脚本？

### ISSUE THREAD

**Issue by MateorChan** [fatedier/frp#2392]
有时候远程连接到客户机，更新了frpc.ini之后发现出错了，但是已经不通了，所以无能为力

如果frpc能够在执行失败（配置文件错误、网络不通等所有情况下）时，执行一个bash，那就好了

**Comment by fatedier** [comment]
能否举一个例子说明做了哪些类型的更新导致无法连通？

**Comment by MateorChan** [comment]
> 能否举一个例子说明做了哪些类型的更新导致无法连通？

并非特指“哪些类型的更新”，比如刚才我连上了一台远程的客户机，希望新增一个TCP的穿透，然而我手误输错了且直接service restart，现在我的客户机就处于无法连通的状态。

如果能新增一个功能，使得frpc因为某种原因（比如配置文件格式错误等）无法正常启动和连接服务端时，能够调用一下指定的shell脚本，那就太好了

**Comment by ax2009live** [comment]
这种一旦断开就 OVER 的场景，推荐的做法是：保持两个 frpc 工作，一个有问题，另外一个还可以连接；

**Comment by MateorChan** [comment]
> 这种一旦断开就 OVER 的场景，推荐的做法是：保持两个 frpc 工作，一个有问题，另外一个还可以连接；

确实是准备这么做，但是如果客户端能支持无法连接时执行一个shell的话，那就有更多可定制的玩法了

**Comment by ax2009live** [comment]
frpc 都搞坏了，shell 意义何在？ 复杂化了，预防思维优于补救思维；

**Comment by fatedier** [comment]
通常这样的设计需要考虑一个通用的可扩展性，如果只是为了解决某一个特定的问题，确实复杂化了。可以想想有没有其他的应对方式。

比如如果是增加 TCP 穿透，可以通过修改配置文件后 Reload 的方式来做，Reload 之前可以检查配置文件的有效性，出错的话就不会应用，也不会影响到正在运行的 frpc。

**Comment by MateorChan** [comment]
> 通常这样的设计需要考虑一个通用的可扩展性，如果只是为了解决某一个特定的问题，确实复杂化了。可以想想有没有其他的应对方式。
> 
> 比如如果是增加 TCP 穿透，可以通过修改配置文件后 Reload 的方式来做，Reload 之前可以检查配置文件的有效性，出错的话就不会应用，也不会影响到正在运行的 frpc。

好的，感谢🙏
