### ISSUE TITLE
可不可以针对每个不同的proxy代理服务单独设置proxy_bind_addr	

### ISSUE THREAD

**Issue by fjh1997** [fatedier/frp#2396]
目前的proxy_bind_addr	是针对frps全局设置的，可不可以在frpc上面针对每个不同的服务设置不同的代理配置，比如是ssh服务就侦听在本地端口，如果是http服务就侦听在外部端口？

**Comment by fatedier** [comment]
目前不考虑支持这样的配置增加复杂性。你的需求可以搭建两个 frps，一个给外部用，一个给内部使用。

**Comment by fjh1997** [comment]
> 目前不考虑支持这样的配置增加复杂性。你的需求可以搭建两个 frps，一个给外部用，一个给内部使用。

非常感谢
