### ISSUE TITLE
能否支持site-to-site?

### ISSUE THREAD

**Issue by galaxyskyknight** [fatedier/frp#2398]
我有两个异地局域网，能否用frps和公网的一台vps(有public ip)把两地局域网透明互通起来？或者不用vps, 其中一个局域网的wan口带公网也可以跑frps，用C/S模式。关键是内网能透明互通。

**Comment by fatedier** [comment]
你需要的是 VPN? 目前不支持，可以尝试其他的 VPN 项目。
