### ISSUE TITLE
AC66U 测试失败

### ISSUE THREAD

**Issue by lotc** [fatedier/frp#240]
硬件：AC66U，CPU BCM 5300，作为客户端。
运行 `./frpc -c frpc.ini` 时报错
返回错误 `[control.go:151] [E] ProxyName [web], connect to server [此处ip隐去:1234] error, dial tcp 此处ip隐去:1234: errno -9`

错误代码 9，是什么意思？

**Comment by Yovanchen** [comment]
应该是芯片对应不上，你可以尝试去刷一个梅林固件，然后软件中心安装frp客户端，将参数填入即可。
梅林固件下载地址：https://sourceforge.net/projects/asuswrt-merlin/files/RT-AC66U/Release/
![092323ty33ye3qjg4qj0na](https://cloud.githubusercontent.com/assets/25312362/22229940/c9cdd9fe-e215-11e6-894a-443fec5169f6.png)

**Comment by lotc** [comment]
@Yovanchen 用的就是这个, 里面没有软件中心. 有软件中心的是二次修改版的.

**Comment by lotc** [comment]
参考这里 https://github.com/RMerl/asuswrt-merlin/issues/974
应该还是编译时环境设置的问题
