### ISSUE TITLE
咨询配置

### ISSUE THREAD

**Issue by songyuyx** [fatedier/frp#2402]
非常感谢开发了这么好的软件, 太棒了。

希望借助该软件实现内网LAN的web的访问, 情况如下：

1- A主机, 位于内网，有个Web服务器，访问地址为 http://192.168.111.81/mplus
2- B主机, 位于内网，用于作为frpC, IP地址为 192.168.182.253
3- C主机，位于外网，有公网IP， 用于frpS
已确认在B主机的浏览器上输入http://192.168.111.81/mplus,是可以正常访问的A主机的Web

现希望通过 C主机 对 A主机的 Web进行访问，按照如下配置：

C主机，用于frpS：
#FrpS
bind_addr = X.X.X.X
bind_port = 2913
kcp_bind_port = 2913
vhost_http_port = 8080
token = 123456

B主机，用于frpC：
#FrpC
[common]
server_addr = X.X.X.X
server_port = 2913
token = 123456
admin_addr = 127.0.0.1
admin_port = 7400
admin_user = admin
admin_pwd = admin
[MES1]
type = http
local_port = 80
remote_port = 8080
custom_domains = 192.168.111.81/mesplus   //A主机的Web地址

按照如上配置。B主机和C主机能够握手成功，在FrpC的CMD窗口内，看到的都是successful. 应该是连接上了。

但是我在公网电脑上输入http://X.X.X.X:8080 却访问不了A的Web，提示:
"The page you requested was not found.  Sorry, the page you are looking for is currently unavailable.  Please try again later."

请大佬协助帮忙看看，是哪里设置出了问题呢

**Comment by songyuyx** [comment]
![image](https://user-images.githubusercontent.com/55168335/118567876-33358b80-b73c-11eb-95f2-613323dc2fbf.png)

**Comment by fatedier** [comment]
主机地址不包括路径，`192.168.111.81/mesplus -> 192.168.111.81`

**Comment by songyuyx** [comment]
问题已解决，是配置问题。 此贴关闭

再次谢谢作者
