### ISSUE TITLE
https2http不成功

### ISSUE THREAD

**Issue by liiloo100** [fatedier/frp#2403]
frps.ini 内容如下：
[common]
bind_port = 7000
vhost_https_port = 443
privilege_token =

frpc.ini 内容如下：
[common]
server_addr = x.x.x.x
server_port = 7000

[test_htts2http]
type = https
custom_domains = test.yourdomain.com

plugin = https2http
plugin_local_addr = 192.168.10.189:80

# HTTPS 证书相关的配置
plugin_crt_path = /volume2/docker/frpc/server.crt
plugin_key_path = /volume2/docker/frpc/server.key
plugin_host_header_rewrite = 127.0.0.1
plugin_header_X-From-Where = frp

这是配置方法，按这个配置没有成功，有几个问题想问一下；
1.frps.ini我开启了443端口，防火墙开启了443，但没有成功，需要开启443吗
2.证书是使用IIS的还是Apache的。

**Comment by ax2009live** [comment]
你的 fprc 客户端能访问 /volume2/docker/frpc/ 下的文件吗？

**Comment by z0ow** [comment]
我的frp好像也没办法正常使用https2http，浏览器报ERR_TIMED_OUT错误，感觉像是证书的问题，但是frpc和frps没有任何报错
