### ISSUE TITLE
http映射URL变成访问内网IP地址

### ISSUE THREAD

**Issue by galaxyskyknight** [fatedier/frp#2408]
版本0.36.2一条普通的http映射，服务器8080 子域名映射内网一台netgear 6150的管理后台页面80端口，勾选加密和压缩。每次在公网用http://子域名:8080访问的时候，浏览器就变成了跳转访问http://10.0.0.3:80了，10.0.0.3是内网netgear的内部IP（我在公网，应该不是dns问题，感觉是frp吧10.0.0.3返回给了浏览器），结果当然是无法打开访问失败了。 请问是什么原因，如何解决？同一个内网下其他的设备同样的http映射又是好的，就这台设备特殊。

**Comment by galaxyskyknight** [comment]
谁遇到相似问题吗

**Comment by fatedier** [comment]
这种一般是前端的问题，前端返回的路径可能就是绝对路径。

**Comment by galaxyskyknight** [comment]
> 这种一般是前端的问题，前端返回的路径可能就是绝对路径。

那我要怎么弄，穿透不就是解决这个问题的吗，frps上有没有什么workaround?

**Comment by fatedier** [comment]
将你的内网服务的路径修改为相对路径即可，或者设置成你通过外网访问的 Host。这个具体和你的服务相关，frp 不会修改这个中间的内容。
