### ISSUE TITLE
日志显示客户端和服务端启动连接正常，但是依然无法访问内网web应用

### ISSUE THREAD

**Issue by doghua** [fatedier/frp#241]
`Get msg from frpc: {"type":1,"proxy_name":"web01","auth_key":"f701e19e6d53b4b3eff855502f8a1659","use_encryption":false,"use_gzip":false,"pool_count":0,"privilege_mode":false,"privilege_key":"","proxy_type":"","remote_port":0,"custom_domains":null,"locations":null,"host_header_rewrite":"","http_username":"","http_password":"","subdomain":"","timestamp":1485855021}`
日志中显示这样的是否有问题？custom_domains为null？

**Comment by fatedier** [comment]
日志不一定有问题，custom_domain 可能是在服务端配置了的。
