### ISSUE TITLE
从0.24.2版本开始无法在winserver2003上运行

### ISSUE THREAD

**Issue by xingtongsf** [fatedier/frp#2412]
0.24.1版本是最后一个能在windows2003上运行的版本。
从0.24.2开始，FRPS就无法在2003上运行，我的是win2003 X64位。
提示“这不是有效的win32程序“。
无论我下载的是64位程序还是32位程序。
希望还能支持win2003系统

**Comment by lbbboy** [comment]
自己编译一个，简单的。

**Comment by fatedier** [comment]
旧的系统和技术会被不断淘汰，抛弃历史包袱才能降低开发和维护成本，随着 golang 版本的更新，会逐渐不支持一些已经停止维护的系统。不管从安全性还是功能性上来说，建议及时更新系统。
