### ISSUE TITLE
frps dashboard last start & last close time issue

### ISSUE THREAD

**Issue by elnayang** [fatedier/frp#2415]
Last Start & Last Close 时间与服务器相差 12 小时

服务器使用 Time zone: Asia/Hong_Kong (HKT, +0800)

现在是 14:30，显示的是 2:30

请问 frps.ini 是否有配置时区的地方 或者哪里出错了

谢谢！

**Comment by fatedier** [comment]
时间是服务器时间，会自动获取时区。

**Comment by elnayang** [comment]
> 时间是服务器时间，会自动获取时区。

重新换了一个 NAT 服务器部署后，时间没有问题
