### ISSUE TITLE
关于Wiki中网络传输速度慢的疑问

### ISSUE THREAD

**Issue by DaPoHou** [fatedier/frp#2418]
我的网络环境是：
frpc 网络是500Mbps专线，上下带宽对等，运行在NAS上。
frps 网络是有公网IP的家宽，下载200Mbit/s，上传30Mbit/s（通过多拨，实现下载200Mbit/s，上传70Mbit/s)，frps运行在网件路由器openwrt上。

根据Wiki中的描述：
> 由于流量需要经过服务器转发，所以传输速度的快慢取决于服务器的下行带宽和客户端的上行带宽，通常家用宽带的上行带宽较低，限制了出口的速度

我的服务器下行带宽是200M，客户端上行带宽是200M，那么通过frp中转速度应该在200M左右。
实际通过iperf3测试，只有30Mbit/s。

那么限制frp转发速率的瓶颈是不是也取决于服务器的上行带宽？

**Comment by fatedier** [comment]
是的，服务器是双向通信，这里描述确实不太准确。
