### ISSUE TITLE
 Difference between chisel and frp

### ISSUE THREAD

**Issue by yuswift** [fatedier/frp#2419]
Hi, I'm new to frp. I'd like to know the difference between [chisel](https://github.com/jpillora/chisel) and frp. Can someone share your opinions? Thanks.

**Comment by egorky** [comment]
IMO, Chisel uses HTTP as a tunneling protocol while FRP uses its own protocol. Maybe the upside of Chisel resides in that it can fool firewalls making them believe is just a HTTP passing through. As far as services go, FRP is more versatile.

**Comment by yuswift** [comment]
@egorky thanks!
/close
