### ISSUE TITLE
能否添加一个实例连接2个服务器的功能

### ISSUE THREAD

**Issue by wsclon** [fatedier/frp#242]
为了可用性，我想让一个frpc客户端实例连接到2个或更多frps服务端。电脑和服务器启动2个frpc实例容易，但是路由器就不那么方便了。

另外，如果能有通过frps修改frpc参数的功能就更好了。

**Comment by fatedier** [comment]
第一个问题，没有支持的打算，还没有想好多 frps 服务端的架构。如果只是启动两个 frpc 可以实现的话就没必要加入这一功能了，如果加入了，就是会提供更加高级一些的功能。

第二个问题，在计划中，目前的想法是先加入一些基础功能，之后再优化使用体验。
