### ISSUE TITLE
MAC OS10.11.6 运行最新0.36.2出现错误

### ISSUE THREAD

**Issue by sunup2015** [fatedier/frp#2420]
MacBookAir:frpc root# ./frpc -c ./frpc.ini
dyld: Symbol not found: _clock_gettime
  Referenced from: /Library/frpc/./frpc
  Expected in: flat namespace

Trace/BPT trap: 5

不知道是什么情况，希望遇到过这种情况的朋友帮忙看看！

**Comment by fatedier** [comment]
Go1.16 doesn't support macos10.11 and Go 1.17 will require macOS 10.13 High Sierra or later.

**Comment by sunup2015** [comment]
> Go1.16 不支持 macos10.11，Go 1.17 将需要 macOS 10.13 High Sierra 或更高版本。

OK，I see. Thank you very much

**Comment by bowuL** [comment]
兄弟，我遇到了一个问题，我的使用的腾讯轻量云服务器跟公司内网的mac主机，别的都配好了，但是在ssh连接这一步，一直提示我输入密码，我输入了各种密码都不行，云服务器的、mac主机的，都不行，请问你有遇到这样的问题过吗，大概怎么处理呢

**Comment by bowuL** [comment]
兄弟，我遇到了一个问题，我的使用的腾讯轻量云服务器跟公司内网的mac主机，别的都配好了，但是在ssh连接这一步，一直提示我输入密码，我输入了各种密码都不行，云服务器的、mac主机的，都不行，请问你有遇到这样的问题过吗，大概怎么处理呢
