### ISSUE TITLE
frpc 运行出错

### ISSUE THREAD

**Issue by zhumingwei** [fatedier/frp#2427]
version ： 0.37.0

错误信息 ：

```
2021/06/03 03:54:28 [I] [service.go:304] [9765624ae6929628] login to server success, get run id [9765624ae6929628], server udp port [0]
2021/06/03 03:54:28 [I] [proxy_manager.go:144] [9765624ae6929628] proxy added: [ssh]
2021/06/03 03:54:28 [I] [control.go:180] [9765624ae6929628] [ssh] start proxy success
2021/06/03 03:54:44 [E] [proxy.go:797] [9765624ae6929628] [ssh] connect to local service [127.0.0.1:22] error: dial tcp 127.0.0.1:22: connect: connection refused
```
请问下这是什情况下会出现的呢？

**Comment by jiqing112** [comment]
connect to local service [127.0.0.1:22] error: dial tcp 127.0.0.1:22: connect: connection refused

连接本地22端口被拒绝

**Comment by zhumingwei** [comment]
我使用的是华硕路由器，系统设置设置中已经打开了22端口，而且在内网的情况下ssh是可以登陆到路由器的

**Comment by zhumingwei** [comment]
使用 ssh admin@192.168.50.1 即可在内网登录路由器

**Comment by haiwenheaven** [comment]
我也是这个情况

**Comment by xqzr** [comment]
添加或修改 `local_ip = 192.168.50.1`

**Comment by haiwenheaven** [comment]
> connect to local service [127.0.0.1:22] error: dial tcp 127.0.0.1:22: connect: connection refused
> 
> 连接本地22端口被拒绝

这个怎么解决

**Comment by haiwenheaven** [comment]
我的解决了，我的客户端是window下的wsl，wsl的openssh-server要重新安装

**Comment by TheOctopus3430** [comment]
> 添加或修改 `local_ip = 192.168.50.1`

我通过这种方式解决了问题

**Comment by alextsao1999** [comment]
> 

这个是加在哪里/哪个文件？

**Comment by alextsao1999** [comment]
> 添加或修改 `local_ip = 192.168.50.1`


这个是加在哪里/哪个文件？

**Comment by xuan-git** [comment]
华为路由器。
在开通防火墙的情况下，需要设置ssh服务端主机为DMZ主机，绑定局域网ip（192.168.3.2）。
将127.0.0.1替换成192.168.3.2，解决问题。
