### ISSUE TITLE
内网存在防火墙，穿不透怎么办（在别的地方可以穿透）

### ISSUE THREAD

**Issue by lamcheukwing** [fatedier/frp#2428]

**Comment by xqzr** [comment]
尝试启用TLS。在客户端 `[common]` 内添加 `tls_enable = true` 。
示例：
```
[common]
...
tls_enable = true
```

**Comment by wyz0211zpc** [comment]
![image](https://user-images.githubusercontent.com/47886949/121307783-f3288980-c932-11eb-8942-6b6405930358.png)
同样遇到这个问题
