### ISSUE TITLE
0.37 linux64 frps文件无法使用

### ISSUE THREAD

**Issue by qq739977075** [fatedier/frp#2432]
配置如下:
[common]
vhost_http_port = 809
vhost_http_timeout = 300
vhost_https_port = 809
dashboard_addr = 0.0.0.0
dashboard_port = 811
dashboard_user = root
dashboard_pwd = he8888???
bind_addr = 0.0.0.0
bind_port = 809
bind_udp_port = 810
kcp_bind_port = 809
tcp_mux = true
max_ports_per_client = 0
max_pool_count = 5
subdomain_host = frp.****.com
heartbeat_timeout = 90
disable_log_color = true
log_max_days = 3
log_level = info
allow_ports = 808-909
log_file = /root/frp/frps.log

同样的配置上一个版本能用，这个版本无法打开，我用宝塔的supervisor无法启动

**Comment by yaott2020-666** [comment]
frps日志有吗

**Comment by qq739977075** [comment]
我之前看了目录，日志没打印出来，建议你检查下上传的文件是否完整



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月5日(周六) 下午4:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fatedier/frp] 0.37 linux64 frps文件无法使用 (#2432)




 
frps日志有吗

**Comment by yaott2020-666** [comment]
frps -c frps.ini
手动启动看看日志输出
连日志都没有怎么找问题

**Comment by qq739977075** [comment]
上一个版本我用的supervisord启动命令是：/root/frp/frps -c /root/frp/frps.ini &amp; 
手动启动日志显示没有找到common
现在改为：/root/frp/frps -c /root/frp/frps.ini
已经正常运行，软件非常实用且好用，感谢分享，感谢回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月5日(星期六) 晚上6:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fatedier/frp] 0.37 linux64 frps文件无法使用 (#2432)





 
frps -c frps.ini
 手动启动看看日志输出
 连日志都没有怎么找问题
