### ISSUE TITLE
frp using high CPU utilization

### ISSUE THREAD

**Issue by Sunil178** [fatedier/frp#2434]
This is for issue occurring while having only 15 connections.

**[REQUIRED] hat version of frp are you using** 

Version: 0.36.2

**[REQUIRED] What operating system and processor architecture are you using**
OS: Linux
CPU architecture: AMD64

**[REQUIRED] description of errors**
CPU is getting utilized very much highly which causes slow data transmission.
![image](https://user-images.githubusercontent.com/45064732/120794306-ab31ed00-c555-11eb-842d-132541dc24d3.png)

**confile**
[common]
bind_addr = 0.0.0.0
bind_port = 2000
bind_udp_port = 2001
kcp_bind_port = 2000

vhost_http_port = 80
vhost_https_port = 443
dashboard_addr = 0.0.0.0
dashboard_port = 2500
dashboard_user = admin
dashboard_pwd = admin
enable_prometheus = true
log_file = ./frps.log
log_level = info

log_max_days = 3
disable_log_color = false
detailed_errors_to_client = true
authentication_method = token
authenticate_heartbeats = false

authenticate_new_work_conns = false
authentication_timeout = 900
token = 12345678
oidc_issuer =
oidc_audience =
oidc_skip_expiry_check = false
OidcIssuer.
oidc_skip_issuer_check = false
allow_ports = 3000-50000
max_pool_count = 5
max_ports_per_client = 0
tls_enable = false
subdomain_host = frps.com
tcp_mux = true
udp_packet_size = 1500

protocol = http
type = http

**Total CPU**
Amazon aws's t3.medium instance with 2 vCPUs

** Last Log **
2021/06/05 14:06:34 [W] [http.go:92] do http proxy request error: no such domain: 13.232.138.251 /api/jsonws/invoke
2021/06/05 14:06:34 [W] [http.go:92] do http proxy request error: no such domain: 13.232.138.251 /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
2021/06/05 14:06:34 [W] [http.go:92] do http proxy request error: no such domain: 13.232.138.251 /solr/admin/info/system
2021/06/05 14:06:34 [W] [http.go:92] do http proxy request error: no such domain: 13.232.138.251 /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
2021/06/05 14:06:34 [W] [http.go:92] do http proxy request error: no such domain: 13.232.138.251 /index.php
2021/06/05 14:06:34 [W] [http.go:92] do http proxy request error: no such domain: 13.232.138.251 /
2021/06/05 14:06:35 [W] [http.go:92] do http proxy request error: no such domain: 13.232.138.251 /
2021/06/05 14:06:35 [W] [http.go:92] do http proxy request error: no such domain: 13.232.138.251 /wp-content/plugins/wp-file-manager/readme.txt
2021/06/05 14:06:35 [W] [http.go:92] do http proxy request error: no such domain: 13.232.138.251 /console/
2021/06/05 14:06:35 [W] [http.go:92] do http proxy request error: no such domain: 13.232.138.251 /Autodiscover/Autodiscover.xml
2021/06/05 14:06:35 [W] [http.go:92] do http proxy request error: no such domain: 13.232.138.251 /_ignition/execute-solution
2021/06/05 14:06:36 [I] [proxy.go:162] [ba30770f1c4e9e16] [android_proxy_8102] get a user connection [103.75.227.226:60572]
2021/06/05 14:06:49 [I] [proxy.go:162] [ba30770f1c4e9e16] [android_proxy_8102] get a user connection [103.75.227.226:60580]
2021/06/05 14:08:16 [I] [proxy.go:162] [ba30770f1c4e9e16] [android_proxy_8102] get a user connection [103.75.227.226:60628]
2021/06/05 14:08:22 [I] [proxy.go:162] [ba30770f1c4e9e16] [android_proxy_8102] get a user connection [103.75.227.226:60632]
2021/06/05 14:08:41 [I] [proxy.go:162] [ba30770f1c4e9e16] [android_proxy_8102] get a user connection [103.75.227.226:60644]
2021/06/05 14:08:59 [I] [proxy.go:162] [ba30770f1c4e9e16] [android_proxy_8102] get a user connection [103.75.227.226:60654]
2021/06/05 14:10:35 [I] [proxy.go:162] [ba30770f1c4e9e16] [android_proxy_8102] get a user connection [103.75.227.226:60705]
2021/06/05 14:11:12 [I] [proxy.go:162] [ba30770f1c4e9e16] [android_proxy_8102] get a user connection [103.75.227.226:60726]

**Comment by fatedier** [comment]
There is not enough information to detect what's wrong.

Config file, log, total CPU of your machine, etc...

**Comment by Sunil178** [comment]
Is it okay now?

**Comment by fatedier** [comment]
No idea from these logs. Can you reproduce this problem in local environment?
