### ISSUE TITLE
Http_proxy and Websocket protocol

### ISSUE THREAD

**Issue by steom** [fatedier/frp#2436]
Connecting to frps via HTTP PROXY with frpc websocket protocol does not work.

frpc "http_proxy" & "protocol = tcp" works fine
frpc "http_proxy" & "protocol = websocket" no connection

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frpc_full.ini#L10

Comments here describe that it only support tcp protocol.

**Comment by steom** [comment]
oh sorry,
I had never seen that note,
it's a limitation,
it's support can be implemented in future?

**Comment by fatedier** [comment]
I'm not sure. Let's keep this issue open as a proposal and see if someone can help.
