### ISSUE TITLE
希望可以分别控制上传和下载带宽。Bandwidth Limit: Separate upload and download bandwidth limit

### ISSUE THREAD

**Issue by H-e-l-l-oW-o-r-l-d** [fatedier/frp#2440]
我用frp连接到了我一个有公网ip的服务器进行Bittorrent做种上传，但发现在下载的时候也会有很多流量走frp通道，浪费了很多流量，所以想单独把下载带宽降低。

**Comment by fatedier** [comment]
https://github.com/fatedier/frp#bandwidth-limit
可以给指定的 proxy 设置限流，目前的策略是上传和下载加起来的值。
