### ISSUE TITLE
希望可以在client端控制每个服务是否允许wan访问

### ISSUE THREAD

**Issue by Sora233** [fatedier/frp#2441]
举个例子，我在client端配置了`ssh`和`web`两个服务，我希望在client配置让`web`监听`0.0.0.0`，而`ssh`监听`localhost`，而不是设置防火墙。

**Comment by Sora233** [comment]
一个简单workaround，如果有人需要的话 [commit](https://github.com/Sora233/frp/commit/60dfd67ffdf3d86020e29f3c6d19e80e8507ab71)。
仅TCP/UDP模式在client端添加了remote_addr (0.0.0.0 or localhost or other)
也许还可以支持多网卡，但我只是简单地想让frp保留http的同时开一个非公开的ssh反向代理。

**Comment by fatedier** [comment]
可以启动两个 frps，通过 `proxy_bind_addr` 设置要绑定的地址，分别用做不同的用途。
