### ISSUE TITLE
客户端新增一个线程监听配置文件，当配置文件发生变化时重启客户端服务

### ISSUE THREAD

**Issue by weifeng12x** [fatedier/frp#2443]
**The solution you want**

客户端新增一个线程监听配置文件，当配置文件发生变化时重启客户端服务

**Alternatives considered**

客户端启动后只提供连接鉴权等信息，所有的链接信息都在服务器上配置（这个工作量太大了。。。），然后实现热更新

**How to implement this function**

1.获得客户端启动的配置文件
2.用一个线程去监听这个文件
3.当文件发生变化时，校验配置是否正确，如果正确重启服务

**Application scenarios of this function**

现在想要修改映射连接需要修改配置文件，并且杀掉进程再重新启动。如果主动监听配置文件变化然后重启服务则可以减少重复操作

**Comment by fatedier** [comment]
这个问题和 https://github.com/fatedier/frp/issues/1176 重复了。

**Comment by QQ2017** [comment]
你不知道可以reload吗？
