### ISSUE TITLE
使用https2http时，wss连接超时

### ISSUE THREAD

**Issue by hyena04** [fatedier/frp#2446]
使用https2http插件时，wss连接超时

[wss_test]
type = https
custom_domains = test.xxxx.cn

plugin = https2http
plugin_local_addr = 127.0.0.1:31143

plugin_crt_path = fullchain.cer
plugin_key_path = key

**Comment by AirYang** [comment]
不是https时，连接websocket没有问题

**Comment by ax2009live** [comment]
你的证书能被fprc 客户端能访问正确访问吗？是绝对路径吗？
