### ISSUE TITLE
编译mips32服务端试出错

### ISSUE THREAD

**Issue by gavin219** [fatedier/frp#245]
src/utils/vhost/router.go:113: undefined: strings.Compare
请问如何解决
frpc客户端正常编译了
我在恩山发了帖子，也没有答复的。还请作者帮忙
http://www.right.com.cn/forum/thread-207072-1-1.html

**Comment by fatedier** [comment]
Go 编译环境不正确，也可能是版本问题。

**Comment by gavin219** [comment]
1、centos 6 x64,go版本为1.4，失败；
2、centos 6 x64,go版本为1.8，mips成功，mipsle成功，但是我发现1.8版本里没有mips32。

**Comment by lotc** [comment]
请参考 #198

**Comment by gavin219** [comment]
使用gomini编译frps是出错的。但是frpc就没问题。貌似是go版本问题。 @lotc

**Comment by fatedier** [comment]
@gavin219 go1.8 才开始支持 mips32，目前 1.8 还不是正式发布的版本。

mips 32位的 GOARCH 就是 mips，64位是 mips64。

**Comment by gavin219** [comment]
@fatedier 等1.8正式版本……？

**Comment by fatedier** [comment]
@gavin219 这个可以给 golang 提 issue....

**Comment by fatedier** [comment]
https://github.com/golang/go/issues/18880

**Comment by fatedier** [comment]
不清楚如何在其他平台交叉编译的时候怎么配置这个 FPU。

**Comment by gavin219** [comment]
原来如此……

**Comment by fatedier** [comment]
https://groups.google.com/d/msg/golang-nuts/DT_P9UPKHgI/SWG61VaODwAJ

看了下，go 官方团队后续还是会解决这个问题的。

**Comment by gavin219** [comment]
只有期待了……

**Comment by yijing1998** [comment]
可重新编译 mt7620 ramips 架构的lede固件，make kernel_menuconfig，在kernel type中选择mips fpu emulator。该固件可直接运行frp release  v0.13.0。

**Comment by IxsCN** [comment]
我编译了未开启 FPU emulator 也能使用的版本，现在只有 mipsle (MTK 762x)。
需要的可以试试 
https://github.com/IxsCN/frpc_mipsle_noFPU

**Comment by nwct** [comment]
我已经编译了0.13.0版本的mips32le的客户端和服务端，有需要的可以下载使用。
下载地址是:https://github.com/nwct/frpu/releases

编译过程中遇到过坑，基本上就是新版本go的依赖和老版本的依赖不兼容的问题 

另外，go1.8版本编译出来的mipsle并不是mips32le这个架构的cpu能使用的 
所以，现在mt7620a这种路由器应该使用mips32le版本的程序
