### ISSUE TITLE
How to work with caddy?

### ISSUE THREAD

**Issue by qiuhaotc** [fatedier/frp#2453]
My configuration:

# frps.ini

```ini
[common]
bind_port = 7000
vhost_http_port = 7001
tcp_mux = true
token = 123
```

# frpc.ini

```ini
[common]
server_addr = remote_ip
server_port = 7000
token = 123

[web]
type = http
local_ip = 127.0.0.1
local_port = 8080
remote_port = 7001
custom_domains = remote_ip

```

# caddyfile

```
subdomain.domain.com {
    gzip
    timeouts none
    proxy / http://localhost:7001 {
        transparent
    }
}

```

# problem

I can use http://remote_ip:7001 to view that site, but when I try to use https://subdomain.domain.com to view the site, it always said:

```
The page you requested was not found.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

The server is powered by frp.

Faithfully yours, frp.
```

Can someone give some advice on that, how to solve that problem?

**Comment by qiuhaotc** [comment]
Error log in server

```log
2021/06/21 15:16:37 [W] [http.go:92] do http proxy request error: no such domain: subdomain.domain.com / 
```

**Comment by fatedier** [comment]
`custom_domains = remote_ip` -> `custom_domains = subdomain.domain.com`

**Comment by qiuhaotc** [comment]
> `custom_domains = remote_ip` -> `custom_domains = subdomain.domain.com`

Thanks for the information, I will give it a try

**Comment by qiuhaotc** [comment]
Its working, thanks a lot!!
