### ISSUE TITLE
在映射Nginx的端口的时候，有一个前导符造成访问不成功

### ISSUE THREAD

**Issue by zsinba** [fatedier/frp#2454]
**[REQUIRED] hat version of frp are you using** 

Version: Latest（today）

**[REQUIRED] What operating system and processor architecture are you using**
OS: Raspberry 4B
CPU architecture: Arm

**[REQUIRED] description of errors**

**confile**

**log file**

**Steps to reproduce the issue**
1. FRPC  映射 80 
![image](https://user-images.githubusercontent.com/890157/122852244-e3ea0880-d342-11eb-886b-3aaaad3d0360.png)

2. Nginx 下面会出来  
![image](https://user-images.githubusercontent.com/890157/122852619-830f0000-d343-11eb-8e5e-1e1b792f1cea.png)
怀疑是frp转发的时候，多了或者添加了什么字符的原因
![image](https://user-images.githubusercontent.com/890157/122852672-991cc080-d343-11eb-83bc-9c3113349c3e.png)

而正常的应该是这样的日志：
![image](https://user-images.githubusercontent.com/890157/122852714-a5088280-d343-11eb-80a1-f547ea6cf1f4.png)

**Supplementary information**

**Can you guess what caused this issue**
配置原因或者代码原因， 转发时多了字符。
**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by ax2009live** [comment]
个人觉得应该是你配置有问题；
你是通过ip访问还是域名访问？
你可以贴出frps的设置吗？
假如是ip访问：
 frps的ip：192.168.0.1
 frpc的ip：192.168.0.2
http://192.168.0.1:19091  等同于 http://192.168.0.2

**Comment by zsinba** [comment]
我也是配置过很多次，没有出问题。 这是刚发现的。
FRPS是192。168。1。168
FRPC是192。168。1。123
168这个服务器是有外网IP的，双穴主机。
FRPC仅做了一个TCP端口转发，没其他配置。

我估计原因是Go编译的东西，在Raspberry下面有问题，造成多出来 一个字符。
这样怀疑的原因，是只有Raspberry下面才出现这个问题，我在其他arm下面并没有出现 这个问题，在Intel下面也没有这个问题。

所以：
要么是Raspberry+Nginx出来的问题
要么是新版本的FRP出的问题。
十分肯定不是我的配置的问题， 因为这个配置同样的在其他环境上正常。

**Comment by zsinba** [comment]
> 个人觉得应该是你配置有问题；
> 不管 type = https 还是 type = tcp ，我设置过很多，都没有出现问题；
> 
> 你是通过ip访问还是域名访问？
> 你可以贴出frps的设置吗？
> 假如是ip访问：
> frps的ip：192.168.0.1
> frpc的ip：192.168.0.2
> http://192.168.0.1:19091 等同于 http://192.168.0.2

我是通过域名访问的，非ip；
难道你是说Nginx并没有监听这个域名，所以出现这个问题？
我也怀疑过这个原因，Nginx没配置这个域名，所以过来的域名不处理嘛。 但是排查后似乎并不是这个原因。我做了星号匹配的监听。

**Comment by ax2009live** [comment]
vhost_http_port = ??
vhost_https_port = ??

**Comment by zsinba** [comment]
> vhost_http_port = ??
> vhost_https_port = ??
> 如果不是frp问题，
> 你有排查 frpc 这个 web 服务器本身有没有问题吗？在没有经过frp的时候访问是否正常？

我并没有使用WEB映射呀。 我仅使用TCP映射，跟WEB这个HTTP没关系。也没有使用Vhost。 
我仅是做一个TCP穿透的映射而已。

**Comment by pub999** [comment]
nginx 配置加上`  listen 80 proxy_protocol；`试试，猜测是tcp转发了真实ip

**Comment by zsinba** [comment]
> nginx 配置加上` listen 80 proxy_protocol；`试试，猜测是tcp转发了真实ip

你是对的。 的确是这个原因。
加了你这句就正常了。
![image](https://user-images.githubusercontent.com/890157/123769287-b7625d80-d8fb-11eb-8066-ea1ac31eb1d1.png)


没有你这句，则是这样：
![image](https://user-images.githubusercontent.com/890157/123769311-c1845c00-d8fb-11eb-907d-89cce08060fd.png)


学习了。感谢指导

**Comment by zsinba** [comment]
![image](https://user-images.githubusercontent.com/890157/123769430-e37dde80-d8fb-11eb-9767-fd5be92645aa.png)

是这样做的测试。
