### ISSUE TITLE
Health Check Endpoint to see if FRPS is running

### ISSUE THREAD

**Issue by seveibar** [fatedier/frp#2455]
**The solution you want**
An HTTP health endpoint, e.g. `/health` to see if frps is running.

**Application scenarios of this function**
To know that frps has successfully started in automated applications, for example, I'd like to know if frps has started for a [docker-compose health check](https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck)

**Comment by fatedier** [comment]
Sure. I will add it next version.
