### ISSUE TITLE
frps: http: Accept error: accept tcp [::]: accept4: too many open files; retrying in 1s

### ISSUE THREAD

**Issue by peterwillcn** [fatedier/frp#2462]
```
frps[1906]: 2021/06/26 22:17:08 http: Accept error: accept tcp [::]: accept4: too many open files; retrying in 1s
```
I am not sure if Go tools exist to help with problems like this. There is problably some connection leak in the code.

A common leak that can happen is forgetting to call ```resp.Body.Close()``` after having consumed the payload of ```http.Response```.

Idle connections could be another possible cause. According to HTTP package doc:

> By default, Transport caches connections for future re-use. This may leave many open connections when accessing many hosts. This behavior can be managed using Transport's CloseIdleConnections method and the MaxIdleConnsPerHost and DisableKeepAlives fields.

If that's the case, you could try to call explicitely ```CloseIdleConnections``` on your ```Transport``` handle, or to reduce ```MaxIdleConnsPerHost``` value.

**Comment by fatedier** [comment]
You'd better optimize your system config about open files limit first.

If there still something wrong, you can paste network infos by `netstat` or `ss` on linux.
