### ISSUE TITLE
Block LAN Access

### ISSUE THREAD

**Issue by tzahico** [fatedier/frp#2464]
Hello,

Is there a way to block FRPC from accessing Local Network (Private / Internal IP addresses)?  

We can achieve that using Windows Firewall
`netsh advfirewall firewall add rule name="FRP" dir=out action=block program="frpc.exe" enable=yes localip=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16 remoteip=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16`

But is there a way to do it from the INI file?  Currently we use the following conf:
```
[common]
server_addr = x.x.x.x
server_port = port

[http_x.x.x.x_677567]
type = tcp
remote_port = port
plugin = http_proxy
plugin_http_user = user
plugin_http_passwd = password
group = http_proxy
group_key = key

```

Thanks!

**Comment by fatedier** [comment]
I don't think it's a good idea to trust that third-party applications won't connect to your specified IP range.

For security issue, system firewall or other underlying network tools are more reliable.
