### ISSUE TITLE
openwrt的frp启动成功 但是日志有错误

### ISSUE THREAD

**Issue by MambaOutZY** [fatedier/frp#2465]
frpc:   
[common]
server_addr=xxxx.xxx
server_port=5443
token=zxxxx
user=xxxx
log_level=info
log_max_days=3
protocol=tcp
log_file=/var/etc/frp/frpc.log
tcp_mux=false
login_fail_exit=false

[file _browser]
type=tcp
remote_port=8090
local_ip=192.168.0.254
local_port=8090
use_encryption=true
use_compression=true

[下载]
type=tcp
remote_port=8099
local_ip=192.168.0.254
local_port=8099
use_encryption=true
use_compression=true

frps:

# [common] is integral section
[common]
# A literal address or host name for IPv6 must be enclosed
# in square brackets, as in "[::1]:80", "[ipv6-host]:http" or "[ipv6-host%zone]:80"
bind_addr = 0.0.0.0
bind_port = 5443
# udp port used for kcp protocol, it can be same with 'bind_port'
# if not set, kcp is disabled in frps
kcp_bind_port = 5443
# if you want to configure or reload frps by dashboard, dashboard_port must be set
dashboard_port = 6443
# dashboard assets directory(only for debug mode)
dashboard_user = admin
dashboard_pwd = aaaaa
# assets_dir = ./static
vhost_http_port = 80
vhost_https_port = 443
# console or real logFile path like ./frps.log
log_file = ./frps.log
# debug, info, warn, error
log_level = info
log_max_days = 3
# auth token
token = aaaaa
# It is convenient to use subdomain configure for http、https type when many people use one frps server together.
subdomain_host = xxxx.xxxx
# only allow frpc to bind ports you list, if you set nothing, there won't be any limit
#allow_ports = 1-65535
# pool_count in each proxy will change to max_pool_count if they exceed the maximum value
max_pool_count = 150
# if tcp stream multiplexing is used, default is true
tcp_mux = true

我现在路由器的openwrt里面设置了两个端口转发，阿里云那边也设置了端口暴露，但是始终无法阿里云ip+port访问，日志里面报错信息：

2021/07/01 21:10:12 [W] [service.go:104] login to server failed: EOF
2021/07/01 21:11:07 [W] [service.go:104] login to server failed: EOF

![无标题](https://user-images.githubusercontent.com/41934953/124134213-3058e500-dab5-11eb-8f4c-316030e840a4.jpg)

**Comment by z0ow** [comment]
可以从本地网络访问服务器的5443端口吗？这个完全属于连不上服务
