### ISSUE TITLE
希望能够自动指定配置文件

### ISSUE THREAD

**Issue by cweijan** [fatedier/frp#2466]
希望当应用的启动参数为空时, 默认指定同目录的配置文件:
1. frps.exe没有启动参数时自动指定frps.ini
2. frp.exe没有启动参数时自动指定frpc.ini

约定大于配置, 让世界更方便点, 感谢老哥的frp.

**Comment by fatedier** [comment]
因为支持不使用配置文件启动，所以不会默认使用同目录的配置文件了。

**Comment by cweijan** [comment]
好吧。
