### ISSUE TITLE
build docker image without go command or provide official docker image

### ISSUE THREAD

**Issue by nnnewb** [fatedier/frp#2471]
**The solution you want**

`docker build . -f dockerfiles/Docker-for-frps` compile frps and build docker image.

**Alternatives considered**

... or provide official frps/frpc docker image? So I don't need build it by myself.

**How to implement this function**

run `make frps`/`make frpc` inside Dockerfile. 

**Application scenarios of this function**

easy to use.

**Comment by fakeboboliu** [comment]
https://hub.docker.com/r/fatedier/frpc/tags
https://hub.docker.com/r/fatedier/frps/tags

**Comment by nnnewb** [comment]
> https://hub.docker.com/r/fatedier/frpc/tags
> https://hub.docker.com/r/fatedier/frps/tags

感谢。

我有这一问主要是因为 README 和 wiki 都没有说明官方镜像是哪个，docker hub 的 fatedier 这个账号所有者也不能确定是这个仓库的所有者。

如果这两个链接确实是官方镜像的话，期望最好是能把链接加入 README ，让其他人也能少走点弯路。

**Comment by fakeboboliu** [comment]
https://github.com/fatedier/frp/blob/dev/.github/workflows/build-and-push-image.yml 

```
fatedier/frpc
fatedier/frps
ghcr.io/fatedier/frpc
ghcr.io/fatedier/frps
```

**Comment by nnnewb** [comment]
> https://github.com/fatedier/frp/blob/dev/.github/workflows/build-and-push-image.yml
> 
> ```
>           echo "TAG_FRPC=fatedier/frpc:${{ env.TAG_NAME }}" >> $GITHUB_ENV
>           echo "TAG_FRPS=fatedier/frps:${{ env.TAG_NAME }}" >> $GITHUB_ENV
>           echo "TAG_FRPC_GPR=ghcr.io/fatedier/frpc:${{ env.TAG_NAME }}" >> $GITHUB_ENV
>           echo "TAG_FRPS_GPR=ghcr.io/fatedier/frps:${{ env.TAG_NAME }}" >> $GITHUB_ENV
> ```

非常感谢你的答复。
