### ISSUE TITLE
privilege_token 连接

### ISSUE THREAD

**Issue by we6607** [fatedier/frp#2476]
版本：FRPS 0.37.0
操作系统：windows serve 2008r2

frps.ini 服务配置
[common]
bind_port = 7000
privilege_token = HJKjkj12021
------------------------------------------------------
frpc.ini 客户配置
[common]
server_addr = 47.107.*.**
server_port = 7000
privilege_token = HJKjkj1200088
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 6000
-------------------------------------------------------------------------------
问题反馈！！！！
frps.ini上配置的秘钥
privilege_token = HJKjkj12021

frpc.ini上配置的秘钥
 privilege_token = HJKjkj1200088
privilege_token = 
秘钥都不一致为什么都可以连接成功？
2021/07/09 11:34:01 [I] [proxy.go:162] [8541283ec4941307] [ssh] get a user conne
ction [47.107.*.*:49184]

是不是我的ps和pc端加密连接写法格式不对？？
那正确写法格式服务端和客户端加密连接写法有样本吗？？谢谢！！

**Comment by fakeboboliu** [comment]
`privilege_token` has been replaced by `token` since April 2018. [ref](https://github.com/fatedier/frp/commit/0f6f674a648e248fd1d842bc24cca2034db148bf#diff-0c326c4f02797b088fc566e64fbfe2162390f52f2fec1483ec3a413a7f11c910)

**Comment by bingtianbaihua** [comment]
可以看下你这个版本的最全配置， 应该是没有你说的  privilege_token 了。
https://github.com/fatedier/frp/blob/v0.37.0/conf/frps_full.ini
