### ISSUE TITLE
Failed to connect if network gateway runs OpenClash

### ISSUE THREAD

**Issue by sarkrui** [fatedier/frp#2481]
**[REQUIRED] hat version of frp are you using** 

Version: 0.37.0 (frpc & frps)

**[REQUIRED] What operating system and processor architecture are you using**
OS: macOS 11.5 Beta
CPU architecture: M1 arm

**[REQUIRED] description of errors**
_Firstly, this is probably not a frp program bug but more like a personal network configuration issue and I hereby intend to find a solution._ 
#### Network gateway is set to an OpenWRT
* OpenWRT is running OpenClash.
* OpenClash doesn't proxy the domain/ip of the frps server. (domain is added to fake-ip blacklist and Clash wasn't proxying the domain from the connection info.)
* tested on both M1 Mac and unRaid host. **Negative**.
* tested OpenClash running in fake-ip (so-called enhanced) mode and redir-host mode. **Negative**.

#### Gateway is not set to OpenWRT 
* using ClashX Pro instead (with system proxy and enhanced mode enabled). **Positive**

**confile**

```
[common]
server_addr = frp.mydomain.com
server_port = 6999
log_file = /usr/local/bin/frp/log/frpc-hk.log
log_level = debug
log_max_days = 3
token = mytoken
tcp_mux = true
```

**log file**
```
2021/07/14 01:22:22 [I] [service.go:177] [fff619003b82db39] try to reconnect to server...
2021/07/14 01:22:22 [W] [service.go:180] [fff619003b82db39] reconnect to server error: dial tcp xxx.xxx.xxx.xxx:6999: connect: connection refused
```

**Comment by fatedier** [comment]
You'd better find answers from topics releated to OpenClash?

frpc just make a simple TCP connection to frps.

**Comment by sarkrui** [comment]
Closed, as it turns out to be a local configuration-side issue.

**Comment by Bobi-zhou** [comment]
@sarkrui I have the same problem, how to fix it？
