### ISSUE TITLE
https2http 子页面无法打开

### ISSUE THREAD

**Issue by q123458384** [fatedier/frp#2482]
OS:linux
Version:0.37
本地typecho的博客是http的，想用frp的 https2http
frpc.ini
```
[blog_https2]
type = https
subdomain = blog
plugin = https2http
plugin_local_addr = 127.0.0.1:90
plugin_host_header_rewrite = 127.0.0.1
plugin_header_X-From-Where = frp
plugin_crt_path = ./cert/server.crt
plugin_key_path = ./cert/server.key
```
可以正常打开https://blog.xx.xx的网站
但是点击子页面转跳到 `http://127.0.0.1/archives/61/`的页面无法正常显示
不懂如何解决

**Comment by z0ow** [comment]
plugin_host_header_rewrite = 127.0.0.1 改成 plugin_host_header_rewrite = blog.xx.xx

**Comment by q123458384** [comment]
> plugin_host_header_rewrite = 127.0.0.1 改成 plugin_host_header_rewrite = blog.xx.xx

谢谢指导，可以正常打开子页面了，但是子页面还是http://blog.xx.xx/archives/61/
不知道是什么问题

**Comment by z0ow** [comment]
> > plugin_host_header_rewrite = 127.0.0.1 改成 plugin_host_header_rewrite = blog.xx.xx
> 
> 谢谢指导，可以正常打开子页面了，但是子页面还是http://blog.xx.xx/archives/61/
> 不知道是什么问题

没有测试过https2http，但是估计是rewrite的原因，可以考虑尝试  plugin_host_header_rewrite = https://blog.xx.xx

或者在frpc客户端的local_addr设备上的网页服务器重新做一个http强制转https的重定向，然后使用https2https

**Comment by q123458384** [comment]
> > > plugin_host_header_rewrite = 127.0.0.1 改成 plugin_host_header_rewrite = blog.xx.xx
> > 
> > 
> > 谢谢指导，可以正常打开子页面了，但是子页面还是http://blog.xx.xx/archives/61/
> > 不知道是什么问题
> 
> 没有测试过https2http，但是估计是rewrite的原因，可以考虑尝试 plugin_host_header_rewrite = https://blog.xx.xx
> 
> 或者在frpc客户端的local_addr设备上的网页服务器重新做一个http强制转https的重定向，然后使用https2https

👌🏻谢谢作者
