### ISSUE TITLE
is https://hub.docker.com/u/fatedier the official docker image publisher?

### ISSUE THREAD

**Issue by bthulu** [fatedier/frp#2484]
**The solution you want**

**Alternatives considered**

**How to implement this function**

**Application scenarios of this function**

**Comment by bingtianbaihua** [comment]
https://hub.docker.com/r/fatedier/frpc/tags?page=1&ordering=last_updated
https://hub.docker.com/r/fatedier/frps/tags?page=1&ordering=last_updated

https://github.com/fatedier/frp/blob/dev/.github/workflows/build-and-push-image.yml
