### ISSUE TITLE
Not starting TCP server for one tunel!

### ISSUE THREAD

**Issue by BBCLSD** [fatedier/frp#2485]
Version:0.37.0

**[REQUIRED] What operating system and processor architecture are you using**
OS:Windows 8.1

help to start a tkp server with a fixed port, kind people give detailed instructions, I can't figure it out myself! If possible, post instructions on YouTube and give a link. please respond!
![Screenshot_1](https://user-images.githubusercontent.com/47313269/125890231-fa97d404-2e6e-43ae-8ebe-9d227aa56a99.jpg)

**Comment by bingtianbaihua** [comment]
I can not get your point.

**Comment by bingtianbaihua** [comment]
You can read the official docs.
