### ISSUE TITLE
frp 的性能

### ISSUE THREAD

**Issue by caler** [fatedier/frp#249]
我如果在公网架设一个frp服务器，同时可以支持多少并发用户？对服务器有什么要求？
我很好奇是不是所有转发流量都会过服务器？

**Comment by caler** [comment]
不好意思 写成fpr了

**Comment by fatedier** [comment]
并发未经过测试，目前所有流量都会经过服务器。

**Comment by caler** [comment]
有没有流量不经过服务器的方案？

**Comment by wxyzh** [comment]
参考 [dog-tunnel](https://github.com/vzex/dog-tunnel)

**Comment by caler** [comment]
多谢！我试试看！就是dogtunnel的作者 readme 没fatedier写得好，看来还真是不想当作家的程序猿，不能成为优秀的程序猿。文档还是很重要的，但一般的程序员都讨厌写文档。
