### ISSUE TITLE
使用 frpc 映射 v2ray 的 socks 代理异常

### ISSUE THREAD

**Issue by liuweiGL** [fatedier/frp#2490]
**[REQUIRED] hat version of frp are you using** 

- Version: 0.37.0

**[REQUIRED] What operating system and processor architecture are you using**

- OS: window 7
- CPU architecture: 64

**[REQUIRED] description of errors**

使用 frpc 映射 v2ray 的 socks 代理时，socks 服务报错：unknown Socks version: 67。

**confile**

`frpc` 配置：
```ini
[xxx_v2ray]
type = tcp
local_ip = 10.1.x.x
local_port = 1080
remote_port = 1080
``` 
`v2ray` 配置：
```ini
{
      "inbounds": [
        {
            "port": 1080,
            "protocol": "socks",
            "settings":{
                "auth": "noauth",
                "userLevel":0
           }
        }
      ],
      "outbounds": [
        {
            "protocol": "freedom",
            "settings": {}
        }
      ]
}
```

**log file**

`frpc` 日志：

```txt
2021/07/21 21:57:17 [D] [proxy_wrapper.go:231] [f91111c97c2f4c0a] [xxx_v2ray] start a new work connection, localAddr: xxx:53699 remoteAddr: xx:xx
2021/07/21 21:57:17 [T] [proxy.go:739] [f91111c97c2f4c0a] [xxx_v2ray] handle tcp work connection, use_encryption: false, use_compression: false
2021/07/21 21:57:17 [D] [proxy.go:801] [f91111c97c2f4c0a] [xxx_v2ray] join connections, localConn(l[xxx:53702] r[xxx:1080]) workConn(l[xxx:53699] r[xxx:xxx])
2021/07/21 21:57:17 [D] [proxy.go:809] [f91111c97c2f4c0a] [xxx_v2ray] join connections closed
```

`v2ray` 日志：

```txt
2021/07/21 21:54:10 tcp:xxx:53665 rejected  proxy/socks: unknown Socks version: 67
2021/07/21 21:57:15 tcp:xxx:53702 rejected  proxy/socks: unknown Socks version: 67
```

**Supplementary information**

https://www.v2ray.com/chapter_00/faq.html#socks-unknown-socks-version-67

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by liuweiGL** [comment]
我是使用 xshell 时配置了 frp 为代理，所以应该是使用 ssh 协议访问的 frp 服务。

- A: xhsell 客户端
- B: frpc 客户端
- C: v2ray 服务端

请求链为：A -> B -> C

**Comment by bingtianbaihua** [comment]
frpc 的 `local_ip`  是v2ray 的IP吗？

**Comment by liuweiGL** [comment]
是的，不然 v2ray 是不会被访问到的呀~

**Comment by bingtianbaihua** [comment]
![image](https://user-images.githubusercontent.com/4812302/126732847-ef399508-adcc-40af-afe6-7f763e47722a.png)

试下？

**Comment by liuweiGL** [comment]
奥，转过来了。frp 是不区分 http 还是 socks 的，A 节点协议用错了。
