### ISSUE TITLE
no log file created

### ISSUE THREAD

**Issue by towerbit** [fatedier/frp#2491]
**[REQUIRED] hat version of frp are you using** 

Version:0.36.1

**[REQUIRED] What operating system and processor architecture are you using**
OS:CentOS 7
CPU architecture:

**[REQUIRED] description of errors**

**confile**

**log file**

log_file = ./frps.log
log_level = info
log_max_days = 7
**Steps to reproduce the issue**
1. frps start, no frps.log file created 
2. ./frps -c frps.ini , shows log in console, but not frps.log file created

**Supplementary information**

**Can you guess what caused this issue**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by bingtianbaihua** [comment]
you should check your file or folders permissions.

**Comment by wxy545812093** [comment]
`nohup ./frps -c frps.ini > frps.log 2>&1 &`   :) -- :)
