### ISSUE TITLE
Configurable websocket PATH

### ISSUE THREAD

**Issue by osnosn** [fatedier/frp#2492]
Create a new config record for websocket PATH when working in WS mode.

New config record for server (frps),
> websocket_path = /myfrp
   or
  websocket_path = /myfrp/aa23
 ( require start with '/', no space, up to 16 characters )

New config record for client (frpc), when protocol = websocket
> websocket_path = /myfrp
( require start with '/', no space, up to 16 characters )

If this empty or not config, then use default path "/~!frp".

**Comment by parsanoori** [comment]
Any progress on this?
