### ISSUE TITLE
docker fatedier/frp image too old

### ISSUE THREAD

**Issue by nickfan** [fatedier/frp#2493]
frp的完整版最新推送是5年前，

https://hub.docker.com/r/fatedier/frp/tags?page=1&ordering=last_updated

而frps的最新推送是2个月前

https://hub.docker.com/r/fatedier/frps/tags?page=1&ordering=last_updated

建议要么就同步都推，要么把fatedier/frp的这个镜像给删了，防止误导别人

**Comment by nickfan** [comment]
而且 fatedier/frps 和 fatedier/frpc 这两个都没有latest的tag，pull起来很不方便

**Comment by fatedier** [comment]
1. fatedier/frp 的镜像是之前使用的，镜像推送了就不会删除，因为有可能还有其他人在使用。
2. fatedier/frps 和 fatedier/frpc 是目前每个版本会自动上传，目前没有打 latest 的 tag，因为不能保证完全兼容，建议也不要使用latest 的 tag，还是清楚自己 pull 的是哪一个版本，避免出现问题。

**Comment by nickfan** [comment]
> 1. fatedier/frp 的镜像是之前使用的，镜像推送了就不会删除，因为有可能还有其他人在使用。
> 2. fatedier/frps 和 fatedier/frpc 是目前每个版本会自动上传，目前没有打 latest 的 tag，因为不能保证完全兼容，并不是可以不用关注版本的基础镜像，建议也不要使用 latest 的 tag，还是清楚自己 pull 的是哪一个版本，避免出现问题。

那至少fatedier/frp 也推一下 v0.37.0的tag的版本更新一下吧？

**Comment by fatedier** [comment]
fatedier/frp 的镜像已经不再维护，从日期上也能看出来，之后文档里会说明一下 docker 镜像相关的使用方式。
