### ISSUE TITLE
http穿透以后报错[400: Bad Request]

### ISSUE THREAD

**Issue by fengcharles** [fatedier/frp#2494]
Version:
frps-0.37.0 frpc-0.37.0

**[REQUIRED] What operating system and processor architecture are you using**
OS: ubuntu18.04
CPU architecture:

**[REQUIRED] description of errors**
服务器，客户端都配置好，穿透了很多内网的http的网站，且半年内都一直在正常运行。

今天想新增一个http穿透 访问局域网的 Home assistant。 
Home assistant 本地可以正常访问，穿透以后一直报错，访问以后页面显示报错 400: Bad Request 后台没有错误日志显示（或者我没有打开相关的错误日志级别），我目前调的是DEBUG。

链路都是正常的，同样的域名切换到其他网站，都是可以穿透的。

无法准确定位问题原因。

**Comment by fengcharles** [comment]
会不会是websocket的原因？

**Comment by bingtianbaihua** [comment]
提供配置，还有一些日志。

**Comment by bingtianbaihua** [comment]
> 会不会是websocket的原因？

你怀疑这个，可以自己去验证一下。

**Comment by fengcharles** [comment]
不是frpc的问题，应该是服务的问题

**Comment by Trace-star** [comment]
> 不是frpc的问题，应该是服务的问题

我遇到了跟你一样的问题，请问你是怎么解决的

**Comment by leruge** [comment]
如何解决的，我也有同样的问题？

**Comment by fengcharles** [comment]
> 如何解决的，我也有同样的问题？

这个跟 Frp 没关系，网站自身的原因

**Comment by tfpdc** [comment]
我也遇到这个问题,发现可以用tcp来解决
在configuration.yaml里面添加一段内容
![image](https://github.com/fatedier/frp/assets/44161306/4f747896-0747-4291-a9a2-2aee14a19273)

frc.ini里面写
![image](https://github.com/fatedier/frp/assets/44161306/783eac58-95b4-4ae4-9272-cd78104d0dbc)
这样就可以ip+端口或者域名+端口来访问

**Comment by ChanLicher** [comment]
HA 想使用内网穿透还得再 configuration.yaml 文件里加上这一段：
```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - xx.xx.xx.xx
    - 192.168.xx.0/24
    - 127.0.0.1
```
x 的部分根据填写自己服务器 ip 和本地 ip
