### ISSUE TITLE
上游代理怎么解决

### ISSUE THREAD

**Issue by huanhaishijie** [fatedier/frp#2496]
INFO      Jul 26 14:57:04.166 [12728]: No upstream proxy for bilibili.com
INFO      Jul 26 14:57:04.166 [12728]: opensock: opening connection to bilibili.com:443
INFO      Jul 26 14:57:04.175 [12728]: opensock: getaddrinfo returned for bilibili.com:443
ERROR     Jul 26 14:57:04.175 [12728]: opensock: Could not establish a connection to bilibili.com:443
CONNECT   Jul 26 15:09:07.429 [12728]: Connect (file descriptor 5): 127.0.0.1 at [127.0.0.1]
CONNECT   Jul 26 15:09:07.429 [12728]: Request (file descriptor 5): CONNECT bilibili.com:443 HTTP/1.1
INFO      Jul 26 15:09:07.429 [12728]: No upstream proxy for bilibili.com
INFO      Jul 26 15:09:07.429 [12728]: opensock: opening connection to bilibili.com:443
INFO      Jul 26 15:09:07.439 [12728]: opensock: getaddrinfo returned for bilibili.com:443
ERROR     Jul 26 15:09:07.439 [12728]: opensock: Could not establish a connection to bilibili.com:443

**Comment by bingtianbaihua** [comment]
没明白你的问题， 按照 issue 的规范描述清楚吧。
