### ISSUE TITLE
docker运行frp，运行stcp模式，无法对外暴露端口提供服务

### ISSUE THREAD

**Issue by myhoger** [fatedier/frp#2497]
1. 运行环境
windows
docker-desktop 
ubuntu 
2. 报错
没有报错
3. 版本
frp_0.37.0_linux_amd64

在容器内部可以访问，通过容器暴露端口，宿主机上则无法访问

**Comment by bingtianbaihua** [comment]
可以提供下错误日志， 而且没有特别明白，你的部署方式，比如什么组件放在了 docker，什么组件放在了宿主机。

**Comment by axboy** [comment]
server网络建议使用host模式，更不需要考虑网络端口映射情况，
我使用这个挺稳定，因自己使用，frp版本相比最新版更新较慢，想起来就更新一下。

https://github.com/axboy/dockerfiles/tree/master/frp

**Comment by oxkenshin** [comment]
wsl2的问题，wsl2的host模式把端口暴露到docker daemon的host下，而不是wsl的命令行环境的host。要么把服务也放到docker里面，要么把frp从docker里面拿出来。
