### ISSUE TITLE
服务端 Dashboard无法访问

### ISSUE THREAD

**Issue by csco11298754** [fatedier/frp#2498]
根据[官方文档](https://gofrp.org/docs/features/common/ui/)的配置进行操作，客户端管理界面配置完不管本地还是外网环境访问 Admin UI都正常，唯独服务端无法正常访问。

**Comment by bingtianbaihua** [comment]
提供下服务端的配置。

**Comment by csco11298754** [comment]
[common] 

bind_addr = 59.100.205.125

bind_port = 7000 

bind_udp_port = 7001 

kcp_bind_port = 7000 

dashboard_port = 7500

dashboard_user = root

dashboard_pwd = Go0Q%MraF$R@PiKt

log_max_days = 7 

privilege_token = #NopVA9scX

privilege_allow_ports = 7006-7020

max_pool_count = 20

authentication_timeout = 0

log_file = /frp/frps.log 

log_level = info

**Comment by bingtianbaihua** [comment]
你这个配置看起来很老了， 更新下配置吧。 
https://github.com/fatedier/frp/blob/dev/conf/frps_full.ini

**Comment by csco11298754** [comment]
> 你这个配置看起来很老了， 更新下配置吧。
> https://github.com/fatedier/frp/blob/dev/conf/frps_full.ini

尝试过了还是不行。

**Comment by guozix** [comment]
同问，用了官方文档，更新最新的软件配置，还是看不了服务端dashboard， @csco11298754 请问你解决了吗

**Comment by guozix** [comment]
> 同问，用了官方文档，更新最新的软件配置，还是看不了服务端dashboard， @csco11298754 请问你解决了吗

./frps -c frps.ini   solves
