### ISSUE TITLE
frpc v0.37.0 在centos8.4添加systemd自启动服务无法执行excrestart里的命令

### ISSUE THREAD

**Issue by TaiChi01** [fatedier/frp#2499]
**[REQUIRED] hat version of frp are you using** 

Version: 0.37.0

**[REQUIRED] What operating system and processor architecture are you using**
OS: centos8.4
CPU architecture: x86_64

**[REQUIRED] description of errors**

**confile**

[Unit]
Description=Frp Client Service
After=network.target
[Service]
Type=simple
User=root
Restart=on-failure
RestartSec=5s
ExecStart=/root/frp/frpc -c /root/frp/frpc.ini
ExecReload=/root/frp/frpc reload -c /root/frp/frpc.ini
[Install]
WantedBy=multi-user.target
**log file**

**Steps to reproduce the issue**
1. 如上配置        systemctl start frpc
2. 查看运行状态 systemctl status frpc
3. 报错信息        code=exited, status=203/EXEC

**Supplementary information**
所有服务手动启动均正常运行，frps在服务器也出现一样的不能执行excrestart里的命令的问题，
但通过将User改为root解决。
在frpc上如此无法解决该问题
**Can you guess what caused this issue**
可能是某种权限问题，
类似的问题在网络搜索到http://yangl.net/2021/04/27/frps-systemctl-error/
**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by chengpeng2015** [comment]
+1
