### ISSUE TITLE
mac版本下载后不能成功执行

### ISSUE THREAD

**Issue by AngryBaby** [fatedier/frp#250]
环境MacOS X
终端执行 ./frpc -c ./frpc.ini
提示报错 -bash: ./frpc: cannot execute binary file

下载地址是官网百度云盘里的Linux文件夹

**Comment by fatedier** [comment]
请在 release 页面下载对应的版本。

**Comment by dengxiaozhen** [comment]
mac要下载那个darwin的，linux的binary不能在mac上跑

**Comment by wyyl1** [comment]
mac为什么是darwin的，而没有写mac？
找了半天才找到了这里，居然是darwin版本在Mac上运行！
感谢 dengxiaozhen
