### ISSUE TITLE
stcp error

### ISSUE THREAD

**Issue by ivan0413** [fatedier/frp#2503]
on  android emulator ........ why?
2021/07/29 13:42:49 [W] [control.go:288] [326d8720ea402dce] read error: message type error
2021/07/29 13:42:49 [I] [control.go:308] [326d8720ea402dce] control writer is closing
2021/07/29 13:42:49 [I] [control.go:407] [326d8720ea402dce] try to reconnect to server...
2021/07/29 13:42:50 [I] [control.go:246] [326d8720ea402dce] login to server success, get run id

**Comment by ivan0413** [comment]
2021/08/01 12:57:14 [W] [visitor_manager.go:83] [d09ac41266809f8b] start error: listen tcp 127.0.0.1:9997: bind: address already in use
2021/08/01 12:57:14 [I] [visitor_manager.go:130] [d09ac41266809f8b] visitor added: [service_visitor0]
2021/08/01 12:57:14 [W] [control.go:261] [d09ac41266809f8b] read error: message type error
2021/08/01 12:57:14 [I] [control.go:282] [d09ac41266809f8b] control writer is closing
2021/08/01 12:57:14 [I] [visitor_manager.go:60] [d09ac41266809f8b] gracefully shutdown visitor manager
2021/08/01 12:57:14 [I] [service.go:177] [d09ac41266809f8b] try to reconnect to server...
2021/08/01 12:57:14 [I] [service.go:304] [d09ac41266809f8b] login to server success, get run id [d09ac41266809f8b], server udp port [9899]
2021/08/01 12:57:14 [W] [visitor_manager.go:83] [d09ac41266809f8b] start error: listen tcp 127.0.0.1:9997: bind: address already in use
2021/08/01 12:57:14 [I] [visitor_manager.go:130] [d09ac41266809f8b] visitor added: [service_visitor0]
2021/08/01 12:57:14 [W] [control.go:261] [d09ac41266809f8b] read error: message type error
2021/08/01 12:57:14 [I] [control.go:282] [d09ac41266809f8b] control writer is closing
2021/08/01 12:57:14 [I] [visitor_manager.go:60] [d09ac41266809f8b] gracefully shutdown visitor manager
2021/08/01 12:57:15 [I] [service.go:177] [d09ac41266809f8b] try to reconnect to server...
2021/08/01 12:57:15 [I] [service.go:304] [d09ac41266809f8b] login to server success, get run id [d09ac41266809f8b], server udp port [9899]
2021/08/01 12:57:15 [W] [visitor_manager.go:83] [d09ac41266809f8b] start error: listen tcp 127.0.0.1:9997: bind: address already in use
2021/08/01 12:57:15 [I] [visitor_manager.go:130] [d09ac41266809f8b] visitor added: [service_visitor0]
2021/08/01 12:57:15 [W] [control.go:261] [d09ac41266809f8b] read error: message type error
2021/08/01 12:57:15 [I] [control.go:282] [d09ac41266809f8b] control writer is closing
2021/08/01 12:57:15 [I] [visitor_manager.go:60] [d09ac41266809f8b] gracefully shutdown visitor manager
2021/08/01 12:57:17 [I] [service.go:177] [d09ac41266809f8b] try to reconnect to server...
2021/08/01 12:57:17 [I] [service.go:304] [d09ac41266809f8b] login to server success, get run id [d09ac41266809f8b], server udp port [9899]
2021/08/01 12:57:17 [W] [visitor_manager.go:83] [d09ac41266809f8b] start error: listen tcp 127.0.0.1:9997: bind: address already in use
2021/08/01 12:57:17 [I] [visitor_manager.go:130] [d09ac41266809f8b] visitor added: [service_visitor0]
2021/08/01 12:57:17 [W] [control.go:261] [d09ac41266809f8b] read error: message type error
2021/08/01 12:57:17 [I] [control.go:282] [d09ac41266809f8b] control writer is closing
2021/08/01 12:57:17 [I] [visitor_manager.go:60] [d09ac41266809f8b] gracefully shutdown visitor manager

**Comment by ivan0413** [comment]
2021/08/01 13:14:57 [I] [visitor_manager.go:86] [f1678b89f2f8e215] start visitor success
2021/08/01 13:14:57 [I] [visitor_manager.go:130] [f1678b89f2f8e215] visitor added: [service_visitor0]
2021/08/01 13:14:57 [W] [control.go:261] [f1678b89f2f8e215] read error: message type error
2021/08/01 13:14:57 [I] [control.go:282] [f1678b89f2f8e215] control writer is closing
2021/08/01 13:14:57 [W] [visitor.go:107] [f1678b89f2f8e215] [service_visitor0] stcp local listener closed
2021/08/01 13:14:57 [I] [visitor_manager.go:60] [f1678b89f2f8e215] gracefully shutdown visitor manager
2021/08/01 13:15:01 [I] [service.go:177] [f1678b89f2f8e215] try to reconnect to server...
2021/08/01 13:15:01 [I] [service.go:304] [f1678b89f2f8e215] login to server success, get run id [f1678b89f2f8e215], server udp port [9899]
2021/08/01 13:15:01 [I] [visitor_manager.go:86] [f1678b89f2f8e215] start visitor success
2021/08/01 13:15:01 [I] [visitor_manager.go:130] [f1678b89f2f8e215] visitor added: [service_visitor0]
2021/08/01 13:15:01 [W] [control.go:261] [f1678b89f2f8e215] read error: message type error
2021/08/01 13:15:01 [I] [control.go:282] [f1678b89f2f8e215] control writer is closing
2021/08/01 13:15:01 [W] [visitor.go:107] [f1678b89f2f8e215] [service_visitor0] stcp local listener closed

**Comment by ivan0413** [comment]
2021/08/01 13:19:21 [I] [visitor_manager.go:60] [eaa7c62515af7e95] gracefully shutdown visitor manager
2021/08/01 13:19:23 [I] [service.go:177] [eaa7c62515af7e95] try to reconnect to server...
2021/08/01 13:19:23 [I] [service.go:304] [eaa7c62515af7e95] login to server success, get run id [eaa7c62515af7e95], server udp port [9899]
2021/08/01 13:19:23 [I] [visitor_manager.go:86] [eaa7c62515af7e95] start visitor success
2021/08/01 13:19:23 [I] [visitor_manager.go:130] [eaa7c62515af7e95] visitor added: [service_visitor0]
2021/08/01 13:19:23 [W] [control.go:261] [eaa7c62515af7e95] ### **read error: message length error**
2021/08/01 13:19:23 [I] [control.go:282] [eaa7c62515af7e95] control writer is closing
2021/08/01 13:19:23 [W] [visitor.go:107] [eaa7c62515af7e95] [service_visitor0] stcp local listener closed
2021/08/01 13:19:23 [I] [visitor_manager.go:60] [eaa7c62515af7e95] gracefully shutdown visitor manager
2021/08/01 13:19:27 [I] [service.go:177] [eaa7c62515af7e95] try to reconnect to server...
2021/08/01 13:19:27 [I] [service.go:304] [eaa7c62515af7e95] login to server success, get run id [eaa7c62515af7e95], server udp port [9899]
2021/08/01 13:19:27 [I] [visitor_manager.go:86] [eaa7c62515af7e95] start visitor success
2021/08/01 13:19:27 [I] [visitor_manager.go:130] [eaa7c62515af7e95] visitor added: [service_visitor0]
2021/08/01 13:19:27 [W] [control.go:261] [eaa7c62515af7e95] _### **read error: message type error**_
2021/08/01 13:19:27 [I] [control.go:282] [eaa7c62515af7e95] control writer is closing
2021/08/01 13:19:27 [W] [visitor.go:107] [eaa7c62515af7e95] [service_visitor0] stcp local listener closed
2021/08/01 13:19:27 [I] [visitor_manager.go:60] [eaa7c62515af7e95] gracefully shutdown visitor manager
2021/08/01 13:19:35 [I] [service.go:177] [eaa7c62515af7e95] try to reconnect to server...
2021/08/01 13:19:35 [I] [service.go:304] [eaa7c62515af7e95] login to server success, get run id [eaa7c62515af7e95], server udp port [9899]
2021/08/01 13:19:35 [I] [visitor_manager.go:86] [eaa7c62515af7e95] start visitor success
2021/08/01 13:19:35 [I] [visitor_manager.go:130] [eaa7c62515af7e95] visitor added: [service_visitor0]

**Comment by ivan0413** [comment]
a other error ...
read error: message length exceed the limit

**Comment by bingtianbaihua** [comment]
show your service config.

**Comment by ivan0413** [comment]
hi,the server config is
--------------------------------------
[common]
bind_addr = 0.0.0.0
bind_port = 9600
bind_udp_port = 9800
dashboard_addr = 0.0.0.0
dashboard_port = 9020
dashboard_user = ***
dashboard_pwd = ****
log_file = ./frps.log
log_level = info
log_max_days = 3
disable_log_color = false
detailed_errors_to_client = true
authentication_method = token
authenticate_heartbeats = true
authenticate_new_work_conns = true
# auth token
token = ******
heartbeat_timeout = 90
allow_ports = 2000-3000,3001,3003,4000-50000
max_pool_count = 5
max_ports_per_client = 0
tls_only = false
tcp_mux = true
udp_packet_size = 15000
-------------------------


---------------------------
the service config is
---------------------------



---------------------------
[common]
server_addr=******
server_port=9600
log_file=/storage/emulated/0/Android/data/****/files/fc.log
log_level=info
log_max_days=3
disable_log_color=false
authenticate_heartbeats=true
authenticate_new_work_conns=true
token=*****
authentication_method=token
pool_count=10
tcp_mux=true
protocol=tcp
heartbeat_interval=10
heartbeat_timeout=90
udp_packet_size=1500
[ser0]
type=stcp
sk=****
server_name=ser0
local_ip =127.0.0.1
local_port =9999
use_encryption=true
use_compression=true

---------------------------
the client config is
-----------------------------
[common]
server_addr=******
server_port=9600
log_file=/storage/emulated/0/Android/data/****/files/fc.log
log_level=info
log_max_days=3
disable_log_color=false
authenticate_heartbeats=true
authenticate_new_work_conns=true
token=*****
authentication_method=token
pool_count=10
tcp_mux=true
protocol=tcp
heartbeat_interval=10
heartbeat_timeout=90
udp_packet_size=1500
[ser_visi0]
role=visitor
type=stcp
sk=****
server_name=ser0
bind_addr=127.0.0.1
bind_port=9999
use_encryption=true
use_compression=true

**Comment by ivan0413** [comment]
**hi,the server config is**

[common]
bind_addr = 0.0.0.0
bind_port = 9600
bind_udp_port = 9800
dashboard_addr = 0.0.0.0
dashboard_port = 9020
dashboard_user = ***
dashboard_pwd = ****
log_file = ./frps.log
log_level = info
log_max_days = 3
disable_log_color = false
detailed_errors_to_client = true
authentication_method = token
authenticate_heartbeats = true
authenticate_new_work_conns = true
# auth token
token = ******
heartbeat_timeout = 90
allow_ports = 2000-3000,3001,3003,4000-50000
max_pool_count = 5
max_ports_per_client = 0
tls_only = false
tcp_mux = true
udp_packet_size = 15000


**the service config is**



[common]
server_addr=******
server_port=9600
log_file=/storage/emulated/0/Android/data/****/files/fc.log
log_level=info
log_max_days=3
disable_log_color=false
authenticate_heartbeats=true
authenticate_new_work_conns=true
token=*****
authentication_method=token
pool_count=10
tcp_mux=true
protocol=tcp
heartbeat_interval=10
heartbeat_timeout=90
udp_packet_size=1500
[ser0]
type=stcp
sk=****
server_name=ser0
local_ip =127.0.0.1
local_port =9999
use_encryption=true
use_compression=true

**the client config is**

[common]
server_addr=******
server_port=9600
log_file=/storage/emulated/0/Android/data/****/files/fc.log
log_level=info
log_max_days=3
disable_log_color=false
authenticate_heartbeats=true
authenticate_new_work_conns=true
token=*****
authentication_method=token
pool_count=10
tcp_mux=true
protocol=tcp
heartbeat_interval=10
heartbeat_timeout=90
udp_packet_size=1500
[ser_visi0]
role=visitor
type=stcp
sk=****
server_name=ser0
bind_addr=127.0.0.1
bind_port=9999
use_encryption=true
use_compression=true

**Comment by ivan0413** [comment]
@bingtianbaihua 
**hi,the server config is**

[common]
bind_addr = 0.0.0.0
bind_port = 9600
bind_udp_port = 9800
dashboard_addr = 0.0.0.0
dashboard_port = 9020
dashboard_user = 111111
dashboard_pwd = 111111
log_file = ./frps.log
log_level = info
log_max_days = 3
disable_log_color = false
detailed_errors_to_client = true
authentication_method = token
authenticate_heartbeats = true
authenticate_new_work_conns = true
token =111111
heartbeat_timeout = 90
allow_ports = 2000-3000,3001,3003,4000-50000
max_pool_count = 5
max_ports_per_client = 0
tls_only = false
tcp_mux = true
udp_packet_size = 15000


**the service config is**



[common]
server_addr=......
server_port=9600
log_file=/storage/emulated/0/Android/data/****/files/fc.log
log_level=info
log_max_days=3
disable_log_color=false
authenticate_heartbeats=true
authenticate_new_work_conns=true
token=111111
authentication_method=token
pool_count=10
tcp_mux=true
protocol=tcp
heartbeat_interval=10
heartbeat_timeout=90
udp_packet_size=1500
[ser0]
type=stcp
sk=111111
local_ip =127.0.0.1
local_port =9999
use_encryption=true
use_compression=true

**the client config is**

[common]
server_addr=...
server_port=9600
log_file=/storage/emulated/0/Android/data/****/files/fc.log
log_level=info
log_max_days=3
disable_log_color=false
authenticate_heartbeats=true
authenticate_new_work_conns=true
token=111111
authentication_method=token
pool_count=10
tcp_mux=true
protocol=tcp
heartbeat_interval=10
heartbeat_timeout=90
udp_packet_size=1500
[ser_visi0]
role=visitor
type=stcp
sk=111111
server_name=ser0
bind_addr=127.0.0.1
bind_port=9999
use_encryption=true
use_compression=true

**Comment by bingtianbaihua** [comment]
what is your frp version ?

**Comment by ivan0413** [comment]
> what is your frp version ?

0.37.0

@bingtianbaihua

**Comment by ivan0413** [comment]
@bingtianbaihua 
Wrong binary file
it's ok

how to change arr file?
