### ISSUE TITLE
tcp协议配置无法生效的问题

### ISSUE THREAD

**Issue by zolopp** [fatedier/frp#2506]
**使用环境：**服务端debian10 ,服务版本0.370，客户端，openwrt
**目前配置：**已绑定域名 ，客户端设备成功关联 ，http协议配置成功，可以穿透并远程访问,本地和远程端口都是22,防火墙开放

**配置文件：**
`[common]
bind_addr = 0.0.0.0
bind_port = 5443
kcp_bind_port = 5443
dashboard_port = 6443
dashboard_user = 12345
dashboard_pwd = 12345
vhost_http_port = 80
vhost_https_port = 443
log_file = ./frps.log
log_level = info
log_max_days = 3
token = 000000000
subdomain_host = good.com
max_pool_count = 50
tcp_mux = true

服务端log:
2021/08/03 15:33:07 [W] [http.go:92] do http proxy request error: no such domain: 111.11.11.111/
2021/08/03 15:35:33 [I] [control.go:307] [85f39098600b910d] control writer is closing
2021/08/03 15:35:33 [I] [proxy.go:87] [85f39098600b910d] [N1.op] proxy closing
2021/08/03 15:35:33 [I] [control.go:382] [85f39098600b910d] client exit success
2021/08/03 15:35:34 [I] [service.go:449] [f3770b5a25610dc5] client login info: ip [111.111.11.11:34532] version [0.37.0] hostname [] os [linux] arch [arm64]
2021/08/03 15:35:34 [W] [control.go:440] [f3770b5a25610dc5] new proxy [aa] error: port unavailable
2021/08/03 15:35:34 [I] [http.go:124] [f3770b5a25610dc5] [aa] http proxy listen for host [ok.domian.com location [] group []

客户端log:
 `[W] [control.go:178] [8fc32b1bd2b01155] [ssh] start error: port unavailable`
 
目前问题：tcp配置，服务端tcp页面没有显示，putty 连接不到目标设备，通过域名连接以后，只能到达frp服务器，并没有穿透。
目前的思路：
域名配置问题？服务端配置文件绑定的是一级域名，在openwrt配置界面下，选择tcp连接就没有域名配置选项，
所以并没有跟目标设备连通？有遇到类似问题的吗？谢谢
![1](https://user-images.githubusercontent.com/58029653/127948207-34d9b7ac-9ef3-4d50-a20d-a7afcc5c9b1a.JPG)

**Comment by bingtianbaihua** [comment]
看下frps 有没有错误日志。

**Comment by zolopp** [comment]
> 看下frps 有没有错误日志。

感谢回复，有错误日志
 [W] [control.go:178] [95d0841] [ssh] start error: port unavailable

**Comment by zolopp** [comment]
客户机的防火墙规则 端口转发规则已经都添加了22端口，用其他方式是可以连接的，不知道这里为什么会报端口错误

**Comment by zolopp** [comment]
我再整理下信息

**Comment by bingtianbaihua** [comment]
换个端口试试， 应该是端口不可用导致的。
