### ISSUE TITLE
服务器端热加载bug

### ISSUE THREAD

**Issue by tldzyx** [fatedier/frp#251]
当ftps配置bind_addr为0.0.0.0时，调用热加载会失败。

**Comment by bingtianbaihua** [comment]
@tldzyx   麻烦你能把问题描述清楚一下。

我在本地测试是没有问题的：

frps和frpc版本都是 0.9.2
frps在mac下测试，reload不会失败。


---------------------------------------
不知道你指的失败，是reload的时候失败是什么失败了？贴一下日志错误信息。

**Comment by fatedier** [comment]
之前的错误可能是系统原因，某些系统不支持，v0.10.0 版本已经取消了 reload 功能，配置全都放在客户端。
