### ISSUE TITLE
ERROR: "kex_exchange_identification: Connection closed by remote host"

### ISSUE THREAD

**Issue by LucasZhan** [fatedier/frp#2512]
**[REQUIRED] hat version of frp are you using** 

Version:0.37.1

**[REQUIRED] What operating system and processor architecture are you using**
OS:Ubuntu 20.04.2 LTS
CPU architecture: x86

**[REQUIRED] description of errors**
"frps' and 'frpc' run successfully on server and client. When I use another device ssh to client, it shows the message **kex_exchange_identification: Connection closed by remote host**. I can ssh to the server directly, so the connection is fine.

**confile**

**server side**
[common]
bind_port = 7000

**client side**
[common]
server_addr = x.x.x.x
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

**log file**

Provided comment below: (coz there is no log file on this machine.)

**Steps to reproduce the issue**
1. Follow the offical instruction of **frp** installation and run **frps**, **frpc** on server and client successfully.
2. On another machine (neither server nor client), ssh to the client via **frp** (using command **ssh -oPort=7000 root@X.X.X.X**).
3.

**Supplementary information**
The server is ECS from Aliyun.

**Can you guess what caused this issue**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by LucasZhan** [comment]
(base)  zhanxu@zhanxudeMacBook-Pro  ~  ssh -p 7000 root@X.X.X.X
kex_exchange_identification: Connection closed by remote host
(base)  ✘ zhanxu@zhanxudeMacBook-Pro  ~  ssh root@X.X.X.X
root@X.X.X.X's password:
Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-77-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

Welcome to Alibaba Cloud Elastic Compute Service !

Last login: Wed Aug  4 19:25:30 2021 from 27.33.90.182

**Comment by LucasZhan** [comment]
**server log**
2021/08/04 20:05:09 ^[[1;34m[I] [root.go:200] frps uses config file: ./frps.ini^[[0m
2021/08/04 20:05:09 ^[[1;34m[I] [service.go:192] frps tcp listen on 0.0.0.0:7000^[[0m
2021/08/04 20:05:09 ^[[1;34m[I] [root.go:209] frps started successfully^[[0m
2021/08/04 20:05:43 ^[[1;34m[I] [service.go:449] [62cbaa8b835f1279] client login info: ip [27.33.90.182:54716] version [0.37.1] hostname [] os [linux] arch [amd64]^[[0m
2021/08/04 20:05:43 ^[[1;34m[I] [tcp.go:63] [62cbaa8b835f1279] [ssh] tcp proxy listen port [6000]^[[0m
2021/08/04 20:05:43 ^[[1;34m[I] [control.go:444] [62cbaa8b835f1279] new proxy [ssh] success^[[0m

**Comment by LucasZhan** [comment]
**client log**
2021/08/04 20:05:09 ^[[1;34m[I] [root.go:200] frps uses config file: ./frps.ini^[[0m
2021/08/04 20:05:09 ^[[1;34m[I] [service.go:192] frps tcp listen on 0.0.0.0:7000^[[0m
2021/08/04 20:05:09 ^[[1;34m[I] [root.go:209] frps started successfully^[[0m
2021/08/04 20:05:43 ^[[1;34m[I] [service.go:449] [62cbaa8b835f1279] client login info: ip [27.33.90.182:54716] version [0.37.1] hostname [] os [linux] arch [amd64]^[[0m
2021/08/04 20:05:43 ^[[1;34m[I] [tcp.go:63] [62cbaa8b835f1279] [ssh] tcp proxy listen port [6000]^[[0m
2021/08/04 20:05:43 ^[[1;34m[I] [control.go:444] [62cbaa8b835f1279] new proxy [ssh] success^[[0m

**Comment by StevendeLiu** [comment]
好奇这个问题如何解决的

**Comment by Chunchunyoyo** [comment]
@LucasZhan Hi, LucasZhan, I meet the same problem as you 'kex_exchange_identification: Connection closed by remote host'. Would you please help me with this problme?

**Comment by LucasZhan** [comment]
Sorry guys it's been a long time ago and I have never set frp once it's was ready to use. I forgot how to solve it...
