### ISSUE TITLE
Centos 7.9 KCP Minecraft1.16.5 bug

### ISSUE THREAD

**Issue by qiaoliangXgamemode** [fatedier/frp#2513]
8月 05 01:05:57 VM-8-2-centos frps[5006]: github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/kcp.go:842 +0xc23
8月 05 01:05:57 VM-8-2-centos frps[5006]: github.com/fatedier/kcp-go.(*UDPSession).update(0xa40a3c0, 0xc03ad01d, 0x43017c32)
8月 05 01:05:57 VM-8-2-centos frps[5006]: github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/sess.go:556 +0x52
8月 05 01:05:57 VM-8-2-centos frps[5006]: github.com/fatedier/kcp-go.(*updateHeap).updateTask(0x8bc8520)
8月 05 01:05:57 VM-8-2-centos frps[5006]: github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/updater.go:91 +0xef
8月 05 01:05:57 VM-8-2-centos frps[5006]: created by github.com/fatedier/kcp-go.init.2
8月 05 01:05:57 VM-8-2-centos frps[5006]: github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/updater.go:13 +0x5f

很遗憾胖次我去年就发过一个关于阿里云的KCP问题，这次也是，不过我用KCP反增加延迟，这很奇怪

**Comment by qiaoliangXgamemode** [comment]
我使用了一些github魔改bbr，不过我之前在pulsbbr上面是基本没有事情

**Comment by fatedier** [comment]
请按照模版附上详细的信息。

**Comment by qiaoliangXgamemode** [comment]
2021/08/07 00:44:06 [I] [tcp.go:63] [724ae6ff63779aec] [XWJ] tcp proxy listen port [5000]
2021/08/07 00:44:06 [I] [control.go:444] [724ae6ff63779aec] new proxy [XWJ] success
2021/08/07 00:44:06 [I] [service.go:449] [3fb182772a682635] client login info: ip [*******:9737] version [0.37.0] hostname [] os [windows] arch [amd64]
2021/08/07 00:44:06 [I] [tcp.go:63] [3fb182772a682635] [ssh] tcp proxy listen port [3555]
2021/08/07 00:44:06 [I] [control.go:444] [3fb182772a682635] new proxy [ssh] success
2021/08/07 00:44:10 [I] [proxy.go:179] [724ae6ff63779aec] [XWJ-MC] get a user connection [******:35378]
panic: unreachable

goroutine 20 [running]:
github.com/klauspost/reedsolomon.reedSolomon.codeSomeShardsAvx512(...)
        github.com/klauspost/reedsolomon@v1.9.1/galois_noasm.go:33
github.com/klauspost/reedsolomon.reedSolomon.codeSomeShards(0xa, 0x3, 0xd, 0x989aaa0, 0xd, 0xd, 0x99ccc90, 0x9bd2380, 0xa, 0xa, ...)
        github.com/klauspost/reedsolomon@v1.9.1/reedsolomon.go:441 +0x3b4
github.com/klauspost/reedsolomon.reedSolomon.reconstruct(0xa, 0x3, 0xd, 0x989aaa0, 0xd, 0xd, 0x99ccc90, 0x9bd2380, 0xa, 0xa, ...)
        github.com/klauspost/reedsolomon@v1.9.1/reedsolomon.go:763 +0x757
github.com/klauspost/reedsolomon.reedSolomon.ReconstructData(...)
        github.com/klauspost/reedsolomon@v1.9.1/reedsolomon.go:643
github.com/fatedier/kcp-go.(*fecDecoder).decode(0x987d270, 0x9bdcc00, 0x546, 0x5dc, 0x1, 0x9bf533a, 0x5)
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/fec.go:155 +0x679
github.com/fatedier/kcp-go.(*UDPSession).kcpInput(0x980a3c0, 0x9bdcc00, 0x546, 0x5dc)
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/sess.go:628 +0x71
github.com/fatedier/kcp-go.(*Listener).packetInput(0x9a11d50, 0x9bdcc00, 0x546, 0x5dc, 0x88713d8, 0x9a65cf8)
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/sess.go:780 +0x2ce
github.com/fatedier/kcp-go.(*Listener).monitor(0x9a11d50)
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/readloop_linux.go:99 +0x254
created by github.com/fatedier/kcp-go.ServeConn
        github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/sess.go:947 +0x1b8

**Comment by qiaoliangXgamemode** [comment]
这次是在debian上面的，无bbr状态下 使用的是frp最新版本

**Comment by qiaoliangXgamemode** [comment]
这次是在debian上面的，无bbr状态下 使用的是frp最新版本v0.37.1

**Comment by Kiritow** [comment]
也许发一下两端的配置和魔改内容会有助于问题解决？
