### ISSUE TITLE
是否支持多个客户端共用一个服务端端口配置

### ISSUE THREAD

**Issue by danileyang** [fatedier/frp#2515]
场景需求描述：
已在阿里云ECS上搭建frps集群，目前有多客户端(假设有10000+)，按照文档给出的frpc.ini配置：
每个client的配置如下：
[common]
server_addr = serverIpHere
server_port = serverPortHere

[spynote]
type = tcp
local_ip = 127.0.0.1
local_port = 8080
remote_port = remotePort1 (当客户端非常多的时候，这个服务端的端口是不够用的)
并且好像并不能配置成和其它客户端相同的remote_port端口

请问这个如何解决？

**Comment by fatedier** [comment]
你想如何解决？

**Comment by IndustrialCommunication** [comment]
tcp的端口还真解决不了，因为共用一个端口时没有一个可以区分的标志，http端口能共用，是因为可以用域名做为区分标志，不然不知道哪个转哪个。

**Comment by xilu0** [comment]
you can use multiple ip address.
