### ISSUE TITLE
frpc在群晖DSM中运行

### ISSUE THREAD

**Issue by acaiplus** [fatedier/frp#252]
1、将frpc和配置文件放到群晖的/usr/local/frpc目录中

2、chmod 0755更改文件夹权限

3、修改/etc/rc文件，在最末尾加入启动命令
sleep 60
cd /usr/local/frpc
./frpc

经过测试可以正常启动。希望有大侠能写一个可以注册成系统服务的脚本。

**Comment by freeradius-xx** [comment]
任务计划-触发的任务中新增用户定义的脚本，开机触发。
# frpc_start.sh
cd <程序所在目录>
nohup ./frpc -c frpc_min.ini &

**Comment by engineerlzk** [comment]
直接修改rc.local文件，在末尾exit 0之前添加如下代码即可随NAS启动
sleep 30
cd /frp#你安装frpc客户端的目录
nohup ./frpc -c ./frpc.ini &

**Comment by bingtianbaihua** [comment]
@acaiplus    sudo命令进入  /etc/rc.local   
将frpc的启动命令添加到里面即可。
nohup ./frpc -c ./frpc.ini &    或   nohup ./frpc -c ./frpc_min.ini  & 

前提是你的frps已经启动了。

**Comment by fatedier** [comment]
需要 sleep 应该是系统的 某些网络服务还没有启动完成， 例如 dns 服务，而 frpc 启动时会连接服务器，失败后直接退出，以后会加一个启动参数，使连接失败后过一段时间再重试，这样等网络服务加载完成后就可以连上了。
