### ISSUE TITLE
Configuration: use YAML/JSON instead of INI

### ISSUE THREAD

**Issue by fatedier** [fatedier/frp#2521]
In the early stage of development, i choose INI as configure format because it looks simple and easy to write. 

However, with the increase of project complexity, INI can't describe complex configures. It doesn't support hierarchical configuration. We use same prefix to represent arrays or maps. It's not an elegant way and difficult to unmarshal to a struct. 

We want to use YAML and JSON to replace INI in a smooth way:

* YAML and JSON will be supported in a future v0.x relase and can fully replace INI.
* INI is still supported in v0.x versions but will be removed in v1 versions.
* Complicated new featrues won't be supported by INI in future release. Users who want to use those features should change their configuration format to YAML/JSON.

**Comment by fakeboboliu** [comment]
maybe TOML?
JSON is hard to write by a human since its commas and quotes. And YAML needs lots of spaces for indenting, which causes hard to read.

**Comment by fatedier** [comment]
TOML maybe not suitable for multiple levels configurations. It's redundant.

We will support JSON and YAML first, it's widely used and easy to auto generate. And then, other format can also be supported if it can simple map file content to a golang struct.

**Comment by cloudwindy** [comment]
Is this planned in v1.0?

**Comment by fatedier** [comment]
@cloudwindy For compatibility reasons, this issue has been temporarily shelved. In the next major version, it will be directly supported, not v1, but v2.
