### ISSUE TITLE
gofrp.org/docs /文档网站访问不了了，是挂了还是怎么了

### ISSUE THREAD

**Issue by IndustrialCommunication** [fatedier/frp#2523]

**Comment by axboy** [comment]
开代理可访问

**Comment by IndustrialCommunication** [comment]
@axboy 意思被封杀了？不至于吧，这个又不违法，正常的一个软件。

**Comment by fatedier** [comment]
我这边可以访问，你用的是什么系统，浏览器，网络环境？

**Comment by axboy** [comment]
> @axboy 意思被封杀了？不至于吧，这个又不违法，正常的一个软件。

我是这么个情况，深圳电信，关闭shadowsocks无法打开。移动手机网络可以访问。

**Comment by ax2009live** [comment]
我刚才测试了一下，开始也是打不开，刷新好几次才打开！打开以后就很正常了；
估计跟网站调用 github.com 内容有关，大家都懂的，国内访问 github.com 有时候会抽风！

**Comment by sidpku** [comment]
有考虑将文档在其他地方做备份吗？我也碰到了网站打不开的情况。
手机流量联通和电脑移动挂代理都试过了，都不行。

**Comment by fatedier** [comment]
@sidpku 建议浏览器打开开发者模式，看一下具体的请求情况是什么问题。

**Comment by QiangZiBro** [comment]
这边也是一样，需要把代理调全局模式才能打开，否则是如下结果
![image](https://user-images.githubusercontent.com/30493365/135756206-077dd9de-57cd-4000-a9c8-c7f9f2741d28.png)
