### ISSUE TITLE
armbian客户端出现错误[W] [service.go:104] login to server failed: dial tcp X.X.X.X:6890: connect: no route to host

### ISSUE THREAD

**Issue by 15802096** [fatedier/frp#2524]
armbian客户端出现错误[W] [service.go:104] login to server failed: dial tcp X.X.X.X:6890: connect: no route to host  请求解决。整一晚没整好，0.37.1版本，0.37.0也是

**Comment by bingtianbaihua** [comment]
xxxx  是 ip 还是域名？ 
ping 下是不是通
nc -zv xxxx 6890 看下
