### ISSUE TITLE
使用frp不到2天，遭受DDOS攻击，之前已经正常使用半年

### ISSUE THREAD

**Issue by kerncoola** [fatedier/frp#2525]
机器是在香港，主要挂VPS，用了半年都很顺利，前两天看到fpr，就把家里的NAS穿透到公网，昨天收到短信遭受DDOS攻击，攻击流量峰值：2001Mbps，不确定是否frp原因，所以来咨询一下，有什么办法能更安全的穿透？
![image](https://user-images.githubusercontent.com/13283995/129292931-28302cc5-2641-4f97-b585-b0723aed89fe.png)

**Comment by kerncoola** [comment]
操作系统：Ubuntu Server 20.04 LTS 64bit

**Comment by XZB-1248** [comment]
很显然，这种问题不应该发issue。又不是软件的锅。这种问题你应该去群里讨论

**Comment by fatedier** [comment]
类似问题更适合网上搜索答案，如果我能很好的帮助你解决如何避免被 DDOS，我给别人收咨询费应该都发财了...
