### ISSUE TITLE
中文文档问题

### ISSUE THREAD

**Issue by lonble** [fatedier/frp#2526]
中文文档标题 **为 frp 做贡献** 下的 **frp 是一个免费且开源的项目** 这句。
**免费且开源** 是否应该改为 **自由且开源** 。因为在英文的使用场景里，**free and open-source** 是 **自由且开源** 的意思。

**Comment by fatedier** [comment]
这段中文并不是翻译过来的，本意就是免费且开源。当然，目前来看，我们可以把免费去掉，不需要强调这一点，`免费且开源的项目` -> `开源项目`。
