### ISSUE TITLE
Arch无法正常使用frpc

### ISSUE THREAD

**Issue by qxqzx3489** [fatedier/frp#2528]
**The solution you want**

**Alternatives considered**

**How to implement this function**

**Application scenarios of this function**

################
> ./frpc -c ./frpc
template: frp:342: unrecognized character in action: U+FFFD '�'
##################

**Comment by qxqzx3489** [comment]
运行提示这个错误
template: frp:342: unrecognized character in action: U+FFFD '�'

**Comment by qxqzx3489** [comment]
在centos8上是正常的

**Comment by 18o** [comment]
-c 后面是配置文件，你-c后面是二进制文件了

**Comment by qxqzx3489** [comment]
请问我要怎么解决这个问题呢

**Comment by 18o** [comment]
> 请问我要怎么解决这个问题呢

-c后面跟配置文件啊
