### ISSUE TITLE
frps运行后默认会占用8080端口么？

### ISSUE THREAD

**Issue by harryczqp** [fatedier/frp#253]
我内网PC使用frpc连接服务器时提示：start proxy error: listen tcp 0.0.0.0:8080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by harryczqp** [comment]
去服务器上查看端口时，发现8080端口被frps占用。

**Comment by bingtianbaihua** [comment]
@harryczqp   你好，麻烦你把frps.ini或者frps_min.ini配置文件信息贴一下，如果会被占用，一般是你配置文件里写的。

**Comment by harryczqp** [comment]
我找到问题了vhost_http_port占用了8080端口 @bingtianbaihua

**Comment by bingtianbaihua** [comment]
@harryczqp   配置文件里默认是写了8080，如果你需要其他端口就改一下。
