### ISSUE TITLE
Pease add remote_ip so I can bind to localhost

### ISSUE THREAD

**Issue by shemgp** [fatedier/frp#2531]
**The solution you want**
It would be nice if I can specify the `remote_ip`, as the pair of `remote_port`, to be able bind to localhost so that I wont expose my home server directly. I have an apache2 reverse proxy, so that I can also host websites in the VPS, while I also use frp, on a separate port, for hosting my home server on that same VPS.

**Alternatives considered**
Use iptables to block outside requests to the `remote_port`.

**How to implement this function**
Implement `remote_ip` as a pair of `remote_port` set  in frpc.ini

**Application scenarios of this function**
When one wants to host a combination of NAT based and VPS hosted sites in a VPS using a reverse proxy, but don't want to expose the NAT server port directly to avoid duplication.

Thank you for considering this feature.

**Comment by fatedier** [comment]
Try to use `proxy_bind_addr` https://github.com/fatedier/frp/blob/dev/conf/frps_full.ini#L17 for each frps.

`remote_ip` can't be set from frpc.

**Comment by shemgp** [comment]
I missed that config. It works as needed. Thanks.
