### ISSUE TITLE
正确填写 vhost_http_port 却提示 not support when vhost_http_port is not set

### ISSUE THREAD

**Issue by chenahoyu** [fatedier/frp#2533]
![截屏2021-08-17 21 50 32](https://user-images.githubusercontent.com/89085743/129737825-35ffbea6-f659-4d35-99db-978f4864c5ca.png)
<img width="968" alt="截屏2021-08-17 21 51 05" src="https://user-images.githubusercontent.com/89085743/129737923-5342e259-d5c0-4539-a6c6-3af50629f937.png">
p1为frpc，p2为frps

我的配置文件
frps.ini
[common]
bind_port = 7000 
dashboard_port = 7500 
token = XXXX
dashboard_user = XXXX
dashboard_pwd = XXXX
Vhost_http_port = 80 
Vhost_https_port = 443 

frpc.ini
[common]
server_addr = XXX.XXX.XXX.XX
server_port = 7000
token = XXXX

[web]
type = http
local_ip = 127.0.0.1 
local_port = 80
custom_domains = [myweb]

希望有人可以帮帮我，感谢了!
I hope someone can help me, thanks a lot!

**Comment by luozongcong** [comment]
vhost_http_port vhost_https_port，全部小写，不要大写

**Comment by linking123** [comment]
> vhost_http_port vhost_https_port，全部小写，不要大写 ,windows 下的frps.exe也遇到过。后来改换到linux版本了，没问题

win server 2012 同样错误，尴尬的系统？

**Comment by linking123** [comment]
> windows下 运行的时候命令一定要写完整 frps.exe -c frps.ini

@qiubi8801 老哥，这句话什么意思，不都是这个命令跑吗？你在win - win 成功了吗？

**Comment by kengerlwl** [comment]
> [hantwain](https://github.com/hantwain)

i meet the same problem, even i write the right config. 
i use the docker to get the effect i want. fail.
