### ISSUE TITLE
360安全提示可否取消

### ISSUE THREAD

**Issue by liuhaogui** [fatedier/frp#2539]
windows环境下载release直接报毒。

添加信任，运行frpc一样报毒。 有什么办法解决么？谢谢

![1629419022457](https://user-images.githubusercontent.com/47664337/130160354-1322169c-db0f-4e42-89c9-ae7d9e9da0e8.jpg)

**Comment by Jamy325** [comment]
卸载360

**Comment by liuhaogui** [comment]
先提交误报，等待反馈

有没有经验的大佬。 给下方向。
开发人员都懂肯定多半不会用360。 如果面向用户的东西就很有必要考虑小白用户了。是需要解决的。

1、360审核
2、加壳免杀

有没别的扫描方向，希望指教谢谢。

**Comment by liangzx96** [comment]
这玩意儿做的事情就是端口转发呀，对于360从行为上来说确实和木马没啥区别吧，要么就是给360缴投名状，要不然就是对抗杀软，这两个都不怎么讨好

**Comment by jiqing112** [comment]
360和腾讯管家都会有提示，卸载就好了

**Comment by tylzh97** [comment]
重复的问题 #1204
golang写的程序在windows下经常报毒，golang官网faq列表中给出如下回复：https://golang.org/doc/faq#virus

**Comment by liuhaogui** [comment]
改几行重新build下就可以了。
