### ISSUE TITLE
subdomain_host与custom_domains检测的bug

### ISSUE THREAD

**Issue by vc1** [fatedier/frp#254]
frps.ini

```
[common]
subdomain_host = frp.mydomain.com

[web01]
custom_domains = web-frp.mydomain.com
```
$ ./frps -c ./frps.ini
`Parse conf error: proxy [http] custom domain should not belong to subdomain_host`

`web-frp`.mydomain.com 与 `frp`.mydomain.com 属于不同二级域名，互不影响
运行的时候却报错

**Comment by vc1** [comment]
文档里写到
```
只需要将 *.subdomain_host 解析到 frps 所在服务器。之后用户可以通过 subdomain 自行指定自己的 web 服务所需要使用的二级域名，通过 {subdomain}.{subdomain_host} 来访问自己的 web 服务。
```
客户端是必须启用 `privilege_mode = true` 才能配置subdomain吗？？
设置特权模式后又必须指定一个remote_host，
我只是想不同客户端可以选择不同的子域名而已

**Comment by vc1** [comment]
服务端配置了custom_domains

客户端
```
[https]
subdomain = debug
local_ip = 127.0.0.1
local_port = 443
```

这样运行以后，服务端配置了custom_domains和{subdomain}.{subdomain_host} 都可以访问到，
客户端没有配置subdomain，就使用服务器配置的subdomain，都没配置就由服务器随机生成一个，返回给客户端，这样比较省事

可以参考一下https://natapp.cn/ 

另外建议一下可以以命令行形式传入配置参数运行

**Comment by fatedier** [comment]
你的提的第一个问题确实是一个 bug，web-frp.mydomain.com 应该是允许配置的，而 web.frp.mydomain.com 则不允许配置。

**Comment by fengqi** [comment]
@fatedier  
就算服务端启用了域名, 比如
[common]
subdomain_host = mydomain.com

客户端也支持
custom_domains = abc.mydomain.com

意思是 custom_domains = abc.mydomain.com 和 subdomain = abc 可以一起用
这样能兼容老配置

这样可以么

**Comment by fatedier** [comment]
如果最终域名一样，会报错，不一样的话可以兼容。

**Comment by fengqi** [comment]
嗯, 说的是一样的情况
