### ISSUE TITLE
多Https客户端配置时BUG

### ISSUE THREAD

**Issue by 462902059** [fatedier/frp#2543]
**[REQUIRED] hat version of frp are you using** 

Version: v0.37.1

**[REQUIRED] What operating system and processor architecture are you using**
OS:CentOS7 / Windows Server 2016
CPU architecture: x86

**[REQUIRED] description of errors**

**confile**
![image](https://user-images.githubusercontent.com/22461600/130361482-95202805-0f50-4192-bd73-e77658bf63f4.png)

**log file**

**Steps to reproduce the issue**
1. 配置好A和B客户端后连接Server

**Supplementary information**

访问https://test2.domain.com 会随机跳转到https://test.domain.com 
test.domain.com的内容为：node:test
test2.domain.com的内容为：node:test2

当访问test.domain.com随机出现node:test2
当访问test2.domain.com随机出现node:test

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by 462902059** [comment]
HTTP正常，HTTPS异常。

**Comment by 462902059** [comment]
https://gofrp.org/docs/features/common/client-plugin/#https2https
使用插件后解决

**Comment by fatedier** [comment]
之前有人反馈是浏览器 HTTP2 的问题，可以搜一下看看。

**Comment by ax2009live** [comment]
#628 
把通配域名证书改成单域名证书
