### ISSUE TITLE
是否有client 掉线后邮件/telegram提醒功能?

### ISSUE THREAD

**Issue by shuivin** [fatedier/frp#2549]
# 是否有client 掉线后邮件/telegram提醒功能?

某台电脑24 小时开机, 偶尔远程急用的, 发现过几次 win10 升级异常等问题导致 frpc 挂了. 
又不是经常看服务台, 是否可以做一个掉线提醒功能?

谢谢!

**Comment by daQzi** [comment]
有对应的插件开发 可以使用frp的插件

**Comment by shuivin** [comment]
谢谢, 有什么关键词可以提示吗?
