### ISSUE TITLE
Dockerfile_alpine不能正常使用

### ISSUE THREAD

**Issue by alwaystest** [fatedier/frp#255]
在go环境下编译好binary后build的Docker_alpine容器不能正常运行。

报错 `no such file or directory`

StackOverflow给出的解决方案在这里 http://stackoverflow.com/a/36308464/3819519

> There are two solutions I've come across:
> - Disable CGO, via CGO_ENABLED=0
> - Force the use of the Go implementation of net dependencies, netgo via go build -tags netgo -a -v, this is implemented for a certain platforms

我使用了第一种方法，编译的二进制文件可以正常运行。

**Comment by fatedier** [comment]
了解，这个 Dockefile 不涉及编译，只是把你编好的文件放进去，编译时需要注意。

**Comment by alwaystest** [comment]
所以Makefile.cross-compiles文件是不是需要更新一下？免得别人在用alpine镜像运行的时候再出问题。相对golang镜像，alpine镜像的大小真的小好多，我想大家如果用Docker来跑frps的时候应该都会倾向选择alpine镜像吧。

我对go语言不熟悉，不知道`CGO_ENABLED=0`会不会有什么别的副作用，所以没有直接提PR。

**Comment by fatedier** [comment]
这个文件是我用来发布版本的时候用的，自己编译的话没必要编译各个平台。

frps 需要对外暴露多个不固定的端口，所以用于 tcp 转发的时候其实不是很适合放在 docker 里。至于 alpine 镜像的问题，下个版本我会维护下 dockerhub 上的 alpine 镜像。
