### ISSUE TITLE
Can't use lower number port as remote port

### ISSUE THREAD

**Issue by tmpuserx** [fatedier/frp#2551]
**[REQUIRED] hat version of frp are you using** 

Version: frp_0.37.1_linux_amd64

**[REQUIRED] What operating system and processor architecture are you using**
OS: Ubuntu 20.04.2 LTS
CPU architecture:  AMD64

**[REQUIRED] description of errors**
When I used ports lower than 1000 for remote_port and start frpc it's giving error start error: port unavailable. i can confirm that the port isn't in used on the system which running the frps

**confile**

[common]
server_addr = serverip
server_port = 7371

[laptop1rdp]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 21

**log file**

**Steps to reproduce the issue**
1. in frpc.ini, the remote_port put something like 21, 23, 80, etc ports which not being used on frps server
2. run frpc -c frpc.ini
3. 

**Supplementary information**

**Can you guess what caused this issue**
those ports might be reserved for the official application such as ftp, telnet, http etc. but as long as there are not these services running on the server, they should need to be able to be used..

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by landuo** [comment]
> 

use default frps.service to start, can't use port 80, change 'User' to 'root' runs goods in frps.service.
