### ISSUE TITLE
xtcp can't be successfully 

### ISSUE THREAD

**Issue by TerryWang159** [fatedier/frp#2552]
### **Error Message :**

**dial client udp address error: dial udp 127.0.0.1:50857->__IP Address_:48909: connect: invalid argument**

  1. FRPS.log
     

>           _2021/08/27 11:05:24 [I] [root.go:200] frps uses config file: /home/terry/frp/frps.ini
>           2021/08/27 11:05:24 [I] [service.go:192] frps tcp listen on 0.0.0.0:8760
>           2021/08/27 11:05:24 [I] [service.go:202] frps kcp listen on udp 0.0.0.0:8760
>           2021/08/27 11:05:24 [I] [service.go:235] http service listen on 0.0.0.0:808
>           2021/08/27 11:05:24 [I] [service.go:250] https service listen on 0.0.0.0:8443
>           2021/08/27 11:05:24 [I] [service.go:275] nat hole udp service listen on 0.0.0.0:2122
>           2021/08/27 11:05:24 [I] [root.go:209] frps started successfully
>           2021/08/27 11:05:29 [I] [service.go:449] [36e3b789e2f75a45] client login info: ip _[IP Address_ :57548] version [0.37.1] hostname [] os [linux] arch [amd64]
>           2021/08/27 11:05:29 [D] [control.go:219] [36e3b789e2f75a45] new work connection registered
>           2021/08/27 11:05:29 [I] [control.go:444] [36e3b789e2f75a45] new proxy [p2p_ssh_host] success
>           2021/08/27 11:05:41 [I] [service.go:449] [75b43221c3733879] client login info: ip [127.0.0.1:43508] version [0.37.1] hostname [] os [linux] arch [amd64]
>           2021/08/27 11:05:41 [D] [control.go:219] [75b43221c3733879] new work connection registered
>           2021/08/27 11:05:59 [D] [control.go:473] [36e3b789e2f75a45] receive heartbeat
>           2021/08/27 11:06:11 [D] [control.go:473] [75b43221c3733879] receive heartbeat
>           2021/08/27 11:06:29 [D] [control.go:473] [36e3b789e2f75a45] receive heartbeat
>           2021/08/27 11:06:35 [D] [control.go:248] [36e3b789e2f75a45] get work connection from pool
>           2021/08/27 11:06:35 [D] [proxy.go:104] [36e3b789e2f75a45] [p2p_ssh_host] get a new work connection: [_IP Addresss_:57548]
>           2021/08/27 11:06:35 [D] [control.go:219] [36e3b789e2f75a45] new work connection registered
>           2021/08/27 11:06:41 [D] [control.go:473] [75b43221c3733879] receive heartbeat
>           2021/08/27 11:06:46 [D] [control.go:248] [36e3b789e2f75a45] get work connection from pool
>           2021/08/27 11:06:46 [D] [proxy.go:104] [36e3b789e2f75a45] [p2p_ssh_host] get a new work connection: [_IP Adress_:57548]
>           2021/08/27 11:06:47 [D] [control.go:219] [36e3b789e2f75a45] new work connection registered
>           2021/08/27 11:06:59 [D] [control.go:473] [36e3b789e2f75a45] receive heartbeat
>           2021/08/27 11:07:11 [D] [control.go:473] [75b43221c3733879] receive heartbeat
>           2021/08/27 11:07:29 [D] [control.go:473] [36e3b789e2f75a45] receive heartbeat
>           2021/08/27 11:07:41 [D] [control.go:473] [75b43221c3733879] receive heartbeat_

  2. FRPC.log (supply services machine )
       
    2021/08/27 11:05:29 [I] [service.go:304] [36e3b789e2f75a45] login to server success, get run id [36e3b789e2f75a45], server udp port [2122]
    2021/08/27 11:05:29 [I] [proxy_manager.go:144] [36e3b789e2f75a45] proxy added: [p2p_ssh_host]
    2021/08/27 11:05:29 [I] [control.go:180] [36e3b789e2f75a45] [p2p_ssh_host] start proxy success
    2021/08/27 11:05:59 [D] [control.go:315] [36e3b789e2f75a45] send heartbeat to server
    2021/08/27 11:05:59 [D] [control.go:346] [36e3b789e2f75a45] receive heartbeat from server
    2021/08/27 11:06:29 [D] [control.go:315] [36e3b789e2f75a45] send heartbeat to server
    2021/08/27 11:06:29 [D] [control.go:346] [36e3b789e2f75a45] receive heartbeat from server
    2021/08/27 11:06:35 [D] [proxy_wrapper.go:231] [36e3b789e2f75a45] [p2p_ssh_host] start a new work connection, localAddr: 192.168.88.88:57548 remoteAddr: _IP Address_:8760
    2021/08/27 11:06:43 [W] [proxy.go:383] [36e3b789e2f75a45] [p2p_ssh_host] get sid from visitor error: read udp 192.168.88.88:48909: i/o timeout
    2021/08/27 11:06:46 [D] [proxy_wrapper.go:231] [36e3b789e2f75a45] [p2p_ssh_host] start a new work connection, localAddr: 192.168.88.88:57548 remoteAddr: _IP Adress_:8760
    2021/08/27 11:06:55 [W] [proxy.go:383] [36e3b789e2f75a45] [p2p_ssh_host] get sid from visitor error: read udp 192.168.88.88:36678: i/o timeout
    2021/08/27 11:06:59 [D] [control.go:315] [36e3b789e2f75a45] send heartbeat to server
    2021/08/27 11:06:59 [D] [control.go:346] [36e3b789e2f75a45] receive heartbeat from server
    2021/08/27 11:07:29 [D] [control.go:315] [36e3b789e2f75a45] send heartbeat to server
    2021/08/27 11:07:29 [D] [control.go:346] [36e3b789e2f75a45] receive heartbeat from server  

  3. FRPC.log  (Visitor machine)
 
```
    2021/08/27 11:05:41 [I] [service.go:304] [75b43221c3733879] login to server success, get run id [75b43221c3733879], server udp port [2122]
    2021/08/27 11:05:41 [I] [visitor_manager.go:86] [75b43221c3733879] start visitor success
    2021/08/27 11:05:41 [I] [visitor_manager.go:130] [75b43221c3733879] visitor added: [p2p_me_visitor]
    2021/08/27 11:06:11 [D] [control.go:315] [75b43221c3733879] send heartbeat to server
    2021/08/27 11:06:11 [D] [control.go:346] [75b43221c3733879] receive heartbeat from server
    2021/08/27 11:06:35 [D] [visitor.go:208] [75b43221c3733879] [p2p_me_visitor] get a new xtcp user connection
    2021/08/27 11:06:35 [E] [visitor.go:277] [75b43221c3733879] [p2p_me_visitor] dial client udp address error: dial udp 127.0.0.1:50857->_IP Adress_ :48909: connect: invalid argument
    2021/08/27 11:06:41 [D] [control.go:315] [75b43221c3733879] send heartbeat to server
    2021/08/27 11:06:41 [D] [control.go:346] [75b43221c3733879] receive heartbeat from server
    2021/08/27 11:06:46 [D] [visitor.go:208] [75b43221c3733879] [p2p_me_visitor] get a new xtcp user connection
    2021/08/27 11:06:47 [E] [visitor.go:277] [75b43221c3733879] [p2p_me_visitor] dial client udp address error: dial udp 127.0.0.1:52644->_IP Adress_ :36678: connect: invalid argument
    2021/08/27 11:07:11 [D] [control.go:315] [75b43221c3733879] send heartbeat to server
    2021/08/27 11:07:11 [D] [control.go:346] [75b43221c3733879] receive heartbeat from server
```

### **Configurations:**

1. **FRPS ---debian 10** 
  
  ```
  [common]
  bind_port = 8760
  bind_udp_port = 2122
  kcp_bind_port = 8760
  
  authentication_method = token
  token = Mmp@123
  vhost_http_port = 808
  vhost_https_port = 8443
  
  log_file = /home/terry/frp/frps.log
  log_level = debug
  log_max_days = 3  
  disable_log_color = false
  ```

2. **FRPC (supply services machine )**

```
[common]
server_addr = 127.0.0.1
server_port = 8760
token = Mmp@123
tls_enable = true
tcp_mux = true
login_fail_exit = false
protocol = tcp

log_file = /home/terry/frp/frpc.log
log_level = debug
log_max_days = 3

[p2p_me_visitor]
type = xtcp
role = visitor  
server_name = p2p_ssh_host  
sk = wanghuan>%#189
bind_addr = 127.0.0.1 
bind_port = 6006
use_encryption = false
use_compression = true
```

3. **FRPC ( (Visitor machine)**

```
[common]
server_addr = IP Adress
server_port = 8760
token = Mmp@123
tls_enable = true
tcp_mux = true

login_fail_exit = false
protocol = tcp

log_file = /home/terry/frp/frpc.log
log_level = debug
log_max_days = 3  
disable_log_color = false

[p2p_ssh_host]
type = xtcp
sk = wanghuan>%#189
local_ip = 192.168.88.88
local_port = 8096	
use_compression = true
```

### **Remark:**

FRPC and FRPS with the same version .  change protocol = KCP  ,Show the same error.  Firewall and  Service port is opening,
FRPS has the public IP address and FRPC (192.168.88.88)  is the DMZ Machine with the router settings .
Who can help me ,how to resolve it ? Thanks!

**Comment by TerryWang159** [comment]
都没有人人气的啊

**Comment by TerryWang159** [comment]
有大神帮忙回答么?

**Comment by TerryWang159** [comment]
报错信息如下 ，请问有大神这是什么问题？

2021/09/11 22:31:48 [E] [visitor.go:277] [e2ab3c5995653401] [p2p_me_visitor] dial client udp address error: dial udp 127.0.0.1:40788->116.234.91.72:37564: connect: invalid argument

**Comment by ashleysommer** [comment]
I'm seeing this same issue. Can this be re-opened?
