### ISSUE TITLE
During startup, can frpc retry if error on server connection?

### ISSUE THREAD

**Issue by yydcool** [fatedier/frp#256]
The case happens when I start frps later than frpc.
frpc will try to connect server, but the frps is not running yet. So frpc print "connect to server failed!" then exit.
Refer to code in frpc/control.go func ControlProcess(cli *client.ProxyClient, wait *sync.WaitGroup)

```
	c, err := loginToServer(cli)
	if err != nil {
		log.Error("ProxyName [%s], connect to server failed!", cli.Name)
		return
	}
```
Would it be better to have a while loop here? always retry until connected to server  (also wait (e.g. 10s) between each retry)

**Comment by cxx8294** [comment]
请讲普通话

**Comment by fatedier** [comment]
@yydcool Uses may set wrong server ip or port, and it will never connect success. So i think it's better to feedback the error and exit.

**Comment by fatedier** [comment]
@cxx8294 Github 上推荐用英语，方便各个国家的使用者共同交流，只要别人能看懂就行了。

**Comment by soldierssword** [comment]
但是有时候需要重启公网的frps来重新加载配置文件，如果不自动重连的话那就很麻烦了，希望在启动参数中加入失败重试。

**Comment by fantasydr** [comment]
If you're using systemd to launch frps, add something like this in the systemd conf file:
```
[Service]
Restart=on-failure    
RestartSec=5s
```

**Comment by HomeLH** [comment]
A configurable retry entry is helpful for embedding devices, because their network service such as 4G may not be stable.

**Comment by HomeLH** [comment]
> 
> 
> If you're using systemd to launch frps, add something like this in the systemd conf file:
> 
> ```
> [Service]
> Restart=on-failure    
> RestartSec=5s
> ```
> 
> A hint for someone like me newly to the frps and systemd.

Thanks a lot. This method works well. It will retry every "RestartSec“.

**Comment by Marcocxy** [comment]
> If you're using systemd to launch frps, add something like this in the systemd conf file:
> 
> ```
> [Service]
> Restart=on-failure    
> RestartSec=5s
> ```
> 
> A hint for someone like me newly to the frps and systemd.

Any idea for frpc(frp client)? The topic was frpc not frps.

**Comment by axmmisaka** [comment]
> > If you're using systemd to launch frps, add something like this in the systemd conf file:
> > ```
> > [Service]
> > Restart=on-failure    
> > RestartSec=5s
> > ```
> > A hint for someone like me newly to the frps and systemd.
> 
> Any idea for frpc(frp client)? The topic was frpc not frps.

You could, if you want, write a wrapper script in powershell like this
```powershell
$ISSUE = $true
while ($ISSUE) {
    ./frpc @args
    if ($LastExitCode -eq 0) {
        $ISSUE = $false
    }
}
```
or a comparable script in bash to make it keep trying.  
That said I ran into similar problems and it might be a good feature to add, although it certainly could be solved externally; I'm using nssm on windows and the restart logic is such a pita

如果你想的话，可以写个上面贴的这种执行脚本或者bash中类似的脚本让程序失败后重试  
不过我最近遇到了类似的问题，虽然这个问题可以用外部工具解决，我觉得可能也是个可以加入的好特性；我在windows上用nssm，重启逻辑是真的高血压
