### ISSUE TITLE
1.stcp能否双向 2.s5走frpc 3. 多ip支持

### ISSUE THREAD

**Issue by gitlsl** [fatedier/frp#2561]
1.role visitor -> frps -> frpc role server
现在的 stcp 只能是这样访问  ， 能否双向 互相访问呢？
简而言之      
A 公网
B 内网
C 内网
BC开启1个STCP后， 能够互相访问  按照 role visitor -> frps -> frpc role server 的模式  得在BC上开2个服务了（这里应该不局限于2个，BCDEFG。。。只要sk一样都能访问）

2. 现在  配置 s5代理， 其实就只在    server上开了代理， 走server的的ip出口去访问，   能否支持 走frpc的网络？
      user--->frps(s5)-->frpc---->internet/lan   这样的形式呢
3.  有些电脑多网卡多IP  的，  能否配置出口ip

**Comment by maxadc** [comment]
当然可以了
