### ISSUE TITLE
Question about Encryption

### ISSUE THREAD

**Issue by padziu** [fatedier/frp#2564]
### Describe the feature request

How is the traffic between the client and the server encrypted?

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by tgbv** [comment]
@fatedier If certificates are not specified in configuration, how is traffic encrypted when specifying `tls_enable = true` between frps <-> frpc ?

**Comment by fatedier** [comment]
> @fatedier If certificates are not specified in configuration, how is traffic encrypted when specifying `tls_enable = true` between frps <-> frpc ?

It will use auto generated certificates.

**Comment by padziu** [comment]
@fatedier I mean how traffic is encrypted between the client and the server if the client is set to use_encryption = true?
