### ISSUE TITLE
[vhost_http_port][vhost_https_port]如果这样配置 80,81,82是不生效，不知道为什么

### ISSUE THREAD

**Issue by luozongcong** [fatedier/frp#2567]
### Bug Description

1、关于这参数配置可以配多个端口
[vhost_http_port] [vhost_https_port]最多只能配置2个端口
```
......

vhost_http_port= 80
vhost_https_port= 443

......

```
如果这样配置 80,81,82是不生效，不知道为什么

```
......

vhost_http_port= 80, 81, 82
vhost_https_port= 443

......

```

2、关于这参数配置可以配多个域名
```
......
custom_domains = 我的域名1.com
custom_domains = 我的域名2.com
......

```
或者
```
......
custom_domains = 我的域名1.com, 我的域名2.com
......

```

### frpc Version

0.37.1

### frps Version

0.37.1

### System Architecture

linux/amd64 + windows/amd64

### Configurations

....
vhost_http_port= 80, 81, 82
vhost_https_port= 443
....
custom_domains = 我的域名1.com
custom_domains = 我的域名2.com
....

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by luozongcong** [comment]
前提1：windows server 2012 r2 datacenter 或windows 10 21H 环境下【frp_0.37.1_windows_amd64】 下的frps.exe启动成功，启动frps,exe正常

结果1：但是如果启动frpc,exe连接就会异常 vhost_http_port is not set

---
前提2：如果是用【frp_0.37.1_linux_amd64】frps则正常

结果2：启动frpc,exe正常

---
配置如下：
frps.ini
```
[common]
bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443

# frp管理后台端口，请按自己需求更改
dashboard_port = 7500
# frp管理后台用户名和密码，请改成自己的
dashboard_user = admin
dashboard_pwd = admin
enable_prometheus = true

# frp日志配置
log_file = /var/log/frps.log
log_level = info
log_max_days = 3


```
frpc.ini
```
[common]
server_addr = api.luozongcong.icu
server_port = 7000

#http服务
[web_80]
type = http
local_port = 8072

custom_domains = api.luozongcong.icu
```

**Comment by luozongcong** [comment]
如果配置
vhost_http_port= 80, 81, 82
 改成
vhost_http_ports= 80, 81, 82
仅80生效

**Comment by fatedier** [comment]
You can only set one port for `vhost_http_port` now.
