### ISSUE TITLE
代理sip端口的时候 内网服务器能收到请求 但是返回后 frp没有代理回客户端请求

### ISSUE THREAD

**Issue by sscenglish** [fatedier/frp#257]
代理sip端口的时候 内网服务器能收到请求 但是返回后 frp没有代理回客户端，导致软电话还是一直在注册的状态，其实这时他已经注册上了！是我的配置问题吗？请指导下 谢谢了

**Comment by fatedier** [comment]
特定的应用层协议不一定能支持，frp 只能转发一个端口。

**Comment by sscenglish** [comment]
这是一个外线ip电话注册到内网服务器（pbx）的一个应用环境  这里确实只用到了一个端口（5060端口），内网服务器（pbx）确实收到了来自ip电话的注册请求（frp代理到内网服务器正常），表现出来的问题就是没有代理内网服务器的返回结果到外线客户端（ip电话），内网服务器的返回结果没有正确的回到ip电话端

**Comment by fatedier** [comment]
简单看了下，应该还是这个协议本身比较复杂，不是端口转发能解决的。

参考：http://blog.csdn.net/dingpeng1978/article/details/4369930
