### ISSUE TITLE
一个端口多个TCP穿透可以吗？

### ISSUE THREAD

**Issue by hrkkid** [fatedier/frp#2570]
### Describe the feature request

比如只有一个服务器。客户端a本地ssh端口22，服务器转发端口6088；客户端b本地ssh端口22，服务器转发端口6088；客户端a和b使用一个服务器上端口6088进行穿透可以吗？怎么设置呢？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
不可以
