### ISSUE TITLE
[Feature Request] 一个功能改进建议

### ISSUE THREAD

**Issue by maxadc** [fatedier/frp#2576]
### Describe the feature request

2021/09/15 15:09:12 [W] [control.go:178] [5fa285526f22a871] [xxxxx] start error: port already used
这个问题,想必每个人都遇到过。从网上找，只能找到一个解决方案，就是改个名字。
这根本不是正常的解决方案。
因为，出现这个问题其实是，客户端的非正常frpc退出，而服务器却认为在线。对吧。
告警却不不处理这根本不是正确的处理方法。
改名称，不现实，特别是穿透的场景中，那意味着不但是被连接的客户端要改，访问的节点，有一个算一个，全都要改。
而这种错误，其实是很多的，一旦非法退出，又在很短的时间内连接，100%会出现这个错误。
其实，我认为，这完全可以通过授权token秘钥来解决名字归属的问题。被连接的客户端token正确，就直接更新服务器的打洞信息。没必要报错而不处理。
以上建议供老大参考。谢谢
这个问题对我非常困扰，也是很多人的困扰。我只能写了一个脚本，每次启动都随机一个名词，而且客户端还要，非常不方便。请老大斟酌

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
`port already used`，字面翻译，端口已被占用，建议尝试更换远端绑定端口。

名字冲突和端口冲突不是一回事。
