### ISSUE TITLE
frps in windows dosen't support token

### ISSUE THREAD

**Issue by asyowish** [fatedier/frp#2577]
### Bug Description

Hi, i use frps in windows server 2019,
When client use token, frpc will failed with the error:
[token in login doesn't match token from configuration.]

The token configuration in frps seems dosen't take effect.
Once client comment the token line in the frpc.ini , then access frps successed, while the frps is enable token.

I've tried this is okay in CentOS 7, but token in frps configuration can't take effect in windows.

### frpc Version

0.37.1

### frps Version

0.37.1

### System Architecture

windows/amd64   Server 2019

### Configurations

# frps.ini
[common]
bind_addr = 0.0.0.0
bind_port = 7000
#bind_udp_port = 7001
#kcp_bind_port = 7000

authentication_method = token
token = *

#log_file = frps.log
#log_level = info
#log_max_days = 5

dashboard_addr = 0.0.0.0
dashboard_port = 7500

dashboard_user = *
dashboard_pwd = *

# frpc.ini 
[common]
server_addr = *
server_port = 7000
token = *

### Logs

frps log:
2021/09/15 16:17:37 [I] [service.go:449] [1d36ede392b42ecf] client login info: ip [IP:Port] version [0.37.1] hostname [] os [windows] arch [amd64]
2021/09/15 16:17:37 [W] [service.go:351] register control error: token in login doesn't match token from configuration

frpc log:
2021/09/15 16:17:37 [E] [service.go:295] token in login doesn't match token from configuration
2021/09/15 16:17:37 [W] [service.go:104] login to server failed: token in login doesn't match token from configuration
token in login doesn't match token from configuration

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [x] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Do you specify the correct configuration file for frps?

**Comment by asyowish** [comment]
@fatedier Thanks! Thanks!
I've added frpc to service in windows without specify the frpc.ini , and it work well.
I think frps as well.
As your advice, i specify the frps.ini, now it work well too. 
Haha, Happy.

**Comment by asyowish** [comment]
噢噢，原来是国人，哈哈，支付宝请您喝杯咖啡，谢谢。

**Comment by asyowish** [comment]
总结一下，我之前是在Windows（windows 10）中使用 nssm 将 frpc 配置成了服务，
当时并未使用参数指定 frpc.ini 的配置文件，会正常调用同目录的配置文件没有问题；

当在windows（Server 2019）中配置同样配置 frps 时，发现配置文件似乎没有生效，
按作者提示，加上参数指定 frps.ini 配置文件，正常工作！
