### ISSUE TITLE
[Feature Request] Support solaris/illumos platform

### ISSUE THREAD

**Issue by lispstudent** [fatedier/frp#2578]
### Describe the feature request

Please consider offering binary for Solaris/[illumos](https://illumos.org/), an OpenSolaris derivative, on which SmartOS, OmniOS, OpenIndiana and more are based.

A binary compiled for Solaris is compatible with illumos.

Go toolchain is present in illumos.

Many go apps are available as binary for Solaris/illumos, one among many, [syncthing](https://github.com/syncthing/syncthing/releases/tag/v1.18.1).

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
I'm not sure how many users want pre-build binary file for `Solaris/illumos`. You can build it by yourself now.

If there are also other requests for this platform, we might provide it future.
