### ISSUE TITLE
bandwidth_limit in cli mode

### ISSUE THREAD

**Issue by RuofengX** [fatedier/frp#2579]
### Bug Description

./frpc.exe xtcp *** --bandwidth_limit 1MB will return `Error: unknown flag: --bandwidth_limit`

### frpc Version

0.37.1

### frps Version

0.37.1

### System Architecture

windows/amd64

### Configurations

using  --bandwidth_limit

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
Command line args only support basic features.

You'd better try configuration file if you need all features.

**Comment by RuofengX** [comment]
I want all my config could run in the memory, is there any solution?
