### ISSUE TITLE
https2http  wss无法连接

### ISSUE THREAD

**Issue by ghycn** [fatedier/frp#2585]
### Bug Description

![image](https://user-images.githubusercontent.com/20291615/134451658-44695e57-1ce7-4664-84de-eb849912be2b.png)
https网站访问正常，但是wss无法连接

内网nginx日志，表明可以收到转发，就是无法连接成功
![image](https://user-images.githubusercontent.com/20291615/134451968-9e33c2a0-08ae-4817-b2f3-3fbd0dba52ca.png)

### frpc Version

0.37.1

### frps Version

0.37.1

### System Architecture

linux/amd64

### Configurations

frps配置
```
[common]
bind_port = 7000
server_addr = x.x.x.x
privilege_token = kXZOPxFvieYYCPtX4sWhdZlW5
vhost_http_port = 9080
vhost_https_port = 9081

```

frpc配置
```
[common]
server_addr = 服务端IP
server_port = 7000
privilege_token = kXZOPxFvieYYCPtX4sWhdZlW5


[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 7001

#[web1]
#type = http
#local_ip = 127.0.0.1
#local_port = 80
#remote_port = 9080
#custom_domains = xx.xx.com

[test_htts2http]
type = https
custom_domains = xx.xx.com

plugin = https2http
plugin_local_addr = 127.0.0.1:80

# HTTPS 证书相关的配置
plugin_crt_path = /opt/app/aipoc/docker/conf/nginx/cert/server.pem
plugin_key_path = /opt/app/aipoc/docker/conf/nginx/cert/server.key
plugin_host_header_rewrite = 127.0.0.1
plugin_header_X-From-Where = frp

```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by opsscn** [comment]
#2125 看这里
