### ISSUE TITLE
Why use `user` as the prefix of `server_name`?

### ISSUE THREAD

**Issue by jat001** [fatedier/frp#2586]
### Bug Description

I have multiple frp clients on multiple computers so I use the prefix `user` to identify them.

frpc adds the prefix to the proxy name. but it also adds the prefix to `server_name`, which is not what I want.
https://github.com/fatedier/frp/blob/dev/pkg/config/visitor.go#L145

For example: see configurations.

### frpc Version

0.37.1

### frps Version

0.37.1

### System Architecture

linux/amd64

### Configurations

I want to connect to the ssh service of client A on client B, and connect to the ssh service of client B on client A.
So these are my configurations.
(Other irrelevant configurations like `local_ip`, `local_port` and `bind_addr`, `bind_port` have been removed.)

client A:

```
[common]
user = cli_a

[ssh]
type = stcp

[ssh_visitor_b]
type = stcp
role = visitor
server_name = cli_b.ssh
```

client B:

```
[common]
user = cli_b

[ssh]
type = stcp

[ssh_visitor_a]
type = stcp
role = visitor
server_name = cli_a.ssh
```

### Logs

I got the following error because frpc added the prefix `cli_a` to the server_name `cli_b.ssh`.

```
[cli_a.ssh_visitor_b] start new visitor connection error: custom listener for [cli_a.cli_b.ssh] doesn't exist
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
You can't connect from one user to another now.
