### ISSUE TITLE
Can we specify a custom proxy bind address for a [section] on frps?

### ISSUE THREAD

**Issue by tgbv** [fatedier/frp#2589]
**frps.ini**
```ini
[common]
bind_addr = x.x.x.x
bind_port = 6999

proxy_bind_addr = 127.0.0.1
vhost_http_port = 6998

[ssh]
proxy_bind_addr = x.x.x.x
```

**frpc.ini**
```ini
[common]
server_addr = x.x.x.x
server_port = 6999

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000
```

With the upper configuration, command `ssh -oPort=6000 user@x.x.x.x` fails.

Is there a way to specify a custom proxy bind host for section on fprs ?

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
I prefer you deploy two frps for different scenarios. Otherwise, it will be complicated to maintain.
