### ISSUE TITLE
hello大神，问问frp多客户端如何实现

### ISSUE THREAD

**Issue by llkak47** [fatedier/frp#259]
完成了服务器建设
然后试着在局域网openwrt mips版本独立运行frpc 成功
独立运行树莓派 arm版 frpc也成功

但是本人以为可以两个局域网ip同时映射 一个域名不同端口吧，怎么设置呢？
折腾半天出不来，求高手指点。

**Comment by mbj2014** [comment]
可以呀，frps.ini里面的配置中，针对不同的局域网IP配置中，端口不同就行。
