### ISSUE TITLE
frpc and frps donot work and tell me syntax error: unexpected "("

### ISSUE THREAD

**Issue by zhizunbao84** [fatedier/frp#2594]
### Bug Description

我有个光猫，想在光猫里面建立frp服务器。

我都是在win7系统下载好软件包，解压好，然后通过ftp上传到光猫里
在操作之前我也看了相关的issue，然后我测试各种不同的版本，具体错误提示如下：

官方 frp_0.37.1_linux_mips\
运行./frps，提示：
./frps: line 1: syntax error: unexpected "("
运行./frpc，提示：
./frpc: line 1: syntax error: unexpected "("

官方 frp_0.37.1_linux_mipsle\
第一次测试
运行./frpc，提示：
./frpc: line 1: syntax error: unexpected word (expecting ")")

运行./frps，提示：
N: not found
./frps: line 1: syntax error: unexpected word (expecting ")")

删除后重新上传，第二次测试
运行./frps后提示：
./frps: line 6: syntax error: unexpected "("

运行./frpc后提示：
./frpc: line 1:ELF: not found
./frpc: line 1: syntax error: unexpected word (expecting ")")
怎么两次还不一样呢？

官方 frp_0.14.1_linux_mips\
运行./frps，提示：
./frps: line 1: syntax error: unexpected "&" (expecting ")")
./frpc: line 2: syntax error: unexpected word (expecting ")")

官方 frp_0.14.1_linux_mipsle\
./frpc: line 1: syntax error: unexpected word (expecting ")")
运行./frps，提示：
@▒Ko: not found
./frps: line 2: 8: not found
./frps: line 3: syntax error: unexpected "("

测试网友编译的https://github.com/IxsCN/frpc_mipsle_noFPU
运行./frpc，提示：
▒72: no such file
./frpc: line 2: syntax error: unexpected "("./frpc: line 1:ELF϶▒▒6▒▒oY▒Π%S▒▒▒: not found

测试网友编译的https://github.com/nwct/frpu/releases
测试linux-mips\
运行./frpc，提示：
./frpc: line 1: can't open ▒▒c▒▒H*: no such file
./frpc: line 1:ELF: not found
./frpc: line 1: syntax error: unexpected ";" (expecting "in")
运行./frps，提示：
./frps: line 1: syntax error: unexpected "("

测试linux-mips32le\
运行./frpc，提示：
./frpc: line 1: syntax error: unexpected ")"
运行./frps，提示：
./frps: line 2: syntax error: unexpected word (expecting ")")

测试linux-mipsle\
运行./frpc，提示：
./frpc: line 2: syntax error: unexpected "("
运行./frps，提示：
./frps: line 1: syntax error: unexpected "("

### frpc Version

0.37.1

### frps Version

0.37.1

### System Architecture

linux mips

**Comment by zhizunbao84** [comment]
搞定了，我每次都是下载在win7系统，解压后再上传到光猫。问题就出在这

后来我直接在光猫里面下载解压就好了

**Comment by laofuzi-debug** [comment]
你最后搞定使用的什么版本？
