### ISSUE TITLE
[Feature Request] 支持自动化 Let's Encrypt

### ISSUE THREAD

**Issue by pinghe** [fatedier/frp#2598]
### Describe the feature request

类似 caddy，frps 自动申请更新配置Let's Encrypt 证书。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by delfer** [comment]
+1 for Let’s Encrypt support. Just add github.com/xenolf/lego/acme like Traefik: https://github.com/traefik/traefik/commit/6e484e5c2dc02fc7e3729dd24d6f368b71a13ddb
