### ISSUE TITLE
0.9.3 服务器端的dashboard无论如何连不上（CentOS7）

### ISSUE THREAD

**Issue by Ourobotos** [fatedier/frp#260]
无论dashboard_port设成什么，访问的时候浏览器只会一直loading
防火墙已关闭

**Comment by fatedier** [comment]
换个浏览器试试 or 给出足够的信息。

**Comment by Ourobotos** [comment]
Microsoft Edge试了可以，Chrome 55.0.2883.87 m (64-bit) 不行，

**Comment by fatedier** [comment]
你给出的信息还不足以判断是什么问题。

**Comment by bingtianbaihua** [comment]
@Ourobotos   截图日志信息

**Comment by Ourobotos** [comment]
@bingtianbaihua @fatedier 我已查出是什么问题。弹出密码输入框和Chrome里的一个VPN插件冲突，禁用插件以后就可以了。
