### ISSUE TITLE
Is possible to configure different  tokens for different clients? 

### ISSUE THREAD

**Issue by cassc** [fatedier/frp#2602]
### Describe the feature request

Currently only one token can be configured in `common` section inside the frps configuration file. 

Is possible to configure different  tokens for different clients? 

### Describe alternatives you've considered

Running multple frps instance

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by v20z** [comment]
Here is "frp server plugin to support multiple users for frp"
https://github.com/gofrp/fp-multiuser
