### ISSUE TITLE
[Bug] 当启用多用户时，stcp sudp xtcp代理均失效

### ISSUE THREAD

**Issue by yaott2020-666** [fatedier/frp#2607]
### Bug Description

A 端 Frpc  配置文件启用user时 即 user = user1 并配置 stcp(sudp/xtcp)  其 server_name = proxy_stcp
B 端 Frpc  配置文件启用user    user = user2 并配置stcp(sudp/xtcp)监听端时

无法连接 提示无法找到 user2.proxy_stcp  但是 服务端生成的是  user1.proxy_stcp

### frpc Version

0.37.0  (一直以来好像都是这样)

### frps Version

0.37.1  (一直以来好像都是这样)

### System Architecture

linux/amd64  linux/arm64   linux/mipsle

### Configurations

frps::
#############
[common]
bind_addr = 0.0.0.0
bind_port = 7000
bind_udp_port = 7001
kcp_bind_port = 7000
vhost_http_port = 81
dashboard_addr = 0.0.0.0
dashboard_port = 7500
log_level = info
log_max_days = 3
max_pool_count = 8
max_ports_per_client = 0
subdomain_host = ***.com
tcp_mux = true
disable_log_color = false
allow_ports = ******
#log_file = /var/log/frps.log
custom_404_page = ****/404.html
token = ********
#############

frpc stcp server::
#############
[common]
server_addr = *******
server_port = 7000
user = user1
token=${token}
log_file = /tmp/frpc.log
log_level = info
log_max_days = 3
pool_count = 0
tcp_mux = true
login_fail_exit = false
protocol = tcp
tls_enable = true
heartbeat_interval = 30
heartbeat_timeout = 90

[proxy_stcp]
type = sudp
sk = **********
local_ip = 127.0.0.1
local_port = 1923
#############

frpc stcp client::
#############
[common]
server_addr = *******
server_port = 7000
user = user2
token=${token}
log_file = /tmp/frpc.log
log_level = info
log_max_days = 3
pool_count = 0
tcp_mux = true
login_fail_exit = false
protocol = tcp
tls_enable = true
heartbeat_interval = 30
heartbeat_timeout = 90

[proxy_stcp_visitor]
type = sudp
role = visitor
server_name = proxy_stcp
sk = *********
bind_addr = 127.0.0.1
bind_port = 1923
#############

### Logs

frpc stcp client

[user2.proxy_stcp_visitor] newVisitorConn to frps error: start new visitor connection error: custom listener for [user2.proxy_stcp] doesn't exist, try to reconnect

frpc stcp server

[user1.proxy_stcp] start proxy success

### Steps to reproduce

上述步骤即可100%复现

### Affected area

- [ ] Docs
- [x] Installation
- [ ] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [x] Developer Infrastructure
- [x] Client Plugin
- [x] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingtianbaihua** [comment]
1. 不是一个 bug
2. 你对 user 的概念没有理解到位
3. 你的配置有不少问题，stcp 和 sudp 的 name 取名混乱，可以改下

我这里测试没问题。

**Comment by bingtianbaihua** [comment]
> 可以贴个配置看看吗，上面配置信息隐私问题改了些东西，但是形式是一致的

user2 -> user1
type = sudp  ->  type = stcp

试试。
