### ISSUE TITLE
ssh login, set allow host, refused

### ISSUE THREAD

**Issue by southfly** [fatedier/frp#2608]
### Describe the feature request

ssh 登录，设置hosts过滤后，被拒绝。

但是可以在服务端可以看到用户建立一个连接：
2021/10/08 11:10:17 [I] [proxy.go:179] [cf0c0b22ae977ada] [ssh] get a user connection [222.90.61.173:6363]

连接报错：
kex_exchange_identification: Connection closed by remote host

目标服务器和代理服务器都有设置。

### Describe alternatives you've considered

vim /etc/hosts.allow
```
sshd:192.168.132.:allow
sshd:222.90.61.173:allow
```
    
vim /etc/hosts.deny
```
sshd:ALL
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by southfly** [comment]
centos7<->centos7
frp_0.37.1_linux_amd64.tar.gz

**Comment by bingtianbaihua** [comment]
提供一些日志信息。
