### ISSUE TITLE
frp流量转发都经过服务器吗？

### ISSUE THREAD

**Issue by yc121** [fatedier/frp#261]
请问大神是不是所有转发流量都会过服务器？
开发计划中说，未来会支持 udp 打洞，提供两边内网机器直接通信。现在这个功能实现了吗？
如果没实现，请问现在有没有开源的udp打洞的解决方案？
谢谢！

**Comment by fatedier** [comment]
目前都经过服务器，udp 打洞的开发需要过段时间。

推荐可以试试这个项目 https://github.com/vzex/dog-tunnel

**Comment by seatrix** [comment]
经过试用，打洞很难成功的，成功率太低，现在光纤到户 ppoe的都是内网ip了，adsl的公网的都少的可怜

**Comment by wxyzh** [comment]
@seatrix 如果是电信的话，可以找客服要求分配外网ip
