### ISSUE TITLE
是否可以支持端对端加密

### ISSUE THREAD

**Issue by lsusu** [fatedier/frp#2612]
### Describe the feature request

stcp支持端到端认证连接，但数据针对服务器依旧是明文
是否能在stcp基础上增加端对端加密，服务器仅传输密文。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by lsusu** [comment]
sk应该只是客服端相互认证用的，但数据对服务端依旧是明文。
针对数据加密应该是客服端到客服端加密，这样服务器拿到的应该也是密文。
类似sk，双方提前添加一个密钥，密钥本地保存，客服端数据发送时加密，客服端接收时解密，这样服务器看到的都是密文。

**Comment by shui-dun** [comment]
请问是否开启useEncryption就可以实现端对端加密？
