### ISSUE TITLE
是否能够在配置中使用通配符

### ISSUE THREAD

**Issue by herui119110** [fatedier/frp#2615]
### Describe the feature request

#frpc配置
[web1]
type = http
local_ip = 127.0.0.1
local_port = 80
custom_domains =www.min1.com,www.min2.com,www.min3.com,www.min4.com,.....
#我希望能够通配所有的域名都指向我的80端口,通过类似于*.*.*的泛域名方式,否则我需要一条一条的写这样很麻烦,请问有通配的方法吗?

### Describe alternatives you've considered

custom_domains =www.min1.com,www.min2.com,www.min3.com,www.min4.com,.....

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by XieB** [comment]
`[web-local]
type = http
local_port = 8881
custom_domains = *.aa.com`
貌似和你的需求不同
