### ISSUE TITLE
frpc dashboard更新脚本显示成功，实际上无权限

### ISSUE THREAD

**Issue by qiujiangkun** [fatedier/frp#2619]
### Bug Description

我用过frpc的dashboard更新配置文件，显示成功，但是刷新后恢复原样。通过F12，得到
500 error:
write content to frpc config file error: open /etc/frp/frpc.ini: permission denied
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/33482468/137430799-dfea9a4a-561d-417b-8219-db98060082c5.png">

配置文件没权限是因为frpc的用户是nobody，我可以解决。希望能正确显示这个500错误

### frpc Version

0.37.1

### frps Version

0.37.1

### System Architecture

linux/amd64 

### Configurations

[common]
server_addr = somehost.com
server_port = 7000
admin_addr = 127.0.0.1
admin_port = 7400
admin_user = xxxx
admin_pwd = xxxx

[frpc-admin]
type = tcp
local_ip = 127.0.0.1
local_port = 7400
remote_port = 17400

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by yuhuazhu** [comment]
@qiujiangkun 
出现同样问题，修改配置提示成功，刷新后还是没变
看到你给的提示是没权限，试着手动给一个权限
`chmod o+w frpc.ini` 
然后就能更新了
