### ISSUE TITLE
frpc出现-ash: ./frpc: not found

### ISSUE THREAD

**Issue by fsyxhua** [fatedier/frp#262]
运行环境：
Openwrt x64环境
root@Gargoyle-X64\:~/frp# uname -a
Linux Gargoyle-X64 3.18.44 #17 SMP Wed Jan 25 15:37:49 CST 2017 x86_64 GNU/Linux

错误描述：
root@Gargoyle-X64\:~/frp# ./frpc
-ash: ./frpc: not found

--------------
2017-2-23 15:30更新
经过自己摸索，google，问题解决：
[root@localhost frp]# ldd frpc
	linux-vdso.so.1 =>  (0x00007ffc4cbbe000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1cefb59000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f1cef798000)
	/lib64/ld-linux-x86-64.so.2 (0x000055a96aed8000)
发现程序依赖了一下库，将这些库拷贝到Openwrt的/lib目录下，运行frpc没有问题！！！

**Comment by bingtianbaihua** [comment]
@fsyxhua  稍微描述清楚一点，没办法定位问题。  尴尬脸！！

**Comment by fatedier** [comment]
检查 frpc 路径是否正确，确认是否具有可执行权限。

**Comment by engineerlzk** [comment]
应该是没有给frpc可执行权限,shell，进入你的frpc安装目录执行
chmod +x frpc
就可以了

**Comment by fsyxhua** [comment]
@fatedier 就在当前目录下，所以执行./frpc的，确定有可执行权限

**Comment by fsyxhua** [comment]
@engineerlzk 如果没给可执行权限，会提示
-bash: ./frpc: 权限不够

**Comment by fsyxhua** [comment]
@bingtianbaihua  就是没法执行，明明有可执行权限，而且路径就在当前文件夹下，所以路径也没错，但是就是说not found，貌似以前在迅雷论坛发现Xware的软件在linux上也出现过这种问题的。

**Comment by engineerlzk** [comment]
第一，你用的frpc是针对哪个操作系统的（下载的那个程序包）？
第二，用winscp进入你的frpc目录截个图来看看
尽量多的提供一些辅助信息有望帮助你解决问题

**Comment by fatedier** [comment]
给你的系统提 bug~

**Comment by fsyxhua** [comment]
@fatedier 认为是系统的问题？
@engineerlzk  openwrt x64

**Comment by engineerlzk** [comment]
@fsyxhua 知道你用的是openwrt x64软路由系统，我问你的你在此下载的frpc是哪一个文件包？还有就是用winscp进入你frpc的安装目录截个完整的图片来看看

**Comment by fsyxhua** [comment]
@engineerlzk  frp_0.9.3_linux_amd64.tar.gz，不好截图的

**Comment by fsyxhua** [comment]
@fatedier @engineerlzk 应该是glibc的问题，问题解决了，详见楼顶更新内容，go编译出来的程序还需要C库，难道代码中有C？？？

**Comment by panjian-win** [comment]
请教各位：
   frp能在openwrt x86上运行过吗？ 自己编译固件还是？
   跪求 万分感谢！
