### ISSUE TITLE
Windows Server系统，当客户端被强制关闭之后，服务器端无法及时释放资源

### ISSUE THREAD

**Issue by xzbaijj** [fatedier/frp#2620]
### Bug Description

Windows Server系统，当客户端被强制关闭之后，服务器端无法及时释放资源，必须在CMD窗口上，按一下回车键，或者关闭Server端，重新启动。设置了心跳延迟时间，不知道是否会正常生效。当服务器端无法释放资源时，客户端无法重新建立连接。建议修改客户端的连接策略，如果新客户端建立连接，服务端判断是重复客户端，则释放原有资源。

### frpc Version

0.37.1

### frps Version

0.37.1

### System Architecture

linux/amd64，windows/amd64

### Configurations

[common]
bind_port = 7000
vhost_http_port = 80
authentication_timeout = 15

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingtianbaihua** [comment]
frpc 和 frps 的配置多提供一些。 敏感信息可以抹掉。
