### ISSUE TITLE
Why FRP is called FRP

### ISSUE THREAD

**Issue by martibook** [fatedier/frp#2622]
### Describe the feature request

Out of curiosity, does "RP" means Reverse Proxy? Then what about "F"?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
> A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet.

From repo description.
