### ISSUE TITLE
[Feature Request] Pass through the tcp tunnel to pass in the real visitor IP?

### ISSUE THREAD

**Issue by gesangtome** [fatedier/frp#2623]
### Describe the feature request

Is it possible to add a flags to let frps send the visitor's real IP to the frpc client, and then the client's frpc will resolve and replace the visitor's IP address in the tcp packet?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
frp works on 4 layer network now. It won't change IP packages.
