### ISSUE TITLE
[Feature Request] 能否做到xtcp失败的时候，自动回落到stcp？

### ISSUE THREAD

**Issue by aa51513** [fatedier/frp#2624]
### Describe the feature request

由于frpc的网络情况不确定，有时候xtcp能够成功，有时候xtcp无法成功；
为了保证实际使用体验，能否做到xtcp失败的时候，自动回落到stcp？

### Describe alternatives you've considered

xtcp设置里，增加一项配置项目，fallback2stcp = ture/false

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Bellegar** [comment]
This would be a great addition to xtcp to make it work like the ICE protocol suggests (if p2p STUN connection fails, then relay TURN is used)

**Comment by Bellegar** [comment]
Visited service in xtcp fallback mode will just open both xtcp and stcp services at frpc start.
Visitor will try addition connection using stcp after xtcp connection timeout (it needs to use same local bind port, those simple adding secont visitor service will be incorrect).
It doesn't seem too hard to implement such a coolest thing.
But my GO knowlege is near the 0 for trying to make it works...

**Comment by fatedier** [comment]
We recently carried out a major overhaul of xtcp, which may significantly improve the success rate of penetration. This change will be released in the next few days.

But it will not be compatible with previous versions.

The function of falling back to STCP is planned and will be developed after this major change.
