### ISSUE TITLE
[Feature Request] stcp与sudp是否考虑会增加负载均衡(group)支持？

### ISSUE THREAD

**Issue by aa51513** [fatedier/frp#2625]
### Describe the feature request

目前的版本负载均衡(group)功能，只支持tcp与http以及tcpmux

如果stcp与sudp无法做到支持负载均衡(group)，那么主备（2个节点，一个主节点，一个从节点，只有一个保持工作状态）是否能够考虑？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by aa51513** [comment]
如果stcp与sudp无法做到支持负载均衡(group)，那么主备（2个节点，一个主节点，一个从节点，只有一个保持工作状态）是否能够考虑？

**Comment by fatedier** [comment]
stcp 和 sudp 用于点对点通信，目前没有计划支持负载均衡。
