### ISSUE TITLE
是否支持类似ss5一样支持多个账号及日志

### ISSUE THREAD

**Issue by maojianyou** [fatedier/frp#2636]
### Describe the feature request

目前ss5只支持一个账号一个密码，对比s5-3.8.9-2.tar.gz,可以支持多行写账号密码，后续是否可以支持

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by caicaicai** [comment]
很简单，你自己改下插件代码，pk/plugin/client/socks5.go  func NewSocks5Plugin, 这个函数里只塞了一对用户名密码到map里面，你想要多少用户，就往这个map里面塞就行了。

**Comment by caicaicai** [comment]
![image](https://user-images.githubusercontent.com/3754009/141038196-7f4fa36c-72d0-4159-b1f4-5a8087f20d34.png)

刚才随手写了个，没测试不知道能不能用。大概意思是读本地一个用户的json文件，解析里面的map，生成用户字典作为验证用的数据。 我不会写go代码，代码是我自己临时查的go语法写的，可能有很多问题，只是提供一个思路。

**Comment by maojianyou** [comment]
这个可以集成到frp程序里面不？ 我们目前用ss5-3.8.9-8.tar.gz这种代理工具，支持带用户的，用来代理挺好用的，但不支持内网穿透，如果能集成到frp里面是非常强大的亮点，相比nps就多一个功能



***@***.***
 
发件人： 蔡忠振
发送时间： 2021-11-10 10:27
收件人： fatedier/frp
抄送： maojianyou; Author
主题： Re: [fatedier/frp] 是否支持类似ss5一样支持多个账号及日志 (Issue #2636)
刚才随手写了个，没测试不知道能不能用。大概意思是读本地一个用户的json文件，解析里面的map，生成用户字典作为验证用的数据。 我不会写go代码，代码是我自己临时查的go语法写的，可能有很多问题，只是提供一个思路。
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by maojianyou** [comment]
这个可以发布frpc版本出来不？



***@***.***
 
发件人： ***@***.***
发送时间： 2021-11-11 10:29
收件人： fatedier/frp; fatedier/frp
抄送： Author
主题： Re: Re: [fatedier/frp] 是否支持类似ss5一样支持多个账号及日志 (Issue #2636)
这个可以集成到frp程序里面不？ 我们目前用ss5-3.8.9-8.tar.gz这种代理工具，支持带用户的，用来代理挺好用的，但不支持内网穿透，如果能集成到frp里面是非常强大的亮点，相比nps就多一个功能



***@***.***
 
发件人： 蔡忠振
发送时间： 2021-11-10 10:27
收件人： fatedier/frp
抄送： maojianyou; Author
主题： Re: [fatedier/frp] 是否支持类似ss5一样支持多个账号及日志 (Issue #2636)
刚才随手写了个，没测试不知道能不能用。大概意思是读本地一个用户的json文件，解析里面的map，生成用户字典作为验证用的数据。 我不会写go代码，代码是我自己临时查的go语法写的，可能有很多问题，只是提供一个思路。
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
