### ISSUE TITLE
runtime: kernel page size (32768) is larger than runtime page size (4096)

### ISSUE THREAD

**Issue by Ourobotos** [fatedier/frp#264]
在西数的Mycloud NAS中（CPU：ARMv7）运行 frp_0.9.3_linux_arm.tar.gz的frpc客户端，出现runtime: kernel page size (32768) is larger than runtime page size (4096)，网上查了下貌似是go语言的bug ：https://github.com/ncw/rclone/issues/426 Frp能修复否？

**Comment by fatedier** [comment]
之后会用 go1.8 重新编译下，替换掉现在 go1.7 编译的版本。

**Comment by hansnow** [comment]
same question

**Comment by fatedier** [comment]
v0.10.0 版本开始已经采用 go1.8.1 编译。
