### ISSUE TITLE
客户端frpc频繁发送连接到frps

### ISSUE THREAD

**Issue by QINLIMIN** [fatedier/frp#2640]
### Bug Description

<img width="821" alt="image" src="https://user-images.githubusercontent.com/8186888/139432823-49a6b821-dcb2-4982-880f-efc3a4e6e27b.png">

### frpc Version

frp_0.34.1

### frps Version

frp_0.29.0

### System Architecture

linux/amd64

### Configurations

frps.ini 配置：
[common]
bind_port = 7000
# enable custom ddns for accessing the web server in local pc
vhost_http_port = 8080

# subdomain_host
subdomain_host = light.com
#subdomain_host = streetlight.top

# enable dashboard
dashboard_port = 7500
# set username and password
dashboard_user = admin
dashboard_pwd = password

fprc.ini 配置：
[common]
server_addr = 139.105.180.16
server_port = 7000

[ssh6209]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6209

[web6209]
type = http
local_port = 8000
subdomain = gtw6209

### Logs

2021/10/29 20:04:50 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:04:51 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:04:53 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:04:53 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:04:53 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:04:56 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:04:57 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:04:58 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:01 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:05 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:09 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:13 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:17 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:18 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:19 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:22 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:24 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:25 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:27 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:27 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:29 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:31 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:32 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:33 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:33 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:34 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:35 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:38 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:38 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:40 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:41 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:42 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:48 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:50 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:52 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:53 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:55 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:55 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:56 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:59 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:05:59 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:06:00 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:06:00 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:06:01 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:06:02 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:06:03 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:06:03 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:06:04 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:06:07 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:06:08 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:06:09 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
2021/10/29 20:06:10 [I] [proxy.go:84] [8e51476000c11bb3] [ssh6221] get a new work connection: [112.96.236.240:23327]
......

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by yaott2020-666** [comment]
建议升级frps版本

**Comment by bingtianbaihua** [comment]
建议升级，并且 client server 保持一致的版本。

**Comment by fatedier** [comment]
有请求就需要建立连接，如果不希望被请求，不要随意把 ssh 暴露到公网

**Comment by QINLIMIN** [comment]
我先升级版本试试‘
