### ISSUE TITLE
Timed out while waiting for handshake Network is disconnected

### ISSUE THREAD

**Issue by 523039704** [fatedier/frp#2644]
### Bug Description

Timed out while waiting for handshake
Network is disconnected

### frpc Version

0.35

### frps Version

0.35

### System Architecture

linux/amd64,

### Configurations

Timed out while waiting for handshake
Network is disconnected

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by bingtianbaihua** [comment]
Please show some logs and your configs.
