### ISSUE TITLE
使用其他编程语言

### ISSUE THREAD

**Issue by OldGodShen** [fatedier/frp#2646]
### Describe the feature request

是否有办法不使用go语言，而是用C# vb.net来构建frpc

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingtianbaihua** [comment]
你可以尝试用你要的语言来重写下。
