### ISSUE TITLE
https://gofrp.org/docs 网站访问不了

### ISSUE THREAD

**Issue by quliting** [fatedier/frp#2650]
### Bug Description

https://gofrp.org/docs 网站访问不了

### frpc Version

docker

### frps Version

docker

### System Architecture

docker

### Configurations

docker

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingtianbaihua** [comment]
我这里可以。 应该不是网站本身问题。

**Comment by quliting** [comment]
嗯，公司可以，家里不可以；谢谢
