### ISSUE TITLE
Can our local computer use frp join into the aliyuncs's k8s master

### ISSUE THREAD

**Issue by liyinxin** [fatedier/frp#2651]
### Describe the feature request

I want use my aliyuncs to deploy a k8s cluster, and let my local computer join into the aliyuncs's k8s. So I want use the frp to　accomplish it.

### Describe alternatives you've considered

nothing

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
It's a very complicated issue. Try some projects like https://github.com/openyurtio/openyurt

**Comment by liyinxin** [comment]
@fatedier  thanks, I will try it
