### ISSUE TITLE
压力测试

### ISSUE THREAD

**Issue by linxingchao** [fatedier/frp#2652]
### Describe the feature request

怎么进行压力测试

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingtianbaihua** [comment]
？
