### ISSUE TITLE
windows_386在32位xp系统上不能运行

### ISSUE THREAD

**Issue by BG8HVH** [fatedier/frp#2654]
### Bug Description

frp_0.38.0_windows_386.zip和前面0.26等版本都不能在32位windows xp系统上运行，提示不是有效的win32应用程序

### frpc Version

0.38

### frps Version

0.38

### System Architecture

windows

### Configurations

num

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by thefantas** [comment]
![imagen](https://user-images.githubusercontent.com/2816602/141646990-05b92ffa-17db-439a-8818-0815e5686c4a.png)
I also have this problem, it only occurs with Windows 386.

**Comment by thefantas** [comment]
Does not work from version v0.29.1.
Last version OK: v0.29.0

**Comment by thefantas** [comment]
The problem is not frp's, but Golang's, since version 1.12 does not support Windows XP. :/

**Comment by BG8HVH** [comment]
> The problem is not frp's, but Golang's, since version 1.12 does not support Windows XP. :/

yes. I don't know if it will be repaired

**Comment by BG8HVH** [comment]
> The problem is not frp's, but Golang's, since version 1.12 does not support Windows XP. :/

Yes, I don’t know if it will be fixed
