### ISSUE TITLE
frps启动后只监听了tcp6端口，导致无法启动启动frpc

### ISSUE THREAD

**Issue by Hassanggg** [fatedier/frp#2657]
### Bug Description

# ./frps -c ./frps.ini &
[1] 2493
2021/11/14 16:08:56 [I] [service.go:190] frps tcp listen on 0.0.0.0:7000
2021/11/14 16:08:56 [I] [root.go:215] start frps success

# netstat -antlp |grep 7000
tcp6       0      0 :::7000                 :::*                    LISTEN      2493/./frps     

frps启动后只监听了tcp6端口，导致起frpc的时候无法连接公网的7000端口，frpc启动失败

### frpc Version

0.34.3

### frps Version

0.34.3

### System Architecture

linux/amd64

### Configurations

# cat frpc.ini 
[common]
server_addr = X.X.X.X
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

### Logs

# ./frpc -c ./frpc.ini 
2021/11/14 16:11:12 [W] [service.go:102] login to server failed: dial tcp X.X.X.X:7000: connect: connection refused
dial tcp 218.89.224.37:7000: connect: connection refused

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
即使只监听了 tcp6，但 IPv4 是可以连接的，检查防火墙
