### ISSUE TITLE
[Feature Request] 直接转发本地端口

### ISSUE THREAD

**Issue by jerry-wolf** [fatedier/frp#2660]
### Describe the feature request

比如 a.example.com 在 frps 所在的服务器上，而 b.example.com 由通过 frpc 连接到 frps 然后在 frps 所在的服务器上提供服务，a.example.com 可以直接由 frps 转发。

### Describe alternatives you've considered

目前可以在 frps 所在的服务器上安装 frpc 并连接到当前服务器上的 frps 实现，只是它产生了额外的开销。

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingtianbaihua** [comment]
听下来感觉你这个场景更适合用 NGINX ？

**Comment by jerry-wolf** [comment]
如果仅仅是根据 Host 头或者 SNI 分流，那 Nginx 确实感觉更合适，但是还有部分名称还是需要转发到远程啊！
