### ISSUE TITLE
frp的所在的客户端的局域网的中的其他服务器进行代理可以吗 ?

### ISSUE THREAD

**Issue by Lingchen218** [fatedier/frp#2661]
### Describe the feature request

frpc的客户端的电脑,输入局域网的其他电脑的IP地址,进行 内网穿透可以吗  ?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by bingtianbaihua** [comment]
网络通就行了。。 可以。

**Comment by Lingchen218** [comment]
好的，谢谢

**Comment by Lingchen218** [comment]
你好！主人有事！主人收到信息会第一时间回复你的

**Comment by Lingchen218** [comment]
你好！主人有事！主人收到信息会第一时间回复你的
