### ISSUE TITLE
[Feature Request] TCP Port Multiplexing using TLS SNI

### ISSUE THREAD

**Issue by rucciva** [fatedier/frp#2662]
### Describe the feature request

For forwarding TLS trafic to one of multiple connected service based on the domain name on the SNI without doing TLS termination on frps.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Just use https proxy.

**Comment by rucciva** [comment]
> Just use https proxy.

Yes, that will work, but it will require https termination in the remote server. 

If frps could multiplex based on SNI, It could helps some users that have high concerns for privacy while at the same time helps in saving some bucks by avoiding to need to buy additional Public IP if they choose to for example use port 443 for all of their service which might be deployed in more than one unexposed private machine.

**Comment by fatedier** [comment]
https proxy in frp means sni proxy. It will only read servername and passthrough traffic to your client.

**Comment by rucciva** [comment]
oh you mean `vhost_https_port` ? i was thinking about deploying https proxy in front of frps.

let me check first

**Comment by rucciva** [comment]
oh by the way, how do you specify multiple domains in `custom_domains` ?  is it comma separated?

**Comment by fatedier** [comment]
> oh by the way, how do you specify multiple domains in `custom_domains` ? is it comma separated?

Yes.

**Comment by rucciva** [comment]
yup, its working. thank you very much
