### ISSUE TITLE
这个可以出一个 具体使用示例吗？

### ISSUE THREAD

**Issue by Lingchen218** [fatedier/frp#2663]
### Describe the feature request

proxy_protocol_version 
关于这个使用

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by Lingchen218** [comment]
我用这个，之后就无法连接上了

**Comment by xqzr** [comment]
需要本地的服务配合
https://gofrp.org/docs/features/common/realip/#proxy-protocol

**Comment by Lingchen218** [comment]
我本地服务，是这样配置的，配置完就 无法使用这个服务了，就链接不上了

**Comment by xqzr** [comment]
> 我本地服务，是这样配置的，配置完就 无法使用这个服务了，就链接不上了

“这样”是怎么样的呢？

**Comment by Lingchen218** [comment]
[ssh]
type = tcp
local_port = 22
remote_port = 6000

# 目前支持 v1 和 v2 两个版本的 proxy protocol 协议。
proxy_protocol_version = v2

  我是这样配置的

**Comment by Lingchen218** [comment]
这个功能只支持HTTP吗？ssh支持显示真实IP吗？

**Comment by zhezhe168** [comment]
> 需要本地的服务配合 https://gofrp.org/docs/features/common/realip/#proxy-protocol

我的情况和楼上一样，开启这个后直接404报错了无法访问web

**Comment by zhezhe168** [comment]
主人回来了么
