### ISSUE TITLE
windows客户端

### ISSUE THREAD

**Issue by mofei828** [fatedier/frp#2666]
### Describe the feature request

你好，我在windows上部署客户端，无法启动应用。提示连接失败，是什么问题啊，windows可以ping通服务器。
c:\frp>frpc -c frpc.ini
2021/11/19 12:21:25 [W] [service.go:104] login to server failed: EOF
EOF

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [x] Others

**Comment by MackeyLao** [comment]
先尝试在本机上同时启动frps, frpc
frpc指向本地frps进行测试，
看看有没有问题，之后再测试外部的frps

**Comment by zyu** [comment]
[service.go:105] login to server failed: EOF
