### ISSUE TITLE
TCP转发效果比较差

### ISSUE THREAD

**Issue by dsf848dfgvs** [fatedier/frp#267]
经过2个月的使用,感觉Frp tcp转发效果很差,客户端经常掉线和大量的重复,用了连接池后,掉线的情况更严重,
希望作者以后能在tcp转发方面做做优化

**Comment by fatedier** [comment]
可以提供一下这个版本的性能测试结果，下个版本我们再来对比一下。

掉线主要取决于网络环境。光说结果没有用， 如果有具体的场景和使用过程，才有优化的可能。

**Comment by billy74** [comment]
客户端掉线会自动连接的啊- -
以前我用来NAS备份，大流量传输也会掉线，但是终究是服务器带宽的问题，换了服务器就好了 满速啊 H
