### ISSUE TITLE
[Feature Request]  Stop the client or server gracefully

### ISSUE THREAD

**Issue by hinupurthakur** [fatedier/frp#2670]
### Describe the feature request

Currently we don't have a command that can stop the frp client (or server) gracefully on a machine

### Describe alternatives you've considered

we should have a command like `frpc stop` (or `frps stop`)  to stop the active connections gracefully.

Please let me know if this is something we would like to have as a feature, I can help to contribute as well.

Thanks

### Affected area

- [X] Docs
- [x] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
I'm not sure if it's necessary.

Can you describe more about your use case and how to decide when frp service can stop?

Lots of people use frp as port forwarder and their connections will keep alive for a long time.

**Comment by hinupurthakur** [comment]
@fatedier Thanks for the response. I am using it with the application for the http proxy. Once I close the application, I want the frpc to stop (not the server, in my case). Currently I am doing it by the process ID but if we can have an option like `frpc stop` but only if this use case is not too specific for my use.
Thank You!

**Comment by fatedier** [comment]
I think it's ok to support graceful shudown only on frpc.

We can add a new api like `/api/stop` and `frpc stop --grace-period=10` will call this api. 

PRs on this feature are welcome.

**Comment by hinupurthakur** [comment]
If nobody have yet taken this issue up, I will be happy to work on it.
