### ISSUE TITLE
安卓手机用户

### ISSUE THREAD

**Issue by pc18189** [fatedier/frp#2671]
### Describe the feature request

有高手能开发frp安卓手机和苹果手机产品？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [x] Extensions
- [ ] Others

**Comment by pc18189** [comment]
补充上面的问题，就是把手机做成4G代理的样子。从而可以远程用手机4G网络上网。

**Comment by NewPersonNew** [comment]
你在android手机上部署了吗，我看有arm架构的frpc包

**Comment by pc18189** [comment]
> 你在android手机上安装了，我看有没有arm架构的frpc包

我没有看到，真的有手机使用安装包吗？

**Comment by NewPersonNew** [comment]
![image](https://user-images.githubusercontent.com/35290404/143169928-007747ff-3bb9-4c8c-931e-7583d3cbfa8b.png)
我尝试在我手机用adb-shell安装了arm架构的frpc，配置tcp链接做http代理，tcp链接成功了，不过发送http请求却报错了，我也在寻找可用的方案。
![image](https://user-images.githubusercontent.com/35290404/143170092-73210423-bdc5-43c5-a163-6dcf56140a04.png)

**Comment by aa51513** [comment]
> 补充上面的问题，就是把手机做成4G代理的样子。从而可以远程用手机4G网络上网。

只是通过手机4G出口上网的话，这个再简单不过了

**Comment by yaotthaha** [comment]
可以试试termux

**Comment by huazinet** [comment]
> termux你测试过吗，我这边用好像不行，启动服务只要ctrl+c面板上就会离线，而且访问提示被拒绝，不知道哪里的问题

**Comment by yaotthaha** [comment]
ctrl+c 都关闭frp了当然离线，用nohup后台保持就行

**Comment by pc18189** [comment]
小白，不会整。有没有高手搞个APP直接生成；地址，端口，用户名，密码

yaotthaha ***@***.***> 于2021年12月9日周四 14:28写道：

**Comment by Yang161941** [comment]
如果用termux的话可以用runsv/sv套件解决，今天也是刚解决了类似的问题

**Comment by pc18189** [comment]
> > 补充上面的问题，就是把手机变成4G代理的样子。可以远程用手机4G网络上网。
> 
> 只是通过手机4G出口上网的话，这个再简单不过了

要求是在完全不相同的网络上远程使用，怎么做？

**Comment by pc18189** [comment]
> 可以使用termux

在手机上能用吗？请说明一下怎么使用。

**Comment by pc18189** [comment]
> 如果用termux的话可以用runsv/sv套件解决，今天也是刚解决了类似的问题

我是小白，请高手指教

**Comment by pc18189** [comment]
![image](https://user-images.githubusercontent.com/94864701/146631904-df363353-ca64-4f56-a55b-28da758dea4a.png)

**Comment by pc18189** [comment]
![image](https://user-images.githubusercontent.com/94864701/146631980-2689286c-c842-4ecb-9849-06acae625b5d.png)

**Comment by pc18189** [comment]
我上传了两张图，都是4G场景下的

**Comment by pc18189** [comment]
![Screenshot_20211218-164925](https://user-images.githubusercontent.com/94864701/146636565-3aba49c3-939d-44f8-a710-f9cc6e1ebbd1.png)

**Comment by pc18189** [comment]
![Screenshot_20211218-173807](https://user-images.githubusercontent.com/94864701/146636684-a77b67cb-f199-49e0-b61b-9583d3316dd5.png)

**Comment by pc18189** [comment]
![IMG_20211218_174437](https://user-images.githubusercontent.com/94864701/146636740-1c8386c5-92e9-44d9-b55a-317dedcc1376.jpg)

**Comment by pc18189** [comment]
上传三张图是在手机4G场景的使用，有没有高手可以写FRP的手机APP

**Comment by pc18189** [comment]
我之前没有把问题说清楚，下面发的链接就是我想说的问题。frp能做到吗？


Yang ***@***.***>于2021年12月12日 周日21:39写道：

**Comment by pc18189** [comment]
https://meta.appinn.net/t/topic/9616

https://github.com/xapanyun/4gproxy

生王 ***@***.***>于2021年12月25日 周六18:24写道：

**Comment by pc18189** [comment]
> > 如果用termux的话可以用runsv/sv套件解决，今天也是刚解决了类似的问题
> 
> 我是小白，请高手指教

有没有视频教程？

**Comment by pc18189** [comment]
> 有没有视频教程？

**Comment by pc18189** [comment]
> 可以使用termux

有没有视频教程？
