### ISSUE TITLE
CentOS8 systemd start problem 

### ISSUE THREAD

**Issue by Handonghuang** [fatedier/frp#2673]
### Bug Description

fprc systemd start error with code=exited, status=203/EXEC

### frpc Version

0.38.0

### frps Version

0.38.0

### System Architecture

linux/amd64

### Configurations

frpc.ini
[common]
server_addr = xxxxxxxxx
server_port = 7000
token =xxxxxx

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 48100

frpc.service
#!/bin/bash
[Unit]
Description=Frp Client Service
After=network.target

[Service]
Type=simple
User=root
Restart=on-failure
RestartSec=5s
ExecStart=/root/remote/fpc/frp_0.38.0_linux_amd64/frpc -c /root/remote/fpc/frp_0.38.0_linux_amd64/frpc.ini
ExecReload=/root/remote/fpc/frp_0.38.0_linux_amd64/frpc reload -c /root/remote/fpc/frp_0.38.0_linux_amd64/frpc.ini
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target

### Logs

[root@localhost system]# systemctl status frpc
● frpc.service - Frp Client Service
   Loaded: loaded (/usr/lib/systemd/system/frpc.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2021-11-23 09:12:42 EST; 1s ago
  Process: 23125 ExecStart=/root/remote/fpc/frp_0.38.0_linux_amd64/frpc -c /root/remote/fpc/frp_0.38.0_linux_amd64/frpc.ini (code=exited, status=203/EXEC)
 Main PID: 23125 (code=exited, status=203/EXEC)

### Steps to reproduce

1. add chmod  777 to 3 different files   frpc  frpc.ini  frpc.service
2. add  #!/bin/bash for fprc.service
3. works for frps but for frpc on CentoOS8, didn't work
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by JIA-Jimmy** [comment]
disable SELinux

**Comment by wwwadx** [comment]
> disable SELinux

Solved, thank you
