### ISSUE TITLE
容器中 bridge模式，UDP转发无效

### ISSUE THREAD

**Issue by lynzhai** [fatedier/frp#2678]
### Bug Description

frps 部署在docker中时，网络使用host模式，udp转发才能生效，使用bridge模式，udp转发无效，TCP正常

### frpc Version

0.38.1

### frps Version

0.38.1

### System Architecture

linux docker

### Configurations

无

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by kfcceo** [comment]
本来就得用host模式吧

**Comment by lynzhai** [comment]
> 本来就得用host模式吧

必须得用host模式工作吗，不能再bridge网络中吗
