### ISSUE TITLE
custom_domains那里可不可以设置多个域名？

### ISSUE THREAD

**Issue by jearol** [fatedier/frp#268]
如题，不知道是否支持，如果支持应用什么格式？

**Comment by bingtianbaihua** [comment]
@jearol  可以，用逗号分隔，配置文件里的例子和注释已经写的很清楚了。。。

**Comment by engineerlzk** [comment]
可以的，像这样写即ok：
custom_domains = web01.yourdomain.com,web02.yourdomain.com,web03.yourdomain.com

**Comment by jearol** [comment]
谢谢指点

**Comment by bingzhangdai** [comment]
custom_domains可以是通配符吗？比如`custom_domains = *.yourdomain.com`
