### ISSUE TITLE
STCP模式下，visitor与frps之间的流量能被加密吗？

### ISSUE THREAD

**Issue by pcform** [fatedier/frp#2680]
### Describe the feature request

visitor配置文件中的use_encryption、use_compression项目会生效吗？
因为STCP模式下frps的dashboard中看不到visitors明细，故有此疑问。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingtianbaihua** [comment]
会生效，可以抓个包试试就清楚了。

**Comment by pcform** [comment]
> 

已经抓包证实有效，谢谢~

**Comment by pcform** [comment]
> 会生效，可以抓个包试试就清楚了。

已经抓包证实有效，谢谢~
