### ISSUE TITLE
Something wrong with frpc . when i type "./frpc -c ./frpc.ini " ,  log shows that "2021/11/28 04:00:04 [W] [service.go:104] login to server failed: session shutdown"

### ISSUE THREAD

**Issue by sesameman** [fatedier/frp#2681]
### frpc Version

0.38.0

### frps Version

0.38.0

### System Architecture

linux/amd64

### Configurations

[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 7000
tls_enable = true
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000
~                              

### Logs

2021/11/28 04:00:04 [W] [service.go:104] login to server failed: session shutdown

### Steps to reproduce

1. open frps
2. open frpc
3. log shows
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingtianbaihua** [comment]
可能是防火墙吧。

**Comment by simonchen** [comment]
I got same issue when upgrading to latest version, but old version 0.45 is ok

**Comment by Ekeky** [comment]
O que é isto?
Que está caindo no meu imail.


Em ter., 10 de out. de 2023 12:39, xychenxy ***@***.***>
escreveu:

**Comment by anselanza** [comment]
This is driving me crazy. I used to use v0.49 and everything was fine, but now I cannot connect any clients even though nothing is changed (and I don't use TLS)

**Comment by anselanza** [comment]
Is it a problem to run an older version of FRPS (e.g. 0.49) with a newer client (0.52+) perhaps?
