### ISSUE TITLE
[Feature Request] 可不可不用域名而是端口实现多web转发

### ISSUE THREAD

**Issue by wsjackys** [fatedier/frp#2683]
### Describe the feature request

因为国内域名需要备案才能绑定域名
我因为工作需要需要把内网的网站映射出来
有两个服务器对应两个网站
然后可不可以像ssh映射一样，使用IP地址和端口进行多web映射，而不是通过不同域名区分进行映射

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
可以，就像 ssh 一样配置。
