### ISSUE TITLE
如何快速停止服务？

### ISSUE THREAD

**Issue by wenxiayili** [fatedier/frp#2686]
### Describe the feature request

请问下作者，有没有相关的命令快速重启哈？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by reggiepy** [comment]
systemctl 管理服务不就行了？
