### ISSUE TITLE
[Question] TLS support

### ISSUE THREAD

**Issue by hons82** [fatedier/frp#2687]
### Describe the feature request

I'm currently using the `use_encryption` feature, but I'd like to use TLS. What I'd like to have is a self signed certificate on the client and potentially on the server as well. 

Do I need then a certificate authority? 
Does it need to be the same CA on the server and on all the clients?

### Describe alternatives you've considered

Remain on `use_encryption`

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Docs here may help you https://github.com/fatedier/frp#tls

**Comment by hons82** [comment]
Sure, but there it just says certificate.key, certificate.crt and ca.crt on both server and client, but do they need to be the same on both sides?
Would it be possible to run a self signed without ca?

**Comment by fatedier** [comment]
Can you just try what's you want?

**Comment by hons82** [comment]
That seems to work well. I did use the following to create the certificates
```
$ openssl req -x509 -nodes -newkey rsa:2048 -sha256 -keyout client.key -out client.crt
$ openssl req -x509 -nodes -newkey rsa:2048 -sha256 -keyout server.key -out server.crt

```
and used them on the server/client respectively. 
```
tls_enable = true
tls_cert_file = ./client.crt
tls_key_file = ./client.key
```
Without CA.
