### ISSUE TITLE
frpc static_file plugin cannot work in windows

### ISSUE THREAD

**Issue by MackeyLao** [fatedier/frp#2689]
### Bug Description

no mattar how I can set the "plugin_local_path", 
I only got follow error after input user and pw:
404 page not found

The "plugin_local_path" i had tried inlcude windows style and linux style:
c:\Temp
/c/Temp
/c
All cannot work.

this plugin can work in Linux client environment.

Question:
 How can I set the "plugin_local_path" in Windows?

### frpc Version

0.38.0

### frps Version

0.38.0

### System Architecture

Server: Linux Centos7.9/amd64, Client: windows 10/amd64

### Configurations

[common]
server_addr = x.x.x.x
server_port = 7000

[plugin_static_file1]
type = tcp
remote_port = 7501
plugin = static_file
plugin_local_path = /c
plugin_strip_prefix = static
plugin_http_user = abc
plugin_http_passwd = abc

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by MackeyLao** [comment]
I found out the solution myself and paste here for other reference.

if disable this line as below, I can accept the frpc folder in browser.
#plugin_local_path = /c/Temp

Then try to set:
plugin_local_path = ../
the folder is frpc folder's father folder.
That means the "plugin_local_path" in windows is using relative path.
e.g.: frpc's folder is C:\Temp\frp
then "plugin_local_path = ../" will set the path to "C:\Temp".

**Comment by acse-bp221** [comment]
Hi, I tried your method and I can indeed access C:\Temp, but this method can only share the disk where frpc is located. If I want to access D:\Temp, how should I fill in the path?

**Comment by avin** [comment]
use path like this `plugin_local_path = c:\\tmp\\222222`
