### ISSUE TITLE
不需要token就可以连接、端口错误

### ISSUE THREAD

**Issue by CatalpaCute** [fatedier/frp#2690]
### Bug Description

frps/frpc均在Windows主机上，版本v0.38.0
尝试了v0.38.0、v0.37.1、v0.36.1等版本，frpc皆是不需要输入frps.ini中的token即可链接，输入了会报错
frps.ini中bind_port改为8000后重启frps没有变化
先是上月25日连了的两台Windows电脑均中勒索病毒，frps找到了个俄罗斯的IP
昨天又见到了几个荷兰ip的连上了..
我换了一台服务器继续尝试，仍有问题，印象中linux(ubuntu/amd64)使用[这个安装脚本](https://github.com/stilleshan/frpc)是没有问题的
![20211203202013](https://user-images.githubusercontent.com/78294083/144601781-35e2f66c-aac0-4b17-8717-19acaf08bd61.png)
![20211203202108](https://user-images.githubusercontent.com/78294083/144601792-8c3d09b8-b4b8-447d-8ffa-87f6ff2289b5.png)
![QQ图片20211203202037](https://user-images.githubusercontent.com/78294083/144601798-2bae1f1c-6c06-4fdf-8d5d-0d36d8aaa7f5.png)
.

### frpc Version

v0.38.0

### frps Version

v0.38.0

### System Architecture

Windows/amd64

### Configurations

frps:
[common]
bind_port = 7000
dashboard_port = 7500
token = 79x983*
dashboard_user = admin
dashboard_pwd = admin
vhost_http_port = 10080
vhost_https_port = 10443

frpc:
[common]
server_addr = domain
server_port = 7000

[bedrock]
type = udp
local_ip = 127.0.0.1
local_port = 6960
remote_port = 6960

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by lizard1998myx** [comment]
我也有这个问题，另外在服务器端启用了TLS，客户端不启用就能连

**Comment by lizard1998myx** [comment]
我好像知道为什么了，直接运行frps的话是使用缺省配置的，token等都是默认的，需要“frps -c frps.ini”手动选择配置文件才可以

**Comment by CatalpaCute** [comment]
> 我好像知道为什么了，直接运行frps的话是使用缺省配置的，token等都是默认的，需要“frps -c frps.ini”手动选择配置文件才可以

我这边似乎也不行，之前试过
