### ISSUE TITLE
直接在release下载的版本都提示有病毒,然后我自己重新编译后发现竟然不会提示有毒?

### ISSUE THREAD

**Issue by bkkkd** [fatedier/frp#2697]
### Bug Description

在https://github.com/fatedier/frp/releases 里下载了多个版本,都被360提示 frpc 有病毒,然后自动删除.
然后我尝试自己编译,发现是没有病毒提示.
是否打包的环境被植入病毒?

### frpc Version

v0.38.0 v0.37.1 v0.37.0 v0.36.2

### frps Version

v0.38.0 v0.37.1 v0.37.0 v0.36.2

### System Architecture

windows/amd64

### Configurations

未配置

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [x] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by woshiniming007** [comment]
这个我试过，明天你再用360扫一次就报毒了，他应该是后台慢慢离线分析

**Comment by cresentboy** [comment]
说实话，360这种东西，关了就好，没什么影响。

**Comment by jdua3546** [comment]
0.38.0版本 上传腾讯云服务器，也报有木马

**Comment by bkkkd** [comment]
> 这个我试过，明天你再用360扫一次就报毒了，他应该是后台慢慢离线分析

测试过没有再报.

**Comment by bkkkd** [comment]
> 0.38.0版本 上传腾讯云服务器，也报有木马

之前linux下的0.36.2版本被阿里提示过,后来删除了.

**Comment by bkkkd** [comment]
> 说实话，360这种东西，关了就好，没什么影响。

虽然360是个大流氓,但还是能控制大部分的流氓.不会太乱.

**Comment by Nriver** [comment]
建议删除360

**Comment by duanxg** [comment]
0.38.0版本 上传腾讯云服务器，腾讯安全中心报有木马

**Comment by bkkkd** [comment]
今天再扫码一次,确实出现这个问题.
另外目前使用的是0.29.1是完全没有这个问题的.
类型：
Win64/Trojan.Generic.HgEASiQA

描述：
Win64/Trojan.Generic.HgEASiQA

扫描引擎：
360云查杀引擎

文件路径：
D:\code\go\frp\release\packages\frpc.exe

文件指纹(MD5)：
1f7518cb2bd6727285f53c1002791f7f

**Comment by feiker315** [comment]
我试过了，确实有毒，根本不是360的问题，里面被绑定了蠕虫，而且我用的服务器已经被绑了勒索病毒！

**Comment by feiker315** [comment]
我被勒索了，不知道是哪里出了问题。

**Comment by topazus** [comment]
没有360，被微软报有病毒

**Comment by ilaotan** [comment]
哎 ，自己拿源码编译的360/微软报毒，release里下的不报
