### ISSUE TITLE
能否考虑通过重试机制来提升xtcp的可用性

### ISSUE THREAD

**Issue by Ariez1** [fatedier/frp#2698]
### Describe the feature request

xtcp这种p2p模式可以最大限度的利用网络资源，在远程桌面这种需要低延时和高带宽的场景下效果很好。
目前xtcp的成功连接是概率性的，从尝试结果来看，即使是较差的网络，多次尝试后也能够成功建立连接。
如果能在代码中实现，xtcp连接成功的概率是不是就大大提升了呢

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [x] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by lunfangyu** [comment]
目前网络很多都是端口限制型的，在两端都是这种类型网络的情况下，我还没成功的建立过xtcp连接

**Comment by lunfangyu** [comment]
目前网络很多都是端口限制型的，在两端都是这种类型网络的情况下，我还没成功的建立过xtcp连接

**Comment by lunfangyu** [comment]
> 



> 目前网络很多都是端口限制型的，在两端都是这种类型网络的情况下，我还没成功的建立过xtcp连接

如果xtcp能够有90%以上的成功率的话，那才是最实用的

**Comment by Wronthyou-Emme** [comment]
> 目前网络很多都是端口限制型的，在两端都是这种类型网络的情况下，我还没成功的建立过xtcp连接

可能是因为：ISP给个人用户的光猫nat配置是默认，然后大部分个人用户没有root权限改也不会去改。拿我目前用的电信千兆来说，是提供了一个APP进行有效的更改的，其中有个DMZ主机的配置，能配置一个内网IP。这个内网IP是全开发性NAT。我通常让我自己的二级路由使用这个DMZ。
