### ISSUE TITLE
压力测试

### ISSUE THREAD

**Issue by One-people-world** [fatedier/frp#2700]
### Bug Description

怎么进行压力测试呢？
如果在服务器上挂载多个客户端的web服务，
那么挂载的客户端数量最高数量是多少？支持的最大访问量能达多少？

### frpc Version

0.34.2

### frps Version

0.34.2

### System Architecture

linux/amd64

### Configurations

1

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
https://github.com/fatedier/frp/issues/1289

> 现在我用 Swoole 重写了后端业务代码，回到了 HTTP/1.0（因为对应软件是轮询，没有必要做长连接），再进行了一次高并发请求测试，在 2000 线程 + 512 连接的情况下 Frps 依然毫无压力，可以证明就是因为连接数过多导致的这个错误了。

试试ab，wrk等http压力测试工具
或者用jmeter进行tcp压力测试
