### ISSUE TITLE
[Feature Request] TLS V1.2 Support

### ISSUE THREAD

**Issue by zulfilee** [fatedier/frp#2701]
### Describe the feature request

Does frp have support for TLS V1.2 ? 
I did not find it as part of any config option

### Affected area

- [x] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Yes.

**Comment by zulfilee** [comment]
Can you please let me know how to go about enabling it ?

**Comment by BecodReyes** [comment]
Whether TLS V1.2 is supported or not depends on your web server, frp only does proxying unless you are using the static_file plugin.
As I don't use the static_file plugin I don't really know if the static_file plugin supports TLS v1.2, I suggest you read the source code or do it yourself.

**Comment by zulfilee** [comment]
Using a certificate from Sectigo to get around this issue
Thanks for the resolution
