### ISSUE TITLE
[Feature Request] frps 服务器端不停止服务的情况下，平滑升级。服务器端配置文件的热加载。

### ISSUE THREAD

**Issue by X-designer** [fatedier/frp#2703]
### Describe the feature request

1. frps server端不停止运行的情况下，做到平滑升级。像nginx一样的，不停止业务的情况下，平滑升级。
2. frps server端热加载配置文件。

of course，这是一个艰巨的任务。0.x以及1.x是否有打算把这两个特性加入呢？

### Affected area

- [ ] Docs
- [X] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
在做 v2 版本的设计，高可用、平滑升级方面会做一定的考虑，但是复杂度较高，实际使用场景可能也比较少，所以优先级也不高。
