### ISSUE TITLE
[Feature Request] HTTP和HTTPS中的custom_domains最好能设置所有域名

### ISSUE THREAD

**Issue by rebootder** [fatedier/frp#2705]
### Describe the feature request

在frpc客户端中
[web]
type = http
local_port = 80
custom_domains=a.com,b.com,c.com,d.com.......(无数个)

域名很多在增加删除起来麻烦.
功能建议: {无需考虑多客户端,只有自己使用}
[web]
type = http
local_port = 80
custom_domains=*

这个功能使用tcp转发80可以解决,但是无法获取用户真实IP地址.
如果在TCP转发增加一个能获取用户真实IP地址那最好了

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
支持泛域名，`custom_domains = *.xxx.com`

> 如果在TCP转发增加一个能获取用户真实IP地址那最好了

这个会在 v2 版本中支持。

**Comment by rebootder** [comment]
V2什么时候发布啊 很是期待

**Comment by fatedier** [comment]
@rebootder 目前还在早期的设计阶段，有什么想法也可以提出来，主要是目前的版本框架已经固定，不太好做大的改动，使用量比较大，如果不兼容会影响到很多用户。

**Comment by rebootder** [comment]
原来大佬早已经把这个加进来了
proxy_protocol_version = v2

[https web]
type = https
local_port = 443
custom_domains = onet.yourdomain.com
# 目前支持 v1 和 v2 两个版本的 proxy protocol 协议。
proxy_protocol_version = v2

nginx配置文件如下:
server {
  listen 443 ssl http2 proxy_protocol;
  real_ip_header proxy_protocol;
  real_ip_recursive on;
  set_real_ip_from 127.0.0.1;
  ……
}

目前希望的就是一个要求了
custom_domains=*
custom_domains=*.cn
custom_domains=*.com
这样的写法

**Comment by zhezhe168** [comment]
同上，有这个需求，不知op现在解决这个问题了么？
