### ISSUE TITLE
WIN10处理器intel用那个？[Feature Request] 

### ISSUE THREAD

**Issue by pc18189** [fatedier/frp#2706]
### Describe the feature request

WIN10处理器intel用那个FRP？我看到有两个

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by pc18189** [comment]
![image](https://user-images.githubusercontent.com/94864701/146632132-d903c1cb-969f-465f-a3ba-fe1b7f240cf8.png)

**Comment by jiayaoO3O** [comment]
我要是开发看到这样提issue真的拳头都硬了.

**Comment by pc18189** [comment]
很抱歉我是小白，请原谅

佳瑶 ***@***.***> 于2021年12月23日周四 14:25写道：

**Comment by jiayaoO3O** [comment]
如果你的cpu是32位的, 就选386, 如果你的cpu是64位的, 就选amd64, 如果你是小白, 看到这两个文件名称只有"386"和"amd64"的区别, 那你只需要上网搜"386和amd64是什么意思", 马上就能知道他们之间的区别了, 你这样开一个Feature Request, 人家大佬直接close你又显得不近人情, 不close你又毫无营养, 哎.

**Comment by pc18189** [comment]
谢谢，我之前还问了一个问题。你可以看看吗？
https://github.com/fatedier/frp/issues/2671

佳瑶 ***@***.***> 于2021年12月24日周五 10:31写道：

**Comment by pc18189** [comment]
高手在吗？帮忙看看下面的东西，它没有视频教程我想学都没门。
我想用自已的服务器，但是不知怎么把服务端建上去。它有安卓客户端使用很方便我工作上的需要
https://meta.appinn.net/t/topic/9616
https://github.com/xapanyun/4gproxy

生王 ***@***.***> 于2021年12月24日周五 14:40写道：
