### ISSUE TITLE
dial tcp: lookup frp.xrick.cn on 100.100.2.136:53: no such host

### ISSUE THREAD

**Issue by Chaofan-Z** [fatedier/frp#2707]
### Bug Description

在服务器上本来正常使用frpc，在kill掉重启后就再也无法正常成功启动了，一直报这个错，尝试更改了dns server配置也没有用。

### frpc Version

0.29.0

### frps Version

no

### System Architecture

linux/amd64

### Configurations

[common]
server_addr = 139.224.68.119
server_port = 7000
tcp_mux = true
protocol = tcp
user = xxxxxxx
token = xxxxx
# dns_server = 114.114.114.114
dns_server = 8.8.8.8

[yxxxxxx6]
privilege_mode = true
type = tcp
local_ip = 127.0.0.1
local_port = 8888
remote_port = 18806
use_encryption = true
use_compression = true

[yxxxxxx6_1]
privilege_mode = true
type = tcp
local_ip = 127.0.0.1
local_port = 8888
remote_port = 18807
use_encryption = true
use_compression = true

### Logs

2021/12/18 15:07:08 [E] [service.go:228] Get http://frp.xrick.cn/api/?action=checktoken&apitoken=l8q6sfd24f5g%7C1&timestamp=1639811228&token=25a8eaf83e9e914a891a470b3349123c&user=a50d44a5487ae99e: dial tcp: lookup frp.xrick.cn on 100.100.2.136:53: no such host
2021/12/18 15:07:08 [W] [service.go:86] login to server failed: Get http://frp.xrick.cn/api/?action=checktoken&apitoken=l8q6sfd24f5g%7C1&timestamp=1639811228&token=25a8eaf83e9e914a891a470b3349123c&user=a50d44a5487ae99e: dial tcp: lookup frp.xrick.cn on 100.100.2.136:53: no such host
Get http://frp.xrick.cn/api/?action=checktoken&apitoken=l8q6sfd24f5g%7C1&timestamp=1639811228&token=25a8eaf83e9e914a891a470b3349123c&user=a50d44a5487ae99e: dial tcp: lookup frp.xrick.cn on 100.100.2.136:53: no such host

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
你用的并不是本项目编译的 release 包，经过了修改。
