### ISSUE TITLE
[Feature Request]  可以提供一些公共库来把FRP作为依赖引入到别的项目中

### ISSUE THREAD

**Issue by wwhai** [fatedier/frp#2708]
### Describe the feature request

可以提供一些公共库来把FRP作为依赖引入到别的项目中

### Describe alternatives you've considered

有时候希望以一个公共组件来引入而不是单独来运行这个frp主程序

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by fatedier** [comment]
已经有类似的 issue 了，现在已经部分可以作为库来使用的。下个大版本会设计的更彻底一些。

**Comment by wwhai** [comment]
> 已经有类似的 issue 了，现在已经部分可以作为库来使用的。下个大版本会设计的更彻底一些。

棒
