### ISSUE TITLE
win10下运行frpc，提示拒绝访问，是什么原因？

### ISSUE THREAD

**Issue by huangzhuohua** [fatedier/frp#2709]
### Bug Description

D:\frp_0.38.0_windows_amd64>frpc -c frpc.ini
拒绝访问。

### frpc Version

0.38.0

### frps Version

0.38.0

### System Architecture

windows/amd64

### Configurations

[common]
server_addr = X.X.X.X
server_port = 7000

[RDP]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 6000

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by aorosora** [comment]
被 Defender 攔截了。。。。。

**Comment by Wronthyou-Emme** [comment]
首先检查是否被windows Defender 拦截，添加进信任区。然后检查文件是否只读，只读关掉。
