### ISSUE TITLE
[Feature Request] Searching for a collaboration

### ISSUE THREAD

**Issue by adioanca-rpma** [fatedier/frp#2711]
### Describe the feature request

Hi,

I wrote 2 emails to you last week, and didn't got an answer from you, so I'm trying this channel too... :)

below is the text from my emails:

Hi,

My name is Adrian, I'm a senior software engineer with RPMA Networks.

I have hacked your frp software to make it work under 40KB/day of keep-alives at 1h, it works great ... most of the times, I still have a couple errors to figure out - total Go newbie here...

But, I find your project very interesting, and I'd like to use it in one of our future deployments.

Since we are searching for new people to join us, why not invite you to join us in our efforts?

Would you be interested in working with RPMA Networks on an hourly basis(or employee) on a feature plan?

As a hint:
- we want to have a low bandwidth (4MB/month, ~1,2MB of hearbeats at 60s)
- we want to have minimal tests for simulated 250K devices connected at once on a server
- some devops work, if interested
- other proposals that may come from our discussions

Thank you,
Adrian Oanca

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Sorry, now i have a full-time job and not enough time to do other jobs.

**Comment by adioanca-rpma** [comment]
No full-time job, understood.

What about a few paid hours a month? As many as you want/have.

I'm thinking this would be beneficial for both of us - we'll make use of `frp` at scale (and at our required specifications) and those changes will make it back into this repo, if you so wish, thus benefiting the entire project and community.

If you are interested, can we continue over email so that I can CC my project manager?

Thank you,
Adrian

**Comment by adioanca-rpma** [comment]
Thank you for accepting. We'll continue over email.
