### ISSUE TITLE
[Feature Request] FRP Client or Server start via frp package instead of binary

### ISSUE THREAD

**Issue by hinupurthakur** [fatedier/frp#2712]
### Describe the feature request

Currently to integrate the functionality of the frp to another package we have to integrate the .exe file. Can we use the frp package directly to integrate it. I have requested this feature before as well for version 0.37.1 ( related issue #2516 )

### Describe alternatives you've considered

```
func runClient(cfgFilePath string) error {
	cfg, pxyCfgs, visitorCfgs, err := config.ParseClientConfig(cfgFilePath)
	if err != nil {
		return err
	}
	return startService(cfg, pxyCfgs, visitorCfgs, cfgFilePath)
}

func startService(
	cfg config.ClientCommonConf,
	pxyCfgs map[string]config.ProxyConf,
	visitorCfgs map[string]config.VisitorConf,
	cfgFile string,
) (err error) {

	log.InitLog(cfg.LogWay, cfg.LogFile, cfg.LogLevel,
		cfg.LogMaxDays, cfg.DisableLogColor)

	if cfg.DNSServer != "" {
		s := cfg.DNSServer
		if !strings.Contains(s, ":") {
			s += ":53"
		}
		// Change default dns server for frpc
		net.DefaultResolver = &net.Resolver{
			PreferGo: true,
			Dial: func(ctx context.Context, network, address string) (net.Conn, error) {
				return net.Dial("udp", s)
			},
		}
	}
	svr, errRet := client.NewService(cfg, pxyCfgs, visitorCfgs, cfgFile)
	if errRet != nil {
		logrus.Errorln(err)
		return
	}
	err = svr.Run()
	if err != nil {
		logrus.Errorln("unable to start client: ", err)
	}
	return
}
```
Something like this, this is the code snippet picked from the frp client but it doesn't work it gives the error like:
```
2021/12/20 15:02:31 [I] [service.go:304] [7d45247c15b4cb72] login to server success, get run id [7d45247c15b4cb72], server udp port [0]
2021/12/20 15:02:31 [I] [proxy_manager.go:144] [7d45247c15b4cb72] proxy added: [web]
2021/12/20 15:02:31 [W] [control.go:261] [7d45247c15b4cb72] read error: message type error
2021/12/20 15:02:31 [I] [control.go:282] [7d45247c15b4cb72] control writer is closing
2021/12/20 15:02:31 [I] [visitor_manager.go:60] [7d45247c15b4cb72] gracefully shutdown visitor manager
2021/12/20 15:02:31 [I] [service.go:177] [7d45247c15b4cb72] try to reconnect to server...
2021/12/20 15:02:31 [I] [service.go:304] [7d45247c15b4cb72] login to server success, get run id [7d45247c15b4cb72], server udp port [0]
2021/12/20 15:02:31 [I] [proxy_manager.go:144] [7d45247c15b4cb72] proxy added: [web]
2021/12/20 15:02:31 [W] [control.go:261] [7d45247c15b4cb72] read error: message type error
2021/12/20 15:02:31 [W] [control.go:287] [7d45247c15b4cb72] write message to control connection error: stream closed
2021/12/20 15:02:31 [I] [visitor_manager.go:60] [7d45247c15b4cb72] gracefully shutdown visitor manager
2021/12/20 15:02:31 [I] [service.go:177] [7d45247c15b4cb72] try to reconnect to server...
2021/12/20 15:02:31 [I] [service.go:304] [7d45247c15b4cb72] login to server success, get run id [7d45247c15b4cb72], server udp port [0]
2021/12/20 15:02:31 [I] [proxy_manager.go:144] [7d45247c15b4cb72] proxy added: [web]
```

### Affected area

- [X] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by hinupurthakur** [comment]
@fatedier Please let me know if I can help with this in any possible way, as I would really like this feature to be there with frp. I will be happy to help and contribute.
Thanks!

**Comment by fatedier** [comment]
`read error: message type error`

From this log, i guess your server version is not compatible with your client.

**Comment by fatedier** [comment]
All message types are defined in `github.com/fatedier/frp/pkg/msg/msg.go`.

**Comment by hinupurthakur** [comment]
@fatedier Checked and both server and client have same version as 0.38.0

**Comment by hinupurthakur** [comment]
```
[common]
server_addr = 
server_port = 7000

[web]
type = http
local_port = 8090
custom_domains = 
use_compression = true

```
For the reference above is my cfg file. @fatedier 
It will be really helpful if you could please guide here

**Comment by fatedier** [comment]
It's not releated to your configures. This error means received message type is not registered in `github.com/fatedier/frp/pkg/msg/msg.go`.

I can't help you without any debugging method or full codes.

**Comment by hinupurthakur** [comment]
@fatedier Below is the repository with whole code please let me know if this is sufficient
https://github.com/hinupurthakur/frpc

**Comment by fatedier** [comment]
@hinupurthakur I found this problem caused by you missing these codes https://github.com/fatedier/frp/blob/dev/cmd/frpc/main.go#L28

**Comment by hinupurthakur** [comment]
Thanks @fatedier It worked. 🎉

**Comment by hinupurthakur** [comment]
Thanks @fatedier It worked. 🎉
