### ISSUE TITLE
is it possible to provide the VPN relay ?

### ISSUE THREAD

**Issue by simonchen** [fatedier/frp#2713]
### Describe the feature request

I've tried to setup VPN with PPTP protocol (port 1723), but it raised the error at client side:

LCP: timeout sending Config-Requests

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by simonchen** [comment]
please ignore this issue, I setup openvpn, it works like a charm

**Comment by samratfkt** [comment]
Hey, I have tried to install openvpn and wireguard but both are not working with FRP, I know I am doing something wrong. Can you please guide me a little bit? I know this is not appropriate to take help like this :\ but I need the feature :\
