### ISSUE TITLE
FRP cannot run in Windows Service 2003

### ISSUE THREAD

**Issue by AdminWhaleFall** [fatedier/frp#2714]
### Bug Description

![image](https://user-images.githubusercontent.com/63758849/146970642-d45d3c41-2371-498c-8dbd-5f5977ef1148.png)

Windows Service 2003 is a 32-bit system? Why I cannot run frpc??
Windows Service 2003 应该是32位系统,我选择386那个运行不了/

### frpc Version

0.38.0

### frps Version

0.38.0

### System Architecture

windows/X86

### Configurations

None

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Yes, it not supported any more.

**Comment by AdminWhaleFall** [comment]
> Yes, it not supported any more.

Thank you for your prompt reply!

So,What is the way to use FRPC on Windows server 2003?Use older versions such as frp v0.24?

**Comment by fatedier** [comment]
Maybe. Or you can upgrade your system version.

**Comment by AdminWhaleFall** [comment]
> Maybe. Or you can upgrade your system version.

If I want to run version 0.3x of frpc on an xp system, can I compile the source code implementation?

**Comment by AdminWhaleFall** [comment]
This problem has been solved, thank you.
