### ISSUE TITLE
[Feature Request] 使用域名连接的时候，frpc客户端如何开启ipv6优先？

### ISSUE THREAD

**Issue by aa51513** [fatedier/frp#2715]
### Describe the feature request

为了应对ip地址变化，我为frps设置了域名；
问题随之而来，frpc连接的时候，如何指定优先使用ipv6地址？

### Describe alternatives you've considered

是否应该设置一个ipv6优先的参数(默认值为false)？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
You should resolve your domain to an ipv6 address.

If so, go will try IPv6 first.
