### ISSUE TITLE
[Feature Request] 有没有办法指定客户端（frpc）的端口与frps建立初始连接？

### ISSUE THREAD

**Issue by scoryi** [fatedier/frp#2718]
### Describe the feature request

客户端frpc与frps建立连接的时候，使用的是随机端口。
有没有办法指定frpc的某个端口与frps建立连接？
![111](https://user-images.githubusercontent.com/35684058/147334548-e568f785-d01c-493e-8469-1a7241e343f6.png)

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Can do that but why?

**Comment by scoryi** [comment]
> Can do that but why?

因为在客户端前面的防火墙也限制了端口号，只有某几个端口号可以通过~

**Comment by fatedier** [comment]
cc @bingtianbaihua

**Comment by fatedier** [comment]
We discuss it and decide not to support this feature.

There may be multiple connections between frpc and frps, so you can't only specify one local port.

Instead, we will support `connect_local_ip`.
