### ISSUE TITLE
HTTP_PROXY不支持特殊字符

### ISSUE THREAD

**Issue by do21** [fatedier/frp#272]
你好，
由于PROXY密码中包含 @ 符号，于是没法用……
不知能否通过 HTTP_PROXY_USERNAME 和 HTTP_PROXY_PASSWORD 的方式来对密码中的特殊字符进行支持呢？

谢谢。

**Comment by fatedier** [comment]
请 Google 搜索解决方案。

**Comment by do21** [comment]
将 @ 替换为 %40 后依然还是报错……
