### ISSUE TITLE
客户端80端口和443端口配置同一 个域名的泛解析会提示 start error: router config conflict

### ISSUE THREAD

**Issue by gicexxopode** [fatedier/frp#2721]
### Bug Description

frp如果要同时映射80和443端口到远程服务器配置如下：
```
[webhttp]
type = http
local_port = 80
remote_port = 808
custom_domains = *.abc.com

[webhttps]
type = https
local_port = 443
remote_port = 809
use_encryption=true
use_compression=true
custom_domains = *.abc.com
```
会提示 start error: router config conflict，这个是功能设计如此，还是说是个BUG

### frpc Version

0.38.0

### frps Version

0.38.0

### System Architecture

linux/amd64

### Configurations

[webhttp]
type = http
local_port = 80
remote_port = 808
custom_domains = *.abc.com

[webhttps]
type = https
local_port = 443
remote_port = 809
use_encryption=true
use_compression=true
custom_domains = *.abc.com

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Unable to reproduce.

**Comment by ax2009live** [comment]
很明显，你的配置写的有问题，http 和 https 里的端口，是在 frps.ini 设置好的；
比如
vhost_http_port = 80
vhost_https_port = 443

[webhttp]
type = http
local_ip = xxx.xxx.xxx.xxx
local_port = 808
custom_domains = *.abc.com

[webhttps]
type = https
local_ip = xxx.xxx.xxx.xxx
local_port = 809
use_encryption=true
use_compression=true
custom_domains = *.abc.com
