### ISSUE TITLE
修改heartbeat_interval为20s，keepalive_interval仍然是30s

### ISSUE THREAD

**Issue by ZRJUN** [fatedier/frp#2725]
### Bug Description

有什么办法可以修改keepalive_interval吗，为什么heartbeat_interval最好是90s不要修改

### frpc Version

0.36.2

### frps Version

0.36.2

### System Architecture

linux/amd64

### Configurations

[common]
bind_port = 7071
authentication_method = token
token = XXX
log_file = /var/log/frps.log
log_level = info
log_max_days = 3
log_level = trace
heartbeat_timeout = 20

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
写死了
自行修改源码编译
https://github.com/fatedier/frp/blob/0cee1877e36abbce9a0473c3c1da7e548c199621/test/e2e/pkg/request/request.go#L200

**Comment by hsiang0100** [comment]
設定tcp_mux = false
即可讓heartbeat_interval有效
