### ISSUE TITLE
[Feature Request]  是否能使用cdn 加速  server

### ISSUE THREAD

**Issue by kbitlive** [fatedier/frp#2728]
### Describe the feature request

使用国外服务器 ip 被墙后，就没有办法使用了。
现在手上有国内cdn ，是否能通过cdn 加速serve的连接

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Wronthyou-Emme** [comment]
不能

**Comment by fatedier** [comment]
CDN 一般用于缓存和加速静态页面。

**Comment by kbitlive** [comment]
好吧，服务端是什么协议，可以用nginx 来反代或者做负债均衡吗

**Comment by BecodReyes** [comment]
可以，但是流量一般很贵，且得支持tcp才行
比如Cloudflare Spectrum

**Comment by kbitlive** [comment]
> 

谢谢 可以了
