### ISSUE TITLE
local websocket port access

### ISSUE THREAD

**Issue by ranjeet-pivotchain** [fatedier/frp#2735]
### Bug Description

Hey,

How do I access the local web socket port?
Currently, I am trying using HTTP but it's telling **upgrade required.**

[web]
type = http
local_port = 80
custom_domains = xyz.domain.com

### frpc Version

0.38.0

### frps Version

0.38.0

### System Architecture

linux/amd64 ubuntu

### Configurations

frps server side:
cat frps.ini 
[common]
bind_port = 7000
vhost_http_port = 8080

frpc client side:
cat frpc.ini
cat frpc.ini 
[common]
server_addr = SERVER_IP
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

[web]
type = http
local_port = 80
custom_domains = xyz.domain.com

After starting client and server when I hit URL http://xyz.domain.com:8080 then it's showing logs **Upgrade required**
![lplplplplp](https://user-images.githubusercontent.com/71004089/148051407-8c0b99c9-1c8a-471b-bdd1-54851b492550.png)

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
https://github.com/fatedier/frp/pull/2601

> We don't want to maintain the protocol websocket between frpc and frps now. It's not the core feature for frp.

For this I suggest that you use the tcp protocol to proxy the local web server
