### ISSUE TITLE
Subdomain Bug

### ISSUE THREAD

**Issue by felix530-h** [fatedier/frp#2736]
### Bug Description

Thanks for the great github repository. 

I want to make multiple services reachable using frp. I have set the following in the config:
frps.ini:
[common]
bind_port = 7000
vhost_http_port = 8480
subdomain_host = test.abc

frpc.ini
[common]
server_addr = 127.0.0.1
server_port = 7000

[web-01]
type = http
local_ip = 127.0.0.1
local_port = 80
subdomain = web01
custom_domains = test.abc

[web-02]
type = http
local_ip = 192.168.178.1
local_port = 80
subdomain = web02
custom_domains = test.abc

as soon as I start frpc I get the following error message:
[web-02] start error: router config conflict

But if I start only one subdomain service then don't get any error message.

### frpc Version

0.38.0

### frps Version

0.38.0

### System Architecture

linux_amd64

### Configurations

frpc.ini
[common]
server_addr = 127.0.0.1
server_port = 7000

[web-01]
type = http
local_ip = 127.0.0.1
local_port = 80
subdomain = web01
custom_domains = test.abc

[web-02]
type = http
local_ip = 192.168.178.1
local_port = 80
subdomain = web02
custom_domains = test.abc

### Logs

error: router config conflict

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Remove `custom_domains`

**Comment by felix530-h** [comment]
Thanks for the fast support. Without "custom_domains" it works.
