### ISSUE TITLE
[Feature Request] Dashboard中不显示stcp的客户端连接

### ISSUE THREAD

**Issue by hlpan** [fatedier/frp#2740]
### Describe the feature request

安全地暴露内网服务，需要两个frpc运行。
Dashboard中只会显示[secret_ssh]，而不显示[secret_ssh_visitor]。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
正常现象

**Comment by fatedier** [comment]
visitor 并不需要和 frps 做交互，它只存在于本地。
