### ISSUE TITLE
frpc: login to server failed: i/o deadline reached

### ISSUE THREAD

**Issue by duzhor** [fatedier/frp#2741]
### Bug Description

frpc启动后几秒即退出，日志报[W]...i/o deadline reached
frps无对应连接的日志

### frpc Version

0.38.0

### frps Version

0.38.0

### System Architecture

windows/amd64

### Configurations

# frpc.ini
[common]
server_addr = example.com
server_port = 7000

### Logs

2022/01/09 02:17:31 [W] [service.go:104] login to server failed: i/o deadline reached

### Steps to reproduce

1. frpc配置server_addr为域名即出现此报错日志
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by TongChiYip** [comment]
I've tried on Ubuntu18.04/Ubuntu18.04 and reproduce exactly the same failure. What could be the reason and how could I solve it?

**Comment by fatedier** [comment]
It means network error. Makesure your can connect to your server address normally.

**Comment by duzhor** [comment]
似乎是本地dns解析域名的问题，通过更换dns解决

**Comment by connected201** [comment]
problem was in Windows firewall!
