### ISSUE TITLE
关于OpenWrt中的frpc问题求助

### ISSUE THREAD

**Issue by blueboyggh** [fatedier/frp#2744]
### Bug Description

我用的R2s软路由，最近想用里面的frpc，但是如果我用自带的软件生成的配置，就会报login to server failed: EOF，用自己修改的配置文件就可以正常连接。
自带软件生成的配置文件：
[common]
server_addr=XXXXXXXXXXXX
server_port=700
token=XXXXXXXX
user=bd-r2s
log_level=info
log_max_days=3
protocol=tcp
log_file=/var/etc/frp/frpc.log
tcp_mux=false
tls_enable=false
login_fail_exit=false

[bd-r2s]
type=tcp
remote_port=XXX
local_ip=192.168.XX.XX
local_port=XX
use_encryption=false
use_compression=false

我修改的：
[common]
server_addr=XXXXXXXX
server_port=700
token=XXXXXX

[bd-r2s]
type=tcp
remote_port=XXX
local_ip=192.168.XX.XX
local_port=XX

我只是把一些默认关闭的参数删掉了，按理说这两个配置文件应该是一样的，为啥用自带的就无法正常连接呢？求大神指点

### frpc Version

0.38.0

### frps Version

0.37.1

### System Architecture

openwrt/arm64

### Configurations

[common]
server_addr=XXXXXXXXXXXX
server_port=700
token=XXXXXXXX
user=bd-r2s
log_level=info
log_max_days=3
protocol=tcp
log_file=/var/etc/frp/frpc.log
tcp_mux=false
tls_enable=false
login_fail_exit=false

[bd-r2s]
type=tcp
remote_port=XXX
local_ip=192.168.XX.XX
local_port=XX
use_encryption=false
use_compression=false

### Logs

客户端：2022/01/10 10:03:29 [W] [service.go:104] login to server failed: EOF

服务器端：没有相关报错LOG

**Comment by fatedier** [comment]
The default value of `tcp_mux` is true.

**Comment by blueboyggh** [comment]
> The default value of `tcp_mux` is true.

原来是这样，路由器第一次提示这个参数和服务器不符，我就取消了，原来是这个问题，感谢！
