### ISSUE TITLE
[Feature Request] frpc启动时连接失败没有重连机制，导致自动启动时失败

### ISSUE THREAD

**Issue by huanghe-1** [fatedier/frp#2745]
### Describe the feature request

运行过程中连接失败有重连机制，启动时没有，导致设置随系统启动时，如果网络中断，就会启动失败，导致frpc失联，后续网络恢复也无法连接frpc。

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
There are already same issues about this question.

**Comment by huanghe-1** [comment]
哦，不好意思，那这个issue可以删掉吗，我只能关，不能删。

**Comment by huanghe-1** [comment]
对了，刚才找了一下，没有找到same issues ？

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/issues/2605

**Comment by huanghe-1** [comment]
作者牛逼，原来早已经考虑到了，这个参数可以控制，login_fail_exit = false，那这个issue怎么删掉呢，重复了。
