### ISSUE TITLE
frpc.exe from frp_0.38.0_windows_amd64.zip fails virus scan

### ISSUE THREAD

**Issue by DarrenMax** [fatedier/frp#2749]
### Bug Description

Win10 defender quarrantines the frpc.exe file. Virus found is called: Program:Win32/Uwamson.A!ml

### frpc Version

0.38.0

### frps Version

0.38.0

### System Architecture

windows/amd64

### Configurations

Setup to integrate with Moralis.

### Steps to reproduce

1. Download zip
2. Unzip the file
3. Windows Defender deletes the file within 15 seconds once it has been unzipped
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by DarrenMax** [comment]
Suspect false positive, will try an older version.

**Comment by xqzr** [comment]
#2095
