### ISSUE TITLE
记得以前服务端有特权模式和普通模式，现在取消了吗？

### ISSUE THREAD

**Issue by rongwing** [fatedier/frp#2750]
### Describe the feature request

以前普通模式，开启什么服务由服务器写配置，客户端只能对应生成配置，特权模式客户端权限大，需要什么端口开放自己写就行了， 现在新版直接剩下特权模式这种了吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Not support anymore. You can try [server manager plugin](https://github.com/fatedier/frp/blob/dev/doc/server_plugin.md) to implement your own plugin to limit used ports.

**Comment by rongwing** [comment]
> Not support anymore. You can try [server manager plugin](https://github.com/fatedier/frp/blob/dev/doc/server_plugin.md) to implement your own plugin to limit used ports.

好的，谢谢！
