### ISSUE TITLE
FRP流量可以被检测到了?

### ISSUE THREAD

**Issue by PRNDA** [fatedier/frp#2752]
### Bug Description

我们这边有一台服务器开通FRP打洞被网管检测到了。

### frpc Version

0.38.0

### frps Version

0.38.0

### System Architecture

linux/amd64

### Configurations

no

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
建议合理使用，不要违反内部网络管理规定。

**Comment by xqzr** [comment]
一直都可以检测，设计是这样

**Comment by testonlys** [comment]
只要产生流量被检测到是必然的
