### ISSUE TITLE
get a user connection 显示一个国外的IP

### ISSUE THREAD

**Issue by zhizunbao84** [fatedier/frp#2755]
### Bug Description

我远程访问我的内网电脑，远程桌面，除了我自己的ip外还显示：
`get a user connection [89.248.165.4:7283]`
后来我测试了好几次，每次都是这个ip段的地址，我百度了一下，显示是荷兰阿姆斯特丹的ip，怎么会出现这个ip呢
是有人连接我的frps服务器了么？
我已经设置了token

### frpc Version

0.37.1

### frps Version

0.37.1

### System Architecture

windows/amd64

### Configurations

authentication_method = token
token = xxxxxxxx

authenticate_heartbeats = true
authenticate_new_work_conns = true

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
`user connection` 是指你暴露出去的端口有新的用户连接。并不是 frpc 连接到 frps。

比如你暴露了一个网站，当有国外的 IP 请求你的网站时，就会看到这样的日志。

**Comment by zhizunbao84** [comment]
> `user connection` 是指你暴露出去的端口有新的用户连接。并不是 frpc 连接到 frps。
> 
> 比如你暴露了一个网站，当有国外的 IP 请求你的网站时，就会看到这样的日志。

你的意思是有人连接我的内网电脑？

**Comment by xqzr** [comment]
> > `user connection` 是指你暴露出去的端口有新的用户连接。并不是 frpc 连接到 frps。
> > 比如你暴露了一个网站，当有国外的 IP 请求你的网站时，就会看到这样的日志。
> 
> 你的意思是有人连接我的内网电脑？

尝试连接。
互联网是这样的

**Comment by xqzr** [comment]
> 不仅仅是尝试，有时候89.248.165.4这个ip连接后，我自己的远程桌面就会被下线

应该是密码弱，被破解。可能已经被种木马

**Comment by zhizunbao84** [comment]
> > 不仅仅是尝试，有时候89.248.165.4这个ip连接后，我自己的远程桌面就会被下线
> 
> 应该是密码弱，被破解。可能已经被种木马

卧槽！！！我应该怎么排查呢？

**Comment by zhizunbao84** [comment]
今天又显示    get a user connection   121.89.223.191，是个阿里云的ip

**Comment by zhizunbao84** [comment]
get a user connection [124.47.8.238:22516]
 get a user connection [124.47.8.238:29725]
 get a user connection [124.47.8.238:15661]
 get a user connection [124.47.8.238:26086]
 get a user connection [124.47.8.238:33554]
 get a user connection [124.47.8.238:19050]
 get a user connection [124.47.8.238:37377]
 get a user connection [124.47.8.238:41082]
 get a user connection [124.47.8.238:44580]
 get a user connection [124.47.8.238:48151]
 get a user connection [124.47.8.238:51484]
 get a user connection [124.47.8.238:54958]
 get a user connection [124.47.8.238:58602]
 get a user connection [124.47.8.238:62703]
 get a user connection [124.47.8.238:2160]
 get a user connection [124.47.8.238:6119]
 get a user connection [124.47.8.238:9896]
 get a user connection [124.47.8.238:13694]
 get a user connection [124.47.8.238:17189]
 get a user connection [124.47.8.238:20792]
 get a user connection [124.47.8.238:24409]
 get a user connection [124.47.8.238:28273]
 get a user connection [124.47.8.238:32113]
 get a user connection [124.47.8.238:36071]
 get a user connection [124.47.8.238:40020]
 get a user connection [124.47.8.238:44004]
 get a user connection [124.47.8.238:47715]

我在我的内网机器已经限制了ip，为啥还显示这么多啊？

**Comment by zhizunbao84** [comment]
@fatedier 你确定这些都是连接我的内网机器的ip么，我内网机器的远程连接，端口是3389，也不能这么多ip同时连接啊？！

**Comment by zhizunbao84** [comment]
还是说这些ip在扫描？

**Comment by zhizunbao84** [comment]
这一会会，这么些
 
get a user connection [124.47.8.238:50047]
 get a user connection [124.47.8.238:58991]
 get a user connection [193.32.164.60:34325]
 get a user connection [124.47.8.238:64714]
 get a user connection [124.47.8.238:53118]
 get a user connection [124.47.8.238:61827]
 get a user connection [124.47.8.238:3246]
 get a user connection [124.47.8.238:56065]
 get a user connection [124.47.8.238:6329]
 get a user connection [124.47.8.238:9357]
 get a user connection [124.47.8.238:12298]
 get a user connection [193.32.164.60:50939]
 get a user connection [124.47.8.238:15056]
 get a user connection [124.47.8.238:17819]
 get a user connection [124.47.8.238:20594]
 get a user connection [124.47.8.238:23475]
 get a user connection [124.47.8.238:26393]
 get a user connection [124.47.8.238:29305]
 get a user connection [193.32.164.60:3640]
 get a user connection [124.47.8.238:32348]
 get a user connection [124.47.8.238:35435]
 get a user connection [124.47.8.238:38438]
 get a user connection [124.47.8.238:41394]
 get a user connection [124.47.8.238:44473]
 get a user connection [124.47.8.238:47571]
 get a user connection [193.32.164.60:19854]
 get a user connection [124.47.8.238:50846]
 get a user connection [124.47.8.238:54070]
 get a user connection [124.47.8.238:57480]
 get a user connection [124.47.8.238:60826]
 get a user connection [124.47.8.238:64257]
 get a user connection [124.47.8.238:2978]
 get a user connection [193.32.164.60:36784]
 get a user connection [124.47.8.238:6228]
 get a user connection [124.47.8.238:9148]
 get a user connection [124.47.8.238:12142]
 get a user connection [124.47.8.238:14970]
 get a user connection [124.47.8.238:17898]
 get a user connection [124.47.8.238:20925]
 get a user connection [193.32.164.60:53940]
 get a user connection [124.47.8.238:23858]
 get a user connection [124.47.8.238:26771]
 get a user connection [124.47.8.238:29724]
 get a user connection [124.47.8.238:32483]
 get a user connection [124.47.8.238:35296]
 get a user connection [124.47.8.238:38147]
 get a user connection [124.47.8.238:40982]
 get a user connection [193.32.164.60:6142]
 get a user connection [124.47.8.238:43870]
 get a user connection [124.47.8.238:46806]
 get a user connection [124.47.8.238:49767]
 get a user connection [124.47.8.238:52635]
 get a user connection [124.47.8.238:55350]
 get a user connection [124.47.8.238:57963]
 get a user connection [124.47.8.238:60662]
 get a user connection [193.32.164.60:23563]
 get a user connection [124.47.8.238:63475]
 get a user connection [124.47.8.238:1858]
 get a user connection [124.47.8.238:4807]
 get a user connection [124.47.8.238:7843]
 get a user connection [124.47.8.238:10714]
 get a user connection [124.47.8.238:13486]
 get a user connection [193.32.164.60:40820]
 get a user connection [124.47.8.238:16176]
 get a user connection [124.47.8.238:19071]
 get a user connection [124.47.8.238:22160]
 get a user connection [124.47.8.238:25424]
 get a user connection [124.47.8.238:28769]
 get a user connection [124.47.8.238:32117]
 get a user connection [193.32.164.60:57740]
 get a user connection [124.47.8.238:35542]
 get a user connection [124.47.8.238:38616]
 get a user connection [124.47.8.238:41562]
 get a user connection [124.47.8.238:44507]
 get a user connection [124.47.8.238:47506]
 get a user connection [124.47.8.238:50563]
 get a user connection [124.47.8.238:53704]
 get a user connection [193.32.164.60:10567]
 get a user connection [124.47.8.238:57086]
 get a user connection [124.47.8.238:60551]

**Comment by Max-Qiu** [comment]
用stcp，基本上不会出问题

**Comment by aloikun** [comment]
2022/02/10 07:29:26 [I] [proxy.go:162] [6f8c308d0a682159] [server] get a user connection [89.248.163.206:40760]
然后我那小服务器就收到163条尝试登录的失败信息？这个也是外国地址

**Comment by nsc117** [comment]
如楼上大佬所言，互联网就是这样，你被扫描了。
这些来自互联网的扫描可以视作互联网噪音，避免不了。
使用强密码等安全措施吧，根据你的描述，应该是密码被破了。

**Comment by shangweixiao** [comment]
参考：
1. 设置一个复杂一些的token。
2. 远程桌面设置复杂密码。
3. 装上fail2ban，设置规则，每天连接超过多少次就直接ban一个月。然后用这条命令把自己的IP忽略 fail2ban-client set frps addignoreip x.x.x.x/xx
我已经用了几年了，没有任何问题。

**Comment by justbelieveyourself** [comment]
换一个数字大一点的端口,不要用常用的端口
