### ISSUE TITLE
work connection closed before response StartWorkConn message：EOF是被公司防火墙墙了么？

### ISSUE THREAD

**Issue by eternalcbh** [fatedier/frp#2756]
### Bug Description

当打开在公司内网打开frpc服务的时候报：
2022/01/12 08:37:47 [I] [service.go:304] [355779d141dc078a] login to server success, get run id [355779d141dc078a], server udp port [7001]
2022/01/12 08:37:47 [I] [visitor_manager.go:86] [355779d141dc078a] start visitor success
2022/01/12 08:37:47 [I] [visitor_manager.go:130] [355779d141dc078a] visitor added: [visitor_company]
2022/01/12 08:37:47 [I] [proxy_manager.go:144] [355779d141dc078a] proxy added: [web]
2022/01/12 08:37:47 [I] [control.go:180] [355779d141dc078a] [web] start proxy success
2022/01/12 08:38:17 [E] [control.go:158] [355779d141dc078a] work connection closed before response StartWorkConn message: EOF
2022/01/12 08:38:17 [I] [control.go:282] [355779d141dc078a] control writer is closing
2022/01/12 08:38:17 [W] [visitor.go:196] [355779d141dc078a] [visitor_company] xtcp local listener closed
2022/01/12 08:38:17 [I] [service.go:177] [355779d141dc078a] try to reconnect to server...
2022/01/12 08:38:17 [I] [visitor_manager.go:60] [355779d141dc078a] gracefully shutdown visitor manager
2022/01/12 08:38:17 [I] [service.go:304] [355779d141dc078a] login to server success, get run id [355779d141dc078a], server udp port [7001]
2022/01/12 08:38:17 [I] [visitor_manager.go:86] [355779d141dc078a] start visitor success
2022/01/12 08:38:17 [I] [visitor_manager.go:130] [355779d141dc078a] visitor added: [visitor_company]
2022/01/12 08:38:17 [I] [proxy_manager.go:144] [355779d141dc078a] proxy added: [web]
2022/01/12 08:38:17 [I] [control.go:282] [355779d141dc078a] control writer is closing
2022/01/12 08:38:17 [E] [control.go:158] [355779d141dc078a] work connection closed before response StartWorkConn message: EOF
2022/01/12 08:38:17 [W] [visitor.go:196] [355779d141dc078a] [visitor_company] xtcp local listener closed
2022/01/12 08:38:17 [I] [service.go:177] [355779d141dc078a] try to reconnect to server...

### frpc Version

frpc -v 0.38.0

### frps Version

---------

### System Architecture

windows/amd64

### Configurations

[common]
server_addr = 
server_port = 

# 主机
[web]
type = xtcp
local_ip = 127.0.0.1
local_port = 3389
sk = 

# 访问机
[visitor_company]
type = xtcp
role = visitor
sk = 
server_name = ssh
bin_addr = 127.0.0.1
bind_port = 12221

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
可以尝试启用 `tls_enable = true` 加密流量。

但是建议遵循公司的安全规则合理使用。

**Comment by zhousongsong** [comment]
本来是正常的，后来我也遇到这样的问题，请问是什么原因产生的呢

**Comment by websecer** [comment]
> 可以尝试启用`tls_enable = true`加密流量。
> 
> 建议遵循公司的安全规则合理使用。

客户端开启tls_enable = true 依然提示这个错误

**Comment by ruoshui901** [comment]
有规律性的断开吗。设置了frps的heartbeat_timeout。

**Comment by grootsong** [comment]
> > 可以尝试启用`tls_enable = true`加密流量。
> > 建议遵循公司的安全规则合理使用。
> 
> 客户端开启tls_enable = true 依然提示这个错误

请问最后解决了吗？

**Comment by cusber** [comment]
> 这个问题也困扰我很久了，希望能够解决

我也遇到同样的问题， 最终判断是公司网络把这个IP给封了。 可能是i触发了什么规则，或者流量非常像媒体服务。 

我把服务器IP改了  问题就解决了。   后来也一直没有再出现这个问题。
