### ISSUE TITLE
Load balancer for frp http proxy for horizontal scaling.

### ISSUE THREAD

**Issue by anand-010** [fatedier/frp#2757]
### Describe the feature request

Nginx or other load balancer technique for dynamic loads.
I have already seen the subdomains assigning to each server which is not flexible, scalable  and dynamic.
May be there needs to be extra headers or something from proxy connection and user connection for the load balancer to route.

### Describe alternatives you've considered

Assigning subdomains to each server manually is the current solutionwhich is not flexible, scalable and dynamic. 

### Affected area

- [X] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
I can't get your point. Can you describe more or draw a simple flow chart?

**Comment by anand-010** [comment]
Here is the flow chart i am created.
Before that i am created plugin for authentication for each reverse proxy users.
![diagram](https://user-images.githubusercontent.com/32414977/149088660-e65d0aa3-11c0-4f3d-949d-a1836b7bbcb7.PNG)
Each http connections and it's associated reverse proxy connection must be forward to same vm otherwise it doesn't work.
How do we deal with this situations.

**Comment by fatedier** [comment]
As you said, load-balance by DNS is a simple way. You can resolve `xxx.group1.com` and `xxx.group2.com` to different VMs.

This project is not designed for this scenario. It's not an easy feature, especially for TCP connections.

**Comment by anand-010** [comment]
Do you have any suggestions how to implement it.
is there any header or other specific data's to uniquely identify proxy connection and http user connections ?.
