### ISSUE TITLE
Windows Defender 报告病毒

### ISSUE THREAD

**Issue by nebulabox** [fatedier/frp#2759]
### Bug Description

frpc.exe 

Trojan:Win32/Sabsik!ml

### frpc Version

0.38

### frps Version

0.38

### System Architecture

windows/amd64

### Configurations

Trojan:Win32/Sabsik!ml

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by andrew2558** [comment]
我的也是。什么情况。

**Comment by beituan** [comment]
同样~也是报告有问题
Trojan:Win32/Sabsik!ml

**Comment by nebulabox** [comment]
应该是误报。这导致很多问题。

**Comment by xqzr** [comment]
#2768
