### ISSUE TITLE
FRP使用中出现getsockopt: connection refused求指点

### ISSUE THREAD

**Issue by bittyboy** [fatedier/frp#276]
[client.go:129] [E] ProxyName [web287987898qR], connect to server [x.x.x.x:7000] error, dial tcp x.x.x.x:7000: getsockopt: connection refused
出现这样的提示，然后打开网站肯定卡半天了，我在下面附上图片地址，希望大家指点问题所在。http://wx3.sinaimg.cn/mw690/005TOkJAgy1fdm2geuu4ij30k80b20uz.jpg

**Comment by 4ier** [comment]
@bittyboy
我也遇到了同样的问题：
[client.go:111] [E] ProxyName [web], connect to local port error, dial tcp 127.0.0.1:80: getsockopt: connection refused
求教怎么解决的

**Comment by blinkdr** [comment]
遇到一种情况是，Nginx没有启动，意思说80端口没服务，然后就会拒绝连接
