### ISSUE TITLE
[Feature Request] Multiple IP on server and remote_Ip value

### ISSUE THREAD

**Issue by d-513** [fatedier/frp#2762]
### Describe the feature request

My server has many public ip, I need to define what IP to use with frpc

### Describe alternatives you've considered

multiple instances of frps

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by BecodReyes** [comment]
https://github.com/fatedier/frp/blob/293003fcdb6a090f9e2919b8e7d1224ab1e41549/conf/frps_full.ini#L3-L6

or [yongboy/bindp](https://github.com/yongboy/bindp)

**Comment by dada513** [comment]
> https://github.com/fatedier/frp/blob/293003fcdb6a090f9e2919b8e7d1224ab1e41549/conf/frps_full.ini#L3-L6
> 
> or [yongboy/bindp](https://github.com/yongboy/bindp)

yes, but you need multiple instances to use many addresses

**Comment by yashodhank** [comment]
What OP meant is having Multiple FRPS running on different cloud server having their own public IPs and allow FRPC hosting one or many services on local port to use these FRPS to ensure high availability of exit node? correct me if I am wrong. @dada513 
I am playing with Traefik to do it right now but wonder if there is any FRPS/FRPC native way of doing it with SSL termination.
In my case I am using Traefik docker container to do load balancing as well as ssl termination for one FRPS instance at the moment I have not yet tested possibility of having multiple FRPS nodes as proxy into Traefik router to achieve high availability. 

In my case, I have subdomian.domain.ext is unique exposing local web server using FRPC and FRPS hosted on cloud server sitting behind Traefik router (in docker) is terminating SSL as well as working as revers proxy for FRPS, load balancer configuration is technically possible but I am yet to test it. Thank you

**Comment by Nour963** [comment]
> 

@yashodhank any news of that ?

**Comment by yashodhank** [comment]
@Nour963 I was able to get it working for my own use case in limited way as natively FRP does not support it at the moment.
I have implemented Docker-swarm, Traefik as load balancer and gateway for FRP Server instances running on remote nodes on any popular cloud providers. Where as FRP Clients are connecting to one such server instance to make services available to/from internet.
