### ISSUE TITLE
[Feature Request]  How to ensure safe when we use third part FRP services provider? 

### ISSUE THREAD

**Issue by sshuangliu** [fatedier/frp#2763]
### Describe the feature request

Hope you are doing well.
For some resaons, we used the third part FRP services provider that is beyond my control to forward our traffic , so how can we ensure our traffic to be safe for againsting **the monitor of services provider**

are there any features for FRP?
by the way , if we use third part services, we can only control FRPC.ini rather than FRPS.ini

thanks

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Use HTTPS or encrypt your traffic by yourself.
