### ISSUE TITLE
[Feature Request] 国内 Web服务转发时， 域名备案问题

### ISSUE THREAD

**Issue by sshuangliu** [fatedier/frp#2764]
### Describe the feature request

在部署了FRP相关的服务在国内云主机上，并配置了转发**web一类**服务到内网，当我们用云主机**公网ip访问**时，一切正常，能转发流量到内网，但是当我们用域名访问（域名映射等都已配置就绪），到云主机web流量就被block了，然后定向到一个网站备案的页面，应该是云厂商的策略，检查到http head的host字段是domain信息，然后把通过域名访问的web流量给block。
![image](https://user-images.githubusercontent.com/38092313/149719624-7b94ce94-26e0-458b-b9c1-06d2cb8548c1.png)

请问现在版本的FRP有解决这个问题的办法吗？
以及 FRPS收到browser的流量后，是通过怎样的方式转发到FRPC的？类似隧道的方式，users traffic(TCP/UDP or http) over tunnel(tcp/udp) ? 数据包是如何一层层封装？隧道协议是私有的还是公用的？

如果是隧道方式转发，加密users traffic，或许可以防止被云厂商检测出。

谢谢

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by sshuangliu** [comment]
wrong

**Comment by yhcc** [comment]
请问这个问题解决了吗？
