### ISSUE TITLE
xtcp is not supported in frps

### ISSUE THREAD

**Issue by CyberFoxHax** [fatedier/frp#2765]
### Bug Description

i followed the p2p instruction on the front page and all i get is: "xtcp is not supported in frps"

### frpc Version

0.38.0

### frps Version

0.38.0

### System Architecture

Windows 10 x64

### Configurations

Remote machine
```
[p2p_rdp]
type = xtcp
sk = abcdefg
local_ip = 127.0.0.1
local_port = 3389

```

My machine
```
[p2p_rdp_visitor]
type = xtcp
role = visitor
server_name = p2p_rdp
sk = abcdefg
bind_addr = 127.0.0.1
bind_port = 6000
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by CyberFoxHax** [comment]
doing some digging on my own


```go
if cfg.BindUDPPort > 0 {
	var nc *nathole.Controller
	address := net.JoinHostPort(cfg.BindAddr, strconv.Itoa(cfg.BindUDPPort))
	nc, err = nathole.NewController(address)
	if err != nil {
		err = fmt.Errorf("Create nat hole controller error, %v", err)
		return
	}
	svr.rc.NatHoleController = nc
	log.Info("nat hole udp service listen on %s", address)
}
```
https://github.com/fatedier/frp/blob/293003fcdb6a090f9e2919b8e7d1224ab1e41549/server/service.go#L267

according to this piece, as long as there's an entry for bind_udp_port and it's value is greater than 0, it should log either success or failure for the NAT service.

But neither is logged.

**Comment by Looomo** [comment]
add bind_udp_port = 7000 to your frps.ini.
make it looks like this:
[common]
bind_port = 7000
bind_udp_port = 7000

**Comment by CyberFoxHax** [comment]
same, i'm not gonna pretend to know what's going on, but i think perhaps xtcp is a plugin that needs to be installed somehow?
