### ISSUE TITLE
啟用 https 後， X-Forward-For 和 Proxy Protocol 都無法抓取到正確的真實ip ，但採 http 就能抓到正確的用戶 ip

### ISSUE THREAD

**Issue by markku636** [fatedier/frp#2766]
### Bug Description
啟用 https 後， X-Forward-For 和 Proxy Protocol 都無法抓取到正確的真實ip ，但採 http 就能抓到正確的用戶 ip
* X-Forwarded-For 只有 frps 的ip，抓不到用戶的 ip
* 抓不到 X-Real-IP 

開發環境
frps 0.38 => 架設在 google cloud ubuntu 上 
frpc 0.38 windows (win 10)

### frpc Version

0.38 =

### frps Version

0.38 =

### System Architecture

windows/amd64

### Configurations

[Comma.Admin]
type = https
local_port = 5201
custom_domains = works-admin.markkulab.net
plugin = https2http
plugin_local_addr = 127.0.0.1:5201
proxy_protocol_version = v2
# HTTPS 证书相关的配置
plugin_crt_path = ./markkulab.net/fullchain.pem
plugin_key_path = ./markkulab.net/privkey.pem
plugin_header_X-From-Where = frp

**Comment by markku636** [comment]
![image](https://user-images.githubusercontent.com/8486599/149964662-32974ad7-ead0-4ed9-bd89-b650f1571cde.png)
不知道和這個有關嗎?

**Comment by BecodReyes** [comment]
请把https放在后端

并且需要启用Proxy Protocol解析 `listen 443 ssl proxy_protocol;`

**Comment by markku636** [comment]
謝謝你的建議，
我後來解決了，
我後來發現 net core 的 web server 不支援 Proxy Protocol , 
需要額外透過 nginx 在轉發一層。
