### ISSUE TITLE
为什么你的程序里有病毒？

### ISSUE THREAD

**Issue by qq921124136** [fatedier/frp#2768]
### Bug Description

为什么会报病毒？
![bug](https://user-images.githubusercontent.com/83702287/150362896-88343196-a4ae-4894-b305-d6ff73ec8885.png)

### frpc Version

frp_0.38.0_windows_amd64

### frps Version

frp_0.38.0_windows_amd64

### System Architecture

windows/amd64

### Configurations

..

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
#2095

**Comment by fatedier** [comment]
如果不能明确是否有风险，请不要再继续使用！
