### ISSUE TITLE
hacker？

### ISSUE THREAD

**Issue by qq921124136** [fatedier/frp#2769]
### Bug Description

![~HU)A_N 0)MQABIE6Y3X(TD](https://user-images.githubusercontent.com/83702287/150367980-670ba112-69a7-43c0-805b-8b6e6f55c882.png)

### frpc Version

frp_0.38.0_linux_amd64

### frps Version

frp_0.38.0_linux_amd64

### System Architecture

windows/amd64

### Configurations

..

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
#2768

**Comment by fatedier** [comment]
如果不能明确是否有风险，请不要再继续使用！
