### ISSUE TITLE
Windows 如何后台运行

### ISSUE THREAD

**Issue by touzi** [fatedier/frp#277]
1. Windows 服务器端 (frps) 如何后台运行? 
2. Windows 客户端 (frpc) 如何后台运行?

我在文档中只找到了 `frps -c frps.ini` 这样一种启动方式. 

望解答, 谢谢!

**Comment by fatedier** [comment]
推荐通过 google 搜索以及查询之前相关的 issue 记录，会有一些帮助。

这个问题和具体的项目无关，对于任意的其他应用来说是通用的，这里并不一定保证 windows 环境下的可用性，并不作为主要的开发环境进行测试。

**Comment by mbj2014** [comment]
推荐用NSSM来把frp注册成服务的方式运行。
