### ISSUE TITLE
Segmentation fault in cloud server.

### ISSUE THREAD

**Issue by qinglew** [fatedier/frp#2770]
### Bug Description

When I run the frps in cloud server, it reports segmentation fault.

### frpc Version

0.38.0

### frps Version

0.38.0

### System Architecture

linux/amd64

### Configurations

All in default.

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
https://github.com/fatedier/frp/issues/1491

> 下载版本不匹配，需要下载系统支持的对应版本。

You need to download the corresponding version supported by the system

**Comment by AXFOX** [comment]
> #1491
> 
> > 下载版本不匹配，需要下载系统支持的对应版本。
> 
> 需要下载系统支持的相应版本
Linux racknerd-XXX 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
那我还能用哪个版本，frp_0.49.0_linux_amd64.tar.gz出现同样地问题
