### ISSUE TITLE
http跳转的p2p模式

### ISSUE THREAD

**Issue by konijiji** [fatedier/frp#2771]
### Describe the feature request

希望增加一个http跳转的p2p模式，就是把xxx.com定向到服务器ip，访问者访问http://xxx.com,服务器返回301跳转到http://路由器ip:port，这样访问者不用安装frp也可以p2p传输。

比如客户端有一个web服务是192.168.1.1:80，frp经过运营商nat后是1.1.1.1:12345，在服务器的frp能自动更新客户端的ip和端口信息。访问者直接访问http://xxx.com，xxx.com的ip指向服务器，服务器的frp返回301跳转到1.1.1.1:12345，这样访问者就可以直接访问到web服务，访问者也不用安装frp程序就可以直连web，这对一些web文件服务很有用

大多数运营商nat都是full clone nat。。。。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
建议可以使用 DDNS。

**Comment by konijiji** [comment]
> 建议可以使用 DDNS。

和ddns不一样，我的意思是客户端frp将孔打好，然后服务端frp实现301跳转到这个孔。
比如客户端有一个web服务是192.168.1.1:80，frp经过运营商nat后是1.1.1.1:12345，在服务器的frp能自动更新客户端的ip和端口信息。访问者直接访问http://xxx.com，xxx.com的ip指向服务器，服务器的frp返回301跳转到1.1.1.1:12345，这样访问者就可以直接访问到web服务，访问者也不用安装frp程序就可以直连web，这对一些web文件服务很有用
