### ISSUE TITLE
[Feature Request]  how to visit switch through frp

### ISSUE THREAD

**Issue by peter2022** [fatedier/frp#2772]
### Describe the feature request

how to visit switch or Optical Network Terminals Modem through frp?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
[Access your computer in LAN by SSH](https://github.com/fatedier/frp#access-your-computer-in-lan-by-ssh)

```
# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[switch]
type = tcp
local_ip = <Your switch IP>
local_port = 80
remote_port = 80
```
