### ISSUE TITLE
login to server failed: malformed HTTP response

### ISSUE THREAD

**Issue by JiyaoWei** [fatedier/frp#2773]
### Bug Description

[W] [service.go:103] login to server failed: malformed HTTP response "\xd4\xda\xcf\xdf\xd3û\xa7\xca\xfd\xb3\xac\xb9\xfd\xc1\xcb\xd0\xf2\xc1к\xc5\xd4\xca\xd0\xed\xa1\xa3\xc4\xfa\xd0\xe8Ҫ\xb9\xba\xc2\xf2\xbb\xf2\xc9\xfd\xbc\xb6\xc4\xfa\xb5\xc4\xd0\xf2\xc1кš\xa3"
malformed HTTP response "\xd4\xda\xcf\xdf\xd3û\xa7\xca\xfd\xb3\xac\xb9\xfd\xc1\xcb\xd0\xf2\xc1к\xc5\xd4\xca\xd0\xed\xa1\xa3\xc4\xfa\xd0\xe8Ҫ\xb9\xba\xc2\xf2\xbb\xf2\xc9\xfd\xbc\xb6\xc4\xfa\xb5\xc4\xd0\xf2\xc1кš\xa3"

### frpc Version

frp_0.35.1

### frps Version

frp_0.35.1

### System Architecture

linux/amd64

### Configurations

你好，我在client端运行nohup ./frpc -c ./frpc.ini &时报了以上的问题，求助～

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
This is the http/2 encoding format, what are you doing that is causing this? Can you refine your reproduction steps?
