### ISSUE TITLE
[Feature Request] net/http2 support

### ISSUE THREAD

**Issue by penguine** [fatedier/frp#2780]
### Describe the feature request

perhaps you want to use
https://pkg.go.dev/golang.org/x/net/http2
the performance should be better.
an example you can find here:

https://github.com/mmatczuk/go-http-tunnel/blob/master/cmd/tunneld/tunneld.go

**Comment by BecodReyes** [comment]
If you're just using the http/tcp protocol, http2 is fine for the back-end web server
frp probably doesn't need http/2

**Comment by penguine** [comment]
thx :-)
