### ISSUE TITLE
服务端下线后，启动客户端会直接退出，没有自动重连

### ISSUE THREAD

**Issue by gwnpeter** [fatedier/frp#2786]
### Bug Description

服务端下线后，重新启动客户端会直接退出，没有重连。需要等待服务端上线后，手动运行客户端。
服务端下线后，之前连接的客户端重连太频繁，建议插入更多延时，降低系统开销

### frpc Version

0.39.0

### frps Version

0.39.0

### System Architecture

windows/amd64

### Configurations

.....

### Logs

2022/01/28 20:30:02 [W] [service.go:178] [843871a99f9e5c89] reconnect to server
error: dial tcp 0.0.0.0:0->175.178.6.79:7000: connectex: No connection could be
made because the target machine actively refused it.
2022/01/28 20:30:04 [I] [service.go:175] [843871a99f9e5c89] try to reconnect to
server...
2022/01/28 20:30:05 [W] [service.go:178] [843871a99f9e5c89] reconnect to server
error: dial tcp 0.0.0.0:0->175.178.6.79:7000: connectex: No connection could be
made because the target machine actively refused it.
2022/01/28 20:30:07 [I] [service.go:175] [843871a99f9e5c89] try to reconnect to
server...
2022/01/28 20:30:08 [W] [service.go:178] [843871a99f9e5c89] reconnect to server
error: dial tcp 0.0.0.0:0->175.178.6.79:7000: connectex: No connection could be
made because the target machine actively refused it.
2022/01/28 20:30:10 [I] [service.go:175] [843871a99f9e5c89] try to reconnect to
server...
2022/01/28 20:30:11 [W] [service.go:178] [843871a99f9e5c89] reconnect to server
error: dial tcp 0.0.0.0:0->175.178.6.79:7000: connectex: No connection could be
made because the target machine actively refused it.
2022/01/28 20:30:13 [I] [service.go:175] [843871a99f9e5c89] try to reconnect to
server...
2022/01/28 20:30:14 [W] [service.go:178] [843871a99f9e5c89] reconnect to server
error: dial tcp 0.0.0.0:0->175.178.6.79:7000: connectex: No connection could be
made because the target machine actively refused it.
2022/01/28 20:30:16 [I] [service.go:175] [843871a99f9e5c89] try to reconnect to
server...

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/wiki#frpc-%E8%83%BD%E5%90%A6%E5%9C%A8%E7%B3%BB%E7%BB%9F%E5%90%AF%E5%8A%A8%E9%98%B6%E6%AE%B5%E6%97%A0%E7%BD%91%E7%BB%9C%E6%97%B6%E4%B8%80%E7%9B%B4%E7%AD%89%E5%BE%85%E8%80%8C%E4%B8%8D%E6%98%AF%E7%9B%B4%E6%8E%A5%E9%80%80%E5%87%BA
