### ISSUE TITLE
腾讯云报告了 病毒文件 Linux.Risk.Riskware.Pbow 来自 frp_0.39.0_linux_amd64/frpc

### ISSUE THREAD

**Issue by rashagu** [fatedier/frp#2787]
### Bug Description

腾讯云报告了 病毒文件 Linux.Risk.Riskware.Pbow 来自 frp_0.39.0_linux_amd64/frpc
文件MD5 `b12e4ef901e1afab7dcb0ed405320360`

### frpc Version

0.39.0

### frps Version

0.39.0

### System Architecture

linux/amd64

### Configurations

*

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
https://github.com/fatedier/frp/issues/2095

**Comment by iawes** [comment]
我直觉忽略了

**Comment by vimagick** [comment]
Tencent is evil. It is a virus in itself. 🤡
