### ISSUE TITLE
怎么才能使用多秘钥？

### ISSUE THREAD

**Issue by juelianfy** [fatedier/frp#2789]
### Describe the feature request

我想每个客户端都使用不同的秘钥，万一秘钥泄露，怕被有心之人滥用。
我也想过给每个客户端对应启一个服务端实例，但是客户量有点多，不太实际。
查看了很多文档，都不太明白，
好像OIDC可以解决，但是查了很多资料，不知道怎么使用。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
参考可以多用户管理的fork进行魔改
[ZeroDream-CN/SakuraFrp](https://github.com/ZeroDream-CN/SakuraFrp)
