### ISSUE TITLE
请问可以搭建出VPN隧道么？

### ISSUE THREAD

**Issue by xinqiu** [fatedier/frp#279]
有三台机器，A 有外网ip，B、C均为内网。C是VMware ESXi 主机。我在B的网段内是可以连接viclient的，B是C虚拟出来的一台主机。
我现在已经在A上搭建了server，B是client，C是一台我无法直接接触的主机，B可以访问C，我想问一下有没有方法可以让我通过A来访问C？因为viclient只有win版，我想的是A上建立连接到B的VPN，然后我的笔记本D连接到A上。B因为是内网，我没有B的ip，直接建不了VPN，想咨询一下有没有什么解决方案> < 麻烦大佬来解答了。

**Comment by fatedier** [comment]
参考 #178

**Comment by xinqiu** [comment]
是这样的，我如果要访问C主机，必须在windows上通过viclient这个程序才能连接，如果我笔记本连上内网，则才可以通过viclient客户端连接C主机。因为不知道viclient用的是什么端口，所以只能想让我的笔记本能像连VPN一样，直接连到内网里，因为B主机是linux，且我可以控制，不知道有什么办法能解决让win主机能够连入B的网络中。

**Comment by fatedier** [comment]
frp 仅提供了转发请求到内网指定端口这个功能，至于如何实现其他的需求，需要你自己考虑一下。

**Comment by plus1998** [comment]
刚好在实现外网访问vcenter。在内网部署VPN + frp的udp端口透传是可以成功访问到的
