### ISSUE TITLE
[Feature Request] 添加对s390x架构的支持

### ISSUE THREAD

**Issue by Lemonawa** [fatedier/frp#2790]
### Describe the feature request

对于s390x架构的介绍： https://en.wikipedia.org/wiki/Linux_on_IBM_Z
希望添加对此架构的支持，我手中有两台机器想要使用却用不了

### Describe alternatives you've considered

none，不过golang是可以支持s390x的

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
如果 go 本身支持，那么你可以自己下载源码编译，对于不是广泛使用的架构就不上传编译好的包了。

**Comment by Lemonawa** [comment]
> 如果 go 本身支持，那么你可以自己下载源码编译，对于不是广泛使用的架构就不上传编译好的包了。

好的
