### ISSUE TITLE
Moonlight-qt client from network with default ports blocked

### ISSUE THREAD

**Issue by ermac500** [fatedier/frp#2793]
### Bug Description

My Nvdia gamestream PC ( server ) has all the ports open and works remotely from about any network except one. Would frp let me bypass the client network blocked ports?
Moonlight Gamestream client states many of the ports are unnaccessible:
![image](https://user-images.githubusercontent.com/7088719/153161135-57ed0aa8-4539-4a79-9c3a-89acb575b8a9.png)

Did I not understand correctly how frp works? doesn't all the traffic go trough the bind_port(1194)?

### frpc Version

0.36.1

### frps Version

0.36.1

### System Architecture

windows/amd64

### Configurations

frps.ini
[common]
bind_port = 1194
bind_addr = 0.0.0.0
token = 5555
allow_ports = 47000-49000,5353

frpc.ini
[common]
server_addr = MYIP
server_port = 1194
token = 5555

[nvidia-stream-tcp-1]
type = tcp
local_ip = 127.0.0.1
local_port = 47984
remote_port = 47984

[nvidia-stream-tcp-2]
type = tcp
local_ip = 127.0.0.1
local_port = 47989
remote_port = 47989

[nvidia-stream-tcp-3]
type = tcp
local_ip = 127.0.0.1
local_port = 48010
remote_port = 48010

[nvidia-stream-udp-1]
type = udp
local_ip = 127.0.0.1
local_port = 5353
remote_port = 5353

[nvidia-stream-udp-2]
type = udp
local_ip = 127.0.0.1
local_port = 47998
remote_port = 47998

[nvidia-stream-udp-3]
type = udp
local_ip = 127.0.0.1
local_port = 47999
remote_port = 47999

[nvidia-stream-udp-4]
type = udp
local_ip = 127.0.0.1
local_port = 48000
remote_port = 48000

[nvidia-stream-udp-5]
type = udp
local_ip = 127.0.0.1
local_port = 48002
remote_port = 48002

[nvidia-stream-udp-6]
type = udp
local_ip = 127.0.0.1
local_port = 48010
remote_port = 48010

**Comment by fatedier** [comment]
I'm not sure, just give it a try.

**Comment by ermac500** [comment]
I gave it. the photo was the result.

**Comment by apoklyps3** [comment]
bump on this?

**Comment by apoklyps3** [comment]
I'm having  a similar issue. I need to bypass the blocked ports on a client computer and no ideea how to achieve this

**Comment by apoklyps3** [comment]
no support offered it seems

**Comment by apoklyps3** [comment]
how is this stale with no answer provided?
