### ISSUE TITLE
server_addr 配置优化

### ISSUE THREAD

**Issue by zuozhehao** [fatedier/frp#2796]
### Describe the feature request

```
[common]
server_addr = domain.com
```
server_addr 使用域名配置时，域名绑定的ip变化，frpc 连接的ip未跟随变化。

当使用域名时心跳检测前增加DNS解析，或配置支持多IP 如`server_addr = 192.168.1.100,192.168.1.200`

在多台服务器部署frps，域名做了灾备自动切换，提高可用性。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by 172721404** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已经收到你给我发的邮件，谢谢你...

**Comment by fatedier** [comment]
关闭之前的服务端后，客户端会重连，就可以正常连接到新的地址。

**Comment by zuozhehao** [comment]
> 关闭之前的服务端后，客户端会重连，就可以正常连接到新的地址。

A主B备，A挂了后DNS自动切到B，Frpc也会切换到B(DNS生效后)，这个正常。
当A恢复正常后DNS切回A，Frpc还是保持使用B，这个时候域名连接就不正常了。
有没好的方法 @fatedier

**Comment by fatedier** [comment]
目前没有平滑的迁移方式，只能通过断开和客户端的连接，让客户端重连到新的节点。

会有集群方案的支持计划，包括针对大规模客户端的优化，但应该不会开源，相对来说这些已经是一些企业级的需求，目前已经有一些公司有这方面的需求沟通和付费意愿，所以后续应该会对这样的场景提供针对性的解决方案。
