### ISSUE TITLE
[Feature Request] frp with sslh

### ISSUE THREAD

**Issue by vay3t** [fatedier/frp#2797]
### Describe the feature request

how could i use frp with sslh, specifically with bind_port?

### Describe alternatives you've considered

i think it would be possible with unix socket

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by vay3t** [comment]
I understand, what I need is to know which is the byte regex that I must use to recognize that it is an frp connection

**Comment by fatedier** [comment]
> I understand, what I need is to know which is the byte regex that I must use to recognize that it is an frp connection

Maybe complex and unfixed. You'd better not rely on this.
