### ISSUE TITLE
utils\pcrypto\Encrypt 加密问题

### ISSUE THREAD

**Issue by chmis8000** [fatedier/frp#28]
目前是gzip/ aes / base64 顺序执行：压缩+aes加密+ASCII转码。
两个问题：
1. 能否去掉 aes（新增配置项），以便 c端带宽有限的 节省上传带宽。
2. 能否去除 base64， 这个是仅仅是为了分包吗？有没有更好的办法，分包而不需要重新编码，毕竟base64是http协议才更有意义，若传输的数据都是二进制数据，多次转义增加了带宽、CPU开销。
顺带，个人认为go的优势是接近c、C++的性能，那实现某些软件细节时 也应该考虑极致的性能、高并发。望考虑

**Comment by vashstorm** [comment]
现在处理分包是通过换行，所以要用到 base64， 后面的版本可能考虑的用tlv来替代， 这样就可去掉base64。也可以提供加密和压缩是否启用的配置选项。

**Comment by fatedier** [comment]
开发完成后再关闭此 issue 吧。
