### ISSUE TITLE
穿透了以后该如何配置aria2？

### ISSUE THREAD

**Issue by ayellowcat** [fatedier/frp#280]
感谢大神，frp穿透成功了，但我主要想用来远程控制aria2下载和sftp，这该如何配置呢

**Comment by 1oo1** [comment]
巧了，正好重装 aria2+frp 记录下来了，你参考下 [在ac68u上部署aria2](https://1oo1.github.io/2017/03/18/%E5%9C%A8ac68u%E4%B8%8A%E9%83%A8%E7%BD%B2aria2/)
