### ISSUE TITLE
How can a client connect to a server through ssh-key?

### ISSUE THREAD

**Issue by cqiwencom** [fatedier/frp#2800]
### Describe the feature request

How can a client connect to a server through ssh-key?

My VM server uses ssh-key. When the client connects to the server through SSH, you need to specify the local ssh-key path.Do you have the corresponding configuration parameters in the frpc.ini file?

### Describe alternatives you've considered

I think we can add a parameter:
[common]
server_addr = x.x.x.x
server_port = 7000
ssh-key = ssh-key-server01.key

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
frp don't use ssh protocol. You don't need ssh-key to connect your frps.

**Comment by packet-sent** [comment]
> ### Describe the feature request
> 
> How can a client connect to a server through ssh-key?
> 
> My VM server uses ssh-key. When the client connects to the server through SSH, you need to specify the local ssh-key path.Do you have the corresponding configuration parameters in the frpc.ini file?
> ### Describe alternatives you've considered
> 
> I think we can add a parameter: [common] server_addr = x.x.x.x server_port = 7000 ssh-key = ssh-key-server01.key
> ### Affected area
> 
>     * [ ]  Docs
> 
>     * [ ]  Installation
> 
>     * [ ]  Performance and Scalability
> 
>     * [ ]  Security
> 
>     * [ ]  User Experience
> 
>     * [ ]  Test and Release
> 
>     * [ ]  Developer Infrastructure
> 
>     * [ ]  Client Plugin
> 
>     * [ ]  Server Plugin
> 
>     * [ ]  Extensions
> 
>     * [ ]  Others

If you want to use SSH for proxying then frp isn't the solution but you can just start a local proxy server on the client and ssh to a server with a remote forward port of the local server for it to be accessible by the SSH server.
