### ISSUE TITLE
[Feature Request] How to expose multiple local web servers with a single public domain

### ISSUE THREAD

**Issue by JimBeam2019** [fatedier/frp#2801]
### Describe the feature request

Hi there, I've experimented with the "Visit your web service in LAN by custom domains" example and it worked well with one local web server, but I was wondering if it is possible to expose multiple local web servers, say hundreds of them, with one public domain. Please any advice will be appreciated.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Try https://github.com/fatedier/frp#load-balancing

**Comment by JimBeam2019** [comment]
> Try https://github.com/fatedier/frp#load-balancing

Thank you for your quick reply, though I think there is a misunderstanding.

What I meant was the vhost can only connect to one local web server, but it fails to connect to a second one. It simply returned error message `[W] [control.go:447] [128472af6ade081b] new proxy [web] error: router config conflict`. So, my question is if I would like to set a proxy server in the cloud with a public domain to expose multiple local web servers, how can I do that using frp?

**Comment by fatedier** [comment]
`load-balancing` is what you want. Requests to same domain will route to different local web server round robin.

**Comment by JimBeam2019** [comment]
> `load-balancing` is what you want. Requests to same domain will route to different local web server round robin.

Excuse me, I don't really get what you mean. The `load-balancing` seems to be running in the local web server by configuring the **frpc.ini** file. Are you suggesting doing the same configuration on the **frps.ini** file in public vhost?

**Comment by albenex** [comment]
I've same request as OP:
I have different web services (dump1090 daemon, home assistant interface, car controller interface etc..)
FRP works great tunneling SSH connections and first web-service configured inside FRPC.ini on Server "B". 
further web-services configured won't work.

desired behavior would be configuring FRPC.ini like this:

```
# Home assistant 
[web]
type = tcp
local_port = 8123
remote_port = 5003
local_ip = 127.0.0.1

# dump1090 
type = tcp
local_port = 80
remote_port = 5001
local_ip = 127.0.0.1

# car controller
type = tcp
local_port = 5000
remote_port = 5000
local_ip = 127.0.0.1
```


load balancing feature is meant for a number of duplicate web services hooked to different ports but exposed with same one.

here we're requesting multiple web services hooked to different ports, exposed to different ports.

**Comment by fatedier** [comment]
> I've same request as OP: I have different web services (dump1090 daemon, home assistant interface, car controller interface etc..) FRP works great tunneling SSH connections and first web-service configured inside FRPC.ini on Server "B". further web-services configured won't work.
> 
> desired behavior would be configuring FRPC.ini like this:
> 
> ```
> # Home assistant 
> [web]
> type = tcp
> local_port = 8123
> remote_port = 5003
> local_ip = 127.0.0.1
> 
> # dump1090 
> [web]
> type = tcp
> local_port = 80
> remote_port = 5001
> local_ip = 127.0.0.1
> 
> # car controller
> [web]
> type = tcp
> local_port = 5000
> remote_port = 5000
> local_ip = 127.0.0.1
> ```
> 
> load balancing feature is meant for a number of duplicate web services hooked to different ports but exposed with same one.
> 
> here we're requesting multiple web services hooked to different ports, exposed to different ports.

```ini
# Home assistant 
[web-home-assistant]
type = tcp
local_port = 8123
remote_port = 5003
local_ip = 127.0.0.1

# dump1090 
[web-dump1090]
type = tcp
local_port = 80
remote_port = 5001
local_ip = 127.0.0.1

# car controller
[web-car-controller]
type = tcp
local_port = 5000
remote_port = 5000
local_ip = 127.0.0.1
```

**Comment by albenex** [comment]
> 

thank you very much! it worked

**Comment by didibaba** [comment]
@albenex how to configure frps.ini of the server for your case?
