### ISSUE TITLE
Wildcard for http Services

### ISSUE THREAD

**Issue by alturismo** [fatedier/frp#2804]
### Describe the feature request

use wildcard subdomain in terms FRP is ahead of a nginx reverse proxy webserver

or may this is not the real usecase as FRP is already a RP by itself, i also struggle with the forward ip ... but this would be my next step in terms wildcard is possible/implemented.

### Describe alternatives you've considered

use tcp instead http/s, but then the real ip forwarding seems to be impossible, and as there are rules on the nginx server for geo blocking, fail2ban, ... would be nice ;)

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
You can use custom domains instead of studomain.

**Comment by fatedier** [comment]
`custom_domains = my-domain.de` -> `custom_domains = *.my-domain.de`

**Comment by alturismo** [comment]
> `custom_domains = my-domain.de` -> `custom_domains = *.my-domain.de`

no idea what i did before, but yes, that now worked, thanks alot ;)

for the issue with

proxy_protocol_version = v1, v2, ...

shell i rather open another issue ?

**Comment by fatedier** [comment]
What's your problem about proxy protocol?

**Comment by alturismo** [comment]
as soon as i set proxy_protocol_version = v1 or v2, no more connection to nginx is possible.

i interpreted the proxy_protocol_version is to forward the x-real ip from the client to the frpc destination, in my term its a nginx server.

i also dont get any real errors in the real time logging from frps or frpc, sample

![image](https://user-images.githubusercontent.com/8406490/154667123-e74dc487-8a7d-4877-834c-f9d832210a63.png)

i end up with this in the browser, no connection due
ERR_SSL_PROTOCOL_ERROR

from frps log (source ip redone)
2022/02/18 11:40:09 [I] [proxy.go:179] [0a6137ada86241af] [https] get a user connection [12.13.14.15:33175]

**Comment by alturismo** [comment]
or is this not possible in this usecase, www client -> FRPS -> FRPC -> Nginx Reverse Proxy -> Services (app1, app2, app3, ...) to use the real ip mode.

Reason im looking into this, currently tested the ssh reverse tunnel but there its not possible to forward the www client ip to the nginx Server, and as there should be some protection left like geo blocking, fail2ban, ... this is obsolete without real ip forwarding.

**Comment by alturismo** [comment]
> You should update your nginx config to identify proxy protocol.

thanks for the hint, now only left howto get xreal ip with the proxy protocol ;)
i have to watch as the FRP solution here is meant as fallback solution, so i dont want to loose xreal ip in "normal" usage.

thanks again for your help

**Comment by alturismo** [comment]
can be closed for the Topic Question, wildcard is working as expected, i give up on the project with real ip forwarding, i followed the nginx tut but i stay on local server as source ip in all apps

https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/#:~:text=To%20configure%20NGINX%20to%20accept,%3B%20%23...%20%7D%20%7D

thanks again, if i wouldnt resist on x real ip it would be the perfect solution ;) but seems it doesnt fit in my enviroment or i have some bad setting somewhere ;)

but 👍 for this nice app

**Comment by alturismo** [comment]
ok, after some more digging i figured it and its working ;)

thanks for the pointers, sadly its a only working in a one way solution, either behind nginx directly (withoud mods) OR behind the FRP solution (with nginx mods).

but thats a different story ... ;)

may as note why, i arranged myself a Fallback LTE Internet solution if my cable is failing, so in this situation i switch to mobile network, as its behind NAT i cant connect directly anymore and need a reverse tunnel, which i accomplished with ssl reverse tunneling, now there was the point as ssl reverse has no way to forward client's real ip ... so i started today morning with this and voila, very nice.

thanks again 👍
