### ISSUE TITLE
id token issued by a different provider

### ISSUE THREAD

**Issue by sunzeteng9** [fatedier/frp#2806]
### Bug Description

register control error: invalid OIDC token in login: oidc: id token issued by a different provider, expected "http://127.0.0.1:8086/" got ""

### frpc Version

frp_0.39.1_windows_amd64

### frps Version

frp_0.39.1_windows_amd64

### System Architecture

_windows

### Configurations

[common]
bind_port = 7001
server_addr = 127.0.0.1
dashboard_port = 65533

authentication_method = oidc
authenticate_heartbeats = true
oidc_audience = openid
oidc_issuer = http://127.0.0.1:8086/

[common]
server_addr = 127.0.0.1
server_port = 7001

authentication_method = oidc
oidc_client_id = wYqmpgj04puuyPUeRKgK9zP1IYi5X1kG
oidc_client_secret = z2RHeCn1c0hBSVGhfM6jO1kMnRQKGq5cHEu5U4UF
oidc_audience = openid
oidc_token_endpoint_url = http://127.0.0.1:8086/oauth/token

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingtianbaihua** [comment]
1. 猜测是你的 oidc_issuer = http://127.0.0.1:8086/  链接有问题，maybe 是一个  oidc_issuer = http://127.0.0.1:8086/xxx/oidc  这样的或者带个其他 path，可以检查下。
2. 确认你搭建的这个 oidc 服务，是否为 client credentials 的授权方式。 Oauth2.0 支持很多种授权方式。
3. 方便起见，可以去申请一个 auth0 服务测试跑起来，对理解这块有帮助。

[https://github.com/fatedier/frp/issues/2822](url)
