### ISSUE TITLE
求添加服务器的均衡负载

### ISSUE THREAD

**Issue by 666sxrA** [fatedier/frp#2808]
### Describe the feature request

现在只有客户端可以利用本地端口来实现均衡负载，如果我有多个服务器我想多个服务端来组成均衡负载

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
需求过于模糊不清

若是需要多frps负载均衡，请考虑多开frpc
