### ISSUE TITLE
游戏转发

### ISSUE THREAD

**Issue by MarilynPalmer** [fatedier/frp#2811]
### Bug Description

有些游戏会二次转发导致无法连接，这个怎么解决

登录正常，进游戏就会被转发到下面地址127.0.0.1

### frpc Version

0.39.1

### frps Version

0.39.1

### System Architecture

linux/amd64

### Configurations

[common]
server_addr = 
server_port = 7000

[]
type = udp
local_ip = 127.0.0.1
local_port = 19132
remote_port = 19132

[_tcp]
type = tcp
local_ip = 127.0.0.1
local_port = 30002
remote_port = 30002

[_udp]
type = udp
local_ip = 127.0.0.1
local_port = 30002
remote_port = 30002

[_game_tcp]
type = tcp
local_ip = 127.0.0.1
local_port = 27005
remote_port = 27005

[_game_udp]
type = udp
local_ip = 127.0.0.1
local_port = 27005
remote_port = 27005

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
描述不清

看端口应该为minecraft be

尝试在服务端套上代理并开启proxy protocol协议

**Comment by MarilynPalmer** [comment]
> 描述不清
> 
> 看端口应该为minecraft be
> 
> 尝试在服务端套上代理并开启proxy protocol协议

启动游戏时通过30002端口连接服务端显示ip 127.0.0.1 但可以登录，到了房间内开始游戏或加入游戏会转到本地127.0.0.1地址导致无法连接

**Comment by BecodReyes** [comment]
描述依旧不清，请提供 `游戏日志` `frp的双端日志` `游戏服务端配置`
