### ISSUE TITLE
在移动宽带+香港线路下似乎有断流

### ISSUE THREAD

**Issue by zhezhe168** [fatedier/frp#2813]
### Bug Description

此问题只在移动宽带+香港线路下出现，如果是电信宽带，或者移动+其他地区线路没有这个问题。

一段时间后（30分钟到6小时不等，没有规律，最长24小时内肯定会发生一次）疑似断流，客户端掉线后就无法再连接上服务端

客户端和服务端都运行正常，必须重启客户端或者服务端，才能恢复连接

试了不同版本组合，都是相同情况，怀疑是遇到了移动QoS，但无法自动重连

### frpc Version

000

### frps Version

000

### System Architecture

000

### Configurations

000

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [x] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [x] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by godsontop** [comment]
联通宽带+香港线路也有同样问题

**Comment by OldGodShen** [comment]
这和frp有什么关系
