### ISSUE TITLE
frp不能穿透访问svn VisualSVN-Server的https的地址

### ISSUE THREAD

**Issue by chenpan1224** [fatedier/frp#2815]
### Bug Description

frp不能穿透访问svn VisualSVN-Server的https的地址

### frpc Version

0.38.0

### frps Version

0.38.0

### System Architecture

windows server 2012/amd64

### Configurations

[common]
server_addr = 云主机ip
server_port = 7000
log_file = ./frpc.log
log_level = trace
log_max_days = 7
login_fail_exit = false

[svn]
type = tcp
local_ip = 192.168.3.248
local_port = 443
remote_port = 6001

### Logs

2022/02/23 14:38:11 [D] [control.go:322] [129f269493231632] send heartbeat to server
2022/02/23 14:38:11 [D] [control.go:353] [129f269493231632] receive heartbeat from server
2022/02/23 14:38:28 [D] [proxy_wrapper.go:231] [129f269493231632] [svn] start a new work connection, localAddr: 192.168.3.248:49927 remoteAddr: 云主机ip:7000
2022/02/23 14:38:28 [T] [proxy.go:738] [129f269493231632] [svn] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/23 14:38:28 [D] [proxy.go:800] [129f269493231632] [svn] join connections, localConn(l[192.168.3.248:50469] r[192.168.3.248:443]) workConn(l[192.168.3.248:49927] r[云主机ip:7000])
2022/02/23 14:38:28 [D] [proxy.go:808] [129f269493231632] [svn] join connections closed
2022/02/23 14:38:28 [D] [proxy_wrapper.go:231] [129f269493231632] [svn] start a new work connection, localAddr: 192.168.3.248:49927 remoteAddr: 云主机ip:7000
2022/02/23 14:38:28 [T] [proxy.go:738] [129f269493231632] [svn] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/23 14:38:28 [D] [proxy.go:800] [129f269493231632] [svn] join connections, localConn(l[192.168.3.248:50470] r[192.168.3.248:443]) workConn(l[192.168.3.248:49927] r[云主机ip:7000])
2022/02/23 14:38:28 [D] [proxy.go:808] [129f269493231632] [svn] join connections closed
2022/02/23 14:38:28 [D] [proxy_wrapper.go:231] [129f269493231632] [svn] start a new work connection, localAddr: 192.168.3.248:49927 remoteAddr: 云主机ip:7000
2022/02/23 14:38:28 [T] [proxy.go:738] [129f269493231632] [svn] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/23 14:38:28 [D] [proxy.go:800] [129f269493231632] [svn] join connections, localConn(l[192.168.3.248:50471] r[192.168.3.248:443]) workConn(l[192.168.3.248:49927] r[云主机ip:7000])
2022/02/23 14:38:28 [D] [proxy.go:808] [129f269493231632] [svn] join connections closed
2022/02/23 14:38:28 [D] [proxy_wrapper.go:231] [129f269493231632] [svn] start a new work connection, localAddr: 192.168.3.248:49927 remoteAddr: 云主机ip:7000
2022/02/23 14:38:28 [T] [proxy.go:738] [129f269493231632] [svn] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/23 14:38:28 [D] [proxy.go:800] [129f269493231632] [svn] join connections, localConn(l[192.168.3.248:50472] r[192.168.3.248:443]) workConn(l[192.168.3.248:49927] r[云主机ip:7000])
2022/02/23 14:38:28 [D] [proxy.go:808] [129f269493231632] [svn] join connections closed
2022/02/23 14:38:28 [D] [proxy_wrapper.go:231] [129f269493231632] [svn] start a new work connection, localAddr: 192.168.3.248:49927 remoteAddr: 云主机ip:7000
2022/02/23 14:38:28 [T] [proxy.go:738] [129f269493231632] [svn] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/23 14:38:28 [D] [proxy.go:800] [129f269493231632] [svn] join connections, localConn(l[192.168.3.248:50473] r[192.168.3.248:443]) workConn(l[192.168.3.248:49927] r[云主机ip:7000])
2022/02/23 14:38:28 [D] [proxy.go:808] [129f269493231632] [svn] join connections closed
2022/02/23 14:38:28 [D] [proxy_wrapper.go:231] [129f269493231632] [svn] start a new work connection, localAddr: 192.168.3.248:49927 remoteAddr: 云主机ip:7000
2022/02/23 14:38:28 [T] [proxy.go:738] [129f269493231632] [svn] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/23 14:38:28 [D] [proxy.go:800] [129f269493231632] [svn] join connections, localConn(l[192.168.3.248:50474] r[192.168.3.248:443]) workConn(l[192.168.3.248:49927] r[云主机ip:7000])
2022/02/23 14:38:28 [D] [proxy.go:808] [129f269493231632] [svn] join connections closed
2022/02/23 14:38:28 [D] [proxy_wrapper.go:231] [129f269493231632] [svn] start a new work connection, localAddr: 192.168.3.248:49927 remoteAddr: 云主机ip:7000
2022/02/23 14:38:28 [T] [proxy.go:738] [129f269493231632] [svn] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/23 14:38:28 [D] [proxy.go:800] [129f269493231632] [svn] join connections, localConn(l[192.168.3.248:50475] r[192.168.3.248:443]) workConn(l[192.168.3.248:49927] r[云主机ip:7000])
2022/02/23 14:38:28 [D] [proxy.go:808] [129f269493231632] [svn] join connections closed
2022/02/23 14:38:28 [D] [proxy_wrapper.go:231] [129f269493231632] [svn] start a new work connection, localAddr: 192.168.3.248:49927 remoteAddr: 云主机ip:7000
2022/02/23 14:38:28 [T] [proxy.go:738] [129f269493231632] [svn] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/23 14:38:28 [D] [proxy.go:800] [129f269493231632] [svn] join connections, localConn(l[192.168.3.248:50476] r[192.168.3.248:443]) workConn(l[192.168.3.248:49927] r[云主机ip:7000])
2022/02/23 14:38:28 [D] [proxy.go:808] [129f269493231632] [svn] join connections closed
2022/02/23 14:38:28 [D] [proxy_wrapper.go:231] [129f269493231632] [svn] start a new work connection, localAddr: 192.168.3.248:49927 remoteAddr: 云主机ip:7000
2022/02/23 14:38:28 [T] [proxy.go:738] [129f269493231632] [svn] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/23 14:38:28 [D] [proxy.go:800] [129f269493231632] [svn] join connections, localConn(l[192.168.3.248:50477] r[192.168.3.248:443]) workConn(l[192.168.3.248:49927] r[云主机ip:7000])
2022/02/23 14:38:28 [D] [proxy.go:808] [129f269493231632] [svn] join connections closed
2022/02/23 14:38:28 [D] [proxy_wrapper.go:231] [129f269493231632] [svn] start a new work connection, localAddr: 192.168.3.248:49927 remoteAddr: 云主机ip:7000
2022/02/23 14:38:28 [T] [proxy.go:738] [129f269493231632] [svn] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/23 14:38:28 [D] [proxy.go:800] [129f269493231632] [svn] join connections, localConn(l[192.168.3.248:50478] r[192.168.3.248:443]) workConn(l[192.168.3.248:49927] r[云主机ip:7000])
2022/02/23 14:38:28 [D] [proxy.go:808] [129f269493231632] [svn] join connections closed
2022/02/23 14:38:28 [D] [proxy_wrapper.go:231] [129f269493231632] [svn] start a new work connection, localAddr: 192.168.3.248:49927 remoteAddr: 云主机ip:7000
2022/02/23 14:38:28 [T] [proxy.go:738] [129f269493231632] [svn] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/23 14:38:28 [D] [proxy.go:800] [129f269493231632] [svn] join connections, localConn(l[192.168.3.248:50479] r[192.168.3.248:443]) workConn(l[192.168.3.248:49927] r[云主机ip:7000])
2022/02/23 14:38:28 [D] [proxy.go:808] [129f269493231632] [svn] join connections closed

### Steps to reproduce

1. 启动frp服务器（Ubuntu）
2. 启动windows server 2012 frp 客户端
3. 在window11 上使用TortoiseSVN客户端访问https://域名:6001/svn/ 就不能访问，访问https://云主机IP:6001/svn/ 就可以访问。云是阿里云。
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by BecodReyes** [comment]
> 访问https://**域名**:6001/svn/ 就不能访问，访问https://**云主机IP**:6001/svn/就可以访问

考虑域名解析是否配置正确

**Comment by chenpan1224** [comment]
域名解析应该是正确的。因为我还配置了一个git服务器，用sourcetree克隆的时候用域名地址，显示是一个git库。

**Comment by BecodReyes** [comment]
需要更多的信息，比如直接访问和TortoiseSVN的日志

考虑是否是因为https证书导致的问题

**Comment by chenpan1224** [comment]
我在阿里云申请了备案，就能访问https://域名:6001/svn/ 了，应该是之前阿里云限制了https的流量。
