### ISSUE TITLE
frpc一直向frps发起ssh连接请求，导致frpc流量消耗过快

### ISSUE THREAD

**Issue by w435044190** [fatedier/frp#2817]
### Bug Description

同一个frpc一直不停地向frps发起链接（一秒内几十次），从frps日志中可以看到打印了超多“get a user connection”，但是frpc日志中无异常，导致frpc端流量消耗异常；在客户端日志里发现好多的“start a new work connection”以及"join connections"，“join connections closed”

### frpc Version

0.39.1

### frps Version

0.39.1

### System Architecture

linux/amd64

### Configurations

[common]
bind_addr = 0.0.0.0
bind_port = 7000
bind_udp_port = 7001
kcp_bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
dashboard_addr = 0.0.0.0
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin
enable_prometheus = true
log_file = ./frps.log
log_level = info
log_max_days = 3
disable_log_color = false
detailed_errors_to_client = true
authentication_method = token
authenticate_heartbeats = false
authenticate_new_work_conns = false
token = 
oidc_issuer =
oidc_audience =
oidc_skip_expiry_check = false
oidc_skip_issuer_check = false
allow_ports = 2000-3000,3001,3003,4000-50000
max_pool_count = 5
max_ports_per_client = 0
tls_only = false
subdomain_host = frps.com
tcp_mux = true
udp_packet_size = 1500

### frps.log
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44012]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:43956]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44070]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44122]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44176]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:42600]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44230]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44290]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44342]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44398]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44452]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:42818]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44506]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44558]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44614]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44668]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44724]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44778]
2022/02/21 21:44:42 [I] [proxy.go:179] [6412cc7e06237c52] [ssh_wly] get a user connection [137.184.69.219:43640]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44830]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44882]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44942]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:44996]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:45052]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:45104]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:45156]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:45212]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:45266]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:45316]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:45380]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:45438]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:45486]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:45544]
2022/02/21 21:44:42 [I] [proxy.go:179] [7c65ab551aaed169] [ssh_thty] get a user connection [137.184.132.220:45596]
### frpc.log
2022/02/25 02:36:06 [D] [proxy_wrapper.go:231] [3b60800f703a604b] [ssh-ryzg] start a new work connection, localAddr: 10.171.70.82:36794 remoteAddr: 121.199.3.33:7000
2022/02/25 02:36:06 [T] [proxy.go:735] [3b60800f703a604b] [ssh-ryzg] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/25 02:36:06 [D] [proxy.go:797] [3b60800f703a604b] [ssh-ryzg] join connections, localConn(l[127.0.0.1:60778] r[127.0.0.1:22]) workConn(l[10.171.70.82:36794] r[121.199.3.33:7000])
2022/02/25 02:36:06 [D] [proxy.go:805] [3b60800f703a604b] [ssh-ryzg] join connections closed
2022/02/25 02:36:07 [D] [proxy.go:805] [3b60800f703a604b] [ssh-ryzg] join connections closed
2022/02/25 02:36:07 [D] [proxy_wrapper.go:231] [3b60800f703a604b] [ssh-ryzg] start a new work connection, localAddr: 10.171.70.82:36794 remoteAddr: 121.199.3.33:7000
2022/02/25 02:36:07 [T] [proxy.go:735] [3b60800f703a604b] [ssh-ryzg] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/25 02:36:07 [D] [proxy.go:797] [3b60800f703a604b] [ssh-ryzg] join connections, localConn(l[127.0.0.1:60780] r[127.0.0.1:22]) workConn(l[10.171.70.82:36794] r[121.199.3.33:7000])
2022/02/25 02:36:07 [D] [proxy.go:805] [3b60800f703a604b] [ssh-ryzg] join connections closed
2022/02/25 02:36:07 [D] [proxy_wrapper.go:231] [3b60800f703a604b] [ssh-ryzg] start a new work connection, localAddr: 10.171.70.82:36794 remoteAddr: 121.199.3.33:7000
2022/02/25 02:36:07 [T] [proxy.go:735] [3b60800f703a604b] [ssh-ryzg] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/25 02:36:07 [D] [proxy.go:797] [3b60800f703a604b] [ssh-ryzg] join connections, localConn(l[127.0.0.1:60782] r[127.0.0.1:22]) workConn(l[10.171.70.82:36794] r[121.199.3.33:7000])
2022/02/25 02:36:07 [D] [proxy.go:805] [3b60800f703a604b] [ssh-ryzg] join connections closed
2022/02/25 02:36:07 [D] [proxy.go:805] [3b60800f703a604b] [ssh-ryzg] join connections closed
2022/02/25 02:36:08 [D] [proxy_wrapper.go:231] [3b60800f703a604b] [ssh-ryzg] start a new work connection, localAddr: 10.171.70.82:36794 remoteAddr: 121.199.3.33:7000
2022/02/25 02:36:08 [T] [proxy.go:735] [3b60800f703a604b] [ssh-ryzg] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/25 02:36:08 [D] [proxy.go:797] [3b60800f703a604b] [ssh-ryzg] join connections, localConn(l[127.0.0.1:60784] r[127.0.0.1:22]) workConn(l[10.171.70.82:36794] r[121.199.3.33:7000])
2022/02/25 02:36:08 [D] [proxy.go:805] [3b60800f703a604b] [ssh-ryzg] join connections closed
2022/02/25 02:36:08 [D] [proxy_wrapper.go:231] [3b60800f703a604b] [ssh-ryzg] start a new work connection, localAddr: 10.171.70.82:36794 remoteAddr: 121.199.3.33:7000
2022/02/25 02:36:08 [T] [proxy.go:735] [3b60800f703a604b] [ssh-ryzg] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/25 02:36:08 [D] [proxy.go:797] [3b60800f703a604b] [ssh-ryzg] join connections, localConn(l[127.0.0.1:60786] r[127.0.0.1:22]) workConn(l[10.171.70.82:36794] r[121.199.3.33:7000])
2022/02/25 02:36:08 [D] [proxy.go:805] [3b60800f703a604b] [ssh-ryzg] join connections closed
2022/02/25 02:36:08 [D] [proxy_wrapper.go:231] [3b60800f703a604b] [ssh-ryzg] start a new work connection, localAddr: 10.171.70.82:36794 remoteAddr: 121.199.3.33:7000
2022/02/25 02:36:08 [T] [proxy.go:735] [3b60800f703a604b] [ssh-ryzg] handle tcp work connection, use_encryption: false, use_compression: false
2022/02/25 02:36:08 [D] [proxy.go:797] [3b60800f703a604b] [ssh-ryzg] join connections, localConn(l[127.0.0.1:60788] r[127.0.0.1:22]) workConn(l[10.171.70.82:36794] r[121.199.3.33:7000])
2022/02/25 02:36:08 [D] [proxy.go:805] [3b60800f703a604b] [ssh-ryzg] join connections closed
2022/02/25 02:36:09 [D] [proxy.go:805] [3b60800f703a604b] [ssh-ryzg] join connections closed
2022/02/25 02:36:09 [D] [proxy.go:805] [3b60800f703a604b] [ssh-ryzg] join connections closed
2022/02/25 02:36:09 [D] [proxy.go:805] [3b60800f703a604b] [ssh-ryzg] join connections closed
2022/02/25 02:36:09 [D] [proxy.go:805] [3b60800f703a604b] [ssh-ryzg] join connections closed
2022/02/25 02:36:09 [D] [proxy.go:805] [3b60800f703a604b] [ssh-ryzg] join connections closed
2022/02/25 02:36:09 [D] [proxy.go:805] [3b60800f703a604b] [ssh-ryzg] join connections closed
2022/02/25 02:36:09 [D] [proxy.go:805] [3b60800f703a604b] [ssh-ryzg] join connections closed
### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
IP | 位置 | 发现时间 | 更新时间 | 情报内容 | 状态
-- | -- | -- | -- | -- | --
137.184.132.220 | 美国 新泽西州 皮斯卡特维 | 2022-02-23 | 2022-02-24 | 扫描 | 有效

恶意爆破，尝试更换ssh端口

**Comment by w435044190** [comment]
> 

这个ip问题不清楚为什么国内的物联网卡变成了国外的ip，但是能确认这些请求不是其它地方发起的，是我的frpc终端发起的，我贴了frpc的日志

**Comment by hao0616** [comment]
我也有这个问题，不过我的是frpc不停连接自己的地址，频率很高，导致死机的那种

**Comment by w435044190** [comment]
> oin connections,

麻烦问下frpc日志中不停地start a new work connection是什么原因导致的呢

**Comment by jukrb0x** [comment]
> > user connection 是指你暴露出去的端口有新的用户连接。并不是 frpc 连接到 frps。
> > 比如你暴露了一个网站，当有国外的 IP 请求你的网站时，就会看到这样的日志。
> 
> **恶意爆破，尝试更换ssh端口** 然后关闭issue

用证书登录，关闭密码登录的权限，应该可以解决这个问题。
