### ISSUE TITLE
custom listener for [xxx] is repeated & [xxx] start error: port already used

### ISSUE THREAD

**Issue by jonozw** [fatedier/frp#2819]
### Bug Description

run frps 0.39.1 on linux amd64 server. 

start frpc client, and got error message. 

主要是这两个问题
1. 2022/02/14 11:28:57 [W] [control.go:179] [31f6cea8abecc2c6] [SR_USER_AAA] start error: custom listener for [SR_USER_AAA] is repeated
2. 2022/02/14 11:28:57 [W] [control.go:179] [31f6cea8abecc2c6] [WEB_FFF] start error: port already used

### frpc Version

0.39.1

### frps Version

0.39.1

### System Architecture

linux/amd64

### Configurations

NA

### Logs

主要是这两个问题
1. 2022/02/14 11:28:57 [W] [control.go:179] [31f6cea8abecc2c6] [SR_USER_AAA] start error: custom listener for [SR_USER_AAA] is repeated
2. 2022/02/14 11:28:57 [W] [control.go:179] [31f6cea8abecc2c6] [WEB_FFF] start error: port already used

2022/02/14 11:28:57 [I] [service.go:327] [31f6cea8abecc2c6] login to server success, get run id [31f6cea8abecc2c6], server udp port [5566]
2022/02/14 11:28:57 [I] [visitor_manager.go:86] [31f6cea8abecc2c6] start visitor success
2022/02/14 11:28:57 [I] [visitor_manager.go:86] [31f6cea8abecc2c6] start visitor success
2022/02/14 11:28:57 [I] [visitor_manager.go:86] [31f6cea8abecc2c6] start visitor success
2022/02/14 11:28:57 [I] [visitor_manager.go:86] [31f6cea8abecc2c6] start visitor success
2022/02/14 11:28:57 [I] [visitor_manager.go:130] [31f6cea8abecc2c6] visitor added: [visitor_XXX visitor_SH_USER_AAA visitor_SC_BBB visitor_CCC]
2022/02/14 11:28:57 [I] [proxy_manager.go:144] [31f6cea8abecc2c6] proxy added: [SR_USER_AAA SR_USER_BBB SR_CCC SR_USER_DDD SR_USER_EEE SR_USER_FFF SR_USER_GGG SR_USER_HHH SR_USER_HHH SR_USER_XU SR_FIN  SR_USER_HHH SR_USER_HHH WEB_XXX]
2022/02/14 11:28:57 [W] [control.go:179] [31f6cea8abecc2c6] [SR_USER_AAA] start error: custom listener for [SR_USER_AAA] is repeated
2022/02/14 11:28:57 [I] [control.go:181] [31f6cea8abecc2c6] [SR_USER_DDD] start proxy success
2022/02/14 11:28:57 [I] [control.go:181] [31f6cea8abecc2c6] [SR_USER_BBB] start proxy success
2022/02/14 11:28:57 [I] [control.go:181] [31f6cea8abecc2c6] [SR_CCC] start proxy success
2022/02/14 11:28:57 [W] [control.go:179] [31f6cea8abecc2c6] [SR_USER_FFF] start error: custom listener for [SR_USER_FFF] is repeated
2022/02/14 11:28:57 [I] [control.go:181] [31f6cea8abecc2c6] [SR_USER_HHH] start proxy success
2022/02/14 11:28:57 [W] [control.go:179] [31f6cea8abecc2c6] [SR_USER_YYY] start error: custom listener for [SR_USER_YYY] is repeated
2022/02/14 11:28:57 [I] [control.go:181] [31f6cea8abecc2c6] [SR_FFF] start proxy success
2022/02/14 11:28:57 [I] [control.go:181] [31f6cea8abecc2c6] [SR_USER_HHH] start proxy success
2022/02/14 11:28:57 [W] [control.go:179] [31f6cea8abecc2c6] [WEB_XXX] start error: port already used
2022/02/14 11:28:57 [I] [control.go:181] [31f6cea8abecc2c6] [SR_USER_HHH] start proxy success
2022/02/14 11:28:57 [W] [control.go:179] [31f6cea8abecc2c6] [WEB_TCMS] start error: port already used
2022/02/14 11:28:57 [I] [control.go:181] [31f6cea8abecc2c6] [SR_USER_TTT] start proxy success
2022/02/14 11:28:57 [I] [control.go:181] [31f6cea8abecc2c6] [WEB_VVV] start proxy success
2022/02/14 11:28:57 [W] [control.go:179] [31f6cea8abecc2c6] [WEB_FFF] start error: port already used

### Steps to reproduce

1. 启动FRPS
2. 启动FRPC
3. 出现一堆 
   1. start error: custom listener for [xxx] is repeated 
   2. [xxx] start error: port already used
...

将frps从0.39.1回退到0.37.1, 一切恢复正常

这个bug貌似是0.39引入的问题

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
No Configurations, no answer.

**Comment by jonozw** [comment]
配置大致如下, 拷贝了部分

# 运行frpc的 `服务器端`, 用于提供192.168.1.25的windows remote desktop的服务器端
[SH_USER_AAA]
type            = stcp
sk              = 12345678
local_ip        = 192.168.1.25
local_port      = 3389

运行fprc的笔记本`客户端`, 用于访问服务器端的windows remote desktop 服务
[visitor_SC_USER_AAA]
type            = stcp
role            = visitor
server_name     = SH_USER_AAA
sk              = 12345678
bind_addr       = 0.0.0.0
bind_port       = 9833

-----------------------------------------------------------------
以前都是正常的, 更换了frps从0.37.1到0.39.1后, 就开始报错了. 

替换回0.37.1后, 就又好了, 其他都没变.

**Comment by fatedier** [comment]
Can't reproduce this issue with your configures.

**Comment by jonozw** [comment]
好的, 等我明天构建一个例子

**Comment by BecodReyes** [comment]
`[WEB_FFF] start error: port already used`
建议使用netstat或者iostat查看端口占用情况
