### ISSUE TITLE
在路由器上运行客户端出现panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by shitizen-x** [fatedier/frp#282]
root@OpenWrt:~/frp# ./frpc -c ./frpc.ini
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/astaxie/beego/logs.(*fileLogWriter).lines(0x1066e300, 0x0, 0x0, 0x0)
        /root/go-mips32/src/gocode/src/github.com/astaxie/beego/logs/file.go:225 +0x370
github.com/astaxie/beego/logs.(*fileLogWriter).initFd(0x1066e300, 0x0, 0x0)
        /root/go-mips32/src/gocode/src/github.com/astaxie/beego/logs/file.go:183 +0x2d4
github.com/astaxie/beego/logs.(*fileLogWriter).startLogger(0x1066e300, 0x0, 0x0)
        /root/go-mips32/src/gocode/src/github.com/astaxie/beego/logs/file.go:112 +0xdc
github.com/astaxie/beego/logs.(*fileLogWriter).Init(0x1066e300, 0x1064e4e0, 0x28, 0x0, 0x0)
        /root/go-mips32/src/gocode/src/github.com/astaxie/beego/logs/file.go:98 +0x2ec
github.com/astaxie/beego/logs.(*BeeLogger).setLogger(0x106101e0, 0x333118, 0x4, 0x1069de68, 0x1, 0x1, 0x0, 0x0)
        /root/go-mips32/src/gocode/src/github.com/astaxie/beego/logs/log.go:194 +0x4b0
github.com/astaxie/beego/logs.(*BeeLogger).SetLogger(0x106101e0, 0x333118, 0x4, 0x1069de68, 0x1, 0x1, 0x0, 0x0)
        /root/go-mips32/src/gocode/src/github.com/astaxie/beego/logs/log.go:212 +0x170
github.com/fatedier/frp/src/utils/log.SetLogFile(0x333118, 0x4, 0x1060bb6b, 0xa, 0x0, 0x3)
        /root/go-mips32/src/gocode/src/github.com/fatedier/frp/src/utils/log/log.go:41 +0x304
github.com/fatedier/frp/src/utils/log.InitLog(0x333118, 0x4, 0x1060bb6b, 0xa, 0x1060bbec, 0x4, 0x0, 0x3)
        /root/go-mips32/src/gocode/src/github.com/fatedier/frp/src/utils/log/log.go:31 +0x60
main.main()
        /root/frp/src/cmd/frpc/main.go:99 +0xb40

goroutine 5 [runnable]:
github.com/astaxie/beego/logs.(*fileLogWriter).dailyRotate(0x1066e300, 0xe, 0xd065f58e, 0x26cd73ca, 0x47baa0)
        /root/go-mips32/src/gocode/src/github.com/astaxie/beego/logs/file.go:192
created by github.com/astaxie/beego/logs.(*fileLogWriter).initFd
        /root/go-mips32/src/gocode/src/github.com/astaxie/beego/logs/file.go:180 +0x288
root@OpenWrt:~/frp#

**Comment by shitizen-x** [comment]
dashboard 界面里SSH和web都是运行了的，路由器上启动客户端就报错，绑定的域名也访问不了

**Comment by fatedier** [comment]
先停用日志输出的功能。

**Comment by shitizen-x** [comment]
停止日志后重启正常连接了!谢谢!
