### ISSUE TITLE
反复报get a new work connection:

### ISSUE THREAD

**Issue by hao0616** [fatedier/frp#2820]
### Bug Description

几十台设备，有一台设备反复报get a new work connection:，有时候频率1秒几十次，几乎同样的系统和frpc配置，其他设备都正常。求助各位大佬~~~~

frpc日志：
2022/03/01 09:46:15 [1;34m[I] [service.go:221] login to server success, get run id [631da93e8ff37982], server udp port [0][0m
2022/03/01 09:46:15 [1;34m[I] [proxy_manager.go:137] [631da93e8ff37982] proxy added: [ssh17011][0m
2022/03/01 09:46:15 [1;34m[I] [control.go:144] [ssh17011] start proxy success[0m

frps日志：
2022/03/01 10:57:44 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 10:58:03 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 10:58:14 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 10:58:14 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 10:58:14 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 10:58:32 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 10:58:36 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 10:59:21 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 10:59:43 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 10:59:44 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 10:59:48 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 10:59:55 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:00:02 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:00:12 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:00:14 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:00:34 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:01:01 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:01:22 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:01:28 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:01:29 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:01:41 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:01:50 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:01:53 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:01:57 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:02:15 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:02:36 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:03:06 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:03:12 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:03:14 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:03:24 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:03:26 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:03:48 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:03:53 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]
2022/03/01 11:04:16 [I] [proxy.go:80] [631da93e8ff37982] [ssh17011] get a new work connection: [117.136.107.120:16923]

### frpc Version

0.25.3

### frps Version

0.25.3

### System Architecture

linux/arm

### Configurations

[common]
;This section set the server info
server_addr = xx.xx.xxx.xxxx
server_port = xxx
token = xxxxx
login_fail_exit = false

[ssh17011]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port =17011

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
https://github.com/fatedier/frp/issues/2817

可以关了

**Comment by hao0616** [comment]
> ~#2817~ ~可以关了~
> 
> ~需要配置文件~
> 
> 持续性眼瞎 请在问题机上尝试frps的连接是否被阻断 并尝试升级frp到最新版本

谢谢，升级新版本后解决
