### ISSUE TITLE
[Feature Request] Notify server plugins when a proxy is closed.

### ISSUE THREAD

**Issue by chengyuhui** [fatedier/frp#2821]
### Describe the feature request

Currently, server plugins only receive `NewProxy` events, it would be great if we can send `CloseProxy` messages to them as well (e.g. to use with https://github.com/arugal/frp-notify and notify users when a proxy goes offline for a certain length of time).

If the maintainers think that this is worth implementing, I can prepare a PR for this.

### Describe alternatives you've considered

Use external services to ping frp proxies and send notifications when they are down, but this sometimes does not work for non-HTTP(S) services.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
I think it's ok, but maybe a little different with `NewProxy`.

We can discuss more in your PR later.

**Comment by chengyuhui** [comment]
Closing this since #2823 has been merged.
