### ISSUE TITLE
[Feature Request] How do I specify multiple network adapters on the server

### ISSUE THREAD

**Issue by LeiyuanBlog** [fatedier/frp#2824]
### Describe the feature request

My server has multiple network cards and has multiple public IP addresses. How do I specify which network card and IP to use?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingtianbaihua** [comment]
It's an easy problem, you need deeply learning TCP/IP protocol.
