### ISSUE TITLE
[Feature Request] IP透传功能

### ISSUE THREAD

**Issue by LeiyuanBlog** [fatedier/frp#2825]
### Describe the feature request

我有两个服务器A-B，我需要A代理B的所有流量。也就是说当我访问A时，A将所有流量或者请求全部透传转发到B

### Describe alternatives you've considered

我有两个服务器A-B，我需要A代理B的所有流量。也就是说当我访问A时，A将所有流量或者请求全部透传转发到B

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingtianbaihua** [comment]
frp 只解决 4 层协议问题。

**Comment by fatedier** [comment]
Search VPN
