### ISSUE TITLE
[W] [service.go:105] login to server failed: i/o deadline reached

### ISSUE THREAD

**Issue by huangchengbuhuang** [fatedier/frp#2826]
### Bug Description

frpc客户端程序运行不起来

### frpc Version

 frp_0.39.1_linux_amd64.tar.gz

### frps Version

 frp_0.39.1_linux_amd64.tar.gz

### System Architecture

centos7

### Configurations

[common]
server_addr = ·······················
server_port = 9090

[ssh]
type = tcp
local_ip = ········································
local_port = 221
remote_port = 9999

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by bingtianbaihua** [comment]
自己查下这种问题，然后为啥要建 2 个 issue ？
