### ISSUE TITLE
[W] [service.go:105] login to server failed: i/o deadline reached

### ISSUE THREAD

**Issue by huangchengbuhuang** [fatedier/frp#2827]
### Bug Description

frpc客户端程序运行不起来

### frpc Version

 frp_0.39.1_linux_amd64.tar.gz

### frps Version

 frp_0.39.1_linux_amd64.tar.gz

### System Architecture

centos7

### Configurations

server_addr = 101.200.222.209
server_port = 9090

[ssh]
type = tcp
local_ip = 10.170.24.249
local_port = 221
remote_port = 9999

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by BecodReyes** [comment]
**请提供LOG**

**Comment by huangchengbuhuang** [comment]
> 
服务端设置：

[common]
bind_port = 9090
# 对外访问端口i
vhost_http_port = 9005
vhost_https_port = 9006
# 连接认证token
token = ·······
# dashboard图形管理页面
#设置日志文件记录路径
log_file=./logs/frps.log
errorlog_level=info
log_max_days=3

日志：
[root@iZ2ze170eiax8ju5n6bifbZ logs]# cat frps.log
2022/03/11 10:23:42 [I] [root.go:200] frps uses config file: ./frps.ini
2022/03/11 10:23:42 [I] [service.go:193] frps tcp listen on 0.0.0.0:9090
2022/03/11 10:23:42 [I] [service.go:236] http service listen on 0.0.0.0:9005
2022/03/11 10:23:42 [I] [service.go:251] https service listen on 0.0.0.0:9006
2022/03/11 10:23:42 [I] [service.go:292] Dashboard listen on 0.0.0.0:9091
2022/03/11 10:23:42 [I] [root.go:209] frps started successfully
2022/03/11 10:24:06 [I] [root.go:200] frps uses config file: ./frps.ini
2022/03/11 10:24:06 [I] [service.go:193] frps tcp listen on 0.0.0.0:9090
2022/03/11 10:24:06 [I] [service.go:236] http service listen on 0.0.0.0:9005
2022/03/11 10:24:06 [I] [service.go:251] https service listen on 0.0.0.0:9006
2022/03/11 10:24:06 [I] [service.go:292] Dashboard listen on 0.0.0.0:9091
2022/03/11 10:24:06 [I] [root.go:209] frps started successfully
2022/03/11 10:28:29 [I] [dashboard_api.go:70] Http request: [/api/serverinfo]
2022/03/11 10:28:29 [I] [dashboard_api.go:63] Http response [/api/serverinfo]: code [200


客户端的frpc因为运行不起来，所以没有日志出来、
客户端配置：
[common]
server_addr = 59.123.123.123
server_port = 9090
token=······

[ssh]
type = tcp
local_ip = 10.34.21.31
local_port = 22
remote_port = 9999
log_file = ./logs/frps.log
errorlog_level = info
log_max_days = 1


服务器的端口已开放，阿里云防火墙的端口也已经开放，ip和token做了处理

**Comment by Waterkin** [comment]
同上，期待回答

**Comment by zliu1111** [comment]
试试在客户端的frpc.ini的 [common] 中加入
tls_enable=true
我就是这么解决的

**Comment by Waterkin** [comment]
> 试试在客户端的frpc.ini的 [common] 中加入 tls_enable=true 我就是这么解决的
太感谢了！！成功连上！！！解决了大问题！感谢！

**Comment by connected201** [comment]
I have same problem betwen Windows. with last version of frp (0.40)

**Comment by huangchengbuhuang** [comment]
I use the version of 0.38 ,in the frps.ini add tls_only = true and in the frpc.ini add tls_enable=true.

**Comment by huangchengbuhuang** [comment]
I use the version of 0.38 ,in the frps.ini add tls_only = true and in the frpc.ini add tls_enable=true.

**Comment by connected201** [comment]
in my case, problem was in Windows firewall (i turned it off, and all working fine).

**Comment by huzhiyuan1994** [comment]
> > 试试在客户端的frpc.ini的 [common] 中加入 tls_enable=true 我就是这么解决的
> > 太感谢了！！成功连上！！！解决了大问题！感谢！

这个问题也太迷了吧，我的阿里云服务器上一直在用着0.27.1没更新，多个客户端也对应的一直没更新。之前都正常使用，但最近，其中一个客户端突然出这个问题，重启服务器，更新版本，更新go语言版本等都没效，加上这句就好了

**Comment by Love666sJane** [comment]
> 试试在客户端的frpc.ini的 [common] 中加入 tls_enable=true 我就是这么解决的

感谢，我也通过您的设置解决了这一问题

**Comment by mookixiao** [comment]
用tls_enable的方法解决了，有人解释解释为什么吗

**Comment by CoCoThink** [comment]
请问是流量过墙的原因吗？确实加上tls_enable好多了
