### ISSUE TITLE
[Feature Request] 访问的时候可以不加端口号嘛

### ISSUE THREAD

**Issue by mofei828** [fatedier/frp#2828]
### Describe the feature request

网上用了一个大佬免费提供的FRP，可以域名后不加端口号直接访问，现在自己尝试配置frps，
vhost_http_port不写打不开，写了就必须写端口号，想实现域名后不加端口号的方式，求大佬指点一下

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
写 `80` 就可以不加。

**Comment by BecodReyes** [comment]
frps想要让frpc能绑定域名则必须指定`vhost_http_port`

或者，使用tcp把frpc端的web服务映射出去
```
# frps.ini
[common]
bind_port = 7000
```

```
# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[web]
type = tcp
local_port = 80
```

**Comment by entrehuihui** [comment]
nginx转发
