### ISSUE TITLE
0.9.3版本在用nginx做前端反向代理时出现502问题

### ISSUE THREAD

**Issue by CN-P5** [fatedier/frp#283]
之前使用0.8.1版本，用来做内网穿透。环境如下：
服务器：阿里云 ubuntu
内网：win
把内网的80端口转发到服务器的8082端口，服务器上nginx监听80端口，然后用nginx的反向代理服务器的8082端口来实现把内网上的web服务转到外网。使用正常稳定。
今天换成0.9.3之后nginx开始出现502错误，调试未果又换回去了。
看新版更新日志感觉这是个bug，或许只是我自己出现这个问题？

**Comment by robscc** [comment]
我也遇到这个问题了，有解决吗？

**Comment by CN-P5** [comment]
我换回0.8.1版本用了，看更新作者应该正在尝试新的网络库之类的。我们可以多测试下等待作者更新

**Comment by Cong5** [comment]
我使用 0.8.1 还是出现 502 ，死活不行。求分享配置信息

**Comment by CN-P5** [comment]
好的，这几天我会写个简单的配合nginx的小笔记。到时候可以贴过来

**Comment by qq690712575** [comment]
我用nginx代理的时候会出现session共用的情况，内网转发出来的是同一个session

- 发送自我的Sony Xperia™智能手机

---- CN-P5编写 ----


好的，这几天我会写个简单的配合nginx的小笔记。到时候可以贴过来

**Comment by openmynet** [comment]
0.9.3 阿里u16.04， 本地win10 未出现502 配置在#287

**Comment by fatedier** [comment]
直接向 frp 的 http 端口发送请求看是否正常，502 可能就是没有正常穿透出去。

**Comment by zhfish** [comment]
frp只转发端口吧，session共用什么的检查nginx

**Comment by eeve** [comment]
0.11.0 也有这个问题，不配置nginx，直接向 frp 的 http 端口发送请求是可以的，开启nginx proxy_pass就502

**Comment by fatedier** [comment]
@eeve 你都已经说了直接发送请求可以，那就检查 nginx 的配置。

**Comment by eeve** [comment]
好吧，刚开始是一直都有问题，我刚重新启动一下nginx，顺便将chrome disable cache之后就莫名奇妙的好了！

**Comment by fatedier** [comment]
这个 issue 直接关闭了，再有类似问题，先检查直接访问 frp 是否正常，如果正常，只有通过 nginx 反向代理时出现问题，可以 1. 给 nginx 提 issue，寻求帮助。 2. 上网查找相关解决方法。 

如果直接访问 frp 就不正常，和 nginx 无关，另外提 issue。

友情建议遇到问题的人参考下 @openmynet 在 issue #287 中的配置。
