### ISSUE TITLE
How to custom the 404 page

### ISSUE THREAD

**Issue by smallfish01** [fatedier/frp#2830]
### Bug Description

Hello,

When I access FRP server IP from web browser and I got the information:

"The page you requested was not found.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

The server is powered by [frp](https://github.com/fatedier/frp).

Faithfully yours, frp."

I found the information came from /opt/frp/pkg/util/vhost/resource.go, but when I removed these information and restart frps service, then try access frp server again the information still exists.

How can I custom the information?  Which file/files should I edit ?

Thank you.

### frpc Version

0.38.1

### frps Version

0.38.1

### System Architecture

Linux/amd64

### Configurations

Configuration files are ok, I can access the custom domain from outside.

### Steps to reproduce

1.  Access FRP server IP from web browser;
2. Got information:
The page you requested was not found.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

The server is powered by [frp](https://github.com/fatedier/frp).

Faithfully yours, frp.

4. I want to change the information, sush as: It works.

...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/blob/bf635c0e902c5e4b07de55440c6886d7f919dfc8/conf/frps_full.ini#L129

**Comment by smallfish01** [comment]
Thank you so much.
