### ISSUE TITLE
frpc-frps不是同一运营商，dashboard显示连接成功，但远程桌面访问frpc失败

### ISSUE THREAD

**Issue by zxyqq** [fatedier/frp#2835]
### Bug Description

frps是电信网络-linux
frpc1是移动的(os:win10)
frpc2是电信的(os:win7)
pc是和frps在同一内网。
pc远程桌面访问frpc1失败。访问frpc2正常。

### frpc Version

0.39.1

### frps Version

0.39.1

### System Architecture

frps: linux/amd64， frpc: windows/amd64

### Configurations

frps的dashboard上可以看到和frpc1和frp2的两个tcp连接都是online状态。

frpc1的配置（地址和端口部分用x.x.x.x代替了）
os: win10
frpc: 0.39.1
[common]
server_addr = S.x.x.x   #frps的地址
server_port = sxxx      #frps监听的tcp端口

[xxx-rdp]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = cxxx #frps用于此连接的tcp端口
use_encryption = true 

在frps上开启了trace级别的日志，在pc远程访问frpc1时的日志输出如下：
对比pc远程访问是frpc2的日志多了如下一条，
2022/03/12 00:26:28 [D] [proxy.go:300] [34eca7910ec090ea] [xxx-rdp] join connections closed

### Logs

在frps上开启了trace级别的日志，在pc远程访问frpc1时的日志输出如下：
对比pc远程访问是frpc2的日志多了如下一条，
2022/03/12 00:26:28 [D] [proxy.go:300] [34eca7910ec090ea] [xxx-rdp] join connections closed

日志如下，其中A.x.x.x是发起访问的PC的内网IP地址。
2022/03/12 00:26:26 [I] [proxy.go:179] [34eca7910ec090ea] [xxx-rdp] get a user connection [A.x.x.x:53095]
2022/03/12 00:26:26 [D] [control.go:248] [34eca7910ec090ea] get work connection from pool
2022/03/12 00:26:26 [D] [proxy.go:104] [34eca7910ec090ea] [xxx-rdp] get a new work connection: [C.x.x.x:39857]
2022/03/12 00:26:26 [T] [proxy.go:279] [34eca7910ec090ea] [xxx-rdp] handler user tcp connection, use_encryption: true, use_compression: false
2022/03/12 00:26:26 [D] [proxy.go:290] [34eca7910ec090ea] [xxx-rdp] join connections, workConn(l[S.x.x.x:sxxx] r[C.x.x.x:39857]) userConn(l[S.x.x.x:cxxx] r[A.x.x.x:53095])
2022/03/12 00:26:26 [D] [control.go:219] [34eca7910ec090ea] new work connection registered
2022/03/12 00:26:28 [D] [proxy.go:300] [34eca7910ec090ea] [xxx-rdp] join connections closed
2022/03/12 00:26:30 [D] [control.go:480] [61ffb60fc77d3a7f] receive heartbeat
2022/03/12 00:26:30 [D] [control.go:480] [34eca7910ec090ea] receive heartbeat
2022/03/12 00:26:30 [D] [control.go:480] [f3cf3dc5a7cbf456] receive heartbeat

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by zxyqq** [comment]
the reason here:
https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-allow-access
You can use Remote Desktop to connect to Windows 10 Pro and Enterprise, Windows 8.1 and 8 Enterprise and Pro, Windows 7 Professional, Enterprise, and Ultimate, and Windows Server versions newer than Windows Server 2008. You can't connect to computers running a Home edition (like Windows 10 Home).

**Comment by bitcl2** [comment]
我只用过电信的，验证会封端口。
具体现象是一开始能连上，过一会就不行了。此时换一个端口，还是一开始可以，一传输流量又被封锁了。
frp特征明显，封端口的问题4年前就有反馈了。不适合家用宽带用。

**Comment by zsinba** [comment]
电信不是只无封80、443这些吗、 3389也封？
