### ISSUE TITLE
[Feature Request] Please document how lifecycle of a remote port (as well as its traffic) is managed.

### ISSUE THREAD

**Issue by enihcam** [fatedier/frp#2837]
### Describe the feature request

From the doc i can see the remote port (via frp server) is managed by a local frp client.
If that's true, will this remote port be closed as long as the local port is closed (or frp client terminates)?
Or, if the local port is closed, will there be any traffic taken in place between server and client?

Thanks.

### Describe alternatives you've considered

More infra docs maybe?

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
You can find what you want to know by reading source codes.

We haven't enough time to write tutorial and all codes are open source.
