### ISSUE TITLE
How much frpc can we start with one frps server? is there any limit for frpc? [Feature Request] 

### ISSUE THREAD

**Issue by ranjeet-pivotchain** [fatedier/frp#2838]
### Describe the feature request

How much frpc can we start with one frps server? is there any limit for frpc? 
We have an unlimited subdomain so can we start unlimited frpc with one frps server?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingtianbaihua** [comment]
It depends on many factors. Such as
1. all frpc and frps on a single machine or not
2. The cpu, mem of the machine where frps is located

The best way is download latest binary and  benchmark it.
