### ISSUE TITLE
请教如何获取客户端真实IP

### ISSUE THREAD

**Issue by smallfish01** [fatedier/frp#2839]
### Bug Description

内网web server用的是nginx,在nginx.conf里添加了X-Forwarded-For和X-Real-IP，

然后在frpc.ini设置了proxy_protocol_version,

当用户在外网访问next.domain.com时，在内部nginx日志上还是显示frps 的IP，不知道配置哪里出错了？

谢谢！

### frpc Version

 0.38.1

### frps Version

 0.38.1

### System Architecture

Linux/amd64

### Configurations

内网Nginx.conf:

server {
        listen 80 proxy_protocol;
        listen [::]:80;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

server {
    listen 443 ssl http2 proxy_protocol;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

frpc.ini

[next]
type = https
local_port = 443
local_ip = 192.168.21.49
custom_domains = next.domain.com
proxy_protocol_version = v2

[next-http]
type = http
local_port = 80
local_ip = 192.168.21.49
custom_domains = next.domain.com
proxy_protocol_version = v2

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by smallfish01** [comment]
经过排查，是Nginx配置不对，正确的应该是：
   listen 80 proxy_protocol;
    real_ip_header proxy_protocol;
    set_real_ip_from 192.168.20.2(frp_server_IP);

但是还有个问题，内网IIS如何获取客户端访问的真实IP，目前还在研究中。

**Comment by BecodReyes** [comment]
配置proxy_protocol之后web服务端只能解析proxy_protocol协议
请另开端口

**Comment by smallfish01** [comment]
> 配置proxy_protocol之后web服务端只能解析proxy_protocol协议 请另开端口

请教下，IIS支持该协议吗，需要怎么配置

**Comment by zhezhe168** [comment]
> 配置proxy_protocol之后web服务端只能解析proxy_protocol协议 请另开端口

是开哪边的端口，nginx还是？可以给个配置文件参考下嘛，小白不懂

**Comment by smallfish01** [comment]
> > 配置proxy_protocol之后web服务端只能解析proxy_protocol协议 请另开端口
> 
> 是开哪边的端口，nginx还是？可以给个配置文件参考下嘛，小白不懂
Nginx，我上面有配置，您可以看看。

**Comment by zhezhe168** [comment]
> > > 配置proxy_protocol之后web服务端只能解析proxy_protocol协议 请另开端口
> > 
> > 
> > 是开哪边的端口，nginx还是？可以给个配置文件参考下嘛，小白不懂
> > Nginx，我上面有配置，您可以看看。

我按照这个设置了，nginx启动报错。。。

**Comment by smallfish01** [comment]
把你的错误和配置贴出来看看。
