### ISSUE TITLE
frp大老板,网站无法获得浏览器用户ip地址啥时候解决啊

### ISSUE THREAD

**Issue by soybacn** [fatedier/frp#284]
http网站无法获得浏览器用户ip地址,看到论坛里有 好几个人反馈了.可我更急着需要这个功能,所以我再发帖催你下啊
国内的ngrok有个服务器已经解决了,就是你之前说的加在 x-real-ip,但用户第一次连接时才传递真实IP地址,第2次连接值就为空了,隔3分钟后又传递了.
希望尽快解决.基于国内环境,GONGAN都要求网站登记访客ip地址.所以很需要这个功能.
ps:没想到frp大老板是中国人.自豪啊

**Comment by zhujinyan** [comment]
frps前面加个nginx

**Comment by mbj2014** [comment]
我的frps前面就有个nginx，是不是网站程序取x-real-ip就能得到真实客户IP了？

**Comment by zhujinyan** [comment]
function getonlineip() {
	$ip = $_SERVER['REMOTE_ADDR'];
	if(isset($_SERVER['HTTP_CLIENT_IP']) && preg_match('/^([0-9]{1,3}\.){3}[0-9]{1,3}$/', $_SERVER['HTTP_CLIENT_IP'])) {
		$ip = $_SERVER['HTTP_CLIENT_IP'];
	} elseif(isset($_SERVER['HTTP_X_FORWARDED_FOR'])) {
		$tmp = $_SERVER['HTTP_X_FORWARDED_FOR'];
		preg_match_all('#\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}#s', $tmp, $matches);
		foreach($matches[0] as $x_ip) {
			if(!preg_match('#^(10|172\.16|192\.168)\.#', $x_ip)) {
				$ip = $x_ip;
				break;
			}
		}
	}
	return $ip;
}

**Comment by zhujinyan** [comment]
nginx设置下
proxy_set_header   X-Real-IP  $remote_addr;
proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;

**Comment by soybacn** [comment]
to:zhujinyan:
谢谢您的留言
我是win环境.你的getonlineip() 我测试过,通过获取remote_addr,X-Real-IP,HTTP_X_FORWARDED_FOR,这3个参数,均获取不到真实IP.

**Comment by openmynet** [comment]
@soybacn #270
