### ISSUE TITLE
frpc连接数增长，会导致frps服务端端口占用数量增长吗？

### ISSUE THREAD

**Issue by SMU-Rainflow** [fatedier/frp#2840]
### Describe the feature request

想通过frpc暴露一个TCP Server，如果连接TCP Server的连接数过多，会不会导致frps服务器端口被占用过多而影响其他功能呢？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
1. 连接和端口不相关，不是一回事。
2. 不能保证不会因为被攻击或其他原因导致服务器整体不稳定，如果有必要，建议自行使用容器或其他方式限制所使用的资源。
3. 如果没有相关的知识，建议谨慎使用，不要随意对外开放。

**Comment by SMU-Rainflow** [comment]
好的，谢谢您的建议，想明白了一部分。
刚刚测试本地 协程TCP Server承压能力的时候，端口占用过多是因为测试脚本中异步的TCP连接请求造成的。我以为是TCP Server为每个IO等待的连接单独创建了一个端口。
