### ISSUE TITLE
login to server failed: dial tcp {IP:PORT}: i/o timeout

### ISSUE THREAD

**Issue by rootGH** [fatedier/frp#2843]
### Bug Description

VPS IP:PORT has been switched off already

### frpc Version

0.40.0

### frps Version

0.40.0

### System Architecture

windows/amd64

### Configurations

Client
[common]
server_addr = {IP}
server_port = 7000

[RDP] 
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 7001

Server
[common]
bind_port = 7000

### Logs

D:\frp_0.40.0_windows_amd64>frpc.exe
2022/03/15 09:25:40 [W] [service.go:105] login to server failed: dial tcp {IP:PORT}: i/o timeout
dial tcp {IP:PORT}: i/o timeout

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Qpp0** [comment]
same here

**Comment by BecodReyes** [comment]
post the log of frps, pls

**Comment by rootGH** [comment]
> 

no logs, only two lines
D:\frp_0.40.0_windows_amd64>frpc.exe
2022/03/15 09:25:40 [W] [service.go:105] login to server failed: dial tcp {IP:PORT}: i/o timeout
dial tcp {IP:PORT}: i/o timeout

**Comment by rootGH** [comment]
> post the log of frps, pls

no logs, only two lines
D:\frp_0.40.0_windows_amd64>frpc.exe
2022/03/15 09:25:40 [W] [service.go:105] login to server failed: dial tcp {IP:PORT}: i/o timeout
dial tcp {IP:PORT}: i/o timeout

**Comment by PilotXia** [comment]
me too here

**Comment by BecodReyes** [comment]
Use tcping to test if the port is open properly

**Comment by smpile** [comment]
Have you found a solution

**Comment by Pil0tXia** [comment]
solved, this problem mostly happens in cloud servers, the source port range should be *

**Comment by smpile** [comment]
> solved, this problem mostly happens in cloud servers, the source port range should be *

how to do it, buddy
is it means that i need to open all the tcp+udp port

**Comment by smpile** [comment]
> solved, this problem mostly happens in cloud servers, the source port range should be *

我也搞好了，我用内网那个ping外网的IP发现ping不通，然后发现路由器的网络控制把我那个frp服务器给限时了，改了一下就好了。

**Comment by fantasyEthan** [comment]
I encountered the same problem. I use Aliyun ECS + computer in edu domain. I followed the instructions and set the firewalls of ecs. How did you solve these problems?

**Comment by Waterkin** [comment]
腾讯云 同样有这个问题 设置了防火墙也没有用。

**Comment by ArthurWang0829** [comment]
> 

请问下这个是怎么改？阿里云ping起来回报正常，是端口不对？

**Comment by CaesarHolland** [comment]
My cloud server is Tencent cloud, I solved the problem by add a firewall rule (open port 7000 of tcp) on cloud server

**Comment by liugeng518** [comment]
怎么解决的？

**Comment by wshidaijingshen** [comment]
我是客户端的 公网ip 地址写错了，好好检查下  
I solved this by correcting the `server_addr` in  frpc.ini .
Then problems gone.

**Comment by wshidaijingshen** [comment]
> 怎么解决的？

我是客户端的 公网ip 地址写错了，好好检查下
I solved this by correcting the server_addr in frpc.ini .
Then problems gone.

**Comment by 52Lau** [comment]
![image](https://user-images.githubusercontent.com/37538641/232370717-4aa9cbb0-49ec-4b89-a0e2-c13cac8d961b.png)
如楼上所说 放开  *

**Comment by Lucca-cherries** [comment]
It turns out that the port 6000 and 7000 should both be opened. In my case, this solves my problem.
