### ISSUE TITLE
[Feature Request] Client behind the Forward Proxy

### ISSUE THREAD

**Issue by justdatguymat** [fatedier/frp#2845]
### Describe the feature request

Hi,

Can CLIENT support connection with the SERVER via CONNECT method in HTTP Proxy?

thanks,
Matt

### Describe alternatives you've considered

I have tried using http_proxy plugin but It wouldn't work and I doubt this was designed for it.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frpc_full.ini#L14

**Comment by justdatguymat** [comment]
@fatedier thank you! this has worked now... i had to get rid off the `plugin = http+proxy` from the config. 
Strange as I was trying this before and was getting only I/O Reach errors.
