### ISSUE TITLE
[Feature Request] custom client name, and use it to prefix for service.

### ISSUE THREAD

**Issue by jayagami** [fatedier/frp#2847]
### Describe the feature request

An option for custom client name, and use it to prefix the section.
So, you don't have to modify config in different server,  like [a-ssh], [b-ssh]

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frpc_full.ini#L78

**Comment by jayagami** [comment]
> https://github.com/fatedier/frp/blob/dev/conf/frpc_full.ini#L78

Thanks for your replying. I checked the documentation and mistakenly thought that there is no such function.
Thanks for your great job. 
Have a wonderful day!
