### ISSUE TITLE
FRP 不支持.vip 后缀的域名映射吗？

### ISSUE THREAD

**Issue by NikoHXX** [fatedier/frp#2848]
### Bug Description

FRP 不支持.vip 后缀的域名映射吗？

### frpc Version

0.38

### frps Version

0.32

### System Architecture

linux/amd64

### Configurations

.com 域名一摸一样配置可以访问

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingtianbaihua** [comment]
No config, no log, no answer.
