### ISSUE TITLE
frp 0.4.0最新版本下載一直說有毒…

### ISSUE THREAD

**Issue by JB-Ming** [fatedier/frp#2850]
### Bug Description

windows 會擋
我的防毒軟體nod32也會擋說有毒

### frpc Version

0.4.0

### frps Version

0.4.0

### System Architecture

windows/amd64

### Configurations

na.

### Logs

na.

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by Daodanfd5** [comment]
我认为你说是0.40.0了
报毒的原因大概是杀软集体更新规则frp歇菜，加白名单就好了，如果不放心可以审计代码
