### ISSUE TITLE
[Feature Request] custom_domains可以是通配符吗

### ISSUE THREAD

**Issue by zhangyang215** [fatedier/frp#2854]
### Describe the feature request

custom_domains可以是通配符吗？比如custom_domains = *.yourdomain.com

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
可以多个 `,` 分割

**Comment by fatedier** [comment]
可以
