### ISSUE TITLE
在多用户的情况下，每隔一段时间，会出现更改本地用户密码行为

### ISSUE THREAD

**Issue by tybbt** [fatedier/frp#2855]
### Bug Description

我在云服务器上设置了frps文件：
[common]
bind_port = 8000

在本地服务器配置的frpc：
[common]
server_addr = xxxxxxxx1
server_port = 8000

[ssh1]
type = tcp
local_ip = xxxxxxxx2
local_port = 22
remote_port = 6000

[ssh2]
type = tcp
local_ip = xxxxxxxxx2
local_port = 8888
remote_port = 8888
每过一段时间，都会出现只有某个用户可以继续登录服务器，而其他所有用户都不能登录。此时在root用户下修改其他用户的密码，才能继续登录。现在root用户的密码也被更改了
此时的frps端会一直输出
2022/03/18 23:42:54 [I] [service.go:157] frps tcp listen on 0.0.0.0:8000
2022/03/18 23:42:54 [I] [root.go:209] start frps success
2022/03/18 23:43:11 [I] [service.go:420] [0b5c47e00bcc8131] client login info: ip [XXXXXXX3] version [0.32.1] hostname [] os [linux] arch [amd64]
2022/03/18 23:43:11 [I] [tcp.go:63] [0b5c47e00bcc8131] [ssh1] tcp proxy listen port [6000]
2022/03/18 23:43:11 [I] [control.go:445] [0b5c47e00bcc8131] new proxy [ssh1] success
2022/03/18 23:43:11 [I] [tcp.go:63] [0b5c47e00bcc8131] [ssh2] tcp proxy listen port [8888]
2022/03/18 23:43:11 [I] [control.go:445] [0b5c47e00bcc8131] new proxy [ssh2] success
2022/03/18 23:43:12 [I] [proxy.go:91] [0b5c47e00bcc8131] [ssh1] get a new work connection: [XXXXXX3]
2022/03/18 23:43:13 [I] [proxy.go:91] [0b5c47e00bcc8131] [ssh1] get a new work connection: [XXXXXX3]

### frpc Version

0.32.1

### frps Version

0.32.1

### System Architecture

linux/amd64

### Configurations

单服务器多用户远程登陆
多用户除用户名密码外使用同一host和port配置

### Logs

2022/03/18 23:42:54 [I] [service.go:157] frps tcp listen on 0.0.0.0:8000
2022/03/18 23:42:54 [I] [root.go:209] start frps success
2022/03/18 23:43:11 [I] [service.go:420] [0b5c47e00bcc8131] client login info: ip [XXXXXXX3] version [0.32.1] hostname [] os [linux] arch [amd64]
2022/03/18 23:43:11 [I] [tcp.go:63] [0b5c47e00bcc8131] [ssh1] tcp proxy listen port [6000]
2022/03/18 23:43:11 [I] [control.go:445] [0b5c47e00bcc8131] new proxy [ssh1] success
2022/03/18 23:43:11 [I] [tcp.go:63] [0b5c47e00bcc8131] [ssh2] tcp proxy listen port [8888]
2022/03/18 23:43:11 [I] [control.go:445] [0b5c47e00bcc8131] new proxy [ssh2] success
2022/03/18 23:43:12 [I] [proxy.go:91] [0b5c47e00bcc8131] [ssh1] get a new work connection: [XXXXXX3]
2022/03/18 23:43:13 [I] [proxy.go:91] [0b5c47e00bcc8131] [ssh1] get a new work connection: [XXXXXX3]
2022/03/18 23:43:14 [I] [proxy.go:91] [0b5c47e00bcc8131] [ssh1] get a new work connection: [XXXXXX3]
2022/03/18 23:43:15 [I] [proxy.go:91] [0b5c47e00bcc8131] [ssh1] get a new work connection: [XXXXXX3]
2022/03/18 23:43:16 [I] [proxy.go:91] [0b5c47e00bcc8131] [ssh1] get a new work connection: [XXXXXX3]
2022/03/18 23:43:17 [I] [proxy.go:91] [0b5c47e00bcc8131] [ssh1] get a new work connection: [XXXXXX3]

### Steps to reproduce

1. 设置frpc端内容
2. 设置frps端内容
3. 启动frpc、 frps
4. 配置final shell： host port username passwd
5. 连接运行一段时间，多用户登录

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
密码弱 被更改

**Comment by BecodReyes** [comment]
弱密码
请加强密码强度并实装fail2ban
