### ISSUE TITLE
[内容过滤] 

### ISSUE THREAD

**Issue by wanghaiqing2015** [fatedier/frp#2857]
### Describe the feature request

我想实现一个内容过滤的功能，比如转发的TCP请求，有固定的字符串时，就丢弃，该如何实现呢。

最终转发数据的代码没有找到，有知道的大佬，麻烦给个提示啊

### Describe alternatives you've considered

无

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
作者应该不会满足你的需求。

**Comment by bingtianbaihua** [comment]
frp v2 架构会考虑类似的事情，在扩展模块去做。

**Comment by fatedier** [comment]
不会提供通用的功能，但是新架构会让修改这部分的代码更容易一些。
