### ISSUE TITLE
Can't connect to local service

### ISSUE THREAD

**Issue by Parmicciano** [fatedier/frp#2859]
### Bug Description

Hello, 
I'm trying to set up frp to connect an ec2 instance with an ubuntu virtual machine and i get the following error :
[E] proxy.go
[ssh]connect to local service [127.0.0.1:22] error : dial tcp 127.0.0.1:22 connect : connection refused

I've followed the basic tutorial in the readme

### frpc Version

0.40.0

### frps Version

0.40.0

### System Architecture

linux/amd64

### Configurations

Ubuntu vm inside a windows computer that connect to an EC2 instance with a public ip (AWS)

### Logs

[E] proxy.go
[ssh]connect to local service [127.0.0.1:22] error : dial tcp 127.0.0.1:22 connect : connection refused

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
Please check if 127.0.0.1:22 can be accessed under normal circumstances

**Comment by Parmicciano** [comment]
>>>>>ssh root@127.0.0.1
ssh: connect to host 127.0.0.1 port 22: Connection refused

It seems that it cant be accessed

**Comment by BecodReyes** [comment]
> It seems that it cant be accessed

Then it's your ssh problem, not frp's business, you can close this issue now

**Comment by yunyuyuan** [comment]
Myabe you need start `sshd`  
`sudo systemctl status sshd`  
`sudo systemctl start sshd`
