### ISSUE TITLE
报错被检测到病毒

### ISSUE THREAD

**Issue by filwu8** [fatedier/frp#2860]
### Bug Description

<img width="442" alt="1647761022(1)" src="https://user-images.githubusercontent.com/54697960/159152589-6581130b-db38-4495-9142-26c84edd4b05.png">

其中 v0.40.0  v0.39.0 这两个版本均被检测出病毒，

我还在用老的V0.38.0  这个版本在win10 win11自带的病毒威胁防护下都正常使用

### frpc Version

v0.40.0 

### frps Version

v0.40.0 

### System Architecture

windows/amd64

### Configurations

win11

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by JobsLeeCN** [comment]
同上问题，i386版本没有问题，但x64版本确实有问题，Chrome浏览器下载也显示风险提示。

**Comment by xqzr** [comment]
#2095

**Comment by BecodReyes** [comment]
**说了多少遍了**

> 这个并不是没有发生过，putty都曾被当hacktool杀过
> 估计主要还是因为frp名气不是很大，否则厂商查杀会更小心一点。现阶段还是叫frp用户自己排除比较好。其实这个binary最早应该是eset开始查杀的，后来其他厂商看到eset杀就全部跟进了。我一直在观测查杀情况，看到这个雪球越滚越大心情着实复杂……


> 前两天在学校服务器装了frp，然后被报我们服务器在攻击其他平台，网络中心老师直接把网段封了。现在申请的服务器被回收了，难受啊，不知道是不是frp的问题，当时腾讯云报病毒我还没在意，安全意识薄弱啊

releases下载的frp是安全的，所以可能有以下原因
1. 你申请的服务器密码被爆破
2. 学校行为管理识别出了frp的流量
3. 非releases下载的frp，已被植入病毒
4. 服务器内其他软件发起的攻击

**Comment by CQJTU-Andy** [comment]
哥别生气，我的问题，可能我frp token设置得太简单了，也可能是其他原因。不过我确实是在release里面下的软件。咱们服务器密码确实比较简单，考虑到是内网，所以没太在意。以前没被病毒欺负过，这次长心眼了。frp用着确实很方便，也免费，是自己其他方面没做到位。

**Comment by melodyne** [comment]
我们下载都有报病毒，只能手动添加信任了

**Comment by Declarcall** [comment]
正常，我放virustotal检测也有部分引擎报毒。win11是直接把我下载的frp压缩包干掉了。关掉windows自带的杀毒就好了

https://www.virustotal.com/gui/file/f6b96c46d8395d08ae91d5a19d55f8c9f19d512207612a89ca4c79df0c2f3c5d
https://www.virustotal.com/gui/file/a003f5539bcf1c36e9d8f0565857dc8478015da4f97fa64bcb91f6495bbfc105

**Comment by afrojewelz** [comment]
0.44下载也被拦截了 也检测到病毒 是哪行代码被检测到模仿了病毒行为呢 我不懂 从哪里可以看呢

**Comment by filwu8** [comment]
> 

我还在用老版本，老本无毒，很健康。

**Comment by bibitoo** [comment]
我用源码编译的有时也报病毒，源码应该review查找病毒特征源

**Comment by Guohui-Peng** [comment]
> > 
> 
> 我还在用老版本，老本无毒，很健康。

确实用0.38.0只报frpc.exe是HackTool，最新版本的报Trojan。
还是希望作者重视下，review下原码。这种开源项目被投毒前段时间好像还爆过新闻。

**Comment by yangjieshao** [comment]
还是得想办法解决一下的，很多客户对安全的管控有点严，这样会慢慢流失用户的
