### ISSUE TITLE
Auto reconnect every 30 seconds

### ISSUE THREAD

**Issue by DDFantasyV** [fatedier/frp#2861]
### Bug Description

使用frp远程连接树莓派时，可以正常连接但是每隔一段时间自动断开。查看树莓派运行记录显示每隔30秒自动重连。服务器端无报错。

### frpc Version

0.40.0

### frps Version

0.40.0

### System Architecture

server:ubuntu/amd64 client:raspbian

### Configurations

frps.ini
[common]
bind_addr=*.*.*.*
bind_port=****
authenticate_heartbeats = false
authenticate_new_work_conns = true
authentication_method = token
token = ******
dashboard_port = ****
dashboard_user = *****
dashboard_pwd = *****
max_pool_count = 0
cognification_timeout = 300

frpc.ini
[common]
server_addr = *.*.*.*
server_port = ****
tls_enable = true
authentication_method = token
authenticate_new_work_conns = true
token = ******
login_fail_exit = false

[ssh]
type = tcp
local_ip = *.*.*.*
local_port = **
remote_port = ****

### Logs

2022/03/20 11:33:49 [I] [control.go:315] [88533fc240e44d4f] control writer is closing
2022/03/20 11:33:49 [I] [visitor_manager.go:60] [88533fc240e44d4f] gracefully shutdown visitor manager
2022/03/20 11:33:50 [I] [service.go:178] [88533fc240e44d4f] try to reconnect to server...
2022/03/20 11:33:50 [I] [service.go:325] [88533fc240e44d4f] login to server success, get run id [88533fc240e44d4f], server udp port [0]
2022/03/20 11:33:50 [I] [proxy_manager.go:144] [88533fc240e44d4f] proxy added: [ssh]
2022/03/20 11:33:50 [I] [control.go:181] [88533fc240e44d4f] [ssh] start proxy success

2022/03/20 11:34:20 [I] [control.go:315] [88533fc240e44d4f] control writer is closing
2022/03/20 11:34:20 [I] [visitor_manager.go:60] [88533fc240e44d4f] gracefully shutdown visitor manager
2022/03/20 11:34:20 [I] [service.go:178] [88533fc240e44d4f] try to reconnect to server...
2022/03/20 11:34:20 [I] [service.go:325] [88533fc240e44d4f] login to server success, get run id [88533fc240e44d4f], server udp port [0]
2022/03/20 11:34:20 [I] [proxy_manager.go:144] [88533fc240e44d4f] proxy added: [ssh]
2022/03/20 11:34:20 [I] [control.go:181] [88533fc240e44d4f] [ssh] start proxy success

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
mtr一下frps，测试是否有严重丢包或者间歇性断网现象出现
