### ISSUE TITLE
port unavailable

### ISSUE THREAD

**Issue by zuozhehao** [fatedier/frp#2862]
### Bug Description

port unavailable

### frpc Version

0.40.0

### frps Version

0.40.0

### System Architecture

window

### Configurations

```
[common]
bind_addr = 0.0.0.0
bind_port = 2222



# auth token
token = token

# trace, debug, info, warn, error
log_level = debug
```

### Logs

2022/03/21 10:58:51 [I] [service.go:325] [9c4ebd9ed37ee832] login to server success, get run id [9c4ebd9ed37ee832], server udp port [0]
2022/03/21 10:58:51 [I] [proxy_manager.go:144] [9c4ebd9ed37ee832] proxy added: [test_tcp]
2022/03/21 10:58:51 [W] [control.go:179] [9c4ebd9ed37ee832] [test_tcp] start error: port unavailable

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingtianbaihua** [comment]
check the port is open by yourself

**Comment by zuozhehao** [comment]
> check the port is open by yourself

服务器端口是打开的，Telnet 可以进去。

**Comment by BecodReyes** [comment]
> start error: port unavailable

端口被占用，kill占用端口的程序或者换个端口
