### ISSUE TITLE
最近客户端连接失败，i/o timeout. frp被墙？

### ISSUE THREAD

**Issue by SwaySZ** [fatedier/frp#2865]
### Bug Description

校园网客户端，腾讯云服务端，tcping服务器端口正常，一旦执行frpc后无法再tcping；换了若干端口，出现相同现象。PS:外网（如开热点连接）客户端一切正常。难道端口被墙了？

### frpc Version

0.38-0.40

### frps Version

0.40

### System Architecture

linux/amd64

### Configurations

frcp.ini
##############
[common]
server_addr = xxx
server_port = xxx
token = xxx

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = xxx

### Logs

NA

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingtianbaihua** [comment]
大概率是防火墙。

**Comment by SwaySZ** [comment]
不清楚原理是啥？为啥只墙端口？防火墙是怎么侦测到的？是frp的什么特征触发了被墙？

**Comment by yaotthaha** [comment]
实在不行就拿websocket顶一下

**Comment by Waterkin** [comment]
同上，不知道什么情况

**Comment by Waterkin** [comment]
> 可以开启 KCP + TLS 试试

请问怎么开启呢？

**Comment by SwaySZ** [comment]
开启kcp连接不上。以上问题暂时无解，太奇怪了。

**Comment by 799034552** [comment]
我也这样，怎么破

**Comment by SwaySZ** [comment]
> 我也这样，怎么破

破不了

**Comment by bitcl2** [comment]
国内点对点也会被封端口，换一个端口同样只能存活几十秒。

**Comment by iSonce** [comment]
一样的情况，阿里云的frp服务端开了，用校园网连不上

**Comment by 799034552** [comment]
> 一样的情况，阿里云的frp服务端开了，用校园网连不上

我们校园网加上tls加密就行了
`tls_enable = true`

**Comment by iSonce** [comment]
> 
加上tls加密解决了（原来的7000端口墙了得换一个），十分感谢

**Comment by ysl2** [comment]
我们校园网更狠，直接把ip给封了，我开始的时候不知道怎么回事，以为自己的某一步操作导致运营商给封了ip，就弄了一台腾讯云的服务器，一台阿里云的服务器来测试。结果这俩服务器又都登不上了。继续研究发现是校园网给封的，直接把ip封了，现在校园网内根本登不上这俩服务器。感觉试错成本有点高，不想继续捣鼓了。
