### ISSUE TITLE
SSH几十秒自动断开

### ISSUE THREAD

**Issue by mofei828** [fatedier/frp#2871]
### Bug Description

[W] [proxy.go:176] [987ad6393190d19d] [880828-centos ssh] listener is closed: accept tcp [::]:12244: use of closed network connection
报错
一直敲键盘  也会自动断开

### frpc Version

frp_0.41.0_linux_amd64

### frps Version

frp_0.41.0_linux_amd64

### System Architecture

linux/amd64

### Configurations

[common]
bind_port = 7000
vhost_http_port = 123
tls_only = true
token = 123456

[common]
server_addr = 1.1.1.1
server_port = 7000
token = 123456
tls_enable = true

[880828-centos ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 601
remote_port = 1224

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by mofei828** [comment]
frps使用的腾讯云，经测试frps使用甲骨文就没事，为啥

**Comment by AmitKatyal-Sophos** [comment]
any update on this?

**Comment by piwawa** [comment]
> frps使用的腾讯云，经测试发现使用甲骨文没问题。原因为腾讯云内添加frp为信任就没出现自动断线的现象了。

怎么添加啊？？
