### ISSUE TITLE
下载下来的windows软件，杀毒软件报木马病毒

### ISSUE THREAD

**Issue by melodyne** [fatedier/frp#2872]
### Describe the feature request

![image](https://user-images.githubusercontent.com/12462384/160228077-d288c930-a0d4-448f-b2eb-1869987653ec.png)

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
立即删除，不要使用。

**Comment by melodyne** [comment]
为啥？？
