### ISSUE TITLE
[Feature Request] 请问frpc能支持s390x架构吗？

### ISSUE THREAD

**Issue by gitiy1** [fatedier/frp#2879]
### Describe the feature request

我们公司的服务器是linux one，系统是Red Hat Enterprise Linux 7.9，最近正在进行一个项目，发现编译安装十分困难，请问frpc能否支持s390x架构？

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [x] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://go.dev/dl/

**Comment by 1451522755** [comment]
这是我已经编译好支持s390x的frp
http://down.freenn.com/file/frp/frp-0.42.0/release/frpc_linux_s390x
http://down.freenn.com/file/frp/frp-0.42.0/release/frps_linux_s390x
