### ISSUE TITLE
无法在Android linux上面解析域名

### ISSUE THREAD

**Issue by Suphappy** [fatedier/frp#2880]
### Bug Description

使用的是V0.41 arm64包

[W] [service.go:105] login to server failed: couldn't generate OIDC token for login: Post "https://test-gz.xxsaw.com/iot-link/deviceAuth/OIDC/auth": dial tcp: lookup test-gz.xxsaw on [::1]:53: read udp [::1]:42171->[::1]:53: read: connection refused
couldn't generate OIDC token for login: Post "https://test-gz.xxsaw.com/iot-link/deviceAuth/OIDC/auth": dial tcp: lookup test-gz.xxsaw.com on [::1]:53: read udp [::1]:42171->[::1]:53: read: connection refused

### frpc Version

V0.41

### frps Version

V0.41

### System Architecture

linux/arm64

### Configurations

[common]
server_addr = xxxxxxxxxxxxxxxxxxxxx
server_port = 27100

authenticate_heartbeats = true
authentication_method = oidc
oidc_client_id = bfd79fcd35a602f8a6f39715bc07cb84
oidc_client_secret = e1de4c423241bb79c1f844277ef2ed43c06212cca701c1e7ae5828b63d79017ba7a327a29e4fe4ba4a0b5b37ebd888ab
oidc_token_endpoint_url = https://test-gz.xxsaw.com/iot-link/deviceAuth/OIDC/auth

[1509364968562073602_SSH]
type = tcp
local_ip = 127.0.0.1
local_port = 5555
remote_port = 27178

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frpc_full.ini#L106

**Comment by Suphappy** [comment]
> https://github.com/fatedier/frp/blob/dev/conf/frpc_full.ini#L106

谢谢！！不好意思没注意到这个细节，已经可以了
