### ISSUE TITLE
FRP redirects me from the domain to 127.0.0.1:8080

### ISSUE THREAD

**Issue by Nuckerr** [fatedier/frp#2881]
### Bug Description

When I go to `nucker.me` it redirects me to `127.0.0.1:8080` and I have no clue why. I have multiple other services working on this, the only difference is they use subdomains.

### frpc Version

0.39.1

### frps Version

0.39.1

### System Architecture

linux/amd64

### Configurations

```ini
[common]
token = [redacted]
server_addr = [redacted].nucker.me
server_port = 7000

admin_addr = 0.0.0.0
admin_port = 7400
admin_user = adminuser
admin_pwd = [redacted]
enable_prometheus = true

[blog]
type = https
custom_domains = nucker.me
plugin = https2http
plugin_local_addr = 192.168.0.139:8080
plugin_crt_path = /etc/certs/cert.pem
plugin_key_path = /etc/certs/key.pem
plugin_host_header_rewrite = 127.0.0.11
plugin_header_X-From-Where = frp
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
Why you set `plugin_host_header_rewrite = 127.0.0.11`?

**Comment by Nuckerr** [comment]
Oh, it was originally 127.0.0.1 and then I tried to see if that was causing the redirect and changed it to 11. I've changed it back

**Comment by fatedier** [comment]
I'm not sure why you add this param.

**Comment by Nuckerr** [comment]
Now it redirects to `nucker.me:8080`

**Comment by Nuckerr** [comment]
Any ideas?
