### ISSUE TITLE
[Feature Request] Specify client plugin http2https from command line

### ISSUE THREAD

**Issue by meixger** [fatedier/frp#2883]
### Describe the feature request

Extend the command line to start a http single proxy with a http2https client plugin.

I would like to start frpc.exe without frpc.ini by only relaying on command line parameters.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by M4jx** [comment]
It would be very helpful to support all client plugins to be able to use them through command line.

**Comment by fatedier** [comment]
We don't want to do that. It's only used for some simple use case, not all.

It's complex and not elegant to support nested struct config in command line. It's also difficult to maintain since you can't deserialize it to a struct easliy.
