### ISSUE TITLE
[Feature Request] Default HTTP(S) Tunnel

### ISSUE THREAD

**Issue by dong-zeyu** [fatedier/frp#2888]
### Describe the feature request

Hi, I want to know if I can config the frp server such that all undefined (or not found) http(s) tunnel goes to a default service, for example, local port 8080 or 4430? Thank you!

### Affected area

- [ ] Docs
- [ ] Installation
- [x] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Not support.
