### ISSUE TITLE
【建议】将当前项目核心抽象出来，作为core

### ISSUE THREAD

**Issue by hktalent** [fatedier/frp#2896]
### Describe the feature request

【建议】将当前项目核心抽象出来，作为core
方便二次开发，core没有web功能，更加轻量

thanks

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [X] Others

**Comment by blizard863** [comment]
可以使用 package 的方式去用，已经有很多产品这样用了。
