### ISSUE TITLE
Can prefixes be removed when routing

### ISSUE THREAD

**Issue by WSYwsy22** [fatedier/frp#2897]
### Describe the feature request

Is it possible to forward the request according to the route? Can the prefix be automatically removed
Just like nginx, / ABC can be removed from the real request path assuming/ABC matches  

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
We plan to support proxy features like this in v2 architecture.
