### ISSUE TITLE
Contains  Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by Murf** [fatedier/frp#2900]
### Bug Description

"This program is dangerous and executes commands from an attacker."

### frpc Version

0.41.0

### frps Version

0.41.0

### System Architecture

windows/amd64

### Configurations

Installing....

### Steps to reproduce

1. Download (blocked by chrome)
2. Download with Edge
3. Windows Defender intercepts any manipulation of the zip file
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by faunX** [comment]
This is false positive!

**Comment by xqzr** [comment]
😅#2095
