### ISSUE TITLE
[Question] HTTPS-Proxy ... BAD GATEWAY message in Browser

### ISSUE THREAD

**Issue by ikarstein** [fatedier/frp#2904]
### Describe the feature request

Hi all,

I have a question regarding the configuration of FRPS/FRPC... 

"Outside" my LAN I have a Debian VM with a public IP (v4). Inside my LAN I have a Windows machine.

On the Windows machine I run an ASP.NET app on IIS with HTTPS and SNI. This is all running.

I want to access this ASP.NET app from the internet. Also via HTTPS.

I started FRPS on the Debian VM and added "vhost_https_port=443" to the frps.ini

On the Windows machine I added this to frsc.ini:

[web01]
type = https
local_ip = 127.0.0.1
local_port = 443
use_encryption = false
use_compression = true
custom_domains = myapp.example.com
proxy_protocol_version = v2

frpc starts without problems and connects to frps (on the Debian VM).

On a third machine (Windows) I added an entry to the HOSTS file for "myapp.example.com" for the public IP of the Debian machine (FRPS).

When I try to access http://myapp.example.com I see the request on the Debian machine (FRPS) but in the browser (on the third machine) I get an error "ERR_CONNECTION_CLOSED".

What do I miss here? I cannot find my mistake.

Thank you all!

Regards
Ingo

**Comment by ikarstein** [comment]
Now I found the plugin "https2https"

I changed the config:

[web01]
type = https
#local_ip = 127.0.0.1
#local_port = 443
use_encryption = false
use_compression = false
custom_domains = myapp.example.com
proxy_protocol_version = v2
plugin = https2https
plugin_local_addr = 127.0.0.1:443
plugin_crt_path = c:\ssl\myapp.example.com.crt
plugin_key_path = c:\ssl\myapp.example.com.key
plugin_host_header_rewrite = myapp.example.com
plugin_header_X-From-Where = frp

On the third machine I use the browser to access https://myapp.example.com. Now I get a 502 "Bad Gateway" error.

**Comment by fatedier** [comment]
Why you set `proxy_protocol_version = v2`?

**Comment by ikarstein** [comment]
Thank you for your answer!

... because I saw it in a sample config. I already tried it without this line.

**Comment by ikarstein** [comment]
The current (and also not working) config is:

```
#frpc.ini
[common]
server_addr = x.x.x.x
server_port = yyyy
token=abc
log_level = trace
tls_enable = true
tls_cert_file = c:\ssl\client.crt
tls_key_file = c:\ssl\client.key

[web01]
type = https
#local_ip = 127.0.0.1
#local_port = 443
#use_encryption = false
#use_compression = false
custom_domains = myapp.example.com
#proxy_protocol_version = v2
plugin = https2https 
plugin_local_addr = 127.0.0.1:443
plugin_crt_path = c:\ssl\myapp.example.com.crt
plugin_key_path = c:\ssl\myapp.example.com.key
plugin_host_header_rewrite = myapp.example.com
plugin_header_X-From-Where = frp
```

As you can see I added TLS for the connection between FRPC and FRPS. The handshake seems to be okay.

On FRPC machine I get this log message:
`2022/04/20 23:41:11 [D] [proxy.go:784] [XXXXXXXXXXXXXXXX] [web01] handle by plugin: https2http`

Without a "s" behind the second "http" in the plugin name... Is that correct?

**Comment by fatedier** [comment]
You can try your original configs:

```
[web01]
type = https
local_ip = 127.0.0.1
local_port = 443
custom_domains = myapp.example.com
```

**Comment by ikarstein** [comment]
This was my first approach.

...But now it works !!!

I am confused. I still had that first configuration at the end of my
FRPC.INI file.

THANK YOU!
