### ISSUE TITLE
支持按域名暴露WebSockets接口

### ISSUE THREAD

**Issue by mbj2014** [fatedier/frp#2907]
### Describe the feature request

当前只能通过暴露一个http和一个tcp来共同配合实现暴露内网的WebSockets。

但当我的内网有多台相似主机，要暴露一样的ws时，希望能想http一样通过域名来区分，而使用一样的外部端口。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by jingslunt** [comment]
https://raw.githubusercontent.com/the-cc-dev/inlets/master/main.go

**Comment by jingslunt** [comment]
```
# inlets client --upstream=https://10.238.241.11:8443 --remote wss://test.connex.com --token=5a1374d7a7037813d71e0f52d378cca5ba1b131c
2022/04/29 15:42:54 Upstream:  => https://10.238.241.11:8443
2022/04/29 15:42:54 Token: "5a1374d7a7037813d71e0f52d378cca5ba1b131c"
Welcome to inlets.dev! Find out more at https://github.com/alexellis/inlets

map[Authorization:[Bearer 5a1374d7a7037813d71e0f52d378cca5ba1b131c] X-Inlets-Id:[236874f9ffed409fa6b0f60e4fc0d014] X-Inlets-Upstream:[=https://10.238.241.11:8443]]
INFO[0000] Connecting to proxy                           url="wss://test.connex.com/tunnel"

```

**Comment by mbj2014** [comment]
另外一个软件的实现？
