### ISSUE TITLE
[Feature Request] Does `use_encryption` rely on `token`?

### ISSUE THREAD

**Issue by ThewBear** [fatedier/frp#2909]
### Describe the feature request

I looked at the source code and found that `use_encryption` use `token` configuration as a pbkdf2 key.

So if I set `use_encryption` without specifying `token`, does it use empty string by default?

If it use empty string by default, I think we should state in the README that token must also be set.

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
> So if I set use_encryption without specifying token, does it use empty string by default

Yes.

However, `tls_enable` is preferred to encrypt all traffics between frpc and frps. `use_encryption` is reserved not to break compatibility.

**Comment by ThewBear** [comment]
So if I use `tls_enable`, can I omit `use_encryption`?

**Comment by fatedier** [comment]
Yes.
