### ISSUE TITLE
尝试在手机跑frp失败

### ISSUE THREAD

**Issue by Leonhardt92** [fatedier/frp#2910]
### Bug Description

![image](https://user-images.githubusercontent.com/35802996/164987579-6350e22e-008e-485a-ae31-552a9463f16d.png)

### frpc Version

0.42

### frps Version

0.42

### System Architecture

linux/amd64

### Configurations

小米8
安卓9

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
手机端请使用arm架构

**Comment by Leonhardt92** [comment]
> 放在 `/data/local/tmp/` 这个目录试一下

可以了谢谢
