### ISSUE TITLE
centos8上面frp怎么自动升级[Feature Request] 

### ISSUE THREAD

**Issue by bzmjcster** [fatedier/frp#2912]
### Describe the feature request

我在centos8上面安装了frp，版本更新很快，但是我不知道怎么自动升级？谢谢给我方法。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by OldGodShen** [comment]
自己下新的啊

**Comment by bzmjcster** [comment]
原来的配置文件，怎么导入呢？重新配置吗？之前的文件是不是全部删除呢？请大师指点下！谢谢

**Comment by bzmjcster** [comment]
我已经下载全新文件，也已经解压了！

**Comment by OldGodShen** [comment]
要导入什么？就拿新的 <frpc> -c <配置文件啊>
