### ISSUE TITLE
Cannot start frpc with systemctl

### ISSUE THREAD

**Issue by sgpublic** [fatedier/frp#2918]
### Bug Description

I'm running frpc with systemctl on CentOS 8.5, I copied `frpc.service` and `frpc@.service` to the path of `/usr/lib/systemd/system/`, and `frpc.ini` to the path of `/etc/frp/frpc.ini`, then I run command `systemctl start frpc`, but it seems failed to start, `systemctl status frpc` shows:

```
● frpc.service - Frp Client Service
   Loaded: loaded (/usr/lib/systemd/system/frpc.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2022-04-29 20:38:13 CST; 1s ago
  Process: 17329 ExecStart=/usr/bin/frpc -c /etc/frp/frpc.ini (code=exited, status=1/FAILURE)
 Main PID: 17329 (code=exited, status=1/FAILURE)
```

But frpc can be start successfully with command `/usr/bin/frpc -c /etc/frp/frpc.ini`.

I‘m sorry about that I have no idea with how to find any other log, so how can I solve it? Thanks adcanced.

### frpc Version

0.42.0

### frps Version

0.42.0

### System Architecture

linux/amd64

### Configurations

frps.ini
```
[common]
bind_port = 7000
```

frpc.ini
```
[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by penguine** [comment]
have you the correct user in frp.service? normally the script works. you only need the frpc.service  file.

**Comment by ututono** [comment]
Hi. I met the same issue as yours. Have you solve it or any idea?

**Comment by sgpublic** [comment]
> Hi. I met the same issue as yours. Have you solve it or any idea?

Hi! This is my service file, and you can replace `ExecStart` with your own:

```
[Unit]
Description=Frp Client
After=network.target network-online.target
Requires=network-online.target

[Service]
ExecStart=/approot/bin/frpc -c /approot/etc/frpc.d/frpc.ini
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**Comment by ututono** [comment]
> > Hi. I met the same issue as yours. Have you solve it or any idea?
> 
> Hi! This is my service file, and you can replace `ExecStart` with your own:
> 
> ```
> [Unit]
> Description=Frp Client
> After=network.target network-online.target
> Requires=network-online.target
> 
> [Service]
> ExecStart=/approot/bin/frpc -c /approot/etc/frpc.d/frpc.ini
> Restart=always
> RestartSec=5
> 
> [Install]
> WantedBy=multi-user.target
> ```

Thank for your prompt reply. It turns out that the `ExectStart` was wrong in my config file. It runs well now.

**Comment by sealionking** [comment]
> > Hi. I met the same issue as yours. Have you solve it or any idea?
> 
> Hi! This is my service file, and you can replace `ExecStart` with your own:
> 
> ```
> [Unit]
> Description=Frp Client
> After=network.target network-online.target
> Requires=network-online.target
> 
> [Service]
> ExecStart=/approot/bin/frpc -c /approot/etc/frpc.d/frpc.ini
> Restart=always
> RestartSec=5
> 
> [Install]
> WantedBy=multi-user.target
> ```

it works after setting the authentication config according the frps.ini

without setting it，the frpc.service failed.
