### ISSUE TITLE
start error: port unavailable

### ISSUE THREAD

**Issue by rgzn-aiyun** [fatedier/frp#2920]
### Bug Description

start error: port unavailable

### frpc Version

0.42.0

### frps Version

0.42.0

### System Architecture

amd64

### Configurations

frpc -c frpc.ini

### Logs

This error occurs a lot, No problem switching back to version 0.41.0
start error: port unavailable

bug
acquire port 22 error: port unavailable
 [test] start error: port unavailable
[test] start error: acquire port 22 error: port unavailable
 [test] start error: port unavailable
 [test] start error: acquire port 22 error: port unavailable
 [test] start error: port unavailable

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
https://github.com/fatedier/frp/issues/2067

> `port unavailable` means frps can't bind this port.
>
>The reason maybe:
>
> 1. The port is listened by other process.
> 2. frps has no enough permissions, try to give it root permission.

**Comment by rgzn-aiyun** [comment]
> #2067
> 
> > `port unavailable` means frps can't bind this port.
> > The reason maybe:
> > 
> > 1. The port is listened by other process.
> > 2. frps has no enough permissions, try to give it root permission.

It should be a new version problem, a new parameter config_dir has been added.
