### ISSUE TITLE
中国大陆境内的客户端连接不到大陆地区以外的服务端

### ISSUE THREAD

**Issue by billgateno** [fatedier/frp#2921]
### Bug Description

中国大陆地区的客户端无法连接境外的服务端

版本均为0.42.0

服务端1：vultr jp centos 8.5
服务端2：linode in centos 7.9

但是，连接国内的阿里云就能正常使用

服务端3：aliyun cn bj centos 7.9

国内的阿里云带宽太小，而且限制域名，国外的就是连接不上

有没有办法解决呢？

就不加英文翻译了，这个应该是中国特色问题，说给外国人也不懂。

### frpc Version

0.42.0

### frps Version

0.42.0

### System Architecture

linux/amd64,、windows/amd64

### Configurations

就是默认配置，监听7000端口。没了

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by billgateno** [comment]
报错信息是

`2022/05/01 21:**:** [W] [service.go:128] login to server failed: EOF
EOF
`

**Comment by billgateno** [comment]
近来发现zerotier也是，境内外可以ping通，但是传输不了其他数据，不知道是不是同一个原因

**Comment by BecodReyes** [comment]
考虑是否被gfw阻断连接
