### ISSUE TITLE
[Feature Request]  Clients do not automatically reconnect

### ISSUE THREAD

**Issue by SShnoodles** [fatedier/frp#2924]
### Describe the feature request

Version: 0.42.0
In client configuration document  cannot find like set `reconnect = false`.

When server restart, clients will auto reconnect. That's right.
But I want to add a configuration for client, so that some clients don't need to reconnect.

### Affected area

- [X] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
No plan to support it.
