### ISSUE TITLE
启用 tls 后的 token 安全性问题

### ISSUE THREAD

**Issue by m2acgi** [fatedier/frp#2926]
### Bug Description

请问问启用 tls 后, 服务端与客户端之间的 token 是否也被加密了？tls 验证是在 token 验证之前还是之后呢？谢谢。

### frpc Version

v0.42.0

### frps Version

v0.42.0

### System Architecture

linux/amd64

### Configurations

服务端、客户端启用 tls

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
安全
