### ISSUE TITLE
config_dir error when systemd reload service

### ISSUE THREAD

**Issue by MikoyChinese** [fatedier/frp#2928]
### Bug Description

1.  First, start frpc service with config_dir.
2. Then, restart frpc service with config_dir in Terminal. The command is `frpc reload --config_dir /usr/local/bin/frp/config`
3. You will get the error `open ./frpc.ini: no such file or directory`.
...

### frpc Version

0.42.0

### frps Version

0.42.0

### System Architecture

linux/amd64

### Configurations

[Unit]
Description=Frp Client Service
After=network.target

[Service]
Type=simple
User=root
Restart=on-failure
RestartSec=5s
ExecStart=/usr/local/bin/frp/frpc --config_dir /usr/local/bin/frp/config
ExecReload=/usr/local/bin/frp/frpc reload --config_dir /usr/local/bin/frp/config

[Install]
WantedBy=multi-user.target

### Logs

open ./frpc.ini: no such file or directory

### Steps to reproduce

1.  First, start frpc service with config_dir.
2. Then, restart frpc service with config_dir in Terminal. The command is `frpc reload --config_dir /usr/local/bin/frp/config`
3. You will get the error `open ./frpc.ini: no such file or directory`.
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Config reload is unsupported for `config_dir`.
