### ISSUE TITLE
TCPMUX出错

### ISSUE THREAD

**Issue by WINKCM** [fatedier/frp#2929]
### Bug Description

TCPMUX应该怎么用？
![image](https://user-images.githubusercontent.com/83860530/167246827-f14a5d89-d705-4a9d-adec-262250784176.png)
这样配置，
![image](https://user-images.githubusercontent.com/83860530/167246840-ad7a1188-2ad9-409c-bf52-66eda44a8aec.png)
然后连接成功但是会报错。
![image](https://user-images.githubusercontent.com/83860530/167246885-bfe440b6-181a-4fb2-9e37-a5cf472a98c3.png)
 new proxy [proxy1] error: proxy [proxy1] type [tcpmux] with multiplexer [httpconnect] requires tcpmux_httpconnect_port configuration
两端都会报这个错误，然后访问由boa监控的这个端口也不能成功启动CGI。是我配置有错误还是其他原因。

### frpc Version

0.42.0

### frps Version

0.42.0

### System Architecture

linux/amd64

### Configurations

![image](https://user-images.githubusercontent.com/83860530/167246827-f14a5d89-d705-4a9d-adec-262250784176.png)
![image](https://user-images.githubusercontent.com/83860530/167246840-ad7a1188-2ad9-409c-bf52-66eda44a8aec.png)
common设置了只是没截上图。

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by CocoTang1024** [comment]
在frps端配置一下tcpmux_httpconnect_port 就可以了
