### ISSUE TITLE
[Feature Request] API interface instead of using .ini files for configuration of the client/server?

### ISSUE THREAD

**Issue by JohnnyRacer** [fatedier/frp#2931]
### Describe the feature request

Does there exist an API interface for `frp`? If not would it be possible to add a simple API interface instead of using `.ini` files for configuring the server/client? This would allow `frp` to be integrated with other components in languages like Python, JS or Rust much more easily. Since currently one would have to manually dump the `.ini` file and mess around with starting/stopping services which can be a pain in more complicated projects.

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [X] Extensions
- [X] Others

**Comment by fatedier** [comment]
We plan to support it in frp v2. There won't be changes in current version.

**Comment by penguine** [comment]
i did some tests on which places we put the REST api. it works. right now the API is on holt. but we can work on it together if we start it again with that. that can certainly be used directly for v2.
