### ISSUE TITLE
[Feature Request] 使用tls时新增自定义san配置

### ISSUE THREAD

**Issue by hyhy01** [fatedier/frp#2933]
### Describe the feature request

错误：
```sh
 login to server failed: x509: cannot validate certificate for xxxxxxxxx because it doesn't contain any IP SANs
```
我没有使用自签名证书。
我生成的证书的域名绑定了cdn，因此在连接frp时填写了ip而不是域名。
我在用trojan-go时记得可以单独设置sni。

发现客户端可以不需要验证证书，好像也不是那么必要。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frpc_full.ini#L103
