### ISSUE TITLE
[Feature Request] Host配置中的local_ip, 能否用域名或者机器名代替? 

### ISSUE THREAD

**Issue by jonozw** [fatedier/frp#2935]
### Describe the feature request

当前我的使用方式是在文件服务器上开一个FRPC, 监听很多个Host, 然后将不同的Host映射到不同的PC上, 这样就不用每个人单独在PC上安装FRPC了, 从而让大家能在家远程登陆RDP. 

服务器端每个用户的配置大致为
[SH_USER_XXX]
type            = stcp
sk              = 1234567890
local_ip        = 192.168.1.123
local_port      = 3389

但是一般来说, 除非将IP地址固定, 否则IP地址偶尔会改动
1.  一个解决方法是在路由器端指定每台机器的静态IP地址. 
2. 另一个解决方案是, 能否用机器名替代IP地址? 比方说如下这样: 
[SH_USER_XXX]
type            = stcp
sk              = 1234567890
local_ip        = PC_XXX
local_port      = 3389

请评估一下, 谢谢

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
可以使用域名

**Comment by jonozw** [comment]
嗯嗯, 的确可以, 谢谢
