### ISSUE TITLE
Allow ports for a specific user server side[Feature Request] 

### ISSUE THREAD

**Issue by Parmicciano** [fatedier/frp#2937]
### Describe the feature request

Hi guys,
I've setup multiusers frp.
I would like to know if there is a way to allow a client to use a specific ports and not another.
Ex :
Frps
  Bind port user1 :7000
 Bind port user2 : 7001

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
You can try to write your own [plugin](https://github.com/fatedier/frp/blob/dev/doc/server_plugin.md) to implement this feature.

**Comment by Masternetworks** [comment]
Thanks for your answer, 

I've write my own plugin, available [here ](https://github.com/Parmicciano/frp_plugin_allowed_ports) (Published on my personnal account)

**Comment by Parmicciano** [comment]
Thanks for your answer,

I've write my own plugin, available [here ](https://github.com/Parmicciano/frp_plugin_allowed_ports)
