### ISSUE TITLE
[Feature Request] Dashboard里希望支持显示frpc的内网地址和转发的服务器地址

### ISSUE THREAD

**Issue by mbj2014** [fatedier/frp#2940]
### Describe the feature request

frps仅通过密码来管理接入，无法真正识别接入者。

在Dashboard里，只能看到标签信息，但没有frpc的内网服务器地址和转发服务地址。

如果可以在每个标签的信息里，可以显示frpc的内网服务器地址、机器名、MAC和转发服务地址等信息，就容易在Dashboard里看到接入者是什么机器了。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Botium1** [comment]
同意

**Comment by chijiao** [comment]
应该可以自己编译增加功能吧
