### ISSUE TITLE
内网穿透后内网网站静态资源无法访问

### ISSUE THREAD

**Issue by ynzhangsp** [fatedier/frp#2944]
### Bug Description

通过frp内网穿透后，外网访问内网服务器部署的网站，可以正常访问，但静态资源都无法加载，控制台显示网站调用的CSS、JS等文件都显示404，网页样式没有了，请问大佬们这是怎么回事啊

### frpc Version

0.42.0

### frps Version

0.42.0

### System Architecture

frps：linux/amd64，frpc：linux/arm64

### Configurations

服务器端为Debian 64位系统，本地客户端为树莓派4B Debian  64位系统

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Parmicciano** [comment]
It's probably a misconfiguration of your client. 
The image [here](http://service.masternetwork.us/) is in the folder of the website and it work well

**Comment by BecodReyes** [comment]
![CM6PHS7AGGJPN31Y2DI83MS.png](https://s2.loli.net/2022/05/19/YCWKze3vuMG4lrt.png)

**Comment by chjiyun** [comment]
我的客户端 windows 也是无法访问，配置更文档一样的
