### ISSUE TITLE
Windows Server 2003 client running FRPC Exe prompt is not a valid Win32 Application.

### ISSUE THREAD

**Issue by pxycn** [fatedier/frp#2945]
### Bug Description

Windows Server 2003 client running FRPC Exe prompt is not a valid Win32 Application.

### frpc Version

frp_0.42.0_windows_386

### frps Version

frp_0.42.0_windows_386

### System Architecture

windows

### Configurations

Is the version downloaded wrong? Can you give me a link to download the version available for 32-bit Windows Server 2003? Thank you!

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by BecodReyes** [comment]
Version 0.24.1 is the last version that can run on Windows 2003.

> 旧的系统和技术会被不断淘汰，抛弃历史包袱才能降低开发和维护成本，随着 golang 版本的更新，会逐渐不支持一些已经停止维护的系统。不管从安全性还是功能性上来说，建议及时更新系统。

**Comment by pxycn** [comment]
谢谢解答，感谢！！
