### ISSUE TITLE
TCP and HTTP intranet penetration cannot be set at the same time

### ISSUE THREAD

**Issue by willyautoman** [fatedier/frp#2947]
### Bug Description

TCP and HTTP intranet penetration cannot be set at the same time

### frpc Version

0.41.0

### frps Version

0.41.0

### System Architecture

linux/amd64

### Configurations

-- frps.ini ---
[common]
bind_port=7000
vhost_http_port=18080

---- frpc.ini ----
[common]
server_addr = x.x.x.x.x.
server_port = 7000
vhost_http_port=18080

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

[jellyfin]
type = tcp
local_ip = 172.17.0.3
local_port = 8096
remote_port =18096

[qbittorrent]
type = http
local_ip = 172.17.0.2
local_port = 8080
custom_domains = frp.x.tech

### Logs

2022/05/22 03:06:47 [I] [root.go:202] frps uses command line arguments for config
2022/05/22 03:06:47 [I] [service.go:194] frps tcp listen on 0.0.0.0:7000
2022/05/22 03:06:47 [I] [root.go:209] frps started successfully
2022/05/22 03:06:53 [I] [service.go:450] [adc1f5d46b1e9957] client login info: ip [1.28.102.6:43852] version [0.41.0] hostname [] os [linux] arch [amd64]
2022/05/22 03:06:53 [I] [tcp.go:64] [adc1f5d46b1e9957] [jellyfin] tcp proxy listen port [18096]
2022/05/22 03:06:53 [I] [control.go:465] [adc1f5d46b1e9957] new proxy [jellyfin] success
2022/05/22 03:06:53 [W] [control.go:461] [adc1f5d46b1e9957] new proxy [qbittorrent] error: type [http] not support when vhost_http_port is not set
2022/05/22 03:06:53 [I] [tcp.go:64] [adc1f5d46b1e9957] [ssh] tcp proxy listen port [6000]
2022/05/22 03:06:53 [I] [control.go:465] [adc1f5d46b1e9957] new proxy [ssh] success

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
> 2022/05/22 03:06:53 [W] [control.go:461] [adc1f5d46b1e9957] new proxy [qbittorrent] error: **type [http] not support when vhost_http_port is not set**

Please set vhost_http_port.
