### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by stebansaa** [fatedier/frp#2948]
### Describe the feature request

I would like to be able to expose a RPC server as if it was a local service, and then connect it to a remote server.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by blizard863** [comment]
Just use the TCP type, see more official doc.
