### ISSUE TITLE
plugin_http_proxy doesn't open web site

### ISSUE THREAD

**Issue by atimofeev86** [fatedier/frp#2949]
### Bug Description

I tried to use plugin_http_proxy

when I open web browser with proxy I see an error: 
Hmm. We’re having trouble finding that site.

An error occurred during a connection to whoer.net. 

If I use plugin_socks5 web site opens fine.

### frpc Version

0.42

### frps Version

0.42

### System Architecture

linux/amd6

### Configurations
server config:
[common]
bind_port = 24031

client config:
[common]
server_addr = 51.81.4.100
server_port = 24031

[http_proxy]
type = tcp
remote_port = 24000
plugin = http_proxy

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by atimofeev86** [comment]
I think it has something to do with dns

**Comment by BecodReyes** [comment]
![CM6PHS7AGGJPN31Y2DI83MS.png](https://s2.loli.net/2022/05/19/YCWKze3vuMG4lrt.png)
