### ISSUE TITLE
关于frpc后台运行时，防止进程意外退出的方法

### ISSUE THREAD

**Issue by vistasea** [fatedier/frp#295]
先感谢作者，使用很方便。有个小问题：ISP每隔两天会自动重新分配IP，也就是每隔两天网络会断开，然后路由器再重连，这个过程中frpc退出不起作用了，这样要经常手动重新启动frpc，但是远程情况下，就没办法手动重启了，能否去掉网络断开退出这个设置呢？谢谢

**Comment by fatedier** [comment]
可以先搜 issue 了解相关问题的情况。

然后再有问题，可以贴出详细信息。

**Comment by vistasea** [comment]
自己又试验了几次
先打开putty运行frpc，然后主动断开网络，再重连，可以看到frpc也会自动重连，可以正常使用。

每次不明退出，都是在连网一段时间后，路由网络断开然后重连，随后frpc就不在后台了。

看来网络断开不一定会引起frpc退出，而长时间运行后，如果网络断开则会退出，原因不明。日志文件设置后无效，所以没有日志可看

我是在路由器上运行的frpc，路由内存256M，frpc后台运行时显示有70%内存可用。

不知道能不能加个守护，或者每隔一段时间检测frpc是否运行，如果检测不到，则重新启动的脚本

**Comment by fatedier** [comment]
frpc 一旦运行成功，不会主动退出。异常情况需要提供日志或者其他相关信息才能分析原因。

最好自己分析原因再指出问题，否则无法复现的问题也很难给出任何帮助。比如 "看来网络断开不一定会引起frpc退出，而长时间运行后，如果网络断开则会退出，原因不明。日志文件设置后无效，所以没有日志可看"， 这个是否有进行过准确的测试？能够稳定复现？是否在其他平台验证过此问题？

提供的信息越详细，越容易复现和定位问题，否则，没有精力对这样的 issue 持续跟进。

**Comment by vistasea** [comment]
谢谢回复，抱歉暂时找不到原因，我在计划任务加这个脚本，设置每隔十分钟运行，麻烦看下是否可行，谢谢！
#!/bin/sh

RUNNING=`pgrep frpc`

   if [ -n "$RUNNING" ];then

        echo "program is running"

   else
        echo "starting frpc"

         /root/frpc/frpc -c /root/frpc/frpc.ini &
   fi

**Comment by dfc643** [comment]
同有此问题，如果 frps 在 frpc 之后启动，frpc 就不会自动重连。
我现在的环境是 pi 启动后发送 api 启动 frps，导致 frpc 开机无法连上 frps
