### ISSUE TITLE
多台代理主机需要TCP协议端口转发，如何为不同的代理主机设置不同的Token呢

### ISSUE THREAD

**Issue by pxycn** [fatedier/frp#2952]
### Bug Description

一台外网云服务器装了fprs，现在要给多台代理主机提供TCP协议端口转发服务。请问如何给不同的代理主机设置不同的token。
目的：如果不想给其中一台代理主机提供服务，希望在frps端修改器对应的token，即可，而不想其他代理主机的正常使用。

能实现吗，改如何配置呢

谢谢

### frpc Version

0.42

### frps Version

0.42

### System Architecture

windows/amd64

### Configurations

只有基本的配置。

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by maozaizi** [comment]
跟你有类似的需求，我目前的做法是frps部署在VPS，frpc则部署在本地路由器中。这样就能变相的实现你想要的功能。当然了，这需要你花一笔钱来购买可以部署frpc的路由器设备。

**Comment by fatedier** [comment]
https://github.com/gofrp/fp-multiuser

**Comment by pxycn** [comment]
> https://github.com/gofrp/fp-multiuser

感谢，
但是WINDOWS SERVER 2003支持的最后版本是：frp_0.24.1，而多用户验证的版本要求是 v0.31.0，能不能编译一个多用户支持版本支持代理主机是WINDOWS SERVER 2003 的 frpc 端啊？ 因为代理主机是用户的，他用windows server 2003，我决定不了。

**Comment by fatedier** [comment]
精力有限，请自行尝试其他解决方案。
