### ISSUE TITLE
Windows报frp潜在的垃圾软件

### ISSUE THREAD

**Issue by tldzyx** [fatedier/frp#2959]
### Bug Description

建议不要在程序中包含外部链接
![image](https://user-images.githubusercontent.com/5987706/170870465-16ce5497-85c2-4be7-82fc-354117a43856.png)

### frpc Version

0.42.0

### frps Version

0.42.0

### System Architecture

linux/amd64, windows/amd64

### Configurations

none

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by JinOuYongGu** [comment]
同样的问题，被微软自动杀了好几次了qwq
