### ISSUE TITLE
mipsle版frpc可能有些问题

### ISSUE THREAD

**Issue by topillar** [fatedier/frp#296]
同样的配置文件在Windows下没有问题，但在路由器上怎么都不成，因此猜测mipsle版可能有问题，不知道有没有成功的。

# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000
auth_token = test
[ssh]
type = tcp
local_ip = 192.168.1.12
local_port = 22

# ./frpc_linux_mipsle -c ./frpc.ini
2017/04/11 15:37:50 [main.go:109] [I] Start frpc success
2017/04/11 15:37:50 [control.go:151] [E] ProxyName [ssh], connect to server [x.x.x.x:7000] error, dial tcp x.x.x.x:7000: errno -89
2017/04/11 15:37:50 [control.go:39] [E] ProxyName [ssh], connect to server failed!
2017/04/11 15:37:50 [main.go:112] [W] All proxy exit!

**Comment by topillar** [comment]
难道又是uclib的问题？rootfs中有ld-uClibc-0.9.33.2.so。errno -89 是否就是0x59，对应EDESTADDRREQ,解释为：不处于连接模式，没有指定对端地址（Destination address required）。
golang的sys call 与uclibc调用接口问题吗？

**Comment by fatedier** [comment]
Go 对于 mipsle 目前支持也不是很好，如果有兴趣你可以继续跟下去。

**Comment by topillar** [comment]
虽然很有兴趣，然能力有限，非常感谢您做的frp。

**Comment by topillar** [comment]
zerrors_linux_mipsle.go   ：ENOSYS          = Errno(0x59) ， EDESTADDRREQ    = Errno(0x60)
zerrors_linux_amd64.go ：EDESTADDRREQ    = Errno(0x59)
zerrors_linux_arm.go： EDESTADDRREQ    = Errno(0x59)
zerrors_linux_386.go： EDESTADDRREQ    = Errno(0x59)
zerrors_linux_mips64.go：EDESTADDRREQ    = Errno(0x60)
zerrors_linux_mips64le.go：EDESTADDRREQ    = Errno(0x60)
zerrors_linux_mips.go： EDESTADDRREQ    = Errno(0x60)

**Comment by marspage** [comment]
mipsle, BCM 4706, Netgear R6300 V1, frpc v0.13.0前来报道：connect to server failed

**Comment by zhagoonet** [comment]
1. mipsle,mtk sdk4300: mipsel-linux-uclibc-gcc-3.4.2 异常
[W] [control.go:121] login to server failed: lookup x.x.x.x on 192.168.30.1:53: dial udp 192.168.30.1:53: errno -89
lookup x.x.x.x on 192.168.30.1:53: dial udp 192.168.30.1:53: errno -89

1. mipsle,mtkop -v3.3: mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2
同样配置使用正常。
