### ISSUE TITLE
type=http时，开启proxy_protocol导致404响应

### ISSUE THREAD

**Issue by zhezhe168** [fatedier/frp#2962]
### Bug Description

type=http时，开启proxy_protocol导致404响应
页面是frp的默认404白底黑字页面
无论proxy_protocol=v1还是v2，都是一样情况

### frpc Version

0.43.0

### frps Version

0.43.0

### System Architecture

arm,amd64

### Configurations

[web02]
type = http
local_ip = 192.168.1.2
local_port = 80
custom_domains = *
# if not empty, frpc will use proxy protocol to transfer connection info to your local service
# v1 or v2 or empty
proxy_protocol_version = v2

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by BecodReyes** [comment]
`proxy_protocol`需要后端支持以及正确配置

请贴相关配置文件
