### ISSUE TITLE
frpc reload command is not compatible with '--config_dir' flags

### ISSUE THREAD

**Issue by aa51513** [fatedier/frp#2964]
### Bug Description

/usr/bin/frpc reload --config_dir /etc/frp/client.d
open ./frpc.ini: no such file or directory

### frpc Version

0.43.0

### frps Version

0.43.0

### System Architecture

linux/amd64

### Configurations

root@server:~# frpc reload --help
Hot-Reload frpc configuration

Usage:
  frpc reload [flags]

Flags:
  -h, --help   help for reload

Global Flags:
  -c, --config string       config file of frpc (default "./frpc.ini")
      --config_dir string   config directory, run one frpc service for each file in config directory
  -v, --version             version of frpc

### Logs

open ./frpc.ini: no such file or directory

### Steps to reproduce

1. run command '/usr/bin/frpc reload --config_dir /etc/frp/client.d' in linux shell
2. got "open ./frpc.ini: no such file or directory"

### Affected area

- [X] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Yes, not compatible.
