### ISSUE TITLE
tcp可以连接远程桌面，换成stcp连接不了。

### ISSUE THREAD

**Issue by esperar** [fatedier/frp#2967]
### Bug Description

tcp可以连接远程桌面，换成stcp连接不了

### frpc Version

0.33.0

### frps Version

0.33.0

### System Architecture

内网windows8，云服务器Linux，外网windows8

### Configurations

云服务器Linux
[commom]
bind_port = 7000
bind_udp_port = 7000
token =123123

被访问的内网电脑windows8
[common]
server_addr = 云服务器ip
server_port = 7000
token = 123123

[remotedesktop]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 3389

[remotedesktop_stcp]
type = stcp
sk = adad1212
local_ip = 127.0.0.1
local_port = 3389
use_encryption = false
use_compression = false

[remotedesktop_xtcp]
type = xtcp
sk = adad1212
local_ip = 127.0.0.1
local_port = 3389
use_encryption = false
use_compression = false
通过仪表盘可以看见stcp和xtcp，connection为0

外网电脑windows8
[common]
server_addr =  云服务器ip
server_port = 7000
token = 123123

admin_addr = 127.0.0.1
admin_port = 7400
admin_user = admin
admin_pwd = admin

[remotedesktop_stcp_visitor]
role = visitor
type = stcp
server_name = remotedesktop_stcp
sk = adad1212
bind_addr = 127.0.0.1
bind_port = 2323
use_encryption = false
use_compression = false

[remotedesktop_xtcp_visitor]
role = visitor
type = xtcp
server_name = remotedesktop_xtcp
sk = adad1212
bind_addr = 127.0.0.1
bind_port = 2324
use_encryption = false
use_compression = false

windows自带的远程桌面连接  云服务器ip，可以成功
远程桌面连接  云服务器ip：2323，无法连接到远程计算机
远程桌面连接  云服务器ip：2324，无法连接到远程计算机

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by BecodReyes** [comment]
> Some services will be at risk if **exposed directly to the public network**. With STCP (secret TCP) mode, a preshared key is needed to access the service from another client.

把云服ip换成127.0.0.1

或者使用tcp映射
