### ISSUE TITLE
authorization failed

### ISSUE THREAD

**Issue by geekmingl** [fatedier/frp#297]
这是 frps.ini
[common]
bind_addr = 0.0.0.0
bind_port = 1000
dashboard_port = 7500

[svn]
type = tcp
auth_token = !@#uniquepasswd
bind_addr = 0.0.0.0
listen_port = 443

[guilin-test]
type = tcp
auth_token = guilin-test
bind_addr = 0.0.0.0
listen_port = 8880

这是 frpc.ini
[common]
server_addr = 58.213.75.36
server_port = 1000

[guilin-test]
type = tcp
local_ip = 200.100.49.93
local_port = 8080
auth_token = guilin-test

 最后终端提示报错
2017/04/12 09:10:16 [main.go:109] [I] Start frpc success
2017/04/12 09:10:16 [control.go:202] [E] ProxyName [guilin-test], start proxy error, ProxyName [guilin-test], authorization failed
2017/04/12 09:10:16 [control.go:39] [E] ProxyName [guilin-test], connect to server failed!
2017/04/12 09:10:16 [main.go:112] [W] All proxy exit!

**Comment by topillar** [comment]
frpc.ini中auth_token = guilin-test放common试试。

**Comment by fatedier** [comment]
see #294
