### ISSUE TITLE
[Feature Request] Windows操作系统作为服务端，无法启用dashboard

### ISSUE THREAD

**Issue by zzzzbbbxxx** [fatedier/frp#2970]
### Describe the feature request

在windows操作系统的机器内，设置了frps.ini
[common]
dashboard_port 7500
后使用管理员权限用cmd启动frps.exe，显示frps started successfully, 但是通过浏览器访问 localhost:7500 无法连接，
netstat -ano|findstr 7500 也找不到这个端口被占用的情况，预测在windows服务器上无法使用dashboard？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
**不要用错模板**

![CM6PHS7AGGJPN31Y2DI83MS.png](https://s2.loli.net/2022/05/19/YCWKze3vuMG4lrt.png)

同理 缺少配置文件的诊断无异于你在请上帝给你解决，因为只有上帝知晓一切
