### ISSUE TITLE
访问网站cors error

### ISSUE THREAD

**Issue by 759855630** [fatedier/frp#2971]
### Bug Description

通过frp将内网网站穿透出来，使用公网ip访问，出现跨域问题，导致无法正常访问网站

### frpc Version

0.37.1

### frps Version

0.41.0

### System Architecture

linux/amd64

### Configurations

[ssh7777]
type = tcp
local_ip = 127.0.0.1
local_port = 7777
remote_port = 8888

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by 759855630** [comment]
![4142434dc1fbff35bf43b87192529b8](https://user-images.githubusercontent.com/45380727/172285891-8867eb9d-5e8e-4acc-b0ae-7de527297e63.png)

**Comment by BecodReyes** [comment]
服务端或者浏览器跨域配置问题

尝试加`Access-Control-Allow-Origin`头
