### ISSUE TITLE
[Feature Request] add `latest ` docker tag in docker hub

### ISSUE THREAD

**Issue by jayagami** [fatedier/frp#2972]
### Describe the feature request

add `latest ` docker tag in docker hub

currently only version and test tags appeared in docker hub
https://hub.docker.com/r/fatedier/frps/tags

if running
```
docker pull fatedier/frps
```
you will get
```
 Error response from daemon: manifest for fatedier/frps:latest not found:
``` 

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
[development-status](https://github.com/fatedier/frp#development-status)

No compatibility promise. You should always make sure which version you used.

**Comment by ImranR98** [comment]
Could this be re-opened? It is still an issue.

**Comment by jayagami** [comment]
> Could this be re-opened? It is still an issue.

I currently utilize a third-party Docker image.
