### ISSUE TITLE
nginx 做代理 转发tcp 上传超过7m的文件报502

### ISSUE THREAD

**Issue by iCloudys** [fatedier/frp#2974]
### Bug Description

正常按照教程搭建好客户端和服务端，如果直接使用服务端ip:端口号上传文件没问题，如果在服务端安装了nginx并且配置了proxy_pass 到本机的端口号，则上传超过7m会报502,并且log_level=trace没有日志信息

### frpc Version

0.43.0

### frps Version

0.43.0

### System Architecture

linux/amd64

### Configurations

frps.ini
``` 
[common]
bind_port = 223
log_level=trace
```

frpc.ini
``` 
[common]
server_addr = XXX.XXX.XXX.XXX
server_port = 223
log_level=trace

[tcp3]
type = tcp
remote_port=9877
local_ip = 127.0.0.1
local_port = 80
``` 

nginx.conf
```
server {
        listen       80;
        server_name  _;

        location /api/ {
	    client_max_body_size 1000M;
	    proxy_pass http://127.0.0.1:9877/;
	    proxy_redirect     off;  
            proxy_set_header   Host             $host;  
            proxy_set_header   X-Real-IP        $remote_addr;  
            proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;  
	}
    }
 
```
以上配置如果直接使用XXX.XXX.XXX.XXX:9877 上传文件没问题，如果使用XXX.XXX.XXX.XXX:80  文件超过7m就报502。
这边查看nginx日志和程序日志，以及frp日志，没有任何输出

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Paper-Folding** [comment]
That's the problem of nginx, please see documentation of nginx on how to configure the upload limits.

**Comment by BecodReyes** [comment]
依你的配置来看，frp转发tcp，由此可明确502发生在你的nginx上，请检查你的配置

**Comment by K2M74** [comment]
添加这个试试
proxy_buffering off;

**Comment by iCloudys** [comment]
@K2M74 依然不行

**Comment by star7th** [comment]
顺手看到了就回复下吧。我觉得，这样大概能解决： nginx配置里， client_max_body_size 1000M 放到location /api/  块的外面而不是里面。然后重启nginx

**Comment by iCloudys** [comment]
> 

这个方式试了，不行

**Comment by iCloudys** [comment]
@star7th 这个方式试了，不行

**Comment by cainb** [comment]
你好，我在用 nginx 转发时，也遇到了这个，请问你最后解决了嘛？

**Comment by iCloudys** [comment]
> 

没解决，放弃转发的方案了

**Comment by iCloudys** [comment]
@cainb 没解决，放弃转发的方案了

**Comment by cainb** [comment]
> @cainb 没解决，放弃转发的方案了

这样子吖，那新方案方便分享下嘛（

**Comment by cainb** [comment]
> 项目放公网了，所以不需要内网穿透了

我最近换了 openvpn 方案，实测完全没问题，如果你的服务不需要对公众用户开放，只是私人范围使用，推荐可以试试 openvpn（

**Comment by iCloudys** [comment]
> > 项目放公网了，所以不需要内网穿透了
> 
> 我最近换了 openvpn 方案，实测完全没问题，如果你的服务不需要对公众用户开放，只是私人范围使用，推荐可以试试 openvpn（

谢谢
