### ISSUE TITLE
[Feature Request] 希望在frpc内加入备用server-addr支持

### ISSUE THREAD

**Issue by coolxy** [fatedier/frp#2984]
### Describe the feature request

设置了frps服务器的重启，指向服务器的域名有多个，服务器重启后个别域名解析慢了点，能不能加入备用域名支持，当联不上一个时去连接另一个。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by K2M74** [comment]
既然是多个域名指向同一个服务器/IP，为何不直接多域名CNAME一个呢？
如果是多个服务器使用备用连接还稍微有点意义，但好像不能确定FRPC连接了哪台。
担心服务器出问题不知道建议用 uptime。
