### ISSUE TITLE
frpc 总是报错，启动不了，[service.go:128] login to server failed

### ISSUE THREAD

**Issue by pandona** [fatedier/frp#2985]
### Bug Description

frpc 启动失败，报错[service.go:128] login to server failed: EOF，远程服务端启动正常，端口也有打开，服务端关闭防火墙，frpc也还是启动失败交接不上。请大家帮帮忙

### frpc Version

0.43

### frps Version

0.43

### System Architecture

服务端linux/amd64，客户端 linux/mips

### Configurations

无异常

### Logs

[service.go:128] login to server failed: EOF^[[0m
Jun 17 07:04:07 【frp】:  EOF

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
测试端口是否**真正**打开

**Comment by changyonggang** [comment]
> 

我也遇到了一样的情况，telnet frps 端口是可以通的。

**Comment by zjsailor** [comment]
add this command on your client 
[common]
tls_enable = true

**Comment by DreamWaterFound** [comment]
> add this command on your client [common] tls_enable = true

It works. Thanks!

**Comment by wanglixiang90** [comment]
frps 服务端无法使用API管理，报错如下:
2022/09/19 17:02:51 [W] [service.go:128] login to server failed: EOF
2022/09/19 17:03:02 [W] [service.go:128] login to server failed: EOF
2022/09/19 17:03:13 [W] [service.go:128] login to server failed: EOF
2022/09/19 17:03:24 [W] [service.go:128] login to server failed: EOF
2022/09/19 17:03:34 [W] [service.go:128] login to server failed: EOF

**Comment by wanglixiang90** [comment]
尝试修改 frps 配置
[plugin.user-manager]
addr = 0.0.0.0:9000
path = /handler
ops = Login

[plugin.port-manager]
addr = 0.0.0.0:9001
path = /handler
ops = NewProxy

报错如下；
2022/09/19 17:05:46 [W] [service.go:128] login to server failed: EOF
2022/09/19 17:05:51 [E] [service.go:340] send Login request to plugin error
2022/09/19 17:05:51 [W] [service.go:128] login to server failed: send Login request to plugin error
2022/09/19 17:08:12 [E] [service.go:340] send Login request to plugin error
2022/09/19 17:08:12 [W] [service.go:128] login to server failed: send Login request to plugin error

服务端启动报错 ： logs.BeeLogger.SetLogger: open /tmp/frps.log: permission denied

**Comment by bithaolee** [comment]
> add this command on your client [common] tls_enable = true↳

thank you, it works

**Comment by TronYY** [comment]
> add this command on your client [common] tls_enable = true

[W] [service.go:128] login to server failed: session shutdown
session shutdown
