### ISSUE TITLE
"Cannot Execute Binary File" - Raspberry Pi 3

### ISSUE THREAD

**Issue by Bl0yster** [fatedier/frp#2988]
### Bug Description

Hi, I'm attempting to load frps.ini onto my raspberry pi 3, however it gives an error message when I attempt to run the program. "Exec Format Error" "Cannot execute binary file"

Any ideas? I'm using the AMD64 version (Which should be correct unless I'm missing something)

### frpc Version

N/A - Haven't even installed it yet

### frps Version

frps 0.43.0 AMD64

### System Architecture

linux/amd64

### Configurations

Attempting to run program using Raspbian

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
Use the arm version, the Raspberry Pi is based on arm.
