### ISSUE TITLE
[Feature Request] C library and/or protocol description

### ISSUE THREAD

**Issue by mickeyl** [fatedier/frp#2989]
### Describe the feature request

I'd like to directly connect to `frps` from platforms where I can't install `frpc`, e.g. iOS and/or microcontrollers, such as the ESP32 family of devices. For that I wonder whether a C library and/or a protocol description would be feasible, so that we could write our own clients that talk to `frps`.

### Describe alternatives you've considered

There are no alternatives, I can't install `frpc` on iOS or microcontrollers.

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Maybe you can try to build it by [tinygo](https://tinygo.org/)

**Comment by chuhangRadarDev** [comment]
Please refrence to [gateway-rs](https://github.com/OpenIoTHub/gateway-rs) which implemented the OpenIoTHub(Another one NAT tool) gateway on esp32, work ok,but speed low currently with about 512k ram

**Comment by Bellegar** [comment]
I was searching for frp library build and found several github repos.
I merged v0.48.0 and @HaidyCao projects of mobile library and desktop library how much I understood Go into https://github.com/Bellegar/frp_lib.
For direct testing, https://github.com/HaidyCao/libfrp/releases provides prebuild libs of v0.42.0 version for ios and android.
But my frp library project is not so optimised for using as library, but it work correctly for stcp from windows as visitor to android.
Did not touch tinygo.
