### ISSUE TITLE
frp + cloudflare 获取真实IP求教

### ISSUE THREAD

**Issue by ilworkcn** [fatedier/frp#2991]
### Bug Description

我目前使用的服务器软件是 nginx
目前的网络是 cloudflare - frp - nginx
目前启用了 proxy_protocolv2
但是现在网站获取到访客IP显示的是cloudflare服务器的IP 各种能想到的方法都试过了（我菜）
求教如何获取访客真实IP

### frpc Version

0.43.0

### frps Version

0.43.0

### System Architecture

linux/amd64

### Configurations

![屏幕截图 2022-06-24 105330](https://user-images.githubusercontent.com/34296329/175452856-13b75d49-de61-4815-abc2-f99f33121771.png)
![屏幕截图 2022-06-24 105404](https://user-images.githubusercontent.com/34296329/175452861-72d50718-1b08-4bbf-b172-562f2dbf425f.png)

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by BecodReyes** [comment]
一般来说CDN厂商都采用了X-Forwarded-For和X-Real_IP等标准协议
所以取这两个标头就行了

**Comment by ilworkcn** [comment]
> 

谢谢 我去试试
