### ISSUE TITLE
这该怎么办，看了/var/log的日志，有访问不良网站的记录，是怎么回事

### ISSUE THREAD

**Issue by esperar** [fatedier/frp#2993]
### Bug Description

2022/06/23 04:40:12 [W] [http.go:86] do http proxy request error: no such domain: wujieliulan.com /
2022/06/23 04:40:12 [W] [http.go:86] do http proxy request error: no such domain: www.minghui.org /
2022/06/23 04:40:12 [W] [http.go:86] do http proxy request error: no such domain: www.epochtimes.com /
2022/06/23 04:40:12 [W] [http.go:86] do http proxy request error: no such domain: www.boxun.com /
2022/06/23 04:40:12 [W] [http.go:86] do http proxy request error: no such domain: www.bing.com /
2022/06/23 04:40:12 [W] [http.go:86] do http proxy request error: no such domain: www.123cha.com /
2022/06/23 04:40:17 [W] [http.go:86] do http proxy request error: no such domain: www.rfa.org /
2022/06/23 04:40:17 [W] [http.go:86] do http proxy request error: no such domain: www.voanews.com

### frpc Version

0.33

### frps Version

0.33

### System Architecture

ubuntu

### Configurations

[common]
bind_port = 7000
bind_udp_port = 7000
token = 52010

vhost_http_port = 9090

dashboard_port = 7500
dashboard_user = admin1234
dashboard_pwd = admin1234
enable_prometheus = true

log_file = /var/log/frps.log
log_level = info
log_max_days = 3

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by esperar** [comment]
是被劫持了吗

**Comment by esperar** [comment]
日志的 [W] 代表什么

**Comment by ChrisKimZHT** [comment]
来扫站的，一般来说没啥影响。
