### ISSUE TITLE
Getting Real IP Addresses for Port Forwarding or P2P

### ISSUE THREAD

**Issue by EMREOYUN** [fatedier/frp#2995]
### Describe the feature request

While using port forwarding with frp, all connections reach to client shows as came from localhost, not from real address. Is it possible to enable real addresses?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp#get-real-ip

**Comment by EMREOYUN** [comment]
> https://github.com/fatedier/frp#get-real-ip

![image](https://user-images.githubusercontent.com/35144629/175928714-3d43d288-0a24-43aa-b6a3-c147e26e9dc1.png)
Doesn't work on TCP connections & clients also receive unsupported protocol errors and do not connect as well.

**Comment by EMREOYUN** [comment]
Alright, it seems we need to develop an implementation for the server as a plugin. Thanks for the answer.
