### ISSUE TITLE
如何从frps的dashboard中移除不用的连接

### ISSUE THREAD

**Issue by AiHaoChen** [fatedier/frp#3000]
### Bug Description

![image](https://user-images.githubusercontent.com/37200516/176903516-4f2e75b0-5910-4a88-bcb1-45a8373e772f.png)
如图，上面是我的两个连接，现在都已经不在使用了，我该如何从列表中移除他们？

### frpc Version

0.43.0

### frps Version

0.43.0

### System Architecture

frps windows/amd64， frpc linux/amd64

### Configurations

[common]
bind_port = 7001
vhost_http_port = 8888
dashboard_port = 8787
dashboard_user = admin
dashboard_pwd = 123456

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by aa51513** [comment]
Don't worry, they will disappear automatically after a while

**Comment by AiHaoChen** [comment]
> Don't worry, they will disappear automatically after a while

As of now, they are still on the list.

**Comment by HuaWang135608** [comment]
重启 frps 服务
