### ISSUE TITLE
vhost_https_port 可以设置多个端口么？

### ISSUE THREAD

**Issue by ChinaParrot** [fatedier/frp#3001]
### Describe the feature request

vhost_https_port 可以设置多个端口么？希望支持一下

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
目前不支持，v2 版本计划可以实现。
