### ISSUE TITLE
dashboard 没有被TLS加密

### ISSUE THREAD

**Issue by tlsalex** [fatedier/frp#3004]
### Bug Description

我的IP是1.2.3.4 ， dashboard 的端口是8080， 已经绑定了SSL证书，但无法通过https去访问dashboard, 通过http访问则无问题,提示以下错误：
```
Secure Connection Failed
An error occurred during a connection to my 1.2.3.4:8080. SSL received a record that exceeded the maximum permissible length.
Error code: SSL_ERROR_RX_RECORD_TOO_LONG
```
所绑定的证书用在nginx里是没有问题的，所以证书没问题。 即使subject name不匹配也应该能访问。

### frpc Version

0.43.0

### frps Version

0.43.0

### System Architecture

linux/amd64

### Configurations

```
#frps.ini

[common]
bind_port = 80

#proxy type
vhost_https_port = 443

#host header
subdomain_host = mydomain.cn

#TLS
tls_cert_file = /ssl/xray.crt
tls_key_file = /ssl/xray.key

#auth
token = mypasswork

#log
log_file = /var/log/frps.log
log_level = info
log_max_days = 7

#dashboard
dashboard_addr = 0.0.0.0
dashboard_port = 8080
dashboard_user = myuser
dashboard_pwd = mypasswork
```

### Logs

don't see logs for the access of dashboard.

### Steps to reproduce

1. start frps
2. access https://1.2.3.4:8080
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by k3rwin** [comment]
终于找到问题所在了，配置配的我怀疑人生😇
