### ISSUE TITLE
FRP_0.43_不断的中断重连

### ISSUE THREAD

**Issue by lonelydespair** [fatedier/frp#3006]
### Bug Description

FRP_0.43_每隔几个小时，或者一两天，就会自动中断，然后能自动重新连接成功？不知道是什么问题？
control writer is closing
work connection closed before response StartWorkConn message: EOF
gracefully shutdown visitor manager
try to reconnect to server...

### frpc Version

0.43

### frps Version

0.43

### System Architecture

windows/amd64

### Configurations

frps:
common
bind_addr = 0.0.0.0
bind_port = xx
dashboard_port =  xx			
dashboard_user =  xx	
dashboard_pwd =  xx
vhost_http_port =  xx
vhost_https_port =  xx
log_file = ./frps.log
log_level = error
log_max_days = 3
token =  xx
max_pool_count = 50
tcp_mux = true

frpc:
[common]
server_addr = xx
server_port = xx
token = xx
tls_enable = true

[range:127.0.0.1-xx]
type = tcp
local_ip = 127.0.0.1
local_port = xx
remote_port = xx

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by ForeverArt** [comment]
似乎和这个 issue 类似，https://github.com/fatedier/frp/issues/1657.
Mantainer 建议是设置 log_level=trace，观察数据流在哪里中断.
不过最终提出者设置 tcp_mux 规避了问题.
