### ISSUE TITLE
How to change the local ip?

### ISSUE THREAD

**Issue by Tonny-zhou** [fatedier/frp#3011]
### Describe the feature request

Dear author,

Thank you for this amazing tool!!! I have a question, i.e., can i change the local ip 127.0.0.1 (I am a newbie...)? I have changed the local ip 127.0.0.1 to the ip of my linux server, and then i could not connect to this linux server.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
Please check if your linux server can be accessed by a client running frpc.
