### ISSUE TITLE
[Feature Request] Global encryption and compression.

### ISSUE THREAD

**Issue by fernvenue** [fatedier/frp#3013]
### Describe the feature request

Hi, I just found out that all my frpc connection using encryption and compression, and I have to write them over and over again, could you please make them global? When the user write them in the `[common]` like this:

```
[common]
...
use_encryption = true
use_compression = true
...
```

Then, all the connection will enable encryption and compression.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Use `tls_enable` instead of `use_encryption`.

**Comment by fernvenue** [comment]
> Use `tls_enable` instead of `use_encryption`.

Sounds great, thanks a lot for your answer, I just added `tls_enable` to my config as you said, and I have some questions about that, hope this will not take up too much of your time:

- Does TLS will make traffic easier to identify?
- Is it require more resources than `use_necryption`?
- And what should I do if I wanna use compression for all connections?

Again, thanks for your help :)

**Comment by fatedier** [comment]
TLS is very common in the internet. You can also add `disable_custom_tls_first_byte = true` to eliminate particularity in frp.

Global compression is not planned. Maybe frp v2, we are working on it.

**Comment by fernvenue** [comment]
Thanks for such a clear answer, I will use `tls_enable` and `disable_custom_tls_first_byte` instead of `use_encryption`. Expect to see global compression in frp v2, I'm gonna close this issue for now, thanks again.

**Comment by zsinba** [comment]
> TLS 在 Internet 中非常常见。您还可以添加`disable_custom_tls_first_byte = true`以消除 frp 中的特殊性。
> 
> 未计划全局压缩。也许 frp v2，我们正在努力。

请问使用压缩，大概会多使用多少cpu，减少多少带宽？
