### ISSUE TITLE
OIDC 认证的时候 oidc_issuer oidc_audience oidc_client_id oidc_client_secret oidc_audience oidc_token_endpoint_url 说明是什么

### ISSUE THREAD

**Issue by Tongzhongren** [fatedier/frp#3015]
### Bug Description

OIDC 认证的时候 oidc_issuer oidc_audience oidc_client_id oidc_client_secret oidc_audience oidc_token_endpoint_url 说明是什么，能说一下吗

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

linux/amd64，windows/amd64

### Configurations

# frps.ini
[common]
authentication_method = oidc
oidc_issuer = https://example-oidc-issuer.com/
oidc_audience = https://oidc-audience.com/.default
# frpc.ini
[common]
authentication_method = oidc
oidc_client_id = 98692467-37de-409a-9fac-bb2585826f18 # Replace with OIDC client ID
oidc_client_secret = oidc_secret
oidc_audience = https://oidc-audience.com/.default
oidc_token_endpoint_url = https://example-oidc-endpoint.com/oauth2/v2.0/token

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
https://github.com/fatedier/frp/blob/4af85da0c2c6eb981142a8fdb44f885d26cb9d08/conf/frpc_full.ini#L43-L62
https://github.com/fatedier/frp/blob/4af85da0c2c6eb981142a8fdb44f885d26cb9d08/conf/frps_full.ini#L66-L94

**Comment by Tongzhongren** [comment]
> https://github.com/fatedier/frp/blob/4af85da0c2c6eb981142a8fdb44f885d26cb9d08/conf/frpc_full.ini#L43-L62
> 
> 
> https://github.com/fatedier/frp/blob/4af85da0c2c6eb981142a8fdb44f885d26cb9d08/conf/frps_full.ini#L66-L94

我想知道oidc服务怎么搭建，有具体的链接参考吗
