### ISSUE TITLE
能够直接转发端口吗？ 

### ISSUE THREAD

**Issue by cipfs** [fatedier/frp#3018]
### Describe the feature request

服务端能直接访问到客户端，可以只安装frps直接把端口映射到另外一台主机上吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
不能
请考虑使用端口转发

**Comment by Anduin2017** [comment]
这种情况没必要用frp呀

**Comment by cipfs** [comment]
> 这种情况没必要用frp呀
总感觉iptables 性能有问题
