### ISSUE TITLE
frp在BCM路由器里运行报错

### ISSUE THREAD

**Issue by yuhuan21** [fatedier/frp#302]
![qq 20170418142555](https://cloud.githubusercontent.com/assets/10203925/25129804/304972b2-2472-11e7-90ef-d5df1cd4e814.jpg)
这个是截图信息,我运行的设备是Broadcom BCM5357处理器的路由器,肯定能联网

**Comment by gigibox** [comment]
是不是配置的问题?

**Comment by yuhuan21** [comment]
配置肯定没问题,因为这个配置我是从正常运行的服务器里复制出来的,就是改一下节点名称而已,服务器我还试过直接用IP地址来配置

**Comment by liudf0716** [comment]
路由器上当然要用xfrp了

https://github.com/KunTengRom/xfrp

**Comment by Ramon403** [comment]
楼上这波广告666

**Comment by liudf0716** [comment]
做开源不易，开发还带推广

**Comment by yuhuan21** [comment]
@liudf0716 坑爹,XFRP没有编译好的版本,难道还要我自己编译?

**Comment by mindfocus** [comment]
@yuhuan21 你要是给钱， @liudf0716 可以提供编译版本
