### ISSUE TITLE
[Feature Request] 能不能增加对中文的兼容

### ISSUE THREAD

**Issue by haotian2004** [fatedier/frp#3023]
### Describe the feature request

能不能加入中文支持，指的是web界面，添加一个语言选择

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
暂时没有计划
