### ISSUE TITLE
ssh连接的时候提示要输入密码，请问这个密码是怎么获取到

### ISSUE THREAD

**Issue by animelfc** [fatedier/frp#3026]
### Bug Description

ssh连接的时候提示要输入密码，请问这个密码是怎么获取到
![QQ截图20220721135139](https://user-images.githubusercontent.com/16792882/180140520-d002e739-2ff6-436f-9c3e-1f289977e183.png)

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

linux/amd64

### Configurations

ssh连接的时候提示要输入密码，请问这个密码是怎么获取到

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Wuqibor** [comment]
这个密码是您服务器的密码，您是否可以学习Linux的基础知识后提问？
The password is the password to your server. Can you learn some basic knowledge about Linux after questions?

**Comment by animelfc** [comment]
您好，您的邮件已收到，查阅后，我会尽快回复您！
