### ISSUE TITLE
I cant open frpc.exe

### ISSUE THREAD

**Issue by mzjqwq** [fatedier/frp#3028]
### Bug Description

text in powershell/cmd:
open ./frpc.ini: The system cannot find the file specified.

### frpc Version

0.44.0 Windows x64

### frps Version

0.44.0 Windows x64

### System Architecture

windows/amd64

### Configurations

text in powershell/cmd:
open ./frpc.ini: The system cannot find the file specified.

### Logs

no log

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by mzjqwq** [comment]
but i can open frps.exe

**Comment by Becods** [comment]
The system cannot find frpc.ini,

Try creating and editing it.

And learn how to understand the error message thrown.

**Comment by fuyoo** [comment]
try [frper](https://github.com/fuyoo/frper) gui desktop client.
It's the wrapper of frpc

**Comment by yuyc2022** [comment]
[一键启动.zip](https://github.com/fatedier/frp/files/9388574/default.zip)
请解压它，并放在frps.exe同一目录

**Comment by yuyc2022** [comment]
并运行
