### ISSUE TITLE
请问frps 之前可以正常连接，现在必须客户端启用tls_enable=true才能连接了是什么原因呢

### ISSUE THREAD

**Issue by pope-L** [fatedier/frp#3029]
### Bug Description

请问frps 之前可以正常连接，现在必须客户端启用tls_enable=true才能连接了是什么原因呢

### frpc Version

0.33

### frps Version

0.33

### System Architecture

windows

### Configurations

原有

### Logs

客户端没加 tls_enable=true 时 无如何提示就是连不上

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
请更新

**Comment by pope-L** [comment]
是的 有新版， 不过这个 之前都正常，frps服务端按理也不会受有新版影响，我就好奇这个原因是什么， 是电信的问题 还是 本地防火墙的问题导致

**Comment by pope-L** [comment]
抱歉，我确认了 ，是我本地这里新加的防火墙导致的
结帖
