### ISSUE TITLE
frp的桌面配置工具由于携带了frpc 会被360这个病毒工具报病毒

### ISSUE THREAD

**Issue by fuyoo** [fatedier/frp#3035]
### Bug Description

我创建了一个frp的桌面配置工具[frper](https://github.com/fuyoo/frper)，这个工具可以可视化的配置并生成frpc.ini，然后执行frpc -c frpc.ini。
但是由于携带了frpc 会被360这个病毒工具报病毒。。。
我看了#2095。请问还有其他的解决方法吗？

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

windows/amd64

### Configurations

无

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by zjsailor** [comment]
敢用360.。。。。。
建议赶紧卸载。

**Comment by fuyoo** [comment]
> 敢用360.。。。。。 建议赶紧卸载。

兄弟，我也很无奈啊。别人用的。

**Comment by Becods** [comment]
加壳
