### ISSUE TITLE
frpc.ini依照配置port range & Envs在local_port上出錯

### ISSUE THREAD

**Issue by Superarc543** [fatedier/frp#3036]
### Bug Description

錯誤的frpc.ini：
[common]
server_addr = 10.1.3.68
server_port = 7000

[node_exporter]
type = tcp
local_ip = 127.0.0.1
**local_port = 9100-9200
remote_port = 9100-9200**

我僅配置單個Port (9100) 完全正常!!!!

如我修改為{{ .Envs.NODE }} ，如用多個非範圍的Port (Ex. 9100,9111,9122)依然錯誤

錯誤只顯示：
failed to parse proxy node_exporter err: error local_poxy node_exporter, err: error local_port

### frpc Version

0.44

### frps Version

0.44

### System Architecture

CentOS Linux release 7.9.2009 (Core)

### Configurations

[common]
server_addr = 10.1.3.68
server_port = 7000

[node_exporter]
type = tcp
local_ip = 127.0.0.1
**local_port = 9100-9200
remote_port = 9100-9200**

### Logs

failed to parse proxy node_exporter, err: error local_poxy node_exporter, err: error local_port

### Affected area

- [X] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fuyoo** [comment]
frpc could not support port-range

see [doc](https://gofrp.org/docs/reference/proxy/#tcp)

**Comment by Becods** [comment]
> frpc could not support port-range
> 
> see [doc](https://gofrp.org/docs/reference/proxy/#tcp)

👆 Outdated content.

See [Range ports mapping](https://github.com/fatedier/frp#range-ports-mapping).
