### ISSUE TITLE
[Feature Request] SSH 可以跟HTTP一样 使用不同的域名，同一个端口吗

### ISSUE THREAD

**Issue by rundaisc** [fatedier/frp#3038]
### Describe the feature request

现在有多个客户端想使用ssh, 目前每开启一个客户端 ssh ，服务器就要多开放一个端口。比较难以管理， 想问问ssh ，可以跟http一样，可以使用不同的子域名来区分吗。

比如 
http 
a.test.com  8081 
b.test.com  8081 

ssh
a.test.com  8082 
b.test.com  8082

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by Becods** [comment]
不能
