### ISSUE TITLE
[Feature Request]  Some questions on some Special scenarios when we use FRP solution 

### ISSUE THREAD

**Issue by sshuangliu** [fatedier/frp#3039]
### Describe the feature request

![image](https://user-images.githubusercontent.com/38092313/181739885-f66f7b53-12ce-4d56-806e-95f2b8b3eef9.png)

### Describe alternatives you've considered

1: it will not be a loop since the http request from frpc without HOST segment, the frps homepage will back to users
2: I have no idea , it is really need
### Affected area

- [ ] Docs
- [X] Installation
- [x] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
1. Yes.
2. Deploy nginx in front of frps and route traffics to frps and your wordpress by domains.

**Comment by sshuangliu** [comment]
> 1. Yes.
> 2. Deploy nginx in front of frps and route traffics to frps and your wordpress by domains.

1 yes ?
2. it is a good idea ,I can deploy Nginx Proxy Manager in front of frps
