### ISSUE TITLE
https2http碰到Error502

### ISSUE THREAD

**Issue by paladin4fan** [fatedier/frp#3040]
### Bug Description

申请了一个域名和对应的SSL证书 
服务器是nginx反代apache的owncloud
通过IPv6 直接使用https访问是正常的
现在用Frp穿透IPv4
之前v0.36的时候 用https2http插件 可以正常代理

但是重新安装系统后使用0.44版本 ipv4访问frp代理返回http error 502
另一个单纯的穿透http就正常

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

linux/amd64

### Configurations

[common]
server_addr = 18.176.xxx.xxx
server_port = 8443
token = ***
log_file = /var/log/frpc.log
log_level = debug
log_max_days = 3
pool_count = 0
tcp_mux = true
login_fail_exit = false
protocol = tcp
tls_enable = false
heartbeat_interval = 30
heartbeat_timeout = 90
[Web-test]
type = http
local_ip = 192.168.10.2
local_port = 32080
use_encryption = false
use_compression = false
custom_domains = b.mydomain.xyz
[OC]
type = https
plugin = https2http
plugin_local_addr = [192.168.10.2:8080]
plugin_crt_path = /etc/frpc/ssl/1_domain_bundle.crt
plugin_key_path = /etc/frpc/ssl/2_domain.key
plugin_host_header_rewrite = a.mydomain.xyz
use_encryption = false
use_compression = false
custom_domains = a.mydomain.xyz

### Logs

frp客户端日志相关如下
2022/07/29 14:32:43 [D] [proxy_wrapper.go:231] [1c2ede17a19f814e] [OC] start a new work connection, localAddr: 10.118.xx.xx:55442 remoteAddr: 18.176.xxx.xxx:8443
2022/07/29 14:32:43 [D] [proxy.go:783] [1c2ede17a19f814e] [OC] handle by plugin: https2http
2022/07/29 14:32:43 [D] [proxy.go:785] [1c2ede17a19f814e] [OC] handle by plugin finished

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by paladin4fan** [comment]
> ### Bug Description
> 申请了一个域名和对应的SSL证书 服务器是nginx反代apache的owncloud 通过IPv6 直接使用https访问是正常的 现在用Frp穿透IPv4 之前v0.36的时候 用https2http插件 可以正常代理
> 
> 但是重新安装系统后使用0.44版本 ipv4访问frp代理返回http error 502 另一个单纯的穿透http就正常
> 
> ### frpc Version
> 0.44.0
> 
> ### frps Version
> 0.44.0
> 
> ### System Architecture
> linux/amd64
> 
> ### Configurations
> [common] server_addr = 18.176.xxx.xxx server_port = 8443 token = *** log_file = /var/log/frpc.log log_level = debug log_max_days = 3 pool_count = 0 tcp_mux = true login_fail_exit = false protocol = tcp tls_enable = false heartbeat_interval = 30 heartbeat_timeout = 90 [Web-test] type = http local_ip = 192.168.10.2 local_port = 32080 use_encryption = false use_compression = false custom_domains = b.mydomain.xyz [OC] type = https plugin = https2http plugin_local_addr = [192.168.10.2:8080] plugin_crt_path = /etc/frpc/ssl/1_domain_bundle.crt plugin_key_path = /etc/frpc/ssl/2_domain.key plugin_host_header_rewrite = a.mydomain.xyz use_encryption = false use_compression = false custom_domains = a.mydomain.xyz
> 
> ### Logs
> frp客户端日志相关如下 2022/07/29 14:32:43 [D] [proxy_wrapper.go:231] [1c2ede17a19f814e] [OC] start a new work connection, localAddr: 10.118.xx.xx:55442 remoteAddr: 18.176.xxx.xxx:8443 2022/07/29 14:32:43 [D] [proxy.go:783] [1c2ede17a19f814e] [OC] handle by plugin: https2http 2022/07/29 14:32:43 [D] [proxy.go:785] [1c2ede17a19f814e] [OC] handle by plugin finished
> 
> ### Steps to reproduce
> 
> ...
> 
> ### Affected area
> * [ ]  Docs
> * [ ]  Installation
> * [ ]  Performance and Scalability
> * [ ]  Security
> * [ ]  User Experience
> * [ ]  Test and Release
> * [ ]  Developer Infrastructure
> * [x]  Client Plugin
> * [ ]  Server Plugin
> * [ ]  Extensions
> * [ ]  Others

是我自己搞错了 mdzz

**Comment by superzjg** [comment]
你使用是这个frpc的luci界面有小问题：插件-本地地址不能带端口号，否则会错误的显示 [192.168.10.2:8080]，但这个luci支持代理增加额外选项，插件-本地地址那里留空，然后最下面额外选项写plugin_local_addr=192.168.10.2:8080即可

**Comment by paladin4fan** [comment]
> 你使用是这个frpc的luci界面有小问题：插件-本地地址不能带端口号，否则会错误的显示 [192.168.10.2:8080]，但这个luci支持代理增加额外选项，插件-本地地址那里留空，然后最下面额外选项写plugin_local_addr=192.168.10.2:8080即可

是的 我之前就遇到过了 这次换路由器忘了这茬
已经修改了相关的init脚本 但是这个项目好像没人维护了 我只能自己fork出去了
