### ISSUE TITLE
[Feature Request]  remove TLS 1.0/1.1 support

### ISSUE THREAD

**Issue by Popo-TW** [fatedier/frp#3043]
### Describe the feature request

sslscan frp server bind_port TLSv1.0/1.1   enabled
If not blocked, detect obsolete cipher suites

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Popo-TW** [comment]
frp 0.35.1

- TLSv1.0   disabled
- TLSv1.1   disabled
- TLSv1.2   disabled
- TLSv1.3   disabled

frp 0.41.0

- TLSv1.0   enabled
- TLSv1.1   enabled
- TLSv1.2   enabled
- TLSv1.3   enabled

**Comment by Becods** [comment]
Why do you propose to do this?

What is the motivation for doing it?

What will happen when the proposal is implemented?

**Comment by Anduin2017** [comment]
Directly expose 443 port as pure TCP. Secure that in the original web server.
