### ISSUE TITLE
not support when vhost_http_port is not set

### ISSUE THREAD

**Issue by Liner03** [fatedier/frp#3044]
### Bug Description

服务端配置
![image](https://user-images.githubusercontent.com/38096847/182584158-49a85bc3-b435-4d0c-b905-a216ab4f6d92.png)
客户端配置
![image](https://user-images.githubusercontent.com/38096847/182584319-9e532ac3-7d4a-4536-aedd-7765dcfb9287.png)
运行结果
![image](https://user-images.githubusercontent.com/38096847/182584479-b472d4b3-fd0d-4af5-8d51-caa9ebd461ce.png)

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

arm64

### Configurations

服务端配置
![image](https://user-images.githubusercontent.com/38096847/182584158-49a85bc3-b435-4d0c-b905-a216ab4f6d92.png)
客户端配置
![image](https://user-images.githubusercontent.com/38096847/182584319-9e532ac3-7d4a-4536-aedd-7765dcfb9287.png)

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
无法复现

![image](https://user-images.githubusercontent.com/35525491/182617025-406e7677-70d6-40b4-8bc1-7b0870fce6da.png)
