### ISSUE TITLE
[Feature Request]  Publish frps and frpc to package manager to allow auto upgrading.

### ISSUE THREAD

**Issue by Anduin2017** [fatedier/frp#3045]
### Describe the feature request

Hi.

Since we are using FRP, every time it releases a new version, we need to manually update it on the server side and on the client side. It brings us possibility to make mistakes and have to do that manually.

Do your team ever consider to publish that to a package manager like 'apt' so I can do: 'sudo apt install frps' to install it and update it along side with system upsates?

Thanks!

### Describe alternatives you've considered

Every time it releases a new version, we need to manually update it on the server side and on the client side.

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
No experience and enough time to do this.

**Comment by Anduin2017** [comment]
Got it. I will try to build a custom installation and upgrade script.

**Comment by Anduin2017** [comment]
I just wrote a very brief frpc upgrade script for myself to use, incase anyone need it.

```bash
latestUrl=$(curl https://api.github.com/repos/fatedier/frp/releases/latest | jq -r '(.assets[] | select(.browser_download_url | contains("linux_amd64"))).browser_download_url')
echo "Latest download url is $latestUrl"
wget -O /home/anduin/frp.tar.gz $latestUrl
mkdir /home/anduin/temp
tar -zxvf /home/anduin/frp.tar.gz --directory /home/anduin/temp

frpcPath=$(find /home/anduin/temp/ -name "frpc")
frpsPath=$(find /home/anduin/temp/ -name "frps")

sudo systemctl stop frpc.service
sudo cp $frpcPath /usr/bin/
sudo cp $frpsPath /usr/bin/
sudo systemctl start frpc.service
sudo systemctl status frpc.service
```
