### ISSUE TITLE
Missing systemd folder

### ISSUE THREAD

**Issue by Gensight** [fatedier/frp#3048]
### Bug Description

I use FRP with my production AI system and tried to download [frp_0.44.0_linux_arm64.tar.gz] but am missing the systemd folder. I need this to run as a service. Please advise.

### frpc Version

44.0

### frps Version

44.0

### System Architecture

linux/arm64

### Configurations

basic port forwarding

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
https://github.com/fatedier/frp/blob/a72259c604f23a077f6030f1b141a80ce060f1c3/conf/systemd/frpc.service#L1-L15

https://github.com/fatedier/frp/blob/a72259c604f23a077f6030f1b141a80ce060f1c3/conf/systemd/frpc%40.service#L1-L15

https://github.com/fatedier/frp/blob/a72259c604f23a077f6030f1b141a80ce060f1c3/conf/systemd/frps.service#L1-L14

https://github.com/fatedier/frp/blob/a72259c604f23a077f6030f1b141a80ce060f1c3/conf/systemd/frps%40.service#L1-L14

**Comment by fatedier** [comment]
There are many systemd issues or PRs and we have not enough resource to sovle it, so it was removed from the official release assets to avoid usage problems.

You can write your own systemd or other deploy files if needed.

We may provide deploy configs when we have active developers focus on this area.

**Comment by c04022004** [comment]
Was using the `systemd` files along with older versions without much problem.

Good to know about the reason behind the removal, completely understand your concerns.
Hope it can be put back soon.
