### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by yexingr** [fatedier/frp#3049]
### Describe the feature request

Whether you can add a management client on the web view page to control the opening and closing of the client

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
https://github.com/fatedier/frp/issues/1570

> v0.31.0 已支持服务端插件，可以自行实现。

https://github.com/fatedier/frp/issues/3033

> Planned in frp v2, we want to support multiple configure registry such as static file, remote url, etc.
