### ISSUE TITLE
getsockopt: no route to host错误

### ISSUE THREAD

**Issue by 694982827** [fatedier/frp#305]
我所处服务器所在网络有的时候会有点小波动，出现no route to host的错误后一直卡在这里，当网络恢复正常后依然一直报这个错误，重新启动frpc客户端程序才正常。
**************************************日志如下**************************************
_2017/04/23 00:00:11 [control.go:81] [I] ProxyName [6000], try to reconnect to frps [xx.xx.xx.xx:7000]...
2017/04/23 00:00:11 [control.go:81] [I] ProxyName [6001], try to reconnect to frps [xx.xx.xx.xx:7000]...
2017/04/23 00:00:14 [control.go:151] [E] ProxyName [6000], connect to server [xx.xx.xx.xx:7000] error, dial tcp xx.xx.xx.xx:7000: getsockopt: no route to host
2017/04/23 00:00:14 [control.go:151] [E] ProxyName [6001], connect to server [xx.xx.xx.xx:7000] error, dial tcp xx.xx.xx.xx:7000: getsockopt: no route to host
2017/04/23 00:00:44 [control.go:81] [I] ProxyName [6001], try to reconnect to frps [xx.xx.xx.xx:7000]...
2017/04/23 00:00:44 [control.go:81] [I] ProxyName [6000], try to reconnect to frps [xx.xx.xx.xx:7000]...
2017/04/23 00:00:47 [control.go:151] [E] ProxyName [6000], connect to server [xx.xx.xx.xx:7000] error, dial tcp xx.xx.xx.xx:7000: getsockopt: no route to host
2017/04/23 00:00:47 [control.go:151] [E] ProxyName [6001], connect to server [xx.xx.xx.xx:7000] error, dial tcp xx.xx.xx.xx:7000: getsockopt: no route to host
2017/04/23 00:01:17 [control.go:81] [I] ProxyName [6000], try to reconnect to frps [xx.xx.xx.xx:7000]...
2017/04/23 00:01:17 [control.go:81] [I] ProxyName [6001], try to reconnect to frps [xx.xx.xx.xx:7000]...
2017/04/23 00:01:20 [control.go:151] [E] ProxyName [6001], connect to server [xx.xx.xx.xx:7000] error, dial tcp xx.xx.xx.xx:7000: getsockopt: no route to host
2017/04/23 00:01:20 [control.go:151] [E] ProxyName [6000], connect to server [xx.xx.xx.xx:7000] error, dial tcp xx.xx.xx.xx:7000: getsockopt: no route to host
2017/04/23 00:01:50 [control.go:81] [I] ProxyName [6001], try to reconnect to frps [xx.xx.xx.xx:7000]...
2017/04/23 00:01:50 [control.go:81] [I] ProxyName [6000], try to reconnect to frps [xx.xx.xx.xx:7000]...
2017/04/23 00:01:53 [control.go:151] [E] ProxyName [6001], connect to server [xx.xx.xx.xx:7000] error, dial tcp xx.xx.xx.xx:7000: getsockopt: no route to host
2017/04/23 00:01:53 [control.go:151] [E] ProxyName [6000], connect to server [xx.xx.xx.xx:7000] error, dial tcp xx.xx.xx.xx:7000: getsockopt: no route to host_
*************************************************************************************************
请问是什么原因？

**Comment by fatedier** [comment]
日志上看是网络问题，连不上服务器。
