### ISSUE TITLE
[Feature Request] Request to display the remote IP address of the service provider of stcp and sudp on the frps dashboard

### ISSUE THREAD

**Issue by aa51513** [fatedier/frp#3051]
### Describe the feature request

I have many servers with the exact same frpc configuration on them.

Usually I only start frpc on one of the servers for stcp connection.

I ran into a pretty big trouble today: I can't remember which machine I'm running frpc on.

Obviously, with so many machines, I can't find them one by one.

So I thought of the frps dashboard, and in the end I was very sorry, I didn't find any information about the IP address in "proxies-STCP-connection information".

Considering the principle of stcp, frps must know the IP address of the stcp service provider, and the dashboard display will not bring additional security problems. Can you consider supporting this feature?

### Describe alternatives you've considered

Display the IP address of the stcp service provider on the frps dashboard

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
Maybe you can set [user](https://github.com/fatedier/frp/blob/dev/conf/frpc_full.ini#L83) in different frpc.ini
