### ISSUE TITLE
How many ports could be mapped?

### ISSUE THREAD

**Issue by yuhang9580** [fatedier/frp#3053]
### Bug Description

i have tried to mapped from 1 to 65535 ,server and client has no error, and i tried one port , and i didn't get any response from the server

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

linux/and64

### Configurations

[range:test_tcp]
type = tcp
local_ip = 127.0.0.1
local_port = 1-65535
remote_port = 1-65535

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
Please make sure that the port you are trying on has a corresponding service listening on the frpc side.
