### ISSUE TITLE
external IP forward UDP

### ISSUE THREAD

**Issue by lootoos** [fatedier/frp#3054]
### Describe the feature request

The frp server will take the external IP of the connected player and transfer it to the frp client so that the players have the correct IP on the Minecraft game server

The function will be useful for game servers\various sites.

Why can't  implement Ip forward for UDP protocol?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [X] Extensions
- [X] Others

**Comment by fatedier** [comment]
PRs are welcome.

**Comment by lootoos** [comment]
I don't understand what you're talking about, I'm mostly Russian

**Comment by fatedier** [comment]
Anyone needs this feature can contribute to this project.

**Comment by Becods** [comment]
Are you a be player?

Currently, the proxy protocol of frp only supports tcp (I guess so).

So you need to use other methods to get the player's ip.

For example DSR or IP address pass-through.

But I don't know much about this, you might google for information on it

**Comment by lootoos** [comment]
> Are you a be player?
> 
> Currently, the proxy protocol of frp only supports tcp (I guess so).
> 
> So you need to use other methods to get the player's ip.
> 
> For example DSR or IP address pass-through.
> 
> But I don't know much about this, you might google for information on it

I am the creator of the server.
all players on the server have Ip 10.228.228.1 - to avoid this, add   support the proxy protocol or support IP forward

DSR or IP address pass-through. - are there articles on setting this up?
