### ISSUE TITLE
can not relate to the intranet mac service

### ISSUE THREAD

**Issue by bowuL** [fatedier/frp#3055]
### Bug Description

Remote cloud linux service start frps successfully,and intranet mac start frpc successfully,use another computer ssh connect to the mac,but can not do well,as long as i `ssh xxx`,and type password, but always show me this, whatever I type  mac's password or remote cloud service's password is not do well, can you give me any advice?

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

linux/amd64

### Configurations

![image](https://user-images.githubusercontent.com/41602940/184054628-32db0e86-7067-4b5e-ad00-9e6efcd30eab.png)
![image](https://user-images.githubusercontent.com/41602940/184054667-2241bf9c-ce89-4790-996f-2f04a2e3a5ec.png)

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/184063719-2727fabc-cfe3-4d88-bad9-5b59714c6f19.png)
