### ISSUE TITLE
[Feature Request] 请问一下有没有frp设计文档可以共享一下？我想用其他语言实现frpc客户端

### ISSUE THREAD

**Issue by aa51513** [fatedier/frp#3056]
### Describe the feature request

我想用其他语言实现frpc客户端，目标是为了能够在手机上安装附加有frpc的APP

### Describe alternatives you've considered

我想请问一下有没有相关设计文档？
如果没有，是否从“msg.go”开始看起，就能够入门了呢

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
应该没有

不过，你可以去看看相关轮子，比如[FrpcCluster/frpc-Android](https://github.com/FrpcCluster/frpc-Android)、[qiuhaotc/frp_android](https://github.com/qiuhaotc/frp_android)

**Comment by aa51513** [comment]
> 应该没有
> 
> 不过，你可以去看看相关轮子，比如[FrpcCluster/frpc-Android](https://github.com/FrpcCluster/frpc-Android)、[qiuhaotc/frp_android](https://github.com/qiuhaotc/frp_android)

感谢回复
这两个项目，我都去看了一下，都是将本项目编译成Libiary来调用，并不是用其他语言来实现的

**Comment by coderhh** [comment]
我也想知道

**Comment by dwxiayi** [comment]
我看着一些注册的接口是json

**Comment by dwxiayi** [comment]
手机上用go还行吧 路由器上占用内存、可执行程序都比较大，用upx压缩了后小了一些。
