### ISSUE TITLE
[Feature Request] 请问能编译一个 在 iStoreOS arm cpu路由器能使用的 FRPC插件吗？

### ISSUE THREAD

**Issue by sven721** [fatedier/frp#3057]
### Describe the feature request

请问能编译一个 在 iStoreOS arm cpu路由器能使用的 FRPC插件吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
自行在软件中心里找 [linkease/istore](https://github.com/linkease/istore)

**Comment by duliang123** [comment]
frpc 在OpenWrt中占用内存很高，有优化的方面吗

**Comment by duliang123** [comment]
luci-app-frpc

**Comment by sven721** [comment]
<img width="1769" alt="image" src="https://user-images.githubusercontent.com/7079455/184330994-6c372c8e-037c-41a0-bcd4-3ef5a5f6733b.png">
是这里找到的一个，报错了。
我的路由器信息：
主机名 | iStoreOS
型号 | FriendlyElec NanoPi R5S
架构 | ARMv8 Processor rev 0
固件版本 | OpenWrt 21.02.1 2022061021 / LuCI branch git-22.161.50247-cb92cb0
内核版本 | 4.19.219

**Comment by Becods** [comment]
非frp错误

请在对应仓库回报问题

**Comment by sven721** [comment]
好的 。
