### ISSUE TITLE
login to server failed: dial tcp 182.243.33.96:7000: i/o timeout

### ISSUE THREAD

**Issue by coolxy** [fatedier/frp#3058]
### Bug Description

I have two frpc client,one is good,another is error of :
login to server failed: dial tcp 182.243.33.96:7000: i/o timeout

why?

### frpc Version

0.44

### frps Version

0.44

### System Architecture

linux/amd64

### Configurations

I have two frpc client,one is good,another is error of :
login to server failed: dial tcp 182.243.33.96:7000: i/o timeout

why?

### Logs

2022/08/12 12:24:16 [W] [service.go:128] login to server failed: dial tcp 182.243.33.96:7000: i/o timeout
dial tcp 182.243.33.96:7000: i/o timeout

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by coolxy** [comment]
Aug 12 12:21:13 qqserver systemd[1]: Started fraps service.
Aug 12 12:21:23 qqserver frpc[1314717]: 2022/08/12 12:21:23 [W] [service.go:128] login to server failed: dial tcp 182.243.33.96:7000: i/o timeout
Aug 12 12:21:23 qqserver frpc[1314717]: dial tcp 182.243.33.96:7000: i/o timeout
Aug 12 12:21:23 qqserver systemd[1]: frpc.service: Main process exited, code=exited, status=1/FAILURE
Aug 12 12:21:23 qqserver systemd[1]: frpc.service: Failed with result 'exit-code'.

**Comment by Becods** [comment]
![image](https://user-images.githubusercontent.com/35525491/184287478-3f5e386c-b7b3-478d-8058-876f30971d86.png)

Open your port.
