### ISSUE TITLE
[Feature Request] unix socket support on sever side

### ISSUE THREAD

**Issue by xqin93** [fatedier/frp#3061]
### Describe the feature request

In some cases(commercial VPS, docker, etc.),  limited permissions were given. Users cannot bind ports freely. Typically in that scenario, we can only deploy service via a Unix socket and proxied by an Nginx ahead of it. So, can we consider supporting that bind FRP server to a Unix socket? Many Thanks.

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Maybe not. frp is a port forwarding tool and it relies on listenning on specified ports not just port 7000.
