### ISSUE TITLE
Frps can't Listening ipv4

### ISSUE THREAD

**Issue by fengziyun** [fatedier/frp#3069]
### Bug Description

``` shell
[root@localhost frps]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
[root@localhost frps]# uname -a
Linux localhost.localdomain 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

无法监听ipv4 
```  shell
[root@localhost frps]# netstat  -tnlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      786/rpcbind         
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1126/sshd           
tcp6       0      0 :::7000                :::*                    LISTEN      73367/./frps        
tcp6       0      0 :::111                  :::*                    LISTEN      786/rpcbind
```
试过很多版本

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

Linux localhost.localdomain 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Configurations

[common]

bind_port = 7000
bind_addr = 0.0.0.0

### Steps to reproduce

1. ./frps -c frps.ini
2. netstat -tnlp

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fengziyun** [comment]
是私人服务器，不是云服务器

**Comment by Becods** [comment]
自行谷歌怎么关掉ipv6

**Comment by YsMox** [comment]
这个问题已经问过了，一句话说清楚就是ipv6可以同时监听ipv6和ipv4。
https://github.com/fatedier/frp/issues/838

**Comment by YsMox** [comment]
您发给我的信件已经收到。Your letter to me has been received.

**Comment by YsMox** [comment]
您发给我的信件已经收到。Your letter to me has been received.
