### ISSUE TITLE
Kubernetes Ingress Controller exemple

### ISSUE THREAD

**Issue by cicerocomp** [fatedier/frp#307]
https://kubernetes.io/docs/concepts/services-networking/ingress/

**Comment by fatedier** [comment]
I read the docs about k8s ingress and very interested to let frp compatible with it.

I will do it but not recently. I am busy doing other works. It's better to try traefik at present, i think it is the project with same idea.

**Comment by Mikulas** [comment]
I've set up frp on kubernetes without changing the app at all.

The configuration I used is here: https://gist.github.com/Mikulas/16fdfd4b294560b47208bc863c332ba6

There are multiple ways to configure it:
- if you have static highly-available ip on at least on of your nodes, you only need `NodePort`
- with nginx ingress controller, which supports TCP incoming connections, you can load balance the connection between host and the proxy

Load balancing requests against the proxy is easy as any ingress controller should be able to handle those.
