### ISSUE TITLE
创建好代理后访问不了

### ISSUE THREAD

**Issue by DAMYSDS** [fatedier/frp#3072]
### Bug Description

代理创建好，服务启动成功，端口已开放，访问不了

### frpc Version

0.44.0

### frps Version

0.44

### System Architecture

服务端 linux/amd64 客户端windows/amd64

### Configurations

服务端
[common]
# frp监听的端口，默认是7000，可以改成其他的
bind_port = 7001

vhost_http_port = 2201
# frp管理后台端口，请按自己需求更改
dashboard_port = 7501
# frp日志配置
log_file = /var/log/frps.log
log_level = info
log_max_days = 3

客户端
[common]
server_addr = 118.107.41.4
server_port = 7001
[web]
type = http
local_ip = 127.0.0.1
local_port = 8001
# web域名
custom_domains = eacoding.cn
# 自定义的远程服务器端口，例如8080
remote_port = 2201

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/186658421-e19087c8-c467-454b-8712-2827479431ff.png)
