### ISSUE TITLE
启动frpc系统崩溃

### ISSUE THREAD

**Issue by wynn-dev** [fatedier/frp#3075]
### Bug Description

启动frpc后系统崩溃
Kernel panic - not syncing: Fatal exception in interrupt

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

linux/amd64

### Configurations
frpc.ini
```
[common]
server_addr = 
server_port = 7000
token = 

[web]
type = tcp
local_ip = 127.0.0.1
local_port = 8080
remote_port = 40001
```
### Logs

```
# frpc -c /etc/frp/frpc.ini

2022/08/26 12:52:41 [I] [service.go:327] [4bf98d55e4a19996] login to server success, get run id [4bf98d55e4a19996], server udp port [0]

Message from syslogd@web2 at Aug 26 12:52:41 ...
 kernel:[  377.372359] Kernel panic - not syncing: Fatal exception in interrupt
```

**Comment by Becods** [comment]
请提供更多信息

比如系统发行版 软件包列表 内核转储什么的

另外建议再尝试多几次，看看复现概率是不是特别高

**Comment by wynn-dev** [comment]
Ubuntu 20.04
内核5.4.0-125-generic

每次启动frpc都会死机，frps不会

**Comment by wynn-dev** [comment]
![image](https://user-images.githubusercontent.com/66362261/187072160-1b14bf0b-72cb-423e-b61f-b9cbf9845364.png)

**Comment by fatedier** [comment]
系统崩溃需要给对应的系统提 issue~
