### ISSUE TITLE
内网多台主机穿透存在网页访问混淆问题

### ISSUE THREAD

**Issue by jasonfanjun** [fatedier/frp#3077]
### Bug Description

1台公网ip主机，配置frps

2台内网主机，ip定义为192.168.10.201和192.168.10.202

在192.168.10.201 中配置frpc 并运行。
[web-gitlab_s]
type = https
local_port = 443
local_ip = 192.168.10.201
custom_domains = gitlab.xxxxxx.com

[web-pms_s]
type = https
custom_domains = pms.xxxxxx.com
local_port = 443
local_ip = 192.168.10.202

可以正常运行，正常访问。但是谷歌浏览器测试， 当打开gitlab.xxxxxx.com后 浏览器再打开pms.xxxxxx.com 也是显示 前一个域名的页面。 用无痕模式 访问 亦是如此。

总结下来就是。打开浏览器，哪个网站先访问，另一个 也会显示第一个访问的页面。

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

linux/x386

### Configurations

无

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/187059237-a14750b5-52ad-48fa-b688-7ce6fd5b5fce.png)

**Comment by wmwgz** [comment]
在使用nginx反向代理的时候，就会出现此问题

**Comment by fdxx** [comment]
你遇到的可能是 [HTTP2连接合并](https://github.com/dlundquist/sniproxy/issues/178#issuecomment-303393876) 的问题
解决方法是: 关闭HTTP2或者不要使用通配符SSL证书
