### ISSUE TITLE
启动一段时间后，包括管理页面、frpc都无法访问

### ISSUE THREAD

**Issue by adinghub** [fatedier/frp#3079]
### Bug Description

启动一段时间后，包括管理页面、frpc都无法访问，需要重新启动 frps 服务 才正常，但过段时间还会这样，时间段暂无发现规律。

### frpc Version

0.44

### frps Version

0.44

### System Architecture

linux/386

### Configurations

[common]
bind_addr = 0.0.0.0
bind_port = 7000
bind_udp_port = 7001
kcp_bind_port = 7000
vhost_http_port = 8080
vhost_https_port = 443
dashboard_addr = 0.0.0.0
dashboard_port = 0000
dashboard_user = 0000
dashboard_pwd = 0000
token = 000000

log_file = ./frps.log
log_level = info
log_max_days = 30

### Logs

暂无

### Steps to reproduce

暂无

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by 1194570458** [comment]
确实有这情况，只能脚本定时访问面板接口 超时了就重启
