### ISSUE TITLE
[Feature Request] 关于V2版本

### ISSUE THREAD

**Issue by lunfangyu** [fatedier/frp#3082]
### Describe the feature request

听说已经V2版本已经在开发中，并且加入了万众期待的 服务器统一管理功能 ，而不必手工修改ini配置文件。
那么想问下V2版本开源吗，还是说V2版本只面向商用（像Ngrok一样）？
V2版本是否有内测、公测、上线时间？如果有，我个人愿意参与测试。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
1. 保持开源，核心是整体架构上提高可扩展性，以支撑更加复杂的能力和插件系统。
2. 在架构上高度可扩展的情况下，可能部分复杂的需求会以插件的形式仅面向商用。
3. 并不一定加入 服务器统一管理功能 ，而是计划将配置管理抽象，以支持更多的接入形式，核心还是使之更易扩展。
4. 个人精力有限，整体架构和规划中的工作量很大，也没法有具体的时间线。
5. 一旦有可用于测试的版本，也会在 Github 上 release。
