### ISSUE TITLE
"https://gofrp.org/docs"无法访问

### ISSUE THREAD

**Issue by aa51513** [fatedier/frp#3083]
### Bug Description

浏览器访问https://gofrp.org/docs

无法访问此网站gofrp.org 意外终止了连接。
请试试以下办法：

检查网络连接
[检查代理服务器和防火墙](chrome-error://chromewebdata/#buttons)
[运行 Windows 网络诊断](javascript:diagnoseErrors())
ERR_CONNECTION_CLOSED

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

linux/amd64

### Configurations

直连和翻墙都试过了

### Logs

无法访问此网站gofrp.org 意外终止了连接。
请试试以下办法：

检查网络连接
[检查代理服务器和防火墙](chrome-error://chromewebdata/#buttons)
[运行 Windows 网络诊断](javascript:diagnoseErrors())
ERR_CONNECTION_CLOSED

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
[gofrp/frp-doc](https://github.com/gofrp/frp-doc)

能麻烦哪里出的问题去哪个仓库提好吗

**Comment by lunfangyu** [comment]
![image_20220902102203](https://user-images.githubusercontent.com/41062458/188045067-899deaa7-e0e5-4533-af66-804c2a76a569.png)

刚刚试了，直连，访问正常
