### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by jingjianjie** [fatedier/frp#3084]
### Describe the feature request

作为 RDP 使用者，希望基于 stcp/sudp ，开发服务器带宽分流功能。

### Describe alternatives you've considered

背景：国内带宽很贵，带宽扩大 2 倍，服务器费用可能扩大 5 倍。这对于只是想简单 RDP 连电脑的我来说太伤了，因此希望多订阅两台低带宽的服务器来组成大带宽的中转站，这需要 FRP 有原生的分流功能

希望在主控端和被控端都起 FRP 的时候，能自动均衡带宽，向 2 台或者多台 FRPS 发包。
![image](https://user-images.githubusercontent.com/48371840/187723838-b9ad6b0e-fb5b-4c63-94ba-a27d846e2c5e.png)

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/fft

之前有做过试验，效果不好需要进一步优化，暂时没有精力。
