### ISSUE TITLE
[Feature Request]  can add  bandwidth_limit  in server side

### ISSUE THREAD

**Issue by freshgeek** [fatedier/frp#3085]
### Describe the feature request

[Feature Request]  can add  bandwidth_limit  in server  side
add   bandwidth_limit  in client side  is not useful，  client is not controlled  

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
[#bandwidth-limit](https://github.com/fatedier/frp#bandwidth-limit)

**Comment by fatedier** [comment]
An optional method it the [server plugin](https://github.com/fatedier/frp/blob/dev/doc/server_plugin.md) to override proxy `bandwidth_limit` in frps.

**Comment by cbodonnell** [comment]
Opened https://github.com/fatedier/frp/pull/3271 to support setting `bandwidth_limit` from a server plugin.  This allows the server to control the limit for each proxy.

**Comment by tecufanujacu** [comment]
> An optional method it the [server plugin](https://github.com/fatedier/frp/blob/dev/doc/server_plugin.md) to override proxy `bandwidth_limit` in frps.

Is it possible to receive a little help? I'm trying to do this from several days, I'm trying to understand how, I studied the server plugin documentation and I'm also trying to understand how available server plugins works. Unfortunalty I'm failing.
