### ISSUE TITLE
[Feature Request] The attributes of bin file frpc are automatically changed when i try to ssh

### ISSUE THREAD

**Issue by WCJ-Chance** [fatedier/frp#3087]
### Describe the feature request

Everything works fine when the client starts up, until when i try to ssh to connect, it just crashes. Here are my troubleshooting steps:

```
# ll /usr/bin/frpc
---------- 1 root root /usr/bin/frpc 
# lsattr /usr/bin/frpc
----i----------- /usr/bin/frpc 
```
the file attributes been changed, which is so weird··· 
- OS: CentOS 7 
- frp version: frp_0.44.0_linux_amd64

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Client Plugin
- [ ] Developer Infrastructure
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
I don't know what you are talking about.

![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/188299782-45b70a01-3ef7-46e0-81ba-a94fcf2f4f6c.png)
