### ISSUE TITLE
http隧道出现 “The page you requested was not found.” 如何解决

### ISSUE THREAD

**Issue by SuperH-0630** [fatedier/frp#3089]
### Bug Description

我的服务端http监听80，https监听443，客户端由nginx监听80端口并反向代理到8080。8080是python+Flask的项目。
www.song-zh.com 解析到了我的服务端，我访问www.song-zh.com却出现The page you requested was not found。

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

Linux/x86_64

### Configurations

我的客户端添加了如下配置（略有删减）：
```
[common]
server_addr = xxxx
server_port = xxxx
token = xxxx

admin_addr = xxxx
admin_port = xxxx
admin_user = xxxx
admin_pwd = xxxx

[http]
type = http
local_port = 80
custom_domains = song-zh.com www.song-zh.com
# use_encryption = true
# use_compression = true
```

我的服务端添加了如下配置：
```
[common]
bind_port = xxxx
vhost_http_port = 80
vhost_https_port = 443
token = xxxx
allow_ports = 465,995,993,1024-50000

dashboard_port = xxxx
dashboard_user = xxxx
dashboard_pwd = xxxx
```

### Logs

每次对www.song-zh.com访问出现服务端日志（syslog）：
```
Sep  5 17:54:55 song-zh frps[89870]: 2022/09/05 17:54:55 #033[1;33m[W] [http.go:115] do http proxy request [host: www.song-zh.com] error: no route found: www.song-zh.com / #033[0m
```
客户端除了启动的日志，无其他日志。

### Steps to reproduce

1. 按照上述配置文件配置服务端和客户端
2. 启动服务
3. 访问www.song-zh.com
4. 

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by SuperH-0630** [comment]
我找到问题似乎出现在客户端配置文件`custom_domains = song-zh.com www.song-zh.com`，修改为`custom_domains = song-zh.com,www.song-zh.com`后可以成功

**Comment by SuperH-0630** [comment]
问题解决

**Comment by VAJlai** [comment]
请问一下，我的是会断续出现这种情况，然后持续十分钟左右，自己又恢复正常，请问这会是什么原因？
