### ISSUE TITLE
[Feature Request] systemd conf

### ISSUE THREAD

**Issue by a-wing** [fatedier/frp#3091]
### Describe the feature request

Hello I'am archlinux aur frp package maintainer [frpc](https://aur.archlinux.org/packages/frpc) [frps](https://aur.archlinux.org/packages/frps)

archlinuxcn repo: https://build.archlinuxcn.org/packages/#/frp

I noticed that frp project remove systemd conf https://github.com/fatedier/frp/commit/bd89eaba2fc465c0c3ba4509c7ce75b2ca49206d

Why is remove systemd unit file ?

In the future, frp will no provide systemd unit file ?

If this project no provide systemd. I will provide systemd unit file at package building script

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
https://github.com/fatedier/frp/issues/3048

>There are many systemd issues or PRs and we have not enough resource to sovle it, so it was removed from the official release assets to avoid usage problems.
>
>You can write your own systemd or other deploy files if needed.
>
>We may provide deploy configs when we have active developers focus on this area.
