### ISSUE TITLE
本地服务拒绝连接 

### ISSUE THREAD

**Issue by ydecl** [fatedier/frp#3092]
### Bug Description

![image](https://user-images.githubusercontent.com/53930390/189007984-c2722083-c025-4ca0-b228-31893de566e3.png)

我在任何设备 上都是报这个错，换过frp版本。也换过设备 ，原先运行可以正常运行。不知道为什么。本地IP 是正确的。

两个机器的防火墙都是关闭状态，服务器的安全组也是开放的。
server
![image](https://user-images.githubusercontent.com/53930390/189008334-5d2fc58d-c40d-41bf-b7dc-7619b90fb2c4.png)

客户端
![image](https://user-images.githubusercontent.com/53930390/189008486-e2640045-54da-4234-80a8-89781224ce75.png)
server_addr 为了防止IP泄露 截图时 去掉了

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

linux/amd64

### Configurations

frpc.ini
[common]
server_addr = 
server_port = 5000

[mm]
type = tcp
local_ip = 192.168.1.11
local_port = 16000
remote_port = 16000

frps.ini
[common]
bind_port = 5000

### Logs

2022/09/07 20:26:28 [I] [service.go:349] [869a44ebf11c3cce] login to server success, get run id [869a44ebf11c3cce], server udp port [0]
2022/09/07 20:26:28 [I] [proxy_manager.go:144] [869a44ebf11c3cce] proxy added: [mm]
2022/09/07 20:26:28 [I] [control.go:181] [869a44ebf11c3cce] [mm] start proxy success

2022/09/07 20:31:56 [E] [proxy.go:795] [869a44ebf11c3cce] [mm] connect to local service [192.168.1.11:16000] error: dial tcp 192.168.1.11:16000: connect: connection refused                                                           
2022/09/07 20:31:56 [E] [proxy.go:795] [869a44ebf11c3cce] [mm] connect to local service [192.168.1.11:16000] error: dial tcp 192.168.1.11:16000: connect: connection refused                                                           
2022/09/07 20:31:56 [E] [proxy.go:795] [869a44ebf11c3cce] [mm] connect to local service [192.168.1.11:16000] error: dial tcp 192.168.1.11:16000: connect: connection refused                                                           
2022/09/07 20:31:56 [E] [proxy.go:795] [869a44ebf11c3cce] [mm] connect to local service [192.168.1.11:16000] error: dial tcp 192.168.1.11:16000: connect: connection refused                                                           
2022/09/07 20:31:56 [E] [proxy.go:795] [869a44ebf11c3cce] [mm] connect to local service [192.168.1.11:16000] error: dial tcp 192.168.1.11:16000: connect: connection refused                                                           
2022/09/07 20:31:56 [E] [proxy.go:795] [869a44ebf11c3cce] [mm] connect to local service [192.168.1.11:16000] error: dial tcp 192.168.1.11:16000: connect: connection refused                                                           
2022/09/07 20:31:56 [E] [proxy.go:795] [869a44ebf11c3cce] [mm] connect to local service [192.168.1.11:16000] error: dial tcp 192.168.1.11:16000: connect: connection refused                                                           

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
检查`192.168.1.11:16000`上的服务是否正常运行
