### ISSUE TITLE
It works with TLS correctly, but fails when adding kcp.

### ISSUE THREAD

**Issue by guorouda** [fatedier/frp#3093]
### Bug Description

It works with TLS correctly, but fails when adding kcp.

Only output this message show as below in my terminal.
`2022/09/08 16:33:11 [W] [service.go:128] login to server failed: connection write timeout
connection write timeout`
Does my network  reset the connection ? Or It can't work with tls and kcp.

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

Server: linux/amd64, Client: windows/amd64

### Configurations

Client
[common]
server_addr = X.X.X.X
server_port = 7000
protocol = kcp
tls_enable = true
tls_cert_file = D:\dev\frp_0.44.1_windows_amd64\client.crt
tls_key_file = D:\dev\frp_0.44.1_windows_amd64\client.key
tls_trusted_ca_file = D:\dev\frp_0.44.1_windows_amd64\ca.crt

Server:
[common]
bind_port = 7000 
kcp_bind_port = 7000
tls_cert_file = /home/ubuntu/server.crt
tls_key_file = /home/ubuntu/server.key
tls_trusted_ca_file = /home/ubuntu/ca.crt

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
You can deploy both frpc and frps in the same local machine to test if it's normal.

Then you can confirm if the configuration is correct avoiding network problems.

**Comment by guorouda** [comment]
This approach is great. Thanks.

And it's my honor to get reply from THE AUTHOR himslef.
