### ISSUE TITLE
[Feature Request] Recognize which device to connect to over remote port from 100s of devices in field 

### ISSUE THREAD

**Issue by ovfstack** [fatedier/frp#3095]
### Describe the feature request

Hello,
We want to deploy 100s of devices in field which can run frpc and connect back to frps. The logic is each of this device will generate a unique remote port value when frpc is installed. This is a random unique port value which is generated when frpc is installed. On the frps side, how to know which device is available on which port?

The reason to use random but unique remote port value for each frpc is to simplify the device deployment. However when trying to connect from frps side to frpc over ssh, we need to know which port will connect to which device. Is there a way to map deviceid (Mac address in our case) that we know before hand with this remote port, so that we know that to ssh in to a device (which has a particular MAC address) we need to ssh to which remote port on frps

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Set `user` in your frpc configuration https://github.com/fatedier/frp/blob/dev/conf/frpc_full.ini#L83

And you can get the info from frps dashboard api.
