### ISSUE TITLE
If Microsoft KM-TEST is installed

### ISSUE THREAD

**Issue by Junsen2356579199** [fatedier/frp#3097]
### Describe the feature request

frpc.ini
server_addr = Microsoft KM-TEST ipv4 ip address
frpc Unable to start
can be excluded or bypassed Microsoft KM-TEST ?
or specify a network device to run ?

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
I have no idea about Microsoft KM-TEST and can't help you. Maybe you can google the solution.

**Comment by Becods** [comment]
Fill in your Microsoft KM-TEST Loopback ip in the server_addr
