### ISSUE TITLE
直接命令行 参数运行 ini 两用的方式吗

### ISSUE THREAD

**Issue by 873202227** [fatedier/frp#3098]
### Describe the feature request

请问有 直接命令行   参数运行  ini  两用的方式吗

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by Becods** [comment]
你这种问题自己试一试就知道了

**Comment by 873202227** [comment]
试过了 不支持

**Comment by anarckk** [comment]
直接` -c xxx.ini` 不就行了
