### ISSUE TITLE
映射远程端口到本地

### ISSUE THREAD

**Issue by foxconndmd** [fatedier/frp#31]
可以实现远程端口到本地到本地吗？本地电脑在内网且IP不固定，没法在本地安装服务端。
谢谢提供这么好的工具。

**Comment by fatedier** [comment]
不是太理解你的这个需求，是指有 A B C 三台机器，A 有公网IP，B和C在内网，B可以访问A，然后B可以访问C，你需要通过 A 来访问 C 吗？ip 不固定，是指 B 和 C 在内网内的 ip 也是不固定的？

**Comment by foxconndmd** [comment]
就是A为服务器，B和C在内网，B连接A将A服务器上的端口转发到内网。

**Comment by fatedier** [comment]
服务器A需要有一个公网 IP，然后 B 的内网 IP 可以不固定，通过在 frpc.ini 中指定 local_ip 为 C 的内网 IP 即可，这里 local_ip 不一定要填 127.0.0.1，可以是任意的可以建立连接的其他 IP。

如果 B 和 C 的内网 IP 都不固定的话填 IP 的话下次可能就无效了，这时候如果有内网 DNS 的话可以填域名之类的。
