### ISSUE TITLE
客户端断线一段时间后 , 连回网不会自动连接

### ISSUE THREAD

**Issue by Diaoji** [fatedier/frp#310]
具体症状 :

长时间不让frp客户端联网后 , 解除防火墙限制并不会自动重连

有些时候是假死 得手动重启客户端

**Comment by yhcvb** [comment]
确实有这个问题，我是在Ubuntu里面用systemd来运行，每次都要restart一下，要是可以自动重连就好了，之前用ngrok在网络恢复后会自动连上的

**Comment by fatedier** [comment]
可以尝试 v0.10.0 版本，如果仍然有问题，请按照新的 issue 模版提交问题。
