### ISSUE TITLE
Ubuntu 18.04.4 系统开启 Dashboard 无法访问的问题

### ISSUE THREAD

**Issue by ouyanghuangrunda** [fatedier/frp#3101]
### Bug Description

Ubuntu 18.04.4 系统开启 Dashboard 无法访问，在本地可以curl 通，但是在浏览器访问不到。
没有安全组，使用本机的iptable去管理的。
iptable的规则如下：
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:50000
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED
ACCEPT     all  --  127.0.0.1            127.0.0.1           
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:88
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:50010
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:17001
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:88
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:7001
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:22
DROP       all  --  0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

Linux ubuntu 4.15.0-108-generic #109-Ubuntu SMP Fri Jun 19 11:33:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Configurations

[common]
bind_port = 7000
vhost_http_port = 80

log_file = ./frps.log

dashboard_user = ********
dashboard_pwd = ********
dashboard_port = 88

### Logs

2022/09/16 01:40:59 [I] [root.go:209] frps uses config file: frps.ini
2022/09/16 01:40:59 [I] [service.go:194] frps tcp listen on 0.0.0.0:7000
2022/09/16 01:40:59 [I] [service.go:237] http service listen on 0.0.0.0:80
2022/09/16 01:40:59 [I] [service.go:293] Dashboard listen on 0.0.0.0:88
2022/09/16 01:40:59 [I] [root.go:218] frps started successfully

### Steps to reproduce

1. 系统使用Ubuntu 18.04.4
2. 安装0.44.0版本的frp
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
请 提供截图
![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/190619914-954b6e60-2efa-4ff0-9b65-8c1898a65936.png)
