### ISSUE TITLE
远程桌面连接一会会自动断开是什么情况？

### ISSUE THREAD

**Issue by DY13208** [fatedier/frp#3102]
### Bug Description

远程桌面连接一会会自动断开是什么情况？

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

windows/amd64

### Configurations

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 6000

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/191016378-e5140cba-2312-4585-88d2-091155576ef4.png)

**Comment by DY13208** [comment]
主要是frps没有报错日志只有正常运行的日志...

**Comment by Becods** [comment]
mtr检查服务器连接稳定性
