### ISSUE TITLE
ssh代理，获取公网源地址

### ISSUE THREAD

**Issue by wuai1024** [fatedier/frp#3103]
### Describe the feature request

现在ssh代理的，只能获取到内网ip地址，导致外网 ssh 一直被刷。

希望能增加一个选项，获取到源外网ip和内网ip

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
[proxy-protocol](https://github.com/fatedier/frp#proxy-protocol) + [go-mmproxy](https://github.com/path-network/go-mmproxy)

**Comment by wuai1024** [comment]
这个是代理 http的吧

**Comment by Becods** [comment]
> HAProxy is a free and open source software that provides a high availability load balancer and reverse proxy for **TCP** and HTTP-based applications that spreads requests across multiple servers

> go-mmproxy is a standalone application that unwraps **HAProxy's PROXY protocol**
