### ISSUE TITLE
[Feature Request] Want Official Docker Image

### ISSUE THREAD

**Issue by StudentWeis** [fatedier/frp#3104]
### Describe the feature request

I want an official docker image so that I can deploy easily on the server side.

### Affected area

- [ ] Docs
- [X] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
[fatedier/frpc](https://hub.docker.com/r/fatedier/frpc)
[fatedier/frps](https://hub.docker.com/r/fatedier/frps)

**Comment by StudentWeis** [comment]
> [fatedier/frpc](https://hub.docker.com/r/fatedier/frpc) [fatedier/frps](https://hub.docker.com/r/fatedier/frps)

感谢！

**Comment by huanghe-1** [comment]
@StudentWeis 为什么要用docker呢，frp本来就是绿色免安装，一个单应用+一个ini配置，用了docker反倒更加麻烦了。

**Comment by Becods** [comment]
> @StudentWeis 为什么要用docker呢，frp本来就是绿色免安装，一个单应用+一个ini配置，用了docker反倒更加麻烦了。

Docker对开发的影响不大，但对于部署来说是场革命

传统的部署模式是：安装(包管理工具或者源码包编译)->配置->运行
Docker的部署模式是：复制->运行

除此之外docker化还有

- 隔离性
- 安全性
- 更轻松的维护和扩展
- 更轻松的迁移
- 一致的运行环境
