### ISSUE TITLE
【bug】windows文件共享SMB无法访问

### ISSUE THREAD

**Issue by JaneYork** [fatedier/frp#3105]
### Bug Description

客户端windows server2012R2，
服务端windows server
用Mac OS访达 - 连接服务器 smb://映射后的地址，可以弹出输入用户密码框，但是无法访问。
直接用smb://192.168.xx可以访问，可见Windows server文件共享没有问题。
同时用了netapp测试映射，可以访问。

### frpc Version

0.4.4

### frps Version

0.4.4

### System Architecture

windows/amd64

### Configurations

[pusdn-secure-smb]
type = tcp
local_ip = 127.0.0.1
local_port = 445
remote_port = 14001

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by JaneYork** [comment]
@fatedier

**Comment by Becods** [comment]
[proxy-protocol](https://github.com/fatedier/frp#proxy-protocol) + [go-mmproxy](https://github.com/path-network/go-mmproxy)

**Comment by Becods** [comment]
```
[pusdn-secure-smb]
type = tcp
local_ip = 127.0.0.1
local_port = 445
remote_port = 445
```

**Comment by 8ar10der** [comment]
遇见了同样的问题，我将remote端口换成10445后可以访问，但是如果是445的话，过了认证就是timeout无法访问。 已经确认frps加权可以监听1024一下端口。希望检查修复。

**Comment by 8ar10der** [comment]
@fatedier 希望 reopen 这个 issue

**Comment by 1500256797** [comment]
我也一样，我在frpc上把445映射到公网服务器的18759上后，也是无法链接。其他服务都是ok的，单独smb无法用。

**Comment by JaneYork** [comment]
> 

I only say shift,yeah yeah is shift not shit!
