### ISSUE TITLE
connection write timeout

### ISSUE THREAD

**Issue by pxzhang94** [fatedier/frp#3107]
### Bug Description

[W] [service.go:97] login to server failed: connection write timeout
connection write timeout

### frpc Version

0.29.1

### frps Version

0.29.1

### System Architecture

linux/amd64

### Configurations

default

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
Update your frp, and

![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/191945776-ba7bbee1-e086-4289-ac0e-ea1783f5cfd7.png)

**Comment by pxzhang94** [comment]
I already update my frp to version 0.44.0, and the only information in log file is "2022/09/23 22:32:07 [W] [service.go:128] login to server failed: connection write timeout", and the configuration of frpc.ini is "
[common]
tls_enable = true
server_addr = XXX
server_port = 7000
log_file = ./frpc.log
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = XXX"

> Update your frp, and
> 
> ![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/191945776-ba7bbee1-e086-4289-ac0e-ea1783f5cfd7.png)

**Comment by Becods** [comment]
Paste your startup command.

**Comment by pxzhang94** [comment]
> Paste your startup command.

Do you mean this "./frpc -c ./frpc.ini"?

**Comment by Becods** [comment]
Check if your server port is open and can be connected properly.

Use tcping.

**Comment by yudonglin** [comment]
> Check if your server port is open and can be connected properly.
> 
> Use tcping.

Ok so @Becods 's suggestion makes me realize what is the problem here... make sure to go to "Security Group" on the server end and switch your 7000 port protocol type from "customize tcp" to "customize tcp". This fix my problem.

**Comment by kaifeiji** [comment]
Try changing your bind_port in frps.ini and server_port in frpc.ini to another port number, like 6789. Works for me.
A rough guess: GFW or your ISP monitored some "unusual" network traffic on this port, and then block or restrict the port.

**Comment by wk989898** [comment]
Try to use kcp protocol

**Comment by N-E-E** [comment]
> Try to use kcp protocol

correct. I fix the problem by using kcp protocol
