### ISSUE TITLE
[Feature Request]  URL rewrite functionality?

### ISSUE THREAD

**Issue by shouldsee** [fatedier/frp#3111]
### Describe the feature request

Wants to rewrite a the url in a proxied HTTP request, as one would do in nginx. This is useful when mounting application to a url_prefix. I am not very familiar with HTTP but at the very basic the url needs to be recovered to remove the /${base_url} in the proxyed url?

### Describe alternatives you've considered

nginx way to mount supervisor  interface at 8999. as from https://github.com/Supervisor/supervisor/issues/29

```
location /supervisor {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # hack the host https://github.com/Supervisor/supervisor/issues/251
    proxy_set_header Host $http_host/supervisor/index.html;
    proxy_redirect off;
    rewrite ^/supervisor(.*)$ /$1 break;
    proxy_pass http://127.0.0.1:8999/;
}
```

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by fatedier** [comment]
It can be supported in frp v2 future.

**Comment by SKJoy** [comment]
Following worked for me well with;

## Supervisor
```
...
[inet_http_server]
port=127.0.0.1:9001
...
```

## NginX
```
...
location /supervisor/ {
	proxy_set_header Host $http_host/supervisor/;
	proxy_pass http://127.0.0.1:9001/;
}
...
```

URL: `https://host.gtld/supervisor/`
