### ISSUE TITLE
Support for clustering and high availability 

### ISSUE THREAD

**Issue by Palezvar** [fatedier/frp#3112]
### Describe the feature request

 I was wondering if it is or will be possible to group multiple frps servers to operate together to increase capacity or add redundancy to the solution. 

Please excuse me if something with Kubernetes and LoadBalancers is already available to achieve this. So far I did not see anything.

Thank you.

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
No support now.

**Comment by Becods** [comment]
The design of clusters is more complex and mostly commercial requirements, and since frp is open source software, not much effort is destined to be spent on this..

Or you can use third-party software to implement.

https://github.com/fatedier/frp/issues/1435

> You can use nginx/HAProxy to inverse-substitute each frps node to achieve.

**Comment by Palezvar** [comment]
thank you for the response.

**Comment by Nour963** [comment]
Any news on that? Has anyone been able to achieve that and if yes, can someone please share snippet of code of how to do that?

**Comment by Mmx233** [comment]
> Any news on that? Has anyone been able to achieve that and if yes, can someone please share snippet of code of how to do that?

I made one with QUIC protocol, full HA architecture, CC https://github.com/Mmx233/QMux
