### ISSUE TITLE
Documentation for API for remote management and status check

### ISSUE THREAD

**Issue by Palezvar** [fatedier/frp#3113]
### Bug Description

Are there any APIs on FRP that we can use to check the current status of proxies and get some details for each.

If so, is any documentation available?

Thanks,

### frpc Version

0.44

### frps Version

0.44

### System Architecture

linux/amd64

### Configurations

admin_addr = 127.0.0.1
admin_port = 7400

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
https://github.com/fatedier/frp/blob/9d077b02cfd6967d0f2aa06f5f65cc3239bbac3f/server/dashboard_api.go#L35-L52

**Comment by Palezvar** [comment]
Can you please elaborate on this one.

Can I actually access different proxy details and status externally using Postman or Curl? If so, what is the syntax?

**Comment by Palezvar** [comment]
folks, is there anyway for me to access the proxy details such as "name", "domain", "status", "encryption" remotely via an API? If not, maybe there is another method you could recommend me to harness this data via a script that runs locally on the frp server.

Please advise.
