### ISSUE TITLE
关于frp重启后出现时区bug，日志时间慢8小时

### ISSUE THREAD

**Issue by usertest001** [fatedier/frp#3114]
### Bug Description

frps和frpc  kill重启后出现日志时间不对，系统正常重启，时间是正确的。希望大佬能解决下这个问题。

### frpc Version

frp_0.44.0_linux_arm

### frps Version

frp_0.44.0_linux_arm64

### System Architecture

arm

### Configurations

[common]
bind_addr=0.0.0.0
bind_port=8888
bind_udp_port=5555
tls_only=true
tls_cert_file=./server.crt
tls_key_file=./server.key
tls_trusted_ca_file=./ca.crt
vhost_http_port=4444
vhost_https_port=3333
log_file=/mnt/sda/sc1_log/frp/log/frps.log
log_level=trace
log_max_days=999

[common]
server_addr = 22.2222.com
server_port = 8888
token = 111111
tls_enable = true
tls_cert_file = ./client.crt
tls_key_file = ./client.key
tls_trusted_ca_file = ./ca.crt
log_file = /mnt/sda1/sc1_log/frp/log/frpc.log
log_level = trace
log_max_days = 999
login_fail_exit = false
admin_addr = 127.0.0.1
admin_port = 7600

### Logs

`
如下日志是手动重启frp，2022/09/29 11:58:03 [T] [root.go:211] start frpc service for config file [./frpc.ini] 出现时间慢8小时，正确的时间应该是19:58

2022/09/29 19:56:16 [D] [proxy_wrapper.go:231] [efa6ad893663d11d] [rdp001] start a new work connection, localAddr: 1.1.1.1:38563 remoteAddr: 2.2.2.2:3333
2022/09/29 19:56:16 [T] [proxy.go:734] [efa6ad893663d11d] [r*****01] handle tcp work connection, use_encryption: false, use_compression: false
2022/09/29 19:56:19 [E] [proxy.go:795] [efa6ad893663d11d] [rd*****01] connect to local service [192.168.51.130:3389] error: dial tcp 192.168.51.130:3389: connect: no route to host
2022/09/29 19:56:21 [D] [control.go:360] [efa6ad893663d11d] send heartbeat to server
2022/09/29 19:56:21 [D] [control.go:391] [efa6ad893663d11d] receive heartbeat from server
2022/09/29 19:56:21 [T] [proxy.go:534] [efa6ad893663d11d] [ope*****udp] send ping message to udp workConn
2022/09/29 11:58:03 [T] [root.go:211] start frpc service for config file [./frpc.ini]
2022/09/29 11:58:03 [I] [service.go:349] [f45e1ebe0a7260a8] login to server success, get run id [f45e1ebe0a7260a8], server udp port [1*****9]
2022/09/29 11:58:03 [I] [proxy_manager.go:144] [f45e1ebe0a7260a8] proxy added: [rdp001 ssh 6*****p route*****-5-http router*****http ope*****tcp op*****-udp]
2022/09/29 11:58:03 [T] [proxy_wrapper.go:171] [f45e1ebe0a7260a8] [router-ac*****-http] change status from [new] to [wait start]
2022/09/29 11:58:03 [T] [proxy_wrapper.go:171] [f45e1ebe0a7260a8] [rdp*****] change status from [new] to [wait start]
2022/09/29 11:58:03 [T] [proxy_wrapper.go:171] [f45e1ebe0a7260a8] [ssh] change status from [new] to [wait start]
2022/09/29 11:58:03 [T] [proxy_wrapper.go:171] [f45e1ebe0a7260a8] [we*****tp] change status from [new] to [wait start]
2022/09/29 11:58:03 [T] [proxy_wrapper.go:171] [f45e1ebe0a7260a8] [openv*****tcp] change status from [new] to [wait start]
2022/09/29 11:58:03 [T] [proxy_wrapper.go:171] [f45e1ebe0a7260a8] [route*****http] change status from [new] to [wait start]
2022/09/29 11:58:03 [T] [proxy_wrapper.go:171] [f45e1ebe0a7260a8] [open*****dp] change status from [new] to [wait start

如下日志是系统重启，日志时间正确2022/09/29 21:47:22 [T] [root.go:211] start frpc service for config file [./frpc.ini]

2022/09/29 13:44:18 [W] [service.go:204] [f45e1ebe0a7260a8] reconnect to server error: dial tcp: lookup 1.2.com on 8.8.8.8:53: dial udp 8.8.8.8:53: connect: network is unreachable, wait 4s for another retry
2022/09/29 13:44:22 [I] [service.go:201] [f45e1ebe0a7260a8] try to reconnect to server...
2022/09/29 13:44:22 [W] [service.go:204] [f45e1ebe0a7260a8] reconnect to server error: dial tcp: lookup 1.2.com on 8.8.8.8:53: dial udp 8.8.8.8:53: connect: network is unreachable, wait 8s for another retry
2022/09/29 21:47:22 [T] [root.go:211] start frpc service for config file [./frpc.ini]
2022/09/29 21:47:22 [I] [service.go:349] [f619eded6be72b7f] login to server success, get run id [f619eded6be72b7f], server udp port [13*****9]
2022/09/29 21:47:22 [I] [proxy_manager.go:144] [f619eded6be72b7f] proxy added: [rdp001 ssh 66-*****tp router*****http router*****-http open*****tcp ope*****udp]
2022/09/29 21:47:22 [T] [proxy_wrapper.go:171] [f619eded6be72b7f] [openv*****p] change status from [new] to [wait start]
2022/09/29 21:47:22 [T] [proxy_wrapper.go:171] [f619eded6be72b7f] [ope*****-udp] change status from [new] to [wait start]
2022/09/29 21:47:22 [T] [proxy_wrapper.go:171] [f619eded6be72b7f] [rdp*****01] change status from [new] to [wait start]
2022/09/29 21:47:22 [T] [proxy_wrapper.go:171] [f619eded6be72b7f] [ssh] change status from [new] to [wait start]
2022/09/29 21:47:22 [T] [proxy_wrapper.go:171] [f619eded6be72b7f] [web1*****tp] change status from [new] to [wait start]
2022/09/29 21:47:22 [T] [proxy_wrapper.go:171] [f619eded6be72b7f] [route*****http] change status from [new] to [wait start]
2022/09/29 21:47:22 [T] [proxy_wrapper.go:171] [f619eded6be72b7f] [route**********-http] change status from [new] to [wait start]

如下日志是手动重启frp，2022/09/29 13:52:03 [T] [root.go:211] start frpc service for config file [./frpc.ini] 出现时间慢8小时，正确的时间应该是21:52

2022/09/29 21:51:43 [T] [proxy.go:734] [f619eded6be72b7f] [rdp*****1] handle tcp work connection, use_encryption: false, use_compression: false
2022/09/29 21:51:46 [E] [proxy.go:795] [f619eded6be72b7f] [rd*****1] connect to local service [192.168.51.130:3389] error: dial tcp 1.2.51.130:332: connect: no route to host
2022/09/29 21:51:52 [D] [proxy_wrapper.go:231] [f619eded6be72b7f] [rou*****http] start a new work connection, localAddr: 334.16.3.44:33396 remoteAddr: 1.2.51.130:332
2022/09/29 21:51:52 [T] [proxy.go:734] [f619eded6be72b7f] [route*****ttp] handle tcp work connection, use_encryption: false, use_compression: false
2022/09/29 21:51:52 [D] [proxy.go:799] [f619eded6be72b7f] [route*****ttp] join connections, localConn(l[127.0.0.1:33659] r[127.0.0.1:8080]) workConn(l[44.12.44.122:33396] r[34.12.66.39:666])
2022/09/29 21:51:52 [D] [control.go:360] [f619eded6be72b7f] send heartbeat to server
2022/09/29 21:51:52 [D] [control.go:391] [f619eded6be72b7f] receive heartbeat from server
2022/09/29 21:51:53 [T] [proxy.go:534] [f619eded6be72b7f] [open*****dp] send ping message to udp workConn
2022/09/29 13:52:03 [T] [root.go:211] start frpc service for config file [./frpc.ini]
2022/09/29 13:52:03 [I] [service.go:349] [649a41ddfa310d82] login to server success, get run id [649a41ddfa310d82], server udp port [12**9]
2022/09/29 13:52:03 [I] [proxy_manager.go:144] [649a41ddfa310d82] proxy added: [rd*****01 ssh 66*****p router-*****-http rout*****tp op*****tcp op*****-udp]
2022/09/29 13:52:03 [T] [proxy_wrapper.go:171] [649a41ddfa310d82] [router*****ttp] change status from [new] to [wait start]
2022/09/29 13:52:03 [I] [service.go:158] admin server listen on 127.0.0.1:7400
2022/09/29 13:52:03 [T] [proxy_wrapper.go:171] [649a41ddfa310d82] [rd*****1] change status from [new] to [wait start]
2022/09/29 13:52:03 [T] [proxy_wrapper.go:171] [649a41ddfa310d82] [ssh] change status from [new] to [wait start]
2022/09/29 13:52:03 [T] [proxy_wrapper.go:171] [649a41ddfa310d82] [web1*****tp] change status from [new] to [wait start]
2022/09/29 13:52:03 [T] [proxy_wrapper.go:171] [649a41ddfa310d82] [openv*****cp] change status from [new] to [wait start]
2022/09/29 13:52:03 [T] [proxy_wrapper.go:171] [649a41ddfa310d82] [route*****tp] change status from [new] to [wait start]
2022/09/29 13:52:03 [T] [proxy_wrapper.go:171] [649a41ddfa310d82] [ope*****dp] change status from [new] to [wait start]

`

### Steps to reproduce

1. 手动重启frp
2. 系统重启
3. 手动重启frp
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by superzjg** [comment]
可能是固件有问题，我曾在装有openwrt的路由器上遇到过日志时间相差8小时的问题，虽然我没有注意重启的方式。
后来尝试在openwrt上安装zoneinfo-asia这个软件包后，重启路由器日志恢复正常，供参考。

**Comment by usertest001** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by usertest001** [comment]
> 
看了下系统时区是正常的
/tmp/home/root# opkg list zoneinfo-*
zoneinfo-africa - 2022a-1 - Zone Information (Africa)
zoneinfo-asia - 2022a-1 - Zone Information (Asia)
zoneinfo-atlantic - 2022a-1 - Zone Information (Atlantic)
zoneinfo-australia-nz - 2022a-1 - Zone Information (Australia-NZ)
zoneinfo-core - 2022a-1 - Zone Information (core)
zoneinfo-europe - 2022a-1 - Zone Information (Europe)
zoneinfo-india - 2022a-1 - Zone Information (India)
zoneinfo-northamerica - 2022a-1 - Zone Information (NorthAmerica)
zoneinfo-pacific - 2022a-1 - Zone Information (Pacific)
zoneinfo-poles - 2022a-1 - Zone Information (Arctic, Antarctic)
zoneinfo-simple - 2022a-1 - Zone Information (simple)
zoneinfo-southamerica - 2022a-1 - Zone Information (SouthAmerica)


/tmp/home/root# opkg install zoneinfo-core zoneinfo-asia
Package zoneinfo-core (2022a-1) installed in root is up to date.
Package zoneinfo-asia (2022a-1) installed in root is up to date.

不是系统问题

> 可能是固件有问题，我曾在装有openwrt的路由器上遇到过日志时间相差8小时的问题，虽然我没有注意重启的方式。 后来尝试在openwrt上安装zoneinfo-asia这个软件包后，重启路由器日志恢复正常，供参考。

看了下系统时区是正常的
/tmp/home/root# opkg list zoneinfo-*
zoneinfo-africa - 2022a-1 - Zone Information (Africa)
zoneinfo-asia - 2022a-1 - Zone Information (Asia)
zoneinfo-atlantic - 2022a-1 - Zone Information (Atlantic)
zoneinfo-australia-nz - 2022a-1 - Zone Information (Australia-NZ)
zoneinfo-core - 2022a-1 - Zone Information (core)
zoneinfo-europe - 2022a-1 - Zone Information (Europe)
zoneinfo-india - 2022a-1 - Zone Information (India)
zoneinfo-northamerica - 2022a-1 - Zone Information (NorthAmerica)
zoneinfo-pacific - 2022a-1 - Zone Information (Pacific)
zoneinfo-poles - 2022a-1 - Zone Information (Arctic, Antarctic)
zoneinfo-simple - 2022a-1 - Zone Information (simple)
zoneinfo-southamerica - 2022a-1 - Zone Information (SouthAmerica)


/tmp/home/root# opkg install zoneinfo-core zoneinfo-asia
Package zoneinfo-core (2022a-1) installed in root is up to date.
Package zoneinfo-asia (2022a-1) installed in root is up to date.

不是系统问题

**Comment by usertest001** [comment]
建议下次更新配置文件增加时区设置，启动时加载时区配置，这样应该能解决这个问题。

**Comment by usertest001** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lilisore** [comment]
出现了跟楼主一样的问题，建议加载时区配置

**Comment by caiwenmin** [comment]
请问问题是怎么解决的呀，我也遇到了相同的问题，连不上服务器

**Comment by yaoyi2008** [comment]
> 可能是固件有问题，我曾在装有openwrt的路由器上遇到过日志时间相差8小时的问题，虽然我没有注意重启的方式。 后来尝试在openwrt上安装zoneinfo-asia这个软件包后，重启路由器日志恢复正常，供参考。

连接不到服务器没解决到，不过安装上zoneinfo-asia这个后，日志时间倒是解决了。感谢！
