### ISSUE TITLE
[Feature Request]重写response header

### ISSUE THREAD

**Issue by aynakeya** [fatedier/frp#3116]
### Describe the feature request

在frpc中添加重写后端response header的功能。

大概的思路是在添加设置后，通过设置ReverseProxy中的ModifyResponse来实现

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
计划在 v2 版本中支持，当前的版本不再提供额外的七层能力的处理。

**Comment by aa51513** [comment]
> 计划在 v2 版本中支持，当前的版本不再提供额外的七层能力的处理。

v2大概什么时候能有试用版，有个大概时间就好，非常期待
