### ISSUE TITLE
[Feature Request] frps如何获取frpc客户端登陆的账号密码

### ISSUE THREAD

**Issue by NozVine** [fatedier/frp#3119]
### Describe the feature request

frps服务端有相应的日志或者工具可以查看到连接过来的客户端的账号密码嘛？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
[#Authenticating the Client](https://github.com/fatedier/frp#authenticating-the-client)

frp原版默认只有token和oidc这两种验证方法

二开请到对应仓库提issue

**Comment by NozVine** [comment]
用的就是原版的工具呀，想知道frpc客户端连上frps服务端后，比如用win的master工具远程访问frpc客户端这台电脑需要输入账号密码，那么frps服务端可以知道这个账号密码嘛？

**Comment by Becods** [comment]
不能

这不属于frp的问题
