### ISSUE TITLE
如果想从固定ip段去ssh管理各个frpc，不是固定来源的ssh则拒绝，能在frps,frpc上用iptables实现吗？

### ISSUE THREAD

**Issue by blackantt** [fatedier/frp#312]
frp开了ssh后，只要一次ssh登录，就能进入frpc岂不是不安全,能改进吗？ (http 登录时，就有2次验证。 一次是自己设的 frp的密码， 一次是frpc所在的机器的登录密码。 但ssh登录时就只有一次密码验证。)

   能不能在frps， frpc 上用iptables对 来源ip 做限制？  使只有来自于某网段的ip才能ssh 通过frps，进入frpc  ？
假设一种场景， 需要从固定网段去ssh管理多个frpc 。 但不是从这个固定网段去连 frps， 就拒绝。

**Comment by fatedier** [comment]
可以自行使用 iptables 做这件事，frp 不提供这个功能。
