### ISSUE TITLE
哪里能下载到能用的luci-app-frpc？最新版的以前老的luci-app-frpc都不能用了，官方可能搞个luci-app-frpc？

### ISSUE THREAD

**Issue by vpei** [fatedier/frp#3123]
### Describe the feature request

哪里能下载到能用的luci-app-frpc？最新版的以前老的luci-app-frpc都不能用了，官方可能搞个luci-app-frpc？

### Describe alternatives you've considered

哪里能下载到能用的luci-app-frpc？最新版的以前老的luci-app-frpc都不能用了，官方可能搞个luci-app-frpc？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
请将问题分割，分别去对应的仓库提问

**Comment by vpei** [comment]
已解决。

**Comment by vpei** [comment]
https://github.com/openwrt/packages/pull/19589#pullrequestreview-1139104864

**Comment by shen-lan** [comment]
怎么弄的 ？我这边直接不显示 开启按钮，根本没法开启呀 
![image](https://user-images.githubusercontent.com/21122615/220687438-b4639940-4cfe-4ce7-8d87-0f1e05889b66.png)

**Comment by vpei** [comment]
> 怎么弄的 ？我这边直接不显示 开启按钮，根本没法开启呀 ![image](https://user-images.githubusercontent.com/21122615/220687438-b4639940-4cfe-4ce7-8d87-0f1e05889b66.png)

这个是/etc/config/frpc.ini默认配置文件出错，从网上下载个正确的即可。

**Comment by vpei** [comment]
> > https://github.com/openwrt/luci/tree/master/applications/luci-app-frpc
> 
> 请问这个应该怎么build............

OPENWT的软件包中自带，先opkg update  再opkg install luci-app-frpc安装即可。
