### ISSUE TITLE
SFTP does not work over frp

### ISSUE THREAD

**Issue by Nuckerr** [fatedier/frp#3124]
### Bug Description

I have a server, with sftp. I can connect fine using it's ip, however if I put it under frp with this config;
```
[code_server]
type = tcp
local_ip = 192.168.0.148
local_port = 22
remote_port = 2007
```
it gives me
`Permission denied, please try again.`

### frpc Version

0.43.0

### frps Version

0.39.1

### System Architecture

linux/amd64

### Configurations

```
[code_server]
type = tcp
local_ip = 192.168.0.148
local_port = 22
remote_port = 2007
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
`Permission denied, please try again` indicates that the error occurred on your sftp server and has nothing to do with frp.

**Comment by Nuckerr** [comment]
Well the password is definitely right. And I can sftp when using my internal ip inside the network, no issues. Only through frp does this error occur

**Comment by Arsen6331** [comment]
Is it possible that your SFTP server is configured to only accept internal IPs?

**Comment by Nuckerr** [comment]
I think that is most likely, how do I configure this?

**Comment by Nuckerr** [comment]
@Arsen6331?

**Comment by Arsen6331** [comment]
That depends on which SFTP server you're using. Look at the docs of whichever one you're using.
