### ISSUE TITLE
请问一下关于frp文件传输的文件大小问题

### ISSUE THREAD

**Issue by VeddySama** [fatedier/frp#3125]
### Describe the feature request

我frp代理了一个webdav服务，不使用frp的时候是可以传输大文件的(1.3GB)，但是使用了frp之后该文件(1.3GB)传输不上去，过一段时间就会提示该文件已被占用，这是frp的问题吗

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by filwu8** [comment]
我也有这个问题，我从服务器上下载一个文件，30M大小，就 无线循环，下载不下来

**Comment by VeddySama** [comment]
![image](https://user-images.githubusercontent.com/49411287/195513541-f4f8cec9-3e7b-4061-afd0-f3c2dcaa6bdb.png)

**Comment by VeddySama** [comment]
未解决
