### ISSUE TITLE
内网服务通过frp访问公网服务

### ISSUE THREAD

**Issue by gocpplua** [fatedier/frp#3127]
### Bug Description

我的网络拓扑如下:
公网服务A --  FRPS  -- FRPC(主机1) -- 内网服务B(主机2)

服务AB都是微服务，使用REST API架构。 当测试的时候，AB都在内网，我可以使用IP直接通过HTTP访问，但是现在必须将A部署在外网，B部署在内网。同时还有一个限制是主机1上可以访问公网，我部署了FRPC。 主机2不能访问公网，部署服务B。

我遇到的问题是，现在服务A 可以 访问到B的接口， 但是 服务B 如何通过主机1上的FRPC 访问到 公网服务A的接口？

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

linux/amd64, windows/amd64

### Configurations

frps.ini

[common]
vhost_http_port = 7000

#日志记录等级，有trace, debug, info, warn, error
log_level = debug
#日志保留时间
log_max_days = 3

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
使用 stcp 或在主机 1 部署 http proxy。

**Comment by gocpplua** [comment]
> 使用 stcp 或在主机 1 部署 http proxy。

我google了一圈，issue也看了。 发现 #2280 这问题类似。 官网上也说了[通过代理连接 frps](https://gofrp.org/docs/features/common/client/#%E9%80%9A%E8%BF%87%E4%BB%A3%E7%90%86%E8%BF%9E%E6%8E%A5-frps)。 但是配置是怎么样的还是不太清楚。 我举个例子：
假设主机1： 192.168.1.128   主机2： 192.168.1.130
现在frps.ini 配置是：
`[common]
vhost_http_port = 7000`

那么我是只要在主机1配置 frpc.ini:
`
# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000
http_proxy = http://user:pwd@192.168.1.128:8080`

那么，我由下面的问题：
1. 我主机2 是不是不需要启动frpc，只要在发送http请求的时候，指向主机1：192.168.1.128:8080?  
2. 上面的user:pwd是在哪里设置的？

**Comment by berlin2123** [comment]
如果你的内网服务B无法访问外网。首先保证主机1可以访问服务A的接口（利用frp实现，可以在frps的服务器上运行frpc，或者在其他能够直接访问服务A的能访问外网的主机上运行frpc）。 然后，在主机1上端口转发（firewall-cmd实现，转发主机1上的某个端口到frps服务器的对应端口，或者在主机1上使用stcp并firewall-cmd转发主机1某个端口到stcp设置的那个端口），服务B直接访问主机1的ip和端口就行。

**Comment by gocpplua** [comment]
> 如果你的内网服务B无法访问外网。首先保证主机1可以访问服务A的接口（利用frp实现，可以在frps的服务器上运行frpc，或者在其他能够直接访问服务A的能访问外网的主机上运行frpc）。 然后，在主机1上端口转发（firewall-cmd实现，转发主机1上的某个端口到frps服务器的对应端口，或者在主机1上使用stcp并firewall-cmd转发主机1某个端口到stcp设置的那个端口），服务B直接访问主机1的ip和端口就行。

感谢，有些复杂，我去尝试下 @berlin2123

**Comment by ax2009live** [comment]
主机1 frpc,ini
<pre>
[common]
server_addr = x.x.x.x （frps 的地址）
server_port = 7000
token = admin （密码）

[http_proxy-128]
type = tcp
remote_port = 8080
plugin = http_proxy
plugin_http_user = user
plugin_http_passwd = password
use_encryption = true
use_compression = true
tls_enable = true</pre>

外网程序使用 frps 代理端口 8080 就相当于使用 **_主机1_** 作为代理
**_主机1_** 和 **_主机2_** 在同一局域网，因此外网程序使用 frps 代理端口 8080 可以访问局域网 **_主机2_** 任意开放了的端口；
**主机2** 不需要启动frpc，

服务B 可以通过 frps 代理端口 8080 访问到 公网服务A的接口


另外逆向思维一下：把中国大陆看做互联网，把除了中国之外看做**_局域网_**，
根据上面的方法，frps 在互联网内，frpc 在**_局域网_**内，frpc 配置 http_proxy，
相关程序使用 frps 的 http_proxy 端口，即可不受限制的访问 **_局域网_** ，懂的都会明白；

**Comment by gocpplua** [comment]
> 局域网路由器有公网 ip，frps 跟 **_主机2_** 同一局域网，服务B 可以通过 frps 代理端口 8080 访问到 公网服务A的接口

明白了，感谢！！
