### ISSUE TITLE
Detected as malware App/FRProxy-F

### ISSUE THREAD

**Issue by ferronsw** [fatedier/frp#3129]
### Bug Description

When I download https://github.com/fatedier/frp/releases/tag/v0.44.0 it's detected as malware by Sophos (App/FRProxy-F).

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

linux/amd64, windows/amd64

### Configurations

none

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
https://github.com/fatedier/frp/issues/2095

Take it or leave it.
