### ISSUE TITLE
如何将http请求映射到局域网内其他机器提供的http服务？

### ISSUE THREAD

**Issue by axiang117** [fatedier/frp#313]
报错信息如下：
connect to local port error, dial tcp 192.168.1.170:18080: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

配置如下：
[sun]
privilege_mode = true
type = http
local_ip = 192.168.1.170
local_port = 18080
remote_port = 8088
subdomain = www

**Comment by qq690712575** [comment]
同问

**Comment by zhujia18** [comment]
我的么有问题，没写远端端口，由服务端配置的

**Comment by fatedier** [comment]
网络问题，或者是本地服务的问题。
