### ISSUE TITLE
[Feature Request] 为啥访问静态文件不能通过网址访问，还必须加上端口

### ISSUE THREAD

**Issue by bin01211** [fatedier/frp#3130]
### Describe the feature request

为啥访问静态文件不能通过网址访问，还必须加上端口。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/196087973-a2965d1c-ad34-441e-8def-4f61a6d6e120.png)
