### ISSUE TITLE
great work! i would like to add a rate limiting / ip blocking feature. is there a rate limiting feature for this?

### ISSUE THREAD

**Issue by ultperf** [fatedier/frp#3132]
### Describe the feature request

1. great work! i would like to add a rate limiting / ip blocking feature. is there a rate limiting feature for this?

where can i add this rate limiting or ip detection thing as trying to add firewall capabilities to this.

possible to gimme a clue which file locations i shld be looking at?

2. is there a way to write a plugin addon type for the above?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
You can try it by [Server Plugin](https://github.com/fatedier/frp/blob/dev/doc/server_plugin.md)

**Comment by Becods** [comment]
https://github.com/fatedier/frp/blob/4af85da0c2c6eb981142a8fdb44f885d26cb9d08/conf/frpc_full.ini#L145-L146
