### ISSUE TITLE
how do u disable the admin access of the site?

### ISSUE THREAD

**Issue by ultperf** [fatedier/frp#3133]
### Describe the feature request

how do u disable the admin access of the site?

basically to prevent from attacks / ddos etc.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
What does `admin access` mean?

For the dashboard, it is disabled by default unless it is enabled in the configuration.
