### ISSUE TITLE
有个安全问题。

### ISSUE THREAD

**Issue by accp309** [fatedier/frp#3135]
### Describe the feature request

就是别人知道你的服务器地址和端口就可以连上你的frp了。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frps_full.ini#L83

https://github.com/fatedier/frp/blob/dev/conf/frps_full.ini#L123
