### ISSUE TITLE
Linux版的二进制，Windows下报病毒

### ISSUE THREAD

**Issue by machine-doll** [fatedier/frp#3137]
### Bug Description

<img width="267" alt="image" src="https://user-images.githubusercontent.com/87234334/196601901-9f949a79-ed8a-47a9-bda2-3adfd4b41f34.png">
Windows安全中心说是有病毒

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

linux/amd64

### Configurations

还没开始用

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
https://github.com/fatedier/frp/issues/2095
