### ISSUE TITLE
frp有空主机头功能吗

### ISSUE THREAD

**Issue by befen** [fatedier/frp#3139]
### Describe the feature request

举个例子,这样可以有默认网站
[abc.com]
type = http
local_ip = 127.0.0.1
local_port = 80
custom_domains = *

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
那你为什么不直接tcp
```
[web]
type = tcp
local_ip = 127.0.0.1
local_port = 80
remote_port = 80
```

**Comment by befen** [comment]
这样不能同时多个客户端使用

**Comment by ityc** [comment]
type = http 的本质类似虚拟主机
给个 * 怎么标识

另,不太理解你所指的多客户端使用是 abc.com 这个重复吗
如果是 可以加设备名上去

**Comment by befen** [comment]
比如一个服务端，A客户端绑定*（类似空主机头），默认的http请求都转发到A，其他的客户端就正常绑定custom_domains
