### ISSUE TITLE
有vpn功能吗？

### ISSUE THREAD

**Issue by accp309** [fatedier/frp#3140]
### Describe the feature request

有vpn功能吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
No
