### ISSUE TITLE
xtcp "get sid from visitor error"

### ISSUE THREAD

**Issue by jonayang** [fatedier/frp#3141]
### Bug Description

xtcp无法正常穿透，只把"xtcp"改成"stcp"成功穿透
被访问端NAT类型symmetric
访问端NAT类型full-cone

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

服务端: linux/x86, 被访问端: Windows/x86, 访问端: Mac/Arm

### Configurations

// 被访问端
[common]
server_addr = ipaddr
server_port = 7000

[p2p _ssh]
type = xtcp
local ip = 127.0.0.1
local_port = 3389
sk = sksksk

// 访问端
[common]
server_addr = ipaddr
server_port = 7000

[p2p_ssh_visitor]
type = xtcp
role = visitor
server_name = p2p_ssh
sk = sksksk
bind_addr = 127.0.0.1
bind_port = 6000

// server端
[common]
bind_port = 7000
bind_udp_port = 7000
dashboard_port = ...
//...  dashboard配置

### Logs

访问端报错 "incorrect sid from client"
被访问端报错 "get sid from visitor error: read udp ip:port: i/o timeout"

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
对称型就不要想着p2p了
不是成功不了，是概率特别小

**Comment by AXFOX** [comment]
> 对称型就不要想着p2p了 不是成功不了，是概率特别小

现在FRP的P2P支持哪些类型的NAT穿透呢?
