### ISSUE TITLE
frpc 无法输出日志到文件

### ISSUE THREAD

**Issue by bit-water** [fatedier/frp#3143]
### Bug Description

frpc 无法输出日志到文件

### frpc Version

frp_0.44.0_linux_amd64

### frps Version

frp_0.44.0_linux_amd64

### System Architecture

frp_0.44.0_linux_amd64

### Configurations

log_file = /home/software/frpc/frpc.log

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
控制台报错 麻烦
![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/198593345-d0214f93-d665-4777-9ecf-1c0f0955dee2.png)
