### ISSUE TITLE
stcp搭建完之后无法连接

### ISSUE THREAD

**Issue by tiriolo** [fatedier/frp#3144]
### Bug Description

事情是这样的
我想通过自己的mac远程访问家里面的ubuntu系统的工作站
每次在mac上输入ssh -oPort=6000 [ubuntu的用户名]@127.0.0.1都会提示:
kex_exchange_identification: Connection closed by remote host
Connection closed by 127.0.0.1 port [bind_port]

同时ubuntu系统的工作站提示：
[E] [proxy.go:795] [456249bfbec7724c] [secret_ssh] connect run to local service [127.0.0.1:22] error: dial tcp 127.0.0.1:22 : connect: connection refused

起初我怀疑是ubuntu的端口没有开启，但似乎当我开启ufw，并放行22端口后，依然出现同样的错误，我还尝试检查了ssh的配置文件，似乎并没有什么问题，所以到底问题出在哪里，该如何解决呢

### frpc Version

0.44

### frps Version

0.44

### System Architecture

linux/amd64 , mac

### Configurations

mac上的frpc.ini：
[common]
server_addr = x.x.x.x
server_port = xxxxx
token = xxxxxxxx

[secret_ssh_visitor]
type = stcp
role = visitor
sk = xxxx
server_name = secret_ssh
bind_addr = 127.0.0.1
bind_port = 39725

ubuntu上的frpc.ini
[common]
server_addr = x.x.x.x
server_port = xxxxxx
token = xxxxx

[secret_ssh]
type = stcp
sk = xxxxx
local_ip = 127.0.0.1
local_port = 22

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
`bind_port = 39725`

请指定端口
