### ISSUE TITLE
7400端口网页添加的服务列表，openwrt重启后丢失

### ISSUE THREAD

**Issue by Kalpeny** [fatedier/frp#3145]
### Bug Description

7400端口，网页添加的服务列表不会在openwrt前端显示，且网页添加后passwall无法连接

### frpc Version

0.44.0

### frps Version

0.20.0

### System Architecture

openwrt

### Configurations

[common]
server_addr=xxxx
server_port=5443
log_level=info
log_max_days=3
protocol=tcp
log_file=/var/etc/frp/frpc.log
admin_addr=0.0.0.0
admin_port=7400
admin_user=admin
admin_pwd=admin
tcp_mux=true
tls_enable=false
login_fail_exit=false

### Logs

2022/10/25 15:21:08 [I] [service.go:349] [7feddde26e6caf15] login to server success, get run id [7feddde26e6caf15], server udp port [0]
2022/10/25 15:21:08 [I] [proxy_manager.go:144] [7feddde26e6caf15] proxy added: [openwrt]
2022/10/25 15:21:08 [I] [service.go:158] admin server listen on 0.0.0.0:7400
2022/10/25 15:21:08 [I] [control.go:181] [7feddde26e6caf15] [openwrt] start proxy success
2022/10/25 15:21:34 [I] [admin_api.go:212] Http get request [/api/config]
2022/10/25 15:21:34 [I] [admin_api.go:214] Http get response [/api/config], code [200]
2022/10/25 15:21:35 [I] [admin_api.go:212] Http get request [/api/config]
2022/10/25 15:21:35 [I] [admin_api.go:214] Http get response [/api/config], code [200]
2022/10/25 15:21:36 [I] [admin_api.go:212] Http get request [/api/config]
2022/10/25 15:21:36 [I] [admin_api.go:214] Http get response [/api/config], code [200]
2022/10/25 15:22:19 [E] [control.go:159] [7feddde26e6caf15] work connection closed before response StartWorkConn message: EOF
2022/10/25 15:22:19 [I] [control.go:316] [7feddde26e6caf15] control writer is closing
2022/10/25 15:22:19 [I] [visitor_manager.go:60] [7feddde26e6caf15] gracefully shutdown visitor manager
2022/10/25 15:22:19 [I] [service.go:201] [7feddde26e6caf15] try to reconnect to server...

**Comment by Becods** [comment]
自行检查是否端口冲突
