### ISSUE TITLE
https2http

### ISSUE THREAD

**Issue by chuan1127** [fatedier/frp#3151]
### Bug Description

[W] [control.go:175] [ab1436d24e82fa3a] [plugin_https2http] start error: proxy [plugin_https2http] domain conf check error: custom domain [abc.abc.com] should not belong to subdomain_host [abc.com]

[common]                                                                                                                                                                                                      
server_addr=abc.com                                                                                                                                                                                         
token=123456
server_port = 5443

[plugin_https2http]

type=https
custom_domains=abc.abc.com 

plugin=https2http
plugin_local_addr=192.168.50.7:8088  我需要转发的ip和端口

plugin_tls_crt_path=./mnt/user/frpc/lspon/abc.cert  Lets Encrypt机构X3签发的
plugin_tls_key_path=./mnt/user/frpc/lspon/abc.key   Lets Encrypt机构X3签发的

plugin_host_header_rewrite=192.168.50.7
plugin_header_X-From-Where=frp

无论我们怎么修改始终会报错，或者报错证书路径不存在。
如果可以，希望得到大佬的回应，同时也我给大佬发了邮件，希望能付费远程帮忙解决. 

### frpc Version

0.44

### frps Version

0.44

### System Architecture

linux/amd64

### Configurations

[common]                                                                                                                                                                                                      
server_addr=abc.com                                                                                                                                                                                         
token=123456
server_port = 5443

[plugin_https2http]

type=https
custom_domains=abc.abc.com 

plugin=https2http
plugin_local_addr=192.168.50.7:8088  我需要转发的ip和端口

plugin_tls_crt_path=./mnt/user/frpc/lspon/abc.cert  Lets Encrypt机构X3签发的
plugin_tls_key_path=./mnt/user/frpc/lspon/abc.key   Lets Encrypt机构X3签发的

plugin_host_header_rewrite=192.168.50.7
plugin_header_X-From-Where=frp

### Logs

[W] [control.go:175] [ab1436d24e82fa3a] [plugin_https2http] start error: proxy [plugin_https2http] domain conf check error: custom domain [abc.abc.com] should not belong to subdomain_host [abc.com]

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
frps不要开启subdomain

**Comment by chuan1127** [comment]
大佬，你好，我后面的也删除了，但是还是不行. 实在是不知道咋回事.&nbsp;
frps在国外服务器上，所有的端口全部放行了，
192.168.50.7 是本地的网站，同时FRPC, 也在本地，不知道是证书不支持，还是什么原因, 我看你github的说明是,crt证书，但是我这个是cert，证书的服务商是Let's Encrypt 提供的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fatedier/frp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月28日(星期五) 晚上9:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fatedier/frp] https2http (Issue #3151)





 
frps不要开启subdomain

**Comment by superzjg** [comment]
把证书扩展名改成crt试一下，或者调试时换一个证书试一下，比如使用openssl自签名证书。
把subdomain先关闭。
把以下两句先注释掉，我发现有些web不需要用这两句：
plugin_host_header_rewrite=192.168.50.7
plugin_header_X-From-Where=frp

**Comment by chuan1127** [comment]
已经找到解决办法了，


[lsky.lspon.com]
type = https
custom_domains = lsky.lspon.com
# 接下来的配置是支持 https 的重点配置
# 配置插件，将 https 请求转换成 http 请求后再发送给本地 Web 服务程序
plugin = https2http
# 转换成 http 后，发送到本机的 10000 端口
plugin_local_addr = 192.168.50.7:17900
# 指定成你在前面部分导出的证书的路径
plugin_crt_path = ./lspon.cert
plugin_key_path = ./lspon.key
# frps在本机穿透可能是 frp 的 Bug？这里必须写成 127.0.0.1
#plugin_host_header_rewrite = 192.168.50.7
# 指定代理方式为 frp
#plugin_header_X-From-Where = frp


[lsky]
type = http
local_ip = 192.168.50.7
local_port = 17900
custom_domains = lsky.lspon.com



有些网站要同时开启http的穿透，&nbsp; 这样https才会正常，&nbsp; 估计是bug。&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fatedier/frp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月2日(星期三) 中午12:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fatedier/frp] https2http (Issue #3151)





 
把证书扩展名改成crt试一下，或者调试时换一个证书试一下，比如使用openssl自签名证书。
 把subdomain先关闭。
 把以下两句先注释掉，我发现有些web不需要用这两句：
 plugin_host_header_rewrite=192.168.50.7
 plugin_header_X-From-Where=frp
