### ISSUE TITLE
Verify if Same Code From This Repo

### ISSUE THREAD

**Issue by FliKites** [fatedier/frp#3153]
### Bug Description

A company by the name of "Proxidize" uploaded files manually into github on September 15th, 2022 that claims to use this exact implementation of a FRP server. You can see the credits of their project to confirm by visiting: https://github.com/proxidize/proxidize-android/blob/main/CREDITS

They bundled the "server" file in Binary form and have stated that I should cross reference the MD5 with the binary of your repo:

This is the MD5 hash for the file below: 2C9148CF7F7EF624AD3DA7A7B4CB8B7C

https://github.com/proxidize/proxidize-android/blob/main/server/server

They told me to do a check on the MD5 so that's what I am doing: 

https://prnt.sc/WWgUvNx1-ehS

Would you be able to confirm that the MD5 above matches up with your code from this repo? 

### frpc Version

not available

### frps Version

not available 

### System Architecture

not available

### Configurations

Binary?

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
In each release assets, there is a `frp_sha256_checksums.txt` file. You can check it by yourself.

**Comment by FliKites** [comment]
Can you provide me a link to the file? I can't seem to find it in the repo.

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/releases
