### ISSUE TITLE
服务端开放客户端远程端口无法连接

### ISSUE THREAD

**Issue by wxjeek** [fatedier/frp#3154]
### Bug Description

我搭建了一个cs端，客户端注册到服务端是ok的，服务端也监听了客户端配置的远程端口，服务端本地连接客户端网络端口是ok的，但是我把服务端的远程端口开放，其他客户端无法连接此监听端口

### frpc Version

0.45.0

### frps Version

0.45.0

### System Architecture

clinet windows/amd64 & server linux/amd64

### Configurations

主页简单配置

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by Becods** [comment]
大部分需要gslt的服务端的连接ip必须是向gslt注册时使用的ip

所以，frp不兼容此类游戏服务器的穿透，也不可能去适配

![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/199038452-464e5499-ed44-492a-b1c4-c0440483d388.png)
