### ISSUE TITLE
no such domain

### ISSUE THREAD

**Issue by augustdoit** [fatedier/frp#3158]
### Bug Description

以前偶尔断，现在连不上了。
frps debian
frpc openwrt

### frpc Version

0.34.3

### frps Version

0.34.3

### System Architecture

debain openwrt

### Configurations

[common]
bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
token = ******
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = ******
log_file = /root/frp/frps.log
log_level = info
log_max_days = 3
tcp_mux = true

### Logs

root@debian:~/frp# tail -f frps.log
2022/11/03 02:22:31 [I] [control.go:384] [3a6f783cfbd70032] client exit success
2022/11/03 02:22:31 [I] [service.go:444] [3a6f783cfbd70032] client login info: ip [221.***.***.243:10341] version [0.34.3] hostname [] os [linux] arch [amd64]
2022/11/03 02:22:35 [W] [http.go:86] do http proxy request error: no such domain: pan.******.cyou /seafhttp/protocol-version
2022/11/03 02:22:40 [I] [service.go:190] frps tcp listen on 0.0.0.0:7000
2022/11/03 02:22:40 [I] [service.go:232] http service listen on 0.0.0.0:80
2022/11/03 02:22:40 [I] [service.go:253] https service listen on 0.0.0.0:443
2022/11/03 02:22:40 [I] [service.go:289] Dashboard listen on 0.0.0.0:7500
2022/11/03 02:22:40 [I] [root.go:215] start frps success
2022/11/03 02:22:41 [I] [service.go:444] [3a6f783cfbd70032] client login info: ip [221.***.**.243:10359] version [0.34.3] hostname [] os [linux] arch [amd64]
2022/11/03 02:22:46 [W] [http.go:86] do http proxy request error: no such domain: pan.******.cyou /seafhttp/protocol-version
2022/11/03 02:22:55 [W] [http.go:86] do http proxy request error: no such domain: pan.******.cyou /seafhttp/protocol-version
2022/11/03 02:23:01 [I] [service.go:444] [f325fb9b2d041657] client login info: ip [221.******.243:10395] version [0.34.3] hostname [] os [linux] arch [amd64]
2022/11/03 02:23:05 [W] [http.go:86] do http proxy request error: no such domain: pan.******.cyou /seafhttp/protocol-version
2022/11/03 02:23:11 [W] [http.go:86] do http proxy request error: no such domain: h5ai.******.cyou /
2022/11/03 02:23:11 [I] [control.go:309] [3a6f783cfbd70032] control writer is closing
2022/11/03 02:23:11 [I] [control.go:384] [3a6f783cfbd70032] client exit success

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by augustdoit** [comment]
2022/11/03 02:36:58 [I] [https.go:51] [77f8aa3d56f8cb14] [exsi] https proxy listen for host [exsi.******.cyou]
2022/11/03 02:36:58 [I] [control.go:446] [77f8aa3d56f8cb14] new proxy [exsi] success
2022/11/03 02:37:01 [I] [service.go:444] [066a1a3cb301e93b] client login info: ip [221.***.***.243:9732] version [0.34.3] hostname [] os [linux] arch [amd64]
2022/11/03 02:37:05 [I] [proxy.go:103] [77f8aa3d56f8cb14] [NAS-PANWORK] get a new work connection: [221.223.51.243:9715]
2022/11/03 02:37:13 [W] [http.go:86] do http proxy request error: context canceled
2022/11/03 02:37:16 [W] [control.go:269] [77f8aa3d56f8cb14] timeout trying to get work connection
2022/11/03 02:37:16 [W] [proxy.go:100] [77f8aa3d56f8cb14] [NAS-h5ai] failed to get work connection: timeout trying to get work connection
2022/11/03 02:37:19 [I] [control.go:309] [77f8aa3d56f8cb14] control writer is closing
2022/11/03 02:37:19 [I] [proxy.go:87] [77f8aa3d56f8cb14] [NAS-PT] proxy closing
2022/11/03 02:37:19 [I] [proxy.go:87] [77f8aa3d56f8cb14] [NAS-ariang] proxy closing
2022/11/03 02:37:19 [I] [proxy.go:87] [77f8aa3d56f8cb14] [aria2-rcp] proxy closing
2022/11/03 02:37:19 [W] [http.go:86] do http proxy request error: EOF
2022/11/03 02:37:19 [W] [control.go:263] [77f8aa3d56f8cb14] no work connections avaiable, control is closed

这个是因为网络条件不好么？

**Comment by Becods** [comment]
大概率网络不好

尝试使用kcp以及更新版本
