### ISSUE TITLE
How to judge the failure of xtcp, and then automatically convert to stcp

### ISSUE THREAD

**Issue by aotuitx** [fatedier/frp#3159]
How to judge the failure of xtcp, and then automatically convert to stcp?

How is the v2 version now? Can you see it this year?

**Comment by Bellegar** [comment]
I assumed that automatic fallback to stcp from xtcp is mentioned in readme "You might want to fallback to stcp if xtcp doesn't work." (as protocol ICE works STUN->TURN), suddenly, it's not woking as i expected.
