### ISSUE TITLE
start error: port unavailable

### ISSUE THREAD

**Issue by wuai1024** [fatedier/frp#3160]
### Bug Description

映射两位数和三位数的端口会报错，端口不可用

### frpc Version

0.45.0

### frps Version

0.45.0

### System Architecture

linux/amd64

### Configurations

remote_port = 88     ×
remote_port = 888   ×
remote_port = 8888 √

### Logs

start error: port unavailable

### Steps to reproduce

![image](https://user-images.githubusercontent.com/13379708/199997263-ed3d6d34-7cef-494a-b758-bfe1408866a6.png)

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
尝试用root权限启动frps

非root权限无法映射1024以下端口

**Comment by wuai1024** [comment]
强啊，解决了我的问题了。
