### ISSUE TITLE
望考虑 https2http 插件支持 wss 

### ISSUE THREAD

**Issue by whwnow** [fatedier/frp#3162]
### Describe the feature request

我在本地部署 Rocket.Chat 时，本地服务是 http + ws，然后使用 https2http 插件转成 https 对外，wss 协议的状态码一直为101 。看到 issues 里有不少都在提这个功能。给的方案是是自己在加一层 nginx，然后 frp 使用 tcp 协议。这个从易用性上牺牲好多，本来使用 https2http 插件，证书的问题全都解决了，现在还要自己再加一套 nginx，做 https 转发。望考虑一下这个需求

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
如果解决方案不复杂的话，可以考虑。

**Comment by xeahsoon** [comment]
+1，啥时候能支持 wss 啊，现在通过 frp 运行 code-server 根本用不了 https，有点小抓狂

**Comment by ningfdx** [comment]
@fatedier 可否提供一下思路，，我可以帮助开发和贡献

**Comment by fatedier** [comment]
排查到是由于 yamux 的一个问题导致 wss 无法正常使用: https://github.com/hashicorp/yamux/pull/121

会在这个 PR 中修复: https://github.com/fatedier/frp/pull/3503

**Comment by whwnow** [comment]
> 

给力，这个问题终于解决了，哈哈

**Comment by rebron1900** [comment]
@whwnow 大佬，如何才能在插件里启用wss呢？

**Comment by kriskongx** [comment]
@rebron1900 请问下最终解决了吗？看了半天https2http插件是不是还是不支持wss啊

**Comment by PhDLuffy** [comment]
@FocusProgram 问题解决了，更新frp 0.51之后的版本就OK了，正常使用https2http就可以，非常完美。

**Comment by rebron1900** [comment]
> [@FocusProgram](https://github.com/FocusProgram) 问题解决了，更新frp 0.51之后的版本就OK了，正常使用https2http就可以，非常完美。
 
你具体怎么配置的？我现在是下面这个配置，但是minio前端提示 `objectBrowserWSMiddleware.ts:78 WebSocket connection to 'wss://miniow.test.com:1234/ws/objectManager' failed: `

```
[[proxies]]
name = "miniow"
type = "https"
subdomain = "miniow"
transport.proxyProtocolVersion = "v2"
[proxies.plugin]
type = "https2http"
localAddr = "192.168.1.12:56184"                                         
crtPath = "/ssl/1234/frp.crt"
keyPath = "/ssl/1234/frp.key"      
hostHeaderRewrite = "192.168.1.12"                                      
requestHeaders.set.x-from-where = "frp"
```
