### ISSUE TITLE
[Feature Request] frps能否增加一个限制带宽的参数，能独立限制上行或者下行的

### ISSUE THREAD

**Issue by wuai1024** [fatedier/frp#3163]
### Describe the feature request

目前我看到在 frpc 里面是有网速限制的。客户端多了，需要每个都配置。

能否在frps上也增加个网速限制的配置参数，这样避免超流量使用。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
整个进程的带宽限制建议看是否能配合其他工具实现吧。
