### ISSUE TITLE
[Feature Request] 是否可以通过类似与vmess://之类的形式通过url快速启动frpc

### ISSUE THREAD

**Issue by zwx08** [fatedier/frp#3165]
### Describe the feature request

在使用中，想到v2ray等可以通过vmess://这类的协议进行快速导入配置
是否可以通过比如说frp://ababababab这类型的一串非加密url解析出配置文件然后进行启动
也就是说是
配置文件→frp://→配置文件
在执行时通过./frpc -url "frp://ababababab"这样进行快速启动，优先度高于配置文件且与-c冲突
（懒人必备）frp提供商仅需要给与此url即可

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
之前的 issue 有提到，v2 中会这方面的改进。

**Comment by sazima** [comment]
```
Windows Registry Editor Version 5.00
[HKEY_CLASSES_ROOT\frpc]
@="URL:"
"URL Protocol"=""
[HKEY_CLASSES_ROOT\frpc\shell]
[HKEY_CLASSES_ROOT\frpc\shell\open]
[HKEY_CLASSES_ROOT\frpc\shell\open\command]
@="c:\\frpc.exe -c c:\\frpc.ini"
```


可以写一个类似这样的注册表文件, 参考一下这个: https://stackoverflow.com/questions/64277878/open-external-application-from-browser-in-windows-from-a-mediawiki-page
