### ISSUE TITLE
[Feature Request] 能否增加一个功能，访问之后关闭当前连接？

### ISSUE THREAD

**Issue by liasica** [fatedier/frp#3168]
### Describe the feature request

工作需要，经常家里公司两边使用同一个端口进行调试
这个时候就会冲突

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
之前有类似的 issue，以后可能会支持。
