### ISSUE TITLE
[Feature Request] 是否考虑添加import外部配置功能？

### ISSUE THREAD

**Issue by Orisland** [fatedier/frp#3169]
### Describe the feature request

在本地网络有多个frp服务器线路时，如果需要增删本地的链接则需要使用两份不同的frpc.ini，而实际上，两个frpc.ini的区别仅在于token与域名，希望frp在未来可以推出import功能，导入公共的配置，让两个frpc使用相同的客户端连接配置和不同的common配置。
这样可以免去反复复制粘贴的烦恼，也方便不同的功能进行拆分处理。
例如:
```c
frpc1.ini

[common]
token = xxx
ip = xxx

[import]
id = primary_key1
dir = xxx/xxx/frpc_public.ini
```

```c
frpc2.ini

[common]
token = xxx
ip = xxx

[import]
id = primary_key2
dir = xxx/xxx/frpc_public.ini
```
```c
frpc_public.ini

[client1]
type = xxx
local_ip = xxx
remote_port = xxx
local_port = xxx

[client2]
.....
```

### Describe alternatives you've considered

如果该功能不能被提供，那么我就需要对每一个frpc.ini进行重复性的复制粘贴工作，这会提高配置的错误率，也更为繁琐。
一旦涉及到本地客户端的增删或者端口的调整则需要对n个frpc.ini进行重复的工作。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Orisland** [comment]
> 这个，个人认为用途不大，从您提供的配置文件实例来看，既然已经指定了服务器 IP 地址，又何必在多此一举，将单隧道文件再拆分开来，再其次的话，对于 Frp 这类项目而言，仅仅是一个求将内网服务穿透出去，对于大访问量分布式服务个人认为是不太适合，犹如现在的主要几家 Frp 服务，每个服务器的子隧道的配置文件很难做到一样，如果是仅是自己的使用需求，不使用市面上已有的穿透服务的话，无论内外网，都可以直接采用 HAProxy IPtables 等直接进行代理，对于多线路的需求理论上不大，因此我认为，没太大的必要吧……（仅个人建议，勿喷）

错误的，这种功能的面向为我自己的多台云服务器，每台服务器均为我自行搭建的frps，并不是市面上的商业frp。我需要不止一条线路来减少某一台宕机导致的连接全部中断问题。
多个线路的接入仅出于线路稳定性考虑。

**Comment by fatedier** [comment]
https://github.com/fatedier/frp#split-configures-into-different-files
