### ISSUE TITLE
FRP开机自启动、HTTP穿透失效等问题

### ISSUE THREAD

**Issue by zhujia18** [fatedier/frp#317]
跑FRP大概3周了，Server跑在阿里云上，Client跑在树莓派上，issue也都翻了很多，配置也调试过，还是有些问题和疑惑，开个issue求解一下~
1.关于FRP开机自启动的问题，搜了issue，看见开发者有回复说不支持，也有人自己写systemd实现了的，但是我自己写systemd之后，手动调用总是能成功，但是设置enable开机启动的话，放在网络之后，还是启动失败。。。写rc.local里，不是每次都能成功。。已经sleep 30了。不知道这块有没有其他的解决办法

2.http穿透成功后，过一段时间再访问就穿透不进去了，ssh却是一直没问题，这时候无论重启Server或者是Client之后，http穿透都会恢复正常，但是过一段时间又失效了，可能也就30分钟或者1个小时。

3.设置host_header_rewrite不起作用。。。好像host被替换错了

4.这个算是一个疑惑，如果使用特权模式，做http穿透配置，又给这个配置写了remote_port，那么这个远端端口跟vhost_http_port是啥关系啊？是会被自动忽略么？目前是只能配置一个http的端口么？

感谢解惑~

**Comment by fatedier** [comment]
1. 一个 issue 反馈一个问题。
2. 每一个问题需要提供详细的信息。
3. 反馈问题之前先查看是否已经有类似的 issue。

这个 issue 先关闭，之后如果仍然有问题按照规范提交 issue。
