### ISSUE TITLE
[Feature Request] use the same remote port by multiple local machines

### ISSUE THREAD

**Issue by shabakett** [fatedier/frp#3170]
how to expose 10 machines each running REST API (http) server on port 8080 using the same remote port 5588 and a custom header or query string to distinguish between destinations?

**Comment by shabakett** [comment]
already done with `vhost_http_port`, `subdomain_host`, `subdomain`

**Comment by Becods** [comment]
As you said, just set a different custom header on each REST API server.

Or you can modify the api server callback.
