### ISSUE TITLE
[Feature Request] basic authentication using a simple SQLite database

### ISSUE THREAD

**Issue by shabakett** [fatedier/frp#3173]
add `authentication_method = basic`, basic_authentication_username and basic_authentication_password
using a local SQLite database with a table "clients" (username, password)

**Comment by fatedier** [comment]
You can implement your own plugin like this [fp-multiuser](https://github.com/gofrp/fp-multiuser)

**Comment by shabakett** [comment]
you can just use fastapi:

`@app.post("/tunnel_auth")
async def tunnel_auth(request: Request):
    try:
        body = await request.json()
        results = await database.fetch_all(query="SELECT * FROM tunnel WHERE tun_enabled=1 AND tun_endpoint_code=:code AND tun_password=:password", values={"code": body["content"]["user"], "password": body["content"]["metas"]["password"]}) 
        if results: return {"reject": False, "unchange": True } 
        else: return {"reject": True, "reject_reason": "authentication failed!" }
    except Exception as e:
        return {"reject": True, "reject_reason": "exception: " + str(e) }`
