### ISSUE TITLE
[Feature Request] 希望增加一个run_fail_exit的配置，用于运行过程中出现错误时是否退出

### ISSUE THREAD

**Issue by xiangxisheng** [fatedier/frp#3175]
### Describe the feature request

增加的 run_fail_exit 配置的功能类似 login_fail_exit 配置的作用，
当 login_fail_exit 为 true 时，则在第一次登录失败后就退出，
而 run_fail_exit 为 true 时，则在运行过程中只要遇到错误就会退出。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
没有这样的计划，如果有需要，建议可以结合其他工具或脚本实现。

**Comment by xiangxisheng** [comment]
想知道结合什么工具可以实现这种操作呢？监控返回错误后去杀进程吗？
而且实现我说的这个功能，代码量并不多。如果默认值为false的话，是不会影响现有的执行逻辑的。
不到5分钟就能实现的代码量为什么让我们花半个小时去额外加一套脚本或工具呢？

**Comment by ilaziness** [comment]
@xiangxisheng 这不是你在公司提需求，不是普遍需要的功能，是不会做的，人人都这样，就会出现一大堆垃圾功能。
