### ISSUE TITLE
[Feature Request] 更改 frps 上的 https 证书 (Change https-certificats on frps)

### ISSUE THREAD

**Issue by cedricbieder** [fatedier/frp#3176]
### Describe the feature request

Hi I am not sure if this features exist alreasy, but I cannot find it. I want to proxy a local-https port over my frps and change the used certificates on the frps so they match the domain of the tunnel.
For example:
tunnel my local webpage running wit the cert: "firstdomain.com"

frpc:

```
[8443]
type=https
local_ip=127.0.0.1
local_port=8443
subdomain=sub

[common]
server_addr=serverdomain.com
server_port=80
authentication_method=token
token=megasecret
```
frps:

```
[common]
subdomain_host = serverdomain.com
bind_port = 80
vhost_https_port = 80
token = megasecret
```

If I call now https://sub.serverdomain.com I get my local running page but still have the certificate of firstdomain.com which end in a not so pretty warning/error of the browser. It would be nice if you can swap here the certs to *.serverdomain.com or something. 

Can it be that this is already implemented for tls? 

I am kind of new to the project so please forgive me if this is already solved. :)

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Not supported now.

You can use plugin [https2http](https://github.com/fatedier/frp#enable-https-for-local-https-service) and put your certs on frpc's machine.
