### ISSUE TITLE
log_file on windows : backslash issue

### ISSUE THREAD

**Issue by shabakett** [fatedier/frp#3178]
### Bug Description

`log_file = D:\log.txt` shows `logs.BeeLogger.SetLogger: invalid character 'l' in string escape code`
`log_file = D:/log.txt` works well

### frpc Version

0.45.0

### frps Version

0.45.0

### System Architecture

windows/amd64

**Comment by Becods** [comment]
`\` is an escape character.

Please replace it with `/`.

**Comment by shabakett** [comment]
but `\` in windows is the path separator also and it is easier to copy a path then paste it in frpc.ini
