### ISSUE TITLE
使用xtcp协议访问同一IP的不同端口时，部分端口访问失败

### ISSUE THREAD

**Issue by iwlei** [fatedier/frp#3179]
### Bug Description

前提1：nas的docker中部署了两套媒体库（plex、emby），均使用了该nas的IP地址，在nas所在局域网内任意设备均可正常访问媒体库；
前提2：nas另搭建了个debian11虚拟机，专门负责运行frp穿透；
前提3：使用xtcp协议已可正常从外网其他设备使用微软远程桌面访问nas下的Windows11虚拟机；
问题描述：
当我配置完后，在外网其他设备使用设置的IP及端口访问被访问端时，两套媒体库中有一套（plex）访问失败，另一套则正常访问（emby）。

### frpc Version

0.45.0

### frps Version

0.45.0

### System Architecture

被访问端：linux/amd64，访问端：windows/amd64

### Configurations

被访问端frpc.ini
[common]
server_addr = **********
server_port = ****
token = *********
log_file = /usr/frp/frpc.log
log_level = info
log_max_days = 3
tls_enable = true

[xn-win11-p2p]
type = xtcp
sk = ********
local_ip = 10.0.0.213
local_port = 3389

[emby-p2p]
type = xtcp
sk = ********
local_ip = 10.0.0.84
local_port = 8096

[plex-p2p]
type = xtcp
sk = ********
local_ip = 10.0.0.84
local_port = 32400

访问端frpc.ini
[common]
server_addr = **********
server_port = ****
token = ********

[XX-RDP-QS]
type = xtcp
role = visitor
server_name = xn-win11-p2p
sk = ********
bind_addr = 0.0.0.0
bind_port = 1111

[plex-xx-p2p]
type = xtcp
role = visitor
server_name = plex-p2p
sk = ********
bind_addr = 0.0.0.0
bind_port = 32400

[emby-xx-p2p]
type = xtcp
role = visitor
server_name = emby-p2p
sk = ********
bind_addr = 0.0.0.0
bind_port = 8096

### Logs

2022/11/22 10:45:22 [I] [visitor.go:301] [589928533313c5e5] [emby-xx-p2p] nat hole connection make success, sid [16690851228df794c058715a86]
2022/11/22 10:45:22 [I] [visitor.go:301] [589928533313c5e5] [emby-xx-p2p] nat hole connection make success, sid [1669085122aa160e5c00b79980]
2022/11/22 10:45:22 [I] [visitor.go:301] [589928533313c5e5] [emby-xx-p2p] nat hole connection make success, sid [16690851229e9449c12021ed35]
2022/11/22 10:45:29 [I] [visitor.go:301] [589928533313c5e5] [plex-xx-p2p] nat hole connection make success, sid [1669085129042c7c841792a5f7]
2022/11/22 10:59:55 [I] [visitor.go:301] [589928533313c5e5] [XX-RDP-QS] nat hole connection make success, sid [1669085994e0c7a281b5be9a12]
2022/11/22 10:59:59 [W] [visitor.go:245] [589928533313c5e5] [plex-xx-p2p] get natHoleRespMsg error: read udp 192.168.2.202:64590->162.14.122.68:45432: i/o timeout
2022/11/22 11:00:00 [I] [visitor.go:301] [589928533313c5e5] [plex-xx-p2p] nat hole connection make success, sid [16690860008277f3b7a7f07c4f]
2022/11/22 11:00:12 [I] [visitor.go:301] [589928533313c5e5] [plex-xx-p2p] nat hole connection make success, sid [1669086012748cf34b07584da8]
2022/11/22 11:00:38 [W] [visitor.go:245] [589928533313c5e5] [plex-xx-p2p] get natHoleRespMsg error: read udp 192.168.2.202:64595->162.14.122.68:45432: i/o timeout
2022/11/22 11:00:41 [W] [visitor.go:296] [589928533313c5e5] [plex-xx-p2p] incorrect sid from client
2022/11/22 11:01:32 [I] [visitor.go:301] [589928533313c5e5] [plex-xx-p2p] nat hole connection make success, sid [1669086090bf6a62805029f356]

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
xtcp 暂时没有继续维护了。

**Comment by iwlei** [comment]
> 维护了。

可惜了，可以正常访问的端口目前体验挺好
