### ISSUE TITLE
why is this section removed?

### ISSUE THREAD

**Issue by shabakett** [fatedier/frp#3180]
why is "Connect website through frpc's network" section removed? I think it is useful to explain the purpose of `plugin = http_proxy`

Connect website through frpc's network

```
# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[http_proxy]
type = tcp
remote_port = 6000
plugin = http_proxy # or socks5
```

Set http proxy or socks5 proxy x.x.x.x:6000 in your browser and visit website through frpc's network.

### frpc Version

0.45.0

### frps Version

0.45.0

**Comment by Becods** [comment]
[#Client Plugins](https://github.com/fatedier/frp#client-plugins)

> frpc only forwards requests to local TCP or UDP ports by default.
>
> Plugins are used for providing rich features. There are built-in plugins such as unix_domain_socket, http_proxy, **socks5**, static_file, http2https, https2http, https2https and you can see [example usage](https://github.com/fatedier/frp#example-usage).
>
>Specify which plugin to use with the plugin parameter. Configuration parameters of plugin should be started with plugin_. local_ip and local_port are not used for plugin.

**Comment by shabakett** [comment]
these expressions make the doc clearer:

`Connect website through frpc's network`

`Set http proxy or socks5 proxy x.x.x.x:6000 in your browser and visit website through frpc's network.`
