### ISSUE TITLE
http功能默认404错误能否改成403或者503错误

### ISSUE THREAD

**Issue by befen** [fatedier/frp#3181]
### Describe the feature request

http功能默认404错误能否改成403或者503错误

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
https://github.com/fatedier/frp/blob/da51adc27670f495478f50634462954319e4fc14/pkg/util/vhost/resource.go#L77-L78

**Comment by befen** [comment]
> https://github.com/fatedier/frp/blob/da51adc27670f495478f50634462954319e4fc14/pkg/util/vhost/resource.go#L77-L78

403和503的Status分别是啥？

**Comment by befen** [comment]
> https://github.com/fatedier/frp/blob/da51adc27670f495478f50634462954319e4fc14/pkg/util/vhost/resource.go#L77-L78

Status:        "Service Unavailable",
StatusCode:    503,

这么写编译完了还是404
