### ISSUE TITLE
客户断新增在后台看见那些IP连接了客户端

### ISSUE THREAD

**Issue by GithubGey** [fatedier/frp#3182]
### Describe the feature request

可不可在后台页面新增
那些IP连接了客户端

方便查看和跟踪

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
get+diff
