### ISSUE TITLE
timeout when connecting to frps through the socks5 proxy with the kcp protocol

### ISSUE THREAD

**Issue by aa51513** [fatedier/frp#3183]
### Bug Description

When connecting to frps through the socks5 proxy, if kcp is specified, it will fail to connect

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

linux/amd64

### Configurations

[common]
log_file = /var/log/frp/frpc.log
http_proxy = socks5://hello:world@127.0.0.1:1080
server_addr = 10.0.0.173
server_port = 7000
token = frpToken123
protocol = kcp

[server_ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

### Logs

[W] [service.go:204] [f98f1934ed9f4b28] reconnect to server error: i/o deadline reached, wait 20s for another  retry
[I] [service.go:201] [f98f1934ed9f4b28] try to reconnect to server...
[W] [service.go:204] [f98f1934ed9f4b28] reconnect to server error: i/o deadline reached, wait 20s for another  retry
[I] [service.go:201] [f98f1934ed9f4b28] try to reconnect to server...
[W] [service.go:204] [f98f1934ed9f4b28] reconnect to server error: i/o deadline reached, wait 20s for another  retry
[I] [service.go:201] [f98f1934ed9f4b28] try to reconnect to server...
[W] [service.go:204] [f98f1934ed9f4b28] reconnect to server error: i/o deadline reached, wait 20s for another  retry
[I] [service.go:201] [f98f1934ed9f4b28] try to reconnect to server...

### Steps to reproduce

when i changed the protocol from kcp to tcp it worked
[common]
log_file = /var/log/frp/frpc.log
http_proxy = socks5://hello:world@127.0.0.1:1080
server_addr = 10.0.0.173
server_port = 7000
token = frpToken123
protocol = **tcp**

[server_ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frpc_full.ini#L17

**Comment by aa51513** [comment]
> https://github.com/fatedier/frp/blob/dev/conf/frpc_full.ini#L17

Thanks for pointing out my oversight
