### ISSUE TITLE
remote_port不能设置为22么

### ISSUE THREAD

**Issue by yutent** [fatedier/frp#3184]
### Bug Description

服务端22端口是空闲的。
我想把内网中一台机器的ssh端口, 映射到远程的22端口上, 发现不起作用, 也没报错。
换其他端口, 如2222, 就正常。

### frpc Version

0.43

### frps Version

0.43

### System Architecture

linux/amd64

### Configurations

.

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
端口冲突

**Comment by yutent** [comment]
> 端口冲突

没冲突, 应该只是程序内部不允许设置吧, 我试了几个比较小的端口都不行。  现在用iptables做一层转发来实现22端口了
