### ISSUE TITLE
how to hide token and http_pwd when using frpc on windows?

### ISSUE THREAD

**Issue by shabakett** [fatedier/frp#3186]
I try to pass `token` and `http_pwd` to `frpc.exe` using a c# application, I set them as environment variables in `frpc.ini` then pass them to the process, but some tools like `Process Explorer` and `Process Hacker` can view those environment variables.
hiding them is required when you have a server on the internet running frps and you need to run frpc on a machine (owned by another person) behind the nat.

is there any method to hide them? 
can I use `P/Invoke` to call frpc from c# program? this involves building `frpc.dll` and I do not know if it will resolve the `big problem` on windows: detecting golang binaries as virus by `microsoft defender` and some other antiviruses.

**Comment by Becods** [comment]
Discard environment variables

Write these variables directly into frpc.ini

Then delete this configuration file the moment frpc starts successfully
