### ISSUE TITLE
frp can not get Mac‘s localhost(frp无法获取Mac的localhost）

### ISSUE THREAD

**Issue by Danielkarlheng** [fatedier/frp#3187]
### Bug Description

I have configured frps and frpc,also get dashboard,open my website ,it is prompt The page you requested was not found.According to my test, the question is frp can not get my localhost(Mac).I don't know how to solve it.I would appreciate if you help me, thank you!

### frpc Version

0.45.0

### frps Version

0.45.0

### System Architecture

linux Mac

### Configurations

 have configured frps and frpc,also get dashboard,open my website ,it is prompt The page you requested was not found.According to my test, the question is frp can not get my localhost(Mac).I don't know how to solve it.I would appreciate if you help me, thank you!

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/204139050-9f8c8581-5e12-4471-b669-493e99992c8c.png)

**Comment by girishbin** [comment]
On you local machine where you run frp client i.e frpc -c frpc.ini make a entry of the  frp server ( frps) address in "/etc/hosts".  This works for both mac and linux.
