### ISSUE TITLE
[Feature Request] 开启 tls_enable 时支持远程证书

### ISSUE THREAD

**Issue by liuweiGL** [fatedier/frp#3189]
### Describe the feature request

现在开启 `tls_enable` 之后每个端都要复制一份证书文件有点麻烦，希望能添加一个配置项比如 `tls_remote_repo`  用于从远程仓库自动下载更新 `tls_cert_file` `tls_key_file` `tls_trusted_ca_file` 所需要的证书文件

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
那如何信任远端获取的证书？

**Comment by liuweiGL** [comment]
这个是用户自己配置的应该没问题吧，只不过是把本地文件放在远程仓库里面统一维护而已

**Comment by xqzr** [comment]
> 那如何信任远端获取的证书？

系统内置 CA
