### ISSUE TITLE
转局域网的https出错

### ISSUE THREAD

**Issue by gamexy** [fatedier/frp#3191]
### Bug Description

转http服务没有问题，但如果是https，就会报
ERR_SSL_PROTOCOL_ERROR

### frpc Version

0.45

### frps Version

0.45

### System Architecture

linux/amd64

### Configurations

frpc的配置
[common]
server_addr = x.x.x.x
server_port = 7000

[NASweb]
type = tcp
local_ip = 192.168.1.100
local_port = 5000
remote_port = 5000

然后浏览器使用x.x.x.x:5000访问，就出现以下提示

此站点的连接不安全x.x.x.x 发送了无效的响应。
[尝试运行 Windows 网络诊断](javascript:diagnoseErrors())。
ERR_SSL_PROTOCOL_ERROR

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
你穿透的是tcp
不关frp的事
自行寻找原因

**Comment by gamexy** [comment]
> 你穿透的是tcp 不关frp的事 自行寻找原因

确实不关frp的事儿，是我使用上的问题，请问该怎样做？

**Comment by gamexy** [comment]
找到问题了，frpc端上的openssl版本的问题
