### ISSUE TITLE
流量被嗅探

### ISSUE THREAD

**Issue by lerogo** [fatedier/frp#3193]
### Describe the feature request

frp客户端的流量通过防火墙时，流量会被防火墙嗅探到，从而内网机器被封ip
希望增加伪装功能，或者加密传输

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [x] Client Plugin
- [x] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
```
[common]
...
tls_enable = true
disable_custom_tls_first_byte = true
```

**Comment by ideazw** [comment]
> ```
> [common]
> ...
> tls_enable = true
> disable_custom_tls_first_byte = true
> ```

加了这个就不会被嗅探到了吗？

**Comment by xqzr** [comment]
> > ```
> > [common]
> > ...
> > tls_enable = true
> > disable_custom_tls_first_byte = true
> > ```
> 
> 加了这个就不会被嗅探到了吗？

~最大~可能减少。

**Comment by guation** [comment]
改用kcp协议然后外面套个udp2raw 以前v2ray的mkcp被gfw检测封杀的时候就是用udp2raw来过墙的
