### ISSUE TITLE
[Feature Request] Dynamically update frpc.ini

### ISSUE THREAD

**Issue by CarbonPool** [fatedier/frp#3196]
### Describe the feature request

I need to obtain custom meta information on the server, but the meta defined on the client is dynamic. Is there any way to achieve it?

### Affected area

- [ ] Docs
- [X] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by Becods** [comment]
[#Hot-Reloading frpc configuration](https://github.com/fatedier/frp#hot-reloading-frpc-configuration)

Please read the README.md carefully.
