### ISSUE TITLE
can work if install on a private ip host and set port  map in  a router which have a public ip?

### ISSUE THREAD

**Issue by lygn128** [fatedier/frp#3197]
### Describe the feature request

client A：private  ip host;
client B:   private ip host;
Server A: private ip host under a public ip router R;
i want ssh to client A  from client B,  if   i   install  frp in Server A, and config port map in route R,
do the config can work?  thank you very much.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
Yes, the odds are that this will work.

Practice makes perfect.
