### ISSUE TITLE
[Feature Request] 可以多个客户端连接同一个端口负载均衡吗？

### ISSUE THREAD

**Issue by accp309** [fatedier/frp#3199]
### Describe the feature request

可以多个客户端连接同一个端口负载均衡吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
你需要 [Haproxy](https://www.haproxy.org/)
