### ISSUE TITLE
Use Token for Each Connection [Feature Request] 

### ISSUE THREAD

**Issue by defexnicolas** [fatedier/frp#3200]
### Describe the feature request

Hey hi! I was thinking about the Token parameter on the Server.. it's possible to add that token but for each instance and no one General token?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
Write your own plugin like this https://github.com/gofrp/fp-multiuser
