### ISSUE TITLE
[Feature Request] frps域名黑白名单

### ISSUE THREAD

**Issue by cnyasin** [fatedier/frp#3201]
### Describe the feature request

frps可否增加个配置：allow_subdomains或allow_custom_domains，其功能类似allow_ports，思路也可以是取反黑名单。

目的是排除一些域名解析不被干扰，因为实际使用中我只希望一部分域名解析被frp接管，而不是所有域名解析都被frp接管。防止其他域名解析被滥用。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/dev/doc/server_plugin.md
