### ISSUE TITLE
[Feature Request] 内网域名访问问题

### ISSUE THREAD

**Issue by RookieTerry** [fatedier/frp#3203]
### Describe the feature request

如题，我家使用的是TP-LINK的路由器，在局域网内使用域名`tplogin.cn`登录路由器后台。现在我在家里的一台服务器上部署了frp客户端，请问我该怎么样从外网访问到路由器后台？浏览器把frp服务端设置为代理，在外网可以用局域网ip访问其它设备，但是不能用局域网ip访问路由器，外网pc修改hosts文件也不行。请问这个问题该如何解决？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by RookieTerry** [comment]
issues数量被我打破100了，哈哈

**Comment by RookieTerry** [comment]
拓扑图大概如下：
![Snipaste_2022-12-10_18-20-05](https://user-images.githubusercontent.com/77920425/206849901-30fac6eb-3b19-4e0d-8a57-f06100840a38.png)

**Comment by Becods** [comment]
```
# frpc.ini
[common]
server_addr = <Server Address>
server_port = 7000

[route]
type = tcp
local_ip = <Route Address>
local_port =80
remote_port = <Remote Port>
```

**Comment by RookieTerry** [comment]
> ```
> # frpc.ini
> [common]
> server_addr = <Server Address>
> server_port = 7000
> 
> [route]
> type = tcp
> local_ip = <Route Address>
> local_port =80
> remote_port = <Remote Port>
> ```

这个`route address`指的是路由器后台的局域网ip吗？

**Comment by 2Beyong** [comment]
你从内网服务器，是不是也只能用域名访问路由器的配置，不能用IP去访问?

**Comment by RookieTerry** [comment]
> 你从内网服务器，是不是也只能用域名访问路由器的配置，不能用IP去访问?

是的

**Comment by superzjg** [comment]
> > 你从内网服务器，是不是也只能用域名访问路由器的配置，不能用IP去访问?
> 
> 是的

不太可能吧，我用过tp的家用路由器，是可以用lan口ip地址访问的（内网中连接到它下面的设备即可以用lan口ip也可以用tplogin.cn访问），曾经还用frpc的https2http插件配合自己的openssl自签名证书，将ip:80转换为https从外面访问进来。

**Comment by RookieTerry** [comment]
> > > 你从内网服务器，是不是也只能用域名访问路由器的配置，不能用IP去访问?
> > 
> > 
> > 是的
> 
> 不太可能吧，我用过tp的家用路由器，是可以用lan口ip地址访问的（内网中连接到它下面的设备即可以用lan口ip也可以用tplogin.cn访问），曾经还用frpc的https2http插件配合自己的openssl自签名证书，将ip:80转换为https从外面访问进来。

可能是固件版本原因导致的？反正我的就是不行，可能你的tp路由器不是主路由吧，做交换机的情况下倒是有可能

**Comment by superzjg** [comment]
> > > > 你从内网服务器，是不是也只能用域名访问路由器的配置，不能用IP去访问?
> > > 
> > > 
> > > 是的
> > 
> > 
> > 不太可能吧，我用过tp的家用路由器，是可以用lan口ip地址访问的（内网中连接到它下面的设备即可以用lan口ip也可以用tplogin.cn访问），曾经还用frpc的https2http插件配合自己的openssl自签名证书，将ip:80转换为https从外面访问进来。
> 
> 可能是固件版本原因导致的？反正我的就是不行，可能你的tp路由器不是主路由吧，做交换机的情况下倒是有可能

哦，明白了。记得好像是有线中继模式，跟交换机差不多......刚刚问了懂路由器的大哥，针对TP家用路由器他跟我说了3点：
1、内网接在路由器下的设备即可以ip访问也可以tplogin.cn访问，非常地肯定。
2、固件禁止从wan口访问管理页面（除非很老的型号提供了选项可以开启，新的都不行），所以**不能用frp打开**；
3、大部分型号默认开启ipv6防火墙，无法从外访问内网，少部分型号可以找客服要关闭ipv6防火墙的固件。

**Comment by RookieTerry** [comment]
> > > > > 你从内网服务器，是不是也只能用域名访问路由器的配置，不能用IP去访问?
> > > > 
> > > > 
> > > > 是的
> > > 
> > > 
> > > 不太可能吧，我用过tp的家用路由器，是可以用lan口ip地址访问的（内网中连接到它下面的设备即可以用lan口ip也可以用tplogin.cn访问），曾经还用frpc的https2http插件配合自己的openssl自签名证书，将ip:80转换为https从外面访问进来。
> > 
> > 
> > 可能是固件版本原因导致的？反正我的就是不行，可能你的tp路由器不是主路由吧，做交换机的情况下倒是有可能
> 
> 哦，明白了。记得好像是有线中继模式，跟交换机差不多......刚刚问了懂路由器的大哥，针对TP家用路由器他跟我说了3点： 1、内网接在路由器下的设备即可以ip访问也可以tplogin.cn访问，非常地肯定。 2、固件禁止从wan口访问管理页面（除非很老的型号提供了选项可以开启，新的都不行）即便把lan端口映射到wan也不行，所以**不能用frp打开** 3、大部分型号默认开启ipv6防火墙，无法从外访问内网，少部分型号可以找客服要关闭ipv6防火墙的固件。
> 
> 如一定要用frp打开，在内网可用ip打开管理页的前提下，可以尝试在内网frpc服务器上同时部署一个frps服务器，在局域网内部弄一个路由器管理员的代理，公网的frps再代理内网frps的数据...

好的，谢谢解答！那我还是放弃吧！

**Comment by superzjg** [comment]
> > > > > > 你从内网服务器，是不是也只能用域名访问路由器的配置，不能用IP去访问?
> > > > > 
> > > > > 
> > > > > 是的
> > > > 
> > > > 
> > > > 不太可能吧，我用过tp的家用路由器，是可以用lan口ip地址访问的（内网中连接到它下面的设备即可以用lan口ip也可以用tplogin.cn访问），曾经还用frpc的https2http插件配合自己的openssl自签名证书，将ip:80转换为https从外面访问进来。
> > > 
> > > 
> > > 可能是固件版本原因导致的？反正我的就是不行，可能你的tp路由器不是主路由吧，做交换机的情况下倒是有可能
> > 
> > 
> > 哦，明白了。记得好像是有线中继模式，跟交换机差不多......刚刚问了懂路由器的大哥，针对TP家用路由器他跟我说了3点： 1、内网接在路由器下的设备即可以ip访问也可以tplogin.cn访问，非常地肯定。 2、固件禁止从wan口访问管理页面（除非很老的型号提供了选项可以开启，新的都不行）即便把lan端口映射到wan也不行，所以**不能用frp打开** 3、大部分型号默认开启ipv6防火墙，无法从外访问内网，少部分型号可以找客服要关闭ipv6防火墙的固件。
> > 如一定要用frp打开，在内网可用ip打开管理页的前提下，可以尝试在内网frpc服务器上同时部署一个frps服务器，在局域网内部弄一个路由器管理员的代理，公网的frps再代理内网frps的数据...
> 
> 好的，谢谢大佬的细心解答！看来无论是tp路由还是水星路由都不能通过frp访问，那我还是放弃吧！

上述说法可能不太正确，**经测试是可以用frp的**：
目前手上没有tp零售版路由器，刚刚翻出来一个中国移动定制版的TP WMA301，接到主路由上测试了。上级主路由网段192.168.0.0/24，开了fprs服务器；WMA301的wan口自动获得ip：192.168.0.100，Lan口ip：192.168.10.1。**在连接tp的电脑上使用frpc代理192.168.10.1，外面可以正常访问**。
其他测试：
1、连接到tp路由器的手机可以使用IP地址，或域名cmcc.wifi 访问管理页
2、连接到上级路由的手机不能通过wan口ip访问tp，tp的虚拟服务器不能映射自身的lan端口。
3、连接tp路由器下的电脑的ipv6地址正常，可以上网，但是不能从外部访问电脑的web和远程桌面，确实有ipv6防火墙。

**Comment by RookieTerry** [comment]
> > > > > > > 你从内网服务器，是不是也只能用域名访问路由器的配置，不能用IP去访问?
> > > > > > 
> > > > > > 
> > > > > > 是的
> > > > > 
> > > > > 
> > > > > 不太可能吧，我用过tp的家用路由器，是可以用lan口ip地址访问的（内网中连接到它下面的设备即可以用lan口ip也可以用tplogin.cn访问），曾经还用frpc的https2http插件配合自己的openssl自签名证书，将ip:80转换为https从外面访问进来。
> > > > 
> > > > 
> > > > 可能是固件版本原因导致的？反正我的就是不行，可能你的tp路由器不是主路由吧，做交换机的情况下倒是有可能
> > > 
> > > 
> > > 哦，明白了。记得好像是有线中继模式，跟交换机差不多......刚刚问了懂路由器的大哥，针对TP家用路由器他跟我说了3点： 1、内网接在路由器下的设备即可以ip访问也可以tplogin.cn访问，非常地肯定。 2、固件禁止从wan口访问管理页面（除非很老的型号提供了选项可以开启，新的都不行）即便把lan端口映射到wan也不行，所以**不能用frp打开** 3、大部分型号默认开启ipv6防火墙，无法从外访问内网，少部分型号可以找客服要关闭ipv6防火墙的固件。
> > > 如一定要用frp打开，在内网可用ip打开管理页的前提下，可以尝试在内网frpc服务器上同时部署一个frps服务器，在局域网内部弄一个路由器管理员的代理，公网的frps再代理内网frps的数据...
> > 
> > 
> > 好的，谢谢大佬的细心解答！看来无论是tp路由还是水星路由都不能通过frp访问，那我还是放弃吧！
> 
> 上述说法可能不太正确，**经测试是可以用frp的**： 目前手上没有tp零售版路由器，刚刚翻出来一个中国移动定制版的TP WMA301，接到主路由上测试了。上级主路由网段192.168.0.0/24，开了frps服务器；WMA301的wan口自动获得ip：192.168.0.100，Lan口ip：192.168.10.1。**在连接tp的电脑上使用frpc代理192.168.10.1，外面可以正常访问**。 其他测试： 1、连接到tp路由器的手机可以使用IP地址，或域名cmcc.wifi 访问管理页 2、连接到上级路由的设备可以ping通tp的wan口ip，但不能打开tp管理页；lan口ip无法ping通；tp的虚拟服务器不能映射自身的lan端口。 3、连接tp路由器下的电脑的ipv6地址正常，可以上网，但是不能从外部访问电脑的web和远程桌面，确实有ipv6防火墙。

**上级主路由网段192.168.0.0/24，开了frps服务器**，请问frp服务端是部署在上级主路由上的吗？

**Comment by RookieTerry** [comment]
> > > > > > > > > 你从内网服务器，是不是也只能用域名访问路由器的配置，不能用IP去访问?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 是的
> > > > > > > 
> > > > > > > 
> > > > > > > 不太可能吧，我用过tp的家用路由器，是可以用lan口ip地址访问的（内网中连接到它下面的设备即可以用lan口ip也可以用tplogin.cn访问），曾经还用frpc的https2http插件配合自己的openssl自签名证书，将ip:80转换为https从外面访问进来。
> > > > > > 
> > > > > > 
> > > > > > 可能是固件版本原因导致的？反正我的就是不行，可能你的tp路由器不是主路由吧，做交换机的情况下倒是有可能
> > > > > 
> > > > > 
> > > > > 哦，明白了。记得好像是有线中继模式，跟交换机差不多......刚刚问了懂路由器的大哥，针对TP家用路由器他跟我说了3点： 1、内网接在路由器下的设备即可以ip访问也可以tplogin.cn访问，非常地肯定。 2、固件禁止从wan口访问管理页面（除非很老的型号提供了选项可以开启，新的都不行）即便把lan端口映射到wan也不行，所以**不能用frp打开** 3、大部分型号默认开启ipv6防火墙，无法从外访问内网，少部分型号可以找客服要关闭ipv6防火墙的固件。
> > > > > 如一定要用frp打开，在内网可用ip打开管理页的前提下，可以尝试在内网frpc服务器上同时部署一个frps服务器，在局域网内部弄一个路由器管理员的代理，公网的frps再代理内网frps的数据...
> > > > 
> > > > 
> > > > 好的，谢谢大佬的细心解答！看来无论是tp路由还是水星路由都不能通过frp访问，那我还是放弃吧！
> > > 
> > > 
> > > 上述说法可能不太正确，**经测试是可以用frp的**： 目前手上没有tp零售版路由器，刚刚翻出来一个中国移动定制版的TP WMA301，接到主路由上测试了。上级主路由网段192.168.0.0/24，开了frps服务器；WMA301的wan口自动获得ip：192.168.0.100，Lan口ip：192.168.10.1。**在连接tp的电脑上使用frpc代理192.168.10.1，外面可以正常访问**。 其他测试： 1、连接到tp路由器的手机可以使用IP地址，或域名cmcc.wifi 访问管理页 2、连接到上级路由的设备可以ping通tp的wan口ip，但不能打开tp管理页；lan口ip无法ping通；tp的虚拟服务器不能映射自身的lan端口。 3、连接tp路由器下的电脑的ipv6地址正常，可以上网，但是不能从外部访问电脑的web和远程桌面，确实有ipv6防火墙。
> > 
> > 
> > “**上级主路由网段192.168.0.0/24，开了frps服务器**”，请问frp服务端是部署在上级主路由上的吗？这样部署的话，外网可以访问到192.168.10.0/24网段吗？
> 
> 是的，穿透了

也就是说在没有内网穿透的前提下，外网可以直接访问192.168.0.0/24网段？

**Comment by superzjg** [comment]
> > > > > > > > > > 你从内网服务器，是不是也只能用域名访问路由器的配置，不能用IP去访问?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 是的
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 不太可能吧，我用过tp的家用路由器，是可以用lan口ip地址访问的（内网中连接到它下面的设备即可以用lan口ip也可以用tplogin.cn访问），曾经还用frpc的https2http插件配合自己的openssl自签名证书，将ip:80转换为https从外面访问进来。
> > > > > > > 
> > > > > > > 
> > > > > > > 可能是固件版本原因导致的？反正我的就是不行，可能你的tp路由器不是主路由吧，做交换机的情况下倒是有可能
> > > > > > 
> > > > > > 
> > > > > > 哦，明白了。记得好像是有线中继模式，跟交换机差不多......刚刚问了懂路由器的大哥，针对TP家用路由器他跟我说了3点： 1、内网接在路由器下的设备即可以ip访问也可以tplogin.cn访问，非常地肯定。 2、固件禁止从wan口访问管理页面（除非很老的型号提供了选项可以开启，新的都不行）即便把lan端口映射到wan也不行，所以**不能用frp打开** 3、大部分型号默认开启ipv6防火墙，无法从外访问内网，少部分型号可以找客服要关闭ipv6防火墙的固件。
> > > > > > 如一定要用frp打开，在内网可用ip打开管理页的前提下，可以尝试在内网frpc服务器上同时部署一个frps服务器，在局域网内部弄一个路由器管理员的代理，公网的frps再代理内网frps的数据...
> > > > > 
> > > > > 
> > > > > 好的，谢谢大佬的细心解答！看来无论是tp路由还是水星路由都不能通过frp访问，那我还是放弃吧！
> > > > 
> > > > 
> > > > 上述说法可能不太正确，**经测试是可以用frp的**： 目前手上没有tp零售版路由器，刚刚翻出来一个中国移动定制版的TP WMA301，接到主路由上测试了。上级主路由网段192.168.0.0/24，开了frps服务器；WMA301的wan口自动获得ip：192.168.0.100，Lan口ip：192.168.10.1。**在连接tp的电脑上使用frpc代理192.168.10.1，外面可以正常访问**。 其他测试： 1、连接到tp路由器的手机可以使用IP地址，或域名cmcc.wifi 访问管理页 2、连接到上级路由的设备可以ping通tp的wan口ip，但不能打开tp管理页；lan口ip无法ping通；tp的虚拟服务器不能映射自身的lan端口。 3、连接tp路由器下的电脑的ipv6地址正常，可以上网，但是不能从外部访问电脑的web和远程桌面，确实有ipv6防火墙。
> > > 
> > > 
> > > “**上级主路由网段192.168.0.0/24，开了frps服务器**”，请问frp服务端是部署在上级主路由上的吗？这样部署的话，外网可以访问到192.168.10.0/24网段吗？
> > 
> > 
> > 是的，穿透了
> 
> 也就是说在没有内网穿透的前提下，外网可以直接访问192.168.0.0/24网段？

没有使用frp的情况下，所说的的192.168.0.0/24网段是在我主路由下，我有公网ip可以直接通过端口映射访问。tp下的192.168.10.0/24网段下的**设备**也可以通过tp的虚拟服务器映射端口访问到上层（但tp路由器**本身**不能通过这种方式），再通过主路由映射出去。但tp可以通过frpc代理lan口192.168.10.1访问到，也就是**你最初的问题的结论是可以的**。我说的已经很清楚了吧

> > > > > > > > > > 你从内网服务器，是不是也只能用域名访问路由器的配置，不能用IP去访问?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 是的
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 不太可能吧，我用过tp的家用路由器，是可以用lan口ip地址访问的（内网中连接到它下面的设备即可以用lan口ip也可以用tplogin.cn访问），曾经还用frpc的https2http插件配合自己的openssl自签名证书，将ip:80转换为https从外面访问进来。
> > > > > > > 
> > > > > > > 
> > > > > > > 可能是固件版本原因导致的？反正我的就是不行，可能你的tp路由器不是主路由吧，做交换机的情况下倒是有可能
> > > > > > 
> > > > > > 
> > > > > > 哦，明白了。记得好像是有线中继模式，跟交换机差不多......刚刚问了懂路由器的大哥，针对TP家用路由器他跟我说了3点： 1、内网接在路由器下的设备即可以ip访问也可以tplogin.cn访问，非常地肯定。 2、固件禁止从wan口访问管理页面（除非很老的型号提供了选项可以开启，新的都不行）即便把lan端口映射到wan也不行，所以**不能用frp打开** 3、大部分型号默认开启ipv6防火墙，无法从外访问内网，少部分型号可以找客服要关闭ipv6防火墙的固件。
> > > > > > 如一定要用frp打开，在内网可用ip打开管理页的前提下，可以尝试在内网frpc服务器上同时部署一个frps服务器，在局域网内部弄一个路由器管理员的代理，公网的frps再代理内网frps的数据...
> > > > > 
> > > > > 
> > > > > 好的，谢谢大佬的细心解答！看来无论是tp路由还是水星路由都不能通过frp访问，那我还是放弃吧！
> > > > 
> > > > 
> > > > 上述说法可能不太正确，**经测试是可以用frp的**： 目前手上没有tp零售版路由器，刚刚翻出来一个中国移动定制版的TP WMA301，接到主路由上测试了。上级主路由网段192.168.0.0/24，开了frps服务器；WMA301的wan口自动获得ip：192.168.0.100，Lan口ip：192.168.10.1。**在连接tp的电脑上使用frpc代理192.168.10.1，外面可以正常访问**。 其他测试： 1、连接到tp路由器的手机可以使用IP地址，或域名cmcc.wifi 访问管理页 2、连接到上级路由的设备可以ping通tp的wan口ip，但不能打开tp管理页；lan口ip无法ping通；tp的虚拟服务器不能映射自身的lan端口。 3、连接tp路由器下的电脑的ipv6地址正常，可以上网，但是不能从外部访问电脑的web和远程桌面，确实有ipv6防火墙。
> > > 
> > > 
> > > “**上级主路由网段192.168.0.0/24，开了frps服务器**”，请问frp服务端是部署在上级主路由上的吗？这样部署的话，外网可以访问到192.168.10.0/24网段吗？
> > 
> > 
> > 是的，穿透了
> 
> 也就是说在没有内网穿透的前提下，外网可以直接访问192.168.0.0/24网段？

我不知道你的逻辑什么？结论就是tp管理页可以通过frpc代理lan口192.168.10.1访问到，跟你的frps服务器安装在哪里没有关系。。也就是**你最初的问题的结论_是可以的_**。
