### ISSUE TITLE
[Feature Request] frpc允许在第一次连接时重试连接到frps

### ISSUE THREAD

**Issue by aereobert** [fatedier/frp#3204]
### Describe the feature request

请求允许frpc在重试连接到frps超过指定次数和timeout之后才退出

这个特性对于这种情况有用：
在某些情况下frpc的机器还在启动中，尚未连接到互联网，此时frpc被服务启动，尝试dial dns server，发现host unreachable，随后frpc自动退出，导致这台frpc未能被frps发现

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
[common]
# 首次登录服务器失败后是否退出，默认true，一般设为false
login_fail_exit = false
