### ISSUE TITLE
客户端获取HTTP_X_FORWARDED_FOR并非用户的IP

### ISSUE THREAD

**Issue by flystarme** [fatedier/frp#3208]
### Bug Description

客户端获取HTTP_X_FORWARDED_FOR并非用户的IP，而是frp服务端的IP，这个是bug还是我配置不对呢
如下配置：获取HTTP_X_FORWARDED_FOR 的值为：154.42.61.45
### frpc Version

0.45

### frps Version

0.45

### System Architecture

linux/amd64

### Configurations

[common]
bind_port = 7200
vhost_http_port = 80
vhost_https_port = 443

dashboard_addr = 0.0.0.0
dashboard_port = 7800

# dashboard user and passwd for basic auth protect
dashboard_user = test
dashboard_pwd = test2234

token = iL43243421432rew

上面为服务端配置
下面为客户端配置

[common]
server_addr = 154.42.61.45
server_port = 7200
token = iL43243421432rew

[synology]
type = http
local_ip = 192.168.10.20
local_port = 80
custom_domains = www.zhngsd.me
use_encryption = true
use_compression = true

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by fatedier** [comment]
可能前面套了 nginx，连接 frps 的是本地应用
