### ISSUE TITLE
feautre not working

### ISSUE THREAD

**Issue by 7054company** [fatedier/frp#3212]
### Bug Description

A i use 
dashboard feauture by setup in frps.ini
It work well over port
But when i try to use admin ui feature it not work
It does not assign the port 
And does not work ..

Can you fix that 

### frpc Version

latest release 

### frps Version

latest release

### System Architecture

linux

### Configurations

Simple setup not complex 

### Steps to reproduce

1. nano frps.ini
2. add admin docs setup
3. now run
4. frps -c frps.ini
5. It does not assign or activate admin feature
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [X] Test and Release
- [X] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
Post your configuration.

**Comment by 7054company** [comment]
Wait i will soon response

**Comment by 7054company** [comment]
[common]                                                            
bind_addr = 0.0.0.0                                                  
bind_port = 7000                                                     
bind_udp_port = 7001                                                 
kcp_bind_port = 7000                                                 
                                                                     
                                                                     
dashboard_addr = 0.0.0.0                                             
dashboard_port = 7005                                                
dashboard_user= admin                                                
dashboard_pwd = admin                                                
enable_prometheus = true                                             
                                                                     
allow_ports = 2000-9000,4000-50000                                   
                                                                     
detailed_errors_to_client = true

**Comment by 7054company** [comment]
Bro i resolve that isssu but i have to ask how i assign random port to client fprc in ssh
