### ISSUE TITLE
important bug

### ISSUE THREAD

**Issue by 7054company** [fatedier/frp#3213]
### Bug Description

In ssh random connecting
in which the frps assign frpc a random port
The client did't get info about random remort port assign in terminal

### frpc Version

Lastest

### frps Version

Lastest

### System Architecture

linux

### Configurations

Nothing

### Logs

No

### Steps to reproduce

1. You try own
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by 7054company** [comment]
FrpC logs

[root@15-206-145-28 f]# ./frpc -c ./c.ini
2022/12/15 06:10:19 [I] [service.go:357] [73ca9508a53185fa] login to
server success, get run id [73ca9508a53185fa], server udp port [7001]
2022/12/15 06:10:19 [I] [proxy_manager.go:142] [73ca9508a53185fa] pro
xy added: [ssh_random]
2022/12/15 06:10:19 [I] [service.go:162] admin server listen on 0.0.0
.0:7004
2022/12/15 06:10:19 [I] [control.go:177] [73ca9508a53185fa] [ssh_rand
om] start proxy success



In this i connect to frps server for ssh over random port but it connect but does not show info about the remote ssh port in logs
please help

**Comment by Becods** [comment]
Check your configuration file.

**Comment by 7054company** [comment]
Ya need enhancement in feature
