### ISSUE TITLE
[Feature Request] Video recording

### ISSUE THREAD

**Issue by cedricbieder** [fatedier/frp#3215]
### Describe the feature request

Hello,

I am thinking about recording http(s) sessions on the frps server. 
Do you have already though about something? Does it seem possible? If I want to implement this, where should I start?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
Logging in your backend server.

It is not very practical to try to use frp to record https log unless your https encryption and decryption is provided by frp.

**Comment by cedricbieder** [comment]
> Logging in your backend server.
> 
> It is not very practical to try to use frp to record https log unless your https encryption and decryption is provided by frp.

In this case the encryption is provided by my frp structure.
 Recording and logging on the target server is not possible in this case.
