### ISSUE TITLE
[Feature Request] Pass client certificate subject information to plugin handler

### ISSUE THREAD

**Issue by CrazyPandar** [fatedier/frp#3221]
### Describe the feature request

With TLS client authentication, I hope the subject information, like CN, SUBJECT_ID, can be sent to the plugin handler. So I can do authentication and authorization based on the subject information.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
You should describe the details about what you want to change.

**Comment by CrazyPandar** [comment]
change the plugin HTTP request body to include FRP client's TLS  peer certificate information, for example  the "common name", "subject ID" ....

**Comment by fatedier** [comment]
It's the connection level info, not the meta info of `user`. 

I don't want to make more changes on current version. Maybe considered in v2.
