### ISSUE TITLE
Lag in video streaming

### ISSUE THREAD

**Issue by sayan-futurehook** [fatedier/frp#3223]
### Bug Description

I am trying to stream video from a RTSP camera to mobile app. I am using FRPS on AWS EC2 ubuntu and FRPC on a Raspberry pi. I am tunnelling the RTSP port from my local network to my EC2 instance ip and streaming the video, on mobile.
I am able to stream the video using FRP, but there is a lot of delay and choppy. But when I am putting local ip there is not lag and choppiness.
Is there any way to fix, or optimize the lag.

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

frps on ubuntu/amd64, frpc on raspbian/arm

### Configurations

```ini
# frps.ini
[common]
bind_port = 7000
```

```ini
# frpc.ini
[common]
server_addr = ec2InstanceIp
server_port = 7000

[ssh]
type = tcp
local_ip = 192.0.0.65
local_port = 554
remote_port = 10000
```

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
The lag is rely on your network delay between frpc and frps.

**Comment by sayan-futurehook** [comment]
> The lag is rely on your network delay between frpc and frps.

This is the speedtest on frpc
![Screenshot 2022-12-20 at 4 59 55 PM](https://user-images.githubusercontent.com/110037874/208657030-4cc33bd7-238e-42b4-871e-b77480403f82.png)

frps is in aws ec2


Is there any way to optimize?

**Comment by Becods** [comment]
Select the server area nearest to you.

Or try [xtcp](https://github.com/fatedier/frp#p2p-mode).
