### ISSUE TITLE
frpc public ip not available

### ISSUE THREAD

**Issue by Gamst123** [fatedier/frp#3226]
### Bug Description

Except for the public IP and vpn, all other IPs work with frpc without problems.

this has a problem

### frpc Version

0.46.0

### frps Version

0.46.0

### System Architecture

linux/ubuntu

### Configurations

[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 8899
token =xxxx

[tcp]
type = tcp
local_ip = 127.0.0.1
local_port = 2888
remote_port = 2888

[udp]
type = udp
local_ip = 127.0.0.1
local_port = 20041
remote_port = 20041

### Logs

● frpc.service - frp server
     Loaded: loaded (/etc/systemd/system/frpc.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-12-22 13:07:43 UTC; 10s ago
    Process: 2951 ExecStart=/usr/local/frpc/frpc -c /usr/local/frpc/frpc.ini (code=exited, status=1/FAILURE)
   Main PID: 2951 (code=exited, status=1/FAILURE)

Dec 22 13:07:41  systemd[1]: Started frp server.
Dec 22 13:07:43 frpc[2951]: 2022/12/22 13:07:43 [W] [service.go:132] login to server failed: dial tcp xxx.xxx.xxx.xxx:8899: connect: connection refused
Dec 22 13:07:43 frpc[2951]: dial tcp xxx.xxx.xxx.xxx:8899: connect: connection refused
Dec 22 13:07:43 systemd[1]: frpc.service: Main process exited, code=exited, status=1/FAILURE
Dec 22 13:07:43 systemd[1]: frpc.service: Failed with result 'exit-code'.

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by Becods** [comment]
`tcping xxx.xxx.xxx.xxx:8899`

**Comment by Gamst123** [comment]
~$ telnet xxx.xxx.xxx.xxx 8899
Trying xxx.xxx.xxx.xxx ...
telnet: Unable to connect to remote host: Connection refused

**Comment by Gamst123** [comment]
seq 0: tcp response from xxx.xxx.xxx.xxx [closed]  2028.898 ms
seq 1: tcp response from xxx.xxx.xxx.xxx [closed]  2035.935 ms
seq 2: tcp response from xxx.xxx.xxx.xxx [closed]  2035.283 ms
seq 3: tcp response from xxx.xxx.xxx.xxx [closed]  2029.924 ms
seq 4: tcp response from xxx.xxx.xxx.xxx [closed]  2026.038 ms
seq 5: tcp response from xxx.xxx.xxx.xxx [closed]  2032.468 ms
seq 6: tcp response from xxx.xxx.xxx.xxx [closed]  2030.728 ms
seq 7: tcp response from xxx.xxx.xxx.xxx [closed]  2027.501 ms
seq 8: tcp response from xxx.xxx.xxx.xxx [closed]  2032.387 ms
seq 9: tcp response from xxx.xxx.xxx.xxx [closed]  2029.970 ms
seq 10: tcp response from xxx.xxx.xxx.xxx [closed]  2032.952 ms
seq 11: tcp response from xxx.xxx.xxx.xxx [closed]  2033.465 ms
seq 12: tcp response from xxx.xxx.xxx.xxx [closed]  2033.510 ms
seq 13: tcp response from xxx.xxx.xxx.xxx [closed]  2032.958 ms
seq 14: tcp response from xxx.xxx.xxx.xxx [closed]  2028.018 ms

**Comment by Becods** [comment]
Server connection problems.

Problems not caused by frp.
