### ISSUE TITLE
STCP not working

### ISSUE THREAD

**Issue by Setsuna-Kitahara** [fatedier/frp#3228]
### Bug Description

如日志所示，无法联通
两边都能连上FRP服务端，STCP服务端的设置在FRP服务端这里是看得到的，STCP客户端有其他TCP再跑，也跑得动。

### frpc Version

0.46

### frps Version

0.46

### System Architecture

Client: Linux/arm64 Server: Linux/amd64

### Configurations

client

[NAME-Client]
type = stcp
role = visitor
sk = ***
server = NAME
bind_addr = 172.17.0.1 # This Client's IP
bind_port = 20001

server

[NAME]
type = stcp
sk = ***
local_port = 10050
use_encryption = true
use_compression = true

### Logs

2022/12/25 06:33:39 [D] [visitor.go:118] [8562aa28541e628d] [NAME-Client] get a new stcp user connection
2022/12/25 06:33:39 [W] [visitor.go:149] [8562aa28541e628d] [NAME-Client] start new visitor connection error: custom listener for [] doesn't exist

### Steps to reproduce

telnet 172.17.0.1 20001

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
看上去server没有指明local_ip =

**Comment by Setsuna-Kitahara** [comment]
> 看上去server没有指明local_ip = ？ client中server_name = NAME是标准写法

其实就是127.0.0.1
也尝试过写过，但是问题依旧

**Comment by superzjg** [comment]
> 

我不是提示你 client中server_name = NAME才是标准写法吗？看来你没改，还说问题依旧。
实际上我刚刚把server_name = NAME改成server = NAME以后，跟你报一样错：
custom listener for [] doesn't exist
下次注意仔细点！

**Comment by Setsuna-Kitahara** [comment]
> > 
> 
> 我不是提示你 client中server_name = NAME才是标准写法吗？看来你没改，还说问题依旧。 实际上我刚刚把server_name = NAME改成server = NAME以后，跟你报一样错： custom listener for [] doesn't exist 下次注意仔细点！

好吧，是没仔细看文件，这代码是0.37版本抄下来的，但是当年好像就是server_name……是当年脑子烧糊涂了吧……
