### ISSUE TITLE
frp使用http2https出现“no route found”报错

### ISSUE THREAD

**Issue by hydrogenoxide-user** [fatedier/frp#3231]
### Bug Description

配置之前能正常运行，近期突然出现客户端和服务端启动都正常，但访问https时出现“The page you requested was not found”页面，服务端报错no route found。

### frpc Version

0.46.0

### frps Version

0.46.0

### System Architecture

linux/amd64

### Configurations

[common]
server_addr = 103.158.36.24
server_port = 7000
token = 114514
[opi-ssh]
type = tcp
local_ip = 192.168.80.150
local_port = 22
remote_port = 6000
[blog]
type = https
custom_domains = hydrogenoxide.eu.org
proxy_protocol_version = v2
plugin = https2http
plugin_local_addr = 192.168.80.160:443

# HTTPS 证书相关的配置
plugin_crt_path = /frpc/server.crt
plugin_key_path = /frpc/server.key
plugin_host_header_rewrite = 192.168.80.160
plugin_header_X-From-Where = frp

### Logs

● frps.service - frp server
     Loaded: loaded (/etc/systemd/system/frps.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-12-29 09:57:46 UTC; 4h 41min ago
   Main PID: 55795 (frps)
      Tasks: 4 (limit: 527)
     Memory: 16.6M
     CGroup: /system.slice/frps.service
             └─55795 /frps/frps -c /frps/frps.ini

Dec 29 14:36:37 C20221229136683 frps[55795]: 2022/12/29 14:36:37 [W] [http.go:119] do http proxy request [host: hydrogenoxide.eu.org] error: no route found: hydrogenoxide.eu.org / 
Dec 29 14:36:42 C20221229136683 frps[55795]: 2022/12/29 14:36:42 [I] [control.go:306] [1a54f1259099e96f] control writer is closing
Dec 29 14:36:42 C20221229136683 frps[55795]: 2022/12/29 14:36:42 [I] [proxy.go:88] [1a54f1259099e96f] [opi-ssh] proxy closing
Dec 29 14:36:42 C20221229136683 frps[55795]: 2022/12/29 14:36:42 [W] [proxy.go:176] [1a54f1259099e96f] [opi-ssh] listener is closed: accept tcp [::]:6000: use of closed network connection
Dec 29 14:36:42 C20221229136683 frps[55795]: 2022/12/29 14:36:42 [I] [proxy.go:88] [1a54f1259099e96f] [blog] proxy closing
Dec 29 14:36:42 C20221229136683 frps[55795]: 2022/12/29 14:36:42 [I] [control.go:395] [1a54f1259099e96f] client exit success
Dec 29 14:36:42 C20221229136683 frps[55795]: 2022/12/29 14:36:42 [W] [proxy.go:176] [1a54f1259099e96f] [blog] listener is closed: Listener closed
Dec 29 14:38:38 C20221229136683 frps[55795]: 2022/12/29 14:38:38 [W] [http.go:119] do http proxy request [host: hydrogenoxide.eu.org] error: no route found: hydrogenoxide.eu.org / 
Dec 29 14:38:39 C20221229136683 frps[55795]: 2022/12/29 14:38:39 [W] [http.go:119] do http proxy request [host: hydrogenoxide.eu.org] error: no route found: hydrogenoxide.eu.org /favicon.ico 
Dec 29 14:38:59 C20221229136683 frps[55795]: 2022/12/29 14:38:59 [W] [http.go:119] do http proxy request [host: hydrogenoxide.eu.org] error: no route found: hydrogenoxide.eu.org / 

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by superzjg** [comment]
应该是域名解析的问题，与frp无关

**Comment by hydrogenoxide-user** [comment]
服务端和客户端配置无误，不是防火墙的问题，域名在cloudflare解析到映射服务器。
日志如下，访问url出现报错：
● frps.service - frp server
   Loaded: loaded (/etc/systemd/system/frps.service; enabled; vendor preset: disabled)
   Active: active (running) since 六 2022-12-31 01:57:28 CST; 7min ago
 Main PID: 17354 (frps)
   CGroup: /system.slice/frps.service
           └─17354 /frps/frps -c /frps/frps.ini

12月 31 02:05:08 C20221229136683 frps[17354]: 2022/12/31 02:05:08 [I] [control.go:395] [17d1cad4fa325e81] client exit success
12月 31 02:05:08 C20221229136683 frps[17354]: 2022/12/31 02:05:08 [W] [proxy.go:176] [17d1cad4fa325e81] [blog] listener is closed: Listener closed
12月 31 02:05:10 C20221229136683 frps[17354]: 2022/12/31 02:05:10 [I] [service.go:500] [0522f91207f192e2] client login info: ip [125.81.47.249:62165] version [0.45.0] hostname [] os [linux] arch [arm]
12月 31 02:05:10 C20221229136683 frps[17354]: 2022/12/31 02:05:10 [I] [tcp.go:64] [0522f91207f192e2] [opi-ssh] tcp proxy listen port [6000]
12月 31 02:05:10 C20221229136683 frps[17354]: 2022/12/31 02:05:10 [I] [control.go:464] [0522f91207f192e2] new proxy [opi-ssh] type [tcp] success
12月 31 02:05:10 C20221229136683 frps[17354]: 2022/12/31 02:05:10 [I] [https.go:51] [0522f91207f192e2] [blog] https proxy listen for host [hydrogenoxide.eu.org]
12月 31 02:05:10 C20221229136683 frps[17354]: 2022/12/31 02:05:10 [I] [control.go:464] [0522f91207f192e2] new proxy [blog] type [https] success
12月 31 02:05:15 C20221229136683 frps[17354]: 2022/12/31 02:05:15 [W] [http.go:119] do http proxy request [host: hydrogenoxide.eu.org] error: no route found: hydrogenoxide.eu.org / 
12月 31 02:05:16 C20221229136683 frps[17354]: 2022/12/31 02:05:16 [W] [http.go:119] do http proxy request [host: hydrogenoxide.eu.org] error: no route found: hydrogenoxide.eu.org /favicon.ico 
12月 31 02:05:17 C20221229136683 frps[17354]: 2022/12/31 02:05:17 [W] [http.go:119] do http proxy request [host: hydrogenoxide.eu.org] error: no route found: hydrogenoxide.eu.org /

**Comment by itsKV** [comment]
Have you any solution to the issue? 

I am facing same issue. I can confirm that domain dns configuration is correct as `random.sub.domain.tld` is replying frp's default 404 error while accessing random proxy. Otherwise, that would trigger my web-server's default 404 error file. I am getting following error in frps log file

`[httputil/reverseproxy.go:486] do http proxy request [host: random.sub.domain.tld:8080] error: no route found: random.sub.domain.tld:8080 /`
