### ISSUE TITLE
NewProxy类型插件未上报自动生成的remote_port

### ISSUE THREAD

**Issue by zhangboqi** [fatedier/frp#3232]
### Bug Description

当frpc代理配置remote_port=0时,即意味着由frps自动分配端口，在这种情况下NewProxy类型插件却未上报remote_port值

### frpc Version

0.46.0

### frps Version

0.46.0

### System Architecture

linux/amd64

### Configurations

**frpc.ini**
```
[common]
server_addr = 127.0.0.1
server_port = 7000
user=sn000001
[eppbox]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 0
meta_key=aaa
```
**frps.ini**
```
[common]
bind_port = 7000

[plugin.epp-notify]
addr = 127.0.0.1:8081
path = /handler
ops = NewProxy,CloseProxy,NewWorkConn,NewUserConn
```

### Logs

**这是插件收到的消息体：**
```
{
"version":"0.1.0",
"op":"NewProxy",
"content":{
"user":{"user":"sn000001","metas":null,"run_id":"03fd2277703bcb59"},
"proxy_name":"sn000001.eppbox",
"proxy_type":"tcp",
"metas":{"key":"aaa"}
}
}
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by zhangboqi** [comment]
不知道这个应该是bug,还是特性
但是希望能提供此类支持

**Comment by fatedier** [comment]
只有当 NewProxy 消息处理成功之后，才会去监听端口，才能明确监听在哪个端口。
如果需要知道 proxy 监听的端口，可以通过 api 接口去获取。

**Comment by zhangboqi** [comment]
明白了。我理解的有问题了。

**Comment by zhangboqi** [comment]
我并未在官方文档中查找到frps api服务的相关文档，可否提供下相关文档说明地址？

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/dev/server/dashboard_api.go
原来是给前端用的，没有明确暴露出来，直接看代码吧

**Comment by zhangboqi** [comment]
哈哈。可以
