### ISSUE TITLE
请问，怎么才能获取搭建OIDC服务的完整说明或示例？

### ISSUE THREAD

**Issue by jackwang-wangcb** [fatedier/frp#3233]
### Describe the feature request

作者，您好
想启用frp的OIDC认证，但是通过目前的文档无法获得足够的支持
请问，我通过什么样的途经才能获取搭建OIDC服务的完整说明或示例？
付费之类的文档，咨询都可以，谢谢

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
[OIDC搭建](https://lmstfy.net/?q=T0lEQ+aQreW7ug==)

**Comment by jackwang-wangcb** [comment]
> [OIDC搭建](https://lmstfy.net/?q=T0lEQ+aQreW7ug==)

你这回答，绝了
如果能在baidu google找到答案，我也不会跑到这里来发帖啊

我已经用Spring Authorization Server 1.0 搭建了服务，并用客户端实验了，也好用
可仍然无法 与FRP对接啊
