### ISSUE TITLE
frp单线程速度只有2mbps

### ISSUE THREAD

**Issue by qwe-one** [fatedier/frp#3234]
### Bug Description

多线程没有问题，可以跑满服务器速度。单线程无论是web服务、远程桌面还是其他服务，速度都限制的死死的只有2mbps，一点不多一点不少，tcp mux也已经关了还是这样

### frpc Version

0.46.0

### frps Version

0.46.0

### System Architecture

Linux/amd64

### Configurations

[common]
server_addr = xxxx.xxxx
server_port = 7000
protocol=tcp
dns_server=1.1.1.1
tcp_mux=false

[rdp]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 3389
use_encryption = false
use_compression = false

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
尝试客服直连是否还存在这样的问题

**Comment by qwe-one** [comment]
> 尝试客服直连是否还存在这样的问题

直连没有任何问题

**Comment by yyingc** [comment]
[rdp-tcp]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 3389
use_encryption = false
use_compression = false
[rdp_udp]
type = udp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 3389
use_encryption = false
use_compression = false

建议同时开启udp
