### ISSUE TITLE
0.46版FRP，参数oidc_audience如何配置

### ISSUE THREAD

**Issue by jackwang-wangcb** [fatedier/frp#3236]
### Describe the feature request

0.46版本中
当设置
authentication_method = oidc
需要配置
oidc_audience =

在frps_full.ini 中
有这样一句
oidc_audience specifies the audience OIDC tokens should contain when validated.
本人英文不好，没太明白这句的意思
哪位大神给说下当 authentication_method = oidc时
参数 oidc_audience 该怎样配置
谢谢了

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
这里有一个教程，不过我还没来得及试：
https://blog.csdn.net/ly1358152944/article/details/126712406

**Comment by jackwang-wangcb** [comment]
> 这里有一个教程，不过我还没来得及试： https://blog.csdn.net/ly1358152944/article/details/126712406

这个教程我也看了，版本不太一致
不过我自己用spring 搭建了一个oidc服务，能用

**Comment by aldington-david** [comment]
> > 这里有一个教程，不过我还没来得及试： https://blog.csdn.net/ly1358152944/article/details/126712406
> 
> 这个教程我也看了，版本不太一致 不过我自己用spring 搭建了一个oidc服务，能用

你好能请教一下怎么搭建的吗，有没有相关的教程

**Comment by jackwang-wangcb** [comment]
哪有什么教程啊，都是找spring的官方文档一点一点尝试。
frpc.ini配置
[common]
server_addr = 3x.xx.1xx.xx
server_port = 7000
authentication_method = oidc
authenticate_heartbeats = true
authenticate_new_work_conns = false
oidc_client_id = clientid（自定义的）
oidc_client_secret =密钥（自定义的）
oidc_audience = 
oidc_scope = openid
oidc_token_endpoint_url =http://xxx.xxx.xx/oauth2/token（spring项目地址）
[xxx]
type = http
local_port = 80
subdomain = xxx

spring 配置 参考附件







***@***.***
 
发件人： aldington.david
发送时间： 2023-08-01 18:06
收件人： fatedier/frp
抄送： jackwang-wangcb; State change
主题： Re: [fatedier/frp] 0.46版FRP，参数oidc_audience如何配置 (Issue #3236)
这里有一个教程，不过我还没来得及试： https://blog.csdn.net/ly1358152944/article/details/126712406
这个教程我也看了，版本不太一致 不过我自己用spring 搭建了一个oidc服务，能用
你好能请教一下怎么搭建的吗，有没有相关的教程

**Comment by jackwang-wangcb** [comment]
> > > 这里有一个教程，不过我还没来得及试： https://blog.csdn.net/ly1358152944/article/details/126712406
> > 
> > 
> > 这个教程我也看了，版本不太一致 不过我自己用spring 搭建了一个oidc服务，能用
> 
> 你好能请教一下怎么搭建的吗，有没有相关的教程.还有问一下你的SCOPES参数是怎么填的，我看frps的oidc设置里只有oidc_issuer跟oidc_audience

给个邮箱，我把关键配置给你

**Comment by aldington-david** [comment]
> > > > 这里有一个教程，不过我还没来得及试： https://blog.csdn.net/ly1358152944/article/details/126712406
> > > 
> > > 
> > > 这个教程我也看了，版本不太一致 不过我自己用spring 搭建了一个oidc服务，能用
> > 
> > 
> > 你好能请教一下怎么搭建的吗，有没有相关的教程.还有问一下你的SCOPES参数是怎么填的，我看frps的oidc设置里只有oidc_issuer跟oidc_audience
> 
> 给个邮箱，我把关键配置给你

感谢，麻烦发到ken_neth@live.cn。我自己用django整了个，老是SCOPES参数验证不了
