### ISSUE TITLE
frp0.46版，启用OIDC，出现 clientId混乱问题

### ISSUE THREAD

**Issue by jackwang-wangcb** [fatedier/frp#3237]
### Bug Description

frp0.46版启用OIDC，服务端配置如下
bind_port = 7000
vhost_http_port = 80
subdomain_host =frpserver.com
max_pool_count = 50
authentication_method = oidc
oidc_issuer = http://192.168.78.124:8080
oidc_audience = http://192.168.78.124:8080/default
authenticate_new_work_conns = true

客户端配置1：
[common]
#忽略其它配置
authentication_method = oidc
oidc_client_id = zzming
oidc_client_secret = secret2
oidc_audience = http://192.168.78.124:8080/default
oidc_scope = openid
oidc_token_endpoint_url =http://192.168.78.124:8080/oauth2/token
authenticate_new_work_conns = true
[zzming]
type = http
local_port = 18080
subdomain = zzming
客户端配置2：
[common]
#忽略其它配置
authentication_method = oidc
oidc_client_id = taolin
oidc_client_secret = secret1
oidc_audience = http://192.168.78.124:8080/default
oidc_scope = openid
oidc_token_endpoint_url =http://192.168.78.124:8080/oauth2/token
authenticate_new_work_conns = true
[taolin]
type = http
local_port = 6688
subdomain = taolin

按此配置 运行一段时间后，出现如下错误
2023/01/03 17:04:59 [E] [control.go:155] [b88169377d0c25cd] StartWorkConn contai
ns error: received different OIDC subject in login and ping. original subject: t
aolin, new subject: zzming

请问 这是什么原因

### frpc Version

0.46

### frps Version

0.46

### System Architecture

win10

### Configurations

服务端配置如下
bind_port = 7000
vhost_http_port = 80
subdomain_host =frpserver.com
max_pool_count = 50
authentication_method = oidc
oidc_issuer = http://192.168.78.124:8080
oidc_audience = http://192.168.78.124:8080/default
authenticate_new_work_conns = true

客户端配置1：
[common]
#忽略其它配置
authentication_method = oidc
oidc_client_id = zzming
oidc_client_secret = secret2
oidc_audience = http://192.168.78.124:8080/default
oidc_scope = openid
oidc_token_endpoint_url =http://192.168.78.124:8080/oauth2/token
authenticate_new_work_conns = true
[zzming]
type = http
local_port = 18080
subdomain = zzming
客户端配置2：
[common]
#忽略其它配置
authentication_method = oidc
oidc_client_id = taolin
oidc_client_secret = secret1
oidc_audience = http://192.168.78.124:8080/default
oidc_scope = openid
oidc_token_endpoint_url =http://192.168.78.124:8080/oauth2/token
authenticate_new_work_conns = true
[taolin]
type = http
local_port = 6688
subdomain = taolin

### Logs

aolin, new subject: zzming
2023/01/03 17:03:42 [D] [control.go:286] [b88169377d0c25cd] send heartbeat to se
rver
2023/01/03 17:03:42 [D] [control.go:317] [b88169377d0c25cd] receive heartbeat fr
om server
2023/01/03 17:04:12 [D] [control.go:286] [b88169377d0c25cd] send heartbeat to se
rver
2023/01/03 17:04:12 [D] [control.go:317] [b88169377d0c25cd] receive heartbeat fr
om server
2023/01/03 17:04:15 [D] [proxy.go:819] [b88169377d0c25cd] [zzming] join connecti
ons closed
2023/01/03 17:04:42 [D] [control.go:286] [b88169377d0c25cd] send heartbeat to se
rver
2023/01/03 17:04:42 [D] [control.go:317] [b88169377d0c25cd] receive heartbeat fr
om server
_**2023/01/03 17:04:59 [E] [control.go:155] [b88169377d0c25cd] StartWorkConn contai
ns error: received different OIDC subject in login and ping. original subject: t
aolin, new subject: zzming**_
2023/01/03 17:05:12 [D] [control.go:286] [b88169377d0c25cd] send heartbeat to se
rver
2023/01/03 17:05:12 [D] [control.go:317] [b88169377d0c25cd] receive heartbeat fr
om server
2023/01/03 17:05:42 [D] [control.go:286] [b88169377d0c25cd] send heartbeat to se

### Steps to reproduce

1. 按配置启动
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Nitsuya** [comment]
我用spring写了一个也是这种情况. 老哥解决了吗?
