### ISSUE TITLE
[Feature Request]  FRP 隧道 默认的数据加密方式

### ISSUE THREAD

**Issue by sshuangliu** [fatedier/frp#3238]
### Describe the feature request

当FRPS--FRPC 建立隧道时，如果上面承载的是一些明文流量，例如http或者某些tcp.udp流量，隧道本身是否有默认的加密方式？
多谢

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
[#Encryption and Compression](https://github.com/fatedier/frp#encryption-and-compression)

**Comment by superzjg** [comment]
关于加密的中文版说明：
[https://gofrp.org/docs/features/common/network/](url)
