### ISSUE TITLE
how expose local website http to https in frp server

### ISSUE THREAD

**Issue by thomazr** [fatedier/frp#3241]
### Bug Description

Hello guys! I'm trying to expose a local http site to a frp server using https but I'm not succeeding. my frpc.ini looks like this:
[common]
server_addr = 137.184.181.209
server_port = 7000

[https]
type = https
local_port = 8080
custom_domains = api.tiggomark.com.br

and my frps.ini (on the server) looks like this:
_[common]
bind_port = 7000
vhost_http_port = 9888
vhost_https_port = 7001_

However, even having an ssl certificate installed for the api.tiggomark.com.br domain, when I try to access the address https://api.tiggomark.com.br:7001 I cannot access the address (certificate error), using the tables settings for http, works normally. Can anyone help me? Thanks!

### frpc Version

0.46.0

### frps Version

0.46.0

### System Architecture

linux/amd64

### Configurations

Sever:
[common]
bind_port = 7000
vhost_http_port = 9888
vhost_https_port = 7001

Client:
[common]
server_addr = 137.184.181.209
server_port = 7000

[https]
type = https
local_port = 8080
custom_domains = api.tiggomark.com.br

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
[Enable HTTPS for local HTTP(S) service](https://github.com/fatedier/frp#enable-https-for-local-https-service)
