### ISSUE TITLE
[Feature Request] enforce basic auth for HTTPS web services when http_user and http_pwd are set

### ISSUE THREAD

**Issue by shabakett** [fatedier/frp#3242]
enforce basic auth for https web services when http_user and http_pwd are set

**Comment by Becods** [comment]
[#Require HTTP Basic Auth (Password) for Web Services](https://github.com/fatedier/frp#require-http-basic-auth-password-for-web-services)

**Comment by shabakett** [comment]
it mentions `It can only be enabled when proxy type is http`
why not for https?

**Comment by Becods** [comment]
> it mentions `It can only be enabled when proxy type is http` 
> why not for `https`?

http authentication requires a special header, https encrypts this and frp cannot decrypt it.
