### ISSUE TITLE
[Feature Request] 关于Dashboard统计数据的建议

### ISSUE THREAD

**Issue by Knownniu001** [fatedier/frp#3249]
### Describe the feature request

目前Dashboard的统计数据是直接存储在内存中，并没有存储在磁盘
每次重启frps后统计数据会清零
建议作者考虑存储在磁盘中，并提供可修改的保存数据的时间，使其重启后统计数据从重启前的数据继续统计，方便用户看见整体数据
此issue在2016年已经被提过了，目前已经被关闭，但是我身边有很多使用frp的用户都有这个需求，希望作者能再次考虑一下
感谢

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
持久化需求建议使用 prometheus 采集。

https://github.com/fatedier/frp/blob/dev/conf/frps_full.ini#L60
