### ISSUE TITLE
frpc端连接安全问题

### ISSUE THREAD

**Issue by Codecaver** [fatedier/frp#3253]
### Bug Description

请教一下，怎么设置frpc鉴权。例如下面的配置
`frps.ini`
```
[common]
bind_port = 7000

```
`frpc.ini`

```
[common]
server_addr = x.x.x.x
server_port = 7000  
 
[adb] 
type = tcp 
local_ip = 127.0.0.1 # 手机本地地址
local_port = 5555 # 手机调试端口
remote_port = 8555
```
是不是所有用户只要知道` 8555` 这个端口，就都能通过adb连接上我的设备。我应该怎么配置访问权限呢

### frpc Version

0.46.1

### frps Version

0.46.1

### System Architecture

linux/arm64

### Configurations

如` description` 所示

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [X] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Codecaver** [comment]
看blog介绍，认证好像只用在frps和frpc之间，没有对连接的用户进行认证

**Comment by fatedier** [comment]
1. 通过 stcp 暴露，想连接的话需要访问端也部署 frpc 且鉴权通过才行。
2. 基于服务端插件，开发一些类似防火墙的能力，比如限制指定 IP 可访问。

**Comment by Codecaver** [comment]
嗯嗯，看了blog中的stcp例子，有一个疑问，frpc与frps建立连接的时候是不是就不用在frps端监听新端口了，当用户端 配置frpc去连接 客户端frpc的时候，才在frps设置需要监听的端口？这样的话，我是不是可以根据不同名字，配置n多个客户端frpc，当用户端frpc需要去连接 客户端frpc的时候，修改自己配置的server_name，就可以实现连接不同的客户端了？

**Comment by superzjg** [comment]
> 谢谢解惑，看了blog中的stcp例子，还有两个疑问。
> 
> 1. frpc与frps建立连接的时候是不是就不用在frps端监听新端口了（意味如果配置了n多个客户端frpc，都可以在frps是看到已连接的客户端？），当访问端 配置frpc去连接 客户端frpc的时候，才在frps设置需要监听的端口？
> 2. 这样的话，我是不是可以根据不同名字，配置n多个客户端frpc，当用户端frpc需要去连接 客户端frpc的时候，修改自己配置的server_name，就可以实现连接不同的客户端了？

1、stcp没有远程端口，只有bind_port。
2、还可以使用参数 user = name1，这样进行用户分类，server_name就变成name1.代理名称
