### ISSUE TITLE
https2http

### ISSUE THREAD

**Issue by bouyeijiang** [fatedier/frp#3258]
### Bug Description

使用frp的http代理转发geoserver正常使用，但是换成https后遇到一些问题,浏览网页字页面掉转后提示连接被重置，不知道是是什么原因导致！

### frpc Version

0.45.0

### frps Version

0.45.0

### System Architecture

win7/ubuntu20

### Configurations

frpc的https配置如下：
[web]
type=https
local_ip=127.0.0.1
local_port=8080

custom_domains=m.gzgdhx.cn
plugin=https2http
plugin_local_addr=127.0.0.1:8080
plugin_crt_path=cer/m.gzgdhx,cn.crt
plugin_key_path=cer/m.gzghdx.cn.key

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/214100499-87a701e5-8296-46ae-a77a-177cdbf44663.png)

**Comment by bouyeijiang** [comment]
谢谢您的来信！我会及时查阅的

**Comment by bouyeijiang** [comment]
i have found the question and solved it.
