### ISSUE TITLE
[Feature Request] 用https访问不能链接或未配置的域名时，不能跳转到自定义的404错误页面。

### ISSUE THREAD

**Issue by vpei** [fatedier/frp#3259]
### Describe the feature request

用https访问不能链接或未配置的域名时，不能跳转到自定义的404错误页面。提示此站点的连接不安全，ERR_SSL_PROTOCOL_ERROR。

### Describe alternatives you've considered

用https访问不能链接或未配置的域名时，不能跳转到自定义的404错误页面。提示此站点的连接不安全，ERR_SSL_PROTOCOL_ERROR。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
**请选择正确的分类**
![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/214100160-f4b5de87-16fd-4588-9b92-3d8141a78af9.png)

frp默认的404界面不适用于https

**Comment by nkxingxh** [comment]
你要知道https是需要加密证书的。frps不可能为未绑定的域名生成一张受信任的证书。

**Comment by vpei** [comment]
> 你要知道https是需要加密证书的。frps不可能为未绑定的域名生成一张受信任的证书。

不能指定到错误的指定的提示页吗？

**Comment by nkxingxh** [comment]
> > 你要知道https是需要加密证书的。frps不可能为未绑定的域名生成一张受信任的证书。
> 
> 不能指定到错误的指定的提示页吗？

建议你先了解一下 HTTPS 的基本原理。HTTPS 需要证书与对应的密钥进行加密。
而frps本身无签发证书的能力，故不能对未绑定的域名进行响应。

即使frps有自签证书，也会被浏览器标为不信任。

所以，答案是显然的——不能。

**Comment by vpei** [comment]
> > > 你要知道https是需要加密证书的。frps不可能为未绑定的域名生成一张受信任的证书。
> > 
> > 
> > 不能指定到错误的指定的提示页吗？
> 
> 建议你先了解一下 HTTPS 的基本原理。HTTPS 需要证书与对应的密钥进行加密。 而frps本身无签发证书的能力，故不能对未绑定的域名进行响应。
> 
> 即使frps有自签证书，也会被浏览器标为不信任。
> 
> 所以，答案是显然的——不能。


可不可以在那种不信任的错误网站页面上，显示错误的提示内容（或跳转到新的网站）？

**Comment by nkxingxh** [comment]
> > > > 你要知道https是需要加密证书的。frps不可能为未绑定的域名生成一张受信任的证书。
> > > 
> > > 
> > > 不能指定到错误的指定的提示页吗？
> > 
> > 
> > 建议你先了解一下 HTTPS 的基本原理。HTTPS 需要证书与对应的密钥进行加密。 而frps本身无签发证书的能力，故不能对未绑定的域名进行响应。
> > 即使frps有自签证书，也会被浏览器标为不信任。
> > 所以，答案是显然的——不能。
> 
> 可不可以在那种不信任的错误网站页面上，显示错误的提示内容（或跳转到新的网站）？

不能。

**Comment by FrancisChuh** [comment]
那这个ERR_SSL_PROTOCOL_ERROR问题是不是就不能解决呢？也就意味着不能用 https ?
