### ISSUE TITLE
0.10.0 arm 版会报 Illegal instruction

### ISSUE THREAD

**Issue by fengqi** [fatedier/frp#326]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
Illegal instruction

**What operating system and processor architecture are you using (`go env`)?**
armv7l 
> -sh: go: not found

**Steps to reproduce the issue:**
1. ./frpc --version
2. output: Illegal instruction

**Describe the results you received:**
output: Illegal instruction

**Describe the results you expected:**
0.10.0

**Additional information you deem important (e.g. issue happens only occasionally):**
0.9.3 正常, 另外 arm 0.9.3 查看版本只能使用 --version 使用 -v 会提示 open ./frpc.ini: no such file or directory

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
请按照模版提交问题。

**Comment by fatedier** [comment]
换了一个系统编译，你可以重新下载运行尝试下，或者自行编译后运行。

**Comment by fatedier** [comment]
-v 不能正常输出的错误之后会修复。

**Comment by fengqi** [comment]
运行正常了, -v 也正常了
