### ISSUE TITLE
FRP遇到大量请求时客户方崩溃

### ISSUE THREAD

**Issue by KleeLoveLife** [fatedier/frp#3263]
### Bug Description

使用FRP转发Minecraft时遇到压测时FRPC崩溃

### frpc Version

0.46.1

### frps Version

0.46.1

### System Architecture

linux/amd64 -> windows/amd64

### Configurations

[common]
server_addr = 114514
server_port = 7000
token = 114514

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 25565
remote_port = 60009
proxy_protocol_version = v2
# console or real logFile path like ./frpc.log
log_file = ./frpc.log

# trace, debug, info, warn, error
log_level = info

log_max_days = 3

### Logs

![)`1 UF5MTT5{OBY__ JK` C](https://user-images.githubusercontent.com/86773633/213439636-f3ad394d-e1b2-4785-a943-e33fb3958ad7.png)
![P}R)FCHBLJG}ZEC1)WMK$HH](https://user-images.githubusercontent.com/86773633/213439656-0addb470-52f9-4b75-a6dd-7f64b4b53214.png)
![@F%0FOV3`1NV07(O3{$R{49](https://user-images.githubusercontent.com/86773633/213439672-da6647f5-47f0-499f-a693-57b4fd833b5b.png)

### Steps to reproduce

1. 打开MCSTORM网站，输入本站IP
2. FRPS接收到大量TCP请求，产生大量WARNING
3. FRPC疯狂报错，崩溃
...
[nohup.tgz.log](https://github.com/fatedier/frp/files/10456653/nohup.tgz.log)

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
错误信息需要更完整的日志

**Comment by KleeLoveLife** [comment]
> 错误信息需要更完整的日志

[client.log](https://github.com/fatedier/frp/files/10463071/client.log)

**Comment by KleeLoveLife** [comment]
[client_end.txt](https://github.com/fatedier/frp/files/10463077/client_end.txt)


> 错误信息需要更完整的日志

**Comment by KleeLoveLife** [comment]
> 错误信息需要更完整的日志

服务端见上nohup.tgz.log 删掉.log后缀

**Comment by fatedier** [comment]
@KleeLoveLife 你后面补充的 client 端的日志还是没有完整的日志，看不到 panic 的原因。

但是从日志中协程数量来看的话，猜测大概率是协程很多，某个资源耗尽后异常退出了。

至于为什么会有大量连接，取决于你的测试过程了，除非有可以便于我本地复现的方法，否则也没法给到更多的帮助。
