### ISSUE TITLE
使用cloudflare给内网某台电脑开了7000端口和7500。7500可以直接访问，但是7000端口始终无法用客户端连接

### ISSUE THREAD

**Issue by yelublue** [fatedier/frp#3268]
### Bug Description

使用cloudflare给内网某台电脑开了7000端口和7500。7500可以直接访问，但是7000端口始终无法用客户端连接。
是因为cloudflare转发的时候地址就不对吗？
![image](https://user-images.githubusercontent.com/41419025/214192790-7a3bfdfb-148d-45a7-bc0f-9233a1151731.png)

### frpc Version

0.461

### frps Version

0.461

### System Architecture

windows64

### Configurations

[common]
server_addr = b.xxx.top
server_port = 7000

[w520]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 9002

### Logs

PS C:\frp> C:\frp\frpc.exe -c 112.ini
2023/01/24 08:50:12 [W] [service.go:133] login to server failed: dial tcp 172.67.135.129:7000: i/o timeout
dial tcp 172.67.135.129:7000: i/o timeout
PS C:\frp> C:\frp\frpc.exe -c 112.ini
2023/01/24 08:50:49 [I] [service.go:298] [c58355a158d5d389] login to server success, get run id [c58355a158d5d389], server udp port [0]
2023/01/24 08:50:49 [I] [proxy_manager.go:142] [c58355a158d5d389] proxy added: [w520]
2023/01/24 08:50:49 [I] [control.go:172] [c58355a158d5d389] [w520] start proxy success
PS C:\frp> C:\frp\frpc.exe -c 112.ini
2023/01/24 08:52:05 [W] [service.go:133] login to server failed: dial tcp 172.67.135.129:7000: i/o timeout
dial tcp 172.67.135.129:7000: i/o timeout
PS C:\frp> C:\frp\frpc.exe -c 112.ini
2023/01/24 08:57:53 [W] [service.go:133] login to server failed: dial tcp 172.67.135.129:7000: i/o timeout
dial tcp 172.67.135.129:7000: i/o timeout
PS C:\frp> C:\frp\frpc.exe -c 112.ini
2023/01/24 08:58:45 [W] [service.go:133] login to server failed: dial tcp 172.67.135.129:7000: i/o timeout
dial tcp 172.67.135.129:7000: i/o timeout
PS C:\frp>

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
**需要tunnel的配置文件**

检查本地7000端口是否被监听，大概率**非frp问题**

cf不支持此[协议列表](https://developers.cloudflare.com/cloudflare-one/applications/non-http/)所用端口之外的直连tcp隧道

参照官方教程 [Arbitrary TCP](https://developers.cloudflare.com/cloudflare-one/applications/non-http/arbitrary-tcp/) 正确配置双端tunnel

**Comment by yelublue** [comment]
>检查过了，确实cl不支持tcp 上7000端口的。只能他限定的那几个。谢谢了！
