### ISSUE TITLE
[Feature Request] use `uname -s` and `uname -m` to combine the release file name

### ISSUE THREAD

**Issue by whlsxl** [fatedier/frp#3269]
### Describe the feature request

Use `uname` to define the name of the release file, can easily use in CI/CD or `Dockerfile`.

Example [docker compose](https://github.com/docker/compose/releases) .

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
```dpkg --print-architecture```

Or

```
architecture=""
case $(uname -m) in
    i386) architecture="386" ;;
    i686) architecture="386" ;;
    x86_64) architecture="amd64" ;;
    arm) dpkg --print-architecture | grep -q "arm64" && architecture="arm64" || architecture="arm" ;;
    *) echo "Unable to determine system architecture."; exit 1 ;;
esac
```

Or you can be more direct and compile the source code directly from, you can refer to [Makefile.cross-compiles](https://github.com/fatedier/frp/blob/dev/Makefile.cross-compiles)
