### ISSUE TITLE
可以在客户端配置文件指定remote_listen_ip么

### ISSUE THREAD

**Issue by wwqgtxx** [fatedier/frp#327]
有些时候服务器可能有多个公网Ip，而只需要其中的一个IP提供该服务；有时候可能只希望将客户端端口映射到服务器的localhost（比如讲内网的数据库映射到公网服务器内部提供服务），所以希望作者可以提供监听ip设置，提高frp的适用性

**Comment by fatedier** [comment]
通过服务器配置文件 bind_addr 指定，客户端没有权限指定绑定 ip，所以不会提供这个功能。如果有特殊需求可以 fork 后自己修改编译。

**Comment by wwqgtxx** [comment]
那如何实现绑定localhost呢

**Comment by fatedier** [comment]
如果不想其他人访问，可以自行设置防火墙，或者采用其他方式实现。
