### ISSUE TITLE
frpc.exe被Windows Defender误判成病毒

### ISSUE THREAD

**Issue by GreatHuang2007** [fatedier/frp#3272]
### Bug Description

![图片](https://user-images.githubusercontent.com/74058954/214814081-9092863f-b6c3-4c1c-8fad-b395635c398b.png)
这是Windows Defender的截图，操作系统为Windows Server 2019

### frpc Version

0.46.1

### frps Version

0.46.1

### System Architecture

windows/amd64

### Configurations

-

### Logs

-

### Steps to reproduce

-

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
https://github.com/fatedier/frp/issues/2095

怕就不要用

**Comment by davidng530** [comment]
加个自签证书就可以解决了

**Comment by Kylin93CN** [comment]
你用火绒试试，之前看过一篇文章说 有些杀毒软件识别不了特征码都归为病毒了

**Comment by davidng530** [comment]
@Kylin93CN 要求不要太高，要想什么杀毒软件都能过检测，干脆就别用。微软自带的 Defenden 实际测试，对frpc.exe 文件加个数字签名，或伪装成其他品牌公司的数字签名就能过。国内的杀毒软件最好能不用就别用。

**Comment by GreatHuang2007** [comment]
我直接添加信任区了

**Comment by iawes** [comment]
> 

怎么加呢？

**Comment by xia-huang-411303** [comment]
> > 
> 
> 怎么加呢？

在 Windows Defender 中，选择“病毒和威胁防护"->"病毒和威胁防护 设置"->“管理设置”->“排除项”->"添加或删除排除项" 中设置

**Comment by miaopan607** [comment]
> 你用火绒试试，之前看过一篇文章说 有些杀毒软件识别不了特征码都归为病毒了

（）今天发现火绒也给报毒了，笑死

<img width="1188" height="227" alt="Image" src="https://github.com/user-attachments/assets/3dc8e79a-17db-4a5b-a01d-1d206ecf7cd2" />
