### ISSUE TITLE
How do route/IP/domain configuration directives work?

### ISSUE THREAD

**Issue by ylluminate** [fatedier/frp#3273]
### Bug Description

On an `frps` server with a well crafted `frps.ini` configuration file, I am finding a lot of strange traffic that comes in to various attempted efforts to penetrate various file paths, etc.

I would like to create specific rules/routes for various inbound garbage that comes into the FRP server, is this possible?

I have seen some various options that seem that `frps.ini` might be able to have `[route]` or `[somedomainname.com]` with perhaps custom directives such as a `redirect` or multiple `custom_404_page` directives...

Is there some documentation about these that I'm missing that's not covered in the `https://github.com/fatedier/frp/blob/dev/conf/frps_full.ini` example?

### frpc Version

0.46.1

### frps Version

0.46.1

### System Architecture

linux/amd64

### Configurations

Any

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
I think you'd better deploy a nginx before frps to achieve your requirements.

frp doesn't support all l7 features.

**Comment by ADMrugacz** [comment]
frp docs are confusing
