### ISSUE TITLE
frpc execute cause centos reboot

### ISSUE THREAD

**Issue by linlih** [fatedier/frp#3274]
### Bug Description

As the title says : frpc execute cause centos reboot.

### frpc Version

0.46.1

### frps Version

0.46.1

### System Architecture

linux/amd64 centos 8 stream

### Configurations

frpc.ini
```
[common]
server_addr = xxx
server_port = 33080

token=xxx

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 1xx
use_encryption = true
````
frps.ini
```
[common]
bind_port = 33080


token=xxx
```

### Steps to reproduce

1.  start the server  frps
2.  start  client frpc

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
Cannot be reproduced.

Post your kernel dumps,

or a full clone image of the system.

**Comment by linlih** [comment]
Thanks for the hint !

Though the kernel dump I find it produce a bug says： “kernel bug at drivers/net/vmxnet3/vmxnet3_drv.c:1599.c”

I install the centos in VMware ESXi 6.5 Version, it provide the solution : https://kb.vmware.com/s/article/2151480
