### ISSUE TITLE
[Feature Request] Add whitelist to frp

### ISSUE THREAD

**Issue by ForgottenZ** [fatedier/frp#3278]
### Describe the feature request

l want to add a whitelist file in frp.I want to ban someone‘s ip who want to attack my server under NAT (without firewall).
Maybe it can appear as a plugin
(Ignore my language errors)

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
under NAT ≠ without firewall

```
apt-get install iptables #Ubuntu

apt-get install iptables #Debian

apk add iptables #Alpine

pacman -S iptables #Arch Linux

apt-get install iptables #Kali Linux

yum install iptables #CentOS

dnf install iptables #Fedora

apt-get install iptables #Raspbian

```

**Comment by soonxf** [comment]
###  Recommend My Project Firewall [firewall](https://github.com/soonxf/Micro-Firewall) @ForgottenZ
