### ISSUE TITLE
Method to forward through a client to an internal device?

### ISSUE THREAD

**Issue by ylluminate** [fatedier/frp#3281]
### Describe the feature request

In a scenario where one needs to access another device on a LAN that is incapable of running `frpc`, is it possible to have an `frpc` client on a system forward access to another internal IP+port?

So, as an example, if I need to directly access a network device at LAN IP:port 192.168.0.15:2345, could another `frpc.ini` be setup to facilitate accessing that device through itself and creating the tunnel back out to the `frps` server?

If this can be done, is there an example config for the `frpc.ini` to do this?

### Affected area

- [X] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frpc_full.ini#L153

**Comment by ylluminate** [comment]
Thank you, this helps. It does appear that simply forwarding an IP + port to another device actually works perfectly. This leads me to believe that one could simply run `frpc` on a single system on a LAN and then forward all ports to any and all devices desired through this singular client.
