### ISSUE TITLE
frpc在frpc.ini中指定输出日志时无法输出日志

### ISSUE THREAD

**Issue by Daodanfd5** [fatedier/frp#3285]
### Bug Description

如题，将frpc的log名称设成mcfrpc.log，启动时会显示logs.BeeLogger.SetLogger: invalid character 'm' in string escape code，但不影响frpc反向代理

### frpc Version

0.46.1

### frps Version

0.46.1

### System Architecture

windows/amd64

### Configurations

frpc无日志输出，将程序复制到另一台电脑上也无法使用，两台机器一台启用了utf-8一台没有启用utf-8

以下是frpc.ini内容
```
[common]
tls_enable = true
server_addr = example.net
server_port = *****
log_file = D:\*****\mcfrpc.log
log_level = trace
token = **********
```
删除log_file = D:\*****\mcfrpc.log后日志会在控制台完整输出。

### Logs

控制台输出:
```
logs.BeeLogger.SetLogger: invalid character 'm' in string escape code
```

### Steps to reproduce

1. 启用Windows的utf-8支持
2. 关闭所有杀软
3. 用如下命令启动： frpc -c frpc.ini

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by Daodanfd5** [comment]
系统信息：

版本	Windows Server 2022 Datacenter
版本号	21H2
安装日期	‎2022/‎8/‎18
操作系统内部版本	20348.1487

补充：在启用utf-8支持后重启时并没有立即出现该现象，但另一台使用GBK编码的电脑却可以正常运行从GitHub下载的同一版本

**Comment by Becods** [comment]
将 `\` 替换成 `/`

`\` 为转义字符

**Comment by Daodanfd5** [comment]
感谢，运行成功了，不过这个路径在frp中的处理方式和其他大部分应用程序不同，是为了保持frpc.ini可以在多平台通用吗？
