### ISSUE TITLE
[Feature Request] frpc admin dashboard enable tls

### ISSUE THREAD

**Issue by ringerl** [fatedier/frp#3289]
### Describe the feature request

I've found no way to expose the frpc admin-dashboard via **https** - is this already possible?

https://github.com/fatedier/frp/blob/dev/conf/frpc_full.ini#L69:
```
# set admin address for control frpc's action by http api such as reload
admin_addr = 127.0.0.1
```

### Affected area

- [x] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [x] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Not support

**Comment by Becods** [comment]
```
[common]
dashboard_tls_mode = true
dashboard_tls_cert_file = server.crt
dashboard_tls_key_file = server.key
```

https://github.com/fatedier/frp/blob/7678938c088c8d57367494ad53dd5c3b9e0cca35/pkg/config/server.go#L85-L95

**Comment by ringerl** [comment]
@Becods, dashboard_tls_*-settings refer to frps not frpc. I was looking for TLS settings for the dashboard/api-endpoint in frpc.
