### ISSUE TITLE
dashboard开启https的证书应该怎么选？

### ISSUE THREAD

**Issue by Wrandz** [fatedier/frp#3291]
### 文档里面写的是加上证书和密钥文件即可，如图所示
![3](https://user-images.githubusercontent.com/70056470/216870535-80260020-5187-442a-a6ef-68d7ce8a5d19.png)
### 我找了一下阿里云证书下载界面，对应的就是apache的是crt/key，如图所示
![1](https://user-images.githubusercontent.com/70056470/216870723-9d801dc3-c046-4e27-91ef-aed4d6879b75.png)
### 可是下载下来有2个crt，这两个是要合并？还是选择哪一个？
![2](https://user-images.githubusercontent.com/70056470/216870888-285e0d2e-4724-4f77-b434-eb6af53bb5a8.png)

### frpc Version

0.46.1

### frps Version

0.46.1

### System Architecture

linux/amd64

### Configurations

[common]
bind_port=52511
bind_udp_port=52511
authentication_method=token
token=admin
dashboard_port=52512
dashboard_user=admin
dashboard_pwd=admin

dashboard_tls_mode = true
dashboard_tls_cert_file = server.crt
dashboard_tls_key_file = server.key

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
## **实践出真知**

一般情况下二选一

**Comment by Wrandz** [comment]
@Becods 不是的，你错了，并不是二选一，我后面用的是nginx那个pem/key证书，这个是可以的。
