### ISSUE TITLE
[Feature Request] 如果客户端突然断网重新恢复 是否会自动重新连接到服务端

### ISSUE THREAD

**Issue by sudi703** [fatedier/frp#3294]
### Describe the feature request

如果客户端突然断网重新恢复 是否会自动重新连接到服务端，如果可以需要配置什么呢？

### Affected area

- [ ] Docs
- [ ] Installation
- [x] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [x] Client Plugin
- [x] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by sudi703** [comment]
> ### Describe the feature request
> 如果客户端突然断网重新恢复 是否会自动重新连接到服务端，如果可以需要配置什么呢？
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Affected area
> * [ ]  Docs
> * [ ]  Installation
> * [ ]  Performance and Scalability
> * [ ]  Security
> * [ ]  User Experience
> * [ ]  Test and Release
> * [ ]  Developer Infrastructure
> * [ ]  Client Plugin
> * [ ]  Server Plugin
> * [ ]  Extensions
> * [ ]  Others

**Comment by Becods** [comment]
https://github.com/fatedier/frp/blob/0eecab06c17d69ba11a84162aae35ed7d94f0423/conf/frpc_full.ini#L90-L92
