### ISSUE TITLE
[Feature Request] how to close the window about login

### ISSUE THREAD

**Issue by llwq123456** [fatedier/frp#3297]
### Describe the feature request

我想把登录页面填写用户名密码的那个页面给去了，在哪里去除啊

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
https://github.com/fatedier/frp/blob/aa31d7ad0bdcc05ee0a4add6cfd0eacf04c241c5/conf/frpc_full.ini#L72-L73

https://github.com/fatedier/frp/blob/aa31d7ad0bdcc05ee0a4add6cfd0eacf04c241c5/conf/frps_full.ini#L50-L52
