### ISSUE TITLE
端口汇聚及安全性考虑的需求

### ISSUE THREAD

**Issue by SandyLu** [fatedier/frp#330]
当前有Ａ，Ｂ两个不同内网机，均可连入互联网　Ｃ为阿里云。
当前可实现　Ｃ安装frps，  B安装 frpc. 做好映射。A访问C开的端口。

现在问题是C将B的端口服务暴露在互联网不安全，可否实现A连接C单一加密的端口。Ｂ的服务最终在Ａ展开，让Ａ同内网的其他机器访问A即相当于访问B对应端口。
也就是实现通过C完成一条隧道链路。

**Comment by fatedier** [comment]
在计划中，TODO

**Comment by hanqian200705** [comment]
内网服务直接通过公网暴露出来确实有些安全隐患，提供一个简单点的方案看是否可行：frp是否能提供一个简单的认证页面，连接公网暴露的服务前，需要先通过此认证页面进行登录认证，由frpc端提供 认证密码，认证过期时间，是否绑定ip等一些配置。frps端根据情况决定是否拒绝访问，这样做是否会简单些。 @fatedier

**Comment by fatedier** [comment]
@hanqian200705  tcp 类型的服务，无法提供这样的认证页面。

0.13 将会版本将会加入 stcp(secret tcp) 的类型，需要两边都运行 frpc，并且指定相同的 sk 才能访问，提高安全性，避免将 tcp 服务直接暴露于公网。

**Comment by yingnierxiao** [comment]
可以加ip限制下
