### ISSUE TITLE
frp server reject connection after upgrade from 0.46.1 to 0.47.0

### ISSUE THREAD

**Issue by cloverzrg** [fatedier/frp#3301]
### Bug Description

server(0.47.0): 
[W] [control.go:460] [65f02f3f7dfdee98] new proxy [k2p-web] type [http] error: bandwidth_limit_mode should be client or server

client(0.45.0):
[W] [control.go:460] [65f02f3f7dfdee98] new proxy [k2p-web] type [http] error: bandwidth_limit_mode should be client or server

### frpc Version

0.45.0

### frps Version

0.47.0

### System Architecture

linux/amd64

### Configurations

frps:
```
[common]
bind_port = 7700
token = xxx
vhost_http_port = 8080
vhost_https_port = 8443

dashboard_port = 7100
dashboard_user = xxx
dashboard_pwd = xxx

enable_prometheus = true
```

frpc:
```
[common]
server_addr = xxx.com
server_port = 7700
token = xxx


[k2p-web]
type = http
local_port = 80
use_encryption = true
use_compression = true
custom_domains = xxx.com
http_user = xxx
http_pwd = xxx


[k2p-ssh]
type = tcp
local_port = 22
remote_port = xxx
```

### Logs

[I] [service.go:500] [65f02f3f7dfdee98] client login info: ip [xxx:18918] version [0.45.0] hostname [] os [linux] arch [mipsle]
frp-server    | 2023/02/10 12:15:38 [W] [control.go:460] [65f02f3f7dfdee98] new proxy [k2p-ssh] type [tcp] error: bandwidth_limit_mode should be client or server
frp-server    | 2023/02/10 12:15:38 [W] [control.go:460] [65f02f3f7dfdee98] new proxy [k2p-web] type [http] error: bandwidth_limit_mode should be client or server

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Please download the new binary [here](https://github.com/fatedier/frp/releases/tag/v0.47.0)

**Comment by cloverzrg** [comment]
so you had re-upload the binary? ok
