### ISSUE TITLE
xtcp模式不能跨user匹配p2p服务

### ISSUE THREAD

**Issue by Cp0204** [fatedier/frp#3302]
### Bug Description

背景：平时我用 [common]user 字段以区分不同设备端，避免服务名冲突（表现为user.server）；当使用xtcp时，访问端server_name也会加上访问端的user，导致不能相互匹配。

**设备A：**
[common]
user = AAA
[p2p_ssh]
此时服务名为：AAA.p2p_ssh

**设备B：**
[common]
user = BBB
[p2p_ssh_visitor]
server_name = p2p_ssh

将报错：[BBB.p2p_ssh_visitor] natHoleRespMsg get error info: xtcp server for [BBB.p2p_ssh] doesn't exist

期望 server_name = AAA.p2p_ssh 可以匹配上，而目前会自动变成 BBB.AAA.p2p_ssh，同样doesn't exist

### frpc Version

0.46.1

### frps Version

0.46.1

### System Architecture

linux/amd64

### Configurations

2. 在需要暴露到外网的机器上部署 frpc，且配置如下：
```
[common]
server_addr = x.x.x.x
server_port = 7000
user=AAA

[p2p_ssh]
type = xtcp
# 只有 sk 一致的用户才能访问到此服务
sk = abcdefg
local_ip = 127.0.0.1
local_port = 22
```

3. 在想要访问内网服务的机器上也部署 frpc，且配置如下：
```
[common]
server_addr = x.x.x.x
server_port = 7000
**user = BBB**

[p2p_ssh_visitor]
type = xtcp
# xtcp 的访问者
role = visitor
# 要访问的 xtcp 代理的名字
server_name = p2p_ssh
sk = abcdefg
# 绑定本地端口用于访问 ssh 服务
bind_addr = 127.0.0.1
bind_port = 6000
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Miaoerr** [comment]
使用stcp  遇到同样的问题
作为visitor时，server_name是否应该不自动添加user前缀？
