### ISSUE TITLE
http: TLS handshake error from xxxxx: EOF

### ISSUE THREAD

**Issue by 1143461596** [fatedier/frp#3305]
### Bug Description

使用https类型的配置，添加了阿里云nginx域名证书，启用了https2http插件，frps与frpc的连接也正常，可是一旦访问系统，frpc端日志就提示报错http: TLS handshake error from xxxxxx: EOF
更换过其他域名证书，更换过fprs和fprc的版本，也更换过客户端的操作系统，均是相同情况。
开启了trace模式的日志输出，配置如下。请问各位大佬有遇到类似情况吗？该如何解决?

### frpc Version

0.46.1

### frps Version

0.46.1

### System Architecture

linux/amd64

### Configurations

[https2http]
type = https
local_ip = 127.0.0.1
local_port = 8000
custom_domains = xxx.xxxx.com
plugin = https2http
plugin_local_addr = 127.0.0.1:8000
plugin_host_header_rewrite = 127.0.0.1
plugin_header_X-From-Where = frp
plugin_crt_path = ./server.pem
plugin_key_path = ./server.key

### Logs

2023/02/13 10:43:49 [D] [control.go:286] [40261acec1f32e81] send heartbeat to server
2023/02/13 10:43:49 [D] [control.go:317] [40261acec1f32e81] receive heartbeat from server
2023/02/13 10:43:57 [D] [proxy_wrapper.go:231] [40261acec1f32e81] [https2http] start a new work connection, localAddr: 10.1.40.3:59570 remoteAddr: xxxxx
2023/02/13 10:43:57 [D] [proxy_wrapper.go:231] [40261acec1f32e81] [https2http] start a new work connection, localAddr: 10.1.40.3:59570 remoteAddr: xxxxxx
2023/02/13 10:43:57 [T] [proxy.go:742] [40261acec1f32e81] [https2http] handle tcp work connection, use_encryption: false, use_compression: false
2023/02/13 10:43:57 [T] [proxy.go:742] [40261acec1f32e81] [https2http] handle tcp work connection, use_encryption: false, use_compression: false
2023/02/13 10:43:57 [D] [proxy.go:791] [40261acec1f32e81] [https2http] handle by plugin: https2http
2023/02/13 10:43:57 [D] [proxy.go:791] [40261acec1f32e81] [https2http] handle by plugin: https2http
2023/02/13 10:43:57 [D] [proxy.go:793] [40261acec1f32e81] [https2http] handle by plugin finished
2023/02/13 10:43:57 [D] [proxy.go:793] [40261acec1f32e81] [https2http] handle by plugin finished
2023/02/13 10:43:57 http: TLS handshake error from xxxxxxx: EOF
2023/02/13 10:43:57 http: TLS handshake error from xxxxxxx: EOF

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
确保在 `127.0.0.1:8000` 上运行的服务是 http 而不是 https

**Comment by 1143461596** [comment]
> 确保在 `127.0.0.1:8000` 上运行的服务是 http 而不是 https

127.0.0.1:8000 确定是http，而且https的我也试过，都不行。 真的怀疑是frpc根本没读到我的证书，但是证书文件的路径和权限都是没问题的。

**Comment by cnjsyyb** [comment]
> 找到原因了，因为域名未完成备案导致，刚刚正好域名通过了管局备案，问题解决了。谢谢大家~
还有这种事

**Comment by yikexiaoyao** [comment]
我也遇到这种问题，未解决

**Comment by steveoOn** [comment]
相同的问题，frpc用https2https插件把本地http转换为https，域名和云服务器都是海外的，不存在备案问题，但是提示提示：

http: TLS handshake error from xxxx:xxxx: EOF

**Comment by ChouYih** [comment]
> 相同的问题，frpc用https2https插件把本地http转换为https，域名和云服务器都是海外的，不存在备案问题，但是提示提示：
> 
> http: TLS handshake error from xxxx:xxxx: EOF

解决了吗？

**Comment by actonknowledge** [comment]
> 相同的问题，frpc用https2https插件把本地http转换为https，域名和云服务器都是海外的，不存在备案问题，但是提示提示：
> 
> http: TLS handshake error from xxxx:xxxx: EOF

最新版存在同样的问题
