### ISSUE TITLE
type [tcp] error: port unavailable

### ISSUE THREAD

**Issue by llwq123456** [fatedier/frp#3311]
### Bug Description

![image](https://user-images.githubusercontent.com/56341280/219262747-49f9ffbd-4235-4689-b772-e9856498c02b.png)
![image](https://user-images.githubusercontent.com/56341280/219262813-69a61b5d-5824-47cb-8625-df7a361f0019.png)

![image](https://user-images.githubusercontent.com/56341280/219263378-a819c5b7-b51e-4de0-9f80-5a5a16d296d8.png)

### frpc Version

 fp-compiler-3.0.4

### frps Version

0.46.1

### System Architecture

window/amd64

### Configurations

frpc------
[https]
type = tcp
local_port = 8443
local_ip = 172.18.75.45
remote_port = 4430

frps--------
vhost_http_port = 12889
vhost_https_port = 4430
log_level = debug

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
https://github.com/fatedier/frp/issues/2067#issuecomment-724559996
