### ISSUE TITLE
单 frp server instance 的最多客户端连接数

### ISSUE THREAD

**Issue by shaojun** [fatedier/frp#3312]
### Describe the feature request

hi,
非常感谢这个作品。
我是物联网的场景，可能有**上万个**边缘网关分布于各处，而每台边缘网关上有一个`frp client instance`，每个`frp client instance` 会映射**两个**`tcp连接`到`frp server`. _(但同一时间，仅有**个位数**的真实应用连接会从公网发起, like `SSH`)_
问题:
1. 请问单个`frp server instance` 能承载的最多客户端连接数是多少呢？
2. 如果单个`frp server instance`达到了上限，如何进行技术处理来提升上限呢？
3. 有注意到 `http://url.com/static/#/proxies/tcp` 还没有分页显示，请问有计划优化它，以提供更大数量的客户端状态监测吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
1. https://github.com/fatedier/frp/issues/1289#issuecomment-517934271
> 现在我用 Swoole 重写了后端业务代码，回到了 HTTP/1.0（因为对应软件是轮询，没有必要做长连接），再进行了一次高并发请求测试，在 2000 线程 + 512 连接的情况下 Frps 依然毫无压力，可以证明就是因为连接数过多导致的这个错误了。

2. https://github.com/fatedier/frp/issues/2445#issuecomment-861982286
> 集群的方案有相关的设计，但是相对复杂，而且大多数偏商业化需求，开源版本里可能不会花太多精力做这件事。

3. 建议使用 prometheus 采集监测数据
https://github.com/fatedier/frp/blob/24f0b3afa5141a63a246c0b91d81ca43b288d9ae/conf/frps_full.ini#L59-L60

4. 物联网建议使用轻量的 mqtt
