### ISSUE TITLE
总提示client exit

### ISSUE THREAD

**Issue by websecer** [fatedier/frp#3314]
### Bug Description

`2023/02/16 14:45:33 [I] [service.go:500] [8d1ddc961eff3115] client login info: ip [123.123.123.123:21477] version [0.47.0] hostname [] os [linux] arch [amd64]
2023/02/16 14:45:52 [I] [control.go:306] [8d1ddc961eff3115] control writer is closing
2023/02/16 14:45:52 [I] [control.go:395] [8d1ddc961eff3115] client exit success
2023/02/16 14:45:52 [I] [service.go:500] [8d1ddc961eff3115] client login info: ip [123.123.123.123:13707] version [0.47.0] hostname [] os [linux] arch [amd64]
2023/02/16 14:46:11 [I] [control.go:306] [8d1ddc961eff3115] control writer is closing
2023/02/16 14:46:11 [I] [control.go:395] [8d1ddc961eff3115] client exit success
2023/02/16 14:46:11 [I] [service.go:500] [8d1ddc961eff3115] client login info: ip [123.123.123.123:48405] version [0.47.0] hostname [] os [linux] arch [amd64]
2023/02/16 14:46:30 [I] [control.go:306] [8d1ddc961eff3115] control writer is closing
2023/02/16 14:46:30 [I] [control.go:395] [8d1ddc961eff3115] client exit success
2023/02/16 14:46:31 [I] [service.go:500] [8d1ddc961eff3115] client login info: ip [123.123.123.123:18716] version [0.47.0] hostname [] os [linux] arch [amd64]
2023/02/16 14:46:50 [I] [control.go:306] [8d1ddc961eff3115] control writer is closing
2023/02/16 14:46:50 [I] [control.go:395] [8d1ddc961eff3115] client exit success
2023/02/16 14:46:51 [I] [service.go:500] [8d1ddc961eff3115] client login info: ip [123.123.123.123:3551] version [0.47.0] hostname [] os [linux] arch [amd64]
2023/02/16 14:47:09 [I] [control.go:306] [8d1ddc961eff3115] control writer is closing
2023/02/16 14:47:09 [I] [control.go:395] [8d1ddc961eff3115] client exit success
2023/02/16 14:47:10 [I] [service.go:500] [8d1ddc961eff3115] client login info: ip [123.123.123.123:8946] version [0.47.0] hostname [] os [linux] arch [amd64]
2023/02/16 14:47:29 [I] [control.go:306] [8d1ddc961eff3115] control writer is closing
2023/02/16 14:47:29 [I] [control.go:395] [8d1ddc961eff3115] client exit success
2023/02/16 14:47:29 [I] [service.go:500] [8d1ddc961eff3115] client login info: ip [123.123.123.123:35951] version [0.47.0] hostname [] os [linux] arch [amd64]
2023/02/16 14:47:48 [I] [control.go:306] [8d1ddc961eff3115] control writer is closing
2023/02/16 14:47:48 [I] [control.go:395] [8d1ddc961eff3115] client exit success
2023/02/16 14:47:49 [I] [service.go:500] [8d1ddc961eff3115] client login info: ip [123.123.123.123:46980] version [0.47.0] hostname [] os [linux] arch [amd64]
2023/02/16 14:48:08 [I] [control.go:306] [8d1ddc961eff3115] control writer is closing
2023/02/16 14:48:08 [I] [control.go:395] [8d1ddc961eff3115] client exit success
2023/02/16 14:48:08 [I] [service.go:500] [8d1ddc961eff3115] client login info: ip [123.123.123.123:17433] version [0.47.0] hostname [] os [linux] arch [amd64]
2023/02/16 14:48:27 [I] [control.go:306] [8d1ddc961eff3115] control writer is closing`

### frpc Version

0.47.0

### frps Version

0.47.0

### System Architecture

linux/amd64

### Configurations

总是断线 很频繁

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
1. 检查客服之间的连接质量

2. 尝试使用 [KCP](https://github.com/fatedier/frp#support-kcp-protocol) 协议

**Comment by websecer** [comment]
failed to parse proxy zzzz, err: proxy zzzz has invalid type [KCP]
