### ISSUE TITLE
[Feature Request] Please clarify TLS usage in the docs

### ISSUE THREAD

**Issue by AndrewBedscastle** [fatedier/frp#3318]
### Describe the feature request

in frpc.ini I have
`tls_enable = true`
in frps.ini I have
`tls_only = true`

That works fine. According to wireshark it's encrypted

I did not configure 

```
tls_cert_file = certificate.crt
tls_key_file = certificate.key
tls_trusted_ca_file = ca.crt
```
Docs say: 

> You will need a root CA cert and at least one SSL/TLS certificate. It can be self-signed or regular (such as Let's Encrypt or another SSL/TLS certificate provider).

Even though I did not configure it, it works without adding certificates. What happens in this case? Does it use generated certs?
Please clarify in the docs

Thank you very much

PS: Awesome project, Thank you very much <3

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
It uses auto generated certs in memory.

**Comment by yuliu** [comment]
IMO, the TLS configuration is well documented in frp docs' Chinese version at https://gofrp.org/zh-cn/docs/features/common/network/network-tls/ , and the English version of README.md in the repo may be updated accordingly.
