### ISSUE TITLE
[Feature Request] 是否可以在FRP server添加ip封禁功能

### ISSUE THREAD

**Issue by AoXIUy** [fatedier/frp#3321]
### Describe the feature request

是否可以在FRP server添加ip封禁功能

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
尝试 [zfb132/frp_info](https://github.com/zfb132/frp_info)

> You can use iptables first.
> Or maybe we can add this by server plugin later.

> 可以尝试其他 linux 防火墙的工具，或者通过 [服务端插件](https://gofrp.org/docs/features/common/server-plugin/) 来实现这个扩展能力

> 从我个人的角度而言，这个阶段不太希望引入各种琐碎的 feature，很容易让项目成为一个大杂烩，既提高开发者的维护成本，也增加了用户的使用成本。最终某些功能可能只有几个人使用，甚至没有人用，但是持续的维护却需要耗费很多精力。
>
> 所以，目前可能更多的是希望做减法，专注核心能力，做一些重构。之后能通过插件的方式开放更多的扩展能力出来，可以由有需求的人来完善。

**Comment by soonxf** [comment]
我来推荐我自己 [防火墙](https://github.com/soonxf/Micro-Firewall)

**Comment by soonxf** [comment]
@AoXIUy 我来推荐我自己 [防火墙](https://github.com/soonxf/Micro-Firewall)

**Comment by AoXIUy** [comment]
@soonxf 我去试试，感谢
天天被爆破烦死了
