### ISSUE TITLE
[Feature Request] 防火墙

### ISSUE THREAD

**Issue by soonxf** [fatedier/frp#3325]
### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by fatedier** [comment]
项目挺好，但请合理使用 Github issue，不要给其他人造成过多的干扰。Issue 主要是用来追踪项目本身的问题，推广可以尝试其他一些社区/论坛等更合适的地方。
