### ISSUE TITLE
[Feature Request] 无法通过修改配置文件取消http_proxy环境变量设置的代理

### ISSUE THREAD

**Issue by yyjdelete** [fatedier/frp#3329]
### Describe the feature request

应该有某种方式可以在配置文件中设置不走代理(即使http_proxy环境变量设置了一个代理服务器), 当前版本可以`http_proxy = `设置为另一个代理, 但不允许通过这种方式取消代理的设置

### Describe alternatives you've considered

允许通过设置如`http_proxy = none`之类的配置来覆盖并忽略环境变量中的代理

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
启动应用时，主动设置此环境变量值为空。

**Comment by yyjdelete** [comment]
我错了, 在配置文件里面设置`http_proxy = none`是能取消的, 空字符串不行
