### ISSUE TITLE
dashboard suggestions: gzip and API CORS (v0.10.0)

### ISSUE THREAD

**Issue by undirectlookable** [fatedier/frp#333]
0.10.0 版的新 dashboard 比前一版有很大进步，但 js 打包的 bundle 体积太大，一共 1.3MB，这在很多国内云服务器的 1M 小水管上需要十几秒才能打开。

建议 dashboard 内置服务器开启 gzip，体积至少可减少一半以上。

另外，像 /api/proxy/tcp 这些 API 的返回 Header，如果加上 [CORS](https://developer.mozilla.org/docs/Web/HTTP/Headers/Access-Control-Allow-Origin)，则可以实现第三方 dashboard，类似于 [aria2c.com](http://aria2c.com/) 与 [aria2 json-rpc](https://aria2.github.io/manual/en/html/aria2c.html#rpc-interface) 的配合形式。这可以激发大家写自己的 dashboard，或者把 frp 集成到现有的后台系统中去。

**Comment by fatedier** [comment]
1. 内置服务器开启 gzip，这个 TODO。
2. CORS 暂时感觉没有必要，dashboard 和服务端放在一起，自己看就可以了。
