### ISSUE TITLE
Token error if authenticate_new_work_conns = true

### ISSUE THREAD

**Issue by dlinx** [fatedier/frp#3331]
### Bug Description

Token error on client startup if `authenticate_new_work_conns = true` or `authenticate_heartbeats = true`

```
[E] [control.go:155] [ab7f3719eca08d92] StartWorkConn contains error: token in NewWorkConn doesn't match token from configuration

```

### frpc Version

0.47.0

### frps Version

0.47.0

### System Architecture

Server: linux/amd64, Client: windows/amd64

### Configurations

authenticate_new_work_conns = true
authenticate_heartbeats = true

### Logs

2023/02/23 23:37:44 [I] [service.go:299] [ab7f3719eca08d92] login to server success, get run id [ab7f3719eca08d92], server udp port [7001]
2023/02/23 23:37:44 [I] [proxy_manager.go:142] [ab7f3719eca08d92] proxy added: [web]
2023/02/23 23:37:44 [I] [control.go:172] [ab7f3719eca08d92] [web] start proxy success
2023/02/23 23:37:44 [E] [control.go:155] [ab7f3719eca08d92] StartWorkConn contains error: token in NewWorkConn doesn't match token from configuration

### Steps to reproduce

1. Configure server with auth
2. Try to run client (This will work)
3. Enable authenticate_new_work_conns = true, and restart server.
4. Restart client, (This will give token error)

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frpc_full.ini#LL33C37-L33C37

You should also set this parameters in frpc.ini
