### ISSUE TITLE
UDP packets not being forwarded

### ISSUE THREAD

**Issue by 0xAl3xH** [fatedier/frp#3332]
### What I've tried
Here is the `frpc.ini` configuration in what I will call the `UDP_server`
```
[udp-test]
type = udp
local_ip = 127.0.0.1
local_port = 9710
remote_port = 9710
```
After checking the dashboard to make sure the port is online:
<img width="862" alt="Screen Shot 2023-02-24 at 1 38 24 PM" src="https://user-images.githubusercontent.com/20210402/221298163-6dccdfe5-5533-43e1-ac2e-bbb8f1e31e2e.png">

To test, I ran `nc -lu 9710` on `UDP_server` and on my own machine, I ran `echo "hello world" | nc -4 -v -u [FRP_server_IP] 9710` and nothing happened. 

However, as a sanity check I set `type = tcp` and repeated the netcat test above with `nc -l 9710` on the server and `echo "hello world" | nc -4 -v [FRP_server_IP] 9710` on the client and I was able to recieve the message.

### What I expected
I expected UDP forwarding to work as well. 

### What happened
TCP forwarding worked but UDP didn't

### frpc Version

0.46.1

### frps Version

0.46.1

### System Architecture

linux/x86_64, macOS/arm64

### Configurations

[udp-test]
type = udp
local_ip = 127.0.0.1
local_port = 9710
remote_port = 9710

and 

[udp-test]
type = tcp
local_ip = 127.0.0.1
local_port = 9710
remote_port = 9710

### Steps to reproduce

1. Set the configurations
2. Run `nc -lu 9710` on `UDP_server` 
3. Run `echo "hello world" | nc -4 -v -u [FRP_server_IP] 9710` on the client 

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by brostosjoined** [comment]
Test with this see if the is udp or your configuration https://github.com/DKingAlpha/frp#all-ports-mapping
