### ISSUE TITLE
[Feature Request] need freebsd arm64 release

### ISSUE THREAD

**Issue by shallowinggg** [fatedier/frp#3336]
### Describe the feature request

I have seen some releases for `freebsd-x86`, but I need `freebsd-arm64` release so I can write install scripts for my Raspberry Pi, instead clone and compile locally. Thanks!!!

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
We don't want to provide pre-compiled binary files for every system and architecture unless there are a significant number of users for that system and architecture.
