### ISSUE TITLE
配置的quic，但是为什么服务器显示的链接方式是tcp

### ISSUE THREAD

**Issue by hhrensheng** [fatedier/frp#3337]
### Bug Description

我的服务器和客户端配置的都是quic链接，但是控制面板显示的链接方式为什么是tcp？
![image](https://user-images.githubusercontent.com/29398035/221731574-b9a184f3-31fb-4ad8-a62a-a9da59ebf8c5.png)

### frpc Version

0.46.1

### frps Version

0.46.1

### System Architecture

linux/amd64

### Configurations

`frps`
bind_port = 7000
quic_bind_port = 7000
token = xxxxx
dashboard_port = 7500
dashboard_user =xxx
dashboard_pwd =xxx

`frpc`
[common]
token = xxxxx
server_addr = xxxxxxx
server_port = 7000
admin_addr = 127.0.0.1
admin_port = 7400
protocol = quic

[RDP_VM]
local_ip = 127.0.0.1
local_port = 3389
remote_port = 7789
use_encryption = true
use_compression = true

### Logs

`frps`
Feb 27 20:37:01 active-silo-5.localdomain frps[16860]: 2023/02/27 20:37:01 [I] [root.go:206] frps uses config file: /root/frp/frps.ini
Feb 27 20:37:01 active-silo-5.localdomain frps[16860]: 2023/02/27 20:37:01 [I] [service.go:200] frps tcp listen on 0.0.0.0:7000
Feb 27 20:37:01 active-silo-5.localdomain frps[16860]: 2023/02/27 20:37:01 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for
Feb 27 20:37:01 active-silo-5.localdomain frps[16860]: 2023/02/27 20:37:01 [I] [service.go:226] frps quic listen on quic 0.0.0.0:7000
Feb 27 20:37:01 active-silo-5.localdomain frps[16860]: 2023/02/27 20:37:01 [I] [service.go:317] Dashboard listen on 0.0.0.0:7500
Feb 27 20:37:01 active-silo-5.localdomain frps[16860]: 2023/02/27 20:37:01 [I] [root.go:215] frps started successfully
Feb 27 20:37:30 active-silo-5.localdomain frps[16860]: 2023/02/27 20:37:30 [I] [service.go:500] [5778d335102fd46d] client login info: ip [xxxxxxxxx:2077] version [0.46.1] hostname [] os [windows] arch [amd64]
Feb 27 20:37:31 active-silo-5.localdomain frps[16860]: 2023/02/27 20:37:31 [I] [tcp.go:64] [5778d335102fd46d] [RDP_VM] tcp proxy listen port [7789]
Feb 27 20:37:31 active-silo-5.localdomain frps[16860]: 2023/02/27 20:37:31 [I] [control.go:464] [5778d335102fd46d] new proxy [RDP_VM] type [tcp] success
Feb 27 20:37:39 active-silo-5.localdomain frps[16860]: 2023/02/27 20:37:39 [I] [service.go:500] [4e448167191fa31d] client login info: ip [xxxxxxxxxxx:3885] version [0.46.1] hostname [] os [windows] arch [amd64]
Feb 27 20:37:39 active-silo-5.localdomain frps[16860]: 2023/02/27 20:37:39 [I] [tcp.go:64] [4e448167191fa31d] [RDP_HT] tcp proxy listen port [8899]
Feb 27 20:37:39 active-silo-5.localdomain frps[16860]: 2023/02/27 20:37:39 [I] [control.go:464] [4e448167191fa31d] new proxy [RDP_HT] type [tcp] success
Feb 27 20:37:43 active-silo-5.localdomain frps[16860]: 2023/02/27 20:37:43 [I] [proxy.go:179] [5778d335102fd46d] [RDP_VM] get a user connection [xxxxxxxxx:2156]

`frpc`
2023/02/28 09:45:52 [I] [service.go:298] [d28d9e10f5eacf81] login to server success, get run id [d28d9e10f5eacf81], server udp port [0]
2023/02/28 09:45:52 [I] [proxy_manager.go:142] [d28d9e10f5eacf81] proxy added: [RDP_VM]
2023/02/28 09:45:52 [I] [service.go:163] admin server listen on 127.0.0.1:7400
2023/02/28 09:45:52 [I] [control.go:172] [d28d9e10f5eacf81] [RDP_VM] start proxy success

### Steps to reproduce

1. 配置服务端
2. 配置客户端
3. 启动
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
此tcp非彼tcp。
0.46时我试过，流量走的是udp端口
你应该监视一下，使用中流量走的是tcp端口还是udp端口，比如通过软件或路由器等查看。

**Comment by xqzr** [comment]
`type` 默认 `tcp`
https://gofrp.org/docs/reference/proxy/#%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE

**Comment by hhrensheng** [comment]
> `type` 默认 `tcp` https://gofrp.org/docs/reference/proxy/#%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE

那这个时候type应该配置成什么比较好呢tcp、udp还是没有区别

**Comment by hhrensheng** [comment]
> 此tcp非彼tcp。 0.46时我试过，流量走的是udp端口 你应该监视一下，使用中流量走的是tcp端口还是udp端口，比如通过软件或路由器等查看。

哦哦 好的吧，会感觉有歧义

**Comment by xqzr** [comment]
> > `type` 默认 `tcp` https://gofrp.org/docs/reference/proxy/#%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE
> 
> 那这个时候type应该配置成什么比较好呢tcp、udp还是没有区别

看名称，应该是 RDP 服务，它必须有 TCP
