### ISSUE TITLE
关于服务端插件NewUserConn和NewWorkConn的疑问?

### ISSUE THREAD

**Issue by zhangboqi** [fatedier/frp#3338]
### Bug Description

很抱歉在Bug类型的Issue中提出这个问题，实在是搜寻各种文档和自己运行尝试也没有弄明白这两个插件机制的区别。
目前我看到的现象是frpc启动时触发NewWorkConn
然后当代理被连接时会同时触发NewWorkConn和NewUserConn
是否有该问题相关的详细说明文档能更详细的讲解这个区别
如能能提出几个使用场景那就更好了
   非常感谢~~

### frpc Version

0.46.0

### frps Version

0.46.0

### System Architecture

linux/amd64

### Configurations

```ini
[common]
bind_port = 7000
dashboard_port = 7500
allow_ports = 10000-50000
[plugin.notify]
addr = 127.0.0.1:3578
path = /handler
ops = Ping,NewProxy,CloseProxy,NewWorkConn,NewUserConn
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [x] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by blizard863** [comment]
跟源码。
