### ISSUE TITLE
why so many opened sock files? >1024

### ISSUE THREAD

**Issue by googlehim** [fatedier/frp#3339]
### Bug Description

systemctl status frps.service
http: Accept error: accept tcp [::]:7500: accept4: too many open files; retrying in 1s

lsof -p 431
.....
frps 431 noboty 1023u sock 0,8 0t0 47837121 protocol: TCPv6

### frpc Version

0.42.0

### frps Version

0.31.1

### System Architecture

linux/amd64

### Configurations

# [common] is integral section
[common]
# A literal address or host name for IPv6 must be enclosed
# in square brackets, as in "[::1]:80", "[ipv6-host]:http" or "[ipv6-host%zone]:80"
bind_addr = 0.0.0.0
bind_port = 7000

# udp port to help make udp hole to penetrate nat
bind_udp_port = 7001

# udp port used for kcp protocol, it can be same with 'bind_port'
# if not set, kcp is disabled in frps
kcp_bind_port = 7000

# specify which address proxy will listen for, default value is same with bind_addr
# proxy_bind_addr = 127.0.0.1

# if you want to support virtual host, you must set the http port for listening (optional)
# Note: http port and https port can be same with bind_port
vhost_http_port = 7000
vhost_https_port = 7000

# response header timeout(seconds) for vhost http server, default is 60s
# vhost_http_timeout = 60

# set dashboard_addr and dashboard_port to view dashboard of frps
# dashboard_addr's default value is same with bind_addr
# dashboard is available only if dashboard_port is set
dashboard_addr = 0.0.0.0
dashboard_port = 7500

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/commit/2cfba84e472c1de3e556049081fb24b5ffcc45a4

**Comment by googlehim** [comment]
> [2cfba84](https://github.com/fatedier/frp/commit/2cfba84e472c1de3e556049081fb24b5ffcc45a4)

this is a solution, i wand why and how to reduce it.
