### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by ancienter** [fatedier/frp#3340]
### Describe the feature request

服务端http和https允许设置一个默认转发端口，当没有任何frpc能匹配的时候把流量转发到默认的地址上去，这样当frpc和默认服务器在一起的时候就可以不用单独再启动frpc了

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
暂时没有这方面的考虑，可能会有非必要的流量劫持行为。
