### ISSUE TITLE
[Feature Request] Support Basic Auth in Service Health Check

### ISSUE THREAD

**Issue by MisteryMonster** [fatedier/frp#3341]
### Describe the feature request

I have host a service with Basic Auth I need a load-balancing. but Service Health Check don't support Basic Auth so health check won't work, maybe is returning a HTTP 400 Unauthorized error.

### Describe alternatives you've considered

Or supporting different HTTP response code in Service Health Check.

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
You can use `tcp` probe.
