### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by cancundeyingzi** [fatedier/frp#3342]
### Bug Description

http网页中使用https资源,浏览器会报错
`Access to XMLHttpRequest at 'xxx' from origin '' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
上述http网页和https资源均使用frp穿透,
192.168局域网没有此问题,Cloudflare Tunnels的http/https网页也没此问题
也就是说,在调用frp穿透的https资源时,只有frp穿透的http网页报错

### frpc Version

0.47

### frps Version

0.46

### System Architecture

win11

### Configurations

[main]
type = http
local_ip = 1
local_port = 5244
custom_domains = c
use_encryption=true
use_compression=true

[w]
type = https
local_ip = 1
local_port = 443
custom_domains = c
use_encryption=true
use_compression=true
proxy_protocol_version = v2

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
非frp的问题

自行在网页服务器添加`Access-Control-Allow-Origin`头
