### ISSUE TITLE
new proxy [web] type [http] error: type [http] not support when vhost_http_port is not set

### ISSUE THREAD

**Issue by qwertor-5678** [fatedier/frp#3344]
### Bug Description

 [W] [control.go:460] [a979649*******6e246] new proxy [web] type [http] error: type [http] not support when vhost_http_port is not set

### frpc Version

0.47.0

### frps Version

0.47.0

### System Architecture

linux/amd64

### Configurations

#######frps (tencent-cloud-Ubuntu Server 18.04.1 LTS 64bit)
[common]
bind_port = 7000
token = 1234567890

dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin
enable_prometheus = true

log_file = /var/log/frps.log
log_level = info
log_max_days = 3

#######frpc  (windows11-vmware-Ubuntu Server 18.04.1 LTS 64bit)
[common]
server_addr = xxxxxx-ip
server_port = 7000
token = 1234567890

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

[web]
type = http
local_ip = 127.0.0.1
local_port = 8080
subdomain = test.ggg456.com

### Logs

error-out
XXXXXXXXXX [web] start error [http] not support when vhost_http_port is not set

### Steps to reproduce

1. ./frps -c frps.ini &
2. ./frpc -c frpc.ini &
3.  error out

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
[#Accessing Internal Web Services with Custom Domains in LAN](https://letmegooglethat.com/?q=frp+not+support+when+vhost_http_port+is+not+set)

**Comment by superzjg** [comment]
日志很清楚：服务器未配置vhost_http_port

**Comment by Liuhuifeng** [comment]
-c 指定配置文件

**Comment by Doonkey** [comment]
frps.ini文件中添加
vhost_http_port = 80

frpc.ini文件中添加
#服务器ip
custom_domains = xxx.xxx.xxx.xxx

**Comment by jiusiguer** [comment]
Try to switch to the new version
