### ISSUE TITLE
以服务形式开机自启动报错

### ISSUE THREAD

**Issue by aiming0420** [fatedier/frp#3349]
### Bug Description

1，想让客户端开机自启动，使用winsw注册成服务开机自启动。
2，服务程序启动报错：dial tcp xxx:30000: connectex: A socket operation was attempted to an unreachable network.
3，使用延迟启动可以正常连接，说明启动时电脑还没有链接Internet的时候程序会退出而不是保持运行状态并继续尝试连接。
4，希望可以调整程序运行机制，启动的时候如果检测到网络错误不要退出，继续尝试连接服务端。

### frpc Version

0.47.0

### frps Version

0.47.0

### System Architecture

windows11 专业版 64位

### Configurations

#frpc
[common]
server_addr = xxx
server_port = 30000

#frps
[common]
bind_port = 30000

### Logs

2023/03/09 10:49:29 [W] [service.go:134] login to server failed: dial tcp xxx:30000: connectex: A socket operation was attempted to an unreachable network.
dial tcp xxx:30000: connectex: A socket operation was attempted to an unreachable network.

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
确认frpc已经注册服务启动程序后，剩下的就是仔细阅读配置文件指南。你的情况要设置：login_fail_exit = false

**Comment by aiming0420** [comment]
> 确认frpc已经注册服务启动程序后，剩下的就是仔细阅读配置文件指南。你的情况要设置：login_fail_exit = false

配置项太多，没仔细看。非常感谢回复！
