### ISSUE TITLE
window security center reports frp v0.48 has a virus

### ISSUE THREAD

**Issue by EWinner1** [fatedier/frp#3350]
### Bug Description

window security center reports frp v0.48 has a virus
window安全中心报告frp v0.48有病毒

### frpc Version

frpc 0.48.0

### frps Version

frps 0.48.0

### System Architecture

windows/amd64

### Configurations

[common]
server_addr = 0.0.0.0
server_port = 7001
token = **
local_ip = 192.168.31.200
type = udp

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by superzjg** [comment]
https://github.com/fatedier/frp/issues/2095

**Comment by limaofu** [comment]
Fuck the Windows !!!

**Comment by nirui** [comment]
Just saying, maybe go met a lawyer to see if there's any possibly for a legal action.

**Comment by nirui** [comment]
Just saying, maybe go meet a lawyer to see if there's any possibly for a legal action.

**Comment by XstormLeigh** [comment]
i am looking for the whitelist, does anyone know?
