### ISSUE TITLE
dial tcp 127.0.0.1:3389: connect: connection refused[Feature Request] 

### ISSUE THREAD

**Issue by 1500256797** [fatedier/frp#3354]
### Bug Description

server端已经搭建完成 端口18189已经开放
client端已经注册到sever端，并且在dashboard上是正常的。

使用mstsc远程访问18189时候，查看c端的控制台，发现如下报错导致无法连接。本地使用局域网地址是可以连接这个c端机器的。3389端口也是ok的。
dial tcp 127.0.0.1:3389: connect: connection refused[Feature Request] 

### frpc Version

docker pull snowdreamtech/frpc

### frps Version

docker pull snowdreamtech/frps

### System Architecture

windows/amd64

### Configurations

server端已经搭建完成 端口18189已经开放
client端已经注册到sever端，并且在dashboard上是正常的。

使用mstsc远程访问18189时候，查看c端的控制台，发现如下报错导致无法连接。本地使用局域网地址是可以连接这个c端机器的。3389端口也是ok的。
dial tcp 127.0.0.1:3389: connect: connection refused[Feature Request] 

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
`dial tcp 127.0.0.1:3389: connect: connection refused`

检查`127.0.0.1:3389`是否有程序在监听

**Comment by 1500256797** [comment]
C:\Users\jianjianjianjian>netstat -a

活动连接

  协议  本地地址          外部地址        状态
  TCP    0.0.0.0:135            DESKTOP-N2B3HNP:0      LISTENING
  TCP    0.0.0.0:445            DESKTOP-N2B3HNP:0      LISTENING
  TCP    0.0.0.0:2179           DESKTOP-N2B3HNP:0      LISTENING
  TCP    0.0.0.0:3389           DESKTOP-N2B3HNP:0      LISTENING
  TCP    0.0.0.0:5040           DESKTOP-N2B3HNP:0      LISTENING
  TCP    0.0.0.0:7680           DESKTOP-N2B3HNP:0      LISTENING
  TCP    0.0.0.0:19531          DESKTOP-N2B3HNP:0      LISTENING
  TCP    0.0.0.0:49664          DESKTOP-N2B3HNP:0      LISTENING
  TCP    0.0.0.0:49665          DESKTOP-N2B3HNP:0      LISTENING
  TCP    0.0.0.0:49666          DESKTOP-N2B3HNP:0      LISTENING
  TCP    0.0.0.0:49667          DESKTOP-N2B3HNP:0      LISTENING
  TCP    0.0.0.0:49668          DESKTOP-N2B3HNP:0      LISTENING
  TCP    0.0.0.0:49669          DESKTOP-N2B3HNP:0      LISTENING
  TCP    0.0.0.0:49670          DESKTOP-N2B3HNP:0      LISTENING
  TCP    0.0.0.0:57778          DESKTOP-N2B3HNP:0      LISTENING
  TCP    127.0.0.1:7890         DESKTOP-N2B3HNP:0      LISTENING

**Comment by lee-cq** [comment]
如果你使用的是Docker，那么你可能需要注意下Docker网络的连通性是否正常。

Docker内部的IP地址和主机的IP地址是不一样的，frpc 使用的127.0.0.1 时容器内部的地址，而容器内应该并没有监听3389端口（它在你的主机上）。

解决方案：容器中的FRPC不要使用127.0.0.1 而是使用你的局域网IP地址。
