### ISSUE TITLE
[Feature Request] After hiding server ip with cloudflare, connection failed

### ISSUE THREAD

**Issue by visualwind** [fatedier/frp#3355]
### Describe the feature request

Hello everyone，
I want to hide server ip,
server_addr = domain name

I use cloudflare to do DNS management.
When I set Proxy status as DNS only, connections are successful,
When I set Proxy status as Proxied, connetions failed.

Hiding server ip. Can this goal be done with frp?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by MANKUD** [comment]
You are trying to using frp proxy behind cloudflare proxy which will hide server original IP so the client cannot communicate with the server directly hence this will not work.
