### ISSUE TITLE
Authentication Loop

### ISSUE THREAD

**Issue by MANKUD** [fatedier/frp#3358]
### Bug Description

Hello on the latest version of FRP v0.48.0 the web dashboard seems to be repeatedly asking for authentication on every tab after successful login even a page refresh seems to ask for authentication again and again.

### frpc Version

v0.48.0

### frps Version

v0.48.0

### System Architecture

linux/amd64

### Configurations

FRP Dashboard Authentication Loop.

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
No configurations, no logs, no answer.

**Comment by MANKUD** [comment]
The issue seems to be not there when I tried to reinstall the latest version FRP after removing the updated version.
