### ISSUE TITLE
如何实现绑定多个域名

### ISSUE THREAD

**Issue by kingchaoliang** [fatedier/frp#3359]
### Describe the feature request

功能需求：我在甲骨文做了frp，然后穿透到自己的nas服务器。然后nas服务器里面绑定了多个网站

问题了解：
1.目前用很愚蠢的方法就是甲骨文单独建立多个网站配置对应的frp设置
2.我需要用到ssl，目前需要申请了证书后再甲骨文的配置里面填上证书且在nas的对应网站也要填写上证书。

有没有比较好的办法方便配置以实现我直接在nas的宝塔直接配置好。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by visualwind** [comment]
点对点，然后caddy反代

**Comment by Becods** [comment]
[#Accessing Internal Web Services with Custom Domains in LAN](https://github.com/fatedier/frp#accessing-internal-web-services-with-custom-domains-in-lan)

**Comment by vpei** [comment]
这个很简单呀，在frpc中设置就行，域名没有限制，再多域名也可以。

**Comment by litrycn** [comment]
frp支持通配符配置 https证书

frps配置：
```
[common]
bind_port = 80
vhost_http_port = 80
vhost_https_port = 443
```

服务端frpc1配置：
```
[common]
protocol = tcp
server_addr = 127.0.0.1
server_port = 80

[S*]
type = https
custom_domains = *.996.icu,*.fuck.996.icu
plugin = https2http
plugin_local_addr = 127.0.0.1:80
plugin_crt_path = /root/cert/996.icu_ecc/fullchain.cer
plugin_key_path = /root/cert/996.icu_ecc/996.icu.key
plugin_header_safe = https
```

其他环境frpc2配置
```
[common]
protocol = tcp
server_addr = 9.9.6.74
server_port = 80

[homeassistant]
type = http
local_ip = 192.168.0.1
local_port = 80
custom_domains = homeassistant.996.icu,homeassistant.fuck.996.icu
```
homeassistant.996.icu支持https访问： https://homeassistant.996.icu 

访问时路由貌似是 frps >> frpc1 >> frpc2

**Comment by vpei** [comment]
把所有域名都解析到frps的服务器，客户端自己配置相应域名和证书即可。
`
[www_domain_com_https]
type = https
custom_domains = www.domain.com

plugin = https2http
plugin_local_addr = 127.0.0.1:80

# HTTPS 证书相关的配置
plugin_crt_path = /etc/frp/domain.com.crt
plugin_key_path = /etc/frp/domain.com.key
plugin_host_header_rewrite = 127.0.0.1
plugin_header_X-From-Where = frp
`
