### ISSUE TITLE
https2http 子页面无法打开

### ISSUE THREAD

**Issue by netfun2000** [fatedier/frp#3360]
### Bug Description

https://github.com/fatedier/frp/issues/2482 这个已经closed了。

我也遇到类似问题。我是在给odoo做https2http:

[odoo_https2http]
type = https
plugin = https2http
plugin_local_addr = 127.0.0.1:8069
plugin_crt_path = /certs/odoo_public.crt
plugin_key_path = /certs/odoo.key
plugin_host_header_rewrite = odoo.xxxx.com
plugin_header_X-From-Where = frp
subdomain = odoo

跳转子页面的时候，不自动转https而是变成了http，例如访问：
https://odoo.xxxx.com，

Odoo要跳转到子页面odoo.xxxx.com/web，
而这时候，就变成了
http://odoo.xxxx.com/web
而不是
https://odoo.xxx.com/web

### frpc Version

0.48.0

### frps Version

0.24.1

### System Architecture

linux/arm64

### Configurations

[odoo_https2http]
type = https
plugin = https2http
plugin_local_addr = 127.0.0.1:8069
plugin_crt_path = /certs/odoo_public.crt
plugin_key_path = /certs/odoo.key
plugin_host_header_rewrite = odoo.xxxx.com
plugin_header_X-From-Where = frp
subdomain = odoo

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
redirect，链接这些都是应用前端自身的问题，建议了解一下相关的知识然后进行合理的配置。frp 这里无法解决特定服务的问题。
