### ISSUE TITLE
[Feature Request] does http_proxy support also public proxy without cradentials?

### ISSUE THREAD

**Issue by zaalgol** [fatedier/frp#3366]
### Describe the feature request

frp provides a options using a proxy. 
the pattern in the configuration is `http_proxy = http://user:pwd@192.168.1.128:8080`

But what about using a public proxy that doesn't require username and password?
I can use it like this: `http_proxy = http://192.168.1.128:8080`?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by Becods** [comment]
Practice is the sole criterion for testing truth.
