### ISSUE TITLE
Get HTTP/2 error on my fiveM server proxied through FRP

### ISSUE THREAD

**Issue by samskrillz** [fatedier/frp#3367]
### Bug Description

Hi all, I'm getting a little bit out of idea, and would like to see if anyone here could help me ...

So I have a FiveM server. I want to use FRP to tunnel the connection and then protect it against ddos attack (the server where frp is, are protect against ddos attack). My problem is, sometime I get this error ; **Failed handshake to server https://play.destiny-roleplay.com:30120/ - HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1) - CURL error code 92 (Stream error in the HTTP/2 framing layer)** when trying to connect on my FiveM Server. I tried to troubleshoot, but without success... I'm wondering if there is something I forget to activate and I get this error? Any help would be very appreciated Thank you!! 

### frpc Version

0.47.0

### frps Version

0.47.0

### System Architecture

linux/adm64

### Configurations

[common]
server_addr = 45.79.xxx.xxx
server_port = 7000
tls_enable = true
tls_cert_file = ./certificate.crt
tls_key_file = ./certificate.key
tls_trusted_ca_file = ./ca.crt
http2_enabled = true

[RDP1]
type = tcp
remote_port = 13388
local_ip = 10.0.2.15
local_port = 3389

[RDP2]
type = udp
remote_port = 13388
local_ip = 10.0.2.15
local_port = 3389

[RDP3]
type = tcp
remote_port = 13389
local_ip = 192.168.2.22
local_port = 3389

[RDP4]
type = udp
remote_port = 13389
local_ip = 192.168.2.22
local_port = 3389

[DESTINY1]
type = udp
remote_port = 30120
local_ip = 23.137.xx.xx
local_port = 301xx
use_encryption = true

[DESTINY2]
type = tcp
remote_port = 30120
local_ip = 23.137.xx.xx
local_port = 301xx
use_encryption = true

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by Becods** [comment]
You are using tcp instead of http.

That means the problem is caused by FIVEM or the client.

Try a direct connection to check if the error is caused by FIVEM.

**Comment by samskrillz** [comment]
> You are using tcp instead of http.
> 
> That means the problem is caused by FIVEM or the client.
> 
> Try a direct connection to check if the error is caused by FIVEM.

You seems right. Because the error only occur if I try to connect on the server with the "history"

but there is another way to connect, in FIVEM if you do "F8" you can do connect play.destiny-roleplay.com per example and it work each time... the only thing it's we want to let the user to reconnect with the "server history" as well. But, you seems right when you say that it's probably caused by Fivem. Thank you very much, will investigate more.

Have a nice one

**Comment by samskrillz** [comment]
Okay, I investigated a little bit more. I was curious, I installed Nginx and did the config. All work well. I got the same error. I tried another thing, I did F8 connect http/https://play.destiny-roleplay.com it connect and ... the as well in the server history !!! So I conclude it's a bug in the FIVEM client, which nobody here have control over that. Thanks for the reply very appreciate. Also FRPS it's a goat !!! Work so well to proxy thing under NAT. Have a nice one

**Comment by ax2009live** [comment]
@samskrillz   Is that the reason?

[ if you do not want connection sharing to happen, have a different IP address and/or ensure no overlaps in certificates](https://stackoverflow.com/questions/41785803/http2-the-421-misdirected-request-status-code-example)，

![image](https://user-images.githubusercontent.com/41521020/232186938-396b752f-f9e0-4865-af12-c519b26a7045.png)
