### ISSUE TITLE
客户端UI界面读取出来的配置文件中文乱码，请修复

### ISSUE THREAD

**Issue by ftf1218** [fatedier/frp#3369]
### Bug Description

客户端UI界面读取出来的配置文件中文乱码，请修复
![1679803819398_F326D832-3F41-48fe-9522-306CFB4E6ED1](https://user-images.githubusercontent.com/38513754/227754899-b6358052-52be-458e-9a0a-408d0f4563e3.png)

### frpc Version

0.48.0

### frps Version

0.48.0

### System Architecture

linux/amd64

### Configurations

客户端UI界面读取出来的配置文件中文乱码，请修复

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
![image](https://user-images.githubusercontent.com/35525491/227757866-1ea4c40a-14e5-4c81-9246-12e02162afa1.png)
无法复现

**Comment by programmer-zheng** [comment]
@ftf1218 配置文件使用utf8编码保存试下
