### ISSUE TITLE
如何方便处理大量域名？

### ISSUE THREAD

**Issue by HappyHam** [fatedier/frp#337]
当域名比较多时，在 c 端增删非常麻烦，有没有类似 default的参数，没有指定 custom_domains 的就都扔某个端口让web服务器去处理它们，就方便了。

**Comment by zhfish** [comment]
特权模式，泛解析

**Comment by HappyHam** [comment]
泛解析仍然是解析的一个域名的子域名而已啊，不是多个域名。

**Comment by yi** [comment]
把 frp 完全当通道用
公网服务器nginx做一套虚拟主机，全部转发给 frps
本地同样nginx 做一套虚拟主机，处理 frpc 发过来的请求
done

**Comment by 36bian** [comment]
服务器不需要安装nginx，直接在frps.ini中配置：
```shell
[common]
bind_port = 7000
vhost_http_port = 80
```

客户端frpc.ini中配置：
```shell
[common]
server_addr = 服务器ip
server_port = 7000

[web]
type = http
local_ip = 127.0.0.1
local_port = 80 # nginx端口
custom_domains = *.example.com
```
剩下的配置nginx解析就可以了。但是不支持https

**Comment by dick129418** [comment]
@36bian 大兄弟，我的0.16版本custom_domains = *.example.com为啥不行呢， 还是说这个是你猜测的

**Comment by 36bian** [comment]
> @36bian 大兄弟，我的0.16版本custom_domains = *.example.com为啥不行呢， 还是说这个是你猜测的

example.com 是示例域名，要改成自己的。

**Comment by dick129418** [comment]
frps 和 fprc 都启动成功后，通过 test.frps.com 就可以访问到内网的 web 服务。

需要注意的是如果 frps 配置了 subdomain_host，则 custom_domains 中不能是属于 subdomain_host 的子域名或者泛域名。

同一个 http 或 https 类型的代理中 custom_domains 和 subdomain 可以同时配置。

------------------》》》》》》》》》》》》
搞定了。看了首页说明，原来服务器端不能配置这个 subdomain_host
