### ISSUE TITLE
[Question] Does stcp support SSL certificate encryption?

### ISSUE THREAD

**Issue by HuengchI** [fatedier/frp#3370]
### Bug Description

Hi there,

I'm wondering if frp supports SSL certificate encryption for stcp. I want to secure my stcp connection using SSL certificates. Can someone please let me know if it's possible and how to configure it?

Thanks in advance for your help!

### frpc Version

latest

### frps Version

latest

### System Architecture

any supported

### Configurations

-

### Logs

-

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
Yes.
