### ISSUE TITLE
[Feature Request] frps服务端dashboard中增加端口映射来源

### ISSUE THREAD

**Issue by programmer-zheng** [fatedier/frp#3374]
### Describe the feature request

希望在服务端dashboard中增加映射来源端口显示，即同时显示`local_port`和`remote_port`

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
local port 是客户端配置，不会发给服务端，也不会暴露出来。
