### ISSUE TITLE
[Feature Request] Darwin release add launchd plist file

### ISSUE THREAD

**Issue by jifanghang** [fatedier/frp#3375]
### Describe the feature request

In the Linux releases you've added systemd files (frp*.service), which is very helpful. Perhaps you could add similar launchd files into the Darwin releases?

Big fan of your work btw.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Consider installing it via brew on MacOS since nobody is currently working on the deployment scripts.
