### ISSUE TITLE
嘗試在客戶端使用QUIC 報錯並中斷服務

### ISSUE THREAD

**Issue by jspantheonlab** [fatedier/frp#3378]
### Bug Description

已在服務段開啟QUIC， 但在客戶端啟用時 無法正常運作

```sh
docker run -it -v "/Users/user/frpc.ini:/frpc.ini" -p "7001:7000" --add-host=host.docker.internal:host-gateway --restart unless-stopped --name="frpc" fatedier/frpc:v0.48.0 --config frpc.ini
```

### frpc Version

v0.48.0

### frps Version

v0.48.0

### System Architecture

linux/amd64

### Configurations

```ini
#frps.ini
[common]
bind_port = 7000
dashboard_port = 7001
vhost_https_port=6033
vhost_http_port=6032
quic_bind_port = 7000
```

```ini
#frpc.ini
[common]
server_addr = 1.2.3.4
server_port = 7000
protocol = quic

[test]
type = http
custom_domains = example.com
local_port = 3003
local_ip = host.docker.internal
```

### Logs

```log
2023/03/29 05:15:58 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2023/03/29 05:16:03 [W] [service.go:134] login to server failed: timeout: no recent network activity
timeout: no recent network activity
2023/03/29 05:16:04 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2023/03/29 05:16:09 [W] [service.go:134] login to server failed: timeout: no recent network activity
timeout: no recent network activity
2023/03/29 05:16:09 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2023/03/29 05:16:14 [W] [service.go:134] login to server failed: timeout: no recent network activity
timeout: no recent network activity
2023/03/29 05:16:15 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2023/03/29 05:16:20 [W] [service.go:134] login to server failed: timeout: no recent network activity
timeout: no recent network activity
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by xingtongsf** [comment]
quic使用另外的端口，不要和kcp使用相同的端口，这个在作者帮助里没有明确，但是实际使用下来，kcp和quic不能使用同一端口

**Comment by xqzr** [comment]
开放 UDP 7000

**Comment by liujianying** [comment]
`#frps.ini
[common]
#服务器监听端口
bind_port = 7000
# quic 绑定的是 udp 端口，可以和 bind_port 一样客户端需要添加protocol = quic
quic_bind_port = 7000
#kcp_bind_port = 7000
#对网穿透http端口
#vhost_http_port =81
tcp_mux = false
#tls_enable = true
#管理页面防访问端口
dashboard_port = 7001
# dashboard's username and password are both optional，if not set,       default is admin.
dashboard_user = admin
dashboard_pwd = 123456`

`[common]
# frp 服务器的ip
server_addr = 124.222.13x.xx
# frp 服务端口
server_port = 7000
protocol = quic
tcp_mux = false
log_file = ./frpc.log

; log_file = /sdcard/frp_log/frpc.log
; log_level = info
; log_max_days = 3
; login_fail_exit = false

# 客户端配置web页面，配置后可以在web页面修改本地配置
admin_addr = 0.0.0.0
admin_port = 7400
admin_user = admin
admin_pwd = admin


[tcpadb]
type = tcp
local_ip = 127.0.0.1
# 手机调试端口
local_port = 5555
# sk = abcdefg
# frp服务穿透的端口
remote_port = 8555
# 对传输内容进行压缩
use_compression = true`
### 
报错如下
**2023/05/30 22:18:32 [W] [service.go:131] login to server failed: timeout: no recent network activity**

**Comment by jspantheonlab** [comment]
> 我也遇到了这个问题，题主标注了已关闭是怎么解决的呢

服務器UDP端口沒開放 看看防火牆
