### ISSUE TITLE
可以考虑增加一下混淆吗

### ISSUE THREAD

**Issue by wolfgangsk07** [fatedier/frp#3379]
### Describe the feature request

现在对frp链接的限制越来越严重了，我们单位从上个月开始了对frp链接的封杀，百度了一下，也有好多用户在搜索这个问题（搜索提示框里）。可以参考ssr那样做个链接混淆吗

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xingtongsf** [comment]
尝试直接使用tls加密接入就行，能骗过启明等大部分企业级防火墙。不建议增加混淆，加了这玩儿，整个大陆地区这软件就都别用了。分分钟就给你干掉

**Comment by fatedier** [comment]
请不要在被禁止的环境中使用，后果自负。
