### ISSUE TITLE
How can I frpc multiple clients(behind NAT) to one frps server?

### ISSUE THREAD

**Issue by Microos** [fatedier/frp#338]
I just tried with one client and it's wonderful! And is that possible for me to frpc multiple clients(behind NAT) to one frps server?

**Comment by fatedier** [comment]
It's no different with one client. Just note that each proxy name mustn't be same.

**Comment by Microos** [comment]
Do you mean I should create multiple `[common]` sections in `./frps.ini`with different listening `bind_ports` and for each client, the `./frpc.ini` contains a corresponding `server_port` plus a distinct `remote_port`?

**Comment by runique** [comment]
You could configure the frpc.ini with different proxy name. 
for example, one frpcs.ini:
[webaaa]
type = http
...

and another frpc.ini:
[webbbb]
type = http
...

you could get it surely.

**Comment by WooodHead** [comment]
What if I want to access two clients both with SSH?
