### ISSUE TITLE
[Feature Request] frp如何实现HTTP同一域名多端口访问

### ISSUE THREAD

**Issue by threerog** [fatedier/frp#3384]
### Describe the feature request

frp如何实现HTTP多端口访问
例如域名`my.baidu.com`实现如下需求
```
my.baidu.com:80=>192.168.5.1:80
my.baidu.com:81=>192.168.5.1:9568
my.baidu.com:82=>192.168.5.1:5244
my.baidu.com:90=>192.168.5.100:5000
```

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by programmer-zheng** [comment]
添加多个端口映射即可

**Comment by superzjg** [comment]
使用type=tcp，可以轻松实现。不同内网端口转发不同远程端口即可

**Comment by threerog** [comment]
> 使用type=tcp，可以轻松实现。不同内网站口转发不同远程口即可

我试了 确实非常nice，但是这种方案好像无法使用https访问

**Comment by superzjg** [comment]
> > 使用type=tcp，可以轻松实现。不同内网站口转发不同远程口即可
> 
> 我试了 确实非常nice，但是这种方案好像无法使用https访问

https本质上也是tcp，一样可以的。内网端口用https的，外网就是https访问。如果内网服务不支持https，就用frpc的插件转成https
