### ISSUE TITLE
[Feature Request] 请问能使用自己用IP地址生成的SSL证书吗？

### ISSUE THREAD

**Issue by itsyuyi** [fatedier/frp#3385]
### Describe the feature request

自己用IP地址制作了SSL证书，想通过vhost_https_port实现内网穿透。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
vhost 依靠 host 标头，而 ip访问 也会带 host 标头，你猜可不可以

**实践是检验真理的唯一标准**

**Comment by xqzr** [comment]
> vhost 依靠 host 标头，而 ip访问 也会带 host 标头，你猜可不可以
> 
> **实践是检验真理的唯一标准**

`vhost_http` 依靠 host。
`vhost_https` 依靠 SNI。但 IP 访问不带 SNI。

**Comment by xqzr** [comment]
`type = tcp`

**Comment by itsyuyi** [comment]
> vhost 依靠 host 标头，而 ip访问 也会带 host 标头，你猜可不可以
> 
> **实践是检验真理的唯一标准**

如何添加host标头？

**Comment by itsyuyi** [comment]
> > vhost 依靠 host 标头，而 ip访问 也会带 host 标头，你猜可不可以
> > **实践是检验真理的唯一标准**
> 
> `vhost_http` 依靠 host。 `vhost_https` 依靠 SNI。但 IP 访问不带 SNI。

你的意思是不能用IP地址生成的SSL证书？

**Comment by itsyuyi** [comment]
> `type = tcp`

frpc的配置文件里是按照这个配置的

**Comment by itsyuyi** [comment]
> 

亲测有效

**Comment by xqzr** [comment]
> > > vhost 依靠 host 标头，而 ip访问 也会带 host 标头，你猜可不可以
> > > **实践是检验真理的唯一标准**
> > 
> > 
> > `vhost_http` 依靠 host。 `vhost_https` 依靠 SNI。但 IP 访问不带 SNI。
> 
> 你的意思是不能用IP地址生成的SSL证书？

可以，但需要 `type = tcp`
