### ISSUE TITLE
[Feature Request] 大佬们能搞个服务端的Webui管理界面吗

### ISSUE THREAD

**Issue by zhuerhao** [fatedier/frp#3386]
### Describe the feature request

大佬们能搞个服务端的Webui管理界面吗，感觉要是每次想改配置都要手动去服务器上重新编辑配置文件然后重启，很麻烦，很且如果有图形化界面感觉也可以减少操作失误

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
[Admin UI](https://github.com/fatedier/frp#admin-ui)

[Server Plugin](https://github.com/fatedier/frp/blob/dev/doc/server_plugin.md)

或者

[Zo3i/frpMgr](https://github.com/Zo3i/frpMgr)

[ZeroDream-CN/SakuraPanel](https://github.com/ZeroDream-CN/SakuraPanel)

**Comment by pkxutao** [comment]
什么情况下会有频繁改配置的需求呢？

**Comment by VaalaCat** [comment]
@zhuerhao
https://github.com/VaalaCat/frp-panel
我有同样的需求，就写了一个，老哥可以看看可不可以满足你的需求，欢迎feature request
