### ISSUE TITLE
windows10 启动失败

### ISSUE THREAD

**Issue by rubjptg0004** [fatedier/frp#3387]
### Bug Description

在windows10 cmd中，无论运行frps.exe -c frps.ini 还是运行 frpc.exe -c frps.ini,都会直接退出，没有任何错误信息。但在某些电脑上可以正常运行。
失败运行后的并没有任何错误提示，日志文件也没有报错。
![image](https://user-images.githubusercontent.com/121129326/230067788-c7e3f06f-0757-4ecf-8b8a-9238675cf152.png)

### frpc Version

0.48

### frps Version

0.48

### System Architecture

windows/amd64

### Configurations

默认的

### Logs

2023/04/05 19:23:29 [I] [root.go:206] frps uses config file: frps.ini
2023/04/05 19:23:29 [I] [service.go:200] frps tcp listen on 0.0.0.0:7000
2023/04/05 19:23:29 [I] [service.go:317] Dashboard listen on 0.0.0.0:7500
2023/04/05 19:23:29 [I] [root.go:215] frps started successfully

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
开启debug，然后回报日志

https://github.com/fatedier/frp/blob/7678938c088c8d57367494ad53dd5c3b9e0cca35/conf/frps_full.ini#L65-L69
