### ISSUE TITLE
TCP正常，但是UDP不能正常建链

### ISSUE THREAD

**Issue by NeverSayd1e** [fatedier/frp#3388]
### Bug Description

TCP正常，但是UDP不能正常建链

### frpc Version

0.20

### frps Version

0.33

### System Architecture

koolshare merlin

### Configurations

#frps configuration:
[common]
bind_addr = 0.0.0.0
bind_port = 7000
bind_udp_port = 7001
kcp_bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
dashboard_addr = 0.0.0.0
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin
log_file = ./frps.log
log_level = info
log_max_days = 3
disable_log_color = false
token = xxxx
max_pool_count = 5
max_ports_per_client = 0
subdomain_host = frps.com
tcp_mux = true

# frpc configuration:
[common]
server_addr = xxxx
server_port = 7000
token = xxxx
log_file = /tmp/frpc.log
log_level = info
log_max_days = 3
tcp_mux = true
protocol = tcp
login_fail_exit = false
user = admin_dl
[ssh1]
type = tcp
local_ip = 192.168.3.81
local_port = 8090
remote_port = 54032
use_encryption = true
use_compression = true
[frpc_tcp]
type = tcp
local_ip = 192.168.3.81
local_port = 9999
remote_port = 54033
use_encryption = true
use_compression = true
[frpc_udp]
type = udp
local_ip = 192.168.3.81
local_port = 8888
remote_port = 54034
use_encryption = true
use_compression = true

### Logs

#FRPS log:
2023/04/05 20:32:25 [I] [udp.go:84] [1dbbbc0b25c38a2a] [admin_dl.frpc_udp] udp proxy listen port [54034]
2023/04/05 20:32:25 [I] [control.go:446] [1dbbbc0b25c38a2a] new proxy [admin_dl.frpc_udp] success
2023/04/05 20:32:25 [I] [tcp.go:63] [1dbbbc0b25c38a2a] [admin_dl.ssh1] tcp proxy listen port [54032]
2023/04/05 20:32:25 [I] [control.go:446] [1dbbbc0b25c38a2a] new proxy [admin_dl.ssh1] success
2023/04/05 20:32:25 [I] [tcp.go:63] [1dbbbc0b25c38a2a] [admin_dl.frpc_tcp] tcp proxy listen port [54033]
2023/04/05 20:32:25 [I] [control.go:446] [1dbbbc0b25c38a2a] new proxy [admin_dl.frpc_tcp] success
2023/04/05 20:32:25 [I] [proxy.go:103] [1dbbbc0b25c38a2a] [admin_dl.frpc_udp] get a new work connection: [60.21.100.130:54559]

2023/04/05 20:33:25 [W] [udp.go:102] [1dbbbc0b25c38a2a] [admin_dl.frpc_udp] read from workConn for udp error: i/o deadline reached
2023/04/05 20:33:25 [I] [proxy.go:103] [1dbbbc0b25c38a2a] [admin_dl.frpc_udp] get a new work connection: [60.21.100.130:54559]
2023/04/05 20:33:25 [I] [udp.go:157] [1dbbbc0b25c38a2a] [admin_dl.frpc_udp] sender goroutine for udp work connection closed

2023/04/05 20:34:25 [W] [udp.go:102] [1dbbbc0b25c38a2a] [admin_dl.frpc_udp] read from workConn for udp error: i/o deadline reached
2023/04/05 20:34:25 [I] [proxy.go:103] [1dbbbc0b25c38a2a] [admin_dl.frpc_udp] get a new work connection: [60.21.100.130:54559]
2023/04/05 20:34:25 [I] [udp.go:157] [1dbbbc0b25c38a2a] [admin_dl.frpc_udp] sender goroutine for udp work connection closed

#FRPC LOG
2023/04/05 20:01:58 [I] [proxy.go:350] [admin_dl.frpc_udp] incoming a new work connection for udp proxy, 221.214.170.113:7000
2023/04/05 20:01:58 [W] [proxy.go:365] [admin_dl.frpc_udp] read from workConn for udp error: EOF
2023/04/05 20:01:58 [I] [proxy.go:379] [admin_dl.frpc_udp] writer goroutine for udp work connection closed
2023/04/05 20:02:58 [I] [proxy.go:350] [admin_dl.frpc_udp] incoming a new work connection for udp proxy, 221.214.170.113:7000
2023/04/05 20:02:58 [W] [proxy.go:365] [admin_dl.frpc_udp] read from workConn for udp error: EOF
2023/04/05 20:02:58 [I] [proxy.go:379] [admin_dl.frpc_udp] writer goroutine for udp work connection closed

### Steps to reproduce

1. 创建FRPS，版本0.33
2. 创建FRPC，版本0.20
3. 创建UDP连接
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
更新frp

检查服务器是否开放 udp 端口
