### ISSUE TITLE
病毒引擎检测为恶意文件【Linux.Server-Proxy.Frp.Rimw】【已解决-#2095】

### ISSUE THREAD

**Issue by x-em** [fatedier/frp#3389]
### Bug Description

1.云服务器检测为高风险文件
![image](https://user-images.githubusercontent.com/12546949/230252286-a8e19fdd-8786-4a13-bcdb-23b5de84ed13.png)

### frpc Version

0.32.1

### frps Version

0.32.1

### System Architecture

linux/amd64

### Configurations

常规配置，http内网代理

**Comment by x-em** [comment]
运行三年了，今天云服务器有病毒检测到为严重病毒等级。尚不清楚是云服务的新的检测规则还是确实是漏洞

**Comment by xingtongsf** [comment]
这不是写了的很明白么。服务器代理服务病毒。可不就是这个功能么

**Comment by x-em** [comment]
看提示是这么显示的，所以我上面标了尚不清楚是否云服务器提供商的新检测规则。今天才检测到的。看了一下frp的文档跟资料没找到有这方面的说明提示

**Comment by liuliping0315** [comment]
腾讯：你这里有肉鸡。
楼主：我自己养得。

**Comment by zroorz** [comment]
新版win10也报毒了

**Comment by cuigege** [comment]
我这 win11 ，版本0.48 也抱毒了

**Comment by xqzr** [comment]
#2095

**Comment by x-em** [comment]
@xqzr 非常感谢
