### ISSUE TITLE
dashboard didn't use password to auth

### ISSUE THREAD

**Issue by mindfocus** [fatedier/frp#339]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.10.0

**What operating system and processor architecture are you using (`go env`)?**
aliyun linux 

**Steps to reproduce the issue:**
1.  config frps like the guide
2.  config dashboard_port 7500
3. config dashboard_user = admin
4. config dashboard_pwd = admin
5. open brower and type the target ip:7500
6. type admin 123123 and I get in

**Describe the results you received:**

I get into the dashboard website

**Describe the results you expected:**

Display password error.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
It's a bug and thanks for your report.
