### ISSUE TITLE
[Feature Request] Esxi8.0  是否可以运行frpc ?

### ISSUE THREAD

**Issue by zasufe** [fatedier/frp#3392]
### Describe the feature request

Esxi8.0  是否可以运行frpc ? 目前是在windows 上虚拟出来的vmware Esxi 8.0，通过ssh 连接esxi， 运行有报错
![image](https://user-images.githubusercontent.com/49631859/230838522-75a97f38-94bf-486c-a707-120402e86f35.png)

### Affected area

- [ ] Docs
- [x] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
**强烈不建议在esxi主机上运行frp
以及在windows里运行esxi**

```
chmod +x frpc
./frpc -c frpc.ini
```

**Comment by zsinba** [comment]
> ### Describe the feature request
> Esxi8.0 是否可以运行frpc ? 目前是在windows 上虚拟出来的vmware Esxi 8.0，通过ssh 连接esxi， 运行有报错 ![image](https://user-images.githubusercontent.com/49631859/230838522-75a97f38-94bf-486c-a707-120402e86f35.png)
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Affected area
> * [ ]  Docs
> * [x]  Installation
> * [ ]  Performance and Scalability
> * [ ]  Security
> * [ ]  User Experience
> * [ ]  Test and Release
> * [ ]  Developer Infrastructure
> * [ ]  Client Plugin
> * [ ]  Server Plugin
> * [ ]  Extensions
> * [ ]  Others

1. 在Esxi里跑，会增加很大的风险 ，不建议这样跑；
2. 你没跑起来，并不是因为frpc不支持，你可以试试chmod +x frpc 这样来跑。它是能跑出来的，并不是frpc不支持
