### ISSUE TITLE
[Feature Request] custom_domains 希望支持泛域名 *.b.a.com

### ISSUE THREAD

**Issue by yyimen** [fatedier/frp#3393]
### Describe the feature request

我在 frpc中配置了多域名,转到内部nginx,再根据域名及路径 重定向的不同的网站,如果frpc支持自定义*.a.com,就太好了

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
支持。

**Comment by yyimen** [comment]
实测 custom_domains配置中 *.a.com不行
