### ISSUE TITLE
[Feature Request] tcpmux文档使用疑惑

### ISSUE THREAD

**Issue by hsy-design** [fatedier/frp#3396]
### Describe the feature request

通过[上面的](https://gofrp.org/docs/features/tcpmux/)配置，frps 如果接收到 HTTP CONNECT 请求内容:
CONNECT test1 HTTP/1.1\r\n\r\n
该连接将会被路由到 proxy1 。

我是初学者可能有些误区:
1. http connect 是 http 1.1 建立tcp隧道的特殊请求
2. type tcpmux 是不是 listen同端口，根据Host的不同 进行路由的tcp转发？(类似ningx hostname)
3. 我该怎样使用测试它？
![image](https://user-images.githubusercontent.com/52811347/230940325-4fbdd248-869f-47bd-b94f-847f40146157.png)
curl 和浏览器直接访问 我看到了连接和关闭 怎么看有没有被frp route到frpc那边
4. 我用tcpmux代理nginx\ssh\squid都没成功，我该如何使用它？
[proxy1]
type = tcpmux
multiplexer = httpconnect
custom_domains = nginx
local_port = 80
[proxy2]
type = tcpmux
multiplexer = httpconnect
custom_domains = ssh
local_port = 22
[proxy3]
type = tcpmux
multiplexer = httpconnect
custom_domains = squid
local_port = 8080

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
你可以先从网上检索一些关于 CONNECT 代理方式的文章，学习一下。
