### ISSUE TITLE
是否能够增加流量统计

### ISSUE THREAD

**Issue by chmis8000** [fatedier/frp#34]
c发给s的流量, 还有发给访问者的流量（按C端区分），仅每天总量，目的是发现流量异常c端

**Comment by fatedier** [comment]
恩，感谢你的建议，这个功能是在规划中的，0.6 版本可以看到加了一个 dashboard_port 配置，计划之后提供一些查看、管理之类的功能。最近忙于其他项目，开发进度会比较慢，望理解。
