### ISSUE TITLE
[Feature Request] health check endpoint

### ISSUE THREAD

**Issue by f1-outsourcing** [fatedier/frp#3401]
### Describe the feature request

Nice job! I have been testing a bit with frp last view days.

for container environment it could be nice to have a health check url for the task frps/frpc. Something like http://0.0.0.0/health that returns 200 OK

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/db52f07d3492946037d85df7bfbfda0013481a27/server/dashboard.go#L39
