### ISSUE TITLE
 do http proxy request error

### ISSUE THREAD

**Issue by windzhu** [fatedier/frp#3403]
### Bug Description

2023/04/12 22:07:03 [W] [http.go:115] do http proxy request [host: testfrp1.cwwuyou.com:8090] error: net/http: HTTP/1.x transport connection broken: malformed MIME header: missing colon: "charset=utf-8"

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

windows/amd64

### Configurations

[http2]
type = http
local_port = 80
local_ip = 192.168.2.217
subdomain = testfrp1

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
From ChatGPT:

> What's the meaning of this error message: malformed MIME header: missing colon: "charset=utf-8"

This error message indicates that there is an issue with the format of the MIME header. Specifically, it is missing a colon after the header name "charset" and before the value "utf-8". The MIME header is used to specify the type of data being sent over the internet, and this error suggests that the header is not properly formatted, which could cause issues with the transmission or interpretation of the data.

**Comment by windzhu** [comment]
[http2]

type = http

local_port = 80

local_ip = 192.168.2.217

#remote_port = 8080

subdomain = testfrp1

#header_X-From-Where = frp

header_Content-Type = text/html; charset=UTF-8


OK ??










At 2023-04-13 10:01:18, "fatedier" ***@***.***> wrote:

From ChatGPT:

What's the meaning of this error message: malformed MIME header: missing colon: "charset=utf-8"

This error message indicates that there is an issue with the format of the MIME header. Specifically, it is missing a colon after the header name "charset" and before the value "utf-8". The MIME header is used to specify the type of data being sent over the internet, and this error suggests that the header is not properly formatted, which could cause issues with the transmission or interpretation of the data.
