### ISSUE TITLE
[Feature Request] 建议每个代理配置也可以配置连接池最大连接数

### ISSUE THREAD

**Issue by sourcetk** [fatedier/frp#3405]
### Describe the feature request

建议每个代理配置也可以配置连接池最大连接数， 
原因：我这边有个软件，有2个链路不同的需求：
1.tcp控制链路，只有第一个连接有控制权。
2.tcp数据链路，每个链路都可以传输数据。

如果tcp控制链路可以单独设定连接池大小就完美了

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
不太现实，并不会带来非常明显的提升。

并且由于 tcpmux 的机制，实际上目前不启用连接池也问题不大。
