### ISSUE TITLE
make报错

### ISSUE THREAD

**Issue by PUGE** [fatedier/frp#341]
cmd/frps/main.go:63: cannot use conf (type "github.com/vaughan0/go-ini".File) as type "github.com/fatedier/frp/vendor/github.com/vaughan0/go-ini".File in argument to config.LoadServerCommonConf
是我缺少安装某些包吗？

**Comment by fatedier** [comment]
你需要研究学习下 Go 的包管理机制以及使用 >= 1.8 的版本，和本项目无关。
