### ISSUE TITLE
[Feature Request] provide remote port at random

### ISSUE THREAD

**Issue by mlhess** [fatedier/frp#3411]
### Describe the feature request

This tool is awesome.   We are using it for tcp forwarding.  In the documented configuration, the client determines the port on the server.  Is there a way to have the server provide a random port to the client that would change?  This would have to be returned in some format that is parseable. 

### Affected area

- [ ] Docs
- [X] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by mlhess** [comment]
It looks like

```# if remote_port is 0, frps will assign a random port for you
remote_port = 0
```

Would solve this problem but on the client I don't get a port number assigned and on the server 
```
2023/04/15 13:37:52 [I] [tcp.go:66] [6db8faca558c3248] [sql] tcp proxy listen port [0]
2023/04/15 13:37:52 [I] [control.go:464] [6db8faca558c3248] new proxy [sql] type [tcp] success
```
It looks like it is trying to bind to 0

**Comment by fatedier** [comment]
You can find the port on client/server dashboard or use api to query.

**Comment by mlhess** [comment]
I just found the port on the dashboard.  Is there a way to get the client to spit it out in a manner that I could parse it?
