### ISSUE TITLE
[Feature Request]  Please allow the daemon to setuid to a particular user

### ISSUE THREAD

**Issue by yurivict** [fatedier/frp#3417]
### Describe the feature request

The daemon needs to read certificates as root, but then it is desirable to setuid to some unprivileged user.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by galdor** [comment]
Being able to drop privileges to a specific user and group would be really nice; this way frp can read files such as TLS key files as root then drop to a non-privileged user for security.

You can easily do that by:

- Fetching user and group info with `user.Lookup` and `user.LookupGroup`.
- Calling `syscall.Setgid` and `syscall.Setuid` (in this order).

**Comment by fatedier** [comment]
I am not inclined to introduce such complexity, as it is not a universal solution.

**Comment by yurivict** [comment]
Why is it not a universal solution?

A lot of network servers use such strategy to improve security.

**Comment by fatedier** [comment]
Doing it this way is very inelegant. A better approach would be a unified solution that is independent of the application.

**Comment by galdor** [comment]
If you want to support dynamic certificate renewal, you are in trouble. What NGINX does is to maintain both a master process running as root and one or more worker processes running as a non-privileged user. This would be a large and complex change though.

But Frp does not support certificate renewal, and restarting the daemon every couple months on certificate rotation is a non issue.
