### ISSUE TITLE
[Feature Request]内网https服务怎么代理出去 tcp https http2https 都试过了全都连不上 

### ISSUE THREAD

**Issue by maogeigei** [fatedier/frp#3418]
### Describe the feature request

试了以下三种方式都是500的错，还有那个frpc 配置里的remote_port 设置感觉没有作用，服务器查看对应端口 也没有监听
[http2https]
type = tcp
custom_domains = 123.43.23.133
plugin = http2https
plugin_local_addr = 127.0.0.1:7800
remote_port = 6202

[tcp]
type = tcp
custom_domains = 123.43.23.133
local_ip= 127.0.0.1
local_port = 7800
remote_port = 6202

[web2]
type = https
custom_domains = 123.43.23.133
local_port = 7800

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/233551388-2be38062-7be9-467c-9c92-de822753b68c.png)

**Comment by superzjg** [comment]
内网现存的https代理很简单啊，使用tcp和https都可以（不能用http2https）
用tcp时不需要写 域名custom_domains，但要写远程端口remote_port
使用时记得加https://

**Comment by shyandsy** [comment]
@superzjg 
尝试用tcp方式转内网https，不行啊

client端配置
```
[[proxies]]
name = "kubectl"
type = "tcp"
localIP = "192.168.101.20"
localPort = 6443
remotePort = 52000
```

服务端报错
```
2024-12-09 21:12:32.919 [I] [proxy/proxy.go:204] [b02c85b44184bf62] [kubectl] get a user connection [223.166.248.161:50422]
2024-12-09 21:12:32.919 [D] [server/control.go:272] [b02c85b44184bf62] get work connection from pool
2024-12-09 21:12:32.919 [D] [proxy/proxy.go:131] [b02c85b44184bf62] [kubectl] get a new work connection: [223.166.248.161:41344]
2024-12-09 21:12:32.919 [D] [proxy/proxy.go:261] [b02c85b44184bf62] [kubectl] join connections, workConn(l[172.16.19.89:50000] r[223.166.248.161:41344]) userConn(l[172.16.19.89:52000] r[223.166.248.161:50422])
2024-12-09 21:12:32.933 [D] [server/control.go:243] [b02c85b44184bf62] new work connection registered
2024-12-09 21:12:32.952 [D] [proxy/proxy.go:271] [b02c85b44184bf62] [kubectl] join connections closed
```

客户端没有任何log

**Comment by superzjg** [comment]
> @superzjg 尝试用tcp方式转内网https，不行啊
> 
> client端配置
> 
> ```
> [[proxies]]
> name = "kubectl"
> type = "tcp"
> localIP = "192.168.101.20"
> localPort = 6443
> remotePort = 52000
> ```
> 
> 服务端报错
> 
> ```
> 2024-12-09 21:12:32.919 [I] [proxy/proxy.go:204] [b02c85b44184bf62] [kubectl] get a user connection [223.166.248.161:50422]
> 2024-12-09 21:12:32.919 [D] [server/control.go:272] [b02c85b44184bf62] get work connection from pool
> 2024-12-09 21:12:32.919 [D] [proxy/proxy.go:131] [b02c85b44184bf62] [kubectl] get a new work connection: [223.166.248.161:41344]
> 2024-12-09 21:12:32.919 [D] [proxy/proxy.go:261] [b02c85b44184bf62] [kubectl] join connections, workConn(l[172.16.19.89:50000] r[223.166.248.161:41344]) userConn(l[172.16.19.89:52000] r[223.166.248.161:50422])
> 2024-12-09 21:12:32.933 [D] [server/control.go:243] [b02c85b44184bf62] new work connection registered
> 2024-12-09 21:12:32.952 [D] [proxy/proxy.go:271] [b02c85b44184bf62] [kubectl] join connections closed
> ```
> 
> 客户端没有任何log

可能跟网络环境有关，尝试改一下传输协议，比如frpc通用部分配置`transport.protocol = "quic"`，印象中见过这种情况

**Comment by yogaxu** [comment]
把http2https改成https2https就可以了
