### ISSUE TITLE
CheckAndEnableTLSServerConnWithTimeout-- non-TLS connection received on a TlsOnly server

### ISSUE THREAD

**Issue by woshibba** [fatedier/frp#3419]
### Bug Description

服务段报错[service.go:401] CheckAndEnableTLSServerConnWithTimeout error: non-TLS connection received on a TlsOnly server
我想弄一个tls加密的frp
服务端开启了tls_only= true
客户端开启了 tls_enable = true
客户端报错   [service.go:133] login to server failed: EOF

### frpc Version

frpc 0.46.0

### frps Version

frps 0.43.0

### System Architecture

linux/amd64

### Configurations

frpc.ini
server_addr = 
server_port = 
tls_enable = true
tls_cert_file = client.crt
tls_key_file = client.key
tls_trusted_ca_file = ca.crt

[ssh]
type = tcp
plugin = socks5
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000
**================================================**
frps.ini
[common]
bind_port = 
tls_only= true
tls_cert_file = cert/server.crt
tls_key_file = cert/server.key
tls_trusted_ca_file = cert/ca.crt

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by woshibba** [comment]
服务段报错应该是服务端报错，是我 写错了

**Comment by superzjg** [comment]
参考教程：
https://gofrp.org/docs/features/common/network/network-tls/
