### ISSUE TITLE
0.10客户端ssh的root登录后，立即被弹出，其他客户端没有这个问题。

### ISSUE THREAD

**Issue by baozhilin** [fatedier/frp#342]
0.10的frps和fprc在一台服务器上出现了root登录后立即被弹出的现象，提示：Server unexpectedly closed netwrok connection.
第一次调整时间后，恢复正常，但30分钟后又出现登录后被弹出。
第二次重新下载客户端，修改配置文件后，恢复正常，但2小时后又出现。

再其他服务器上一切正常，且问题服务器的80端口服务一直可以远程访问。且在dashboard里能看到问题服务器一直在online状态。ssh可以连接，输入账号和密码，但登录后就被弹出。

**Comment by fatedier** [comment]
可能是 ssh server 自身的问题或者是 ssh client 的配置问题。

**Comment by fatedier** [comment]
可能是 ssh server 自身的问题或者是 ssh client 的配置问题。

**Comment by fatedier** [comment]
经过测试，可能是被网关或防火墙设备主动断开双方的连接，下个版本可尝试使用 kcp 协议，也就是走 udp 发包。
