### ISSUE TITLE
[Feature Request] frpc配置代理后，baidu搜索ip。显示的还是原地址。没显示代理服务器地址。

### ISSUE THREAD

**Issue by wgf4242** [fatedier/frp#3420]
### Describe the feature request

代理配置如下。
```
[common]
server_addr = 1.2.3.4
server_port = 7000
authentication_method = token
authenticate_new_work_conns = true
token = xxxxxx

[socks5]
type = tcp
remote_port = 2121
plugin = socks5
```

用配置的代理上网没问题。但是显示的是原机的ip。用其他软件做代理服务器测的都是显示服务器的地址。
是要做其他设置么？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
你把frp当成什么了
```
A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet.
```
