### ISSUE TITLE
dashboard登录以后的有效期是多久

### ISSUE THREAD

**Issue by vinurs** [fatedier/frp#3421]
### Describe the feature request

可以设置有效期吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
浏览器会话。
没有这个选项。
