### ISSUE TITLE
frpc 客户端断网后，网络恢复后，无法访问，重启frpc客户端以后仍然不能访问，只有重启了frps服务器端以后才可以访问

### ISSUE THREAD

**Issue by gsdong** [fatedier/frp#3422]
### Bug Description

frpc 客户端断网后，网络恢复后，无法访问，重启frpc客户端以后仍然不能访问，只有重启了frps服务器端以后才可以访问，目前不知道出了什么问题，按理说，frpc 客户端断网后，重新重启应该是可以的，但是目前是不能访问的 必须要重启frps服务端，这中情况有没有可以检测的，如果出现这种情况，能用脚本检测出来吗？如果可以我就在frps 服务端做个脚本

### frpc Version

0.38

### frps Version

0.38

### System Architecture

linux/amd64

### Configurations

frpc 客户端断网后，网络恢复后，无法访问，重启frpc客户端以后仍然不能访问，只有重启了frps服务器端以后才可以访问，目前不知道出了什么问题，按理说，frpc 客户端断网后，重新重启应该是可以的，但是目前是不能访问的 必须要重启frps服务端，这中情况有没有可以检测的，如果出现这种情况，能用脚本检测出来吗？如果可以我就在frps 服务端做个脚本

### Affected area

- [X] Docs
- [X] Installation
- [X] Performance and Scalability
- [X] Security
- [X] User Experience
- [X] Test and Release
- [X] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [X] Extensions
- [X] Others

**Comment by Becods** [comment]
更新，然后反馈

![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/234476011-d1928c69-c501-4b89-a0ce-5ce7f7b0c041.png)
