### ISSUE TITLE
 get a user connection

### ISSUE THREAD

**Issue by fuyouping** [fatedier/frp#3423]
### Bug Description

服务端启动正常，
客户端启动正常
端口转发正常。

只是服务端日志，一直重复
2023/04/23 10:57:55 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:55 [D] [proxy.go:326] [6f0584ba2e8f1e9a] [ssh] join connections closed
2023/04/23 10:57:56 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [116.153.70.111:47862]
2023/04/23 10:57:56 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:56 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:56 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:56 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[116.153.70.111:47862])

其中出现2个IP
116.153.70.111  不知道哪里来的

222.93.218.214  客户端IP，正常的

服务器是 腾讯云轻应用。
请问一下，这样的日志重复显示，是有啥问题么。出现了一个不认识的IP   connection

### frpc Version

0.48.0

### frps Version

0.48.0

### System Architecture

linux/amd64

### Configurations

frps.ini

[common]
bind_port = 7007
vhost_http_port = 8080
vhost_https_port = 8443
token = abcdddd
log_level=trace

frpc.ini

[common]
server_addr = xx.xx.xx.xx
server_port = 7007
log_file = ./frpc.log
token = abcdddd

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 60022

### Logs

2023/04/23 10:57:49 [I] [service.go:500] [6f0584ba2e8f1e9a] client login info: ip [222.93.218.214:4607] version [0.48.0] hostname [] os [windows] arch [amd64]
2023/04/23 10:57:49 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:49 [I] [tcp.go:66] [6f0584ba2e8f1e9a] [ssh] tcp proxy listen port [60022]
2023/04/23 10:57:49 [I] [control.go:464] [6f0584ba2e8f1e9a] new proxy [ssh] type [tcp] success
2023/04/23 10:57:50 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [116.153.70.111:45600]
2023/04/23 10:57:50 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:50 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:50 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:50 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[116.153.70.111:45600])
2023/04/23 10:57:50 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:50 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [116.153.70.111:45850]
2023/04/23 10:57:50 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:50 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:50 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:50 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[116.153.70.111:45850])
2023/04/23 10:57:50 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:51 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [194.233.169.245:46262]
2023/04/23 10:57:51 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:51 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:51 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:51 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[194.233.169.245:46262])
2023/04/23 10:57:51 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:51 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [116.153.70.111:46092]
2023/04/23 10:57:51 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:51 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:51 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:51 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[116.153.70.111:46092])
2023/04/23 10:57:51 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:52 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [116.153.70.111:46344]
2023/04/23 10:57:52 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:52 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:52 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:52 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[116.153.70.111:46344])
2023/04/23 10:57:52 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:52 [D] [proxy.go:326] [6f0584ba2e8f1e9a] [ssh] join connections closed
2023/04/23 10:57:52 [D] [proxy.go:326] [6f0584ba2e8f1e9a] [ssh] join connections closed
2023/04/23 10:57:52 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [116.153.70.111:46594]
2023/04/23 10:57:52 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:52 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:52 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:52 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[116.153.70.111:46594])
2023/04/23 10:57:52 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:53 [D] [proxy.go:326] [6f0584ba2e8f1e9a] [ssh] join connections closed
2023/04/23 10:57:53 [D] [proxy.go:326] [6f0584ba2e8f1e9a] [ssh] join connections closed
2023/04/23 10:57:53 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [116.153.70.111:46856]
2023/04/23 10:57:53 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:53 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:53 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:53 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[116.153.70.111:46856])
2023/04/23 10:57:53 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:54 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [116.153.70.111:47098]
2023/04/23 10:57:54 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:54 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:54 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:54 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[116.153.70.111:47098])
2023/04/23 10:57:54 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:54 [D] [proxy.go:326] [6f0584ba2e8f1e9a] [ssh] join connections closed
2023/04/23 10:57:54 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [194.233.169.245:46266]
2023/04/23 10:57:54 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:54 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:54 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:54 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[194.233.169.245:46266])
2023/04/23 10:57:54 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:54 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [116.153.70.111:47348]
2023/04/23 10:57:54 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:54 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:54 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:54 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[116.153.70.111:47348])
2023/04/23 10:57:54 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:55 [D] [proxy.go:326] [6f0584ba2e8f1e9a] [ssh] join connections closed
2023/04/23 10:57:55 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [116.153.70.111:47616]
2023/04/23 10:57:55 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:55 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:55 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:55 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[116.153.70.111:47616])
2023/04/23 10:57:55 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:55 [D] [proxy.go:326] [6f0584ba2e8f1e9a] [ssh] join connections closed
2023/04/23 10:57:56 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [116.153.70.111:47862]
2023/04/23 10:57:56 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:56 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:56 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:56 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[116.153.70.111:47862])
2023/04/23 10:57:56 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:56 [D] [proxy.go:326] [6f0584ba2e8f1e9a] [ssh] join connections closed
2023/04/23 10:57:56 [D] [proxy.go:326] [6f0584ba2e8f1e9a] [ssh] join connections closed
2023/04/23 10:57:56 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [116.153.70.111:48120]
2023/04/23 10:57:56 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:56 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:56 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:56 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[116.153.70.111:48120])
2023/04/23 10:57:56 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:56 [D] [proxy.go:326] [6f0584ba2e8f1e9a] [ssh] join connections closed
2023/04/23 10:57:57 [D] [proxy.go:326] [6f0584ba2e8f1e9a] [ssh] join connections closed
2023/04/23 10:57:57 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [194.233.169.245:50316]
2023/04/23 10:57:57 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:57 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:57 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:57 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[194.233.169.245:50316])
2023/04/23 10:57:57 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:57 [I] [proxy.go:189] [6f0584ba2e8f1e9a] [ssh] get a user connection [116.153.70.111:48370]
2023/04/23 10:57:57 [D] [control.go:247] [6f0584ba2e8f1e9a] get work connection from pool
2023/04/23 10:57:57 [D] [proxy.go:114] [6f0584ba2e8f1e9a] [ssh] get a new work connection: [222.93.218.214:4607]
2023/04/23 10:57:57 [T] [proxy.go:298] [6f0584ba2e8f1e9a] [ssh] handler user tcp connection, use_encryption: false, use_compression: false
2023/04/23 10:57:57 [D] [proxy.go:316] [6f0584ba2e8f1e9a] [ssh] join connections, workConn(l[10.0.16.9:7007] r[222.93.218.214:4607]) userConn(l[10.0.16.9:60022] r[116.153.70.111:48370])
2023/04/23 10:57:57 [D] [control.go:218] [6f0584ba2e8f1e9a] new work connection registered
2023/04/23 10:57:57 [D] [service.go:450] Accept new mux stream error: read tcp 10.0.16.9:7007->222.93.218.214:4607: read: connection reset by peer

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
user connection 是指用户的ip（内网ip）
work connection 是指用户的外网ip

**Comment by Becods** [comment]
ssh被攻击

换stcp

**Comment by xqzr** [comment]
公网便是如此
