### ISSUE TITLE
frps control writer is closing

### ISSUE THREAD

**Issue by GUMEIK** [fatedier/frp#3424]
### Bug Description

frps每隔一段时间(大概70s左右)就会断开连接，无法使用，日志打印control writer is closing。断开链接后，大概4mins左右会重新连接

### frpc Version

0.38

### frps Version

0.38

### System Architecture

linux

### Configurations

version 0.38.0
BindPort 7000
BindUdpPort disable
Http Port 7080
Https Port 7081
Subdomain Host 

Max PoolCount 5
Max Ports Per Client no limit
HeartBeat Timeout 90

### Logs

2023/04/24 07:02:10 [W] [proxy.go:101] [899fcde41cf14fca] [nextcloud] failed to get work connection: control is closed

2023/04/24 07:02:21 [I] [dashboard_api.go:185] Http request: [/api/proxy/tcp]

2023/04/24 07:02:21 [I] [dashboard_api.go:179] Http response [/api/proxy/tcp]: code [200]

2023/04/24 07:06:33 [I] [service.go:447] [899fcde41cf14fca] client login info: ip [120.244.42.44:12236] version [0.38.0] hostname [] os [linux] arch [amd64]

2023/04/24 07:06:33 [I] [tcp.go:63] [899fcde41cf14fca] [nextcloud] tcp proxy listen port [9100]

2023/04/24 07:06:33 [I] [control.go:444] [899fcde41cf14fca] new proxy [nextcloud] success

2023/04/24 07:07:09 [I] [proxy.go:179] [899fcde41cf14fca] [nextcloud] get a user connection [120.244.42.44:11808]

2023/04/24 07:07:43 [I] [control.go:307] [899fcde41cf14fca] control writer is closing

2023/04/24 07:07:43 [I] [proxy.go:88] [899fcde41cf14fca] [nextcloud] proxy closing

2023/04/24 07:07:43 [W] [proxy.go:176] [899fcde41cf14fca] [nextcloud] listener is closed: accept tcp [::]:9100: use of closed network connection

2023/04/24 07:07:43 [I] [control.go:382] [899fcde41cf14fca] client exit success

2023/04/24 07:08:17 [I] [dashboard_api.go:70] Http request: [/api/serverinfo]

2023/04/24 07:08:17 [I] [dashboard_api.go:63] Http response [/api/serverinfo]: code [200]

### Steps to reproduce

1.查看日志：2023/04/24 07:07:09 [I] [proxy.go:179] [899fcde41cf14fca] [nextcloud] get a user connection [120.244.42.44:11808]
2.查看日志： 2023/04/24 07:07:43 [I] [control.go:307] [899fcde41cf14fca] control writer is closing

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
更新你的版本

用其他工具排查是否因为客服网络情况导致

**Comment by Crazyokd** [comment]
没想到我52.3版本又考古到这里来了。
有解决该问题吗？@GUMEIK
