### ISSUE TITLE
内存资源不足 无法处理此命令

### ISSUE THREAD

**Issue by naranakula** [fatedier/frp#3425]
### Bug Description

Frpc 连接没有问题，但是半小时左右就报错： 内存资源不足 无法处理此命令 。不是所有客户端都这样。
（其实机器内存很够 16G ，没有其他程序运行，虚拟内存也设置为4G-12G），报错的时候机器内存没有明显的增长。
![image](https://user-images.githubusercontent.com/6154391/234143859-c162bb64-bab0-40e1-880c-ba8a99410614.png)

### frpc Version

4.0-4.8

### frps Version

4.0-4.8

### System Architecture

windows server 2019 

### Configurations

任意配置在某些机器都会这样。有的机器是好的 有的机器就一直不可以。
这个错误和配置无关。
项目没有用udp。
报错的是 frpc客户端。
frps服务没有问题。

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
检查问题机硬盘空间是否充足

**Comment by naranakula** [comment]
关闭360 杀毒就可以了。 （我已经设置exe程序为信任了，文件夹也设置为信任了。）

**Comment by naranakula** [comment]
关闭360 杀毒  换成火绒安全。
