### ISSUE TITLE
How to remove offline client proxies from FRP dashboard

### ISSUE THREAD

**Issue by ksingh7** [fatedier/frp#3426]
### Bug Description

Every time when a FRP client connects and disconnects , it leaves an entry in FRP > Proxies list (API as well as dashboard). This entry stays forever , unless FRP server is restarted. 

I am looking for a way to clear FRP client list that are offline , either by API call or a ini file parameter (that i am missing)

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/9701902/234446819-2ec2c935-8494-4e6b-8094-70c17106e27d.png">

### frpc Version

0.48

### frps Version

0.48

### System Architecture

linux/amd64

### Configurations

- frpc.ini
```
[common]
bind_port = 7000
#vhost_http_port = 8000
subdomain_host = xxxx.cn
tls_enable = true
token = xxxx
# Frps Dashboard
dashboard_addr = 0.0.0.0
dashboard_port = 7500
# dashboard user and passwd for basic auth protect
dashboard_user = admin
dashboard_pwd = xxxx

# Frps Logs
#log_file = /var/log/frps.log
# trace, debug, info, warn, error
log_level = debug
log_max_days = 3

allow_ports = 30001-30025
#max_ports_per_client = 2
max_pool_count = 10
```
- frpc.ini
```
[common]
server_addr = xxxx
server_port = 7000
tls_enable = true
token = xxxx

[client-30001]
type = tcp
local_ip = 127.0.0.1
local_port = 8888
remote_port = 30001
use_encryption = true
use_compression = true
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/0214b974ddd928f74f0922dd28ee8aa9e5b0743f/pkg/metrics/mem/server.go#L77

It will be cleaned periodically, with a reserved time hard-coded for 7 days.

**Comment by ksingh7** [comment]
Thanks @fatedier  for response.
