### ISSUE TITLE
frpc reconnect memory leak

### ISSUE THREAD

**Issue by hqs136413** [fatedier/frp#3427]
### Bug Description

linux system Power on，frpc start：
frpc process：
![image](https://user-images.githubusercontent.com/52150091/234449200-af1c2d87-b565-4de7-a777-addab2908e92.png)

![image](https://user-images.githubusercontent.com/52150091/234449355-5a2ef589-82b1-440a-90c1-f7077d9db7e1.png)
When an exception occurs in the network，the frpc is Always reconnected
2-3minutes after：
![image](https://user-images.githubusercontent.com/52150091/234450309-072ed9f7-27bd-4e48-a5df-f55b96aad59b.png)
![image](https://user-images.githubusercontent.com/52150091/234450343-3f0be39d-cd3f-40fe-a1ba-04501a9f8d13.png)
![image](https://user-images.githubusercontent.com/52150091/234450358-191a6285-9b12-4afa-a18e-6a4fb9302e5d.png)

### frpc Version

0.37.0

### frps Version

0.37.0

### System Architecture

linux/arm32

### Configurations

[common]
tls_enable = true
server_addr = xxx
server_port = xxx
privilege_token = xxx
log_level = info
log_max_days = 3
protocol = tcp
log_file = /var/log/frpc.log
tcp_mux = true
login_fail_exit = false

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by hqs136413** [comment]
![image](https://user-images.githubusercontent.com/52150091/234450757-a63dcd80-faef-448c-9b31-8e4247c7e348.png)

**Comment by fatedier** [comment]
First, update to the latest version.
Then, run this test for an extended period to observe if the memory usage continues to increase. 
Two or three minutes are not sufficient for accurate results. It doesn't make any sense.

**Comment by hqs136413** [comment]
我们有长时间测试2-3天，一开始frpc进程占用4-5M，把网络断了几分钟后内存增加了2-3M，继续把网络断开，内存增加1-2M，当frpc进程内存增加到8-9M的时候，后面内存增加缓慢，网络断了一两天，也不过增加几百k，但是还是过一会累加4K左右。过一会继续累计4k。
![image](https://user-images.githubusercontent.com/52150091/234453177-7af47eb5-3838-4782-a064-26021453c5e1.png)

**Comment by hqs136413** [comment]
断开网络 ，frpc重连的时候，一开始内存增加很快，后面趋于平缓，一点点累加。

**Comment by hqs136413** [comment]
你好，之前看到frp0.32.1版本有修复frpc重连导致的内存泄露 #1722（https://github.com/fatedier/frp/pull/1722/commits/68118b08e2eddd0d17dd90049a816158fd89e485） ，我还遇到一个现象，网络一直正常的时候，frpc没有一直重连，内存也会慢慢增加一点。
