### ISSUE TITLE
tunnel reach wrong proxy-webside

### ISSUE THREAD

**Issue by cedricbieder** [fatedier/frp#3429]
### Bug Description

Hello,

I have to websides running on the same machine, on different ports. With the help of an proxy one of them is reachable under 
user.domain.com and the other is reachable under admin.domain.comhost_header_rewrite.

If I set the frpc client now to user.domain.com the tunnel always gets the admin.domain.com page.
I thought I can fix this but manipulating the request header-host with the "host_header_rewrite=user.domain.com" parameter but that shows now effect. In the webrequest the host is still mytunnelsubdomain.tunneldomain.com.

Does I understand the parameter wrong or does he just not work?

Is there another way to get the correct webpage?

### frpc Version

0.45

### frps Version

0.45

### System Architecture

linux/amd64

### Configurations

frpc:

[common]
token = mytoken
server_addr = tunneldomain.com
server_port = 443

[secret_ssh]
type = https
local_ip = user.domain.com
local_port = 443  
subdomain = mytunnelsubdomain
host_header_rewrite = user.domain.com

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
`host_header_rewrite` is only valid for HTTP, not HTTPS. frp cannot modify content that is encrypted via TLS.

**Comment by cedricbieder** [comment]
Right, thank you. It works with the https2https plugin and "plugin_host_header_rewrite".
