### ISSUE TITLE
frp有病毒，在release下载的，被小红伞查出有病毒，什么情况？

### ISSUE THREAD

**Issue by JackSeven** [fatedier/frp#3431]
### Bug Description

frp被杀毒软件查出有病毒？

### frpc Version

0.38

### frps Version

0.38

### System Architecture

linux/amd64

### Configurations

1. mac小红伞扫描，扫到了之前下载的frp安装文件，提示有病毒。啥情况？
[https://img1.imgtp.com/2023/04/29/ezJQXCya.png](url)

### Steps to reproduce

1. mac小红伞扫描，扫到了之前下载的frp安装文件，提示有病毒。啥情况？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
#2095

**Comment by JackSeven** [comment]
> #2095

谢谢。我看了。但是我和重新用源码自己编译了一遍，自己生成的bin目录下的frps和frpc就没有提示病毒。
