### ISSUE TITLE
some request

### ISSUE THREAD

**Issue by banjie123** [fatedier/frp#3432]
### Describe the feature request

I set the HeartbeatInterval of frpc to a negative number, so when the user end does not access the client resources, there will be no flow of heartbeat packets, and the client and server should not generate traffic. Why does wireshark still capture the client here? I haven't seen this part in the code for the traffic between the server and the server, can you give me some pointers?
![image](https://user-images.githubusercontent.com/89896919/236454885-9b125ece-1311-4073-b0ff-8ee1cf4b86c7.png)

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Maybe the heartbeat is from Yamux.
