### ISSUE TITLE
Security Vulnerability found

### ISSUE THREAD

**Issue by porcupineyhairs** [fatedier/frp#3433]
### Describe the feature request

Hi,

I would like to report a security vulnerability. Can you please [create a draft Github secuirty advisory](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/creating-a-repository-security-advisory) and add me as a collaborator?

cc @fatedier 

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
You can send me an email with the vulnerability details.
