### ISSUE TITLE
最新release版，有一个不明的连接，nrt12s36-in-f10.1e100.net:443，这域名看起来，像个后门地址

### ISSUE THREAD

**Issue by ikv163** [fatedier/frp#3435]
### Bug Description

frpc起来后，有一个不明的连接，nrt12s36-in-f10.1e100.net:443，这域名看起来，像个后门地址

### frpc Version

latest

### frps Version

latest

### System Architecture

linux amd64

### Configurations

[common]
server_addr = 86.20.47.29
server_port = 8081

[plugin_socks5]
type = tcp
remote_port = 8082
plugin = socks5

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by ikv163** [comment]
想请教一下这些外连的网络是干什么的？很多奇怪的域名
[Uploading image.png…]()

**Comment by ikv163** [comment]
![image](https://user-images.githubusercontent.com/36132976/236726011-a481eb31-9a27-41f0-964a-2c0544a5235f.png)

**Comment by fatedier** [comment]
1. frp 的代码开源，编译和打包上传流程也完全基于 github action，编译和打包脚本也是公开的，有任何问题都可以通过阅读代码和查询 github 相关服务的状态来确认是否有异常。
2. 这种情况的话，在不确定程序和代码安全的条件下，建议就不要再使用了，以免造成资产损失。如有需要ye 可以考虑商业软件，可能可以对你的环境安全更有保障。

**Comment by AlanWeekend** [comment]
https://support.google.com/faqs/answer/174717?hl=en
