### ISSUE TITLE
请教一下这些外连的网络是干什么的？我用的是release版（二进制），这些奇怪的域名

### ISSUE THREAD

**Issue by ikv163** [fatedier/frp#3436]
### Bug Description

能告诉我这些网络是干啥的吗？
![image](https://user-images.githubusercontent.com/36132976/236724578-eb907e09-cf9f-48ff-9b01-5386206a56f9.png)

### frpc Version

all

### frps Version

all

### System Architecture

linux amd64

### Configurations

[common]
server_addr = 86.20.47.29
server_port = 8081

[plugin_socks5]
type = tcp
remote_port = 8082
plugin = socks5

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by ikv163** [comment]
![image](https://user-images.githubusercontent.com/36132976/236726112-86819b1a-e172-4500-ba22-5144c3bf63cd.png)

**Comment by superzjg** [comment]
反正应该不是后门，因为frp是开源的，代码摆在那里。且关注度比较高。

**Comment by aa51513** [comment]
> 反正应该不是后门，因为frp是开源的，代码摆在那里。且关注度比较高。

有没有可能是引用的libiary里面有后门？

**Comment by fatedier** [comment]
Duplicate of #3435
