### ISSUE TITLE
强烈要求作者更改frp的网络包头，因为头包中有明显的0x 17 特征，这一点容易被国家防火墙迅速识别，最好能够去除这一特征

### ISSUE THREAD

**Issue by lhywc** [fatedier/frp#3439]
### Bug Description

这样的话，frp在中国国内环境中容易被识别出来，而且第一个包始终是283位，特征太明显了，请作者能够更改一下， 由于我的go不太熟悉，我是java python 方面的！

### frpc Version

latest

### frps Version

latest

### System Architecture

amd64

### Configurations

磊

### Logs

....

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by jsgzsjskj** [comment]
我使用校园网无法运行也是因为被拦截了嘛

**Comment by geekidentity** [comment]
@lhywc  能讲一下Java怎么做吗

**Comment by zhaoboy9692** [comment]
自己编译源码改呗

**Comment by fatedier** [comment]
frp 的功能和目的不包括混淆协议，去除特征。如果有需要可以使用其他的工具。

**Comment by hqvv** [comment]
frp 又不能用来科学上网，只是一个内网穿透的应用。
这东西挂在国内和国外的vps上都一样用... 

为什么怕被识别，怕被墙？

**Comment by Becods** [comment]
https://github.com/fatedier/frp/issues/1992 https://github.com/fatedier/frp/issues/3050

https://github.com/fatedier/frp/blob/da51adc27670f495478f50634462954319e4fc14/pkg/msg/msg.go#L61-L191

> 建议不要在公司禁止的情况下使用，安全风险和后果需要自负。

**Comment by zzzxxxfff** [comment]
> frp 又不能用来科学上网，只是一个内网穿透的应用。 这东西挂在国内和国外的vps上都一样用...
> 
> 为什么怕被识别，怕被墙？

有的地区frps在国外vps已经链接已经凉了

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/issues/3193#issuecomment-1332547301
