### ISSUE TITLE
连接失败会话结束

### ISSUE THREAD

**Issue by jsgzsjskj** [fatedier/frp#3440]
### Bug Description

frps服务器端正常运行，frpc客户端是Windows 在写好配置后执行：
D:\Software\frp_0.48.0_windows_amd64>frpc -c ./frpc.ini
2023/05/13 23:25:12 [W] [service.go:134] login to server failed: session shutdown
session shutdown
端口放行了的 服务器出入规则为全部 所有来源

### frpc Version

0.48.0

### frps Version

0.20.0

### System Architecture

liux/amd64，windows/amd64

### Configurations

[common]
tls_enable = true
server_addr = 52.12.85.198
server_port = 5443
token = 隐藏

[My Home PC]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 3390
custom_domains = frp.jskj.tk

[FTP_server]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 2222
custom_domains = ftp.jskj.tk

### Logs

frpc端无法启动
D:\Software\frp_0.48.0_windows_amd64>frpc.exe -c ./frpc.ini
2023/05/14 01:23:34 [W] [service.go:134] login to server failed: session shutdown
session shutdown
D:\Software\frp_0.48.0_windows_amd64>telnet 52.12.85.198 5443
DNS 服务器对区域没有权威。
D:\Software\frp_0.48.0_windows_amd64>curl 52.12.85.198:5443
curl: (52) Empty reply from server

frps服务器：
root@ip-172-31-23-192:~# ufw allow 5443
Skipping adding existing rule
Skipping adding existing rule (v6)
root@ip-172-31-23-192:~# ufw allow 3389
Skipping adding existing rule
Skipping adding existing rule (v6)
root@ip-172-31-23-192:~# ufw allow 3390
Skipping adding existing rule
Skipping adding existing rule (v6)
root@ip-172-31-23-192:~# ufw allow 22
Skipping adding existing rule
Skipping adding existing rule (v6)
root@ip-172-31-23-192:~# ufw allow 2222
Skipping adding existing rule
Skipping adding existing rule (v6)
root@ip-172-31-23-192:~# frps status
Frps (pid 44020) is running...
root@ip-172-31-23-192:~# frps restart

log
2023/05/13 11:32:42 [I] [service.go:128] frps tcp listen on 0.0.0.0:5443
2023/05/13 11:32:42 [I] [service.go:137] frps kcp listen on udp 0.0.0.0:5443
2023/05/13 11:32:42 [I] [service.go:161] http service listen on 0.0.0.0:5000
2023/05/13 11:32:42 [I] [service.go:182] https service listen on 0.0.0.0:5001
2023/05/13 11:32:42 [I] [service.go:205] Dashboard listen on 0.0.0.0:888
2023/05/13 11:32:42 [I] [root.go:190] Start frps success
2023/05/13 11:33:46 [I] [dashboard_api.go:67] Http request: [/api/serverinfo]
2023/05/13 11:33:46 [I] [dashboard_api.go:64] Http response [/api/serverinfo]: code [0]
2023/05/13 11:46:54 [I] [dashboard_api.go:67] Http request: [/api/serverinfo]
2023/05/13 11:46:54 [I] [dashboard_api.go:64] Http response [/api/serverinfo]: code [0]

### Steps to reproduce

1. 打开cmd
2. 进入frpc目录
3. 执行frpc -c ./frpc.ini
4. 校园网切换到手机热点关闭Windows防火墙依然这样

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by jsgzsjskj** [comment]
D:\Software\frp_0.48.0_windows_amd64>frpc.exe -c ./frpc.ini
2023/05/14 01:23:34 [W] [service.go:134] login to server failed: session shutdown
session shutdown

D:\Software\frp_0.48.0_windows_amd64>telnet 52.12.85.198 5443
DNS 服务器对区域没有权威。

**Comment by jsgzsjskj** [comment]
关闭防火墙，第二天校园网来网后尝试login to server failed: EOFEOF

**Comment by jsgzsjskj** [comment]
在frps设置kcp_bind_port = 5443
后 frp添加protocol = kcp后启动报错
login to server failed: connection write timeout
connection write timeout

**Comment by Becods** [comment]
被阻断了

更新frps

https://github.com/fatedier/frp/issues/1992 https://github.com/fatedier/frp/issues/3050

https://github.com/fatedier/frp/blob/db52f07d3492946037d85df7bfbfda0013481a27/conf/frpc_full.ini#L118-L119

https://github.com/fatedier/frp/blob/da51adc27670f495478f50634462954319e4fc14/pkg/msg/msg.go#L61-L191

> 建议不要在公司禁止的情况下使用，安全风险和后果需要自负。

**Comment by jsgzsjskj** [comment]
我在两端都添加过tle_ensble = yes依然不行的 被校园网拦截

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/issues/3193#issuecomment-1332547301

**Comment by jsgzsjskj** [comment]
> [第3193章（评论）](https://github.com/fatedier/frp/issues/3193#issuecomment-1332547301)

试了还是不行

**Comment by xqzr** [comment]
> > [第3193章（评论）](https://github.com/fatedier/frp/issues/3193#issuecomment-1332547301)
> 
> 试了还是不行

`protocol = quic`

**Comment by jsgzsjskj** [comment]
> > > [第3193章（评论）](https://github.com/fatedier/frp/issues/3193#issuecomment-1332547301)
> > 
> > 
> > 试了还是不行
> 
> `protocol = quic`

加了后是超时login to server failed: timeout: no recent network activity
timeout: no recent network activity

**Comment by xqzr** [comment]
> > > > [第3193章（评论）](https://github.com/fatedier/frp/issues/3193#issuecomment-1332547301)
> > > 
> > > 
> > > 试了还是不行
> > 
> > 
> > `protocol = quic`
> 
> 加了后是超时登录到服务器失败：超时：无最近的网络活动超时：没有最近的网络活动

放行 相应 UDP 端口

**Comment by jsgzsjskj** [comment]
> > > > > [第3193章（评论）](https://github.com/fatedier/frp/issues/3193#issuecomment-1332547301)
> > > > 
> > > > 
> > > > 试了还是不行
> > > 
> > > 
> > > `protocol = quic`
> > 
> > 
> > 加了后是超时登录到服务器失败：超时：无最近的网络活动超时：没有最近的网络活动
> 
> 放行 相应 UDP 端口

我是vps出入规则是全部流量
