### ISSUE TITLE
frp always transfers my request from 443 to 80 port.

### ISSUE THREAD

**Issue by Kidsunbo** [fatedier/frp#3441]
### Bug Description

I use frp to expose my website to public for testing. I would like to serve 80 and 443 port.
On the local machine, I start nginx to listen to 80 and 443 with SSL certificate signed to the domain. I found that the requests are always transfer to 80 port even I type https in the browser. After I delete the 80 port server block, it reports 404. So how could I transfer to 443?

### frpc Version

0.48.0

### frps Version

No idea, it's some free node.

### System Architecture

Linux arm

### Configurations

[kies_cf_http]
type = http
local_ip = 192.168.0.106
local_port = 80
custom_domains = kies.cf
host_header_rewrite = kies.cf

[kies_cf_https]
type = https
local_ip = 192.168.0.106
local_port = 443
custom_domains = kies.cf
host_header_rewrite = kies.cf

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
It depends on your nginx configuration.

**Comment by Kidsunbo** [comment]
> 

Yeah sure. But I am sure that the nginx configuration is ok. I can access both 80 and 443 in my local network. I guess it's caused by cloudflare. I will test it again. Thanks.
