### ISSUE TITLE
[Feature Request] - new release 0.48.1 for fix el-popover bug (#3413)

### ISSUE THREAD

**Issue by manprint** [fatedier/frp#3442]
### Describe the feature request

Hi @fatedier 

When can you release version 0.48.1 which contains the fix for the dashboard el-popover bug (#3413)?
It's a very boring bug and doesn't allow you to fully use the dashboard!
Thank you so much for your work and great frp project.
I wish you the best.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
This modification will be released in version 0.49.0. 

However, due to some incompatible changes we have in this version, the release date of this version is still uncertain.

You can download the code and compile the content you need by yourself for now.

**Comment by manprint** [comment]
I compiled the sources. Everything OK. The fix works.
Thank you very much

**Comment by jsgzsjskj** [comment]
> 此修改将在 0.49.0 版本中发布。
> 
> 但是，由于我们在此版本中进行了一些不兼容的更改，因此该版本的发布日期仍不确定。
> 
> 您可以先下载代码，自行编译您需要的内容。

不会编译又想正常用呢，希望作者在0.49.0中可以解决被墙的问题
