### ISSUE TITLE
start error: router config conflict ( Using http/https with subdomain )

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [fatedier/frp#3443]
### Bug Description

I can't establish a second connection to the server even using two different subdomains.

### frpc Version

0.48.0

### frps Version

0.48.0

### System Architecture

linux/amd64

### Configurations

1 )  server 

[common]
bind_addr = 0.0.0.0
bind_port = 15000
bind_udp_port = 7001
kcp_bind_port = 7000
vhost_http_port = 1580
vhost_https_port = 1443
tcpmux_httpconnect_port = 1337
dashboard_addr = 0.0.0.0
dashboard_port = 1300
dashboard_user = admin
dashboard_tls_mode = false
enable_prometheus = true
log_file = /var/log/frps.log
log_level = trace
log_max_days = 3
disable_log_color = false
detailed_errors_to_client = true
authentication_method = token
authenticate_heartbeats = false
authenticate_new_work_conns = false
token = XXXXXXXXXX
oidc_issuer =
oidc_audience =
oidc_skip_expiry_check = false
oidc_skip_issuer_check = false
allow_ports = 2000-3000,3001,3003,4000-50000
max_pool_count = 5
max_ports_per_client = 0
tls_only = false
subdomain_host = dominio.com.br
udp_packet_size = 1500
pprof_enable = false

2 ) cliente1

[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 15000
log_file = ./frpc.log
log_level = trace
log_max_days = 3
token = XXXXXXXXXX

[cliente1]
type = http
local_ip = 127.0.0.1
local_port = 80
remote_port = 0
subdomain = cliente1
custom_domains = dominio.com.br

3 ) cliente2

[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 15000
log_file = ./frpc.log
log_level = trace
log_max_days = 3
token = XXXXXXXXXX

[cliente2]
type = http
local_ip = 127.0.0.1
local_port = 80
remote_port = 0
subdomain = cliente2
custom_domains = dominio.com.br

### Logs

1 ) Server 

sudo cat /var/log/frps.log
2023/05/14 19:52:22 [D] [vhost.go:214] http request for host [] path [] httpUser [] not found
2023/05/14 19:53:13 [T] [service.go:423] start check TLS connection...
2023/05/14 19:53:13 [T] [service.go:432] check TLS connection success, isTLS: false custom: false
2023/05/14 19:53:13 [I] [service.go:500] [2bbbda8e03a6c7a6] client login info: ip [45.xxx.xxx.127:53590] version [0.48.0] hostname [] os [linux] arch [amd64]
2023/05/14 19:53:13 [D] [control.go:218] [2bbbda8e03a6c7a6] new work connection registered
2023/05/14 19:53:13 [I] [http.go:95] [2bbbda8e03a6c7a6] [cliente1] http proxy listen for host [dominio.com.br] location [] group [], routeByHTTPUser []
2023/05/14 19:53:13 [I] [http.go:128] [2bbbda8e03a6c7a6] [cliente1] http proxy listen for host [cliente1.dominio.com.br] location [] group [], routeByHTTPUser []
2023/05/14 19:53:13 [I] [control.go:464] [2bbbda8e03a6c7a6] new proxy [cliente1] type [http] success
2023/05/14 19:53:43 [D] [control.go:493] [2bbbda8e03a6c7a6] receive heartbeat
2023/05/14 19:54:13 [D] [control.go:493] [2bbbda8e03a6c7a6] receive heartbeat
2023/05/14 19:54:34 [T] [service.go:423] start check TLS connection...
2023/05/14 19:54:34 [T] [service.go:432] check TLS connection success, isTLS: false custom: false
2023/05/14 19:54:34 [I] [service.go:500] [18e05a801e851126] client login info: ip [45.xxx.xxx.127:53542] version [0.48.0] hostname [] os [windows] arch [amd64]
2023/05/14 19:54:34 [I] [proxy.go:98] [18e05a801e851126] [cliente2] proxy closing
2023/05/14 19:54:34 [W] [control.go:460] [18e05a801e851126] new proxy [cliente2] type [http] error: router config conflict
2023/05/14 19:54:34 [D] [control.go:218] [18e05a801e851126] new work connection registered

2 ) Cliente 1

2023/05/14 20:00:54 [T] [root.go:212] start frpc service for config file [frpc.ini]
2023/05/14 20:00:54 [I] [service.go:299] [75b5c28988ce1718] login to server success, get run id [75b5c28988ce1718], server udp port [7001]
2023/05/14 20:00:54 [I] [proxy_manager.go:142] [75b5c28988ce1718] proxy added: [cliente1]
2023/05/14 20:00:54 [T] [proxy_wrapper.go:171] [75b5c28988ce1718] [cliente1] change status from [new] to [wait start]
2023/05/14 20:00:54 [I] [control.go:172] [75b5c28988ce1718] [cliente1] start proxy success

3 ) Cliente 2

2023/05/14 19:37:12 [I] [service.go:299] [9c60db41bb005cdc] login to server success, get run id [9c60db41bb005cdc], server udp port [7001]
2023/05/14 19:37:12 [I] [proxy_manager.go:142] [9c60db41bb005cdc] proxy added: [cliente2]
2023/05/14 19:37:12 [W] [control.go:170] [9c60db41bb005cdc] [cliente2] start error: router config conflict
2023/05/14 19:37:42 [D] [control.go:286] [9c60db41bb005cdc] send heartbeat to server
2023/05/14 19:37:42 [D] [control.go:317] [9c60db41bb005cdc] receive heartbeat from server
2023/05/14 19:37:42 [W] [control.go:170] [9c60db41bb005cdc] [cliente2] start error: router config conflict
2023/05/14 19:38:12 [D] [control.go:286] [9c60db41bb005cdc] send heartbeat to server
2023/05/14 19:38:12 [D] [control.go:317] [9c60db41bb005cdc] receive heartbeat from server
2023/05/14 19:38:13 [W] [control.go:170] [9c60db41bb005cdc] [cliente2] start error: router config conflict
2023/05/14 19:38:42 [D] [control.go:286] [9c60db41bb005cdc] send heartbeat to server
2023/05/14 19:38:42 [D] [control.go:317] [9c60db41bb005cdc] receive heartbeat from server
2023/05/14 19:38:43 [W] [control.go:170] [9c60db41bb005cdc] [cliente2] start error: router config conflict
2023/05/14 19:54:33 [I] [service.go:299] [18e05a801e851126] login to server success, get run id [18e05a801e851126], server udp port [7001]
2023/05/14 19:54:33 [I] [proxy_manager.go:142] [18e05a801e851126] proxy added: [cliente2]
2023/05/14 19:54:33 [W] [control.go:170] [18e05a801e851126] [cliente2] start error: router config conflict
2023/05/14 19:55:03 [D] [control.go:286] [18e05a801e851126] send heartbeat to server
2023/05/14 19:55:03 [D] [control.go:317] [18e05a801e851126] receive heartbeat from server
2023/05/14 19:55:03 [W] [control.go:170] [18e05a801e851126] [cliente2] start error: router config conflict
2023/05/14 19:55:33 [D] [control.go:286] [18e05a801e851126] send heartbeat to server
2023/05/14 19:55:33 [D] [control.go:317] [18e05a801e851126] receive heartbeat from server
2023/05/14 19:55:33 [W] [control.go:170] [18e05a801e851126] [cliente2] start error: router config conflict

### Steps to reproduce

1.  Server 
2. sudo /usr/bin/frps -c /etc/frp/frps.ini
3. Cliente 1
4. sudo ./frpc -c frpc.ini
5. Cliente 2
6. sudo ./frpc -c frpc.ini
...

### Affected area

- [X] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others
![image](https://github.com/fatedier/frp/assets/1152426/c66e8c65-8942-4bd5-b85d-c53062f0c5ff)

**Comment by fatedier** [comment]
```
[cliente1]
type = http
...
custom_domains = dominio.com.br

3 ) cliente2
[cliente2]
...
custom_domains = dominio.com.br
```

You cannot use the same `custom_domains`.

**Comment by andersondeoliveiramachado** [comment]
> subdomain

I'm using different subdomains, is it still necessary to use different domains?

**Comment by fatedier** [comment]
I am not sure why you are using `custom_domains`. Perhaps you can remove it.

**Comment by andersondeoliveiramachado** [comment]
It worked using only subdomain , without having to specify custom_domains.
