### ISSUE TITLE
What ports to open for FRP client? Getting token mismatch error

### ISSUE THREAD

**Issue by kennethban** [fatedier/frp#3445]
### Bug Description

I am using frpc from a system with a firewall with default open ports 80,443. What other ports should be open to allow access?

I have requested port 7000 to be opened as the frps bind port is 7000. I am using the token authentication

When I attempt to connect with frpc on this firewalled system (ports 80,443,7000 open), it reports a token mismatch:
[E] [service.go:295] token in login doesn't match token from configuration

When I use the same frpc.ini file on another system without a firewall, it connects properly without any token error

I assume that there are some other ports (TCP/UDP) that I need to open?

### frpc Version

0.37

### frps Version

0.37

### System Architecture

linux/amd4

### Configurations

**frpc.ini**

[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 7000
privilege_token = xxx xxx xx xx

[notebook]
type = http
local_ip = 127.0.0.1
local_port = 8888
custom_domains = xxx.xxx.xxx

**frps.ini**
[common]
bind_port = 7000
vhost_http_port = 14000

authentication_method = token
token = xxx xxx xxx x

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [x] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
It should be `token`, not `privilege_token`.

**Comment by kennethban** [comment]
Oh my bad, i think i used an old keyword 'privileged_token' in the ini file. Works now when i changed it to 'token'
