### ISSUE TITLE
看来可能是我自己的问题

### ISSUE THREAD

**Issue by huxuansong** [fatedier/frp#3446]
tcping nginx 和 apache也是不通，
可能nginx和apache能够访问的原因是ipv6
因为我同时解析了ipv6的的ddns

非常感谢作者能提供这么优秀的程序，
我也算得上是Frp的老用户了，从0.16版本就开始使用至今

反馈一个Frps在多线多播下的一个小问题，猜测某一设定与默认路由有关

我使用的openwrt软路由，IP是192.168.1.1

电信、联通双线双拨，分别获得公网IPv4，
但只有电信线路绑定DDNS动态域名ddnsct.XXX.com

然后我在这个openwrt上运行了**frps**最新版0.48
frpc客户端使用的是电信动态ddns域名ddnsct.XXX.com连接

如果openwrt设定默认路由/网关为电信线路的时候，frpc客户端连接frps正常，frp系统正常工作
但如果openwrt设定默认路由/网关为联通线路的时候，frpc客户端就无法连接上frps了

这个小问题猜测frps的某一项设定似乎与默认路由有关

而apache和nginx在上述切换默认路由/网关的情况下，是可以正常工作的
即：即使切换默认路由/网关为联通的时候，电信的动态域名，也是可以正常访问

不知道作者能否解决这个特殊情况下的小问题，谢谢

附：

frpc日志应该显示的是连接超时

2023/05/20 00:00:02 [I] [service.go:211] [a6ac36de3ccd54ea] try to reconnect to server...
2023/05/20 00:00:12 [W] [service.go:214] [a6ac36de3ccd54ea] reconnect to server error: dial tcp 27.159.132.213:17010: i/o timeout, wait 20s for another retry
2023/05/20 00:00:32 [I] [service.go:211] [a6ac36de3ccd54ea] try to reconnect to server...
2023/05/20 00:00:42 [W] [service.go:214] [a6ac36de3ccd54ea] reconnect to server error: dial tcp 27.159.132.213:17010: i/o timeout, wait 20s for another retry
2023/05/20 00:01:00 [I] [service.go:211] [a6ac36de3ccd54ea] try to reconnect to server...
2023/05/20 00:01:10 [W] [service.go:214] [a6ac36de3ccd54ea] reconnect to server error: dial tcp 27.159.132.213:17010: i/o timeout, wait 20s for another retry
2023/05/20 00:01:28 [I] [service.go:211] [a6ac36de3ccd54ea] try to reconnect to server...
2023/05/20 00:01:38 [W] [service.go:214] [a6ac36de3ccd54ea] reconnect to server error: dial tcp 27.159.132.213:17010: i/o timeout, wait 20s for another retry
2023/05/20 00:01:57 [I] [service.go:211] [a6ac36de3ccd54ea] try to reconnect to server...
2023/05/20 00:02:07 [W] [service.go:214] [a6ac36de3ccd54ea] reconnect to server error: dial tcp 27.159.132.213:17010: i/o timeout, wait 20s for another retry

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
在tcping nginx和frp时切换网关

然后回报结果

**Comment by huxuansong** [comment]
> 在tcping nginx和frp时切换网关
> 
> 然后回报结果

你好，tcping frp端口的时候切换网关如下
切换之后就No response了，切换之前是open的

Probing 27.159.132.213:17010/tcp - Port is open - time=6.880ms
Probing 27.159.132.213:17010/tcp - Port is open - time=6.818ms
Probing 27.159.132.213:17010/tcp - Port is open - time=5.863ms
Probing 27.159.132.213:17010/tcp - Port is open - time=6.807ms
Probing 27.159.132.213:17010/tcp - Port is open - time=6.848ms
Probing 27.159.132.213:17010/tcp - Port is open - time=7.342ms
Probing 27.159.132.213:17010/tcp - Port is open - time=12.071ms
Probing 27.159.132.213:17010/tcp - Port is open - time=6.768ms
Probing 27.159.132.213:17010/tcp - Port is open - time=7.299ms
Probing 27.159.132.213:17010/tcp - Port is open - time=7.919ms
Probing 27.159.132.213:17010/tcp - Port is open - time=5.848ms
Probing 27.159.132.213:17010/tcp - Port is open - time=7.083ms
Probing 27.159.132.213:17010/tcp - Port is open - time=7.543ms
Probing 27.159.132.213:17010/tcp - Port is open - time=6.175ms
Probing 27.159.132.213:17010/tcp - No response - time=2010.053ms
Probing 27.159.132.213:17010/tcp - No response - time=2012.726ms
Probing 27.159.132.213:17010/tcp - No response - time=2003.009ms
Probing 27.159.132.213:17010/tcp - No response - time=2013.992ms
Probing 27.159.132.213:17010/tcp - No response - time=2011.968ms
Probing 27.159.132.213:17010/tcp - No response - time=2011.147ms
Probing 27.159.132.213:17010/tcp - No response - time=2015.039ms
Probing 27.159.132.213:17010/tcp - No response - time=2011.682ms
Probing 27.159.132.213:17010/tcp - No response - time=2012.719ms

**Comment by huxuansong** [comment]
看来可能不是frp的原因，

tcping nginx 和 apache也是不通，
可能nginx和apache能够访问的原因是ipv6
因为我同时解析了ipv6的的ddns

谢谢 [Becods](https://github.com/Becods)的指导
