### ISSUE TITLE
希望服务端支持多节点部署，毕竟单机宕机的概率是有的，以保证高可用

### ISSUE THREAD

**Issue by 767102998** [fatedier/frp#3448]
### Describe the feature request

希望服务端支持多节点部署，毕竟单机宕机的概率是有的，以保证高可用

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
https://github.com/fatedier/frp/issues/2445

> 集群的方案有相关的设计，但是相对复杂，而且大多数偏商业化需求，开源版本里可能不会花太多精力做这件事。

**Comment by DOGTT** [comment]
我最近开发了一个基于k8s headless service的高可用实现，是基于sidecar模式+plugin的方式，看大家有没有兴趣，等我有空整理出来。

**Comment by JaegerFong** [comment]
> 我最近开发了一个基于k8s headless service的高可用实现，是基于sidecar模式+plugin的方式，看大家有没有兴趣，等我有空整理出来。

老哥可以分享一下吗
