### ISSUE TITLE
The user = your_name configuration item is concatenated with  visitor server_name item , Therefore custom cannot be found

### ISSUE THREAD

**Issue by louzhuzhijia** [fatedier/frp#3450]
### Bug Description

computer   windows01
[common]
user = win_01

[xtcp_win_02_3389_visitor]
type = xtcp
role = visitor
server_name = win_02.xtcp_3389

computer   windows02
[common]
user = win_02

[xtcp_3389]
type = xtcp

use computer 01 connection exception log：
[win_01.xtcp_win_02_3389_visitor] start new visitor connection error: custom listener for [win_01.win_02.xtcp_3389] doesn't exist
When computer 01 connects to computer 02  port 3389, its [user] name will be concatenated to [server_name]. Therefore, custom cannot be found
Remove the user = win_01 configuration in computer 01  to access normally

### frpc Version

0.48.0

### frps Version

0.48.0

### System Architecture

windows/amd64

### Configurations

see the description

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by zhangnew** [comment]
根据[ #927 ](https://github.com/fatedier/frp/issues/927#issuecomment-440503770) 作者的回复，stcp 客户端和服务端的 user 需要相同，这个逻辑比较奇怪~
