### ISSUE TITLE
获取真实IP问题 proxy_protocol_version = v2

### ISSUE THREAD

**Issue by rebootder** [fatedier/frp#3456]
### Describe the feature request

客户端配置了 
proxy_protocol_version = v2
然后 nginx
real_ip_header proxy_protocol;
set_real_ip_from 127.0.0.1/0;
real_ip_recursive on;
php里面获取的IP地址是 ::ffff:x.x.x.x
怎么是IPV6和IPV4的IP
服务器已经关闭了IPv6
客户端也关闭了IPV6

如何让IP只显示IPV4的 
不要IPV6的

### Affected area

- [ ] Docs
- [X] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by rebootder** [comment]
我自己解决了
我原先用的V0.27版本 
更换最新版的 V0.49版本问题解决了

问题原因
php 打印 print_r($_SERVER);
[REMOTE_ADDR] => ::ffff:255.255.255.255
返回的IP地址为IPV6  
我关闭了服务端和客户端的IPV6 问题依旧
网上找了半天资料都不行

然后想着换个版本试试 结果问题解决了
现在 [REMOTE_ADDR] => 255.255.255.255
能正常显示IPV4

**Comment by gaojianstyle** [comment]
我也是这样的问题,nodejs下https获取不到真实ip
