### ISSUE TITLE
Cli command tool

### ISSUE THREAD

**Issue by tecnicosya** [fatedier/frp#3458]
### Describe the feature request

FRP need to have a simple Cli tool to use all rich features have in a easy way.

### Describe alternatives you've considered

Frp add service Minecraft
FRP service Minecraft setport 4569
Frp service Minecraft setprotocol stcp
Frp service Minecraft enable true
FRP service Minecraft setpassword "12345"
Frp service Minecraft start

FRP service Minecraft enable false
Frp service Minecraft stop
...
..

### Affected area

- [ ] Docs
- [X] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
At present, there is no energy to invest in this aspect.

**Comment by tecnicosya** [comment]
> At present, there is no energy to invest in this aspect.

I test today on my server and I'm so happy with great performance of you software. 💪💪💪
