### ISSUE TITLE
怎样将80端口复用?

### ISSUE THREAD

**Issue by impig33** [fatedier/frp#346]
我的服务器上本来就有apache，跑了多个网站。

现在我的想法是，在家里的pc上面跑一个ftp客户端，把pc的网站反代到服务器的80上去，同时不影响原有 网站。

问题：
1.怎样实现?

2.开个脑洞，如果在apache上面建一个与我pc上面同样的虚拟主机，然后使用.htacces文件可否再反代到pc的80上?

.

**Comment by fatedier** [comment]
可以搜索之前的 issue，参考 nginx 的使用配置问题，不要重复提问。
