### ISSUE TITLE
Java library

### ISSUE THREAD

**Issue by tecnicosya** [fatedier/frp#3461]
### Describe the feature request

I want to build a tool in Java using your frp.
Currently I'm using shell to call frp from my app

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
I am not familiar with Java and do not have any plans in this area.

**Comment by tecnicosya** [comment]
I read frp will compile to library. But I don't know where is the documentation for it. Maybe I will used with dotnet

**Comment by tecnicosya** [comment]
> No estoy muy familiarizado con go, pero puede ayudar. Tal vez sea posible incluir la dependencia de jni en la compilación de cgo para la biblioteca compartida. O tal vez exista algún 'go-builder' para Java. Por ejemplo, gomobile crea AAR para Android para usar la interfaz Java, extrayendo bibliotecas compartidas jni, creadas por gomobile. Puede usar librerías compartidas generadas por gomobile en su código java, también gomobile produce un 'encabezado' de código fuente con directivas 'nativas' para construir métodos jni. Aquí está mi comentario sobre la creación de [la biblioteca FRP](https://github.com/fatedier/frp/issues/2989#issuecomment-1563214660) , frp necesita cambiar algo de código para un funcionamiento mínimo como biblioteca.
Wow! thats what a I need, FRP Library for Android and Windows, now I will try to integrate on my project!.
Thank you so much!
