### ISSUE TITLE
0.49版服务器面板无法读取Bind UDP Port参数

### ISSUE THREAD

**Issue by xingtongsf** [fatedier/frp#3462]
### Bug Description

在Bind UDP Port参数那一栏显示为空。以前版本正常。
服务器端参数设置是正常的
![{}H`Q$_@IVQSP5D_L1X KL2](https://github.com/fatedier/frp/assets/121077990/15434571-5f3d-499b-9d9e-9a20ccb5f4be)

### frpc Version

0.49

### frps Version

0.49

### System Architecture

linux/amd64

### Configurations

Nothing to preview

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
`Bind UDP Port` 参数已移除，xtcp 不再依赖这个配置。后续版本会在 dashboard 中移除这个展示。
