### ISSUE TITLE
User authorization from server

### ISSUE THREAD

**Issue by tecnicosya** [fatedier/frp#3466]
### Describe the feature request

Add the possibility to set clients will connect.

I'm here starting from Rathole and they have that option to about abuse of our server.
Every client set first in Config file server and the password apply only for that client.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
There already exists a similar issue, and the solution is to use the server-side plugin.

There is already a demo: https://github.com/gofrp/fp-multiuser
