### ISSUE TITLE
邮件提醒功能

### ISSUE THREAD

**Issue by hope-zjl** [fatedier/frp#3467]
### Describe the feature request

添加邮件提醒功能，当有用户通过frps访问 便发邮件提醒（个人用户）

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
This is not the function that this project focuses on. You can try to customize it yourself.

**Comment by hope-zjl** [comment]
好的  谢谢

**Comment by gainskills** [comment]
@hope-zjl  here are some info for reference
- https://github.com/fatedier/frp/issues/1186
- https://github.com/lukacu/docker-frps/tree/master/plugins/linknotifier
