### ISSUE TITLE
How does the port set by 'bind_udp_port' work when making an xtcp connection? 

### ISSUE THREAD

**Issue by iaston** [fatedier/frp#3471]
### Describe the feature request

Although 'bind_udp_port' is set in frp.ini, the corresponding connection port for 'bind_udp_port' is not set in frp.ini. How can the client know the 'bind_udp_port' on the server side and establish an xtcp connection using 'bind_udp_port'?

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BeUnhappy** [comment]
https://gofrp.org/docs/examples/xtcp/
