### ISSUE TITLE
[Feature Request] udp 添加 proxy protocol 的支持

### ISSUE THREAD

**Issue by mclk623** [fatedier/frp#3476]
### Describe the feature request

希望udp协议也可以支持proxy protocol来获取用户端的ip 
都是127.0.0.1太痛苦了

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
成本太高，每个数据包都需要附加额外信息，暂时不考虑支持，除非有更合适的方式。

**Comment by sekaom** [comment]
可以使用sakura frp等支持udp proxy protocol 的frpc连接frps即可。原版frps可以
