### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by liunx7594** [fatedier/frp#3479]
### Bug Description

When I run the client, I always report an error.
The following is the output result of the running client

2023/06/06 10:49:26 [W] [service.go:132] login to server failed: read tcp 192.168.1.116:48200->202.111.16.100:7000: read: connection reset by peer
read tcp 192.168.1.116:48200->202.111.16.100:7000: read: connection reset by peer

2023/06/06 10:56:01 [W] [service.go:132] login to server failed: read tcp 192.168.1.116:46766->202.111.16.100:7000: read: connection reset by peer
read tcp 192.168.1.116:46766->202.111.16.100:7000: read: connection reset by peer

### frpc Version

0.45.0

### frps Version

0.45.0

### System Architecture

linux/amd64 ubuntu

### Configurations

[common]
server_addr = 202.111.16.100
server_port = 7000
tls_enable = true

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

### Logs

2023/06/06 10:49:26 [W] [service.go:132] login to server failed: read tcp 192.168.1.116:48200->202.111.16.100:7000: read: connection reset by peer
read tcp 192.168.1.116:48200->202.111.16.100:7000: read: connection reset by peer

2023/06/06 10:56:01 [W] [service.go:132] login to server failed: read tcp 192.168.1.116:46766->202.111.16.100:7000: read: connection reset by peer
read tcp 192.168.1.116:46766->202.111.16.100:7000: read: connection reset by peer

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
![image](https://github.com/fatedier/frp/assets/35525491/3cf58077-2a17-4bb5-99a5-5c96d3327828)

Check your firewall.
