### ISSUE TITLE
Should tls be enabled when using quic protocol between frps and frpc ?

### ISSUE THREAD

**Issue by azlxm2021** [fatedier/frp#3481]
### Describe the feature request

Should tls be enabled when using quic protocol between frps and frpc for security reason?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by azlxm2021** [comment]
If not ,I hope add up some suggestion in configure document files.

**Comment by fatedier** [comment]
This depends on whether you need to use your own certificate.
