### ISSUE TITLE
[Feature Request] Map server port on local port

### ISSUE THREAD

**Issue by tiagogbarbosa** [fatedier/frp#3482]
### Describe the feature request

In possible to map server port (http proxy) on a client port?
So user (with frpc.ini) can 'curl -x localhost:6006' and be redirected to proxy running on server on port 6006?

Ty

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [x] Server Plugin
- [x] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Not supported, unless you enable another frpc on the server and use a proxy of type stcp.
