### ISSUE TITLE
fc连接frps成功后一直重连

### ISSUE THREAD

**Issue by llwq123456** [fatedier/frp#3486]
### Bug Description

![image](https://github.com/fatedier/frp/assets/56341280/dc18ccd1-46ac-478e-99aa-b40ea2dd46c7)

### frpc Version

0.46.1

### frps Version

0.46.1

### System Architecture

windows/amd64

### Configurations

frps
[common]
bind_port = 7001
token =hupu123
request_addr = 10.10.2.33
request_port = 8087
log_level = debug
#log_file = ./imangw.log
#log_max_days = 7

frpc
[common]
server_addr = 10.10.2.155
server_port = 7001
token = hupu123
use_gzip = true
log_level = debug
#log_file = ./imanagt.log

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
1. 你的frp是自己编译的吗
2. 原版frps中不存在request_addr和request_port这两个配置

如果是第三方frp，请找对应二开作者

**Comment by llwq123456** [comment]
> 1. 你的frp是自己编译的吗
> 2. 原版frps中不存在request_addr和request_port这两个配置
> 
> 如果是第三方frp，请找对应二开作者

自己修改的，找到原因了，添加了服务后，传输格式有问题了

**Comment by llwq123456** [comment]
> 

还有个问题，就是frps部署在1段，frpc部署在2段网络，s和c能连上，访问的时候都不走s，直接无法访问网站，是不能分两段吗
