### ISSUE TITLE
mipsle版本的客户端对tcp端口的支持有问题

### ISSUE THREAD

**Issue by dodohappi** [fatedier/frp#349]
局域网电脑如下：
一台黑群晖，IP为：192.168.111.119 ，局域网内访问正常。
路由器：IP：192.168.111.1，是mtk7621的，下载mipsle的frpc，可运行成功，服务器端显示连接成功。
笔记本：IP：192.168.111.2，64位win7，使用amd64版本的frpc，可运行成功，服务器端显示连接成功。

目的为暴露黑群晖的5000端口，配置文件中设置了TCP的反向代理，远程端口和本地端口均为5000，
用笔记本frpc连接外网服务器frps，测试可以成功打开群晖的管理界面，
用路由器frpc连接外网服务器frps，测试无法打开群晖管理界面。
但是用路由器和笔记本，均能够顺利访问暴露的群晖的80端口。
所以，我怀疑，mipsle的版本有问题。

下面是配置文件
-----------------------------------------------------------------------------------------
[privilege_DS_Photo]
privilege_mode =true
type =tcp
local_ip =192.168.111.119
local_port =80
remote_port = 8088
use_gzip =true
use_encryption = true
custom_domains =[服务器IP]
subdomain = dsPhoto

[privilege_DS_home]
privilege_mode = true
type = tcp
local_ip = 192.168.111.119
local_port = 5000
use_gzip = false
use_encryption = true
remote_port =5000
custom_domains =[服务器IP]
subdomain = ds

**Comment by fatedier** [comment]
参考 #245，目前 mips 的版本可能存在问题也没法从应用层面解决。

另外配置文件不需要的参数不用配，用最简单的配置开始尝试，再检查下防火墙之类的是否正常。

**Comment by yovanc** [comment]
[privilege_DS_home]
privilege_mode = true
type = tcp
remote_port = 5000
local_ip = 192.168.111.119
local_port = 5000

保留最基本的试试，还有把路由器的端口给设置映射，或者关闭防火墙。
