### ISSUE TITLE
反代虚拟路径的配置模式

### ISSUE THREAD

**Issue by yh4922** [fatedier/frp#3490]
### Describe the feature request

这是我的配置文件
```
[common]
bind_port = 37000
vhost_http_port = 38080
token = xxxxxxxxxxxxxxxxxxxxxxxxx
custom_404_page = /frps/frp_0.47.0_linux_amd64/404.html
; log_file = /frps/frp_0.47.0_linux_amd64/log.txt
```
我可以通过 {device_id}.demo.com:38080 正常访问设备。但现在有一个小程序需要请求设备端的接口，由于设备的 ID 是动态的，小程序不支持这种方式。因此，我想通过 http://device.demo.com/{device_id} 的方式配置 Nginx 反向代理。虽然可以跳转到 FRP，但会出现 FRP 的 404 页面。我怀疑这是由于域名验证不匹配导致的。请问是否有办法支持这种方式？

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
没有理解，可以查看日志排查问题
