### ISSUE TITLE
[Feature Request] FRP服务器 与客户端能否同时建立IPV4+IPV6 连接

### ISSUE THREAD

**Issue by unknown-0054** [fatedier/frp#3491]
电信宽带上行只有30Mbps 我这 V6 V4上行是独立的 
希望 frpc 填写支持双栈的域名时 可以同时走 IPV4+IPV6 这样可以提升速度。
目前已经试过 frpc与frps之间 IPV6的连接。

**Comment by Glucy-2** [comment]
我觉得可以客户端分别创建两个服务然后在服务端负载均衡
