### ISSUE TITLE
二进制程序链接更醒目些

### ISSUE THREAD

**Issue by chmis8000** [fatedier/frp#35]
doc里面的二进制连接也不够醒目，为了不懂go语言的盆友，只是一般网管级别技术人员，而非开发人员，只是找工具使用。
建议：
1.直接将二进制下载 链接 放到 README*.md 文件里面，并单独章节醒目些（而不是在“下载源码”章节里面顺便提一下）。
2.windows发布，建议增加服务（service 保证windows启动时 s端自动已启动）指导说明：
 NSSM - the Non-Sucking Service Manager 
http://www.nssm.cc/
安装服务： nssm install frps x:\xxx\frp\frps.exe
启动服务：nssm start frps
停止服务：nssm stop frps

**Comment by chmis8000** [comment]
补充原因：大量windows server的用户还是有很多的，像国内用友、金蝶、进销存、ERP用户等，https://ngrok.com/ 服务端部署复杂，不懂linux的先学 玩起来困难。 希望 frp 能多一些自己的优点，差异化提供一种解决方案。

**Comment by fatedier** [comment]
1. 我个人觉得既然熟悉 Github 的话，找发布的程序应该问题不大。
2. winodws 方面不是很熟悉，不会优先考虑，只能在出现问题的情况下或者有实际的需求时尽量解决，你提到的 service 启动我会看一下，感觉应该类似 supervisor 之类的，与程序无关，需要用户自行配置吧。

**Comment by chmis8000** [comment]
晕，高手都用linux，类似，但仅仅是无界面的后台进程， 当windows启动时，会自动启动，而不需要登录账号后才启动。 win下开发工具，一般能直接开发支持 services 的exe。而不支持的exe（如go默认发布的exe），可以用第三方 ，如 nssm.exe 启动后加载 要发布的.exe 。

**Comment by fatedier** [comment]
@chmis8000 你如果比较熟悉的话，可以帮忙编写一些关于 windows 方面部署的文档说明 :smile:。

**Comment by chmis8000** [comment]
哦，那我写写，给你发邮箱。
 另外，RE:“我个人觉得既然熟悉 Github 的话，找发布的程序应该问题不大。”  有的项目醒目位置链接官网 或wiki吗，毕竟GIthub专攻源码关联，变通的文档管理，若有官网、wiki，当然更有助于普通用户使用，虽然，现在能找见此项目的，都是GIthub搜索来的，多多推广贴，宣传宣传么
