### ISSUE TITLE
frp httpproxy

### ISSUE THREAD

**Issue by yyimen** [fatedier/frp#3500]
### Describe the feature request

目前frp的类型http可以公用80端口,通过host头区分路由,但是httpproxy(类似socket5)不能有效转发

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
HTTP `CONNECT`
