### ISSUE TITLE
Ubuntu运行frpc出现dial tcp: lookup http on 192.168.1.1:53: no such host

### ISSUE THREAD

**Issue by Canvas-Atomer** [fatedier/frp#3505]
### Bug Description

在运行frpc -c frpc.ini后，报错
2023/06/29 17:58:18 [I] [root.go:217] start frpc service for config file [frpc.ini]
2023/06/29 17:58:18 [W] [service.go:131] login to server failed: dial tcp: lookup http on 192.168.1.1:53: no such host
2023/06/29 17:58:18 [I] [root.go:237] frpc service for config file [frpc.ini] stopped
先前我在win10上成功配置过，frpc.ini是直接复制我在windows上的。

### frpc Version

0.50.0

### frps Version

0.50.0

### System Architecture

linux/amd64

### Configurations

[common]
server_addr = #我的服务器地址
server_port = 7000
token = abc123
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 33389

### Logs

2023/06/29 17:58:18 [I] [root.go:217] start frpc service for config file [frpc.ini]
2023/06/29 17:58:18 [W] [service.go:131] login to server failed: dial tcp: lookup http on 192.168.1.1:53: no such host
2023/06/29 17:58:18 [I] [root.go:237] frpc service for config file [frpc.ini] stopped

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
可能启用了什么代理功能但是代理地址配置不正确，或者 server_addr 配置不正确。

**Comment by Canvas-Atomer** [comment]
> 可能启用了什么代理功能但是代理地址配置不正确，或者 server_addr 配置不正确。

检查了一下确实是打错server_addr的地址了，但是更新了之后还是报错login to server failed: EOF，或者是login to server failed: session shutdown。防火墙里对应的端口都已经开放了。
