### ISSUE TITLE
server_addr中填写的domain会自动更新对应IP吗

### ISSUE THREAD

**Issue by CharlesWou** [fatedier/frp#3507]
### Describe the feature request

server_addr中填写的domain是DDNS的，domain对应的IP可能会变动。
frpc是否会定时刷新domain对应的最新ip？
或者，当frpc发现连接不上server时候，尝试重连服务器时，会刷新domain对应的ip吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
理论上会，具体的还是自己测试一下
