### ISSUE TITLE
[Feature Request] apt get install?

### ISSUE THREAD

**Issue by luohao123** [fatedier/frp#3508]
### Describe the feature request

apt get install? or anytoher pkacage manager able to install convienintly?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
brew

**Comment by luohao123** [comment]
how, most of the time, using frp on server, except download the binary from github (which is might slow or not even possible), any package support for linux server?
