### ISSUE TITLE
使用“https://gofrp.org/docs/examples/https2http/”时出现的问题

### ISSUE THREAD

**Issue by kroazi** [fatedier/frp#3509]
### Bug Description

在“https://gofrp.org/docs/examples/https2http/”中，我根据示例来设置了我的frpc，但启动的时候提示“[control.go:179] [e12496ec4b7a0ed2] [bt] start error: type [https] not support when vhost_https_port is not set”，但示例中未标注需要填写vhost_https_port呀，这是怎么回事？我的frpc与frps均与示例中的参数一致。

frpc配置文件如下：
[common]
server_addr = 这里我填写了的
server_port = 7000

[bt]
type = https
custom_domains = 这里我填写了的

plugin = https2https
plugin_local_addr = 127.0.0.1:6888
# HTTPS 证书相关的配置
plugin_crt_path = 
plugin_key_path = 
plugin_host_header_rewrite = 127.0.0.1
plugin_header_X-From-Where = frp

frps配置文件如下：
[common]
bind_port = 7000

frp版本 0.44.0

### frpc Version

0.44.0

### frps Version

0.44.0

### System Architecture

frpc: ubuntu server 2022 linux/amd64 frps:cent os 7.9/未知

### Configurations

frpc配置文件如下：
[common]
server_addr = 这里我填写了的
server_port = 7000

[bt]
type = https
custom_domains = 这里我填写了的

plugin = https2https
plugin_local_addr = 127.0.0.1:6888
# HTTPS 证书相关的配置
plugin_crt_path = 
plugin_key_path = 
plugin_host_header_rewrite = 127.0.0.1
plugin_header_X-From-Where = frp

frps配置文件如下：
[common]
bind_port = 7000

frp版本 0.44.0

### Logs

[control.go:179] [e12496ec4b7a0ed2] [bt] start error: type [https] not support when vhost_https_port is not set

### Steps to reproduce

1. 跟着https://gofrp.org/docs/examples/https2http/做就会出现
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
恩，文档的问题，`type = https` 需要配置 `vhost_https_port`，或者直接使用 `tcp = tcp`。
