### ISSUE TITLE
搭建xtcp后，可以通过windows命令提示符进行ssh连接，但是不能通过mobaxterm的ssh连接

### ISSUE THREAD

**Issue by Canvas-Atomer** [fatedier/frp#3513]
### Bug Description

包括mobaxterm、windows自带的远程桌面都无法连接。不清楚是不是配置文件里还需要别的项。

### frpc Version

0.50.0

### frps Version

0.50.0

### System Architecture

visitor:windows/amd64; server:linux/amd64

### Configurations

访客端frpc.ini
[common]
server_addr=[hidden]
server_port=7000
token=abc123

[p2p_tcp_visitor]
role=visitor
type=xtcp
server_name=p2p_tcp
sk=abcdefg
bind_addr=127.0.0.1
bind_port=3389

服务端frpc.ini
[common]
server_addr=[hidden]
server_port=7000
token=abc123
[ssh]
type=tcp
local_ip=127.0.0.1
local_port=3389
remote_port=33389
[p2p_tcp]
type=xtcp
sk=abcdefg
local_ip=127.0.0.1
local_port=22

公网服务器frps.ini
[common]
#log_file = ./frps.log
#log_level = info
#log_max_days = 3
bind_port = 7000
bind_udp_port = 7001
kcp_bind_port - 7000
token = abc123
dashboard_port = 7500
dashboard_user = user
dashboard_pwd = password
vhost_http_port = 10080
vhost_https_port = 10443

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
标题 <code><b>可以</b>通过windows命令提示符进行ssh连接</code>
正文 <code>包括mobaxterm、windows自带的远程桌面<b>都无法连接</b></code>
配置 `ssh` `type=tcp`

所以你**真正**的问题是什么

**Comment by Canvas-Atomer** [comment]
> 标题 `可以通过windows命令提示符进行ssh连接` 正文 `包括mobaxterm、windows自带的远程桌面都无法连接` 配置 `ssh` `type=tcp`
> 
> 所以你**真正**的问题是什么

只通过tcp，我可以通过访问我的公网服务器地址和特定端口来访问远程桌面。按我的理解通过udp打洞之后，可以通过我绑定的127.0.0.1访问远程桌面，但是不行。命令行我可以用ssh进行p2p连接，说明连接应该没问题，就是不知道远程桌面和mobaxterm这些软件里为什么不能成功连接。

**Comment by guation** [comment]
不知道这中间是不是有什么奇怪的机制在里面 我的xtcp可以使用微软的远程桌面 可以使用wsl的ssh 但是xshell连接ssh就会卡在连接成功但是不出shell的状态 只要使用wsl的ssh连一下ssh的端口xshell就出shell了

**Comment by cnjmj** [comment]
[p2p_tcp]
type=xtcp
sk=abcdefg
local_ip=127.0.0.1
local_port=22

[p2p_tcp_visitor]
role=visitor
type=xtcp
server_name=p2p_tcp
sk=abcdefg
bind_addr=127.0.0.1
bind_port=3389

P2P_TCP对应的是22端口吗，你要远程桌面的话，是不是写错了
