### ISSUE TITLE
Router config conflict

### ISSUE THREAD

**Issue by trancanh1102** [fatedier/frp#3514]
### Bug Description

Thanks for the great github repository.

i want to create multiple pages to listen to the specified ports but i seem to have an error somewhere

frps.ini
[common]
bind_port = 7000
kcp_bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
allow_ports = 7800

frpc.ini
[common]
server_addr = 192.168.16.112
server_port = 7000
vhost_http_port = 80
vhost_https_port = 443

[web01]
type = http
local_port = 80
local_ip = 127.0.0.1
custom_domains = 192.168.16.112

[web02]
type = http
local_port = 7800
local_ip = 127.0.0.1
custom_domains = 192.168.16.112

but if i remove the config [web02] part i don't get the error message

### frpc Version

0.50.0

### frps Version

0.50.0

### System Architecture

linux/amd64

### Configurations

frps.ini
[common]
bind_port = 7000
kcp_bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
allow_ports = 7800

frpc.ini
[common]
server_addr = 192.168.16.112
server_port = 7000
vhost_http_port = 80
vhost_https_port = 443

[web01]
type = http
local_port = 80
local_ip = 127.0.0.1
custom_domains = 192.168.16.112

[web02]
type = http
local_port = 7800
local_ip = 127.0.0.1
custom_domains = 192.168.16.112

### Logs

[control.go:170] [18569ee3e1a51352] [web02] start error: router config conflict

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by rhine14586** [comment]
same issue
