### ISSUE TITLE
[Feature Request] 服务端插件能自定义传递参数吗

### ISSUE THREAD

**Issue by Jovesong1** [fatedier/frp#3518]
### Describe the feature request

按照服务端的插件文档我成功配置并实现了登录相关的鉴权，想问一下有没有方法可以让服务端也传递一些参数？ 例如在服务端也配置meta_xxx 然后服务端一并传递？
[plugin.multiuser]
addr = http://xxx
path = xxx
ops = Login,NewProxy,CloseProxy
tls_verify = false

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
那为什么不直接配置在你的插件里？
