### ISSUE TITLE
树莓派3上编译运行

### ISSUE THREAD

**Issue by yuiopt** [fatedier/frp#352]
如何在树莓派3上编译运行？

**Comment by XGFan** [comment]
直接下载 linux arm 版本。

**Comment by yuiopt** [comment]
@XGFan 就是用的arm版，提示可执行文件格式不正确

**Comment by WindGreen** [comment]
@yuiopt 树莓派3b，因为raspbian是32位的，所以下载armv7的包，不要下arm64 v8的包

**Comment by CaiJinHao** [comment]
armv7的包在哪下载没找到啊

**Comment by CaiJinHao** [comment]
@WindGreen armv7的包在哪下载没找到啊,方便贴个链接吗
