### ISSUE TITLE
双向认证openssl一定要填IP吗，动态IP的ddns服务器怎么办？

### ISSUE THREAD

**Issue by ppllpig** [fatedier/frp#3521]
### Bug Description

双向认证openssl一定要填IP吗，动态IP的ddns服务器怎么办？

### frpc Version

0.50.0

### frps Version

0.50.0

### System Architecture

amd64/windows

### Configurations

none

### Logs

none

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [X] Others

**Comment by fatedier** [comment]
域名？

**Comment by ppllpig** [comment]
> 域名？

ddns
