### ISSUE TITLE
[Feature Request] support udp in socks5 plugin

### ISSUE THREAD

**Issue by aa51513** [fatedier/frp#3523]
### Describe the feature request

support udp in socks5 is very necessary

### Describe alternatives you've considered

 socks5 libiary that support udp in golang is easy to find

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bannyhm** [comment]
> ### Опишите запрос функции
> поддережка в носках5 о члене необходима
> 
> ### Опишите алтернативи, которое всмосмотрели
> socks5 libiary, podderjivāüpgiy udp в голанже, legko naiyti
> 


You managed to solve the problem with UDP transmission?

**Comment by aa51513** [comment]
> You managed to solve the problem with UDP transmission?

Maybe you can use brook
