### ISSUE TITLE
[Feature Request] 一台服务器最多只能65535个映射吗

### ISSUE THREAD

**Issue by crylg** [fatedier/frp#3524]
### Describe the feature request

我有很多设备，都有自己的外网，每一个我都需要写一个remote-port去映射socks5
那就最多一台服务器就只能连接65535个(同一种连接协议)

有办法突破吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by crylg** [comment]
能有其他分配方式吗

**Comment by Becods** [comment]
多个frps绑定不同ip

**Comment by wxlg1117** [comment]
重写自己版本的tcp/ip协议.
