### ISSUE TITLE
systemctl start可以启动frpc，但是reboot后，服务stopped

### ISSUE THREAD

**Issue by yang369875** [fatedier/frp#3526]
### Bug Description

设置了systemctl enable，直接systemctl start是可以正常ssh，但是重启客户端后无法连接，查看status显示connect: network is unreachable
frpc service for config file [/home/pi/frp/frpc.ini] stopped
应该是说网络问题

### frpc Version

0.51.0

### frps Version

0.51.0

### System Architecture

linux/arm

### Configurations

#/usr/lib/systemd/system/frpc.service
[Unit]
Description=frps service
After=network.target syslog.target
Wants=network.target

[Service]
Type=simple
User=nobody
Restart=on-failure
RestartSec=5s
# TimeoutStartSec=60
ExecStartPre=/bin/sleep 10
ExecStart=/home/pi/frp/frpc -c /home/pi/frp/frpc.ini
# ExecStop=/bin/kill $MAINPID
ExecReload=/home/pi/frp/frpc reload -c /home/pi/frp/frpc.ini

[Install]
WantedBy=multi-user.target

### Logs

pi@raspberrypi:~ $ sudo systemctl status frpc
● frpc.service - frp server
   Loaded: loaded (/etc/systemd/system/frpc.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2023-07-12 09:54:16 CST; 18min ago
  Process: 589 ExecStart=/home/pi/frp/frpc -c /home/pi/frp/frpc.ini (code=exited, status=0/SUCCESS)
 Main PID: 589 (code=exited, status=0/SUCCESS)

7月 12 09:54:15 raspberrypi systemd[1]: Started frp server.
7月 12 09:54:16 raspberrypi frpc[589]: 2023/07/12 09:54:16 [I] [root.go:220] start frpc service for config file [/home/pi/frp/frpc.ini]
7月 12 09:54:16 raspberrypi frpc[589]: 2023/07/12 09:54:16 [W] [service.go:133] login to server failed: dial tcp xx.xx.xx.xx:7000: connect: network is unreachable
7月 12 09:54:16 raspberrypi frpc[589]: 2023/07/12 09:54:16 [I] [root.go:236] frpc service for config file [/home/pi/frp/frpc.ini] stopped
7月 12 09:54:16 raspberrypi systemd[1]: frpc.service: Succeeded.

ssh：
~ % ssh -oPort=6000 pi@xx.xx.xx.xx -v
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 47: Applying options for *
debug1: Connecting to xx.xx.xx.xx [xx.xx.xx.xx] port 6000.
debug1: connect to address xx.xx.xx.xx port 6000: Connection refused
ssh: connect to host xx.xx.xx.xx port 6000: Connection refused

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by gexiaopeng** [comment]
这个情况我也有时遇到，应该是frpc启动的时候，服务器网络还没有完全设置好，解决办法可以把ExecStartPre=/bin/sleep  设置的长一点  。 其实这个也是frpc的一个bug，如果能一直间隔几秒重新连接，就没有问题了。（重连的机制可以与正常连接以后的断开机制，间隔1秒，2秒，4秒，8秒，16秒，后面一直20秒）

**Comment by Glucy-2** [comment]
我也是这个情况，设置了`login_fail_exit = true`也不会退出，也不会重连，就一直挂在那

**Comment by gexiaopeng** [comment]
> 我也是这个情况，设置了`login_fail_exit = true`也不会退出，也不会重连，就一直挂在那

按官方描述 login_fail_exit =true是默认设置，启动以后失败一次就退出。 可以设置login_fail_exit=false试一试，这样应该就不会退出。

**Comment by lamhui** [comment]
> 遇到相同问题，退回之前版本就正常，看起来是frpc在启动时联网得问题
请问你退回之前正常的版本号是多少？

**Comment by lamhui** [comment]
> 遇到相同问题，退回之前版本就正常，看起来是frpc在启动时联网得问题

请问你退回正常的版本号是多少？谢！

**Comment by ddddavid-he** [comment]
> > 遇到相同问题，退回之前版本就正常，看起来是frpc在启动时联网得问题
> 
> 请问你退回正常的版本号是多少？谢！

大概是0.49和以下吧，按照上面的方法在配置文件加一行就能解决问题了

**Comment by IMJacky** [comment]
同求，老铁们怎么解决的

**Comment by Glucy-2** [comment]
我设置了个5秒的启动延迟就没出现了
或者试试把依赖改成network-online.target

**Comment by IMJacky** [comment]
> 我设置了个5秒的启动延迟就没出现了 或者试试把依赖改成`network-online.target`

`[Unit]
# 服务名称，可自定义
Description = frp client
After = network.target network-online.target syslog.target
Wants = network.online.target

[Service]
Type = simple
# 启动frps的命令，需修改为您的frps的安装路径
ExecStart = /home/wjgpi4/frp/frpc -c /home/wjgpi4/frp/frpc.toml

[Install]
WantedBy = multi-user.target
`

在官方的实例上面添加 `network.online.target`  这个方法亲测可行

**Comment by sonor-liang** [comment]
> > 我设置了个5秒的启动延迟就没出现了 或者试试把依赖改成`network-online.target`
> 
> `After = network.target network-online.target syslog.target` `Wants = network.online.target`
> 
> 在官方的实例上面添加 `network.online.target` 这个方法亲测可行

该方法亲测可行！！！！！！！
