### ISSUE TITLE
HTTP request error

### ISSUE THREAD

**Issue by crpgbogor** [fatedier/frp#353]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.11.0

**What operating system and processor architecture are you using (`go env`)?*
frps running on debian AMD
frpc running on debian ARM

**Configures you used:**
frpc.ini
[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 7000
privilege_token = xxxxxxxxx
[web]
type = http
local_port = 80
custom_domains = www.xxxxxx.xxx

frps.ini
[common]
bind_addr = xxx.xxx.xxx.xxx
bind_port = 7000
privilege_token = xxxxxxxxx
vhost_http_port = 8080

**Steps to reproduce the issue:**
1.go to www.xxxxxx.xxx

**Describe the results you received:**
1..receive site cant be reached from browser
2.receive [E] [vhost.go:131] get hostname from http/https request error: EOF from SSH

**Describe the results you expected:**
able to use http

**Additional information you deem important (e.g. issue happens only occasionally):**
TCP is working fine but http is not working

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
Can you use tcpdump to capture http request contents on port 8080?

**Comment by crpgbogor** [comment]
tcpdump didn't reveal any info. From the client side it was a simple txt file and then a simple html file (apache default html). I've tried with windows client, same result.
