### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by LyingDoc** [fatedier/frp#3534]
### Describe the feature request

可以增加一个功能，可以域名绑定端口访问，type=http，万一存在应用存在多个端口后台，映射很麻烦，这个功能可以增加

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
我是用type = tcp，然后定义不同的远程端口，同一个域名访问。
