### ISSUE TITLE
[Feature Request] udp隧道不支持ProxyProtocol v2

### ISSUE THREAD

**Issue by XiYang6666** [fatedier/frp#3535]
### Describe the feature request

能否在后续更新中加入对udp隧道的ProxyProtocol v2支持?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
当前支持的成本太高，需要在每个包里附加额外的信息，之后会考虑重构 UDP 转发的实现，可能会支持。
