### ISSUE TITLE
0.51.1 https2http not working

### ISSUE THREAD

**Issue by hq-git** [fatedier/frp#3541]
### Bug Description

After I upgraded frp from 0.49.0 to 0.51.1, the https2http not working, I got no response for most of the static files.
When I using local nginx + frp tcp plugin, it works well.

### frpc Version

0.51.1

### frps Version

0.51.1

### System Architecture

linux/amd64

### Configurations

[web_virtualbox]
type = https
custom_domains = virtualbox.demo.com
plugin = https2http
plugin_local_addr = 127.0.0.1:8080
use_compression = true
plugin_crt_path = /etc/letsencrypt/live/star.demo.com/fullchain.pem
plugin_key_path = /etc/letsencrypt/live/star.demo.com/privkey.pem
plugin_host_header_rewrite = 127.0.0.1
plugin_header_X-From-Where = frp

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by hq-git** [comment]
downgrade the frpc to 0.49.0 (still using frps 0.51.1) can solve the issue

**Comment by hq-git** [comment]
frpc 0.51.0 also works well, while using frpc 0.51.1 will get '400 Bad Request' in browser.

**Comment by fatedier** [comment]
logs

**Comment by hq-git** [comment]
@fatedier 

-------------------------------> frps.log

2023/07/24 23:50:47 [D] [control.go:245] [c15e3fc1e27a0724] new work connection registered
2023/07/24 23:50:47 [D] [control.go:245] [c15e3fc1e27a0724] new work connection registered
2023/07/24 23:51:08 [D] [control.go:519] [c15e3fc1e27a0724] receive heartbeat
2023/07/24 23:51:13 [D] [proxy.go:265] [c15e3fc1e27a0724] [web_virtualbox] join connections closed
2023/07/24 23:51:13 [D] [vhost.go:245] [c15e3fc1e27a0724] [web_virtualbox] new request host [virtualbox.demo.cn] path [] httpUser []
2023/07/24 23:51:13 [I] [proxy.go:199] [c15e3fc1e27a0724] [web_virtualbox] get a user connection [117.129.4.151:15865]
2023/07/24 23:51:13 [D] [control.go:274] [c15e3fc1e27a0724] get work connection from pool
2023/07/24 23:51:13 [D] [proxy.go:126] [c15e3fc1e27a0724] [web_virtualbox] get a new work connection: [117.129.4.151:15699]
2023/07/24 23:51:13 [T] [proxy.go:235] [c15e3fc1e27a0724] [web_virtualbox] handler user tcp connection, use_encryption: false, use_compression: true
2023/07/24 23:51:13 [D] [proxy.go:255] [c15e3fc1e27a0724] [web_virtualbox] join connections, workConn(l[192.168.0.133:7000] r[117.129.4.151:15699]) userConn(l[192.168.0.133:8443] r[117.129.4.151:15865])
2023/07/24 23:51:13 [D] [vhost.go:245] [c15e3fc1e27a0724] [web_virtualbox] new request host [virtualbox.demo.cn] path [] httpUser []
2023/07/24 23:51:13 [I] [proxy.go:199] [c15e3fc1e27a0724] [web_virtualbox] get a user connection [117.129.4.151:15867]
2023/07/24 23:51:13 [D] [control.go:274] [c15e3fc1e27a0724] get work connection from pool
2023/07/24 23:51:13 [D] [proxy.go:126] [c15e3fc1e27a0724] [web_virtualbox] get a new work connection: [117.129.4.151:15699]
2023/07/24 23:51:13 [T] [proxy.go:235] [c15e3fc1e27a0724] [web_virtualbox] handler user tcp connection, use_encryption: false, use_compression: true
2023/07/24 23:51:13 [D] [proxy.go:255] [c15e3fc1e27a0724] [web_virtualbox] join connections, workConn(l[192.168.0.133:7000] r[117.129.4.151:15699]) userConn(l[192.168.0.133:8443] r[117.129.4.151:15867])
2023/07/24 23:51:13 [D] [proxy.go:265] [c15e3fc1e27a0724] [web_virtualbox] join connections closed
2023/07/24 23:51:13 [D] [vhost.go:245] [c15e3fc1e27a0724] [web_virtualbox] new request host [virtualbox.demo.cn] path [] httpUser []
2023/07/24 23:51:13 [I] [proxy.go:199] [c15e3fc1e27a0724] [web_virtualbox] get a user connection [117.129.4.151:15866]
2023/07/24 23:51:13 [D] [control.go:274] [c15e3fc1e27a0724] get work connection from pool
2023/07/24 23:51:13 [D] [proxy.go:126] [c15e3fc1e27a0724] [web_virtualbox] get a new work connection: [117.129.4.151:15699]
2023/07/24 23:51:13 [T] [proxy.go:235] [c15e3fc1e27a0724] [web_virtualbox] handler user tcp connection, use_encryption: false, use_compression: true
2023/07/24 23:51:13 [D] [proxy.go:255] [c15e3fc1e27a0724] [web_virtualbox] join connections, workConn(l[192.168.0.133:7000] r[117.129.4.151:15699]) userConn(l[192.168.0.133:8443] r[117.129.4.151:15866])
2023/07/24 23:51:13 [D] [control.go:245] [c15e3fc1e27a0724] new work connection registered
2023/07/24 23:51:13 [D] [control.go:245] [c15e3fc1e27a0724] new work connection registered
2023/07/24 23:51:13 [D] [control.go:245] [c15e3fc1e27a0724] new work connection registered
2023/07/24 23:51:13 [D] [vhost.go:245] [c15e3fc1e27a0724] [web_virtualbox] new request host [virtualbox.demo.cn] path [] httpUser []
2023/07/24 23:51:13 [I] [proxy.go:199] [c15e3fc1e27a0724] [web_virtualbox] get a user connection [117.129.4.151:15868]
2023/07/24 23:51:13 [D] [control.go:274] [c15e3fc1e27a0724] get work connection from pool
2023/07/24 23:51:13 [D] [proxy.go:126] [c15e3fc1e27a0724] [web_virtualbox] get a new work connection: [117.129.4.151:15699]
2023/07/24 23:51:13 [T] [proxy.go:235] [c15e3fc1e27a0724] [web_virtualbox] handler user tcp connection, use_encryption: false, use_compression: true
2023/07/24 23:51:13 [D] [proxy.go:255] [c15e3fc1e27a0724] [web_virtualbox] join connections, workConn(l[192.168.0.133:7000] r[117.129.4.151:15699]) userConn(l[192.168.0.133:8443] r[117.129.4.151:15868])
2023/07/24 23:51:13 [D] [vhost.go:245] [c15e3fc1e27a0724] [web_virtualbox] new request host [virtualbox.demo.cn] path [] httpUser []
2023/07/24 23:51:13 [I] [proxy.go:199] [c15e3fc1e27a0724] [web_virtualbox] get a user connection [117.129.4.151:15869]
2023/07/24 23:51:13 [D] [control.go:274] [c15e3fc1e27a0724] get work connection from pool
2023/07/24 23:51:13 [D] [proxy.go:126] [c15e3fc1e27a0724] [web_virtualbox] get a new work connection: [117.129.4.151:15699]
2023/07/24 23:51:13 [T] [proxy.go:235] [c15e3fc1e27a0724] [web_virtualbox] handler user tcp connection, use_encryption: false, use_compression: true
2023/07/24 23:51:13 [D] [proxy.go:255] [c15e3fc1e27a0724] [web_virtualbox] join connections, workConn(l[192.168.0.133:7000] r[117.129.4.151:15699]) userConn(l[192.168.0.133:8443] r[117.129.4.151:15869])
2023/07/24 23:51:13 [D] [vhost.go:245] [c15e3fc1e27a0724] [web_virtualbox] new request host [virtualbox.demo.cn] path [] httpUser []
2023/07/24 23:51:13 [I] [proxy.go:199] [c15e3fc1e27a0724] [web_virtualbox] get a user connection [117.129.4.151:15870]
2023/07/24 23:51:13 [D] [control.go:274] [c15e3fc1e27a0724] get work connection from pool
2023/07/24 23:51:13 [D] [proxy.go:126] [c15e3fc1e27a0724] [web_virtualbox] get a new work connection: [117.129.4.151:15699]
2023/07/24 23:51:13 [T] [proxy.go:235] [c15e3fc1e27a0724] [web_virtualbox] handler user tcp connection, use_encryption: false, use_compression: true
2023/07/24 23:51:13 [D] [proxy.go:255] [c15e3fc1e27a0724] [web_virtualbox] join connections, workConn(l[192.168.0.133:7000] r[117.129.4.151:15699]) userConn(l[192.168.0.133:8443] r[117.129.4.151:15870])
2023/07/24 23:51:13 [D] [control.go:245] [c15e3fc1e27a0724] new work connection registered
2023/07/24 23:51:13 [D] [control.go:245] [c15e3fc1e27a0724] new work connection registered
2023/07/24 23:51:13 [D] [proxy.go:265] [c15e3fc1e27a0724] [web_virtualbox] join connections closed
2023/07/24 23:51:13 [D] [proxy.go:265] [c15e3fc1e27a0724] [web_virtualbox] join connections closed
2023/07/24 23:51:13 [D] [control.go:245] [c15e3fc1e27a0724] new work connection registered
2023/07/24 23:51:13 [D] [vhost.go:245] [c15e3fc1e27a0724] [web_virtualbox] new request host [virtualbox.demo.cn] path [] httpUser []
2023/07/24 23:51:13 [I] [proxy.go:199] [c15e3fc1e27a0724] [web_virtualbox] get a user connection [117.129.4.151:15871]
2023/07/24 23:51:13 [D] [control.go:274] [c15e3fc1e27a0724] get work connection from pool
2023/07/24 23:51:13 [D] [proxy.go:126] [c15e3fc1e27a0724] [web_virtualbox] get a new work connection: [117.129.4.151:15699]
2023/07/24 23:51:13 [T] [proxy.go:235] [c15e3fc1e27a0724] [web_virtualbox] handler user tcp connection, use_encryption: false, use_compression: true
2023/07/24 23:51:13 [D] [proxy.go:255] [c15e3fc1e27a0724] [web_virtualbox] join connections, workConn(l[192.168.0.133:7000] r[117.129.4.151:15699]) userConn(l[192.168.0.133:8443] r[117.129.4.151:15871])


-------------------------------> frpc.log
2023/07/24 23:48:47 [D] [proxy_wrapper.go:255] [c15e3fc1e27a0724] [web_virtualbox] start a new work connection, localAddr: 192.168.50.110:57129 remoteAddr: 47.93.16.154:7000
2023/07/24 23:48:47 [T] [proxy.go:135] [c15e3fc1e27a0724] [web_virtualbox] handle tcp work connection, use_encryption: false, use_compression: true
2023/07/24 23:48:47 [D] [proxy.go:186] [c15e3fc1e27a0724] [web_virtualbox] handle by plugin: https2http
2023/07/24 23:48:47 [D] [proxy.go:188] [c15e3fc1e27a0724] [web_virtualbox] handle by plugin finished
2023/07/24 23:48:47 [D] [proxy_wrapper.go:255] [c15e3fc1e27a0724] [web_virtualbox] start a new work connection, localAddr: 192.168.50.110:57129 remoteAddr: 47.93.16.154:7000
2023/07/24 23:48:47 [T] [proxy.go:135] [c15e3fc1e27a0724] [web_virtualbox] handle tcp work connection, use_encryption: false, use_compression: true
2023/07/24 23:48:47 [D] [proxy.go:186] [c15e3fc1e27a0724] [web_virtualbox] handle by plugin: https2http
2023/07/24 23:48:47 [D] [proxy.go:188] [c15e3fc1e27a0724] [web_virtualbox] handle by plugin finished
2023/07/24 23:48:47 [D] [proxy_wrapper.go:255] [c15e3fc1e27a0724] [web_virtualbox] start a new work connection, localAddr: 192.168.50.110:57129 remoteAddr: 47.93.16.154:7000
2023/07/24 23:48:47 [T] [proxy.go:135] [c15e3fc1e27a0724] [web_virtualbox] handle tcp work connection, use_encryption: false, use_compression: true
2023/07/24 23:48:47 [D] [proxy.go:186] [c15e3fc1e27a0724] [web_virtualbox] handle by plugin: https2http
2023/07/24 23:48:47 [D] [proxy.go:188] [c15e3fc1e27a0724] [web_virtualbox] handle by plugin finished
2023/07/24 23:48:47 [D] [proxy_wrapper.go:255] [c15e3fc1e27a0724] [web_virtualbox] start a new work connection, localAddr: 192.168.50.110:57129 remoteAddr: 47.93.16.154:7000
2023/07/24 23:48:47 [T] [proxy.go:135] [c15e3fc1e27a0724] [web_virtualbox] handle tcp work connection, use_encryption: false, use_compression: true
2023/07/24 23:48:47 [D] [proxy.go:186] [c15e3fc1e27a0724] [web_virtualbox] handle by plugin: https2http
2023/07/24 23:48:47 [D] [proxy.go:188] [c15e3fc1e27a0724] [web_virtualbox] handle by plugin finished
2023/07/24 23:48:47 [D] [proxy_wrapper.go:255] [c15e3fc1e27a0724] [web_virtualbox] start a new work connection, localAddr: 192.168.50.110:57129 remoteAddr: 47.93.16.154:7000
2023/07/24 23:48:47 [T] [proxy.go:135] [c15e3fc1e27a0724] [web_virtualbox] handle tcp work connection, use_encryption: false, use_compression: true
2023/07/24 23:48:47 [D] [proxy.go:186] [c15e3fc1e27a0724] [web_virtualbox] handle by plugin: https2http
2023/07/24 23:48:47 [D] [proxy.go:188] [c15e3fc1e27a0724] [web_virtualbox] handle by plugin finished
2023/07/24 23:49:08 [D] [control.go:296] [c15e3fc1e27a0724] send heartbeat to server
2023/07/24 23:49:08 [D] [control.go:329] [c15e3fc1e27a0724] receive heartbeat from server

**Comment by fatedier** [comment]
Can not reproduce in my env and the logs seems no error.

**Comment by fatedier** [comment]
When making concurrent requests, it is possible to reproduce the issue. It requires time to investigate the cause.
