### ISSUE TITLE
[Feature Request] 请问 xtcp 是否能够从 visitor 侧将 http 请求通过 p2p 转发至 client 侧的 web 服务上

### ISSUE THREAD

**Issue by choumin** [fatedier/frp#3542]
### Describe the feature request

请问 xtcp 是否能够从 visitor 侧将 http 请求通过 p2p 转发至 client 侧的 web 服务上，就像从 visitor 侧通过 ssh 连接 client 侧的 sshd 一样

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by guation** [comment]
同样TCP协议同样方向 我觉得没问题

**Comment by choumin** [comment]
> 同样TCP协议同样方向 我觉得没问题

谢谢，已验证，确实可以。
