### ISSUE TITLE
run docker image with frps.ini file mounting

### ISSUE THREAD

**Issue by testarchitecture39** [fatedier/frp#3544]
### Bug Description

Hi,

in the current implementation, I am not able to run the frps docker by mounting a frps.ini file.
Is this supported.
It works with frpc by adding the file to ./frpc.ini, but for servers it does not work.

docker run -v /etc/frp/frps.ini:/etc/frp/frps.ini fatedier/frps:v0.51.0

I always see the log message as ,

[root.go:206 ]frps uses command line arguments for config

### frpc Version

v0.51.0

### frps Version

v0.51.0

### System Architecture

mac

### Configurations

question related to the configuration file not being picked while running as docker for the frp server

### Steps to reproduce

docker run -v /etc/frp/frps.ini:/etc/frp/frps.ini fatedier/frps:v0.51.0

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
`-c` to specify configration file

**Comment by testarchitecture39** [comment]
Thanks for the quick response.!!!
I was able to run it fine now.

**Comment by glacierck** [comment]
完整的docker run 指令是啥？-c不是docker的内置指令吗？怎么变成了指定配置文件。
 @fatedier
