### ISSUE TITLE
Prometheus Monitoring for the client

### ISSUE THREAD

**Issue by testarchitecture39** [fatedier/frp#3545]
### Describe the feature request

Hi,
I could not find the property to monitor the frp client via prometheus (enable_prometheus).Is my understanding correct that there is no client monitoring ?
It would be nice to have the client monitoring in place.

### Describe alternatives you've considered

none

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
No plan for that.

**Comment by vithusel** [comment]
I'm using Tactical RMM to monitor my frp instances for both on server and client. I've had to build a script to check the output from the logs and then desipher that to something i can use to generate reports. I've not used prometheus before but if its like zabbix you might be able to setup a similar external reporting.
