### ISSUE TITLE
0.51.1版本http如果开启页面压缩，就无法显示网页

### ISSUE THREAD

**Issue by xingtongsf** [fatedier/frp#3546]
### Bug Description

使用0.51.1作为服务器的时候，如果开启页面压缩和页面加密。那么交互页面便无法访问，出现网页显示不全错误。
关闭页面压缩后正常。
客户端使用0.51.1或老版本都出现这一相同问题

### frpc Version

0.48

### frps Version

0.51.1

### System Architecture

linux/amd64

### Configurations

.

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
You should provide `steps to reproduce`

**Comment by fatedier** [comment]
Maybe Duplicate of #3541
