### ISSUE TITLE
内网穿透后的域名CNAME到域名b访问404有解决办法吗

### ISSUE THREAD

**Issue by sunianOvO** [fatedier/frp#3548]
### Describe the feature request

内网穿透后的域名CNAME到域名b访问404有解决办法吗

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
![CM6PHS7AGGJPN31Y2DI83MS](https://github.com/fatedier/frp/assets/35525491/debaefcb-8653-4f2d-a2d6-e470a2cf7284)

**Comment by wuruiwm** [comment]
我觉得这不是frp的问题。。。。
