### ISSUE TITLE
反向代理windows远程桌面不成功

### ISSUE THREAD

**Issue by BoredTape** [fatedier/frp#355]
客户端远程桌面端口是3389，服务端对应端口是3333，配置成功后远程连接服务端3333端口卡在“正在配置远程会话“。
客户端配置如下：
[grdp]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 3333
在frps面板的tcp下可以看到对应配置，且在卡连接的时候显示有连接状态。Traffic In显示38 bytes。
日志显示：
2017/06/09 11:02:23 [I] [proxy.go:76] [83d45c8e51601710] [公司.grdp] get a $ new work connection: [xxx.xxx.xxx.xxx:xxxx]（最后的xxx是我改的，原来是ip地址加端口）

**Comment by fatedier** [comment]
为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。
