### ISSUE TITLE
An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by yzhgu** [fatedier/frp#3554]
### Bug Description

有三个frpc客户端，之前三个都连接正常，最近更新了0.51.2，然后两个客户端正常连接，有一个无法连接，但是无法连接的这个frpc.ini换台pc又是可以连接的。

D:\frpc>frpc -c ./frpc.ini
2023/07/27 15:29:31 [I] [root.go:220] start frpc service for config file [./frpc.ini]
2023/07/27 15:29:31 [W] [service.go:133] login to server failed: read tcp 192.168.1.103:49818->[ipaddress:port]: wsarecv: An existing connection was forcibly closed by the remote host.
2023/07/27 15:29:31 [I] [root.go:236] frpc service for config file [./frpc.ini] stopped

### frpc Version

0.51.2

### frps Version

0.51.2

### System Architecture

frpc: windows/amd64; frps: 群晖docker (https://registry.hub.docker.com/r/snowdreamtech/frps/)

### Configurations

//frpc.ini
[common]
server_addr = domain
server_port = 7000
token = blablabla

[rdp1]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 33333

//frps.ini
[common]
bind_addr = 0.0.0.0
bind_port = 7000

bind_udp_port = 7001

kcp_bind_port = 7000

tls_enable = true

vhost_http_port = 10080
vhost_https_port = 10443

dashboard_addr = 0.0.0.0
dashboard_port = 7500

dashboard_user = user
dashboard_pwd = userpw

log_file = ./frps.log

log_level = info

log_max_days = 3

disable_log_color = false

authentication_method = token

authenticate_heartbeats = false

authenticate_new_work_conns = false
token = blablabla

allow_ports = 2000-3000,3001,3003,4000-50000

max_pool_count = 5

max_ports_per_client = 0

subdomain_host = frps.com

tcp_mux = true

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by yzhgu** [comment]
我想问题可能在于运行frpc的机子有多个网卡，从输出192.168.1.103:49818->[ipaddress:port]可以看出，frpc使用了不能联外网那个网卡，怎么能让frpc使用另一个网卡？我试着将"local_ip = 127.0.0.1"改成"local_ip = 172.16.110.49"（另一个网卡的IP地址），可是输出信息任然显示192.168.1.103

**Comment by vvanouytsel** [comment]
@yzhgu can you elaborate a little bit on how you solved this issue or what the exact problem was?

**Comment by yzhgu** [comment]
> @yzhgu can you elaborate a little bit on how you solved this issue or what the exact problem was?

The problem is that I have vpn connected in the client. It works fine after I disconnect the vpn.
