### ISSUE TITLE
[Feature Request] 对于 tcp_mux = true 的情况，能否每个 frpc 连接 frps的时候，建立多条固定的TCP通道，以提高速率？

### ISSUE THREAD

**Issue by yelky** [fatedier/frp#3555]
### Describe the feature request

经过监控，tcp_mux = true 的情况下，对于外网服务器连接国内的情况，单线程通讯对于下载类的应用测速发现不友好，速度慢，无法满速，特别是ping比较高的情况下。但是 tcp_mux= false 的情况下，虽然可以达到满速，但是却会触发电信运营商或者强的限制，短时间内发起过多的链接，造成IP短时被屏蔽，造成一些例如  io/timeout 之类的，被rst之类的。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by linzhengwu** [comment]
速度只有400-600K多！怎么配置都没用！苦恼！

**Comment by yelky** [comment]
新版本0.50以上的版本已经通过调整MaxStreamWindowSize解决了这个问题，高延迟网络速度还是可以的。tcp_mux=true速度已经倍增。

**Comment by yelky** [comment]
新版本0.50以上的版本已经通过调整MaxStreamWindowSize解决了这个问题，高延迟网络速度还是可以的。tcp_mux=true速度已经倍增。
