### ISSUE TITLE
最近电脑中勒索病毒，如何配置可以更加安全

### ISSUE THREAD

**Issue by arvinws** [fatedier/frp#3557]
### Bug Description

最近电脑中勒索病毒，公司网管怀疑是我使用内网穿透工具导致，想了解下如何配置更加安全，之前的配置如下_

### frpc Version

frp_0.33.0_windows_386

### frps Version

0.38.0

### System Architecture

linux/amd64

### Configurations

 #frps.ini
[common]
bind_addr = 0.0.0.0
bind_port = 50000
dashboard_addr = 0.0.0.0
dashboard_port = 7000
token = xxxxx
dashboard_user = xxx
dashboard_pwd = xxxx
log_file = ./frps.log
log_level = info
log_max_days = 3
disable_log_color = false

#frpc.ini
[common]
server_addr = 0.0.0.0
server_port = 50000
token = xxxxx

[rdp]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 6000

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Glucy-2** [comment]
1. 开启tls
2. 穿透出去的服务没有做好防护

**Comment by fatedier** [comment]
首先，你没有保持版本更新，那么可能存在一些历史问题没有修复。

其次，当你提出这个问题的时候，说明你对将服务暴露在公网上的安全相关的事务可能并不是非常清楚，那么建议就不要暴露有风险的服务。可以参考示例使用 stcp/xtcp，服务不直接暴露在公网上，会很大程度上避免你的内部服务弱口令，存在漏洞等问题。
