### ISSUE TITLE
frpc客户端中疑似木马HackTool.Linux.ServerProxy.BA

### ISSUE THREAD

**Issue by chralies** [fatedier/frp#3559]
### Bug Description

服务器中安装的frpc中扫描结果中被提示存在疑似木马程序。
病毒木马类型：HackTool.Linux.ServerProxy.BA
这个能消除么。

### frpc Version

0.46.0

### frps Version

0.46.0

### System Architecture

linux/amd64

### Configurations

[common]
server_addr = 192.168.90.1
server_port = 7000
token = etqqtest
admin_addr = 127.0.0.1
admin_port = 7400
[ssh]
type = tcp
local_ip = localhost
local_port = 22
remote_port = 2021

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
没办法，下载时注意比对md5码。
https://github.com/fatedier/frp/issues/2095

**Comment by yangjieshao** [comment]
抢向日葵饭碗了 懂吧

**Comment by chralies** [comment]
好的，明白了！谢谢~
