### ISSUE TITLE
如何使用frp搭建一个内网网站的反向代理

### ISSUE THREAD

**Issue by mckeyu** [fatedier/frp#356]
frpc、frps版本：0.11.0
客户端：处于内网中的树莓派，服务端：具有公网IP的路由器R6300 v2
已经在树莓派上成功的设置了ssh的穿透，现在想让frp代理内网中其他电脑的web，需要如何设置？

**Comment by fatedier** [comment]
https://github.com/fatedier/frp#visit-your-web-service-in-lan-by-custom-domains
