### ISSUE TITLE
客户端频繁异常掉线

### ISSUE THREAD

**Issue by Soirks** [fatedier/frp#3560]
### Bug Description

如题,大致每隔五六小时出现依次掉线，问了服务商说线路没问题，没有遭到攻击
有大佬可以帮忙猜测一下问题吗

### frpc Version

0.51.2

### frps Version

0.51.2

### System Architecture

windows/amd64

### Configurations

[pc]
tpc
ip
port
无复杂配置

### Logs

![image](https://github.com/fatedier/frp/assets/69170210/2ad3ac7e-76a2-43c3-b2a7-b28cfefe452f)

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by Becods** [comment]
使用第三方程序定期检测客服连接状况，以排除网络因素

**Comment by steveoOn** [comment]
> ### Bug Description
> 如题,大致每隔五六小时出现依次掉线，问了服务商说线路没问题，没有遭到攻击 有大佬可以帮忙猜测一下问题吗
> 
> ### frpc Version
> 0.51.2
> 
> ### frps Version
> 0.51.2
> 
> ### System Architecture
> windows/amd64
> 
> ### Configurations
> [pc] tpc ip port 无复杂配置
> 
> ### Logs
> ![image](https://user-images.githubusercontent.com/69170210/258000071-2ad3ac7e-76a2-43c3-b2a7-b28cfefe452f.png)
> 
> ### Steps to reproduce
> 
> ...
> 
> ### Affected area
> * [ ]  Docs
> * [ ]  Installation
> * [ ]  Performance and Scalability
> * [ ]  Security
> * [ ]  User Experience
> * [ ]  Test and Release
> * [ ]  Developer Infrastructure
> * [ ]  Client Plugin
> * [ ]  Server Plugin
> * [ ]  Extensions
> * [x]  Others

题主有发现什么原因吗？
