### ISSUE TITLE
copyright & plagiarize

### ISSUE THREAD

**Issue by Hua-An9527** [fatedier/frp#3561]
### Bug Description

https://www.openfrp.net/

### frpc Version

https://www.openfrp.net/

### frps Version

https://www.openfrp.net/

### System Architecture

https://www.openfrp.net/

### Configurations

https://www.openfrp.net/

### Logs

https://www.openfrp.net/

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by uruzFR** [comment]
Hello, what is the problem I do not understand.
Can you describe it please.

**Comment by liuchengts** [comment]
What is openFrp? What is the relationship with the current frp?

**Comment by eebssk1** [comment]
It has nothing to do with this project.
"OpenFrp(开放映射)是一个免费且完全公益性质的内网穿透映射，使用Github-Frp项目作为基础，连接到我们的面板。"
