### ISSUE TITLE
frp远程桌面获取真实ip

### ISSUE THREAD

**Issue by luckyjian0508xyz** [fatedier/frp#3562]
### Describe the feature request

frp远程桌面穿透如何获取客户端真实ip

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by CG1995** [comment]
绑定ddns就行了，frps和frpc客户端都用域名登录

**Comment by Becods** [comment]
[Proxy Protocol](https://github.com/fatedier/frp#proxy-protocol)
