### ISSUE TITLE
frps显示frpc已经连接但是无法使用

### ISSUE THREAD

**Issue by CG1995** [fatedier/frp#3563]
### Bug Description

[求助]
电信公网ip
绑定了域名
openwrt上安装了frps（0.48），主要用于windows 远程桌面。
openwrt上防火墙转发了7000端口
windows上的fprc（0.49）连接了frps，frps面板显示window接入并且一直显示是接入状态
windows上代理了本地端口3389，远程端口5389
然后用别的设备远程桌面这台windows一直连接不上

### frpc Version

0.49

### frps Version

0.48

### System Architecture

windows/amd64

### Configurations

openwrt上的frps版本 0.48
windows上的fprc版本0.49

### Logs

2023/08/08 04:13:22 [I] [service.go:500] [8cfa421506a92646] client login info: ip [xx.xx.xx.xx:7007] version [0.49.0] hostname [] os [windows] arch [amd64]
2023/08/08 04:13:22 [I] [tcp.go:66] [8cfa421506a92646] [RDPlp] tcp proxy listen port [5389]
2023/08/08 04:13:22 [I] [control.go:464] [8cfa421506a92646] new proxy [RDPlp] type [tcp] success

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
这貌似不是issue，而是设置问题。
比如：openwrt防火墙是否开启了5389端口？

**Comment by CG1995** [comment]
> 这貌似不是issue，而是设置问题。 比如：openwrt防火墙是否开启了5389端口？

你说的对。。。已经解决了，确实是要开放5389端口，感谢~~~
