### ISSUE TITLE
[Feature Request] 为什么需要客户端和服务端？ 

### ISSUE THREAD

**Issue by Locter9001** [fatedier/frp#3564]
### Describe the feature request

很奇怪呢，为什么一个内网穿透要客户端和服务端？这样的设计思路是为什么？我配置了几个小时了一直没配置好，为什么不能简单点呢，一个暴露IP+端口列表，再加几个参数不就可以了吗？为什么要这么绕啊

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
可以考虑选择一些开箱即用的产品服务，这个项目可能不是很适合你。

**Comment by yangjieshao** [comment]
你需要的是这个
https://www.natfrp.com/

**Comment by Locter9001** [comment]
重点是按照官方文档一步一步来，还是不行，很奇怪，命令行总是报错说vhost_https没有配置

**Comment by Locter9001** [comment]
![image](https://github.com/fatedier/frp/assets/96331179/2cd9f507-a27f-4025-a403-6b5dcb791252)

比如说这个，这个 x.x.x.x 改成127.0.0.1报 vhost_https_port is not set 不改默认就 x.x.x.x 就又说这个host找不到，然后我完全按照这个做的，就是更换了密钥和域名还有 127.0.0.0:80 这个地方，为什么官网示例跑不了啊就很奇怪，我是windows server 2012

**Comment by Locter9001** [comment]
@fatedier @yangjieshao

**Comment by Locter9001** [comment]
![1691594500920](https://github.com/fatedier/frp/assets/96331179/17b5cd03-6af6-4b79-9c9e-fd292fedfe5e)

**Comment by yangjieshao** [comment]
我现在知道了 
https://www.natfrp.com/ 
这个也不适合你
你还是花钱找人弄吧 专业的事交给专业的人（虽然 用这个东西 并不需要太专业）
你 基础的网络知识都还没有 用这个确实难为你了

**Comment by Locter9001** [comment]
> 我现在知道了 https://www.natfrp.com/ 这个也不适合你 你还是花钱找人弄吧 专业的事交给专业的人（虽然 用这个东西 并不需要太专业） 你 基础的网络知识都还没有 用这个确实难为你了

你是傻逼吧？

**Comment by Locter9001** [comment]
整个项目都是一群阴阳怪气的垃圾做的吧？自己文档写不好，还怪别人，你示例程序就应该能完全运行，典型的写完不负责。会一点破东西还一直阴阳怪气，我怎么用nginx做内网穿透？能做的话我会来找这玩意儿吗？

**Comment by Locter9001** [comment]
文档写的简单，用起来不简单啊？找台有公网的机器我找了，服务端和客户端都部署我也部署了，只要有公网那两个程序都是可以同时放到一个地方的，妈的这种**，你自己学的时候别人都是这么教你的吗？自私的🐕

**Comment by Locter9001** [comment]
花我那么多时间来折腾，结果就这样答复，社区是招募了一群垃圾了吧？你怎么不问问我为什么愿意用你这个东西？为什么愿意给你star？
