### ISSUE TITLE
[Feature Request] 希望可以在 frps 增加对请求者的带宽限制

### ISSUE THREAD

**Issue by BingYanchi** [fatedier/frp#3567]
### Describe the feature request

我知道现有的可以在 frpc 里添加对单个隧道的带宽限制，但它似乎不能用于对每个访问者进行带宽限制。

比如，对 TCP 隧道的每个访问者进行带宽的限制。限制每个访问者最高的带宽，避免因为某个访问者使用带宽过大而影响到其他访问者。

只不过有没有可能根据在线的访问数量，平分带宽？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by wuai1024** [comment]
这个我之前提过了，可能目前还没有考虑这个

**Comment by doveppp** [comment]
限制有解决方法了吗
我看着有个bandwidthLimitMode 能指定为server
不知道具体什么意思

**Comment by fidding** [comment]
> 现在有解决方法了吗 我看着有个bandwidthLimitMode 能指定为server 不知道具体什么意思

同一个客户端配置：client是每个连接，server是所有连接

**Comment by wuai1024** [comment]
就还是 frpc 客户端设置的限制，如果别人去掉这个配置，就又不限速了对吧。
