### ISSUE TITLE
frps 跑在电信公网ip中，frpc再铁通的nat 后面，每1分钟就链接短了

### ISSUE THREAD

**Issue by andsontan** [fatedier/frp#357]
下面是日志
2017/06/10 00:28:56 [I] [control.go:255] [57a3f20445540708] login to server success, get run id [57a3f20445540708]
2017/06/10 00:28:56 [I] [control.go:364] [57a3f20445540708] [dns] start proxy success
2017/06/10 00:28:56 [I] [control.go:364] [57a3f20445540708] [web] start proxy success
2017/06/10 00:28:57 [I] [proxy.go:206] [dns] incoming a new work connection for udp proxy, 14.118.130.203:7000
2017/06/10 00:29:56 [W] [control.go:279] [57a3f20445540708] read error: broken pipe
2017/06/10 00:29:56 [I] [proxy.go:235] [dns] writer goroutine for udp work connection closed
2017/06/10 00:29:56 [E] [control.go:172] [57a3f20445540708] work connection closed, broken pipe
2017/06/10 00:29:56 [W] [control.go:301] [57a3f20445540708] write message to control connection error: broken pipe
2017/06/10 00:29:56 [W] [proxy.go:221] [dns] read from workConn for udp error: broken pipe
2017/06/10 00:29:57 [I] [control.go:407] [57a3f20445540708] try to reconnect to server...
2017/06/10 00:29:58 [I] [control.go:255] [57a3f20445540708] login to server success, get run id [57a3f20445540708]
2017/06/10 00:29:59 [I] [control.go:364] [57a3f20445540708] [dns] start proxy success
2017/06/10 00:29:59 [I] [control.go:364] [57a3f20445540708] [web] start proxy success
2017/06/10 00:29:59 [I] [proxy.go:206] [dns] incoming a new work connection for udp proxy, 14.118.130.203:7000
2017/06/10 00:30:58 [W] [control.go:147] [57a3f20445540708] start new work connection error: writeFrame: broken pipe
2017/06/10 00:30:58 [W] [control.go:147] [57a3f20445540708] start new work connection error: writeFrame: broken pipe
2017/06/10 00:30:58 [W] [control.go:279] [57a3f20445540708] read error: broken pipe
2017/06/10 00:30:58 [I] [proxy.go:235] [dns] writer goroutine for udp work connection closed
2017/06/10 00:30:58 [W] [control.go:301] [57a3f20445540708] write message to control connection error: broken pipe
2017/06/10 00:30:58 [W] [proxy.go:221] [dns] read from workConn for udp error: broken pipe
2017/06/10 00:30:58 [E] [control.go:172] [57a3f20445540708] work connection closed, broken pipe
2017/06/10 00:30:59 [I] [control.go:407] [57a3f20445540708] try to reconnect to server...
2017/06/10 00:31:00 [I] [control.go:255] [57a3f20445540708] login to server success, get run id [57a3f20445540708]
2017/06/10 00:31:00 [I] [control.go:364] [57a3f20445540708] [dns] start proxy success
2017/06/10 00:31:00 [I] [control.go:364] [57a3f20445540708] [web] start proxy success
2017/06/10 00:31:00 [I] [proxy.go:206] [dns] incoming a new work connection for udp proxy, 14.118.130.203:7000

**Comment by fatedier** [comment]
为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。
