### ISSUE TITLE
无法连接dashboard

### ISSUE THREAD

**Issue by CleMooling** [fatedier/frp#3570]
### Bug Description

如题

### frpc Version

null

### frps Version

0.51.2

### System Architecture

linux/amd64

### Configurations

[common]
bind_port = 7000
bind_addr = 0.0.0.0
token = xxxxxx
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
![CM6PHS7AGGJPN31Y2DI83MS](https://github.com/fatedier/frp/assets/35525491/a788e639-a682-4c4c-96fb-218592d55fff)

**Comment by CleMooling** [comment]
请关闭此issue，问题已自行解决，由于网络原因未能及时自行关闭。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月13日(周日) 上午10:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fatedier/frp] 无法连接dashboard (Issue #3570)
