### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by liuchengts** [fatedier/frp#3577]
### Describe the feature request

Added the method of using frp in docker mode

### Describe alternatives you've considered

here is the solution:
https://github.com/liuchengts/frp-docker

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/dev/.github/workflows/build-and-push-image.yml

We have provided Docker images.

**Comment by liuchengts** [comment]
> https://github.com/fatedier/frp/blob/dev/.github/workflows/build-and-push-image.yml
> 
> 我们提供了 Docker 镜像。

Sorry, I didn't notice that there is already an official docker way. this is very good news

**Comment by liuchengts** [comment]
This is a fixed issue, I'm closing it
