### ISSUE TITLE
get hostname from http/https request error: i/o timeout

### ISSUE THREAD

**Issue by jwister** [fatedier/frp#358]
**你使用什么版本的frp（./frpc -v或./frps -v）？**
        0.11.0 

**你使用什么操作系统和处理器架构（`go env`）？**
    linux amd64   

**配置您使用的：**
服务端
  [common]
bind_port = 7000
vhost_http_port = 80
客户端
[common]
server_addr = frp.xxxxxx.xx
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 12580
remote_port = 6000

[web]
type = http
local_port = 12585
custom_domains = www.xxxxxx.xx

 **重现问题的步骤：**
   修改好配置文件
   启动服务端和客户端
  ssh转发没问题，但是http转发的时候 总是报一下错误
2017/06/11 11:43:47 [I] [proxy.go:165] [d71c1a7a8162c6c7] [ssh] tcp proxy listen port [6000]
2017/06/11 11:43:47 [I] [control.go:316] [d71c1a7a8162c6c7] new proxy [ssh] success
2017/06/11 11:43:47 [I] [proxy.go:204] [d71c1a7a8162c6c7] [web] http proxy listen for host [www.xxxxxx.xx] location []
2017/06/11 11:43:47 [I] [control.go:316] [d71c1a7a8162c6c7] new proxy [web] success
2017/06/11 11:44:03 [I] [proxy.go:76] [d71c1a7a8162c6c7] [ssh] get a new work connection: [103.240.125.67:23790]
2017/06/11 11:44:56 [E] [vhost.go:131] get hostname from http/https request error: EOF
2017/06/11 11:45:02 [E] [vhost.go:131] get hostname from http/https request error: read tcp 49.4.143.50:80->103.240.125.67:38100: i/o timeout
2017/06/11 11:45:26 [E] [vhost.go:131] get hostname from http/https request error: read tcp 49.4.143.50:80->103.240.125.67:31728: i/o timeout

之前用ngrok的时候 也是同样的问题 ssh没问题 http也是这个问题
 
 我想知道 这个是我配置的问题 还是运营商的主机问题  
谢谢了。

**Comment by fatedier** [comment]
根据你提供的信息还没法准确判断，但是猜测是运营商的主机主动将这个 80 端口的连接断开或者屏蔽了，可以发工单给你的服务器供应商。

**Comment by jwister** [comment]
可是，http的端口我换过8080  8000  等。都是一样的问题。

**Comment by fatedier** [comment]
1. 可以通过 tcpdump 抓 80 端口的数据包，然后贴上来帮你分析。
2. 邮件我服务器环境，帮你调试看下。

**Comment by fatedier** [comment]
你的云服务器提供商屏蔽了 http 请求包，所以任何端口都不行，这种情况下，最简单的做法就是自己装一个 nginx 看是否能访问，该问题和 frp 无关。
