### ISSUE TITLE
请问一下， 支持动态IP地址吗？ 我的内网是动态IP 地址， 也就是IP会变动， 今天问了运营商， 说是动态IP地址， 这个支持吗？ 动态IP地址。 [Feature Request] 

### ISSUE THREAD

**Issue by dellshan** [fatedier/frp#3583]
### Describe the feature request

请问一下， 支持动态IP地址吗？ 我的内网是动态IP 地址， 也就是IP会变动， 今天问了运营商， 说是动态IP地址， 这个支持吗？ 动态IP地址。 

### Describe alternatives you've considered

请问一下， 支持动态IP地址吗？ 我的内网是动态IP 地址， 也就是IP会变动， 今天问了运营商， 说是动态IP地址， 这个支持吗？ 动态IP地址。 

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by gainskills** [comment]
你尝试一下 DDNS, 然后通过DDNS到域名链接.  DDNS不是frp实现的, 具体的步骤, 建议在网上搜索一下.

**Comment by Stone-yu** [comment]
你内网ip跟运营商没啥关系，变动也没关系，连接时客户端主动向服务端发起的。服务端部署好后ip和端口不变

**Comment by Stone-yu** [comment]
担心内网ip的变动，你可以设置静态ip地址

**Comment by JohnGump** [comment]
如果你是静态IP，那你就不需要穿墙啦，就是因为动态IP才用frp的

**Comment by kaine1973** [comment]
我有一个类似的问题。
服务端使用的是DDNS更新ip到cloudflare域名。
客户端设置的服务端ip为域名。那么域名指向ip变更后，客户端可能不会自动重新解析域名连接到新的IP？
