### ISSUE TITLE
frp 在macOS Monterey操作系统上运行有问题

### ISSUE THREAD

**Issue by myhnuhai** [fatedier/frp#3586]
### Bug Description

frp 在macOS Monterey操作系统上运行有问题，frpc服务运行不了
具体日志：
2023/08/25 11:01:50 [I] [root.go:220] start frpc service for config file [frpc_stcpVisitor.ini]
2023/08/25 11:01:50 [W] [service.go:133] login to server failed: session shutdown
2023/08/25 11:01:50 [I] [root.go:236] frpc service for config file [frpc_stcpVisitor.ini] stopped

### frpc Version

0.51.3

### frps Version

0.33

### System Architecture

macOS monterey

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
有什么问题，也不说清。
我在此系统用frpc，主要是tcp和stcp没发现问题。

**Comment by Becods** [comment]
检查frps是否正常
