### ISSUE TITLE
frp如何在windows sever2012版本以上结合nginx使用

### ISSUE THREAD

**Issue by yujunchengg** [fatedier/frp#3595]
### Describe the feature request

我现在假如在windows server A这台云服务器上本身有启动nginx进程，然后我在阿里云后台去解析了个二级域名到这个服务器，我试了一下再启动frp server端，并且设置server端的vhost_http_port的值为80端口，因为我看文档说如果要代理http的话，要设置这个端口值，然后我再设置了个subdomain_host = 刚在阿里云后台解析的二级域名，然后我在客户端，本地一个内网主机服务器上面配置frpc相关配置，然后启动，我去访问，访问不到，frps和frpc配置文件分别如下所示

![image](https://github.com/fatedier/frp/assets/36986915/4730b649-c3bd-4e86-82fd-f326bc48c0fc)

![frpc](https://github.com/fatedier/frp/assets/36986915/1fd05368-677a-4379-817f-40fd513356d8)

上面截图中的公网ip是随便写的，其它配置我看跟文档都是保持一致的，但是就是访问不到内网我nginx监听的8300端口

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by aienuo** [comment]
同求啊，本来我也想着  所有的端口都走nginx 转发 配置，还想着用Nginx 代理 frp 的7500 端口 来减少对外暴露的端口，可惜我没搞出来。
