### ISSUE TITLE
frpc.exe会被Windows安全中心当作病毒隔离

### ISSUE THREAD

**Issue by alexfeeling** [fatedier/frp#3596]
### Describe the feature request

在一些机子上，frpc.exe会被Windows安全中心当作病毒隔离，需要手动加入白名单才可以，请问如何解决默认就不会触发隔离呢？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Silence-dream** [comment]
将Windows安全中心关了就好了,没必要开启

https://zhuanlan.zhihu.com/p/365896473
