### ISSUE TITLE
frp的subdomin不支持3级域名

### ISSUE THREAD

**Issue by yujunchengg** [fatedier/frp#3598]
### Describe the feature request

frp使用泛域名匹配模式代理http的时候，我域名是3级域名，比如a.b.baidu.com这种，我在frpc.ini的subdomin中设置为这个3级域名，启动直接失败

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
https://gofrp.org/docs/features/http-https/subdomain/
