### ISSUE TITLE
增加免服务端配置模式

### ISSUE THREAD

**Issue by chmis8000** [fatedier/frp#36]
前几天，在邮件中提过，这里再次写上来，补充些想法。
Ngrok 是免服务端配置的，指新增加一个c端配置，s端不用重改ini 且重启服务才能生效。

免服务端配置，起码适用于分享s端的盆友。
如 Ngrok  已知国内的 免费服务：
http://www.qydev.com/  北京阿里云
http://www.ittun.com/  深圳阿里云
http://www.natapp.cn/ 深圳阿里云（已商业化）
http://www.ngrok.cc/ 香港
http://www.gotunnel.org/  香港

有些都是在校朋友，如，阿里云有在校生优惠计划，9.92元/月， 愿意分享的会公开给大家服务。
希望frp 借鉴 Ngrok， 增加仅c端配置模式。
另外，结合前面一个issues，或许加个流量限制参数，本来免费提供大家s端的，限制极端使用的用户超流量。

**Comment by fatedier** [comment]
这个功能将在下个版本添加，至于一些平台化的需求目前还不是重点。
