### ISSUE TITLE
frps怎么能显示请求的内容

### ISSUE THREAD

**Issue by zjtjustin** [fatedier/frp#3607]
### Describe the feature request

1、日志如何配置才能看到请求头、参数、返回值等
2、在frps所在服务器上，如何配套第三方工具进行抓包，想直观的看到请求和返回信息？（服务器启动抓包工具charles、anyproxy、whistle）。proxy_bind_addr是否配置抓包用的。例如开启了 whistle8899端口的抓包服务， 配置了proxy_bind_addr = 127.0.0.1:8899 ，frpc上的代理好像就不好使了

### Describe alternatives you've considered

希望能看到相关的请求和返回信息

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [x] Others

**Comment by fengyuclub** [comment]
如果能将日志转发到专用日志服务器（类似rsyslog、splunk）就好了，目前用的log_max_days参数
