### ISSUE TITLE
FRP支持UPnP？

### ISSUE THREAD

**Issue by linkerlin** [fatedier/frp#361]
如果让FRP直接支持UPnP协议，即frpc把自己模拟成一个支持UPnP协议的家用路由器。
这样子，大部分支持UPnP的P2P软件完全不需要配置啊。

**Comment by linkerlin** [comment]
举个例子，很多P2P下载软件会自动搜索UPnP路由器，开启NAT端口映射。
如果FRP能把自己模拟成一台路由器，并支持UPnP，那么很多P2P软件无需修改和配置就可以直接用上FRP的功能了。

**Comment by fatedier** [comment]
不是很理解这个场景。目前不打算考虑支持额外的应用层的协议，
