### ISSUE TITLE
armbian无法开机自动frpc

### ISSUE THREAD

**Issue by lamhui** [fatedier/frp#3611]
### Bug Description

![frpc](https://github.com/fatedier/frp/assets/76201983/8f5e8472-3df9-4009-9bde-01191825e5e6)
按照网上的教程拉取安装frpc插件并配置frpc.ini文件，之后再在 /usr/lib/systemd/system下创建frpc.service服务以便于机器每次启动后能自启动frpc应用，可是每次重启或者开机后都无法顺利进行并出现以上截图信息，只能手动输入指令systemctl restart frpc重新启动frpc后才能顺利启动和使用，不知道到底是哪里出错了还是程序的bug望知道的指点一二，先谢过！

### frpc Version

0.51.3

### frps Version

N/A

### System Architecture

armbian/arm64

### Configurations

[Unit]
#服务描述
Description=frpc service 
After=network.target syslog.target
Wants=network.target

[Service]
Type=simple
#执行命令 
ExecStart=/usr/local/frpc/frpc -c /usr/local/frpc/frpc.ini

[Install]
WantedBy=multi-user.target

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by aienuo** [comment]
这个是我在  ConstOs8.5 里面的配置你可以做个参考（其中我对 service 文件权限做了最大处理）： https://gitee.com/xinlau/DocumentationAndTutorials/blob/master/Linux/FRP.md
