### ISSUE TITLE
[Feature Request] 如何批量反代子域名？

### ISSUE THREAD

**Issue by JZLeung** [fatedier/frp#3615]
### Describe the feature request

后台服务会自动创建多个子域名以区分应用，并且用 header_host 来做校验。如一个appId为xxx的应用，它的url为：

```
[app-xxx]
type=http
local_ip=192.168.3.1.nip.io
local_port=80
custom_domains=xxx.frp.example.com
host_header_rewrite = xxx.192.168.3.1.nip.io
```

创建多个子应用，则需要在 frpc.ini 中增加多个反代条目，有点麻烦。

### Describe alternatives you've considered

能否自定义重写规则？

```
[app-*]
type=http
local_ip=192.168.3.1.nip.io
local_port=80
custom_domains=$1.frp.example.com
host_header_rewrite = $1.192.168.3.1.nip.io
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [x] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
你可以写一个脚本批量创建和维护。

各种各种简化的需求可以有很多，配置本身只提供最基础的能力，否则难以维护，其他额外的需求都可以通过脚本或外部程序实现。
