### ISSUE TITLE
XTCP 无法使用提示：xtcp is not supported by server

### ISSUE THREAD

**Issue by yale8888** [fatedier/frp#3617]
### Bug Description

XTCP P2P服务无法使用。
客户端这个提示是什么原因。
2023/09/16 14:18:59 [E] [visitor.go:209] [074352678918a875] [p2p_ssh_visitor_3] xtcp is not supported by server
下载的文件是官方最新的文件。
0.51.3版本里面的文件。成品文件。

不定期出现此问题。有时重启电脑能解决，有时重启电脑还是一样。

### frpc Version

0.51.3

### frps Version

0.51.3

### System Architecture

Windows 7  64 

### Configurations

2023/09/16 14:18:51 [I] [service.go:357] [074352678918a875] login to server success, get run id [074352678918a875], server udp port [0]

2023/09/16 14:18:51 [I] [visitor_manager.go:86] [074352678918a875] start visitor success
2023/09/16 14:18:51 [I] [visitor_manager.go:86] [074352678918a875] start visitor success
2023/09/16 14:18:51 [I] [visitor_manager.go:86] [074352678918a875] start visitor success
2023/09/16 14:18:51 [I] [visitor_manager.go:86] [074352678918a875] start visitor success
2023/09/16 14:18:51 [I] [visitor_manager.go:128] [074352678918a875] visitor added: [p2p_ssh_visitor_1 p2p_ssh_visitor_2 p2p_ssh_visitor_3 p2p_ssh_visitor_4]

2023/09/16 14:18:59 [E] [visitor.go:209] [074352678918a875] [p2p_ssh_visitor_3] xtcp is not supported by server

### Logs

[common]
bind_port=58888
bind_udp_port=59999
token=1234ABCD
dashboard_port=1979
dashboard_user=admin
dashboard_pwd=admin
udp_packet_size=15000
#====================

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by yale8888** [comment]
服务端提示：

2023/09/16 14:34:58 [I] [root.go:204] frps uses config file: frps.ini

2023/09/16 14:35:06 [I] [service.go:206] frps tcp listen on 0.0.0.0:58888
ini
s
%
2023/09/16 14:35:06 [I] [service.go:318] Dashboard listen on 0.0.0.0:1979
2023/09/16 14:35:06 [I] [root.go:213] frps started successfully
c
2023/09/16 14:35:07 [I] [service.go:539] [074352678918a875] client login info: ip [120.227.204.36:29986] version [0.45.0] hostname [] os [windows] arch [amd64]
wX.
2023/09/16 14:35:07 [I] [service.go:539] [3d949be3f541972d] client login info: ip [120.227.204.36:29989] version [0.51.3] hostname [] os [windows] arch [386]
]
wX.
2023/09/16 14:35:07 [I] [stcp.go:56] [3d949be3f541972d] [p2p_ssh_1] stcp proxy custom listen success

2023/09/16 14:35:07 [I] [control.go:497] [3d949be3f541972d] new proxy [p2p_ssh_1] type [stcp] success
2023/09/16 14:35:07 [I] [control.go:497] [3d949be3f541972d] new proxy [p2p_ssh_2] type [xtcp] success
2023/09/16 14:35:07 [I] [control.go:497] [3d949be3f541972d] new proxy [p2p_ssh_3] type [xtcp] success
2023/09/16 14:35:07 [I] [control.go:497] [3d949be3f541972d] new proxy [p2p_ssh_4] type [xtcp] success
>t

**Comment by fatedier** [comment]
服务端和客户端都更新到最新

**Comment by superzjg** [comment]
bind_udp_port  这个参数貌似在最近更新的新版里面已经被删除。

**Comment by yale8888** [comment]
XTCP还支持吗，没有这个监听端口。




imoffices
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fatedier/frp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月17日(星期天) 中午11:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fatedier/frp] XTCP 无法使用提示：xtcp is not supported by server (Issue #3617)





 
bind_udp_port  这个参数貌似在最近更新的新版里面已经被删除。

**Comment by superzjg** [comment]
> XTCP还支持吗，没有这个监听端口。 imoffices ***@***.*** &nbsp;
> […](#)

支持的，并且进行了重构（v0.49及以后），打洞成功率更高。

**Comment by yale8888** [comment]
试了很多次，首次连接，需要多次连接XTCP才会成功。不知道什么原因。连接5-10次。时间在5-10分钟，持续不断，点击连接。就会成功。
不像STCP，秒连。






imoffices
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fatedier/frp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月18日(星期一) 中午1:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fatedier/frp] XTCP 无法使用提示：xtcp is not supported by server (Issue #3617)





  
XTCP还支持吗，没有这个监听端口。 imoffices @.*** &nbsp;
 …
  
支持的，并且进行了重构（v0.49及以后），打洞成功率更高。
