### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by anjasamar** [fatedier/frp#3619]
### Bug Description

Windows detect as virus

### frpc Version

latest

### frps Version

latest

### System Architecture

Windows/X64

### Configurations

not yet just download and get defender issue

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
https://github.com/fatedier/frp/issues/2095
