### ISSUE TITLE
windows 怎么后台运行，不借用第三方工具

### ISSUE THREAD

**Issue by Yancy0220** [fatedier/frp#3621]
### Describe the feature request

windows 怎么后台运行，不借用第三方工具

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Glucy-2** [comment]
计划任务

**Comment by aienuo** [comment]
我现在是把他注册到服务里面，参考：https://gitee.com/xinlau/DocumentationAndTutorials/blob/master/Windows/FRP-Client.md

**Comment by Walkersifolia** [comment]
简单点的写个vbs放在启动文件夹里就行了，Win+R打开运行，输入shell:startup，把vbs脚本放里面，就像这样
![image](https://github.com/fatedier/frp/assets/129571444/2f0a30e2-eeb8-438c-82f6-6d88cfb037e6)

**Comment by Walkersifolia** [comment]
然后就能看见了，开机自启动，并且没有cmd窗口
![image](https://github.com/fatedier/frp/assets/129571444/ac610e7f-afb8-457c-9f87-67015271b635)

**Comment by cholau0** [comment]
vbs这个好！

**Comment by wzshuang** [comment]
> 简单点的写个vbs放在启动文件夹里就行了，Win+R打开运行，输入shell:startup，把vbs脚本放里面，就像这样 ![image](https://user-images.githubusercontent.com/129571444/273459235-2f0a30e2-eeb8-438c-82f6-6d88cfb037e6.png)

求vbs脚本

**Comment by Walkersifolia** [comment]
> 求vbs脚本
路径记得自己改一下

**Comment by wzshuang** [comment]
> > 求vbs脚本
> 
> ```
> Set WshShell = CreateObject("WScript.Shell") 
> WshShell.Run chr(34) & "D:\frp.bat" & Chr(34), 0
> Set WshShell = Nothing
> ```
> 
> frp.bat里就是正常的frp启动命令`frpc -c D:/frp/frpc.ini`

收到，感谢

**Comment by Meta39** [comment]
最好还是用第三方工具WinSW把frpc做成服务放到服务里面。我试过写脚本放到shell:startup有时候不行！最稳妥还是用windows的服务！用米家智能WIFI插座 + 服务，现在很稳定！基本上想开机就开机，想关机就关机！
![image](https://github.com/fatedier/frp/assets/57950116/17ea3c03-a84e-4ba9-b1f2-3bc7e9e4f78f)

[可以参考一下这篇文章《使用WinSW第三方工具设置开机启动》](https://blog.csdn.net/weixin_43933728/article/details/132783275)

**Comment by Xiaeer** [comment]
```
Set shell = Wscript.CreateObject("WScript.Shell")

maxRetryCount = 3
retryDelay = 5000 ' 5秒

retryCount = 0
exitCode = -1

Do While retryCount < maxRetryCount And exitCode <> 0
    If retryCount > 0 Then
        Wscript.Sleep retryDelay
    End If
    
    retryCount = retryCount + 1
    
    ' Wscript.Echo "Running command: frpc.exe -c frpc.toml (Attempt " & retryCount & ")..."
    exitCode = shell.Run("frpc.exe -c frpc.toml", 0, False)
    
    If exitCode <> 0 Then
        ' Wscript.Echo "Command failed with exit code: " & exitCode
        ' Wscript.Echo "Retrying..."
    End If
Loop

If exitCode = 0 Then
    ' Wscript.Echo "Command executed successfully."
Else
    Wscript.Echo "Command execution failed after " & maxRetryCount & " attempts."
End If
```
个人觉得这个 vbs 脚本稍微好些，自带重试功能，因为我发现，vbs 自启 frpc 时，网卡没加载完毕时，frpc 进程会直接崩溃退出，`loginFailExit = false` 设置了都没用，一样崩溃退出。
