### ISSUE TITLE
[Feature Request] Stun Support username and credential

### ISSUE THREAD

**Issue by chuanxinwong** [fatedier/frp#3622]
### Describe the feature request

我使用coturn搭建了一个stun服务，带有账号密码， 在webRTC中使用正常：
```js
var stun = {
    iceServers: [
      // my server
      {
        urls: "turn:xxx.xx.xx.xxx:3478",
        username: "joey",
        credential: "bluebluesky",
      },
      //{ urls: "stun:stun.services.mozilla.com" },
     // { urls: "stun:stun.l.google.com:19302" },
    ],
  },
```
我在frp中的写法：
```ini
[common]
server_addr = xx.xx.xx.xxx
server_port = 7000
token = eFFwDjrG
nat_hole_stun_server joey:bluebluesky@xxx.xx.xx.xxx:3478
```
要如何设置用户名密码?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Not supported.

**Comment by chuanxinwong** [comment]
> Not supported.

May I ask if there are any plans to support it in the future?

**Comment by fatedier** [comment]
No plan for that. This seems to be something that very few ordinary users would need, and the subsequent maintenance cost of the related functionality is high. The cost of building this test environment is very high, and it is difficult for us to maintain it in the long term.
