### ISSUE TITLE
[Feature Request] 我在使用命令行启动时参数出现问题，frps配置了fp-multiuser

### ISSUE THREAD

**Issue by 65658dsf** [fatedier/frp#3623]
### Describe the feature request

 .\frpc tcp -s 服务器ip:端口 -l 888 -r 56001 -u 用户名 --meta_token 密码
Error: unknown flag: --meta_token
这个应该如何解决

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [x] Client Plugin
- [x] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
不支持 meta_token 参数。
