### ISSUE TITLE
日志文件显示的时间与linux系统时间不一致

### ISSUE THREAD

**Issue by caiwenmin** [fatedier/frp#3628]
### Bug Description

frpc日志文件输出的时间比系统时间早8小时整，，导致连接不上frps服务端（服务端机器时间与客户端机器时间一致）

### frpc Version

0.51.3

### frps Version

0.51.3

### System Architecture

linux/amd64

### Configurations

就正常的配置

### Logs

2023/09/23 11:50:06 [W] [service.go:133] login to server failed: EOF

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by caiwenmin** [comment]
查了一下问题，应该是time.Now()获取的默认是UTC时间的时区，代码中未做时区转换，这就导致了时间一直是UTC时区

**Comment by superzjg** [comment]
曾在openwrt上安装zoneinfo-asia解决此问题，实际上就是补全了/usr/share/zoneinfo/Asia/Shanghai文件。但在华硕路由器的官改固件上，因为/zoneinfo/Asia/Shanghai文件不在/usr/share目录下，且无法修改，frpc日志时间就差8小时（但是可以与上述openwrt的frps正常连接使用）。以上都是linux内核系统，供参考。

**Comment by caiwenmin** [comment]
frpc按照你的方法可以解决日志时间不对的问题，，frps也存在同样的问题要怎么做呀

**Comment by superzjg** [comment]
> frpc按照你的方法可以解决日志时间不对的问题，，frps也存在同样的问题要怎么做呀

方法一样的，重启一下系统。

**Comment by caiwenmin** [comment]
frps是在debian 11系统上docker启动的，，时区还是和宿主机时区不一致，，设置了TZ也不生效

**Comment by superzjg** [comment]
> frps是在debian 11系统上docker启动的，，时区还是和宿主机时区不一致，，设置了TZ也不生效

我刚测试不影响使用：frps 0.47的日志（差8小时），可以接受frpc0.51.3的连接：
2023/09/26 02:18:33 [I] [root.go:206] frps uses config file: /tmp/upload/.frps.ini
2023/09/26 02:18:46 [I] [service.go:200] frps tcp listen on 0.0.0.0:7000
2023/09/26 02:18:46 [I] [service.go:226] frps quic listen on quic 0.0.0.0:7000
2023/09/26 02:18:46 [I] [root.go:215] frps started successfully
2023/09/26 02:20:06 [I] [service.go:500] [5023f2c901278dbd] client login info: ip [[240e:382:5a6:2f00::1]:57962] version [0.51.3] hostname [] os [linux] arch [arm64]
2023/09/26 02:20:06 [I] [tcp.go:66] [5023f2c901278dbd] [smb] tcp proxy listen port [12345]
2023/09/26 02:20:06 [I] [control.go:464] [5023f2c901278dbd] new proxy [smb] type [tcp] success

**Comment by superzjg** [comment]
> 我frps 0.51.3（日志差8小时），frpc0.51.3（时间正确） 但是服务端接收不到客户端的连接
> 
> 客户端日志 2023/09/26 19:03:01 [I] [root.go:220] start frpc service for config file [/var/etc/frp/frpc.conf]
> 
> 服务端无任何日志

那就是配置文件问题，或者防火墙没打通，仔细检查，应该跟时间没关系

**Comment by caiwenmin** [comment]
宝塔对应的端口都放开了呀，，唉，折腾好几天了
