### ISSUE TITLE
[Feature Request] Global SSL

### ISSUE THREAD

**Issue by ckpw** [fatedier/frp#3629]
### Describe the feature request

how can i do it so it sets a cert like let's encrypt for https on server side so i don't need to set it on the client side, like ngrok? i know there's the tls mode but i think this is only for authentication, i want a thing like dashboard_tls_mode = true, but globally, on all https

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Please read the doc first.

**Comment by ckpw** [comment]
I don't know what do you wanna mean with that, I read the entire doc and couldn't find something similar to this
