### ISSUE TITLE
[Feature Request] Ability to configure failover

### ISSUE THREAD

**Issue by vithusel** [fatedier/frp#3631]
### Describe the feature request

Some of my servers have multiple uplinks so have multiple potential routes to take in the event of a failure. 

Is there a way we can enable a fail over option? so config similar to below. 

Node 1 

[common]
server_port = 7003
token = sanitized
log_file = /root/frpc/frpc.log
log_max_days = 3
server_addr = demo.url.sanitized

[sanitized-80]
type = http
server_order = 1
local_ip = 127.0.0.1
local_port = 80
use_encryption = false
use_compression = true
custom_domains = demo.url.sanitized

[sanitized-443]
type = https
server_order = 1
local_ip = 127.0.0.1
local_port = 443
use_encryption = false
use_compression = true
custom_domains = demo.url.sanitized

Node 2 

[common]
server_port = 7003
token = sanitized
log_file = /root/frpc/frpc.log
log_max_days = 3
server_addr = demo.url.sanitized

[sanitized-80]
type = http
server_order = 2
local_ip = 127.0.0.1
local_port = 80
use_encryption = false
use_compression = true
custom_domains = demo.url.sanitized

[sanitized-443]
type = https
server_order = 2
local_ip = 127.0.0.1
local_port = 443
use_encryption = false
use_compression = true
custom_domains = demo.url.sanitized

so the lower number for server_order is always used first. If a connection cannot be achieved it then fails over to the next one. This would give excellent DR capabilities to this amazing utility. 

### Describe alternatives you've considered

Configuring a load balancer in front of the server frp so it can decide which route to take using roundrobin algo. But this would mean setting up two independent frp environments which is a lot of work in terms of management and increases odds of failure / troubleshooting issues. 

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp#load-balancing

Does this feature help?

**Comment by vithusel** [comment]
@fatedier i previously saw this but was unsure if this works when there is https enabled?

**Comment by fatedier** [comment]
Only for `tcp, http, tcpmux`, `https` is not support.

This is not within the short-term plan, but it will be considered for support later.
