### ISSUE TITLE
[Feature Request] http/https隧道是否支持`custom-domains`绑定通配符域名

### ISSUE THREAD

**Issue by 8MiYile** [fatedier/frp#3634]
### Describe the feature request

就是像域名解析那样支持通配符 然后直通域名
因为我后端是一个nginx多域名服务 三种后缀 N条二级域名，想只是用6条域名来解决
例如 *.xxx.com,*.xxx.net
或者更极端的 *.xxx.*

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
支持。
