### ISSUE TITLE
How to limit the client only can access specified ports by OIDC.

### ISSUE THREAD

**Issue by bnuzhouwei** [fatedier/frp#3636]
### Describe the feature request

OIDC is a useful feature to validate clients so that some clients can be disabled as wish.

But how to limit the client only can access specified ports?

i.e limit the ports and service count in the server.

### Describe alternatives you've considered

When oidc auth, send ports and client ak, sk together, so that we can custom the OIDC server to determine whether sending id_token or not.

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Try https://github.com/fatedier/frp#server-manage-plugins
