### ISSUE TITLE
type [http] error: type [http] not support when vhost_http_port is not set

### ISSUE THREAD

**Issue by manishbuttan** [fatedier/frp#3639]
### Bug Description

Hello, I have put the vhost_http_port in my ini file for the server, but the server still gives this errror. What am I doing wrong? The server is AWS EC2 Amazon 2023 linux. The client is running on rpi cm4 with the latest raspbian OS.

frps.ini:
[common]
bind_port = 7000
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = xyz@pi
vhost_http_port = 8080 
subdomain_host = 12.12.12.12.xip.io #ip changed here

[common]
server_addr = 12.12.12.12 #ip changed
server_port = 7000

[some_name]
type = http
local_ip = 192.168.1.42
local_port = 8000
subdomain = some_name

### frpc Version

0.51.3

### frps Version

0.51.3

### System Architecture

Amazon AWS linux 2023 and Rpi raspbian os 

### Configurations

Provided in message

### Logs

pi@raspberrypi:~/frp_0.51.3_linux_arm64 $ ./frpc -v
0.51.3
pi@raspberrypi:~/frp_0.51.3_linux_arm64 $ sudo ./frpc -c frpc.ini
2023/10/03 08:58:10 [I] [root.go:220] start frpc service for config file [frpc.ini]
2023/10/03 08:58:10 [I] [service.go:301] [fe5d7d28f65bdd24] login to server success, get run id [fe5d7d28f65bdd24]
2023/10/03 08:58:10 [I] [proxy_manager.go:150] [fe5d7d28f65bdd24] proxy added: [cms_main_rpi_0001]
2023/10/03 08:58:10 [W] [control.go:170] [fe5d7d28f65bdd24] [cms_main_rpi_0001] start error: type [http] not support when vhost_http_port is not set
----
$ sudo ./frps -c frps.ini
2023/10/03 03:27:59 [I] [root.go:204] frps uses config file: frps.ini
2023/10/03 03:28:00 [I] [service.go:206] frps tcp listen on 0.0.0.0:7000
2023/10/03 03:28:00 [I] [service.go:318] Dashboard listen on 0.0.0.0:7500
2023/10/03 03:28:00 [I] [root.go:213] frps started successfully
2023/10/03 03:28:10 [I] [service.go:539] [fe5d7d28f65bdd24] client login info: ip [58.84.62.172:22244] version [0.51.3] hostname [] os [linux] arch [arm64]
2023/10/03 03:28:10 [W] [control.go:493] [fe5d7d28f65bdd24] new proxy [cms_main_rpi_0001] type [http] error: type [http] not support when vhost_http_port is not set

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by manishbuttan** [comment]
In the comment, the config was:
---
frps.ini:
[common]
bind_port = 7000
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = xyz@pi
vhost_http_port = 8080
subdomain_host = 12.12.12.12.xip.io #ip changed here

frpc.ini
[common]
server_addr = 12.12.12.12 #ip changed
server_port = 7000

[some_name]
type = http
local_ip = 192.168.1.42
local_port = 8000
subdomain = some_name

**Comment by fatedier** [comment]
Your `vhost_http_port` configuration is not taking effect, and I'm not sure what the reason is. It could be due to using the wrong configuration file or something similar.

**Comment by manishbuttan** [comment]
Thank you for your reply fatedier. I tried this again with a registered domain as the subdomain host and it worked fine. Thank you for writing this software.

**Comment by share32** [comment]
> some_name

could you please share your new config? i get the same issue, tks.
