### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by chaoscreater** [fatedier/frp#364]
This isn't really an issue but more of a question.

How can I configure frp similar to NGROK, so that it generates a public address for you to use? For example, with NGROK you can do this:
ngrok.exe tcp 8080

NGROK then generates a public URL for you to use, e.g.:
http://0.tcp.ngrok.io:41184

So you can simply type in the above URL from an external host, and it will connect to port 8080 on your localhost. Easy.

I'm looking for something similar here with FRP. I don't have a public IP for my server. I would have to ask our company's network team to give me one (they will most definitely not give me one for testing). The server is behind a router and firewall and port forwarding can't be setup.

NGROK works, but it only tunnels TCP ports and not UDP. How can I get this to work on FRP?

**Comment by fatedier** [comment]
Sorry, now we don't provide a public frp server for testing. So you need to deploy frps on a server with a public IP by your self and use your own custom domain.
