### ISSUE TITLE
http_proxy 代理请求网站提示连接已重置

### ISSUE THREAD

**Issue by Hhpon** [fatedier/frp#3640]
### Bug Description

背景： 我们学校的一些网站只有校园内网可以访问，我现在经常不在学校，所以有的时候希望浏览一些资源的时候不是很方便。
解法：使用http_proxy转发http请求；网站A即是只有内网可以访问的网站，我在frpc运行的机器上访问网站A时可以访问，使用代理连接的机器上访问网站A就会提示连接已重置。

### frpc Version

0.51.3

### frps Version

0.38.0

### System Architecture

ubuntu/amd64, windows/amd64

### Configurations

[common]
server_addr = xx.xx.xx.xx
server_port = 7000
log_file = logs/http_proxy.log
log_level = info
log_max_days = 3
protocol = tcp
login_fail_exit = false
tcp_mux = true
tls_enable = true

[X6sZX9Rj]
type = tcp
group = http_proxy
group_key = web
local_ip = 127.0.0.1
plugin = http_proxy
health_check_type = tcp
health_check_timeout_s = 3
health_check_max_failed = 3
health_check_interval_s = 10
remote_port = 6001

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
~~被发现了~~

**Comment by Hhpon** [comment]
> ~被发现了~

所以有什么办法解决不？
