### ISSUE TITLE
[Feature Request] I don't know if I already have this requirement! Does FRPC support multiple domain names?

### ISSUE THREAD

**Issue by worm001** [fatedier/frp#3643]
### Describe the feature request

Can the key parameter 'server_addr=' in the [common] field of the FRPC client support multiple domain names? For example: [123. f3322. net] [123. x3322. net], can we restart the second domain to take effect when the first domain name fails? It is best to support up to 3 domain names! When the specified port corresponding to the first domain name is invalid, automatically switch to the second or third domain name?

frpc客户端方面[common]字段里的"server_addr =" 这个很关键的参数，可否支持多域名？比如: [123.f3322.net][123.x3322.net]，经常会遇到第1域名失效的时候能不能再启动第2域名生效呢？最好能支持多达3个域名！当第1域名对应指定的端口无效时，自动切换到第2个，第3个？

### Affected area

- [ ] Docs
- [X] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Currently, there are no plans to support it.
