### ISSUE TITLE
Document full configuration file link error

### ISSUE THREAD

**Issue by maoxuner** [fatedier/frp#3646]
### Bug Description

full config file was renamed in #3608 
https://github.com/fatedier/frp/blob/5e70d5bee0e99eeaccd555cc24bd76a3d5bfe045/README.md?plain=1#L463
https://github.com/fatedier/frp/blob/5e70d5bee0e99eeaccd555cc24bd76a3d5bfe045/README.md?plain=1#L465

### frpc Version

dev

### frps Version

dev

### System Architecture

ignore

### Configurations

ignore

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Fixed
