### ISSUE TITLE
debian系统运行frpc提示./frpc 无法执行二进制文件，二进制文件格式错误

### ISSUE THREAD

**Issue by DAMYSDS** [fatedier/frp#3649]
### Bug Description

Debian系统，amd64位，运行frpc提示./frpc 无法执行二进制文件，二进制文件格式错误
![mmexport1696879287376](https://github.com/fatedier/frp/assets/40637253/5230ddd7-3888-4bdd-b8ed-d54c20d9d07d)

### frpc Version

0.51.3

### frps Version

0.51.3

### System Architecture

linux/amd64

### Configurations

配置正常

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
这貌似不是issues，尝试修改frpc文件权限为0755

**Comment by Yang2635** [comment]
frpc没有可执行权限，需赋予执行权：chmod +x frpc
