### ISSUE TITLE
/api/proxy/tcp `{"proxies":[]}`

### ISSUE THREAD

**Issue by xqzr** [fatedier/frp#3658]
### Bug Description

`/api/proxy/*` 都没有数据

### frpc Version

0.52.0

### frps Version

0.52.0

### System Architecture

linux/amd64

### Configurations

```json
{
 "webServer": {
  "addr": "::1",
  "port": 7501,
  "user": "●●●●",
  "password": "●●●●"
 }
}
```

### Logs

```
2023/10/11 00:56:10 [I] [dashboard_api.go:192] Http request: [/api/proxy/tcp]
2023/10/11 00:56:10 [W] [dashboard_api.go:214] unmarshal proxy [●●●●] conf info error: unknown plugin type:
2023/10/11 00:56:10 [I] [dashboard_api.go:186] Http response [/api/proxy/tcp]: code [200]
```

### Steps to reproduce

1. `curl -s ●●●●:●●●●@[::1]:7501/api/serverinfo | jq .proxy_type_count`
```json
{
  "https": 3,
  "tcp": 12,
  "udp": 3,
  "xtcp": 8
}
```
2. `curl -s ●●●●:●●●●@[::1]:7501/api/proxy/tcp | jq .`
```json
{
  "proxies": []
}
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by sfdex** [comment]
I have the same issue as you
