### ISSUE TITLE
v0.52.0中在ubuntu8中cpu架构为x86_64请问使用哪一个文件

### ISSUE THREAD

**Issue by juchuangsoft** [fatedier/frp#3661]
### Describe the feature request

在v0.52.0版本中，没有linux_386.tar.gz这个版本支持，请问在最新版本中，我应该使用那个版本替代

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
不再提供 32 位的预编译包，你可以下载源码后自行编译。

**Comment by juchuangsoft** [comment]
是不是使用以往版本中支持x86_64的Makefile.cross-compiles 文件进行编译？

**Comment by juchuangsoft** [comment]
> 不再提供32位的预编译包，您可以下载源码后自行编译。
是不是使用以往版本中支持x86_64的Makefile.cross-compiles文件进行编译？

**Comment by juchuangsoft** [comment]
是不是使用以往版本中支持x86_64的Makefile.cross-compiles文件进行编译？
