### ISSUE TITLE
v0.52.0  服务端 frps dashboard 不能显示Proxies 数据

### ISSUE THREAD

**Issue by gexiaopeng** [fatedier/frp#3666]
### Bug Description

v0.52.0 版本 服务端 frps dashboard 不能显示Proxies 数据 （以前版本是正常的）

![1](https://github.com/fatedier/frp/assets/7857056/ae38cfcd-684b-4bf3-9bab-db8ed4dd8040)
![2](https://github.com/fatedier/frp/assets/7857056/b73b5606-765f-4920-9e7e-5b16aa6221e5)
![3](https://github.com/fatedier/frp/assets/7857056/da9a05e5-036f-4b4a-bc19-463f2f1a74a9)

### frpc Version

v0.52.0

### frps Version

v0.52.0

### System Architecture

linux/amd64

### Configurations

bindPort = xxx
vhostHTTPPort = xxx

transport.maxPoolCount = 10

webServer.addr = "0.0.0.0"
webServer.port = xxx
webServer.user = "xxx"
webServer.password = "xxx"

log.to = "/home/logs/frps/frps.log"

log.level = "info"
log.maxDays = 15

auth.method = "token"
auth.token = "xxx"

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
#3658

**Comment by fatedier** [comment]
下个版本会恢复。
