### ISSUE TITLE
[Feature Request] frp 安全方面的一个问题

### ISSUE THREAD

**Issue by soonxf** [fatedier/frp#3674]
### Describe the feature request

frp 服务端 是否能解析 frpc客户端 传来的流量,这里的解析指的是,将这些流量解析成明文,主要是针对市面上一些免费的 frpc 代理产生了安全性的顾虑

### Describe alternatives you've considered

不使用免费的 frpc

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by soonxf** [comment]
主要担心的是使用 如 樱花Frp 会不会造成信息泄露的风险,或者有没有什么方法避免这个风险

**Comment by xqzr** [comment]
```json
{
 "type": "https"
}
```

**Comment by penndu** [comment]
`transport.useEncryption = true`

**Comment by xqzr** [comment]
> `transport.useEncryption = true`

这将在 frps 解密

**Comment by fatedier** [comment]
一般来说，两端都是你自己的服务，中间应用层自己把加密做好，否则在互联网上传输的流量，都没法保证。

**Comment by KennanChan** [comment]
FRPS服务器上部署一套VPN（我用的Softether VPN），网关对外只开放FPRS的注册端口，真正的映射端口只有连上VPN进入内网才能访问

**Comment by guation** [comment]
你从ftpc进的流量是什么样的从frps出的流量就是什么样的 反过来也是 这是端口映射服务特性决定的 你只能自行将输入的流量加密以达到避免明文传输的目的
