### ISSUE TITLE
 token in login doesn't match token from configuration

### ISSUE THREAD

**Issue by Shane-Meng** [fatedier/frp#3675]
### Bug Description

我的服务器是 centos7，客户机是 ubuntu22.04，分别使用 snowdreamtech/frpc 和 snowdreamtech/frps 这两个镜像创建容器来实现内网穿透。之前一直是好好的，今天容器自动更新后，发现是新版本启用了 toml 格式的配置，造成客户端容器无法启动了，我花了一点时间按照文档修改了我的配置文件，如果包含
```
auth.method = "token"
auth.token = "foobar2020"
```
客户端就会报如下错误，起不来
[I] [root.go:154] frpc service for config file [/etc/frp/frpc.toml] stopped
2023/10/14 07:27:16 [I] [root.go:139] start frpc service for config file [/etc/frp/frpc.toml]
2023/10/14 07:27:16 [E] [service.go:291] token in login doesn't match token from configuration
2023/10/14 07:27:16 [W] [service.go:131] login to server failed: token in login doesn't match token from configuration

删掉就好了。

不知是什么问题？哪位兄台给指教一下。

两个配置文件我都用 cat -A  查看过，没有古怪字符。

### frpc Version

0.52.1

### frps Version

0.52.1

### System Architecture

linux/amd64

### Configurations

Server
```
bindAddr = "0.0.0.0"
bind_port = 7000
kcpBindPort = 7000
auth.method = "token"
auth.token = "foobar2020" 
```

Client
```
serverAddr = "a.b.c.d"
serverPort = 7000
auth.method = "token"
auth.token = "foobar2020"
webServer.addr = "0.0.0.0"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "foobar"


[[proxies]]
name = "rsshub"
type = "tcp"
localIP = "192.168.199.10"
localPort = 1200
remotePort = 9001

``` 

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by duandaxei** [comment]
bind_port => bindPort

**Comment by Shane-Meng** [comment]
对，现在工作了，谢谢

**Comment by whd9732** [comment]
一样碰到了 楼主是怎么解决的
