### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by ershuaili** [fatedier/frp#3679]
### Describe the feature request

locations配置https无效，目前是只支持http吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by penndu** [comment]
https://dusays.com/616/#atk-comment-32267

**Comment by xqzr** [comment]
frp 不解密 https
