### ISSUE TITLE
最新版本服务器端部署完毕，客户端出错提示：Parse conf error: proxy [] remote_port not found

### ISSUE THREAD

**Issue by xiaxiaofu** [fatedier/frp#368]
问题描述：服务器可以访问控制面板，客户端运行出错Parse conf error: proxy [] remote_port not found
部署信息如下：
**服务端**：
    软件版本：frp_0.11.0_linux_386
    主机：谷歌vps，Ubuntu14.04LTS
frps.ini信息：
 [common]
bind_addr = 0.0.0.0
bind_port = 7000
vhost_http_port = 8080
vhost_https_port = 8443
dashboard_port = 7500
dashboard_user = XXXX	
dashboard_pwd = XXXX
log_file = ./frps.log
log_level = info
log_max_days = 3
privilege_mode = true
privilege_token = XXXX
privilege_allow_ports = 5000-60000
max_pool_count = 50
authentication_timeout = 0
subdomain_host = XXXX.tech

**客户端**：
    软件版本：frp_0.11.0_darwin_amd64.tar
    主机：MacBook Pro2015，OS X EI Capitan 10.11.6
frpc.ini:
server_addr = xx.xx.xx.xx
server_port = 7000
privilege_token = XXXX
host_http_port = 8080
host_https_port = 8443
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000
服务端运行xx.xx.xx.xx:7500可以进入控制面板，但是客户端运行./frpc -c ./frpc.ini出错
**错误提示**：Parse conf error: proxy [] remote_port not found

求大神解答，谷歌云主机的防火墙规则已经开启tcp:5000-60000端口，包括6000,7000,7500,8080,8443端口.

**Comment by wxlg1117** [comment]
frpc.ini里面删除掉这俩行试试
host_http_port = 8080
host_https_port = 8443

**Comment by fatedier** [comment]
https://github.com/fatedier/frp#access-your-computer-in-lan-by-ssh

**Comment by xiaxiaofu** [comment]
那个提示是客户端和服务器端没有建立起链接，不是ssh登陆问题

在 2017-06-16 18:23:51，"fatedier" <notifications@github.com> 写道：


Closed #368.

**Comment by xiaxiaofu** [comment]
已经删除http与https的两行，依旧无效

**Comment by fatedier** [comment]
https://github.com/fatedier/frp#access-your-computer-in-lan-by-ssh
