### ISSUE TITLE
 ssh端口不能按照指定的端口设置,而是自动生成

### ISSUE THREAD

**Issue by itgoyo** [fatedier/frp#3680]
### Bug Description

 ssh端口不能按照指定的端口设置,而是自动生成

### frpc Version

0.38.0

### frps Version

0.38.0

### System Architecture

linux/amd64

### Configurations

在三台客户端机器都发现了相同的问题，每个ssh的端口和我设置的都不一样，感觉是随机生成的

```
[um480xt-ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote-port = 40000
[um480xt-portainer]
type = tcp
local_ip = 127.0.0.1
local_port = 9000
remote_port = 40002
[um480xt-bililive]
type = tcp
local_ip = 127.0.0.1
local_port = 12345
remote_port = 40003
[um480xt-brec]
type = tcp
local_ip = 127.0.0.1
local_port = 2333
remote_port = 40004
```

<img width="1489" alt="image" src="https://github.com/fatedier/frp/assets/23348551/94caa91c-8ab2-44f2-ba3e-b2e915b06f4e">

### Logs

.

### Steps to reproduce

.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by superzjg** [comment]
很显然，[um480xt-ssh]的参数写错了，当然不会生效

**Comment by itgoyo** [comment]
@superzjg 感谢，你这么一说我才细心的去看了一下参数，确实错了
