### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by aapelismith** [fatedier/frp#3684]
### Describe the feature request

建议考虑为 frp 项目添加 [DependaBot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) 来确保依赖能够及时被更新. 

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
目前并不需要及时更新依赖包，徒增维护成本。
