### ISSUE TITLE
Find unknown ips in my frps.log

### ISSUE THREAD

**Issue by GraceZhuuu** [fatedier/frp#3685]
### Bug Description

I am a newbie. I just tried to set up the service in the morning. After the test was normal, I went to take a nap. After my nap, I checked the frps log and found the login record of the unknown IP. I didn't know what was going on, but I was worried, so I stopped the service. My configuration is the simplest configuration, and many unused plug-ins are commented out. 
![Home_image_2](https://github.com/fatedier/frp/assets/124070462/885cc9c6-9d19-4379-a371-765b6812ec8a)
the masked one are my own ip, and the others are unknown. Please give some advise to me, 3Q!

我是新手。我只是嘗試在早上設定服務。檢查正常後我就去睡覺了。午睡後，我查看了frps日誌，發現了未知IP的登入記錄。我不知道發生了什麼事，但我擔心，所以我停止了服務。我的配置是最簡單的配置，很多沒用的插件都被註解掉了。
被屏蔽的就是我自己的ip，其他的都不知道。請給我一些建議，3Q！

### frpc Version

0.52.1

### frps Version

0.52.1

### System Architecture

linux/amd64

### Configurations

```
bindAddr = "0.0.0.0"
bindPort = 7002
kcpBindPort = 7002
transport.maxPoolCount = 5
```
```
[[proxies]]
# 'ssh' is the unique proxy name
# If global user is not empty, it will be changed to {user}.{proxy} such as 'your_name.ssh'
name = "ssh"
type = "tcp"
localIP = "172.20.109.133"
localPort = 22
# Limit bandwidth for this proxy, unit is KB and MB
transport.bandwidthLimit = "1MB"
# Where to limit bandwidth, can be 'client' or 'server', default is 'client'
transport.bandwidthLimitMode = "client"
# If true, traffic of this proxy will be encrypted, default is false
transport.useEncryption = false
# If true, traffic will be compressed
transport.useCompression = false
# Remote port listen by frps
remotePort = 6001
# frps will load balancing connections for proxies in same group
loadBalancer.group = "test_group"
# group should have same group key
loadBalancer.groupKey = "123456"
# Enable health check for the backend service, it supports 'tcp' and 'http' now.
# frpc will connect local service's port to detect it's healthy status
healthCheck.type = "tcp"
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
可能会攻击，建议不要继续使用，或者通过防火墙限制。
