### ISSUE TITLE
[Feature Request] 文档链接打开404

### ISSUE THREAD

**Issue by Garbo1229** [fatedier/frp#3688]
### Describe the feature request

是有新的文档链接 还是在迁移 https://gofrp.org/docs

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://gofrp.org/
