### ISSUE TITLE
frp代理NAS：该网页无法正常运作

### ISSUE THREAD

**Issue by mesakas** [fatedier/frp#3690]
### Bug Description

frp代理NAS：该网页无法正常运作，报502

### frpc Version

0.51.3

### frps Version

0.51.3

### System Architecture

ubuntu 20.04

### Configurations

frpc.ini:

```
[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 7000
token = xxxxxx

[ssh_nas]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 60022



[DMS]
type = tcp
local_ip = 127.0.0.1
local_port = 5000
remote_port = 55000
```

我代理了我的Nas，但是我用浏览器来访问Nas报502错误，请问是因为什么原因？

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by wuai1024** [comment]
`local_ip` 错了

**Comment by flash91120** [comment]
同问
