### ISSUE TITLE
frpc.toml服务启动了，但是监听端口看不到

### ISSUE THREAD

**Issue by gax888** [fatedier/frp#3692]
### Bug Description

● frpc.service - Frpc Client
   Loaded: loaded (/etc/systemd/system/frpc.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since 三 2023-10-18 10:41:25 CST; 1min 35s ago
  Process: 9027 ExecStart=/usr/bin/frpc -c /tools/frpc/frpc.toml (code=exited, status=0/SUCCESS)
 Main PID: 9027 (code=exited, status=0/SUCCESS)

### frpc Version

0.52.1

### frps Version

0.52.1

### System Architecture

amd64

### Configurations

frpc.toml配置文件
user = "X"
serverAddr = "a.b.c.d"
serverPort = 7000

# STUN server to help penetrate NAT hole.
# natHoleStunServer = "stun.easyvoip.com:3478"

loginFailExit = true
log.to = "./tools/frpc/frpc.log"
log.level = "info"
log.maxDays = 3
log.disablePrintColor = false

auth.method = "token"
auth.token = "123"
webServer.pprofEnable = false

transport.poolCount = 5
transport.protocol = "kcp"
transport.connectServerLocalIP = "0.0.0.0"
transport.tls.enable = true

udpPacketSize = 1500

### Logs

2023/10/18 10:41:25 [I] [root.go:139] start frpc service for config file [/tools/frpc/frpc.toml]
2023/10/18 10:41:25 [E] [service.go:291] send Login request to plugin error

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by asdf5329** [comment]
toml和INI不一样，服务器地址是域名的话就这样，INI的服务器地址是域名就不报错，这个报，
