### ISSUE TITLE
Encryption and compression

### ISSUE THREAD

**Issue by WuMe-sicx** [fatedier/frp#3693]
### Bug Description

"I have enabled encryption and compression, but the server displays a closed status."

### frpc Version

0.52.1

### frps Version

0.52.1

### System Architecture

linux/amd64

### Configurations

[[proxies]]
name = "ssh"
type = "tcp"
localPort = 22
remotePort = 6000
transport.useEncryption = true
transport.useCompression = true

### Logs

![IE 5 ~BQQ{WZDY$6OTIDC69](https://github.com/fatedier/frp/assets/80626027/14a60ae9-3765-4705-bc4a-7a05c92e4f11)

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
https://github.com/fatedier/frp/pull/3682

It has been fixed but has not been updated to the release yet.
