### ISSUE TITLE
客户端连接后自动断开，无法登录

### ISSUE THREAD

**Issue by techluo** [fatedier/frp#3696]
### Bug Description

客户端连接后自动断开，无法登录

### frpc Version

0.43.0

### frps Version

0.37.1

### System Architecture

Linux 64位

### Configurations

frpc配置
<img width="277" alt="企业微信截图_16976968902332" src="https://github.com/fatedier/frp/assets/148426727/72bcda38-8056-4064-9751-9d3eb96d101a">[common]
frps配置
bind_port = 7000
#tcp_mux = false

# frp管理后台端口，请按自己需求更改
dashboard_port = 7500
# frp管理后台用户名和密码，请改成自己的
dashboard_user = admin
dashboard_pwd = admin
enable_prometheus = true

[ssh]
bandwidth_limit = 1024KB

log_file = /home/ubuntu/frps/frp.log
#log_level = trace  #debug info
log_max_days = 7

### Logs

frpc
2023/10/19 14:29:45 [I] [service.go:201] [75aabaaadeba91f7] try to reconnect to server...
2023/10/19 14:29:45 [I] [service.go:349] [75aabaaadeba91f7] login to server success, get run id [75aabaaadeba91f7], server udp port [0]
2023/10/19 14:29:45 [I] [proxy_manager.go:144] [75aabaaadeba91f7] proxy added: [7991]
2023/10/19 14:29:45 [T] [proxy_wrapper.go:171] [75aabaaadeba91f7] [7991] change status from [new] to [wait start]
2023/10/19 14:29:45 [E] [control.go:159] [75aabaaadeba91f7] work connection closed before response StartWorkConn message: EOF
2023/10/19 14:29:45 [D] [control.go:292] [75aabaaadeba91f7] read from control connection EOF
2023/10/19 14:29:45 [I] [control.go:316] [75aabaaadeba91f7] control writer is closing
2023/10/19 14:29:45 [I] [visitor_manager.go:60] [75aabaaadeba91f7] gracefully shutdown visitor manager

2023/10/19 14:30:01 [I] [service.go:185] [75aabaaadeba91f7] wait 16s to reconnect
2023/10/19 14:30:01 [I] [service.go:201] [75aabaaadeba91f7] try to reconnect to server...
2023/10/19 14:30:01 [I] [service.go:349] [75aabaaadeba91f7] login to server success, get run id [75aabaaadeba91f7], server udp port [0]
2023/10/19 14:30:01 [I] [proxy_manager.go:144] [75aabaaadeba91f7] proxy added: [7991]
2023/10/19 14:30:01 [T] [proxy_wrapper.go:171] [75aabaaadeba91f7] [7991] change status from [new] to [wait start]
2023/10/19 14:30:11 [E] [control.go:159] [75aabaaadeba91f7] work connection closed before response StartWorkConn message: EOF

frps

![Uploading image.png…]()

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
网络问题，可以尝试 QUIC
https://github.com/fatedier/frp/blob/5760c1cf92b87a9d734e6c31c626f9a4d282fde0/conf/frps_full_example.toml#L15
https://github.com/fatedier/frp/blob/5760c1cf92b87a9d734e6c31c626f9a4d282fde0/conf/frpc_full_example.toml#L82
另外，建议两端版本相同
