### ISSUE TITLE
 login to server failed: EOF

### ISSUE THREAD

**Issue by jiang0608** [fatedier/frp#3697]
### Bug Description

使用NAT虚拟机搭建FRPS，第一次搭建完成能正常访问，后续因其他原因，重新启用一台虚拟机搭建FRPS（同一IP地址，不同端口），客户端无法连接服务端，提示： login to server failed: EOF；删除客户端文件重新下载配置出现同样问题；改回第一次搭建的端口又能正常连接服务端

### frpc Version

0.52.1

### frps Version

0.52.1

### System Architecture

linux/amd64

### Configurations

user = "a"
serverAddr = "域名"
serverPort = xxxx
loginFailExit = true
log.to = "./frpc.log"

log.level = "info"
log.maxDays = 3
log.disablePrintColor = false
auth.method = "token"
auth.token = "*"
transport.protocol = "tcp"
transport.connectServerLocalIP = "0.0.0.0"
transport.tls.enable = true
udpPacketSize = 1500

### Logs

##使用端口b(使用新虚拟机)
2023/10/19 14:39:37 [I] [root.go:139] start frpc service for config file [frpc.toml]
2023/10/19 14:39:38 [W] [service.go:131] login to server failed: EOF
2023/10/19 14:39:38 [I] [root.go:154] frpc service for config file [frpc.toml] stopped
2023/10/19 14:40:11 [I] [root.go:139] start frpc service for config file [frpc.toml]
##使用端口a(使用旧虚拟机)
2023/10/19 14:40:11 [I] [service.go:299] [xxxxx] login to server success, get run id [xxxxxxxx]
2023/10/19 14:40:11 [I] [visitor_manager.go:118] [xxxxx] start visitor success
2023/10/19 14:40:11 [I] [visitor_manager.go:162] [xxxxx] visitor added: [user.proxy]

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by zlm324** [comment]
排查一下frps所在虚拟机的防火墙设置？

**Comment by jiang0608** [comment]
NAT主机问题
