### ISSUE TITLE
可以把UDP也加进去吗

### ISSUE THREAD

**Issue by 694982827** [fatedier/frp#37]
是否可以将UDP协议也加进去？

**Comment by fatedier** [comment]
这个可以有，不过可能与原来的设计不通用，需要改动的地方比较多。

**Comment by istrwei** [comment]
udp稳定性不太好吧，容易掉包，除非tcp不能用了才用udp

**Comment by bhzhu203** [comment]
这个软件和dog-tunnel 有啥区别么

**Comment by fatedier** [comment]
@bhzhu203 这个项目的创建主要是因为我在使用 ngrok 的时候遇到的一些问题， 作者不再开源以及维护了，所以目前大部分的功能上是和 ngrok 类似的。

**Comment by tiane12** [comment]
@istrwei 不是的啊，比如内网的摄像头映射到公网上，就可以用UDP协议，没必要用TCP的。

**Comment by wxyzh** [comment]
@fatedier @bhzhu203 dog-tunnel有tcp和udp两种连接方式，udp是两台内网机器直连，udp是用的kcp协议；tcp是通过服务器中转。

**Comment by iseeyou** [comment]
希望早日实现UDP。

**Comment by yi-ge** [comment]
虽然任重道远，但是很有必要。

**Comment by fcying** [comment]
在这里看到dog-tunnel, 去试了下, 直连的速度好快...虽然功能少了点

**Comment by kkstun** [comment]
等着udp呢
