### ISSUE TITLE
p2p 必须dmz才行吗？ upnp是否支持？

### ISSUE THREAD

**Issue by wuai1024** [fatedier/frp#3703]
### Describe the feature request

如题，支持upnp吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by wuai1024** [comment]
先决条件是这样的， 因为一条外网线路只能设置一个 `dmz`

但是如果是支持 `upnp` 的话，就不需要独占我这个 `dmz`了。我就可以做其他事。

**Comment by wuai1024** [comment]
？？？

**Comment by JsonSong89** [comment]
dmz upnp都是你自己本地路由器及内部网络环境的设置,和frp没关系
有的路由器应该是支持upnp端口转发的

**Comment by wuai1024** [comment]
upnp需要客户端发起

**Comment by lee-cq** [comment]
建议考虑Upnp, 因为在绝大多数情况下我们在访问侧没有权限设置DMZ

**Comment by wuai1024** [comment]
是的，upnp比较有用。

**Comment by wuai1024** [comment]
这个有计划纳入吗？
