### ISSUE TITLE
[Feature Request] support multiple natHoleStunServer 

### ISSUE THREAD

**Issue by aa51513** [fatedier/frp#3705]
### Describe the feature request

support multiple natHoleStunServer address
支持配置多个natHoleStunServer地址

### Describe alternatives you've considered

Sometimes natHoleStunServer will fail to connect. 
有些时候natHoleStunServer 会失效

Supporting multiple natHoleStunServer addresses can improve reliability.
支持配置多个natHoleStunServer地址可以提高可靠性

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by hentailjb** [comment]
支持
