### ISSUE TITLE
frp的配置文件可以加密吗？

### ISSUE THREAD

**Issue by Lingchen218** [fatedier/frp#3706]
### Describe the feature request

希望frp的配置文件可以加密

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
目前不支持，以后的架构里可能会考虑支持多种加载配置的方式。
