### ISSUE TITLE
Server Dashboard connection refused

### ISSUE THREAD

**Issue by lilongsky** [fatedier/frp#3709]
### Bug Description

after setting up the server dashboard, follow [Web 界面](https://gofrp.org/zh-cn/docs/features/common/ui/). 
The chrome shows ERR_CONNECTION_REFUSED

It could be fixed by adding  `webServer.addr = "0.0.0.0"`  to Configurations

### frpc Version

0.52.1

### frps Version

0.52.1

### System Architecture

linux/amd64

### Configurations

bindPort = 7000
subdomainHost = "*"
vhostHTTPPort = 80
vhostHTTPSPort = 443

webServer.port = 7500
webServer.user = "*"
webServer.password = "*"

webServer.tls.certFile = "*"
webServer.tls.keyFile = "*"

### Logs

no log related to it

### Steps to reproduce

1. Setting `frps.toml` follow https://gofrp.org/zh-cn/docs/features/common/ui/
2. Chrome access ip:7500 or domain:7500
3. get error "ERR_CONNECTION_REFUSED"

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
This is expected. For security reasons, the default listening address for the web server is `127.0.0.1`.
