### ISSUE TITLE
[Feature Request] How to configure SNI in frps.toml?

### ISSUE THREAD

**Issue by SidneyLann** [fatedier/frp#3710]
### Describe the feature request

Every subdomains have their own certification files, how to confige them? ERR_SSL_UNRECOGNIZED_NAME_ALERT alert if  configue only one cert file.

### Describe alternatives you've considered
transport.tls.certFile.www = "www.pc.com_bundle.crt"
transport.tls.keyFile.www = "www.pc.com.key"

transport.tls.certFile.sz = "sz.pc.com_bundle.crt"
transport.tls.keyFile.sz = "sz.pc.com.key"

transport.tls.certFile.sh = "sh.pc.com_bundle.crt"
transport.tls.keyFile.sh = "sh.pc.com.key"

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [x] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
`transport.tls` in frps.toml is used for connections from frpc, not user.

Your current requirement is not supported. I suggest using a proxy like nginx.
