### ISSUE TITLE
0520以后如何对范围端口进行映射？

### ISSUE THREAD

**Issue by ccraise** [fatedier/frp#3711]
### Describe the feature request

以前可以用range来映射多个端口，0520以后该如何配置？
[range:someserver]
type = tcp
local_ip = XXX.XXX.1.XXX
local_port = 1234,4444,5556,8081-8083
remote_port = 1234,4445,6667,8081-8083

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
0.52.0 的更新项有这样一个描述，是否相关？
No longer support range ports mapping in TOML/YAML/JSON.

**Comment by fatedier** [comment]
INI 仍然可用，但是不再推荐，至少 v0 版本中会一直保留。
