### ISSUE TITLE
[Feature Request] 端口复用- > 依据不同路径反向代理到不同web，gzip的index.html 内部js css path能自动修改stripPrefix？

### ISSUE THREAD

**Issue by gowy222** [fatedier/frp#3712]
### Describe the feature request

s端 通过 path 反向到 c端:
192.168.0.2:8888/app1 -> 10.0.0.2:81 http web
192.168.0.2:8888/app2 -> 10.0.0.2:82 http web
192.168.0.2:8888/app3 -> 10.0.0.2:83 http web

这个能实现？
关键经典问题 gzip的index.html 内部的 js css 静态 path怎么自动解压gzip替换 stripPrefix 再gzip on

**Comment by fatedier** [comment]
没太看懂，但是复杂的 web/HTTP 的需求，建议结合 nginx 之类的代理使用，功能更全面。
