### ISSUE TITLE
frps 面板 默认无法连接。

### ISSUE THREAD

**Issue by superzjg** [fatedier/frp#3715]
### Bug Description

以前面板监听webServer.addr默认是0.0.0.0，现在默认是webServer.addr = "127.0.0.1"，导致必须设置这个参数改回来才能连接，留空连接不上。

### frpc Version

0.52.1

### frps Version

0.52.1

### System Architecture

linux/arm64

### Configurations

webServer.addr = ""

### Logs

2023/10/23 10:56:55 [I] [service.go:200] frps tcp listen on 0.0.0.0:5340
2023/10/23 10:56:55 [I] [service.go:226] frps quic listen on quic 0.0.0.0:5340
2023/10/23 10:56:55 [I] [service.go:261] http service listen on 0.0.0.0:5341
2023/10/23 10:56:55 [I] [service.go:312] Dashboard listen on 127.0.0.1:5342

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/issues/3709#issuecomment-1774338490
