### ISSUE TITLE
What‘s the problem

### ISSUE THREAD

**Issue by JoshuaShaw** [fatedier/frp#3716]
### Bug Description

<img width="598" alt="微信图片_20231023104326" src="https://github.com/fatedier/frp/assets/6315304/facf0d22-84d1-440a-910e-64bfdb06ec99">

### frpc Version

0.52.1 & 0.52.0

### frps Version

0.52.1 & 0.52.0

### System Architecture

MAC & WIndows

### Configurations

Just Download

### Logs

Virus

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by liaobadadi** [comment]
我也是同样的问题，需要防火墙设置下

**Comment by XYZliang** [comment]
这有什么好 problem 的，微软defender什么成分不知道？

**Comment by potoo0** [comment]
tar 相关的压缩文件，微软都有可能错检，不会改 windows 扫描策略的话就下载 zip，或者在子系统或者用 wget/curl 等命令下载

**Comment by xqzr** [comment]
#2095

**Comment by Meta39** [comment]
在防火墙排除文件扫描即可！
![image](https://github.com/fatedier/frp/assets/57950116/b87b7a3a-a885-4af4-af43-f5a20ee14d16)
![image](https://github.com/fatedier/frp/assets/57950116/b4ccbd6e-4360-4459-802d-298f4d82da8e)
![image](https://github.com/fatedier/frp/assets/57950116/2c2ad50c-6954-4d83-ab6f-66d52cb8741a)
![image](https://github.com/fatedier/frp/assets/57950116/54c2c9c9-26be-4817-b2c6-a4f5a84b6008)

**Comment by JoshuaShaw** [comment]
> 这有什么好 problem 的，微软defender什么成分不知道？

不知道，愿闻其详！谢谢。

**Comment by JoshuaShaw** [comment]
> 我也是同样的问题，需要防火墙设置下

设置谁都会。关键是要知道为什么，要是万一真的病毒，全是生产环境。不敢造次！

**Comment by fatedier** [comment]
真的是病毒，千万不要在生产环境用。

**Comment by xqzr** [comment]
> 在防火墙排除文件扫描即可！ ![image](https://private-user-images.githubusercontent.com/57950116/278291354-b87b7a3a-a885-4af4-af43-f5a20ee14d16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2ODA2NDgsIm5iZiI6MTcwMzY4MDM0OCwicGF0aCI6Ii81Nzk1MDExNi8yNzgyOTEzNTQtYjg3YjdhM2EtYTg4NS00YWY0LWFmNDMtZjVhMjBlZTE0ZDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDEyMzIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYTU1Mjc4YTk4NGM3NjdkM2YwMmM4MzZmZGZkZTk1ZGQ3MmRjODdiZjY4MDEwYzkzYzdkNGQyMWUwN2M0MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fY9FGDF2SgXcA2XOl9SbMlKZgYDYsxvGmBVDN_r6cBg) ![image](https://private-user-images.githubusercontent.com/57950116/278291462-b4ccbd6e-4360-4459-802d-298f4d82da8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2ODA2NDgsIm5iZiI6MTcwMzY4MDM0OCwicGF0aCI6Ii81Nzk1MDExNi8yNzgyOTE0NjItYjRjY2JkNmUtNDM2MC00NDU5LTgwMmQtMjk4ZjRkODJkYThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDEyMzIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5Mjc3YzgxMWIzNjJiZThlMTcyMzdhMjJjYWJjZTQ3ZDcyZTAxZWIxMTA5OWMxZTI2YjEzNjViMTcwNThmODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CY0msNBVg27o_hu94Pcmm3bAcJblRnCDmAg9XRIWd6Q) ![image](https://private-user-images.githubusercontent.com/57950116/278291594-2c2ad50c-6954-4d83-ab6f-66d52cb8741a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2ODA2NDgsIm5iZiI6MTcwMzY4MDM0OCwicGF0aCI6Ii81Nzk1MDExNi8yNzgyOTE1OTQtMmMyYWQ1MGMtNjk1NC00ZDgzLWFiNmYtNjZkNTJjYjg3NDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDEyMzIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNmIzOTgzMzBhYmM2OWNlZWU2ZDM4ZGFhZmQ2ZjRjNzYyZDNjMDMyMjE3MDVjM2YzN2NkYWNkY2ZjMzc5ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3qVGU9NAVqmHbd1Cycc5G6s96Gr4esSnB_dCaDd8MZU) ![image](https://private-user-images.githubusercontent.com/57950116/278291719-54c2c9c9-26be-4817-b2c6-a4f5a84b6008.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2ODA2NDgsIm5iZiI6MTcwMzY4MDM0OCwicGF0aCI6Ii81Nzk1MDExNi8yNzgyOTE3MTktNTRjMmM5YzktMjZiZS00ODE3LWIyYzYtYTRmNWE4NGI2MDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDEyMzIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MjViNTk4MDRlZTJiMTI5YzlmN2YzOTJjNDYzMGNjZmVlOWE1MTdlMzg2ZjY4MDZhMDNmMjZjZGQ5MGUzN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Q1b78-aQRg5LV18gFrFMNrLvKHJeV5TtFALCHR0Efw)

排除单个文件就足够，而不是整个文件夹

**Comment by superzjg** [comment]
> > 我也是同样的问题，需要防火墙设置下
> 
> 设置谁都会。关键是要知道为什么，要是万一真的病毒，全是生产环境。不敢造次！

源码是公开的，你自己可以分析，下载和编译。
你觉得若是病毒，别人发现不了？
