### ISSUE TITLE
0.52.2的frpc认证始终无法成功

### ISSUE THREAD

**Issue by JsonSong89** [fatedier/frp#3718]
### Bug Description

curl -u admin:admin http://127.0.0.1:9002/static/

0.52.2一直失败
换成 0.51.3之后,配置无修改,可以认证成功

### frpc Version

0.52.2

### frps Version

不涉及服务端

### System Architecture

linux/armv7

### Configurations

admin_addr = 127.0.0.1
admin_port = 9002
admin_user = admin
admin_pwd = admin

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fsnhljz** [comment]
0.52.2的配置改了呀，变成frpc.toml格式了。
