### ISSUE TITLE
0.52.2 登陆失败立刻退出

### ISSUE THREAD

**Issue by wzm2256** [fatedier/frp#3720]
### Bug Description

这个问题多次被提到过 https://github.com/fatedier/frp/issues/3556
在0.51 版本中加入 login_fail_exit = false 可以解决，但0.52.2 版本中同样的策略无效。在full_configuration_file 中并没有这个选项。也没有找到任何说明。

PS: 能否直接把尝试重连设定成默认？在什么情况下不需要这个设定？

### frpc Version

0.52.2

### frps Version

0.52.2

### System Architecture

linux/amd64

### Configurations

[[common]]
login_fail_exit = false

也试过不要这个[[common]]
login_fail_exit = false

### Logs

2023/10/24 01:18:52 [I] [root.go:220] start frpc service for config file [./frpc.ini]
2023/10/24 01:18:52 [W] [service.go:133] login to server failed: dial tcp 127.0.0.1:7000: connect: connection refused
2023/10/24 01:18:52 [I] [root.go:236] frpc service for config file [./frpc.ini] stopped

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
试试用新 toml 配置文件试一下，要重新写配置，参数名称都一样了（ loginFailExit = false ）。
https://github.com/fatedier/frp/blob/dev/conf/frpc.toml

**Comment by penndu** [comment]
https://dusays.com/636/

**Comment by wzm2256** [comment]
> 试试用新 toml 配置文件试一下，要重新写配置，参数名称大都不一样了（ loginFailExit = false ）。 https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml 还要注意值的格式，字符串用引号，数组用方括号，布尔和整数不需要符号。
> 
> ps：我感觉不建议改默认值，连不上退出应该是正确的策略，这样更安全。

感谢回复  参数名称居然也改了，完全不懂意义在哪。 

新参数是 loginFailExit 不再是 login_fail_exit
