### ISSUE TITLE
toml配置问题

### ISSUE THREAD

**Issue by fengyuclub** [fatedier/frp#3724]
### Bug Description

1. 明明指定了端口17000，但启动却显示7000
frps: the configuration file frps.toml syntax is ok
root@ubuntu:~/frps# ./frps -c frps.toml
WARNING: ini format is deprecated and the support will be removed in the future, please use yaml/json/toml format instead!
2023/10/25 15:04:15 [I] [root.go:102] frps uses config file: frps.toml
2023/10/25 15:04:15 [I] [service.go:200] frps tcp listen on **0.0.0.0:**7000**
2023/10/25 15:04:15 [I] [root.go:111] frps started successfully
2. dashboard为啥启动不起来，哪里错了？

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

frps.toml
-----------------
bindPort = 17000
quicBindPort = 17000
auth.method = "token"
auth.token = "123456"
tls_trusted_ca_file = /root/frps/ca.crt
#new dashborad
webServer.port = 17500
webServer.user = "admin"
webServer.password = "123456"
webServer.tls.certFile = "/root/frps/xxx.cer"
webServer.tls.keyFile = "/root/frps/xxx.key"
webServer.assetsDir = "./static"
#log
log.to = "./frps_new.log"
log.level = "debug"
log.maxDays = 3
-----------------

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
不要 新旧格式配置混用，可能解析出错 （tls_trusted_ca_file）。

**Comment by fengyuclub** [comment]
> 不要 新旧格式配置混用，可能解析出错 （tls_trusted_ca_file）。

注释掉一样的

**Comment by superzjg** [comment]
> > 不要 新旧格式配置混用，可能解析出错 （tls_trusted_ca_file）。
> 
> 注释掉一样的

配置文件使用绝对路径试试，难道读取的不是同一个？
我这用了一段时间没问题，亦0.52.3

**Comment by superzjg** [comment]
你打开时有警告信息，识别成 ini 了，注意toml不需要 写 [common] 否则识别为 ini

**Comment by fengyuclub** [comment]
> 你打开时有警告信息，识别成 ini 了，注意toml不需要 写 [common] 否则识别为 ini
我当然试了，但是verify -c 过不去的，详细看了文档，没找到相应的toml示例，能给个链接关于toml的吗 ？

**Comment by superzjg** [comment]
> > 你打开时有警告信息，识别成 ini 了，注意toml不需要 写 [common] 否则识别为 ini
> 
> 我当然试了，但是verify -c 过不去的，详细看了文档，没找到相应的toml示例，能给个链接关于toml的吗 ？

toml示例：https://github.com/fatedier/frp/blob/dev/conf/frps_full_example.toml
中文文档：https://gofrp.org/zh-cn/docs/

**Comment by fengyuclub** [comment]
和安装包里一样的，就是按这个弄的，真奇怪

**Comment by fengyuclub** [comment]
> 1. WARNING: ini format is deprecated and the support will be removed in the future, please use yaml/json/toml format instead!

这句WARNING应该是让我会错意了，应该直接就说“WARNING:检测到配置文件格式为ini，布拉布拉xxx”
谢谢你的提醒，目前应该正常了，还在测试服务端的面板，不知道是不是出于安全考虑不能访问了，之前ini正常的。

**Comment by superzjg** [comment]
> > 1. WARNING: ini format is deprecated and the support will be removed in the future, please use yaml/json/toml format instead!
> 
> 这句WARNING应该是让我会错意了，应该直接就说“WARNING:检测到配置文件格式为ini，布拉布拉xxx” 谢谢你的提醒，目前应该正常了，还在测试服务端的面板，不知道是不是出于安全考虑不能访问了，之前ini正常的。

面板问题，是绑定地址问题，默认只有本机访问，改一下就行，作者大佬这里说了出于安全：
https://github.com/fatedier/frp/issues/3709#issuecomment-1774338490
