### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Zqq19930717** [fatedier/frp#3725]
### Describe the feature request

frps支持命令行指定参数，可以不使用配置文件。frpc也可以支持命令行指定参数（比如服务器ip，端口，本机端口，远端端口），而不是一定要依赖于配置文件来使用frpc吗？

### Describe alternatives you've considered

frpc也可以支持命令行指定参数而不是一定要依赖于配置文件来使用frpc吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
为什么不自己试试
 `frpc --help`会显示总帮助
或者对于http类型，使用`frpc http --help`

**Comment by Zqq19930717** [comment]
已经解决
