### ISSUE TITLE
群辉NAS连接报错

### ISSUE THREAD

**Issue by MeetGGBoy** [fatedier/frp#3729]
### Bug Description

使用最新版本0.52.3，Windows平台客户端是可以的
![Snipaste_2023-10-29_15-49-14](https://github.com/fatedier/frp/assets/39196936/246d664a-300a-4769-a329-16d07605a30c)
![Snipaste_2023-10-29_15-58-35](https://github.com/fatedier/frp/assets/39196936/c5aa3e88-3848-4aee-bb13-50b5cec7661e)
![Snipaste_2023-10-29_15-59-23](https://github.com/fatedier/frp/assets/39196936/113ec321-92a4-45f4-96df-ac4419257811)

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

群辉配置如下
serverAddr = "XXXXXXXX"
serverPort = 7000
token = XXXXXXXX

[[Synology DSM]]
name = "DSM"
type = "tcp"
localIP = "127.0.0.1"
localPort = 5000
remotePort = 1688

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
这应该是你把toml和ini格式混用的原因（token = XXXXXXXX）
另外，issues板块主要是讨论bug和功能需求，使用上的问题请仔细参看文档。

**Comment by wuai1024** [comment]
你用的镜像不对

**Comment by flash91120** [comment]
[common]
server_addr = xxxx
server_port = 7000
token = 123

[DMS]
type = tcp
local_ip = 127.0.0.1
local_port = 5000
remote_port = 7501

###########分割线########
.toml文件按照我这么配就行，需要注意，一定要把所有的remote_port在服务器放通，然后访问的都是remote_port端口

**Comment by flash91120** [comment]
no




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月3日(星期五) 下午2:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fatedier/frp] 群辉NAS连接报错 (Issue #3729)





 
Closed #3729 as completed.
