### ISSUE TITLE
frps日志中的未知IP地址

### ISSUE THREAD

**Issue by zhixin612** [fatedier/frp#3730]
### Bug Description

请问通过frps连接其他设备时，frps服务器端日志中的“userConn.RemoteAddr”地址是什么
（即日志中“userConn l[AAA] r[BBB]”的BBB部分）

为什么会解析出来不属于自己服务器、客户端的地址？并且使用防火墙屏蔽该IP之后下次连接还会出现新的IP？

![图片](https://github.com/fatedier/frp/assets/53746620/ecaad40c-5521-4486-a1b3-c01efa9bbf75)

图中红色遮挡部分是我终端设备的IP，但黄色标注部分的IP地址并非我的服务器、任一终端设备的IP

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

NULL

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
这个我观察过我的https代理，workConn 的 l 后面是frps服务器ip，r 后面是客户端外网ip
userConn的 r 对应我的客户端内网ip。

你的ip若有问题，尝试更换端口，可能是有人在扫描并尝试连接，一般不会造成损失，因为你转发的服务肯定有强密码，别人登录不上。。
其实我觉得还是stcp更安全。

**Comment by zhixin612** [comment]
> 这个我观察过我的https代理，workConn 的 l 后面是frps服务器ip，r 后面是客户端外网ip userConn的 r 对应我的客户端内网ip。
> 
> 你的ip若有问题，尝试更换端口，可能是有人在扫描并尝试连接，一般不会造成损失，因为你转发的服务肯定有强密码，别人登录不上。。 其实我觉得还是stcp更安全。

谢谢回复，你说的有道理，不过我没有明白为什么这个userConn.RemoteAddr的IP为什么不是我的终端设备的实际IP地址，我并没有使用代理。不知道是bug还是怎样

**Comment by superzjg** [comment]
> > 这个我观察过我的https代理，workConn 的 l 后面是frps服务器ip，r 后面是客户端外网ip userConn的 r 对应我的客户端内网ip。
> > 你的ip若有问题，尝试更换端口，可能是有人在扫描并尝试连接，一般不会造成损失，因为你转发的服务肯定有强密码，别人登录不上。。 其实我觉得还是stcp更安全。
> 
> 谢谢回复，你说的有道理，不过我没有明白为什么这个userConn.RemoteAddr的IP为什么不是我的终端设备的实际IP地址，我并没有使用代理。不知道是bug还是怎样

我刚试了，是显示自己的ip的。

**Comment by wuai1024** [comment]
我怎么看不到这样的日志？

**Comment by zhixin612** [comment]
> 我怎么看不到这样的日志？

日志等级没有设对吧，debug级别才行
