### ISSUE TITLE
How to use vscode to connect to remote server?

### ISSUE THREAD

**Issue by Nutingnon** [fatedier/frp#3732]
### Bug Description

As the instruction on [多个 SSH 服务复用同一端口](https://gofrp.org/zh-cn/docs/examples/multiple-ssh-over-same-port/). I successfully use terminal to connect my client machine. However, it took me a whole day to figure out how to connect my client machine on vscode. 

What should I do?

### frpc Version

the newest

### frps Version

the newest

### System Architecture

linux/amd64

### Configurations

same as the 多个 SSH 服务复用同一端口 website

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by anselanza** [comment]
I got this to work.

Go to `Remote-SSH: Add New Host..`

Then add the full SSH command including the relevant port, e.g. 
```
ssh -p 6000 destinationUsername@server.domain
```

Use `ssh-id-copy` to make the process even smoother (no prompt for password).
