### ISSUE TITLE
[Feature Request] Recommended to add the network card binding function of frpc

### ISSUE THREAD

**Issue by ChishFoxcat** [fatedier/frp#3733]
### Describe the feature request

My server has dual broadband access, but the upload speed of one of them is very slow, but that broadband has a public network, and a fast broadband does not have a public network, and I need a fast broadband for the frpc outlet. I checked the documentation. There is no function to specify or bind a network card.

我的服务器是双宽带出入，但是其中的一个上传速度很慢，但是那个宽带是有公网的，很快的宽带则没有公网，而我需要很快的宽带为frpc的出口，查了文档并没有指定或绑定网卡的功能。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
你可以绑定 源IP
https://github.com/fatedier/frp/blob/5760c1cf92b87a9d734e6c31c626f9a4d282fde0/conf/frpc_full_example.toml#L87
