### ISSUE TITLE
[Feature Request] reduce the binary size for the embedded devices

### ISSUE THREAD

**Issue by ty359** [fatedier/frp#3739]
### Describe the feature request

openwrt上别的软件就几kb，frps/frpc 加起来10M，是不是可以考虑想办法缩减一下。

### Affected area

- [ ] Docs
- [ ] Installation
- [x] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
说 frps/frpc 加起来10M也不对，你装的ipk应该是制作者把binary用ups压缩过的（运行时在ram解压），原版arm64的frpc大于12M，frps约15M。
那种几kb的软件一般是 C 语言编写的，动态编译，链接了系统很多库文件（依赖）。
其实 go 语言编写的程序体积都比较大的，比如 alist 将近50M，跟默认 静态编译 关系很大，但也有好处，就是基本不需要安装什么依赖单个文件即可运行。

**Comment by fatedier** [comment]
考虑硬件成本越来越低，嵌入式设备的性能和内存/存储也越来越强，在这方面的投入似乎价值不是很大。

像上面说的，你也可以尝试针对你的系统看能不能用动态链接库的方式编译。
