### ISSUE TITLE
windows 启动log报异常

### ISSUE THREAD

**Issue by wuai1024** [fatedier/frp#3741]
### Bug Description

``` yaml
log:
  to: "D:\\frp\\logs\\frpc.log"
```

``` shell
logs.BeeLogger.SetLogger: invalid character 'l' in string escape code
```

### frpc Version

v0.52.3

### frps Version

v0.52.3

### System Architecture

windows/amd64

### Configurations

如题，必须去掉，to 才可以启动

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by wuai1024** [comment]
另外控制台显示也有一点问题。

客户端日志：
``` shell
2023/11/02 22:53:07 [I] [root.go:139] start frpc service for config file [frpc.yaml]
2023/11/02 22:53:07 [I] [service.go:299] [0da462d3a3c7e558] login to server success, get run id [0da462d3a3c7e558]
2023/11/02 22:53:07 [I] [proxy_manager.go:156] [0da462d3a3c7e558] proxy added: [1125.web 1125.remote-tcp 1125.remote-udp]
2023/11/02 22:53:07 [I] [control.go:173] [0da462d3a3c7e558] [1125.web] start proxy success
2023/11/02 22:53:07 [I] [control.go:173] [0da462d3a3c7e558] [1125.remote-tcp] start proxy success
2023/11/02 22:53:07 [I] [control.go:173] [0da462d3a3c7e558] [1125.remote-udp] start proxy success
2023/11/02 22:53:08 [I] [udp.go:91] [0da462d3a3c7e558] [1125.remote-udp] incoming a new work connection for udp proxy
```

服务端控制台显示：
![image](https://github.com/fatedier/frp/assets/13379708/67b393d8-7c65-4935-8455-f020adfe2ae6)

**Comment by superzjg** [comment]
问题一：路径改成这样：`to: "D:/frp/logs/frpc.log"`，为何不能用\原因不明
问题二：没看明白

**Comment by wuai1024** [comment]
> 问题一：路径改成这样：`to: "D:/frp/logs/frpc.log"`，为何不能用\原因不明 问题二：没看明白

路径修改后好了，奇怪，以前都不能这样用的，新版的连这个分隔符都修改了
