### ISSUE TITLE
腾讯云 centos8上 dashboard 不能访问

### ISSUE THREAD

**Issue by 334-c** [fatedier/frp#3742]
### Bug Description

1.异常问题
    核心问题：代理均可正常访问，仅仅不能访问centos上的 dashboard。
    在该centos服务器上： 0.51版本可以正常访问dashboard，0.52版本、0.52.3版本均不能访问dashboard。0.52.3配置和windows10配置相同。
    在本地windows10上：0.52.3可正常访问dashboard，其他版本未测试。
    
2. 硬件信息
    服务器: 腾讯云轻量应用服务器
    硬件: 2h4g
    系统: CentOS Stream 8 64bit
    uname -a信息: Linux VM-20-6-centos 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

3.版本配置
frp版本0.52.3: frp_0.52.3_linux_amd64.tar.gz
frp版本0.52.0: frp_0.52.0_linux_amd64.tar.gz
`
[root@VM-20-6-centos frp_0.52.0_linux_amd64]# ./frps -c frps.toml
2023/11/03 11:00:25 [I] [root.go:102] frps uses config file: frps.toml
2023/11/03 11:00:26 [I] [service.go:200] frps tcp listen on 0.0.0.0:9005
2023/11/03 11:00:26 [I] [service.go:312] Dashboard listen on 127.0.0.1:9003
2023/11/03 11:00:26 [I] [root.go:111] frps started successfully
`
配置文件:
`
bindPort = 9005

webServer.port = 9003
# dashboard 用户名密码，可选，默认为空
webServer.user = "admin"
webServer.password = "admin"
`

frp版本0.51.0: frp_0.51.0_linux_amd64.tar.gz
运行日志:
`
[root@VM-20-6-centos frp_0.51.0_linux_amd64]# ./frps -c frps.ini
2023/11/03 10:58:38 [I] [root.go:204] frps uses config file: frps.ini
2023/11/03 10:58:38 [I] [service.go:206] frps tcp listen on 0.0.0.0:7000
2023/11/03 10:58:38 [I] [service.go:318] Dashboard listen on 0.0.0.0:9051
2023/11/03 10:58:38 [I] [root.go:213] frps started successfully
`
配置文件:
`
[common]
bind_port = 7000
dashboard_port = 9051
`

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

bindPort = 9005

webServer.port = 9003
# dashboard 用户名密码，可选，默认为空
webServer.user = "admin"
webServer.password = "admin"

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by 334-c** [comment]
配置文件
    `
        bindPort = 9005

        webServer.port = 9003
        # dashboard 用户名密码，可选，默认为空
        webServer.user = "admin"
        webServer.password = "admin"
    `

**Comment by superzjg** [comment]
配置一下 `webServer.addr`

https://github.com/fatedier/frp/issues/3709
