### ISSUE TITLE
frp能否直接用IP地址访问，一直提示frpc中要配置customDomains

### ISSUE THREAD

**Issue by liaoweiguo** [fatedier/frp#3743]
### Describe the feature request

能不能不配置域名，直接用IP访问

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
用tcp类型就不需要配置域名啊
