### ISSUE TITLE
[frpc] login to server failed: dial tcp: lookup tp.xx.com on 127.0.0.53:53: server misbehaving

### ISSUE THREAD

**Issue by zolagz** [fatedier/frp#3748]
### Bug Description

[W] [service.go:133] login to server failed: dial tcp: lookup tp.xx.com on 127.0.0.53:53: server misbehaving

### frpc Version

0.51.3

### frps Version

0.51.3

### System Architecture

linux/arm

### Configurations

[common]
tls_enable = true
server_addr = tp.xx.com
server_port = 7000

[test]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 70011

### Logs

2023/11/06 14:41:31 [I] [root.go:220] start frpc service for config file [/opt/frp_0.51.3_linux_arm64/frpc.ini]
2023/11/06 14:41:31 [W] [service.go:133] login to server failed: dial tcp: lookup tp.xx.com on 127.0.0.53:53: server misbehaving
2023/11/06 14:41:31 [I] [root.go:236] frpc service for config file [/opt/frp_0.51.3_linux_arm64/frpc.ini] stopped
2023/11/06 14:41:32 [I] [root.go:220] start frpc service for config file [/opt/frp_0.51.3_linux_arm64/frpc.ini]
2023/11/06 14:41:32 [W] [service.go:133] login to server failed: dial tcp: lookup  tp.xx.com on 127.0.0.53:53: server misbehaving
2023/11/06 14:41:32 [I] [root.go:236] frpc service for config file [/opt/frp_0.51.3_linux_arm64/frpc.ini] stopped
2023/11/06 14:41:34 [I] [root.go:220] start frpc service for config file [/opt/frp_0.51.3_linux_arm64/frpc.ini]
2023/11/06 14:41:34 [W] [service.go:133] login to server failed: dial tcp: lookup  tp.xx.com on 127.0.0.53:53: server misbehaving
2023/11/06 14:41:34 [I] [root.go:236] frpc service for config file [/opt/frp_0.51.3_linux_arm64/frpc.ini] stopped
2023/11/06 14:41:37 [I] [root.go:220] start frpc service for config file [/opt/frp_0.51.3_linux_arm64/frpc.ini]
2023/11/06 14:41:37 [W] [service.go:133] login to server failed: dial tcp: lookup  tp.xx.com on 127.0.0.53:53: server misbehaving
2023/11/06 14:41:37 [I] [root.go:236] frpc service for config file [/opt/frp_0.51.3_linux_arm64/frpc.ini] stopped

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
最大端口号65535

**Comment by zolagz** [comment]
remote_port = 51034,这样也是不行的

**Comment by xqzr** [comment]
确保 系统 DNS 能解析域名
另，可通过 https://github.com/fatedier/frp/blob/184223cb2f240b844f90b3390645672d2225da88/conf/frpc_full_example.toml#L121 自定义 DNS

**Comment by viocha** [comment]
请问systemd如何等待dns服务器可用

**Comment by viocha** [comment]
目前 0.65.0 版本也会存在这个问题，开机时登录总是失败，即便等待 `network-online` 也会失败。给 `frpc.toml` 加上 `loginFailExit = false` 能比较好地解决。

```
[Unit]
Description=FRP Client
After=network-online.target
Requires=network-online.target
```

**Comment by sinoll** [comment]
楼上才是正解 0.65版 修改两处
frpc.toml
loginFailExit = false

frp.service
[Unit]
Description=FRP Client
After=network-online.target
Requires=network-online.target
