### ISSUE TITLE
frpc 始终启动不起来

### ISSUE THREAD

**Issue by MengXueSD** [fatedier/frp#3749]
### Bug Description

serverAddr = "x.x.x.x"
serverPort = 与frps的bind_port一致

[[proxies]]
name = "test-http"
type = "http"
localIP = "127.0.0.1"
localPort = 80
remotePort = 与frps的bind_port一致
custom_domains = x.x.com

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

frps linux/amd64; frpc  windows/amd64

### Configurations

无法启动frpc

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
自定义域名的正确写法：`customDomains = ["web01.yourdomain.com"]`

**Comment by xqzr** [comment]
需要**日志**
