### ISSUE TITLE
[Feature Request] Nightly Docker image

### ISSUE THREAD

**Issue by RobKenis** [fatedier/frp#3751]
### Describe the feature request

A docker image is not being built on a release or manual input. Can we get a nightly build to validate changes that have been merged but have not been released yet?

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
This may not be suitable for the current development process. The dev branch does not have any guarantee of usability and is not recommended for use.
