### ISSUE TITLE
Stranger problem:cannot use frp in new configs mode while everything normal in old patterns

### ISSUE THREAD

**Issue by MChello1990** [fatedier/frp#3753]
### Bug Description

Today I decide to update my frp to gather new features. Unfortunately, sth. stranger occurred to me.
Here's the problem:
I rewrite my old config files to match new config syntax. But I found that if I use old files the frp will functions normal. When I exchange config to new file, frp can still start and gather connection, but have no response to any connections, I cannot even open the dashboard. Anyway, I decide to write this issue to figure out it.

### frpc Version

0.52.2

### frps Version

0.52.2

### System Architecture

windows/amd64

### Configurations

Frps:
{{
Old ini:
[common]
bind_addr = 0.0.0.0
bind_port = 52222
quicBindPort = 52222
kcpBindPort = 52221
token = *****
dashboard_user = ****
dashboard_pwd = ****
dashboard_port = 7500
transport.useEncryption = true
transport.useCompression = true

new toml:
bindPort = 52222
webServer.addr = "127.0.0.1"
webServer.port = 7500
webServer.user = *****
webServer.password = *****
auth.method = "token"
auth.token = ******
transport.useEncryption = true
transport.useCompression = true
}}

Frpc:
{{
Old ini:
[common]
server_addr = 47.102.218.172
server_port = 52222
token=*****
transport.useEncryption = true
transport.useCompression = true

[ssh]
type = tcp
name = "ssh"
local_ip = 127.0.0.1
local_port = 3389
remote_port = 52002

[netdisk]
type = tcp
local_ip = 127.0.0.1
local_port = 775
remote_port = 52001
name = "netdisk"

New toml:
serverAddr = "47.102.218.172"
serverPort = 52222
auth.method = "token"
auth.token = "****"

[ssh1]
name = "ssh1"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3389
remotePort = 51000

[netdisk11]
name = "netdisk11"
type = "tcp"
localIP = "127.0.0.1"
localPort = 775
remotePort = 52221
}}

### Logs

Old ini:
C:\Servers>frps -c frps.ini
WARNING: ini format is deprecated and the support will be removed in the future, please use yaml/json/toml format instead!
2023/11/08 14:44:43 [I] [root.go:102] frps uses config file: frps.toml
2023/11/08 14:44:44 [I] [service.go:200] frps tcp listen on 0.0.0.0:52222
2023/11/08 14:44:44 [I] [service.go:312] Dashboard listen on 0.0.0.0:7500
2023/11/08 14:44:44 [I] [root.go:111] frps started successfully
2023/11/08 14:44:44 [I] [service.go:533] [****] client login info: ip [*****] version [0.52.3] hostname [] os [windows] arch [amd64]
2023/11/08 14:44:45 [I] [service.go:533] [****] client login info: ip [*****] version [0.52.2] hostname [] os [windows] arch [amd64]
2023/11/08 14:44:53 [I] [dashboard_api.go:73] Http request: [/api/serverinfo]
2023/11/08 14:44:53 [I] [dashboard_api.go:66] Http response [/api/serverinfo]: code [200] 
2023/11/08 15:04:56 [I] [tcp.go:82] [fdf7d3b53a0dfb97] [netdisk] tcp proxy listen port [52001]
2023/11/08 15:04:56 [I] [control.go:500] [fdf7d3b53a0dfb97] new proxy [netdisk] type [tcp] success
2023/11/08 15:04:56 [I] [tcp.go:82] [fdf7d3b53a0dfb97] [ssh] tcp proxy listen port [52002]
2023/11/08 15:04:56 [I] [control.go:500] [fdf7d3b53a0dfb97] new proxy [ssh] type [tcp] success
2023/11/08 15:04:59 [I] [proxy.go:204] [fdf7d3b53a0dfb97] [netdisk] get a user connection [****]

#I visited the dashboard, functions normal,frpc either.

New toml:
C:\Servers>frps -c frps1.toml
2023/11/08 14:59:24 [I] [root.go:102] frps uses config file: frps1.toml
2023/11/08 14:59:25 [I] [service.go:200] frps tcp listen on 0.0.0.0:52222
2023/11/08 14:59:25 [I] [service.go:312] Dashboard listen on 127.0.0.1:7500
2023/11/08 14:59:25 [I] [root.go:111] frps started successfully
2023/11/08 14:59:29 [I] [service.go:533] [****] client login info: ip [****] version [0.52.3] hostname [] os [windows] arch [amd64]
2023/11/08 14:59:30 [I] [service.go:533] [****] client login info: ip [****] version [0.52.2] hostname [] os [windows] arch [amd64]
#connect to dashboard:HTTP ERROR 502
#connect to a website through frpc:ERR_CONNECTION_RESET

### Steps to reproduce

1. As the normal start process
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
Syntax error.

frpc:

**[[proxies]]**
name = "ssh1"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3389
remotePort = 51000

**[[proxies]]**
name = "netdisk11"
type = "tcp"
localIP = "127.0.0.1"
localPort = 775
remotePort = 52221

**Comment by MChello1990** [comment]
So now the proxies config must write as the [[proxies]] right?

**Comment by MChello1990** [comment]
but its still unreasonable that my dashboard cannot get connection

**Comment by superzjg** [comment]
> but its still unreasonable that my dashboard cannot get connection

`webServer.addr = "127.0.0.1"` means localhost access.
https://github.com/fatedier/frp/issues/3709

**Comment by MChello1990** [comment]
Oops, problem solved, thank a lot!!
