### ISSUE TITLE
frp 怎么转发websocket消息

### ISSUE THREAD

**Issue by mengxueForgoogle** [fatedier/frp#3756]
### Bug Description

局域网可以跑通，直接部署到公网也可以跑通，但是想要通过webrtc做转发就跑不通了，需要frp转发做实时程序调试。

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64, windows/amd64

### Configurations

frp无法转发ws://消息

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by mengxueForgoogle** [comment]
现在使用的是tcp还是不行

**Comment by xqzr** [comment]
webrtc 使用 UDP
