### ISSUE TITLE
http本质上就是tcp，为什么要单独做一个http和https呢？[Feature Request] 

### ISSUE THREAD

**Issue by ryouaki** [fatedier/frp#3761]
### Describe the feature request

我希望使用frp代理我的http。但是我只有ip没有域名，所以按目前的用法不能使用http模式。所以使用了tcp代理。但是这也导致我用浏览器访问的时候，无服务。而使用curl的时候却可以访问到服务器。

而http协议就是基于tcp协议开发的。那么是否可以直接使用一个tcp来同时处理http，https，tcp。而不需要单独处理？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
tcp模式应该可以访问，经常使用tcp访问远端路由器的页面，指定一个 `remotePort`即可。
不晓得你为何浏览器打不开，注意remotePort需要在服务器防火墙中打开。

至于http模式有一些tcp没有的高级功能，参看：
https://gofrp.org/zh-cn/docs/reference/proxy/#httpproxyconfig

**Comment by xqzr** [comment]
浏览器无法访问，可通过 F12 检查

**Comment by ryouaki** [comment]
<img width="390" alt="截屏2023-11-13 15 26 03" src="https://github.com/fatedier/frp/assets/9922563/65956bbf-ae8b-4471-9d1d-a95b175f37a2">
![截屏2023-11-13 16 16 33](https://github.com/fatedier/frp/assets/9922563/5d66232b-1aa3-48c0-b5ab-f35a4541f623)
<img width="421" alt="截屏2023-11-13 16 16 41" src="https://github.com/fatedier/frp/assets/9922563/64c5aa4e-2200-49b9-9b43-4d3b3fb5b7b6">
<img width="1014" alt="截屏2023-11-13 16 16 46" src="https://github.com/fatedier/frp/assets/9922563/0464acaa-a10d-46ba-a6ee-ad939e160b91">
<img width="723" alt="截屏2023-11-13 16 16 51" src="https://github.com/fatedier/frp/assets/9922563/336e9ae0-2f82-468a-800c-c5971d10270b">
我这里测试，就是这样的。使用tcp代理。然后浏览器发出的请求，会没有响应。。。。。。

**Comment by ryouaki** [comment]
结案了。可以直接在customDomains写ip。最后发送给frpc的都是按customDomains + vhostHTTPPort去寻找服务的。

**Comment by jkhAIjava** [comment]
老哥，customDomains是 配置在frpc，vhostHttpPort配置在frps上吗

**Comment by shyandsy** [comment]
@ryouaki 可以提供个例子么
我也是内网https，死活不通
