### ISSUE TITLE
这么有名的项目，居然没有Socks5的说明

### ISSUE THREAD

**Issue by qooboy** [fatedier/frp#3762]
### Bug Description

最新版的官方文档，对于配置文件的编写好像做了改变，很多参数后面加了""才能运行，而网上的信息，参数后面大多是不需要“”，然后搜了全网，硬是配置了不Socks5，请路过的大神指点一下！

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

inux/amd64

### Configurations

服务器配置
```
serverAddr = "1.1.1.1"
bindPort = 7000
auth_token = "abcdef"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"
log_file = "./frps.log"
log_level = "info"
log_max_days = 3
```
客户端配置
```
serverAddr = "1.1.1.1"
bindPort = 7000
auth_token = "abcdef"
[[proxies]]
name = "socks_proxy"
type = "tcp"
remotePort = 6000
[proxies.plugin]
type = "socks5"
httpUser = "admin"
httpPassword = "123456"
transport.useEncryption = true
transport.useCompression = true
```

服务器端管理面板能看到在线，但是在其他设备使用Socks5代理配置上网，无法打开网页

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by shangzeng** [comment]
我也是，难受的要死

**Comment by aohanhongzhi** [comment]
确实，文档确实，看来有点难度上手。
