### ISSUE TITLE
frpc莫名访问0.0.0.0

### ISSUE THREAD

**Issue by black-zero358** [fatedier/frp#3763]
### Bug Description

![image](https://github.com/fatedier/frp/assets/53086059/26ecda22-00f6-4ac5-8607-8041c629aa45)
![image](https://github.com/fatedier/frp/assets/53086059/b16b15c7-be75-445d-9f94-3752955fb4f8)

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

frps:
bindPort = 7899

frpc:
erverAddr = "47.*.*.*"
serverPort = 7899

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 5*

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by black-zero358** [comment]
妈的，不知道哪里的bug，复制配置文件过去的时候总少个第一个字符

**Comment by Raymond631** [comment]
我也遇到了这个问题，请问您是怎么解决的呀？

**Comment by black-zero358** [comment]
> 我也遇到了这个问题，请问您是怎么解决的呀？

仔细检查配置文件
