### ISSUE TITLE
通过http代理到国外的客户端，能并入国外客户端的内网，但打不开被墙的网站！

### ISSUE THREAD

**Issue by qooboy** [fatedier/frp#3764]
> ### Bug Description
> 服务器在香港，国外客户端开通了http代理端口，在国内的windows网络设置代理上网，通过浏览器查询ip，可显示与国外客户端同网ip，也能访问国外客户端的内网(如路由器、nas等)，但却不能打开Google等网站，也就是说打不开被墙的网站，按说ip都显示在国外，用的也是国外的网络，为什么打不开国外的网站？
> 
> ### frpc Version
> 0.52.3
> 
> ### frps Version
> 0.52.3
> 
> ### System Architecture
> inux/amd64
> 

```
# 客户端配置文件
[[proxies]] name = "th_http" 
type = "tcp" 
remotePort = 6600 
[proxies.plugin] 
type = "http_proxy"
```

**Comment by qooboy** [comment]
> ### Bug Description
> 服务器在香港，国外客户端开通了http代理端口，在国内的电脑通过浏览器查询ip，可显示与国外客户端同网ip，也能访问国外客户端的内网(如路由器、nas等)，但却不能打开Google等网站，也就是说打不开被墙的网站，按说ip都显示在国外，用的也是国外的网络，为什么打不开国外的网站？
> 
> ### frpc Version
> 0.52.3
> 
> ### frps Version
> 0.52.3
> 
> ### System Architecture
> inux/amd64
> 
> ### Configurations

```
# 客户端配置文件
[[proxies]] name = "th_http" 
type = "tcp" 
remotePort = 6600 
[proxies.plugin] 
type = "http_proxy"
```

> 
>

**Comment by qooboy** [comment]
我同时配置了Socks5代理，用代理软件填入Socks5的代理信息，是可以的

**Comment by xqzr** [comment]
http 不加密

**Comment by asdf5329** [comment]
直接用OPENVPN
