### ISSUE TITLE
如何设置日志保存时间为0天

### ISSUE THREAD

**Issue by befen** [fatedier/frp#3765]
### Describe the feature request

如何设置日志保存时间为0天

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
这也许 未实现

**Comment by fatedier** [comment]
输出到标准输出，然后重定向 `/dev/null` 之类的方法

**Comment by befen** [comment]
> 输出到标准输出，然后重定向 `/dev/null` 之类的方法
我想保存当天的日志

**Comment by fatedier** [comment]
标准输出重定向到其他日志分割工具，或者自己写个脚本处理。

**Comment by xqzr** [comment]
> 标准输出重定向到其他日志分割工具，或者自己写个脚本处理。

Linux crontab
```sh
#每日执行
0 0 * * * >frp.log
```

Windows 任务计划程序
程序或脚本：
```batch
%windir%\System32\cmd.exe
```
添加参数：
```batch
/C echo|set /p=>frp.log
```

**Comment by xqzr** [comment]
> 标准输出重定向到其他日志分割工具，或者自己写个脚本处理。

这是一种方法
但还是希望 frp 能够实现

**Comment by mapxn** [comment]
@fatedier 

> 版本0.53.2

frps 如果配置了具体log路径，就不再向标准输出打印了吗？
```yml
log:
  to: /var/log/frp/frps.log
  level: info
  maxDays: 7
  disablePrintColor: false
```
