### ISSUE TITLE
[Feature Request] 建议把frp拆分为经典版本跟frp2

### ISSUE THREAD

**Issue by Whichbfj28** [fatedier/frp#3766]
### Describe the feature request

ini版本很好用。配置简单有效、符合需求
yaml也许对于开发者友好。但是对于用户配置很蛋疼。建议拆分为frp2

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
这里有简单的说明：[关于 v2 的一些说明](https://github.com/fatedier/frp/blob/dev/README_zh.md#%E5%85%B3%E4%BA%8E-v2-%E7%9A%84%E4%B8%80%E4%BA%9B%E8%AF%B4%E6%98%8E)

此外，你可以继续使用 INI，在相当长的时间内都会保持已有功能的兼容（但不会增加新功能支持），直到我们在未来某个不能确定的时间点觉得渐进式重构已经接近完成，将会做较大的破坏性更改时，会彻底抛弃兼容部分的代码。

你可以适用 toml, yaml, json 等格式，其中 toml 和 ini 的配置合适很接近。

**Comment by Whichbfj28** [comment]
发帖子之前我是看过说明的。但是我觉得既然是重构版本。还是分开更好。

**Comment by Whichbfj28** [comment]
而且我也直接建议。frp2版本不需要兼容经典的ini版本。这样更好的进行开发。大家也更容易接受。

**Comment by fatedier** [comment]
这是一个开源项目，而不是商业项目，很多决策受到很多因素限制，只能尽量做更好的选择。

项目的长期发展，应用的功能扩展，迭代，重构，也不是一两句话能说的清。

最后，很重要的一点，你可以继续使用 INI，而不会有任何影响，为了实现这点，其实耗费了较多的时间，但是相比于维护两个版本，对未来是一个非常关键的减负。但是我仍然建议你使用 TOML，几乎没有任何负担，很容易迁移。

你也可以选择 fork 项目，独立维护旧版本的代码。

**Comment by Whichbfj28** [comment]
1、大家都很感谢你提供的这个开源项目。他满足了很多的需求。虽然很多人不说
2、我担心的是。为了保持兼容性。frp会变的跟微信一样臃肿、低效、复杂。
3、我懂。其实我这样使用这个项目且没有提供支持的人是没有权利要求你做过改变的。我只是站在使用者的角度来提供建议。
最后 感谢你提供的这个项目。
