### ISSUE TITLE
[Feature Request] Disallow unknown keys in `verify`

### ISSUE THREAD

**Issue by akx** [fatedier/frp#3769]
### Describe the feature request

Related to #3757 (validating the configuration against a strict schema).

`frpc verify` doesn't validate the presence of extraneous/unknown keys in the document given, so typos are easily uncaught. Can you spot at least 4 in the document below? 😁 

```shell
$ cat > config.json
{
  "serverAddr": "localhost",
  "serverPort": 7000,
  "auth": {
    "metho": "oidc"
  },
  "log": {
    "leverl": "trace"
  },
  "proxies": [
    {
      "name": "xxx",
      "type": "http",
      "localPort": 8888,
      "customDomains": [
        "xxx"
      ],
      "transpor": {
        "useEncrypion": true,
        "useCompression": true
      }
    }
  ]
}
$ ./frpc verify -c a.json
frpc: the configuration file a.json syntax is ok
$
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
I think it is ok to add a `--strict-mode` option to enable this feature, with validation disabled by default.
