### ISSUE TITLE
能转发shadowsocks请求吗？

### ISSUE THREAD

**Issue by yanggis** [fatedier/frp#377]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.12版本

**What operating system and processor architecture are you using (`go env`)?**
Linux x64

**Configures you used:**
Ubuntu 16.04

首先感谢作者开发这么强悍的app,真是太好用了，现在做http proxy转发，很好用。

想请问一下这个能否也可以转发shadowsocks请求到后台的nat里的内网服务器。

**Comment by fatedier** [comment]
这个问题不做讨论。
