### ISSUE TITLE
frpc config reload fails saying it requires web server port

### ISSUE THREAD

**Issue by rbose21** [fatedier/frp#3770]
### Bug Description

I have an frpc client running fine, but if I update its config file and try to hot reload, the command fails. See below:  

```
~# /usr/local/bin/frpc reload -c .~/frpc.toml
web server port should be set if you want to use this feature

```
If I dont use reload everything works fine. I want to reload the frpc config with updated changes without stopping the client. Not sure why it requires the web-server and I can see that if I add the webServer.Port to frpc config, it tries to call the API `http://127.0.0.1:7500/api/reload` so it might be getting confused with the dashboard reload.

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

frpc config is:

serverAddr = "x.x.x.x"
serverPort = xxxx
auth.method = "token"
auth.token = "xxxxxxxx"
log.to = "/frpc.log"
log.level = "debug"
log.maxDays = 3
includes = ["/confd/*.toml"]

### Steps to reproduce

1. Create a simple frpc/frps service ( e.g. just use the examples)
2. Run /usr/local/bin/frpc reload -c ./frpc.toml

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
https://github.com/fatedier/frp/blob/dev/README.md#hot-reloading-frpc-configuration

**Comment by rbose21** [comment]
> https://github.com/fatedier/frp/blob/dev/README.md#hot-reloading-frpc-configuration

thanks for the reply. Isn't hot reload for reloading frpc with a new configuration. I am not trying to use the HTTP API, only trying to reload a running client with an updated configuration

**Comment by superzjg** [comment]
> > https://github.com/fatedier/frp/blob/dev/README.md#hot-reloading-frpc-configuration
> 
> thanks for the reply. Isn't hot reload for reloading frpc with a new configuration. I am not trying to use the HTTP API, only trying to reload a running client with an updated configuration

May not support this feature.
