### ISSUE TITLE
xtcp 发起的 QUIC 使用 IP 地址 作为 SNI 

### ISSUE THREAD

**Issue by xqzr** [fatedier/frp#3771]
### Bug Description

![屏幕截图 2023-11-15 053625](https://github.com/fatedier/frp/assets/34030394/932d06d4-246d-4201-a146-ba746713ee58)
使用 IP 地址 作为 SNI 违反 [RFC6066](https://datatracker.ietf.org/doc/html/rfc6066#section-3)
```
Literal IPv4 and IPv6 addresses are not permitted in "HostName".
```

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

客户端
```json
{"proxies": [
        {
            "name": "SSH",
            "type": "xtcp",
            "localIP": "::1",
            "localPort": 22,
            "allowUsers": [
                "*"
            ]
        }
]}
```
访问端
```json
{"visitors": [
        {
            "name": "SSH_v",
            "type": "xtcp",
            "serverName": "SSH",
            "bindAddr": "::1",
            "bindPort": 2202
        }
]}
```

### Steps to reproduce

访问 `bindPort` 端口

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
所以现在具体的问题是什么？有哪些影响？

**Comment by xqzr** [comment]
> 所以现在具体的问题是什么？有哪些影响？

不符合 RFC 规范。暂时未发现 有任何影响
