### ISSUE TITLE
[Feature Request] Resolves the domain name every time when connecting to the FRP server.

### ISSUE THREAD

**Issue by rikka0w0** [fatedier/frp#3772]
### Describe the feature request

Some FRP servers use DDNS to update their IP addresses in their DNS record. Those servers don't have static IP addresses, and their IP address can change frequently.

Currently, frpc only resolves the domain name once when it starts. This behavior makes it unable to detect host IP changes afterward. If the host IP changes while the frpc is running, the connection will be interrupted, and frpc will still try to connect to the old IP address. I encountered this a few times. Restarting frpc locally re-establishes the channel.

I suggest making frpc resolve the domain name whenever it attempts to connect to the server.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
When the previously connected frps exits, frpc will connect to the new address, otherwise it will not make any changes.
