### ISSUE TITLE
auth.token not available

### ISSUE THREAD

**Issue by ChinaHongkong** [fatedier/frp#3774]
### Bug Description

the version is 0.52.3
i set the auth.token，but always error
![image](https://github.com/fatedier/frp/assets/42881936/be2c3f42-5337-4063-b2d9-cf5882d3b184)

may be commit 4915852b cause this
i change the version to 0.48.0 is ok 

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

frps is linux/amd64  frpc  is windows10

### Configurations

serverAddr = "xx.xx.xx.xx"
serverPort = 7000
auth.token = "xxxxxx"
auth.method = "token"
 
[[kali]]
name = "test-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 7022

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
Change `[[kali]]` to `[[proxies]]`

**Comment by ChinaHongkong** [comment]
good solution thank you

**Comment by naY9yjoS6ZqhOd35sIFH** [comment]
reproduct even [[proxies]] and [[visitors]]
