### ISSUE TITLE
怎么禁用  TLS1.0、TLS1.1 啊 

### ISSUE THREAD

**Issue by DEEPAO** [fatedier/frp#3775]
### Describe the feature request

配置禁用TLS1.0、TLS1.1  可以吗

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
未实现
