### ISSUE TITLE
文档超前，版本滞后

### ISSUE THREAD

**Issue by monk-after-90s** [fatedier/frp#3776]
### Bug Description

我在用[frp_0.52.3_linux_arm64.tar.gz](https://github.com/fatedier/frp/releases/download/v0.52.3/frp_0.52.3_linux_arm64.tar.gz)，
我感觉文档里的特性很多都没有体现在软件里，可能作者还在肝。
比如文档里Dashboard的配置(如下所示)以及子域名设置(会报“not enabld in server”)

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

# frps.toml
webServer.port = 7500
# dashboard 用户名密码，可选，默认为空
webServer.user = "admin"
webServer.password = "admin"

### Logs

11月 16 10:48:45 iZ2vc7z253p2dhqfv8gt3nZ frps[32359]: 2023/11/16 10:48:45 [I] [root.go:102] frps uses config file: /root/code/frp/frps.toml
11月 16 10:48:45 iZ2vc7z253p2dhqfv8gt3nZ frps[32359]: 2023/11/16 10:48:45 [I] [service.go:200] frps tcp listen on 0.0.0.0:7000
11月 16 10:48:45 iZ2vc7z253p2dhqfv8gt3nZ frps[32359]: 2023/11/16 10:48:45 [I] [service.go:261] http service listen on 0.0.0.0:6006
11月 16 10:48:45 iZ2vc7z253p2dhqfv8gt3nZ frps[32359]: 2023/11/16 10:48:45 [I] [root.go:111] frps started successfully

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
关于Dashboard
https://github.com/fatedier/frp/issues/3709#issuecomment-1774338490

**Comment by monk-after-90s** [comment]
> 关于Dashboard [#3709 (comment)](https://github.com/fatedier/frp/issues/3709#issuecomment-1774338490)

curl 127.0.0.1:7500 也试了，connection refused

**Comment by superzjg** [comment]
> > 关于Dashboard [#3709 (comment)](https://github.com/fatedier/frp/issues/3709#issuecomment-1774338490)
> 
> curl 127.0.0.1:7500 也试了，connection refused

注意127.0.0.1为本机地址，只在本机才有效。远程访问请更改。
我一直用着Dashboard没问题

**Comment by xqzr** [comment]
看起来 配置内容 没有被读取

**Comment by monk-after-90s** [comment]
> > > 关于Dashboard [#3709 (comment)](https://github.com/fatedier/frp/issues/3709#issuecomment-1774338490)
> > 
> > 
> > curl 127.0.0.1:7500 也试了，connection refused
> 
> 注意127.0.0.1为本机地址，只在本机才有效。远程访问请更改。 我一直用着Dashboard没问题

我在服务端本地curl的啊

**Comment by monk-after-90s** [comment]
> 看起来 配置内容 没有被读取

我用”dashboard_port = 8889“就可以了，”webServer.port = 8889“没什么用哇。所以我觉得，Linux这个版本应该是没更新，毕竟没有固定公网IP的Linux服务器太少了，作者也太忙了🤣

**Comment by superzjg** [comment]
> > 看起来 配置内容 没有被读取
> 
> 我用”dashboard_port = 8889“就可以了，”webServer.port = 8889“没什么用哇。所以我觉得，Linux这个版本应该是没更新，毕竟没有固定公网IP的Linux服务器太少了，作者也太忙了🤣

怎么可能？一套代码编译的。
我也是Linux-arm64的。
你把完整配置文件贴出来看看，估计有语法错误，未读取到。

**Comment by monk-after-90s** [comment]
> > > 看起来 配置内容 没有被读取
> > 
> > 
> > 我用”dashboard_port = 8889“就可以了，”webServer.port = 8889“没什么用哇。所以我觉得，Linux这个版本应该是没更新，毕竟没有固定公网IP的Linux服务器太少了，作者也太忙了🤣
> 
> 怎么可能？一套代码编译的。 我也是Linux-arm64的。 你把完整配置文件贴出来看看，估计有语法错误，未读取到。

无效的dashboard配置：

```shell
[common]
#内网穿透服务器端监听的IP地址，可以省略，默认为127.0.0.1
bindAddr = 0.0.0.0
#服务器端监听的端口，默认是7000，可自定义
bindPort = 7000
#该端口就是以后访问web服务需要用到的端口
vhost_http_port = 6006

webServer.addr = "0.0.0.0"
webServer.port = 8889
#dashboard_port = 8889
# dashboard 用户名密码，可选，默认为空
#webServer.user = "admin"
#webServer.password = "admin"

privilegeMode = true
```
日志
```shell
● frps.service - FRP Server Service
   Loaded: loaded (/etc/systemd/system/frps.service; enabled; vendor preset: disabled)
   Active: active (running) since 五 2023-11-17 16:39:29 CST; 1s ago
 Main PID: 13215 (frps)
    Tasks: 5
   Memory: 12.5M
   CGroup: /system.slice/frps.service
           └─13215 /root/code/frp/frps -c /root/code/frp/frps.toml

11月 17 16:39:29 iZ2vc7z253p2dhqfv8gt3nZ systemd[1]: Started FRP Server Service.
11月 17 16:39:29 iZ2vc7z253p2dhqfv8gt3nZ frps[13215]: WARNING: ini format is deprecated and the support will be removed in the future, please use yaml/json/toml format instead!
11月 17 16:39:29 iZ2vc7z253p2dhqfv8gt3nZ frps[13215]: 2023/11/17 16:39:29 [I] [root.go:102] frps uses config file: /root/code/frp/frps.toml
11月 17 16:39:29 iZ2vc7z253p2dhqfv8gt3nZ frps[13215]: 2023/11/17 16:39:29 [I] [service.go:200] frps tcp listen on 0.0.0.0:7000
11月 17 16:39:29 iZ2vc7z253p2dhqfv8gt3nZ frps[13215]: 2023/11/17 16:39:29 [I] [service.go:261] http service listen on 0.0.0.0:6006
11月 17 16:39:29 iZ2vc7z253p2dhqfv8gt3nZ frps[13215]: 2023/11/17 16:39:29 [I] [root.go:111] frps started successfully
```

有效的配置
```shell
[common]
#内网穿透服务器端监听的IP地址，可以省略，默认为127.0.0.1
bindAddr = 0.0.0.0
#服务器端监听的端口，默认是7000，可自定义
bindPort = 7000
#该端口就是以后访问web服务需要用到的端口
vhost_http_port = 6006

#webServer.addr = "0.0.0.0"
#webServer.port = 8889
dashboard_port = 8889
# dashboard 用户名密码，可选，默认为空
#webServer.user = "admin"
#webServer.password = "admin"

privilegeMode = true
```
日志
```shell
● frps.service - FRP Server Service
   Loaded: loaded (/etc/systemd/system/frps.service; enabled; vendor preset: disabled)
   Active: active (running) since 五 2023-11-17 16:47:18 CST; 1s ago
 Main PID: 13343 (frps)
    Tasks: 5
   Memory: 10.0M
   CGroup: /system.slice/frps.service
           └─13343 /root/code/frp/frps -c /root/code/frp/frps.toml

11月 17 16:47:18 iZ2vc7z253p2dhqfv8gt3nZ systemd[1]: Started FRP Server Service.
11月 17 16:47:18 iZ2vc7z253p2dhqfv8gt3nZ frps[13343]: WARNING: ini format is deprecated and the support will be removed in the future, please use yaml/json/toml format instead!
11月 17 16:47:18 iZ2vc7z253p2dhqfv8gt3nZ frps[13343]: 2023/11/17 16:47:18 [I] [root.go:102] frps uses config file: /root/code/frp/frps.toml
11月 17 16:47:18 iZ2vc7z253p2dhqfv8gt3nZ frps[13343]: 2023/11/17 16:47:18 [I] [service.go:200] frps tcp listen on 0.0.0.0:7000
11月 17 16:47:18 iZ2vc7z253p2dhqfv8gt3nZ frps[13343]: 2023/11/17 16:47:18 [I] [service.go:261] http service listen on 0.0.0.0:6006
11月 17 16:47:18 iZ2vc7z253p2dhqfv8gt3nZ frps[13343]: 2023/11/17 16:47:18 [I] [service.go:312] Dashboard listen on 0.0.0.0:8889
11月 17 16:47:18 iZ2vc7z253p2dhqfv8gt3nZ frps[13343]: 2023/11/17 16:47:18 [I] [root.go:111] frps started successfully
```

```shell
./frps -v
0.52.3
```

**Comment by superzjg** [comment]
你所指的【无效的dashboard配置】有语法错误：
1、删除`[common]`，有这个frpc会认为你是用旧 ini 格式的配置文件。
2、删除`privilegeMode = true`，貌似我没在参数列表找到这个。

**Comment by superzjg** [comment]
把我说的上面**4个错误语法**改掉，再试。
严重怀疑你有没有认真读文档。

**Comment by monk-after-90s** [comment]
> 把我说的上面**4个错误语法**改掉，再试。 严重怀疑你有没有认真读文档。

改了，确实是我的错🤣。我太忙，没细度文档，网上找的资料
