### ISSUE TITLE
[Feature Request] Web Interface

### ISSUE THREAD

**Issue by lozn00** [fatedier/frp#3777]
### Describe the feature request

I hope to implement a web interface function similar to ngrok for convenient viewing of requests. ngrok has an address called 127.0.0.1:4040 where I can view the detailed information of HTTP request messages, which is very useful for me

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Yes, I also hope.
