### ISSUE TITLE
建议client端增加运行时创建pid file功能的选项

### ISSUE THREAD

**Issue by Magicbrust** [fatedier/frp#378]
如题，这样会方便编写一些运行脚本和systemd service，谢谢。

**Comment by fatedier** [comment]
supervisor?

**Comment by Magicbrust** [comment]
linux下，就是在frpc每次启动时，当前目录会增加一个frpc.pid，里面记录了frpc进程的pid号。
很多程序都有的功能，具体编程上怎么描述，小白不知道怎么说....

**Comment by fatedier** [comment]
建议用 supervisor 管理。

**Comment by wxlg1117** [comment]
既然是血shell,那自己用脚本捕捉也可以啊
 ps -ef | grep frpc | grep '.ini' | awk '{print $2}'

**Comment by 1oo1** [comment]
楼上的脚本改成这个可以通用其他 `ps -ef | grep frpc | grep -v grep | awk '{print $2}'`
