### ISSUE TITLE
port leak

### ISSUE THREAD

**Issue by leeuwin** [fatedier/frp#3780]
### Bug Description

frpc成功登陆连接frps之后，一段时间后，偶然出现frpc发现离线重新登陆frps，但是映射的端口没有释放，导致无法重新登陆成功

### frpc Version

v0.52.3

### frps Version

v0.52.3

### System Architecture

linux/amd64

### Configurations

nothing special

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/blob/526e809bd50eed4ff5c2211adc91126abb864530/conf/frps_full_example.toml#L25-L41

**Comment by thanh-tl** [comment]
> https://github.com/fatedier/frp/blob/526e809bd50eed4ff5c2211adc91126abb864530/conf/frps_full_example.toml#L25-L41

I have the same problem and set transport.heartbeatTimeout = 30 or lower does not resolve the problem. I think we need a button like "Kill Proxy" on the dashboard
