### ISSUE TITLE
是否支持范围端口代理，如40000-50000端口由同一个端口6000反向代理

### ISSUE THREAD

**Issue by linshangqiang** [fatedier/frp#3781]
### Describe the feature request

感谢大佬开源

咨询两个问题：
1、是否支持范围端口由同一个端口映射出去，如udp_port : 40000-50000端口映射到6000端口
2、http、udp端口能否使用同一个端口映射

想要达到的目的：  所有需要的端口，不管是http，范围udp端口，都走同一个端口代理，这样服务器只需要开放一个端口。或者http单独走一个端口代理，范围udp端口共同使用一个端口代理，这样服务器对外只需要开发2个端口

我的配置如下：

- frps.toml
```
bindPort = 7000
```

-  frpc.toml
```
server_addr = 182.245.156.93
server_port = 7000

[udpPortRange]
type = udp
local_ip = 10.10.0.24
local_port = 40000-50000
remote_port = 6000
```

- 实际测试结果
在10.10.0.24上启动了一个监听udp 40001端口的服务
使用另外一个设备，发送  echo "Hello from UDP client" | nc -u 182.254.156.93 6000
10.10.0.24未收到任何数据

如果我将local_port = 40000-50000改成local_port = 40000，udp服务器监听40000端口，另一台设备发送 echo "Hello from UDP client" | nc -u 182.254.156.93 6000 时，成功收到数据

想要范围端口能够走同一个端口代理，我该如何配置，如果不能，范围端口-范围代理端口 的这个方案，我该如何配置？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by linshangqiang** [comment]
目前udp范围端口+范围映射已调通,配置如下：
- frps.toml
```
bindPort = 7000
```

- frpc.toml
```
[common]
server_addr = 182.254.156.93
server_port = 7000

[range:test_udp]
type = udp
local_ip = 10.10.0.24
local_port = 42000-50000
remote_port = 42000-50000
use_encryption = false
use_compression = false
```

这种方式需要开放的端口比较多，frp支持 n个udp端口由一个端口代理出去吗

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/blob/526e809bd50eed4ff5c2211adc91126abb864530/conf/frpc_full_example.toml#L254-L261 ~它可能不支持 UDP~

**Comment by linshangqiang** [comment]
> https://github.com/fatedier/frp/blob/526e809bd50eed4ff5c2211adc91126abb864530/conf/frpc_full_example.toml#L254-L261
> 
> ~它可能不支持 UDP~
这个配置没看到有指定范围端口。能否告知下完整得配置？

**Comment by xqzr** [comment]
>>  https://github.com/fatedier/frp/blob/526e809bd50eed4ff5c2211adc91126abb864530/conf/frpc_full_example.toml#L254-L261
>>  
>>  ~它可能不支持 UDP~

>这个配置没看到有指定范围端口。能否告知下完整得配置？

https://gofrp.org/zh-cn/docs/features/common/client-plugin/

**Comment by superzjg** [comment]
https://github.com/fatedier/frp/issues/3711
