### ISSUE TITLE
frps新的配置模式下dashboard不能用

### ISSUE THREAD

**Issue by lyg4795** [fatedier/frp#3787]
### Bug Description

配置文件
bindPort = 2000
# frps.toml
webServer.port = 2001
# dashboard 用户名密码，可选，默认为空
webServer.user = "admin"
webServer.password = "admin"

这样配置 frpc能访问2000 但是web访问ip:2001打不开

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64 Ubuntu20.04

### Configurations

[common]
bind_port = 2000
dashboard_port = 2001
# dashboard 用户名密码，可选，默认为空
dashboard_user = admin
dashboard_pwd = admin
采用旧版的配置文件可以成功打开dashboard

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by lyg4795** [comment]
找了历史issue, 添加webServer.addr = "0.0.0.0"可以了, 另外真的不在官方文档里面添加一下说明吗?

**Comment by fatedier** [comment]
可以加
