### ISSUE TITLE
frpv0.52.2 无法通过ip访问

### ISSUE THREAD

**Issue by lemon5227** [fatedier/frp#3789]
### Bug Description

frpc 端有个服务端口 3000 
[[proxies]]
name = "chatnext"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3000
remotePort = 10300

[[proxies]]
name = "chatweb"
type = "http"
localIP = "127.0.0.1"
localPort = 3000
customDomains = ["xxx.xxx.xxxx"]
可以通过域名访问跟但是不能通过 ip:10300f访问

### frpc Version

0.52.2

### frps Version

0.52.0

### System Architecture

linux/amd64

### Configurations

  GNU nano 6.2                                                                         frpc.toml                                                                                   
serverAddr = "xx.xx.xx.xx"
serverPort = 7000
token = "ladmin"

[[proxies]]
name = "api"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8000
remotePort = 10800

[[proxies]]
name = "chatnext"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3000
remotePort = 10300

[[proxies]]
name = "chatweb"
type = "http"
localIP = "127.0.0.1"
localPort = 3000
customDomains = ["xx.xx.xx.xx"]

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
没有日志吗

**Comment by lemon5227** [comment]
> 没有日志吗

f4802801-2208 frpc[649706]: 2023/11/22 23:52:23 [E] [proxy.go:195] [60554c3a921102bb] [4090] connect to local service [127.0.0.1:3000] error: dial tcp 127.0.0.1:3000: connect: connection refused
Nov 22 23:52:31 gpu-5e81ea91d24f4802801-2208 frpc[649706]: 2023/11/22 23:52:31 [E] [proxy.go:195] [60554c3a921102bb] [4090] connect to local service [127.0.0.1:3000] error: dial tcp 127.0.0.1:3000: connect: connection refused
Nov 22 23:52:32 gpu-5e81ea91d24f4802801-2208 frpc[649706]: 2023/11/22 23:52:32 [E] [proxy.go:195] [60554c3a921102bb] [4090] connect to local service [127.0.0.1:3000] error: dial tcp 127.0.0.1:3000: connect: connection refused
Nov 22 23:52:32 gpu-5e81ea91d24f4802801-2208 frpc[649706]: 2023/11/22 23:52:32 [E] [proxy.go:195] [60554c3a921102bb] [4090] connect to local service [127.0.0.1:3000] error: dial tcp 127.0.0.1:3000: connect: connection refused
Nov 22 23:52:32 gpu-5e81ea91d24f4802801-2208 frpc[649706]: 2023/11/22 23:52:32 [E] [proxy.go:195] [60554c3a921102bb] [4090] connect to local service [127.0.0.1:3000] error: dial tcp 127.0.0.1:3000: connect: connection refused

**Comment by lemon5227** [comment]
> 没有日志吗
·
(base) root@gpu-5e81ea91d24f4802801-2208:~/frp# ./frpc -c frpc.toml 
2023/11/23 00:20:03 [I] [root.go:139] start frpc service for config file [frpc.toml]
2023/11/23 00:20:03 [I] [service.go:299] [270a9b18a57d2ea1] login to server success, get run id [270a9b18a57d2ea1]
2023/11/23 00:20:03 [I] [proxy_manager.go:156] [270a9b18a57d2ea1] proxy added: [4090 openai]
2023/11/23 00:20:04 [I] [control.go:173] [270a9b18a57d2ea1] [4090] start proxy success
2023/11/23 00:20:04 [I] [control.go:173] [270a9b18a57d2ea1] [openai] start proxy success
·

`2023/11/22 16:23:23 [I] [root.go:102] frps uses config file: frps.toml
2023/11/22 16:23:24 [I] [service.go:200] frps tcp listen on 0.0.0.0:7000
2023/11/22 16:23:24 [I] [service.go:261] http service listen on 0.0.0.0:8080
2023/11/22 16:23:24 [I] [service.go:276] https service listen on 0.0.0.0:443
2023/11/22 16:23:24 [I] [service.go:312] Dashboard listen on 0.0.0.0:7500
2023/11/22 16:23:24 [I] [root.go:111] frps started successfully
2023/11/22 16:23:25 [I] [service.go:533] [dcd643b990100649] client login info: ip [223.88.142.118:52121] version [0.52.2] hostname [] os [linux] arch [arm64]
2023/11/22 16:23:26 [I] [http.go:110] [dcd643b990100649] [omv] http proxy listen for host [omv.lemony.eu.org] location [] group [], routeByHTTPUser []
2023/11/22 16:23:26 [I] [control.go:500] [dcd643b990100649] new proxy [omv] type [http] success
2023/11/22 16:23:26 [I] [tcp.go:82] [dcd643b990100649] [smb] tcp proxy listen port [4545]
2023/11/22 16:23:26 [I] [control.go:500] [dcd643b990100649] new proxy [smb] type [tcp] success
2023/11/22 16:23:26 [I] [http.go:110] [dcd643b990100649] [emby] http proxy listen for host [emby.lemony.eu.org] location [] group [], routeByHTTPUser []
2023/11/22 16:23:26 [I] [control.go:500] [dcd643b990100649] new proxy [emby] type [http] success
2023/11/22 16:23:26 [I] [tcp.go:82] [dcd643b990100649] [ssh] tcp proxy listen port [6000]
2023/11/22 16:23:26 [I] [control.go:500] [dcd643b990100649] new proxy [ssh] type [tcp] success
2023/11/22 16:23:26 [I] [http.go:110] [dcd643b990100649] [blog] http proxy listen for host [blog.lemony.eu.org] location [] group [], routeByHTTPUser []
2023/11/22 16:23:26 [I] [control.go:500] [dcd643b990100649] new proxy [blog] type [http] success
2023/11/22 16:23:26 [I] [tcp.go:82] [dcd643b990100649] [next] tcp proxy listen port [3001]
2023/11/22 16:23:26 [I] [control.go:500] [dcd643b990100649] new proxy [next] type [tcp] success
2023/11/22 16:23:26 [I] [https.go:67] [dcd643b990100649] [emby_htts2http] https proxy listen for host [emby.lemony.eu.org]
2023/11/22 16:23:26 [I] [control.go:500] [dcd643b990100649] new proxy [emby_htts2http] type [https] success
2023/11/22 16:23:26 [I] [http.go:110] [dcd643b990100649] [qt] http proxy listen for host [qt.lemony.eu.org] location [] group [], routeByHTTPUser []
2023/11/22 16:23:26 [I] [control.go:500] [dcd643b990100649] new proxy [qt] type [http] success
2023/11/22 16:23:26 [I] [https.go:67] [dcd643b990100649] [omv_htts2http] https proxy listen for host [omv.lemony.eu.org]
2023/11/22 16:23:26 [I] [control.go:500] [dcd643b990100649] new proxy [omv_htts2http] type [https] success
2023/11/22 16:23:26 [I] [https.go:67] [dcd643b990100649] [qt_htts2http] https proxy listen for host [qt.lemony.eu.org]
2023/11/22 16:23:26 [I] [control.go:500] [dcd643b990100649] new proxy [qt_htts2http] type [https] success
2023/11/22 16:23:26 [I] [https.go:67] [dcd643b990100649] [blog_htts2http] https proxy listen for host [blog.lemony.eu.org]
2023/11/22 16:23:26 [I] [control.go:500] [dcd643b990100649] new proxy [blog_htts2http] type [https] success
2023/11/22 16:23:26 [I] [service.go:533] [8c96f7b9d2cec848] client login info: ip [118.180.49.2:29203] version [0.52.2] hostname [] os [linux] arch [amd64]
2023/11/22 16:23:26 [I] [tcp.go:82] [8c96f7b9d2cec848] [4090] tcp proxy listen port [10300]
2023/11/22 16:23:26 [I] [control.go:500] [8c96f7b9d2cec848] new proxy [4090] type [tcp] success
2023/11/22 16:23:26 [I] [tcp.go:82] [8c96f7b9d2cec848] [openai] tcp proxy listen port [10800]
2023/11/22 16:23:26 [I] [control.go:500] [8c96f7b9d2cec848] new proxy [openai] type [tcp] success`

当我通过ip:10300端口访问 没有任何反应

**Comment by superzjg** [comment]
比如`remotePort = 10300`是否被服务器上其他程序占用？是否没有在服务器防火墙上开启？
如果只有找一个端口不能访问，考虑系统环境的问题，与frp无关。

**Comment by xqzr** [comment]
确保 域名解析 与 IP 访问 是同一个 IP
