### ISSUE TITLE
http能转发成功，ssh不行

### ISSUE THREAD

**Issue by 985492783** [fatedier/frp#3790]
### Bug Description

ssh: connect to host xxx port 6000: Connection refused

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

客户端日志
[common]
server_addr = xxx
server_port = 7000
privilege_token = 123456789
token = 123456789
login_fail_exit = true

[web]
type = tcp
localIp = 127.0.0.1
local_port = 22
remote_port = 6000

### Logs

2023/11/22 00:06:44 [I] [root.go:139] start frpc service for config file [frpc.toml]
2023/11/22 00:06:44 [I] [service.go:299] [0467ff3b008ac32a] login to server success, get run id [0467ff3b008ac32a]
2023/11/22 00:06:44 [I] [proxy_manager.go:156] [0467ff3b008ac32a] proxy added: [web]
2023/11/22 00:06:44 [I] [control.go:173] [0467ff3b008ac32a] [web] start proxy success

### Steps to reproduce

防火墙都是打开的，http是可以成功映射的，tcp不行。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
删除privilege_token 这个无效
修改localIp，这个错了

**Comment by 985492783** [comment]
找到问题了，我是docker启动的，所以端口在docker容器内开放了没暴露出来
