### ISSUE TITLE
打开服务器Web 界面后无法访问

### ISSUE THREAD

**Issue by fanhua1994** [fatedier/frp#3794]
### Bug Description

防火墙，安全组全部关闭的情况下。通过外网IP:7500 无法访问Dashboard ，但是`http://127.0.0.1:7500 `提示`Unauthorized`

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

bindPort = 7000
auth.token = "eeeeeeeeeeeeeeeeeeeeeee"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "adeeeeeeee"

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
默认是本机访问，远程需改配置
https://github.com/fatedier/frp/issues/3709

**Comment by xqzr** [comment]
7500 端口 默认监听 `127.0.0.1`

**Comment by xydfg** [comment]
service端7500默认是管理页面，如果在云服务上装的。需把端口加入防火墙，以及服务器对应供应商安全组

**Comment by zhengxl5566** [comment]
作者为了安全考虑，web管理页面 默认监听 127.0.0.1，如果你想在其他机器上访问web页，可以修改监听地址为 0.0.0.0（监听所有）贴个配置参考：
# frps.toml
webServer.port = 7500
webServer.addr = "0.0.0.0"

**Comment by yanxin152133** [comment]
frps Version
0.52.3
我的也不能访问web页面，客户端还死活连不上服务端

**Comment by trowa520** [comment]
试了两台服务器都不行

**Comment by yanxin152133** [comment]
> 试了两台服务器都不行

旧版本试过没

**Comment by superzjg** [comment]
@yanxin152133 @trowa520  一般是配置问题，你不发配置和日志，怎么分析？

**Comment by trowa520** [comment]
> @yanxin152133 @trowa520 一般是配置问题，你不发配置和日志，怎么分析？

找到原因了，需要添加安全组，现在可以正常访问了
![WechatIMG465](https://github.com/fatedier/frp/assets/15259416/7f5311aa-17c6-4791-9c53-becbce75bfe4)

**Comment by yanxin152133** [comment]
> @yanxin152133 @trowa520 一般是配置问题，你不发配置和日志，怎么分析？

我的openwrt，溜了溜了

**Comment by zczy999** [comment]
> 作者为了安全考虑，web管理页面 默认监听 127.0.0.1，如果你想在其他机器上访问web页，可以修改监听地址为 0.0.0.0（监听所有）贴个配置参考：
> 
> # frps.toml
> webServer.port = 7500 webServer.addr = "0.0.0.0"

感谢，改了就好了

**Comment by yanxin152133** [comment]
> > @yanxin152133 @trowa520 一般是配置问题，你不发配置和日志，怎么分析？
> 
> 找到原因了，需要添加安全组，现在可以正常访问了 ![WechatIMG465](https://private-user-images.githubusercontent.com/15259416/290379850-7f5311aa-17c6-4791-9c53-becbce75bfe4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTk2MzIsIm5iZiI6MTcwMjkxOTMzMiwicGF0aCI6Ii8xNTI1OTQxNi8yOTAzNzk4NTAtN2Y1MzExYWEtMTdjNi00NzkxLTljNTMtYmVjYmNlNzViZmU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE3MDg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkOTRlMzI5Yzc4ZTQ5MGI4NzFjMTljMjYwNTUxZTY2NGYyZWVlNjZlMDJjYTg4NmFmNjkxMWRkYzI1NjVmMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yPnzOSn-i4ijqRGCsh_2WNm1LAhfg2ezbDf4k08cUiM)

好奇的问一下你这买的什么云服务器啊

**Comment by 0xganz** [comment]
同问。
`* processing: http://127.0.0.1:7500
* Uses proxy env variable no_proxy == '127.0.0.1,localhost'
*   Trying 127.0.0.1:7500...
* Connected to 127.0.0.1 (127.0.0.1) port 7500
> GET / HTTP/1.1
> Host: 127.0.0.1:7500
> User-Agent: curl/8.2.1
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< Www-Authenticate: Basic realm="Restricted"
< X-Content-Type-Options: nosniff
< Date: Sun, 07 Jan 2024 09:25:07 GMT
< Content-Length: 13
<
Unauthorized
* Connection #0 to host 127.0.0.1 left intact`
