### ISSUE TITLE
How to install FRPC to iPhone iOS

### ISSUE THREAD

**Issue by lxlijava** [fatedier/frp#3795]
### Describe the feature request

How to install FRPC to iPhone iOS

### Affected area

- [X] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [x] Others

**Comment by xqzr** [comment]
https://apps.apple.com/app/id1436902243

**Comment by qiankl** [comment]
> https://apps.apple.com/app/id1436902243

可以在自己开发的app里加入frpc的服务吗

**Comment by lxlijava** [comment]
> https://apps.apple.com/app/id1436902243

It didn't work. Is there a tutorial?

**Comment by xqzr** [comment]
> > https://apps.apple.com/app/id1436902243
> 
> It didn't work. Is there a tutorial?

不工作？提供更多信息。也许你错过了什么...

**Comment by mlkt** [comment]
go 1.17以下编译的在iSH上可以用，但很不稳定，动不动就卡死，xtcp试过编译很多版本，都没有成功，不过其他转发的可以用，但容易挂掉
