### ISSUE TITLE
stcp点对点模式下存在注册proxy被判定存在导致无法二次上线的BUG

### ISSUE THREAD

**Issue by djerryz** [fatedier/frp#3804]
### Bug Description

当运行3到5天左右，偶发出现，会发现proxier会报错：
new [p2p_xxx] already exist!
此时需要杀掉frps，然后重启frps，否则proxier永远无法注册proxies，导致隧道无法使用，影响正常使用。

上述情况已经出现两次，怀疑是frps实现proxies掉线后没有注销掉，导致proxies二次上线被判定重复进而拒绝了注册~！

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

# server
serverAddr = "x"
serverPort = x
auth.method = "token"
auth.token = "xx"
transport.tls.enable = true

# visitor
[[visitors]]
name = "p2p_xxx_visitor"
type = "stcp"
serverName = "p2p_xxx"
secretKey = "xx"
bindAddr = "xx"
bindPort = xx
keepTunnelOpen = false

# proxier
[[proxies]]
name = "p2p_xxx"
type = "stcp"
secretKey = "x"
localIP = "127.0.0.1"
localPort = x

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
我也发现这个问题了，怀疑是某些启动脚本使用 SIGKILL 信号杀frpc进程引起的。我在梅林固件上发现shell脚本写的是killall -9 ，kill -9这些，我现在在前面使用默认信号先杀一次，杀不掉再用-9。或者使用start-stop-daemon 默认信号停止。
