### ISSUE TITLE
with 52.3, there is segmentation fault on centos stream 9

### ISSUE THREAD

**Issue by licanli2082** [fatedier/frp#3806]
### Bug Description

[root@htali99 frp_0.52.3_freebsd_amd64]# ./frpc -h
Segmentation fault (core dumped)
[root@htali99 frp_0.52.3_freebsd_amd64]# ./frps -h
Segmentation fault (core dumped)
[root@htali99 frp_0.52.3_freebsd_amd64]# lsb_release
bash: lsb_release: command not found
[root@htali99 frp_0.52.3_freebsd_amd64]# uname -ar
Linux htali99 5.14.0-386.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov 15 10:38:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[root@htali99 frp_0.52.3_freebsd_amd64]# cat /etc/redhat-release 
CentOS Stream release 9
[root@htali99 frp_0.52.3_freebsd_amd64]# virt-what 
alibaba_cloud
kvm

# dmesg
[ 5959.971864] frps[5562]: segfault at 0 ip 000000000046eea4 sp 00007fffa289bfd0 error 4 in frps[400000+728000] likely on CPU 0 (core 0, socket 0)
[ 5959.971875] Code: 24 10 48 8b 4c 24 08 48 8b 04 24 48 81 c4 70 01 00 00 9d 5d c3 cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc 48 8d 77 08 <48> 8b 3f e9 94 c5 ff ff cc cc cc cc cc cc cc cc cc cc cc cc cc cc
[ 5963.491286] frps[5573]: segfault at 0 ip 000000000046eea4 sp 00007ffc73015060 error 4 in frps[400000+728000] likely on CPU 0 (core 0, socket 0)
[ 5963.491295] Code: 24 10 48 8b 4c 24 08 48 8b 04 24 48 81 c4 70 01 00 00 9d 5d c3 cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc 48 8d 77 08 <48> 8b 3f e9 94 c5 ff ff cc cc cc cc cc cc cc cc cc cc cc cc cc cc
[ 5978.602405] frps[5583]: segfault at 0 ip 000000000046eea4 sp 00007ffd00e4b710 error 4 in frps[400000+728000] likely on CPU 0 (core 0, socket 0)
[ 5978.602414] Code: 24 10 48 8b 4c 24 08 48 8b 04 24 48 81 c4 70 01 00 00 9d 5d c3 cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc 48 8d 77 08 <48> 8b 3f e9 94 c5 ff ff cc cc cc cc cc cc cc cc cc cc cc cc cc cc

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

just frpc -h
and 
frps -h
so it does not have anything to do with configuration file.

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/releases/download/v0.52.3/frp_0.52.3_linux_amd64.tar.gz

**Comment by licanli2082** [comment]
it works now, thank you. though i am not a dev staff , i wonder what the cause is?

**Comment by xqzr** [comment]
> it works now, thank you. though i am not a dev staff , i wonder what the cause is?

Centos 是 Linux 发行版，而不是 freebsd
