### ISSUE TITLE
xtcp如何开启加密？

### ISSUE THREAD

**Issue by PHCSJC** [fatedier/frp#3807]
### Describe the feature request

文档是这样写的：自定义 TLS 协议加密，启用此功能后除 xtcp ，可以不用再设置 use_encryption 重复加密

问题是：最新版默认开启了TLS，如果不自定义证书的情况下，会使用内置自动生成的证书，此时xtcp会走加密吗？如果没有怎么开启加密呢？是用use_encryption参数吗？要在客户端和visitor都配置吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [x] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
文档的意思就是默认开启 全局 tls 后，其他都有效，但对xtcp无效，需要在代理设置加密。
我觉得应该是服务端角色和访问端角色都要设置。

**Comment by xqzr** [comment]
xtcp 默认使用 QUIC 传输
https://gofrp.org/zh-cn/docs/reference/visitor/#xtcpvisitorconfig
#3771
