### ISSUE TITLE
能否添加一个socks5的plugin?

### ISSUE THREAD

**Issue by fyhong** [fatedier/frp#381]
现在的http_proxy不支持https的网站。上不了google,youtube之类的。

**Comment by fatedier** [comment]
http proxy 支持 https，socks5 看情况 TODO。

**Comment by fyhong** [comment]
我连接了http proxy以后，打开google, youtube, tvb.com之类的Https网页，直接无法显示。

**Comment by fatedier** [comment]
https://github.com/fatedier/frp#connect-website-through-frpcs-network

看文档配置，如有问题按 issue 格式反馈 bug。

**Comment by fyhong** [comment]
配置没错。ip.cn可以上，并显示正确的ip.
所有https的网站都上不了。

**Comment by fatedier** [comment]
socks5 plugin 将在 v0.13 中支持。
