### ISSUE TITLE
.toml not working (where .ini works)

### ISSUE THREAD

**Issue by Preston2jager** [fatedier/frp#3811]
### Bug Description

I am trying to establish a private proxy for rdp from my windows tablet to my windows desktop at home, the relay is my ubuntu vps with public ip.  So frpc on 2 windows devices and frps on linux server.

I followed the full template to prepare .toml config and it passed the `frpc verify` command.

While execute standard `frpc -c frpc.toml` for both frpc clients:
- both frpc report `login to server success, get run id[xxxxxx]`
- debug level frpc log got `receive heartbeat from server` and `send heartbeat to server`
- fprs log got `clinet login info:ip [xxx]...`
- No error log at all
- **However, no proxy register info** 
- RDP connection failed

Then I created .ini configs with the same info (but of course different syntax) and the RDP is now working.

On server, the frps is started with `frps -c frps.toml` and no changes.

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

client: windows/amd64 server:Linux/amd64

### Configurations

Frpc 1:

serverAddr = "xxx"
serverPort = 7000
auth.method = "token"
auth.token = "xxx"

[[rdp]]
name = "test"
type = "stcp"
secretKey = "111"
localIp = "127.0.0.1"
localPort = 33890

Frpc 2:

serverAddr = "xxx"
serverPort = 7000
auth.method = "token"
auth.token = "xxx"

[[rdp-v]]
name = "test"
type = "stcp"
secretKey = "111"
serverName = "test"
BindAddr = "127.0.0.1"
bindPort = 1234

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
Change `[[rdp]]``[[rdp-v]]`to `[[proxies]]`.

**Comment by Preston2jager** [comment]
@superzjg Thanks, its working now.

**Comment by ylluminate** [comment]
It seems that the conversion from the .ini format to .toml is not quite as straight forward as I had believed it should be. How should an entry such as the following in the .ini format:
```
# Some HTTPS Service
[win10_workbench_servicename]
type = tcp
local_ip = 10.0.0.31
local_port = 7465
remote_port = 22283
```
Be converted to the .toml format?

I tried the following, which does not work:
```
[[proxies]]
name = "win10_workbench_servicename"
type = "tcp"
localIP = "10.0.0.31"
localPort = 7465
bindPort = 22283
```

I also tried it with "remotePort" vs "bindPort" as well with no success.

**Comment by ylluminate** [comment]
Any clarifications on the above yet? Would like to convert to toml from ini, but it seems I can't sort this out yet.
