### ISSUE TITLE
p2p下访问samba，一直访问的是本机，已做端口转发

### ISSUE THREAD

**Issue by kktt007** [fatedier/frp#3814]
### p2p下访问samba怎么正确配置 
- frp --verison 0.52.3

- 前提：已经配置过xtcp下ssh 端口转发访问被访问端，且被访问端的web端都能访问，一切正常

- 现在是需要访问文件服务器linux上安装的samba4

## 被访问端是linux:
```
serverAddr = "x.x.x.x"
serverPort = 11111
frpc.toml:
[[proxies]]
name = "samba"
type = "xtcp"
secretKey = "abcde"
localIp = "192.168.1.3"
localPort = 445
```

## 访问端是windows:
```
frpc.toml
serverAddr = "x.x.x.x"
serverPort = 11111
[[visitors]]
name = "smb_visitor"
type = "xtcp"
serverName = "smb"
secretKey = "abcde"
bindAddr = "127.0.0.1"
bindPort = 12345
```

- 然后windows下对445也做了端口转发了，用的命令是：
netsh interface portproxy add v4tov4 listenport=445 connectaddress=127.0.0.1 connectport=12345

windows下查看是以下结果：
```
Listen on ipv4:             Connect to ipv4:

Address         Port        Address         Port
--------------- ----------  --------------- ----------
*               445         127.0.0.1       12345
```

### 现在在windows文件管理中输入 \\127.0.0.1 默认定位到的是本机的共享，应该怎么设置才能xtcp远程访问到linux上的samba上面去。
1. 怎么修改配置才能正常访问到Linux下的samba
2. 如果实在不支持，有其他方案吗(ftp太古老了)

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
Windows 默认会监听
```log
tcp [::]:445
tcp 0.0.0.0:445
```
```batch
netstat -an|find "445"
```

**Comment by superzjg** [comment]
你这windows的转发445，貌似还缺少listenaddress，检查命令是不是错了。

**Comment by kktt007** [comment]
> Windows 默认会监听
> 
> ```
> tcp [::]:445
> tcp 0.0.0.0:445
> ```
> 
> ```batchfile
> netstat -an|find "445"
> ```

是啊，而且默认端口改不了，所以我才用了转发，不过我只显示这一条：tcp 0.0.0.0:445，另一条对我没影响吧

**Comment by ATKghost** [comment]
尝试一下监听127.0.0.2、127.0.0.3这些地址呢？

**Comment by RowgerGo** [comment]
大佬，你最后是怎么解决监听的
