### ISSUE TITLE
[Feature Request] URL Routing FOR HTTPS

### ISSUE THREAD

**Issue by brightcael** [fatedier/frp#3815]
### Describe the feature request

How to configure frpc service for https url routing, especially one specific domain for different url routing?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Currently unable to support in HTTPS.

**Comment by xqzr** [comment]
HTTPS 内容被加密，frp 不知道它的内容
