### ISSUE TITLE
How do I delete old records?

### ISSUE THREAD

**Issue by paolosezart** [fatedier/frp#3817]
### Bug Description

![screenshot 2023-11-29_FRPS](https://github.com/fatedier/frp/assets/38177890/f6293317-8672-41ca-abe6-61794987f947)

I have FRPS installed on ubuntu. I recently updated the port forwarding entries. I restarted FRPS on the server, but the old Web console entries remain. 
How do I get rid of them?
Maybe I need to clear the cache of FRPS entries somewhere?

### frpc Version

0.33.0

### frps Version

0.33.0

### System Architecture

Ubuntu

### Configurations

[common]
bind_port = 8000
# vhost_https_port = 443
# vhost_http_port = 80

dashboard_addr = 0.0.0.0
dashboard_port = 8500

dashboard_user = goot
dashboard_pwd = opret

log_file = ./frps.log

log_level = info

authentication_method = token

token = ploerq

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
After restarting FRPS, the records will be cleared (tested in v0.52.3)

**Comment by fatedier** [comment]
There are plans to add a button/api for cleaning offline proxies.

**Comment by paolosezart** [comment]
> After restarting FRPS, the records will be cleared (tested in v0.52.3)

Thanks, it worked. I thought it was enough to reboot only the client
