### ISSUE TITLE
[Feature Request] INI 转换到 TOML

### ISSUE THREAD

**Issue by xqzr** [fatedier/frp#3818]
### Describe the feature request

INI 格式 “一键”转换为 TOML 格式。形如：
```sh
frpc convert -c frpc.ini frpc.toml
frps convert -c frps.ini frps.toml
```
INI 已弃用，为现存用户 **方便地** 迁移到 TOML、YAML 和 JSON。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by vikii0210** [comment]
大神，照顾一下小白，这个配置，转换挺好的想法，先感谢感谢~~~

**Comment by wuai1024** [comment]
这个需要的人多吗？需要的人多 我可以做一个工具

**Comment by fatedier** [comment]
新旧配置不是完全一一对应，且 INI 仍然可以正常使用，所以目前不会做什么转换的事情，能保持兼容已经付出了比较高的成本做重构。

而且这样大概率会让很多人不仔细阅读文档，出现问题后，直接在 issue 里提很多奇奇怪怪的问题，实在没有精力跟进这一类问题。新版本中也加了配置文件的严格校验模式，来尽量避免配置错误的问题。建议需要切换格式时，通过仔细阅读和参考文档理解其中的配置编写。

此外，这个功能也不需要这个项目本身来实现，只要有一些开发能力的话应该都可以自己创建一个工具分享出来。

**Comment by vikii0210** [comment]
> 新旧配置不是完全一一对应，且 INI 仍然可以正常使用，所以目前不会做什么转换的事情，能保持兼容已经付出了比较高的成本做重构。
> 
> 而且这样大概率会让很多人不仔细阅读文档，出现问题后，直接在 issue 里提很多奇奇怪怪的问题，实在没有精力跟进这一类问题。新版本中也加了配置文件的严格校验模式，来尽量避免配置错误的问题。建议需要切换格式时，通过仔细阅读和参考文档理解其中的配置编写。
> 
> 此外，这个功能也不需要这个项目本身来实现，只要有一些开发能力的话应该都可以自己创建一个工具分享出来。

大神，理解你的意思了。 没关系，我已经根据文档全部换成新版了。 其实主要是使用惯性的问题，一些ini配置不能直接拿到toml这种格式里，主要几个点要注意

1.字符串要在前后加  ‘ ， 新版配置文件中，类似字符串变量的，如ip地址要写成   '127.0.0.1' 的格式 ，但端口还是数字不要加‘
2.常用的变量形式 有   ab_cde 要写成   abCde 的形式
3.部分变量   由   token  变成了   auth.token  的形式 
4.部分变量 修改   sk   变成了   secretKey  具体设置要注意新版文档说明
5.直接参考示例即可，  由  ini  的形式 

接收端
[rd_win]
type = stcp
sk = test1234
local_ip = 127.0.0.1
local_port = 3389

换成 toml 的

[[proxies]]
name="rd_win"
type="stcp"
secretKey="test1234"
localIp="127.0.0.1"
localPort=3389

访问端

[rdwin_visitor]
type = stcp
role = visitor
server_name = rdwin
sk = test1234
bind_addr = 127.0.0.1
bind_port = 3390

[[visitors]]
name="rdwin_visitor"
type="stcp"
serverName="rdwin"
secretKey="test1234"
bindAddr="127.0.0.1"
bindPort=3390

我在两版配置踩坑最多的就是 第一条  字符串变量遗漏 '   ，尤其是配置很多的时候很容易犯错。

请各位转换配置文件的时候注意~

**Comment by vikii0210** [comment]
> 直接关闭吧 这是什么？人家写工具给你用，你连自己看文档迁移的时间都不愿意付出？懒成这样就别用了，什么都要喂到嘴里？你知道写一个迁移配置多麻烦？就为了让你们这些伸手党一句小白，就可以一键配置文档都不用看？小白看不懂中文是吗？人家想的是怎么优化 加功能 还得给你们擦屁股？惯的

你这种垃圾除了输出负面情绪，没有任何的价值的言论，下次我直接无视。

**Comment by xqzr** [comment]
> > > 直接关闭吧 这是什么？人家写工具给你用，你连自己看文档迁移的时间都不愿意付出？懒成这样就别用了，什么都要喂到嘴里？你知道写一个迁移配置多麻烦？就为了让你们这些伸手党一句小白，就可以一键配置文档都不用看？小白看不懂中文是吗？人家想的是怎么优化 加功能 还得给你们擦屁股？惯的
> > 
> > 
> > 你这种垃圾除了输出负面情绪，没有任何的价值的言论，下次我直接无视。
> 
> 而且我可没有对着你回复
> 
那就是针对本 issue 回复了？
> 直接关闭吧 这是什么？
>
这可由不得你。如题，这是 **功能请求**。
>人家写工具给你用，你连自己看文档迁移的时间都不愿意付出？
>
不知道你从哪得出，我不愿意付出时间查阅文档。
>懒成这样就别用了，什么都要喂到嘴里？
>
这样的用户可不少 ~~，还有不会“张嘴”的呢~~
>你知道写一个迁移配置多麻烦？
>
这确实不简单，不过，如果愿意的话，这将是**动力**。
>就为了让你们这些伸手党一句小白，就可以一键配置文档都不用看？
>
如果可以“一键”配置好，且不出现问题，谁不乐意呢
>小白看不懂中文是吗？
>
如果遇到“术语”，未必能看懂。即使它是 能够理解的语言。
>人家想的是怎么优化 加功能 还得给你们擦屁股？
>
本 issue 是 **功能请求**，而非“擦屁股“。

**Comment by fatedier** [comment]
就事论事，发言没必要过于情绪化，只是各自看待问题的角度不同，互相理解。

总的来说，精力有限，就和现在各个公司降本增效一样，尽量把有限的精力分配到更有“价值”的事情上。

这里的价值衡量并不只是对用户是否友好，而是包括了需求是否广泛，是否对大多数人有价值，是否有简单的替代方案，对开发者来说，这个功能是否有技术含量，是否有挑战性，对开发者的个人能力是否有提升，亦或是本身比较有意思。

这里的衡量标准也会随着个人的生活工作状态而变化，如果这个项目能让我不需要工作就能保证日常生活水平，那可能会考虑做一些对开发者来说没什么意思和价值，但是对用户来说更友好的功能。反之亦然。

顺带一提，像之前 xtcp 代理的 P2P 彻底重构，正常来说需要比较多的开发测试时间，是很难有精力持续推进。但是因为得到了一个企业的资助，所以才会持续在这个功能上投入时间。

**Comment by geekidentity** [comment]
这事没必要吵，最基础的只转换proxy，可以直接问ChatGPT。下面供参考

写个python脚本，读取文件内容如下
[alist]
type = tcp
local_ip = 127.0.0.1
local_port = 5244
remote_port = 5244

[homeassistant]
type = tcp
local_ip = 127.0.0.1
local_port = 8123
remote_port = 8123

转成如下格式

[[proxies]]
name = "alist"
type = "tcp"
localIP = "127.0.0.1"
localPort = 5244
remotePort = 5244

[[proxies]]
name = "homeassistant"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8123
remotePort = 8123



下面是一个Python脚本，它可以读取上述格式的文件，并将其转换为指定的格式。假设原始文件名为`config.ini`，转换后的文件将保存为`converted.toml`。

```python
import re

def parse_config(filename):
    with open(filename, 'r') as file:
        content = file.read()

    # 使用正则表达式匹配节和键值对
    sections = re.findall(r'\[(.*?)\]\n(.*?)\n\n', content, re.DOTALL)
    
    proxies = []
    for section in sections:
        proxy = {'name': section[0]}
        for line in section[1].split('\n'):
            if line.strip() == '':
                continue
            key, value = line.split(' = ')
            # 将原始键转换为新格式的键
            new_key = {
                'type': 'type',
                'local_ip': 'localIP',
                'local_port': 'localPort',
                'remote_port': 'remotePort'
            }.get(key, key)
            proxy[new_key] = value
        proxies.append(proxy)
    
    return proxies

def convert_to_toml(proxies):
    toml_content = ''
    for proxy in proxies:
        toml_content += '[[proxies]]\n'
        for key, value in proxy.items():
            # 对于端口，不需要引号
            if 'Port' in key:
                toml_content += f'{key} = {value}\n'
            else:
                toml_content += f'{key} = "{value}"\n'
        toml_content += '\n'
    
    return toml_content.strip()

def main():
    input_filename = 'config.ini'
    output_filename = 'converted.toml'
    
    proxies = parse_config(input_filename)
    toml_content = convert_to_toml(proxies)
    
    with open(output_filename, 'w') as file:
        file.write(toml_content)
    
    print(f'Converted content written to {output_filename}')

if __name__ == '__main__':
    main()
```

确保将此脚本保存为`.py`文件，并且在同一目录下有一个名为`config.ini`的文件，其中包含了你提供的原始内容。运行脚本后，它将创建或覆盖名为`converted.toml`的文件，其中包含转换后的内容。
