### ISSUE TITLE
客户端与服务端版本号不一样是不是就不能连接成功

### ISSUE THREAD

**Issue by mmiluy** [fatedier/frp#382]
请问服务器端是0.9.3版本，客户端0.12版本 现在一启动客户端 客户端frpc就无限重启，是不是必须升级服务器端到0.12版本？？？

**Comment by mmiluy** [comment]
求大佬回复啊。。。。。

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/README_zh.md#开发状态
