### ISSUE TITLE
Server Dashboard behind a Web Proxy

### ISSUE THREAD

**Issue by ArminRadmueller** [fatedier/frp#3829]
### Describe the feature request

I would like to make the server dashboard easier accessible to my users and publish it behind a reverse proxy. Unfortunately, an HTTP/301 rewirte / causes the page not to work.

example config in Apache:

```
<VirtualHost *:443>
  ServerName admin.mycompany.com

  RewriteEngine On

  <Location />
    Require all granted
  </Location>

  # if reports is requested go to it as it is and skip following rules
  RewriteRule "^/connect.*" - [NC,L]

  <Location /connect >
    ProxyPass         http://192.168.1.1:7500/
    ProxyPassReverse  http://192.168.1.1:7500/
  </Location>

</VirtualHost>

```

### Describe alternatives you've considered

Is it possible to introduce a URI variable?
in this case e.g. https://admin.mycompany.com/connect

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
I don't understand Apache configuration very well, but if it's a 301 issue, I think you can directly implement this URL rewrite in the Apache configuration.
