### ISSUE TITLE
是否能支持特权模式下的指定frps监听ip地址的需求？

### ISSUE THREAD

**Issue by hotsun168** [fatedier/frp#383]
frpc 中的配置文件示例中，有 remote_port 配置项，如下：
[ssh]
type = tcp
local_ip = 218.2.2.2
local_port = 22
remote_port = 6001
测试后发现，默认监听的ip地址是根据 common 节的 server_addr 来设置的，也就是**全部统一**。
期望**只**对外网提供一个7000端口用于工作，为安全起见，其余的端口**监听于127.0.0.1或内网网卡**，使用 nginx 统一走80端口进行转发。（因有其他需求，所以无法使用frp自己的路由转发）
而将 server_addr 直接改为127.0.0.1后，7000端口又无法连通。
请问后续是否有计划支持对每一个反向代理设置**不同的 remote_ip** 的需求？

**Comment by fatedier** [comment]
不支持 remote_ip，之后会加 proxy_bind_addr 用于绑定另外的 ip 地址。

**Comment by hotsun168** [comment]
好的。多谢！
