### ISSUE TITLE
ssh连接时本地客户端报错error: dial tcp : i/o timeout

### ISSUE THREAD

**Issue by 2512036947** [fatedier/frp#3830]
### Bug Description

客户端报错
<img width="847" alt="屏幕截图 2023-12-06 213949" src="https://github.com/fatedier/frp/assets/56762048/8c58b876-d7f2-49eb-89ea-1dcf86ea8d9f">
connect to local service [XXX] error: dial tcp XXX: i/o timeout

所有都填好了
server_addr = 
server_port = 
heartbeat_timeout = 30

type = tcp
local_ip = 
local_port = 
remote_port = 

### frpc Version

0.43.0

### frps Version

0.43.0

### System Architecture

windows/amd64

### Configurations

所有都填好了
server_addr = 
server_port = 
heartbeat_timeout = 30

type = tcp
local_ip = 
local_port = 
remote_port = 

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Bitee1024** [comment]
我也是连接不上，什么防护墙安全组规则都关了的

**Comment by Fragmentszz** [comment]
> 我也是连接不上，什么防护墙安全组规则都关了的

请问解决了没  我还是解决不了
