### ISSUE TITLE
腾讯云服务器是否支持

### ISSUE THREAD

**Issue by BearIsHeavy** [fatedier/frp#3834]
### Describe the feature request

当使用腾讯云服务器时，能够成功有效的使用ssh,但是不能暴露本地的web服务。也不支持访问admin的页面.
frps配置
`bindAddr = "0.0.0.0"                                                                   
bindPort = 7001

vhostHTTPPort = 7003

# tcpmuxHTTPConnectPort = 7002

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "password"
webServer.pprofEnable = false

enablePrometheus = true

## console or real logFile path like ./frps.log
#log.to = "./frps.log"
## trace, debug, info, warn, error
#log.level = "info"
#log.maxDays = 3
## disable log colors when log.to is console, default is false
#log.disablePrintColor = false

detailedErrorsToClient = true

auth.method = "token"
auth.token = "token"
`

frpc的配置
`serverAddr = "xx.xx.xx.xx"
serverPort = 7001

#loginFailExit = true

## console or real logFile path like ./frpc.log
#log.to = "./frpc.log"
## trace, debug, info, warn, error
#log.level = "info"
#log.maxDays = 3
## disable log colors when log.to is console, default is false
#log.disablePrintColor = false

auth.method="token"
auth.token="token"

transport.protocol = "tcp"
transport.connectServerLocalIp = "0.0.0.0"

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000

[[proxies]]
name = "web"
type = "tcp"
localPort = 9487
customDomains = ["xx.xx.xx.xx"]
`
我的customDomains设置的时public ip因为我没有domain。

### Describe alternatives you've considered

但是当我使用虚拟机进行操作的时候，就可以成功访问admin页面，但是把相同的配置放置在腾讯云服务器上就不可以。我查看了一下防火墙，使用nmap进行了扫描，显示7500端口时open的，但是浏览器无法访问，并且利用curl命令进行访问也是不能成功的。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BearIsHeavy** [comment]
浏览器url我直接输入的时Public_ip:7500不知道是不是我输入的方式不对

**Comment by BearIsHeavy** [comment]
解决了忘记关闭proxy了，能够连接admin网页了，但是export web server还是不行[W] [http.go:119] do http proxy request [host: xx.xx.xx.xx:7003] error: no route found: xx.xx.xx.xx /favicon.ico

**Comment by xqzr** [comment]
```toml
type = "http"
```

**Comment by BearIsHeavy** [comment]
> ```toml
> type = "http"
> ```

是的改好就可以了，呜呜，一直没看见。感谢大佬
