### ISSUE TITLE
[Feature Request] Adding multiple ports to transmit

### ISSUE THREAD

**Issue by ycMia** [fatedier/frp#3836]
### Describe the feature request

As title, I want to add multiple ports in config file. Requesting a easier way to add them.

one suggestion is moving this kind
```
[[proxies]]
name = "AOC3_2299"
type = "udp"
localIP = "127.0.0.1"
localPort = 2299
remotePort = 2299

[[proxies]]
name = "AOC3_2300"
type = "udp"
localIP = "127.0.0.1"
localPort = 2300
remotePort = 2300
```

to this

```
[[proxies]]
name = "AOC3_Ports"
type = "udp"
localIP = "127.0.0.1"
localPort = {2299, 2230}
remotePort = {2299, 2230}
```

This will save a lot of efforts in config editing, please add that feature, thanks! 

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/blob/dev/conf/legacy/frpc_legacy_full.ini#L196-L202

**Comment by ycMia** [comment]
Thank you, the demand is fulfilled.
<3
