### ISSUE TITLE
基于ppc64le架构的平台我要下载哪个能用？[Feature Request] 

### ISSUE THREAD

**Issue by arnbunchen** [fatedier/frp#3838]
### Describe the feature request

ibm powerpc8 指令集，我要下载哪个能使用？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
可能需要自行编译
