### ISSUE TITLE
reproduct #3774 auth.token error

### ISSUE THREAD

**Issue by naY9yjoS6ZqhOd35sIFH** [fatedier/frp#3839]
### Bug Description

same screenshot

but configuration file is correct

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64 

### Configurations

```
serverAddr = " example.com"
serverPort = "12345"
token = "string" #used to typo of quota
loginFailExit = false
includes = ["./frpc-srv-meta.toml","./frpc-client-meta.toml"]
```

frpc-srv-meta.toml
```
[[proxies]]
name = "ssh-host"
type = "stcp"
secretKey = "secret"
localIP = "127.0.0.1"
localPort = 22
```
frpc-client-meta.toml
```
[[visitors]]
name = "ssh-host"
type = "stcp"
secretKey = "secret"
serverName = "ssh-host"
bindAddr = "127.0.0.1"
bindPort = 8022
```

### Logs

[same](https://github.com/fatedier/frp/issues/3774#issue-1994985558)

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
`token =" "string"` quotation mark syntax error

**Comment by naY9yjoS6ZqhOd35sIFH** [comment]
so
```
token = "string"
```
should be
```
auth.token = "string"
```

right?

**Comment by superzjg** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml#L27-L34

**Comment by naY9yjoS6ZqhOd35sIFH** [comment]
Thanks,it's my fault.
