### ISSUE TITLE
kcp使用不了啊？

### ISSUE THREAD

**Issue by zhuhangyu** [fatedier/frp#384]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.12.0

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**
cat frps.ini
[common]
bind_addr = 0.0.0.0
bind_port = 6000
kcp_bind_port = 6000

[common]
server_addr = x.x.x.x
server_port = 6000
protocol = kcp

**Steps to reproduce the issue:**
1. ./frps -c ./frps.ini 正常
2../frpc -c ./frpc.ini 几秒钟后就exit
3.

**Describe the results you received:**
显示i/o timeout

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
注释掉protocol = kcp就正常了

**Comment by fatedier** [comment]
验证下 udp 是否能正常使用，是否被防火墙阻挡了。

**Comment by zhuhangyu** [comment]
哦，确实是防火墙拒绝了udp，已经解决。谢谢。
