### ISSUE TITLE
设置域名后，mstsc远程桌面，电脑通过域名+端口无法访问，但ip+端口可正常访问

### ISSUE THREAD

**Issue by chouxiang99** [fatedier/frp#3840]
### Bug Description

我在服务器上部署了frp，然后在frps.toml中配置了subDomainHost为主域名，在windows客户端配置了subdomain = "company"，然后用mstsc远程桌面通过company+主域名+端口，无法连接成功，但通过ip+端口，可以正常访问，我ping了一下company.主域名也是可以正常解析到对应的ip，所以想来问问各位大佬  可能是什么原因  找了好久没有找到原因

### frpc Version

frp_0.52.3_windows_amd64

### frps Version

frp_0.52.3_linux_amd64

### System Architecture

linux/amd64, windows/amd64

### Configurations

frps.toml：
bindPort = 36224
auth.token = "zx946894"
subDomainHost = "xxxxx.top"

frpc.toml
serverAddr = "xx.xx.xx.xxx"
serverPort = 36224
auth.token = "zx946894"

[[proxies]]
name = "company"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3389
remotePort = 6002
subdomain = "company"

### Logs

mac通过rd连接windwos时候，提示：
Your session ended because of an error. If this keeps happening, contact your network administrator for assistance.
Error code: 0x4

windows通过mstsc连接时候，可以正常输入密码，最后一步连接失败

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by chouxiang99** [comment]
终于找到了原因，域名没有备案导致无法连接成功，如果有遇到相同问题的问，希望可以你们提供参考

**Comment by fsleo** [comment]
感谢，我也遇到这个问题。我是mac　连，设置了hosts，自己乱定了一个域名，比如：al.dev 指向我的服务器，结果不行，研究了半天，直到看到你的这个，我用IP，就行了

**Comment by fsleo** [comment]
感谢，我也遇到这个问题。我是mac在本机设置了hosts，自己乱定了一个域名，比如：al.dev 指向我的服务器，而且发现ssh是没有问题的，但是rdp结果不行，研究了半天，直到看到你的这个，rdp 要用ip连接才行。
