### ISSUE TITLE
纯命令行选项没有tcp中的（plugin）插件功能

### ISSUE THREAD

**Issue by Do0x-Ccc** [fatedier/frp#3846]
### Describe the feature request

例如unix_domain_socket, http_proxy, socks5, static_file, http2https, https2http, https2https，使用命令行 frp tcp ... 等，无法使用这些插件，希望可以添加

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
命令行一般不方便表达复杂的配置结构，所以不会支持所有的配置参数，复杂能力建议通过配置文件启动。
