### ISSUE TITLE
[Feature Request] 有没有frps配置文件生成的网站，看文档不会配

### ISSUE THREAD

**Issue by Xiao-yux** [fatedier/frp#3847]
### Describe the feature request

frps和frpc的配置文件生成，
![image](https://github.com/fatedier/frp/assets/79674967/f6a84ef0-b321-4bdd-9257-608046a17c71)
![image](https://github.com/fatedier/frp/assets/79674967/c8e46782-cd6b-4c0e-81b1-857728c14ae9)

有没有人帮我看看错误，顺便帮我改改发给我

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by yufin** [comment]
+1

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frps_full_example.toml
https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml

**Comment by Xiao-yux** [comment]
> https://github.com/fatedier/frp/blob/dev/conf/frps_full_example.toml https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml

谢了

**Comment by Xiao-yux** [comment]
> https://github.com/fatedier/frp/blob/dev/conf/frps_full_example.toml https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml

![image](https://github.com/fatedier/frp/assets/79674967/e3abed92-797e-44df-8fda-21c2e37f214b)
![image](https://github.com/fatedier/frp/assets/79674967/956ab6d9-8526-49a5-839e-5ec1d4e6eb82)
还是这个报错
