### ISSUE TITLE
[Feature Request] Hide FRPC Client Real IP Address because Rate Limit in DIP

### ISSUE THREAD

**Issue by ashkan-moghadasi** [fatedier/frp#3849]
### Describe the feature request

Because DIP has a rate limit on the ip address of some data centers. We need a feature to hide our external server IP address from DIP Perspective.

In reverse proxy mode when frpc client connects to frp server and its IP address belongs to hetzner or digital occasion. DIP will have a rate limit in this connection. Traffic between client and server transfer with a limited speed.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
I don't think we can achieve this capability.

**Comment by yuzhoua** [comment]
Is there a solution to this problem now?
