### ISSUE TITLE
为啥xtcp的连接需要frps不中断

### ISSUE THREAD

**Issue by mlkt** [fatedier/frp#3853]
试了下xtcp，确实打洞成功连上了，但我发现一结束中转服务器上的 frps 进程后点对点连接立刻中断，既然已经点对点成功了，为什么还需要frps呢？如果是为了保活，那也应该是结束 frps 进程后过一段时间连接才中断。是frpc做了什么额外操作，当和frps的连接中断后就立刻自己中断点对点连接的吗？这是出于什么考虑吗？

还有一个问题，打洞是否必须使用udp，如果frpc使用了HTTP代理，所有流量是否都会经过这个代理？如果是socks5代理呢？

**Comment by fatedier** [comment]
目前的架构并不只是为 p2p 通信而设计，整体上是客户端服务端的架构，客户端需要和服务端保持通信，一旦通信中断，就认为整体不可用，会释放之前的资源进行重连。

**Comment by mlkt** [comment]
OK，感谢解答，感谢开发了这么棒的工具

**Comment by xqzr** [comment]
打洞通常需要 UDP 等 无状态协议
