### ISSUE TITLE
[Feature Request] multiple token settings?

### ISSUE THREAD

**Issue by zhaobingxiang** [fatedier/frp#3855]
### Describe the feature request

When does it support multiple token settings? When a token is leaked, modifying it will cause all clients to be unable to access it

### Describe alternatives you've considered

Allow multiple token settings, FRPS can set multiple tokens, such as token1="", token2="", FRPC connection only needs to connect any token。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [x] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Try plugins: https://github.com/gofrp/plugin
