### ISSUE TITLE
connect to server error: dial tcp 0.0.0.0:7000: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by wo4wangle** [fatedier/frp#3856]
### Bug Description

Addr is "117.13.194.95", why connect with 0.0.0.0? what's the issue
"telnet 117.13.194.95 7000" can connect to target in client.

### frpc Version

0.53.0

### frps Version

0.53.0

### System Architecture

windows/amd64

#### client
C:\portableApp\frp_0.53.0_windows_amd64>type frpc.toml
Addr = "117.13.194.95"
serverPort = 7000

[[proxies]]
name = "rdp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3389
remotePort = 6000
#### server
[root@VM-16-13-opencloudos frp_0.53.0_linux_amd64]# cat frps.toml
bindPort = 7000

#### client
C:\portableApp\frp_0.53.0_windows_amd64>frpc.exe -c frpc.toml
2023/12/18 01:50:05 [I] [root.go:141] start frpc service for config file [frpc.toml]
2023/12/18 01:50:05 [I] [service.go:288] try to connect to server...
2023/12/18 01:50:07 [W] [service.go:291] connect to server error: dial tcp 0.0.0.0:7000: connectex: No connection could be made because the target machine actively refused it.
2023/12/18 01:50:07 [I] [service.go:288] try to connect to server...
2023/12/18 01:50:07 [W] [service.go:291] connect to server error: dial tcp 0.0.0.0:7000: operation was canceled
2023/12/18 01:50:07 [I] [root.go:159] frpc service for config file [frpc.toml] stopped
login to the server failed: dial tcp 0.0.0.0:7000: connectex: No connection could be made because the target machine actively refused it.. With loginFailExit enabled, no additional retries will be attempted

#### server
[root@VM-16-13-opencloudos frp_0.53.0_linux_amd64]# ps -ef |grep -in frp
97:root     2175042       1  0 01:16 ?        00:00:00 ./frps -c frps.toml
[root@VM-16-13-opencloudos frp_0.53.0_linux_amd64]# cat nohup.out
2023/12/18 01:16:39 [I] [root.go:104] frps uses config file: frps.toml
2023/12/18 01:16:39 [I] [service.go:225] frps tcp listen on 0.0.0.0:7000
2023/12/18 01:16:39 [I] [root.go:113] frps started successfully

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml#L9

**Comment by wo4wangle** [comment]
> https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml#L9

It works, thank you

**Comment by mustafaguven** [comment]
> > https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml#L9
> 
> It works, thank you

how did you solve the problem? I could not understand what you did

**Comment by anthony-dl** [comment]
I'm having the same problem. I've looked at these configurations files but I havent been able resolve it. Please help me if you know it. Basically the frps is hosted on a server with a public IP, which I can only ssh into with a ssh -i ssh_key username@public_ip (exactly like how you would do with AWS). Here's my config file

<img width="304" alt="image" src="https://github.com/fatedier/frp/assets/63137043/ba8d6486-49f6-4e44-bb5e-13166fd7fbef">
![image](https://github.com/fatedier/frp/assets/63137043/a6e8682b-197b-47a9-81e8-a9bfd18b9eb2)

**Comment by darld** [comment]
> I'm having the same problem. I've looked at these configurations files but I havent been able resolve it. Please help me if you know it. Basically the frps is hosted on a server with a public IP, which I can only ssh into with a ssh -i ssh_key username@public_ip (exactly like how you would do with AWS). Here's my config file
> 
> <img alt="image" width="304" src="https://private-user-images.githubusercontent.com/63137043/312566657-ba8d6486-49f6-4e44-bb5e-13166fd7fbef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTI1MTksIm5iZiI6MTcxNDExMjIxOSwicGF0aCI6Ii82MzEzNzA0My8zMTI1NjY2NTctYmE4ZDY0ODYtNDlmNi00ZTQ0LWJiNWUtMTMxNjZmZDdmYmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA2MTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNGU2ZThmMjIzNTlkMzEyNzZmM2VjMjUwODI0YWNjNWJmMzg2ZTYwMTJlMmZhYjBiMzNmMTUxNmU3ZTdkODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0vEw-SaZ0lXwQuo3uQAa6QyV9ZSshFtug43EvJnQMSw">
> ![image](https://private-user-images.githubusercontent.com/63137043/312567820-a6e8682b-197b-47a9-81e8-a9bfd18b9eb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTI1MTksIm5iZiI6MTcxNDExMjIxOSwicGF0aCI6Ii82MzEzNzA0My8zMTI1Njc4MjAtYTZlODY4MmItMTk3Yi00N2E5LTgxZTgtYTliZmQxOGI5ZWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA2MTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNjc1NWIwN2IzMzg4ZjI3MDJmZjA4MWU5ZGQwNzU5MDJkMDc0ZDlkNmU1ZTgxZmY5MzZmM2UxOTVjNDYyOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yzqEnnurVG4q3WPhkqp4SuxOgOMfjpW0U0ykkK2q4VI)

Possible aws block frps?

**Comment by anthony-dl** [comment]
Hi @darld , I've able to solve the problem. Thanks

**Comment by darld** [comment]
> Hi @darld , I've able to solve the problem. Thanks

I able to connect now as I need to change the 7000 port from ipv6 to ipv4 in the Aws ec2 instance security. But even connected, but my port of local server still unable to exposed to public internet.

**Comment by katoue** [comment]
> Hi @darld , I've able to solve the problem. Thanks

Could you please provide the method for resolving this issue?
