### ISSUE TITLE
[Feature Request] frpc的webGui configure页面的配置内容能增加语法高亮吗?

### ISSUE THREAD

**Issue by DecSgr01** [fatedier/frp#3858]
### Describe the feature request

frpc的webGui configure页面的配置内容增加语法高亮

为了方便新手上手以及用户维护,可以给配置内容加上语法高亮

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
静态资源是会被编译进二进制文件中，不会引入过多复杂的功能。
