### ISSUE TITLE
解组 JSON 时出错：解码 JSON：json：无法将字符串解组为 v1.ClientConfig 类型的 Go 值

### ISSUE THREAD

**Issue by stubborn-fk** [fatedier/frp#3859]
### Bug Description

win11 windows frpc客户端运行frpc.exe指定配置文件后报错：E:\brouser_download\frp_0.53.0_windows_amd64>frpc.exe -c frpc.toml
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1.ClientConfig
toml配置文件内容如下
<img width="227" alt="image" src="https://github.com/fatedier/frp/assets/98369312/08d4550b-fa2f-41cb-9b1a-cbdfb3aef548">

### frpc Version

0.53.0

### frps Version

0.53.0

### System Architecture

windows/amd64

### Configurations

<img width="227" alt="image" src="https://github.com/fatedier/frp/assets/98369312/a550d655-63be-4023-b080-d67907f2e57b">

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
注意键值对的格式，tcp示例：https://gofrp.org/zh-cn/docs/examples/ssh/

**Comment by zhaobingxiang** [comment]
解决了么，我这也是同样的问题

**Comment by zhaobingxiang** [comment]
arm环境，目前amd环境测试没啥问题，出问题的就是arm环境

**Comment by maston2** [comment]
我也是，不知道是不是Toml格式才能行？两个中括号？

```
serverAddr = "x.x.x.x"
serverPort = 7000

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000
```

**Comment by huangluyu** [comment]
Same problem happend in 0.53.2. My config works on other windows, but not works on special one.

**Comment by huangluyu** [comment]
> Same problem happend in 0.53.2. My config works on other windows, but not works on special one.

我的问题是由于 windows 和 linux 的换行符不一致而导致的，windows 自带的记事本不容易发现这个问题，我使用其他文本编辑器才发现。
