### ISSUE TITLE
[Question] Can I forward all ports except some?

### ISSUE THREAD

**Issue by TiberiumN** [fatedier/frp#386]
Hi! Thanks for your program!
I have a question - can I forward all ports from a server with public IP to server with NAT?
For example:
myserver:25565  would point to myclient:25565 (which is behind NAT)
and so on for EVERY port except 22 (so myserver:22 would still point to myserver:22)
Can this be done with frp?

**Comment by TiberiumN** [comment]
TL;DR:
How to expose all ports except port 22?

**Comment by fatedier** [comment]
What's your real need is VPN?

Now frp can only expose one port in one tunnel. You may export all ports you want by creating many tunnels although it's not a good idea.

**Comment by TiberiumN** [comment]
@fatedier hmm, VPN?
is there any tutorials on the internet?

**Comment by fatedier** [comment]
https://en.wikipedia.org/wiki/Virtual_private_network

https://openvpn.net/index.php/open-source/downloads.html
