### ISSUE TITLE
FRPC disconnect after running 1 day

### ISSUE THREAD

**Issue by ellionsh** [fatedier/frp#3863]
### Bug Description

Start FRPC and tried to use it after 1 day. It was disconnected. Cannot find frpc process in the system. It seems that that frpc process exited.

### frpc Version

0.53.0

### frps Version

0.53.0

### System Architecture

linux/amd64

### Configurations

[[proxies]]
name = "ssh"
type = "tcpmux"
multiplexer = "httpconnect"
customDomains = ["xxxxxxx"]
localIP = "127.0.0.1"
localPort = 22

### Logs

2023/12/19 06:52:37 [I] [root.go:141] start frpc service for config file [/etc/frp/frpc.toml]
2023/12/19 06:52:37 [I] [service.go:288] try to connect to server...
2023/12/19 06:52:40 [I] [service.go:279] [095c930438596037] login to server success, get run id [095c930438596037]
2023/12/19 06:52:40 [I] [proxy_manager.go:173] [095c930438596037] proxy added: [ssh]
2023/12/19 06:52:40 [I] [service.go:288] [095c930438596037] try to connect to server...
2023/12/19 06:52:41 [I] [service.go:279] [095c930438596037] login to server success, get run id [095c930438596037]
2023/12/19 06:52:41 [I] [proxy_manager.go:173] [095c930438596037] proxy added: [ssh]
2023/12/19 06:52:41 [I] [panic.go:914] frpc service for config file [/etc/frp/frpc.toml] stopped
2023/12/19 06:52:46 [I] [root.go:141] start frpc service for config file [/etc/frp/frpc.toml]
2023/12/19 06:52:46 [I] [service.go:288] try to connect to server...
2023/12/19 06:52:50 [I] [service.go:279] [bbeb6eb85625258b] login to server success, get run id [bbeb6eb85625258b]
2023/12/19 06:52:50 [I] [proxy_manager.go:173] [bbeb6eb85625258b] proxy added: [ssh]
2023/12/19 06:52:50 [I] [service.go:288] [bbeb6eb85625258b] try to connect to server...
2023/12/19 06:52:51 [I] [control.go:169] [bbeb6eb85625258b] [ssh] start proxy success
2023/12/19 06:52:51 [I] [service.go:279] [bbeb6eb85625258b] login to server success, get run id [bbeb6eb85625258b]
2023/12/19 06:52:51 [I] [proxy_manager.go:173] [bbeb6eb85625258b] proxy added: [ssh]
2023/12/19 06:52:51 [I] [panic.go:914] frpc service for config file [/etc/frp/frpc.toml] stopped

### Steps to reproduce

1. Start frpc
2. Try to use it after 1 day
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
尝试最新版
