### ISSUE TITLE
请教一下json怎么写

### ISSUE THREAD

**Issue by superen7527** [fatedier/frp#3867]
### Describe the feature request

看了一下文档和文件，没找到json示例。不是说支持json吗。我想看看同名key你们是怎么处理的。还是说和toml一样的配置？只是改文件名后缀。。

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
几种主流格式之间 可互转，可以在线搜索 相关工具
