### ISSUE TITLE
FRPC

### ISSUE THREAD

**Issue by shagunkam** [fatedier/frp#3872]
### Describe the feature request

i  generated a random port through a randiant function (23456) when i run frpc i set ip and port through socks i set port and socks proxy in proxy setting by using frpc when i run this the socks ip and proxy set in proxy setting but the internet stops working!!but i want that the internet should wokring i set token and all at server side 

this is my configuration file:
[common]
    server_addr = "X.X.X.X.X"  
    server_port = 7000
    auth_token = "X.X.X.X"       

    [ssh_proxy]
    type = "tcp"
    local_ip = "127.0.0.1"
    local_port = 443
    remote_port = 23456
    use_encryption = true
    use_compression = true
    privilege_key = Accf8c0FTuUW
    custom_username = GRYF56D

    [http_proxy]
    type = "http"
    local_ip = "127.0.0.1"
    local_port = 80

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by eebssk1** [comment]
Pls clarify your question. If english isn't your native lang then pls atleast use a translator.

Restart frpc will interrupt all handled connections. You can use rpc to hot reload the config without restarting.
