### ISSUE TITLE
进程运行30个小时左右会退出 WIN7

### ISSUE THREAD

**Issue by stillywud** [fatedier/frp#388]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
使用的版本为frp_0.11.0_windows_amd64

**What operating system and processor architecture are you using (`go env`)?**
WIN7 X64 

**Configures you used:**

**Steps to reproduce the issue:**
故障重现有点困难，但是遇到过两次，进程无故退出
1.
2.
3.

**Describe the results you received:**
没有反馈，日志中未看到异常
frps.log如下
2017/06/29 20:17:46 [I] [proxy.go:76] [e5d3f43329e860d8] [shiwu.hunan_svn] get a new work connection: [118.249.102.157:38080]
2017/06/29 20:45:50 [I] [proxy.go:76] [e5d3f43329e860d8] [shiwu.hunan_svn] get a new work connection: [118.249.102.157:38080]
2017/06/29 20:45:51 [I] [proxy.go:76] [e5d3f43329e860d8] [shiwu.hunan_svn] get a new work connection: [118.249.102.157:38080]
2017/07/03 09:56:36 [I] [service.go:114] Dashboard listen on 0.0.0.0:7515
2017/07/03 09:56:36 [I] [main.go:112] Start frps success
2017/07/03 09:56:36 [I] [main.go:114] PrivilegeMode is enabled, you should pay more attention to security issues

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
无预兆的，大概运行24到30个小时左右会出现问题

**Can you point out what caused this issue (optional)**

**Comment by zhfish** [comment]
目前我是24小时重启。。

**Comment by fatedier** [comment]
1. 程序不会重启，只会退出，确认是否是其他程序控制。
2. 异常退出需要提供 panic 日志，通常在标准输出中打印。
