### ISSUE TITLE
[Feature Request] dae + juicity for enhanced performance option?

### ISSUE THREAD

**Issue by ylluminate** [fatedier/frp#3883]
### Describe the feature request

Possible new target tooling to support with improved performance [dae](https://github.com/daeuniverse/dae?tab=readme-ov-file) ([benchmarks](https://docs.google.com/spreadsheets/d/1UaWU6nNho7edBNjNqC8dfGXLlW0-cm84MM7sH6Gp7UE/edit#gid=1965963111)) + [juicity](https://github.com/juicity/juicity): https://qyz.one/high-performance-transparent-proxy-with-dae-juicity

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
frp does not support transparent proxy mode.

**Comment by ylluminate** [comment]
I'll close the issue then, but it seems worth keeping in mind in case the landscape changes.
