### ISSUE TITLE
transport.poolCount: unknown field

### ISSUE THREAD

**Issue by ylluminate** [fatedier/frp#3884]
### Bug Description

When including the `transport.poolCount` field (eg, `transport.poolCount = 1`) in the config, such as a TOML config file, it results in an error now:
```
$ ./frps --strict_config --config frps.toml
json: unknown field "poolCount"
```

### frpc Version

0.53.2

### frps Version

0.53.2

### System Architecture

linux/amd64

### Configurations

```
# Pool count in each proxy will keep no more than maxPoolCount.
transport.maxPoolCount = 5
transport.poolCount = 1
```

### Steps to reproduce

Simply insert into config and execute test via `--strict_config`.

### Affected area

- [X] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
`poolCount` 只存在于 frpc

**Comment by ylluminate** [comment]
> `poolCount` Present only in FRPC

Gotcha, thanks. It was easy to flip the `transport.poolCount = 5` in frpc.ini vs `transport.maxPoolCount = 5` in frps.ini when reviewing the changes.
