### ISSUE TITLE
请问服务器插件有没有WorkConnClose事件

### ISSUE THREAD

**Issue by eauxxs** [fatedier/frp#3888]
### Describe the feature request

如题

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
文档没有
https://gofrp.org/zh-cn/docs/features/common/server-plugin/#%E6%93%8D%E4%BD%9C%E7%B1%BB%E5%9E%8B
