### ISSUE TITLE
FEATURE REQUEST Can plugin: http_proxy Support  local_ip config?

### ISSUE THREAD

**Issue by paulownia99** [fatedier/frp#389]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc 0.12

**What operating system and processor architecture are you using (`go env`)?**
win10

**Configures you used:**

**Steps to reproduce the issue:**
1.frpc.ini中普通tcp连接支持配置local_ip ,这样可以在局域网任何一台外网机甚至路由器中用frpc配置对目标机器的访问，比如3389.
2.but local_ip  and  local_port  is useless for plugin.

**Describe the results you received:**
but local_ip  and  local_port  is useless for plugin，即使配置了，走的还是开frpc的机器。

**Describe the results you expected:**
希望plugin也可以支持配置local_ip。这样即使内网需要inode或web认证，也可以在lan内没有办法完成认证的机器或路由器上开frpc了。

**Additional information you deem important (e.g. issue happens only occasionally):**
当内网需要inode客户端或web认证，路由器无法完成认证。

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
没理解你的问题是什么，plugin 是内置的处理连接数据的程序，不需要 ip 和 port。

如果只是需要暴露内网的一个已经存在的 http proxy，使用 tcp 的方式即可。
