### ISSUE TITLE
使用新版toml格式的配置文件时非常困惑的一点，官方文档提供的配置参考无法使用

### ISSUE THREAD

**Issue by ZimaBlueee** [fatedier/frp#3890]
### Describe the feature request

我在[官网](https://gofrp.org/zh-cn/docs/reference/client-configures/)查询到token的配置如下图
![image](https://github.com/fatedier/frp/assets/53747502/a1ce353f-8d53-4745-890a-564b290637b1)

但实际上，配置文件需要的是：
`auth.token = "xxx"`
而不是：
`token = "xxx"`

这让我很困扰，不止我举的这个例子，其他配置也有同样的问题：往新版toml格式的配置文件上转换时，参照官网的配置是不行的，只能从issue里翻答案。

请教下，哪里有新版格式（toml，yaml）的标准配置案例可供参考呢？还是我找错地方了呢？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
#3847

**Comment by ZimaBlueee** [comment]
> #3847

感谢感谢！

**Comment by superzjg** [comment]
实际上是排版的问题，并不是文档错误，不仔细看容易搞错。比如你说的 token 是有上级 auth 的 ：
https://gofrp.org/zh-cn/docs/reference/server-configures/#serverconfig

**Comment by udbyygyt** [comment]
查了半天，真的是这配置太奇怪 

感谢感谢！
