### ISSUE TITLE
[Feature Request] 功能建议: 让控制端client决定受控端client的target和port

### ISSUE THREAD

**Issue by strugglesharp** [fatedier/frp#3891]
### Describe the feature request

先描述一下场景
P: 公网服务器 1.1.1.1,  , **公网只能1个Port**,  运行 frps
D: 穿透的目标端,内网 192.168.0.50  ,  运行一个frpc 
S:  穿透的发起方,内网 10.0.0.30,  运行一个frpc
P/D/S 都是上网不受限制的, 走STCP,   S网络不允许使用全局的sock5代理tcp

 D上想加一个 127.0.0.1:3389, 
 现在就得先在D上配置里先配置一通. 然后再在S上配置一通.  如果想再临时加几个呢/再改几个呢?
 比较麻烦的是, 我常在S上, 本身D就在一个访问不方便的地方,  老动D非常痛苦
 
 我希望有个功能,   然后要开什么 IP/PORT组合, 直接在S上设好,  D上就直接同步接受就好了.  安全什么的我靠auth.token = "abc"就足够了.

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
可以尝试使用 UI
https://gofrp.org/zh-cn/docs/features/common/ui/#%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%AE%A1%E7%90%86%E7%95%8C%E9%9D%A2
或许可以 调用它的 API，自动化 这一切

**Comment by strugglesharp** [comment]
> 可以尝试使用 UI https://gofrp.org/zh-cn/docs/features/common/ui/#%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%AE%A1%E7%90%86%E7%95%8C%E9%9D%A2 或许可以 调用它的 API，自动化 这一切
但我公网服务端口只有1个。给力client ui 就没有口给server的port了。

**Comment by xqzr** [comment]
> > 可以尝试使用 UI https://gofrp.org/zh-cn/docs/features/common/ui/#%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%AE%A1%E7%90%86%E7%95%8C%E9%9D%A2 或许可以 调用它的 API，自动化 这一切
> 
> 但我公网服务端口只有1个。给了client ui 就没有口给server的port了。

你可以 stcp 它
