### ISSUE TITLE
[Feature Request] 请问，是否有接口文档？

### ISSUE THREAD

**Issue by quliting** [fatedier/frp#3892]
### Describe the feature request

例如：
1：获取Token的接口；
2：新增客户端的接口。。。
3：。。。

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://gofrp.org/zh-cn/docs/features/common/server-plugin/
https://gofrp.org/zh-cn/docs/features/common/ui/#%E6%9C%8D%E5%8A%A1%E7%AB%AF-dashboard

**Comment by quliting** [comment]
感谢，我知道这个web；
那我是通过他的NetWork来调接口？

**Comment by xqzr** [comment]
```
/api/serverinfo
/api/proxy/tcp
...
```
