### ISSUE TITLE
[Feature Request] 感觉中文文档描述配置参数，容易让新手出错。

### ISSUE THREAD

**Issue by superzjg** [fatedier/frp#3894]
### Describe the feature request

希望 写清楚 参数的 上级 和 下级。现在排版看上去，新手容易忽略上级。
例如：https://github.com/fatedier/frp/issues/3890
就是忽略了  token 是有上级 auth 的 。
上次在其他网站也有人提到类似问题。

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://gofrp.org/zh-cn/docs/reference/server-configures/
这个描述的清楚吗

**Comment by superzjg** [comment]
> https://gofrp.org/zh-cn/docs/reference/server-configures/ 这个描述的清楚吗，如果还无法理解，建议去其他论坛之类的地方寻求帮助吧

我个人完全没问题，在其他论坛我都是帮别人（新手）解释。
现在发文档链接，我都不发这个中文文档链接了，发出来，他们很多不添加上级，写参数出错，然后不停的追问。
现在改发这个frpc_full_example.toml了：
https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml
反而都说能看明白。

**Comment by fatedier** [comment]
那没问题，所以我上面也说了论坛更适合没有任何基础的用户，互相之间讨论，寻求帮助，不会把问题都堆积到一个人身上。Github 面向的主要不是什么都不懂，想要点开一个软件直接用的用户，对于类似的 issue 基本上也不会回复。

当前的格式基本上是很常见的云原生项目里的 Reference 格式，不太会为了几乎不看文档的人再去特意做什么调整。

很多人只是惯性，不习惯自己尝试解决问题，习惯了有问题直接寻求他人帮助。作为开发者也不是保姆，一定要把饭喂到嘴里。
https://gofrp.org/zh-cn/docs/features/common/authentication/
提问之间能够先看一看文档的话，也算是一种对开发者的尊重吧，有的 issue 也不会存在了。
