### ISSUE TITLE
内网web，外面访问，被127.0.0.1后面加端口0，导致访问失败

### ISSUE THREAD

**Issue by zouzhe1** [fatedier/frp#3902]
### Bug Description

客户端：
```
[[proxies]]
name = "nas"
type = "http"
local_port = 5000
subdomain= "nas"
```

服务端：
```
bindPort = 9001
vhostHTTPPort = 9002
subDomainHost = "xxx.com"
```

客户端log
`[E] [proxy.go:204] [858dabc00abfd261] [nas] connect to local service [127.0.0.1:0] error: dial tcp 127.0.0.1:0: connect: connection refused`

服务端log
` [W] [http.go:119] do http proxy request [host: nas.xxx.com:9002] error: EOF`

### frpc Version

0.53.2

### frps Version

0.53.2

### System Architecture

linux/amd64

### Configurations

内网web，外面访问，被127.0.0.1后面加端口0，导致访问失败

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
仔细看示例（本地端口有误）：
https://gofrp.org/zh-cn/docs/examples/vhost-http/
