### ISSUE TITLE
Get real ip in 'ssh service' by 'frpc'

### ISSUE THREAD

**Issue by youhuiji** [fatedier/frp#3903]
### Bug Description

What should I do to get the real ip via frpc, because I see log files of people trying to burst my ssh service, but luckily I have authorized_key logon turned on and password verification turned off. I want to get the real ip and then automatically blacklist these illegal ip.
So how do I do this?

### frpc Version

0.48

### frps Version

0.48

### System Architecture

linux/amd64

### Configurations

Get real ip in 'ssh service' by 'frpc'

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
https://gofrp.org/zh-cn/docs/features/common/realip/

**Comment by alex-ibb** [comment]
@superzjg 
According to the link, i tried the proxy config block below:
```bash
[[proxies]]
name = "ssh-aws-us-to-asus"
type = "tcp"
# 
localIP = "127.0.0.1"
localPort = 22
# 
remotePort = 18810
# 
transport.useEncryption = true
# 
transport.useCompression = true
# Forward Real IP to local
transport.proxyProtocolVersion = "v2"
```

The last line leads to the errors below when trying to connect the proxy:
```bash
# Via MobaXTerm
Incoming packet was garbled on decryption

# Via CMD on Windows
Bad packet length 1231976033.
ssh_dispatch_run_fatal: Connection to 43.134.111.111 port 18810: message authentication code incorrect
```

Could you please provide some advises on this ?

**Comment by superzjg** [comment]
> @superzjg According to the link, i tried the proxy config block below:
> 
> ```shell
> [[proxies]]
> name = "ssh-aws-us-to-asus"
> type = "tcp"
> # 
> localIP = "127.0.0.1"
> localPort = 22
> # 
> remotePort = 18810
> # 
> transport.useEncryption = true
> # 
> transport.useCompression = true
> # Forward Real IP to local
> transport.proxyProtocolVersion = "v2"
> ```
> 
> The last line leads to the errors below when trying to connect the proxy:
> 
> ```shell
> # Via MobaXTerm
> Incoming packet was garbled on decryption
> 
> # Via CMD on Windows
> Bad packet length 1231976033.
> ssh_dispatch_run_fatal: Connection to 43.134.111.111 port 18810: message authentication code incorrect
> ```
> 
> Could you please provide some advises on this ?

Local services are required to support the Proxy Protocol protocol, such as nginx.

**Comment by xZinio** [comment]
So is there no way to make this work?
