### ISSUE TITLE
使用url路由功能,路由地址也会被转发.

### ISSUE THREAD

**Issue by zldaysleepy** [fatedier/frp#3905]
### Bug Description

我在win10上使用客户端
***
[[proxies]]
name = "web1"
type = "http"
localIP = "127.0.0.1"
localPort = 8092
remotePort = 9000
customDomains = ["xxxxxxx.com"]
locations = ["/user"]
***
访问 xxxxxxx.com:9000/user 转发到本地服务上的结果是 127.0.0.1:8092/user
想请问一下有没有一种配置在使用路由功能的时候,路由不转发 即访问xxxxxxx.com:9000/user转发到127.0.0.1:8092

### frpc Version

frp_0.53.2

### frps Version

frp_0.53.2

### System Architecture

windows/amd64

### Configurations

[[proxies]]
name = "web1"
type = "http"
localIP = "127.0.0.1"
localPort = 8092
remotePort = 9000
customDomains = ["xxxxxxx.com"]
locations = ["/user"]

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
似乎 未实现，但可以修改 请求头
https://gofrp.org/zh-cn/docs/reference/proxy/#httpproxyconfig

**Comment by zldaysleepy** [comment]
> 似乎 未实现，但可以修改 请求头 https://gofrp.org/zh-cn/docs/reference/proxy/#httpproxyconfig

我目前采用的方案是使用tcp,路由功能如果客户端是服务器就很友好(因为我不太可能在win上搭建一个nginx)
