### ISSUE TITLE
[Feature Request] 请问服务端的地址如果为域名，是否支持服务端DDNS动态域名配置？

### ISSUE THREAD

**Issue by fraee** [fatedier/frp#3908]
### Describe the feature request

感谢FRP所有的开发者们，请教个问题：

这是我的frpc.toml
```
serverAddr = "frp.example.com"
serverPort = 7000

[[proxies]]
name = "client-a"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 10022
```

如果frp.example.com通过DDNS动态配置ip地址，那么已连接的client-a是否支持动态切换服务端的ip地址？

目前我的测试是无法切换到新的ip地址，也没有找到相关说明，不知道是不支持还是我的配置有问题，感谢解答，祝新年快乐！

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
动态ip更换时，域名解析需要数分钟生效，在这个空隙连不上，一旦解析生效就会连上。

**Comment by fraee** [comment]
> 动态ip更换时，域名解析需要数分钟生效，在这个空隙连不上，一旦解析生效就会连上。 你最好全局加一个 `loginFailExit = false`

感谢回答
我测试将域名指向了一个无效的ip地址   但是现在frps dashboard还是显示客户端正在连接   是缓存还是？loginFailExit字面意思是说 如果不加这个选项  在客户端连接失败后会自动退出？

**Comment by superzjg** [comment]
> > 动态ip更换时，域名解析需要数分钟生效，在这个空隙连不上，一旦解析生效就会连上。 你最好全局加一个 `loginFailExit = false`
> 
> 感谢回答 我测试将域名指向了一个无效的ip地址 但是现在frps dashboard还是显示客户端正在连接 是缓存还是？loginFailExit字面意思是说 如果不加这个选项 在客户端连接失败后会自动退出？

是的

**Comment by fraee** [comment]
> > > 动态ip更换时，域名解析需要数分钟生效，在这个空隙连不上，一旦解析生效就会连上。 你最好全局加一个 `loginFailExit = false`
> > 
> > 
> > 感谢回答 我测试将域名指向了一个无效的ip地址 但是现在frps dashboard还是显示客户端正在连接 是缓存还是？loginFailExit字面意思是说 如果不加这个选项 在客户端连接失败后会自动退出？
> 
> 是的

感谢，将域名指向了一个无效的ip地址 frps dashboard依然显示客户端正在连接  是否属于一个bug？

**Comment by xqzr** [comment]
> > > > 动态ip更换时，域名解析需要数分钟生效，在这个空隙连不上，一旦解析生效就会连上。 你最好全局加一个 `loginFailExit = false`
> > > 
> > > 
> > > 感谢回答 我测试将域名指向了一个无效的ip地址 但是现在frps dashboard还是显示客户端正在连接 是缓存还是？loginFailExit字面意思是说 如果不加这个选项 在客户端连接失败后会自动退出？
> > 
> > 
> > 是的
> 
> 感谢，将域名指向了一个无效的ip地址 frps dashboard依然显示客户端正在连接 是否属于一个bug？

frps 还没知道 frpc 下线了

**Comment by cli8910** [comment]
？

**Comment by fraee** [comment]
> > > > > 动态ip更换时，域名解析需要数分钟生效，在这个空隙连不上，一旦解析生效就会连上。 你最好全局加一个 `loginFailExit = false`
> > > > 
> > > > 
> > > > 感谢回答 我测试将域名指向了一个无效的ip地址 但是现在frps dashboard还是显示客户端正在连接 是缓存还是？loginFailExit字面意思是说 如果不加这个选项 在客户端连接失败后会自动退出？
> > > 
> > > 
> > > 是的
> > 
> > 
> > 感谢，将域名指向了一个无效的ip地址 frps dashboard依然显示客户端正在连接 是否属于一个bug？
> 
> frps 还没知道 frpc 下线了

想知道这个缓存时间是多久  目测几个小时数量还没正常更新  dns缓存应该不会这么久
还是说frp只取一次域名对应的ip地址  而不会随域名dns的更新而更新  @superzjg

**Comment by superzjg** [comment]
> > > > > > 动态ip更换时，域名解析需要数分钟生效，在这个空隙连不上，一旦解析生效就会连上。 你最好全局加一个 `loginFailExit = false`
> > > > > 
> > > > > 
> > > > > 感谢回答 我测试将域名指向了一个无效的ip地址 但是现在frps dashboard还是显示客户端正在连接 是缓存还是？loginFailExit字面意思是说 如果不加这个选项 在客户端连接失败后会自动退出？
> > > > 
> > > > 
> > > > 是的
> > > 
> > > 
> > > 感谢，将域名指向了一个无效的ip地址 frps dashboard依然显示客户端正在连接 是否属于一个bug？
> > 
> > 
> > frps 还没知道 frpc 下线了
> 
> 想知道这个缓存时间是多久 目测几个小时数量还没正常更新 dns缓存应该不会这么久 还是说frp只取一次域名对应的ip地址 而不会随域名dns的更新而更新 @superzjg

我有一台frps（arm64）动态域名更新时候，我的另外2台frpc（一台arm，一台arm64），通常会断线几分钟到十几分钟，然后重新连上。我的frps是普通家庭宽带动态公网ip，配合花生壳免费域名。供参考。
