### ISSUE TITLE
请教一下使用Nginx作为frps前置代理的配置

### ISSUE THREAD

**Issue by heqiaomu** [fatedier/frp#3911]
### Bug Description

在 nginx 的配置中，我配置的是：
```shell
    location /application  {  
        proxy_pass http://172.23.161.143:30080;  
        proxy_set_header Host $host;
    } 
```
我的服务端的配置是：
```shell
bindAddr = "0.0.0.0"
bindPort = 7011

vhostHTTPPort = 30080
vhostHTTPSPort = 30443

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"

auth.method = "token"
auth.token = ""
```

然后我的客户端：
```shell
user = "heqiaomu"

serverAddr = "x.x.x.x"
serverPort = 7011
auth.method = "token"
auth.token = ""

[[proxies]]
name = "confluence"
type = "http"
localPort = 8090
customDomains = ["www.heqiaomu123.cn"]
locations = ["/application/wiki"]
```
然后我在访问 www.heqiaomu123.cn/application/wiki 我的路由会直接跳到 http://www.heqiaomu123.cn/login.action。理论上应该是到 www.heqiaomu123.cn/application/wiki/login.action 这个地址。我想请问下这块有相关的配置上的参考吗？

### frpc Version

0.53.2

### frps Version

0.53.2

### System Architecture

linux/amd64

### Configurations

在 nginx 的配置中，我配置的是：
```shell
    location /application  {  
        proxy_pass http://172.23.161.143:30080;  
        proxy_set_header Host $host;
    } 
```
我的服务端的配置是：
```shell
bindAddr = "0.0.0.0"
bindPort = 7011

vhostHTTPPort = 30080
vhostHTTPSPort = 30443

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"

auth.method = "token"
auth.token = ""
```

然后我的客户端：
```shell
user = "heqiaomu"

serverAddr = "x.x.x.x"
serverPort = 7011
auth.method = "token"
auth.token = ""

[[proxies]]
name = "confluence"
type = "http"
localPort = 8090
customDomains = ["www.heqiaomu123.cn"]
locations = ["/application/wiki"]
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
那个客户端 `localIP` 是没有吗？

**Comment by Fiary-Tale** [comment]
兄弟，你试着把customDomains = ["1.1.1.1"]这个配置为customDomains = ["127.0.0.1"]，就会默认转发到他的127.0.0.1:58880端口上，这样就可以做nginx反向代理了

**Comment by Fiary-Tale** [comment]
frpc的配置改一下就可以

**Comment by Heqiaomu** [comment]
我不是很明白这个路由的配置：
我在客户端中的配置是这样的
```
subdomain = "www"
customDomains = ["www.heqiaomu123.cn"]
locations = ["/application/wiki"]
```
服务端里面的配置是这样的：
```
vhostHTTPPort = 30080
vhostHTTPSPort = 30443
```

用一层 Nginx 在外围进行了反向代理。那 www.heqiaomu123.cn/application/wiki 这个地址为什么会请求不到呢 ？404 的 frp 页面。

**Comment by Heqiaomu** [comment]
OKOK, 应该是我这边的代理问题导致的。
