### ISSUE TITLE
请问：frp的日志保留时间有多长？

### ISSUE THREAD

**Issue by Apelious** [fatedier/frp#3913]
### Bug Description

我的frps已经运行了一个多月，但是我只发现了最近四天的日志，请问frp是有日志保留时间的吗？

frps配置如下：
```
bindPort = 7000
quicBindPort = 7000
transport.maxPoolCount = 30
webServer.addr = "0.0.0.0"
webServer.port = 9000
webServer.user = "*******"
webServer.password = "*****************************"
auth.token = "*******************"
log.to = "/var/log/frp/frps.log"
```

/var/log/frp/下的日志文件如下：
```
total 1.5M
drwxr-xr-x  2 root root 4.0K Jan  6 19:02 .
drwxr-xr-x 15 root root 4.0K Jan  6 17:26 ..
-r--r-----  1 root root 1.1M Jan  3 23:59 frps.2024-01-03.log
-r--r-----  1 root root 297K Jan  4 23:52 frps.2024-01-04.log
-r--r-----  1 root root  17K Jan  5 23:39 frps.2024-01-05.log
-r--r-----  1 root root  35K Jan  6 03:42 frps.2024-01-06.log
-rw-rw----  1 root root  54K Jan  6 18:54 frps.log
```

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

```
bindPort = 7000
quicBindPort = 7000
transport.maxPoolCount = 30
webServer.addr = "0.0.0.0"
webServer.port = 9000
webServer.user = "*******"
webServer.password = "*****************************"
auth.token = "*******************"
log.to = "/var/log/frp/frps.log"
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frps_full_example.toml#L85-L91

**Comment by Apelious** [comment]
> https://github.com/fatedier/frp/blob/dev/conf/frps_full_example.toml#L85-L91

感谢解答！
