### ISSUE TITLE
[Feature Request] - Ability to record personal notes on the proxy

### ISSUE THREAD

**Issue by manprint** [fatedier/frp#3914]
### Describe the feature request

It would be really great to be able to record personal notes on the client-side proxy when it is instantiated. For example, you could enter a note key on the proxy client configuration for tcp, upd, http, https, etc:

``` 
[[proxies]]
name = "web"
note = "Tunnel for develop my awesome app, located on aws cloud server named: mydemoapp_v01"
type = "http"
localPort = 80
customDomains = ["www.example.com"] 
```

This note should appear in the proxy console details, so that it is possible to immediately understand what that proxy does and where it has been instantiated.

Thank you so much for your work and for this amazing project

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
> This note should appear in the proxy console details.

Where exactly do you mean to display it?

The mechanism similar to K8s object annotation is being considered.

**Comment by manprint** [comment]
Hi @fatedier,
thanks for your quick response.
The entered note may appear in the console in the proxy detail, for example under the "Last Start" label.
I attach an example image

![frp](https://github.com/fatedier/frp/assets/64725303/933f8aaf-934a-4b57-b22b-604d4973f15b)

Thank You.

**Comment by fatedier** [comment]
@manprint OK. I will consider this feature, but it may introduce an annotations map instead of a single note, which would provide greater scalability.
