### ISSUE TITLE
[Feature Request] Linux x86

### ISSUE THREAD

**Issue by byzhao** [fatedier/frp#3916]
### Describe the feature request

你好，由于节点有不少X86的设备，请问咱们还有支持Linux x86的计划吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by superzjg** [comment]
https://github.com/fatedier/frp/issues/3661

**Comment by jasonfanjun** [comment]
给你一个可行的方案，针对最新的版本已经经过测试。
1.克隆仓库或者直接下来 zip
2.解压后进入该目录。
3.使用 vscode 编辑根目录下Makefile.cross-compiles 文件
4.第 5 行改为os-archs=linux:linux:386
5.保存后终端执行make -f Makefile.cross-compiles 注意，必须是最新的 go 版本

编译后在release目录拿到编译后可执行文件，放到对应位置就可以使用，frps和 frpc 两个。
