### ISSUE TITLE
升级后外部无法访问使用nginx的网站

### ISSUE THREAD

**Issue by cc0h** [fatedier/frp#3917]
### Bug Description

之前用NGINX和0.38.0的frp自己做了个静态网站，更新frp后外部不能访问这个网站了

### frpc Version

0.53.2

### frps Version

0.53.2

### System Architecture

linux/amd64

### Configurations

[[proxies]]
name = "srv"
type = "tcp"
localIP = "127.0.0.1"
loaclPort = 80
remotePort = 8089

### Logs

2024/01/07 09:14:12 [E] [proxy.go:204] [1144260ce720d4d7] [dynamicx.srv] connect to local service [127.0.0.1:0] error: dial tcp 127.0.0.1:0: connect: connection refused

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by cc0h** [comment]
add more log

2024/01/07 11:25:25 [I] [root.go:141] start frpc service for config file [/etc/frpc/frpc.toml]
2024/01/07 11:25:25 [I] [service.go:287] try to connect to server...
2024/01/07 11:25:25 [I] [service.go:279] [6201b1651447d84c] login to server success, get run id [6201b1651447d84c]
2024/01/07 11:25:25 [I] [proxy_manager.go:173] [6201b1651447d84c] proxy added: [dynamicx.ssh dynamicx.srv]
2024/01/07 11:25:25 [I] [control.go:169] [6201b1651447d84c] [dynamicx.ssh] start proxy success
2024/01/07 11:25:25 [I] [control.go:169] [6201b1651447d84c] [dynamicx.srv] start proxy success
2024/01/07 11:25:44 [E] [proxy.go:204] [6201b1651447d84c] [dynamicx.srv] connect to local service [0.0.0.0:0] error: dial tcp 0.0.0.0:0: connect: connection refused

**Comment by xqzr** [comment]
```toml
localIP = "127.0.0.1"
loaclPort = 80
```
它们没有起作用

**Comment by fatedier** [comment]
新增了一个参数 `--strict_config`，加上这个参数会一定程度上避免这样的问题。

**Comment by superzjg** [comment]
我觉得参数从官方示例直接复制，粘贴会比较好，手打容易出问题，还不自知。

**Comment by cc0h** [comment]
我换了一个远程端口之后问题解决了，感谢各位
