### ISSUE TITLE
Reponse header sets wrong location

### ISSUE THREAD

**Issue by cedricbieder** [fatedier/frp#3919]
### Bug Description

I am using a frp-http tunnel to get access to a webapplication. I can also reach the login screen of this app with subdomain.mydomain.com:443. If I log in, the authentication response returns in the header a new location with subdomain.mydomain.com:82 and the browser redirects to this port. I always have to remove this port again to work normal on the 443 tunnel. Is there a parameter which I can set to manipulate this response location?

### frpc Version

0.53

### frps Version

0.53

### System Architecture

linux/amd64

### Configurations

[16]
type=https
local_ip=127.0.0.1
local_port=82
subdomain=subdomain
#host_header_rewrite=subdomain.domain.com
[common]
server_addr=server.domain.com
server_port=443
authentication_method=token
token=my_token
log_level=trace
user=my_user
tls_enable=true

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
You can modify it in your own app.
