### ISSUE TITLE
host_header_rewrite似乎有问题

### ISSUE THREAD

**Issue by SifuLi** [fatedier/frp#392]
linux frps 0.12
win10 frpc 0.12

![tim 20170705152354](https://user-images.githubusercontent.com/10288368/27853615-fcb76efc-6195-11e7-9e68-3002e1ead2dc.png)

**Comment by fatedier** [comment]
1. 请按 issue 指定格式反馈问题。
2. #248 避免重复提交类似的问题。
3. 已在 0.13 版本修复。
