### ISSUE TITLE
Is the configuration secure enough for RDP access?

### ISSUE THREAD

**Issue by alexmartynov666** [fatedier/frp#3923]
### Bug Description

STCP + QUIC
Are there any other mandatory settings needed?

### frpc Version

0.53.2

### frps Version

0.53.2

### System Architecture

windows/amd64

### Configurations

_Tunnel server frps.toml:_
quicBindPort = 60000

_RDP server frpc.toml:_
serverAddr = "XXXX"
serverPort = 60000
transport.protocol = "quic"
[[proxies]]
name = "secret_rdp"
type = "stcp"
secretKey = "XXXX"
localIP = "127.0.0.1"
localPort = 3389

_Client server frpc.toml:_
serverAddr = "XXXX"
serverPort = 60000
transport.protocol = "quic"
[[visitors]]
name = "secret_rdp_visitor"
type = "stcp"
serverName = "secret_rdp"
secretKey = "XXXX"
bindAddr = "127.0.0.1"
bindPort = 3389

**Comment by superzjg** [comment]
This is OK
1. The STCP mode is relatively safe.
2. FRP is encrypted by default since v0.50.0.
3. RDP defaults to using self signed certificates.
