### ISSUE TITLE
360防火墙报病毒,是否有异常?

### ISSUE THREAD

**Issue by hkargv** [fatedier/frp#3925]
### Bug Description

![QQ截图20240111204155](https://github.com/fatedier/frp/assets/61319333/5f5fd706-ad7f-48c6-a7bd-422310cf9b20)

### frpc Version

frp_0.53.2_linux_amd64.tar

### frps Version

frp_0.53.2_linux_amd64.tar

### System Architecture

Rocky Linux release 9.3
Windows 11下的360杀毒报的,应该没啥问题就是反馈一下

### Configurations

null
前一个版本 frp_0.52.3_linux_amd64.tar 没有这个问题

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
看置顶issue
