### ISSUE TITLE
frpc客户端莫名其妙的掉线

### ISSUE THREAD

**Issue by yujunchengg** [fatedier/frp#3926]
### Bug Description

frps版本号： 0.52.3，运行在windows server2016上
frpc客户端1：  0.52.3， 运行在windows server 2012上
frpc客户端2：  0.52.3， 运行在centos7上
目前发现的问题是，frpc客户端1，出现wait time out的提示字样，大致意思就是连接frps超时，然后触发重试
frpc客户端2，莫名其妙的进程直接挂掉，然后我frpc配置的日志，也没有生成对应的log文件

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64, windows/amd64

### Configurations

serverAddr = "x.x.x.x"
serverPort = 7000

auth.method = "token"
auth.token = "fasdfasdfasdfasdfasfd"

# console or real logFile path like ./frpc.log
log.to = "./frpc.log"
# trace, debug, info, warn, error
log.level = "info"
log.maxDays = 3
# disable log colors when log.to is console, default is false
log.disablePrintColor = false

[[proxies]]
name = "passport"
type = "http"
localIP = "127.0.0.1"
localPort = 8300
customDomains = ["passport.xxxx.com"]

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
尝试 QUIC
