### ISSUE TITLE
[Feature Request] 请问tcp转发时能否获取到真实的公网ip？

### ISSUE THREAD

**Issue by seepine** [fatedier/frp#3927]
### Describe the feature request

我内网有服务器A，需要客户电脑B的tcpClient去连A的tcpServer，我通过云服务器G搭建frps，A搭建frpc，转发tcp端口5000，然后B通过公网ip+5000端口连接，能够成功连到A了，但是A识别到的ip是127.0.0.1，毕竟在A的tcpServer看来，是本机frpc发起的连接，而我需要让A的tcpServer识别出是公网ip连接过来的，请问frp目前可以实现吗或以后是否会实现，或者有没有其他方案可以解决

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
tcpServer 自行实现 `Proxy Protocol` 与 frpc 对接
https://gofrp.org/zh-cn/docs/features/common/realip/#proxy-protocol
