### ISSUE TITLE
穿透内网多个http端口出来

### ISSUE THREAD

**Issue by pigping88** [fatedier/frp#3929]
### Bug Description

frpc.toml:
serverAddr = "x.x.x.x"
serverPort = 7000

[[proxies]]
name = "web"
type = "http"
localIP = "127.0.0.1"
localPort = 8000
customDomains = ["x.x.x.x"]

[[proxies]]
name = "mobile"
type = "http"
localIP = "127.0.0.1"
localPort = 8080
customDomains = ["x.x.x.x:8080"]

[[proxies]]
name = "file"
type = "http"
localIP = "127.0.0.1"
localPort = 9300
customDomains = ["x.x.x.x:9300"]

frps.toml:
bindPort = 7000
vhostHTTPPort = 80

目前这样无法通过ip映射多个端口，x.x.x.x是公网ip，目前没有域名，备案麻烦

### frpc Version

frp_0.53.0_windows_amd64

### frps Version

frp_0.53.2_linux_amd64

### System Architecture

client: windows, server: centos7

### Configurations

frpc.toml:
serverAddr = "x.x.x.x"
serverPort = 7000

[[proxies]]
name = "web"
type = "http"
localIP = "127.0.0.1"
localPort = 8000
customDomains = ["x.x.x.x"]

[[proxies]]
name = "mobile"
type = "http"
localIP = "127.0.0.1"
localPort = 8080
customDomains = ["x.x.x.x:8080"]

[[proxies]]
name = "file"
type = "http"
localIP = "127.0.0.1"
localPort = 9300
customDomains = ["x.x.x.x:9300"]

frps.toml:
bindPort = 7000
vhostHTTPPort = 80

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by pigping88** [comment]
我需要内网多个端口，同时穿透映射到外网一样的端口，不然我要改动调整，直接端口对端口，简单，

**Comment by pigping88** [comment]
已处理，用tcp，服务端，监听多个端口，客服端，绑定映射多个端口

**Comment by zzyouyou** [comment]
> 已处理，用tcp，服务端，监听多个端口，客服端，绑定映射多个端口

方便看下配置项嘛？
为什么我这样不行
客户端：
serverAddr = "x.x.x.x"
serverPort = 7000

[[proxies]]
name = "test-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000

[[web_cas]]
name = "cas"
type = "tcp"
localIP = "127.0.0.1"
localPort = 80
remotePort = 480

[[web_homeassistant]]
name = "homeassistant"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8080
remotePort = 48080 

服务端：
bindPort = 7000

**Comment by just12321** [comment]
> > 已处理，用tcp，服务端，监听多个端口，客服端，绑定映射多个端口
> 
> 方便看下配置项嘛？ 为什么我这样不行 客户端： serverAddr = "x.x.x.x" serverPort = 7000
> 
> [[proxies]] name = "test-tcp" type = "tcp" localIP = "127.0.0.1" localPort = 22 remotePort = 6000
> 
> [[web_cas]] name = "cas" type = "tcp" localIP = "127.0.0.1" localPort = 80 remotePort = 480
> 
> [[web_homeassistant]] name = "homeassistant" type = "tcp" localIP = "127.0.0.1" localPort = 8080 remotePort = 48080
> 
> 服务端： bindPort = 7000

应该要都是[[proxies]]
