### ISSUE TITLE
服务器必须使用IPV4地址吗，怎么才能使用二级域名做为服务器地址呢?

### ISSUE THREAD

**Issue by a7858250** [fatedier/frp#3931]
### Describe the feature request

服务器必须使用IPV4地址吗，怎么才能使用二级域名做为服务器地址呢?
因为我们的网络基本上很少有固定的IPV4公网地址，都是动态的IPV4地址，每次重启ADSL后就会获得一个新的IPV4地址，如果可以用二级域名作为服务器地址的话就好很多了，

在openwrt中的frp客户端中
当我用二级域名作为服务器地址的时候，控制台上就会显示客户端离线

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
域名正确解析后使用

**Comment by a7858250** [comment]
2024/01/13 00:00:59 [W] [service.go:134] login to server failed: dial tcp: lookup frps.workused.com on [::1]:53: server misbehaving
域名解析是正确的   因为我用域名访问仪表盘是没问题了，只是仪表盘中的tcp协议下 容器是离线。上面是openwrt中的frp内网穿透日志
![OpenWrt - Frp 内网穿透 - LuCI](https://github.com/fatedier/frp/assets/59914266/94d65bd1-51e8-44a6-9c80-9c1b0995c685)

**Comment by xqzr** [comment]
`[::1]:53` 解析结果不正确
