### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by a7858250** [fatedier/frp#3932]
### Describe the feature request

frps搭建好以后用户与内网主机在TCP数据传输的时候是经过服务器的数据转发，这样会受服务器带宽的限制，同时会大量耗费服务器的流量，有什么好的办法和建议来解决这个问题吗

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://gofrp.org/zh-cn/docs/examples/xtcp/
