### ISSUE TITLE
最新版的frp，http端口问题

### ISSUE THREAD

**Issue by keaidragon** [fatedier/frp#3933]
### Describe the feature request

我在istoreos上部署frpc为啥没有http端口设置了？通过域名没有办法访问，求解

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
在frps设置：
# If you want to support virtual host, you must set the http port for listening (optional)
`vhostHTTPPort = 80`
`vhostHTTPSPort = 443`
