### ISSUE TITLE
[Feature Request] Add an API to server to disconnect the client

### ISSUE THREAD

**Issue by kingc2022** [fatedier/frp#3934]
### Describe the feature request

Let the server disconnect the client, like `/api/client/close/{proxy_name}`.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [x] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by thanh-tl** [comment]
I need this API. Sometimes the server port is not released properly, causing the client to got the "proxy already exists" error.

**Comment by kingc2022** [comment]
I really need this API. Can you help me with that? TAT
