### ISSUE TITLE
frps_full_example.toml内容勘误

### ISSUE THREAD

**Issue by seeyou2n1ght** [fatedier/frp#3937]
### Bug Description

完整的frps配置文件132行关于配置子域名的注释：
> When subdomain is est, the host used by routing is test.frps.com
subDomainHost = "frps.com"

也许是想表示子域名配置为test？

### frpc Version

0.53.2

### frps Version

0.53.2

### System Architecture

linux/amd64

### Configurations

NA

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
明显是的

**Comment by wuqinqiang** [comment]
可以提交一个typo -_-
