### ISSUE TITLE
[Feature Request] 服务器网络异常时，重试时间是如何确定的？

### ISSUE THREAD

**Issue by liqilong2017** [fatedier/frp#3939]
### Describe the feature request

请问，客户端的服务器网络异常时，多长时间会重试去连服务器端，重试时间是如何确定的？
文档里没有找到相关的配置

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
上面有列出代码。
其实你可以自己看log文件，把frps服务器关掉，frpc配置 `loginFailExit = false` ，然后看frpc的log，会有具体“等待多少秒重试”之类的log。
