### ISSUE TITLE
FRP有没有可能演化成一个全功能的代理？

### ISSUE THREAD

**Issue by linkerlin** [fatedier/frp#394]
保留现在的功能，增加类似Shadowsocks的功能。

**Comment by fatedier** [comment]
不是一个类型的项目，frp 是作为一个反向代理，目的是穿透内网。

**Comment by linkerlin** [comment]
@fatedier 确实是类型不一样，但是有没有可能演化成 n2n 这样的项目呢？

**Comment by fatedier** [comment]
会有类似的功能，但不以此为主。
