### ISSUE TITLE
使用tcpmux无法访问网站

### ISSUE THREAD

**Issue by MS1987** [fatedier/frp#3940]
### Bug Description

你好，我想使用tcpmux实现一台服务器链接多个客户机器，
运行后，服务端可以log出来test-tcp的链接信息：
`2024/01/15 15:22:58 [I] [control.go:401] [471889f40a4b96ce] new proxy [test-tcp]
 type [tcpmux] success`
但在浏览器上直接访问“120.79.122.236:7003”或者“machine-b.example.com:7003”都不能访问网页。之前测试ssh的端口是可以的。请问是什么设置问题么？

### frpc Version

0.53.2

### frps Version

0.53.2

### System Architecture

linux/arm64

### Configurations

服务端frps配置：
```
bindAddr = "0.0.0.0"
bindPort = 7002
tcpmuxHTTPConnectPort = 7003

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin1235"
webServer.password = "admin1235"
```

客户端配置：
```
serverAddr = "120.79.122.236"
serverPort = 7002
tcpmuxHTTPConnectPort = 7003

[[proxies]]
name = "test-tcp"
type = "tcpmux"
multiplexer = "httpconnect"
customDomains = ["machine-b.example.com"]
localIP = "127.0.0.1"
localPort = 80
remotePort = 6000
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
它需要 HTTP `CONNECT` 方法

**Comment by JsonSong89** [comment]
网站应该使用http类型吧
