### ISSUE TITLE
[web] start error: type [http] not supported when vhost http port is not set

### ISSUE THREAD

**Issue by StarSink9** [fatedier/frp#3943]
### Bug Description

客户端配置
serverAddr = "xxxx"
serverPort = 7000

[[proxies]]
name = "web"
type = "http"
localPort = 3000
customDomains = ["yc.xxxx.com"]

服务端配置
[common]
bindPort = 7000
vhostHTTPPort = 80

# FRPS 服务端 仪表盘 dashboard 登陆端口
dashboard_port = 7500
 
# FRPS 服务端 仪表盘 dashboard 登陆用户名、密码
dashboard_user = admin
dashboard_pwd = admin

### frpc Version

0.53.2_windows_amd64.

### frps Version

0.53.2_linux_amd64

### System Architecture

windows/amd64

### Configurations

然后报错[web] start error: type [http] not supported when vhost http port is not set

### Logs

C:\frps>frpc -c frpc.toml
2024/01/22 17:02:31 [I] [root.go:141] start frpc service for config file [frpc.toml]
2024/01/22 17:02:31 [I] [service.go:287] try to connect to server...
2024/01/22 17:02:31 [I] [service.go:279] [65aceb84eaecac91] login to server success, get run id [65aceb84eaecac91]
2024/01/22 17:02:31 [I] [proxy_manager.go:173] [65aceb84eaecac91] proxy added: [web]
2024/01/22 17:02:31 [W] [control.go:167] [65aceb84eaecac91] [web] start error: type [http] not supported when vhost http port is not set
2024/01/22 17:03:01 [W] [control.go:167] [65aceb84eaecac91] [web] start error: type [http] not supported when vhost http port is not set
2024/01/22 17:03:31 [W] [control.go:167] [65aceb84eaecac91] [web] start error: type [http] not supported when vhost http port is not set
2024/01/22 17:04:02 [W] [control.go:167] [65aceb84eaecac91] [web] start error: type [http] not supported when vhost http port is not set
2024/01/22 17:04:32 [W] [control.go:167] [65aceb84eaecac91] [web] start error: type [http] not supported when vhost http port is not set
2024/01/22 17:05:02 [W] [control.go:167] [65aceb84eaecac91] [web] start error: type [http] not supported when vhost http port is not set
2024/01/22 17:05:35 [W] [control.go:167] [65aceb84eaecac91] [web] start error: type [http] not supported when vhost http port is not set
2024/01/22 17:06:05 [W] [control.go:167] [65aceb84eaecac91] [web] start error: type [http] not supported when vhost http port is not set
2024/01/22 17:06:35 [W] [control.go:167] [65aceb84eaecac91] [web] start error: type [http] not supported when vhost http port is not set

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
服务端配置未生效，先阅读文档...

**Comment by xqzr** [comment]
~~`[common]`~~
