### ISSUE TITLE
0.53.以后支持的SSH reverse tunneling功能怎么用？有没有大佬教程

### ISSUE THREAD

**Issue by lonelydespair** [fatedier/frp#3945]
### Describe the feature request

0.53.以后支持的SSH reverse tunneling功能怎么用？有没有大佬教程

### Describe alternatives you've considered

0.53.以后支持的SSH reverse tunneling功能怎么用？有没有大佬教程

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
参看：
https://github.com/fatedier/frp/blob/f7efbfeec53b64b85b256124b896430289933757/doc/ssh_tunnel_gateway.md

issues板块主要用于反馈bug，使用问题尽量不要发到这..
