### ISSUE TITLE
ssh登陆失败

### ISSUE THREAD

**Issue by SJTUHGX** [fatedier/frp#3946]
### Bug Description

在公网机器：./frps -c ./frps.toml
返回的是frps starts sucessfully,new proxy[ssh] type [tcp] success等成功信息

在内网机器：./frpc -c ./frpc.toml
返回的是login to server success，get run id[xxxxx]
proxy added:[ssh]
[ssh] start proxy success等成功信息

ssh -o Port=6000 内网机器用户名:公网机器IP
但ssh的连接总是被拒绝，返回信息
Could not connet to “公网机器IP”（port 6000):connection field

### frpc Version

0.53.2

### frps Version

0.53.2

### System Architecture

linux/amd64

### Configurations

公网机器上：
bindPort = 7000

内网机器上：
serverAddr = "公网机器的IP"
serverPort = 7000

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "内网机器的IP"
localPort = 22
remotePort = 在公网机器开启的6000端口

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
frps 所在网络 开放 6000 端口

**Comment by touale** [comment]
也许和你的安全组策略有关

**Comment by SJTUHGX** [comment]
可能是系统的原因，我重装了系统，问题就解决了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: touale ***@***.***&gt;
发送时间: 2024年2月17日 12:53
收件人: fatedier/frp ***@***.***&gt;
抄送: SJTUHGX ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [fatedier/frp] ssh登陆失败 (Issue #3946)





 
也许和你的安全组策略有关

**Comment by SJTUHGX** [comment]
谢谢，问题已经解决了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xqzr ***@***.***&gt;
发送时间: 2024年1月28日 23:59
收件人: fatedier/frp ***@***.***&gt;
抄送: SJTUHGX ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [fatedier/frp] ssh登陆失败 (Issue #3946)





 
frps 所在网络 开放 6000 端口
