### ISSUE TITLE
请求大佬解答服务器自动删除了我的frpc可执行文件怎么办

### ISSUE THREAD

**Issue by shishanya** [fatedier/frp#3948]
### Describe the feature request

请求大佬解答服务器自动删除了我的frpc可执行文件怎么办

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
若信任，通常启用白名单

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/issues/3716#issuecomment-1870090882
