### ISSUE TITLE
火狐访问内网web服务出错 SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by skywinds5012** [fatedier/frp#395]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.12

**What operating system and processor architecture are you using (`go env`)?**
服务端debian8 amd64，客户端win10 x64

**Configures you used:**
[frps.ini]
vhost_https_port = 443

[frpc.ini]
[web1]
type = https
custom_domains = web1.mydomain.com

or

[frps.ini]
vhost_https_port = 443
subdomain_host = mydomain.com

[frpc.ini]
[web1]
type = https
subdomain = web1

vhost_https_port还尝试更改为其它端口，报同样错误

**Steps to reproduce the issue:**
1.配置完毕后正常运行服务端与客户端
2.从另一台电脑（win10 x64）的火狐（32位）访问web1.mydomain.com
3.报错

**Describe the results you received:**
火狐提示：建立安全连接失败，SSL 接收到一个超出最大准许长度的记录。 错误代码:SSL_ERROR_RX_RECORD_TOO_LONG
Edge提示：无法安全地连接到此页面 这可能是因为该站点使用过期的或不安全的 TLS 安全设置
Chrome提示：此网站无法提供安全连接 发送的响应无效。 ERR_SSL_PROTOCOL_ERROR
服务端只有info，火狐连接时会打印出get a new work connection，edge与chrome无反应

**Describe the results you expected:**
正常打开web服务的首页

**Additional information you deem important (e.g. issue happens only occasionally):**
其实我同时运行2个不同的web服务，两个服务监听的本地端口不同。
改为http模式时2个web服务都能正常访问，但是我对安全方面有一定的需求，想至少通过https加强一些。

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
先确认下你的 web 服务的 ssl 证书配置是否正确。

frp 里不提供关于证书的配置和解析功能，仅通过域名来路由转发 https 请求。

**Comment by skywinds5012** [comment]
明白了，谢谢解答

**Comment by iblogc** [comment]
@skywinds5012 你好请问是如何解决的？我在本地如果启一个https的服务是没有问题，如果如果本地的是http不行，因为我本地现在要放一个静态的网站，所以有没有什么方法可以是地址启http://127.0.0.1:8000这样，穿透地址用https协议的方案。

**Comment by skywinds5012** [comment]
我改用ngrok了。-------- 原始邮件 --------主题：Re: [fatedier/frp] 火狐访问内网web服务出错 SSL_ERROR_RX_RECORD_TOO_LONG (#395)发件人：iblogc 收件人：fatedier/frp 抄送：skywinds5012 ,Mention @skywinds5012 你好请问是如何解决的？我在本地如果启一个https的服务是没有问题，如果如果本地的是http不行，因为我本地现在要放一个静态的网站，所以有没有什么方法可以是地址启http://127.0.0.1:8000这样，穿透地址用https协议的方案。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fatedier/frp","title":"fatedier/frp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fatedier/frp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@iblogc in #395: @skywinds5012 你好请问是如何解决的？我在本地如果启一个https的服务是没有问题，如果如果本地的是http不行，因为我本地现在要放一个静态的网站，所以有没有什么方法可以是地址启http://127.0.0.1:8000这样，穿透地址用https协议的方案。"}],"action":{"name":"View Issue","url":"https://github.com/fatedier/frp/issues/395#issuecomment-386518032"}}}

**Comment by iblogc** [comment]
好的吧，谢谢。

skywinds5012 <notifications@github.com>于2018年5月4日周五 下午3:53写道：
