### ISSUE TITLE
Wiki介绍参考配置不明

### ISSUE THREAD

**Issue by BlueDolphin9527** [fatedier/frp#3951]
### Bug Description

[Wiki](https://gofrp.org/zh-cn/docs/examples/vhost-http/)中frpc.toml的配置文件少了`LocalIP = 127.0.0.1`段吧？不然访问的是内网哪台机器呢？

### frpc Version

1

### frps Version

1

### System Architecture

1

### Configurations

1

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
默认 `127.0.0.1`

**Comment by BlueDolphin9527** [comment]
好的，感谢解答。
