### ISSUE TITLE
0.53版本问题

### ISSUE THREAD

**Issue by cexzreal** [fatedier/frp#3953]
### Bug Description

我的网线连接的主机可以成功connect to frp的服务器端，但是wifi连接的笔记本，同样的配置文件。却无法连接到服务端

### frpc Version

0.53.0

### frps Version

0.53.0

### System Architecture

windows/amd64

### Configurations

serverAddr = "serverip"
serverPort = 7000

[[proxies]]
name = "palworld"
type = "udp"
localIP = "127.0.0.1"
localPort = 8211
remotePort = 7000

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by KennanChan** [comment]
解决了吗？我这边palworld的8211端口也不行

**Comment by cexzreal** [comment]
我换Ubuntu和windows11都可以  你懒得换系统开个虚拟机试试呗
