### ISSUE TITLE
[Feature Request] 为啥没有基于udp的 P2P打洞   P2P怎么实现UDP的呢

### ISSUE THREAD

**Issue by bigbeer1** [fatedier/frp#3954]
### Describe the feature request

[Feature Request] 为啥没有基于udp的 P2P打洞   P2P怎么实现UDP的呢

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
看起来需要实现 “xudp”

**Comment by dimsgithubaccount** [comment]
p2p也简单，不过frp的目的就是转发，因为（公网服务器）转发延迟低，p2p延迟高，游戏都是p2p联机，总有卡比，所以才有frp这样的经典转发工具一席之地

**Comment by ShiinaRinne** [comment]
> p2p也简单，不过frp的目的就是转发，因为（公网服务器）转发延迟低，p2p延迟高，游戏都是p2p联机，总有卡比，所以才有frp这样的经典转发工具一席之地

正相反，p2p直连的延迟才低吧，为什么经过服务器转发会更快呢，因为服务器线路好吗？
联机卡顿似乎是由于运营商不同，以及nat等级和丢包影响，但单论延迟我认为直连才是最低的

**Comment by ShiinaRinne** [comment]
> [Feature Request] 为啥没有基于udp的 P2P打洞 P2P怎么实现UDP的呢

猜你在找 zerotier, wireguard, tailscale

**Comment by dimsgithubaccount** [comment]
> > p2p也简单，不过frp的目的就是转发，因为（公网服务器）转发延迟低，p2p延迟高，游戏都是p2p联机，总有卡比，所以才有frp这样的经典转发工具一席之地
> 
> 正相反，p2p直连的延迟才低吧，为什么经过服务器转发会更快呢，因为服务器线路好吗？
> 联机卡顿似乎是由于运营商不同，以及nat等级和丢包影响，但单论延迟我认为直连才是最低的

是的，拥有独立ip的云服务器非常稳定。p2p对区域近的节点非常实用，但平均来说有一小部分的节点离master较远（或处在不同的运营商网络），p2p的问题是存在不稳定性。延迟最低只能适用于特定情况，不适用于普遍情况。

类似frp转发的特点就是稳定，但不一定低延迟，只是这个延迟大多数时候是可以接受的。一般用frp是为了把自己的主机暴露出去，同时也保障了普遍的低延迟。这没什么纠结的，应用程序可以根据两者延迟自行选择连接方式，只要有能力为用户提供云主机流量。

**Comment by xqzr** [comment]
#1729
