### ISSUE TITLE
[Feature Request] 穿透限速问题！？

### ISSUE THREAD

**Issue by WuMe-sicx** [fatedier/frp#3956]
### 限速问题
当前使用的是nas smb远程接入,但是每次下载和看视频的时候 速度只能跑满1MB宽带
公网宽带是1Gbps ,
### 解决问题
想询问一下这个解决这个问题是先解决公网还是内网？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
frps 上/下行 取最小
frpc 取 上行
访问端 取 下行
