### ISSUE TITLE
Reverse proxy a VPN or Fiddler connection reset by peer

### ISSUE THREAD

**Issue by crazy-dragon** [fatedier/frp#3957]
### Bug Description

Bug Description
I want to use frp to share a vpn with others and first I run a VPN in my client(computer or my phone) and run frpc, then in my aliyun server I run the frps. And, I use a third device config a http proxy. It can work and I can use google, but some website cannot access (such as www.v2ex.com, youtube can't play video), and browser says ERR_CONNECTION_RESET. I try to use fiddler replace a VPN, but the result is same. 

And I found websites that cannot be accessed or display abnormally using the HTTP2 protocol. Here is two screenshots of my visits v2ex and google. One fail and One success.

![qRvaf](https://github.com/fatedier/frp/assets/52905417/1026bc30-8241-4eca-9f8e-e3036bfc6dfa)

![4vGFP](https://github.com/fatedier/frp/assets/52905417/e9ca8b4e-35b4-437a-80ee-e51ad373e641)

### frpc Version

0.53.2

### frps Version

0.53.2

### System Architecture

server: linux/amd64  client:windows/amd64

### Configurations

serverAddr = "my.server.ip"
serverPort = 10020

[[proxies]]
name = "test-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 10809
remotePort = 10021

### Steps to reproduce

1. run a vpn or fiddler
2. run frps
3. run frpc
4. config proxy and access www.v2ex.com or youtube.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
For TCP proxy, frp simply forwards traffic without recognizing specific protocols. Therefore, if there are any issues, it is likely to be a problem at the application layer.

**Comment by crazy-dragon** [comment]
> For TCP proxy, frp simply forwards traffic without recognizing specific protocols. Therefore, if there are any issues, it is likely to be a problem at the application layer.

OK, I also think it's may a problem at the application layer. So, thanks you for you reply.
