### ISSUE TITLE
子域名长度不得超过15位，否则无法内网穿透

### ISSUE THREAD

**Issue by mephistopheles217** [fatedier/frp#3959]
### Bug Description

我在部署jenkins的时候发现的问题，我本地有很多节点，取node001节点来讲，我的域名会设置成node-jenkins-001.xxx.top，但是这个域名在穿透的时候报错，无法访问，我检查了很多遍，配置其他的域名都没有问题，就这个域名报错了，然后我猜想可能是长度的原因，我把域名的s给去掉了，现在域名是node-jenkin-001.xxx.top，重新部署后可以使用了！！然后我把域名替换成node-jenkina-001.xxx.top，又不能使用了！！！，所以目前我发现，子域名的长度不能超过15位，长度17、18之后的我没有在测试，仅仅16位的就折磨我半天了。

### frpc Version

v0.53.2

### frps Version

v0.53.2

### System Architecture

linux/amd64

### Configurations

serverAddr = "XXXXXX"
serverPort = 7000

[[proxies]]
name = "web2"
type = "http"
localPort = 8080
customDomains = ["node-jenkina-001.xxx.top"]

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Logs

**Comment by mephistopheles217** [comment]
客户端相关截图：

<img width="833" alt="image" src="https://github.com/fatedier/frp/assets/41058332/a1c35343-3509-443f-9ec4-1d2a86e61bbb">
<img width="592" alt="image" src="https://github.com/fatedier/frp/assets/41058332/72392463-51c8-425a-9679-4387fd625de7">
<img width="1021" alt="image" src="https://github.com/fatedier/frp/assets/41058332/d9c94c8c-dc28-4f84-9995-7f3d7b06a72c">
<img width="1280" alt="image" src="https://github.com/fatedier/frp/assets/41058332/0718a3cc-8da4-4332-b727-98cd89cdf66a">

服务端log：
 no route found: node-panel-001.86xxxxxxx45.top /api/v1/monitors/netoptions [0m
1Panel-frps-0MBX  | 2024/01/30 06:14:05 [1;34m[I] [proxy.go:115] [c28dd9d20e2f6bb3] [web2] proxy closing[0m
1Panel-frps-0MBX  | 2024/01/30 06:14:05 [1;34m[I] [control.go:359] [c28dd9d20e2f6bb3] client exit success[0m
1Panel-frps-0MBX  | 2024/01/30 06:14:15 [1;34m[I] [service.go:563] [805749e4da3a985b] client login info: ip [11xxxx3:42331] version [0.53.2] hostname [] os [darwin] arch [arm64][0m
1Panel-frps-0MBX  | 2024/01/30 06:14:15 [1;34m[I] [http.go:110] [805749e4da3a985b] [web2] http proxy listen for host [node-jenkins-001.8xxxxxxx5.top] location [] group [], routeByHTTPUser [][0m
1Panel-frps-0MBX  | 2024/01/30 06:14:15 [1;34m[I] [control.go:401] [805749e4da3a985b] new proxy [web2] type [http] success[0m

**Comment by mephistopheles217** [comment]
刚刚又换成http://node-jenkina-001.8xxxxxx45.top/，a这个又能访问了，http://node-jenkins-001.8xxxxxx45.top/，s这个不能访问

**Comment by mephistopheles217** [comment]
草了，我发现问题了，原来是我在腾讯云映射ip地址的时候，这个域名少映射了一个数字，导致转发失败，md腾讯云也不提示解析失败。。。。。。
