### ISSUE TITLE
Dashboard 返回 401

### ISSUE THREAD

**Issue by Blankeer** [fatedier/frp#396]
**What version of frp are you using (./frpc -v or ./frps -v)?**
Frps version 0.12.0

**What operating system and processor architecture are you using (`go env`)?**
Centos 7 x86_64  
搬瓦工 vps

**Configures you used:**
[common]
bind_addr = 我的服务器公网 ip
bind_port = 6666
kcp_bind_port = 6666
dashboard_port = 6667
dashboard_user = admin
dashboard_pwd = admin
vhost_http_port = 480
vhost_https_port = 4443
log_file = ./frps.log
log_level = info
log_max_days = 7
privilege_token = xxx
privilege_allow_ports = 1-65535
max_pool_count = 50
tcp_mux = true

**Steps to reproduce the issue:**
1.start 成功,浏览器打不开 http://我的服务器ip:6667/

**Describe the results you received:**
返回结果如下:
curl -v http://x.x.x.x:6667/
* TCP_NODELAY set
* Connected to  port 6667 (#0)
> GET / HTTP/1.1
> Host: x.x.x.x:6667
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< Www-Authenticate: Basic realm="Restricted"
< X-Content-Type-Options: nosniff
< Date: Mon, 10 Jul 2017 09:44:56 GMT
< Content-Length: 13
<
Unauthorized
* Curl_http_done: called premature == 0
* Connection #0 to host x.x.x.x left intact

**Describe the results you expected:**
访问正常

**Additional information you deem important (e.g. issue happens only occasionally):**
vhost_http_port,480访问正常,返回如下:

<h1>The page you visit not found.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>The server is powered by <a href="https://github.com/fatedier/frp">frp</a>.</p>
<p><em>Faithfully yours, frp.</em></p>
</body>
</html>
* Curl_http_done: called premature == 0
* Closing connection 0

日志貌似也正常:
2017/07/10 09:44:32 [I] [service.go:79] frps tcp listen on x.x.x.x:6666
2017/07/10 09:44:32 [I] [service.go:88] frps kcp listen on udp x.x.x.x:6666
2017/07/10 09:44:32 [I] [service.go:104] http service listen on x.x.x.x:480
2017/07/10 09:44:32 [I] [service.go:120] https service listen on x.x.x.x:4443
2017/07/10 09:44:32 [I] [service.go:130] Dashboard listen on x.x.x.x:6667
2017/07/10 09:44:32 [I] [main.go:112] Start frps success
2017/07/10 09:44:32 [I] [main.go:114] PrivilegeMode is enabled, you should pay more attention to security issues

谢谢!

**Comment by fatedier** [comment]
浏览器打不开自行检查网络相关问题。

curl 返回 401 鉴权失败。

**Comment by zhangxiangfeng** [comment]
同一样有此问题
