### ISSUE TITLE
为什么流量一大[服务端上行1M], 穿透就挂了

### ISSUE THREAD

**Issue by ZhanglinX233** [fatedier/frp#3960]
### Bug Description

当我使用vscode远程开发时，一段时间后，就会断掉连接，之后就再也连不上。
 1. 客服端是做了重启的，但是服务端后台日志全部的连接全部挂掉，重启后，还是没反应。 
 2. 之前是用nps，这个问题没有
 3.  服务器带宽是1M
 4. 具体原因是，在操作保存文件，或者运行下载文件(但下载是在内网里运行，不知道影响大不大)。就会挂掉，然后，再也连不上，只有回去重启服务器，才能用，重启之前，去看了客服端的情况，是有网的，服务挂了，但是并没有退出程序
 5. systemd服务里面是设置了重启类型的on-fail～的

### frpc Version

0.53.2

### frps Version

0.53.2

### System Architecture

linux ubuntu22.04 amd64

### Configurations

bindPort = 7001
vhostHTTPPort = 7002
webServer.port = 7003
# dashboard 用户名密码，可选，默认为空
webServer.user = "zhanglin"
webServer.password = "Zhanglin0619"
webServer.addr = "0.0.0.0"

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
你这问题发出来，让大家如何重现。
我这上行40Mbps跑满，稳定使用（arm64版）。

**Comment by ZhanglinX233** [comment]
> 你这问题发出来，让大家如何重现。 我这上行40Mbps跑满，稳定使用（arm64版）。

大概是找到问题所在了，vscode的原因，
