### ISSUE TITLE
[Feature Request] 可配置 Websockets 路径

### ISSUE THREAD

**Issue by fanthos** [fatedier/frp#3965]
### Describe the feature request

根据代码描述，`FrpWebsocketPath`是固定的`/~!frp`。希望将这个放到配置文件中，可以使用反向代理（如nginx）在同一个端口使用多个frp后端。

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
这样的参数暴露的越多，对之后的维护负担就越重，所以目前倾向于尽量不对用户暴露非必要的一些参数。

这个场景中，建议可以可以考虑通过 host 实现端口复用。

**Comment by fanthos** [comment]
之前考虑过使用host进行复用，但是如果前面有cdn或者其他反代服务时候，host不能随意改。
