### ISSUE TITLE
[Feature Request] FRPC for embedded clients / Arudino

### ISSUE THREAD

**Issue by snimavat** [fatedier/frp#3977]
### Describe the feature request

Would like to be able to use FRPC on embedded devices / Arudino / Esp32 etc. 
Will be extremely useful to expose modbus devices over TCP/ IP.

Any hints on how can this be done ? 
If the protocol between frpc/frps is well documented, may be, I could try to get minimal authentication and a TCP service working

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
I am not very familiar with embedded devices.

But perhaps you can refer to [ssh-tunnel-gateway](https://github.com/fatedier/frp?tab=readme-ov-file#ssh-tunnel-gateway) for this feature. You can interact with frps through the ssh protocol to achieve some of the capabilities of frpc.
