### ISSUE TITLE
现在新版都没有32位的程序了吗

### ISSUE THREAD

**Issue by hikefreeman** [fatedier/frp#3978]
### Describe the feature request

现在新版都没有32位的程序了吗
最新的有32位程序的 是frp_0.51.3_windows_386  
希望新版也支持32位windows

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
需要自己编译，这里有一个针对linux架构的步骤，你改一下应该就可以了：
https://github.com/fatedier/frp/issues/3916#issuecomment-1886139232
