### ISSUE TITLE
很不想麻烦，但真的没有反应！frps最大连接池的问题！

### ISSUE THREAD

**Issue by paluo90** [fatedier/frp#3981]
### Bug Description

maxPoolCount = 100 
更新服务端，并未生效，不知道问题出在哪。
一开始以为需要服务与客户端双向输出，我又在服务端设置：
PoolCount = 100
依然无效。。。

### frpc Version

0.54

### frps Version

0.54

### System Architecture

linux/amd64

### Configurations

# frps.toml
bindPort = xxxx 
kcpBindPort = xxxx
auth.token = "xxxxx" 
maxPoolCount = 100

# frpc.toml
[[proxies]]
name = "xxx"
type = "tcp"
localIP = "127.0.0.1"
poolCount = 100
localPort = xxxx
remotePort = xxxx

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [x] Docs
- [X] Installation
- [x] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by paluo90** [comment]
其余一切正常，ssh连接22端口，访问内网端口以运行的docker宿主或网站

**Comment by paluo90** [comment]
> `poolCount` 不在 `proxies`

是这样吗，我看开发文档里写的是客户端，我就搞在客户端了，晓得了！

**Comment by xqzr** [comment]
> > `poolCount` 不在 `proxies`
> 
> 是这样吗，我看开发文档里写的是客户端，我就搞在客户端了，晓得了！

https://github.com/fatedier/frp/blob/cf025d63207b4a2872ba946dc32ab56b3f98053a/conf/frpc_full_example.toml#L72
