### ISSUE TITLE
[Feature Request] 希望实现http自动跳转https

### ISSUE THREAD

**Issue by TianMiao8152** [fatedier/frp#3982]
### Describe the feature request

访问http://自动跳转到https://

### Describe alternatives you've considered

同时映射http和https隧道，然后本地设置nginx跳转

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by xqzr** [comment]
frp 大概不会实现
