### ISSUE TITLE
关于http/https问题

### ISSUE THREAD

**Issue by jinghuashang** [fatedier/frp#3983]
### Bug Description

客户端已经连接，但并被有被代理到frps上的端口，但frps却显示在线，但通过反代端口的访问却显示为
The page you requested was not found.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

The server is powered by [frp](https://github.com/fatedier/frp).

Faithfully yours, frp.

### frpc Version

0.54

### frps Version

0.54

### System Architecture

linux/amd64windows/amd64

### Configurations

[frps]
bindPort = 7000

webServer.addr = "0.0.0.0"
webServer.port = 7500

vhostHTTPPort = 8081
vhostHTTPSPort = 4433
[frpc]
[common]
 server_addr = xxxxx
 server_port = 7000
 token = xxxxx

[http]
 type = http
 local_ip = 127.0.0.1
 local_port = 5244
 custom_domains = XXXXXX

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by YummyNovaSoup** [comment]
the same. How do you resolve it?
