### ISSUE TITLE
[Feature Request] Ability to expose entire port ranges.

### ISSUE THREAD

**Issue by MaximalCats** [fatedier/frp#3984]
### Describe the feature request

Hey!

Let me start by saying that i have been using frp for almost 6 months now, and i really like it.
However, i couldn't find a feature in the documentation that would allow me to expose entire port ranges, eg: ports 8000-9000
Is this a planned feature?
Thanks

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Kamycz3q** [comment]
would be really great

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/blob/cf025d63207b4a2872ba946dc32ab56b3f98053a/conf/legacy/frpc_legacy_full.ini#L196-L202

**Comment by fatedier** [comment]
For the current architecture, exposing a large number of ports simultaneously on a frpc is not friendly and will have obvious performance issues.

In the future, other implementation methods may be considered.

**Comment by ICHx** [comment]
> https://github.com/fatedier/frp/blob/cf025d63207b4a2872ba946dc32ab56b3f98053a/conf/legacy/frpc_legacy_full.ini#L196-L202

I couldn't do this for the TOML format

```
json: cannot unmarshal string into Go struct field ClientConfig.visitors of type int
```
