### ISSUE TITLE
[Feature Request] 可以设置多个服务端吗

### ISSUE THREAD

**Issue by mosttt** [fatedier/frp#3986]
### Describe the feature request

就是服务端frps配置文件不变，可以多台服务器部署，同一客户端的配置文件，不同端口使用不同的服务端来隧穿。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
```
frpc -c 1.toml
frpc -c 2.toml
frpc -c 3.toml
```

**Comment by mosttt** [comment]
可以zhikai

> ```
> frpc -c 1.toml
> frpc -c 2.toml
> frpc -c 3.toml
> ```

可以只开一个客户端，写在一个配置文件里吗
