### ISSUE TITLE
[Feature Request] DDNS IP更新后掉线

### ISSUE THREAD

**Issue by SingletC** [fatedier/frp#3988]
### Describe the feature request

当服务端使用ddns ip变动后 client需要重启服务才能正常通信

### Describe alternatives you've considered

使用定时重启可以解决但是会有断线时间

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by MANKUD** [comment]
Hello @SingletC 

Assuming that you FRP client is a windows machine I have written a powershell script for you which you can run as a batch file by saving it as a batch file with any name. 

Run the batch scipt at regular intervals say every 5 min using windows task scheduler to automatically restart service if the IP address pointing to you DDNS changes and as a additional feature I have added automatically update DNS servers for current network adapter to cloudflare dns that is 1.1.1.1 & 1.0.0.1 and flush dns both are automatically done when the DDNS current IP address changes. 

`# 2>NUL & @CLS & PUSHD "%~dp0" & "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -nol -nop -ep bypass "[IO.File]::ReadAllText('%~f0')|iex" & POPD & EXIT /B

# Define the domain and service name
$domain = "DDNS or Static IP"
$service = "FRP Serive name"

# Function to get the current IP address of a domain
function Get-DomainIPAddress {
    $ipAddress = [System.Net.Dns]::GetHostAddresses($domain) | Where-Object {$_.AddressFamily -eq "InterNetwork"} | Select-Object -ExpandProperty IPAddressToString
    return $ipAddress
}

# Function to compare IP addresses
function Compare-IPAddresses {
    $currentIP = Get-DomainIPAddress
    $storedIP = Get-Content -Path "StoredIPAddress.txt"

    if ($currentIP -ne $storedIP) {
        # IP addresses are different, restart the service
        Restart-Service -Name $service
        Write-Output "Service $service restarted because the IP address of $domain changed."
        
        # Update the stored IP address
        $currentIP | Set-Content -Path "StoredIPAddress.txt"
        Write-Output "Stored IP address updated to $currentIP."
		
		# Define the desired DNS servers
		$desiredDNS = @("1.1.1.1", "1.0.0.1")

		# Get the current DNS settings of the network adapter connected to the internet
		$currentDNS = Get-DnsClientServerAddress -AddressFamily IPv4 | Where-Object {$_.InterfaceAlias -eq (Get-NetAdapter | Where-Object {$_.Status -eq 'Up' -and $_.MediaConnectionState -eq 'Connected'}).InterfaceAlias} | Select-Object -ExpandProperty ServerAddresses

		# Check if the current DNS settings match the desired DNS servers
		if ($currentDNS -ne $desiredDNS) {
		# Set the DNS servers to the desired values
		Set-DnsClientServerAddress -InterfaceAlias (Get-NetAdapter | Where-Object {$_.Status -eq 'Up' -and $_.MediaConnectionState -eq 'Connected'}).InterfaceAlias -ServerAddresses $desiredDNS -Confirm:$false
		Write-Output "DNS servers updated to $($desiredDNS -join ', ')"
		
		$activeAdapterName = (Get-NetAdapter | Where-Object { $_.Status -eq 'Up' -and $_.MediaConnectionState -eq 'Connected' }).Name
		Write-Output "Adapter Name: $activeAdapterName"
		Write-Output "Adapter Current DNS" "$currentDNS"
		Write-Output "Adapter Desired DNS" "$desiredDNS"
	
		} 	
		else {
				Write-Output "DNS servers are already set to $($desiredDNS -join ', '). No changes made."
			 }
		
		# Flush DNS cache
        ipconfig /flushdns
		Write-Output "DNS cache flushed."
		
    } else {
        Write-Output "No change detected in the IP address of $domain."
    }
}

# Call the function to compare IP addresses
Compare-IPAddresses

pause`

**Comment by MANKUD** [comment]
`# 2>NUL & @CLS & PUSHD "%~dp0" & "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -nol -nop -ep bypass "[IO.File]::ReadAllText('%~f0')|iex" & POPD & EXIT /B

# Define the domain and service name
$domain = "DDNS or Static IP"
$service = "FRP Serive name"

# Function to get the current IP address of a domain
function Get-DomainIPAddress {
    $ipAddress = [System.Net.Dns]::GetHostAddresses($domain) | Where-Object {$_.AddressFamily -eq "InterNetwork"} | Select-Object -ExpandProperty IPAddressToString
    return $ipAddress
}

# Function to compare IP addresses
function Compare-IPAddresses {
    $currentIP = Get-DomainIPAddress
    $storedIP = Get-Content -Path "StoredIPAddress.txt"

    if ($currentIP -ne $storedIP) {
        # IP addresses are different, restart the service
        Restart-Service -Name $service
        Write-Output "Service $service restarted because the IP address of $domain changed."
        
        # Update the stored IP address
        $currentIP | Set-Content -Path "StoredIPAddress.txt"
        Write-Output "Stored IP address updated to $currentIP."
		
		# Define the desired DNS servers
		$desiredDNS = @("1.1.1.1", "1.0.0.1")

		# Get the current DNS settings of the network adapter connected to the internet
		$currentDNS = Get-DnsClientServerAddress -AddressFamily IPv4 | Where-Object {$_.InterfaceAlias -eq (Get-NetAdapter | Where-Object {$_.Status -eq 'Up' -and $_.MediaConnectionState -eq 'Connected'}).InterfaceAlias} | Select-Object -ExpandProperty ServerAddresses

		# Check if the current DNS settings match the desired DNS servers
		if ($currentDNS -ne $desiredDNS) {
		# Set the DNS servers to the desired values
		Set-DnsClientServerAddress -InterfaceAlias (Get-NetAdapter | Where-Object {$_.Status -eq 'Up' -and $_.MediaConnectionState -eq 'Connected'}).InterfaceAlias -ServerAddresses $desiredDNS -Confirm:$false
		Write-Output "DNS servers updated to $($desiredDNS -join ', ')"
		
		$activeAdapterName = (Get-NetAdapter | Where-Object { $_.Status -eq 'Up' -and $_.MediaConnectionState -eq 'Connected' }).Name
		Write-Output "Adapter Name: $activeAdapterName"
		Write-Output "Adapter Current DNS" "$currentDNS"
		Write-Output "Adapter Desired DNS" "$desiredDNS"
	
		} 	
		else {
				Write-Output "DNS servers are already set to $($desiredDNS -join ', '). No changes made."
			 }
		
		# Flush DNS cache
        ipconfig /flushdns
		Write-Output "DNS cache flushed."
		
    } else {
        Write-Output "No change detected in the IP address of $domain."
    }
}

# Call the function to compare IP addresses
Compare-IPAddresses

pause`

**Comment by MANKUD** [comment]
# 2>NUL & @CLS & PUSHD "%~dp0" & "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -nol -nop -ep bypass "[IO.File]::ReadAllText('%~f0')|iex" & POPD & EXIT /B

# Define the domain and service name
$domain = "DDNS or Static IP"
$service = "FRP Serive name"

# Function to get the current IP address of a domain
function Get-DomainIPAddress {
    $ipAddress = [System.Net.Dns]::GetHostAddresses($domain) | Where-Object {$_.AddressFamily -eq "InterNetwork"} | Select-Object -ExpandProperty IPAddressToString
    return $ipAddress
}

# Function to compare IP addresses
function Compare-IPAddresses {
    $currentIP = Get-DomainIPAddress
    $storedIP = Get-Content -Path "StoredIPAddress.txt"

    if ($currentIP -ne $storedIP) {
        # IP addresses are different, restart the service
        Restart-Service -Name $service
        Write-Output "Service $service restarted because the IP address of $domain changed."
        
        # Update the stored IP address
        $currentIP | Set-Content -Path "StoredIPAddress.txt"
        Write-Output "Stored IP address updated to $currentIP."
		
		# Define the desired DNS servers
		$desiredDNS = @("1.1.1.1", "1.0.0.1")

		# Get the current DNS settings of the network adapter connected to the internet
		$currentDNS = Get-DnsClientServerAddress -AddressFamily IPv4 | Where-Object {$_.InterfaceAlias -eq (Get-NetAdapter | Where-Object {$_.Status -eq 'Up' -and $_.MediaConnectionState -eq 'Connected'}).InterfaceAlias} | Select-Object -ExpandProperty ServerAddresses

		# Check if the current DNS settings match the desired DNS servers
		if ($currentDNS -ne $desiredDNS) {
		# Set the DNS servers to the desired values
		Set-DnsClientServerAddress -InterfaceAlias (Get-NetAdapter | Where-Object {$_.Status -eq 'Up' -and $_.MediaConnectionState -eq 'Connected'}).InterfaceAlias -ServerAddresses $desiredDNS -Confirm:$false
		Write-Output "DNS servers updated to $($desiredDNS -join ', ')"
		
		$activeAdapterName = (Get-NetAdapter | Where-Object { $_.Status -eq 'Up' -and $_.MediaConnectionState -eq 'Connected' }).Name
		Write-Output "Adapter Name: $activeAdapterName"
		Write-Output "Adapter Current DNS" "$currentDNS"
		Write-Output "Adapter Desired DNS" "$desiredDNS"
	
		} 	
		else {
				Write-Output "DNS servers are already set to $($desiredDNS -join ', '). No changes made."
			 }
		
		# Flush DNS cache
        ipconfig /flushdns
		Write-Output "DNS cache flushed."
		
    } else {
        Write-Output "No change detected in the IP address of $domain."
    }
}

# Call the function to compare IP addresses
Compare-IPAddresses

pause

**Comment by MANKUD** [comment]
> # 2>NUL & @CLS & PUSHD "%~dp0" & "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -nol -nop -ep bypass "[IO.File]::ReadAllText('%~f0')|iex" & POPD & EXIT /B

# Define the domain and service name
$domain = "DDNS or Static IP"
$service = "FRP Serive name"

# Function to get the current IP address of a domain
function Get-DomainIPAddress {
    $ipAddress = [System.Net.Dns]::GetHostAddresses($domain) | Where-Object {$_.AddressFamily -eq "InterNetwork"} | Select-Object -ExpandProperty IPAddressToString
    return $ipAddress
}

# Function to compare IP addresses
function Compare-IPAddresses {
    $currentIP = Get-DomainIPAddress
    $storedIP = Get-Content -Path "StoredIPAddress.txt"

    if ($currentIP -ne $storedIP) {
        # IP addresses are different, restart the service
        Restart-Service -Name $service
        Write-Output "Service $service restarted because the IP address of $domain changed."
        
        # Update the stored IP address
        $currentIP | Set-Content -Path "StoredIPAddress.txt"
        Write-Output "Stored IP address updated to $currentIP."
		
		# Define the desired DNS servers
		$desiredDNS = @("1.1.1.1", "1.0.0.1")

		# Get the current DNS settings of the network adapter connected to the internet
		$currentDNS = Get-DnsClientServerAddress -AddressFamily IPv4 | Where-Object {$_.InterfaceAlias -eq (Get-NetAdapter | Where-Object {$_.Status -eq 'Up' -and $_.MediaConnectionState -eq 'Connected'}).InterfaceAlias} | Select-Object -ExpandProperty ServerAddresses

		# Check if the current DNS settings match the desired DNS servers
		if ($currentDNS -ne $desiredDNS) {
		# Set the DNS servers to the desired values
		Set-DnsClientServerAddress -InterfaceAlias (Get-NetAdapter | Where-Object {$_.Status -eq 'Up' -and $_.MediaConnectionState -eq 'Connected'}).InterfaceAlias -ServerAddresses $desiredDNS -Confirm:$false
		Write-Output "DNS servers updated to $($desiredDNS -join ', ')"
		
		$activeAdapterName = (Get-NetAdapter | Where-Object { $_.Status -eq 'Up' -and $_.MediaConnectionState -eq 'Connected' }).Name
		Write-Output "Adapter Name: $activeAdapterName"
		Write-Output "Adapter Current DNS" "$currentDNS"
		Write-Output "Adapter Desired DNS" "$desiredDNS"
	
		} 	
		else {
				Write-Output "DNS servers are already set to $($desiredDNS -join ', '). No changes made."
			 }
		
		# Flush DNS cache
        ipconfig /flushdns
		Write-Output "DNS cache flushed."
		
    } else {
        Write-Output "No change detected in the IP address of $domain."
    }
}

# Call the function to compare IP addresses
Compare-IPAddresses

pause

**Comment by SingletC** [comment]
> Hello @SingletC
> 
> Assuming that you FRP client is a windows machine I have written a powershell script for you which you can run as a batch file by saving it as a batch file with any name.
> 
> Run the batch scipt at regular intervals say every 5 min using windows task scheduler to automatically restart service if the IP address pointing to you DDNS changes and as a additional feature I have added automatically update DNS servers for current network adapter to cloudflare dns that is 1.1.1.1 & 1.0.0.1 and flush dns both are automatically done when the DDNS current IP address changes.

I much appreciate your help; I did not test the above code. But I assume it will work.
It will be easy to let the client query the IP address of a domain instead of caching it. You can close the thread if this feature seems unnecessary.

**Comment by MANKUD** [comment]
![restart proxy and update + flush dns ps1 bat](https://github.com/fatedier/frp/assets/83474708/702cf2e0-c15d-4b80-aea8-90e82d929837)

@SingletC 

I have added the batch script directly here and since it does not allow me to upload a batch scipt I have changed extension just remove the .jpg at the end and it will work.

**Comment by MANKUD** [comment]
@SingletC I am having issues sharing the code here give me some time I will post it here.

**Comment by MANKUD** [comment]
@SingletC Here  you go a link to downlod my batch script.

[https://www.zippyshare.day/ZnzuZ715lWYguC5/file](url)

**Comment by MANKUD** [comment]
let me know if this works for you. @SingletC

**Comment by superzjg** [comment]
我有一台frps（arm64）公网ip被运营商更新时，动态域名更新可能不及时，我的另外2台frpc（一台arm，一台arm64），通常会断线几分钟到十几分钟，然后自动重新连上，并不需要重启。
