### ISSUE TITLE
服务器的监听端口不能自定义？

### ISSUE THREAD

**Issue by BlueDolphin9527** [fatedier/frp#3989]
### Bug Description

我尝试把服务器监听端口从7000改成其它的，防火墙放行了这些端口，但是实测这些端口都不能正常访问。只有改回到7000才能正常运行，请问是不是源码就设定了只能运行在7000端口，如果是，能麻烦您改下源码吗？

### frpc Version

0.54.0

### frps Version

0.54.0

### System Architecture

linux/amd64

### Configurations

测试

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
怎么可能？不生效肯定是配置文件格式写错了。
你不贴出来，靠大家猜！
