### ISSUE TITLE
启动时连接服务器端超时，建议增加连接重试功能

### ISSUE THREAD

**Issue by jjldc** [fatedier/frp#399]
**What version of frp are you using (./frpc -v or ./frps -v)?**
**frpc 0.12.0**

**What operating system and processor architecture are you using (`go env`)?**
**Windows 10 amd64**

**Configures you used:**
`[common]
server_addr = 21.21.29.162
server_port = 7000
privilege_token = 113325

[telnet]
type = tcp
local_ip = 192.168.2.108
local_port = 23
remote_port = 23680
`

**Steps to reproduce the issue:**
**网络质量不佳时，连接到服务器经常超时退出。
我使用脚本将frpc设置为自启动后，有很大概率因为连接不上服务器而退出客户端，无法做到无人值守。**

**Describe the results you received:**

> dial tcp 119.23.29.152:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**建议：
目前frpc在连接到服务器后如果出现断线，有自动恢复措施，但在第一次连接失败时没有相应的重试机制。
建议增加首次连接时的重试功能，方便把frpc作为系统服务添加，实现无人值守的启动。**

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/conf/frpc_full.ini#L34

配置此参数。

**Comment by jjldc** [comment]
谢谢，文档里没看到这个参数，没注意到
已经解决了~
