### ISSUE TITLE
问一下，frps和frpc能部署在同一台机器上吗？

### ISSUE THREAD

**Issue by huangyy** [fatedier/frp#3993]
### Bug Description

frps正常启动，frpc启动报错：
xxx@home-serverr:~/program/frp$ 2024/02/15 15:45:04 [I] [root.go:142] start frpc service for config file [/home/xxx/program/frp/frpc.toml]
2024/02/15 15:45:04 [I] [service.go:287] try to connect to server...
2024/02/15 15:45:24 [W] [service.go:290] connect to server error: unexpected EOF
2024/02/15 15:45:24 [I] [root.go:160] frpc service for config file [/home/xxx/program/frp/frpc.toml] stopped
login to the server failed: unexpected EOF. With loginFailExit enabled, no additional retries will be attempted

[5]   Exit 1                  /home/xxx/program/frp/frpc -c /home/xxx/program/frp/frpc.toml

### frpc Version

0.54

### frps Version

0.54

### System Architecture

ubuntu 22.04

### Configurations

xxx@home-serverr:~/program/frp$ more frps.toml 
bindAddr = "0.0.0.0"
bindPort = 7700
auth.method = "token"
auth.token = "123456"

webServer.addr = "192.168.0.21"
webServer.port = 7701
webServer.user = "xxx"
webServer.password = "123456"

xxx@home-serverr:~/program/frp$ more frpc.toml 
serverAddr = "127.0.0.1"
serverPort = 7700
auth.method = "token"
auth.token = "123456"

[[proxies]]
name = "web"
type = "stcp"
secretKey = "123456"
localIP = "127.0.0.1"
localPort = 80

服务器的IP修改成相同的IP：192.168.0.21，一样的错误

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
可以，不冲突。

**Comment by huangyy** [comment]
那这个错误是怎么回事？实在找不出问题在哪里了，密码不能有符号？实际密码包含 & 和  .

**Comment by superzjg** [comment]
> name = "web"
> type = "stcp"
> secretKey = "123456"
> localIP = "127.0.0.1"
> localPort = 80

不知道，我在openwrt上使用你贴出来的配置文件，运行frps和frpc，正常使用，无法复现错误。
