### ISSUE TITLE
[Feature Request] Forward User IP through Server to Client for UDP

### ISSUE THREAD

**Issue by SevensRequiem** [fatedier/frp#3995]
### Describe the feature request

Forward User IP through Server to Client for UDP, and other protocols.

Instead of client showing 192.x168x.x:xxxx for each user, show real IP and ports used from server connection. 

This will enable me to:
1: Collect Data / Regional Connection Data from UDP connections
2: Be able to Permanently Ban IP's from UDP connections

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Currently not possible, but may support UDP proxy Proxy Protocol in the future.

**Comment by stromsoftware** [comment]
> Currently not possible, but may support UDP proxy Proxy Protocol in the future.

I'm willing to contribute, is there a discord server?

**Comment by fatedier** [comment]
This feature is not accepted now.
