### ISSUE TITLE
[Feature Request] Frpc连接多个Frps

### ISSUE THREAD

**Issue by TianMiao8152** [fatedier/frp#3998]
### Describe the feature request

一个Frpc连接多个Frps，同时开启不同的隧道
如127.0.0.1:10025到111.11.11.111的10025
127.0.0.1:20025到222.22.22.222的20025

### Describe alternatives you've considered

同时运行多个Frpc连接不同节点

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
使用两个配置文件，运行两个进程。
