### ISSUE TITLE
希望服务器能动态加客户端代理规则，避免重启客户端和服务器

### ISSUE THREAD

**Issue by yingnierxiao** [fatedier/frp#400]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.12.0
**What operating system and processor architecture are you using (`go env`)?**
centos 6.8

**Configures you used:**

**Steps to reproduce the issue:**
1.是否可以坐到服务器直接修改配置客户端直接更新配置，客户端不需要重启，服务器直接下发配置文件
2.
3.

**Describe the results you received:**
NO

**Describe the results you expected:**
NO

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
0.13 版本的 frpc 会支持动态更新配置文件，不需要重启 frpc。

服务端下发配置文件不会支持，有安全风险，要开放哪些端口由客户端指定。

**Comment by yingnierxiao** [comment]
还有就是能不能做下内网代理kcp到外网   实现fanqiang

**Comment by fatedier** [comment]
frp 的目的是提供内网穿透功能，你的描述不在功能列表内，有需求可以结合使用其他项目。

**Comment by yingnierxiao** [comment]
主要是客户端在内网  想远程重启客户端万一出问题了就没法连上比较麻烦
