### ISSUE TITLE
看文档发现一个小问题报告

### ISSUE THREAD

**Issue by fengyuclub** [fatedier/frp#4004]
### Bug Description

https://github.com/gofrp/frp-doc/blob/master/content/zh-cn/docs/Features/common/network/network-tls.md#frps-%E5%8D%95%E5%90%91%E9%AA%8C%E8%AF%81-frpc-%E7%9A%84%E8%BA%AB%E4%BB%BD
ini改为toml即可

### frpc Version

0.54

### frps Version

0.54

### System Architecture

linux

### Configurations

127.0.0.1

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
你可以在 frp-doc 这个 repo 中提出或直接修改。
