### ISSUE TITLE
TLS Fingerprinting

### ISSUE THREAD

**Issue by dr3adx** [fatedier/frp#4010]
### Describe the feature request

Hello,

I was wondering how does FRP work in terms of TLS fingerprinting like JA3.
Does it alter the TLS settings at all like cipher suites & extensions? If it does, is there a way I can preserve the original TLS settings?

Any info is appreciated, thank you!

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
We use the go standard library to handle TLS, without any extra logic.

**Comment by dr3adx** [comment]
> We use the go standard library to handle TLS, without any extra logic.

so that means the TLS ja3 hash will be of golang library and not of the original request?

if so, is there a way to preserve original request's JA3? because right now everybody can detect we're using FRP based on ja3, correct me if im wrong.

**Comment by fatedier** [comment]
I do not understand this knowledge, you can try to obtain information in this area from other sources.
