### ISSUE TITLE
多个 SSH 服务复用同一端口，运行报错

### ISSUE THREAD

**Issue by fsleo** [fatedier/frp#4014]
### Bug Description

ssh -o 'proxycommand socat - PROXY:106.55.x.x:%h:%p,proxyport=5002' pi@pi.dev.cn

另外customDomains这个是一定要做a记录的域名吗？
### frpc Version

0.54.0

### frps Version

0.54.0

### System Architecture

linux/aarch64

### Configurations

frps.toml:

bindPort = 7000
tcpmuxHTTPConnectPort = 5002

frpc.toml:
serverAddr = "106.55.x.x"
serverPort = 7000

[[proxies]]
name = "ssh1"
type = "tcpmux"
multiplexer = "httpconnect"
customDomains = ["pi.dev.cn"]
localIP = "127.0.0.1"
localPort = 22

### Logs

zsh:1: command not found: socat
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535

### Steps to reproduce

ssh -o 'proxycommand socat - PROXY:106.55.x.x:%h:%p,proxyport=5002' pi@pi.dev.cn

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by hby07** [comment]
必须安装socat才能正常工作
域名可以是任意的

**Comment by henryzhuhr** [comment]
想问一下，除了 `socat`，还有其他的方式吗，win上好像对 socat 的支持不是很友好
