### ISSUE TITLE
谁帮我看一下日志是哪里出问题了,FRPC

### ISSUE THREAD

**Issue by a7858250** [fatedier/frp#4016]
### Bug Description

2024/02/21 18:03:19 [I] [root.go:220] start frpc service for config file [/var/etc/frp/frpc.conf]
2024/02/21 18:03:19 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:03:19 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:03:19 [W] [control.go:257] [517e8c0ed56448be] write message to control connection error: stream closed
2024/02/21 18:03:19 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:03:19 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:03:19 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:03:19 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:03:19 [I] [control.go:252] [517e8c0ed56448be] control writer is closing
2024/02/21 18:03:19 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:03:19 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:03:19 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:03:19 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:03:19 [W] [control.go:257] [517e8c0ed56448be] write message to control connection error: write tcp 192.168.88.254:59818->36.40.237.37:9555: write: connection reset by peer
2024/02/21 18:03:19 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:03:19 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:03:19 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:03:19 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:03:19 [I] [control.go:252] [517e8c0ed56448be] control writer is closing
2024/02/21 18:03:19 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:03:20 [I] [service.go:194] [517e8c0ed56448be] wait 1s to reconnect
2024/02/21 18:03:20 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:04:30 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:04:30 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:04:30 [W] [control.go:257] [517e8c0ed56448be] write message to control connection error: stream closed
2024/02/21 18:04:30 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:04:32 [I] [service.go:194] [517e8c0ed56448be] wait 2s to reconnect
2024/02/21 18:04:32 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:04:32 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:04:32 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:04:32 [W] [control.go:257] [517e8c0ed56448be] write message to control connection error: stream closed
2024/02/21 18:04:32 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:04:32 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:04:32 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:04:32 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:04:32 [W] [control.go:257] [517e8c0ed56448be] write message to control connection error: write tcp 192.168.88.254:49460->36.40.237.37:9555: write: connection reset by peer
2024/02/21 18:04:32 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:04:33 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:04:33 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:04:33 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:04:33 [W] [control.go:257] [517e8c0ed56448be] write message to control connection error: write tcp 192.168.88.254:49462->36.40.237.37:9555: write: connection reset by peer
2024/02/21 18:04:33 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:04:33 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:04:33 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:04:33 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:04:33 [W] [control.go:257] [517e8c0ed56448be] write message to control connection error: stream closed
2024/02/21 18:04:33 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:04:34 [I] [service.go:194] [517e8c0ed56448be] wait 1s to reconnect
2024/02/21 18:04:34 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:04:34 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:04:34 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:04:34 [I] [control.go:252] [517e8c0ed56448be] control writer is closing
2024/02/21 18:04:34 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:04:36 [I] [service.go:194] [517e8c0ed56448be] wait 2s to reconnect
2024/02/21 18:04:36 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:04:36 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:04:36 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:04:36 [W] [control.go:257] [517e8c0ed56448be] write message to control connection error: stream closed
2024/02/21 18:04:36 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:04:40 [I] [service.go:194] [517e8c0ed56448be] wait 4s to reconnect
2024/02/21 18:04:40 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:04:40 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:04:40 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:04:40 [W] [control.go:257] [517e8c0ed56448be] write message to control connection error: stream closed
2024/02/21 18:04:40 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:04:49 [I] [service.go:194] [517e8c0ed56448be] wait 8s to reconnect
2024/02/21 18:04:49 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:04:49 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:04:49 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:04:49 [W] [control.go:257] [517e8c0ed56448be] write message to control connection error: stream closed
2024/02/21 18:04:49 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:05:06 [I] [service.go:194] [517e8c0ed56448be] wait 16s to reconnect
2024/02/21 18:05:06 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:05:06 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:05:06 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:05:06 [W] [control.go:257] [517e8c0ed56448be] write message to control connection error: stream closed
2024/02/21 18:05:06 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:05:39 [I] [service.go:194] [517e8c0ed56448be] wait 32s to reconnect
2024/02/21 18:05:39 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:05:39 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:05:39 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:05:39 [W] [control.go:257] [517e8c0ed56448be] write message to control connection error: stream closed
2024/02/21 18:05:39 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:05:40 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:05:40 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:05:40 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:05:40 [W] [control.go:257] [517e8c0ed56448be] write message to control connection error: stream closed
2024/02/21 18:05:40 [I] [visitor_manager.go:77] [517e8c0ed56448be] gracefully shutdown visitor manager
2024/02/21 18:05:40 [I] [service.go:214] [517e8c0ed56448be] try to reconnect to server...
2024/02/21 18:05:40 [I] [service.go:301] [517e8c0ed56448be] login to server success, get run id [517e8c0ed56448be]
2024/02/21 18:05:40 [I] [proxy_manager.go:150] [517e8c0ed56448be] proxy added: [admin.pan]
2024/02/21 18:05:40 [W] [control.go:257] [517e8c0ed56448be] write message to control connection error: write tcp 192.168.88.254:35340->36.40.237.37:9555: write: connection reset by peer

### frpc Version

0.51.3

### frps Version

0

### System Architecture

linux/amd64

### Configurations

0

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
要结合配置文件

**Comment by everydoc** [comment]
我也遇到了这个问题，配置文件都是复制的，不存在问题，就是不知道为什么断断续续的。
