### ISSUE TITLE
log.to = "./frps.log"  为何为保存在在根目录？而不是相对目录呢？

### ISSUE THREAD

**Issue by fsleo** [fatedier/frp#4017]
### Bug Description

[apps:/]$ ls
bin  boot  data  dev  etc  frps.log

### frpc Version

0.54.0

### frps Version

0.54.0

### System Architecture

linux/aarch64

### Configurations

...

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
工作路径

**Comment by fsleo** [comment]
> 工作路径

可是我的程序在 /usr/local/frp/frps.exe

**Comment by xqzr** [comment]
[apps:**/**]$
