### ISSUE TITLE
网络繁忙时，frpc断开重连提示端口被占用

### ISSUE THREAD

**Issue by jiangcare** [fatedier/frp#4023]
### Bug Description

frps在一个网络不稳定的机器上，需要接收多个节点的数据到frpc所在的机器里，在网络不好的情况下，frpc经常会端口，在重连frps的时候，可能是因为frps下面的节点持续的传输数据到frps映射的端口上，导致端口一直无法释放，frpc就提示[XXX] start error: proxy [XXX] already exists
![1708744881397](https://github.com/fatedier/frp/assets/9928128/4ce534b0-be1c-4003-9cc7-384cbe4a8d2b)

### frpc Version

0.44.0

### frps Version

0.51.3

### System Architecture

linux/arm

### Configurations

frps.ini
`[common]
bind_port = 3887
dashboard_port = 3888
log_file = /home/frp/frps.log
token = 123123123
`
frpc.ini
`[common]
server_addr = 123.123.123.123
server_port = 3887
admin_addr = 127.0.0.1
admin_port = 7400
tls_enable = false

[XXXX]
type = tcp
local_ip = 127.0.0.1
local_port = 1234
remote_port = 3333
`

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by david9991** [comment]
同样的问题。

**Comment by david9991** [comment]
好像 1.53.2 上面不发生了，还是没达到触发条件就不知道了。
