### ISSUE TITLE
frp 本地端口建议不要采用随机高端口形式，安全软件会拦截

### ISSUE THREAD

**Issue by starscow** [fatedier/frp#4025]
### Bug Description

frp 本地端口建议不要采用随机高端口形式，安全软件会拦截

### frpc Version

全版本

### frps Version

全版本

### System Architecture

全版本

### Configurations

frp 本地端口建议不要采用随机高端口形式

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
❔
