### ISSUE TITLE
FRPS 运行一段时间之后，客户端没法连接上来。

### ISSUE THREAD

**Issue by 1449489029** [fatedier/frp#4026]
### Bug Description

客户端会时不时的连接不上，每次都需要将FRPS和FRPC重启了之后才能恢复正常。这次是在 2024-02-08 重启的，节后每隔一两天测试都正常。今天再要测试时，又发现客户端连接不上了。客户端这次没有开启日志，能提供只有服务端的日志。我们想要知道的是如何避免这种情况？

### frpc Version

0.33.0

### frps Version

0.53.2

### System Architecture

linux/amd64

### Configurations

FRPC 的配置（ini格式）：

[common]
server_addr = xx.xx.xx.xx
server_port = 7000
token = 

[ssh_6002]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6002

[tcp_7830]
type = tcp
local_ip = 127.0.0.1
local_port = 8831
remote_port = 7831

FRPS 的配置（toml格式）：

bindPort = 7000
auth.token=

### Logs

2024/02/25 15:19:01 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58850][0m
2024/02/25 15:19:01 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58858][0m
2024/02/25 15:19:01 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [49.52.46.232:40348][0m
2024/02/25 15:19:01 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58860][0m
2024/02/25 15:19:02 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58870][0m
2024/02/25 15:19:02 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [172.105.89.240:48344][0m
2024/02/25 15:19:02 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58886][0m
2024/02/25 15:19:02 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [172.105.89.240:48300][0m
2024/02/25 15:19:02 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [49.52.46.232:37873][0m
2024/02/25 15:19:02 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58892][0m
2024/02/25 15:19:02 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58896][0m
2024/02/25 15:19:02 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58902][0m
2024/02/25 15:19:02 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58912][0m
2024/02/25 15:19:02 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [49.52.46.232:37525][0m
2024/02/25 15:19:02 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [172.105.89.240:48312][0m
2024/02/25 15:19:02 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58914][0m
2024/02/25 15:19:02 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [172.105.89.240:48368][0m
2024/02/25 15:19:02 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58926][0m
2024/02/25 15:19:02 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:02 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:03 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:03 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:03 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58932][0m
2024/02/25 15:19:03 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [49.52.46.232:56287][0m
2024/02/25 15:19:03 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [172.105.89.240:48374][0m
2024/02/25 15:19:03 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58936][0m
2024/02/25 15:19:03 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:03 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:03 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:03 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:03 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58942][0m
2024/02/25 15:19:03 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:03 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:03 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:03 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:03 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [172.105.89.240:48358][0m
2024/02/25 15:19:03 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58954][0m
2024/02/25 15:19:03 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:03 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:03 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:03 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:03 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [49.52.46.232:54573][0m
2024/02/25 15:19:03 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:58970][0m
2024/02/25 15:19:03 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [172.105.89.240:48392][0m
2024/02/25 15:19:03 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m

...

2024/02/25 15:19:20 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:20 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:20 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:20 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [49.52.46.232:37501][0m
2024/02/25 15:19:20 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:20 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:20 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:20 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:20 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:42536][0m
2024/02/25 15:19:20 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:20 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:20 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:20 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:20 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:42544][0m
2024/02/25 15:19:20 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [172.105.89.240:60212][0m
2024/02/25 15:19:20 [1;33m[W] [control.go:289] [700cc5281cd63e1a] timeout trying to get work connection[0m
2024/02/25 15:19:20 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: timeout trying to get work connection[0m
2024/02/25 15:19:20 [1;34m[I] [proxy.go:204] [700cc5281cd63e1a] [ssh_6002] get a user connection [185.125.50.214:37080][0m
2024/02/25 15:19:21 [1;34m[I] [proxy.go:115] [700cc5281cd63e1a] [ssh_6002] proxy closing[0m
2024/02/25 15:19:21 [1;33m[W] [control.go:283] [700cc5281cd63e1a] no work connections available, control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [proxy.go:201] [700cc5281cd63e1a] [ssh_6002] listener is closed: accept tcp [::]:6002: use of closed network connection[0m
2024/02/25 15:19:21 [1;34m[I] [proxy.go:115] [700cc5281cd63e1a] [tcp_7830] proxy closing[0m
2024/02/25 15:19:21 [1;33m[W] [proxy.go:201] [700cc5281cd63e1a] [tcp_7830] listener is closed: accept tcp [::]:7831: use of closed network connection[0m
2024/02/25 15:19:21 [1;34m[I] [control.go:359] [700cc5281cd63e1a] client exit success[0m
2024/02/25 15:19:21 [1;33m[W] [control.go:283] [700cc5281cd63e1a] no work connections available, control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [control.go:283] [700cc5281cd63e1a] no work connections available, control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [control.go:283] [700cc5281cd63e1a] no work connections available, control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [control.go:283] [700cc5281cd63e1a] no work connections available, control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [control.go:283] [700cc5281cd63e1a] no work connections available, control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [control.go:283] [700cc5281cd63e1a] no work connections available, control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [control.go:283] [700cc5281cd63e1a] no work connections available, control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [control.go:283] [700cc5281cd63e1a] no work connections available, control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [control.go:283] [700cc5281cd63e1a] no work connections available, control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [control.go:283] [700cc5281cd63e1a] no work connections available, control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [control.go:283] [700cc5281cd63e1a] no work connections available, control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [control.go:283] [700cc5281cd63e1a] no work connections available, control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [control.go:283] [700cc5281cd63e1a] no work connections available, control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [proxy.go:128] [700cc5281cd63e1a] [ssh_6002] failed to get work connection: control is closed[0m
2024/02/25 15:19:21 [1;33m[W] [control.go:283] [700cc5281cd63e1a] no work connections available, control is closed[0m

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by 1449489029** [comment]
是还需要提供什么数据吗？

**Comment by heguangzhi** [comment]
frps  和 fpc 版本是否一致？

**Comment by 1449489029** [comment]
frps 和 fpc 版本不是一致的，FRPC：0.33.0，FRPS：0.53.2

**Comment by Puqns67** [comment]
> frps 和 fpc 版本不是一致的，FRPC：0.33.0，FRPS：0.53.2

更新 frpc 后能否复现？你这个 frpc 实在是有点太老了

**Comment by 1449489029** [comment]
好的, 我试一下
