### ISSUE TITLE
P2P Mode 文档错误

### ISSUE THREAD

**Issue by KevinWang15** [fatedier/frp#4027]
文档没问题，是我理解错了，当时想要转发多个端口，所以我在frpc.ini中用了

```
[[proxies1]]
[[proxies2]]
...
```

我以为[[]]里面的是Proxy的名字可以随便起

但是不是的，必须按照文档写 `[[proxies]]`、`[[visitors]]`才可以生效

不好意思打扰了

以下是原Issue，请忽视

---

### Bug Description

~~根据文档中`P2P Mode`配置xtcp，会得到Connection refused~~

```
root@...:~# curl 127.0.0.1:26666
curl: (7) Failed to connect to 127.0.0.1 port 26666 after 0 ms: Connection refused
```

~~把frpc换成使用命令行flags启动，可以正常工作~~

```
./frpc xtcp --server-addr ... --server-port 37006 -n p2p_ssh --local-ip 127.0.0.1 --local-port 22
./frpc xtcp visitor --server-addr ... --server-port 37006 --server-name p2p_ssh -n p2p_ssh_visitor --bind-port 26666 --bind-addr 127.0.0.1
```

```
root@...:~# curl 127.0.0.1:26666
curl: (1) Received HTTP/0.9 when not allowed
```

~~怀疑是文档写错了？~~

### frpc Version

0.54.0

### frps Version

0.54.0

### System Architecture

linux/amd64

### Configurations

```ini
serverAddr = ....
serverPort = 37006

[[proxies1]]
name = "p2p_ssh"
type = "xtcp"
localIP = "127.0.0.1"
localPort = 22
```

---

```ini
serverAddr = ....
serverPort = 37006


[[visitors1]]
name = "p2p_ssh_visitor"
type = "xtcp"
serverName = "p2p_ssh"
bindAddr = "127.0.0.1"
bindPort = 26666
```

---

```ini
[common]
bind_port = 37006
bind_udp_port = 37007
allow_ports = 37008

admin_user = admin
admin_pwd = ....
```

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
~~[common]~~

**Comment by KevinWang15** [comment]
> ~[common]~

之前多了一个[common]的确是我疏忽

我把common去掉了，还是一样的效果（我更新了PR）

以及没有任何错误日志

**Comment by yiliufeng168** [comment]
我遇到了类似情况

**Comment by KevinWang15** [comment]
文档没问题，是我理解错了，当时想要转发多个端口，所以我在frpc.ini中用了

```
[[proxies1]]
[[proxies2]]
...
```

我以为[[]]里面的是Proxy的名字可以随便起

但是不是的，必须按照文档写 `[[proxies]]`、`[[visitors]]`才可以生效

不好意思打扰了

**Comment by KevinWang15** [comment]
之所以犯这个错，是因为我的配置文件是从比较早期的frp配置文件改过来的，那个时候，是定义

```
[proxy1]
...

[proxy2]
...
```

方括号里的内容的确是可以随意指定的名称

---

但是后来配置改了，需要提供指定名称的数组

`[[key]]`是用来定义数组的

```
[[visitors]]
name = "visitor1"

[[visitors]]
name = "visitor2"
```

用来定义长度为2的名称为visitors的数组

---

这个主要是我弄错了

不过或许加一个校验，比如启动时报错 配置文件里有不认识的参数 也会有帮助
