### ISSUE TITLE
Dashboard使用官网文档的配置frps.toml方法无效，到底应该怎么配置？

### ISSUE THREAD

**Issue by taony** [fatedier/frp#4029]
### Bug Description

按照官网文档：https://gofrp.org/zh-cn/docs/features/common/ui/ ，配置frps.toml

### frpc Version

V 0.54.0

### frps Version

V 0.54.0

### System Architecture

linux/amd64

### Configurations

按照官网文档配置的不生效
```
# frps.toml
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"
```

但是使用 frps.ini 的配置参数可以生效：

```
# frps.ini
[common]
bind_port = 7000
vhost_http_port = 7001

dashboard_port = 7005
dashboard_user = admin
dashboard_pwd = admin
```

请问到底应该怎么配置0.54.0的配置？

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by e282486518** [comment]
TOML格式语法: https://toml.io/cn/v1.0.0

# frps.toml
[webServer]
port = 7500
user = "admin"
password = "admin"

或者
webServer = { port = 7500, user = "admin", password = "admin" }

**Comment by taony** [comment]
使用这个配置：
```
bindPort = 7000

[webServer]
port = 7005
user = "admin"
password = "admin"
```

启动后提示是成功的，但是网页上打开就是空白的。
```
[root@ubuntu frp]# ./frps -c frps.toml
2024/02/28 13:49:07 [I] [root.go:105] frps uses config file: frps.toml
2024/02/28 13:49:07 [I] [service.go:225] frps tcp listen on 0.0.0.0:7000
2024/02/28 13:49:07 [I] [root.go:114] frps started successfully
2024/02/28 13:49:07 [I] [service.go:338] dashboard listen on 127.0.0.1:7005

```

**Comment by TLSMars** [comment]
这个就是成功了 dashboard监听在7005端口 浏览器输入ip:7005应该就能看到的

**Comment by Recopec** [comment]
#3709 
It could be fixed by adding webServer.addr = "0.0.0.0" to Configurations

**Comment by superzjg** [comment]
> 使用这个配置：
> 
> ```
> bindPort = 7000
> 
> [webServer]
> port = 7005
> user = "admin"
> password = "admin"
> ```
> 
> 启动后提示是成功的，但是网页上打开就是空白的。
> 
> ```
> [root@ubuntu frp]# ./frps -c frps.toml
> 2024/02/28 13:49:07 [I] [root.go:105] frps uses config file: frps.toml
> 2024/02/28 13:49:07 [I] [service.go:225] frps tcp listen on 0.0.0.0:7000
> 2024/02/28 13:49:07 [I] [root.go:114] frps started successfully
> 2024/02/28 13:49:07 [I] [service.go:338] dashboard listen on 127.0.0.1:7005
> ```

你的日志很明显说明dashboard已经开启了 127.0.0.1:7005的监听，但是要知道127.0.0.1是本机地址，只有在本机才能访问。如果是远程访问，需要改地址配置：`webServer.addr`

**Comment by taony** [comment]
```
#frp服务仪表板配置
webServer.port = 7300 
webServer.addr = "0.0.0.0" 
webServer.user = "admin" 
webServer.password = "admin" 
```
综上，使用这个配置方式可以
