### ISSUE TITLE
在手机上支持所有端口的转发

### ISSUE THREAD

**Issue by zhubinsheng** [fatedier/frp#4030]
### Describe the feature request

1.在手机上支持所有端口的流量转发，包括任何tcp和udp
2.在代理端支持所有端口的转发
如此一来，是不是实现了vpn的功能，因为所有端口的所有连接都被转发了，比如tcp的连接状态也都可以转发

存在以下问题：
1.现有的代码能否经过极小的改动实现此种功能？即打开所有端口即可
2.如ssh的秘钥 https的证书如何在代理端使用client的证书秘钥呢？

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by fatedier** [comment]
直接使用 vpn
