### ISSUE TITLE
register control error: token in login doesn't match token from configuration in v0.54.0

### ISSUE THREAD

**Issue by tcexeexe** [fatedier/frp#4031]
### Bug Description

error in sevice
`2024/02/28 10:09:07 [W] [service.go:433] register control error: token in login doesn't match token from configuration`
error in client
```
2024/02/28 10:09:07 [I] [root.go:160] frpc service for config file [frpc.toml] stopped
login to the server failed: token in login doesn't match token from configuration. With loginFailExit enabled, no additional retries will be attempted
```
Do you know what's wrong with it?

### frpc Version

0.54.0

### frps Version

0.54.0

### System Architecture

linux/amd64

### Configurations

frpc:
```
serverAddr = "xx.xx.xx.xx"
serverPort = xxxx
auth.token = "abc"

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000
```
frps:
```
[common]
bind_port = 20000
auth.method = "token"
auth.token = "abc"
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [x] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
~~[common]~~
`bindPort = 20000`

**Comment by MiuKaShi** [comment]
I found that even it connected successfully, I still get 
`[service.go:433] register control error: token in login doesn't match token from configuration`
bug ?

**Comment by linyuxuanlin** [comment]
I meet the same issue in 0.54.0, with no token I can connect normally. But with the same token configured both on frps and frpc, I can't connect. The error message is:
```
login to the server failed: token in login doesn't match token from configuration. With loginFailExit enabled, no additional retries will be attempted
```
