### ISSUE TITLE
Using frp v0.52.3 keeps showing login server failure: connection write timeout

### ISSUE THREAD

**Issue by M3GUMI** [fatedier/frp#4032]
### Bug Description

The server logs are not receiving frp requests from the client, and the client logs are reporting connection write timeout. when using the tcp protocol or changing enableTLS to false, I still can't connect. I tested the server with telnet and port 7000 is open.

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

frps:
bindPort = 7000
kcpBindPort = 7000
--------------------------------------
frpc:
serverAddr = "x.x.x.x"
serverPort = 7000
enableTLS = true
transport.protocol = "kcp"

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = xxx

### Logs

server:
[root.go:102] frps uses config file: frps.toml
[service.go:200] frps tcp listen on 0.0.0.0:7000
[service.go:210] frps kcp listen on udp 0.0.0.0:7000
[root.go:111] frps started successfully
-------------------------------------------
client:
[root.go:139] start frpc service for config file [frpc.toml]
[service.go:131] login to server failed: connection write timeout
[root.go:154] frpc service for config file [frpc.toml] stopped
-------------------------------------------
It doesn't look like the server is receiving frp requests from the client. It also still doesn't connect when I use the tcp protocol, and when I change enableTLS to false. I tested the server with telnet and port 7000 is open.

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
根据你给出的配置，需要防火墙开放 **UDP** 7000。
`telnet` 测试通过，是因为它 **TCP** 7000
