### ISSUE TITLE
TLS handshake error from xxxxx | frp:EOF 一种可能的解决方法

### ISSUE THREAD

**Issue by ChouYih** [fatedier/frp#4033]
### Bug Description

这两天可能因为升级了系统还是什么原因，导致我用一些工具上传图片和文章到我的博客上时会发生TLS 握手错误，但是访问的时候显示证书是有效的，猜测可能是中间证书有问题。因为我用https转http插件中只配了服务器证书。
解决方法：将服务器证书certificate和ca证书包ca_bundle直接合并，作为新的证书。
虽然不知道之前没有这样做为什么没有导致TLS握手问题，但问题还是解决了，希望能给别人带来帮助。

### frpc Version

0.51.1

### frps Version

0.51.1

### System Architecture

linux/amd64

### Configurations

证书配置

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by actonknowledge** [comment]
> ### Bug Description
> 这两天可能因为升级了系统还是什么原因，导致我用一些工具上传图片和文章到我的博客上时会发生TLS 握手错误，但是访问的时候显示证书是有效的，猜测可能是中间证书有问题。因为我用https转http插件中只配了服务器证书。 解决方法：将服务器证书certificate和ca证书包ca_bundle直接合并，作为新的证书。 虽然不知道之前没有这样做为什么没有导致TLS握手问题，但问题还是解决了，希望能给别人带来帮助。

https转https除了给服务器配置证书，还需要给客户端配置证书吗？
