### ISSUE TITLE
[Feature Request] How to work with vs code

### ISSUE THREAD

**Issue by garrisonz** [fatedier/frp#4034]
### Describe the feature request

As description in README
```
To access server B from another machine through server A via SSH (assuming the username is test), use the following command:
ssh -oPort=6000 test@x.x.x.x
```

But, how to set this in vs code ?
vs code setting ssh configuration in ~/.ssh/config file, which do not support `-oPort=6000` parameter
Then, How can I use vs code with frp ?? Thansk

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [X] Others

**Comment by fatedier** [comment]
You might want to try searching for VS Code tutorials or open an issue for vscode.

This is a question unrelated to this project.
