### ISSUE TITLE
[Feature Request] Support for proxy https over http / 支持使用http代理https

### ISSUE THREAD

**Issue by yuxiaolejs** [fatedier/frp#4041]
### Describe the feature request

For some reason, I have some local services that's only willing to work over https (for example ESXI), and since my cloud server is configured to accept frp proxy via http, and then use nginx to expose to the public internet (with https), I need a way to let frps accept requests using http while frpc forwards it to a web server running https. I have explored so many ways but now the only solution is to add a middle layer of proxy that converts https to http. Really hope FRP can support this.

出于某些原因我需要把用http的代理访问https的服务，因为某些服务只能在https上用（说的就是ESXI）。我的云服务器配置是由FRP代理http流量后使用nginx反代到公网（同时转为https）。所以我需要frps接受http请求后由frpc转发到运行https协议的服务器上。目前探索了一些方法，不过最后只好再加一层代理，把https先转成http。真心希望FRP能支持这个功能。

### Describe alternatives you've considered

add a middle layer of proxy that converts https to http

再加一层代理，把https先转成http

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://gofrp.org/zh-cn/docs/reference/client-plugin/#http2httpspluginoptions
