### ISSUE TITLE
[Feature Request] 两个不同网段的客户端如何进行互相访问？（不通过公网IP）

### ISSUE THREAD

**Issue by 510846** [fatedier/frp#4042]
### Describe the feature request

FRPS  公网 IP: 202.1.1.1

FRPC A      192.168.1.10/24
FRPC B      192.168.2.10/24

Q: FRPC A & B 这两个客户端之间可以通过非公网IP 来进行互访吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by EnderAvaritia** [comment]
看看stcp

**Comment by heguangzhi** [comment]
通过P2P方式可以。

**Comment by 510846** [comment]
> 通过P2P方式可以。

非常感谢指导！

P2P 的话，就不经过服务端了

我是想知道，有没有一种方式，可以从 frpc A 端 访问 frpc B 端，需要经过服务端，但访问方式希望不是 公网ip:端口号 这种外部连接的方式

**Comment by lee-cq** [comment]
https://gofrp.org/zh-cn/docs/features/stcp-sudp/
