### ISSUE TITLE
[Feature Request] 有没有统一管理 frpc配置文件的方案

### ISSUE THREAD

**Issue by zxjzzz** [fatedier/frp#4046]
### Describe the feature request

想在 服务端统一管理 frpc的配置文件 

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by YouZiFeiLe** [comment]
我是在家庭内网中搭建了一整套Gitlab的CICD流程，使用Gitlab管理Frp的版本和配置文件的内容，每次只需要在Git上修改对应的内容，然后加TAG就自动发版更新FRPC或者FRPS了。
虽然有点大炮打蚊子，但是确实是一种很方便的方法

**Comment by wujingquan** [comment]
https://github.com/VaalaCat/frp-panel
