### ISSUE TITLE
frpc 客户端配置文件错误

### ISSUE THREAD

**Issue by liu523** [fatedier/frp#405]
./frpc -v 0.13.0 在读取配置文件时读的文件名为 ./frps.ini  正确的应该是 ./frpc.ini

**Comment by fatedier** [comment]
Got，是有问题，用 `-c` 参数指定吧。

**Comment by asdf3309** [comment]
我说怎么配置还是访问0.0.0.0，，~windows建个快捷方式，后面指定配置

**Comment by stupboy** [comment]
我也是试了几次发现不行，在dos界面运行才看到报错内容,frpc的配置文件和服务端一样都是frps.ini
