### ISSUE TITLE
[Feature Request] 服务器本来有个tcp端口服务的，我想用它转quic协议的客户端去访问它，怎么实现？比如服务器那个端口不对外开放，我怎么进行转发它的端口的内容？

### ISSUE THREAD

**Issue by etimes2008** [fatedier/frp#4058]
### Describe the feature request

[Feature Request] 服务器本来有个tcp端口服务的，我想用它转quic协议的客户端去访问它，怎么实现？比如服务器那个端口不对外开放，我怎么进行转发它的端口的内容？

frps取获取服务器里比如22的ssh服务，转为quic协议传到frpc的客户端里？
这个功能本身可以实现了还是没有？
有的话我怎么配置？
frps跟frpc的配置是？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
不应由 frp 实现
