### ISSUE TITLE
Failed to connect docker frps

### ISSUE THREAD

**Issue by Zonciu** [fatedier/frp#406]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.13.0

**What operating system and processor architecture are you using (`go env`)?**
Server: Centos 7 amd64
Client: Win10 amd64

frpc.ini
```
[common]
server_addr = server ip
server_port = 7000
```

# Run frps in host
frps.ini
```
[common]
bind_addr = server ip
bind_port = 7000
```
Result: Success

# Run frps in docker container
## Config 1
frps.ini
```
[common]
bind_addr = server ip
bind_port = 7000
```
Result: 
frps error, `bind: cannot assign requested address`

## Config 2
frps.ini
```
[common]
bind_addr = 127.0.0.1
bind_port = 7000
```
Docker add `net="host"` config
Result: 
Client error, `login to server failed:  No connection could be made because the target machine actively refused it.`

## Config 3
frps.ini
```
[common]
bind_addr = server ip
bind_port = 7000
```
Docker add `net="host"` config
Result: 
Server error: ` Read error, read: connection reset by peer`
Client error: `login to server failed: i/o timeout`

**Comment by fatedier** [comment]
如果你认为这是一个 bug，指出可能存在的错误，否则自己排查下对于 docker 和 frp 的使用姿势是否有问题。
