### ISSUE TITLE
web页面似乎无法通过外网访问

### ISSUE THREAD

**Issue by Ljtyxhc** [fatedier/frp#4062]
### Bug Description

在外网frps主机上telnet 对应127.0.0.1的端口是通的
但telnet 对应公网ip的端口却不行

### frpc Version

0.55.1

### frps Version

0.55.1

### System Architecture

linux/amd64

### Configurations

改善映射端口的对应设施

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by shookM** [comment]
主机对应的端口已开放？

**Comment by PctAIGM** [comment]
```
[webServer]
addr="0.0.0.0"
```
看看有没有这个配置，默认是127.0.0.1
