### ISSUE TITLE
服务端0.55.1版本tls.force参数报错

### ISSUE THREAD

**Issue by 6baobao9** [fatedier/frp#4071]
### Bug Description

服务端更新至0.55.1后启动报错
``json: unknown field "tls"``

去除配置文件中的`tls.force = true`服务启动正常

### frpc Version

0.55.1

### frps Version

0.55.1

### System Architecture

linux/amd64

### Configurations

tls.force = true

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp?tab=readme-ov-file#tls
