### ISSUE TITLE
vhostHTTPPort 只能设置成8080么

### ISSUE THREAD

**Issue by CloudMW** [fatedier/frp#4075]
### Bug Description

我将vhostHTTPPort设置为其他端口，比如4444等都不行，只能设置成8080才可以

### frpc Version

0.55.1

### frps Version

0.55.1

### System Architecture

ubuntu/amd64

### Configurations

bindPort = 7000
auth.token =  
webServer.addr = "127.0.0.1"
webServer.port = 17001
webServer.user = "admin"
webServer.password = "admin"
subdomainHost = "xxx.xxx"
vhostHTTPPort = 444

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by bingxl** [comment]
检查防火墙，检查云服务器的安全策略有没有开放对应端口
