### ISSUE TITLE
请求给出 frpc 作为 socks5 代理服务器的详细配置文件示例。

### ISSUE THREAD

**Issue by bywenshu** [fatedier/frp#4076]
### Describe the feature request

如题，要求使用 frpc 作为 socks5 代理服务器，并能访问外网。感谢解答。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Hanson** [comment]
@junbujianwpl 你这个配置是客户端还是服务端的
