### ISSUE TITLE
service unit服务单元

### ISSUE THREAD

**Issue by datafeng** [fatedier/frp#4079]
### Bug Description

以前那个开启systemctl管理的服务单元脚本在新版本里为什么找不到了？

### frpc Version

0.54

### frps Version

0.54

### System Architecture

linux/amd64

### Configurations

以前那个开启systemctl管理的服务单元脚本在新版本里为什么找不到了？

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
不再提供

**Comment by ShulkerSakura** [comment]
能问一下是什么原因导致不再提供默认的systemd服务文件了呢

**Comment by fatedier** [comment]
> 能问一下是什么原因导致不再提供默认的systemd服务文件了呢

之前应该有 issue 说明过。此类部署脚本或配置，一旦由官方提供，会有很多人会根据各自的需要提交各种更新，这些都需要开发者去 review 测试、验证，花费精力。当前并没有过多的精力放在这一部分。

**Comment by piwawa** [comment]
> > 能问一下是什么原因导致不再提供默认的systemd服务文件了呢
> 
> 之前应该有 issue 说明过。此类部署脚本或配置，一旦由官方提供，会有很多人会根据各自的需要提交各种更新，这些都需要开发者去 review 测试、验证，花费精力。当前并没有过多的精力放在这一部分。

那官方默认的systemd启动脚本是啥，我正在找这个配置，网上各种魔改版本太多
