### ISSUE TITLE
服务端可以正常访问客户端的网站，但网站中某个存在webSocket请求的页面无法被穿透访问

### ISSUE THREAD

**Issue by zhuminquan** [fatedier/frp#4080]
### Bug Description

1.  服务端可以正常访问客户端的网站
2.  但是客户端网站的某一个页面中使用了webSocket请求，导致该页面一直无法被穿透访问。
3.  网页报错信息为：WebsocketConnection WebSocket onerror
4.  经过测试可以确定本地访问是没问题的
5.  我看issues#2199已解决webSocket问题，但是0.55.1版本（截止目前是最新版）还存在此问题

### frpc Version

0.55.1

### frps Version

0.55.1

### System Architecture

服务器：linux/amd64  客户端： windows/amd64

### Configurations

客户端配置: frpc.ini
serverAddr = "*.*.*.*"
serverPort = 7000

[[proxies]]
name = "web"
type = "http"
localIP = "127.0.0.1"
localPort = 7861
customDomains =  ["www.xxxxxx.com"]

服务器配置: frps.toml
bindPort = 7000
vhostHttpPort = 8090

服务端Nginx配置：
server {
        listen       443 ssl http2;
        listen       [::]:443 ssl http2;
        server_name  _;
        root         /usr/share/nginx/html;
        
        ssl_certificate "/etc/pki/tls/********.com.pem";
        ssl_certificate_key "/etc/pki/tls//********..com.key";
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
        ssl_prefer_server_ciphers on;
        
        location / {
            proxy_pass http://127.0.0.1:8090;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_ssl_server_name on;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
}

### Logs

日志没有报错

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by dzsdbsdxq** [comment]
ng加上下面配置试试
`
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
`
