### ISSUE TITLE
[Feature Request] frp会被一些安全软件识别到

### ISSUE THREAD

**Issue by datafeng** [fatedier/frp#4082]
### Describe the feature request

如题，frp会被一些像例如深信服啊之类的安全软件识别到，是否可以通过修改frp源码什么地方，然后重新编译而不被识别到是frp吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
不在此项目的讨论范围内，建议不要在不允许使用的环境下使用。
