### ISSUE TITLE
Connection to FRPS via socks5

### ISSUE THREAD

**Issue by paolosezart** [fatedier/frp#4083]
### Describe the feature request

Here https://github.com/fatedier/frp?tab=readme-ov-file#connecting-to-frps-via-proxy shows an example how to connect FRPC to FRPS via http proxy. 
Is it possible to connect via socks5?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [X] Others

**Comment by fatedier** [comment]
Yes, like this: https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml#L92

**Comment by passioncsu** [comment]
is that support stcp type? 

[[proxies]]
name = "plugin_socks5"
type = "stcp"
[proxies.plugin]
type = "socks5"
