### ISSUE TITLE
json: unknown field "vhostHTTPSPort"

### ISSUE THREAD

**Issue by Jaydenha09** [fatedier/frp#4089]
### Bug Description

json: unknown field "vhostHTTPSPort"

### frpc Version

0.55.1

### frps Version

0.55.1

### System Architecture

server: linux/amd64, client: windows/amd64

### Configurations

# frpc_https.toml
serverAddr = "x.x.x.x"
serverPort = 7000
vhostHTTPSPort = 443

[[proxies]]
name = "https2http"
type = "https"
customDomains = ["mydomain"]

[proxies.plugin]
type = "https2http"
localAddr = "192.168.5.111:5000"
crtPath = "./server.crt"
keyPath = "./server.key"
hostHeaderRewrite = "192.168.5.111"
requestHeaders.set.x-from-where = "frp"

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by jikunchong** [comment]
# frps.toml
vhostHTTPSPort = 443

**Comment by xqzr** [comment]
`vhostHTTPSPort` 不在 frpc

**Comment by xqzr** [comment]
> Enable HTTPS for a local HTTP(S) service ![image](https://private-user-images.githubusercontent.com/64531014/324874988-651d7be1-6351-41b4-af97-c0c6b69c0a5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODQ3NTcsIm5iZiI6MTcxMzg4NDQ1NywicGF0aCI6Ii82NDUzMTAxNC8zMjQ4NzQ5ODgtNjUxZDdiZTEtNjM1MS00MWI0LWFmOTctYzBjNmI2OWMwYTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE1MDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NTMwOWYwY2VmMzMxOTJmZWE0Nzg1YzFkMDYzODYwMjJhOTE4MDk3YjJkMjZkZmY4Y2M4OTUzM2RjNDM0ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eIk0NjlkP1paiAsUTFv-tmtBNWHPpYIufwMPH5tNb6Y) vhostHTTPSPort = 443 文档写错了 按照实例写的话提示 json: unknown field "vhostHTTPSPort" @fatedier

可以自行更改文档
