### ISSUE TITLE
能否增加一种瘦客户端的模式?

### ISSUE THREAD

**Issue by chenall** [fatedier/frp#409]
为的是解决如下问题:
1. 客户端比较多时不好管理.
2. 有一些服务不想暴露出来,在需要使用的时候登录服务器配置一下就可以使用,用完了继续保持关闭禁用状态,避免服务长期开启被攻击入侵等.

我的思路大致如下.

瘦客户端: 客户端只配置了使用模式为瘦客户端和user信息用于识别客户端

这个客户端连接到服务器之后,可以通过服务器的统一操作管理界面来操作增加一些应用配置信息并且可以随时设置为启用或禁用状态.

**Comment by wxlg1117** [comment]
可能性不大,刚转为唯一功能的PrivilegeMode功用刚好和你的要求相反...
