### ISSUE TITLE
Windows server 2008 R2 企业版下，frps运行不起来

### ISSUE THREAD

**Issue by blue8228** [fatedier/frp#4090]
### Bug Description

运行后直接报异常，信息如下：
E:\server\frp>frps -v
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x22fcf8)
        runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x47ab9a
rax     0x0
rbx     0x1596bd8
rcx     0x161ee68
rdx     0x20
rdi     0x7fffffdc000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x2eba2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0x1595bc0
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

### frpc Version

0.55.1

### frps Version

0.55.1

### System Architecture

Windows server 2008 R2 企业版

### Configurations

无设置

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
似乎不支持

**Comment by JunXiaoRuo** [comment]
> 似乎不支持

frp_0.51.3可以运行
