### ISSUE TITLE
Linux上如何使用非root用户运行服务端？

### ISSUE THREAD

**Issue by milkbrother666** [fatedier/frp#4093]
### Bug Description

现在可以支持以非特权用户或sudo的方式运行吗？比如指定nobody/nogroup运行。

### frpc Version

0.55.1

### frps Version

0.55.1

### System Architecture

linux/amd64

### Configurations

```
#bindPort = 7000
bindPort = 22888

# log
log.to = "/var/log/frp/frps.log"
log.level = "info"
log.maxDays = 30
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
监听 1024 及以上的端口号
