### ISSUE TITLE
[Feature Request] Can provide a converter from ini to toml?

### ISSUE THREAD

**Issue by WangNingkai** [fatedier/frp#4095]
### Describe the feature request

if ini format is deprecated and the support will be removed in the future,Can provide a converter from ini to toml?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Currently, there is no capacity to provide such additional tools. Perhaps others may be able to offer third-party tools to achieve this functionality.
