### ISSUE TITLE
Unable to start frpc on client

### ISSUE THREAD

**Issue by foilandwater** [fatedier/frp#4098]
### Bug Description

I have used frps and frpc on a few raspberry pi's and it works very well. It's a very nice app, thank you. My requirement is simple, I have a few weather stations that we use for wind speed and direction and each one is managed by a raspberry pi. I use frp for being able to log in remotely and manage the pi's.

I have about 5 working devices over the last 2 years so I have a basic understanding of how to set it up. However, now I'm preparing a new pi and I cannot get it to connect to the server. I have spent lots of time with no success, which is why I am reaching for assistance. I notice that frp has had a lot of updates since I started using it, so maybe an incompatibility between the new client and the old server? Or else, maybe raspberry pi OS has evolved and now has some kind of blocked port of something? I did try open the ports but maybe I did it wrong. I'm sorry, my knowledge is limited so I cannot troubleshoot it further.

The error I am getting when I try run frpc directly is: (I have removed the server name for security reasons)
2024-03-23 09:49:17.919 [W] [client/service.go:297] connect to server error: read tcp 192.168.1.216:45282->x.x.x.x:7000: read: connection reset by peer

I wanted to try updating frps server on the digital ocean droplet which is currently on 0.17.0 but I was afraid that it would impact the connection for the other weather stations that are currently working.

I have made a donation via paypal. Thanks again for this great app.

Would appreciate any support or suggestions, thank you!

### frpc Version

0.56.0

### frps Version

0.17.0

### System Architecture

linux/amd64, linux/arm64

### Configurations

The fps.ini is: (I have removed the token for security reasons)
[common]
bind_port = 7000
tcp_mux = false
authentication_method = token
token = x

The frpc.toml is: (I have removed the server name and token for security reasons)
# frpc.toml
user = "sean"
serverAddr = "x.x.x.x"
serverPort = 7000
auth.method = "token"
auth.token = "x"
loginFailExit = false
transport.tcpMux = false

[[proxies]]
name = "yas"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6037

### Steps to reproduce

1. Create new pi installation using raspberry pi imager for MacOS
2. Insert SD card into pi and boot
3. Log in via ssh
4. Install frpc and set up .toml file
5. Run frpc directly and then get errors

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by foilandwater** [comment]
Just to update on this issue, I downloaded an older version for the client (ie. 0.24.0) and then the connection is successful.

**Comment by cnpcshangbo** [comment]
> ### Bug Description
> I have used frps and frpc on a few raspberry pi's and it works very well. It's a very nice app, thank you. My requirement is simple, I have a few weather stations that we use for wind speed and direction and each one is managed by a raspberry pi. I use frp for being able to log in remotely and manage the pi's.
> 
> I have about 5 working devices over the last 2 years so I have a basic understanding of how to set it up. However, now I'm preparing a new pi and I cannot get it to connect to the server. I have spent lots of time with no success, which is why I am reaching for assistance. I notice that frp has had a lot of updates since I started using it, so maybe an incompatibility between the new client and the old server? Or else, maybe raspberry pi OS has evolved and now has some kind of blocked port of something? I did try open the ports but maybe I did it wrong. I'm sorry, my knowledge is limited so I cannot troubleshoot it further.
> 
> The error I am getting when I try run frpc directly is: (I have removed the server name for security reasons) 2024-03-23 09:49:17.919 [W] [client/service.go:297] connect to server error: read tcp 192.168.1.216:45282->x.x.x.x:7000: read: connection reset by peer
> 
> I wanted to try updating frps server on the digital ocean droplet which is currently on 0.17.0 but I was afraid that it would impact the connection for the other weather stations that are currently working.
> 
> I have made a donation via paypal. Thanks again for this great app.
> 
> Would appreciate any support or suggestions, thank you!
> 
> ### frpc Version
> 0.56.0
> 
> ### frps Version
> 0.17.0
> 
> ### System Architecture
> linux/amd64, linux/arm64
> 
> ### Configurations
> The fps.ini is: (I have removed the token for security reasons) [common] bind_port = 7000 tcp_mux = false authentication_method = token token = x
> 
> The frpc.toml is: (I have removed the server name and token for security reasons)
> 
> # frpc.toml
> user = "sean" serverAddr = "x.x.x.x" serverPort = 7000 auth.method = "token" auth.token = "x" loginFailExit = false transport.tcpMux = false
> 
> [[proxies]] name = "yas" type = "tcp" localIP = "127.0.0.1" localPort = 22 remotePort = 6037
> 
> ### Logs
> _No response_
> 
> ### Steps to reproduce
> 1. Create new pi installation using raspberry pi imager for MacOS
> 2. Insert SD card into pi and boot
> 3. Log in via ssh
> 4. Install frpc and set up .toml file
> 5. Run frpc directly and then get errors
> 
> ### Affected area
> * [ ]  Docs
> * [ ]  Installation
> * [ ]  Performance and Scalability
> * [ ]  Security
> * [ ]  User Experience
> * [ ]  Test and Release
> * [ ]  Developer Infrastructure
> * [x]  Client Plugin
> * [ ]  Server Plugin
> * [ ]  Extensions
> * [ ]  Others

You can keep the 0.17.0 frps running and run another frps on another port like 7001, then you can try new versions without breaking the old connections.

**Comment by fatedier** [comment]
@foilandwater v0.17 This version is too old. In the historical versions of frp, there may be incompatible updates, which may cause the new version of the client to be unable to connect to the old version of the server. If I remember correctly, version v0.18 is incompatible with previous versions. This should be explained in the release notes.

> You can keep the 0.17.0 frps running and run another frps on another port like 7001, then you can try new versions without breaking the old connections.

I think it is a feasible method to gradually update to the latest version in a more controllable way.

In order to avoid problems caused by destructive updates, we have made the updates afterwards as compatible as possible with the old versions. There are some minor changes that will only be deprecated after several versions of compatibility, so it is recommended to read the release notes between the new and old versions before updating.

**Comment by Beryesa** [comment]
I'm getting
unknown field "loginFailExit"
on the latest version
Maybe try commenting that out for now

**Comment by foilandwater** [comment]
Thanks to everyone for the replies. It makes sense that the client and server would be incompatible after many version updates. Right now it is working well using an older version of the software and I don't require any new functionality so I am happy to keep it as is. At some point I will roll out updates to server and all clients.

Thanks again for the support and for this great app!

**Comment by foilandwater** [comment]
Thanks to everyone for the replies. It makes sense that the client and server would be incompatible after many version updates. Right now it is working well using an older version of the software and I don't require any new functionality so I am happy to keep it as is. At some point I will roll out updates to server and all clients.

Thanks again for the support and for this great app!
