### ISSUE TITLE
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type v1.ClientConfig

### ISSUE THREAD

**Issue by yinqinghe** [fatedier/frp#4099]
### Bug Description

error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type v1.ClientConfig

### frpc Version

v0.56.0

### frps Version

v0.56.0

### System Architecture

linux/amd64

### Configurations

![image](https://github.com/fatedier/frp/assets/70678389/a5d7e526-d6b7-49a8-8ae5-db739c5026b1)

### Logs

![image](https://github.com/fatedier/frp/assets/70678389/a2a4b1ae-2633-4e2e-ab88-73cb6b9ead31)

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
~~`[common]`~~
