### ISSUE TITLE
想请教：内网80端口的服务无法穿透到外网访问，个人网盘服务穿透后无法在外网上传下载

### ISSUE THREAD

**Issue by davidz125** [fatedier/frp#410]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.12 ，server端用的是一键安装包，客户端文件是重新在这里下载的

**What operating system and processor architecture are you using (`go env`)?**
服务器与客户端都是debian 8 64位

**Configures you used:**
server端
bind_port = xxx
vhost_http_port = xxxx
vhost_https_port = xxxx
privilege_mode = true
privilege_token = xxxxxx
客户端
分了web01和web02(具体配置文件在公司电脑上...)
大致为
[web01]
type = http
local_port = 80
custom_domains = web.yourdomain.com
use_encryption = true
use_compression = true
01和02一个用在80端口，装了wordpress网站，另一个用在5000端口上，装了seafile

1.两个服务在内网都非常正常，内网服务器上启动frpc后，日志显示正常，我也已查看外网服务器上的管理页面，两个web服务都是正常在线的
2.现通过外网访问5000端口的seafile也很顺利，可登陆、添加删减转移文件，但无法上传和下载文件（seafile页面会跳转到其他端口）
3.80端口在外网始终没办法访问，会直接跳转到外网服务器的网站根页面（apache的初始页）

想请问是我配置的问题或有其他解决办法，非常感谢！

**Comment by zeeqy** [comment]
强行答一下，首先seafile应该需要两个端口8000和8082（默认的），那么你的seafile在穿透的时候最好也使用两个端口。

另外请检查seafile的设置，FILE_SERVER_ROOT 和 SERVICE_URL 需要对应相应的域名和端口。
例如 frpc.ini 可以用tcp设置

```
[web03]
type = tcp
local_port = 8000
remote_port = 2001

[web04]
type = tcp
local_port = 8082
remote_port = 2002
```

希望能帮到你

**Comment by davidz125** [comment]
多谢楼上的答复，周一到公司我试一下
