### ISSUE TITLE
win7启动失败

### ISSUE THREAD

**Issue by JunXiaoRuo** [fatedier/frp#4100]
### Bug Description

![image](https://github.com/fatedier/frp/assets/47996900/fe602bc9-7855-4755-8beb-0612e40ada46)

### frpc Version

v0.56.0

### frps Version

v0.56.0

### System Architecture

windows/amd64

### Configurations

。

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
#4090
