### ISSUE TITLE
docker deploy: json: unknown field "auto"

### ISSUE THREAD

**Issue by wang1zhen** [fatedier/frp#4101]
### Bug Description

Both docker frps and frpc gives error:
```
json: unknown field "auto"
```

### frpc Version

0.56.0

### frps Version

0.56.0

### System Architecture

linux/amd64

### Configurations

frps.toml:

```
auto.method = "token"
auth.token = "x"
bindPort = 1234
```

### Logs

```
json: unknown field "auto"

json: unknown field "auto"

json: unknown field "auto"

json: unknown field "auto"

json: unknown field "auto"

json: unknown field "auto"

json: unknown field "auto"

json: unknown field "auto"

json: unknown field "auto"

json: unknown field "auto"

json: unknown field "auto"

json: unknown field "auto"
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/blob/86f90f4d2709194c7537e7be4f4a6d4f379adbd4/conf/frps_full_example.toml#L99

**Comment by wang1zhen** [comment]
thx, seemed to be a change in naming format. Closing.
