### ISSUE TITLE
配置文件根据文档配置不正确了

### ISSUE THREAD

**Issue by skinhc** [fatedier/frp#4105]
### Bug Description

我在使用0.56.0版本时,用frpc.toml时出现错误,无法解析remotePort字段
serverAddr = "xx.xx.xx.xx"
serverPort = 7000
auth.token = "aaaa"

[[proxies]]
name = "stcp-test1"
secretKey = "asdf"
type = "stcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000

### frpc Version

0.56.0

### frps Version

0.56.0

### System Architecture

linux/amd64

### Configurations

serverAddr = "xx.xx.xx.xx"
serverPort = 7000
auth.token = "aaaa"

[[proxies]]
name = "stcp-test1"
secretKey = "asdf"
type = "stcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000

### Logs

unmarshal ProxyConfig error: json: unknown field "remotePort"

### Steps to reproduce

1. 编辑frpc.toml
2. 运行 ./frpc -c ./frpc.toml
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by wuai1024** [comment]
可以仔细检查下配置文件。

`stcp` 不支持 `remotePort`
