### ISSUE TITLE
frpc reload重加载问题

### ISSUE THREAD

**Issue by SifuLi** [fatedier/frp#411]
版本：0.13.0  windows 386

执行重加载命令时（D:\frp_0.13.0_windows_386>frpc.exe -c ./frpc.ini --reload）

出错提示：
frpc reload error: Get http://127.0.0.1:0/api/reload: dial tcp 127.0.0.1:0: connectex: The requested address is not valid in its context.

**Comment by fatedier** [comment]
看文档。
