### ISSUE TITLE
为某个端口指定一个单独的token

### ISSUE THREAD

**Issue by XCLHove** [fatedier/frp#4113]
### Describe the feature request

为某个端口指定一个单独的token，如全局token为：`token-g`,为`22`端口指定token:`token-1`，`23`端口指定token:`token-2`，这样别人知道`22`端口的token就只能被限制使用`22`端口，而不是只有一个全局token，一旦暴露了别人就使用全局token将`22`端口替换为任意其他端口。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://github.com/gofrp/plugin?tab=readme-ov-file
