### ISSUE TITLE
[Feature Request] dedicated interface for binding to on frpc

### ISSUE THREAD

**Issue by modpotato** [fatedier/frp#4115]
### Describe the feature request

id like to have a dedicated interface for binding programs to so they forward their traffic to frpc. if this already exists PLEASE let me know as im quite confused. (im trying to run a docker container through frpc, but when i bind it to 0.0.0.0 you cant access it. however when i bind it to nothing but just list a port, i can access it (through frps of course) but the program im using automatically binds to the ip and i cant find where it sets up)

### Describe alternatives you've considered

ive changed the bound ip to none and it works fine though i need it to bind to an ip.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/issues/3826#issuecomment-1839273219
