### ISSUE TITLE
[Feature Request] 能否使一个frpc链接多个frps.

### ISSUE THREAD

**Issue by youyi0218** [fatedier/frp#4116]
### Describe the feature request

我想在不同的frps部署多个ip端口然后让一个frpc链接多个frps，只能开多个frpc程序吗

### Describe alternatives you've considered

开多个frpc写不同的配置文件：（

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by jiafeimao99** [comment]
我也需要这个功能，希望可以开发连接多个frps的功能。

**Comment by yangjieshao** [comment]
如非必要勿增实体
能用多个client解决的事就不要合并在一个client处理了，这个改动可以预见的是会引入很多bug风险的，风险和收益不成正比

**Comment by fatedier** [comment]
借助配置文件的环境变量渲染可以帮助你复用配置文件，也相对简单。

**Comment by jiafeimao99** [comment]
明白了，感谢哈
