### ISSUE TITLE
你好，能否在服务端自定义二级域名功能里加入域名白名单功能，那样防止别人随意乱用二级域名，也不至于每次去域名管理那修改域名映射，谢谢

### ISSUE THREAD

**Issue by teak2100** [fatedier/frp#412]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
自行配合其他组件（例如 nginx）管理
