### ISSUE TITLE
昨晚服務器和人個電腦遭遇了勒索病毒。

### ISSUE THREAD

**Issue by mynameking** [fatedier/frp#4120]
### Bug Description

這個工具不知道哪裏有問題，而且我才使用這個幾天，我搭建的目的就是為了3389遠程連接，首次發現間題的時候，是我在使用期間，突然3389顯示有人登錄，我當時覺得有點奇怪，但沒有處理。等我回家打開電腦的時候，發現密碼被改了。我當時覺得自己的密碼太短了，然後就加強到12密碼。然而就在今天早上起來發現情況不妙，所有文件加密，登錄服務器，直接顯示我中了勒索病毒，要我按照他們的方法支付比特幣。

### frpc Version

v0.56.0

### frps Version

v0.56.0

### System Architecture

windows

### Configurations

windows 10

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
请确保下载的文件与本站发布的校验码一致。（这个是开源项目）
另外病毒也可能是其他途径中的。。。

**Comment by yangjieshao** [comment]
自己把 3389 暴露出去 怪谁

**Comment by PctAIGM** [comment]
敢开放3389到公网，另外应该是弱口令，这是位勇士

**Comment by fatedier** [comment]
请从此以后不要再继续使用类似的项目，此外，我们之后会考虑在相关的地方给出风险提示。

**Comment by mynameking** [comment]
> 請確保下載的檔案與本站發布的驗證碼一致。（這個是開源專案） 另外的病毒也可能是途徑其他中的。。。3389開放本來就不太安全，我都是用stcp模式開的3389 ，用不敢tcp模式

我就是在這裏下載的。只是我這次比較幸運，非常重要的文件沒有被加密。我另外想問的是，使用STCP就不會有問題嗎？ 我現在不敢嘗試這個了，或許我應該在虛擬機多次測試。

**Comment by mynameking** [comment]
> 請今後不要再繼續使用類似的項目，此外，我們事後會考慮在相關的地方給予風險提示。

因為我很想使用3389遠控家裏電腦。我的服務器和家裏電腦的密碼都非常強，但是還是被中毒了。很不明白是什麼原因。

**Comment by superzjg** [comment]
> > 請確保下載的檔案與本站發布的驗證碼一致。（這個是開源專案） 另外的病毒也可能是途徑其他中的。。。3389開放本來就不太安全，我都是用stcp模式開的3389 ，用不敢tcp模式
> 
> 我就是在這裏下載的。只是我這次比較幸運，非常重要的文件沒有被加密。我另外想問的是，使用STCP就不會有問題嗎？ 我現在不敢嘗試這個了，或許我應該在虛擬機多次測試。

stcp模式需要访问者在电脑上开一个frpc客户端才能连接，除了配置frp的通用token，还需要配置secretKey，除非你的整个配置文件提前泄露，否则应该是比较安全的。

**Comment by yangjieshao** [comment]
> 我就是在這裏下載的。只是我這次比較幸運，非常重要的文件沒有被加密。我另外想問的是，使用STCP就不會有問題嗎？ 我現在不敢嘗試這個了，或許我應該在虛擬機多次測試。

这和你在哪下载的 用的什么软件都没关系，你自己把 3389 暴露到公网，随便用什么工具都是一样的
如果你一定要开放远程端口到公网
首先你要修改默认远程端口改成一个不常用的端口，常用端口分分钟被扫描出来
其次你要用个有足够复杂度的密码
然后你要各种杀毒软件都装好

**最后，无论你提前做了什么准备工作，当你都发现有异常登录了就应该立刻修改密码，有条件的就先断开公网链接**

**最后一条你都做不到，你就应该听劝，别用类似的软件了**，用个远程软件吧，比如 “向日葵” “ToDesk” “teamviewer” “RustDesk”

**Comment by yangjieshao** [comment]
> 我就是在這裏下載的。只是我這次比較幸運，非常重要的文件沒有被加密。我另外想問的是，使用STCP就不會有問題嗎？ 我現在不敢嘗試這個了，或許我應該在虛擬機多次測試。

讲个笑话  拉屎拉不出怪马桶没吸力

**Comment by yangjieshao** [comment]
> 因為我很想使用3389遠控家裏電腦。我的服務器和家裏電腦的密碼都非常強，但是還是被中毒了。很不明白是什麼原因。

![image](https://github.com/fatedier/frp/assets/3275834/9669554b-4a5e-4147-887a-30633b889179)

![image](https://github.com/fatedier/frp/assets/3275834/c2782997-eb20-41fc-9300-d8b59f7e7d7b)
再讲个笑话  “我的服務器和家裏電腦的密碼都非常強”   “我當時覺得自己的密碼太短了”
