### ISSUE TITLE
How can I restart the frps server on ubuntu every hour?

### ISSUE THREAD

**Issue by bannyhm** [fatedier/frp#4127]
### Describe the feature request

How can I restart the frps server on ubuntu automatically every hour?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
```shell
crontab -e
```
```
0 * * * * systemctl restart frps
```

不过，我很好奇 为什么要这么做

**Comment by bannyhm** [comment]
> ```shell
> crontab -e
> ```
> 
> ```
> 0 * * * * systemctl restart frps
> ```
> 
> 不过，我很好奇 为什么要这么做

thanks. But for some reason I get this in return:

$ systemctl restart frps
Failed to restart frps.service: Unit frps.service not found.

**Comment by bannyhm** [comment]
It looks like this example is working
https://github.com/fatedier/frp/issues/176#issuecomment-349880778
