### ISSUE TITLE
illegal instruction on ARMv6

### ISSUE THREAD

**Issue by Zeyu-W** [fatedier/frp#4129]
### Bug Description

I am trying to deploy the FRP on my Raspberry Pi Zero W (as the client), but when I execute the "./frpc -c frpc.toml" I got the "illegal instruction" problem. I suppose the processor that the RPI Zero W has is an ARMv6-based processor, and it looks like FRP was not compiled for ARMv6, may I ask whether there is a compatible FRP version for ARMv6?

### frpc Version

0.55.1

### frps Version

0.55.1

### System Architecture

linux/arm

### Configurations

as normal

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Zeyu-W** [comment]
我试图在我的 Raspberry Pi Zero W（作为客户端）上部署 FRP，但是当我执行“./frpc -c frpc.toml”时，我遇到了“非法指令”问题。 我猜RPI Zero W的处理器是基于ARMv6的处理器，并且看起来FRP不是为ARMv6编译的，请问是否有兼容ARMv6的FRP版本？

**Comment by fatedier** [comment]
You can try to compile the corresponding version for the environment by yourself.

**Comment by peace4j** [comment]
> 我试图在我的 Raspberry Pi Zero W（作为客户端）上部署 FRP，但是当我执行“./frpc -c frpc.toml”时，我遇到了“非法指令”问题。 我猜RPI Zero W的处理器是基于ARMv6的处理器，并且看起来FRP不是为ARMv6编译的，请问是否有兼容ARMv6的FRP版本？

It also happened on my CentOS 7.  And I compiled and built it by myself on my CentOS7 and after that it's OK then. It's seems something missing or something not compitable with the target system in the pre-compiled binary file.

**Comment by molpie** [comment]
Same problem on Raspberry Pi Model B Rev 2.
I tried generating the executables for arm on amd64 (Current version), using package.sh, but the error remains.
Compiling directly on Raspberry Pi Model B Rev 2 the error does not occur.

**Comment by fatedier** [comment]
@molpie Thank you for your testing and research.

I will consider compiling a separate binary file for Linux armv6 in the next version.

**Comment by Zeyu-W** [comment]
> @molpie Thank you for your testing and research.
> 
> I will consider compiling a separate binary file for Linux armv6 in the next version.

Great! That will be very helpful for any ARMv6-based devices used as the hub of sensor network.
