### ISSUE TITLE
获取真实IP地址

### ISSUE THREAD

**Issue by motolvla** [fatedier/frp#413]
求指教：
apache+php环境
按文档所述，用户第一次访问可以通过X-Forwarded-For 和 X-Real-IP获取真实IP。
之后的访问有时能获取有时不能，请问为何不每次访问都带上X-Forwarded-For 和 X-Real-IP，还是说可以通过其他配置实现？
获取真实IP对做站有较大作用，诚心求教。
另感谢作者辛勤开发，从第一个版本开始用，功能越来越强大了。

**Comment by motolvla** [comment]
已通过在frps前加apache代理解决，希望以后版本每次都能附上真实IP

**Comment by hrj5032188** [comment]
如果直接访问frps是没有真实ip的吗?

**Comment by BusyHe** [comment]
怎么解决的？
