### ISSUE TITLE
我使用了remotePort但是并不起作用

### ISSUE THREAD

**Issue by youjunxiaji** [fatedier/frp#4132]
### Bug Description

- 这个是frpc启动日志文件
![image](https://github.com/fatedier/frp/assets/94896689/6d2be11a-666e-4e40-932a-9566efffe144)

- 这个是frpc上的配置文件
![image](https://github.com/fatedier/frp/assets/94896689/acec5b04-5a54-4cf1-9ac5-17fe7ca7b220)

- 这个是端口使用情况
![image](https://github.com/fatedier/frp/assets/94896689/7808fe52-c56a-43c6-a4de-714d09090a0f)

---
- 这个是frps日志 服务器来源于阿里云
![image](https://github.com/fatedier/frp/assets/94896689/6133c2b7-584b-4df6-a459-69c4b24af34a)

### frpc Version

0.56.0

### frps Version

0.56.0

### System Architecture

linux/amd64

### Configurations

使用了remotePort但是并不起作用

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by peace4j** [comment]
可确认下阿里云ECS实例对应的安全组中，tcp port 6000的入站是accept的
