### ISSUE TITLE
请求超过60秒立刻超时报错

### ISSUE THREAD

**Issue by maxin9966** [fatedier/frp#4138]
### Bug Description

请求超过60秒返回以下数据，版本0.4.x，查看文档后，尝试设置vhostHTTPTimeout = 100000后依然不行，还是60秒报错：

<!DOCTYPE html>
<html>
<head>
<title>Not Found</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>The page you requested was not found.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>The server is powered by <a href="https://github.com/fatedier/frp">frp</a>.</p>
<p><em>Faithfully yours, frp.</em></p>
</body>
</html>

### frpc Version

0.49.0

### frps Version

不确定版本？cat docker-compose.yml version: '3.3' services:     frps:         restart: always         network_mode: host         volumes:             - './frps.ini:/etc/frp/frps.ini'         container_name: frps         image: snowdreamtech/frps

### System Architecture

linux/amd64

### Configurations

[root@hklite2 frp]# cat frps.ini
[common]

#frp 监听端口，与客户端绑定端口

bind_port= 5443
kcp_bind_port = 5443

vhost_http_port = 7860
vhost_ssh_port = 7991
vhostHTTPTimeout = 600000
userConnTimeout = 600000

#dashboard用户名

dashboard_user= admin

#dashboard密码

dashboard_pwd= xxxxxx

#dashboard端口，启动成功后可通过浏览器访问如http://ip:9527

dashboard_port= 9527

#设置客户端token，对应客户端有页需要配置一定要记住，如果客户端不填写你连不上服务端

token = xxxxxxx

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by maxin9966** [comment]
frps Jul  6  2023 docker-compose.yml

[root@hklite2 frp]# cat docker-compose.yml
version: '3.3'
services:
    frps:
        restart: always
        network_mode: host
        volumes:
            - './frps.ini:/etc/frp/frps.ini'
        container_name: frps
        image: snowdreamtech/frps

去年年中7月6号的版本，应该是0.4x.x

**Comment by fatedier** [comment]
请完全按照官方文档来进行配置，不要混用 INI 和 TOML 格式的配置参数写法。
