### ISSUE TITLE
路由器中使用frpc，能否结合路由器的port forwards访问内网web服务。即：内网服务器不需要运行frpc，只在路由器上运行frpc。请问是否可行？

### ISSUE THREAD

**Issue by yijing1998** [fatedier/frp#414]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frp 0.13

**What operating system and processor architecture are you using (`go env`)?**
Linux LEDE 4.4.71 mips GNU/Linux
MediaTek MT7620A MIPS 24KEc V5.0

**Configures you used:**
server部分
bind_port = 7000

client部分
[common]
server_addr = ...
server_port = 7000
[web]
type = tcp
remote_port = 8080
local_port = 8080（修改为local_port = 80后，可通过 http://server_addr:8080 正常访问路由器管理页面）

路由器端口转发配置
![default](https://user-images.githubusercontent.com/3353173/28777949-c8a6622c-762f-11e7-8c2d-dff2361a1975.PNG)

**Steps to reproduce the issue:**
1.运行服务端
2.运行客户端
3.浏览器访问：http://server_addr:8080

**Describe the results you received:**
客户端日志：
![default](https://user-images.githubusercontent.com/3353173/28778210-f9be4df6-7630-11e7-9179-114c5ba0bb25.PNG)

**Describe the results you expected:**
frp能否与路由器的端口转发配合使用

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
请自行研究解决，不要每一个遇到的问题，出一点错（大多数根本不是 bug）都开 issue，没有时间一一解答。

**Comment by pastay** [comment]
可行，梅林koolshare固件提供frpc功能，道理一样的，内网存在多个主机可以在frpc的配置文件里添加不同的remote端口对应不同主机的内网ip地址，完成端口转发功能，不需要在路由器再设置端口转发
