### ISSUE TITLE
客户端 0.57.0 在 win11 无法正常运行

### ISSUE THREAD

**Issue by jjyou-github** [fatedier/frp#4140]
### Bug Description

通过nssm工具，生成的服务无法启动；
命令行启动，没有任何内容回显。

![image](https://github.com/fatedier/frp/assets/63731955/7209fc68-1c17-42c4-b8d7-acc75f4c343d)

客户端回退到0.53.2正常，其它中间版本未尝试

### frpc Version

0.57.0  && 0.56.0

### frps Version

0.52.3

### System Architecture

windows/amd64

### Configurations

serverAddr = "xxx"
serverPort = xxx

auth.method = "token"
auth.token = "xxx"
tls.force = false
user = "xxx"

[[proxies]]
name = "mstsc"
type = "tcp"
localIP = "127.0.0.1"
localPort = xxx
remotePort = xxx

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
请测试 release 页面下载的版本是否能够执行，其他方式不熟悉，无法提供有效建议。

**Comment by jjyou-github** [comment]
> 请测试 release 页面下载的版本是否能够执行，其他方式不熟悉，无法提供有效建议。

就是从release页面下载的，windows_amd64的包，解压出来的exe

**Comment by fatedier** [comment]
目前没有验证环境，但是大概率是使用姿势问题，你可以自行编译调试看看。

**Comment by suixin7260** [comment]
0.53是正常吗

**Comment by jjyou-github** [comment]
> 0.53是正常吗

正文里说了，0.53.2正常。
之前0.52.3也是正常的。

**Comment by xqzr** [comment]
```batch
.\frpc.exe -c jjyou.toml
```
