### ISSUE TITLE
无法使用switchyomega代理插件访问

### ISSUE THREAD

**Issue by hamsterLi** [fatedier/frp#4141]
### Bug Description

直接使用curl测试是正常的，但是配置到浏览器的代理插件上就出现无法访问的情况，这是什么原因

### frpc Version

0.33

### frps Version

0.33

### System Architecture

win11

### Configurations

frps.ini
[common]
bind_addr=0.0.0.0
bind_port = 7002
token=123456
log_file = console
log_level = trace

frpc.ini
[common]
server_addr = xxxx
server_port = 7002
token=123456

[http]
type = "tcp"
remote_port = 8002
plugin=http_proxy

### Logs

2024/04/10 03:13:50 [D] [proxy.go:283] [3bd524f3e8562b40] [http] join connections closed
2024/04/10 03:13:50 [D] [control.go:219] [3bd524f3e8562b40] new work connection registered
2024/04/10 03:13:53 [D] [proxy.go:283] [3bd524f3e8562b40] [http] join connections closed
2024/04/10 03:14:13 [D] [control.go:474] [3bd524f3e8562b40] receive heartbeat
2024/04/10 03:14:43 [D] [control.go:474] [3bd524f3e8562b40] receive heartbeat
2024/04/10 03:15:13 [D] [control.go:474] [3bd524f3e8562b40] receive heartbeat
2024/04/10 03:15:43 [D] [control.go:474] [3bd524f3e8562b40] receive heartbeat
2024/04/10 03:16:13 [D] [control.go:474] [3bd524f3e8562b40] receive heartbeat
2024/04/10 03:16:14 [D] [proxy.go:162] [3bd524f3e8562b40] [http] get a user connection [xxx.xxx.xxx.xxx:53684]
2024/04/10 03:16:14 [D] [control.go:248] [3bd524f3e8562b40] get work connection from pool
2024/04/10 03:16:14 [I] [proxy.go:103] [3bd524f3e8562b40] [http] get a new work connection: [xxx.xxx.xxx.xxx:35993]
2024/04/10 03:16:14 [T] [proxy.go:262] [3bd524f3e8562b40] [http] handler user tcp connection, use_encryption: false, use_compression: false
2024/04/10 03:16:14 [D] [proxy.go:273] [3bd524f3e8562b40] [http] join connections, workConn(l[xxx.xxx.xxx.xxx:7002] r[119.122.113.80:35993]) userConn(l[xxx.xxx.xxx.xxx:8002] r[xxx.xxx.xxx.xxx:53684])
2024/04/10 03:16:14 [D] [proxy.go:283] [3bd524f3e8562b40] [http] join connections closed
2024/04/10 03:16:14 [D] [control.go:219] [3bd524f3e8562b40] new work connection regi

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
如果 curl 正常，其他方式不正常，请先自行 debug 排查一下这中间的差异，确认是否是一个 bug 还是使用姿势不正确。

此外，请更新到最新版本。
