### ISSUE TITLE
最新版0.57.0的windows版本和Linux版本

### ISSUE THREAD

**Issue by suixin7260** [fatedier/frp#4143]
### Bug Description

分别在windows、linux配置frpc，无法正常运行frp客户端

### frpc Version

0.57.0

### frps Version

0.57.0

### System Architecture

linux/amd64，windows/amd64

### Configurations

serverAddr = "xxx.xxx.xx.xxx"
serverPort = 7000
auth.token = "xxx"

[[proxies]]
name = "test-tcp"
type = "http"
localIP = "127.0.0.1"
localPort = 9000
remotePort = 80

### Steps to reproduce

1. linux：执行./frpc -c frpc.toml unmarshal ProxyConfig error: json: unknown field "remotePort"
2. windows：执行start frpc.exe -c frpc.toml，无任何响应

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by suixin7260** [comment]
> Remove `remotePort`

去掉这个之后，如何配置远程服务器的端口

**Comment by jjyou-github** [comment]
参考下我的客户端配置吧，0.52和0.53的客户端都能用，我也是0.56和0.57客户端不能用
https://github.com/fatedier/frp/issues/4140

**Comment by cainsyake** [comment]
参考 https://gofrp.org/zh-cn/docs/examples/stcp

@suixin7260
