### ISSUE TITLE
[Feature Request] 错误配置跳过功能

### ISSUE THREAD

**Issue by L-evi** [fatedier/frp#4146]
### Describe the feature request

能够添加一个错误配置跳过的功能吗？或者允许用户配置一个兜底文件，这样子再不小心配置错误了之后，有一定的容错率
因为目前我这边配置了ssh登陆，但是我添加别的内网穿透的时候会不小心配置错误，导致要千里迢迢跑回去重新设置一下配置文件，如果在项目启动的时候感知到配置文件错误并且启动兜底文件的话，会更加好。感谢开源作者的不断付出

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
[v0.55.0](https://github.com/fatedier/frp/releases/tag/v0.55.0)
--strict config 的默认值已从 false 更改为true。如果您的配置文件使用了不存在的配置项或存在拼写错误，则应用程序将引发错误。此启动参数是在 v0.53.0 版本中引入的（false）。如果希望继续使用旧的行为，则需要显式设置 --strict-config=false
