### ISSUE TITLE
The value of log.to cannot be configured as a non-existent path

### ISSUE THREAD

**Issue by FoundAdd** [fatedier/frp#4147]
### Describe the feature request

If I configure log.to with a path that does not exist, the logging system will not automatically create this directory, but will directly prompt "no such file or directory". 
![image](https://github.com/fatedier/frp/assets/58539321/d37558d2-4733-41eb-b90f-b78620c2e1c6)

### Describe alternatives you've considered

It would be much more convenient if the logic could be changed to automatically create lower-level directories. Currently, the corresponding log directory can only be created in advance.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
Please use the latest version and use explicit paths instead of environment variables.
