### ISSUE TITLE
Dashboard可以做权限限制么

### ISSUE THREAD

**Issue by it-noob** [fatedier/frp#415]
Dashboard中可以对在线的代理进行权限控制么，比如http代理列表中禁用某个代理；另外，目前Linux版本的无论客户端frpc还是服务端frps启动，都需要自行用(./frpc -c ./frpc.ini &)命令来设置守护进程，能否则在官方启动命令层面添加守护进程，或者可以安装为系统服务；另外win下，直接双击frpc.exe加载的不是frpc.ini也不是frpc_full.ini，可否设置一个默认加载的配置文件，另外windows下是否可以设置常驻进程或者安装为系统服务。

**Comment by fatedier** [comment]
暂不支持。程序如何启动和管理自行决定，有 N 种方式，在不同的平台自行选择合适的方式，这个问题回答过多次了。

**Comment by it-noob** [comment]
@fatedier 抱歉，没有查看之前的issue。谢谢回复。
