### ISSUE TITLE
[Feature Request] 第一行日志输出frp当前版本，还有配置文件是否错误？

### ISSUE THREAD

**Issue by Dunkelicht** [fatedier/frp#4157]
### Describe the feature request

frp端口转发非常稳定，但是有时候需要诊断网络问题和配置问题，
可否在日志输出的时候输出一些实用信息，例如frps和frpc的使用的版本。
配置文件是否错误可能不是必须的，毕竟多了一个检查就多一个故障点。

### Describe alternatives you've considered

我是在windows下运行的，会用bat启动frp，所以一开始会执行frps -v /frpc -v, 当然 这样不会进入文件日志中

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
尝试调整 日志级别 https://github.com/fatedier/frp/blob/2626d6ed926745a6dda4301ceee79d00d44f696c/conf/frps_full_example.toml#L88

**Comment by Dunkelicht** [comment]
> 尝试调整 日志级别
> 
> https://github.com/fatedier/frp/blob/2626d6ed926745a6dda4301ceee79d00d44f696c/conf/frps_full_example.toml#L88

非常感谢 我想 应该是 trace>debug>info>warn>error，而且优先级高的包含低的，我的理解有问题吗？

**Comment by xqzr** [comment]
> > 尝试调整 日志级别
> > https://github.com/fatedier/frp/blob/2626d6ed926745a6dda4301ceee79d00d44f696c/conf/frps_full_example.toml#L88
> 
> 非常感谢 我想 应该是 trace>debug>info>warn>error，而且优先级高的包含低的，我的理解有问题吗？

✅
