### ISSUE TITLE
请问能否做成配置热加载或者数据库获取的模式呢？

### ISSUE THREAD

**Issue by housirvip** [fatedier/frp#416]
F大你好，用了蛮久的frp，建议privilege key这种可以多用户单独生成，然后保存在数据库中，这样就方便实现api接口，能有网页来控制，实现自主注册，更甚实现商业化，就类似shadowsocks-rss那样，不知道这么直接提在issue中合不合规定，还请见谅啊

**Comment by fatedier** [comment]
想法很好，不过类似这样的平台和管理的功能点，不会放到开源项目里来做。这个项目的目标是实现一个对于个人用户来说易于使用，能满足大多数需求的小工具。

**Comment by housirvip** [comment]
嗯在理，那F大可以开一个私有项目，然后发行alpha和beta测得release供大家使用和反馈bug，最后的stable做成需要授权注册商业化软件，我想还蛮好的呀

**Comment by fatedier** [comment]
可以加入未来的计划，等 features 完成的差不多，能发布 1.0 版本以后。
