### ISSUE TITLE
nodelay for tcp/udp

### ISSUE THREAD

**Issue by linnuxx** [fatedier/frp#4160]
### Describe the feature request

will you add the "nodelay" function?

### Describe alternatives you've considered

https://github.com/rapiz1/rathole 

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
No, the default value of Go is true. I do not expect users to perceive this configuration, which applies to almost all scenarios.
