### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by linslZero** [fatedier/frp#4162]
### Describe the feature request

nat_hole_stun_server 能否支持写多个
因为看代码是支持多个的

```

func Discover(stunServers []string, localAddr string)


```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
不妨试试 写成数组
```toml
natHoleStunServer = ["stun.easyvoip.com:3478", "stun.cloudflare.com:3478"]
```
https://github.com/fatedier/frp/blob/885278c045d6d7c865f0e7e5937f86057ce22b33/conf/frpc_full_example.toml#L13

**Comment by fatedier** [comment]
缺乏实际的场景，且不推荐，所以目前不会考虑支持。
