### ISSUE TITLE
how to download frpc_full.toml ?

### ISSUE THREAD

**Issue by ybinson** [fatedier/frp#4164]
### Describe the feature request

frpc_full.ini
frps_full.ini

frpc_full.toml ?
frps_full.toml ?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
https://github.com/fatedier/frp/tree/dev/conf
