### ISSUE TITLE
[Feature Request] 希望文档能支持搜索功能

### ISSUE THREAD

**Issue by sjhsbhqf** [fatedier/frp#4165]
### Describe the feature request

希望文档能支持搜索功能，不然不方便学习配置文件变量

### Describe alternatives you've considered

希望文档能支持搜索功能，不然不方便学习配置文件变量

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
新文档 移除了。
Ctrl+F
