### ISSUE TITLE
Is it possible to increase traffic compression?

### ISSUE THREAD

**Issue by linnuxx** [fatedier/frp#4169]
### Describe the feature request

Does traffic compression work for "tcp" and "udp"?
Is it possible to compress traffic more?
in order for compressed data to go through the tunnel, not compressed outside the tunnel, the fact is that some hosting providers would not want a lot of traffic to come from them.
For example, a 64kb pact will shrink to 32kb if it goes into the frp tunnel.
as it looks like: player>ipvds>frpserver>frpclient>gameserver. the return route of the packages: gameserver>frpclient>frpserver.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by superzjg** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml#L152-L153

**Comment by linnuxx** [comment]
> https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml#L152-L153

I'm talking about compression in %
