### ISSUE TITLE
同样配置，私有电信服务器正常，阿里云报验证错误。(已翻阅之前issue，有类似情况但无法按参考解决。)

### ISSUE THREAD

**Issue by scaldstack** [fatedier/frp#417]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.10.0

**What operating system and processor architecture are you using (`go env`)?**
server: aliyun ubuntu 16.04
client: windows 10

**Configures you used:**
## frps.ini:
bind_addr = 0.0.0.0
bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = 123
log_file = ./frps.log
log_level = info
log_max_days = 3
privilege_mode = true
privilege_token = 123
privilege_allow_ports = 2000-3000,3001,3003,4000-50000
max_pool_count = 100
authentication_timeout = 900
subdomain_host = frps.com
tcp_mux = true

## frpc.ini:
[common]
server_addr = www.myaliyunurl.com
server_port = 7000
log_file = ./frpc.log
log_level = info
log_max_days = 3
privilege_token = 123
pool_count = 5
tcp_mux = true
user = your_name
[ssh]
privilege_mode = true
type = tcp
local_ip = 127.0.0.1
local_port = 6666
use_encryption = true
use_compression = false
remote_port = 6666

**Steps to reproduce the issue:**
1. 关闭服务器端和用户端的防火墙。
1. 在aliyun ubuntu16.04 上下载frp，并将frps.ini配置成如上，用 **nohup ./frps -c frps.ini &** 启动
2. 在Windows 10 上下载frp，并将frpc.ini配置成如上格式，并用frpc -c frpc.ini启动
3. Windows 10上程序退出，显示错误：2017/08/03 01:58:19 [E] [control.go:235] authorization failed
4. 将aliyun上整个frp文件夹纹丝不动复制到自己的一个电信ubuntu 16.04服务器上，并用一样的方式启动。
5. windows 10 上将frpc.ini的server_addr换成电信服务器的IP地址，开启frpc，一切正常。

**Describe the results you received:**
2017/08/03 01:58:19 [E] [control.go:235] authorization failed

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
在aliyun上出问题，电信正常。aliyun直接用域名，电信服务器直接用IP地址。

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
这种因为环境造成的不确定的问题，就给阿里云提工单吧。

**Comment by wxlg1117** [comment]
看看会不会是 frps和frpc俩地的时间相差太大导致的验证失败啊?

**Comment by fyhong** [comment]
authentication_timeout = 900
改为
authentication_timeout = 0

**Comment by wbpluto** [comment]
看这里，很可能是时区问题：http://www.right.com.cn/forum/forum.php?mod=viewthread&tid=262258
