### ISSUE TITLE
frp_0.57.0_linux_amd64   客户端连不上，服务器日志提示 error: no route found

### ISSUE THREAD

**Issue by aabababb** [fatedier/frp#4170]
### Bug Description

frp_0.57.0_linux_amd64   客户端连不上，服务器日志提示 error: no route found
error: no route found: frp.test.net /config/query 

### frpc Version

frp_0.57.0_linux_amd64

### frps Version

frp_0.57.0_linux_amd64

### System Architecture

centos7

### Configurations

cat /etc/frp/frps.toml 
bindAddr = "0.0.0.0"
# 服务端监听端口
bindPort = 8888
kcpBindPort = 8888
# 鉴权使用的 token 值
auth.method = "token"
auth.token = "12345678"

# HTTP 类型代理监听的端口（给Nginx反向代理用）
vhostHTTPPort = 8080
vhostHTTPSPort = 8443
vhostHTTPTimeout = 120

# 【可选】FRP管理界面（修改账号密码，Nginx反向代理到7777）
webServer.addr = "127.0.0.1"
webServer.port = 7777
webServer.user = "admin"
webServer.password = "12345678"

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
请参照文档配置。
