### ISSUE TITLE
wireguard over frp,performance is lower than wireguard over rathole.

### ISSUE THREAD

**Issue by linnuxx** [fatedier/frp#4174]
### Bug Description

What could be the matter?
wgserver mtu 1300.
wgclient mtu 1300.
frps/frpc are installed on debian12.
go version go1.22.2 linux/amd64.

### frpc Version

0.57.0

### frps Version

0.57.0

### System Architecture

linux/amd64

### Configurations

# frps.toml
bindPort = 7000

# frpc.toml
serverAddr = "ipvps"
serverPort = 7000

[[proxies]]
name = "wg"
type = "udp"
localIP = "192.168.1.237"
localPort = 51820
remotePort = 51821
transport.useCompression = true

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
Thank you for your testing. It would be more helpful if you could provide complete data and various tests of controlled variables. Otherwise, we won't be able to do anything.

**Comment by fatedier** [comment]
I am not familiar with wireguard and rathole, so I cannot provide any additional advice.

**Comment by linnuxx** [comment]
> I am not familiar with wireguard and rathole, so I cannot provide any additional advice.

you are familiar with frp, but for some reason the speed of working with frp is lower.

**Comment by linnuxx** [comment]
> Thank you for your testing. It would be more helpful if you could provide complete data and various tests of controlled variables. Otherwise, we won't be able to do anything.
![ScreenShot_20240429173814](https://github.com/fatedier/frp/assets/154101918/dcf56ba0-4a53-4e87-b811-3031d448047b)

ratholeserver:
# server.toml
[server]
bind_addr = "0.0.0.0:8388" # `2333` specifies the port that rathole listens for clients

[server.services.my_nas_ssh]
type = "udp"
token = "key" # Token that is used to authenticate the client for the service. Change to an arbitrary value.
bind_addr = "0.0.0.0:51821" # `5202` specifies the port that exposes `my_nas_ssh` to the Internet
nodelay = true

ratholeclient:
# client.toml
[client]
remote_addr = "46.174.53.140:8388" # The address of the server. The port must be the same with the port in `server.bind_addr`

[client.services.my_nas_ssh]
token = "key" # Must be the same with the server to pass the validation
local_addr = "192.168.1.237:51820" # The address of the service that needs to be forwarded
nodelay = true
type = "udp"

wireguard over rathole - so performance does not drop much.
wireguard over frp - There is less performance through frp, although the vps performance is sufficient to withstand 80-100mbps.
