### ISSUE TITLE
mipsle arch is missing softfloat flag due to Makefile.cross-compiles bug

### ISSUE THREAD

**Issue by ddscentral** [fatedier/frp#4175]
### Bug Description

In Makefile.cross-compiles even though both mips and mipsle have softfloat flag, it is only applied for "mips" due to a bug in "if statement.

Line
```
 elif [ "$${os}" = "linux" ] && [ "$${arch}" = "mips" ] && [ "$${extra}" != "" ] ; then \
```

should look like this:

```
 elif [ "$${os}" = "linux" ] && ([ "$${arch}" = "mips" ] || [ "$${arch}" = "mipsle" ]) && [ "$${extra}" != "" ] ; then \
```

### frpc Version

0.57.0

### frps Version

0.57.0

### System Architecture

linux/mipsel

### Configurations

Not applicable

### Steps to reproduce

1. Run make -f Makefile.cross-compiles
2. Copy mipsle binary (any frps or frpc) to a MIPS device without a FPU
3. Binary does not run due to "illegal instruction".

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by ddscentral** [comment]
With the line corrected, binaries do run on the device.

**Comment by fatedier** [comment]
Can you submit a PR to fix it?

**Comment by ddscentral** [comment]
Created a PR: https://github.com/fatedier/frp/pull/4176
