### ISSUE TITLE
How to change the configuration from frpc.ini to frpc.toml

### ISSUE THREAD

**Issue by bannyhm** [fatedier/frp#4178]
### Describe the feature request

the following configuration is in fprc.ini, how can I fix it so that it works correctly in frpc.toml

[common]
forward_all = tcp+udp
all_use_encryption = false
all_use_compression = false
server_addr = x.x.x.x
server_port = 9100
plugin_user = abc
plugin_passwd = abc
authentication_method = token
token = 12345678
dns_server = x.x.x.x

udp_forward = true

[web_tcp]
type = tcp
local_ip = 127.0.0.1
local_port = 6000
remote_port = 6000
use_encryption = false
use_compression = false
protocol = tcp

[web_udp]
type = udp
local_ip = 127.0.0.1
local_port = 6000
remote_port = 6000
use_encryption = false
use_compression = false
protocol = udp

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
You can continue to use the INI format configuration file until you have new feature requirements, then rewrite the TOML format configuration file according to the document.

**Comment by xqzr** [comment]
#3818

**Comment by bannyhm** [comment]
Thank you very much
