### ISSUE TITLE
Windows下载文件报有木马

### ISSUE THREAD

**Issue by l1985q** [fatedier/frp#4183]
### Bug Description

在windows中下载文件包，直接提示有木马，这是正常还是不正常？

### frpc Version

0.57.0

### frps Version

0.57.0

### System Architecture

windows/amd64

### Configurations

windows

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/issues/2095
