### ISSUE TITLE
[Feature Request] dns支持配置doh, dns over https

### ISSUE THREAD

**Issue by Weltolk** [fatedier/frp#4187]
### Describe the feature request

配置dns的地方支持配置doh

### Describe alternatives you've considered

提升安全性

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
不在此项目的计划内，建议结合其他工具一起使用。
