### ISSUE TITLE
请问穿透后连不上filezilla server是什么问题？

### ISSUE THREAD

**Issue by jjj333** [fatedier/frp#4188]
### Bug Description

我的网络情况如下：
电脑A：在电信下运行着frps和frpc，有公网ip
电脑B：是电信下的公司电脑，运行frpc并映射了filezilla server的3个端口（主动模式端口和2个被动模式端口），另外还映射了远程桌面的端口。

filezilla server已该链接说的进行了配置。https://github.com/fatedier/frp/issues/219#issuecomment-514870300

故障为：
用A上的filezilla客户端去连B的服务端，直接就报【尝试连接“ECONNREFUSED - 连接被服务器拒绝”失败】，在B上的filezilla管理界面上看，根本没连上，没有任何日志消息。
但是用A的远程桌面去连B完全没问题。

### frpc Version

0.51.3

### frps Version

0.54.0

### System Architecture

windows/amd64

### Configurations

1

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by jjj333** [comment]
补充：
A是我家里的网络，拥有完整控制权，B是公司网络，完全没控制权。今天又做了一下实验，两者的关系对调，filezilla服务端在A，客户端在B，同样的设置也是走不通，连接2、3秒后报"尝试连接“ECONNREFUSED - 连接被服务器拒绝”失败"。然后我把家里路由上的端口打开，就能顺利连接，但这又失去了frp的意义。。。。。。我没有想通的是，为啥ftp不行而远程桌面的rdp是可以的

**Comment by jjj333** [comment]
问题解决！
其实是frps端口的问题，我在2个frpc上设置的远程端口都不在我在自己的路由上开给frps的端口范围内，所以连不上ftp的本质是连不上frps。。。
这里还有个细节，ftp上的被动模式的端口，必须本地端口和远程端口一直且都在路由上开给frps的端口范围内，否则又是个坑！

**Comment by menglinxi** [comment]
求配置文件，怎么映射多个被动端口？
http://ocdman.github.io/2018/07/17/%E5%80%9F%E5%8A%A9frp%E5%AE%9E%E7%8E%B0ftp%E6%9C%8D%E5%8A%A1%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F/

[range:ftp]
type = tcp
local_ip = 127.0.0.1
local_port = 21,50000-50002
remote_port = 2121,50000-50002
这种配置失效了。

**Comment by jjj333** [comment]
> 求配置文件，怎么映射多个被动端口？ http://ocdman.github.io/2018/07/17/%E5%80%9F%E5%8A%A9frp%E5%AE%9E%E7%8E%B0ftp%E6%9C%8D%E5%8A%A1%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F/
> 
> [range:ftp] type = tcp local_ip = 127.0.0.1 local_port = 21,50000-50002 remote_port = 2121,50000-50002 这种配置失效了。

我就是这么写的，没有失效啊

**Comment by menglinxi** [comment]
> > 求配置文件，怎么映射多个被动端口？ http://ocdman.github.io/2018/07/17/%E5%80%9F%E5%8A%A9frp%E5%AE%9E%E7%8E%B0ftp%E6%9C%8D%E5%8A%A1%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F/
> > [range:ftp] type = tcp local_ip = 127.0.0.1 local_port = 21,50000-50002 remote_port = 2121,50000-50002 这种配置失效了。
> 
> 我就是这么写的，正常没有失效

你用的是哪个版本的？

**Comment by jjj333** [comment]
> > > 求配置文件，怎么映射多个被动端口？ http://ocdman.github.io/2018/07/17/%E5%80%9F%E5%8A%A9frp%E5%AE%9E%E7%8E%B0ftp%E6%9C%8D%E5%8A%A1%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F/
> > > [range:ftp] type = tcp local_ip = 127.0.0.1 local_port = 21,50000-50002 remote_port = 2121,50000-50002 这种配置失效了。
> > 
> > 
> > 我就是这么写的，正常没有失效
> 
> 你用的是哪个版本的？

0.59.0
我记得之前某个版本的配置文件格式改过了，从ini改成现在的conf，你看看是不是覆盖安装的，老的ini还在

**Comment by weiqi-chen** [comment]
#4401
