### ISSUE TITLE
通过外网ip+port不能访问内网的http服务

### ISSUE THREAD

**Issue by Luoyinwei** [fatedier/frp#419]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.13.0

**What operating system and processor architecture are you using (`go env`)?**
server: ubuntu 16.04
client: windows 7

**Configures you used:**
# frps.ini:
bind_addr = 0.0.0.0
bind_port = 7000
vhost_http_port = 8080

# frpc.ini:
[common]
server_addr = 113.108.176.112
server_port = 7000
[web]
type = http
local_port = 8080
custom_domains = www.ssntest.net

**Steps to reproduce the issue:**
1. 关闭服务器端和用户端的防火墙。
2. 在ubuntu16.04 上下载frp，并将frps.ini配置成如上，用 sudo ./frps -c frps.ini & 启动
3. 在Windows 7 上下载frp，并将frpc.ini配置成如上格式，并用frpc -c frpc.ini启动
4. 在外网通过浏览器输入www.ssntest.net:8080可以访问到内网web服务，但是输入113.108.176.112:8080访问失败

**Describe the results you received:**
浏览器输入ip+端口访问web服务失败：The page you visit not found.

**Describe the results you expected:**
通过ip+端口可以访问内网web服务

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
你理解有误，搜索一下虚拟主机的相关内容或者 nginx 相关方面的资料学习一下。
