### ISSUE TITLE
subdomains not supported

### ISSUE THREAD

**Issue by alexiskhoury** [fatedier/frp#4194]
### Bug Description

When using http, frpc reports that the subdomain is not not supported by the frps server.
Is there any workaround?
Thanks

### frpc Version

0.54

### frps Version

0.57

### System Architecture

linux/amd64, linux/arm

### Configurations

[[proxies]]
name = "repeater"
type = "http"
localIP = "192.168.1.250"
localPort = 80
subdomain = "ap"
#customDomains = ["web.example.com"]
#locations = ["/"]
hostHeaderRewrite = "127.0.0.1"
requestHeaders.set.x-from-where = "frp"

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp?tab=readme-ov-file#custom-subdomain-names

**Comment by alexiskhoury** [comment]
It works like a charm.
Many thanks for this great piece of software.
