### ISSUE TITLE
[Feature Request] frp http using random port like tcp and udp 

### ISSUE THREAD

**Issue by ahmedvista** [fatedier/frp#4196]
### Describe the feature request

Hi, I hope you are doing well.
i want to make frps to use multiple ports for http like others ( tcp and udp)

for example i want to set frpc.toml

[[proxies]]
name = "ssh_1"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 0

[[proxies]]
name = "http_1"
type = "http"
localIP = "127.0.0.1"
localPort = 80
subdomain = "frp1"      >>>> remotePort = 0 

to use it like host_doamin:port instead of frp1.host_doamin:80

is this a request for feature or i just do not know how to do it ?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
可以试试 设为 `0`
https://github.com/fatedier/frp/blob/e81b36c5ba3ee0b4b88ed8832f4a302ed3289bda/conf/frps_full_example.toml#L52

**Comment by fatedier** [comment]
There are currently no supported plans.
