### ISSUE TITLE
From v0.55.0 to 0.57.0, linux_arm arch won't work and shows illegal instruction when its start

### ISSUE THREAD

**Issue by gbh19930406** [fatedier/frp#4199]
### Bug Description

From v0.55.0 to 0.57.0, linux_arm arch won't work and shows illegal instruction when its start

### frpc Version

0.55.1-0.57.0

### frps Version

0.55.1-0.57.0

### System Architecture

linux/arm

### Configurations
EXAMPLES OF INI FORMAT

FRPS AS BELOW

[common]
bind_addr = 0.0.0.0
bind_port = 7000
dashboard_port = 7500
dashboard_user = xxx
dashboard_pwd = xxxxxxxx
[#] dashboard_tls_mode = true
[#] dashboard_tls_cert_file = 
[#] dashboard_tls_key_file = 
subdomain_host = x.y.z
vhost_http_port = 80
vhost_https_port = 443
log_file = /dev/null
log_level = error
log_max_days = 1
token = xxxxxxxx
allow_ports = 8081, 10000-65535
max_pool_count = 200
tcp_mux = true
tcpmux_httpconnect_port = 1337
tcpmux_passthrough = false
max_ports_per_client = 6
tls_only = true
[#] tls_cert_file = 
[#] tls_key_file = 
[# ]tls_trusted_ca_file = 
enable_prometheus = true
custom_404_page = /jffs/404.html

FRPC AS BELOW

[common]
server_addr = x.y.z
server_port = 7000
login_fail_exit = false
pool_count = 0
protocol = tcp
tcp_mux = true
tls_enable = true
[#] tls_cert_file = 
[# ]tls_key_file = 
[#] tls_trusted_ca_file = 
admin_addr = 127.0.0.1
admin_port = 7400
admin_user = xxx
admin_pwd = xxxxxxxx
user = xxx
token = xxxxxxxx
authentication_timeout = 0
heartbeat_interval = 30
heartbeat_timeout = 90
dns_server = 8.8.8.8
start = proxya,proxyb

[proxya]
type = http
local_ip = 127.0.0.1
local_port = 7400
subdomain = frpc
use_compression = true
use_encryption = true
http_user = xxx
http_pwd = xxxxxxxx

[proxyb]
type = http
local_ip = 127.0.0.1
local_port = 80
subdomain = web
use_compression = true
use_encryption = true
http_user = xxx
http_pwd = xxxxxxxx

### Logs

illegal instruction

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by kingwilliam** [comment]
try to change config file to toml format

**Comment by gbh19930406** [comment]
However, arm64 arch using this ini format works well in version 0.57.0. And arm arch using this ini format works well in version 0.54.0.

**Comment by gbh19930406** [comment]
Since version 0.58.0 released, arm arch and armhf arch are separated, the problem has resolved.
