### ISSUE TITLE
[Feature Request] 增加命令行 强制以 TOML/JSON/INI 方式解析配置文件

### ISSUE THREAD

**Issue by grdll** [fatedier/frp#4200]
### Describe the feature request

希望可以以命令行 `-f` 的方式指定用什么方式启动 Frp ，如 `-f toml` / `-f ini`

Linux 下显示
`unmarshal ProxyConfig error: json: unknown field "use_Encryption"`
`unmarshal ProxyConfig error: json: unknown field "use_Compression"`
Linux 的 Frpc 在 toml 格式下完全没有办法在 `[[proxies]]` 栏目使用任何 `transport.` 参数。
然而 Windows 下完全没有问题。

已测试版本 `v0.57.0` / `v0.56.0` / `v0.55.1`

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by superzjg** [comment]
不太可能的。
哪个正确写法是没有下划线的。
transport.useEncryption
transport.useCompression

**Comment by grdll** [comment]
> 不太可能的。 正确toml写法是没有下划线的。 transport.useEncryption transport.useCompression

傻眼，仔细对比了几十个配置文件，Windows用的都是远古 v0.52.x 所以都没问题。
