### ISSUE TITLE
[Feature Request] Enable dashboard behind a reverse proxy

### ISSUE THREAD

**Issue by rui8832** [fatedier/frp#4203]
### Describe the feature request

Enable dashboard behind a reverse proxy:

I want my dashboard URL like: `https://some.domain.com/frp/`

My frps conf:

```
# frps.ini
[common]
bind_port = 7000

dashboard_port = 7500
dashboard_user = username
dashboard_pwd = password

```

My Nginx reserve proxy conf:

```
location /frp/ {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Connection "";
    proxy_pass http://192.168.0.2:7500/;
}

```

Now, it dosnot work.

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by rui8832** [comment]
I tried the fllowing Nginx reserve proxy conf and it works!

```
location /frp/ {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Connection "";
    proxy_pass http://192.168.0.2:7500/;
    proxy_redirect / /frp/;
}
```

**Comment by GitHub4LP** [comment]
> ### Describe the feature request
> Enable dashboard behind a reverse proxy:
> 
> I want my dashboard URL like: `https://some.domain.com/frp/`
> 
> My frps conf:
> 
> ```
> # frps.ini
> [common]
> bind_port = 7000
> 
> dashboard_port = 7500
> dashboard_user = username
> dashboard_pwd = password
> ```
> 
> My Nginx reserve proxy conf:
> 
> ```
> location /frp/ {
>     proxy_http_version 1.1;
>     proxy_set_header Host $host;
>     proxy_set_header Connection "";
>     proxy_pass http://192.168.0.2:7500/;
> }
> ```
> 
> Now, it dosnot work.
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Affected area
> * [ ]  Docs
> * [x]  Installation
> * [ ]  Performance and Scalability
> * [ ]  Security
> * [ ]  User Experience
> * [ ]  Test and Release
> * [ ]  Developer Infrastructure
> * [ ]  Client Plugin
> * [ ]  Server Plugin
> * [ ]  Extensions
> * [ ]  Others

how to make frps  behind a reverse proxy
