### ISSUE TITLE
树莓派3无法使用frpc并且编译错误

### ISSUE THREAD

**Issue by n0trace** [fatedier/frp#421]
版本 `0.13`
下载的包 [frp_0.13.0_linux_arm.tar.gz](https://github.com/fatedier/frp/releases/download/v0.13.0/frp_0.13.0_linux_arm.tar.gz)
系统 `archlinux`
架构 `aarch64`
```
[alarm@alarm frp]$ uname -a
Linux alarm 4.12.5-1-ARCH #1 SMP Sun Aug 6 16:44:48 MDT 2017 aarch64 GNU/Linux
```
执行错误
```
[alarm@alarm frpc]$ ./frpc -v
-bash: ./frpc: cannot execute binary file: Exec format error
```
然后试着自己编译，删除了makefile 的frps，go get 了 相关的包，然后编译错误

```
[alarm@alarm frp]$ make
go fmt ./assets/...
go fmt ./client/...
go fmt ./cmd/...
go fmt ./models/...
go fmt ./server/...
go fmt ./utils/...
go build -o bin/frpc ./cmd/frpc
# _/home/alarm/frpc/frp/cmd/frpc
cmd/frpc/main.go:77: cannot use conf (type "github.com/vaughan0/go-ini".File) as type "github.com/fatedier/frp/vendor/github.com/vaughan0/go-ini".File in argument to config.LoadClientCommonConf
cmd/frpc/main.go:159: cannot use conf (type "github.com/vaughan0/go-ini".File) as type "github.com/fatedier/frp/vendor/github.com/vaughan0/go-ini".File in argument to config.LoadProxyConfFromFile
make: *** [Makefile:25: frpc] Error 2
```
希望得到您的帮助，谢谢

**Comment by guoycx** [comment]
你好！我刚刚也遇到这样的问题了，不过 go get 项目到本机后，在go path目录下找到的frp项目源码是可以正常编译的，在其它目录编译就遇到这问题了。

   不过我用命令 go build main.go 编译无报错，但运行时出错为：
2017/08/11 12:43:15 [W] [control.go:121] login to server failed: address 400422: invalid port
address 400422: invalid port

 //**** frps.ini 文件内容为 ****//
[common]
bind_port = 40022
#vhost_http_port = 40023

//**** frpc.ini 文件内容为 ****//
[common]
server_addr = dogtail.xyz
server_port = 400422
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 40023

   刚遇到这个错误，在查中，同一配置文件在其他linux上可以正常运行，请问各位怎么解决啊？
   谢谢！

**Comment by WindGreen** [comment]
3b和3b+虽然是arm64 v8的芯片，但是raspbian是32的，所以只能安装arm v7的包

**Comment by CaiJinHao** [comment]
@WindGreen arm v7的包在哪下载，方便贴个地址吗
