### ISSUE TITLE
客户端一会就会断开

### ISSUE THREAD

**Issue by wendao8469759** [fatedier/frp#4211]
### Bug Description

客户端每分钟都会断开一次
![1715420128980](https://github.com/fatedier/frp/assets/32348566/d32a80f8-2682-4471-a02e-3a1dc0f3f771)

### frpc Version

0.51.0

### frps Version

0.51.0

### System Architecture

linux/amd64

### Configurations

[common]
server_addr = ***
server_port = 7000

admin_addr = 127.0.0.1
admin_port = 7400
admin_user = admin
admin_pwd = ****

[admin_ui]
type = tcp
local_port = 7400
remote_port = 7400

[api]
type = tcp
local_port = 9888
local_ip = 192.168.1.3
remote_port = 7401

[nginx_file]
type = tcp
local_port = 8600
local_ip = 192.168.1.3
remote_port = 7402

[vr_api]
type = tcp
local_port = 8088
local_ip = 192.168.1.4
remote_port = 7403

[vr_api_web]
type = tcp
local_port = 80
local_ip = 192.168.1.3
remote_port = 7404

[wx_gongzhonghao]
type = tcp
local_port = 8088
local_ip = 192.168.1.21
remote_port = 7405

[windows_yuancheng]
type = tcp
local_port = 3389
local_ip = 192.168.1.3
remote_port = 7406

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
提供**客户端**日志

**Comment by wendao8469759** [comment]
我发现，是网络环境问题
我的网络原本是这样的，  
   1. 猫直接拨号，然后电脑从猫直接直连过来
    2. 家里还有个小米路由器，为了统一，我把小米路由器改成了有线桥接的方式，让小米路由器的IP段和猫的IP段一样了。
    这种网络环境下 一分钟会断开一次，
    
   然后我改变了小米路由器的有线桥接，把他变成了下级路由器， 发现现在不在重连了
