### ISSUE TITLE
最新版0.58.0，报错vhost_http_port没有设置

### ISSUE THREAD

**Issue by Scau-Guang** [fatedier/frp#4213]
### Bug Description

start error: type [http] not supported when vhost http port is not set，但现在只有vhostHTTPPort

### frpc Version

0.58.0

### frps Version

0.58.0

### System Architecture

Linux

### Configurations

开web服务

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
提供配置
