### ISSUE TITLE
不能开机自启动

### ISSUE THREAD

**Issue by wjx0428** [fatedier/frp#4214]
### Bug Description

![image](https://github.com/fatedier/frp/assets/68766497/b7778eda-4c65-4233-be31-a0e6f86d9390)
不能开机自启动

### frpc Version

v0.57.0

### frps Version

v0.57.0

### System Architecture

linux/ard64

### Configurations

serverAddr = "xxx"
serverPort = 7000

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 8003

[[proxies]]
name = "ql"
type = "tcp"
localIP = "127.0.0.1"
localPort = 5700
remotePort = 8004

[[proxies]]
name = "rabbit"
type = "tcp"
localIP = "127.0.0.1"
localPort = 5702
remotePort = 8005

### Logs

May 12 12:13:25 armbian systemd[1]: Started frpc.service - frpc server.
May 12 12:13:25 armbian frpc[1528]: 2024-05-12 12:13:25.716 [I] [sub/root.go:142] start frpc service for config file [/root/frp/frpc.toml]
May 12 12:13:25 armbian frpc[1528]: 2024-05-12 12:13:25.716 [I] [client/service.go:294] try to connect to server...
May 12 12:13:25 armbian frpc[1528]: 2024-05-12 12:13:25.719 [W] [client/service.go:297] connect to server error: dial tcp xxx: connect: network is unreachable
May 12 12:13:25 armbian frpc[1528]: 2024-05-12 12:13:25.720 [I] [sub/root.go:160] frpc service for config file [/root/frp/frpc.toml] stopped
May 12 12:13:25 armbian frpc[1528]: login to the server failed: dial tcp xxx: connect: network is unreachable. With loginFailExit enabled, no additional retries will be attempted
May 12 12:13:25 armbian systemd[1]: frpc.service: Main process exited, code=exited, status=1/FAILURE
May 12 12:13:25 armbian systemd[1]: frpc.service: Failed with result 'exit-code'.
﻿

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by wjx0428** [comment]
添加到配置文件可以解决login_fail_exit = false

**Comment by Yo-gurts** [comment]
20241016 配置选项名称为：loginFailExit = false
https://gofrp.org/zh-cn/docs/reference/client-configures/
