### ISSUE TITLE
设置[[proxies]]

### ISSUE THREAD

**Issue by Leard-K** [fatedier/frp#4218]
### Bug Description

设置到第5个的时候，远程端口没有了
![image](https://github.com/fatedier/frp/assets/73871922/5a0e5103-edff-4a90-bbb2-9e7264f4013f)

### frpc Version

0.58.0

### frps Version

0.58.0

### System Architecture

linux/amd64

### Configurations

**frpc**
serverAddr = "xxxxx"
serverPort = 7000

auth.method = "token"
auth.token = "xxxxx"

webServer.addr = "0.0.0.0"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "admin_5GFKSt"
webServer.pprofEnable = false

# tls
#transport.tls.certFile = "/etc/frp/ssl/client.crt"
#transport.tls.keyFile = "/etc/frp/ssl/client.key"
#transport.tls.trustedCaFile = "/etc/frp/ssl/ca.crt"

[[proxies]]
name = "cloudreve"
type = "tcp"
localIP = "192.168.1.6"
localPort = 40033
remotePort = 40033
healthCheck.type = "tcp"

[[proxies]]
name = "1panel"
type = "tcp"
localIP = "192.168.1.6"
localPort = 14329
remotePort = 14329
healthCheck.type = "tcp"

[[proxies]]
name = "jellyfin"
type = "tcp"
localIP = "192.168.1.6"
localPort = 8096
remotePort = 8096
healthCheck.type = "tcp"

[[proxies]]
name = "frpc"
type = "tcp"
localIP = "192.168.1.6"
localPort = 7400
remotePort = 7400
healthCheck.type = "tcp"

[[proxies]]
name = "php_my_admin"
type = "tcp"
localIP = "192.168.1.6"
localPort = 8089
remotePort = 8089
healthCheck.type = "tcp"

**frps**
bindAddr = "0.0.0.0"
bindPort = 7000

#HTTPS 类型代理监听的端口，启用后才能支持 HTTPS 类型的代理。
vhostHTTPSPort = 7001

auth.method = "token"
auth.token = "xxxx"

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin_NFck2B"

#允许客户端设置的最大连接池大小，如果客户端配置的值大于此值，会被强制修改为最大值，默认为 5。
transport.maxPoolCount = 50

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Leard-K** [comment]
![image](https://github.com/fatedier/frp/assets/73871922/afb9e4a6-f0d1-4f2e-89be-ebeeefd66dbc)
貌似不是满多少就不能新增，很怪

**Comment by Leard-K** [comment]
frps的配置
![image](https://github.com/fatedier/frp/assets/73871922/4cb4c88d-6256-4b6d-bd06-2ad4578d1d88)
frpc的配置
![image](https://github.com/fatedier/frp/assets/73871922/8ddc67ec-0589-48c5-b868-b2a4de0d44a8)

**Comment by Leard-K** [comment]
应该是心跳检测把连接池耗光了

**Comment by xqzr** [comment]
```toml
#healthCheck.type = "tcp"
```
