### ISSUE TITLE
使用frp访问内网的ftp能上传但不能列出目录

### ISSUE THREAD

**Issue by dxkrs** [fatedier/frp#422]
frp v0.13.0
frps-linux
frpc-windows7

部署好后，通过代理访问内网ftp（内网服务器的ftp协议使用pasv模式）不能list出目录，在等待目录数据返回的时候一直卡着，但在卡着的时候，使用flashFXP的放弃命令功能（一个红色的交叉）放弃list命令的等待，却能成功显示list的目录，然后可以正常上传文件。

为什么不能正常list目录？frp不支持ftp连接吗？根据pasv模式的理解，列出目录命令在21端口发送，接收数据是在服务器主动提供的端口，需要客户端主动去连接，是不是frpc端在连接了FTP服务器的数据端口后没有正确返回给代理请求的机器呢？

**Comment by fatedier** [comment]
#219
