### ISSUE TITLE
重编译后客户端无法连接到服务器

### ISSUE THREAD

**Issue by nomoneynolife** [fatedier/frp#4222]
### Bug Description

参考 https://blog.csdn.net/gmowcey/article/details/128670433 去除了特征

服务器端成功运行，并可以看到端口已开启

![a1f](https://github.com/fatedier/frp/assets/53741948/785aca3e-aa93-4b4f-9c2f-596600d4c641)

客户端，配置文件检查没有问题，但就是无法启动，已经更换了热点，网络
![企业微信截图_17159090963913](https://github.com/fatedier/frp/assets/53741948/893b1299-bb55-44ba-823e-d9f23a5dfb35)

如果我关闭frps，然后FRPC提示：
connect to server error: dial tcp x.x.x.x:57000: connectex: No connection could be made because the target machine actively refused it.

我开启FRPS后，连接FPRC有时会提示：
 connect to server error: dial tcp x.x.x.x:57000: i/o timeout
login to the server failed: dial tcp x.x.x.x:57000: i/o timeout. With loginFailExit enabled, no additional retries will be attempted

### frpc Version

0.58.0

### frps Version

0.58.0

### System Architecture

linux/amd64, windows/amd64

### Configurations

serverAddr = "1.1.1.1"
serverPort = 57000
auth.token = "xxxxxx"

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 1234

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by nomoneynolife** [comment]
FRPS config
bindAddr = "0.0.0.0"
bindPort = 57000
auth.token = "xxxxxx"

webServer.addr = "0.0.0.0"
webServer.port = 57500
webServer.user = "admin"
webServer.password = "admin123@"

**Comment by fatedier** [comment]
请只用 github release 页面下载的二进制文件。

**Comment by nomoneynolife** [comment]
> 请只用 github release 页面下载的二进制文件。

那可不行，被公司安全软件识别了，分分钟直接口头警告
