### ISSUE TITLE
此应用无法在你的电脑上运行

### ISSUE THREAD

**Issue by muyibu** [fatedier/frp#4226]
### Bug Description

以前一直在用的是0.3x的版本, 今天发现版本已经迭代这么多了, 想着部署一个新版的, Linux上的frps已经正常跑起来了. 
在本地下载了一个Windows版的, 但是无法运行, 在网上也没找到相关的内容, 随后不同的版本挨着测试, 发现自0.43版本往后, 均是一样的错误, 也就是说我现在的电脑可运行的最高版本只能到0.43
操作系统: Win10专业工作站版 / 22H2 / 19045

### frpc Version

0.58

### frps Version

0.58

### System Architecture

windows/amd64

### Configurations

默认配置. frpc无法运行

### Logs

程序“frpc.exe”无法运行: 指定的可执行文件不是此操作系统平台的有效应用程序。所在位置 行:1 字符: 1
+ .\frpc.exe
+ ~~~~~~~~~~。
所在位置 行:1 字符: 1
+ .\frpc.exe
+ ~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by 428571c** [comment]
试试32位版本。 https://github.com/fatedier/frp/releases/download/v0.51.3/frp_0.51.3_windows_386.zip 我的Win10 Lot LTSC 2021测试能用。这好像是releases最后一个编译好的32位版本。

**Comment by muyibu** [comment]
> 试试32位版本。 https://github.com/fatedier/frp/releases/download/v0.51.3/frp_0.51.3_windows_386.zip 我的Win10 Lot LTSC 2021测试能用。这好像是releases最后一个编译好的32位版本。
> 
> 另外也可以测试用管理员权限运行cmd.exe来启动frpc，或者用这个[NSudo](https://github.com/M2TeamArchived/NSudo) 以trustedinstaller运行，（注意不要用这个“新版nsudo”https://github.com/M2Team/NanaRun 你不可能打开它，它本身就只是一个"此应用无法在你的电脑上运行"）
![image](https://github.com/fatedier/frp/assets/6924630/e53b0e72-c74a-403b-81cf-1c50d2e30f4e)
也是同样的错误, 无法启动. 使用管理员权限执行或者使用NSudo来执行都是一样的问题. 还是提示"此应用无法在你的电脑上运行"

**Comment by 428571c** [comment]
> > 试试32位版本。 https://github.com/fatedier/frp/releases/download/v0.51.3/frp_0.51.3_windows_386.zip 我的Win10 Lot LTSC 2021测试能用。这好像是releases最后一个编译好的32位版本。
> > 另外也可以测试用管理员权限运行cmd.exe来启动frpc，或者用这个[NSudo](https://github.com/M2TeamArchived/NSudo) 以trustedinstaller运行，（注意不要用这个“新版nsudo”https://github.com/M2Team/NanaRun 你不可能打开它，它本身就只是一个"此应用无法在你的电脑上运行"）
> 
> ![image](https://private-user-images.githubusercontent.com/6924630/333951007-e53b0e72-c74a-403b-81cf-1c50d2e30f4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODgzMjEsIm5iZiI6MTcxNjk4ODAyMSwicGF0aCI6Ii82OTI0NjMwLzMzMzk1MTAwNy1lNTNiMGU3Mi1jNzRhLTQwM2ItODFjZi0xYzUwZDJlMzBmNGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMTMwNzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzRhZmRiZGIwMmI0MmU2OTFhOThmMGQ0NjIxMWJhODViNzhmYzhkYjEzOTg1YTMxZmViNDgyOWEwNzBiMDQwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v3O3HDvc72teytlpTG1Qw4biIKSeEdzebhVHBDUjeW4)
> 
> 也是同样的错误, 无法启动. 使用管理员权限执行或者使用NSudo来执行都是一样的问题. 还是提示"此应用无法在你的电脑上运行"

用CMD.exe（管理员命令提示符）执行一下看看，不要用PowerShell。那个截图是Powershell。我这里直接就是能用的（测试系统为 Win10 22H2 不忘初心极限精简版 64位 https://www.pc528.net/22h2jixian.html ），Win10 LTSC2021 64位也可以。另外，请确定你的Win10不在S模式，不是Windows 10 SE。发一下你的系统信息。这个问题很玄学，我无法复现，也不知道具体原因。
