### ISSUE TITLE
Accept new mux stream error: broken pipe

### ISSUE THREAD

**Issue by chuntsky** [fatedier/frp#423]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
版本 0.13
下载的包 frp_0.13.0_linux_arm.tar.gz

**What operating system and processor architecture are you using (`go env`)?**
系统 centos7

**Configures you used:**
frps.ini

> [common]
bind_port = 7001
tcp_mux = true
vhost_http_port = 80
vhost_https_port = 443
dashboard_port = 7501
dashboard_user = admin
dashboard_pwd = admin7501
privilege_token = 12345679
privilege_allow_ports = 2000-3000,7001

frpc.ini

> [common]
server_addr = 123.249.20.198
server_port = 7001
privilege_token = 12345679
[web]
type = http
local_ip = 127.0.0.1
local_port = 80
use_encryption = false
use_compression = true
custom_domains = frp.jtlvhua.com`

控制台输出：
2017/08/11 06:21:02 [I] [service.go:83] frps tcp listen on 0.0.0.0:7001
2017/08/11 06:21:02 [I] [service.go:108] http service listen on 0.0.0.0:80
2017/08/11 06:21:02 [I] [service.go:124] https service listen on 0.0.0.0:443
2017/08/11 06:21:02 [I] [service.go:134] Dashboard listen on 0.0.0.0:7501
2017/08/11 06:21:02 [I] [main.go:112] Start frps success
2017/08/11 06:21:02 [I] [main.go:114] PrivilegeMode is enabled, you should pay more attention to security issues
2017/08/11 06:21:14 [I] [service.go:230] client login info: ip [14.18.157.98:30948] version [0.13.0] hostname [] os [linux] arch [amd64]
2017/08/11 06:21:14 [I] [proxy.go:209] [880aeb074ade5bfe] [web] http proxy listen for host [frp.jtlvhua.com] location []
2017/08/11 06:21:14 [I] [control.go:318] [880aeb074ade5bfe] new proxy [web] success
2017/08/11 06:21:20 [W] [service.go:214] Accept new mux stream error: broken pipe
2017/08/11 06:21:44 [W] [service.go:214] Accept new mux stream error: broken pipe

访问  http://frp.jtlvhua.com:7001/  总是 输出 Accept new mux stream error: broken pipe  
是我  哪里配置错误？
感谢！

**Comment by thiner** [comment]
我也碰到了一样的错误。服务器刚启动的时候是正常的，但是运行一段时间后就会发生这种错误，然后退出。

**Comment by fatedier** [comment]
忽略，连接断开正常提示。

如果有其他问题，描述具体信息。

**Comment by chuntsky** [comment]
frps.ini
修改如下

> vhost_http_port = 8080

frp.jtlvhua.com:8080  访问正常

感谢

**Comment by zhangs2018** [comment]
把客户端和服务端的时间调成一致，即可解决！

**Comment by shenzheke** [comment]
路由器和vps提示都正常，刚登上时还能看dashboard，再等一会用Chrome登指向路由器的域名加端口，提示未发送任何数据，也不是拒绝连接，以后再换个vps试试
