### ISSUE TITLE
[Feature Request] static_file: disable directory listing

### ISSUE THREAD

**Issue by Guanran928** [fatedier/frp#4233]
### Describe the feature request

Disable directory listing in plugin `static_file`.

I am hosting a Mastodon instance from home, and I am using frps to host it over NAT.

Mastodon need to serve media files under `example.org/system/` without file listing, or it will show "Your web server is misconfigured"
https://docs.joinmastodon.org/admin/optional/object-storage/#FS

![image](https://github.com/fatedier/frp/assets/68757440/de11ced8-6d58-4d17-a446-8da418326108)

### Describe alternatives you've considered

Install an additional web server and proxy it through frp. 

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
We currently will not provide more support for plugins like `static_file`, its purpose is only to quickly meet certain simple needs, for more complex strategies, it should be used in conjunction with a proxy like nginx.

For complex proxy capability requirements, we have considered this in v2, but it is a long-term plan and will not be implemented in the short term.
