### ISSUE TITLE
[Feature Request] 客户端日志增加日志类型，只有一个日志文件

### ISSUE THREAD

**Issue by mourenZhu** [fatedier/frp#4237]
### Describe the feature request

我想在frpc中的日志模块新增一个日志类型，新的日志类型的主要特点是只有一个日志文件，而不是像之前那样按天分割日志。
在只有一个日志文件时，可以设置日志文件的文件大小最大值，当超过最大值时，清空最早一部分日志。
也可以单文件，按天清空一部分日志。
日志配置可如下所示
LogConfig
logType string "日志类型，当日志类型为空或者没写时，为原始日志类型。当为 singleFileSize时为单文件按文件大小清空，当为singleFileDay时为单文件按天清空"  
maxFileSize string "最大日志文件大小，例如1KB， 1MB等等，在日志类型为 singleFileSize才生效。当文件大小超过最大值时，开始删除一部分日志文件"
removeFileSize string "当日志文件超过最大日志文件大小时，需要删除最前面多少文件，例如1KB, 1MB，在日志类型为 singleFileSize才生效。" 

如果作者没有时间做，本人实现了上述需求并且通过所以测试后，可否pull request?

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
类似的需求可以将标准输出重定向到文件之后由你自己编写的工具来管理，这个项目不会考虑支持这样的功能。
