### ISSUE TITLE
外网server frps命令日志中的close表示内网client挂了吗？

### ISSUE THREAD

**Issue by sungda** [fatedier/frp#424]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.13.0

**What operating system and processor architecture are you using (`go env`)?**
frps  Centos amd64
frpc  Ubuntu amd64

**Configures you used:**
frps 配置了
bind_port =
frpc 配置了
type = tcp
local_ip = 
local_port = 
remote_port = 

**Steps to reproduce the issue:**
1号简单地搭建了下，14号发现进不了内网，查看日志感觉内网的client挂了。
是不是仅仅是内网client断连了，重新连接就好了（回家了，不在client旁，没办法试，但想知道为什么）
2017/08/13 11:54:48 [1;34m[I] [proxy.go:76] [01d30818056c0exx] [frp1] get a new work connection: [115.xxx.xxx.xxx:3131][0m
2017/08/13 11:54:48 [1;34m[I] [proxy.go:76] [01d30818056c0exx] [frp1] get a new work connection: [115.xxx.xxx.xxx:3131][0m
2017/08/13 11:54:48 [1;33m[W] [service.go:214] Accept new mux stream error: broken pipe[0m
2017/08/13 11:54:48 [1;33m[W] [service.go:214] Accept new mux stream error: broken pipe[0m
2017/08/13 17:07:23 [1;33m[W] [service.go:214] Accept new mux stream error: broken pipe[0m
2017/08/13 17:07:23 [1;33m[W] [control.go:236] [01d30818056c0exx] read error: broken pipe[0m
2017/08/13 17:07:23 [1;34m[I] [control.go:208] [01d30818056c0exx] control writer is closing[0m
2017/08/13 17:07:23 [1;34m[I] [proxy.go:62] [01d30818056c0exx] [frp1] proxy closing[0m
2017/08/13 17:07:23 [1;34m[I] [control.go:277] [01d30818056c0exx] client exit success[0m
2017/08/13 17:07:23 [1;34m[I] [proxy.go:108] [01d30818056c0exx] [frp1] listener is closed[0m

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
是，网络断了。
