### ISSUE TITLE
启动frps失败

### ISSUE THREAD

**Issue by 759855630** [fatedier/frp#4241]
### Bug Description

![image](https://github.com/fatedier/frp/assets/45380727/b4b4a89e-385a-436b-8139-20846055dcc5)
通过frps  -c frps.ini启动脚本日志中到此就截止了，以前是正常使用的
![image](https://github.com/fatedier/frp/assets/45380727/b6839646-d7fb-4c0c-ae63-fdbbdc7b8a09)

### frpc Version

frp_0.41.0_linux_amd64

### frps Version

frp_0.41.0_linux_amd64

### System Architecture

linux/amd64

### Configurations

[common]
bind_port = 7000
vhost_https_port = 7010		#当代理出来的是web服务时，在外网访问http://vps的IP:7001
#dashboard_port状态以及代理统计信息展示,网址:7500可查看详情

#log_file日志文件log_level记录的日志级别log_max_days日志留存3天authentication_timeout超时时间
log_file = ./frps.log
log_level = info
log_max_days = 3
authentication_timeout = 0
#max_pool_count最大链接池,每个代理预先与后端服务器建立起指定数量的最大链接数
max_pool_count = 50

### Logs

2024/05/27 14:17:37 [I] [root.go:200] frps uses config file: frps.ini
2024/05/27 14:32:42 [I] [root.go:200] frps uses config file: frps.ini
2024/05/27 14:32:57 [I] [root.go:200] frps uses config file: frps.ini
2024/05/27 14:36:06 [I] [root.go:200] frps uses config file: frps.ini

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by 759855630** [comment]
![image](https://github.com/fatedier/frp/assets/45380727/2dfab060-f059-4eea-abc2-59a631c59198)
补内存使用情况

**Comment by fatedier** [comment]
首先请使用最新版本进行测试。
