### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by asdf5329** [fatedier/frp#4242]
### Describe the feature request

这个好像不支持域名，原来的是支持的，现在用域名的话会报错，希望加上域名，那样服务器更换的话客户端就不用再改了，还有就是希望frpc支持在线升级。远程升级生怕搞不好就再连不上了

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by wb1t** [comment]
域名一直都是支持的,我估计你买的阿里云类似的云服务器,被恶心的防火墙给挡住了,你用域名访问会有问题,用IP访问就没问题

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/issues/3778#issuecomment-1817034440
