### ISSUE TITLE
[功能请求]Commands 支持多代理运行

### ISSUE THREAD

**Issue by lintent** [fatedier/frp#4246]
### Describe the feature request

支持多代理使用参数加载，可以减少frps相关内容泄露，起码不是明文在配置文件中了。
字典+列表 的参数进行加载
如：
frpc -D {“token”:"fatedierAAAfrp",“server_addr”:"8.8.8.8",“server_port”:7000,"proxies":[{"name":"server1", type:"tcp","secretKey":"google","local_ip":"127.0.0.1","local_port"3389},{"name":"server2",type:"tcp","secretKey":"google","local_ip":"127.0.0.1","local_port"3389}]}

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
没有这方面的计划。
