### ISSUE TITLE
自动listener is closed

### ISSUE THREAD

**Issue by zhfish** [fatedier/frp#425]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.13.0

**What operating system and processor architecture are you using (`go env`)?**
Centos7.3 amd64

**Configures you used:**
```
➜  frp cat frps.ini
[common]
bind_port = 7000
bind_addr = 0.0.0.0
privilege_token = token
kcp_bind_port = 7000
authentication_timeout = 0
tcp_mux = true
```

**Steps to reproduce the issue:**
1. wait some hours
2.
3.

**Describe the results you received:**
```
Aug 15 13:30:41 iZwz9bjpjfqnlko994k3b1A frps[8557]: 2017/08/15 13:30:41 [I] [proxy.go:76] [dea5b86ca0aa9cc1] [sql] get a new work connection: [51.49.159.98:9409]
Aug 15 17:23:18 iZwz9bjpjfqnlko994k3b1A frps[8557]: 2017/08/15 17:23:18 [W] [service.go:214] Accept new mux stream error: broken pipe
Aug 15 17:23:18 iZwz9bjpjfqnlko994k3b1A frps[8557]: 2017/08/15 17:23:18 [W] [control.go:236] [dea5b86ca0aa9cc2] read error: broken pipe
Aug 15 17:23:18 iZwz9bjpjfqnlko994k3b1A frps[8557]: 2017/08/15 17:23:18 [I] [control.go:208] [dea5b86ca0aa9cc2] control writer is closing
Aug 15 17:23:18 iZwz9bjpjfqnlko994k3b1A frps[8557]: 2017/08/15 17:23:18 [I] [proxy.go:62] [dea5b86ca0aa9cc2] [sql] proxy closing
Aug 15 17:23:18 iZwz9bjpjfqnlko994k3b1A frps[8557]: 2017/08/15 17:23:18 [I] [control.go:277] [dea5b86ca0aa9cc2] client exit success
Aug 15 17:23:18 iZwz9bjpjfqnlko994k3b1A frps[8557]: 2017/08/15 17:23:18 [I] [proxy.go:108] [dea5b86ca0aa9cc2] [sql] listener is closed
```

**Describe the results you expected:**
no close

**Additional information you deem important (e.g. issue happens only occasionally):**
frpc从没有关闭过，之前有一次，重启frps，frpc自动重连上了。
现在再次重启frps，没有连上

frps和frpc是在每天凌晨重启一次。代理的是sql端口1433

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
你的日志一切正常，客户端掉线了。

至于客户端为什么掉线，是否有重连，是另外一个问题。

**Comment by zhfish** [comment]
客户端是pppoe，会掉线重连
至于为什么没有连上，还真不好去查看这个问题
只发生那一次没连上，后面没有了
关掉了哈
