### ISSUE TITLE
http basic认证问题，不断弹出认证窗口

### ISSUE THREAD

**Issue by manlinux** [fatedier/frp#4252]
### Bug Description

文档有缺失，需要补充下后端是tomcat/Jetty/Jenkins等应用等特殊情况

### frpc Version

0.58.0

### frps Version

0.58.0

### System Architecture

linux/amd64

### Configurations

httpUser = "abc"
httpPassword = "abc"

需要添加一个请求header信息：
requestHeaders.set.Authorization  = ""

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
可自行编辑文档后 提交
