### ISSUE TITLE
80访问的默认页面在哪里改呃？

### ISSUE THREAD

**Issue by fungjcode** [fatedier/frp#426]
The page you visit not found.

Sorry, the page you are looking for is currently unavailable.
Please try again later.
The server is powered by frp.
Faithfully yours, frp.

不想显示，但不知道在哪里删或改？

**Comment by fatedier** [comment]
目前不支持修改，不想显示可以不用 http 的类型，用 tcp。

**Comment by fungjcode** [comment]
不知道在哪里改为tcp类型？ 请大佬明示
