### ISSUE TITLE
[Feature Request] SSH服务获取真实的源ip

### ISSUE THREAD

**Issue by FoundAdd** [fatedier/frp#4262]
### Describe the feature request

经过frp转发后的连接，在ssh中显示的源地址都是`127.0.0.1`，文档里有提到用`proxy protocol`协议来发送真实的请求源信息，但是ssh服务好像不支持这个协议，请问是否有其他配置可以让ssh服务获得请求源信息
![image](https://github.com/fatedier/frp/assets/58539321/0e1a8432-c32b-466a-a8e9-f2930be3d334)

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
本地应用不支持 proxy protocol 的话就无法支持，可以搜索一下是否能结合其他支持 proxy protocol 的代理一起使用。
