### ISSUE TITLE
大佬们帮忙看看0.58.1连接不上，其他版本也连不上...

### ISSUE THREAD

**Issue by nomoneynolife** [fatedier/frp#4263]
### Bug Description

看看截图：

抓包看，TCP 3次握手已经完成，   
![企业微信截图_17174954059722](https://github.com/fatedier/frp/assets/53741948/400c5ea2-5037-4aac-979a-5fba4983c207)

客户端连接提示：   
![企业微信截图_1717495464759](https://github.com/fatedier/frp/assets/53741948/d68987dc-a0b4-4a93-add5-d4ef1d2f9d87)

本地到服务端的端口是正常的，   
![企业微信截图_17174955235043](https://github.com/fatedier/frp/assets/53741948/2a595e82-252e-48a7-a688-4efaf2f1b7e1)

这怎么解决。。请大佬们看看   

### frpc Version

0.58.1

### frps Version

0.58.1

### System Architecture

linux/amd64, windows/amd64

### Configurations

server
transport.tls.force = true

client
loginFailExit = true

其他都是正常的节点和IP配置

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by nomoneynolife** [comment]
我用热点抓包，发现 三次请求后，服务端在 IRC 协议后面还会发一个TCP请求，那就是我网络的问题？

这，端口也是通的，无语啊，。，

**Comment by gearfox** [comment]
我刚也发了个Issues，也是连不上

**Comment by JustinTangChina** [comment]
看log信息

**Comment by xqzr** [comment]
如果使用**域名**，可以看看
https://github.com/fatedier/frp/issues/3778#issuecomment-1817034440

**Comment by coolxy** [comment]
是不是开启了VPN之类的软件？我的就是如果开启v2raya后，就连接不上，关闭v2raya后几秒就连接上了

**Comment by lytpe** [comment]
系统架构这边云服务器会不会使用的 ARM架构，安装错frps 类型了 可以看下 服务器端 芯片类型使用  uname  -m  看下 如果是 x86_64 那使用 amd64安装包，如果是 aarch64 使用 arm64安装包

**Comment by lytpe** [comment]
系统架构这边云服务器会不会使用的 ARM架构，安装错frps 类型了 可以看下 服务器端 芯片类型使用  uname  -m  看下 如果是 x86_64 那使用 amd64安装包，如果是 aarch64 使用 arm64安装包

**Comment by daweichen** [comment]
同样遇到了，解决了吗？

**Comment by daweichen** [comment]
请问要怎么解决，快抓狂了。
