### ISSUE TITLE
frpc安装不成功，是否是缺DLL?

### ISSUE THREAD

**Issue by chyl168** [fatedier/frp#4266]
### Bug Description

WIN7X64下，frpc安装不成功，是否是缺DLL?
D:\111\frp_0.58.1_windows_amd64>frpc.exe -c frpc.toml
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x22fcf8)
        runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x47a37a

rax     0x0
rbx     0x11e4e78
rcx     0x126cfe8
rdx     0x20
rdi     0x7fffffde000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x12da2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0x11e3ec0
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

D:\111\frp_0.58.1_windows_amd64>.\frpc.exe -c .\frpc.toml
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x22fcf8)
        runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x47a37a

rax     0x0
rbx     0x11e4e78
rcx     0x126cfe8
rdx     0x20
rdi     0x7fffffde000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x12da2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0x11e3ec0
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

D:\111\frp_0.58.1_windows_amd64>./frpc -c ./frpc.toml
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

![image](https://github.com/fatedier/frp/assets/76003950/4dede076-9e3f-4ad7-86de-602131a1341f)

frps面板可以运行成功
![360截图20240606001753866](https://github.com/fatedier/frp/assets/76003950/011e4956-e4db-460b-882d-1d1c30a21909)

### frpc Version

0.58.1

### frps Version

0.58.1

### System Architecture

windows/amd64

### Configurations

![image](https://github.com/fatedier/frp/assets/76003950/0e958f16-a715-4d96-a595-57464a268eb8)

serverAddr = "1..."
serverPort = 5443

[[proxies]]
name = "test-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 33389

### Steps to reproduce

见截图，在上方"错误描述"
1. 运行管理员CMD到CMD
2. 修改配置TOML如截图（截图在上方"配置"）
3. CMD下运行安装命令
frpc.exe -c frpc.toml 
OR
.\frpc.exe -c .\frpc.toml
如果不带.exe扩展名，如运行./frpc -c ./frpc.toml，则提示：
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

4. 安装失败退出到CMD
D:\111\frp_0.58.1_windows_amd64>
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
不支持 win7，可以升级到最新的系统后再尝试。

**Comment by chyl168** [comment]
下载0.49.0版本后FRPC运行成功（服务器还是0.58.1），谢谢

fatedier ***@***.***> 于2024年6月6日周四 10:53写道：
