### ISSUE TITLE
xtcp 能获取到访问的真实ip吗？

### ISSUE THREAD

**Issue by wuai1024** [fatedier/frp#4268]
### Describe the feature request

目前 xtcp 类型的代理穿透，是提前通道公网服务器联系打洞后再直连访问的，打洞的时候双方的公网ip都能获取的。这个能不能透传下去啊。

希望能获取到tcp的真实ip，现在获取到的是 被访问端的 frpc ip。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
不能获取。
