### ISSUE TITLE
One port for multiple remote connections

### ISSUE THREAD

**Issue by storm66-ag** [fatedier/frp#4270]
### Describe the feature request

Hello Guys! 
Will be great if  the lot of remote frpc apps could to connected to the server to one same ports....
For example frps binds on the port 7000 and frpc1 will connect to the port 7000 and put the RemotePort like 1000, then frpc2 will connect to the 7000 and put the RemotePort like 10001..... etc 

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
无需额外配置，即可实现
