### ISSUE TITLE
android版本怎么安装和使用

### ISSUE THREAD

**Issue by xiaozanooo** [fatedier/frp#4272]
### Describe the feature request

android版本怎么安装和使用

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by YangYongAn** [comment]
可以直接看成品 https://github.com/AceDroidX/frp-Android
