### ISSUE TITLE
login to the server failed: session shutdown.

### ISSUE THREAD

**Issue by bowencool** [fatedier/frp#4273]
### Bug Description

frpc 连接不上。

### frpc Version

0.58.1

### frps Version

0.58.1

### System Architecture

linux/amd64

### Configurations

server 端启动没问题：
frps.toml
```
bindPort = x
vhostHTTPPort = x
vhostHTTPSPort = x
```

客户端启动总是报错，不知道为啥：
frpc.toml
```
serverAddr = "xx"
serverPort = xx

[[proxies]]
name = "test-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000
```

### Logs

```
2024-06-09 22:44:14.040 [I] [sub/root.go:142] start frpc service for config file [./frpc.toml]
2024-06-09 22:44:14.040 [I] [client/service.go:294] try to connect to server...
2024-06-09 22:44:19.043 [W] [client/service.go:297] connect to server error: session shutdown
2024-06-09 22:44:19.043 [I] [sub/root.go:160] frpc service for config file [./frpc.toml] stopped
login to the server failed: session shutdown. With loginFailExit enabled, no additional retries will be attempted
```
一开始明明是对的，我就尝试加了个 token，然后就连不上了，还原配置也连不上了。

两端都重启过，甚至都删掉 `frp_0.58.1_linux_amd64` 目录，都重新配置 port 也没成功连接

我快要抓狂了，明明就这几行配置，咋过了几分钟就连不上了呢，实在是看不出来了，帮帮我

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/issues/3778#issuecomment-1817034440

**Comment by bowencool** [comment]
出去玩了一天，回来没有改任何配置，自己就好了。。。

一直用 server ip 连接的，域名也早备案了而且没有过期。可能是外部因素吧。
