### ISSUE TITLE
[Feature Request] Configure remotePort on the Server

### ISSUE THREAD

**Issue by YXL76** [fatedier/frp#4276]
### Describe the feature request

The server selects the exposed port according to the proxy name, and there is no need to configure the `remotePort` on the client.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Please use a server plugin to implement.
