### ISSUE TITLE
unmarshal ProxyConfig error: json: unknown field "customDomains"

### ISSUE THREAD

**Issue by LandonDeam** [fatedier/frp#4277]
### Bug Description

Can't get frpc to start with a customDomains field, always returns `unmarshal ProxyConfig error: json: unknown field "customDomains"`

### frpc Version

0.58.1

### frps Version

0.58.1

### System Architecture

linux/amd64

### Configurations

# frpc.toml

serverAddr = "x.x.x.x"
serverPort = 7000

auth.method = "token"
auth.token = ""

[[proxies]]
name = "ssh"
type = "tcp"
customDomains = ["ssh.example.com"]
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000

includes = ["/etc/frp/frpc.d/*.toml"]

### Logs

unmarshal ProxyConfig error: json: unknown field "customDomains"

### Steps to reproduce

1. run `/usr/bin/frpc -c /etc/frp/frpc.toml` with the above `frpc.toml` file

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
`customDomains` is not for type `tcp`.

**Comment by Nian2000** [comment]
有点坑，
local_port = 8848 ✔
localPort = 8848 ❌（官网示例是这样的，但是很坑）

**Comment by metalbreeze** [comment]
太坑了，把后缀toml 换成ini 貌似可以。
