### ISSUE TITLE
按照gofrp.org官网，提供的p2p教程示例，两台服务器部署的时候json解析失败

### ISSUE THREAD

**Issue by lazywoo** [fatedier/frp#4279]
### Bug Description

[[proxies]]
name = "p2p_ssh_visitor"
type = "xtcp"
serverName = "p2p_ssh"
secretKey = "abcdefg"
bindAddr = "127.0.0.1"
bindPort = 6000

执行./frpc -c frpc.toml

报错unmarshal ProxyConfig error: json: unknown field "bindAddr"

### frpc Version

0.58.1

### frps Version

0.58.1

### System Architecture

linux/amd64

### Configurations

[[proxies]]
name = "p2p_ssh_visitor"
type = "xtcp"
serverName = "p2p_ssh"
secretKey = "abcdefg"
bindAddr = "127.0.0.1"
bindPort = 6000

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by A2uria** [comment]
`[[proxies]]` 改成 `[[visitor]]`

**Comment by A2uria** [comment]
`[[proxies]]` 改成 `[[visitors]]`

**Comment by lazywoo** [comment]
thanks， 感谢。根据@A2ruia的解惑，可以实现p2p了

**Comment by lazywoo** [comment]
☺
