### ISSUE TITLE
服务端执行成功，但是却连接不了，没有防火墙

### ISSUE THREAD

**Issue by qxwo** [fatedier/frp#428]
检测服务器端的端口正常监听，但是外部检测确是关闭的
错误提示
D:\frp_0.13.0_windows_amd64>frpc.exe -c frpc.ini
2017/08/15 15:56:18 [W] [control.go:121] login to server failed: di
8.10.10:7000: connectex: A connection attempt failed because the co
did not properly respond after a period of time, or established co
ed because connected host has failed to respond.
dial tcp 192.168.10.10:7000: connectex: A connection attempt failed
connected party did not properly respond after a period of time, or
connection failed because connected host has failed to respond.

**Comment by qxwo** [comment]
查看监听端口是tcp6，是ipv6的原因吗？

**Comment by qxwo** [comment]
系统是centos7 64位
服务端日志
2017/08/15 16:15:11 [I] [service.go:79] frps tcp listen on 0.0.0.0:7000
2017/08/15 16:15:11 [I] [service.go:88] frps kcp listen on udp 0.0.0.0:7000
2017/08/15 16:15:11 [I] [service.go:104] http service listen on 0.0.0.0:8888
2017/08/15 16:15:11 [I] [service.go:120] https service listen on 0.0.0.0:8443
2017/08/15 16:15:11 [I] [service.go:130] Dashboard listen on 0.0.0.0:7500
2017/08/15 16:15:11 [I] [main.go:112] Start frps success
2017/08/15 16:15:11 [I] [main.go:114] PrivilegeMode is enabled, you should pay more attention to security issues
服务端端口情况
[root@localhost ~]# netstat -tuln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp6       0      0 :::7500                 :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::8888                 :::*                    LISTEN     
tcp6       0      0 :::7000                 :::*                    LISTEN     
tcp6       0      0 :::1088                 :::*                    LISTEN     
udp        0      0 0.0.0.0:33854           0.0.0.0:*                          
udp6       0      0 :::1088                 :::*                  
本地内网测试，没有防火墙

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
