### ISSUE TITLE
[Feature Request] 是否可以增加压缩条件

### ISSUE THREAD

**Issue by arkerwu** [fatedier/frp#4280]
### Describe the feature request

比如100K以下的不压缩,就跟ngnix那样指定一个最小压缩的参数;
太小的数据压缩得到的性能提升有限,并且还会占用CPU,得不偿失;
100K以上的压缩得到的传输加速效果更为明显;

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
一般来说，建议在自己的应用层做好压缩，不要依赖 frp，frp 的压缩是流式的，效果有限。
