### ISSUE TITLE
Log Failed Authentication Attempts for HTTP Basic Auth on Dashboard [Feature Request] 

### ISSUE THREAD

**Issue by JmmyGun** [fatedier/frp#4282]
### Describe the feature request

First, thank you for the excellent work on frp. It's an invaluable tool for many of us.

I would like to request a new feature for frps: the ability to log failed authentication attempts for HTTP Basic Auth on the dashboard. Currently, successful logins are logged, but failed attempts are not, which makes it difficult to monitor and enhance security.

Logging failed attempts would greatly aid in security monitoring and incident response. Additionally, this feature would allow the implementation of tools like fail2ban to further secure the system.

Thank you for considering this feature if it is possible.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
The features in this aspect is very good, including IP whitelists and blacklists, and we plan to support this in the future.

However, in the current version, we will not introduce such capabilities extensively. Instead, we aim to focus on architectural restructuring to facilitate the implementation of more non-core Layer 7 capabilities through plugins in the future.

**Comment by JmmyGun** [comment]
Thanks anyway for taking my feature into consideration, I look forward to future updates. and thanks again for the wonderful "frp"
