### ISSUE TITLE
[Feature Request] 目前只想client端使用http_proxy功能，

### ISSUE THREAD

**Issue by leetomlee123** [fatedier/frp#4283]
### Describe the feature request

目前包有10m，有什么方法可以减小包大小吗，求指教。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
没有办法，建议使用其他的具有 http proxy 的工具替代。
