### ISSUE TITLE
frps dashboard 代理类型增加 xtcp

### ISSUE THREAD

**Issue by wuai1024** [fatedier/frp#4285]
### Describe the feature request

<img width="1679" alt="image" src="https://github.com/fatedier/frp/assets/13379708/52c4441b-b7dc-4b03-8b00-25d907c36613">

目前图标上显示了 xtcp 有3个代理，但是左侧看不到，没有 xtcp 的类型选择。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
`/api/proxy/xtcp`
