### ISSUE TITLE
最新版frp启动后无法访问控制面板

### ISSUE THREAD

**Issue by arvinws** [fatedier/frp#4289]
### Bug Description

我在服务器上配置了frp_0.58.1_linux_amd64版本,运行后无法访问控制面板，输出的日志显示正常启动。服务器防火墙关闭了，服务器的控制台端口也都放行了，还是不能访问

### frpc Version

0.58.1

### frps Version

0.58.1

### System Architecture

linux/amd64

### Configurations

[common]
bind_port = 7055
dashboard_port = 7510  # 可选
dashboard_user = "admin"
dashboard_pwd = "11111"
token = "1111111111"
tls_enable = true  # 启用 TLS 加密

### Logs

[root@VM-20-10-centos frp_0.58.1_linux_amd64]# ./frps -c frps.toml
WARNING: ini format is deprecated and the support will be removed in the future, please use yaml/json/toml format instead!
2024-06-19 16:13:23.028 [I] [frps/root.go:105] frps uses config file: frps.toml
2024-06-19 16:13:23.153 [I] [server/service.go:237] frps tcp listen on 0.0.0.0:7055
2024-06-19 16:13:23.153 [I] [frps/root.go:114] frps started successfully

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
~`[common]`~

**Comment by arvinws** [comment]
> ~`[common]`~

删除格式不对，会报错error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1.ServerConfig

**Comment by arvinws** [comment]
**补充下完整的配置信息**
**这是文件路径，和权限信息**
[root@VM-20-10-centos frp_0.58.1_linux_amd64]# pwd
/home/frp_0.58.1_linux_amd64
[root@VM-20-10-centos frp_0.58.1_linux_amd64]# ls -lsa
total 31980
  4 drwxr-xr-x 2 root root   4096 Jun 20 08:59 .
  4 drwxr-xr-x. 4 root root   4096 Jun 20 08:58 ..
14136 -rwxr-xr-x 1 root root 14471320 May 31 14:37 frpc
  4 -rw-r--r-- 1 root root   142 May 31 14:40 frpc.toml
17816 -rwxr-xr-x 1 root root 18239640 May 31 14:37 frps
  4 -rw-r--r-- 1 root root   247 Jun 20 08:59 frps.toml
  12 -rw-r--r-- 1 root root  11358 May 31 14:40 LICENSE

**这是frps.toml完整内容**
[common]
bind_addr = 0.0.0.0
bind_port = 55289
dashboard_addr = 0.0.0.0
dashboard_port = 7510
dashboard_user = "admin"
dashboard_pwd = "1111111111"
token = "11111111111111111111111"
tls_enable = true # 启用 TLS 加密

**这是frps.service完整内容**
[Unit]
Description=frp server service
After=network.target
Wants=network-online.target


[Service]
Type=simple
User=root 
Group=root 
WorkingDirectory=/home/frp_0.58.1_linux_amd64 # frp 程序所在的目录
ExecStart=/home/frp_0.58.1_linux_amd64/frps -c /home/frp_0.58.1_linux_amd64/frps.toml
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target

**运行后错误日志**
[root@VM-20-10-centos system]# sudo systemctl daemon-reload
[root@VM-20-10-centos system]# sudo systemctl restart frps.service
[root@VM-20-10-centos system]# sudo journalctl -u frps.service -n 10
-- Logs begin at Tue 2024-03-12 13:37:29 CST, end at Thu 2024-06-20 10:05:48 CST. --
Jun 20 10:05:38 VM-20-10-centos systemd[1]: frps.service: control process exited, code=exited status=217
Jun 20 10:05:38 VM-20-10-centos systemd[1]: Failed to start frp server service.
Jun 20 10:05:38 VM-20-10-centos systemd[1]: Unit frps.service entered failed state.
Jun 20 10:05:38 VM-20-10-centos systemd[1]: frps.service failed.
Jun 20 10:05:48 VM-20-10-centos systemd[1]: Stopped frp server service.
Jun 20 10:05:48 VM-20-10-centos systemd[1]: Started frp server service.
Jun 20 10:05:48 VM-20-10-centos systemd[15873]: Failed at step USER spawning /home/frp_0.58.1_linux_amd64/frps: No such process
Jun 20 10:05:48 VM-20-10-centos systemd[1]: frps.service: main process exited, code=exited, status=217/USER
Jun 20 10:05:48 VM-20-10-centos systemd[1]: Unit frps.service entered failed state.
Jun 20 10:05:48 VM-20-10-centos systemd[1]: frps.service failed.
