### ISSUE TITLE
[Feature Request] 使用XTCP或者STCP类型配置客户端问题

### ISSUE THREAD

**Issue by arvinws** [fatedier/frp#4291]
### Describe the feature request

使用XTCP或者STCP类型配置客户端，开放内网机器的远程服务。那访问端也需要配置frpc才可以访问客户端，那用户使用移动端要怎么远程呢？比如ios的RDClient，微软官方出的远程工具。这种情况客户端是不是不能用XTCP、STCP？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by superzjg** [comment]
你说对了。
目前安卓有frpc了，ios没看到。

**Comment by xqzr** [comment]
iOS 通过 iSH 运行 frpc

**Comment by wuai1024** [comment]
> iOS 通过 iSH 运行 frpc

这是什么啊，ISH

**Comment by arvinws** [comment]
> iOS 通过 iSH 运行 frpc

再深入点需求，我想使用XTCP、STCP，随时随地的远程到客户端，而每次在我访问者电脑上再配置一份frpc。tcp类型满足需求，但是不够安全，有什么办法能解决呢？

**Comment by xqzr** [comment]
> > iOS 通过 iSH 运行 frpc
> 
> 再深入点需求，我想使用XTCP、STCP，随时随地的远程到客户端，而每次在我访问者电脑上再配置一份frpc。tcp类型满足需求，但是不够安全，有什么办法能解决呢？

使用强密码、紧跟“Windows 更新”

**Comment by superzjg** [comment]
> > iOS 通过 iSH 运行 frpc
> 
> 再深入点需求，我想使用XTCP、STCP，随时随地的远程到客户端，而不是每次在我访问者电脑上再配置一份frpc。tcp类型满足需求，但是不够安全，有什么办法能解决呢？

可以的，我就这么用过，你只要在路由器上配置一个frpc，设置stcp的访问者即可，要注意设置本地有效的绑定地址（而不是还回地址），在此路由器下的所有客户端，都可以通过此绑定地址访问，不需要安装frpc。
