### ISSUE TITLE
unmarshal ProxyConfig error: json: unknown field "remotePort"

### ISSUE THREAD

**Issue by cffycls** [fatedier/frp#4293]
### Bug Description

both frps and frpc the version is v0.58.1, in debian12.

./frpc -c ./frpc.toml
unmarshal ProxyConfig error: json: unknown field "remotePort"

### frpc Version

0.58.1

### frps Version

0.58.1

### System Architecture

linux/amd64

### Configurations

host1:client 192.168.10.50 ---- [error]
```
// cat frpc.toml
serverAddr = "192.168.10.11"
serverPort = 7000

[[proxies]]
name = "bt-mysql"
type = "stcp"
localIP = "127.0.0.1"
localPort = 3306
remotePort = 3306
```

host2:server 192.168.10.11 ---- [ok]
./frps -c ./frps.toml
2024-06-22 15:21:45.946 [I] [frps/root.go:105] frps uses config file: ./frps.toml
2024-06-22 15:21:46.093 [I] [server/service.go:237] frps tcp listen on 0.0.0.0:7000
2024-06-22 15:21:46.093 [I] [frps/root.go:114] frps started successfully
```
// cat frps.toml
bindPort = 7000
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml#L330-L339
