### ISSUE TITLE
FRPC unmarshal ProxyConfig error

### ISSUE THREAD

**Issue by JmmyGun** [fatedier/frp#4294]
### Bug Description

sudo frpc -c /etc/frpc/frpc.toml 
unmarshal ProxyConfig error: json: unknown field "webServer"

sudo frpc -c /etc/frpc/frpc.toml 
unmarshal ProxyConfig error: json: unknown field "log"

### frpc Version

0.58.1 armhf

### frps Version

0.58.1 amd64

### System Architecture

frps_linux/amd64 frpc_linux/armv7l

### Configurations

#* Configurazione del client test2

#* il tuo nome user proxy {user}.{proxy}
user = "test2"

#* Indirizzo e porta server
serverAddr = "test.com"
serverPort = 7000

#* Metodo di autenticazione
auth.method = "token"    
#* Token di autenticazione
auth.token = "eh!volevi"

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22    
remotePort = 20222

[[proxies]]
name = "web"
type = "https"  
localIP = "127.0.0.1"
localPort = 1880
subdomain = "test2"

#* console or real logFile path like ./frpc.log
log.to = "/home/test2/data_store/resource/frpc.log"
#* trace, debug, info, warn, error
log.level = "info"
log.maxDays = 3
#* disable log colors when log.to is console, default is false
log.disablePrintColor = false

webServer.addr = "127.0.0.1"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "admin"

### Logs

when I enable the logging options

#console or real logFile path like ./frpc.log
log.to = "/home/test2/data_store/resource/frpc.log"
#* trace, debug, info, warn, error
log.level = "info"
log.maxDays = 3
#* disable log colors when log.to is console, default is false
log.disablePrintColor = false

$ sudo frpc -c /etc/frpc/frpc.toml
unmarshal ProxyConfig error: json: unknown field "log"

when I enable Client Admin UI

webServer.addr = "127.0.0.1"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "admin"

$ sudo frpc -c /etc/frpc/frpc.toml
unmarshal ProxyConfig error: json: unknown field "webServer"

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
You need to follow the syntax rules of YAML.
