### ISSUE TITLE
I have set up webserver, but after starting frps, I am unable to access the dashboard

### ISSUE THREAD

**Issue by xinoer** [fatedier/frp#4296]
### Bug Description

I have set up webserver, but after starting frps, I am unable to access the dashboard
The ‘frps.toml’ file is as follows:
[common]
bind_port = 7000
auth.method = "token"
auth.token = "123456"

webServer.addr = "127.0.0.1"
webServer.port = 7001
webServer.user = "admin"
webServer.password = "admin"

log_file = ./frps.log
log_level = info
log_max_days = 3

vhostHTTPSPort = 443
subdomain_host = 123.com

### frpc Version

frp_0.58.0

### frps Version

frp_0.58.0

### System Architecture

windows_amd64

### Configurations

[common]
bind_port = 7000
auth.method = "token"
auth.token = "123456"

web服务器.addr = “127.0.0.1”
web服务器.port = 7001
web服务器.user = “管理员”
web服务器.password = “管理员”

log_file = ./frps.log
log_level = info
log_max_days = 3

vhostHTTPSPort = 443
subdomain_host = 123.com

### Logs

The log is as follows：
2024-06-24 10:27:29.400 [I] [frps/root.go:105] frps uses config file: frps.toml
2024-06-24 10:27:29.534 [I] [server/service.go:237] frps tcp listen on 0.0.0.0:7000
2024-06-24 10:27:29.534 [I] [frps/root.go:114] frps started successfully

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by wuai1024** [comment]
现在新版的已经没有这个参数了 ~~[common]~~

```shell
webServer.addr = "0.0.0.0"
```

**Comment by arvinws** [comment]
参考这个可以成功http://blog.168hot.cn/448.html

**Comment by xiaoheibaobao** [comment]
请问你的问题解决了吗
，我也是这样
