### ISSUE TITLE
不兼容 windows server 2019 with containers 数据中心版

### ISSUE THREAD

**Issue by workmengxue** [fatedier/frp#4297]
### Bug Description

C:\Users\Administrator\Desktop\frp>frps -c ./frps.toml
该版本的 C:\Users\Administrator\Desktop\frp\frps.exe 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。

### frpc Version

0.58.1

### frps Version

0.58.1

### System Architecture

windows/amd64

### Configurations

C:\Users\Administrator\Desktop\frp>frps -c ./frps.toml
该版本的 C:\Users\Administrator\Desktop\frp\frps.exe 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。

### Logs

C:\Users\Administrator\Desktop\frp>frps -c ./frps.toml
该版本的 C:\Users\Administrator\Desktop\frp\frps.exe 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
确实不兼容，请更新到最新的操作系统后再重试。

**Comment by JianJroh** [comment]
win11 23H2 版本一样问题
