### ISSUE TITLE
怎么配置一个域名对应两个或者多个端口同时转发

### ISSUE THREAD

**Issue by Alanapi** [fatedier/frp#430]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
最新 github 上下载编译的版本

**What operating system and processor architecture are you using (`go env`)?**
 go 环境配置正常

**Configures you used:**
 默认设置

**Steps to reproduce the issue:**
frpc.ini
[web01]
type = http
local_ip = 127.0.0.1
local_port = 8000
subdomain = web01
[web02]
type = http
local_ip = 127.0.0.1
local_port = 8001
subdomain = web01

**Describe the results you received:**
[web01]
type = http
local_ip = 127.0.0.1
local_port = 8000
subdomain = web01
[web02]
type = http
local_ip = 127.0.0.1
local_port = 8001
subdomain = web01
出现错误%%……

**Describe the results you expected:**
我想实现一个本地域名，loacl_port 有两个端口或者多个端口可以转发，
类似 
[web01]
type = http
local_ip = 127.0.0.1
local_port = 8001，8002，8003
subdomain = web01
这样的设置？？？？？

**Additional information you deem important (e.g. issue happens only occasionally):**
无

**Can you point out what caused this issue (optional)**
无

**Comment by fatedier** [comment]
不支持同一个域名转发到两个本地端口。

1. 支持 URL 路由，同一个域名的不同 url 可以转发到不同的本地端口。
2. 如果是需要负载均衡的功能，目前还不支持，但是后续有支持的计划。
