### ISSUE TITLE
[Feature Request] I hope it to support customizing error page if server fails to connect all clients

### ISSUE THREAD

**Issue by ynbgit** [fatedier/frp#4302]
# Now, I cannot modify error page below

![Snipaste_2024-06-26_02-09-10](https://github.com/fatedier/frp/assets/28495600/218a688f-df0b-400c-ba6b-768c1cb0df6b)

# I find source code is here, but I don't know how to  modify

https://github.com/fatedier/frp/blob/939c4907689832b6f15f6ff163e15d2b3adad9ff/pkg/util/vhost/resource.go#L44

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Use any IDE you like to modify the code ~

**Comment by ynbgit** [comment]
> Use any IDE you like to modify the code ~

I hope the backend responses a json fromat to me so that I can use javascript to control my page error info to users

**Comment by ynbgit** [comment]
> Use any IDE you like to modify the code ~

@fatedier  I hope the backend responses a json fromat to me so that I can use javascript to control my page error info to users 

> Use any IDE you like to modify the code ~

@fatedier I hope the backend responses a json fromat to me so that I can use javascript to control my page error info to users
