### ISSUE TITLE
XTCP 比 TCP 更耗资源吗？

### ISSUE THREAD

**Issue by hzqim** [fatedier/frp#4304]
### Bug Description

使用DOCKER部署，在相同的机器，相同的时间段走 IPV6， 看同一个在线视频，XTCP没有添加压缩选项，TCP的速度几乎是XTCP的两倍，在后台观察到TCP模式下 CPU 使用率在 13% 左右浮动，而XTCP的CPU使用率大约是 35%. 

### frpc Version

0.58.1

### frps Version

0.58.1

### System Architecture

SERVER/Debian/amd64, CLIENT/OpenWRT/arm64

### Configurations

这是 XTCP 协议固有的缺点吗？比如 NAT 开销，但 IPV6 应该不用 NAT？

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by wuai1024** [comment]
ipv6 我理解是可以直连的啊。目前我用了很多 `xtcp` 没有测试过性能问题。

**Comment by xqzr** [comment]
xtcp 访问端和客户端之间连接，使用 QUIC（基于 UDP）
