### ISSUE TITLE
远程桌面 3389 udp开启失败

### ISSUE THREAD

**Issue by iwdm-cc** [fatedier/frp#4307]
### Bug Description

控制端显示的协议还是tcp，没法激活udp？

被控制端已开udp协议支持。
![image](https://github.com/fatedier/frp/assets/61677996/f4cc617e-181d-44fa-b577-63fe82d12c5e)
 

### frpc Version

0.58.1

### frps Version

0.58.1

### System Architecture

linux/amd64, windows/amd64

### Configurations

frpc.toml
`serverAddr = "xxxx"
serverPort = 7001
transport.protocol = "kcp"
transport.tls.enable = true

[[proxies]]
name = "test-http"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3389
remotePort = 6000

[[proxies]]
name = "zc-udp"
type = "udp"
localIP = "127.0.0.1"
localPort = 3389
remotePort = 6000`

frps.toml
`bindPort = 7001 
kcpBindPort = 7001`

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/issues/3972#issuecomment-2196367825
