### ISSUE TITLE
Windows10 客户端 An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by xeeoon** [fatedier/frp#431]
版本：v0.13.0
Server端操作系统：Linux Centos 6.8
Client ：Windows 10 企业版 1703
服务端一切正常，处于外网独立ip的环境。

客户端先后试过：
windows server 2003（内网），可连接，一切正常；
windows 7 （外网ip），可连接，一切正常；
windwos 7 （虚拟机，宿主机也处于内网环境），可连接，一切正常；

唯独一台内网中的Windows10链接出现问题：
CMD：
C:\Users\jinzh\Desktop\frp_0.9.3_windows_amd64>frpc -c frpc_min.ini
2017/08/19 12:49:06 [main.go:109] [I] Start frpc success
2017/08/19 12:49:07 [control.go:190] [E] ProxyName [web], read from server error, read tcp 192.168.1.102:50161->104.224.14x.xxx:5443: wsarecv: An existing connection was forcibly closed by the remote host.
2017/08/19 12:49:07 [control.go:39] [E] ProxyName [web], connect to server failed!
2017/08/19 12:49:07 [main.go:112] [W] All proxy exit!

PowerShell：
PS C:\Users\jinzh\Desktop\frp_0.9.3_windows_amd64> ./frpc -c ./frpc_in.ini
2017/08/19 12:50:11 [main.go:109] [I] Start frpc success
2017/08/19 12:50:11 [control.go:190] [E] ProxyName [web], read from server error, read tcp 192.168.1.102:50168->104.224.14x.xxx:5443: wsarecv: An existing connection was forcibly closed by the remote host.
2017/08/19 12:50:11 [control.go:39] [E] ProxyName [web], connect to server failed!
2017/08/19 12:50:11 [main.go:112] [W] All proxy exit!

防火墙为关闭状态。

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
