### ISSUE TITLE
frp运行报错

### ISSUE THREAD

**Issue by korben1029** [fatedier/frp#4313]
### Bug Description

运行报错
系统版本：Linux server 2.6.9-78.ELsmp #1 SMP Wed Jul 9 15:39:47 EDT 2008 i686 i686 i386 GNU/Linux
[root@server frp_0.51.3_linux_386]# ./frpc
futexwakeup addr=0x8cf7658 returned -38
futexwakeup addr=0x8d09af0 returned -38
fatal error: unexpected signal during runtime execution
futexwakeup addr=0x8cf7658 returned -38
futexwakeup addr=0x8d09af0 returned -38
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1006 pc=0x807cb32]

runtime stack:
runtime.throw({0x877aad8, 0x2a})
        runtime/panic.go:1047 +0x4d fp=0x9c5fe34 sp=0x9c5fe20 pc=0x808072d
runtime.sigpanic()
        runtime/signal_unix.go:825 +0x2b8 fp=0x9c5fe4c sp=0x9c5fe34 pc=0x8097ce8
runtime.futexwakeup(0x8d09af0, 0x1)
        runtime/os_linux.go:94 +0x82 fp=0x9c5fe78 sp=0x9c5fe4c pc=0x807cb32
runtime.unlock2(0x8d09af0)
        runtime/lock_futex.go:121 +0x50 fp=0x9c5fe88 sp=0x9c5fe78 pc=0x8052700
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.printunlock()
        runtime/print.go:79 +0x49 fp=0x9c5fe90 sp=0x9c5fe88 pc=0x8082539
runtime.futexwakeup.func1()
        runtime/os_linux.go:91 +0x7f fp=0x9c5fea4 sp=0x9c5fe90 pc=0x807cbbf
runtime.futexwakeup(0x8cf7658, 0x1)
        runtime/os_linux.go:90 +0x7d fp=0x9c5fed0 sp=0x9c5fea4 pc=0x807cb2d
runtime.unlock2(0x8cf7658)
        runtime/lock_futex.go:121 +0x50 fp=0x9c5fee0 sp=0x9c5fed0 pc=0x8052700
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.mcommoninit(0x9c80000, 0x4)
        runtime/proc.go:852 +0x1b3 fp=0x9c5ff10 sp=0x9c5fee0 pc=0x8084c53
runtime.allocm(0x9c3c600, 0x88483b8, 0x4)
        runtime/proc.go:1834 +0xe6 fp=0x9c5ff38 sp=0x9c5ff10 pc=0x80867d6
runtime.newm(0x88483b8, 0x9c3c600, 0x4)
        runtime/proc.go:2197 +0x56 fp=0x9c5ff54 sp=0x9c5ff38 pc=0x8087016
runtime.startm(0x9c3c600, 0x1, 0x0)
        runtime/proc.go:2423 +0x1cf fp=0x9c5ff80 sp=0x9c5ff54 pc=0x808779f
runtime.wakep()
        runtime/proc.go:2559 +0xca fp=0x9c5ffa0 sp=0x9c5ff80 pc=0x8087cda
runtime.resetspinning()
        runtime/proc.go:3262 +0x5b fp=0x9c5ffb0 sp=0x9c5ffa0 pc=0x8089b9b
runtime.schedule()
        runtime/proc.go:3384 +0xec fp=0x9c5ffcc sp=0x9c5ffb0 pc=0x8089f7c
runtime.mstart1()
        runtime/proc.go:1506 +0xad fp=0x9c5ffdc sp=0x9c5ffcc pc=0x8085f3d
runtime.mstart0()
        runtime/proc.go:1456 +0x5a fp=0x9c5ffec sp=0x9c5ffdc pc=0x8085e7a
runtime.mstart()
        runtime/asm_386.s:271 +0x5 fp=0x9c5fff0 sp=0x9c5ffec pc=0x80b3d45

goroutine 1 [runnable, locked to thread]:
runtime.gopark(0x88482ec, 0x9c68030, 0xe, 0x17, 0x2)
        runtime/proc.go:381 +0x108 fp=0x9c4a754 sp=0x9c4a740 pc=0x80837c8
runtime.chanrecv(0x9c68000, 0x0, 0x1)
        runtime/chan.go:583 +0x3f4 fp=0x9c4a79c sp=0x9c4a754 pc=0x804dc64
runtime.chanrecv1(0x9c68000, 0x0)
        runtime/chan.go:442 +0x1c fp=0x9c4a7b0 sp=0x9c4a79c pc=0x804d83c
runtime.gcenable()
        runtime/mgc.go:180 +0xd5 fp=0x9c4a7c4 sp=0x9c4a7b0 pc=0x805ed15
runtime.main()
        runtime/proc.go:209 +0x162 fp=0x9c4a7f0 sp=0x9c4a7c4 pc=0x8083272
runtime.goexit()
        runtime/asm_386.s:1326 +0x1 fp=0x9c4a7f4 sp=0x9c4a7f0 pc=0x80b5191

goroutine 2 [runnable]:
runtime.forcegchelper()
        runtime/proc.go:296 fp=0x9c4aff0 sp=0x9c4afec pc=0x8083520
runtime.goexit()
        runtime/asm_386.s:1326 +0x1 fp=0x9c4aff4 sp=0x9c4aff0 pc=0x80b5191
created by runtime.init.5
        runtime/proc.go:293 +0x23

goroutine 3 [runnable]:
runtime.gcenable.func1()
        runtime/mgc.go:178 fp=0x9c4b7f0 sp=0x9c4b7ec pc=0x805ed80
runtime.goexit()
        runtime/asm_386.s:1326 +0x1 fp=0x9c4b7f4 sp=0x9c4b7f0 pc=0x80b5191
created by runtime.gcenable
        runtime/mgc.go:178 +0x7c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x88483dc, 0x8cf60e0, 0xd, 0x14, 0x2)
        runtime/proc.go:381 +0x108 fp=0x9c4bfb8 sp=0x9c4bfa4 pc=0x80837c8
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.(*scavengerState).park(0x8cf60e0)
        runtime/mgcscavenge.go:400 +0x5f fp=0x9c4bfcc sp=0x9c4bfb8 pc=0x806a50f
runtime.bgscavenge(0x9c68000)
        runtime/mgcscavenge.go:628 +0x4b fp=0x9c4bfe8 sp=0x9c4bfcc pc=0x806ab8b
runtime.gcenable.func2()
        runtime/mgc.go:179 +0x27 fp=0x9c4bff0 sp=0x9c4bfe8 pc=0x805ed67
runtime.goexit()
        runtime/asm_386.s:1326 +0x1 fp=0x9c4bff4 sp=0x9c4bff0 pc=0x80b5191
created by runtime.gcenable
        runtime/mgc.go:179 +0xc1
futexwakeup addr=0x8d09b64 returned -38
fatal error: unexpected signal during runtime execution
panic during panic
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1006 pc=0x807cb32]

runtime stack:
runtime.throw({0x877aad8, 0x2a})
        runtime/panic.go:1047 +0x4d fp=0x9c5fd64 sp=0x9c5fd50 pc=0x808072d
runtime.sigpanic()
        runtime/signal_unix.go:825 +0x2b8 fp=0x9c5fd7c sp=0x9c5fd64 pc=0x8097ce8
runtime.futexwakeup(0x8d09b64, 0x1)
        runtime/os_linux.go:94 +0x82 fp=0x9c5fda8 sp=0x9c5fd7c pc=0x807cb32
runtime.unlock2(0x8d09b64)
        runtime/lock_futex.go:121 +0x50 fp=0x9c5fdb8 sp=0x9c5fda8 pc=0x8052700
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.dopanic_m(0x9c065a0, 0x808072d, 0x9c5fe20)
        runtime/panic.go:1276 +0x2a4 fp=0x9c5fde8 sp=0x9c5fdb8 pc=0x8081034
runtime.fatalthrow.func1()
        runtime/panic.go:1127 +0x62 fp=0x9c5fe08 sp=0x9c5fde8 pc=0x8080a92
runtime.fatalthrow(0x2)
        runtime/panic.go:1120 +0x71 fp=0x9c5fe20 sp=0x9c5fe08 pc=0x8080a21
runtime.throw({0x877aad8, 0x2a})
        runtime/panic.go:1047 +0x4d fp=0x9c5fe34 sp=0x9c5fe20 pc=0x808072d
runtime.sigpanic()
        runtime/signal_unix.go:825 +0x2b8 fp=0x9c5fe4c sp=0x9c5fe34 pc=0x8097ce8
runtime.futexwakeup(0x8d09af0, 0x1)
        runtime/os_linux.go:94 +0x82 fp=0x9c5fe78 sp=0x9c5fe4c pc=0x807cb32
runtime.unlock2(0x8d09af0)
        runtime/lock_futex.go:121 +0x50 fp=0x9c5fe88 sp=0x9c5fe78 pc=0x8052700
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.printunlock()
        runtime/print.go:79 +0x49 fp=0x9c5fe90 sp=0x9c5fe88 pc=0x8082539
runtime.futexwakeup.func1()
        runtime/os_linux.go:91 +0x7f fp=0x9c5fea4 sp=0x9c5fe90 pc=0x807cbbf
runtime.futexwakeup(0x8cf7658, 0x1)
        runtime/os_linux.go:90 +0x7d fp=0x9c5fed0 sp=0x9c5fea4 pc=0x807cb2d
runtime.unlock2(0x8cf7658)
        runtime/lock_futex.go:121 +0x50 fp=0x9c5fee0 sp=0x9c5fed0 pc=0x8052700
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.mcommoninit(0x9c80000, 0x4)
        runtime/proc.go:852 +0x1b3 fp=0x9c5ff10 sp=0x9c5fee0 pc=0x8084c53
runtime.allocm(0x9c3c600, 0x88483b8, 0x4)
        runtime/proc.go:1834 +0xe6 fp=0x9c5ff38 sp=0x9c5ff10 pc=0x80867d6
runtime.newm(0x88483b8, 0x9c3c600, 0x4)
        runtime/proc.go:2197 +0x56 fp=0x9c5ff54 sp=0x9c5ff38 pc=0x8087016
runtime.startm(0x9c3c600, 0x1, 0x0)
        runtime/proc.go:2423 +0x1cf fp=0x9c5ff80 sp=0x9c5ff54 pc=0x808779f
runtime.wakep()
        runtime/proc.go:2559 +0xca fp=0x9c5ffa0 sp=0x9c5ff80 pc=0x8087cda
runtime.resetspinning()
        runtime/proc.go:3262 +0x5b fp=0x9c5ffb0 sp=0x9c5ffa0 pc=0x8089b9b
runtime.schedule()
        runtime/proc.go:3384 +0xec fp=0x9c5ffcc sp=0x9c5ffb0 pc=0x8089f7c
runtime.mstart1()
        runtime/proc.go:1506 +0xad fp=0x9c5ffdc sp=0x9c5ffcc pc=0x8085f3d
runtime.mstart0()
        runtime/proc.go:1456 +0x5a fp=0x9c5ffec sp=0x9c5ffdc pc=0x8085e7a
runtime.mstart()
        runtime/asm_386.s:271 +0x5 fp=0x9c5fff0 sp=0x9c5ffec pc=0x80b3d45
futexwakeup addr=0x8d09b64 returned -38
fatal error: unexpected signal during runtime execution
stack trace unavailable
[root@server frp_0.51.3_linux_386]#

### frpc Version

frp_0.51.3_linux_386

### frps Version

frp_0.51.3_linux_386

### System Architecture

Linux server 2.6.9-78.ELsmp #1 SMP Wed Jul 9 15:39:47 EDT 2008 i686 i686 i386 GNU/Linux

### Configurations

Red Hat Enterprise Linux AS release 4 (Nahant Update 7)

### Logs

frpc  frpc_full.ini  frpc.ini  frps  frps_full.ini  frps.ini  LICENSE
[root@server frp_0.51.3_linux_386]# ./frpc -v
futexwakeup addr=0x8cf6fb0 returned -38
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1006 pc=0x807cb32]

runtime stack:
runtime.throw({0x877aad8, 0x2a})
        runtime/panic.go:1047 +0x4d fp=0xa859f40 sp=0xa859f2c pc=0x808072d
runtime.sigpanic()
        runtime/signal_unix.go:825 +0x2b8 fp=0xa859f58 sp=0xa859f40 pc=0x8097ce8
runtime.futexwakeup(0x8cf6fb0, 0x1)
        runtime/os_linux.go:94 +0x82 fp=0xa859f84 sp=0xa859f58 pc=0x807cb32
runtime.notewakeup(0x8cf6fb0)
        runtime/lock_futex.go:145 +0x4b fp=0xa859f98 sp=0xa859f84 pc=0x80527bb
runtime.startlockedm(0xa8060f0)
        runtime/proc.go:2606 +0x6a fp=0xa859fa8 sp=0xa859f98 pc=0x8087f6a
runtime.schedule()
        runtime/proc.go:3412 +0x7d fp=0xa859fc4 sp=0xa859fa8 pc=0x8089f0d
runtime.park_m(0xa806780)
        runtime/proc.go:3529 +0x157 fp=0xa859fd8 sp=0xa859fc4 pc=0x808a5f7
runtime.mcall()
        runtime/asm_386.s:325 +0x44 fp=0xa859fe0 sp=0xa859fd8 pc=0x80b3da4

goroutine 1 [chan receive, locked to thread]:
runtime.gopark(0x88482ec, 0xa868030, 0xe, 0x17, 0x2)
        runtime/proc.go:381 +0x108 fp=0xa84a754 sp=0xa84a740 pc=0x80837c8
runtime.chanrecv(0xa868000, 0x0, 0x1)
        runtime/chan.go:583 +0x3f4 fp=0xa84a79c sp=0xa84a754 pc=0x804dc64
runtime.chanrecv1(0xa868000, 0x0)
        runtime/chan.go:442 +0x1c fp=0xa84a7b0 sp=0xa84a79c pc=0x804d83c
runtime.gcenable()
        runtime/mgc.go:181 +0xe9 fp=0xa84a7c4 sp=0xa84a7b0 pc=0x805ed29
runtime.main()
        runtime/proc.go:209 +0x162 fp=0xa84a7f0 sp=0xa84a7c4 pc=0x8083272
runtime.goexit()
        runtime/asm_386.s:1326 +0x1 fp=0xa84a7f4 sp=0xa84a7f0 pc=0x80b5191

goroutine 2 [runnable]:
runtime.forcegchelper()
        runtime/proc.go:296 fp=0xa84aff0 sp=0xa84afec pc=0x8083520
runtime.goexit()
        runtime/asm_386.s:1326 +0x1 fp=0xa84aff4 sp=0xa84aff0 pc=0x80b5191
created by runtime.init.5
        runtime/proc.go:293 +0x23

goroutine 3 [runnable]:
runtime.gcenable.func1()
        runtime/mgc.go:178 fp=0xa84b7f0 sp=0xa84b7ec pc=0x805ed80
runtime.goexit()
        runtime/asm_386.s:1326 +0x1 fp=0xa84b7f4 sp=0xa84b7f0 pc=0x80b5191
created by runtime.gcenable
        runtime/mgc.go:178 +0x7c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x88483dc, 0x8cf60e0, 0xd, 0x14, 0x2)
        runtime/proc.go:381 +0x108 fp=0xa84bfb8 sp=0xa84bfa4 pc=0x80837c8
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.(*scavengerState).park(0x8cf60e0)
        runtime/mgcscavenge.go:400 +0x5f fp=0xa84bfcc sp=0xa84bfb8 pc=0x806a50f
runtime.bgscavenge(0xa868000)
        runtime/mgcscavenge.go:628 +0x4b fp=0xa84bfe8 sp=0xa84bfcc pc=0x806ab8b
runtime.gcenable.func2()
        runtime/mgc.go:179 +0x27 fp=0xa84bff0 sp=0xa84bfe8 pc=0x805ed67
runtime.goexit()
        runtime/asm_386.s:1326 +0x1 fp=0xa84bff4 sp=0xa84bff0 pc=0x80b5191
created by runtime.gcenable
        runtime/mgc.go:179 +0xc1

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
> 2.6.9-78

可能是**内核版本**过低
