### ISSUE TITLE
阿里云ECS服务器搭配弹性IP（EIP），客户端的serverAddr填写绑定的域名会导致链接失败，但是使用IP直连就可以

### ISSUE THREAD

**Issue by aircross** [fatedier/frp#4314]
### Bug Description

阿里云ECS服务器搭配弹性IP（EIP），客户端的serverAddr填写绑定的域名会导致链接失败，但是使用IP直连就可以
原因是通过绑定的域名访问国内的IP，大多数会先过一遍备案防火墙，没有备案的访问会被重定向到一个备案提示页面
所以，客户端是否可以针对使用域名的，先进行IP解析后再通过IP链接服务器？
`D:\Softs\frp\frp_0.58.1_windows_amd64>frpc.exe -c frpc.toml
[1;34m2024-07-02 14:09:15.714 [I] [sub/root.go:142] start frpc service for config file [frpc.toml]
[0m[1;34m2024-07-02 14:09:15.723 [I] [client/service.go:294] try to connect to server...
[0m[1;33m2024-07-02 14:09:15.855 [W] [client/service.go:297] connect to server error: read tcp 192.168.8.130:64011->123.123.123.123:7000: wsarecv: An existing connection was forcibly closed by the remote host.
[0m[1;34m2024-07-02 14:09:15.855 [I] [sub/root.go:160] frpc service for config file [frpc.toml] stopped
[0mlogin to the server failed: read tcp 192.168.8.130:64011->123.123.123.123:7000: wsarecv: An existing connection was forcibly closed by the remote host.. With loginFailExit enabled, no additional retries will be attempted`

### frpc Version

0.58.1

### frps Version

0.58.1

### System Architecture

Debain 12 amd64

### Configurations

`serverAddr = "frp.wifias.com"
serverPort = 7000
# auth token
auth.token = "token"

[[proxies]]
name = "M262_RDP"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3389
remotePort = 30022
# If true, traffic will be compressed
transport.useCompression = false
# frpc will connect local service's port to detect it's healthy status
healthCheck.type = "tcp"
# Health check connection timeout
healthCheck.timeoutSeconds = 3
# If continuous failed in 3 times, the proxy will be removed from frps
healthCheck.maxFailed = 3
# Every 10 seconds will do a health check
healthCheck.intervalSeconds = 10
`

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/issues/3778#issuecomment-1817034440
