### ISSUE TITLE
Data communication is unstable.

### ISSUE THREAD

**Issue by Monarsoft** [fatedier/frp#4317]
### Bug Description

frp_0.58.1_linux_amd64 had a disconnection problem, especially in RDP. I switched to frp_0.57.0_linux_amd64 and it didn't have this problem. Yes, RDP automatically reconnects when disconnected. 

### frpc Version

0.58.1

### frps Version

0.58.1

### System Architecture

linux/amd64

### Configurations

***frps.toml
bindAddr = "0.0.0.0"
quicBindPort = 5443
transport.tcpMux = true
transport.tls.force = true
auth.method = "token"

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by rensir** [comment]
i also have the problem
