### ISSUE TITLE
frps管理面板增加功能

### ISSUE THREAD

**Issue by haimian467** [fatedier/frp#4318]
### Describe the feature request

在Proxies分类中，是否可以添加Xtcp分类

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/issues/4285
