### ISSUE TITLE
代理配置文件里增加 “transport.useEncryption = true” 这条报错

### ISSUE THREAD

**Issue by dobelachaos** [fatedier/frp#4320]
### Bug Description

代理配置文件里增加 “transport.useEncryption = true” 这条报错，“ unmarshal ProxyConfig error: unmarshal ClientPluginOptions error: json: unknown field "transport" "    
访问配置里写这条没问题
是只要访问者配置了这条就可以吗？ 
我看官方的文档里代理配置是有这一条目的

使用的是最新版，配置文件格式是toml
而且我用老版的ini文件代理配置这条是没问题的

### frpc Version

0.58.1

### frps Version

0.58.1

### System Architecture

freeBSD

### Configurations

serv00

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
在 `[[proxies]]` 里
https://github.com/fatedier/frp/blob/c6f9d8d4031f6fba9a39fe9e1a79907ceedf0f5f/conf/frpc_full_example.toml#L151

**Comment by dobelachaos** [comment]
多谢 多谢 ，我一下子明白了  我写在了 [proxies.plugin] 里，不好意思 ，还是自己没仔细看文档
