### ISSUE TITLE
[Feature Request] 服务器可以主动断开某个客户端或者某个代理和服务器的链接吗

### ISSUE THREAD

**Issue by adminxy** [fatedier/frp#4322]
### Describe the feature request

服务器可以主动断开某个客户端或者某个代理和服务器的链接吗，frps有提供相应的方法或者api么，或者服务器插件可以实现吗？或者有其他办法可以实现这个功能吗，在不影响其他链接的情况下

我要实现的是

例如：frps启动后，1001，1002，1003端口都有客户端链接，我想在不影响1001，1002 正常的链接和使用的情况下，frps主动断开1003的链接

frps有相关接口或者方法可以，让外部程序控制frps断开指定端口的链接吗

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://gofrp.org/zh-cn/docs/features/common/server-plugin/#ping

**Comment by adminxy** [comment]
> https://gofrp.org/zh-cn/docs/features/common/server-plugin/#ping

可以麻烦您详细说下吗，这个不是客户端的心跳么，我不太理解，我要实现的是，比如frps启动后，1001，1002，1003端口都有客户端链接，我想在不影响1001，1002 正常的链接和使用的情况下，服务器主动断开1003的链接

**Comment by Developer024** [comment]
#4326 可以看下这个issue提供的思路

**Comment by adminxy** [comment]
> #4326 可以看下这个issue提供的思路

感谢，我看下

**Comment by wuai1024** [comment]
> #4326 可以看下这个issue提供的思路

这个跟 流量速率限制一样，都是需要修改客户端，用处感觉不大。还是需要`frps`服务端上支持这样的功能才比较方便。
