### ISSUE TITLE
plugin_socks5  不可用

### ISSUE THREAD

**Issue by simlelcf** [fatedier/frp#4327]
### Bug Description

plugin_socks5  不可用

### frpc Version

59.0

### frps Version

59.0

### System Architecture

linux/amd64, windows/amd64

### Configurations

客户端
serverPort = 7000
auth.method = "token"
auth.token = "12345678"
[[proxies]]
name = "plugin_socks5"
type = "tcp"
remotePort = 6028
transport.useEncryption = true
transport.useCompression = true
[proxies.plugin]
type = "socks5"

服务端
BindPort = 7000
auth.method = "token"
auth.token = "12345678"

### Logs

客户端
![image](https://github.com/fatedier/frp/assets/18651522/12b595b5-b2a3-43da-b775-3af1521e78e4)

服务器
![image](https://github.com/fatedier/frp/assets/18651522/ad77c52b-5d09-4d39-a135-f9d996284c95)

运行日志
![image](https://github.com/fatedier/frp/assets/18651522/a70939a7-933b-43b0-bc87-66331c290b49)

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
frpc 与 frps 之间，连接问题
