### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Li-Ziheng** [fatedier/frp#4328]
### Describe the feature request

StaticFile的type支持udp吗

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
不支持
