### ISSUE TITLE
win7系统启动客户端

### ISSUE THREAD

**Issue by Crazy-zxd** [fatedier/frp#4330]
### Bug Description

![image](https://github.com/fatedier/frp/assets/29646232/c5eaae9b-1e7b-4ad8-846e-81c49fd51c50)

### frpc Version

0.58

### frps Version

0.58

### System Architecture

windows/amd64

### Configurations

![image](https://github.com/fatedier/frp/assets/29646232/30534385-fad4-4a4b-b6f8-b615ab6c0980)

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Not supported, please update the system.
