### ISSUE TITLE
无法连接到 frps-panel 插件面板

### ISSUE THREAD

**Issue by xhzkp** [fatedier/frp#4332]
### Bug Description

我想使用下面链接的服务端面板, 但总是报错, 为了更清楚的表述问题, 我录制了GIF演示, 请求路过的大佬支招
https://github.com/yhl452493373/frps-panel

请单击图片右上角的按钮, 在新标签页中打开并观看
![AA](https://github.com/fatedier/frp/assets/145243997/99baeb02-33c4-487a-aad9-e79576debb4b)

### frpc Version

0.59

### frps Version

0.59

### System Architecture

windows/amd64

### Configurations
```
_______________________________________________________________frps-panel.toml
[common]
# frps panel config info
plugin_addr = "127.0.0.1"
plugin_port = 7200
#admin_user = "admin"
#admin_pwd = "admin"
# specified login state keep time
admin_keep_time = 0

# enable tls
tls_mode = false
#tls_cert_file = "cert.crt"
#tls_key_file = "cert.key"

# frp dashboard info
dashboard_addr = "127.0.0.1"
dashboard_port = 7500
dashboard_user = "admin"
dashboard_pwd = "admin"
_______________________________________________________________frps.toml
bindPort = 7000

[[httpPlugins]]
name = "frps-panel"
addr = "127.0.0.1:7200"
path = "/handler"
ops = ["Login","NewWorkConn","NewUserConn","NewProxy","Ping"]

```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by subei12** [comment]
frps 要开启 Dashboard 吧，在 `frps.toml` 加一下配置试试看。

```
# 默认为 127.0.0.1，如果需要公网访问，需要修改为 0.0.0.0。
webServer.addr = "0.0.0.0"
webServer.port = 7500
# dashboard 用户名密码，可选，默认为空
webServer.user = "admin"
webServer.password = "admin"
```

**Comment by xhzkp** [comment]
> frps 要开启 Dashboard 吧，在 `frps.toml` 加一下配置试试看。
> 
> ```
> # 默认为 127.0.0.1，如果需要公网访问，需要修改为 0.0.0.0。
> webServer.addr = "0.0.0.0"
> webServer.port = 7500
> # dashboard 用户名密码，可选，默认为空
> webServer.user = "admin"
> webServer.password = "admin"
> ```

感谢, 
我这不是用的内置的面板, 是用的插件, 是按下面的帮助文档配置的
https://github.com/yhl452493373/frps-panel/blob/main/README_zh.md

**Comment by subei12** [comment]
> > frps 要打开 Dashboard 吧，在`frps.toml`加一下配置试试看。
> > ```
> > # 默认为 127.0.0.1，如果需要公网访问，需要修改为 0.0.0.0。
> > webServer.addr = "0.0.0.0"
> > webServer.port = 7500
> > # dashboard 用户名密码，可选，默认为空
> > webServer.user = "admin"
> > webServer.password = "admin"
> > ```
> 
> 谢谢, 我这不是用的内置面板,是用的frps-panel面板插件,是按下面的帮助文档配置的 https://github.com/yhl452493373/frps-panel/blob/main/README_zh.md


你的`frps-panel.toml` 面板配置上有一段
```
# frp dashboard info
dashboard_addr = "127.0.0.1"
dashboard_port = 7500
dashboard_user = "admin"
dashboard_pwd = "admin"
```
从注释上看，这里填写的是`frp dashboard `的配置信息，你的报错也是这个信息里的端口，
所以我猜测你需要开启`frp dashboard `你的`frps-panel`面板才可以获取到服务器信息

**Comment by xhzkp** [comment]
> > > frps 要打开 Dashboard 吧，在`frps.toml`加一下配置试试看。
> > > ```
> > > # 默认为 127.0.0.1，如果需要公网访问，需要修改为 0.0.0.0。
> > > webServer.addr = "0.0.0.0"
> > > webServer.port = 7500
> > > # dashboard 用户名密码，可选，默认为空
> > > webServer.user = "admin"
> > > webServer.password = "admin"
> > > ```
> > 
> > 
> > 谢谢, 我这不是用的内置面板,是用的frps-panel面板插件,是按下面的帮助文档配置的 https://github.com/yhl452493373/frps-panel/blob/main/README_zh.md
> 
> 你的`frps-panel.toml` 面板配置上有一段
> 
> ```
> # frp dashboard info
> dashboard_addr = "127.0.0.1"
> dashboard_port = 7500
> dashboard_user = "admin"
> dashboard_pwd = "admin"
> ```
> 
> 从注释上看，这里填写的是`frp dashboard `的配置信息，你的报错也是这个信息里的端口， 所以我猜测你需要开启`frp dashboard `你的`frps-panel`面板才可以获取到服务器信息

奇怪了, 刚才加了你提到的那几行配置, 测试不行, 然后我又改回去, 结果, 现在哪个面板也进不去了, 
不知道是不是那个项目不适配最新的0.59?

**Comment by xhzkp** [comment]
清了一下浏览器的缓存, 现在能进插件的面板了, 但是还是报原来的错误, 估计可能还是哪里有问题

**Comment by subei12** [comment]
开无痕直接访问 http://127.0.0.1:7500 输入账号密码试试吧

我整体测试下来是正常的
![image](https://github.com/fatedier/frp/assets/45759726/b9139678-aaca-4b15-a8c2-87f97a706fbd)


```
_______________________________________________________________frps-panel.toml
# basic options
[common]
# frps panel config info
plugin_addr = "127.0.0.1"
plugin_port = 7200
#admin_user = "admin"
#admin_pwd = "admin"
# specified login state keep time
admin_keep_time = 0

# enable tls
tls_mode = false
#tls_cert_file = "cert.crt"
#tls_key_file = "cert.key"

# frp dashboard info
dashboard_addr = "127.0.0.1"
dashboard_port = 7500
dashboard_user = "admin"
dashboard_pwd = "admin"


_______________________________________________________________frps.toml
bindPort = 7000

# 默认为 127.0.0.1，如果需要公网访问，需要修改为 0.0.0.0。
webServer.addr = "0.0.0.0"
webServer.port = 7500
# dashboard 用户名密码，可选，默认为空
webServer.user = "admin"
webServer.password = "admin"
enablePrometheus = true


[[httpPlugins]]
name = "frps-panel"
addr = "127.0.0.1:7200"
path = "/handler"
ops = ["Login","NewWorkConn","NewUserConn","NewProxy","Ping"]
```

**Comment by xhzkp** [comment]
> # 默认为 127.0.0.1，如果需要公网访问，需要修改为 0.0.0.0。
> webServer.addr = "0.0.0.0"
> webServer.port = 7500
> # dashboard 用户名密码，可选，默认为空
> webServer.user = "admin"
> webServer.password = "admin"
> enablePrometheus = true

非常感谢, 现在7500和7200都能进了, 但是7500是内置的面板, 7200才是插件的面板, 难道官方文档的配置丢了那几行了吗?

**Comment by xhzkp** [comment]
> 开无痕直接访问 http://127.0.0.1:7500 输入账号密码试试吧
> 
> 我整体测试下来是正常的 ![image](https://private-user-images.githubusercontent.com/45759726/347813781-b9139678-aaca-4b15-a8c2-87f97a706fbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDI5NDMsIm5iZiI6MTcyMDg0MjY0MywicGF0aCI6Ii80NTc1OTcyNi8zNDc4MTM3ODEtYjkxMzk2NzgtYWFjYS00YjE1LWE4YzItODdmOTdhNzA2ZmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAzNTA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhOWJjYWNkMTllYjY2YmM5MDVjMTA3YTRkMDY1MjgxYWZlM2E4MGNlMWRhNWE2NzYwMGRhODFlZGE2Yjg5NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T1QBQPA1GJfcNzFN11Y2frIgmxEl-bdMAVvcxmJbfl4)
> 
> ```
> _______________________________________________________________frps-panel.toml
> # basic options
> [common]
> # frps panel config info
> plugin_addr = "127.0.0.1"
> plugin_port = 7200
> #admin_user = "admin"
> #admin_pwd = "admin"
> # specified login state keep time
> admin_keep_time = 0
> 
> # enable tls
> tls_mode = false
> #tls_cert_file = "cert.crt"
> #tls_key_file = "cert.key"
> 
> # frp dashboard info
> dashboard_addr = "127.0.0.1"
> dashboard_port = 7500
> dashboard_user = "admin"
> dashboard_pwd = "admin"
> 
> 
> _______________________________________________________________frps.toml
> bindPort = 7000
> 
> # 默认为 127.0.0.1，如果需要公网访问，需要修改为 0.0.0.0。
> webServer.addr = "0.0.0.0"
> webServer.port = 7500
> # dashboard 用户名密码，可选，默认为空
> webServer.user = "admin"
> webServer.password = "admin"
> enablePrometheus = true
> 
> 
> [[httpPlugins]]
> name = "frps-panel"
> addr = "127.0.0.1:7200"
> path = "/handler"
> ops = ["Login","NewWorkConn","NewUserConn","NewProxy","Ping"]
> ```

大佬发现一个问题, 客户端, 莫名其妙就不连不上服务器了, 一直下面的提示, 然后看服务端的面板里面, 用户并没有被禁用, TCP列表里面为空, 我只能新找一个端口,再新建用一个,  哎, 真是不稳定

C:\Users\Administrator\Desktop\FRP\Frp059>frpc -c frpc.toml
[1;34m2024-07-13 11:47:14.661 [I] [sub/root.go:142] start frpc service for config file [frpc.toml]
[0m[1;34m2024-07-13 11:47:14.679 [I] [client/service.go:294] try to connect to server...
[0m[1;34m2024-07-13 11:47:14.738 [I] [client/service.go:286] [3eb0e1eaa3d7a1cb] login to server success, get run id [3eb0e1eaa3d7a1cb]
[0m[1;34m2024-07-13 11:47:14.739 [I] [proxy/proxy_manager.go:173] [3eb0e1eaa3d7a1cb] proxy added: [frp001.Port 4455 Server]
[0m[1;33m2024-07-13 11:47:14.758 [W] [client/control.go:166] [3eb0e1eaa3d7a1cb] [frp001.Port 4455 Server] start error: user [frp001] port [6000] is not allowed
[0m[1;33m2024-07-13 11:47:44.835 [W] [client/control.go:166] [3eb0e1eaa3d7a1cb] [frp001.Port 4455 Server] start error: user [frp001] port [6000] is not allowed
[0m[1;33m2024-07-13 11:48:14.882 [W] [client/control.go:166] [3eb0e1eaa3d7a1cb] [frp001.Port 4455 Server] start error: user [frp001] port [6000] is not allowed
[0m[1;33m2024-07-13 11:48:44.965 [W] [client/control.go:166] [3eb0e1eaa3d7a1cb] [frp001.Port 4455 Server] start error: user [frp001] port [6000] is not allowed
[0m[1;33m2024-07-13 11:49:15.034 [W] [client/control.go:166] [3eb0e1eaa3d7a1cb] [frp001.Port 4455 Server] start error: user [frp001] port [6000] is not allowed
[0m[1;33m2024-07-13 11:49:45.122 [W] [client/control.go:166] [3eb0e1eaa3d7a1cb] [frp001.Port 4455 Server] start error: user [frp001] port [6000] is not allowed
[0m[1;33m2024-07-13 11:50:15.189 [W] [client/control.go:166] [3eb0e1eaa3d7a1cb] [frp001.Port 4455 Server] start error: user [frp001] port [6000] is not allowed

**Comment by fatedier** [comment]
请去对应的项目里咨询。

**Comment by xhzkp** [comment]
> 请去对应的项目里咨询。

那个项目已经封存了,

**Comment by raydoom** [comment]
> > 开无痕直接访问 http://127.0.0.1:7500 输入账号密码试试吧
> > 我整体测试下来是正常的 ![image](https://private-user-images.githubusercontent.com/45759726/347813781-b9139678-aaca-4b15-a8c2-87f97a706fbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDI5NDMsIm5iZiI6MTcyMDg0MjY0MywicGF0aCI6Ii80NTc1OTcyNi8zNDc4MTM3ODEtYjkxMzk2NzgtYWFjYS00YjE1LWE4YzItODdmOTdhNzA2ZmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAzNTA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhOWJjYWNkMTllYjY2YmM5MDVjMTA3YTRkMDY1MjgxYWZlM2E4MGNlMWRhNWE2NzYwMGRhODFlZGE2Yjg5NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T1QBQPA1GJfcNzFN11Y2frIgmxEl-bdMAVvcxmJbfl4)
> > ```
> > _______________________________________________________________frps-panel.toml
> > # basic options
> > [common]
> > # frps panel config info
> > plugin_addr = "127.0.0.1"
> > plugin_port = 7200
> > #admin_user = "admin"
> > #admin_pwd = "admin"
> > # specified login state keep time
> > admin_keep_time = 0
> > 
> > # enable tls
> > tls_mode = false
> > #tls_cert_file = "cert.crt"
> > #tls_key_file = "cert.key"
> > 
> > # frp dashboard info
> > dashboard_addr = "127.0.0.1"
> > dashboard_port = 7500
> > dashboard_user = "admin"
> > dashboard_pwd = "admin"
> > 
> > 
> > _______________________________________________________________frps.toml
> > bindPort = 7000
> > 
> > # 默认为 127.0.0.1，如果需要公网访问，需要修改为 0.0.0.0。
> > webServer.addr = "0.0.0.0"
> > webServer.port = 7500
> > # dashboard 用户名密码，可选，默认为空
> > webServer.user = "admin"
> > webServer.password = "admin"
> > enablePrometheus = true
> > 
> > 
> > [[httpPlugins]]
> > name = "frps-panel"
> > addr = "127.0.0.1:7200"
> > path = "/handler"
> > ops = ["Login","NewWorkConn","NewUserConn","NewProxy","Ping"]
> > ```
> 
> 大佬发现一个问题, 客户端, 莫名其妙就不连不上服务器了, 一直下面的提示, 然后看服务端的面板里面, 用户并没有被禁用, TCP列表里面为空, 我只能再新找一个端口,再新建一个用户, 哎, 真是不稳定
> 
> C:\Users\Administrator\Desktop\FRP\Frp059>frpc -c frpc.toml �[1;34m2024-07-13 11:47:14.661 [I] [sub/root.go:142] start frpc service for config file [frpc.toml] �[0m�[1;34m2024-07-13 11:47:14.679 [I] [client/service.go:294] try to connect to server... �[0m�[1;34m2024-07-13 11:47:14.738 [I] [client/service.go:286] [3eb0e1eaa3d7a1cb] login to server success, get run id [3eb0e1eaa3d7a1cb] �[0m�[1;34m2024-07-13 11:47:14.739 [I] [proxy/proxy_manager.go:173] [3eb0e1eaa3d7a1cb] proxy added: [frp001.Port 4455 Server] �[0m�[1;33m2024-07-13 11:47:14.758 [W] [client/control.go:166] [3eb0e1eaa3d7a1cb] [frp001.Port 4455 Server] start error: user [frp001] port [6000] is not allowed �[0m�[1;33m2024-07-13 11:47:44.835 [W] [client/control.go:166] [3eb0e1eaa3d7a1cb] [frp001.Port 4455 Server] start error: user [frp001] port [6000] is not allowed �[0m�[1;33m2024-07-13 11:48:14.882 [W] [client/control.go:166] [3eb0e1eaa3d7a1cb] [frp001.Port 4455 Server] start error: user [frp001] port [6000] is not allowed �[0m�[1;33m2024-07-13 11:48:44.965 [W] [client/control.go:166] [3eb0e1eaa3d7a1cb] [frp001.Port 4455 Server] start error: user [frp001] port [6000] is not allowed �[0m�[1;33m2024-07-13 11:49:15.034 [W] [client/control.go:166] [3eb0e1eaa3d7a1cb] [frp001.Port 4455 Server] start error: user [frp001] port [6000] is not allowed �[0m�[1;33m2024-07-13 11:49:45.122 [W] [client/control.go:166] [3eb0e1eaa3d7a1cb] [frp001.Port 4455 Server] start error: user [frp001] port [6000] is not allowed �[0m�[1;33m2024-07-13 11:50:15.189 [W] [client/control.go:166] [3eb0e1eaa3d7a1cb] [frp001.Port 4455 Server] start error: user [frp001] port [6000] is not allowed

user [frp001] port [6000] is not allowed
这么明显的错误提示都要发个issue吗，先去看看使用说明README，不要张口就说人家的项目不稳定，先排除自己的使用问题
