### ISSUE TITLE
Please note that the lastest version of FRP is reported as malicious by Google Chrome and Windows Defender.

### ISSUE THREAD

**Issue by Maxwellads** [fatedier/frp#4333]
### Bug Description

All packages themselves and binaries are reported as malicious of different types.
![image](https://github.com/fatedier/frp/assets/95039679/47b46028-f6ac-4efa-90b0-d3cf9b33e7e8)

### frpc Version

0.59

### frps Version

0.59

### System Architecture

windows/amd64

### Configurations

N/A

### Steps to reproduce

1. 
2. 
3. 
..

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
#2095
