### ISSUE TITLE
怎么配置 Websocket 转发    ws://    地址数据转发！

### ISSUE THREAD

**Issue by Alanapi** [fatedier/frp#434]
我现在在 http tcp ssh 配置都能正常转发，但是我现在遇到一个问题，就是在 websocket 的情况下不能正常转发，url 如下：

   ws://ss.xxx.com

现在，客服端和服务端有没有具体到设置  ws://    转发开头的配置？

**Comment by zhfish** [comment]
域名解析成ip，需要nginx过一道吧。。。你要是直接ws://0.0.0.0 肯定没问题啊

**Comment by umena337** [comment]
??域名解析成ip，需要nginx过一道吧。。。你要是直接ws://0.0.0.0 肯定没问题啊
