### ISSUE TITLE
[Feature Request] Live Reload

### ISSUE THREAD

**Issue by SevensRequiem** [fatedier/frp#4340]
### Describe the feature request

I run UDP/TCP apps behind FRP, and I often have to reload the entire FRPC when adding new clients, as such any connections to the server get reset, it would be beneficial if I could just save the config and have frpc detect and add the added proxies, or remove if removed. 

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp?tab=readme-ov-file#hot-reloading-frpc-configuration

**Comment by SevensRequiem** [comment]
> https://github.com/fatedier/frp?tab=readme-ov-file#hot-reloading-frpc-configuration

I tried that, it just returns 
```
Jul 15 16:06:08 amp1 frpc[128019]: Get "http://127.0.0.1:7400/api/reload?strictConfig=true": dial tcp 127.0.0.1:7400: connect: connection refused
Jul 15 16:06:08 amp1 systemd[1]: frpc.service: Main process exited, code=exited, status=1/FAILURE
Jul 15 16:06:08 amp1 systemd[1]: frpc.service: Failed with result 'exit-code'.
Jul 15 16:06:14 amp1 systemd[1]: frpc.service: Scheduled restart job, restart counter is at 99.
Jul 15 16:06:14 amp1 systemd[1]: Stopped frpc.service - frp client.

```

**Comment by xqzr** [comment]
> > https://github.com/fatedier/frp?tab=readme-ov-file#hot-reloading-frpc-configuration
> 
> I tried that, it just returns
> 
> ```
> Jul 15 16:06:08 amp1 frpc[128019]: Get "http://127.0.0.1:7400/api/reload?strictConfig=true": dial tcp 127.0.0.1:7400: connect: connection refused
> Jul 15 16:06:08 amp1 systemd[1]: frpc.service: Main process exited, code=exited, status=1/FAILURE
> Jul 15 16:06:08 amp1 systemd[1]: frpc.service: Failed with result 'exit-code'.
> Jul 15 16:06:14 amp1 systemd[1]: frpc.service: Scheduled restart job, restart counter is at 99.
> Jul 15 16:06:14 amp1 systemd[1]: Stopped frpc.service - frp client.
> ```

https://github.com/fatedier/frp/blob/b4d5d8c756bfa7c5f4fc73c3dff48678d0110fce/conf/frpc_full_example.toml#L53-L55

**Comment by SevensRequiem** [comment]
```
serverAddr = "x.x.x.x"
serverPort = 7000
transport.protocol = "quic"
auth.method = "token"
auth.token = "xxxx"
transport.dialServerKeepalive = 7200
transport.heartbeatInterval = 30
transport.heartbeatTimeout = 90
webServer.addr = "127.0.0.1"
webServer.port = 7400
```

Is my current config
