### ISSUE TITLE
[Feature Request] I found that when the type is UDP, the default is UDP6

### ISSUE THREAD

**Issue by VV46678** [fatedier/frp#4342]
### Describe the feature request

Is this a problem with my system, or is it the default?
I want UDP to use IPv4 address,but i dont know how to do...

### Describe alternatives you've considered

You can add two types of UDP to fix it: UDP 6 and UDP

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Go should support dual stack by default without additional configuration.
