### ISSUE TITLE
[Feature Request] Support UDP in socks5 proxy plugin

### ISSUE THREAD

**Issue by Balder1840** [fatedier/frp#4343]
### Describe the feature request

I'm trying to use frp's socks5 proxy and tun2socks to proxy the internet access in my local network, i.e., computer A has internet but computer B do not, and only A can access B, B can't access A.
Everything looks fine except the DNS resolving. DNS resolving using UDP by default.
I finally got it work with [`nps`](https://github.com/ehang-io/nps), but which is not updated for long time.

I find currently the socks5 plugin is built on top of [`armon/go-socks5`](https://github.com/armon/go-socks5), but which is not support `UDP ASSOCIATE` command introduced in socks5.
Is there any plans to support `UDP` in frp, or do we have any workarounds?
Thanks.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
We currently have no plans to improve the socks5 proxy, it is only provided as a plugin to offer some basic capabilities. It is recommended to use it in conjunction with professional tools unless the changes are very minor and do not have any side effects.

**Comment by Balder1840** [comment]
> We currently have no plans to improve the socks5 proxy, it is only provided as a plugin to offer some basic capabilities. It is recommended to use it in conjunction with professional tools unless the changes are very minor and do not have any side effects.

Thanks for the explanation.
I'm try to develop a new proxy to handle it as I find it's hard for me to archive it base on current implementation of the socks5 plugin.
Do you accept it if I finish it and create a PR?

**Comment by fatedier** [comment]
I'm not sure what you mean by "new proxy"?

As mentioned in the comment above, for the plugin system, we don't aim to continuously iterate and meet all user needs, but rather to provide a basic version that covers most requirements.

However, if there is a widely used library and it doesn't add too much complexity, we may consider supporting some widely requested features.

**Comment by Balder1840** [comment]
A new proxy maybe named socks5 like what we have now under `\server\proxy\`.
I don't want to introduce complexity to the existing `tcp` proxy.
I will be happy if you can accept it and if not, I will keep it for my own.
But anyway, I understand your concern.
Thank you very for building so great a tool!

**Comment by fatedier** [comment]
That shouldn't be part of the project; our goal is not to include all the features in this project.

We are unlikely to have enough energy to maintain it continuously.

**Comment by Balder1840** [comment]
Sure, thanks.
I will close it.
