### ISSUE TITLE
如何设置配置证书http自动定向https获取真实IP。

### ISSUE THREAD

**Issue by YZX56** [fatedier/frp#4345]
### Describe the feature request

如何设置配置证书http自动定向https获取真实IP。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://gofrp.org/zh-cn/docs/features/common/realip/
