### ISSUE TITLE
[Feature Request] 最大支持客户端连接数是多少

### ISSUE THREAD

**Issue by thqiang** [fatedier/frp#4346]
### Describe the feature request

想请问下客户端连接数的上限是否取决于TCP端口数量65535？
如果有上限的话，除了配置tcpmux外，是否有其他方法突破这个上线

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
源地址、源端口、目标地址、目标端口
以上**任意**一项不同，都是不同的连接

**Comment by thqiang** [comment]
> 源地址、源端口、目标地址、目标端口
> 以上**任意**一项不同，都是不同的连接

目前登录frp客户端是使用ssh -p xxxx user@<server ip address>这样。四元祖不同，可以建立多于65535个连接，但是在登录客户端的时候如何区分
