### ISSUE TITLE
[Feature Request] 希望能在 dashboard 中显示客户端的连接ip

### ISSUE THREAD

**Issue by raydoom** [fatedier/frp#4347]
### Describe the feature request

希望能在 dashboard 中显示客户端的连接ip
从frps的日志中可以看到，每个客户端连接上来之后，会有一个 id，例如下面日志中的 [b2e6f870e2cf91da] , 后面创建的端口代理 test-tcp 对用的端口号 17541 都会和这个 id 有关联，说明可以拿到每个Proxy的来源ip，udp应该是类似的，希望能把这个ip显示在dashboard界面，作为一列
```
[0m[1;34m2024-07-20 01:58:09.908 [I] [server/service.go:575] [b2e6f870e2cf91da] client login info: ip [36.142.xxx.xxx:12242] version [0.59.0] hostname [] os [linux] arch [amd64]
[0m[1;34m2024-07-20 01:58:09.957 [I] [proxy/tcp.go:82] [b2e6f870e2cf91da] [test-tcp] tcp proxy listen port [17541]
[0m[1;34m2024-07-20 01:58:09.957 [I] [server/control.go:401] [b2e6f870e2cf91da] new proxy [test-tcp] type [tcp] success
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by wuai1024** [comment]
这个不错

**Comment by fatedier** [comment]
Duplicate of https://github.com/fatedier/frp/issues/3991
