### ISSUE TITLE
[Feature Request] 增加 frpc 重连次数限制

### ISSUE THREAD

**Issue by jiaobuzuji** [fatedier/frp#4348]
## 需求与原因
- frps 的公网 IP 地址会因为某些原因（例如断电重启）而改变（小范围、有规律变化）
- frpc 需要实现**无人职守**
- frpc 在首次连接到 **ServerAddr** 之后，如果此时 frps 断电重启导致  **ServerAddr** 变化了，则由于 frpc 的重连机制而无法退出 #1136 

## Feature
- frpc 的 toml 配置中增加 *最大重连次数*
-  *最大重连次数* 值为 0 （default ）时，则无限次数
- 当重连次数达到 *最大重连次数* 时，则 Error 退出
- 这样我就可以在外部使用 ShellScript 对 toml 的 **ServerAddr** 进行**自动**修改并重启 frpc。从而达到**无人职守**的目的

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
不会考虑这样的功能，设计上就是客户端和服务端始终保持可用。

如果有额外的需要，建议自己通过探测的方式实现相关的检测 -> action 能力。

**Comment by mvscode** [comment]
因为機器改變了ip，你可以用域名來綁定ip更適合，frpc 連接你設定的域名，域名映射frps 服務的ip，即使ip改變你也可以通過域名連接到正確的機器ip
