### ISSUE TITLE
转发后在其他机访问 服务器地址:frpc配置的远程端口 显示它已永久性地移动到了新网址

### ISSUE THREAD

**Issue by KingStarPlus** [fatedier/frp#4349]
### Bug Description

1. 云服务器防火墙放行了，只有服务器上的浏览器能正常访问到转发的服务
2. 配置了token,frpc没有配置token也能直接连接frps

### frpc Version

0.59.0

### frps Version

0.59.0

### System Architecture

windows/amd64

### Configurations

serverAddr = "xxx.xxx.xxx.xxx"
serverPort = 7000

[[proxies]]
name = "测试"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8282
remotePort = 6000

bindPort = 7000
auth.method = "token"
auth.token = "asdasdsa"

![微信图片_20240725101215](https://github.com/user-attachments/assets/09cc56b6-bf3d-45f1-bdc4-5d7a13f5b4e4)

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
Chrome 不允许这个端口

**Comment by YummyNovaSoup** [comment]
> Chrome 不允许这个端口

同样的问题……我试着把端口remote端口改为了80，现在网页错误变成了：“当前无法使用此页面 当前无法处理此请求。”
但是我用curl是能看到html源码的，并且状态码什么也都正常，就是好像浏览器不能正确识别显示？这是为什么呢？

**Comment by YummyNovaSoup** [comment]
> > Chrome 不允许这个端口
> 
> 同样的问题……我试着把端口remote端口改为了80，现在网页错误变成了：“当前无法使用此页面 当前无法处理此请求。” 但是我用curl是能看到html源码的，并且状态码什么也都正常，就是好像浏览器不能正确识别显示？这是为什么呢？

哦是我搞错了，我改的是local端口，正确地更改remote端口是没有问题的。已解决，谢谢！
