### ISSUE TITLE
服务端执行成功，但是却连接不了，没有防火墙 

### ISSUE THREAD

**Issue by qxwo** [fatedier/frp#435]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.13.0

**What operating system and processor architecture are you using (`go env`)?**
centos7 64

**Configures you used:**
frps
bind_addr = 0.0.0.0
bind_port = 7000
frpc
server_addr = 192.168.10.10
server_port = 7000

**Steps to reproduce the issue:**
1.D:\frp_0.13.0_windows_amd64>frpc.exe -c frpc.ini
2.
3.

**Describe the results you received:**

2017/08/15 15:56:18 [W] [control.go:121] login to server failed: di
8.10.10:7000: connectex: A connection attempt failed because the co
did not properly respond after a period of time, or established co
ed because connected host has failed to respond.
dial tcp 192.168.10.10:7000: connectex: A connection attempt failed
connected party did not properly respond after a period of time, or
connection failed because connected host has failed to respond.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

[root@localhost fpr]# netstat -tuln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp6       0      0 :::7500                 :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::8888                 :::*                    LISTEN     
tcp6       0      0 :::7000                 :::*                    LISTEN     
tcp6       0      0 :::8443                 :::*                    LISTEN     
tcp6       0      0 :::1088                 :::*                    LISTEN     
udp        0      0 0.0.0.0:45502           0.0.0.0:*                          
udp6       0      0 :::1088                 :::*                               
udp6       0      0 :::7000                 :::*                  

**Can you point out what caused this issue (optional)**
ipv6没关闭?

**Comment by fatedier** [comment]
1. 你确认这是一个 bug？
2. 你有尝试过各种验证方法排查问题，排除网络和环境因素？
3. 最后遇到问题能给出问题的具体原因分析？

issue 是用来记录有意义的 bug 反馈和 feature request。如果每一个人都是遇到问题，首先不想办法排查定位分析问题，而是直接将问题抛给别人，但凡配置写错，网络有问题都要开个 issue 问一遍，耗费的是别人的时间。

最近看到大部分的 issue 对项目优化和功能更新毫无帮助，几乎没有认真分析问题，给出修改意见的。我也没有精力去帮助每一个人排查各种环境问题。

**Comment by qxwo** [comment]
你确认这是一个 bug？
我不确认这是bug
你有尝试过各种验证方法排查问题，排除网络和环境因素？
我用了2台vps测试，一台公网一台内网，多个配置文件均提示这个错误（同样系统）
最后遇到问题能给出问题的具体原因分析？
原因 我也不清楚，因为软件给我的错误提示有限，仅提示连接失败，且服务端没有任何错误提示
我只是来反馈情况，没有要求你解决，如果觉得这不是问题，大可以关闭这个issue 。

**Comment by stanle1** [comment]
我也遇到这个问题了。。 我是第一二次登录正常，然后就不能登录了。。我怀疑服务商处理了点问题

**Comment by HeartZhang** [comment]
这作者也是没谁了...  各种关闭问题. 不按他要求他关, 按他要求不想解决也关.   这bind_addr = 0.0.0.0
bind_port = 7000 之后启动会绑定到tcp6. 到底是程序问题还是个人配置问题?

**Comment by Lehmaning** [comment]
> 这作者也是没谁了... 各种关闭问题. 不按他要求他关, 按他要求不想解决也关. 这bind_addr = 0.0.0.0 bind_port = 7000 之后启动会绑定到tcp6. 到底是程序问题还是个人配置问题?

是的，搞了半天发现 0.0.0.0 会绑定到 tcp6。。

**Comment by fatedier** [comment]
> > 这作者也是没谁了... 各种关闭问题. 不按他要求他关, 按他要求不想解决也关. 这bind_addr = 0.0.0.0 bind_port = 7000 之后启动会绑定到tcp6. 到底是程序问题还是个人配置问题?
> 
> 是的，搞了半天发现 0.0.0.0 会绑定到 tcp6。。

@Lehmaning 是的，这提问者也是没谁了，各种网上随便搜到的答案也要提问，自己不去排查不去定位非要衣来张口饭来伸手。到底是人性的扭曲还是道德的沦丧？

如果您每天要在繁重的工作之余，帮每一个不知道自己动手搜索的用户去 google，去百度，然后像保姆一样把答案喂到嘴边，不知道您能不能在没有任何报酬的情况下持续坚持几年？

http://www.chengweiyang.cn/2017/03/05/why-netstat-not-showup-tcp4-socket/

> 所以，netstat 只是很真实的显示监听的端口而已，但是需要注意 ipv6 实际上在 Linux 上也支持 ipv4。

**Comment by qxwo** [comment]
是的，也是没谁了，如果搜索引擎能搜到会麻烦的登录账号来反映情况？，排查没排查还真排查了。到底是人性的扭曲还是道德的沦丧？
我已经换nps了，既然选择开源却不允许反馈情况，不如直接关闭分享，有必要在这受我们这些菜鸟的气？
关闭吧或删除吧，不要再@我了
谢谢

**Comment by fatedier** [comment]
@qxwo 不用谢，我是想避免你过于依赖他人，缺乏自己解决问题的能力。这个问题是非常典型的问题，和具体的项目无关，我上面贴出来的链接是很轻易就可以搜索到的，为什么其他 issue 里的人遇到同样的问题也可以搜索到答案呢？

上面的回复也不是针对你，你提问题，我告诉你可以先自己搜索排查分析解决，你做不到，说了可以关闭 issue，我也关了，相安无事，你有提问的权利，我也有不回答的权利，毕竟没有利益关系。

回复针对 

> 这作者也是没谁了... 各种关闭问题. 不按他要求他关, 按他要求不想解决也关. 这bind_addr = 0.0.0.0
bind_port = 7000 之后启动会绑定到tcp6. 到底是程序问题还是个人配置问题?

总有人以为自己提了 issue，不管说了什么，项目维护者就必须给出答案，这是一个很不好的思维方式。尊重是相互的，你认认真真测试，帮助排查，反馈问题，提供足够的线索，我根据我的能力，花时间复现，搜索资料，解决问题，共同促进项目的发展，造福的是更多人。

如果使用者一遇到问题只知道提 issue 问，不知道自己分析，去论坛，去向其他使用者交流，总是期望维护者来提供贴身指导，这是自私的，每个人的时间都很宝贵。
