### ISSUE TITLE
xtcp打洞成功后如何通过http访问

### ISSUE THREAD

**Issue by Hirsi-He** [fatedier/frp#4352]
### Bug Description

我的公司电脑作为被访问端，挂了一个视频服务，配置的xtcp端口映射到这个服务端口上，服务是http协议的
我家这边作为访问端启动了xtcp，打洞成功了，但是无法通过http访问本地端口来访问公司电脑的http服务
![image](https://github.com/user-attachments/assets/b41957d4-4673-43e9-b678-9c5223219a33)

### frpc Version

0.59.0

### frps Version

0.59.0

### System Architecture

windows/amd64

### Configurations

name = "p2p_http_visitor"
type = "xtcp"
serverName = "p2p_http"
secretKey = "**********"
bindAddr = "127.0.0.1"
bindPort = 6000

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Hirsi-He** [comment]
这种如何能通过http访问啊

**Comment by fatedier** [comment]
Please use a search engine to query and solve the problem.

**Comment by Hirsi-He** [comment]
> Please use a search engine to query and solve the problem.

Search engines cannot find a solution to this problem

**Comment by Hirsi-He** [comment]
> Please use a search engine to query and solve the problem.

Can you provide some guidance
