### ISSUE TITLE
重启后第一次启动失败frpc

### ISSUE THREAD

**Issue by xxhh07** [fatedier/frp#4355]
### Bug Description

重启电脑第一次都是启动失败frpc

### frpc Version

0.59.0

### frps Version

0.59.0

### System Architecture

windows

### Configurations

1

### Logs

[1;34m2024-07-29 11:47:13.163 [I] [sub/root.go:142] start frpc service for config file [frpc.toml]
[0m[1;34m2024-07-29 11:47:13.207 [I] [client/service.go:294] try to connect to server...
[0m[1;33m2024-07-29 11:47:13.216 [W] [client/service.go:297] connect to server error: dial tcp: lookup xxxx.cn: no such host
[0m[1;34m2024-07-29 11:47:13.216 [I] [sub/root.go:160] frpc service for config file [frpc.toml] stopped
[0mlogin to the server failed: dial tcp: lookup xxxxx.cn: no such host. With loginFailExit enabled, no additional retries will be attempted

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xxhh07** [comment]
0.54 版本，后面升级到0.59版本 还是一样的，重启后自动启动失败，都要手工启动就正常

**Comment by subei12** [comment]
是不是电脑重启后没连上网就启动`frpc`了
试试这个参数为设置`false`
```
# Decide if exit program when first login failed, otherwise continuous relogin to frps
# default is true
loginFailExit = false
```

**Comment by xxhh07** [comment]
我试试。台式机电脑，是接网线的

**Comment by xxhh07** [comment]
可以了 谢谢
