### ISSUE TITLE
visitors的配置问题，如何连不同user的proxies？a用户的proxies配置x完成后，在b用户来看应该是a.x, 但当b用户配置成a.x后，接入时显示的是b.a.x不存在

### ISSUE THREAD

**Issue by miws** [fatedier/frp#4357]
### Bug Description

visitors的配置问题，如何连不同user的proxies？a用户的proxies配置x完成后，在b用户来看应该是a.x, 但当b用户配置成a.x后，接入时显示的是b.a.x不存在

### frpc Version

0.59.0

### frps Version

0.55.1

### System Architecture

linux/amd64

### Configurations

#a用户 frpc.toml
user="a"
[[proxies]]
name = "redis"
type = "stcp"
secretKey = "redis"
localIP = "127.0.0.1"
localPort = 6379
allowUsers = ["*"]

#b用户 frpc.toml
user="b"
[[visitors]]
name = "rV"
type = "stcp"
serverName = "a.redis"
secretKey = "redis"
bindAddr = "127.0.0.1"
bindPort = 6379

### Logs

visitors的配置问题，如何连不同user的proxies？a用户的proxies配置x完成后，在b用户来看应该是a.x, 但当b用户配置成a.x后，启动是成功的，当使用时 时显示的是b.a.x不存在

2024-07-31 09:42:32.125 [W] [visitor/stcp.go:114] [bfb9e0a1e6472163] [b.rV] start new visitor connection error: custom listener for [b.a.redis] doesn't exist

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
View documents.
