### ISSUE TITLE
frp客户端无法与服务器进行连接的问题

### ISSUE THREAD

**Issue by fatejia** [fatedier/frp#436]
frp版本 0.13.0
frp客户端运行在树莓派中，上级路由是爱快软路由，启动frp后出错，查看log内容为：
reconnect to server error: lookup vps.fatejia.online on 192.168.99.1:53: read udp 192.168.99.201:44127->192.168.99.1:53: read: connection refused
其中 192.168.99.201是树莓派IP，运行frpc；192.168.99.1是爱快软路由地址；vps.fatejia.online是frps所在的地址。
看log应该是路由禁止了访问。在爱快论坛反馈，官方回复为“我们只支持WEB界面登陆，其他的一些登陆方式我们不对用户开放”。
我不明白frpc与frps的通信和爱快的登录有什么关系，希望作者回答一下出现这个问题的起因，如果是路由的问题，希望作者做一个明确说明，我拿着去问爱快的技术支持。

谢谢作者开发的这个非常好用的工具。

**Comment by fatedier** [comment]
这个问题，和这个项目无关，你不应该放在这里提问的，可以去论坛或QQ群寻求帮助。

这个报错，显然是你的路由上的 dns 解析有问题，具体解决方案可以通过去网上搜索相关内容来解决。

**Comment by fatejia** [comment]
谢谢作者提醒
这个问题不是BUG，是设置的问题。
我只是没有找到相关信息，才来这里提问。
感谢作者的解答与提醒。
