### ISSUE TITLE
[Feature Request] frps管理面板中的流量统计增加统计时长设置

### ISSUE THREAD

**Issue by hzqim** [fatedier/frp#4362]
### Describe the feature request

目前的版本只能查看一天的流量？
能否增加一个星期，一个月，或长期的统计模形？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by xqzr** [comment]
目前可以查看**一周**的流量，点击“蓝色按钮”
