### ISSUE TITLE
[Feature Request] Https 能否支持 URL 路由 

### ISSUE THREAD

**Issue by ywj410** [fatedier/frp#4363]
### Describe the feature request

[Feature Request] Https 能否支持 URL 路由 

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
无法支持。frp 没有终结 TLS
