### ISSUE TITLE
How to get real IP address to RDP servers?

### ISSUE THREAD

**Issue by ylluminate** [fatedier/frp#4368]
### Bug Description

RDP servers get a lot of attacks. It doesn't seem there's a way to pass the true IP address of the attackers through FRP so as to be able to block them with EvlWatcher or IPBan. Is there any known workaround or such to facilitate getting the IP to Windows servers?

### frpc Version

0.59

### frps Version

0.59

### System Architecture

linux/amd64

### Configurations

Not relevant.

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
这需要 RDP 支持 “proxy protocol”。显然，这不太可能
