### ISSUE TITLE
服务端能否用80以外端口如8000

### ISSUE THREAD

**Issue by liwenjie119** [fatedier/frp#437]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.13.0

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**
默认

**Steps to reproduce the issue:**
frpc.ini
[common]
server_addr = 107.172.104.123
server_port = 7000
privilege_token = 12345
[web1]
privilege_mode = true
type = http
local_ip = 192.168.31.1
local_port = 80
frps.ini
[common]
bind_port = 7000
dashboard_port = 7500
vhost_http_port = 8000
privilege_mode = true
privilege_token = 12345
log_file = ./frps.log
log_level = info
log_max_days = 3

**Describe the results you received:**
路由端
Aug 23 19:22:43 【frp】: frpc-version: 0.13.0
Aug 23 19:22:43 【frp】: frpc启动失败, 注意检查端口是否有冲突,程序是否下载完整,10 秒后自动尝试重新启动
打开107.172.104.123:8000提示
The page you visit not found.

Sorry, the page you are looking for is currently unavailable.
Please try again later.

The server is powered by frp.

Faithfully yours, frp.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
可以用，有疑问可以再详细看看关于 http 类型的 proxy 的说明文档。
