### ISSUE TITLE
frpc config file

### ISSUE THREAD

**Issue by zsl7091** [fatedier/frp#4372]
### Bug Description

frpc config file has no any errors for the version 0.54.0, but always error for version 0.59.0, so that the frpc cannot start. error logs: unmarshal ProxyConfig error: json: unknown field "customDomains". if run the verification command, it shows: unmarshal ProxyConfig error: json: unknown field "customDomains". 

### frpc Version

0.59.0

### frps Version

0.59.0

### System Architecture

amd64

### Configurations

customDomains

### Logs

unmarshal ProxyConfig error: json: unknown field "customDomains"

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
So you need to remove customDomains.

**Comment by zsl7091** [comment]
If I remove customDomains, how to access the differnt proxies with the same port, such as 8080 and 8081? Why there is no problem on the version 0.54.0?
