### ISSUE TITLE
FRP 的双向验证设置应当使用相同的证书吗？

### ISSUE THREAD

**Issue by MironChen** [fatedier/frp#4375]
### Bug Description

我在运行 frps 的VPS上使用acme.sh（via let's encrypt） 生成了 server.crt server.key 和 ca.crt (使用域名 frp.example.com）然后在本地运行的群晖 DSM里用相同的方式生成了三份证书。但在连接时提示 `x509: certificate has expired or is not yet valid.`

此时，VPS上的CA证书由E6签发（let's encrypt)，DSM 上的证书由E5签发。

在更新两份CA均为 E5 签发后，问题消失。

### frpc Version

0.59

### frps Version

0.59

### System Architecture

linux/amd64

### Configurations

As description

**Comment by xqzr** [comment]
尝试 `fullchain.cer`

**Comment by MironChen** [comment]
`# frpc.toml
transport.tls.certFile = "/to/cert/path/client.crt"
transport.tls.keyFile = "/to/key/path/client.key"
transport.tls.trustedCaFile = "/to/ca/path/ca.crt"

# frps.toml
transport.tls.certFile = "/to/cert/path/server.crt"
transport.tls.keyFile = "/to/key/path/server.key"
transport.tls.trustedCaFile = "/to/ca/path/ca.crt"`

按照 frp 提供的官方文档，似乎只提供了分别使用三个文件的方法？

**Comment by fatedier** [comment]
一般来说需要相同的 CA 签发。
