### ISSUE TITLE
阿里云和内网服务器穿透设置成功后，为什么使用ssh无法穿透到内网服务器？

### ISSUE THREAD

**Issue by minglhappy** [fatedier/frp#4377]
### Bug Description

阿里云和内网服务器穿透设置成功后，为什么使用ssh无法穿透到内网服务器？

下面是内网客户端与服务器端链接成功的输出：
2024-08-13 00:16:52.645 [I] [sub/root.go:142] start frpc service for config file [./frpc.toml]
2024-08-13 00:16:52.645 [I] [client/service.go:294] try to connect to server...
2024-08-13 00:16:52.663 [I] [client/service.go:286] [b9ef3abec30f093f] login to server success, get run id [b9ef3abec30f093f]
2024-08-13 00:16:52.663 [I] [proxy/proxy_manager.go:173] [b9ef3abec30f093f] proxy added: [ssh]
2024-08-13 00:16:52.668 [I] [client/control.go:168] [b9ef3abec30f093f] [ssh] start proxy success

下面是用CMD进行ssh登录返回：无法成功。。。。。。。。。。。。。。。

C:\Users\Administrator>ssh -vvv root@XX.XX.XX.XX -p 6000
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
debug3: Failed to open file:C:/Users/Administrator/.ssh/config error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolve_canonicalize: hostname XX.XX.XX.XX is address
debug2: ssh_connect_direct
debug1: Connecting to XX.XX.XX.XX [XX.XX.XX.XX] port 6000.
debug3: finish_connect - ERROR: async io completed with error: 10060, io:0000028725DE8E50
debug1: connect to address XX.XX.XX.XX port 6000: Connection timed out
ssh: connect to host XX.XX.XX.XX port 6000: Connection timed out

### frpc Version

frp_0.58.1_linux_amd64

### frps Version

frp_0.58.1_linux_amd64

### System Architecture

centos8.5, centos8.5

### Configurations

请见问题描述~

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by subei12** [comment]
阿里云端口开了吗？
试试通不通
``` ssh
telnet XX.XX.XX.XX 6000
```

**Comment by minglhappy** [comment]
感谢大佬回复，昨天是忘了开6000的端口，开通端口后就可以连上了，昨晚一直开着，可不知道为什么早上7:33居然断开了，

因为局域网在校园，晚间3点钟会断网一次，然后自动连上，跟这个有关吗？应该没关系吧？多谢~













在 2024-08-13 11:48:37，"安然" ***@***.***> 写道：

阿里云端口开了吗？
试试通不通

telnet XX.XX.XX.XX 6000

**Comment by subei12** [comment]
断电导致的断网吗？frpc 所在的设备有没有重启呢？
这个最好还是看下7:33的 frpc 日志

**Comment by minglhappy** [comment]
请问日志在哪里看？多谢~













在 2024-08-13 14:07:43，"安然" ***@***.***> 写道：

断电导致的断网吗？frpc 所在的设备有没有重启呢？
这个最好还是看下7:33的 frpc 日志

**Comment by xqzr** [comment]
> 请问日志在哪里看？多谢~ 在 2024-08-13 14:07:43，"安然" ***@***.***> 写道： 断电导致的断网吗？frpc 所在的设备有没有重启呢？ 这个最好还是看下7:33的 frpc 日志 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

你提供的“输出”就是日志
