### ISSUE TITLE
[Feature Request] frpc 单向校验 frps 身份场景下，frps端更新证书时，frpc端是否随之自动获取ca.crt更新

### ISSUE THREAD

**Issue by sopyk** [fatedier/frp#4378]
### Describe the feature request

如题请教，在文档中没看出来。双向校验的情况呢？

### Affected area

- [x] Docs
- [ ] Installation
- [x] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
不会更新另一端的证书
