### ISSUE TITLE
[建议]-将S端和C端分开发布

### ISSUE THREAD

**Issue by ImSiegeLion** [fatedier/frp#438]
如果可以将服务端和客户端分开发布会更方便一些。

因为存在这样一些情况：外网的服务器使用Linux，但是内网的服务器使用的是Mac或Windows。

我现在的环境就是外网是Linux而内网是Mac，这时我需要下载两个版本的完整包，然后在删除对应不需要的部分。

这样我多下载了一些无用的部分，我想我的这种情况应该不是少数。

**Comment by fatedier** [comment]
目前看并没有什么影响，另外推荐自己下载源码编译。

**Comment by ImSiegeLion** [comment]
面向懒人做设计   ----   张小龙
[doge][滑稽]

**Comment by fatedier** [comment]
首先这不是一个产品，github 上也不面向普通用户，其次还在前期开发阶段，不会过多关注细节。

开源项目的目的也不一定就是要让你去使用，我觉得更多的意义在于你可以看到如何实现这个东西，原理是什么，代码组织，框架设计，一些常用的库的封装，等等。
