### ISSUE TITLE
按照配置模板设置tls2raw，https相关的，结果frpc会闪退

### ISSUE THREAD

**Issue by zsanjin-p** [fatedier/frp#4380]
### Describe the feature request

服务端和客户端使用：frp_0.59.0_windows_amd64

https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml  模板328行

frpc配置如下：

serverAddr = "1.1.1.1" 
serverPort = 7000
auth.token = "114514" 
transport.tcpMux = true 
log.to = "./frpc.log"
log.level = "trace"
log.maxDays = 3
log.disablePrintColor = false

[[proxies]]
name = "plugin_tls2raw"
type = "https"
remotePort = 6008
[proxies.plugin]
type = "tls2raw"
localAddr = "127.0.0.1:8008"
crtPath = "./server.crt"
keyPath = "./server.key"

确认frpc工作目录下有crt和key的证书，加上这行配置就会闪退，日志都没有记录原因，删除这段就正常了，不知什么问题

**Comment by haodiao** [comment]
plugin  tls2raw 是下个版本的特征，0.59.0 不支持
