### ISSUE TITLE
frpc自启动出错

### ISSUE THREAD

**Issue by skoy03** [fatedier/frp#4383]
### Bug Description

connect to server error: dial tcp: lookup junhe.268e.cn on 192.168.100.100:53: dial udp 192.168.100.100:53: connect: network is unreachable

因为IP是动态IP，所以serverAddr就填写域名进行获取IP，但是自启动的时候就会报错，手动启动反而没问题

### frpc Version

0.59

### frps Version

0.59

### System Architecture

linux/amd64

### Configurations

frpc配置文件
# Server Configure
serverAddr = "junhe.268e.cn"
serverPort = 7000

### Logs

login to the server failed: dial tcp: lookup junhe.268e.cn on 192.168.100.100:53: dial udp

### Steps to reproduce

只要重启后自启动就会出现

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/blob/2dcdb24cc4a0792a5e75527d43ccb8fd2e40da92/conf/frpc_full_example.toml#L17
