### ISSUE TITLE
配置的http请求，内网穿透后请求头丢失导致无法解析

### ISSUE THREAD

**Issue by yaozg1041138840** [fatedier/frp#4386]
### Describe the feature request

怎么处理请求头才不会丢失呢，内网是正常访问的

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
#4385
