### ISSUE TITLE
我需要直接把配置文件一起编译，请问需要如何做？

### ISSUE THREAD

**Issue by wuai1024** [fatedier/frp#4387]
### Describe the feature request

目前编译后，需要外挂配置文件，我有部分场景，是需要把配置文件内置的，然后直接运行编译之后的文件。请问下我需要如何做？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by superzjg** [comment]
其实可以不用配置文件，而用启动参数实现的。

**Comment by wuai1024** [comment]
> 其实可以不用配置文件，而用启动参数实现的。

多了用参数不是很方便，我是需要集中下发。客户端只需要运行就行，不关注配置文件。

**Comment by wuai1024** [comment]
已解决。

**Comment by yangjieshao** [comment]
> 已解决。

- - 咋解决的倒是说一句啊
