### ISSUE TITLE
FRPC的客户端有其他语言的实现吗？或者说Client的c，c#等sdk实现不

### ISSUE THREAD

**Issue by guozanhua218** [fatedier/frp#4389]
### Describe the feature request

需要一个frpc的其他语言实现

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
SSH 隧道网关 可以了解一下
https://gofrp.org/zh-cn/docs/features/common/ssh/

**Comment by superzjg** [comment]
貌似有第三方用c语言写的客户端，精简功能，占用空间很小，但兼容：
https://github.com/liudf0716/xfrpc
