### ISSUE TITLE
想要同时使用80和8080在同一个域名上处理不成功

### ISSUE THREAD

**Issue by qz812371248** [fatedier/frp#439]
Frp version: 0.13.0

Operating system: Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

Configures:
#配置web站点
[web_pi]
type = http
vhost_http_port = 80
local_ip = 192.168.199.100
local_port = 80
custom_domains = zzdev.top
use_encryption = true
use_compression = true

#配置tomcat
[tomcat8080]
type = http
vhost_http_port = 8080
local_port = 8080
custom_domains = zzdev.top
local_ip = 192.168.199.100
use_encryption = true
use_compression = true
 

Error: 2017/08/25 17:50:45 [W] [control.go:388] [baca68de17fd02bc] [tomcat8080] start error: hostname [zzdev.top] location [] is already registered

**Comment by fatedier** [comment]
Not a problem, read the doc first.

**Comment by qz812371248** [comment]
之前看过文档 没有看到这种配置的例子
能否举个例

**Comment by fatedier** [comment]
使用 type = tcp 的方法。
