### ISSUE TITLE
希望能控制  server 端的监听地址。

### ISSUE THREAD

**Issue by IAliceBobI** [fatedier/frp#4390]
### Describe the feature request

很喜欢 frp！

我有一种场景，有时不想在服务暴露某些内网服务的ip到0.0.0.0，希望可以提供remoteIP 来控制监听地址。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
查看 example 配置文件找一下具体的配置项。

**Comment by IAliceBobI** [comment]
@fatedier   感谢回答。

我还没看懂，想请教一下您。

比如这个例子：

```
serverAddr = "127.0.0.1"
serverPort = 7000

[[proxies]]
name = "test-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000
```

我想要让  6000 监听在 127.0.0.1 如何写？

**Comment by pasiphae321** [comment]
虽然只能绑定到0.0.0.0，但可以通过防火墙实现隐藏

**Comment by IAliceBobI** [comment]
它是通过   客户端 --   服务器  --   客户端     的方式来实现控制ip的。服务器的ip设置是固定公开的。

不过我是觉得可以控制服务器的 IP，这样设置会方便一点。
