### ISSUE TITLE
frpc 启动报错 failed to parse proxy proxies.plugin, err: invalid type [https2http]

### ISSUE THREAD

**Issue by xielingyong918** [fatedier/frp#4393]
### Bug Description

frpc 启动时报错 failed to parse proxy proxies.plugin, err: invalid type [https2http]

### frpc Version

0.60.0

### frps Version

0.60.0

### System Architecture

linux/amd64 Centos7

### Configurations

Enable HTTPS for a local HTTP(S) service

#frps.ini
```shell
[common]
bind_port = 29000
vhost_http_port = 29003
vhost_https_port = 29007
dashboard_port = 29004
token = *****
max_pool_count = 20
#dashboard 用户名密码，默认都为 admin
dashboard_user = *****
dashboard_pwd = *****
log_level = info
log_file=/www/frp6.0/frp.log
```

#frpc.ini
```shell
[common]
server_addr = *****
server_port = 29000
token = *****

[[proxies]]
name = "plugin_https2http"
type = "https"
customDomains = ["a.example.com"]
[proxies.plugin]
type = "https2http"
localAddr = "192.168.103.104:3377"
crtPath = "./fullchain.crt"
keyPath = "./private.pem"
hostHeaderRewrite = "127.0.0.1"
requestHeaders.set.x-from-where = "frp"
#log.to = "./frpc.log"
```

### Logs

无

### Steps to reproduce

```shell
[root@logfile frp6.0]# ./frpc -c frpc.ini 
failed to parse proxy proxies.plugin, err: invalid type [https2http]
```

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
新(toml)旧(ini)格式不可混用，选择一种
**（建议）https://github.com/fatedier/frp/tree/dev/conf**
_https://github.com/fatedier/frp/tree/dev/conf/legacy_

**Comment by Septemberlemon** [comment]
> 新(toml)旧(ini)格式不可混用，选择一种 **（建议）https://github.com/fatedier/frp/tree/dev/conf** _https://github.com/fatedier/frp/tree/dev/conf/legacy_

666

**Comment by LinboLen** [comment]
遇到同样的问题
