### ISSUE TITLE
frps和frpc点对点配置，挂载的三个ssh服务，会不定期同时中断。

### ISSUE THREAD

**Issue by sslzhou948** [fatedier/frp#4395]
### Bug Description

服务端和客户端分别安装在两套openwrt上，使用mobax访问服务端对应的三个ssh服务，不定期的会所有连接同时中断。

### frpc Version

0.47.0

### frps Version

0.47.0

### System Architecture

Linux/X86_64

### Configurations

![image](https://github.com/user-attachments/assets/008d1855-19fb-4016-820b-57f8270f0b3e)

### Logs

![1724220349323](https://github.com/user-attachments/assets/968b484c-e1a1-4163-a46f-cca661f0aa59)

### Steps to reproduce

1. frpc增加transport.tcpMuxKeepaliveInterval = 30 和transport.heartbeatInterval = 30 
2. ssh 启用 keepalive，例如 ServerAliveInterval 60
3. mobax打开链接保持
4. 日志已经可以看到心跳记录
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by firmament2008** [comment]
对于TCP长会话。 是否有中间防火墙，配置了最大持续时间？ 通常来说KeepaliveInterval  需要大于 3倍的 heartbeatInterval 。

**Comment by xqzr** [comment]
注意到心跳只有 接收，没有 发送（回复）

**Comment by sslzhou948** [comment]
> 注意到心跳只有 接收，没有 发送（回复）

我理解另一端的日志里应该有发送吧？
