### ISSUE TITLE
Microsoft Defender 报告病毒

### ISSUE THREAD

**Issue by oddwatcher** [fatedier/frp#4397]
### Bug Description

似乎微软自带的defender会将frps与frpc当作病毒程序进行处理
![image](https://github.com/user-attachments/assets/1e434a22-d108-4512-b7f1-7e57f07ca09a)

### frpc Version

0.6.0

### frps Version

0.6.0

### System Architecture

windows/amd64

### Configurations

None

### Steps to reproduce

1. 下载frps/frpc二进制文件，随后解压
2. 解压过程中Defender则会报告威胁并且移除frps与frpc文件

请排查一下有无发生供应链投毒或者向微软报告误杀
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by huihuoshiguang** [comment]
# 2095

**Comment by huihuoshiguang** [comment]
#2095

**Comment by ilcxyz** [comment]
遇到同样的情况
