### ISSUE TITLE
frp跑不满带宽

### ISSUE THREAD

**Issue by beerjim** [fatedier/frp#4402]
### Bug Description

服务器是2G的口子，家用宽带上行50Mbps，家里架设了群晖nas。在别的地方用浏览器直接下载，速度最多到2.5MB/s，但是用IDM的多线程下载，速度可以到5M/s左右的速度，如果用zerotier或者tailscale穿透速度能到5-6M/s。如果用群晖自带的photo mobile上传，速度也只有1-2M/s的速度。但是用zerotier或者tailscale穿透速度能到5-6M/s。之前看论坛说是tcpmux为ture引起的，后来关了也不行，大佬知道这个啥原因吗

### frpc Version

0.59.0

### frps Version

0.59.0

### System Architecture

linux/amd64

### Configurations

**frps**

bindAddr = "0.0.0.0"
bindPort = 8443

transport.heartbeatTimeout = 90
transport.maxPoolCount = 50

transport.tcpMux = false

vhostHTTPPort = 80
vhostHTTPSPort = 443

webServer.addr = "0.0.0.0"
webServer.port = 6443
webServer.user = "admin"
webServer.password = "*****"
webServer.tls.certFile = "/etc/tls/*****.crt"
webServer.tls.keyFile = "/etc/tls/*****.key"

log.to = "enable"
log.level = "info"
log.maxDays = 3

auth.method = "token"
auth.token = "*****"

**frpc**

serverAddr = "*****" 
serverPort = 8443
auth.method = "token" 
auth.token = "*****" 

[[proxies]] 
name = "dsm"
type = "https"
localIP = "*****"
localPort = 5001
customDomains = ["*****"]

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by wuai1024** [comment]
用  tcp 类型试试

**Comment by xqzr** [comment]
```toml
#frps
quicBindPort = 8443

#frpc
transport.protocol = "quic"
```

**Comment by beerjim** [comment]
quic协议容易被vps厂家当作ddos攻击，用不成

**Comment by beerjim** [comment]
经过多方研究，虽然问题没有彻底得到解决，但是我感觉应该是跟tcp的拥塞算法有关，增大tcp window size可以改善问题，但是并没有完全解决
