### ISSUE TITLE
[Feature Request] 是否可以通过建立多条quic连接、不断换端口等方式规避运营商udp限速？

### ISSUE THREAD

**Issue by MrMu666** [fatedier/frp#4406]
### Describe the feature request

有时候xtcp打洞成功了，但是运营商udp限速，导致只有几百kB/s的网速。是否可以通过建立多路udp连接的方式提升这种场景的网速？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
你可以尝试结合其他项目使用，这个项目目前不太会针对这些问题提供各种规避的方式。

**Comment by MrMu666** [comment]
> 你可以尝试结合其他项目使用，这个项目目前不太会针对这些问题提供各种规避的方式。

大佬有没有推荐的这种项目啊？找好久没找到
