### ISSUE TITLE
[Feature Request] 请问有没有代码api文档？

### ISSUE THREAD

**Issue by Firebasky** [fatedier/frp#4408]
### Describe the feature request

背景：我想在其他工具里面集成frp的代理功能，所以我想能不能直接通过import github.com/fatedier/frp 来使用。请问有没有相关的文档？谢谢

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
没有。
