### ISSUE TITLE
windows远程端口复用不成功

### ISSUE THREAD

**Issue by ww027** [fatedier/frp#4409]
### Bug Description

配置好服务端和客户端后，客户端与服务端链接正常，但是通过MSTSC域名+端口dx.bestk.top:5002一直无法远程访问，telnet测试5002端口测试是通的。

### frpc Version

0.60.0

### frps Version

0.60.0

### System Architecture

服务端：linux/amd64
客户端：Windows/amd64

### Configurations

**frps端配置**
bindPort = 7000
tcpmuxHTTPConnectPort = 5002

**frpc端配置**
serverAddr = "bestk.top"
serverPort = 7000
[[proxies]]
name = "rdp"
type = "tcpmux"
multiplexer = "httpconnect"
customDomains = ["dx.bestk.top"]
localIP = "127.0.0.1"
localPort = 3389

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
不支持。

**Comment by wuai1024** [comment]
这个搞复杂了啊， `mstsc` 直接代理 出来 tcp + udp 就好了，很好用。
