### ISSUE TITLE
[Feature Request] 新增模块构想

### ISSUE THREAD

**Issue by syihujiu** [fatedier/frp#4410]
### Describe the feature request

1.是否可增加对各个在线客户端的管控
2.客户端配置后是否拥有热加载

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
目前没有计划。
