### ISSUE TITLE
virus_result

### ISSUE THREAD

**Issue by HelloShan** [fatedier/frp#4412]
### Bug Description

 2024-08-30 15:14:47	HackerTool.MPE.Frps.A	77372e9109166cd1b59e265610c11117	frp_0.60.0_windows_amd64.zip

### frpc Version

0.60.0

### frps Version

0.60.0

### System Architecture

windows/amd64

### Configurations

null

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by shshbuxi** [comment]
I'm experiencing the same issue on Ubuntu 22.04.
Frp version：0.58.1

**Comment by superzjg** [comment]
https://github.com/fatedier/frp/issues/2095

**Comment by HelloShan** [comment]
close
