### ISSUE TITLE
无法使用Windows RDP

### ISSUE THREAD

**Issue by Sudierth** [fatedier/frp#4413]
### Bug Description

使用frp配置windows RDP但出现0x4错误

我在一台阿里云服务器上设置了frps，并且在一台OpenWRT上设置了frpc。
在确认阿里云安全组、OpenWRT防火墙和CentOS防火墙开启7000和3389端口的情况下，
使用ios和macOS上的由微软官方在Apple Store提供的Remote PC通过阿里云的公网链接到OpenWRT内网下的192.168.22.202这台Windows PC失败，出现0x4错误。在内网环境下通过相同的配置链接到192.168.22.202可以正常使用。
相同环境下的ssh和Minecraft链接均正常工作。

### frpc Version

0.60.0

### frps Version

0.60.0

### System Architecture

CentOS7, OpenWRT

### Configurations

OpenWRT
frpc.toml:
serverAddr = "***"
serverPort = 7000

[[proxies]]
name = "avisa.top"
type = "tcp"
localIP = "192.168.22.201"
localPort = 25565
remotePort = 25565

[[proxies]]
name = "ltsc.avisa.top"
type = "tcp"
localIP = "192.168.22.201"
localPort = 25567
remotePort = 25567

[[proxies]]
name = "ssh-avisa.top"
type = "tcp"
localIP = "192.168.22.201"
localPort = 22
remotePort = 15201

[[proxies]]
name = "ssh-spsMacBookPro2017"
type = "tcp"
localIP = "192.168.22.202"
localPort = 15202
remotePort = 15202

[[proxies]]
name = "rdp-spsLTSC2021"
type = "tcp"
localIP = "192.168.22.203"
localPort = 3389
remotePort = 3389

[[proxies]]
name = "test-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000

CentOS On Aliyun
bindPort = 7000

### Steps to reproduce

1. 在阿里云具有公网的服务器上设置frps
2. 在OpenWRT上设置frpc
3. 通过RDP客户端使用公网ip链接 

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Sudierth** [comment]
Windows防火墙也已经全部打开（直接干掉了（关掉了））

**Comment by wuai1024** [comment]
你 192.168.22.202 不是一台  `mac` 吗？ 你192.168.22.203 才是 win 吧。
