### ISSUE TITLE
高版本是没有bind_udp_port参数了吗

### ISSUE THREAD

**Issue by wangzhengzhen** [fatedier/frp#4414]
### Describe the feature request

在0.60.0版本，示例配置文件，没有bind_udp_port，只有kcpBindPort。如果要使用udp端口，是用kcpBindPort代替bind_udp_port吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by superzjg** [comment]
frpc:
Communication protocol used to connect to server
 supports tcp, **kcp, quic**, websocket and wss now, default is tcp
`transport.protocol = "tcp"`

frps：
 udp port used for kcp protocol, it can be same with 'bindPort'.
 if not set, kcp is disabled in frps.
`kcpBindPort = 7000`

udp port used for quic protocol.
if not set, quic is disabled in frps.
 `quicBindPort = 7002`
