### ISSUE TITLE
[Question]是否支持吧frps作为集群部署，集群使用的部署架构

### ISSUE THREAD

**Issue by peter-wangxu** [fatedier/frp#4415]
### Bug Description

这个不是bug，这是一个问题

场景是这样的

我希望将frps作为集群使用，防止单点故障，提升整体的服务效率

我理解frps对链接有状态，所以当一个frpc 链接到特定的frps服务后，是无法通过对等部署的另外一个frps 服务链接到frpc节点的

我的问题是，如果我有两个以上的frps服务，frps-1，frps-2，怎么部署才能，做到对frpc和使用需要连接到frpc的服务（myproject）无需感知多个frps的存在？

myproject ->  (高可用部署？nginx？) -> (frps-1, frps-2) -> frpc-1

### frpc Version

0.60.0

### frps Version

0.60.0

### System Architecture

linux/amd64

### Configurations

any config

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
目前不支持。
