### ISSUE TITLE
代理http返回 400 Bad Request

### ISSUE THREAD

**Issue by luyanfeng** [fatedier/frp#4418]
### Bug Description

代理springboot 服务 http服务,
返回 400 Bad Request

### frpc Version

0.60.0

### frps Version

0.60.0

### System Architecture

linux/amd64 (ubuntu24.04)

### Configurations

frpc: 
```
[[proxies]]
name = "sgy"
type = "tcp"
#type = "http"
localIP = "127.0.0.1"
localPort = 9236
transport.proxyProtocolVersion = "v2"
subdomain = "sgy"
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by luyanfeng** [comment]
不知道为什么给关了,

实事上,我改用ini文件配置却成功了.

是不是说明.toml的配置方式是有bug的呢?

**Comment by zhangtianming777** [comment]
添加了这个配置：transport.proxyProtocolVersion = "v2" 请问你是否可以获取到用户真实IP呢？
