### ISSUE TITLE
frp断掉了，连不上去

### ISSUE THREAD

**Issue by wenbinonlyid** [fatedier/frp#442]
我的服务器平台是Windows,
服务器配置：
![image](https://user-images.githubusercontent.com/31396141/29757098-f81e69e8-8bdb-11e7-8c89-a0ec126226b4.png)
客户端配置：
![image](https://user-images.githubusercontent.com/31396141/29757127-21120404-8bdc-11e7-8a7d-476d19131e35.png)
frp断掉了，连不上去，重启一下start命令之后又可以了，但是断线的频率太多了，几天来一次；
下面是两个日志截图：
服务端日志截图：
![image](https://user-images.githubusercontent.com/31396141/29757168-6ac62544-8bdc-11e7-9a9b-207f274712d3.png)

客户端日志截图：
![image](https://user-images.githubusercontent.com/31396141/29757159-5a769246-8bdc-11e7-97b8-1a32c29aca69.png)

**Comment by wenbinonlyid** [comment]
版本号补充：frp_0.9.0_windows_386

**Comment by fatedier** [comment]
首先，issue 格式不对，请遵守格式提供必要的信息；其次，0.9 版本已经不再维护，可以尝试更新到最新版本。
