### ISSUE TITLE
[Feature Request] 请问 frp 有没有部署在 serverless 上的思路

### ISSUE THREAD

**Issue by BowmanChow** [fatedier/frp#4420]
### Describe the feature request

我想把 frps 部署在 serverless 上，但是目前的 serverless 似乎只支持 http 请求。

我看了一下似乎 `tcpmuxHTTPConnectPort` 这个可以实现 http 请求。

但是问题又来了， `tcpmuxHTTPConnectPort` 和 `bindPort` 一共需要 2 个 port， 目前的 serverless 似乎只支持 1 个 port。

不知道有没有什么思路，或者后续开发有没有这方面的计划。

PS： 我只测试了 aliyun 的 serverless。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
没有。
