### ISSUE TITLE
如何访问frpc端所在的路由器页面？80端口转发正常！但是浏览器打不开？

### ISSUE THREAD

**Issue by worm001** [fatedier/frp#4424]
### Bug Description

在配置中定义了一个内网网关，192.168.31.254的80端口的转发，一切都正常！但是在服务端这边浏览器上打开： http://127.0.0.1:10080  并不能正常打开小米路由器页面！ 小米路由器IP为： 192.168.31.254 浏览器中显示为： 502 Bad Gateway
nginx/1.12.2，应该端口是正常转发的，会不会是小米路由限制有些IP的访问？ 像这种情况FRP是否无能为力？

### frpc Version

0.60

### frps Version

0.60

### System Architecture

windows/amd64

### Configurations

serverAddr = "x.x.org"
serverPort = 7000
loginFailExit = false
log.to = "./frpc.log"

[[proxies]]
name = "xiaomiluyouqi"
type = "tcp"
localIP = "192.168.31.254"
localPort = 80
remotePort = 10080
transport.useCompression = true

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
小米不知道，同样的配置tplink路由器没有问题，我干过。
你可以尝试改用http类型，然后附加 `hostHeaderRewrite` `requestHeaders.set.x-from-where` `responseHeaders.set.foo`等参数
