### ISSUE TITLE
问题：type [http] not supported when vhost http port is not set

### ISSUE THREAD

**Issue by AetherLude** [fatedier/frp#4425]
### Bug Description

当我启动frpc服务(1panel)的时候，日志跟我说 type [http] not supported when vhost http port is not set

我在尝试设置二级域名，按照这个文档写的：https://gofrp.org/zh-cn/docs/features/http-https/subdomain/

### frpc Version

0.60.0

### frps Version

0.60.0

### System Architecture

frps:Debian11, frpc:Ubuntu20.04.06

### Configurations

(frps)
bindAddr = "0.0.0.0"
bindPort = 7839

auth.method = "token"
auth.token = "atoken"

webServer.addr = "0.0.0.0"
webServer.port = 23679
webServer.user = "admin"
webServer.password = "password"

subdomainHost = "domain.cn"
vhostHTTPSPort = 6001

-----

(frpc)
serverAddr = "ip.ip.ip.ip"
serverPort = 7839

auth.method = "token"
auth.token = "atoken"

webServer.addr = "0.0.0.0"
webServer.port = 23679
webServer.user = "admin"
webServer.password = "password"
webServer.pprofEnable = false

[[proxies]]
name = "proxy1"
type = "http"
localPort = port
subdomain = "sd1"

[[proxies]]
name = "proxy2"
type = "http"
localPort = port
subdomain = "sd2"

[[proxies]]
name = "proxy3"
type = "tcp"
localPort = port
remotePort = remoteport

### Logs

1Panel-frpc-EDUi  | [0m[1;34m2024-09-08 14:05:12.534 [I] [sub/root.go:142] start frpc service for config file [/etc/frp/frpc.toml]
1Panel-frpc-EDUi  | [0m[1;34m2024-09-08 14:05:12.534 [I] [client/service.go:295] try to connect to server...
1Panel-frpc-EDUi  | [0m[1;34m2024-09-08 14:05:12.535 [I] [client/service.go:174] admin server listen on 0.0.0.0:23679
1Panel-frpc-EDUi  | [0m[1;34m2024-09-08 14:05:12.688 [I] [client/service.go:287] [e900be117ded6802] login to server success, get run id [e900be117ded6802]
1Panel-frpc-EDUi  | [0m[1;34m2024-09-08 14:05:12.689 [I] [proxy/proxy_manager.go:173] [e900be117ded6802] proxy added: [proxy1 proxy2 proxy3]
1Panel-frpc-EDUi  | [0m[1;34m2024-09-08 14:05:12.732 [I] [client/control.go:168] [e900be117ded6802] [proxy3] start proxy success
1Panel-frpc-EDUi  | [0m[1;33m2024-09-08 14:05:12.733 [W] [client/control.go:166] [e900be117ded6802] [proxy1] start error: type [http] not supported when vhost http port is not set
1Panel-frpc-EDUi  | [0m[1;33m2024-09-08 14:05:12.733 [W] [client/control.go:166] [e900be117ded6802] [proxy2] start error: type [http] not supported when vhost http port is not set

### Steps to reproduce

配置好以上文件后启动服务出现了这些问题

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
缺少 https://github.com/fatedier/frp/blob/fe4ca1b54e9045ea91ffa4645ac8f39bb2e770ef/conf/frps_full_example.toml#L52

**Comment by AetherLude** [comment]
oh好的谢谢啦，没看见是Https port
