### ISSUE TITLE
[Feature Request] frps启动相对以前的启动挺慢的

### ISSUE THREAD

**Issue by inkstoner** [fatedier/frp#4427]
### Describe the feature request

最新版的frps感觉启动好慢啊，请问有没有什么可以改配置优化启动速度的地方哇

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
应该没有。
