### ISSUE TITLE
An attempt was made to access a socket in a way forbidden by its access permissions.

### ISSUE THREAD

**Issue by gongjianfeng1982** [fatedier/frp#4428]
### Bug Description

![image](https://github.com/user-attachments/assets/b5cbf16c-1136-4839-80a9-daaf312c1702)

### frpc Version

0.6

### frps Version

0.6

### System Architecture

win10

### Configurations

[[proxies]] # siemens server -> resmon.exe | netstat.exe -aon
localIP = "192.168.8.8"
localPort = 102
name = "p2p_siemens"
secretKey = "xyz9527"
type = "xtcp"

[[visitors]] # siemens client -> resmon.exe | netstat.exe -aon 停止102服务 Siemens S7DOS Help Service
bindAddr = "127.0.0.1"
bindPort = 102
name = "p2p_siemens_visitor"
secretKey = "xyz9527"
serverName = "p2p_siemens"
type = "xtcp"

### Logs

F:\windows_amd64>frpc.exe -c frpc.toml
[1;34m2024-09-10 23:17:21.135 [I] [sub/root.go:142] start frpc service for config file [frpc.toml]
[0m[1;34m2024-09-10 23:17:21.143 [I] [client/service.go:294] try to connect to server...
[0m[1;34m2024-09-10 23:17:21.341 [I] [client/service.go:286] [1e2bc86bd1e6586e] login to server success, get run id [1e2bc86bd1e6586e]
[0m[1;33m2024-09-10 23:17:21.342 [W] [visitor/visitor_manager.go:118] [1e2bc86bd1e6586e] start error: listen tcp 127.0.0.1:102: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
[0m[1;34m2024-09-10 23:17:21.342 [I] [visitor/visitor_manager.go:172] [1e2bc86bd1e6586e] visitor added: [p2p_siemens_visitor]
[0m[1;34m2024-09-10 23:17:31.342 [I] [visitor/visitor_manager.go:89] [1e2bc86bd1e6586e] try to start visitor [p2p_siemens_visitor]
[0m[1;33m2024-09-10 23:20:59.256 [W] [visitor/visitor_manager.go:118] [1e2bc86bd1e6586e] start error: listen tcp 127.0.0.1:102: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
[0m[1;34m2024-09-10 23:20:59.256 [I] [visitor/visitor_manager.go:89] [1e2bc86bd1e6586e] try to start visitor [p2p_siemens_visitor]
[0m[1;33m2024-09-10 23:20:59.256 [W] [visitor/visitor_manager.go:118] [1e2bc86bd1e6586e] start error: listen tcp 127.0.0.1:102: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
[0m[1;34m2024-09-10 23:21:01.342 [I] [visitor/visitor_manager.go:89] [1e2bc86bd1e6586e] try to start visitor [p2p_siemens_visitor]
[0m[1;33m2024-09-10 23:21:01.342 [W] [visitor/visitor_manager.go:118] [1e2bc86bd1e6586e] start error: listen tcp 127.0.0.1:102: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
[0m[1;34m2024-09-10 23:21:11.342 [I] [visitor/visitor_manager.go:89] [1e2bc86bd1e6586e] try to start visitor [p2p_siemens_visitor]
[0m[1;33m2024-09-10 23:21:11.342 [W] [visitor/visitor_manager.go:118] [1e2bc86bd1e6586e] start error: listen tcp 127.0.0.1:102: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
[0m[1;34m2024-09-10 23:21:21.341 [I] [visitor/visitor_manager.go:89] [1e2bc86bd1e6586e] try to start visitor [p2p_siemens_visitor]
[0m[1;33m2024-09-10 23:21:21.342 [W] [visitor/visitor_manager.go:118] [1e2bc86bd1e6586e] start error: listen tcp 127.0.0.1:102: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
[0m[1;34m2024-09-10 23:21:31.342 [I] [visitor/visitor_manager.go:89] [1e2bc86bd1e6586e] try to start visitor [p2p_siemens_visitor]
[0m[1;33m2024-09-10 23:21:31.342 [W] [visitor/visitor_manager.go:118] [1e2bc86bd1e6586e] start error: listen tcp 127.0.0.1:102: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
[0m[1;34m2024-09-10 23:21:41.342 [I] [visitor/visitor_manager.go:89] [1e2bc86bd1e6586e] try to start visitor [p2p_siemens_visitor]
[0m[1;33m2024-09-10 23:21:41.342 [W] [visitor/visitor_manager.go:118] [1e2bc86bd1e6586e] start error: listen tcp 127.0.0.1:102: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
[0m[1;34m2024-09-10 23:21:51.342 [I] [visitor/visitor_manager.go:89] [1e2bc86bd1e6586e] try to start visitor [p2p_siemens_visitor]
[0m[1;33m2024-09-10 23:21:51.342 [W] [visitor/visitor_manager.go:118] [1e2bc86bd1e6586e] start error: listen tcp 127.0.0.1:102: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
[0m[1;34m2024-09-10 23:22:01.341 [I] [visitor/visitor_manager.go:89] [1e2bc86bd1e6586e] try to start visitor [p2p_siemens_visitor]
[0m[1;33m2024-09-10 23:22:01.341 [W] [visitor/visitor_manager.go:118] [1e2bc86bd1e6586e] start error: listen tcp 127.0.0.1:102: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
[0m[1;34m2024-09-10 23:22:11.342 [I] [visitor/visitor_manager.go:89] [1e2bc86bd1e6586e] try to start visitor [p2p_siemens_visitor]
[0m[1;33m2024-09-10 23:22:11.342 [W] [visitor/visitor_manager.go:118] [1e2bc86bd1e6586e] start error: listen tcp 127.0.0.1:102: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
[0m

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Duplicate issue
