### ISSUE TITLE
端口被占用，怎么解决

### ISSUE THREAD

**Issue by gongjianfeng1982** [fatedier/frp#4429]
### Bug Description

A地址:frpc（name = "p2p_siemens"）电脑连接现场的设备192.168.8.8
服务器:frps 创建server地址1.1.1.1
B地址:frpc（name = "p2p_siemens_visitor"）工程电脑连接远程设备192.168.8.8
工控电脑专业软件，不能修改ip为127.0.0.1，不能修改端口，固定端口102.
不知道这个问题怎么解决，普通的tcp可以连接上，但是中转会造成流量问题，我想通过xtcp直连。
请高手帮忙想个办法吗？

### frpc Version

0.6

### frps Version

0.6

### System Architecture

windows10

### Configurations

[[proxies]] # siemens server -> resmon.exe | netstat.exe -aon
localIP = "192.168.8.8"
localPort = 102
name = "p2p_siemens"
secretKey = "xyz9527"
type = "xtcp"

[[visitors]] # siemens client -> resmon.exe | netstat.exe -aon 停止102服务 Siemens S7DOS Help Service
bindAddr = "127.0.0.1"
bindPort = 102
name = "p2p_siemens_visitor"
secretKey = "xyz9527"
serverName = "p2p_siemens"
type = "xtcp"

### Logs

![image](https://github.com/user-attachments/assets/8bab1829-782b-4d00-a19e-5c50722c4b86)

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
无法解决，可以使用其他 VPN 类软件。
