### ISSUE TITLE
心跳为什么中断链接  关闭心跳也会中断

### ISSUE THREAD

**Issue by Jianfei-DinG** [fatedier/frp#4432]
### Bug Description

心跳为什么中断链接  关闭心跳也会中断，开启心跳会 根据心跳时间断开 关闭心跳会 长时间断开 但是 重启服务器 或者客户端 又正常 远程桌面特别 不友好 不是知道 怎么才能 爽快的使用

### frpc Version

60

### frps Version

60

### System Architecture

x86

### Configurations

# frpc.toml

[common]
server_addr = "47.243.108.30"
server_port = 7000
token = "f9e7d334a60c974cdf39b8a57007d921"

[rdps]
type = "tcp"
local_ip = "127.0.0.1"
local_port = 3389
remote_port = 6002

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
心跳需要，frpc 和 frps 使用相同的值

**Comment by Jianfei-DinG** [comment]
> 心率需要，frpc 和 frps 使用相同的值

frpc 也要配置 心跳吗  怎么配置

**Comment by xqzr** [comment]
> > 心率需要，frpc 和 frps 使用相同的值
> 
> frpc 也要配置 心跳吗 怎么配置

https://gofrp.org/zh-cn/docs/reference/client-configures/#ClientTransportConfig

**Comment by superzjg** [comment]
60版本默认是关闭心跳的，采用tcpmux内置心跳，默认无需配置，使用没有问题。
另尝试采用 toml 版本格式重写配置试试。
