### ISSUE TITLE
[Feature Request] Can load balancing support more strategies like weighted round robin?

### ISSUE THREAD

**Issue by rty813** [fatedier/frp#4435]
### Describe the feature request

Currently, the load balancing strategy only supports round-robin. Is there any consideration to add more strategies?

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
This is a low-priority long-term plan that will not be realized in the short term.

**Comment by rty813** [comment]
Looking forward to this feature
