### ISSUE TITLE
iStore安装的frps插件，打开管理界面失败，请问如何处理？

### ISSUE THREAD

**Issue by wuyang911** [fatedier/frp#4437]
### Bug Description

iStore安装的frps插件，打开管理界面失败，请问如何处理？

### frpc Version

0.53.2

### frps Version

0.53.2

### System Architecture

openwrt

### Configurations

![1d32153d20200af8e80137fc92234da](https://github.com/user-attachments/assets/ae788467-a783-4ef7-aa9d-5ebb60643bf5)
![06e508342a722211273b94a951892f5](https://github.com/user-attachments/assets/e4d92509-e530-4cf3-ad7b-c621a88af707)

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
这可能 luci 插件的问题，要找 luci 的作者。
这个库是 frp 的作者，不管第三方 luci 的。 

ps：若你的wrt固件是基于 lua api的，可以尝试我改过的luci：https://www.right.com.cn/forum/thread-8268923-1-1.html
