### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HRNasr** [fatedier/frp#4438]
### Describe the feature request

What is the difference between this project and the following project in performance? Is it possible to compare?
https://github.com/mosn/mosn

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
I'm not very sure about other projects, but I think that frp is different from general-purpose proxies; it focuses on solving scenarios and issues in a specific domain.
