### ISSUE TITLE
配置文件格式

### ISSUE THREAD

**Issue by Jianfei-DinG** [fatedier/frp#4441]
### Describe the feature request

![image](https://github.com/user-attachments/assets/96d8c9de-bd19-46f0-92b5-7cfd466b437c)

### Describe alternatives you've considered

我在文档中 查看的配置 为什么是无法链接的
比如在 frpc.toml里的下面配置就是无法链接的
serverAddr = "x.x.x.x"
serverPort = 7000
换成
server_addr = "x.x.x.x"
server_port = 7000
就正常链接，我不清楚  问题在那里 在在很多 配置里有的功能 写了 但是也好像没生效，能规范一下 吗 

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
> 能规范一下 吗

不能，要保留兼容性

你可能在头部添加了 `[common]` 删除它，即可与文档匹配

**Comment by Jianfei-DinG** [comment]
> > 能规范一下吗
> 
> 不能，要保留兼容性
> 
> 你可以在头部添加`[common]`删除它，即可与文档匹配

我删除了 就是这种改成和这个一样的就是连接不上 服务器可以 客户端改成这样就连不上
![image](https://github.com/user-attachments/assets/3f2e0a3b-136b-4fcf-a19d-5badbfa5b30c)

**Comment by xqzr** [comment]
> > > 能规范一下吗
> > 
> > 
> > 不能，要保留兼容性
> > 你可以在头部添加`[common]`删除它，即可与文档匹配
> 
> 我删除了 就是这种改成和这个一样的就是连接不上 服务器可以 客户端改成这样就连不上 ![image](https://private-user-images.githubusercontent.com/96579381/367576888-3f2e0a3b-136b-4fcf-a19d-5badbfa5b30c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzU2OTEsIm5iZiI6MTcyNjQ3NTM5MSwicGF0aCI6Ii85NjU3OTM4MS8zNjc1NzY4ODgtM2YyZTBhM2ItMTM2Yi00ZmNmLWExOWQtNWJhZGJmYTViMzBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA4Mjk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNjUxMDgyMWQ1MTJkMGNjZjMxMGYwZDM1YzBiYmIxNGNhMDE0ZThhMzgzODZhN2Q3NGQ1MDc5MDFlNjdiYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A5NKfKQwnsP3SbUAfl6ewqsnQHWEsV4kyvgxiGj29EE)

如果，配置文件扩展名是 `.ini`，可以尝试改为 `.toml`

**Comment by superzjg** [comment]
一般是格式错，只要有一个不对就会报错。你可以把 frps 和 frpc 双方的完整配置文件贴出来，看看。

**Comment by fatedier** [comment]
请先完全按照文档提供的内容进行测试，如果确认是 bug，请按照 bug 反馈，并提供详细的配置信息和报错内容。
