### ISSUE TITLE
Frp https proxy fail

### ISSUE THREAD

**Issue by kun-guo** [fatedier/frp#4442]
### Bug Description
frp https  proxy failed, cause: [vhost/vhost.go:218] http request for host [] path [] httpUser [] not found
**frp server log:**
![截屏2024-09-15 15 10 55](https://github.com/user-attachments/assets/4fecbd5a-a15c-4c77-930a-6da4d2e992ec)

**dashboard**
![截屏2024-09-15 15 17 38](https://github.com/user-attachments/assets/64480893-bbce-4b38-86f2-06d9b429f723)

### frpc Version

0.59.0

### frps Version

0.60.0

### System Architecture

linux/amd64

### Configurations

```tom
# frps.toml
bindPort = 20000 							
auth.token = "token value" 		 
vhostHTTPSPort =443

# Server Dashboard，可以查看frp服务状态以及统计信息
webServer.addr = "0.0.0.0"		# 后台管理地址
webServer.port = 7001 			  # 后台管理端口
webServer.user = "admin"		  # 后台登录用户名
webServer.password = "password"	# 后台登录密码
```

```tom
# frpc.toml
serverAddr = "118.92.19.12"
serverPort = 20000
auth.token = "xxxxx"
log.level = "debug"

# https
[[proxies]]
name = "my-https"
type = "https"
customDomains = ["118.92.19.12"]

[proxies.plugin]
type = "https2http"
localAddr = "127.0.0.1:80"

# HTTPS 证书相关的配置
crtPath = "/etc/frp/certs/server.crt"
keyPath = "/etc/frp/certs/server.key"
hostHeaderRewrite = "127.0.0.1"
requestHeaders.set.x-from-where = "frp"
```

**SSL 证书使用公网 IP 自签名证书**

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Jianfei-DinG** [comment]
你这个能正常链接吗？# frpc.toml
serverAddr = "118.92.19.12"
serverPort = 20000
auth.token = "xxxxx"
log.level = "debug"

我用这种serverAddr  就连接不上

**Comment by xqzr** [comment]
不支持。
`type = "https"` 需要读取 SNI

**Comment by superzjg** [comment]
是不是 vhostHTTPSPort =443 的问题，换个端口号试试，国内很多时候443用不了，被限制。

**Comment by fatedier** [comment]
In general, please use the domain name to access https.
