### ISSUE TITLE
我希望能增加一种鉴权方式。通过注册用户的方式让frps允许frpc连接。

### ISSUE THREAD

**Issue by wiseforever** [fatedier/frp#4443]
### Describe the feature request

# 希望能增加一种鉴权方式

## 痛点
目前的鉴权方式，可选值为 token 或 oidc，默认为 token。<br>
但是 token 属于是 frps 将其参数固定，不利于多设备之间的管理。

### 具体逻辑
```
    通过注册一个账号、密码去保存 frps 允许的 frpc 设备。在 frps 中将 frpc 注册的账户与密码等数据加密，然后将加密数据（比如一串不可逆的hash）上传给到 frps ，frps 需要指定一个文件保存 frpc 注册的账户信息的加密数据。
 
    frpc 在运行的时候同样将账号、密码写在 toml 配置文件中。frpc 程序需要对 toml 文件中的账户、密码加密后上传给 frps，frps 在对比加密后的 hash 值与保存的 hash 作对比。对比通过则允许连接。
```

### Describe alternatives you've considered

# 希望能增加一种鉴权方式

## 痛点
目前的鉴权方式，可选值为 token 或 oidc，默认为 token。<br>
但是 token 属于是 frps 将其参数固定，不利于多设备之间的管理。

### 具体逻辑
```
    通过注册一个账号、密码去保存 frps 允许的 frpc 设备。在 frps 中将 frpc 注册的账户与密码等数据加密，然后将加密数据（比如一串不可逆的hash）上传给到 frps ，frps 需要指定一个文件保存 frpc 注册的账户信息的加密数据。
 
    frpc 在运行的时候同样将账号、密码写在 toml 配置文件中。frpc 程序需要对 toml 文件中的账户、密码加密后上传给 frps，frps 在对比加密后的 hash 值与保存的 hash 作对比。对比通过则允许连接。
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by cfei0926** [comment]
> 降低版本使用了插件
具体用了什么版本，我一直返回为空
