### ISSUE TITLE
frpc是否支持通过frps上面统一配置管理

### ISSUE THREAD

**Issue by maojianyou** [fatedier/frp#4444]
目前frpc上面配置都得手工进行配置，如果frpc多了，那么管理起来会非常麻烦，后续能否开发经过frps进行统一管理下发配置，实现frpc一键自动上线，然后frps统一管控，方便管理维护

还有其它2种场景，出现故障后的情况
场景1、是否支持，同一个区域，比如有frpc 1 frpc 2 frpc 3  3台，然后配置相同，端口也相同，去连frps，如果frpc 1挂了，自动切换到frpc 2 这样实现故障迁移，而不用端口改来改去，方便访问frps 前端的端口不变；
场景2、是否支持同一个frpc 比如同时连frps1  frps2  ，如果frps1挂了，自动故障切换到frps2，端口同样不变，如果frps使用的域名，就可以实现更改域名改A记录,实现故障无缝切换，使用者不需要更换任何配置；
针对场景1、跟场景2是否可以实现

**Comment by superzjg** [comment]
要支持肯定是可以实现的，但大部分人用不到的话，作者一般会忽略，毕竟是开源项目。
若是刚需，可联系作者询问是否有付费定制途径。

**Comment by TheWorldIsNot** [comment]
或许可以自己通过脚本监测

**Comment by xqzr** [comment]
1、https://gofrp.org/zh-cn/docs/features/common/load-balancer/
2、多开

**Comment by xqzr** [comment]
> 目前frpc上面配置都得手工进行配置，如果frpc多了，那么管理起来会非常麻烦，后续能否开发经过frps进行统一管理下发配置，实现frpc一键自动上线，然后frps统一管控，方便管理维护

作者不希望 frps 控制 frpc。
可以映射 Admin UI
https://gofrp.org/zh-cn/docs/features/common/ui/#%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%AE%A1%E7%90%86%E7%95%8C%E9%9D%A2

**Comment by ldw4033** [comment]
> > 目前frpc上面配置都得手工进行配置，如果frpc多了，那么管理起来会非常麻烦，后续能否开发经过frps进行统一管理下发配置，实现frpc一键自动上线，然后frps统一管控，方便管理维护
> 
> 作者不希望 frps 控制 frpc。 可以映射 Admin UI https://gofrp.org/zh-cn/docs/features/common/ui/#%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%AE%A1%E7%90%86%E7%95%8C%E9%9D%A2

其实我有个疑问哈，那服务端如何主动关闭这个客户端呢？比如：我给某台机器安装了 frpc后给了其他人用，后来我想删除这台机器，不允许他连接frps ，那是不是就还得去frpc 那台机器主动删除？

**Comment by superzjg** [comment]
> > > 目前frpc上面配置都得手工进行配置，如果frpc多了，那么管理起来会非常麻烦，后续能否开发经过frps进行统一管理下发配置，实现frpc一键自动上线，然后frps统一管控，方便管理维护
> > 
> > 
> > 作者不希望 frps 控制 frpc。 可以映射 Admin UI https://gofrp.org/zh-cn/docs/features/common/ui/#%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%AE%A1%E7%90%86%E7%95%8C%E9%9D%A2
> 
> 其实我有个疑问哈，那服务端如何主动关闭这个客户端呢？比如：我给某台机器安装了 frpc后给了其他人用，后来我想删除这台机器，不允许他连接frps ，那是不是就还得去frpc 那台机器主动删除？

目前可以改 `bindPort`、`auth.token`、`quicBindPort`、`vhostHTTPPort`、`vhostHTTPSPort`，让frpc连不上，若 frpc 有 `remotePort`，也可在 frps 所在服务器的防火墙禁用此端口的数据通过。

**Comment by xqzr** [comment]
> > > 目前frpc上面配置都得手工进行配置，如果frpc多了，那么管理起来会非常麻烦，后续能否开发经过frps进行统一管理下发配置，实现frpc一键自动上线，然后frps统一管控，方便管理维护
> > 
> > 
> > 作者不希望 frps 控制 frpc。 可以映射 Admin UI https://gofrp.org/zh-cn/docs/features/common/ui/#%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%AE%A1%E7%90%86%E7%95%8C%E9%9D%A2
> 
> 其实我有个疑问哈，那服务端如何主动关闭这个客户端呢？比如：我给某台机器安装了 frpc后给了其他人用，后来我想删除这台机器，不允许他连接frps ，那是不是就还得去frpc 那台机器主动删除？

可以使用“服务端插件” https://gofrp.org/zh-cn/docs/features/common/server-plugin/
