### ISSUE TITLE
unknown visitor type http

### ISSUE THREAD

**Issue by hemna** [fatedier/frp#4446]
### Bug Description

Trying to launch frpc and expose an http port fails.

### frpc Version

0.60.0

### frps Version

0.60.0

### System Architecture

linux/amd64 and linux/arm64

### Configurations

```
# frpc.toml
serverAddr = "x.x.x.x"
serverPort = 7000

[[visitors]]
name = "Home Dev visitor"
type = "http"
serverName = "something here"
bindAddr = "0.0.0.0"
bindPort = 9110
```

### Logs

```└─> ./frpc -c frpc.toml
unknown visitor type: http
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [X] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Please check the document; visitors only support stcp, sudp, and xtcp.
