### ISSUE TITLE
[E] [service.go:293] user错误，您的usertoken可能已被刷新。 

### ISSUE THREAD

**Issue by zhaochb** [fatedier/frp#4448]
### Describe the feature request

确认Token是和网站上一致的，但是运行frpc时发生了“user错误，您的usertoken可能已被刷新。 “的报错。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Please seek help from the source where you obtained the software.
