### ISSUE TITLE
[Feature Request]  客户端为何不显示visitors的结果？

### ISSUE THREAD

**Issue by sunshe35** [fatedier/frp#4449]
### Describe the feature request

我在客户端有一个visitors配置，如下：
```
[[visitors]]
name = "visitor_xxx"
type = "stcp"
# stcp 的访问者
# 要访问的 stcp 代理的名字
serverName = "name"
secretKey = "key"
# 绑定本地端口用于使用socks5服务
bindAddr = "0.0.0.0"
bindPort = 11080
```
打开客户端的  loclahost:7402，其他类型都正常，就是visitors无法显示，实际结果是连接正常的。通过netstat可以查看端口已经启动。
```
(base) PS C:\Users\sunshe35> NETSTAT.EXE -ant |findstr 1108
  TCP    0.0.0.0:11080          0.0.0.0:0              LISTENING       InHost
  TCP    0.0.0.0:11081          0.0.0.0:0              LISTENING       InHost
  TCP    [::]:11080             [::]:0                 LISTENING       InHost
  TCP    [::]:11081             [::]:0                 LISTENING       InHost
```

为什么不搞个ui显示visitors的连接情况呢？比如说连接的状态，绑定的ip以及端口，毕竟客户端使用应该不涉及隐私和安全问题。

### Describe alternatives you've considered

目前只能通过netstat等命令查看visitors端口是否启动。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
估计是因为 visitors 是连接的 frps，所以只在 frps 那边显示。
不过 frps 只在 Overview 显示一个 Client Counts 的计数变化，无法显示具体哪个代理的 visitors 正在访问，倒是可以改进一下。

**Comment by sunshe35** [comment]
> 估计是因为 visitors 是连接的 frps，所以只在 frps 那边显示。 不过 frps 只在 Overview 显示一个 Client Counts 的计数变化，无法显示具体哪个代理的 visitors 正在访问，倒是可以改进一下。

visitors有绑定的ip 和port啊，主要需要了解以下信息。
- 绑定的是ip和port；
- name；
- 连接状态。

这些在客户端应该都能有数据，而且对于本地来说，不存在隐私泄漏问题。
要不然每次都抓瞎，不知道咋回事儿。我要不断的测试端口，测试客户frp运行，测试stcp那一侧frp运行。

**Comment by superzjg** [comment]
> > 估计是因为 visitors 是连接的 frps，所以只在 frps 那边显示。 不过 frps 只在 Overview 显示一个 Client Counts 的计数变化，无法显示具体哪个代理的 visitors 正在访问，倒是可以改进一下。
> 
> visitors有绑定的ip 和port啊，主要需要了解以下信息。
> 
> * 绑定的是ip和port；
> * name；
> * 连接状态。
> 
> 这些在客户端应该都能有数据，而且对于本地来说，不存在隐私泄漏问题。 要不然每次都抓瞎，不知道咋回事儿。我要不断的测试端口，测试客户frp运行，测试stcp那一侧frp运行。

你没发现这些信息都会在 frps 的日志查看到，从目前的架构来看，visitors 连接的是 frps，而不是另一端的 frpc，所以 frpc 那边没有任何日志或信息显示。
