### ISSUE TITLE
如何把URL路由到另外一个设备

### ISSUE THREAD

**Issue by zdfzdfzdfz** [fatedier/frp#445]
我遇到的需求是这样的，不知道目前frp能否实现，如何配置？
1、frps架设在有公网IP的服务器上。
2、frpc在内网的一台机器上，内网其他设备有需要被访问的资源（这些设备不能安装frpc或者不想安装frpc）
3、想达到的目的就是如何访问内网其他设备上的资源（例如http  或 https）
能否实现，如何配置？
这样可以得话，可以实现一台设备运行frpc，和这台设备同网段的其他设备就可以被访问，比如可以访问猫、路由器的配置页面，直接更改配置。

望答复，谢谢！

**Comment by fatedier** [comment]
搜一下之前的 issue，关键字 `local_ip`。
