### ISSUE TITLE
HTTPS证书文件读取不到

### ISSUE THREAD

**Issue by Gabriel-six** [fatedier/frp#4452]
### Bug Description

客户端配置https服务的证书，日志显示：Start error: gen TLS config error: open ./ssl/server.crt: no such file or directory。但在相应目录下确实有这个文件存在，而且key文件的读取是没有报错的。

### frpc Version

0.6

### frps Version

0.6

### System Architecture

debian/arm

### Configurations

frpc为1panel管理面板安装的docker应用

### Logs

start error: gen TLS config error: open ./ssl/server.crt: no such file or directory。

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
这不就是找不到文件吗，确认文件存在且是正确的，然后使用绝对路径试试。

**Comment by Gabriel-six** [comment]
> 这不就是找不到文件吗，确认文件存在且是正确的，然后使用绝对路径试试。

您好，已经确认文件存在且正确，是从cloudflare申请的证书，复制证书和密钥文本到txt文件后改后缀为.crt和.key，且这两个文件在其它服务上传后都识别正常，所以确定证书文件没有问题。

以下为配置代码段：

[[proxies]]
name = "blog_https"
type = "https"
customDomains = ["www.domain.com"]

[proxies.plugin]
type = "https2http"
localAddr = "127.0.0.1:8090" 

keyPath = "/opt/1panel/apps/frpc/frpc/data/ssl/server.key"
crtPath = "/opt/1panel/apps/frpc/frpc/data/ssl/server.crt"

hostHeaderRewrite = "127.0.0.1"
requestHeaders.set.x-from-where = "frp"

关于证书与密钥的路径，相对路径与绝对路径都已经尝试，报错都为Start error：gen TLS config error，open xxxxxxx, no such file or directory

实在是找不到什么原因，在网上查找也没有找到其他人有遇到这种情况

**Comment by H14467** [comment]
我一模一样的问题，ssh都配置好了，就是一直读取不到ssl文件，你解决了吗

**Comment by Gabriel-six** [comment]
> 我一模一样的问题，ssh都配置好了，就是一直读取不到ssl文件，你解决了吗

还没有解决，昨天搞到凌晨，翻遍全网无果，无奈来提交issue了哈哈。我也是tcp和http都穿透正常了，就是配置这个证书的时候出现了错误，无法读取证书文件。

请问你的证书和密钥是从哪个服务商处获得的？

**Comment by H14467** [comment]
我是直接阿里里面申请的，也是昨天晚上翻遍全网无果，打算来这碰碰运气，一进来就看到你提了这个问题

**Comment by H14467** [comment]
我觉得应该不是证书问题吧，最关键的是我看全网都没有这个问题，还有就是要么都是用的低版本的，没有参考价值，好多都是21年20年的了

**Comment by Gabriel-six** [comment]
> 我觉得应该不是证书问题吧，最关键的是我看全网都没有这个问题，还有就是要么都是用的低版本的，没有参考价值，好多都是21年20年的了

版本或许确实是个问题，我没有尝试更低版本，因为我这边frpc是通过1panel面板的应用商店安装的，商店最低只提供0.59版本。

http2https这个功能好像用到的人并不多，或许该功能缺少维护。

蹲一波大佬来解答一下哈哈

**Comment by H14467** [comment]
的确是，我用的宝塔的docker来配置的，他提供了58和59版本，不过我没有去试，我看网上的教程全是http，估计和使用人群少也有关系
蹲一波吧

**Comment by H14467** [comment]
我都加群里，去问一下群里面大佬们咋说吧

**Comment by Gabriel-six** [comment]
> 我都加群里，去问一下群里面大佬们咋说吧

好的，等你好消息。我也再查找一下

**Comment by H14467** [comment]
我看群里大佬说的docker部署，可能是没有映射的原因

**Comment by H14467** [comment]
frp容器要映射证书文件

**Comment by H14467** [comment]
你证书文件做了映射没啊

**Comment by Gabriel-six** [comment]
> 你证书文件做了映射没啊

我的证书文件就是放在与frpc.toml同级的目录下，这应该不需要再映射了呀。

**Comment by H14467** [comment]
额，不知道额，我现在还在外面，还没去试，你要不也去群里问问，哈哈哈哈

**Comment by Gabriel-six** [comment]
> 额，不知道额，我现在还在外面，还没去试，你要不也去群里问问，哈哈哈哈

可以哈哈，麻烦分享一下群号

**Comment by H14467** [comment]
949022145

**Comment by superzjg** [comment]
> > 这不就是找不到文件吗，确认文件存在且是正确的，然后使用绝对路径试试。
> 
> 您好，已经确认文件存在且正确，是从cloudflare申请的证书，复制证书和密钥文本到txt文件后改后缀为.crt和.key，且这两个文件在其它服务上传后都识别正常，所以确定证书文件没有问题。
> 
> 以下为配置代码段：
> 
> [[proxies]] name = "blog_https" type = "https" customDomains = ["www.domain.com"]
> 
> [proxies.plugin] type = "https2http" localAddr = "127.0.0.1:8090"
> 
> keyPath = "/opt/1panel/apps/frpc/frpc/data/ssl/server.key" crtPath = "/opt/1panel/apps/frpc/frpc/data/ssl/server.crt"
> 
> hostHeaderRewrite = "127.0.0.1" requestHeaders.set.x-from-where = "frp"
> 
> 关于证书与密钥的路径，相对路径与绝对路径都已经尝试，报错都为Start error：gen TLS config error，open xxxxxxx, no such file or directory
> 
> 实在是找不到什么原因，在网上查找也没有找到其他人有遇到这种情况

测试一波 OpenSSL 自签名证书试试，若自签名证书可以，那可能是frp与证书不兼容？参考：
https://gofrp.org/zh-cn/docs/features/common/network/network-tls/

**Comment by Gabriel-six** [comment]
> > > 这不就是找不到文件吗，确认文件存在且是正确的，然后使用绝对路径试试。
> > 
> > 
> > 您好，已经确认文件存在且正确，是从cloudflare申请的证书，复制证书和密钥文本到txt文件后改后缀为.crt和.key，且这两个文件在其它服务上传后都识别正常，所以确定证书文件没有问题。
> > 以下为配置代码段：
> > [[proxies]] name = "blog_https" type = "https" customDomains = ["www.domain.com"]
> > [proxies.plugin] type = "https2http" localAddr = "127.0.0.1:8090"
> > keyPath = "/opt/1panel/apps/frpc/frpc/data/ssl/server.key" crtPath = "/opt/1panel/apps/frpc/frpc/data/ssl/server.crt"
> > hostHeaderRewrite = "127.0.0.1" requestHeaders.set.x-from-where = "frp"
> > 关于证书与密钥的路径，相对路径与绝对路径都已经尝试，报错都为Start error：gen TLS config error，open xxxxxxx, no such file or directory
> > 实在是找不到什么原因，在网上查找也没有找到其他人有遇到这种情况
> 
> 测试一波 OpenSSL 自签名证书试试，若自签名证书可以，那可能是frp与证书不兼容？参考： https://gofrp.org/zh-cn/docs/features/common/network/network-tls/

好的我了解一下啊这个，对openssl不是很懂，谢谢

**Comment by xqzr** [comment]
> apps/**frpc/frpc**/data

出现两次 **frpc**，确定？

**Comment by Gabriel-six** [comment]
> > apps/**frpc/frpc**/data
> 
> 出现两次 **frpc**，确定？

是的，文件路径就是如此。而且之前用相对路径也是同样报错。

**Comment by Gabriel-six** [comment]
> > > 这不就是找不到文件吗，确认文件存在且是正确的，然后使用绝对路径试试。
> > 
> > 
> > 您好，已经确认文件存在且正确，是从cloudflare申请的证书，复制证书和密钥文本到txt文件后改后缀为.crt和.key，且这两个文件在其它服务上传后都识别正常，所以确定证书文件没有问题。
> > 以下为配置代码段：
> > [[proxies]] name = "blog_https" type = "https" customDomains = ["www.domain.com"]
> > [proxies.plugin] type = "https2http" localAddr = "127.0.0.1:8090"
> > keyPath = "/opt/1panel/apps/frpc/frpc/data/ssl/server.key" crtPath = "/opt/1panel/apps/frpc/frpc/data/ssl/server.crt"
> > hostHeaderRewrite = "127.0.0.1" requestHeaders.set.x-from-where = "frp"
> > 关于证书与密钥的路径，相对路径与绝对路径都已经尝试，报错都为Start error：gen TLS config error，open xxxxxxx, no such file or directory
> > 实在是找不到什么原因，在网上查找也没有找到其他人有遇到这种情况
> 
> 测试一波 OpenSSL 自签名证书试试，若自签名证书可以，那可能是frp与证书不兼容？参考： https://gofrp.org/zh-cn/docs/features/common/network/network-tls/

您好，我已经使用openssl对我的域名自签发了证书，但是依然出现找不到文件的报错。或许只是frp程序中关于证书读取的代码有些问题。

另外想请教一下，自签名证书是对所用的域名来签发吗，而不是为客户端的本地ip签发？

**Comment by superzjg** [comment]
我刚刚用路由器测试了，自签名证书，v0.60.0版，读取证书没问题啊，不过浏览器告警（因为没有根证书），忽略后可以浏览网站。配置文件故意配置成与你差不多，不过不是docker环境，如下：
`serverAddr = "superzjg.xxxx.xx"
serverPort = 53413
loginFailExit = false
auth.token = "xxxxxx"
log.to = "/var/log/frpc.log"
transport.tls.disableCustomTLSFirstByte = false

[[proxies]]
name = "test"
type = "https"
customDomains = ["superzjg.xxxx.xx"]
[proxies.plugin]
type = "https2http"
localAddr = "127.0.0.1:53422"
crtPath = "/etc/sky/skyself.crt"
keyPath = "/etc/sky/skyself.key"
hostHeaderRewrite = "127.0.0.1"
requestHeaders.set.x-from-where = "frp"`

**Comment by Gabriel-six** [comment]
> 我刚刚用路由器测试了，自签名证书，v0.60.0版，读取证书没问题啊，不过浏览器告警（因为没有根证书），忽略后可以浏览网站。配置文件故意配置成与你差不多，不过不是docker环境，如下：
> 
> serverAddr = "superzjg.xxxx.xx" serverPort = 53413 loginFailExit = false auth.token = "xxxxxx" log.to = "/var/log/frpc.log" transport.tls.disableCustomTLSFirstByte = false
> 
> [[proxies]] name = "test" type = "https" customDomains = ["superzjg.xxxx.xx"] [proxies.plugin] type = "https2http" localAddr = "127.0.0.1:53422" crtPath = "/etc/sky/skyself.crt" keyPath = "/etc/sky/skyself.key" hostHeaderRewrite = "127.0.0.1" requestHeaders.set.x-from-where = "frp"

感谢您的测试，那现在看来我这里唯一与您不一样的就是docker环境了，可能我要不通过docker直接运行frpc试一下

**Comment by wuai1024** [comment]
文件路径没错的情况下，检查下是否映射目录到docker里了。可以直接进入容器里面，查看一下证书文件是否存在。

**Comment by xqzr** [comment]
可能是 SELinux

**Comment by soonxf** [comment]
keyPath = "/opt/1panel/apps/frpc/frpc/data/ssl/server.key"
crtPath = "/opt/1panel/apps/frpc/frpc/data/ssl/server.crt"

这两个配置项看着是宿主机的目录,你应该改为 docker 的内部目录 默认的应该是 /etc/frp 这个路径,找到对应的证书路径

**Comment by Gabriel-six** [comment]
> keyPath = "/opt/1panel/apps/frpc/frpc/data/ssl/server.key" crtPath = "/opt/1panel/apps/frpc/frpc/data/ssl/server.crt"
> 
> 这两个配置项看着是宿主机的目录,你应该改为 docker 的内部目录 默认的应该是 /etc/frp 这个路径,找到对应的证书路径

好的，谢谢指出

**Comment by yjhdlut** [comment]
像映射frpc.toml,文件一样，把证书的外部储存地址，映射进入docker里面。然后frpc.toml,里面填docker 容器里面的地址如：/etc/frp/server.key和 /etc/frp/server.crt

**Comment by Gabriel-six** [comment]
> 像映射frpc.toml,文件一样，把证书的外部储存地址，映射进入docker里面。然后frpc.toml,里面填docker 容器里面的地址如：/etc/frp/server.key和 /etc/frp/server.crt

感谢解答，当时刚接触docker，可能对宿主机和容器的地址映射这块不熟悉，很多配置都有问题

**Comment by yjhdlut** [comment]
客气
