### ISSUE TITLE
[Feature Request] How to modify the default prompt when the frp reverse proxy site with HTTP is not working properly. 

### ISSUE THREAD

**Issue by esbaidu** [fatedier/frp#4453]
### Describe the feature request

How to modify the default prompt when the frp reverse proxy site with HTTP is not working properly. 
The default prompt is:
![QQ浏览器截图20240923202328](https://github.com/user-attachments/assets/76b05804-531e-4683-9c1d-696ffb702160)

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/blob/fe4ca1b54e9045ea91ffa4645ac8f39bb2e770ef/conf/frps_full_example.toml#L136
