### ISSUE TITLE
[Feature Request] frp xtpc模式是不是对bbr不生效

### ISSUE THREAD

**Issue by onthehide288** [fatedier/frp#4454]
### Describe the feature request

最近我们地区跨网降速了，nas是公网直接对接，nas传文件传不动，尝试了本地开启bbr之后再向目标机器发送文件，提速非常明显
而目前本地机器和目标机器的远程连接为了安全性，用的是frp xtcp模式链接，本地frpc客户端的debian开启了bbr，但是速度并没有任何区别，是不是xtcp打洞之后是tcp udp混合模式，所以bbr就没效了

这方面会有优化的可能性吗

**Comment by xqzr** [comment]
是
如果 frp 实现 QUIC 的 BBR...
