### ISSUE TITLE
[Feature Request] frp的http3是怎么设置的？

### ISSUE THREAD

**Issue by ylgod** [fatedier/frp#4461]
### Describe the feature request

我一直以为quic端口监听就可以实现http3，后来我问了别人才知道frp本身还不支持http3.是这样吗？
还是说我的设置不对。

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
> quic端口监听就可以实现http3

不可以

**Comment by fatedier** [comment]
目前不支持。

**Comment by ylgod** [comment]
> 目前不直接支持。
> 
> 但是因为基于 UDP，所以你可以通过 UDP 端口映射的方式来使用。

好的谢谢！找了好久没找到答案，一直以为quic链接就是支持http3，折腾了很久。。。哈哈哈！
