### ISSUE TITLE
[Feature Request] 希望不要改变X_FORWARDED_PROTO的值

### ISSUE THREAD

**Issue by DaPoHou** [fatedier/frp#4462]
### Describe the feature request

这两天把frp升级到了0.60（之前一直用的0.36.2)，我是使用公网nginx 通过https ---> frp --->内网http服务。很多正常的链接都无法访问，通过排查发现是公网nginx中的HTTP_X_FORWARDED_PROTO原为https，通过frp被修改为了http。
而在之前的版本都是没有被修改的，正常的。
希望新版本不要修改HTTP_X_FORWARDED_PROTO，继续保留公网nginx传输的值。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
可以使用 `requestHeaders.set` 的配置主动覆盖设置一个值，这部分目前不支持自定义，未来会考虑。
