### ISSUE TITLE
[Feature Request] 链接动态库

### ISSUE THREAD

**Issue by Niculuse** [fatedier/frp#4464]
### Describe the feature request

是否有办法在编译时链接系统动态库以减少程序体积，比如在openwrt的路由器上使用，链接openwrt的动态库，减少体积？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by kkqy** [comment]
frp是golang开发的，golang编译的程序体积大是“通病”了，网上有很多相关讨论，大意是Go团队认为对于现在的硬件资源而言，静态链接导致空间占用并不是太大缺陷，但能换来部署方便，开箱即用等好处，不会因为依赖的各种库版本不对而导致程序异常，用空间换方便，是值得的。
而针对嵌入式环境，诞生了[TinyGo](https://github.com/tinygo-org/tinygo)项目，旨在生成体积更小的程序，遗憾的是TinyGo并没有完整实现Go的所有特性，所以就目前的情况，我不认为frp会为了缩小体积去针对TinyGo改造，更不会去为了缩小体积去改造Go的编译器。

**Comment by superzjg** [comment]
用楼上提到的 upx 压缩，openwrt 可以用，可以压缩到30~35%，运行时会先在 RAM 中解压，除了多占用 RAM，及解压时稍微慢一拍，没有其他影响，通过手动测试解压后与原来的md5相同。
