### ISSUE TITLE
[Feature Request] 可以添加一个 -install选项，这样就可以使用systemctl管理了

### ISSUE THREAD

**Issue by haotian2004** [fatedier/frp#4467]
### Describe the feature request

生成.service文件

### Affected area

- [X] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://gofrp.org/zh-cn/docs/setup/systemd/

**Comment by fatedier** [comment]
目前没有这样的计划。
