### ISSUE TITLE
auth_token 好像已经不起作用了

### ISSUE THREAD

**Issue by Xiaoli** [fatedier/frp#447]
服务器frp版本: frp_0.13.0_linux_amd64

frps.ini
`[common]
bind_port = 7000
vhost_http_port = 8008

subdomain_host = xxx.xxx2018.com

dashboard_port = 7500
# dashboard's username and password are both optional，if not set, default is admin.
dashboard_user = admin
dashboard_pwd = admin

log_file = ./frps.log
log_level = info

[f1.web]
auth_token = xxx.xxx2018

[f1.ssh]
auth_token = xxx.xxx2018`

客户端frp版本：frp_0.13.0_linux_arm

frpc.ini
`[common]
server_addr = xx.xx.xx.xx
server_port = 7000
auth_token = ff.2018

[f1.ssh]
local_port = 22
remote_port = 60001

[f1.web]
type = http
local_port = 8123
subdomain = f1`

通过在frps.ini和frpc.ini中用不匹配的auth_token，依然能顺利的创建f1.ssh和f1.web服务。

**Comment by zhfish** [comment]
看文档去。。只有一种token了

**Comment by Xiaoli** [comment]
从0.10.0开始，只有privilege_token了。服务器端和客户端的common中的privilege_token一致就能通过身份验证。
