### ISSUE TITLE
bindAddr 只能写127.0.0.1 吗

### ISSUE THREAD

**Issue by chenxudong2020** [fatedier/frp#4472]
### Bug Description

bindAddr 只能写127.0.0.1 吗

### frpc Version

0.60.0

### frps Version

0.60.0

### System Architecture

windows/amd64

### Configurations

bindAddr 只能写127.0.0.1 吗 如果网卡ipv4是 192.168.0.1 是否可以bindAddr写本地的ip地址 因为有些软件穿透之后绑定本地localhost说是不合法 

### Logs

1

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
默认0.0.0.0代表所有地址（含ipv6）。
指定地址也可以，一般指定公网地址，你指定一个内网地址，除了同在此内网的frpc能连，其他frpc都不能连接。

**Comment by chenxudong2020** [comment]
> 默认0.0.0.0代表所有地址（含ipv6）。 指定地址也可以，一般指定公网地址，你指定一个内网地址，除了同在此内网的frpc能连，其他frpc都不能连接。

p2p模式下 我可能忘记说条件了

**Comment by xqzr** [comment]
系统“可见”的地址，都可以写
