### ISSUE TITLE
建议FRP增加从数据库中读取记录的功能

### ISSUE THREAD

**Issue by Prisma-illya** [fatedier/frp#448]
建议frp新增从MySQL中读取记录的功能
举例：
服务端数据库中的记录是这样的：
`ID  localip     localport  type   customdomain         key`
`0   127.0.0.1  80            http    www.example.com  123456789`
`1   127.0.0.1  443          https  www.example.com   666666666`
客户端：
frpc --server frp.example.com:7000 --key 123456789
然后就开启映射 ID 0
也可以在配置文件中写入
[connect]
key=123456789;666666666;
开启映射ID 1、2......
这样还可以实现FRP商业化运作，或者是可以通过其他语言方便调用

**Comment by fatedier** [comment]
这种方式存在极大的安全隐患，我目前没有能力保证客户端和服务端没有漏洞或其他机制被别人利用，所以由服务端指定内网对外暴露的端口目前是不会考虑的。

这个机制就是相当于对外暴露了一扇窗，你无法预知服务端的行为是否会合理，是否安全，如果你只想暴露80端口，但是有人利用这一机制，暴露了你的 ssh 或者其他数据库端口，都存在安全隐患。
