### ISSUE TITLE
[Feature Request] remoteAdd bind to 127.0.0.1 only

### ISSUE THREAD

**Issue by richervip** [fatedier/frp#4480]
### Describe the feature request

Cloud I bind client service remote service port to 127.0.0.1 only or particular IP rather then 0.0.0.0 ?
I do not want to open this service to any.
for proxies example in frpc.tom.
[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000
remoteIP = "127.0.0.1"

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/dev/conf/frps_full_example.toml#L18

**Comment by lcharles123** [comment]
If I understand what you are requesting, you want to specify source address of frp server and client. It is possible, but only for TCP connections, UDP based connections do not work and you need to use a wrapper to call the frp client. 
The setting to specify bind addres on frp client is [ConnectServerLocalIP](https://github.com/fatedier/frp/blob/b14192a8d3bb5b5a844977ea82de9a7d87dbdf06/pkg/config/v1/client.go#L99) , you need to put it in general section of frpc config
transport.ConnectServerLocalIP = "IP_addr"

Also on the server there is a option bindAddr

**Comment by richervip** [comment]
This is my request.
Server IP  : private_ip: 127.0.0.1 ,  public_ip : 123.123.123.123

frpc.toml
[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 222
remoteIP = "127.0.0.1"          #client ssh bind to server IP 127.0.0.1 only

[[proxies]]
name = "web"
type = "tcp"
localIP = "127.0.0.1"
localPort = 80
remotePort = 80
remoteIP = "123.123.123.123"  #client  web bind to server IP 123.123.123.123 only

**Comment by fatedier** [comment]
> This is my request. Server IP : private_ip: 127.0.0.1 , public_ip : 123.123.123.123
> 
> frpc.toml [[proxies]] name = "ssh" type = "tcp" localIP = "127.0.0.1" localPort = 22 remotePort = 222 remoteIP = "127.0.0.1" #client ssh bind to server IP 127.0.0.1 only
> 
> [[proxies]] name = "web" type = "tcp" localIP = "127.0.0.1" localPort = 80 remotePort = 80 remoteIP = "123.123.123.123" #client web bind to server IP 123.123.123.123 only

remoteIP is not supported. Please use proxyBindAddr and multiple frps instances to achieve this kind of requirement.
