### ISSUE TITLE
服务端日志出现警告no route found，请求无法代理穿透

### ISSUE THREAD

**Issue by junjie-code200** [fatedier/frp#4481]
### Bug Description

内网服务器的 http 接口（http://内网 IP:6211/app/goods/getRegionId）正常，代理穿透访问失败（http://外网 IP:6211/app/goods/getRegionId）,错误显示找不到路由。

### frpc Version

0.60

### frps Version

0.60

### System Architecture

linux/amd64

### Configurations

# 客户端配置
serverAddr = "121.199.175.183"
serverPort = 7000

[[proxies]]
name = "test-vip"
type = "http"
localIP = "127.0.0.1"
localPort = 6211
customDomains = ["www.test.vip.com"]

#服务端配置
bindPort = 7000
vhostHTTPPort = 6211

### Logs

2024-10-11 16:15:55.764 [W] [httputil/reverseproxy.go:472] do http proxy request [host: 122.199.173.181:6211] error: no route found: 22.199.173.181 /app/goods/getRegionId

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
> customDomains = ["www.test.vip.com"]

意味着 需要使用 `www.test.vip.com` 访问
