### ISSUE TITLE
configure file Error in linux amd64 still require ini file?

### ISSUE THREAD

**Issue by 707728642li** [fatedier/frp#4484]
### Bug Description

Error: open ./frpc.ini: no such file or directory

Flags:
  -c, --config string       config file of frpc (default "./frpc.ini")
      --config-dir string   config directory, run one frpc service for each file in config directory
  -h, --help                help for frpc
      --strict-config       strict config parsing mode, unknown fields will cause an errors (default true)
  -v, --version             version of frpc

### frpc Version

0.60, 0.59, 0.58, ...

### frps Version

0.60, 0.59, 0.58, ...

### System Architecture

linux/amd64

### Configurations

Error: open ./frpc.ini: no such file or directory

Flags:
  -c, --config string       config file of frpc (default "./frpc.ini")
      --config-dir string   config directory, run one frpc service for each file in config directory
  -h, --help                help for frpc
      --strict-config       strict config parsing mode, unknown fields will cause an errors (default true)
  -v, --version             version of frpc

### Logs

Error: open ./frpc.ini: no such file or directory

Flags:
  -c, --config string       config file of frpc (default "./frpc.ini")
      --config-dir string   config directory, run one frpc service for each file in config directory
  -h, --help                help for frpc
      --strict-config       strict config parsing mode, unknown fields will cause an errors (default true)
  -v, --version             version of frpc

### Steps to reproduce

1../frpc
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
> -c, --config string config file of frpc (default "./frpc.ini")
