### ISSUE TITLE
[Feature Request] Restrict access to client from certain IP ranges in server based on ip ranges provided by client

### ISSUE THREAD

**Issue by rishi-anand** [fatedier/frp#4487]
### Describe the feature request

Client supports taking list of allowed IP ranges from where requests can be made to the client and passes it to server when it's authenticating for first time.
Whenever a request comes to the server, the server intercepts the request and checks if it's allowed.

### Affected area

- [X] Docs
- [X] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
The ACL feature is in the plan.

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/blob/dev/doc/server_plugin.md#newuserconn
