### ISSUE TITLE
[Feature Request] When will the Chinese version of the webui interface be available?

### ISSUE THREAD

**Issue by kjljjl** [fatedier/frp#4488]
### Describe the feature request

When will the Chinese version of the webui interface be available?
请问什么时候可以提供中文版的webui界面

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
You can modify the UI resources yourself by specifying the resource directory to use your modified resources.

Alternatively, you can use a third-party web console.

Currently, there isn't much content, so multilingual adaptation won't be implemented.
