### ISSUE TITLE
很神奇的https代理问题

### ISSUE THREAD

**Issue by hongnod** [fatedier/frp#4489]
### Bug Description

在阿里云上买了一台上云服务器，部署frp，内网nginx反向代理seafile和git，提供内网https访问，然后用frp暴露该https到公网。
问题：在PC上chrome和edge访问都没问题，但seafile客户端就是和手机浏览器就是不通，frps的日志里会报join connections closed,如下：
10:16:07.135 [D] [vhost/vhost.go:249] [fdd41d805e96f2c0] [AllServices] new request host [x.y.z] path [] httpUser []
10:16:07.135 [I] [proxy/proxy.go:204] [fdd41d805e96f2c0] [AllServices] get a user connection [1.2.3.4:26645]
10:16:07.135 [D] [server/control.go:272] [fdd41d805e96f2c0] get work connection from pool
10:16:07.135 [D] [proxy/proxy.go:131] [fdd41d805e96f2c0] [AllServices] get a new work connection: [5.6.7.8:6128]
10:16:07.135 [T] [proxy/proxy.go:240] [fdd41d805e96f2c0] [AllServices] handler user tcp connection, use_encryption: true, use_compression: true
10:16:07.135 [D] [proxy/proxy.go:261] [fdd41d805e96f2c0] [AllServices] join connections, workConn(l[a.b.c.d:7117] r[5.6.7.8:6128]) userConn(l[a.b.c.d:443] r[1.2.3.4:26645])
10:16:07.135 [D] [proxy/proxy.go:271] [fdd41d805e96f2c0] [AllServices] join connections closed
10:16:07.152 [D] [server/control.go:243] [fdd41d805e96f2c0] new work connection registered
折腾了几天试了TCP、https、https2http都搞不定

### frpc Version

0.60.0

### frps Version

0.60.0

### System Architecture

linux/amd64

### Configurations

frps.toml:
bindPort = xxxx
vhostHTTPSPort = yyy
log.to = "frps.log"
log.level = "trace"
log.maxDays = 3
auth.method = "token"
auth.token = "*****"

frpc.toml:
serverAddr = "aa.bb.cc.dd"
serverPort = xxxx
transport.protocol = "tcp"
log.to = "/srv/frp/frpc.log"
log.level ="trace"
log.maxDays = 3
log.disablePrintColor = false
auth.method = "token"
auth.token = "*****"
transport.tls.enable = false
transport.tls.disableCustomTLSFirstByte = false
transport.poolCount = 1

[[proxies]]
name = "AllServices"
type = "https"
#type = "tcp"
localIP = "127.0.0.1"
localPort = yyy
#remotePort = yyy
transport.useEncryption = true
transport.useCompression = true
customDomains = ["a.ccc.com","b.ccc.com"]

### Logs

10:16:07.135 [D] [vhost/vhost.go:249] [fdd41d805e96f2c0] [AllServices] new request host [x.y.z] path [] httpUser []
10:16:07.135 [I] [proxy/proxy.go:204] [fdd41d805e96f2c0] [AllServices] get a user connection [1.2.3.4:26645]
10:16:07.135 [D] [server/control.go:272] [fdd41d805e96f2c0] get work connection from pool
10:16:07.135 [D] [proxy/proxy.go:131] [fdd41d805e96f2c0] [AllServices] get a new work connection: [5.6.7.8:6128]
10:16:07.135 [T] [proxy/proxy.go:240] [fdd41d805e96f2c0] [AllServices] handler user tcp connection, use_encryption: true, use_compression: true
10:16:07.135 [D] [proxy/proxy.go:261] [fdd41d805e96f2c0] [AllServices] join connections, workConn(l[a.b.c.d:7117] r[5.6.7.8:6128]) userConn(l[a.b.c.d:443] r[1.2.3.4:26645])
10:16:07.135 [D] [proxy/proxy.go:271] [fdd41d805e96f2c0] [AllServices] join connections closed
10:16:07.152 [D] [server/control.go:243] [fdd41d805e96f2c0] new work connection registered

### Steps to reproduce

1. seafile+nginx install  + configure frp
2. pc browser open url, result fine.
3. seafile client add url,  open failed
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
域名未备案

**Comment by hongnod** [comment]
> 域名未备案

非常感谢！
