### ISSUE TITLE
Programatically start frp service via batch file on windows without cmd runin in background

### ISSUE THREAD

**Issue by StevenLiSiwei** [fatedier/frp#449]
你好作者，

请问如何可以用BATCH 运行后 BATCH会自动退出，不会像目前一样一直停留在 CONSOLE.READ部分？之前用NGROK， BATCH 文件跑一下就退出了，NGROK会在后台继续运行.

感谢作者.

**Comment by fatedier** [comment]
系统问题自行解决，和此项目无关。
