### ISSUE TITLE
VNC xtcp打洞成功了，但是vnc  viewer 连接不上

### ISSUE THREAD

**Issue by fengyacao** [fatedier/frp#4491]
### Bug Description

xtcp 打洞成功了，我用vnc 客户端登录，一直没反应，其它应用都是可以的

### frpc Version

0.57

### frps Version

0.57

### System Architecture

linux/amd64

### Configurations

[[proxies]]
name = "p2p_vnc"
type = "xtcp"
secretKey = "******"
localIP = "127.0.0.1"
localPort = 5901

### Logs

2024-10-14 15:23:50.153 [I] [visitor/xtcp.go:320] [7ba1a8a206ff509a] [p2p_vnc] establishing nat hole connection successful, sid [17288906251372b8ce6c5546f6], remoteAddr [***.***.124.160:13757]

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [x] Others

**Comment by xqzr** [comment]
VNC 客户端，端口写法需要注意

**Comment by kratos9394** [comment]
ultravnc也不行,其他都ok
