### ISSUE TITLE
没有找到API 地址

### ISSUE THREAD

**Issue by workmengxue** [fatedier/frp#4492]
### Bug Description

拥有多个设备，remote_port = 0 ，需要API 查询每个设备分别分配到的端口

### frpc Version

0.58.1

### frps Version

0.58.1

### System Architecture

windows/amd64

### Configurations

1

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
如果你能够在 frps 的 dashboard 上看到这个端口的话，就可以和 dashboard 用一样的 API 获取这个信息，否则可能就拿不到。

API 方面的重构和改进预计不会在短期内完成。
