### ISSUE TITLE
下载的windows安装包提示有病毒

### ISSUE THREAD

**Issue by RobinsonSir** [fatedier/frp#4493]
### Bug Description

![image](https://github.com/user-attachments/assets/66803a3c-1ebf-47b0-9698-3e24eba0bb8e)
![image](https://github.com/user-attachments/assets/0e905251-209d-4e2c-9f23-b0e8236fd3b5)

### frpc Version

0.60.0

### frps Version

0.60.0

### System Architecture

windows/amd64

### Configurations

https://github.com/fatedier/frp/releases/download/v0.60.0/frp_0.60.0_windows_amd64.zip

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
#2095
