### ISSUE TITLE
frpc不加参数运行的时候，默认读取的依旧是旧的ini格式配置文件，而不是toml

### ISSUE THREAD

**Issue by Xeelee1024** [fatedier/frp#4497]
### Bug Description

ini格式配置文件很早就被抛弃了，可是最新版的frpc文件，不加参数运行的时候，默认读取的依旧是旧版的ini格式的配置文件，请更新到toml，谢谢

### frpc Version

0.61.0

### frps Version

0.61.0

### System Architecture

windows/amd64

### Configurations

frpc.exe
open ./frpc.ini: The system cannot find the file specified.

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
不会做这个调整，默认值只是为了兼容。

所有的文档示例里都会明确加上 `-c` 指定配置文件，不指定的方式不推荐使用了，只是避免对存量服务造成破坏。
