### ISSUE TITLE
[Feature Request] 建议FPRC服务器地址能用域名，换了服务器后不用修改客户端那边的参数

### ISSUE THREAD

**Issue by asdf5329** [fatedier/frp#4505]
### Describe the feature request

现在的FRPC的配置文件里面服务器地址只能是IP，如果邦定的客户端太多，更换了服务器后得重新更新配置文件，建议换域名，只要更改一下解析IP，客户端配置不用动

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by JustinTangChina** [comment]
可以用域名的，我就在用

**Comment by JustinTangChina** [comment]
![image](https://github.com/user-attachments/assets/02ef192d-62d6-45a1-8610-1cab7213e2c4)
