### ISSUE TITLE
[Feature Request] FRP服务端会不会被别人用

### ISSUE THREAD

**Issue by SVgeiliMAN** [fatedier/frp#4507]
### Describe the feature request

今天部署了一下，发现这个FRP的服务端是任何人都可以连的。。。
那别人是不是可以随便用我的FRP服务
会出现这种情况吗？
UP主要不要加个验证密钥什么的

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
加
