### ISSUE TITLE
是否可以通过环境变量来配置frp

### ISSUE THREAD

**Issue by DiamondYuan** [fatedier/frp#451]
frp放在docker里面时，还需要在容器外部放置一个文件。要修改的时候挺麻烦的。

我现在的实现是写了一个go的小脚本。
读取FRP_XXX__YYY=ZZZ的环境变量 然后自动生成frp.ini
[XXX]
YYY = ZZZ
https://github.com/GeorgeYuen/frp

这个能否转正，合并到frp中？我现在的main.go以什么形式加入比较好？放在哪个目录下？
例如作为插件的形式 fprConf

**Comment by fatedier** [comment]
可以考虑命令行启动参数，目前只支持几个参数。

**Comment by GeorgeYuen** [comment]
docker插件如何？在docker启动的时候读取环境变量来生成配置文件。
不需要对frp源码有修改、

**Comment by fatedier** [comment]
环境变量有侵入性，如果能在命令行参数中解决的问题，就不必非要通过环境变量了。

主要是 frps 的配置，如果命令行参数支持全了，那么配置文件就是可选的了。docker run 的时候指定启动参数来运行。

如果你有兴趣改造下目前的命令行参数的使用姿势，非常欢迎。

**Comment by GeorgeYuen** [comment]
frp/cmd/frps/main.go 中我准备增加三个args参数
http_port
https_port
token
这样命名如何 应该只要在main.go里读args然后给config.ServerCommonCfg赋值就可以了吧。
如果没错的话我就去写代码并且PR了。

**Comment by fatedier** [comment]
可以，命名的话先和配置文件里保持一致吧。

**Comment by GeorgeYuen** [comment]
ok 我会和配置文件一致。

**Comment by fatedier** [comment]
v0.17.0 中命令行参数已修改，能支持大多数的配置。

**Comment by rty813** [comment]
> v0.17.0 中命令行参数已修改，能支持大多数的配置。

@fatedier 命令行参数无法实现配置login_fail_exit，这个怎么实现？
