### ISSUE TITLE
frpc 无法登录frps服务

### ISSUE THREAD

**Issue by ALiangTech** [fatedier/frp#4511]
### Bug Description

frps服务：已经启动
<img width="1022" alt="frps_servers" src="https://github.com/user-attachments/assets/072fb898-ade6-46eb-8dcc-48018470081b">
服务端是linux/amd64
客户端是windows/amd64

### frpc Version

0.61.0

### frps Version

0.61.0

### System Architecture

linux/amd64

### Configurations

frps配置：
`
bindPort = 7001

auth.method = "token"

auth.token ="hj@333"

webServer.addr="0.0.0.0"

webServer.port=7000

webServer.user="hj"

webServer.password="asd**77asdf123"

`
frpc配置：
`
serverAddr="xxx"
serverPort=7001
loginFailExit=true
auth.method="token"
auth.token="hj@333"
transport.tls.enable = false

[[proxies]]
name = "test-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3389
remotePort = 23389
`

### Logs

login to the server failed: dial tcp xxxx:7001: connectex: No connection could be made because the target machine actively refused it.. With loginFailExit enabled, no additional retries will be attempted

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Check and confirm that your network environment is normal.
