### ISSUE TITLE
[Feature Request] frp搭配ingress-nginx怎么获取到真实IP?

### ISSUE THREAD

**Issue by zhangtianming777** [fatedier/frp#4512]
### Describe the feature request

目前我测试frp搭配ingress-nginx，日志获取到的但是master的内网IP，怎么获取到真实的IP呢？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Try google first.

**Comment by zhangtianming777** [comment]
> 先尝试一下谷歌。

嗯，之前在谷歌已经查询过多次，大部分都是frp+nginx的配置，我尝试过在ingress-nginx的pods里面修改nginx.conf文件，请求的IP还是master的内网IP
