### ISSUE TITLE
xtcp模式下 内网中的访问端怎么通过内网中的（双网卡）代理服务器访问到外面的被访问端

### ISSUE THREAD

**Issue by kktt007** [fatedier/frp#4514]
### Bug Description

下面的配置是部署在内网有双网卡的linux服务器中
在家里能通过 这个服务器 访问到内网中其他任何电脑，只要proxies配置需要被访问的电脑即可

但是现在想在这个服务器上同时部署visitors端，这样内网中的电脑（比如192.168.1.11）能通过这个服务器，访问外面的被访问端bbb(bbb在家里)

 应该怎么配置 
假如：内网服务器linux的ip是192.168.1.111
bindAddr = "127.0.0.1"
bindPort = 9999
其他内部电脑，可以通过这样的配置借助192.168.1.111这台电脑访问外面的bbb电脑吗
如果可以rdp的方式应该是什么样的

现在用内网电脑192.168.11来操作
打开mstsc后应该怎么做才对

也就是内网中的192.168.11 想借助服务器 192.168.111 访问外部的电脑bbb

### frpc Version

0.60

### frps Version

0.60

### System Architecture

windows/amd64

### Configurations

serverAddr = xxx
serverPort = xxx
auth.method = "token"
auth.token = xxx
log.to = "./frpc.log"
log.level = "info"
log.maxDays = 3

[[proxies]] 这段不用看，做为被访问端没问题
name = "aaa"
type = "xtcp"
secretKey = "aaaaa"
localIp = "192.168.1.2"
localPort = 3389

这个可以吗：
[[visitors]]
name = bbb_visitor
type = "xtcp"
serverName = bbb
secretKey = xxx
bindAddr = "127.0.0.1" # 这样操作感觉更加通用，但是具体在内网的电脑上怎么做？
bindPort = 9999

或者应该设置成
[[visitors]]
name = bbb_visitor
type = "xtcp"
serverName = bbb
secretKey = xxx
bindAddr = "192.168.1.11" # 这样比较麻烦，如果192.168.1.12 等等要访问这边就要添加很多
bindPort = 9999

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by kktt007** [comment]
谢谢，已经搞定了。。。还是想请教下大家的想法

**Comment by xqzr** [comment]
> bindAddr = "192.168.1.11"
```yml
bindAddr = "0.0.0.0"
```
监听所有网卡，但请注意安全

**Comment by kktt007** [comment]
> > bindAddr = "192.168.1.11"
> 
> ```yaml
> bindAddr = "0.0.0.0"
> ```
> 
> 监听所有网卡，但请注意安全

谢谢，这个确实可以

2个问题
1. 能否用127.0.0.1，然后在需要rdp远程的电脑上做端口转发到这个服务器上， 这样就不用0.0.0.0这样太大
2. 比如我的电脑Ip是192.168.1.123，然后我在上面的服务器电脑中添加bindAddr = 192.168.1.123 但是发现居然连接不了，是有什么ip段信任区需要设置吗
