### ISSUE TITLE
[Feature Request] 最新版frp能不能恢复windows 386(32位)编译下载

### ISSUE THREAD

**Issue by one808** [fatedier/frp#4515]
### Describe the feature request

希望最新版frp恢复windows 386(32位)编译下载，很需要。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
可以下载源码自行编译，release 中不会再添加 32 位的版本。
