### ISSUE TITLE
I start the torrent tracker, but it always gives a local ip address if I connect the torrent client to the web.

### ISSUE THREAD

**Issue by DEAM0** [fatedier/frp#4517]
### Bug Description

Hello, can anyone advise me how to make it so that when a user connects to my tracker, his IP address and port are displayed, because every time he connects, 127.0.0.1 or 10.x.x.x is displayed. I tried everything in nginx but nothing works, it still shows the local ip address.

### frpc Version

0.61.0

### frps Version

0.61.0

### System Architecture

linux/amd64

### Configurations

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = ""
webServer.password = ""
enablePrometheus = true
vhostHTTPSPort = 443
vhostHTTPPort = 80
webServer.tls.certFile = ""
webServer.tls.keyFile = ""
bindPort = 7000

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
这需要 `proxy protocol` 支持，但这不太可能

**Comment by DEAM0** [comment]
Not work.
