### ISSUE TITLE
[Feature Request] support bing remote ip

### ISSUE THREAD

**Issue by zjqzero** [fatedier/frp#4518]
### Describe the feature request

binding to a specific remote IP is much more secure. It is important binding '127.0.0.1' for frpc cascading.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Duplicate of https://github.com/fatedier/frp/issues/4480
