### ISSUE TITLE
[Feature Request] dockerhub的fatedier/frps中建议增加Tag:latest

### ISSUE THREAD

**Issue by zzzshanghai** [fatedier/frp#4525]
### Describe the feature request

fatedier您好，我使用docker部署frps。因dockerhub的fatedier/frps中，TAG仅有v0.61.0，我使用docker pull fatedier/frps，无法直接拉取最新版的镜像。系统提示如下：
docker pull fatedier/frps
Using default tag: latest
Error response from daemon: manifest for fatedier/frps:latest not found: manifest unknown: manifest unknown

为便于直接拉取镜像，且可以使用 containrrr/watchtower 自动更新镜像，建议增加TAG:latest（截图如下）。谢谢。
![微信截图_20241105200116](https://github.com/user-attachments/assets/96fde7cd-5482-4ecf-a9b9-2d0a1707398d)

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/issues/2972#issuecomment-1149380901

**Comment by fatedier** [comment]
目前 v0 版本没有兼容性保证，版本和配置强相关，不会提供 latest 镜像，请明确指定镜像版本。

**Comment by wuai1024** [comment]
![image](https://github.com/user-attachments/assets/cdb3c49d-88ff-4603-b9ec-958d5ad3889d)

@zzzshanghai  可以使用我的镜像，就是基于官方编译的，加入了 32 位和其他的支持。 latest 是最新版本。
