### ISSUE TITLE
[Feature Request] 能否实现拒绝来自国外的IP

### ISSUE THREAD

**Issue by jzxkkk** [fatedier/frp#4528]
### Describe the feature request

检查日志时经常出现很多来自国外的IP
是否可以实现软件层面拒绝国外IP
还是只能通过iptables这种实现

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
可以，但需要考虑**性能**

**Comment by 88489754** [comment]
完全可以的啊，如果是云服务器可以使用厂商的防火墙策略阻断海外IP段的TCP+UDP，如果是linux系统和win系统也可以使用防火墙策略实现，或其他支持三层路由的交换机，防火墙路由器等都可以的。

**Comment by fatedier** [comment]
已经有相关 issue 了，未来会考虑支持 ACL 规则配置。
