### ISSUE TITLE
UDP over UDP tunnel

### ISSUE THREAD

**Issue by scriptchildie** [fatedier/frp#4531]
### Describe the feature request

Hi fantastic project. 

I was wondering if there is a way to tunnel UDP traffic over UDP instead of the TCP Port.

Ideally want to have another option in the config file bindUdpPort

Please let me know if it's already implemented and I missed it. 

Thank you  

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by scriptchildie** [comment]
nice one thanks!

**Comment by CalunVier** [comment]
> https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml#L83
> 
> kcp and quic are based on UDP.

Can a purely UDP connection be provided? Both KCP and QUIC have packet loss retransmission mechanisms, but packet loss can be considered a virtue. In some cases, upper-layer applications may already have their own packet loss retransmission mechanisms, which could introduce additional overhead.
能否提供纯粹的UDP连接？kcp 和 quic都有丢包重传机制，但丢包是一种美德（某些情况下，上层应用会包含丢包重传机制，这会带来额外的负担？）
