### ISSUE TITLE
服务端限速

### ISSUE THREAD

**Issue by pilgrimage233** [fatedier/frp#4532]
### Describe the feature request

请问服务端可以直接对客户端建立的通道端口进行限速吗，我不想要客户端限速，我想直接在服务端就能控制各个端口之间的速率

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [x] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by anhao** [comment]
通过服务端插件就可以实现， https://gofrp.org/zh-cn/docs/features/common/server-plugin/

**Comment by pilgrimage233** [comment]
抱歉，我实在没怎么看懂，我是运行在openwrt的FRPS插件，这个配置和官方还不太一样
config frps 'main'
	option server 'frps'
	option client_file '/usr/bin/frps'
	option bind_port '7000'
	option tcp_mux 'true'
是以这种形式的，如果要配置限速可以直接在上面加  option bandwidth_limit 吗？

**Comment by fatedier** [comment]
> 我是运行在openwrt的FRPS插件，这个配置和官方还不太一样

其他平台的相关插件、模块，如果不是正常的方式运行，你应该在对应的平台、论坛寻求帮助。
