### ISSUE TITLE
希望介绍 frp 对os 支持的情况

### ISSUE THREAD

**Issue by gandli** [fatedier/frp#4533]
### Bug Description

希望获知对xp、win7……的支持情况，以及替代方案。
frpc、frps 版本一致才能使用吗？

### frpc Version

0.51.3

### frps Version

0.51.3

### System Architecture

windows/amd64

### Configurations

常规

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
1、Golang 的决定
2、不一定，但建议
