### ISSUE TITLE
windows控制台回显乱码

### ISSUE THREAD

**Issue by alomoi** [fatedier/frp#4534]
### Bug Description

程序在windows控制台中的回显中有类似乱码的字符，新版本c端s端均有此问题。旧版本0.54.0以前则正常。
![1](https://github.com/user-attachments/assets/8fac5124-13e9-4f17-ba8b-e0c45f92126e)
![2](https://github.com/user-attachments/assets/7f852d08-3b69-403c-863a-81707efa34ed)

### frpc Version

0.61.0

### frps Version

0.61.0

### System Architecture

windows/amd64

### Configurations

bindPort = 7000
auth.token = "xxxxx"

### Steps to reproduce

1. 通过控制台调用frp及配置文件，查看回显输出

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
看上去是颜色标记，尝试配置：
log.to = "console"
log.disablePrintColor = true

**Comment by alomoi** [comment]
> 看上去是颜色标记，尝试配置： log.to = "console" log.disablePrintColor = true

log.disablePrintColor = true 禁用掉颜色就ok了，感谢
