### ISSUE TITLE
新版的 socks5到底怎么配置？有小白教程吗?

### ISSUE THREAD

**Issue by cyclestudy** [fatedier/frp#4535]
### Bug Description

新版的 socks5到底怎么配置？有小白教程吗

### frpc Version

0.61

### frps Version

0.61

### System Architecture

s-linux c-windows

### Configurations

新版的 socks5到底怎么配置？有小白教程吗

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/blob/dff56cb0ca4b03d4ee9e3cb76ab863df3a4a83a2/conf/frpc_full_example.toml#L264-L271
