### ISSUE TITLE
[Feature Request] 国密算法

### ISSUE THREAD

**Issue by DerekLoveCC** [fatedier/frp#4536]
### Describe the feature request

请问traffic流SSL是否支持国密SM2算法？如果支持，有没有指南？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
Dup #3663

**Comment by fatedier** [comment]
不清楚，可以参考 Go 官方文档。
