### ISSUE TITLE
frpc 0.61.0 arm64 still uses ini config file

### ISSUE THREAD

**Issue by mochechan** [fatedier/frp#4537]
### Bug Description

When I trying to start frpc arm64 version in termux, the error message shows:
./frpc
open ./frpc.ini: no such file or directory

### frpc Version

0.61.0

### frps Version

0.60.0

### System Architecture

android/termux/arm64

### Configurations

user = "{{.Envs.FRPC_HOSTNAME}}"

serverAddr = "{{.Envs.FRPS_ADDR}}"
serverPort = 7000

loginFailExit = true

auth.method = "token"
auth.token = ""

includes = ["./client/*.toml"]

### Steps to reproduce

1. Just download frp_0.61.0_android_arm64.tar.gz
2. extract tar.gz file
3. execute the frpc
4. show the error message: open ./frpc.ini: no such file or directory

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp?tab=readme-ov-file#access-your-computer-in-a-lan-network-via-ssh

Please refer to the command startup in the document.

**Comment by mochechan** [comment]
However, using -c to specify a toml file appears another errors.
```
./frpc -c frpc.toml 
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1.ClientConfig
```

The mentioned problem does not occur if I use x86_64 version.
