### ISSUE TITLE
[Feature Request] 是否可以在frpc上传局域网ip或其它host信息到frps dashboard展示？

### ISSUE THREAD

**Issue by yimuc** [fatedier/frp#4539]
### Describe the feature request

希望frps能展示frpc的局域网ip，以及其它host信息，原因是有租房搬家需求，换了局域网之后，本地不方便快速查看ip用于ssh连接。
是否可以在frps dashboard上提供相关信息？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
`:7500/api/proxy/tcp`

**Comment by yimuc** [comment]
> `:7500/api/proxy/tcp`

看起来不足以解决问题？我看到了一个"localIP": "127.0.0.1"，但是不太符合要求呀

**Comment by fatedier** [comment]
目前没有计划。

你可以尝试在 proxy 的 annotation 附加信息，会被显示在 frps dashboard 上。
