### ISSUE TITLE
frps does not listen the port which frpc is defined

### ISSUE THREAD

**Issue by super-small-rookie** [fatedier/frp#4541]
### Bug Description

frps and frpc used for a period of time，it works very well.
But after a period of time, it Added configuration.
frpc added the new proxies remoteport and connect to frps, but frps does not listen the port which frpc is defined.
frps log print the port which listened is 0, frps-web displayed the port does not match the defined port. Please refer to the screenshot of the log for details.It seems that the server randomly monitored the port.
The previous configuration which the remoteport is10000 was fine and works well. Only the new config have the problem.

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

[[proxies]]
name = "public-lb-server-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 80
remotePort = 10000

[[proxies]]
name = "public-minio-api"
localIP = "127.0.0.1"
type = "tcp"
local_port = 9002
remote_port = 19003

[[proxies]]
name = "public-minio-web"
localIP = "127.0.0.1"
type = "tcp"
local_port = 8081
remote_port = 18083

### Logs

frpc：
![frpc-log-1](https://github.com/user-attachments/assets/50600748-c8ea-48bd-a1f3-f4e798a1e522)
![frpc-log-2](https://github.com/user-attachments/assets/106a23cb-c2f9-4fe0-9730-083d63a1e53d)

frps:
![frps-log-1](https://github.com/user-attachments/assets/37602aa7-e738-4b7b-82bc-9843d38ef3c4)
![frps-log-2](https://github.com/user-attachments/assets/b23ab7ae-f10e-481a-a985-7b1a7be47c0f)

frps-web:
![frps-web](https://github.com/user-attachments/assets/dbf600b8-5746-4d74-9f81-85ce4edb5736)

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Response from Github Copilot:

> The issue described is that `frps` does not listen on the port defined by `frpc`. Below are the steps to address this:
> 
> 1. **Check Configuration Syntax**: Ensure the configuration syntax is correct. Specifically, verify that the keys `local_port` and `remote_port` are correctly used (should be `localPort` and `remotePort`). For example:
>     ```ini
>     [[proxies]]
>     name = "public-lb-server-tcp"
>     type = "tcp"
>     localIP = "127.0.0.1"
>     localPort = 80
>     remotePort = 10000
> 
>     [[proxies]]
>     name = "public-minio-api"
>     type = "tcp"
>     localIP = "127.0.0.1"
>     localPort = 9002
>     remotePort = 19003
> 
>     [[proxies]]
>     name = "public-minio-web"
>     type = "tcp"
>     localIP = "127.0.0.1"
>     localPort = 8081
>     remotePort = 18083
>     ```
> 
> 2. **Restart `frps` and `frpc`**: After updating the configuration, restart both `frps` and `frpc` to apply the changes.
> 
> 3. **Check Logs for Errors**: Review the logs of both `frps` and `frpc` for any errors or warnings that might indicate why the port is not being listened to.
> 
> 4. **Verify Port Availability**: Ensure that the ports specified in the configuration are not being used by other processes on the server.
> 
> If the issue persists, consider sharing the updated configuration and detailed logs for further troubleshooting.

**Comment by super-small-rookie** [comment]
The high version configuration parameters and low version configuration parameters are mixed, and have been modified according to the new parameters. The problem has been resolved.
