### ISSUE TITLE
隔几天frps文件会被删除

### ISSUE THREAD

**Issue by feng84302** [fatedier/frp#4542]
### Bug Description

frp 版本：0.61.0

frps.toml内容如下：
bindPort = 17000
vhostHTTPPort = 27000

用systemctl启动frps ，最开始一切正常，但是过几天后，frps服务就停止了，
![image](https://github.com/user-attachments/assets/0a013ac1-7073-41a0-be93-56392ac261d6)
然后发现frps文件没了

### frpc Version

0.61.0

### frps Version

0.61.0

### System Architecture

ubuntu20.04

### Configurations

frps.toml内容如下：
bindPort = 17000
vhostHTTPPort = 27000

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
kill 9 是被系统强制停止，和环境相关。
