### ISSUE TITLE
[Feature Request] 希望可以在Frps配置,客户端相关的映射关系,不用每次 都要去frpc进行映射配置

### ISSUE THREAD

**Issue by baxiprince** [fatedier/frp#4543]
### Describe the feature request

如题

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
https://github.com/fatedier/frp?tab=readme-ov-file#client-admin-ui

可以选择将客户端管理页面暴露出来以方便管理，但是会增加安全风险。

**Comment by fenghan0430** [comment]
我找到一个仓库，你可能会感兴趣。

我的体验笔记

[https://github.com/fenghan0430/doc/blob/main/%E7%AC%94%E8%AE%B0/VaalaCat%E7%9A%84frp-panel%E4%BD%BF%E7%94%A8%E7%AC%94%E8%AE%B0.md](https://github.com/fenghan0430/doc/blob/main/%E7%AC%94%E8%AE%B0/VaalaCat%E7%9A%84frp-panel%E4%BD%BF%E7%94%A8%E7%AC%94%E8%AE%B0.md)

仓库地址：[https://github.com/VaalaCat/frp-panel](https://github.com/VaalaCat/frp-panel)
