### ISSUE TITLE
[Feature Request] 网页中的API接口如何代理

### ISSUE THREAD

**Issue by xushaun** [fatedier/frp#4544]
### Describe the feature request

公司内部服务器(内网ip为 192.168.1.100)：
1. 内部网页vue用nginx代理 端口1001 ，内部局域网访问网页 http://192.168.1.100:1001
2. 网页用的接口服务是8082 ，内部局域网访问接口 http://192.168.1.100:8082
3. 现在用frpc tcp代理 把内网1001端口 映射到公网服务器(比如10.10.10.10)6000端口暴露出去，外网访问网页http://10.10.10.10:6000成功，但是页面不显示，原因是网页用http://192.168.1.100:8082这个地址去访问内部接口，外部网络直接访问内部网址肯定无法访问，这个有办法解决吗

ps：我想把8082端口的服务也暴露出去，但是也没用，因为网页的接口请求地址是写死的http://192.168.1.100:8082、

### Affected area

- [X] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by wuai1024** [comment]
你都说了，网页的请求地址写死了还玩啥啊。 vue不是这样玩的，去看下 vue 的官网 路由相关的那一块。你就知道怎么改了

**Comment by xushaun** [comment]
> 你都说了，网页的请求地址写死了还玩啥啊。 vue不是这样玩的，去看下 vue 的官网 路由相关的那一块。你就知道怎么改了

网页的API请求都是具体的ip地址或者域名，一般都写死的。vue路由说的是页面的地址，我这边说的请求是数据的请求，和路由没多大关系，如果您能提供更具体的说明，万分感谢

**Comment by wuai1024** [comment]
> > 你都说了，网页的请求地址写死了还玩啥啊。 vue不是这样玩的，去看下 vue 的官网 路由相关的那一块。你就知道怎么改了
> 
> 网页的API请求都是具体的ip地址或者域名，一般都写死的。vue路由说的是页面的地址，我这边说的请求是数据的请求，和路由没多大关系，如果您能提供更具体的说明，万分感谢

proxy

**Comment by fatedier** [comment]
像上面说的，这个属于是前端方面的问题，和 frp 自身无关，建议遵循常规的网站设计实现。
