### ISSUE TITLE
在台湾繁体WIN7系统上使用时出现错误

### ISSUE THREAD

**Issue by sd3970566** [fatedier/frp#4552]
### Bug Description

runtime.asmstdcall(0x22fcf8)
        runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x47a37a

rax     0x0
rbx     0x11e2e78
rcx     0x126afe8
rdx     0x20
rdi     0x7fffffde000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x170a2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0x11e1ec0
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

### frpc Version

frp_0.61.0_windows_amd64

### frps Version

frp_0.61.0_windows_amd64

### System Architecture

windows_amd64

### Configurations

runtime.asmstdcall(0x22fcf8)
        runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x47a37a

rax     0x0
rbx     0x11e2e78
rcx     0x126afe8
rdx     0x20
rdi     0x7fffffde000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x170a2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0x11e1ec0
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

### Logs

runtime.asmstdcall(0x22fcf8)
        runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x47a37a

rax     0x0
rbx     0x11e2e78
rcx     0x126afe8
rdx     0x20
rdi     0x7fffffde000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x170a2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0x11e1ec0
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

### Steps to reproduce

1. 
2. 
3. 
...
runtime.asmstdcall(0x22fcf8)
        runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x47a37a

rax     0x0
rbx     0x11e2e78
rcx     0x126afe8
rdx     0x20
rdi     0x7fffffde000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x170a2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0x11e1ec0
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by sd3970566** [comment]
退到frp_0.49.0_windows_amd64版本 报错 
2024/11/22 18:27:35 [W] [service.go:131] log
.38.85:7003: i/o timeout
dial tcp 117.25.38.85:7003: i/o timeout

**Comment by wuai1024** [comment]
用老版本，新版本的go已经不支持win7了。

**Comment by sd3970566** [comment]
> 用老版本，新版本的go已经不支持win7了。

要退到具体多少版本呢？  另外我有的繁体电脑如果通过高级语言启动的方式启动FRPC。多加入退出几次就会出现 FRPS卡住···只能通过bat手动启动。有办法解决吗
