### ISSUE TITLE
作为个人自己用可以，但是铺开大面积使用的话。BUG太多了。正规格式提交bug就算了太麻烦了，我口头说几个，愿意研究的就看下吧

### ISSUE THREAD

**Issue by sd3970566** [fatedier/frp#4554]
### Bug Description

作为个人自己用可以，但是铺开大面积使用的话。BUG太多了。正规格式提交bug就算了太麻烦了，我口头说几个，愿意研究的就看下吧！
1：作为反向代理，一般使用场景是让海外客户运行frpc客户端，但是海外机器大部分韩文，日文，繁体中文，只要是这类型的机器，快速的运行退出运行退出(不需要多个同时并发，只要一台海外机器一个frpc客户端开关几次)，。就有可能导致frps服务端卡死，必须重开frps服务端才可以恢复。 
2：win7说是已经不支持了。但是如果没有判定好，或者判定失误，。不小心让win7的机器运行frpc客户端连frps服务端。一两次就会导致frps服务端卡死。(这frps服务端也是真够可以的，各种卡死）
3：常规系统，你以为正常国内中文win10就能正常用？不不。你想太多了，为了适配海外机器大部分开发都用W方法，比如ShellExecuteW 不能用ShellExecuteA。（原因搞开发的都懂不解释了）只要你用ShellExecuteW来启动frpc服务，那么只要两三次也就会把FRPS搞卡死
其他：还有其他情况不一一举例，反正估计也是没人管。我只能说，这个工具客户端和服务端都掌握在自己手上自己用的情况没毛病很稳定。但是客户端是外人运行的情况，外人机器环境不可控的情况，你最多只能判定客户机系统，win7以下的别运行，其他什么也做不了，别说什么鉴权不让他们登，我就是要用他们的海外IP，就是要用他们的网络提供socks5服务。只要是这个情况那么我们这个FRP就是坨屎！
最后说两句：感谢作者无偿开源，碎碎念也是自己折腾几天时间损失的抱怨，frps服务端太经常卡死了。而且是受客户端影响，这样的设计就特别不合理。

### frpc Version

frp_0.61.0_windows_amd64

### frps Version

frp_0.61.0_windows_amd64

### System Architecture

windows_amd64

### Configurations

作为个人自己用可以，但是铺开大面积使用的话。BUG太多了。正规格式提交bug就算了太麻烦了，我口头说几个，愿意研究的就看下吧！
1：作为反向代理，一般使用场景是让海外客户运行frpc客户端，但是海外机器大部分韩文，日文，繁体中文，只要是这类型的机器，快速的运行退出运行退出(不需要多个同时并发，只要一台海外机器一个frpc客户端开关几次)，。就有可能导致frps服务端卡死，必须重开frps服务端才可以恢复。 
2：win7说是已经不支持了。但是如果没有判定好，或者判定失误，。不小心让win7的机器运行frpc客户端连frps服务端。一两次就会导致frps服务端卡死。(这frps服务端也是真够可以的，各种卡死）
3：常规系统，你以为正常国内中文win10就能正常用？不不。你想太多了，为了适配海外机器大部分开发都用W方法，比如ShellExecuteW 不能用ShellExecuteA。（原因搞开发的都懂不解释了）只要你用ShellExecuteW来启动frpc服务，那么只要两三次也就会把FRPS搞卡死
其他：还有其他情况不一一举例，反正估计也是没人管。我只能说，这个工具客户端和服务端都掌握在自己手上自己用的情况没毛病很稳定。但是客户端是外人运行的情况，外人机器环境不可控的情况，你最多只能判定客户机系统，win7以下的别运行，其他什么也做不了，别说什么鉴权不让他们登，我就是要用他们的海外IP，就是要用他们的网络提供socks5服务。只要是这个情况那么我们这个FRP就是坨屎！
最后说两句：感谢作者无偿开源，碎碎念也是自己折腾几天时间损失的抱怨，frps服务端太经常卡死了。而且是受客户端影响，这样的设计就特别不合理。

### Logs

作为个人自己用可以，但是铺开大面积使用的话。BUG太多了。正规格式提交bug就算了太麻烦了，我口头说几个，愿意研究的就看下吧！
1：作为反向代理，一般使用场景是让海外客户运行frpc客户端，但是海外机器大部分韩文，日文，繁体中文，只要是这类型的机器，快速的运行退出运行退出(不需要多个同时并发，只要一台海外机器一个frpc客户端开关几次)，。就有可能导致frps服务端卡死，必须重开frps服务端才可以恢复。 
2：win7说是已经不支持了。但是如果没有判定好，或者判定失误，。不小心让win7的机器运行frpc客户端连frps服务端。一两次就会导致frps服务端卡死。(这frps服务端也是真够可以的，各种卡死）
3：常规系统，你以为正常国内中文win10就能正常用？不不。你想太多了，为了适配海外机器大部分开发都用W方法，比如ShellExecuteW 不能用ShellExecuteA。（原因搞开发的都懂不解释了）只要你用ShellExecuteW来启动frpc服务，那么只要两三次也就会把FRPS搞卡死
其他：还有其他情况不一一举例，反正估计也是没人管。我只能说，这个工具客户端和服务端都掌握在自己手上自己用的情况没毛病很稳定。但是客户端是外人运行的情况，外人机器环境不可控的情况，你最多只能判定客户机系统，win7以下的别运行，其他什么也做不了，别说什么鉴权不让他们登，我就是要用他们的海外IP，就是要用他们的网络提供socks5服务。只要是这个情况那么我们这个FRP就是坨屎！
最后说两句：感谢作者无偿开源，碎碎念也是自己折腾几天时间损失的抱怨，frps服务端太经常卡死了。而且是受客户端影响，这样的设计就特别不合理。

### Steps to reproduce

For personal use, it's fine, but for large-scale deployment, there are too many bugs. Filing bugs in a formal format is too troublesome, so I'll just mention a few verbally. If you're willing to investigate, take a look!

1: As a reverse proxy, the typical use case is for overseas clients to run the frpc client. However, most overseas machines have Korean, Japanese, or traditional Chinese interfaces. On these types of machines, if you quickly run and exit the frpc client multiple times (without multiple concurrent instances, just one frpc client on one overseas machine being toggled on and off a few times), it may cause the frps server to freeze, and you have to restart the frps server to recover.

2: It's said that Win7 is no longer supported. But if there's a misjudgment or mistake, and a Win7 machine inadvertently runs the frpc client to connect to the frps server, it may cause the frps server to freeze after just one or two attempts. (This frps server is really something; it frequently freezes.)

3: Regarding regular systems, you might think that a normal domestic Chinese Win10 system can be used without issues. No, no. You're overthinking it. To adapt to overseas machines, most developers use the W method, such as ShellExecuteW instead of ShellExecuteA. (The reasons are understood by developers, so I won't explain.) If you use ShellExecuteW to start the frpc service, it will probably cause the FRPS to freeze after just a couple of attempts.

Others: There are other situations, but I won't enumerate them all. Anyway, I doubt anyone is paying attention. I can only say that when both the client and server are under your control and used personally, the tool is stable and works fine. But when the client is run by outsiders on uncontrollable machine environments, you can only determine the client system and prohibit machines below Win7 from running it. There's nothing else you can do, despite authentication to prevent them from logging in. I need to use their overseas IPs and their networks to provide SOCKS5 services. Under such circumstances, our FRP is a mess!

Finally, a couple of words: Thank you to the author for open-sourcing it for free. My griping is just about the time and effort I wasted troubleshooting. The frps server freezes too often, and it's affected by the client. Such a design is particularly unreasonable.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
我使用 Linux 运行着 frp**s** 作为公共服务器 #4423，从未遇到过 frp**c**”卡死“frp**s**

**Comment by sd3970566** [comment]
> 我使用 Linux 运行着 frp**s** 作为公共服务器 #4423，从未遇到过 frp**c**”卡死“frp**s**

linux的没试过。如果你愿意。可以提供IP 我随便拿台繁体电脑连过去试试

**Comment by xqzr** [comment]
> > 我使用 Linux 运行着 frp**s** 作为公共服务器 #4423，从未遇到过 frp**c**”卡死“frp**s**
> 
> linux的没试过。如果你愿意。可以提供IP 我随便拿台繁体电脑连过去试试

在上文中的链接

**Comment by sd3970566** [comment]
> > > 我使用 Linux 运行着 frp**s** 作为公共服务器 #4423，从未遇到过 frp**c**”卡死“frp**s**
> > 
> > 
> > linux的没试过。如果你愿意。可以提供IP 我随便拿台繁体电脑连过去试试
> 
> 在上文中的链接

我的意思frpc运行socks5代理 需要 server_addr、server_port，remote_port 最精简的情况也要这三个。

**Comment by xqzr** [comment]
> > > > 我使用 Linux 运行着 frp**s** 作为公共服务器 #4423，从未遇到过 frp**c**”卡死“frp**s**
> > > 
> > > 
> > > linux的没试过。如果你愿意。可以提供IP 我随便拿台繁体电脑连过去试试
> > 
> > 
> > 在上文中的链接
> 
> 我的意思frpc运行socks5代理 需要 server_addr、server_port，remote_port 最精简的情况也要这三个。

前两者在链接中。
`remote_port` 非必填，留空由 frps 分配

**Comment by superzjg** [comment]
我的 frps 运行在 openwrt 中，用了两三年了，常驻5个（国内）代理，没有发生过卡死...

**Comment by cyclestudy** [comment]
一个插件只能对应一个客户端，在两个客户端都开启 socks5 就无法使用

**Comment by sd3970566** [comment]
> 一个插件只能对应一个客户端，在两个客户端都开启 socks5 就无法使用

可以的。可以根据端口号随意切换不同的代理服务

**Comment by sd3970566** [comment]
> > > > > 我使用 Linux 运行着 frp**s** 作为公共服务器 #4423，从未遇到过 frp**c**”卡死“frp**s**
> > > > 
> > > > 
> > > > linux的没试过。如果你愿意。可以提供IP 我随便拿台繁体电脑连过去试试
> > > 
> > > 
> > > 在上文中的链接
> > 
> > 
> > 我的意思frpc运行socks5代理 需要 server_addr、server_port，remote_port 最精简的情况也要这三个。
> 
> 前两者在链接中。 `remote_port` 非必填，留空由 frps 分配

start error: 端口不存在！如有疑问，可访问网址：https://pan.wo25.net/frp/

**Comment by xqzr** [comment]
> > > > > > 我使用 Linux 运行着 frp**s** 作为公共服务器 #4423，从未遇到过 frp**c**”卡死“frp**s**
> > > > > 
> > > > > 
> > > > > linux的没试过。如果你愿意。可以提供IP 我随便拿台繁体电脑连过去试试
> > > > 
> > > > 
> > > > 在上文中的链接
> > > 
> > > 
> > > 我的意思frpc运行socks5代理 需要 server_addr、server_port，remote_port 最精简的情况也要这三个。
> > 
> > 
> > 前两者在链接中。 `remote_port` 非必填，留空由 frps 分配
> 
> start error: 端口不存在！如有疑问，可访问网址：https://pan.wo25.net/frp/

配置示例：
```json
{
    "proxies": [
        {
            "name": "32108_tcp",
            "type": "tcp",
            "localIP": "::1",
            "localPort": 3389,
            "remotePort": 32108,
            "metadatas": {
                "uuid": "110aa5bd-24ad-438c-91e4-2c377a4e0dc5"
            }
        }
    ]
}
```
`remotePort` 和 `uuid` 以外的配置项，可自定义

**Comment by fatedier** [comment]
请按照格式反馈 issue，提供足够的信息。

**Comment by cyclestudy** [comment]
> > 一个插件只能对应一个客户端，在两个客户端都开启 socks5 就无法使用
> 
> 可以的。可以根据端口号随意切换不同的代理服务

两个客户端都是 socks5 无法工作

**Comment by Adsryen** [comment]
搞不懂，为啥还是要一个个机器上去修改客户端的配置，就不能 参考nps，客户端只负责连接服务端，所有配置都由服务端的管理界面把控？
这项目一出来我就用了半年，个人用也就很麻烦，还在用停更的nps

如：
https://github.com/ehang-io/nps
https://github.com/snail007/goproxy

**Comment by superzjg** [comment]
> 搞不懂，为啥还是要一个个机器上去修改客户端的配置，就不能 参考nps，客户端只负责连接服务端，所有配置都由服务端的管理界面把控？ 这项目一出来我就用了半年，个人用也就很麻烦，还在用停更的nps
> 
> 如： https://github.com/ehang-io/nps https://github.com/snail007/goproxy

最开始架构就定好了，项目已经相对成熟，中途改架构需要大量精力修改代码，开源项目没什么收入，作者不停更就不错了。

**Comment by xqzr** [comment]
> 就不能 参考nps，客户端只负责连接服务端，所有配置都由服务端的管理界面把控？

https://github.com/fatedier/frp/issues/4444#issuecomment-2363834160
