### ISSUE TITLE
Protocol support

### ISSUE THREAD

**Issue by tymoshh** [fatedier/frp#4555]
### Describe the feature request

Does frp support TCP+UDP mode?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
Yes.
