### ISSUE TITLE
frpc启动成功，但是穿透失败

### ISSUE THREAD

**Issue by sagexy** [fatedier/frp#456]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.13.0

**What operating system and processor architecture are you using (`go env`)?**
server:Centos 6 x86  
client:synology nas DS216+II

**Configures you used:**
frps.ini 
![a3b85d06-2961-40d8-9a17-181b7884ba9b](https://user-images.githubusercontent.com/4734448/30191100-470b0276-9471-11e7-81a2-03583c32fc49.png)

frpc.ini
![c5d3a0ba-4068-4be7-a19c-82c8b69d2e2e](https://user-images.githubusercontent.com/4734448/30191161-9643ac12-9471-11e7-88e1-9fad47ac5760.png)

**Steps to reproduce the issue:**
1.服务器端配置后启动成功

![1ee8bce3-f9c5-4b57-9286-4ac3372bf26e](https://user-images.githubusercontent.com/4734448/30191200-e1bea48a-9471-11e7-89e7-8444a84dbfe2.png)
2.**群晖nas通过docker安装了frpc配置后启动成功，以下是docker的日志**
![754a9362-4e29-4f80-8815-40a7915abbf9](https://user-images.githubusercontent.com/4734448/30191240-1e57e082-9472-11e7-90af-6eab0bf1f740.png)

3.服务端frp控制台显示正常
![dd9f5643-b308-4c2b-a7ce-9f9ec229dd61](https://user-images.githubusercontent.com/4734448/30191271-4bac1562-9472-11e7-85c6-0df1d07a2165.png)

**Describe the results you received:**

服务端绑定的vhost_http_port = 88 所以浏览器中用 域名:88 该地址无法访问
![05ba27c7-d76c-4d23-b71b-2bb65a3285d6](https://user-images.githubusercontent.com/4734448/30191349-e4090702-9472-11e7-8c26-11e10e375f5f.png)

另外aria2 rpc也远程失败

**Describe the results you expected:**
我用域名:88访问的话 正常应该是显示群晖nas的控制台界面

正常远程aria2

**Additional information you deem important (e.g. issue happens only occasionally):**
有一段时间我服务端vhost_http_port绑定的80端口 然后直接通过域名访问 可以打开群晖的控制台界面，但是过了一段时间又打不开了

**Can you point out what caused this issue (optional)**
我感觉是不是我frpc.ini的某些参数配置错误导致的？另外是不是每次修改了frpc.ini 群晖都需要重启一下

**Comment by GeorgeYuen** [comment]
不需要重启，建议直接使用docker来安装在群晖上。

**Comment by sagexy** [comment]
@GeorgeYuen 我就是直接通过docker安装的frp 但是不知道哪里配置错了 导致穿透失败

**Comment by GeorgeYuen** [comment]
@sagexy 你frp的网络模式选择错误了。应该选择host模式。
就是这种时候选择和主机相同。

**Comment by sagexy** [comment]
@GeorgeYuen host模式是应该怎么搞的？ 具体我应该怎么修改frps.ini和frpc.ini?

**Comment by GeorgeYuen** [comment]
docker启动frp的时候选择高级设置-网络
使用与docker host相同的网络。哪里打勾

**Comment by sagexy** [comment]
@GeorgeYuen 打钩了 也新建了一个启动了
![1504849540863](https://user-images.githubusercontent.com/4734448/30197717-1205fd76-949c-11e7-8160-3319099e3bec.jpg)
docker日志里也显示start proxy success

但是通过 域名:88 还是访问不了

我的frpc.ini设置
![1504849700031](https://user-images.githubusercontent.com/4734448/30197760-6827e19c-949c-11e7-9912-a337e39597d3.jpg)

这里有没有问题呢？

**Comment by GeorgeYuen** [comment]
把local_ip去掉试试看

**Comment by sagexy** [comment]
local_ip去掉也不行
填127.0.0.1和局域网ip都不行
嗨 好纠结 大神 我还有哪里有问题

**Comment by sagexy** [comment]
@GeorgeYuen 经过仔细研究中文说明文档后 我发现我的域名解析地址出错了 应该指向我的frp的远程服务器ip，结果默认synology.me指向的是外网ip
