### ISSUE TITLE
如何让与frpc同子网的用户能够连接到socks5插件？

### ISSUE THREAD

**Issue by Felix-Bao** [fatedier/frp#4560]
### Bug Description

frpc的socks5插件作为简易的socks服务端非常稳定，但只能是对frps侧使用。如何令与frpc同子网的用户也能连接到socks5插件，比如frpc所在服务器为192.168.100.5，那么192.168.100.6的用户使用Proxifier之类的工具如何连接到socks5插件？我应该开放192.168.100.5服务器上的哪些端口，或者需要映射哪些端口？

### frpc Version

0.51.3

### frps Version

0.53.2

### System Architecture

frps linux/amd64      frpc linux/mipsle

### Configurations

config conf
	option name 'Test_Socks5'
	option type 'tcp'
	option use_encryption 'false'
	option use_compression 'false'
	option remote_port '10666'
	option plugin 'socks5'
	option plugin_user 'username'
	option plugin_passwd 'userpassword'

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
frp 针对的是内网穿透的场景，你的需求建议使用专业的 socks5 应用或工具。
