### ISSUE TITLE
[Feature Request]port forward

### ISSUE THREAD

**Issue by ufoozhenghao** [fatedier/frp#4562]
### Describe the feature request

need feature:
tcp connect to server_ip and server_port  redirect to client_port

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
> client_port

这是什么？frp 没有这个

**Comment by dj0106** [comment]
Hi @ufoozhenghao 

Can you please assign this issue to me ?
