### ISSUE TITLE
custom404Page  配置怎么使用

### ISSUE THREAD

**Issue by Tommu10ve** [fatedier/frp#4564]
### Bug Description

custom404Page  配置怎么使用

### frpc Version

0.61

### frps Version

0.61

### System Architecture

linux/amd64

### Configurations

11

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Please refer to the documentation and search for configuration examples in the project repository.
