### ISSUE TITLE
[Feature Request] 增加服务器端负载均衡的需求

### ISSUE THREAD

**Issue by qinxingguan** [fatedier/frp#4567]
### Describe the feature request

我在搭建服务器环境时，对两台服务器同时部署了caddy和frps，域名a.xx.xx同时解析到这两台服务器上，当用户访问时会就地最近的dns解析到指定的一台服务器上，经过caddy web服务器进行反向代理到frps的http请求8880端口上，再经过frps查找内网服务，我需要如何实现一个frpc客户端同时连接两台frps服务呢，或者我用一个域名进行解析到两台frps服务器上在客户端配置serverAddr时使用这个域名，frpc客户端就近连接到最近dns的frps服务器上，在caddy内配置了负载均衡并检测后端服务是否存活时始终能返回frps默认的404内容使得caddy无法判断服务是否异常始终会在正常的frps和不正常的frps直接进行负载均衡连接，有什么方式可以实现frpc客户端未注册到的frps不返回任何内容吗？直接让其无法进行连接。

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
> 实现frpc客户端未注册到的frps不返回任何内容吗？

浏览器会报错。TCP 连接成功，浏览器就不会尝试下一个地址
