### ISSUE TITLE
[Feature Request] fallback for http plugin

### ISSUE THREAD

**Issue by aa51513** [fatedier/frp#4570]
### Describe the feature request

```
[[proxies]]
name = "dev"
type = "http"
localIP = "127.0.0.1"
localPort = 80
customDomains = ["dev.server.com"]
```

When 127.0.0.1:80 cannot be accessed, automatically transfer requests to the configured alternate address.

### Describe alternatives you've considered

What I mean is that when encounter a 404 or 500 series error code,  move to an alternate address.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
Currently, frp's focus is not on various Layer 7 proxy capabilities. For functionalities in this area, we recommend using other tools like nginx.

**Comment by aa51513** [comment]
> Currently, frp's focus is not on various Layer 7 proxy capabilities. For functionalities in this area, we recommend using other tools like nginx.

ok,thank you for your reply
