### ISSUE TITLE
[Feature Request] When I add or delete configurations to frpc, can it take effect without restarting or reloading the service?

### ISSUE THREAD

**Issue by wangkai111111** [fatedier/frp#4571]
### Describe the feature request

When changing configurations, adding, or removing, is it unnecessary to restart or reload the service, allowing other connections to remain active?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by wuai1024** [comment]
```bash
frpc -s reload
```

哈哈

**Comment by xqzr** [comment]
https://gofrp.org/zh-cn/docs/features/common/client/#%E5%8A%A8%E6%80%81%E9%85%8D%E7%BD%AE%E6%9B%B4%E6%96%B0

**Comment by wangkai111111** [comment]
thank you!
