### ISSUE TITLE
[Feature Request] ad-hoc or long-lived (persistent) connections to target?

### ISSUE THREAD

**Issue by ofirc** [fatedier/frp#4573]
### Describe the feature request

In the typical setup of:
client -> frps -> frpc -> private service (e.g. web server)

Does the frp client (frpc) keep a persistent connection to the (target) private service or is it ad-hoc, i.e. every time the client wants to contact the private service (through frps -> frpc) it will open a new socket (and close it later)?
What's the default, is it configurable via the [toml](https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml)?

Thanks!

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by fatedier** [comment]
For TCP proxy, the connections are 1:1. For HTTP, the default Golang HTTP connection pool is used and it is not configurable.

**Comment by ofirc** [comment]
Thanks @fatedier!
I have a setup where I need to demultiplex a single proxy connection into multiple targets.
So given a setup like the following:
client -> frps -> frpc -> targetA
client -> frps -> frpc -> targetB
client -> frps -> frpc -> targetC

And given my restriction that the frp client (frpc) has to be connected to a single target, I was thinking of re-architecting the setup to the following:
client -> frps -> frpc -> [Caddy](https://caddyserver.com/) -> targetA

Caddy can be used for the following scenarios:
1. As a reverse proxy [SNI-based routing](https://github.com/fatedier/frp/issues/4558) - if `targetA` and `targetB` are different hostnames
2. As a forward proxy with port demultiplexing - if `targetA` and `targetB` are the same hostname/IP but differ by their port, then the proxy will see the `CONNECT` request and setup the tunnel to the target

The final targets, i.e. `targetA`, `targetB` are always HTTPS targets.

I'm wondering whether this is too complex or whether there are some gotchas that I missed before I start prototyping.

**Comment by ofirc** [comment]
Thanks @fatedier for the prompt response!
