### ISSUE TITLE
frpc 连接服务端是否可以设置走UDP？

### ISSUE THREAD

**Issue by ansonken** [fatedier/frp#4575]
### Bug Description

我想实现frpc 连接frps 的时候走UDP 端口，主要因为我的vps ，TCP 端口都被封了。只有TCP 443端口和80可用，还有就是UDP 端口可以用。

### frpc Version

v0.61.0

### frps Version

v0.61.0

### System Architecture

ubuntu

### Configurations

bindAddr = "0.0.0.0"
bindPort = 8081
quicBindPort = 8082
kcpBindPort = 8083
transport.maxPoolCount = 5
log.to = "/data/frp_0.61.0_linux_amd64/frps.log"
log.level = "info"
log.maxDays = 3
auth.method = "token"

### Logs

2024-12-06 14:41:22.685 [W] [client/service.go:298] connect to server error: dial tcp   xxxx:8081: i/o timeout
2024-12-06 14:41:22.685 [I] [sub/root.go:160] frpc service for config file [/root/frp_0.61.0_linux_amd64/frpc.toml] stopped

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/issues/4572#issuecomment-2518116808
