### ISSUE TITLE
测试frpc出现串台的问题 , 访问b网站会串到a网站去

### ISSUE THREAD

**Issue by 9844201** [fatedier/frp#4581]
### Bug Description

出现的问题 ,linux服务器 frpc.toml配置,里面有一个顶级域名 和 两个子域名,分别是mirror.test.com blog.test.com 两个域名DNS都解析到 frps服务器的IP上去, mirror.test.com是linux 服务器docker里的mirror服务( http 和 https), blog.test.com 是linux 服务器docker里的blog服务 (http 和 https), 安装好测试环境后 测试 浏览器不停的切换 mirror.test.com 和blog.test.com 访问  发现有时候访问blog.test.com 跑到了mirror.test.com的服务里面 (打开了mirror.test.com的网页),当frpc出现 重新登录的时候日志出现 login to server success, get run id [f8046635a787edcb]的时候或者重启frpc client去刷新blog.test.com 发现又正常的返回了 blog.test.com 服务的http页面 , 就是说出现了串台一样的现象,不知道是哪里的问题,请大佬解惑

### frpc Version

0.61.0

### frps Version

0.61.0

### System Architecture

linux/amd64 & windows/amd64

### Configurations

serverAddr = "hk1.frpsserver.net" # 这里假设服务器IP,服务器是用网上免费的 但是我自己搭建了服务器测试 也是一样的串台
serverPort = 7000
auth.method = "token"
auth.token = "123456"
user = "test"

log.to = "/tmp/logs/frpc.log"
# trace, debug, info, warn, error
log.level = "trace"
log.maxDays = 3
log.disablePrintColor = false

[[proxies]]
name = "blog"
type = "http"
localIP = "172.17.0.4" #docker blog 内网服务的IP
localPort = 80
customDomains = ["blog.test.com"]
subdomain = "blog"

[[proxies]]
name = "ssl.blog"
type = "https"
localIP = "172.17.0.4" #docker blog 内网服务的IP
localPort = 443
customDomains = ["blog.test.com"]

[[proxies]]
name = "mirror"
type = "http"
localIP = "172.17.0.6" #docker mirror 内网服务的IP
localPort = 80
customDomains = ["mirror.test.com"]

[[proxies]]
name = "ssl.mirror"
type = "https"
localIP = "172.17.0.6" #docker mirror 内网服务的IP
localPort = 443
customDomains = ["mirror.test.com"]

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
同时只能配置一个http，或者https
要配置多个请使用tcp

**Comment by Yiomo** [comment]
我也遇到了一样的问题，不知道现在有没有解决方法
