### ISSUE TITLE
frps监听ipv6:7000端口,无法监听ipv4:7000端口

### ISSUE THREAD

**Issue by Evergarden-Alan** [fatedier/frp#4585]
### Bug Description

在frps端配置好启动后,日志显示正常监听ip:7000端口,但是使用netstat -tuln | grep 7000查看,监听的是ipv6的7000端口,没有监听ipv4的7000端口.而后导致frpc无法连接到frps,日志显示"connect: no route to host"

### frpc Version

0.61.0

### frps Version

0.61.0

### System Architecture

linux/amd64

### Configurations

# frpc
serverPort = 7000

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6022

[[proxies]]
name = "cloud"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8880
remotePort = 8880

[[proxies]]
name = "dmzs"
type = "tcp"
localIP = "127.0.0.1"
localPort = 5001
remotePort = 5001

[[proxies]]
name = "dmz"
type = "tcp"
localIP = "127.0.0.1"
localPort = 5000
remotePort = 5000

[[proxies]]
name = "home"
"/usr/local/frp/frpc.toml" 41L, 532B                                                                                 
serverAddr = "IP"
serverPort = 7000

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6022

[[proxies]]
name = "cloud"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8880
remotePort = 8880

[[proxies]]
name = "dmzs"
type = "tcp"
localIP = "127.0.0.1"
localPort = 5001
remotePort = 5001

[[proxies]]
name = "dmz"
type = "tcp"
localIP = "127.0.0.1"
localPort = 5000
remotePort = 5000

[[proxies]]
name = "home"
type = "tcp"
localIP = "127.0.0.1"
localPort = 80
remotePort = 6080

#frps: 

bindPort = 7000
bindAddr = "0.0.0.0"
vhostHTTPPort = 8080
vhostHTTPSPort = 443

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"
                                                                       

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
不太可能，要是这样不早就炸锅了。检察你的配置、防火墙等
frps日志显示 `frps tcp listen on 0.0.0.0:7000` 就表示同时监听ipv4/ipv6。

**Comment by zhohg789** [comment]
解决了吗？使用阿里云服务器也遇到这个问题了

**Comment by tt-haogege** [comment]
遇到了同样的问题服务器防火墙已开但是还是监听的v6地址

**Comment by ALLinLLM** [comment]
遇到了同样的问题服务器防火墙ipv4端口已开，但是还是监听的ipv6地址，不通

**Comment by Frankr0** [comment]
同样的问题

**Comment by xxszwz** [comment]
我遇到了转发端口不监听ipv4的问题
lsof -i :27015
COMMAND   PID USER FD   TYPE DEVICE SIZE/OFF NODE NAME
frps    12898 root 9u  IPv6  27112      0t0  UDP *:27015
