### ISSUE TITLE
reload 参数无效

### ISSUE THREAD

**Issue by Hareis** [fatedier/frp#459]
`admin_addr = 127.0.0.1  

admin_port = 7001  

admin_user = admin  

admin_pwd = admin`

在 frpc 最新的 release 版本中启用这个功能
然后再启动参数后面加上了 --reload 参数
出现了如下错误
`frpc reload error: Get http://127.0.0.1:7001/api/reload: dial tcp 127.0.0.1:7001: connectex: No connection could be made because the target machine actively refused it.`
求人帮助下
目录下文件有：
1. frpc.exe
2. frpc.ini
3. frps.ini

[](url)

**Comment by henjue** [comment]
+1
