### ISSUE TITLE
Windows Defender：“这个程序很危险，而且执行来自攻击者的命令。”

### ISSUE THREAD

**Issue by cassuto** [fatedier/frp#4591]
### Bug Description

从release链接下载[frp_0.61.1_windows_amd64.zip](https://github.com/fatedier/frp/releases/download/v0.61.1/frp_0.61.1_windows_amd64.zip)，立刻被检测为恶意程序。

有没有可能是误报了？

已检测的项目：Trojan:Script/Sabsik.FL.A!ml
file: C:\Users\xxxx\Downloads\frp_0.61.1_windows_amd64.zip

### frpc Version

0.61.1

### frps Version

0.61.1

### System Architecture

windows/amd64

### Configurations

从release链接下载[frp_0.61.1_windows_amd64.zip](https://github.com/fatedier/frp/releases/download/v0.61.1/frp_0.61.1_windows_amd64.zip)

Windows 11 22631.4460
Microsoft Edge 版本 131.0.2903.99 

### Steps to reproduce

1. 用Edge从release链接下载[frp_0.61.1_windows_amd64.zip](https://github.com/fatedier/frp/releases/download/v0.61.1/frp_0.61.1_windows_amd64.zip)
2. 等待

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by minesunny** [comment]
close windows defender

**Comment by cassuto** [comment]
I switched to v0.61.0, no more Defender warnings.

**Comment by adokshaj-sclera** [comment]
@cassuto 

v0.61.0 is also being classified as a threat.

Tested using:
Google Chrome
Windows 10 w/ Windows Defender enabled

------

Disabling Windows Defender is not the right solution as well.
