### ISSUE TITLE
frp是否支持Server Sent Events(SSE)? 

### ISSUE THREAD

**Issue by sdaduanbilei** [fatedier/frp#4594]
### Bug Description

frpc 配置
```
serverAddr = ""
serverPort = 
auth.method = ""
auth.token = ""

[[proxies]]
name = "wt-28-api"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8888
remotePort = 6989
```

nginx 配置
```
location /api/ {
        proxy_pass http://apiproxy/;
        proxy_set_header Host $host;
        proxy_pass_header Set-Cookie;
        proxy_redirect http://$host/ http://$http_host/;
        proxy_ssl_server_name on;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
        add_header X-Accel-Buffering "no";
    }
  ```

结构为前后分离项目，前端部署在云服务器上，但是服务器性能不行所以通过frp 配置本地服务器提供后端服务，目前接口都已经正常访问，唯独 Server Sent Events(SSE) 一直未响应

### frpc Version

frp_0.61.1_linux_amd64

### frps Version

frp_0.61.1_linux_amd64

### System Architecture

linux/amd64

### Configurations

1

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by sdaduanbilei** [comment]
@fatedier 求指导

**Comment by sdaduanbilei** [comment]
已经解决，确认可以支持 sse

**Comment by Starix610** [comment]
> 已经解决，确认可以支持 sse

请问你是怎么配置的呢
