### ISSUE TITLE
windows frps 每次建立请求都需要按enter按键

### ISSUE THREAD

**Issue by better-TT** [fatedier/frp#4608]
### Bug Description

windows frps 每次建立请求都需要按enter按键

### frpc Version

0.61.1

### frps Version

0.61.1

### System Architecture

windows/amd64

### Configurations

bandport = 6000

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
没有明白你的意思？
frps可以搭配工具，直接注册windows服务运行
