### ISSUE TITLE
[Feature Request] 是否可以支持 TCP Brutal 阻塞控制算法

### ISSUE THREAD

**Issue by mz289** [fatedier/frp#4609]
### Describe the feature request

https://github.com/apernet/tcp-brutal

### Affected area

- [x] Docs
- [ ] Installation
- [x] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
不支持。
