### ISSUE TITLE
[Feature Request] 有咩有必要增加多文件配置支持

### ISSUE THREAD

**Issue by zzc1231** [fatedier/frp#4613]
### Describe the feature request

类似nginx 支持扫描指定位置的多个配置文件
全部都在一个文件里容易误操作影响到其他的转发

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by wuai1024** [comment]
有没有可能这个已经支持了。

[请看](https://gofrp.org/zh-cn/docs/features/common/configure/)

![image](https://github.com/user-attachments/assets/55810108-d0ec-4c11-8b48-be4a5f4d569c)

**Comment by zzc1231** [comment]
哦哦好的 我一直没找到呢
