### ISSUE TITLE
frp编译报错  go 1.9  centos

### ISSUE THREAD

**Issue by zdj0925** [fatedier/frp#462]
zhaodj@localhost frp-master]$ make frpc
go build -o bin/frpc ./cmd/frpc
# _/home/zhaodj/frp-master/cmd/frpc
cmd/frpc/main.go:77:59: cannot use conf (type "github.com/vaughan0/go-ini".File) as type "github.com/fatedier/frp/vendor/github.com/vaughan0/go-ini".File in argument to config.LoadClientCommonConf
cmd/frpc/main.go:159:81: cannot use conf (type "github.com/vaughan0/go-ini".File) as type "github.com/fatedier/frp/vendor/github.com/vaughan0/go-ini".File in argument to config.LoadProxyConfFromFile
make: *** [frpc] 错误 2
[zhaodj@localhost frp-master]$ go version
go version go1.9 linux/amd64
[zhaodj@localhost frp-master]$

**Comment by fatedier** [comment]
确认项目被放到了正确的目录下。

**Comment by zdj0925** [comment]
自己回答一下，遇到这个问题。
打开文件Dockerfile
[zhaodj@localhost frp]$ cat Dockerfile
FROM golang:1.8

COPY . /go/src/github.com/fatedier/frp    #frp存放路径

RUN cd /go/src/github.com/fatedier/frp \
 && make \
 && mv bin/frpc /frpc \
 && mv bin/frps /frps \
 && mv conf/frpc.ini /frpc.ini \
 && mv conf/frps.ini /frps.ini \
 && make clean

WORKDIR /

EXPOSE 80 443 6000 7000 7500

ENTRYPOINT ["/frps"]
