### ISSUE TITLE
Ubuntu下连接服务器显示 i/o timeout

### ISSUE THREAD

**Issue by 337268759** [fatedier/frp#463]
Ubuntu下连接服务器显示 2017/09/14 12:03:45 [W] [control.go:121] login to server failed: i/o timeout

**Comment by touzi** [comment]
我在 windows 下也遇到了这个问题.

**Comment by imu-hupeng** [comment]
read tcp 172.31.6.24:443->119.137.55.7:25329: i/o timeout
