### ISSUE TITLE
frpc 能否增加dbus 通信或者lib库形式让其他程序调用

### ISSUE THREAD

**Issue by yuxue521** [fatedier/frp#468]
如果使用 dbus 通信  方便其他程序调用 lib方式也是一样 
公司项目 使用c++ 开发 目前只能通过执行命令方式 运行

如果使用 dbus 方式 建立信号这样 就可以实时的看到状态 软件来进行处理
lib 库形式也是一样 其他程序通过接口 调用

**Comment by fatedier** [comment]
不熟悉，目前没有这个计划。
