### ISSUE TITLE
请问，frps服务器端，只有启动命令吗？停止和重启命令用什么？找了半天没找到。

### ISSUE THREAD

**Issue by hxf3591126** [fatedier/frp#469]
请问，frps服务器端，只有启动命令吗？

停止和重启命令用什么？找了半天没找到。

**Comment by wl56012102** [comment]
nohup启动然后ps -e |grep frps找pid kill掉

**Comment by zengxiao2009** [comment]
楼上说的方法 我也是那个方面 自已写一个SH 就可以

**Comment by XiLingHost** [comment]
你可以试试自己写个init.d脚本来作为服务启动，这样可以直接用linux自带的daemon管理来启动/重启/停止服务
