### ISSUE TITLE
客户端出错 “Parse conf error: proxy [commmon] remote_port not found”

### ISSUE THREAD

**Issue by izhaoo** [fatedier/frp#471]
# 问题说明
类似 #368 
服务端配置正常，客户端出错。
提示：Parse conf error: proxy [commmon] remote_port not found
# 环境
版本：0.13.0
服务端：ubuntu 16.04        客户端：树莓派3
# 配置
frpc.ini:
[commmon]
server_addr = x.x.x.x
server_port = 7000 
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000
[web]
type = http
local_port = 80
custom_domains = frp.izhaoo.com

frps.ini:
[common]
bind_port = 7000
vhost_http_port = 8080
dashboard_port = 7500
dashboard_user = xxx
dashboard_pwd = xxx

**Comment by flfq** [comment]
我也是同样的问题

检测发现，启用的是tcp6的端口，而不是tcp4的端口
客户端连接就报上面的错误

**Comment by Hyduan** [comment]
commmon?

**Comment by fatedier** [comment]
拼写错误。

**Comment by Tinywan** [comment]
是呀，配置文件少一个 `[common]`
