### ISSUE TITLE
v0.13.0的windows客户端读取的是frps.ini,应该读取frpc.ini

### ISSUE THREAD

**Issue by JackMou** [fatedier/frp#474]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
./frpc -v
v0.13.0

**What operating system and processor architecture are you using (`go env`)?**
启动windows客户端,提示open ./frps.ini The system can't find.....
把frpc.ini改名为frps.ini 启动就正常了

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by tangyouze** [comment]
mac下同样的问题 需要./frpc -c ./frpc.ini 才能运行

**Comment by vizv** [comment]
https://github.com/fatedier/frp/blob/066172e9c13945241ff114320689b0c9b6d20fbd/cmd/frpc/main.go#L63

**Comment by fatedier** [comment]
#405 中已经提及，这里重复了， 下个版本发布的时候会顺便修改，另外推荐加上 '-c' 参数，因为以后不填配置文件可能会全部使用默认值而不是读取默认配置文件。
