### ISSUE TITLE
服务端客户端无法正常连接

### ISSUE THREAD

**Issue by AricOzem** [fatedier/frp#475]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.13

**What operating system and processor architecture are you using (`go env`)?**
Sever: linux amb64 client linux armv71 (raspi)

**Configures you used:**
frps.ini
[common]
bind_port = 7000
vhost_https_port = 2334
dashboard_port = 7500
dashboard_user = xxxx
dashboard_pwd = xxxx
privilege_token = xxxxxxxx
[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 2334
privilege_token = xxxxxxxx
[web]
type = http
local_ip = 127.0.0.1
local_port = 80
use_encryption = false
use_compression = true
custom_domains = xxx.xxxx.xxx
**Steps to reproduce the issue:**
1. ./frps -c ./frps.ini
2. ./frpc -c ./frpc.ini

**Describe the results you received:**
client:  [W] [control.go:121] login to server failed: broken pipe
sever:  [W] [vhost.go:129] get hostname from http/https request error: readHandshake: proto length[8] is too short

**Describe the results you expected:**
正常工作
**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue **

PS:是我犯蠢看错文档了么

**Comment by fatedier** [comment]
你要用 vhost_http_port 这个配置就可以了，不是 https 的请求。
