### ISSUE TITLE
我的客户端和服务端配置有错误吗？

### ISSUE THREAD

**Issue by hijk1234** [fatedier/frp#476]
frps.ini
[common]
bind_port = 7000
kcp_bind_port = 7000
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin
privilege_mode = true
privilege_token = 12345678
tcp_mux = true
log_file = ./frps.log
log_level = info
log_max_days = 3

frpc.ini
[common]
server_addr = 103.242.25.60
server_port = 7000
type = kcp
privilege_token = 12345678
tcp_mux = true
admin_addr = 127.0.0.1
admin_port = 7400
admin_user = admin
admin_pwd = admin
log_file = ./frpc.log
log_level = info
log_max_days = 3

[r1]
type = tcp
local_ip = 127.0.0.1
local_port = 1953
remote_port = 1953
privilege_mode = true 
authentication_timeout = 0 
use_encryption = true 
use_gzip = true 

[r2]
type = tcp
local_ip = 127.0.0.1
local_port = 36952
remote_port = 36952
privilege_mode = true 
authentication_timeout = 0 
use_encryption = true 
use_gzip = true

**Comment by hijk1234** [comment]
不知道那个KCP协议客户端和服务端有没有设置错，感觉好像没有起到加速作用...............

**Comment by hijk1234** [comment]
frp所有版本都存在一个问题，当一个tcp连接死了后，frp没有能力及时检测出来。通俗的来讲就是frp无法及时感知tcp连接的健康状态。这样就会导致，假死连接。只要手动去点一下，这个tcp连接才会释放。然后过一段时间才会重新连接上来。当同时有几百个用户连接过来后，这个问题会导致服务端感觉特别乱，基本没办法使用了。这个问题1年前和作者提过，到现在也没有解决掉。

**Comment by fatedier** [comment]
https://github.com/fatedier/frp#support-kcp-protocol
