### ISSUE TITLE
编译安装错误

### ISSUE THREAD

**Issue by glkhg** [fatedier/frp#477]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
最新master版(截至 20171002)

**What operating system and processor architecture are you using (`go env`)?**
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/forward/tools/gopkg"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build985044916=/tmp/go-build -gno-record-gcc-swit
ches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
编译安装报错
cmd/frps/main.go:63:59: cannot use conf (type "github.com/vaughan0/go-ini".File) as type "github.com/fatedier/frp/vendor/github.com/vaughan0/go-ini".File in argument to config.LoadServerCommonConf
make: *** [frps] Error 2
make error

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
一般是项目路径放的不对。直接 go get 下载，然后进去 make 编译。

**Comment by w568856** [comment]
我编译也是这个问题

**Comment by glkhg** [comment]
作者是用什么系统开发的，go env环境是什么？ @fatedier

**Comment by fatedier** [comment]
可以参考 travis 的编译流程。
