### ISSUE TITLE
请教一个vhost的问题

### ISSUE THREAD

**Issue by wdc63** [fatedier/frp#479]
请问frps是否支持不同的http vhost一部分使用本地服务例如lamp，另一部分则由frps转发到第三方如内网服务器上。如果lamp的vhost和frp的vhost域名重名冲突了会出现什么情况？谢谢

**Comment by vizv** [comment]
httpd 和 frp 所监听的端口不能冲突，要想一起用的话在 httpd 上做个代理并且设置相应的 `Host` header.

**Comment by wdc63** [comment]
谢谢，通过nginx解决了。
