### ISSUE TITLE
关于http_proxy配置疑问

### ISSUE THREAD

**Issue by GithubCheewah** [fatedier/frp#481]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.13.0

**What operating system and processor architecture are you using (`go env`)?**
Server: Windows 2008 R2
Client: 1.极路由
          2. WIndows 10

**Configures you used:**

frps.ini
[common] 
bind_addr = 0.0.0.0 
bind_port = 9997 
vhost_http_port = 9998 
vhost_https_port = 443 
dashboard_port = 9990 
dashboard_user = ************
dashboard_pwd = ************
log_max_days = 7 
privilege_mode = true 
privilege_token = ************
privilege_allow_ports = 1-65535 
max_pool_count = 100 
log_file = frps.log 
log_level = info 

frpc.ini
[common] 
server_addr = ************
privilege_token = ************
server_port = 9997 
log_file = frpc.log 
log_level = info 
log_max_days = 7 

[tcp_9417] 
type = tcp 
remote_port = 9995 
local_port = 80 
privilege_mode = true 
authentication_timeout = 0 
use_encryption = true 
use_gzip = true 
plugin = http_proxy

**Steps to reproduce the issue:**
在澳门工作, 想网易客户端通过Proxifier代理极路由上的frpc http proxy 听歌
1. 按照官方教程 http_proxy 並不需要填本地端口
但不填入 local_port 启动frpc 会提示 local_port not found
填入local_port后有变成转发端口

**Comment by fatedier** [comment]
先参考 https://github.com/fatedier/frp#connect-website-through-frpcs-network 用最简单的配置尝试下，同时确保 frpc 使用最新的版本。

**Comment by GithubCheewah** [comment]
两边都是0.13.0
用了最简单的模式

Server frps.ini

[common] 
bind_port = 9991

Client frpc.ini
[common] 
server_addr = 202.86.135.98 
server_port = 9991 

[tcp_proxy] 
type = tcp
remote_port = 9993
plugin = http_proxy

frpc.exe -c frpc.ini
仍提示 proxy [tcp_proxy] local_port not found

**Comment by fatedier** [comment]
换其他系统试试看，我本地测试没问题。

**Comment by GithubCheewah** [comment]
之前下载的是amd64.. 用了x86的版本没事了
