### ISSUE TITLE
frp自动停止并导致系统无法ssh

### ISSUE THREAD

**Issue by SuPerCxyz** [fatedier/frp#482]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.13.0

**What operating system and processor architecture are you using (`go env`)?**
centos7_mini_x86_64_1708

**Configures you used:**
[common]
server_addr = xxxxx.xxxx.xxxx
server_port = 7000

[ssh_home]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6001

**Steps to reproduce the issue:**
1.可以正常启动 运行一段时间后失去连接，直接导致系统也无法ssh
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
没有任何信息无法分析原因。

**Comment by SuPerCxyz** [comment]
能告知一下错误日志在哪吗？  message里面看不到任何frp的错误

**Comment by fatedier** [comment]
你应该尽量提供你能获取到的所有的信息，从你的描述中我甚至看不出是 frpc 还是 frps 有问题。

错误日志取决于你的配置，有参数可以指定。

**Comment by SuPerCxyz** [comment]
麻烦请问一下打开日志的配置怎么写？frps机器一直没用问题，其他的frpc与frps连接没有问题，唯独只有一台机器有这样的问题。

**Comment by Yrr0r** [comment]
检查文档啊，里面写的非常清楚，中英文的都有

**Comment by SuPerCxyz** [comment]
get  一开始直接搜索错误日志关键词没找到  刚发现在另一个链接里
