### ISSUE TITLE
socks5代理插件用户名密码设置

### ISSUE THREAD

**Issue by axelburks** [fatedier/frp#484]
麻烦问一下 
socks5插件
设置代理用户名和密码的参数是什么？
按照http代理插件的设置方式不行
plugin = socks5
plugin_socks5_user = abc
plugin_socks5_passwd = deffff

**Comment by fatedier** [comment]
目前尚不支持用户名和密码设置。

**Comment by suisr9255** [comment]
还有 使用socks5插件无法穿透访问路由器的web管理界面，使用http代理插件倒是可以……

**Comment by jeffli678** [comment]
@fatedier 建议能添加这个功能～如果我没记错，socks5的认证不是很复杂。有了用户名密码会安全一些，不然设置了代理会被扫到，然后挂在网上。

@axelburks 可以先用gost（简单）或者3proxy（功能强）设置有认证的socks5代理，然后用frp转发。

**Comment by shellus** [comment]
为socks5插件增加账号密码认证+1
我在网件路由上使用frp，使用gost之类的socks5再用frp转发，对我来说比较困难。

**Comment by jeffli678** [comment]
@shellus 估计作者会添加的。你现在可以暂时用frp本身的功能做一个socks代理，比如vps:port1。然后在vps上设置iptables禁止port1被外网访问。然后在vps:port2用gost或者其他工具设置一个有认证的socks5代理forward到port1上。这样外网可以通过socks://user:passwd@vps:port2访问
