### ISSUE TITLE
小白希望指点下  客户端运行出现  [E] [control.go:267] authorization failed

### ISSUE THREAD

**Issue by ixiamin** [fatedier/frp#488]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
13.0

**What operating system and processor architecture are you using (`go env`)?**
树莓派3b内网   

**Configures you used:**
ssh 等

**Steps to reproduce the issue:**
1.客户端运行frpc -c frpc.ini
出现错误

**Describe the results you received:**
2017/10/19 14:54:09 [E] [control.go:267] authorization failed
2017/10/19 14:54:09 [W] [control.go:121] login to server failed: authorization failed
2017/10/19 14:56:13 [E] [control.go:267] authorization failed
2017/10/19 14:56:13 [W] [control.go:121] login to server failed: authorization failed
2017/10/19 14:56:49 [E] [control.go:267] authorization failed
2017/10/19 14:56:49 [W] [control.go:121] login to server failed: authorization failed

**Describe the results you expected:**
FRPC.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 2200 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
token 设置错误。

**Comment by klin111** [comment]
token  改什么设置可以给个示例吗？
