### ISSUE TITLE
关于kcp协议的问题

### ISSUE THREAD

**Issue by hijk1234** [fatedier/frp#491]
在服务端kcp_bind_port = 7000开启的情况下，客户端protocol = kcp或者tcp，选择kcp或者选择tcp两者之间区别是什么呢？

[tcp_36791]
type = tcp
local_ip = 127.0.0.1
local_port = 36791
use_encryption = true
use_compression = true
remote_port = 36791

比如说只需要转发tcp服务的情况下，protocol后面选哪个更好呢？

**Comment by fatedier** [comment]
网络环境不好的情况下，比如服务器在国外，丢包比较严重，可以选 kcp，kcp 基于 udp 协议，所以如果 tcp 被防火墙禁了，udp 可以用的话也可以选这个。
kcp 协议在丢包时会采取更激进的方式去重复发包，所以流量会增加一些。网络稳定的时候不需要用。
