### ISSUE TITLE
frps和frpc之间的加密方式

### ISSUE THREAD

**Issue by 189dOc** [fatedier/frp#492]
请问下当use_encryption设置为true的情况下, frps和frpc之间是通过哪种加密算法传输数据的呢 (aes-128-cfb)?

**Comment by ihipop** [comment]
https://github.com/fatedier/frp/blob/ad3cf9a64adc67a8d8657b2665571913749645e9/utils/crypto/encode.go#L32

AES-CFB

**Comment by hijk1234** [comment]
多搞几种加密协议供选择也不错啊

**Comment by ihipop** [comment]
这里的加密主要是为了解决一些公司的内网流量识别，他的主要开发目标不是安全代理而是转发程序

**Comment by 189dOc** [comment]
如果是对于ssh/https流量的转发 即使frps与frpc之间不使用加密 应该也能保证数据的安全是吧 (相对于ssh/https直连)

**Comment by ihipop** [comment]
@189dOc 

1. HTTPS 握手过程中，域名并不是加密的，因为需要通过SNI判断使用哪个证书

1. 华为某些带Deep Packet Inspection的路由，会检测包和指定端口的协议是否真的匹配，你要在HTTPS端口上跑SSTP，在一般路由上看是没问题的，那些路由就过不了

1. 不加密和直连没区别

**Comment by 189dOc** [comment]
@ihipop 感谢回复～

**Comment by ihipop** [comment]
@189dOc  更新了一下回复内容。

**Comment by hbxntsxw** [comment]
@ihipop 请问frp的加密能保证http网络传输时输入网站密码的安全性吗？谢谢！

**Comment by RockNHawk** [comment]
同问

> @ihipop 请问frp的加密能保证http网络传输时输入网站密码的安全性吗？谢谢！

同问

**Comment by RockNHawk** [comment]
> @ihipop 请问frp的加密能保证http网络传输时输入网站密码的安全性吗？谢谢！

同问，

> 不加密和直连没区别

也就是说，使用 frp 转发 http ，是能够被 http 工具对流量进行监听的对吗？
