### ISSUE TITLE
作者可否出一套用gomini编译的客户端服务器呐，路由器上很多都是不支持浮点运算的，MT76系列用mipsle的总是显示非法指令，自己编译也有一大堆问题，在网上也找不到很好的编译教程，很喜欢frp，感觉应该花费更多的时间去搭建服务器而不是在编译和处理运行环境上

### ISSUE THREAD

**Issue by yaoyecaizi** [fatedier/frp#497]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
之前有 issue 关联这个问题，需要等 Go 官方解决这个问题。
