### ISSUE TITLE
请问下大神，有frpc的协议文档吗？

### ISSUE THREAD

**Issue by leimiu** [fatedier/frp#498]
如果有其他语言实现的frpc，相信对frp适用更多的场景会有帮助。我想尝试着实现个java版的frpc，想请问下大神，能否提供下frpc的协议细节文档？有文档的话当然比直接扣go代码方便些~

**Comment by fatedier** [comment]
主要的协议格式在 https://github.com/fatedier/frp/blob/master/models/msg/msg.go 这个文件里。

现在还不是太推荐用其他语言去实现，因为版本之间可能改动比较大，协议也会经常变更，等 1.0 比较稳定的版本发布之后会整理一下这些东西。
