### ISSUE TITLE
可以通过ssh访问多台内网机器吗？

### ISSUE THREAD

**Issue by wuzy361** [fatedier/frp#501]
原谅我没有使用固定格式提问问题。我的问题很简单。我现在使用一个阿里云服务器作中转ssh访问内网的一台电脑，现在我又有新的一台电脑需要ssh，我该怎么做？谢谢！

**Comment by ChenHauShen** [comment]
改端口啊


发件人: wuzy361<mailto:notifications@github.com>
发送时间: 2017年10月29日 11:04
收件人: fatedier/frp<mailto:frp@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [fatedier/frp] 可以通过ssh访问多台内网机器吗？ (#501)


原谅我没有使用固定格式提问问题。我的问题很简单。我现在使用一个阿里云服务器作中转ssh访问内网的一台电脑，现在我又有新的一台电脑需要ssh，我该怎么做？谢谢！

―

**Comment by fatedier** [comment]
在新电脑上部署新的 frpc。

**Comment by pastay** [comment]
可以在内网路由器里安装frpc客户端 然后在ini配置文件里做区分 设置不同的remote端口即可
