### ISSUE TITLE
authorization timeout

### ISSUE THREAD

**Issue by terrydash** [fatedier/frp#504]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.12

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
树莓派frpc连接远程WINDOWS 2008下的frps
frpc提示2017/10/29 19:43:10 [E] [control.go:246] authorization timeout
authorization timeout

frps提示Accept new mux stream error: broken pipe
**Describe the results you expected:**

无法联通
**Additional information you deem important (e.g. issue happens only occasionally):**

确认了IP和端口都有没有问题的 且防火墙正常
**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
见文档： https://github.com/fatedier/frp#authentication
服务器和客户端之间的时间差距过大。
