### ISSUE TITLE
路由器http转发失败

### ISSUE THREAD

**Issue by WangSYQM** [fatedier/frp#506]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.13.0

**What operating system and processor architecture are you using (`go env`)?**
router: r6300v2 梅林固件 x7.6
server: vultr debian 8 x64

**Configures you used:**
frps.ini:
[common]
bind_addr = 0.0.0.0
bind_port = xxxx
kcp_bind_port = xxxx

vhost_http_port = 8880
vhost_https_port = 8443

privilege_token = yyyy
max_pool_count = 50
tcp_mux = true

frpc.ini:
[common]
server_addr = aa.aa.aa.aa
server_port = xxxx

privilege_token = yyyy
tcp_mux = true

login_fail_exit = true
protocol = kcp

[router]
type = http
local_ip = 127.0.0.1
local_port = 80
use_encryption = true
use_compression = true
custom_domains = cc.cc.com

**Describe the results you received:**

The page you visit not found.
Sorry, the page you are looking for is currently unavailable.
Please try again later.
The server is powered by frp.
Faithfully yours, frp.

frps.log
[D] [vhost.go:140] http request for host [aa.aa.aa.aa] path [/] not found

**Describe the results you expected:**
view the control panel of my router

**Additional information you deem important (e.g. issue happens only occasionally):**
the status on frps dashboard is online.
I try to change the protocol, use_encryption and use_compression, but nothing improved.

**Comment by fatedier** [comment]
你应该通过 custom_domains 来访问，而不是 server_addr

**Comment by ks55259980** [comment]
@fatedier 多谢 , 刚用还不怎么明白

**Comment by Dakai** [comment]
我现在遇到同样的问题，用custom_domains可以访问没问题，但是是给Plex设置的外网转发，必须要用ip地址登陆一次才Plex才可以成功外网访问，请问这样情况怎么办呢？
