### ISSUE TITLE
建议http协议能够像tcp协议一样根据端口进行区分用户

### ISSUE THREAD

**Issue by vallee11** [fatedier/frp#507]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

frps.ini
[common]
bind_port = 9000
dashboard_port = 9001
dashboard_user = admin
dashboard_pwd = admin
log_level = trace
kcp_bind_port = 9000
privilege_mode = true
privilege_token = 12345678
vhost_http_port = 9002

frpc.ini
[common]
server_addr = 183.131.231.34
server_port = 9000
log_level = trace
protocol = kcp
privilege_token = 12345678
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 9003

[web]
type = http
local_ip = 127.0.0.1
local_port = 80
custom_domains = xxx.xxx.com
use_encryption = true
use_compression = true

**Steps to reproduce the issue:**

1.  当前ssh的登录方式满足需求， 根据frps的不同端口访问不同的frpc的tcp服务。

2.  http的访问接口只有一个 http：//xxx.xxx.com:9002 只能访问到一台服务器， 用二级域名区分用户太费域名了， 路由功能需要改变工程的部署方式。

3.  我当前主要是想基于frp做远程协助功能， http的服务是在很多个用户那边部署， 目的是通过自己的公网服务器穿透用户的内网，控制其http服务。

4.  当前版本的办法只有起多个frps了，这感觉有点不靠谱， 耗费端口，稳定性没法保障

5. 希望vhost_http_port 能够支持不同的用户

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
你的场景 proxy 的类型将 http 换成 tcp 即可。
