### ISSUE TITLE
supervisor配置frpc失败

### ISSUE THREAD

**Issue by xujun05** [fatedier/frp#509]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.13

**What operating system and processor architecture are you using (`go env`)?**
CentOS 6.5

**Configures you used:**
配置frpc 0.13版本，采用frps.ini配置文件(0.13的bug)
手动运行./frpc正常运行,supervisor配置则不行

**Steps to reproduce the issue:**
1.配置supervisor
2.supervisor的部分配置
[program:FRP_Client]
command=/usr/bin/frpc               ; the program (relative uses PATH, can take args)
;process_name=%(program_name)s ; process_name expr (default %(program_name)s)
;numprocs=1                    ; number of processes copies to start (def 1)
;umask=022                     ; umask for process (default None)
;priority=999                  ; the relative start priority (default 999)
autostart=true                ; start at supervisord start (default: true)
startsecs=100                   ; # of secs prog must stay up to be running (def. 1)
startretries=0                ; max # of serial start failures when starting (default 3)
autorestart=unexpected        ; when to restart if exited after running (def: unexpected)
exitcodes=2                 ; 'expected' exit codes used with autorestart (default 0,2)
;stopsignal=QUIT               ; signal used to kill process (default TERM)
;stopwaitsecs=10               ; max num secs to wait b4 SIGKILL (default 10)
;stopasgroup=false             ; send stop signal to the UNIX process group (default false)
;killasgroup=false             ; SIGKILL the UNIX process group (def false)
user=root                   ; setuid to this UNIX account to run the program
redirect_stderr=false          ; redirect proc stderr to stdout (default false)
stdout_logfile=frp.out ;配置路径
stdout_logfile_maxbytes=50MB   ; max # logfile bytes b4 rotation (default 50MB)
stdout_logfile_backups=10     ; # of stdout logfile backups (0 means none, default 10)
;stdout_capture_maxbytes=1MB   ; number of bytes in 'capturemode' (default 0)
;stdout_events_enabled=false   ; emit events on stdout writes (default false)
stderr_logfile=frp.err ;配置路径
stderr_logfile_maxbytes=50MB   ; max # logfile bytes b4 rotation (default 50MB)
stderr_logfile_backups=10     ; # of stderr logfile backups (0 means none, default 10)
;stderr_capture_maxbytes=1MB   ; number of bytes in 'capturemode' (default 0)
;stderr_events_enabled=false   ; emit events on stderr writes (default false)
;serverurl=AUTO                ; override serverurl computation (childutils)
3.supervisor报错，State为**fatal**，Description为**Exited too quickly (process log may have details)**

**Describe the results you received:**
在supervisor.log中发现frpc退出，exit code = 0

**Describe the results you expected:**
frpc正常被supervisor拉起以及维护

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
frpc采用的是daemon模式？

**Comment by fatedier** [comment]
你的问题和 frp 无关，建议自己查阅相关资料解决。
