### ISSUE TITLE
integrate frp into haproxy

### ISSUE THREAD

**Issue by jyf007** [fatedier/frp#512]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
i need for identify frp's tcp shakehand to reverse proxy by haproxy

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.13.0

**What operating system and processor architecture are you using (`go env`)?**
frps linux-amd64
frpc linux-amd64/windows-amd64
**Configures you used:**
tcp_mux = true
only tcp,without kcp

**Additional information you deem important (e.g. issue happens only occasionally):**
i want integrate frp into haproxy for reduce port open on ali ecs.

**Can you point out what caused this issue (optional)**
identify frp's tcp shakehand package for port protocol multiple ,acl by haproxy (1 port open mulitple protocol accept connect)

**Comment by fatedier** [comment]
I don't understand what's your idea. Can you tell more about it?

**Comment by jyf007** [comment]
as an Sysadmin,i want use HAproxy to reserve proxy frp's server tcp port,and i had wrote configure file (/etc/haproxy/haproxy.conf) for others different protocol to reserve proxy by,like ssh or rdp,i want to figure out which tcp shakehand for identify frp's server port .redirect to right tcp port .

**Comment by fatedier** [comment]
Messages between frpc and frps are encrypted, so i'm not sure if you can do this feature.

**Comment by jyf007** [comment]
Or make a new feature,add HAproxy function in frp ,like ngrok issue #518 make frps TCP port multiple protocol port redirect to other protocol like SSH,rdp  and other TLS.
