### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by mymio** [fatedier/frp#513]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.13

**What operating system and processor architecture are you using (`go env`)?**
lede

**Configures you used:**

**Steps to reproduce the issue:**
1.请问frp如何配置samba穿透看传输数据？端口不是标准的情况下。例如tcp 45612 转发 445
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by 599316527** [comment]
不看文档的么？

```
local_port = 445
remote_port = 45612
```

**Comment by mymio** [comment]
不行的，我试过，访问不成功

**Comment by zhu-jiyuan** [comment]
解决没，蹲个答案
