### ISSUE TITLE
0.13.0的mipsel版运行提示Illegal Instruction

### ISSUE THREAD

**Issue by Nick-Hopps** [fatedier/frp#514]
刚开始玩路由的小白，已知是内核中没有开启FPU导致的，用go-mips32重新编译应该就可以了，但是网站的编译方法都好老了，用不了，请问谁能告诉我怎么编译吗？

**Comment by suanite** [comment]
这个是因为路由器没有开启FPU的问题，重新编译一下就可以了。具体可以看看这篇文章。http://www.jianshu.com/p/2a9aa7d841a3

**Comment by fatedier** [comment]
同 #245 。
