### ISSUE TITLE
Create server listener error, listen tcp 0.0.0.0:8080: errno -9

### ISSUE THREAD

**Issue by 4867896** [fatedier/frp#515]
使用编译好的mipsl 0.13.0 二进制版本
使用entware环境mipsl架构处理器
配置你使用：
默认
直接运行frps提示
Create server listener error, listen tcp 0.0.0.0:8080: errno -9
不知道什么原因

**Comment by fatedier** [comment]
mipsle 的版本已知会有问题，参考 #245 。
