### ISSUE TITLE
内网代理转发，IE设置代理后显示连接已重置

### ISSUE THREAD

**Issue by gsszone** [fatedier/frp#517]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
./frpc -v 0.13.0,  ./frps -v0.13.0

**What operating system and processor architecture are you using (`go env`)?**

client=win7,service=vultr vps debian
**Configures you used:**
./frpc.ini
[common]
server_addr = vps的ip
server_port = 7000

[http_proxy]
type = tcp
remote_port = 6001
plugin = http_proxy
plugin_http_user = abc
plugin_http_passwd = abc
[socks5_proxy]
type = tcp
remote_port = 6002
plugin = socks5

./frps.ini
[common]
bind_port = 7000
vhost_http_port = 8080
**Steps to reproduce the issue:**
1.IE代理设置为，vpsip：6001
2.打开百度或其他任何网页，弹出一个验证框，输入abc，abc，显示连接已重置
3.任何网页连接已重置

**Describe the results you received:**
IE设置代理

**Describe the results you expected:**
出差时能将公司内网代理给转发出来，满足上一些内网10.0.0.1网站

**Additional information you deem important (e.g. issue happens only occasionally):**
frpc端显示2017/11/11 07:19:35 [E] [control.go:178] [1b3c2817d8a063b8] work connection clos
ed, EOF

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
有可能是代理的流量被拦截了之类的，可以尝试使用加密和压缩看是否有帮助。
