### ISSUE TITLE
Suggestion： Add fast-open for frp

### ISSUE THREAD

**Issue by oso21** [fatedier/frp#523]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**
Openwrt ARM-v7

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**
To accelerate TCP speed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
Tell more about it?

**Comment by oso21** [comment]
I am sorry ,I do not know enough to present my idea in code. But linux kernel >4.4 supports TCP fast-open,which speeds up the speed of TCP links and is supported in Shadowsocks-rss . I am wondering if fpr could do the similar optimization?

**Comment by fatedier** [comment]
No plan. It's not a important demand now.
