### ISSUE TITLE
微信支付回调报“[W] [vhost.go:129] get hostname from http/https request error: Unknow error”

### ISSUE THREAD

**Issue by GongDexing** [fatedier/frp#524]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.13.0 frps

**What operating system and processor architecture are you using (`go env`)?**
linux centos 7

**Configures you used:**
**Server**
[common]
bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
log_level = debug
[http]
type = http
custom_domains = xxxx
auth_token = xxxx
[https]
type = https
custom_domains = xxxx
auth_token = xxxx

**Client**
[common]
server_addr = xxxxxx
server_port = 7000
auth_token = xxxx
[http]
type = http
local_port = 80
custom_domains = xxxx
[https]
type = https
local_port = 443
custom_domains = xxxx

**Describe the results you received:**
[W] [vhost.go:129] get hostname from http/https request error: Unknow error

**Comment by fatedier** [comment]
你没有说明是 http 还是 https 存在问题。

如果是 https 存在问题，改为以下配置尝试下：
```ini
[https]
type = https
local_ip = manage.zenlogic.com
local_port = 443
custom_domains = xxxx
```

之后使用 custom_domains 配置的域名通过 chrome 访问看能否正常打开。如果能打开，就可能是你的 https 服务的问题。

**Comment by GongDexing** [comment]
https和http都是这个错误

**Comment by fatedier** [comment]
猜测有可能是这个 https 请求没有支持 sni，可以手动发送试试，因为 frps 需要根据域名做路由，https 请求中需要附加上域名信息。

**Comment by fatedier** [comment]
猜测有可能是这个 https 请求没有支持 sni，可以手动发送试试，因为 frps 需要根据域名做路由，https 请求中需要附加上域名信息。

**Comment by wintersun** [comment]
@GongDexing 我也遇到这个问题，但改用http就正常，所以不知道问题出在哪里。请问你解决了吗？
