### ISSUE TITLE
远程桌面不成功该怎么解决？

### ISSUE THREAD

**Issue by jszsw** [fatedier/frp#526]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.13.0

**What operating system and processor architecture are you using (`go env`)?**
公网机器：阿里云,ubuntu16.04
内网机器：windows7
**Configures you used:**
frps.ini
[common]
bind_port = 3389

frpc.ini
[common]
server_addr = 47.104.108.244
server_port = 3389

[RDP]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 6000

**Steps to reproduce the issue:**
1.启动阿里云上的frps。./frps -c ./frps.ini
输出：[I] [service.go:83] frps tcp listen on 0.0.0.0:3389
2017/11/16 14:43:23 [I] [main.go:112] Start frps success
2017/11/16 14:43:23 [I] [main.go:114] PrivilegeMode is enabled, you should pay more attention to security issues
2.启动内网电脑上的frpc。frpc -c frpc.ini
内网电脑上输出：2017/11/16 14:44:22 [I] [control.go:276] [84d60f4d6c7f4a16] login to server success, get run id [84d60f4d6c7f4a16]
2017/11/16 14:44:22 [I] [control.go:411] [84d60f4d6c7f4a16] [RDP] start proxy success
公网上电脑继续输出：[I] [service.go:230] client login info: ip [115.171.62.44:31207] version [0.13.0] hostname [] os [windows] arch [amd64]
2017/11/16 14:44:34 [I] [proxy.go:170] [84d60f4d6c7f4a16] [RDP] tcp proxy listen port [6000]
2017/11/16 14:44:34 [I] [control.go:318] [84d60f4d6c7f4a16] new proxy [RDP] success
3.android手机上使用远程桌面程序连接公网电脑IP:47.104.108.244:22
公网电脑上继续输出：[W] [service.go:214] Accept new mux stream error: broken pipe
手机远程桌面客户端无法连接成功

**Describe the results you received:**
手机远程桌面客户端无法连接成功
出错信息：[W] [service.go:214] Accept new mux stream error: broken pipe

**Describe the results you expected:**
希望通过手机远程桌面程序访问位于内网的WINDOWS机器

**Additional information you deem important (e.g. issue happens only occasionally):**
公网和内网的机器防火墙已全部开放端口。

**Can you point out what caused this issue (optional)**

**Comment by yulinsoft** [comment]
手机远程桌面设置要用6000端口，不能用默认端口。另外要确认内网电脑开启了远程桌面，家庭版系统不支持远程桌面。

**Comment by yulinsoft** [comment]
还要注意运营商的问题，我用移动宽带访问电信公网ip的远程桌面也是有时成功，有时失败，估计是网络互通的问题。

**Comment by jszsw** [comment]
谢谢，我原来理解差了
刚才改了下配置
frps
[common]
bind_port = 7000
frpc
[common]
server_addr = X.X.X.X
server_port = 7000

[RDP]
type = tcp
local_ip = 0.0.0.0
local_port = 3389
remote_port = 6000

远程桌面连接
X.X.X.X:6000
成功
