### ISSUE TITLE
在docker里运行无法穿透

### ISSUE THREAD

**Issue by dxvgef** [fatedier/frp#529]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.9.3

**What operating system and processor architecture are you using (`go env`)?**
darwin/amd64

**Configures you used:**
我在docker里以桥接模式的网络运行frp client，fpr server在远程服务器上运行正常，这是我的客户端配置文件，用这个配置能连上远程服务器（见下图的打印）
[privilege_web]
privilege_mode = true
type = http
local_ip = 127.0.0.1
local_port = 10088
use_gzip = false
subdomain = test

**Steps to reproduce the issue:**
1. 用docker run -p 10088:10088 把容器中的10088端口映射到了宿主机的10088端口；
2.如果宿主机的10088端口的进程正在运行，会无法映射；
3.关闭宿主机的10088端口的进程后能映射成功，然后再启动10088端口的进程，但在进行穿透连接时容器里的frp client报错：
![image](https://user-images.githubusercontent.com/5192264/32982239-c8fe41e6-cc46-11e7-9b7b-4fa4e8a111bd.png)

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
这类问题你需要查阅 docker 相关的资料解决。

**Comment by tolbkni** [comment]
@dxvgef 你搞反了，你要的不是容器中的10088端口映射到宿主机的10088端口，而是宿主机中的10088端口映射到容器的10088端口。

**Comment by dxvgef** [comment]
那应该怎么设置？

________________________________

**Comment by tolbkni** [comment]
找出 docker 网络中 host 的 IP，一般是 docker0 的那个，直接访问 docker0 的 IP:10088 即可

**Comment by dxvgef** [comment]
@tolbkni 知道了，谢谢

**Comment by xiaozefeng** [comment]
是镜像的问题，你别用alpine镜像，用ubuntu作为基础镜像即可解决
https://github.com/xiaozefeng/frp-docker
