### ISSUE TITLE
一些意外的错误

### ISSUE THREAD

**Issue by tanShiLin19981129** [fatedier/frp#532]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
server is frp_0.13.0_linux_amd64 in centos7.x ,client is frp_0.13.0_windows_amd64 in windows10,ide is idea

**What operating system and processor architecture are you using (`go env`)?**
don't know

**Configures you used:**
frps.ini is 
[common]
bind_port = 7000
vhost_http_port = 80
dashboard_port = 7500
# dashboard 用户名密码，默认都为 admin
dashboard_user = admin
dashboard_pwd = admin
frpc.ini is
[common]
server_addr = x.x.x.x
server_port = 7000

[web]
type = http
local_port = 8080
custom_domains = www.xxx.com
**Steps to reproduce the issue:**
1.write by document but error
2.write by document but error
3.write by document but error

**Describe the results you received:**
nothing 

**Describe the results you expected:**
some day ago it's useful but now it's bad,cann't visit my server domian with 80 to mapping my windows10 idea

**Additional information you deem important (e.g. issue happens only occasionally):**
i hope it will can make it more user to use it

**Can you point out what caused this issue (optional)**
i don't know

**Comment by fatedier** [comment]
No enough info to reproduce this issue.
