### ISSUE TITLE
什么时候frpc可以通过配置，直接将真实的IP导过来，而不是第一次？

### ISSUE THREAD

**Issue by idoall** [fatedier/frp#534]
阿里云加了frps
内网通过docker架设的frpc，每次读取客户端信息，现在都是内网的地址，并不是外网用户访问阿里云的IP。

**Comment by fatedier** [comment]
目前不支持，且还没有计划。如果后续支持了，会在 Release Note 里说明。

**Comment by fatedier** [comment]
可以尝试 0.14.1 版本。
