### ISSUE TITLE
不想要kcp协议

### ISSUE THREAD

**Issue by hijk1234** [fatedier/frp#543]
frps.ini
kcp_bind_port = 7000

frpc.ini
protocol = tcp

不想要kcp协议,  直接把frps.ini和frpc.ini里面的这2行去除就可以了吧 ?

**Comment by hanqian200705** [comment]
@hijk1234  frpc 配置protocol = tcp 就是用的tcp传输 ，frps 配置kcp_bind_port 是说frps端可以支持用kcp传输数据 ，最终是否用kcp和frps交互主动权在于frpc 的 protocol = kcp ，readme上应该说的比较清楚了

**Comment by hijk1234** [comment]
@hanqian200705
