### ISSUE TITLE
如何绑定多个子域名用不同端口穿透供多人使用？

### ISSUE THREAD

**Issue by YuDiVSGod** [fatedier/frp#544]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.13

**What operating system and processor architecture are you using (`go env`)?**
服务器：centos6+   客户端：Padavan及OPENWRT 

**Configures you used:**
多个子域名均已解析至VPS上，frps.ini文件上同样也写入了多个子域名。
在不同宽带的多个路由器绑定不同的子域名，A路由穿透成功后，B无法上线，只有待A下线，B才上位。
如何配置才能让不同子域用不同端口穿透，并且共存？
求解，谢谢。
以上

**Comment by mayf09** [comment]
看你的意思应该是这个吧， https://github.com/fatedier/frp#custom-subdomain-names 。
可以在 frps.ini 配置 subdomain_host ，然后在不同的客户端 frpc.ini 配置不同的 subdomain 。

**Comment by fatedier** [comment]
注意使用不同的 proxy 的名字。
