### ISSUE TITLE
客户端弹已终止的错误提示

### ISSUE THREAD

**Issue by yyzh** [fatedier/frp#550]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.14.0
**What operating system and processor architecture are you using (`go env`)?**

centos 7
**Configures you used:**
frps.ini
[common]
bind_port = 41000

frpc.ini
[common]
server_addr = hidden
server_port = 41000
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 8001
**Steps to reproduce the issue:**
1. 双方连接成功后客户端就突然弹已终止的错误信息.然后自动退出
2.
3.

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/4102990/33568571-da78fc90-d961-11e7-80be-204d4a7124d3.png)
![image](https://user-images.githubusercontent.com/4102990/33568617-062ded46-d962-11e7-9755-567c0ec33b58.png)

**Describe the results you expected:**

程序不会自动退出
**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by yyzh** [comment]
![image](https://user-images.githubusercontent.com/4102990/33569059-653de13c-d963-11e7-9c72-012c5099f750.png)
把双方的时区调成一样的,没用.

**Comment by fatedier** [comment]
可能被你的系统 kill 掉了，可以自己排查下。

**Comment by lihua8848** [comment]
问题最后解决了吗，还是有问题
<img width="238" alt="image" src="https://github.com/fatedier/frp/assets/54617440/5c1769a6-fd13-4865-a796-41e9efc9827a">
