### ISSUE TITLE
tcp转发好慢

### ISSUE THREAD

**Issue by 1688pc** [fatedier/frp#553]
tcp转发，SCP和SFTP上传文件速度好慢，速度只有30KB

**Comment by fatedier** [comment]
[网络传输速度慢是什么原因？](https://github.com/fatedier/frp/wiki#%E7%BD%91%E7%BB%9C%E4%BC%A0%E8%BE%93%E9%80%9F%E5%BA%A6%E6%85%A2%E6%98%AF%E4%BB%80%E4%B9%88%E5%8E%9F%E5%9B%A0)

**Comment by 1688pc** [comment]
@fatedier 以下是上传测试和配置，不知道哪里设置错了，望大神指教，谢谢
直接上传文件到VPS测试图
![vps](https://user-images.githubusercontent.com/14054316/33643826-597608ce-da7c-11e7-8710-90123e4b2cdd.PNG)
kcp传输模式文件到路由器挂载的硬盘
![kcp](https://user-images.githubusercontent.com/14054316/33643840-6caaac42-da7c-11e7-8ad8-08e025a923ff.PNG)
tcp传输模式上传文件到路由器挂载的硬盘
![tcp](https://user-images.githubusercontent.com/14054316/33643878-94aa57ce-da7c-11e7-82bd-f6e14bf2729d.PNG)
frps配置
# [common] is integral section
[common]
# A literal address or host name for IPv6 must be enclosed
# in square brackets, as in "[::1]:80", "[ipv6-host]:http" or "[ipv6-host%zone]:80"
bind_addr = 0.0.0.0
bind_port = 5443
# udp port used for kcp protocol, it can be same with 'bind_port'
# if not set, kcp is disabled in frps
kcp_bind_port = 5443
# if you want to configure or reload frps by dashboard, dashboard_port must be set
dashboard_port = 26443
# dashboard assets directory(only for debug mode)
dashboard_user = xxxxxxxx
dashboard_pwd = xxxxxxxx
# assets_dir = ./static

vhost_http_port = 22280
vhost_https_port = 22443
# console or real logFile path like ./frps.log
log_file = ./frps.log
# debug, info, warn, error
log_level = info
log_max_days = 3
# privilege mode is the only supported mode since v0.10.0
privilege_token = xxxxxxxx
# only allow frpc to bind ports you list, if you set nothing, there won't be any limit
#privilege_allow_ports = 1-65535
# pool_count in each proxy will change to max_pool_count if they exceed the maximum value
max_pool_count = 50
# if tcp stream multiplexing is used, default is true
tcp_mux = true
frpc配置图
![_li](https://user-images.githubusercontent.com/14054316/33643956-fdfc9052-da7c-11e7-94b5-8618763a7c7e.jpg)

**Comment by fatedier** [comment]
上一个回复中已说明原因，请仔细阅读文档。

**Comment by 1688pc** [comment]
感谢解答！

**Comment by Thyiad** [comment]
我的也奇慢无比，哎，同样的ng辣么快，真是搞不懂

**Comment by 1688pc** [comment]
@Thyiad 也有可能是VPS的问题，不折腾了，已换联通要到公网IP了

**Comment by Thyiad** [comment]
@1688pc 好吧，我自己服务器的是阿里云ECS，香港1核1G1M，主要是做转发，开发测试用的。我是觉得这个跟带宽有关的，不过我还搭了ngrok，是要比frp快的，具体原因我就搞不懂了。
不知道你的服务器是多少带宽？
