### ISSUE TITLE
配置日志路径后，启动报错logs.BeeLogger.SetLogger: open ~/frpc.log: no such file or directory

### ISSUE THREAD

**Issue by 327101303** [fatedier/frp#555]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.13.0
**What operating system and processor architecture are you using (`go env`)?**
没有go环境

**Configures you used:**
[common]
server_addr = frp.xxxx.cn
server_port = 7000
log_file = ~/frpc.log
log_level = info
log_max_days = 3
privilege_token = Ethicall
admin_addr = 127.0.0.1
admin_port = 7400
admin_user = admin
admin_pwd = admin
pool_count = 5
tcp_mux = true
pid = /etc/frp/frpc.pid
user = zhangj
login_fail_exit = true
protocol = tcp
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
use_encryption = false
use_compression = false
remote_port = 6001
[web01]
type = http
local_ip = 127.0.0.1
local_port = 8000
use_encryption = false
use_compression = true
subdomain = zhangj
locations = /,/pic
host_header_rewrite = example.com

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
日志地址使用绝对路径。
