### ISSUE TITLE
服务端内存占用问题

### ISSUE THREAD

**Issue by heimi** [fatedier/frp#556]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frps 0.14.0
frpc 0.14.0

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**
[common]
bind_addr = 192.168.10.114
bind_port = 7000

vhost_http_port = 1080

**Steps to reproduce the issue:**
1.3000个客户端连接上，访问页面正常，服务端内存战胜450M左右
2.3000个客户端关闭，服务端内存使用不变，还是450M
3.再连接3000个客户端，服务端内存使用700多M

**Describe the results you received:**
客户端关闭后服务端是不是没有释放使用的内存

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
内存使用取决于 Go 的 GC 机制。
测试有没有内存泄露，可以尝试用 3000 客户端持续访问，看一段时间后内存使用是否持续增长，还是维持在一个比较稳定的值，以此来判断。
