### ISSUE TITLE
网件WNDR4300运行时出错

### ISSUE THREAD

**Issue by viagram** [fatedier/frp#558]
路由：网件WNDR4300
平台：linux mips
注：内核没有开户FPU。
v0.13.0 之前版本可以正常运行。
v0.14.0 提示Illegal instruction。
希望你能提供v0.13.0的编译方法或者编译相关版本。
谢谢！

**Comment by fatedier** [comment]
什么时候下载测试的？

**Comment by viagram** [comment]
之前一直在用，大约是大前天发现你更新之后，我下载测试时发现了这个问题。

**Comment by viagram** [comment]
@fatedier 从v0.11.0一直在用，大约是7号时发现你更新之后，我下载测试时发现了这个问题。

**Comment by fatedier** [comment]
重新下载测试下试试。

**Comment by viagram** [comment]
@fatedier 现在可以了，谢谢。
