### ISSUE TITLE
问下请问能跨平台使用吗

### ISSUE THREAD

**Issue by istrwei** [fatedier/frp#56]
比如frps为linux，frpc为windows或者相反

**Comment by fatedier** [comment]
可以，frps 部署在 linux 上，frpc 在 windows 上这种情况目前我自己也在用。

**Comment by istrwei** [comment]
好的，谢谢

**Comment by istrwei** [comment]
@fatedier 对了，linux的releases包是不是可以直接运行，无需安装go环境

**Comment by fatedier** [comment]
可以，主要是 go 的跨平台的特性确实很方便，几乎没什么依赖。
