### ISSUE TITLE
关于https转发的问题

### ISSUE THREAD

**Issue by Jayzisinstance** [fatedier/frp#562]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.14.0

**What operating system and processor architecture are you using (`go env`)?**

centos7

**Configures you used:**

like https example 

**Steps to reproduce the issue:**
1. use the https...

**Describe the results you received:**

我在本地的机器上做了一个https，当然前提是http内网穿透之后是可以访问的，然后用的let's en的证书，然后我在在本地访问https是ok的，但是我内网穿透到公网之后firefox报错，谷歌浏览器也是报错
```
建立安全连接失败

连接到 xxx.com 时发生错误。 SSL 接收到一个超出最大准许长度的记录。 错误代码: SSL_ERROR_RX_RECORD_TOO_LONG

    由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
    建议向此网站的管理员反馈这个问题。

详细了解…

反馈此类错误，帮助 Mozilla 识别并拦截恶意网站
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by 1oo1** [comment]
没有试过本地上证书的方式，但是看文档应该是支持的。

我现在用的是另一种方式，已经运行了两个月左右，挺稳定的，你可以参考下：证书部署在 server 的 nginx 上，然后反向代理 frps，frpc <--> frps 之间还是 http。

**Comment by SuperSuperSuperSuper5** [comment]
@1oo1 ok，现在我直接在服务器上做网站了哈哈哈，实在搞不定

**Comment by yyingc** [comment]
添加这两条
	proxy_ssl_server_name on;
        proxy_ssl_session_reuse off;

**Comment by vampuke** [comment]
@1oo1 能不能分享一下nginx的设置  感激不尽
