### ISSUE TITLE
nginx 转发https 无法正确显示页面 

### ISSUE THREAD

**Issue by keramist** [fatedier/frp#565]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.14.1

**What operating system and processor architecture are you using (`go env`)?**
debian 9 LNMPA

**Configures you used:**
配置没有问题 只用FRP 穿透 http 自动跳转https 网站显示正常

**Steps to reproduce the issue:**
1. 只开启 frp 转发 80 443 端口 到本地网站服务80 443 nginx自动跳转https 网站正常 ssl证书letsencrypt

2.通过nginx 转发80 443 到frp 监听端口http8689  https8989 再到本地服务 https 显示
SSL 接收到一个超出最大准许长度的记录。 错误代码: SSL_ERROR_RX_RECORD_TOO_LONG

3.

**Describe the results you received:**

**Describe the results you expected:**
希望完善 nginx 反代frp 正常显示https网站 的错误
同样的配置下 另外一个只用http的网站 正常 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
root@job:~# curl -vvv https://www.xxx.com
* Rebuilt URL to: https://www.xxx.com/
*   Trying 45.77.108.123...
* Connected to www.xxx.com (45.77.108.123) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: The TLS connection was non-properly terminated.
* Closing connection 0
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.

**Comment by fatedier** [comment]
类似 #359  这样的问题不再回答， 请先自行确认 nginx 的相关配置正常，搜索相关的解决方案，如果通过排查能确认是 frp 的问题，再做反馈。
