### ISSUE TITLE
服务端无法启动

### ISSUE THREAD

**Issue by INT-ZC** [fatedier/frp#566]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.14.1

**What operating system and processor architecture are you using (`go env`)?**
Debian 8

**Configures you used:**
https://gist.github.com/zhfish/c13df1b3ace50bfb1ba34a7db380bbfb
https://lcbk.net/9766.html

**Steps to reproduce the issue:**
1. systemctl start frps
2. systemctl enable frps
3. service frps status

**Describe the results you received:**
● frps.service - frps daemon
   Loaded: loaded (/etc/systemd/system/frps.service; enabled)
   Active: failed (Result: exit-code) since Sat 2017-12-16 22:03:01 CST; 10s ago
 Main PID: 960 (code=exited, status=203/EXEC)

systemd[1]: Starting frps daemon...
systemd[1]: Started frps daemon.
systemd[960]: Failed at step EXEC spawning /home/frps: Permission denied
systemd[1]: frps.service: main process exited, code=exited, status=203/EXEC
systemd[1]: Unit frps.service entered failed state.

**Describe the results you expected:**
frps daemon (pid) is running...

**Additional information you deem important (e.g. issue happens only occasionally):**
Runned as root

**Can you point out what caused this issue (optional)**

**Comment by INT-ZC** [comment]
抱歉最后查出问题来与frp无关，浪费您宝贵的时间了

**Comment by itargaryen** [comment]
我也遇到了同样的问题，请求指教解决办法。

**Comment by quickhot** [comment]
我也有这样的问题，ubuntu 16.04，frps 27.0
