### ISSUE TITLE
关于tcp_mux

### ISSUE THREAD

**Issue by wwqgtxx** [fatedier/frp#568]
请问一下在设置了和服务器之间使用kcp通讯的时候，tcp_mux这个设置对最终的通讯有影响么，会不会最终也只会新建一个kcp链接呢

**Comment by fatedier** [comment]
Yes.

**Comment by wwqgtxx** [comment]
那么提个建议，在客户端使用kcp通讯来转发udp的时候服务器是否可以直接在udp通道上转发数据，而不用再用kcp包一层，毕竟这个时候没必要实现拥塞控制，多加一层kcp反而会影响转发效率
