### ISSUE TITLE
新版本（0.14.1）websocket问题

### ISSUE THREAD

**Issue by liwei19920307** [fatedier/frp#570]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.14.1

**What operating system and processor architecture are you using (`go env`)?**

frps -> Centos 7 x64
frpc -> Ubuntu 16.04.3 LTS (arm)

**Configures you used:**

frpc配置

```
[hass]
type = http
subdomain = hass
local_ip = 127.0.0.1
local_port = 8123
```

Nginx配置

```	
server {

		listen 443 ssl http2 default_server;
		listen [::]:443 ssl http2 default_server;
		server_name xxx.com;
		root /root/www;

		location / {

			proxy_pass http://frp;
			proxy_redirect https://$host/ https://$http_host/;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Host $host;
			proxy_set_header X-Forwarded-proto https;

			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection $connection_upgrade;
		}

		error_page 404 /404.html;
		location = /40x.html {

		}

		error_page 500 502 503 504 /50x.html;
		location = /50x.html {

		}

		ssl_certificate /etc/letsencrypt/live/xxx/fullchain.pem; 
		ssl_certificate_key /etc/letsencrypt/live/xxx/privkey.pem;
		include /etc/letsencrypt/options-ssl-nginx.conf; 

	}
```

**Steps to reproduce the issue:**

1.更新最新版本后出现
2.nginx转发frp，配置了webstocket反代理
3.应用后台登陆报错如下（0.14.0版本没出现这样错误）

```INFO:homeassistant.components.http:Serving /api/websocket to 127.0.0.1 (auth: False)
   INFO:homeassistant.components.http:Serving /api/websocket to 127.0.0.1 (auth: False)
   INFO:homeassistant.components.http:Serving /api/websocket to 127.0.0.1 (auth: False)
   INFO:homeassistant.components.http:Serving /api/websocket to 127.0.0.1 (auth: False)
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

更新后出现，目前其他不涉及到websocket的http应用暂时没有影响

**Can you point out what caused this issue (optional)**

看更新日志，不知道是不是因为这次frp版本中http重构导致的

**Comment by ihao** [comment]
我也遇到了同样的问题，上一个版本是好的吗？@liwei19920307

**Comment by ihao** [comment]
换回0.14.0的服务端一切正常了。

**Comment by fatedier** [comment]
由于代码重构，暂时不支持了，后面跟进下看能否继续支持。

**Comment by fatedier** [comment]
0.15.1 版本尝试使用新的方法支持了，但不一定完善，如果有问题再重新反馈。

**Comment by jasonYje** [comment]
才看到，卡在这里有段时间了
