### ISSUE TITLE
一台公网服务器是否可以充当多个frp server？

### ISSUE THREAD

**Issue by XGBoost** [fatedier/frp#571]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
./frp

**What operating system and processor architecture are you using (`go env`)?**
Ubuntu

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by xsw9527** [comment]
理论上端口不一样就没问题，frp没有限制是否运行了多个实例。

**Comment by netmouser** [comment]
可以运行，我测试过，端口号和proxy name不一样就可以了。

**Comment by nxcjs** [comment]
一个实例里能不能映射多个HTTP端口或者HTTPS端口，大不了登的时候麻烦一点，在域名后面加端口，不用二级域名这么高级
