### ISSUE TITLE
请问，是否支持转发vpn相关协议，以及思路

### ISSUE THREAD

**Issue by chenxin199261** [fatedier/frp#573]
我想用内网一个机器做vpn，请问frp能不能让公网转发vpn那些协议。

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
frp 支持反代 tcp 和 udp 端口，其他的协议通常都基于此，请自行搜索如何去解决。
