### ISSUE TITLE
客服端时不时报错退出，不知道是不是熄屏幕导致

### ISSUE THREAD

**Issue by 27hao** [fatedier/frp#574]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.14.1

**What operating system and processor architecture are you using (`go env`)?**

服务端：4.4.0-62-generic #83-Ubuntu x86_64
客户端: win7企业版
**Configures you used:**
服务端:
[common]
bind_port = 7000
客服端:
[common]
server_addr = xxxxxxx
server_port = 7000

[xxxx]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 7089

**Steps to reproduce the issue:**
客服端时不时报错:
2017/12/25 12:27:07 [W] [control.go:372] [b488c4148f560f44] heartbeat timeout
2017/12/25 12:27:07 [W] [control.go:322] [b488c4148f560f44] read error: broken pipe
2017/12/25 12:27:07 [I] [control.go:340] [b488c4148f560f44] control writer is closing
2017/12/25 12:27:08 [I] [control.go:480] [b488c4148f560f44] try to reconnect to server...
2017/12/25 12:27:08 [E] [control.go:178] [b488c4148f560f44] work connection closed, broken pipe
2017/12/25 12:27:08 [E] [control.go:178] [b488c4148f560f44] work connection closed, broken pipe
2017/12/25 12:27:30 [W] [control.go:483] [b488c4148f560f44] reconnect to server error: dial tcp xxxxxx:7000: connectex: A socket operation encountered a dead network.
2017/12/25 12:27:31 [I] [control.go:480] [b488c4148f560f44] try to reconnect to server...
2017/12/25 12:27:32 [I] [control.go:277] [b488c4148f560f44] login to server success, get run id [b488c4148f560f44], server udp port [0]
2017/12/25 12:27:32 [I] [control.go:412] [b488c4148f560f44] [ralph-rdp] start proxy success
2017/12/25 18:17:17 [W] [control.go:372] [b488c4148f560f44] heartbeat timeout
2017/12/25 18:17:17 [W] [control.go:322] [b488c4148f560f44] read error: broken pipe
2017/12/25 18:17:17 [I] [control.go:340] [b488c4148f560f44] control writer is closing
2017/12/25 18:17:18 [I] [control.go:480] [b488c4148f560f44] try to reconnect to server...
2017/12/25 18:17:18 [E] [control.go:178] [b488c4148f560f44] work connection closed, broken pipe
2017/12/25 18:17:39 [W] [control.go:483] [b488c4148f560f44] reconnect to server error: dial tcp xxxxx:7000: connectex: A socket operation encountered a dead network.
2017/12/25 18:17:40 [I] [control.go:480] [b488c4148f560f44] try to reconnect to server...
2017/12/25 18:17:41 [I] [control.go:277] [b488c4148f560f44] login to server success, get run id [b488c4148f560f44], server udp port [0]
2017/12/25 18:17:41 [I] [control.go:412] [b488c4148f560f44] [xxxx] start proxy success

**Comment by fatedier** [comment]
客户端没有退出，只是在不断重连，因为中间网络断开了，需要你确保网络环境的正常。
