### ISSUE TITLE
是否可支持tun/tap设备，可方便的创建点对点的VPN网络

### ISSUE THREAD

**Issue by viccom** [fatedier/frp#577]
目前版本的frp的功能已经很强了，是否考虑在后续的版本中增加点对点VPN的功能，可以很方便的以网络的管理远程网络中的设备。

**Comment by fatedier** [comment]
目前没有这方面的计划，这方面应该有更合适的工具和项目去完成的。

**Comment by steom** [comment]
now in 2022 with wintun.dll it's very feasible. Please consider to add wintun interface.
