### ISSUE TITLE
frp无法用tightvnc控制内网中的机器

### ISSUE THREAD

**Issue by laozi888** [fatedier/frp#579]
我在公网有一台服务器，想用tightvnc来控制内网中的机器，发现在用tightvnc viewer连接时报错，但是用realvnc是可以的。我尝试了较早版本的也不行。能否帮我看一下原因？

What version of frp are you using (./frpc -v or ./frps -v)?
0.14.1

What operating system and processor architecture are you using (go env)?
公网服务器：ubuntu14
控制端与被控制端：win7 64位

Configures you used:
[common]                    //服务器的配置
kcp_bind_port=9006
bind_addr=XX.XX.XX.XX
bind_port=9006
dashboard_port=9007
dashboard_user=admin
dashboard_pwd=admin
privilege_mode=true
privilege_token=12345678
max_pool_count=100

[common]                  //控制端配置
server_addr=XX.XX.XX.XX
server_port=9006
log_level=trace
protocol=kcp
privilege_token=12345678
[tcp_5900_visitor]
type=stcp
sk=d833ee7447b0233c25f7
role=visitor
server_name=tcp_5900
use_encryption=True
use_compression=True
bind_addr=127.0.0.1
bind_port=14590

[common]    //被控制端配置
server_addr=XX.XX.XX.XX
server_port=9006
privilege_token=12345678
protocol=kcp
[tcp_5900]
type=stcp
local_ip=0.0.0.0
local_port=5900
sk=d833ee7447b0233c25f7
use_encryption=True
use_compression=True

**Comment by fatedier** [comment]
你说的东西我都不懂，frp 用来反代其他的程序，我不可能每个程序去测试，建议还是自己排查下原因，然后再反馈 bug。

**Comment by yi-ge** [comment]
使用tightvnc必须设置local_ip为设备在局域网IP，设置为127.0.0.1或者0.0.0.0都是无法控制的。
