### ISSUE TITLE
join connections error

### ISSUE THREAD

**Issue by doboqopo** [fatedier/frp#58]
2016/08/04 16:54:04 [control.go:181] [I] Start to send heartbeat to frps
2016/08/04 16:54:21 [conn.go:182] [W] join connections error, read tcp 192.168.1.190:41386->192.168.1.190:18080: read tcp 192.168.1.190:44203->121.40.217.143:47000: use of closed network connection

**Comment by fatedier** [comment]
It seems the same problem as #53 , you used a previous version `frpc` and it's incompatible with latest version `frps`.
