### ISSUE TITLE
运营商识别特征导致端口被封

### ISSUE THREAD

**Issue by stanle1** [fatedier/frp#583]
现象：一台法国vps，一个香港vps，其他网上公开服务.第一次连可以成功，第二次连不成功，然后换端口又成功了。网络是互通宽带，这个问题初步有2个猜测。怀疑运营商识别特征端口被封？又或者对于长链接运营商使用了端口老化技术等?
期望：针对第一问题：能不能加入 混淆协议？针对第二问题：有没办法frp 底层使用无状态链接处理，不使用tcp?
参考：https://www.zhihu.com/question/66959697

Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.13.0

**What operating system and processor architecture are you using (`go env`)?**
frps: debian 8
frpc: mac /Ubuntu 16.04.2 LTS

**Configures you used:**
frps
[common]
bind_port = 7005

frpc
[common]
server_addr = *.*.win
server_port = 7005

[neo-ssh]
type = tcp
local_ip = 192.168.199.182
local_port = 22
remote_port = 60500
custom_domains = neo-ssh.*.*.win

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
无提示直接网络超时

**Describe the results you expected:**
无提示直接网络超时

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
1. frp 不会加入 混淆协议，没有必要。
2. frpc 可以使用 kcp 协议连接 frps。
