### ISSUE TITLE
 比较奇怪的问题

### ISSUE THREAD

**Issue by wang20150419** [fatedier/frp#584]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.14.1

**What operating system and processor architecture are you using (`go env`)?**
linux-arm (server), linux-amd64( client)

**Configures you used:**

client frpc.ini:

[common]
server_addr = xx.xx.xx.xx
server_port = 8888
privilege_token = xxxxxx
protocol = kcp

[mysni]
type = tcp
local_ip = 192.168.1.10
local_port = 443
remote_port = 443

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

client 和 server 都在防火墙（openwrt路由器）后面。
client 上建有 sniproxy 服务，通过frp把服务映射到 server里。

client 如果用 vmware虚拟机，网络桥接形式，并设为DMZ，无法访问 client上的服务。
（监视了client里的链接，sniproxy 服务工作了，但无法把数据传回）
但如果是独立硬件（树莓派3），且设置为DMZ，则可以访问。不设置为DMZ，无法访问。

**Describe the results you expected:**

希望能够解决 vmware虚拟机的问题。按道理，vmware虚拟机的桥接网络和独立物理硬件（树莓派3）是一样的，但结果不一样。

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by xbugio** [comment]
@wang20150419 应该是你虚拟机相关配置的问题，我在vmware、esxi里都在用frp，都是正常可用的。

**Comment by fatedier** [comment]
这种问题通常和 frp 无关，建议自己检查和排查下网络环境的问题。
