### ISSUE TITLE
Android 平台运行 frpc 报错

### ISSUE THREAD

**Issue by Titzanyic** [fatedier/frp#586]
版本号：0.14.1
系统：Android 5.1  arm 架构
软件版本：frp_0.14.1_linux_arm.tar.gz
运行方式：
`chmod +x frpc`
`Bad mode`
`./frpc -v`
`/system/bin/sh: ./frpc: can't execute: Permission denied`

问题：
1. Android 平台应该下载那个版本能够使用？
2. 请问上述运行出错的原因？

**Comment by BI7PRK** [comment]
显然是权限问题~

**Comment by yanggis** [comment]
楼主要看清楚，这个是arm linux的二进制包，不是arm android平台二进制包，怎么可能可以在android平台运行呢？android平台的二进制包需要下载源代码自己编译。

**Comment by qq1198** [comment]
如果你是在内置储存器中运行那是肯定的，因为不能在内置储存器中运行，没有权限的，可以试着复制到外置储存器(SD卡)运行，而且frp需要自己编译一下的默认的安卓不支持
