### ISSUE TITLE
Do you have plans to support websockets?

### ISSUE THREAD

**Issue by nkev** [fatedier/frp#59]

**Comment by fatedier** [comment]
Hi, i use the simple web service from http://beego.me/docs/examples/chat.md to test websockets. It works fine.

Here is my configuration file in frpc using privilege mode:

```ini
# frpc.ini
[www]
privilege_mode = true
type = http
local_ip = 127.0.0.1
local_port = 8080
custom_domains = www.yourdomain.com
```

I hope this will help you.

**Comment by SNY7** [comment]
Still not working, ws:// request is alway pending. I'm using meteor
