### ISSUE TITLE
frps dashbboard 无法显示流量信息

### ISSUE THREAD

**Issue by pengzai123** [fatedier/frp#590]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.14.1

**What operating system and processor architecture are you using (`go env`)?**
CentOS Linux 7.4.1708 (Core)

**Configures you used:**
[common]
bind_port = 7000
kcp_bind_port = 7000
privilege_token = test
vhost_http_port = 8090
subdomain_host = xxx.xxx.com
dashboard_port = 7500
max_pool_count = 100
dashboard_user = cpx
dashboard_pwd = test
privilege_allow_ports = 9000-50000
log_file = ./frps.log

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
frps dashbboard 无法显示流量信息
| Name | Port | Connections | Traffic In | Traffic Out | status
stg_1782 | 8090 | 0 | 0 bytes | 0 bytes | online
test_1782 | 8090 | 0 | 0 bytes | 0 bytes | online
test_2047 | 8090 | 0 | 0 bytes | 0 bytes | online

**Describe the results you expected:**
如何解决？是版本问题还是系统问题？

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
已 fix，下个版本发布。
