### ISSUE TITLE
frpc客户端错误求解 [web] start error: router config conflict

### ISSUE THREAD

**Issue by huxuansong** [fatedier/frp#592]
root@HXS-Server:/frpc# ./frpc_linux_amd64 -c /frpc/frpc.ini
2018/01/07 21:05:14 [I] [control.go:277] [7c095a1f9bb3d2da] login to server success, get run id [7c095a1f9bb3d2da], server udp port [0]
2018/01/07 21:05:16 [W] [control.go:389] [51df31f3592079c5] [web] start error: router config conflict
2018/01/07 21:05:26 [I] [control.go:437] [51df31f3592079c5] try to register proxy [web]
2018/01/07 21:05:26 [W] [control.go:389] [51df31f3592079c5] [web] start error: router config conflict

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
