### ISSUE TITLE
[control.go:121] login to server failed: dial tcp 192.168.1.2:9000: errno -89

### ISSUE THREAD

**Issue by caisen** [fatedier/frp#593]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
# ./frpc -v
0.14.1
/frps -version
0.14.1

**What operating system and processor architecture are you using (`go env`)?**
server : darwin_amd64  client : linux_mips client cpu:Broadcom BMIPS4350 V8.1

client  cat /proc/version
Linux version 3.4.11-rt19 (publisher@rd.ty.sc Revision: 1793) (gcc version 4.6.2 (Buildroot 2011.11) ) #1 SMP PREEMPT 2016/10/13 09:29:40
# cat /proc/sys/fs/file-max
10044
**Configures you used:**
frps
bind_addr = 0.0.0.0
kcp_bind_port = 9000
bind_udp_port = 9001
bind_port = 9000
dashboard_addr = 0.0.0.0
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin
assets_dir = ./static
log_file = ./frps.log
log_level = debug
log_max_days = 3
privilege_token = 12345678
privilege_allow_ports = 2000-3000,3001,3003,4000-50000
max_pool_count = 5
authentication_timeout = 900
#subdomain_host = aaa.com
tcp_mux = true

**Steps to reproduce the issue:**
1. MAC  install frps and start  /frps --addr=192.168.1.2:9000 -c frps.ini
2. client install frpc and start  ./frpc --server-addr=192.168.1.2:9000 --log-level=debug
3.clent display :[W] [control.go:121] login to server failed: dial tcp 192.168.1.2:9000: errno -89

**Describe the results you received:**
clent display :[W] [control.go:121] login to server failed: dial tcp 192.168.1.2:9000: errno -89

**Describe the results you expected:**
Client can be connected normally

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
Same with #296
