### ISSUE TITLE
报这个错误怎么处理？

### ISSUE THREAD

**Issue by wangx2** [fatedier/frp#597]
2018/01/08 15:12:38 [I] [control.go:276] [fa6b5d8c86714c88] login to server success, get run id [fa6b5d8c86714c88]
2018/01/08 15:12:38 [I] [control.go:411] [fa6b5d8c86714c88] [web] start proxy success
2018/01/08 15:12:39 [E] [proxy.go:332] [web] connect to local service [127.0.0.1:8080] error: dial tcp 127.0.0.1:8080: getsockopt: connection refused

我看上面代理成功，但是我访问的时候就路由器报错【拒绝连接？】这是哪部出错了呢？

**Comment by flxxyz** [comment]
仔细检查防火墙，基本判断你的frp的连接端口已经放开，应该是你web的端口没有放开

**Comment by Ericwyn** [comment]
很奇怪， 我代理本地的 8989 端口的时候， 就会出现这个错误， 换成 8080 端口之后就没有这个错误了， 版本是 0.14.1
