### ISSUE TITLE
[Question] Does the tool perform NAT hole punching?

### ISSUE THREAD

**Issue by bradacina** [fatedier/frp#60]
Hi, 
It's unclear to me if this tool provides NAT hole punching or not? I'm running a host behind a NAT. The admin of the NAT does not want to allow my host to be visible on the internet so he's only allowing outgoing connections from my host and replies. No incoming connections are allowed. Will this tool allow me to expose a service running on my host to the internet? Thanks.

**Comment by fatedier** [comment]
frp is good fit for you. All connections are established from frpc to frps and messages are forwarded by frps. You should run frpc in your server behind NAT.

NAT hole punching is planned to support in the future.

**Comment by bradacina** [comment]
Thank you very much!
