### ISSUE TITLE
frpc.exe admin address 404 page not found

### ISSUE THREAD

**Issue by RuioWolf** [fatedier/frp#600]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc 0.14.1

**What operating system and processor architecture are you using (`go env`)?**
Windows 10 build 1703 x64

**Configures you used:**
```
server_addr = *
server_port = 7000
privilege_token = *
# admin_addr = 127.0.0.1
admin_port = 7002
admin_user = admin
admin_pwd = *
pool_count = 1
tcp_mux = true
user = *
login_fail_exit = false
protocol = tcp
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000
```

**Steps to reproduce the issue:**
1. `./frpc.exe`
2. http://localhost:7002
3. 404 page not found

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/15277799/34956764-8e173626-fa65-11e7-9446-9bdaa34bd8bb.png)

**Describe the results you expected:**
frpc的网页控制面板？

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by RuioWolf** [comment]
Otherwise, while connecting to localhost:6000 it remains connection failed.

**Comment by fatedier** [comment]
没有页面，该端口仅提供 api 调用，不需关心。
