### ISSUE TITLE
希望能够增加多个 privilege_token

### ISSUE THREAD

**Issue by p4ssw0rd** [fatedier/frp#601]
如题所述，方便为客户端提供不同的 privilege_token

**Comment by fatedier** [comment]
没有计划做管理相关的功能。

**Comment by p4ssw0rd** [comment]
如果我实现，可以PR吗？

**Comment by fatedier** [comment]
这个 repo 里不会加入，你可以自己修改了之后自己使用。

**Comment by p4ssw0rd** [comment]
因为配置实现了二级域名转发，供多人使用，共用一个privilege_token不合适。还请能够考虑加入这个功能。
