### ISSUE TITLE
1.4版本frp中的P2P功能可以使用在NAS中么？

### ISSUE THREAD

**Issue by bzpv2k** [fatedier/frp#602]
现在我使用的是vultr的VPS做服务端，访问端群晖nas接入的是联通宽带，部署的是frp1.3版本用于做内网穿透。我想请问下最新版本的frp加入了点对点内网穿透，这个技术目前适用于群晖的nas做内穿么？

**Comment by fatedier** [comment]
取决于网络环境，该功能不稳定且成功率不高，仅推荐用于测试。

**Comment by bzpv2k** [comment]
谢谢答疑！

**Comment by foxhound1227** [comment]
在自家和公司间做测试 都失败了 一直提示 i/o time out
