### ISSUE TITLE
Netgear WNDR4300 (mips) Illegal instruction

### ISSUE THREAD

**Issue by viagram** [fatedier/frp#609]
固件是LEDE 17.01.4官方版本，内核是没有开户FPU的，刚刚使用frp15时又出现了: Illegal instruction。
之前14.1的时候也出现，也向你反馈过。希望能重新编译一个相关版本，谢谢！

**Comment by fatedier** [comment]
建议先不更新 frp ，等 Go 1.10 版本放出后，后续使用新版本编译应该就可以了，就不单独解决了，影响到自动化发布的步骤。
