### ISSUE TITLE
最新的 0.15.0  版本服务端有问题！回滚后正常

### ISSUE THREAD

**Issue by wang20150419** [fatedier/frp#611]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.15.0

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

服务端无法正常工作。提示 start error: port not allowed， 回滚到前一版本恢复正常。
linux.arm, windows 版本都一样。

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
不按照格式填写的 issue 将会直接关闭。
