### ISSUE TITLE
不使用域名怎样修改配置文件实现访问内网web服务?

### ISSUE THREAD

**Issue by gyje** [fatedier/frp#612]
不知道哪里配置有问题，在内网用Apache开了个1024端口的web页面，想要不通过域名直接访问公网IP实现访问该内网页面。
# frps.ini
[common]
bind_port = 7000
auth_token = admin
privilege_token = 12345678

# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000
auth_token = admin
privilege_token = 12345678
[web]
type = http
local_port = 1024
custom_domains = 127.0.0.1

谢谢！

**Comment by fatedier** [comment]
使用 tcp 类型

**Comment by gyje** [comment]
@fatedier 能否给出一个简单的示例配置？尝试了tcp，但是提示io error

**Comment by fatedier** [comment]
请自行查阅相关文档，提示的错误贴出日志。

**Comment by gyje** [comment]
frps.ini
[common]
bind_port = 7000
frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000
[proxy]
type = tcp
local_ip = 0.0.0.0
local_port = 1024
remote_port = 6000

防火墙配置,端口占用,都检查了,服务端可以启动成功,但是客户端出错:
2018/01/24 20:16:24 [I] [proxy_manager.go:284] proxy removed: []
2018/01/24 20:16:24 [I] [proxy_manager.go:294] proxy added: [proxy]
2018/01/24 20:16:24 [I] [proxy_manager.go:317] visitor removed: []
2018/01/24 20:16:24 [I] [proxy_manager.go:326] visitor added: []
2018/01/24 20:16:45 [W] [control.go:109] login to server failed: dial tcp x.x.
x.x:7000: connectex: A connection attempt failed because the connected party
did not properly respond after a period of time, or established connection faile
d because connected host has failed to respond.
dial tcp x.x.x.x:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by gyje** [comment]
本地web服务已经启动,1024端口web页面正常

**Comment by gyje** [comment]
用[goproxy](https://github.com/snail007/goproxy)解决了

**Comment by bluethon** [comment]
我也遇到同样的问题, 最后找到了配置说明, 解决了, `frpc.ini`例子如下
``` ini
[common]
server_addr = XXX.XXX.XXX.XXX
server_port = 7000

[tcp_port]
type = tcp
local_id = 127.0.0.1
local_port = 5000
# 此处是server需要监听的端口
remote_port = 5005
```
