### ISSUE TITLE
v0.15.0使用http proxy plugin http协议的网站访问不了

### ISSUE THREAD

**Issue by nethuige** [fatedier/frp#613]
测试了下，http协议的网站都不能访问，只能访问https协议的网站。试了下13版插件功能正常，http/https均可以。

**Comment by nethuige** [comment]
。

**Comment by etnperlong** [comment]
同样测试，15版本存在问题

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
