### ISSUE TITLE
[FEATURE REQUEST] can frpc be built and run on jailbreak iOS devices?

### ISSUE THREAD

**Issue by yi** [fatedier/frp#614]
We have a couple of jailbreak iOS devices and realy wish to run frpc on them in order to provide remote shell access over the internet. 

I've learned that golang has a subrepository to support iOS.  Would it be possible to build frp for iOS commadline? Could you guys please shred some light on this.

thanks.

**Comment by fatedier** [comment]
I have no plan for that, but you can have a try.

**Comment by yi** [comment]
好的

**Comment by frakman1** [comment]
This would be really useful. I've tried to run an ARM/iOS compiled ngrok on an jailbroken phone once and it failed. Please let me know if this works for you @yi 
Thanks

**Comment by yi** [comment]
hi @frakman1 

with help from @fatedier , we'd managed to run frpc on iOS. It works quite well on iOS7 actually.

following is the build command.
```
CC=$GOROOT/misc/ios/clangwrap.sh env CGO_ENABLED=1 GOOS=darwin GOARCH=arm go build -ldflags "-s -w" -o ./frpc_darwin ./cmd/frpc
```

Run that command on a MacOS, which has XCode installed.

If you encounter errors like: `xcrun: error: SDK "iphoneos" cannot be located `.  Please set XCode path by `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer/ `

**Comment by caj380** [comment]
Try this: https://drive.google.com/open?id=1N7KWvm3iVwLhsTCqnGc4gs19p0sR8MKS
I went ahead and compiled it for you.

**Comment by techgulesGu0** [comment]
when i run it on ios10.2 ,i get this error:Killed: 9

**Comment by techgulesGu0** [comment]
> hi @frakman1
> 
> with help from @fatedier , we'd managed to run frpc on iOS. It works quite well on iOS7 actually.
> 
> following is the build command.
> 
> ```
> CC=$GOROOT/misc/ios/clangwrap.sh env CGO_ENABLED=1 GOOS=darwin GOARCH=arm go build -ldflags "-s -w" -o ./frpc_darwin ./cmd/frpc
> ```
> 
> Run that command on a MacOS, which has XCode installed.
> 
> If you encounter errors like: `xcrun: error: SDK "iphoneos" cannot be located `. Please set XCode path by `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer/ `
when i run it on ios10.2 ,i get this error:Killed: 9

**Comment by frakman1** [comment]
Well I decided to try this again.
I compiled it on my Mac using the `CC` command above (Thanks for that). 
When it finished I transferred the file `frpc_darwin` to my iOS device and ran into the dreaded `Killed: 9` error. 
I then ran this from the iOS terminal:
`ldid -S frpc_darwin`
`chmod a+x frpc_darwin`
and got it to work.

```bash
# ./frpc_darwin
open ./frpc.ini: no such file or directory
```

Progress!

**Comment by sazima** [comment]
> Well I decided to try this again. I compiled it on my Mac using the `CC` command above (Thanks for that). When it finished, I transferred the file `frpc_darwin` to my iOS device and ran into the dreaded `Killed: 9` error. I then ran this from the iOS terminal: `ldid -S frpc_darwin` `chmod a+x frpc_darwin` and got it to work.
> 
> ```shell
> # ./frpc_darwin
> open ./frpc.ini: no such file or directory
> ```
> 
> Progress!
> 
> Once I added a correctly configured `frpc.ini` to the filesystem, it now runs correctly on my iOS 10.3.2 jailbroken iPhone. I've attached the file that works on my iPhone: [frpc_darwin.zip](https://github.com/fatedier/frp/files/5195533/frpc_darwin.zip)

`Bad CPU type in executable` on IOS12.5.5

```
6p:~/projects root# ./frpc_darwin 
-sh: ./frpc_darwin: Bad CPU type in executable
6p:~/projects root# 


```

**Comment by frakman1** [comment]
> Bad CPU type in executable on IOS12.5.5

What iPhone are you on?
You may be on `arm64` and the binary is compiled for`arm` architecture.

**Comment by frakman1** [comment]
[frpc_darwin_arm64.zip](https://github.com/fatedier/frp/files/9638945/frpc_darwin_arm64.zip)

I tried compiling it on a modern Mac (Ventura, M1 silicon) and finally got it to work. 
I had to change `GOOS` from `darwin` to `ios` and `GOARCH` from `arm` to `arm64`
I tested it on the same iPhoneSE  and it works
``` 
$CC=$GOROOT/misc/ios/clangwrap.sh env CGO_ENABLED=1 GOOS=ios GOARCH=arm64 go build -ldflags "-s -w" -o ./frpc_darwin ./cmd/frpc
```

```bash
$file frpc_darwin
frpc_darwin: Mach-O 64-bit executable arm64
```


On iPhone:
(I renamed it to `frpc_darwin_arm64`)


```bash
FrakPhoneSE:/frak root# ./frpc_darwin_arm64
Killed: 9
FrakPhoneSE:/frak root# ldid -S f ./frpc_darwin_arm64
./minimal/mapping.h(54): _assert(false); errno=2
FrakPhoneSE:/frak root# chmod a+x ./frpc_darwin_arm64
FrakPhoneSE:/frak root# ./frpc_darwin_arm64
2022/09/24 15:06:53 [I] [service.go:357] [535e47879ad12c32] login to server success, get run id [535e47879ad12c32], server udp port [0]
2022/09/24 15:06:53 [I] [proxy_manager.go:142] [535e47879ad12c32] proxy added: [frak_ssh]
2022/09/24 15:06:53 [I] [control.go:177] [535e47879ad12c32] [frak_ssh] start proxy success
^C
```

---

Go environment setup on Mac for reference:
```bash
brew install golang
# put this in ~/.bashrc:
export GOPATH="$HOME/go"
export GOROOT="$(brew --prefix golang)/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
```
```bash
$go version
go version go1.19.1 darwin/arm64
```

**Comment by davidoffxw** [comment]
> [frpc_darwin_arm64.zip](https://github.com/fatedier/frp/files/9638945/frpc_darwin_arm64.zip)
> 
> I tried compiling it on a modern Mac (Ventura, M1 silicon) and finally got it to work. I had to change: `GOOS` from `darwin` -> `ios` `GOARCH` from `arm` -> `arm64`
> 
> I tested it on the same iPhoneSE and it works
> 
> ```
> $CC=$GOROOT/misc/ios/clangwrap.sh env CGO_ENABLED=1 GOOS=ios GOARCH=arm64 go build -ldflags "-s -w" -o ./frpc_darwin ./cmd/frpc
> ```
> 
>  ```shell
> $file frpc_darwin
> frpc_darwin: Mach-O 64-bit executable arm64
> ```
> 
> On iPhone: (I renamed it to `frpc_darwin_arm64`)
> 
> ```shell
> FrakPhoneSE:/frak root# ./frpc_darwin_arm64
> Killed: 9
> FrakPhoneSE:/frak root# ldid -S f ./frpc_darwin_arm64
> ./minimal/mapping.h(54): _assert(false); errno=2
> FrakPhoneSE:/frak root# chmod a+x ./frpc_darwin_arm64
> FrakPhoneSE:/frak root# ./frpc_darwin_arm64
> 2022/09/24 15:06:53 [I] [service.go:357] [535e47879ad12c32] login to server success, get run id [535e47879ad12c32], server udp port [0]
> 2022/09/24 15:06:53 [I] [proxy_manager.go:142] [535e47879ad12c32] proxy added: [frak_ssh]
> 2022/09/24 15:06:53 [I] [control.go:177] [535e47879ad12c32] [frak_ssh] start proxy success
> ^C
> ```
> 
> Go environment setup on Mac for reference:
> 
> ```shell
> brew install golang
> # put this in ~/.bashrc:
> export GOPATH="$HOME/go"
> export GOROOT="$(brew --prefix golang)/libexec"
> export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
> ```
> 
>  ```shell
> $go version
> go version go1.19.1 darwin/arm64
> ```
thanks for your support!
i uesd the file from you,but i got an error:killed 9.
i try to ldid,but the error stills.

**Comment by davidoffxw** [comment]
> [frpc_darwin_arm64.zip](https://github.com/fatedier/frp/files/9638945/frpc_darwin_arm64.zip)
> 
> I tried compiling it on a modern Mac (Ventura, M1 silicon) and finally got it to work. I had to change: `GOOS` from `darwin` -> `ios` `GOARCH` from `arm` -> `arm64`
> 
> I tested it on the same iPhoneSE and it works
> 
> ```
> $CC=$GOROOT/misc/ios/clangwrap.sh env CGO_ENABLED=1 GOOS=ios GOARCH=arm64 go build -ldflags "-s -w" -o ./frpc_darwin ./cmd/frpc
> ```
> 
>  ```shell
> $file frpc_darwin
> frpc_darwin: Mach-O 64-bit executable arm64
> ```
> 
> On iPhone: (I renamed it to `frpc_darwin_arm64`)
> 
> ```shell
> FrakPhoneSE:/frak root# ./frpc_darwin_arm64
> Killed: 9
> FrakPhoneSE:/frak root# ldid -S f ./frpc_darwin_arm64
> ./minimal/mapping.h(54): _assert(false); errno=2
> FrakPhoneSE:/frak root# chmod a+x ./frpc_darwin_arm64
> FrakPhoneSE:/frak root# ./frpc_darwin_arm64
> 2022/09/24 15:06:53 [I] [service.go:357] [535e47879ad12c32] login to server success, get run id [535e47879ad12c32], server udp port [0]
> 2022/09/24 15:06:53 [I] [proxy_manager.go:142] [535e47879ad12c32] proxy added: [frak_ssh]
> 2022/09/24 15:06:53 [I] [control.go:177] [535e47879ad12c32] [frak_ssh] start proxy success
> ^C
> ```
> 
> Go environment setup on Mac for reference:
> 
> ```shell
> brew install golang
> # put this in ~/.bashrc:
> export GOPATH="$HOME/go"
> export GOROOT="$(brew --prefix golang)/libexec"
> export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
> ```
> 
>  ```shell
> $go version
> go version go1.19.1 darwin/arm64
> ```

i used iphone 6s ios13.5
