### ISSUE TITLE
frp能不能实现多线程访问的情况?

### ISSUE THREAD

**Issue by dgrenti** [fatedier/frp#620]
例如我想开启http这个服务，想下载一个大文件，用idm这样的多线程下载程序下载，最后发现，只能开启一个端口进行下载，也只是单线程，然后发现单线程最大的速度只能达到10Mb/s，有没有办法让客户端多个端口对应服务端的一个端口如:7000,这样就可以达到多线程的速度了!

**Comment by dgrenti** [comment]
一开始以为是软件限速了，最后发现用了几个软件也是最快也是10Mb/s，无论是下载多个文件，还是一个大文件，最大也只能去到10Mb/s，请问有没有方法解决多线程的问题?

**Comment by sesky4** [comment]
除非人为软件限制，个人感觉是没有端口限速这个机制的。
你说的限速可能是因为tcp窗口大小限制了单个连接的传输速度，多线程下载貌似是通过HTTP头的accept range，起多个连接，每个连接给不同的range然后再拼接成一个文件，你试一试nginx来提供下载应该就可以。
总之我个人认为这应该不是多线程导致的问题。

**Comment by fatedier** [comment]
是不是多线程下载取决于下载客户端软件。
