### ISSUE TITLE
猜测是由于Frp连接超时后会自动断开连接的1个问题，希望作者能解决

### ISSUE THREAD

**Issue by huxuansong** [fatedier/frp#622]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
1.5.1

**What operating system and processor architecture are you using (`go env`)?**
Frpc: CentOS 6.9 / Xeon L3426
Frps:Ubnuntu 14.04 /KVM VPS

**Configures you used:**

frps.ini
---------
[common]
bind_port = ****
bind_udp_port = ****
kcp_bind_port = ****
privilege_token = ***********
tcp_mux = false
heartbeat_timeout = 300
vhost_http_port = 80
# vhost_https_port = 443
# max_pool_count = 5
log_file = ./frps.log
log_level = info
log_max_days = 3

frpc.ini
----------------
[common]
server_addr = **.**.**.***
server_port = ***
protocol = tcp
tcp_mux = false
# protocol = kcp
heartbeat_interval = 300
heartbeat_timeout = 300
privilege_token = **********
# pool_count = 5

log_file = ./frpc.log
log_level = info
log_max_days = 3

**Steps to reproduce the issue:**
穿透的内网服务器上安装了Wordpress，使用了QQWorld自动抓取图片的插件，来**手动**抓取远程图片（比如微信公众号的图片），

已经将heartbeat_interval = 300和heartbeat_timeout = 300，设置为300秒

**Describe the results you received:**

当图片量比较少的时候，抓取保存无误；
当图片量比较多的时候（几十张图片），抓取保存出错；
直接使用nginx反代的时候（不使用frp），图片量比较多的时候也不会出错；

**Describe the results you expected:**

猜想可能是连接超时会自动断开连接的问题造成的，希望能解决这个问题

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
没有特殊情况不要修改超时配置。

**Comment by huxuansong** [comment]
@fatedier 谢谢回复，默认配置也是出现同样的问题，所以才修改超时配置的

**Comment by fatedier** [comment]
发现可能潜在的原因，尽量在下下个版本中做这方面的优化。

**Comment by fatedier** [comment]
v0.18.0 版本中对这个问题作了相应的修改，建议可以尝试，这个 issue 先关闭了，如果仍然有问题，再 reopen。

**Comment by huxuansong** [comment]
> v0.18.0 版本中对这个问题作了相应的修改，建议可以尝试，这个 issue 先关闭了，如果仍然有问题，再 reopen。

谢谢，知道今天才有空测试一下，的确问题已经完美解决了！以后可以把服务器放在单位了 ，呵呵
