### ISSUE TITLE
p2p访问错误

### ISSUE THREAD

**Issue by yanggis** [fatedier/frp#623]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.15

**What operating system and processor architecture are you using (`go env`)?**
ubuntu for clients and server

**Configures you used:**
服务端：
frps.ini
[common]
bind_addr = 0.0.0.0
bind_port = 7000
bind_udp_port = 7001

客户端1
frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[p2p_ssh]
type = xtcp
sk = xkuniversity1
local_ip = 127.0.0.1
local_port = 22

客户端2
frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[p2p_ssh_visitor]
type = xtcp
role = visitor
server_name = p2p_ssh
sk = xkuniversity1
bind_addr = 127.0.0.1
bind_port = 6000

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
试图访问的时候得到如下错误
[p2p_ssh_visitor] get sid from client error: read udp 192.168.31.127:37460: i/o timeout

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
不是所有设备都能支持，取决于NAT类型。

**Comment by lusi1990** [comment]
> 不是所有设备都能支持，取决于NAT类型。

那么哪种 NAT 类型支持呢

**Comment by ying001ch** [comment]
> 不是所有设备都能支持，取决于NAT类型。

那么什么情况下不支持呢 我也碰到了 很郁闷啊，老连不上
