### ISSUE TITLE
FRPC报错

### ISSUE THREAD

**Issue by FanhuaCloud** [fatedier/frp#625]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
$ ./frpc.exe -v
0.15.1

**What operating system and processor architecture are you using (`go env`)?**
win10 1709 16299.192

**Configures you used:**
[common]
server_addr = 139.199.89.*
server_port = 7000
privilege_token = *

[server1]
type = tcp
local_ip = 127.0.0.1
local_port = 8192
remote_port = 8192

**Steps to reproduce the issue:**
1.修改配置
2.启动客户端

**Describe the results you received:**
2018/01/28 21:28:38 [I] [proxy_manager.go:284] proxy removed: []
2018/01/28 21:28:38 [I] [proxy_manager.go:294] proxy added: [server1]
2018/01/28 21:28:38 [I] [proxy_manager.go:317] visitor removed: []
2018/01/28 21:28:38 [I] [proxy_manager.go:326] visitor added: []
2018/01/28 21:28:38 [W] [control.go:109] login to server failed: parse 127.0.0.1:1080: first path segment in URL cannot contain colon
parse 127.0.0.1:1080: first path segment in URL cannot contain colon

**Describe the results you expected:**
发生报错，无法启动

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by dgwindz** [comment]
出现相似问题，frps挂在vps上，我的是树莓派，使用的frpc版本是0.16的arm版，没配置代理，同网络下CentOS和Win7的frpc均可正常使用，

2018/02/26 15:52:38 [I] [proxy_manager.go:298] proxy removed: []
2018/02/26 15:52:38 [I] [proxy_manager.go:308] proxy added: [pc22_s8022]
2018/02/26 15:52:38 [I] [proxy_manager.go:331] visitor removed: []
2018/02/26 15:52:38 [I] [proxy_manager.go:340] visitor added: []
2018/02/26 15:52:38 [W] [control.go:109] login to server failed: dial tcp 192.168.1.101:1080: connect: connection refused dial tcp 192.168.1.101:1080: connect: connection refused

**Comment by chusiping** [comment]
我也出现这样的情况，有人发现问题在哪里吗

**Comment by fatedier** [comment]
不要使用 http proxy 来连接 frps，或者使用正确的格式。

**Comment by FanhuaCloud** [comment]
我这边测试下来是系统的问题，不过错误原因未知

**Comment by FanhuaCloud** [comment]
之前用ngrok也是这个错误

**Comment by FanhuaCloud** [comment]
不过这么一说，真的有可能是代理的问题，我本地开了ssr，有空我测试下吧

**Comment by chusiping** [comment]
我家里的home-pc也是开了shadowsocks代理的，一点事没有，启动frpc直接就loging server success了，我的工作机work-pc也是开着shadowwsock是代理的，启动frpc，却总是login to server failed: parse 127.0.0.1:1080: first path segment in URL cannot contain colon，死活都不行，在work-pc机器上开vm，在里面的桌面上开frpc，也是正常，一点异常没有，我就奇了怪了，哪里的问题啊

**Comment by fatedier** [comment]
@chusiping 检查 http proxy 相关的环境变量。

**Comment by chusiping** [comment]
谢谢fatedier提醒，谢谢大家的讨论，终于解决了
方法如下，在frpc.ini 的配置里增加了一个代理，但值是空的，问题就解决了
配置如下
1 [common]
2 server_addr = 10.10.10.01
3 server_port = 7000
4 auth_token = admin
5 privilege_token = admin
6 http_proxy = 
第6项是增加的，原来是没有的，启动frpc总是报错
加上之后，直接就login server suces！
我也不知道我的本机的http proxy是配置在哪里的，我仔细去看了frpc的配置文件，看到有一个代理的选项，就加上，测试了一下，结果就可以了

**Comment by FanhuaCloud** [comment]
@chusiping 我回家试试，感谢

**Comment by hdwmp123** [comment]
> 谢谢fatedier提醒，谢谢大家的讨论，终于解决了
> 方法如下，在frpc.ini 的配置里增加了一个代理，但值是空的，问题就解决了
> 配置如下
> 1 [common]
> 2 server_addr = 10.10.10.01
> 3 server_port = 7000
> 4 auth_token = admin
> 5 privilege_token = admin
> 6 http_proxy =
> 第6项是增加的，原来是没有的，启动frpc总是报错
> 加上之后，直接就login server suces！
> 我也不知道我的本机的http proxy是配置在哪里的，我仔细去看了frpc的配置文件，看到有一个代理的选项，就加上，测试了一下，结果就可以了

嗯嗯 这个好使

**Comment by splinter21** [comment]
或者在命令里加环境变量
http_proxy="" ./frpc -c xxx.ini

**Comment by MasterKeee** [comment]
感谢
