### ISSUE TITLE
TFS团队管理器映射后输入账号密码一直提示验证登录失败

### ISSUE THREAD

**Issue by JiangChenYang** [fatedier/frp#626]
TFS代码管理器部署在内部网络中，用http域名映射， 没有加额外的请求验证， 登录输入正确的用户名和密码就是无法通过， 用内网的ip和端口就可以验证通过访问 ， 是TFS2013

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
