### ISSUE TITLE
About Chinese gibberish.（中文乱码）

### ISSUE THREAD

**Issue by SuperManJin** [fatedier/frp#627]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.14.0

**What operating system and processor architecture are you using (`go env`)?**
win10 x64 

**Configures you used:**
#测试中文
[测试中文]
type = tcp
local_ip =192.168.3.16
local_port = 3240
remote_port = 10017

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
页面中文乱码 调整常用编码格式 utf-8 gbk 都不行
![tim 20180129104807](https://user-images.githubusercontent.com/25427359/35491519-edd58c58-04e1-11e8-9689-f4052d101998.jpg)

**Describe the results you expected:**
期望支持中文名称，或者增加备注功能。方便查找

**Comment by SifuLi** [comment]
配置文件是否为 utf-8格式？

**Comment by SuperManJin** [comment]
调整为utf-8格式后可以正常显示了。但遇到了另一个问题。在uft-8 有bom头的情况下
 项目中使用的ini "github.com/vaughan0/go-ini" 无法正常工作。 需要手动调整格式删除bom头。
当前问题已解决 
感谢回复！
