### ISSUE TITLE
把官方文档重写了下，做了简单的完善和补充。有兴趣的可以看看！

### ISSUE THREAD

**Issue by 80imike** [fatedier/frp#631]
没什么含量，做了简单的完善和补充。下面两个地址都可以访问：

推荐一款很好用的内网穿透工具--FRP

http://t.cn/R8tvJQh
https://www.hi-linux.com/posts/25686.html

**Comment by rootrl** [comment]
无耻。

**Comment by ron159** [comment]
不错不错

**Comment by lxq1** [comment]
非常棒，明了了很多

**Comment by Ehustein** [comment]
谢谢，非常详细
