### ISSUE TITLE
安卓 Android 的frpc在配置文件中使用server_addr = 域名，不能工作。望开发者亲测。

### ISSUE THREAD

**Issue by zhoujun2** [fatedier/frp#633]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
安卓 Android 的frpc在配置文件中使用server_addr = 域名，不能工作。（直接填写IP正常）
所以安卓 所有版本frpc都有这个问题
命令行报错如下
2018/01/01 00：00：00 [w] [control.go:109] login to server faied: lookup www.domain.com on [::1]:53: read udp [::1]:39942->[::1]:53: read: connection refused
lookup www.domain.com on  [::1]:53: read udp [::1]:39942->[::1]:53: read: connection refused
在很多安卓手机上做了测试，权限配置正常，DNS配置正常
你别说换成IP，有的环境IP总变，必须用域名
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
frps.ini 内容如下
server_addr = www.domain.com
server_port = 7000
type = tcp
local_ip = 127.0.0.1
local_port = 22

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.16.0 0.15.1 0.14.0

**What operating system and processor architecture are you using (`go env`)?**
Android linux

**Comment by yyingc** [comment]
server_addr = www.domain.com
换成IP

**Comment by Sak94664** [comment]
也遇到了类似的问题。
但是自己使用termux编译不会出现该问题。
亲测正常使用。

**Comment by yyingc** [comment]
因为优先采用了ipv6进行DNS解析了，导致错误。

**Comment by Droid-MAX** [comment]
难道是因为官方提供的预编译文件是静态编译的原因？

**Comment by reinit** [comment]
看日志是无法连接到53端口。你可以试试看用在你运行frp的环境下运行nslookup或者dig，看这两个命令是否能成功得到返回。

因为从[代码](https://github.com/fatedier/frp/blob/456ce09061bea765f511983b835faf6f6b44c91d/utils/net/tcp.go#L105)来看，域名解析的部分直接调用了 `net.ResolveTCPAddr`（如果是TCP直接连接的话），不应该会有这样的问题。

**Comment by Sak94664** [comment]
@reinit 可以啊。
同样的环境，官方编译的不行，自己运行却可以。

**Comment by reinit** [comment]
@Sak94664 你可以再试试看自己编译一下，用命令行：`CGO_ENABLED=0 go build -o ./frpc ./cmd/frpc`看看编译出的二进制文件是不是能重现问题。

这大概是唯一一个会导致编译出的文件Resolver行为不同的地方。

**Comment by Sak94664** [comment]
@reinit 不能重现。
(自己编译的可以运行，官方编译的不能运行)
环境是Termux.
nslookup无错误。

**Comment by reinit** [comment]
@Sak94664 Termux里的Go编译器是什么版本的？以及程序在什么样的权限下运行？

**Comment by Sak94664** [comment]
@reinit go版本1.9.2 ，程序无root运行。

**Comment by fatedier** [comment]
目前没有提供 android 环境编译好的程序，建议可以根据上述其他人编译的经验自行编译。

**Comment by iineva** [comment]
希望重新探讨解决此问题，我对此做了研究，开了个新的issue: #700
