### ISSUE TITLE
frps服务器建立hyperv客户端frpc后，外部frp直接go120.错误，提示i/0 time out。

### ISSUE THREAD

**Issue by jianbosu** [fatedier/frp#634]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.15.0    and 0.16.0

**What operating system and processor architecture are you using (`go env`)?**
frps  on windows server 2016 datacenter
frpc on windows 10 1709

**Configures you used:**
[frps.txt](https://github.com/fatedier/frp/files/1693572/frps.txt)
[frpc.txt](https://github.com/fatedier/frp/files/1693578/frpc.txt)

**Steps to reproduce the issue:**
1.启动Windows10 客户端hyper v虚拟机在服务器端（boot up a Windows 10 hyperv os on windows 2016）
2.启动frpc在hyperv windows 10系统（lauch frpc on hyper v windows 10 client os）
3.启动frpc在互联网得另一个网络里面得客户端。（lauch frpc on another pc from different lan )

**Describe the results you received:**
hyper v windows 10 will work well
another pc will down,and display i/o time out
(but only lauch another pc(shut down frpc on hyper v windows ) will work will

**Describe the results you expected:**
all of them will work together well.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
可能是网络不通的问题，你提供的信息太少，无法判断。
