### ISSUE TITLE
What is the working requirement of xtcp module?

### ISSUE THREAD

**Issue by 886yy40** [fatedier/frp#635]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
I've tried 0.14.1 and 0.16.0, but neither of them worked.

**What operating system and processor architecture are you using (`go env`)?**
frps on linux64
frpc on mipsle and win64

**Steps to reproduce the issue:**
1. "./frps -c ./frps.ini" on a linux64 server (CentOS 7)

frps.ini
```
[common]
bind_port = 7000
privilege_token = 1234567
dashboard_port = 7001
dashboard_user = admin
dashboard_pwd = 1234567
bind_udp_port = 7002
```

2. "./frpc_router -c ./frpc_router.ini &" on a mipsle router (OpenWRT)

frpc_router.ini
```
[common]
server_addr = www.123.com
server_port = 7000
privilege_token = 1234567
log_file = /dev/null
log_level = info
log_max_days = 1

[ssh]
type = xtcp
sk = 1234567
local_ip = 127.0.0.1
local_port = 22
```
3. "./frpc_pc -c ./frpc_pc.ini" on an amd64 pc (Win10)

frpc_pc.txt
```
[common]
server_addr = www.123.com
server_port = 7000
privilege_token = 1234567

[ssh_udp]
type = xtcp
role = visitor
server_name = ssh
sk = 1234567
bind_addr = 127.0.0.1
bind_port = 22
```

ps: all tcp and udp ports are opened on my router, all udp ports are opened on my pc, udp and tcp
 ports used in the conf files are also opened on my server.

**Describe the results you received:**
I tried several times, all failed with the message below (ip address of my server was in +).
> 2018/02/06 20:16:39 [W] [visitor.go:224] [ssh_udp] get natHoleRespMsg error: read udp 192.168.18.3:61478->+.+.+.+:7002: i/o timeout
2018/02/06 20:16:54 [W] [visitor.go:224] [ssh_udp] get natHoleRespMsg error: read udp 192.168.18.3:64372->+.+.+.+:7002: i/o timeout

**Describe the results you expected:**
I want to know the working requirement of xtcp module, need all clients own a public ip or they have to be under a same LAN?
Since the bandwith of VPS is really expensive, xtcp transmission will be great helpful in saving bandwith of the server, I am looking forward to its application, thank you.

**Comment by fatedier** [comment]
It depands on the device's NAT type. It's a early version, not good for all devices.
