### ISSUE TITLE
Feature request: dashboard_api for getting a client status by name

### ISSUE THREAD

**Issue by miwee** [fatedier/frp#636]
At present there is `api/proxy/traffic/:name` but it does not have info whether client is online or offline. The only workaround is to use `/api/proxy/tcp` (or udp, http etc.)  and get full data for all clients and parse specific info from this combined data.

From monitoring purpose, it is useful to have an api similar to  `api/proxy/status/:name`, which simply tells the current status and last known online time.

thanks

**Comment by miwee** [comment]
I have changed and tested this feature. I'm attaching the patch. 
I was trying to use github workflow, but I couldn't compile my forked repository. It was giving some error related to hardcoded paths github.com/fatedier
Hope this should be ok.
[0001-dashboard_api-for-getting-a-client-status-by-name.txt](https://github.com/fatedier/frp/files/1873139/0001-dashboard_api-for-getting-a-client-status-by-name.txt)

**Comment by fatedier** [comment]
Could you send a pr to dev branch? I will review it conveniently.

**Comment by fatedier** [comment]
Just change directory name `miwee` to `fatedier` to compile it.
