### ISSUE TITLE
客户端网络关闭，而服务端不能自动关闭连接

### ISSUE THREAD

**Issue by m2276699** [fatedier/frp#637]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.16.0

**What operating system and processor architecture are you using (`go env`)?**
Server：Ubuntu 16.04.3，Client：Win10

**Configures you used:**
frps.ini
[common]
bind_addr = 0.0.0.0
bind_port = 7000
bind_udp_port = 7880
kcp_bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
privilege_token = 123456
max_pool_count = 5
max_ports_per_client = 0
authentication_timeout = 900
tcp_mux = true

frpc.ini
[common]
server_addr = x.123.com
server_port = 7000
tcp_mux = true
privilege_token = 123456
protocol = kcp
tcp_mux = true
log_file = ./frpc.log
log_level = trace
log_max_days = 3
pool_count = 5

[git_web]
type = http
local_ip = 127.0.0.1
local_port = 80
use_encryption = true
use_compression = true
custom_domains = xx.123.com

**Steps to reproduce the issue:**
1.分别启动FRPS、FRPC
2.用git push 300M左右的源码到FRPC上的git server
3.进度大概80%出现一次连接断开，等待20分钟无法重连
4.20分钟后重启FRPC提示：[git_web] start error: router config conflict

**Describe the results you received:**
[git_web] start error: router config conflict

**Describe the results you expected:**
期望能正常打开frpc，或frpc能成功自动重连

**Additional information you deem important (e.g. issue happens only occasionally):**
2018/02/18 00:00:04 [I] [proxy.go:85] [b1b773b1c46f7dd6] [git_web] get a new work connection: [x.x.x.x:21439]
2018/02/18 00:00:06 [I] [proxy.go:85] [b1b773b1c46f7dd6] [git_web] get a new work connection: [x.x.x.x:21439]
2018/02/18 00:00:07 [I] [proxy.go:85] [b1b773b1c46f7dd6] [git_web] get a new work connection: [x.x.x.x:21439]
2018/02/18 00:37:20 [W] [control.go:304] [b1b773b1c46f7dd6] heartbeat timeout
2018/02/18 00:37:20 [I] [control.go:213] [b1b773b1c46f7dd6] control writer is closing
2018/02/18 00:37:20 [W] [control.go:241] [b1b773b1c46f7dd6] read error: broken pipe
2018/02/18 02:47:50 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:01 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:01 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:02 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:02 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:03 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:03 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:04 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:05 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:05 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:06 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:06 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:07 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:07 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:08 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:08 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:09 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:09 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:10 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:10 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:11 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:11 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 03:18:12 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 05:04:21 [W] [vhost.go:134] get hostname from http/https request error: EOF
2018/02/18 05:04:21 [W] [vhost.go:134] get hostname from http/https request error: Unknow error
2018/02/18 05:04:21 [W] [vhost.go:134] get hostname from http/https request error: Unknow error
2018/02/18 05:38:42 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 05:38:43 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 05:38:43 [W] [newhttp.go:189] http: proxy error: no such domain
2018/02/18 05:38:43 [W] [newhttp.go:189] http: proxy error: no such domain

2018/02/18 07:56:31 [W] [control.go:321] [31e19d14e2033f10] new proxy [git_web] error: router config conflict
2018/02/18 07:56:31 [I] [control.go:330] [31e19d14e2033f10] close proxy [git_web] success
2018/02/18 07:57:31 [W] [control.go:321] [31e19d14e2033f10] new proxy [git_web] error: router config conflict
2018/02/18 07:57:31 [I] [control.go:330] [31e19d14e2033f10] close proxy [git_web] success
2018/02/18 07:58:31 [W] [control.go:321] [31e19d14e2033f10] new proxy [git_web] error: router config conflict
2018/02/18 07:58:31 [I] [control.go:330] [31e19d14e2033f10] close proxy [git_web] success
2018/02/18 07:59:31 [W] [control.go:321] [31e19d14e2033f10] new proxy [git_web] error: router config conflict
2018/02/18 07:59:31 [I] [control.go:330] [31e19d14e2033f10] close proxy [git_web] success
2018/02/18 08:00:31 [W] [control.go:321] [31e19d14e2033f10] new proxy [git_web] error: router config conflict

**Can you point out what caused this issue (optional)**
个人感觉FRPS没有成功关闭已断开的FRPC连接，导致FRPC重连出现router config conflict的提示

**Comment by kavid** [comment]
楼主最后解决了这个吗》？》？

**Comment by xingdaos** [comment]
我部署的时候也遇到了类似的情况：
```
http: proxy error: no such domain #这是客户端配置的域名有误或没有得到正确解析，建议确认域名正确无误
error: router config conflict #这个是因为有另一个配置了相同远程端口的客户端正在运行，冲突了，建议关掉相应的一个客户端
```

**Comment by vpei** [comment]
这个问题解决了吗？
