### ISSUE TITLE
源代码中http 404页面在哪里

### ISSUE THREAD

**Issue by leekunha** [fatedier/frp#638]
如果访问未设置穿透的子域名，会有
The page you visit not found.

Sorry, the page you are looking for is currently unavailable.
Please try again later.

The server is powered by frp.

Faithfully yours, frp.
这样的页面，能否在源代码中修改一下这个页面

**Comment by denymz** [comment]
在utils/vhost/resource.go文件里，你可以自行更改后编译。我在我的博客里有过一篇关于编译frp的文章。
