### ISSUE TITLE
bittorrent类的客户端ctorrent如何进行配置

### ISSUE THREAD

**Issue by junlicn** [fatedier/frp#640]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.16.0

**What operating system and processor architecture are you using (`go env`)?**
ubuntu

**Configures you used:**
官方文档

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**
ctorrent 在 2106-2706的tcp端口监听进来的p2p服务。那么我应该如何配置呢？

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by junlicn** [comment]
在使用p2p mode 的时候？

**Comment by fatedier** [comment]
这一类的应用应该不适合使用 frp 服务穿透出去。
如果想尝试，可以试试 https://github.com/fatedier/frp#range-ports-mapping，但是不推荐。

**Comment by junlicn** [comment]
为什么不适合呢？  如果我没有路由器上的nat的port mapping 的权限， 但是我又需要让 在 2706 端口上监听tcp服务的 ctorrent运行起来，对外提供服务， 也只能这样了。 对外提供的服务会受限与frp服务器的带宽。除此还有什么好的办法么？  我查了一阵子资料发现有 ice, stun, turn 的 NAT Traversal 的穿越方案，但是需要客户端软件做修改。 或者采用 p2p 的vpn来解决穿越。 你有什么建议么？

**Comment by fatedier** [comment]
frp 只是简单的端口映射，你要对外暴露一个 p2p 的服务可能会有一些限制，取决于你要暴露出去的服务，所以能不能起作用我不确定。最好是你研究下 ctorrent 的原理，连接建立的过程，然后去选择合适的工具。
