### ISSUE TITLE
Delete proxy on disconnect

### ISSUE THREAD

**Issue by travisghansen** [fatedier/frp#642]
I'm looking to use this in a CI environment where tunnels are created and deleted at scale.  In my initial tests I'm seeing that the 'proxy' definition on the server remains after the client is killed.  Is there some way to make those disappear after a timeout or when the client disconnects?

**Comment by fatedier** [comment]
All proxies of one client will be deleted when the client disconnect. However, the stats info of those proxies reserve for 7 days, so you can see it in frps dashboard.

**Comment by travisghansen** [comment]
Ah, good to know.  Any chance that time could be made configurable?

**Comment by fatedier** [comment]
Sorry, no plan for that now. It's not a core feature.

**Comment by travisghansen** [comment]
Any chance it would be accepted if I were to put something together?  If so can you point me where that code is?

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/server/metric.go#L27
