### ISSUE TITLE
Background client on start

### ISSUE THREAD

**Issue by travisghansen** [fatedier/frp#643]
I'm looking to use the client in a CI environment.  Ideally I'd be able to start the client and have it exit (cleanly or not) immediately so the subsequent series of commands could be run which an understanding of tunnel up/down.  In my case backgrounding and doing a port check isn't super-helpful as I'm using the http type.

**Comment by fatedier** [comment]
1. Try `nohup` to let client run on background?
2. Run `frpc -c ./frpc.ini status` and you can get all status of proxies.

**Comment by travisghansen** [comment]
Yeah, I was looking into that.  Not ideal but possible, thanks for the pointer.

**Comment by yanggis** [comment]
try supervisor

**Comment by travisghansen** [comment]
Thanks for the suggestion. Supervisor doesn't fit the need here really and would be overkill.  I'm sure I can find a solution using nohup or the like...just would be nice to have a daemonize option that could exit non zero if tunnel(s) failed.
