### ISSUE TITLE
使用nginx反向代理到 frps 的 https://127.0.0.1:7443

### ISSUE THREAD

**Issue by 312102021** [fatedier/frp#644]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.16.0

**What operating system and processor architecture are you using (`go env`)?**
Ubuntu 16.04.3 LTS

**Configures you used:**
双核4G内存

**Steps to reproduce the issue:**
1. frps.ini 
bind_port = 7000
vhost_http_port = 7080
vhost_https_port = 7443
2.  nginx的配置 nginx.ini
server {
    server_name domain.com;
    listen 443 ssl;
    ssl on;
    ssl_certificate   /etc/ssl/domain.pem;
    ssl_certificate_key  /etc/ssl/domain.key;
    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://127.0.0.1:7443;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }
}
3. 启动frp ./frps -c ./frps.ini 
4. 访问 https://domain.com/, 得到以下结果
2018/02/26 19:03:36 [W] [vhost.go:134] get hostname from http/https request error: readHandshake: type[32] is not clientHello
2018/02/26 19:03:36 [W] [vhost.go:134] get hostname from http/https request error: readHandshake: type[32] is not clientHello

**Describe the results you received:**
2018/02/26 19:06:39 [W] [vhost.go:134] get hostname from http/https request error: readHandshake: type[32] is not clientHello
2018/02/26 19:06:40 [W] [vhost.go:134] get hostname from http/https request error: readHandshake: type[32] is not clientHello

**Describe the results you expected:**
[I] [proxy.go:335] [08f73ac80f20a645] [web_local.abc] https proxy listen for host [domain.com]

**Additional information you deem important (e.g. issue happens only occasionally):**
访问https://domain.com使用nginx反向代理到https://127.0.0.1:7443, 

**Can you point out what caused this issue (optional)**
我认为可能是nginx代理的过程中是否缺少了某项数据, 
但是我并不知道frps需要的是什么数据, 所以不知道如何修改.
是否有大神知道如何去修复问题?

**Comment by fatedier** [comment]
See #610
