### ISSUE TITLE
Use https on dashboard

### ISSUE THREAD

**Issue by acrogenesis** [fatedier/frp#647]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.16.0

**What operating system and processor architecture are you using (`go env`)?**
Ubuntu 16.04

**Configures you used:**
```
[common]
bind_port = 7000
privilege_allow_ports = 6000-6100
subdomain_host = domain.com
vhost_http_port = 80
dashboard_port = 7502
# dashboard's username and password are both optional，if not set, default is admin.
dashboard_user = ****
dashboard_pwd = ****
```
**Steps to reproduce the issue:**
1. Expect https://domain.com:7502 to work
2. This gives an error of can't establish secure connection
3. I can't find in the documentation how to add certs for *.domain.com,domain.com

In general I can't find where to specify which certs to use for https.

I would also like to access https://sub.domain.com and proxy that to my computer without having a cert on my computer.

**Comment by fatedier** [comment]
Try nginx to do that?
