### ISSUE TITLE
同一出口内不通网络通过stcp或xtcp访问不成功

### ISSUE THREAD

**Issue by longkeyy** [fatedier/frp#648]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.16.0

**What operating system and processor architecture are you using (`go env`)?**
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"

**Configures you used:**
==============server==================
ip: 202.108.4.4
#frps.ini
[common]
bind_addr = 0.0.0.0
bind_port = 7000
bind_udp_port = 7001
kcp_bind_port = 7000
log_level = info
log_max_days = 3
privilege_token = 123456
max_pool_count = 20

==============client a==================
ip: 192.168.100.10
wan: 202.111.111.112
#frps.ini
[common]
server_addr = 202.108.4.4
server_port = 7000
privilege_token = 123456

[secret_socks5]
type = stcp #or xtcp
sk = 123456
plugin = socks5

==============client b==================
ip: 192.168.200.10
wan: 202.111.111.112

#frpc.ini
[common]
server_addr = 202.108.4.4
server_port = 7000
privilege_token = 123456

[secret_socks5_visitor]
type = stcp #or xtcp
role = visitor
server_name = secret_socks5
sk = 123456
bind_addr = 127.0.0.1
bind_port = 1080

**Steps to reproduce the issue:**
1.  启动client a
2. 启动client b
3. 在b上用proxifier设置192.168.100.0/24 的访问走 scoks5:127.0.0.1:1080

**Describe the results you received:**

**Describe the results you expected:**
2018/03/01 09:35:07 [I] [proxy_manager.go:298] proxy removed: []
2018/03/01 09:35:07 [I] [proxy_manager.go:308] proxy added: []
2018/03/01 09:35:07 [I] [proxy_manager.go:331] visitor removed: []
2018/03/01 09:35:07 [I] [proxy_manager.go:340] visitor added: [secret_socks5_visitor]
2018/03/01 09:35:07 [I] [control.go:240] [ad07ee263a5616a2] login to server success, get run id [ad07ee263a5616a2], server udp port [7001]
2018/03/01 09:35:07 [I] [proxy_manager.go:244] [ad07ee263a5616a2] try to start visitor [secret_socks5_visitor]
2018/03/01 09:35:07 [I] [proxy_manager.go:252] [secret_socks5_visitor] start visitor success
2018/03/01 09:35:09 [W] [visitor.go:139] [secret_socks5_visitor] start new visitor connection error: custom listener for [secret_socks5] doesn't exist
2018/03/01 09:35:14 [W] [visitor.go:139] [secret_socks5_visitor] start new visitor connection error: custom listener for [secret_socks5] doesn't exist
2018/03/01 09:35:29 [W] [visitor.go:139] [secret_socks5_visitor] start new visitor connection error: custom listener for [secret_socks5] doesn't exist
2018/03/01 09:35:34 [W] [visitor.go:139] [secret_socks5_visitor] start new visitor connection error: custom listener for [secret_socks5] doesn't exist
2018/03/01 09:35:36 [W] [visitor.go:139] [secret_socks5_visitor] start new visitor connection error: custom listener for [secret_socks5] doesn't exist
2018/03/01 09:35:39 [W] [visitor.go:139] [secret_socks5_visitor] start new visitor connection error: custom listener for [secret_socks5] doesn't exist

**Additional information you deem important (e.g. issue happens only occasionally):**

当client a 与client b 在不同wan时访问正常;
当client a 与client b 在同一wan下不同内网段时，ab无法连接（a、b之间内网没有连接权限）
注释掉bind_udp_port = 7001 之后没问题

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
检查一下 server 端的日志，secret_socks5 是否启动成功了？

**Comment by longkeyy** [comment]
也许是client a的socks5没有成功启动，现在切换到udp，或者开kcp都没什么问题，也可能是网络防火墙规则发生了什么变化。
