### ISSUE TITLE
建议增加流量限制功能

### ISSUE THREAD

**Issue by LiaoChangFei** [fatedier/frp#649]
建议增加流量限制功能

**Comment by LiaoChangFei** [comment]
同样go语言的同类软件可做参考，
狗洞项目项目地址：https://github.com/vzex/dog-tunnel/

**Comment by delaynomore1996** [comment]
你直接在路由限速得了

**Comment by thinkclaves** [comment]
你这个逻辑有点儿奇怪

**Comment by LiaoChangFei** [comment]
@delaynomore1996 如果没有路由器权限呢?
@thinkclaves 哪里怪了？

**Comment by yanggis** [comment]
不要把所有功能都期望frp来完成，frp就是穿透，其他的用其他APP，像限速这种还有必要frp单独开发？什么功能都集成最后就做成一个linux系统和windows,再加一个android算了。

**Comment by LiaoChangFei** [comment]
@yanggis 你又不是作者，用你来答复？你算个蛋啊，SB玩意，拉黑了。

**Comment by yanggis** [comment]
@LiaoChangFei 疯狗出来咬人了啊，请大家小心。。。。
