### ISSUE TITLE
树莓派运行时遇到fatal error: malloc deadlock

### ISSUE THREAD

**Issue by vowers** [fatedier/frp#650]
**What version of frp are you using (./frpc -v or ./frps -v)?**

0.16.0
**What operating system and processor architecture are you using (`go env`)?**

Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

**Configures you used:**

[common]
server_addr =xxxxxx
server_port = 5443
privilege_token =xxxxxx
protocol = kcp
user = raspberrypi
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 50003
[pan]
type = http
local_port = 6800
subdomain = aria2
[pi]
type = http
local_port = 80
subdomain = pi
[cctv]
type = http
local_port = 8081
subdomain = cctv
[api]
type = http
local_port = 5000
subdomain = api 

**Steps to reproduce the issue:**
 ./frpc -c frpc.ini

**Describe the results you received:**
panic: fatal error: malloc deadlock
panic during panic

runtime stack:
runtime.startpanic_m()
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/panic.go:693 +0x164
runtime.systemstack(0x0)
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/asm_arm.s:349 +0x80
runtime.mstart()
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/proc.go:1170

goroutine 1 [running]:
runtime.systemstack_switch()
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/asm_arm.s:294 +0x4 fp=0x10c37d94 sp=0x10c37d90 pc=0x69e8c
runtime.startpanic()
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/panic.go:592 +0x10 fp=0x10c37d9c sp=0x10c37d94 pc=0x3b9ac
runtime.throw(0x33c4b1, 0xf)
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/panic.go:618 +0x54 fp=0x10c37da8 sp=0x10c37d9c pc=0x3ba88
runtime.mallocgc(0x1008, 0x0, 0x2f0301, 0x2b375b)
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/malloc.go:621 +0x96c fp=0x10c37e0c sp=0x10c37da8 pc=0x20f30
runtime.itabAdd(0x76e79088)
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/iface.go:122 +0x6c fp=0x10c37e30 sp=0x10c37e0c pc=0x1dbb8
runtime.getitab(0x2f0398, 0x2e66c0, 0x1, 0x0)
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/iface.go:70 +0x3c0 fp=0x10c37e70 sp=0x10c37e30 pc=0x1d9c4
runtime.assertE2I2(0x2f0398, 0x2e66c0, 0x10c7a610, 0x0, 0x0, 0x521e00)
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/iface.go:592 +0x34 fp=0x10c37e84 sp=0x10c37e70 pc=0x1eeac
runtime.printany(0x2e66c0, 0x10c7a610)
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/error.go:77 +0xac fp=0x10c37f14 sp=0x10c37e84 pc=0x15f48
runtime.printpanics(0x10c37f60)
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/panic.go:420 +0x54 fp=0x10c37f20 sp=0x10c37f14 pc=0x3b240
panic(0x2f56c8, 0x50b4f0)
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/panic.go:553 +0x3dc fp=0x10c37f74 sp=0x10c37f20 pc=0x3b6a0
runtime.panicmem()
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/panic.go:63 +0x54 fp=0x10c37f80 sp=0x10c37f74 pc=0x3a560
runtime.sigpanic()
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/signal_unix.go:388 +0xec fp=0x10c37fa4 sp=0x10c37f80 pc=0x51180
github.com/fatedier/frp/models/plugin.Register(...)
	/home/wcl/go_projects/src/github.com/fatedier/frp/models/plugin/plugin.go:34
github.com/fatedier/frp/models/plugin.init.1()
	/home/wcl/go_projects/src/github.com/fatedier/frp/models/plugin/socks5.go:30 +0x34 fp=0x10c37fc0 sp=0x10c37fa8 pc=0x28c588
runtime: unexpected return pc for github.com/fatedier/frp/client.init called from 0x2db368
stack: frame={sp:0x10c37fc0, fp:0x10c37fc4} stack=[0x10c36000,0x10c38000)
10c37f40:  10c37fbc  10c000e0  00000002  10c0e034 
10c37f50:  10c94601  10c0e020  10c000f4  10c000f0 
10c37f60:  00000000  002e66c0  10c7a610  00000000 
10c37f70:  00000000  00051180 <runtime.sigpanic+236>  002f56c8  0050b4f0 
10c37f80:  0028c588 <github.com/fatedier/frp/models/plugin.init.1+52>  10c000e0  00017601 <runtime.(*hmap).newoverflow+757>  10c94620 
10c37f90:  0028d968 <github.com/fatedier/frp/models/plugin.init+156>  002e93f0  10c000e0  0033ac8d 
10c37fa0:  0000000a  0028d96c <github.com/fatedier/frp/models/plugin.init+160>  0029be90 <github.com/fatedier/frp/client.init+152>  10c7eda0 
10c37fb0:  0029be88 <github.com/fatedier/frp/client.init+144>  002a7410 <main.init+120>  0003d1e0 <runtime.main+440>  0006be14 <runtime.goexit+4> 
10c37fc0: <002db368 >00000000  10c14240  00000000 
10c37fd0:  00000000  00000000  00000001  00000000 
10c37fe0:  10c000e0  00000000  00000000  00000003 
10c37ff0:  00000000  00000000  00000000  00000000 
github.com/fatedier/frp/client.init()
	<autogenerated>:1 +0x98 fp=0x10c37fc4 sp=0x10c37fc0 pc=0x29be90

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	/home/wcl/.gvm/gos/go1.10rc1/src/runtime/sigqueue.go:139 +0x130
os/signal.loop()
	/home/wcl/.gvm/gos/go1.10rc1/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.0
	/home/wcl/.gvm/gos/go1.10rc1/src/os/signal/signal_unix.go:28 +0x30

goroutine 19 [select]:
github.com/fatedier/frp/vendor/github.com/xtaci/kcp-go.(*updateHeap).updateTask(0x5115a8)
	/home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/xtaci/kcp-go/updater.go:81 +0x264
created by github.com/fatedier/frp/vendor/github.com/xtaci/kcp-go.init.2
	/home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/xtaci/kcp-go/updater.go:13 +0x5c

goroutine 20 [select]:
github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go.(*updateHeap).updateTask(0x511590)
	/home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go/updater.go:81 +0x264
created by github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go.init.2
	/home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go/updater.go:13 +0x5c

**Describe the results you expected:**
运行不起来了

**Additional information you deem important (e.g. issue happens only occasionally):**
 之前都挺好的没啥问题，今天突然就运行不起来了。。。没有更新也没有改配置什么的

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
原因不明确，是运行的时候必现？
参考这个， https://github.com/golang/go/issues/24059
后续再跟踪下是否和这个 issue 相关。

**Comment by fatedier** [comment]
我跟了下  go 的 issue，有可能有相关的 fix，下个版本使用 go1.10.1 版本编译后，可以再关注下是否解决了这个问题。

**Comment by fatedier** [comment]
我跟了下  go 的 issue，有可能有相关的 fix，下个版本使用 go1.10.1 版本编译后，可以再关注下是否解决了这个问题。

**Comment by fatedier** [comment]
v0.17.0 已经使用 go1.10.1 编译了，后续如果有问题再重新反馈下。
