### ISSUE TITLE
能把frpc客户端当代理服务器访问内网中其他机器的服务吗？

### ISSUE THREAD

**Issue by jinjfy** [fatedier/frp#653]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.16.0

**What operating system and processor architecture are you using (`go env`)?**
服务商为ubuntu16.04 64位  客户端win10 64位

**Configures you used:**
frpc客户端在内网，已设置3389，文件共享，socket5 proxy功能。
想实现从访问内网中其他主机的网页服务。可是失败了。在dashobard中能看到有21K的Traffic In，没有任何传出数据。
**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
1. 原理上来说就是内网中的一台主机开启了一个 proxy，这个台主机可以访问到其他内网主机的网页服务。
2. frp 将这个 proxy 穿透出去，则在外网页可以访问到其他主机上的服务。前提是要正确指定其他主机的网页服务的地址。

**Comment by jinjfy** [comment]
用ping命令，查到了正确的ip。在内网中用此ip也行直接访问网页。但是解析后从外网就无法访问。真是复杂。感谢。

**Comment by fatedier** [comment]
可以尝试使用 http proxy，在外网访问时填写的是内网的 ip 地址，不行的话可以通过抓包来跟踪中间哪个环节出现了问题。
