### ISSUE TITLE
win7客户端FRPC，启动失败

### ISSUE THREAD

**Issue by bxgbxm** [fatedier/frp#654]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

v0.16.0
**What operating system and processor architecture are you using (`go env`)?**
服务商为CentOS 6 x64，客户端win7 64位

**Configures you used:**
frpc  启动命令提示符内  没有成功提示也没有失败提示，一段时间后消失。

![image](https://user-images.githubusercontent.com/37093950/37011890-155d448e-212d-11e8-8f58-59411e87a679.png)

**Steps to reproduce the issue:**
1.VPS服务端设置，并能ip+端口打开，服务运行正常。
2.win7客户端启动失败
3.win7尝试其他共享frp服务可以

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
1. 尝试使用 cmd 窗口打开运行程序，不要直接点击 exe 运行。
2. 或者设置日志文件路径，如果程序失败退出，可以查看输出的错误信息，来判断原因，比如常见的连接服务器端网络失败。
