### ISSUE TITLE
能否设置多穿几个端口

### ISSUE THREAD

**Issue by wirechen** [fatedier/frp#656]
能否设置多穿几个端口？我刚刚试了配置tcp穿透端口，多个端口也只能一个端口能穿透，还是我配置的方式写的不对
![image](https://user-images.githubusercontent.com/18135347/37138251-5660ceca-22e4-11e8-9715-ae74fc34f46f.png)

**Comment by yanggis** [comment]
ssh不要重复试试？ssh1    ssh2.....

**Comment by leekunha** [comment]
重名了
