### ISSUE TITLE
http转发出错

### ISSUE THREAD

**Issue by XueyangXu** [fatedier/frp#660]
frpslog显示
[newhttp.go:184] http: proxy error: net/http: HTTP/1.x transport connection broken: unexpected EOF

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
