### ISSUE TITLE
保持持续连接问题

### ISSUE THREAD

**Issue by forwei** [fatedier/frp#663]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.16

**What operating system and processor architecture are you using (`go env`)?**
ubuntu 16.04 server
windows server 2008 client

**Configures you used:**
server:
[common]
bind_port = 7000
client:
[common]
server_addr = SERVER_IP
server_port = 7000

[1433]
type = tcp
local_ip = 127.0.0.1
local_port = 1433
remote_port = 1433

[1434]
type = udp
local_ip = 127.0.0.1
local_port = 1434
remote_port = 1434

**Steps to reproduce the issue:**
1.经过frpc的Windows版本客户端穿透访问MSSQL数据库

**Describe the results you received:**
**Describe the results you expected:**
能正常穿透连接到MSSQL服务器，但是当连接在不活动的时候，就会自动断开MSSQL连接，不能保持持续连接！

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
frp 不会主动断开连接，要穿透的服务和客户端自己维持长连接即可。请通过测试或调试的方式提供更多的信息来说明这个问题。
