### ISSUE TITLE
建议增加外部获取特权密码功能

### ISSUE THREAD

**Issue by kasuganosoras** [fatedier/frp#664]
当用户使用特权模式连接服务器的时候，服务器可以查询MySQL数据库，判断用户提交的特权密码在数据库中是否存在，数据库中可以建立多个字段分别储存每个特权密码的到期时间，允许映射的数量，这样可以实现出租的功能。

**Comment by fatedier** [comment]
作为一个主要用于内网穿透的开源项目来说，这些附加的点不是重点，不会在这里去做这些 "体力劳动"。
