### ISSUE TITLE
FRP 0.16.0 版编译错误

### ISSUE THREAD

**Issue by Angelina-ACE** [fatedier/frp#665]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.16.0源代码

**What operating system and processor architecture are you using (`go env`)?**
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/segfault/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build306542363=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

**Configures you used:**
还未编译成功

**Steps to reproduce the issue:**
1.github上下载0.16.0的源码，然后在源码目录执行make。
2.下载好软件需要的软件包（根据第一次编译报错缺少的软件包进行go get -v）
3.无软件包缺少报错之后再次编译，mian.go第63行报错。
4.然后重新下载了老版本源码直至0.13.0版本（更老的尚未尝试），编译报同一个错，而且编译不同架构的二进制文件（amd64、arm64）报同一个错。

**Describe the results you received:**
以下是编译报错结果：
go fmt ./assets/...
go fmt ./client/...
go fmt ./cmd/...
go fmt ./models/...
go fmt ./server/...
go fmt ./utils/...
go build -o bin/frps ./cmd/frps
# _/media/segfault/Dev/Dev/frp.bak/cmd/frps
cmd/frps/main.go:63: cannot use conf (type "github.com/vaughan0/go-ini".File) as type "github.com/fatedier/frp/vendor/github.com/vaughan0/go-ini".File in argument to config.LoadServerCommonConf
Makefile:26: recipe for target 'frps' failed
make: *** [frps] Error 2

**Describe the results you expected:**
能够正常编译arm64版的二进制文件

**Additional information you deem important (e.g. issue happens only occasionally):**
GO版本1.8、1.9、1.10全部尝试了，报同一个错误。

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
确认 go 环境正常，使用 go get 下载之后进入 frp 目录并编译。

**Comment by Angelina-ACE** [comment]
搞定了 果然跟源码放置的目录有关系 git clone下来的源码需要放到go path下相应源码的位置 谢谢大佬的回答
