### ISSUE TITLE
frp VNC 5900端口

### ISSUE THREAD

**Issue by vinsec** [fatedier/frp#666]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.16.0

**What operating system and processor architecture are you using (`go env`)?**
frps: CentOS 7.4
frpc:Win 10 x64

**Configures you used:**
[range:test_tcp]
type = tcp
local_ip = 127.0.0.1
local_port = 5900
remote_port = 5900

**Steps to reproduce the issue:**
1.Win配置frpc 可以访问web 其他配置都ok
2.配置多tcp端口 想实现远程vnc通过5900访问本地PC
3.远程访问frpc server:5900 无法连接

**Describe the results you received:**
无法通过vnc本地PC  即frps server无法转发发送到端口5900的请求

**Describe the results you expected:**
远程vnc连接

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
这个建议自行研究一下吧，我只能测试常规的 tcp, udp, http, https 的协议，不可能每一个应用都去深入研究。

**Comment by BI7PRK** [comment]
这与FRP无关。VNC有关。
5900是默认端口。VNC Viewer 不需要填写端口号。
但如果 端口号 比如：5911（即5900+11）。VNC Viewer 应该填写：hostname:11。

**Comment by vinsec** [comment]
还是配置出了点问题吧  没什么大问题了

**Comment by Nijisakai** [comment]
remote端口更改为其他，比如5911
然后VNC viewer访问serverip:5911

**Comment by shirh19910112** [comment]
使用frp v0.21.0测试可以使用vnc访问家里的mac，可以转发成功并使用。

**Comment by duyanhan1995** [comment]
> 使用frp v0.21.0测试可以使用vnc访问家里的mac，可以转发成功并使用。

可以看一下你的配置吗？我也遇到同样问题了

**Comment by xxyjskx1987** [comment]
分享一下配置？我也遇到同样问题了

**Comment by AndreGeng** [comment]
是说这样配置吧
```
[range:VNC]
type = tcp
local_ip = 127.0.0.1
local_port = 5900
remote_port = 5911
```
然后VNC view访问ip:5911

**Comment by 128keaton** [comment]
@AndreGeng I just tried using what you posted with no such luck :(

**Comment by xuehy** [comment]
> 
> 
> 还是配置出了点问题吧 没什么大问题了
How do you solve this?
