### ISSUE TITLE
服务器无固定外网IP，但是有外部可访问的web地址，问如何搭配作为ssh中间服务器？

### ISSUE THREAD

**Issue by chenzhihuai1990** [fatedier/frp#674]
机器A和B同一个局域网，A有web地址但无固定外网IP. 希望配置后，外部机器C可以通过A ssh 到B. 求A和B的配制方法？

**Comment by ss6916** [comment]
你需要ddns，绑定一个域名，在A上运行frps 在B上运行frpc
