### ISSUE TITLE
遇到未知的错误

### ISSUE THREAD

**Issue by kasuganosoras** [fatedier/frp#677]
我有5台服务器，都是一样的Ubuntu 16.04系统，frps和配置文件都是一样复制粘贴过去的，结果4个服务器正常，其中一个服务器连不上（之前都是好好的，今天突然就连不上了）<br>
出现了以下报错：<br>
2018/03/27 19:48:18 [W] [control.go:109] login to server failed: authorization timeout<br>
2018/03/27 19:48:28 [E] [control.go:230] authorization timeout<br>
原因不明，之前没有问题的，今天突然这样，端口经过检测是开放的。<br>
还有一个情况：frps的统计面板进不去，Chrome提示服务器没有返回数据，就是ERR_EMPTY_RESPONSE<br>
iptables和firewalld全部已经关了，80端口访问以后显示：<br>
The page you visit not found.<br>
Sorry, the page you are looking for is currently unavailable.<br>
Please try again later.<br>
The server is powered by frp.<br>
Faithfully yours, frp.<br>
求解。

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

**Comment by motecshine** [comment]
FRPC 时间问题
