### ISSUE TITLE
https下不支持host_header_rewrite吗

### ISSUE THREAD

**Issue by MonwF** [fatedier/frp#678]
**What version of frp are you using (./frpc -v or ./frps -v)?**
frps: 0.16.1 linux
frpc: 0.16.1 mac

**Configures you used:**

frps:
```ini
[common]
bind_port = 1234

privilege_allow_ports = 8800-30000
privilege_token = abc-frp

vhost_http_port = 2080
vhost_https_port = 2443
subdomain_host = frp.com
```
frpc:
```ini
[sweb]
type = https
local_ip = a.foo.com
local_port = 443
subdomain = my
host_header_rewrite = a.foo.com
```

访问 https://my.frp.com:2443 时传递给 a.foo.com 的header里host依然是 my.frp.com:2443，而非a.foo.com

**Comment by fatedier** [comment]
看说明文档，不支持 https，只支持 http。
