### ISSUE TITLE
access to frp's  https via cdn

### ISSUE THREAD

**Issue by haoasdasdf** [fatedier/frp#679]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.16.1
**What operating system and processor architecture are you using (`go env`)?**

debian9
**Configures you used:**

bind_https_port = 443

**Steps to reproduce the issue:**
1. I set up a https site
2. I successfully accessed to my site
3. I want to use cdn (like cloudflare) for my https site

**Describe the results you received:**

**Describe the results you expected:**
How can I access https via cdn when I use frp?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
It has noting to do with frp. 
frp just forward all traffic to your https service.

**Comment by xiaoyell** [comment]
It‘s need your CDN server support,changing your host of your request in header.

**Comment by haoasdasdf** [comment]
I want to use cloudflare. In this case do you know how should I set up it in cloudflare?

**Comment by fatedier** [comment]
It's not a problem about frp. So i will close it, if you want more help, try cloudflare's official website.

**Comment by lyh458** [comment]
> I want to use cloudflare. In this case do you know how should I set up it in cloudflare?

Hi, have you solved the problem?
