### ISSUE TITLE
Translate web interface completely to english

### ISSUE THREAD

**Issue by j123b567** [fatedier/frp#680]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

git master

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**

1. run frps, don't run any frpc
2. view for example http://localhost:7500/static/#/proxies/https
3. there will be untranslated text "暂无数据"

**Describe the results you received:**

Some text in chinese.

**Describe the results you expected:**

Same text in english.

**Additional information you deem important (e.g. issue happens only occasionally):**

I would like to provide PR to solve this, but I can't find the source of compressed javascript file https://github.com/fatedier/frp/blob/master/assets/static/vendor.js which contains lot more chinese texts.

**Can you point out what caused this issue (optional)**
Non english texts in https://github.com/fatedier/frp/blob/master/assets/static/vendor.js

**Comment by fatedier** [comment]
Yes, i could reproduce it.
I use [Element](http://element-cn.eleme.io/#/en-US/) in frp's dashboard and it's default language is Chinese.

I found cofigures in [Element i18n doc](http://element-cn.eleme.io/#/en-US/component/i18n). It's welcome for you to submit a PR to change it's language to english.

Find releate code  in https://github.com/fatedier/frp/blob/master/web/frps/src/main.js.
