### ISSUE TITLE
关闭之后再重新运行之前的端口未释放 run admin server error: listen tcp 127.0.0.1:7400: bind: address already in use

### ISSUE THREAD

**Issue by asseywang** [fatedier/frp#681]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.15.0

**What operating system and processor architecture are you using (`go env`)?**

no

**Configures you used:**

dsm 6.15.1
**Steps to reproduce the issue:**
1. ./frpc -c ./frpc.ini
2. control + Z
3. ./frpc -c ./frpc.ini
4. [W] [service.go:47] run admin server error: listen tcp 127.0.0.1:7400: bind: address already in use

**Describe the results you received:**

 [W] [service.go:47] run admin server error: listen tcp 127.0.0.1:7400: bind: address already in use

**Describe the results you expected:**
[service.go:49] admin server listen on 127.0.0.1:7400
**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

my frpc.ini 
admin_addr = 127.0.0.1
admin_port = 7400

第一次关闭之后再重新运行之前的端口未释放

**Comment by lovezm** [comment]
我是强行结束了端口之后再想启动报错如下
2018/04/03 20:37:50 [I] [proxy_manager.go:298] proxy removed: []
2018/04/03 20:37:50 [I] [proxy_manager.go:308] proxy added: []
2018/04/03 20:37:50 [I] [proxy_manager.go:331] visitor removed: []
2018/04/03 20:37:50 [I] [proxy_manager.go:340] visitor added: []
2018/04/03 20:37:50 [W] [control.go:109] login to server failed: dial tcp 0.0.0.0:7000: connect: connection refused
2018/04/03 20:39:22 [I] [proxy_manager.go:298] proxy removed: []
2018/04/03 20:39:22 [I] [proxy_manager.go:308] proxy added: []
2018/04/03 20:39:22 [I] [proxy_manager.go:331] visitor removed: []
2018/04/03 20:39:22 [I] [proxy_manager.go:340] visitor added: []
2018/04/03 20:39:22 [W] [control.go:109] login to server failed: dial tcp 0.0.0.0:7000: connect: connection refused
2018/04/03 20:42:39 [I] [proxy_manager.go:298] proxy removed: []
2018/04/03 20:42:39 [I] [proxy_manager.go:308] proxy added: []
2018/04/03 20:42:39 [I] [proxy_manager.go:331] visitor removed: []
2018/04/03 20:42:39 [I] [proxy_manager.go:340] visitor added: []
2018/04/03 20:42:39 [W] [control.go:109] login to server failed: dial tcp 0.0.0.0:7000: connect: connection refused

**Comment by bookgh** [comment]
等待2分钟后再连或者 改 [common] user= 的值后再连

**Comment by fatedier** [comment]
搜一下你运行 `control + Z` 是什么含义。
