### ISSUE TITLE
想问一下速度的问题

### ISSUE THREAD

**Issue by laojiu613** [fatedier/frp#682]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

我用frp做内网穿透，自己搭了一个seafile，配置了两个端口，但是上传和下载的速度特别慢，想问是因为frp的问题吗？还是我配置得不对

**Comment by fatedier** [comment]
[网络传输速度慢是什么原因？](https://github.com/fatedier/frp/wiki#%E7%BD%91%E7%BB%9C%E4%BC%A0%E8%BE%93%E9%80%9F%E5%BA%A6%E6%85%A2%E6%98%AF%E4%BB%80%E4%B9%88%E5%8E%9F%E5%9B%A0)
