### ISSUE TITLE
ssh端口被攻击

### ISSUE THREAD

**Issue by xujun05** [fatedier/frp#683]
映射在服务器的SSH端口被攻击，希望能够记录连接ssh的IP地址以及http的IP地址，以方便采用iptables封禁IP

**Comment by fatedier** [comment]
这些 case 和 frp 本身无关，可以考虑结合其他的方式去避免或解决此类问题。

**Comment by messyidea** [comment]
今天才发现，内网的端口映射到外网后，外网尝试通过ssh登录在/var/log/auth.log中记录的登录地址是127.0.0.1,直接导致fail2ban成为了摆设。看来只能强制秘钥登陆了。。
