### ISSUE TITLE
How to config https with letsencrypt?

### ISSUE THREAD

**Issue by se77en** [fatedier/frp#69]
help wanted.

**Comment by wxyzh** [comment]
1，看了下配置文件，https好像是要在后端web服务器上设置。
2，是否可以在frps上直接应用证书？

**Comment by se77en** [comment]
I put frp server side to a Docker image and run it by some port forward. eg: `docker run -d -p 8080:80 -p 8081:443 -p 7000:7000 -p 7500:7500 frp`. And use Nginx with Letsencrypt on server side and pass proxy to frp docker image, work well for me.

将 frp 服务端放在一个 Docker 镜像中，然后运行，比如：`docker run -d -p 8080:80 -p 8081:443 -p 7000:7000 -p 7500:7500 frp`。然后在服务端使用 Nginx 和 Letsencrypt，把请求转发到 Docker 镜像中。亲测可用~
