### ISSUE TITLE
ssh: connect to host 192.168.9.18 port 6000: Connection timed out，急，谢谢！！！

### ISSUE THREAD

**Issue by poppingcode** [fatedier/frp#691]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
均为0.16.1

**What operating system and processor architecture are you using (`go env`)?**
阿里云服务器：Linux iZwz98496tukjdqasfddoiZ 4.4.0-85-generic #108-Ubuntu SMP Mon Jul 3 17:24:35 UTC 2017 i686 i686 i686 GNU/Linux
内网服务器：Linux x9423-18 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
内网服务器：上面有多个用户我是其中一个，我是在我的home文件夹下得用户名目录里面配置的。
**Configures you used:**
一、阿里云服务器：
vim frps.ini
1 [common]
2 bind_port = 7000
3 vhost_http_port = 6081
nohup ./frps -c ./frps.ini &（后台执行）
二、内网服务器：我将阿里云服务器的公网地址默认为111.111.111.111
vim frpc.ini
1 [common]
2 server_addr = 111.111.111.111
3 server_port = 7000
4 auth_token = 123
5 privilege_token = 12345678
6 
7 [ssh]
8 type = tcp
9 local_ip = 127.0.0.1
10 local_port = 22
11 remote_port = 6000
./frpc -c ./frpc.ini
三、192.168.9.18是我内网服务器的地址，123是我内网服务器上vim frpc.ini设置的auth_token = 123
在阿里云服务器上ssh -oPort=6000 123@192.168.9.18
四、
过了小段时间
阿里云服务器显示：ssh: connect to host 192.168.9.18 port 6000: Connection timed out
我的内网服务显示了一条：[W] [control.go:109] login to server failed: dial tcp 111.111.111.111:7000: connect: connection timed out
**Steps to reproduce the issue:**
1.阿里云服务器显示：ssh: connect to host 192.168.9.18 port 6000: Connection timed out
2.我的内网服务显示了一条：[W] [control.go:109] login to server failed: dial tcp 111.111.111.111:7000: connect: connection timed out

**Describe the results you received:**

**Describe the results you expected:**
怎么样才能利用外网连接到内网的服务器？谢谢

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by wxlg1117** [comment]
新版本frps不支持auth_token了,只支持privilege_token
