### ISSUE TITLE
how to visit the statistic of haproxy?

### ISSUE THREAD

**Issue by blackantt** [fatedier/frp#692]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v16.1

**What operating system and processor architecture are you using (`go env`)?**
openwrt

**Configures you used:**

**Steps to reproduce the issue:**
1. now I have setup frpc on openwrt, it works. I can visit the statistic of haproxy via 'LAN-ip:88/check', 
how to setup frpc.ini so that I also can visit the statistic of haproxy via 'x.x.x.x:88/check'

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
https://github.com/fatedier/frp#visit-your-web-service-in-lan-by-custom-domains
