### ISSUE TITLE
希望后续的版本可以支持端口池，且端口池中的端口可以复用

### ISSUE THREAD

**Issue by baoguo0511** [fatedier/frp#702]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
不明所以。

**Comment by baoguo0511** [comment]
因为端口数量毕竟有限，每个终端如果必需要指定不同端口的话，早晚要有用光的一天。拓展一下，能否实现端口复用？

**Comment by fatedier** [comment]
1. 你现在遇到光口用光的 case 了吗，具体场景是什么样的？
2. 请描述下你大致上想到的端口复用的方案。

**Comment by windybird** [comment]
@fatedier 
因为有些应用服务不能改端口，当有同时运行两个同样的应用时，客户端不能更改端口，如何解决

**Comment by kavid** [comment]
楼上能说的具体点，什么应用，同时怎么部署的

**Comment by windybird** [comment]
如果有两台服务器上的服务端口相同，端口不可修改，都要经过同一个frp服务端，怎么解决？

**Comment by kavid** [comment]
不同域名就行了。

**Comment by windybird** [comment]
type = tcp 可以域名？

**Comment by kavid** [comment]
既然不是80端口

frps的6001 端口到服务器的a
frps的6002 端口到服务器的b

**Comment by fatedier** [comment]
目前支持 http 协议，根据域名路由，tcp 协议，根据端口路由。
端口是无法复用的，除非在特定的协议类型下能够对协议进行特殊处理，例如 http 协议的 host 或 url 做路由。
每一个应用可能都有自己的协议，不可能去适配，或者说从 tcp 层面复用端口不一定能实现，针对每一个应用去实现成本也比较高，这里不考虑这样的非通用的需求。
