### ISSUE TITLE
建议：添加守护进程

### ISSUE THREAD

**Issue by niluanxy** [fatedier/frp#709]
建议能添加一个守护进程，用户网络中断，或者客户端/服务端卡死后自动重载

**Comment by XiLingHost** [comment]
如果是linux，你写个服务脚本就行了，现在大多数发行版要么是SysV要么是systemd的，我个人感觉systemd的unit写起来更容易一些，不过SysV的那个init脚本写起来也不会很麻烦，二者都可以做到自动检测进程是否存在并自动重启，如果是Windows下的话我记得另一个issue有提到可以安装成系统服务。
