### ISSUE TITLE
建议http/https不强制绑定域名

### ISSUE THREAD

**Issue by maxid** [fatedier/frp#710]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.16.1

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**
[app_http]
type = http
local_ip = 127.0.0.1
local_port = 8000
remote_port = 6000

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
需要要设置subdomain

**Describe the results you expected:**
不设置subdomain，不强制绑定http及https端口
这样可以配合caddy/nginx in docker进行反向代理使用，否则caddy及nginx只能部署在宿主机上，才能识别subdomain

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by maxid** [comment]
没有问题了，type直接配置 tcp即可

**Comment by iineva** [comment]
还是存在一些应用场景问题，type=tcp，不能获取前端的真实IP地址，还是需要type=http时能提供remote_port选项，希望能重新开启问题

**Comment by Jianfenl** [comment]
同意楼上 还是存在一些应用场景问题，type=tcp，不能获取前端的真实IP地址，还是需要type=http时能提供remote_port选项，希望能重新开启问题

**Comment by fatedier** [comment]
有太多方案解决你的问题场景，不是有场景就要在应用中全部支持，只会增加不必要的维护难度，每一个项目都有侧重点，组合起来才是最高效的。

* 起多个 frps。
* frps 前面加一个 nginx 用于转发请求给 frps，nginx 可以做任意和 http 相关的操作，实用性更高。
