### ISSUE TITLE
【请教大家】再提Https转发的疑问

### ISSUE THREAD

**Issue by BI7PRK** [fatedier/frp#711]
关于Http转出现证书错误的问题。翻阅了所有Issues的相关讨论。似乎有人解决了问题。看得我云里雾里。也搞不清是怎么弄。有疑问请教一下大家：

> 1、要在转发服务里部署 Https 服务。
> 2、在转发服务上建立网站服务，配置证书。
> 3、将网站服务做反向代理到frps，使其转发到frpc。
> 4、frpc再映射内网的 web 服务器。

 是不是这样子？
![default](https://user-images.githubusercontent.com/24989210/38909970-b16b93ec-42f9-11e8-8521-4a596413bfc8.png)

-----------------------------------------
如果不是，具体是怎么做的？谢谢。

**Comment by myroid** [comment]
出现的错误可以贴出来一起看看？
方式就如你图所示，这样是可以的。

**Comment by BI7PRK** [comment]
@myroid 
就是证书错误。Client -> FRPS 时。读获取的证书可能是来自 FRPS 服务器上的。

如图所示的搭建是可以的。但这种框架不是真正意义上的转发。还是需要在FRPS服务器上配置Web服务。如果只能这么做，那么目前 FRPS 的 https 转没有实际应用意义。

**Comment by xiaoyell** [comment]
@myroid
按目前的配置文件来看，FRP的确是简单的进行数据包的转发，想实现完美的FRPS转发HTTPS可能要在FRP里增加ssl模块

**Comment by xiaoyell** [comment]
@BI7PRK 
按目前的配置文件来看，FRP只是简单的转发数据包的。想完美实现HTTPS转发，应该需要在FRPS里增加SSL模块了
