### ISSUE TITLE
work端口是否支持指定 或者 支持只用一个端口进行控制和数据交互

### ISSUE THREAD

**Issue by hanqian200705** [fatedier/frp#712]
新功能建议：frpc和frps 交互端口是否可以指定端口，目前至少需要两个，是否可以支持一个

主要应用场景： 内网出去只开放一个端口80 ，此时用frpc 虽然能连接上 frps 的common server port，但是work 端口没法指定，最终还是无法穿透。

**Comment by fatedier** [comment]
不知道你在说的是什么意思，frpc 只会连接 frps 的 7000 端口。

**Comment by hanqian200705** [comment]
理解错误 ，抱歉
