### ISSUE TITLE
请问frpc.ini以及frps.ini可否配置转发多个端口和域名？

### ISSUE THREAD

**Issue by pukanxi** [fatedier/frp#715]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.16.1

**What operating system and processor architecture are you using (`go env`)?**
windows server 2008 r2 *64   cpu：amd x4 645

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

可以同时转发多个域名及端口

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

no

**Comment by fatedier** [comment]
可以参考完整的配置文件 https://github.com/fatedier/frp#configuration-file
