### ISSUE TITLE
希望使用kcp模式的时候 开启p2p网络，可以点对点网络打洞穿透

### ISSUE THREAD

**Issue by YahuiWong** [fatedier/frp#716]
kcp本身是基于udp的，可以实现打洞功能
frps 服务端添加 客户端p2p发现功能
实现p2p功能之后可以破除 客户端必须经过服务端的网络带宽限制，节省服务端流量带宽占用

**Comment by fatedier** [comment]
See https://github.com/fatedier/frp#p2p-mode
