### ISSUE TITLE
可否指定客户端出去的网卡接口

### ISSUE THREAD

**Issue by hieixu** [fatedier/frp#717]
背景：
路由器的操作系统是LEDE，有2个wan接口，frpc 只会走默认的wan。
如果默认的wan出问题（断网，但是连接还在）了，frpc 就无法连接服务器了。

需求:
希望frpc和curl一样，增加一个interface的参数，指定出去的网络接口

**Comment by kavid** [comment]
frpc的服务器在哪里？架构是啥样的

**Comment by kavid** [comment]
那你们的wan口断了一个，你们的网络还能够正常访问的？
就是frps和frpc不能连接？估计重新启动一下frps就行了

**Comment by hieixu** [comment]
frp服务器是普通的架构。
默认wan断掉后，路由器自己是不能上网的，但是路由器下面的客户端可以正常上网。

**Comment by fatedier** [comment]
暂不考虑这个方面的问题，尽量通过外部手段或者脚本去解决吧~

**Comment by kavid** [comment]
嗯，确实没有啥必要考虑
首先专线不是那么容易断掉的。
其次这种应用范围太小了。

**Comment by dongliqiang1985** [comment]
问题描述：
设备有两个网卡，eth0(无法上网，用于内部通信)，wlan0(4G，可上网)。问题：插上eth0网线后，frpc离线。
可有解决方案？能否修改frpc.ini支持指定网卡？

**Comment by haha252** [comment]
要是能让frp在断网过后自动切换线路尝试就好了~
