### ISSUE TITLE
服务端用linux，客户端用windows可以吗？

### ISSUE THREAD

**Issue by keen88** [fatedier/frp#72]
如题

**Comment by keen88** [comment]
测试成功了，cool

**Comment by keen88** [comment]
还有个问题就是，服务端有安装lnmp，有没有办法frps和lnmp共用80端口呢？

**Comment by iyannik0215** [comment]
frps 使用 80端口, 网站使用其他端口 如 8080, 在服务端运行 frpc  把本机 8080 反向到 frps 上.

**Comment by fatedier** [comment]
我觉得 nginx 就绑定 80 端口，frps 绑定一个其他端口，nginx 的 url 路由规则非常丰富，把需要通过 frps 访问的域名或者 url 配置一下 proxy_pass 参数，转发到 frps 这样比较好，对你之前的服务也不会有太大影响。

**Comment by JimLee1996** [comment]
可以实现，nginx监听80端口，对应domain转发到frps相应端口上。
我的配置文件如下：
`server
{
    listen 80;
    server_name xx.xx.xx;
    location / {
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:82;
    }
    proxy_connect_timeout 300s;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
    proxy_buffer_size 64k;
    proxy_buffers 4 32k;
    proxy_busy_buffers_size 64k;
    proxy_temp_file_write_size 64k;
    proxy_ignore_client_abort on;
}`

**Comment by zyy111999** [comment]
1.怎样使用Windows客户端？2.能不能在访问页面前先进行用户名和密码的认证？
