### ISSUE TITLE
frpc 以后会加入多server地址的支持吗?

### ISSUE THREAD

**Issue by goodtogood** [fatedier/frp#723]
因为不涉及配置方面的问题，所以不按Issue格式发了

背景：
有一台服务器有多个外网IP,而且是非固定IP，可以ddns绑到不同域名上，
一个是防止服务器单条线路故障导致全局不可用，再一个是想充分利用多条线路的带宽，

现在用笨的方法，服务端监听一个服务端口，客户端frpc配置中的 server_addr 手工指定用不同的ddns域名，分发后再更新配置时比较麻烦，而且同一台客户端好像也没法用多条线路，目前有没有其它方法实现或以后会不会加入这种功能的支持？

**Comment by goodtogood** [comment]
是可以多个，但这样就多占用了些资源，对于IOT或嵌入式设备可能有点大

**Comment by fatedier** [comment]
如果是对资源非常敏感的设备和场景，建议还是选择 c 写的一些应用。

**Comment by kavid** [comment]
frpc的服务器上，可以运行两个客户端，同时对80端口的进行透传服务吗？
比如一台frps的是国内的服务器，一台frps的服务器是日本服务器
frpc1对国内，frpc2对日本，都可以设置80端口透传到内服服务器对吧

**Comment by fatedier** [comment]
@kavid 可以，这个是不影响的。
