### ISSUE TITLE
远程SSH登陆问题

### ISSUE THREAD

**Issue by rayisoft** [fatedier/frp#728]
**What version of frp are you using (./frpc -v or ./frps -v)?**
安装的v0.17.0，本地frpc端是ubuntu server18.04,而frps端一台是 debian8,另一台是unbuntu 16,
同样的设置，
frps.ini
```
[common]
bind_addr = [::]
bind_port = 7722
vhost_http_port = 888
vhost_https_port = 443
token = ***
```
ubuntu 服务端一切正常，但debian frps端连接正常，能进入到ssh登陆界面，就是输入密码后提示，Access denied. 我也不知道具体是哪里的问题，感觉都没问题。不知，是不是系统间加密传输的问题。

**Comment by rayisoft** [comment]
查看日志，debian端口被占用，已经解决

**Comment by liuzhaoo** [comment]
> 查看日志，debian端口被占用，已经解决
我也遇到这个问题，请问怎么解决呢，我换了bind_port  还是不行
