### ISSUE TITLE
frpc在window（10）上运行提示授权失败

### ISSUE THREAD

**Issue by RiverYangR** [fatedier/frp#729]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**
win10 64位

**Configures you used:**
frpc.ini

```
[common]
server_addr = 我自己的服务器IP（原文是IP）
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

[web]
type = http
local_port = 8090
custom_domains = www.riveryang.top
```
frps配置

```
# in square brackets, as in "[::1]:80", "[ipv6-host]:http" or "[ipv6-host%zone]:80"
bind_addr =  我自己的服务器IP（原文是IP）
bind_port = 7000
# udp port used for kcp protocol, it can be same with 'bind_port'
# if not set, kcp is disabled in frps
kcp_bind_port = 7000
# if you want to configure or reload frps by dashboard, dashboard_port must be set
dashboard_port = 6443
# dashboard assets directory(only for debug mode)
dashboard_user = admin
dashboard_pwd = FkNxdWfc
# assets_dir = ./static

vhost_http_port = 8080
vhost_https_port = 443
# console or real logFile path like ./frps.log
log_file = ./frps.log
# debug, info, warn, error

subdomain_host = www.riveryang.top
"/usr/local/frps/frps.ini" 32L, 1148C
```

**Steps to reproduce the issue:**
服务器端：
1.在服务器上安装frps，并修改配置
2.运行frps服务

客户端：
1.下载安装包
![image](https://user-images.githubusercontent.com/22918088/39405151-74fa0da8-4bd2-11e8-9966-e3b72bcdce85.png)

修改frpc.ini
2.cmd窗口运行命令frpc -c frpc.ini
3.提示登录失败
![image](https://user-images.githubusercontent.com/22918088/39405155-93e65c9e-4bd2-11e8-9353-53809ae4559b.png)

**Describe the results you received:**
C:\Users\River\Downloads\frp_0.17.0_windows_amd64>frpc -c frpc.ini
2018/04/29 17:12:43 [I] [proxy_manager.go:299] proxy removed: []
2018/04/29 17:12:43 [I] [proxy_manager.go:309] proxy added: [ssh web]
2018/04/29 17:12:43 [I] [proxy_manager.go:332] visitor removed: []
2018/04/29 17:12:43 [I] [proxy_manager.go:341] visitor added: []
2018/04/29 17:12:44 [E] [control.go:232] authorization failed
2018/04/29 17:12:44 [W] [control.go:111] login to server failed: authorization failed
authorization failed

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/wiki#%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%BF%9E%E6%8E%A5%E5%A4%B1%E8%B4%A5%E6%8F%90%E7%A4%BA-authorization-failed

**Comment by xiaoyell** [comment]
1、查看服务端与客户端版本
2、查看token值
3、以上两条我都试了，还是这个问题

**Comment by xiaoyell** [comment]
配置文件的token呢？

**Comment by 1036427414** [comment]
我也这个问题，准备看看服务端有没有出错

**Comment by talway** [comment]
win10 测试有这个问题

**Comment by garden4hu** [comment]
在token一致的情况下，你可能需要把frpc.ini中的token放在 common 里面，如下：
[common]
server_addr = 123.123.123.123
server_port = 7000
token = 12345678
