### ISSUE TITLE
frps服务端可以多开吗

### ISSUE THREAD

**Issue by xthsun** [fatedier/frp#731]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
都是0.14.0

**What operating system and processor architecture are you using (`go env`)?**
WIN64的系统，

你好，frps服务端，可以同时运行多个吗？在不同的文件夹中用不同的端口去运行。
使用情景：
用一个阿里云主机，运行多个frps,不同的客户链接自己的frps,

**Comment by fatedier** [comment]
可以，自行绑定不同的端口，需要注意的是客户端使用的端口可能会有冲突。
