### ISSUE TITLE
ipv4和ipv6同时生效如何配置

### ISSUE THREAD

**Issue by zhangruhong** [fatedier/frp#733]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

最新版
**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**
[common]
bind_addr = xx.xx.x.x
bind_port = 9001
#vhost_http_port网站访问端口
vhost_http_port = 80
vhost_https_port = 443
#dashboard_port状态以及代理统计信息展示,网址:7500可查看详情
dashboard_addr = xx.xx.x.x
dashboard_port = 9002
dashboard_user = ddddd
dashboard_pwd = dd8

log_file = ./frps.log
log_level = info
log_max_days = 3
#privilege_mode 特权模式,开通后web,ssh等使用都可以直接在客户端设置
privilege_mode = true
#特权连接密码
privilege_token = dd8
#max_pool_count最大链接池,每个代理预先与后端服务器建立起指定数量的最大链接数
max_pool_count = 50
subdomain_host = xxx.com

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**
希望可以看到同时持之ipv4和ipv6的配置教程

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by Hirozy** [comment]
设置 `bind_addr = [::]`

**Comment by zhangruhong** [comment]
@Hirozy 感谢 我试试看

**Comment by Arthur2012** [comment]
frp双栈验证成功！完美实现IPv6端口<->IPv4端口相互映射。

**Comment by cntjww** [comment]
> 设置 `bind_addr = [::]`



我设置了这条, 
[common]
bind_addr           = [::]
bind_port            = 5566
token                  = 1234567890
max_pool_count      = 255

但是0.51.1给出如下错误
C:\green\frps>frps.exe --config frps.ini
2023/12/05 08:29:05 [I] [root.go:204] frps uses config file: frps.ini
create server listener error, listen tcp: address [[::]]:5566: missing port in address

请指教一下哪里出了问题, 谢谢

**Comment by zhangruhong** [comment]
这是我的自动回复邮件。
This is an automatic reply of the email system.
您好，你的邮件我己收到，我会尽快处理，谢谢！I have received your E-mail, and I will reply as soon as possible. Thank you!

**Comment by fyjing** [comment]
> > 设置 `bind_addr = [::]`
> 
> 我设置了这条, [common] bind_addr = [::] bind_port = 5566 token = 1234567890 max_pool_count = 255
> 
> 但是0.51.1给出如下错误 C:\green\frps>frps.exe --config frps.ini 2023/12/05 08:29:05 [I] [root.go:204] frps uses config file: frps.ini create server listener error, listen tcp: address [[::]]:5566: missing port in address
> 
> 请指教一下哪里出了问题, 谢谢

旧版改为bind_addr = ::
新版的改为 bindAddr="::"

**Comment by zhangruhong** [comment]
这是我的自动回复邮件。
This is an automatic reply of the email system.
您好，你的邮件我己收到，我会尽快处理，谢谢！I have received your E-mail, and I will reply as soon as possible. Thank you!
