### ISSUE TITLE
客户端权限过大的问题，特权模式下客户端可以指定任意frp开放的端口

### ISSUE THREAD

**Issue by iRickcoder** [fatedier/frp#738]
**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.17.0
**What operating system and processor architecture are you using (`go env`)?**
Ubuntu-16.04
**Configures you used:**
```
# frps.ini

token = 12345678
allow_ports = 2000-3000,3001,3003,4000-50000
```
**Describe the results you received:**
在服务端设置token，只要客户端参数知道token后可以任意使用服务端开放的端口池。
应用场景下，客户端权利太大，无法管理客户端

**Describe the results you expected:**
希望能指定客户端配置，比如设置某个token控制分配一个端口给用户。

**Comment by fatedier** [comment]
这个项目目前本身不是用于提供多个用户的服务，仅作为个人测试开发使用，所以不会引入相关的管理功能。你可以通过修改源码自行实现自己的需求。

**Comment by fatedier** [comment]
这个项目目前本身不是用于提供多个用户的服务，仅作为个人测试开发使用，所以不会引入相关的管理功能。你可以通过修改源码自行实现自己的需求。

**Comment by iRickcoder** [comment]
好的，谢谢 @fatedier

**Comment by shoaly** [comment]
额... 本来也想提想同的问题, 看到这个issue..止步了..
确实frpc的权利目前太大了, frps那边基本无法控制端口被滥用
