### ISSUE TITLE
 Accept new mux stream error: invalid protocol version

### ISSUE THREAD

**Issue by hijk1234** [fatedier/frp#741]
frp 0.18版本
server端长时间开着就会提示这个(client端没有开启)
2018/05/05 03:05:10 [W] [service.go:247] Accept new mux stream error: invalid protocol version

后面开启client端测试了一下, 也是正常的

不知道这个提示是否正常

**Comment by fatedier** [comment]
接收到了不符合 frp 协议的请求，无视就可以。
