### ISSUE TITLE
在FRPS使用动态IP的情况下，IP变动之后FRPC连接被拒绝后并不会重新尝试连接

### ISSUE THREAD

**Issue by huxuansong** [fatedier/frp#745]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

FRPC和FRPS均为0.18.0

**What operating system and processor architecture are you using (`go env`)?**
FRPS : MT7620A
FRPC: ubuntu 14.05

**Configures you used:**

frps.ini
[common]
bind_port = ****
privilege_token = ***********

frpc.ini
[common]
server_addr = ddns.oicp.net
server_port = ********
privilege_token = ********8
log_file = frpc.log
log_level = info
log_max_days = 3

**Steps to reproduce the issue:**
1. FRPS使用的小米等MT720A路由器上运行FRPS
2. 路由器已经获得动态外网IP 218.55.55.55
3. 重启路由之后，如果旧IP 218.55.55.55仍然能ping通，则会出现下面的问题，
2018/05/05 07:47:53 [W] [control.go:111] login to server failed: dial tcp 218.66.224.70:7060: connect: connection refused ，
并且不会重新尝试连接

**Describe the results you expected:**

希望能重新尝试连接，
希望能够支持动态DDNS的FRPS，当动态DDNS刷新之后会自动尝试新的IP连接（也就是不要像NGINX那样缓存DNS直到下次重启）

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by newcastlecy** [comment]
没有心跳包

**Comment by huxuansong** [comment]
貌似是我自己的原因，不好意思，暂时关闭

**Comment by rickycm** [comment]
这个问题怎么解决的？外网地址变了之后，客户端可以自动重连吗？
