### ISSUE TITLE
dashboard_passwd设置不起作用

### ISSUE THREAD

**Issue by cianyeah** [fatedier/frp#748]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.18.0

**What operating system and processor architecture are you using (`go env`)?**
Windows Server 2012 R2

**Configures you used:**
dashboard_passwd

**Steps to reproduce the issue:**
1. dashboard_passwd设置不起作用，无论改成什么密码，dashboard的密码仍然是admin，0.16版本时正常

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by XWolcen** [comment]
我也遇到相同的问题，辛苦，developer~
还有一个问题，就是关于status_web,打开缓慢或不能打开可能是什么原因？是因为我没有安装go相关库么？

**Comment by YoungZhao** [comment]
试试  dashboard_pwd = xxxxx
新旧版本兼容的bug

我是dashboard_pwd/dashboard_passwd 两个都加上了
