### ISSUE TITLE
关于server与client时间校验能否集成NTP同步到frp中

### ISSUE THREAD

**Issue by AlliotTech** [fatedier/frp#749]
经常会有因为时间不同步而导致无法认证的情况。  后续会考虑在frp中加入时间同步或者添加取消时间校验的开关吗？

**Comment by YoungZhao** [comment]
时间设置为0就是不校验呀
另外 我不建议 frp集成  ntp  linux系统自己装ntp就好了呀 命令也不复杂

**Comment by fatedier** [comment]
No plan for that.
