### ISSUE TITLE
[bug]1.8 mipsle 时间获取有问题。

### ISSUE THREAD

**Issue by huoban** [fatedier/frp#753]
[SLT /bin]# date
Tue May  8 10:44:39 CST 2018
[SLT /bin]# frps -c /tmp/frp/myfrps.ini
2018/05/08 02:44:43 [I] [service.go:96] frps tcp listen on 0.0.0.0:7000
2018/05/08 02:44:43 [I] [service.go:164] Dashboard listen on 0.0.0.0:7500
2018/05/08 02:44:43 [I] [root.go:190] Start frps success
2018/05/08 02:44:48 [ERR] yamux: Invalid protocol version: 1
2018/05/08 02:44:48 [W] [service.go:247] Accept new mux stream error: invalid protocol version
2018/05/08 02:44:53 [ERR] yamux: Invalid protocol version: 1
2018/05/08 02:44:53 [W] [service.go:247] Accept new mux stream error: invalid protocol version
^C

![qq 20180508104608](https://user-images.githubusercontent.com/3044514/39735194-09c6f410-52ad-11e8-9a83-96467d8b11a7.png)

路由器
mtk 7620  
固件 Padavan（http://www.right.com.cn/forum/thread-161324-1-1.html）

疑似bug问题
frp的时间 +时区8   =date时间。。。

经测试 ，frpc 与 frps 都有同样的问题

frp没有增加时区的偏差。

建议！
在后续版本中。。
frp 内置获取时间。

在frp启动时，先获取时间。
之后在进行frp功能流
最后 在定时个每6小时 获取矫正下时间。

这样不管任何时区，任何电脑时间。
起码在frp之间 保证时间的统一性

**Comment by rsd1987** [comment]
自己上电的时候在MIAN函数增加时区设置即可

**Comment by RukawaKaede** [comment]
同遇到这个问题，和huoban同样的情况，时区总是和系统时区不一致
