### ISSUE TITLE
请问是不是只能保持30秒的长连接？

### ISSUE THREAD

**Issue by 235832289** [fatedier/frp#756]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.1.18

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

请问是不是只能保持30秒的长连接？
我有一个后台算法，通过webserver 去调用，时间超过30秒，每次一到30秒，frp就会断开，然后显示400的错误，但是后台的webserver还是在继续运行。
![qq 20180509102316](https://user-images.githubusercontent.com/26082466/39792404-082acfb6-5373-11e8-9ab8-ce10ce9c9b1e.png)

**Comment by xiaoyell** [comment]
看着像渣渣用友的截面😀

**Comment by 235832289** [comment]
不是，不是用友，是我自己开的的软件系统，用dev插件包而已

**Comment by 235832289** [comment]
自己通过作者的原代码解决了这个问题，在\github.com\fatedier\frp\utils\vhost\newhttp.go
有一个responseHeaderTimeout = time.Duration(30) * time.Second
更改成自己需求的秒数据即可，我系统限定的是180秒，因此这里30更还成180即可。
