### ISSUE TITLE
能否支持服务器和客户端之间用websocket连接？

### ISSUE THREAD

**Issue by xuiv** [fatedier/frp#764]
要是也能把映射的端口封装成服务端的websocket端口就太好了，毕竟不是所有人都有visa或master的信用卡。这样也能在服务端用nginx的子域名或路径把websocket反向代理出来，用这些端口的客户端再把它们转成tcp端口，总之一句话，让所有外网的连接都使用websocket.

**Comment by fatedier** [comment]
目前没有这方面的计划。
