### ISSUE TITLE
frpc xtcp命令行参数中没有--bind_port？只能指定配置文件？

### ISSUE THREAD

**Issue by iamme5945** [fatedier/frp#767]
0.17.0（含）以上版本
点对点内网穿透
……
在要访问这个服务的机器上启动另外一个 frpc，配置如下:
\# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[p2p_ssh_visitor]
type = xtcp
\# xtcp 的访问者
role = visitor
\# 要访问的 xtcp 代理的名字
server_name = p2p_ssh
sk = abcdefg
\# 绑定本地端口用于访问 ssh 服务
bind_addr = 127.0.0.1
bind_port = 6000

写命令行的话：
frpc xtcp -s x.x.x.x:7000 --role visitor --server_name p2p_ssh --sk abcdefg --bind_addr 127.0.0.1
没有--bind_port参数，没地方写绑定的端口啊？

**Comment by fatedier** [comment]
这里做了一些调整，将 host 和 port 合并了，可以直接使用 `--bind_addr 127.0.0.1:9000` 这样的方式来配置，稍后在 `-h` 说明里标注下。

**Comment by fatedier** [comment]
考虑之后，决定还是增加 `--bind_port` 参数，下个 release 版本中发布。

**Comment by iamme5945** [comment]
Ok，期待下个release！
