### ISSUE TITLE
macos high serria startup error:[W] [control.go:113] login to server failed: EOF

### ISSUE THREAD

**Issue by lixiaodong** [fatedier/frp#768]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.19.0

**What operating system and processor architecture are you using (`go env`)?**
mac os high serria

**Configures you used:**
[common]
server_addr = jettylee.com
server_port = 7000

[otc]
type = http
local_ip = 127.0.0.1
local_port = 8090
custom_domains=jettylee.com
subdomain=test
#remote_port = 6000

**Steps to reproduce the issue:**
1.modify config 
2.start ./frpc
3.error shows

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/1568575/39997175-90f4567e-57b4-11e8-8172-0b3b0a0d2981.png)

**Describe the results you expected:**

start service success
**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

sorry ,i can't

**Comment by ishland** [comment]
I have the same problem in version 0.19.0

**Comment by jouyouyun** [comment]
frps 的版本是否与 frpc 的版本一致？一致的话设置下 token 试试，我这样改了后可以了。

**Comment by lixiaodong** [comment]
@jouyouyun Thank you!you are right!I have connect to the server side success when I use the version frp 0.16.1_darwin_amd64
