### ISSUE TITLE
[FEATURE REQUEST] HTTP Referer 自动修改 / Auto Change HTTP Query's Referer

### ISSUE THREAD

**Issue by billchenchina** [fatedier/frp#769]
有些网站在你访问 CSS / JavaScript 文件时会检测你的 Referer 是否是本站的，如果不是的话直接返回 404，但 frp 目前的 referer 貌似是浏览器发出的，请求把 HTTP Query 的 Referer 自动修改。

Some website will detect your HTTP Referer when you request a CSS / JavaScript file, if your referer doesnt belong to the site, it responds a HTTP 404 Error. This issue hopes frp will change HTTP referer automatically.

**Comment by fatedier** [comment]
对这方面不是很理解，看起来是针对 http 协议的一些高级操作，是否能够先通过结合其他组件去实现？

之前有一个 issue 有相关的需求，#699 ，这一类的操作需要仔细考虑如何以适合的方式加入进来，之后有进展会在 #699 这个 issue 中更新。

**Comment by billchenchina** [comment]
@fatedier Thanks!
