### ISSUE TITLE
作者，你这个30秒的限还还没修改吗？

### ISSUE THREAD

**Issue by 235832289** [fatedier/frp#770]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
这个是我上次提及到的问题，估计我关闭了，所在作者你没有看到
https://github.com/fatedier/frp/issues/756

我看了你的代码，这个30秒的限定还是没有更改，建议改成可以配置，默认30秒，有需要的可以去修改，
![qq 20180515173431](https://user-images.githubusercontent.com/26082466/40049184-9c4f3798-5866-11e8-8d8f-ec5b30f184b1.jpg)

**Comment by fatedier** [comment]
你可以修改成可配置，然后提交 PR。

**Comment by kuleyang** [comment]
这个项目是要干掉ngrok...

**Comment by 235832289** [comment]
好，那我修改一下再提交pr,我先关闭贴了

**Comment by tiaod** [comment]
-.- 在写一个需要long pulling的项目，同样遇到这个问题
