### ISSUE TITLE
frps编译成功，但frpc编译出错，为什么？

### ISSUE THREAD

**Issue by sdpong** [fatedier/frp#771]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

make  frpc时编译时出现如下错误 ppc le 64  linux

cmd/frpc/sub/root.go:201:4: 错误：unknown field ‘Dial’ in ‘net.Resolver’
    Dial: func(ctx context.Context, network, address string) (net.Conn, error) {
    ^
Makefile:33: recipe for target 'frpc' failed

why？？？？？

**Comment by fatedier** [comment]
尝试先通过搜索引擎去解决问题。

**Comment by sdpong** [comment]
google.com baidu.com 已经搜了2、3天了没有找到解决问题办法，怀疑是不是少库了！原来都正常的！！！5555
