### ISSUE TITLE
frps ：authorization failed

### ISSUE THREAD

**Issue by duanego** [fatedier/frp#775]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.19.0

**What operating system and processor architecture are you using (`go env`)?**

Debian 9 amd64
**Configures you used:**
涉及隐私，我就不贴了

**Steps to reproduce the issue:**
1.v0.18.0用的好好的
2.下载v0.19.0amd64 Linux的包，解压，用包内的frps frpc替换原来的v0.18.0版本，配置文件仍然是原来的
3.启动服务器端->启动客户端，出现图片里面的情况
![screenshot_20180517-072212](https://user-images.githubusercontent.com/33107702/40149103-418b7de6-59a4-11e8-8390-6fe9428fa0ff.png)

**Describe the results you received:**
如图

**Describe the results you expected:**
像v0.18.0一样正常使用

**Additional information you deem important (e.g. issue happens only occasionally):**

试了几次，都这样
**Can you point out what caused this issue (optional)**
。。。不知道

**Comment by fatedier** [comment]
没有配置的话，不确定是什么问题，你自己修改下 token 相关的内容再试试。

**Comment by xiaoyell** [comment]
跟我的情况一样，但我是0.18的。

**Comment by xiaoyell** [comment]
楼主你把文件替换回去能用么？我用0.16的替换回去都不能用

**Comment by xiaxiaofu** [comment]
privilege_token renamed to token

**Comment by duanego** [comment]
在0.19.0的full.ini文件里面原本的privilege_token换成了token，我没有注意，按照楼上提示修改之后就好了！
