### ISSUE TITLE
更新到0.18后客户端连接失败

### ISSUE THREAD

**Issue by xiaoyell** [fatedier/frp#778]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.18
**What operating system and processor architecture are you using (`go env`)?**
ser：centos6
cli：windows7

**Configures you used:**
server
# [common] is integral section
[common]
# A literal address or host name for IPv6 must be enclosed
# in square brackets, as in "[::1]:80", "[ipv6-host]:http" or "[ipv6-host%zone]:80"
bind_addr = 0.0.0.0
bind_port = 5443
# udp port used for kcp protocol, it can be same with 'bind_port'
# if not set, kcp is disabled in frps
kcp_bind_port = 5443
# if you want to configure or reload frps by dashboard, dashboard_port must be set
dashboard_port = 6443
# dashboard assets directory(only for debug mode)
dashboard_user = admin
dashboard_pwd = admin
# assets_dir = ./static
vhost_http_port = 8080
vhost_https_port = 4433
# console or real logFile path like ./frps.log
log_file = ./frps.log
# debug, info, warn, error
log_level = info
log_max_days = 3
# auth token
token = 254L8QAjdPyF1JpR
# only allow frpc to bind ports you list, if you set nothing, there won't be any limit
#allow_ports = 1-65535
# pool_count in each proxy will change to max_pool_count if they exceed the maximum value
max_pool_count = 50
# if tcp stream multiplexing is used, default is true
tcp_mux = true

client
[common]
server_addr = 106.14.14.20
server_port = 5443
privilege_token = 254L8QAjdPyF1JpR
[webOA]
type = tcp
local_ip = 10.26.1.8
local_port = 80
remote_port = 6001

**Steps to reproduce the issue:**
1.客户端执行返回认证失败
2.
3.

**Describe the results you received:**
server log
2018/05/18 15:10:00 [I] [service.go:96] frps tcp listen on 0.0.0.0:5443
2018/05/18 15:10:00 [I] [service.go:105] frps kcp listen on udp 0.0.0.0:5443
2018/05/18 15:10:00 [I] [service.go:125] http service listen on 0.0.0.0:8080
2018/05/18 15:10:00 [I] [service.go:141] https service listen on 0.0.0.0:4433
2018/05/18 15:10:00 [I] [service.go:164] Dashboard listen on 0.0.0.0:6443
2018/05/18 15:10:00 [I] [root.go:190] Start frps success
2018/05/18 15:10:06 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:10:17 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:10:28 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:10:39 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:10:50 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:11:01 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:11:12 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:11:16 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:11:23 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:11:31 [I] [service.go:262] client login info: ip [58.54.1.238:55054] version [0.18.0] hostname [] os [windows] arch [amd64]
2018/05/18 15:11:31 [W] [service.go:207] authorization failed
2018/05/18 15:11:31 [W] [service.go:247] Accept new mux stream error: read tcp 172.19.240.219:5443->58.54.1.238:55054: read: connection reset by peer
2018/05/18 15:11:34 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:11:45 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:11:56 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:12:07 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:12:18 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:12:29 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:12:40 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:12:51 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:13:02 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:13:13 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:13:24 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:13:35 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:13:46 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:13:57 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:14:05 [I] [dashboard_api.go:63] Http request: [/api/serverinfo]
2018/05/18 15:14:05 [I] [dashboard_api.go:60] Http response [/api/serverinfo]: code [0]
2018/05/18 15:14:08 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:14:13 [I] [dashboard_api.go:129] Http request: [/api/proxy/udp]
2018/05/18 15:14:13 [I] [dashboard_api.go:127] Http response [/api/proxy/udp]: code [0]
2018/05/18 15:14:13 [I] [dashboard_api.go:112] Http request: [/api/proxy/tcp]
2018/05/18 15:14:13 [I] [dashboard_api.go:110] Http response [/api/proxy/tcp]: code [0]
2018/05/18 15:14:14 [I] [dashboard_api.go:63] Http request: [/api/serverinfo]
2018/05/18 15:14:14 [I] [dashboard_api.go:60] Http response [/api/serverinfo]: code [0]
2018/05/18 15:14:14 [I] [dashboard_api.go:163] Http request: [/api/proxy/https]
2018/05/18 15:14:14 [I] [dashboard_api.go:161] Http response [/api/proxy/https]: code [0]
2018/05/18 15:14:15 [I] [dashboard_api.go:63] Http request: [/api/serverinfo]
2018/05/18 15:14:15 [I] [dashboard_api.go:60] Http response [/api/serverinfo]: code [0]
2018/05/18 15:14:19 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:14:28 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:14:30 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:14:41 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:14:52 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:15:03 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:15:14 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:15:25 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:15:36 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:15:47 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:15:58 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:16:09 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:16:20 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:16:31 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:16:42 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:16:53 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:17:04 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:17:18 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:17:26 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:17:37 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:17:48 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:17:59 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:18:10 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:18:21 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:18:32 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:18:43 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:18:54 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:19:05 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:19:16 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:19:27 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:19:38 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:19:49 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:20:00 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:20:11 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:20:22 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:20:33 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:20:44 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:20:55 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:21:06 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:21:17 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:21:19 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:21:28 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:21:44 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:23:07 [I] [service.go:262] client login info: ip [180.167.114.242:15843] version [0.18.0] hostname [] os [windows] arch [amd64]
2018/05/18 15:23:07 [W] [service.go:207] authorization failed
2018/05/18 15:23:07 [W] [service.go:247] Accept new mux stream error: read tcp 172.19.240.219:5443->180.167.114.242:15843: read: connection reset by peer
2018/05/18 15:23:49 [I] [service.go:262] client login info: ip [180.167.114.242:18544] version [0.18.0] hostname [] os [windows] arch [amd64]
2018/05/18 15:23:49 [W] [service.go:207] authorization failed
2018/05/18 15:23:49 [W] [service.go:247] Accept new mux stream error: read tcp 172.19.240.219:5443->180.167.114.242:18544: read: connection reset by peer
2018/05/18 15:23:52 [I] [service.go:262] client login info: ip [180.167.114.242:18163] version [0.18.0] hostname [] os [windows] arch [amd64]
2018/05/18 15:23:52 [W] [service.go:207] authorization failed
2018/05/18 15:23:52 [W] [service.go:247] Accept new mux stream error: read tcp 172.19.240.219:5443->180.167.114.242:18163: read: connection reset by peer
2018/05/18 15:24:33 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:24:57 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:25:08 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:25:19 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:25:30 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:25:41 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:25:52 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:26:03 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:26:14 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:26:25 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:26:36 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:26:47 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:26:58 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:27:09 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:27:20 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:27:31 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:27:42 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:27:53 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:28:04 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:28:15 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:28:26 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:28:37 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:28:48 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:28:59 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:29:10 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:29:21 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:29:32 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:29:43 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:29:54 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:30:05 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:30:16 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:30:27 [W] [newhttp.go:189] http: proxy error: no such domain
2018/05/18 15:30:38 [W] [newhttp.go:189] http: proxy error: no such domain

客户端log
2018/05/18 14:56:00 [I] [proxy_manager.go:299] proxy removed: []
2018/05/18 14:56:00 [I] [proxy_manager.go:309] proxy added: [web123]
2018/05/18 14:56:00 [I] [proxy_manager.go:332] visitor removed: []
2018/05/18 14:56:00 [I] [proxy_manager.go:341] visitor added: []
2018/05/18 14:56:00 [E] [control.go:232] authorization failed
2018/05/18 14:56:00 [W] [control.go:111] login to server failed: authorization failed
2018/05/18 15:01:45 [I] [proxy_manager.go:299] proxy removed: []
2018/05/18 15:01:45 [I] [proxy_manager.go:309] proxy added: [web123]
2018/05/18 15:01:45 [I] [proxy_manager.go:332] visitor removed: []
2018/05/18 15:01:45 [I] [proxy_manager.go:341] visitor added: []
2018/05/18 15:01:45 [E] [control.go:232] authorization failed
2018/05/18 15:01:45 [W] [control.go:111] login to server failed: authorization failed

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
开始怀疑token，但是修改了还是连不上。除状态面板，其他参数真实，欢迎测试！

**Comment by xiaoyell** [comment]
找到问题了，0.18token参数名变了

**Comment by dangyuluo** [comment]
哦？文档里没有更新。
