### ISSUE TITLE
使用FRP弹错

### ISSUE THREAD

**Issue by q8263542** [fatedier/frp#779]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.16.1

**What operating system and processor architecture are you using (`go env`)?**
路由器老毛子

**Configures you used:**
默认

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
出现如下问题
The page you visit not found.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

The server is powered by frp.

Faithfully yours, frp.

**Comment by wangxianfeng** [comment]
像这种问题就不要提issue了吧，这种是因为没有配置对，具体哪里没有配置对，因为你的配置也没有贴，别人没法帮你，可以多看看官方使用文档，多摸索一下。

**Comment by q8263542** [comment]
好的，谢谢了

**Comment by wangxianfeng** [comment]
你的配置：
[web]
remote_port = 8000
type = http
local_ip = 192.168.123.1
local_port = 80
subdomain = test
官方文档配置：
[web]
type = http
local_port = 80
custom_domains = www.yourdomain.com

web服务是不需要remote_port的。

然后你访问你的子域名的时候看看能够解析到你的服务端的IP，域名那里也需要配置。域名要能解析到你的服务器IP

**Comment by xiaoyell** [comment]
subdomain_host = 我的IP
这个不对，应该是你的根域名
