### ISSUE TITLE
关于转发套接字

### ISSUE THREAD

**Issue by ets2015** [fatedier/frp#780]
我在内网主机有个mysql服务，公网服务器有个域名，请问如何配置可以让mysql服务内网穿透映射出去？
比如在frpc里有：
[mysql]
type = tcp
local_port = 3306
remote_port = 3306
use_compression = true

但不希望直接使用frps的主机IP或者域名，而是增加
subdomain = mysql这样的支持，让客户端访问mysql.frpserverdomain.com

**Comment by fatedier** [comment]
你对域名的使用姿势可能有误解，建议先自行搜索资料学习下。
