### ISSUE TITLE
panic error: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by zonas0574** [fatedier/frp#788]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.19.1
**What operating system and processor architecture are you using (`go env`)?**
go version go1.10.2 linux/arm64

**Configures you used:**
### server
[common]
bind_port = 7000
### client
[common]
server_addr = X.X.X.X
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

**Steps to reproduce the issue:**
1.自己用go在archlinuxarm编译   Linux alarm 4.16.8-1-ARCH #1 SMP Thu May 10 21:11:34 MDT 2018 aarch64 GNU/Linux
2. ./frpc -c ./frpc.ini
3.

**Describe the results you received:**
#### frps log
2018/05/21 07:21:49 [1;34m[I] [service.go:299] client login info: ip [39.190.46.194:8637] version [0.19.1] hostname [] os [linux] arch [arm64]
2018/05/21 07:21:51 [1;33m[W] [control.go:249] [2b634f20c686aae9] read error: message type error
2018/05/21 07:21:51 [1;34m[I] [control.go:220] [2b634f20c686aae9] control writer is closing
2018/05/21 07:21:51 [1;34m[I] [control.go:292] [2b634f20c686aae9] client exit success

#### frpc log
2018/05/21 11:26:40 [E] [control.go:274] [d2dbcddd42ff8bc3] panic error: runtime error: makeslice: len out of range
2018/05/21 11:26:40 [E] [control.go:275] [d2dbcddd42ff8bc3] goroutine 552 [running]:
runtime/debug.Stack(0x4420097a10, 0x815d27, 0xf)
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x88
github.com/fatedier/frp/client.(*Control).reader.func1(0x4420150180)
        /root/go/src/github.com/fatedier/frp/client/control.go:275 +0xb4
panic(0x796560, 0x8660c0)
        /usr/lib/go/src/runtime/panic.go:502 +0x1f0
github.com/fatedier/frp/vendor/github.com/fatedier/golib/msg/json.(*MsgCtl).readMsg(0x44200b6160, 0x866b00, 0x442049a480, 0x7087d0, 0x7d7980, 0x442049a480, 0x0, 0x442043a6c0, 0x6)
        /root/go/src/github.com/fatedier/frp/vendor/github.com/fatedier/golib/msg/json/process.go:51 +0x14c
github.com/fatedier/frp/vendor/github.com/fatedier/golib/msg/json.(*MsgCtl).ReadMsg(0x44200b6160, 0x866b00, 0x442049a480, 0x44203b98e0, 0x10, 0x14, 0x442049a480)
        /root/go/src/github.com/fatedier/frp/vendor/github.com/fatedier/golib/msg/json/process.go:64 +0x30
github.com/fatedier/frp/models/msg.ReadMsg(0x866b00, 0x442049a480, 0x44203b98e0, 0x10, 0x14, 0x442049a480)
        /root/go/src/github.com/fatedier/frp/models/msg/ctl.go:37 +0x38
github.com/fatedier/frp/client.(*Control).reader(0x4420150180)
        /root/go/src/github.com/fatedier/frp/client/control.go:283 +0x164
created by github.com/fatedier/frp/client.(*Control).worker
        /root/go/src/github.com/fatedier/frp/client/control.go:435 +0x5dc

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
fix 了会 panic 的问题，但是你编译的版本仍然是无法使用的，会提示出错误信息，建议换平台编译。

**Comment by zonas0574** [comment]
虽然会很快，但我这个平台真没希望吗。。

**Comment by fatedier** [comment]
这一点不是很确定，最好服务端和客户端使用统一的环境编译，你可以自己多尝试下。
