### ISSUE TITLE
server 能只监听端口来自localhost的吗

### ISSUE THREAD

**Issue by feng409** [fatedier/frp#792]
我是通过nginx反向代理，二级域名匹配，
因此不需要直接访问示例中的 vhost_http_port = 8080 端口，
能否设置 vhost_http_port 为 **127.0.0.1:8080** 而不是 **0.0.0.0:8080**

**Comment by fatedier** [comment]
请参考完整的配置文件内容： [frpc_full.ini](https://github.com/fatedier/frp/blob/master/conf/frps_full.ini)
