### ISSUE TITLE
Frp可以支持自定义kcp参数吗

### ISSUE THREAD

**Issue by bhzhu203** [fatedier/frp#794]
Frp可以支持自定义kcp参数吗，比如说支持自定义MTU，因为想在frp上再套一层转换的时候，第三方软件会报“[WARN]huge packet, data_len > 1800,dropped”  对方给的建议是 上层软件需要降低MTU的值。

如果发布新版本软件来不及，我这边可以修改源码里哪个参数可以实现修改MTU的功能？

另外 frp可以支持开放自定义其它kcp参数么。希望frp可以支持，frp是同类kcp软件中比较稳定和好用的软件

**Comment by fatedier** [comment]
不会支持，这个不是核心的功能点，如果有更复杂的需求，建议搭配其他的工具一起使用。
