### ISSUE TITLE
能增加RTSP的视屏码流代理吗？

### ISSUE THREAD

**Issue by buyingqi** [fatedier/frp#796]
想把内网的是摄像头视屏码流代理出来，能够实现吗

**Comment by fatedier** [comment]
支持的协议文档有说明，不会考虑具体的应用层协议，具体能否实现自行搜索下。

**Comment by DoSeek** [comment]
亲测使用frp可以实现海康网络摄像头(IPC)的视频代理。因为海康摄像头支持rtsp协议(端口号554)，而rtsp协议基于TCP协议。

所以在frpc.ini中增加海康摄像头的配置即可。如下：
`[common]
server_port = 7000
server_addr = yourdomain.cn
;或者是IP
;server_addr = 10.10.10.25

[ipc01-rtsp]
type        = tcp
local_ip    = 192.168.1.12
local_port  = 554
remote_port = 5540  ;端口随意，多个IPC的端口必须不一样，否则端口冲突

[ipc02-rtsp]
type        = tcp
local_ip    = 192.168.1.13
local_port  = 554
remote_port = 5541  ;端口随意，多个IPC的端口必须不一样，否则端口冲突
`
frps.ini 无需特殊配置:
`[common]
;允许访问的ip
bind_addr = 0.0.0.0

;服务端和客户端链接的端口
bind_port = 7000
`

VLC打开网络串流：
rtsp://ipc用户名:ipc密码@yourdomain.cn:5540/Streaming/Channels/101
rtsp://ipc用户名:ipc密码@yourdomain.cn:5541/Streaming/Channels/101

**Comment by CoderChen01** [comment]
学到了

**Comment by chaymankala** [comment]
How to use one port and different subdomains to stream multiple cameras?

**Comment by Daixingdeng** [comment]
> 亲测使用frp可以实现海康网络摄像头(IPC)的视频代理。因为海康摄像头支持rtsp协议(端口号554)，而rtsp协议基于TCP协议。
> 
> 所以在frpc.ini中增加海康摄像头的配置即可。如下： `[common] server_port = 7000 server_addr = yourdomain.cn ;或者是IP ;server_addr = 10.10.10.25
> 
> [ipc01-rtsp] type = tcp local_ip = 192.168.1.12 local_port = 554 remote_port = 5540 ;端口随意，多个IPC的端口必须不一样，否则端口冲突
> 
> [ipc02-rtsp] type = tcp local_ip = 192.168.1.13 local_port = 554 remote_port = 5541 ;端口随意，多个IPC的端口必须不一样，否则端口冲突 ` frps.ini 无需特殊配置:
> 
> ` [common] ;允许访问的ip bind_addr = 0.0.0.0
> 
> ;服务端和客户端链接的端口 bind_port = 7000 `
> 
> VLC打开网络串流： 如果服务器配置的是域名 rtsp://ipc用户名:ipc密码@yourdomain.cn:5540/Streaming/Channels/101 rtsp://ipc用户名:ipc密码@yourdomain.cn:5541/Streaming/Channels/101
> 
> 如果服务器配置的是IP rtsp://ipc用户名:ipc密码@10.10.10.25:5540/Streaming/Channels/101 rtsp://ipc用户名:ipc密码@10.10.10.25:5541/Streaming/Channels/101

服务器带宽有要求吗  我这边用vlc播放延时30S左右。。。 还有花屏现象
