### ISSUE TITLE
19.0无法连接

### ISSUE THREAD

**Issue by Omoinemie** [fatedier/frp#797]
客户端和服务器都是18.0的时候能够正常连接，当两者都更新到19.1后，就连接失败了，配置文件没有修改过

**Comment by Omoinemie** [comment]
[common]
# A literal address or host name for IPv6 must be enclosed
# in square brackets, as in "[::1]:80", "[ipv6-host]:http" or "[ipv6-host%zone]:80"
bind_addr = 97.64.***.***
bind_port = ****
# udp port used for kcp protocol, it can be same with 'bind_port'
# if not set, kcp is disabled in frps
kcp_bind_port = ****
# if you want to configure or reload frps by dashboard, dashboard_port must be set
dashboard_port = ****
# dashboard assets directory(only for debug mode)
dashboard_user = ****
dashboard_pwd = ****
# assets_dir = ./static
vhost_http_port = ****
vhost_https_port = ****
# console or real logFile path like ./frps.log
log_file = ./frps.log
# debug, info, warn, error
log_level = info
log_max_days = 3
# auth token
token = **************
subdomain_host = vomiku.com
# only allow frpc to bind ports you list, if you set nothing, there won't be any limit
#allow_ports = 1-65535
# pool_count in each proxy will change to max_pool_count if they exceed the maximum value
max_pool_count = 50
# if tcp stream multiplexing is used, default is true
tcp_mux = true

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
