### ISSUE TITLE
二级域名，默认转发问题

### ISSUE THREAD

**Issue by equinox-flower** [fatedier/frp#798]
请问二级域名如何配置到其他后端？
例如：
我的frps  绑定了 subdomain_host=xxx.com
 frpc 配置了 subdomain=yyy
这样 访问 yyy.xxx.com 就可以打开配置好的web。

现在是想，如何配置 访问xxx.com 时候访问 某个网页，但又不影响三级域名的访问？，比如访问xxx.com时转发到192.168.0.1:80上去。xxx.com 默认出现The page you visit not found.
或者 如何配置frps 访问未配置的域名都转发到某个ip上？

还有个问题：
[file]
type=tcp
remote_port=6000
plugin_local_path=/tmp
plugin_strip_prefix=file
plugin_http_user=admin
plugin_http_passwd=admin
plugin=static_file
无法打开
netstat -l  服务端也未见 6000端口在监听
但是dashboard看到tcp 6000端口正常运行

**Comment by BBDXF** [comment]
你这个想法与我的不谋而合，FRP单独实现不了。我是利用OpenResty+Lua+Redis实现了动态路由效果。FRP只用了端口代理功能。
话说，FRP部分功能越来越与Nginx一类的重叠了~~

**Comment by bluesky4485** [comment]
可以将frqs的vhost_http_port改为一个非80的端口，再到nginx里面将yyy.xxx.com的80端口反向代理到frqs配置的非80端口上去，xxx.com的80端口的访问就与frqs没啥关系了，可以nginx代理，也可以直接再DNS那边做域名解析

**Comment by equinox-flower** [comment]
按照楼上所说两位所说,那frp的存在价值就只为把内网暴露到服务器上?
我现在用dnsmasq + nginx 方法做 感觉 frp 就上诉功能了
而且 dnsmasq 可以根据域名直接转发,管你什么协议 这样就可以多个二级或者三级域名公用一个端口了.
比如 ssh1.xx.com --> 192.168.1.2 (ssh)
        ssh2.xx.com --> 192.168.1.3 (ssh)
类似的还有远程桌面 不用去记端口了
所以frp 是不是.......改考虑一下加入此类功能
