### ISSUE TITLE
为什么我尝试udp提示i/o deadline reached

### ISSUE THREAD

**Issue by mengdodo** [fatedier/frp#799]
服务器端的frps.ini文件
[common]
bind_port = 6100
kcp_bind_port = 6100

内网机器frpc.ini文件
[common]
server_addr = xxxxxxx
server_port = 6100
protocol = kcp

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6122

结果两端建立连接不到5秒就提示错误，frpc端进程自动断开了
2018/05/30 20:34:55 [I] [proxy_manager.go:333] visitor removed: []
2018/05/30 20:34:55 [I] [proxy_manager.go:342] visitor added: []
2018/05/30 20:35:05 [W] [control.go:113] login to server failed: i/o deadline reached

截图请点击查看
https://imgchr.com/i/C5onat
https://imgchr.com/i/C5ouIP

**Comment by love3forever** [comment]
你这个应该是frpc和frps之间就没联通，可以先排查一下网络问题

**Comment by jocongmin** [comment]
这个问题怎么解决呢，我也遇到了

**Comment by XavierXIEXIN** [comment]
我用 KCP 的时候也遇到了，不用 KCP 就没问题

**Comment by jiqing112** [comment]
同样的问题，我也没用kcp
