### ISSUE TITLE
Does't open Gzip option

### ISSUE THREAD

**Issue by niluanxy** [fatedier/frp#80]
I have update frpc and frps to latest version,and add "use_gzip = true" into frpc.ini,but when i look by dashboard,it show Gzip false,why? Whether i need to config frps.ini file?

我刚把 frpc 和 frps 升级到最新的版本，并且在 frpc.ini 中，加上了 “use_gzip = true” 的配置信息，但是我通过 dashboard 查看的时候，还是显示的没开启 Gzip。是不是还需要配置 frps.ini 文件，或者会是其它什么原因了？

```
### frpc.ini

[common]
......
server_port = 7000
log_file = /jffs/frp/frpc.log
log_level = info
log_max_days = 3

[nas]
......
pool_count = 10
use_encryption = false
use_gzip = true
```

**Comment by fatedier** [comment]
Actually the `use_gzip` option is enabled correctly and the display of proxy status isn't updated. I have fixed it.

**Comment by niluanxy** [comment]
好的，那就等你下个版本发布吧，确认是开启的就行，我想用着
