### ISSUE TITLE
负载均衡不支持range

### ISSUE THREAD

**Issue by fyhong** [fatedier/frp#802]
如果批量影射端口
[range:test]
type = tcp
local_ip = x.x.x.x
local_port = 8001,8002,8003
remote_port = 8001,8002,8003
group = 123
group_key = 123

如果用上面这样的参数运行，启动frpc会报错。
start error: group params invalid

**Comment by fatedier** [comment]
负载均衡要求 `remote_port` 相同，所以确实不支持。

**Comment by fyhong** [comment]
能不能做成以下形式？

[range:test]
type = tcp
local_ip = x.x.x.x
local_port = 8001,8002,8003
remote_port = 8001,8002,8003
group = 123,222,333
group_key = 123,222,333

[test222]
type = tcp
local_ip = x.x.x.x
local_port = 8002
remote_port = 8002
group = 222
group_key = 222
