### ISSUE TITLE
像stcp的连接方式，udp也能用吗？

### ISSUE THREAD

**Issue by 4321qasdfv** [fatedier/frp#803]
最近好像tcp封锁有点严重，我无法连接到vps的ssh了，所有tcp连接都被禁止了。
但是udp可以，所以我就使用这个工具的kcp模式连接，使用stcp成功连接了。
但是这样只能实现tcp的连接，udp就不通了。这要怎么办呢。
网络知识是0的新人求助。

**Comment by fatedier** [comment]
很明确了，是 (s **tcp**)，不支持 udp。
