### ISSUE TITLE
不能使用STCP

### ISSUE THREAD

**Issue by AragonSnow** [fatedier/frp#804]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frps 0.20.0
frpc 0.20.0
frpc_Visitor 0.20.0

**What operating system and processor architecture are you using (`go env`)?**
frps - ubuntu
frpc - win2016
frpc_Visitor - win7

**Configures you used:**
frpc 
[ubuntu_shh_stcp]
type = stcp
sk = Qwe159874123
local_ip = 192.168.1.40
local_port = 22
use_encryption = true
use_compression = true

frpc_Visitor
[secret_tcp_visitor]
role = visitor
type = stcp
server_name = ubuntu_shh_stcp
sk = Qwe159874123
bind_addr = 127.0.0.1
bind_port = 22
use_encryption = true
use_compression = true

**Steps to reproduce the issue:**
1.两台机器启动了frpc
2.连接正常
3.使用XSHELL访问Frpc_Visitor

**Describe the results you received:**
![default](https://user-images.githubusercontent.com/22835918/40958076-918299c6-68ca-11e8-8a23-c9e8901f17ad.PNG)

![image](https://user-images.githubusercontent.com/22835918/40958105-a4d01198-68ca-11e8-82c2-fcc26d9ba6bc.png)

![image](https://user-images.githubusercontent.com/22835918/40958138-c012312a-68ca-11e8-8577-590ed57aa3bf.png)

**Describe the results you expected:**
无

**Additional information you deem important (e.g. issue happens only occasionally):**
无

**Can you point out what caused this issue (optional)**
无

**Comment by Aragon159874123** [comment]
User配置是一样的。我想问一下，如果NAT类型是Udpblocked的话应该用不了吧

**Comment by fatedier** [comment]
看起来是对 user 作为 server_name 的 prefix 部分有问题，已修改。

**Comment by ljpwinxp2** [comment]
我也是0.20版本，也是碰到这种问题。我该如何在还没发布新版本的时候去修复这个问题呢
