### ISSUE TITLE
[安全疑问]FRPC会大量连接其他服务器？

### ISSUE THREAD

**Issue by ChenWenBrian** [fatedier/frp#806]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc 0.19.1

**What operating system and processor architecture are you using (`go env`)?**
CentOS 7.2

**Configures you used:**
IP直接连接frps端，部分端口映射本地服务

**Steps to reproduce the issue:**
1. 启动frpc连接服务器
2. 在Linux上查询frpc建立的连接 `netstat -ntap |grep frp`
3. 发现结果中除了第一个连接是连接到自己配置的frps的外，其他都是连接到谷歌的IP

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/7973617/41025189-d613ff88-69a3-11e8-9d7c-72de4651aa94.png)

**Describe the results you expected:**
有点不明白为什么frpc为什么会连连接大量外网的其他服务器。
通过IP查询，这些IP基本上都是连接到谷歌的服务器`（美国 加利福尼亚州圣克拉拉县山景市谷歌公司）`
不清楚这里是否有安全隐患，这些连接的目的是什么？

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by vc1** [comment]
关注，贴下配置看看吧

**Comment by fatedier** [comment]
不清楚就先自己排查下，抓个包，从最基础的配置开始测试，慢慢来，别急着看到什么就马上提问。

**Comment by ChenWenBrian** [comment]
根据@fatedier大神的建议， 抓了一夜的包（之前Linux没玩过抓包，不要笑哈）。发现全是Chrome连接Google的连接，大部分是已经中断后还没释放的连接`SYN_SENT`，只有一个`ESTABLISHED`还处于活跃状态。配置方面是因为之前在frpc端开启了**http_proxy**的plugin配置，关闭后就只有跟远端的服务器连接，以及本地端口的映射连接了。**结果符合预期，证明frpc还是很安全可靠的。**

我测试了frpc的本地端口映射配置、http_proxy配置、socks_proxy配置，全部符合预期。测试过程就不贴了，抓包都没入门，就不贻笑大方了，有兴趣的同学可以自己抓包试试各种配置。

**Comment by fatedier** [comment]
👍没接触过的多尝试尝试，以后就熟练了。
