### ISSUE TITLE
错误的配置导致frpc无法启动

### ISSUE THREAD

**Issue by nzlov** [fatedier/frp#808]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.20.0

**What operating system and processor architecture are you using (`go env`)?**
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nzlov/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nzlov/workspace/go"
GORACE=""
GOROOT="/Users/nzlov/program/go"
GOTMPDIR=""
GOTOOLDIR="/Users/nzlov/program/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_9/6616bz990gb21ds_kw9tv1x40000gn/T/go-build656839605=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Configures you used:**
```
[common]
protocol = kcp
pool_count = 5

[bt]
type = tcp
local_ip = 127.0.0.1
local_port = 6881-6999
remote_port = 6881-6999

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_prot = 6000

[p2p_ssh]
type = xtcp
local_ip = 127.0.0.1
local_port = 22
sk = xx
```

**Steps to reproduce the issue:**
start frpc

**Describe the results you received:**
```
Parse conf error: proxy [s] remote_port error
```

**Describe the results you expected:**
程序正常启动，跳过错误的配置项。

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
单项的错误配置导致整个程序无法启动，由于是在外地配置，配置错误后程序无法启动，无法再通过ssh连接更改配置。

**Comment by fatedier** [comment]
这个逻辑不会变，错误的配置会提示错误内容。
