### ISSUE TITLE
-bash: ./frps: Permission denied

### ISSUE THREAD

**Issue by sparrowjack** [fatedier/frp#81]
I was trying frp server on my vps (bandwagon host), login as root. After modifying frps.ini,I execute 
```./frps -c ./frps.ini```
and it returns 
```-bash: ./frps: Permission denied```
Am I missed sth? I would appreciate if you could give tips.
Thanks !

**Comment by fatedier** [comment]
You should make sure `frps` has execute permission, try this command `chmod 755 ./frps`.

**Comment by sparrowjack** [comment]
It turns out I may mistake between frp_x.x.x_darwin_386.tar.gz and frp_x.x.x_linux_amd64.tar.gz.
I should be more careful.
Anyway, thank u!

**Comment by blankhang** [comment]
that chmod 755 frps fix my problem
thanks

**Comment by jerrychong25** [comment]
Thanks. It fixed my permission denied problem on following commands too.

> ./frpc -c ./frpc.ini
