### ISSUE TITLE
frpc客户端连接会提示 login to server failed: EOF EOF（版本0.20.0），希望有人指点，非常感谢。

### ISSUE THREAD

**Issue by maxmoce** [fatedier/frp#810]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.20.0

**What operating system and processor architecture are you using (`go env`)?**
CentOS 7.3 64位

**Configures you used:**
服务端
[common]
bind_port = 7000
vhost_http_port = 8080
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = XXXXXX
max_pool_count = 5
authentication_timeout = 900

subdomain_host = nas.xxxx.com

[ssh]
listen_port = 6000
auth_token = 123210

黑群客户端
[common]
server_addr = 阿里云CES的IP
server_port = 7000
auth_token = 123210
pool_count = 1

[ssh]
type = tcp
local_ip = 192.168.10.201
local_port = 22
remote_port = 6000

[nas]
type = http
local_port = 5000
custom_domains = nas

[web]
type = http
local_port = 80
custom_domains = web

**Steps to reproduce the issue:**
1.已经在阿里云CES的安全组添加了7000、7500、8080端口的TCP入方向策略
2.万网已经注册并解析到阿里云CES的IP
3.服务端运行frps显示：
   ./frps -c ./frps.ini
  2018/06/08 11:25:14 [I] [service.go:128] frps tcp listen on 0.0.0.0:7000
  2018/06/08 11:25:14 [I] [service.go:161] http service listen on 0.0.0.0:8080
  2018/06/08 11:25:14 [I] [service.go:205] Dashboard listen on 0.0.0.0:7500
  2018/06/08 11:25:14 [I] [root.go:190] Start frps success

**Describe the results you received:**
黑群客户端运行会提示：
admin@DiskStation:~/frp_0.20.0_linux_amd64$ ./frpc -c ./frpc.ini
2018/06/08 11:15:29 [I] [proxy_manager.go:300] proxy removed: []
2018/06/08 11:15:29 [I] [proxy_manager.go:310] proxy added: [ssh nas web]
2018/06/08 11:15:29 [I] [proxy_manager.go:333] visitor removed: []
2018/06/08 11:15:29 [I] [proxy_manager.go:342] visitor added: []
2018/06/08 11:15:29 [W] [control.go:113] login to server failed: EOF
EOF

**Describe the results you expected:**
希望能成功连接上服务器端

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
这种网络问题，别人也无法判断，只有你自己先通过各种工具排查下网络问题，服务端客户端的日志都启用 debug 级别，然后逐一排查。

**Comment by ChenWenBrian** [comment]
网络问题的话，可以先本地telnet一下阿里服务器的7000端口，看看能否连上，能连上则跟网络无关。

**Comment by lixuande** [comment]
我用高版本客户端0.20 连接低版本服务端0.16 也是报这个错误，客户端换成0.16就解决问题了。

**Comment by lgmcode** [comment]
作者说过不同版本的通信协议可能不兼容，客户端和服务端的版本要一致，不要混着用

**Comment by ShuteLee** [comment]
老哥，你搞定了？

**Comment by zhangwen9229** [comment]
> 老哥，你搞定了？

https://blog.phpgao.com/frp_tcp_reset.html

**Comment by ghtz08** [comment]
链接失效了，大致记录下[前面链接](https://blog.phpgao.com/frp_tcp_reset.html)里的解决方案。

**Comment by yihuiluo235** [comment]
> 链接失效了，大致记录下[前面链接](https://blog.phpgao.com/frp_tcp_reset.html)里的解决方案。
> 
> 原因是防火墙识别出 frps，并阻止了 frps 的连接，需要在服务端和客户端的 `[comman]` 下加个 `tls_enable = true`，或者用 kcp 代替 tcp。

解决了，十分感谢。

**Comment by fattoliu** [comment]
> 

很赞，感谢！

**Comment by fattoliu** [comment]
> 链接失效了，大致记录下[前面链接](https://blog.phpgao.com/frp_tcp_reset.html)里的解决方案。
> 
> 原因是防火墙识别出 frps，并阻止了 frps 的连接，需要在服务端和客户端的 `[comman]` 下加个 `tls_enable = true`，或者用 kcp 代替 tcp。

很赞，感谢！

**Comment by commandoccz** [comment]
我特么捣鼓了一天，各种方法都试过了，就特么是不行，结果发现是设置了命令行代理，这里记录一下，方便后来者参考
![image](https://github.com/fatedier/frp/assets/76011848/30cf81ac-2bea-4f75-9538-13f1ffbf9bd6)

**Comment by hellohawaii** [comment]
> 

Great! I set the http_proxy and https_proxy in the environment variables, which causes the "EOF" error for me. I am using v2rayN, I do not need to quit the v2rayN, and unsetting the environment variables works for me.

**Comment by commandoccz** [comment]
> > 
> 
> Great! I set the http_proxy and https_proxy in the environment variables, which causes the "EOF" error for me. I am using v2rayN, I do not need to quit the v2rayN, and unsetting the environment variables works for me.

哈哈，我是因为开了全局代理所以会这样，一般情况下规则模式可以通过设置服务器地址绕过代理，这样就不用取消命令行代理了，有时候git的时候还是需要它的

**Comment by xsthunder** [comment]
我的情况是防火墙阻止，具体而言，frp依赖ICMP-port探测，但防火墙阻止并发送了ICMP-REJECT包，显示以上错误
