### ISSUE TITLE
范围端口映射 端口改变后流量统计显示错误

### ISSUE THREAD

**Issue by xvwvx** [fatedier/frp#815]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.20.0

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
范围端口映射 时 frpc 同一个 proxy 名字 的端口发生改变时 
 frps 的流量统计显示错误 
建议每一个 proxy 以 port 为后缀命名

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
可以考虑，你可以直接做修改后提 PR。
