### ISSUE TITLE
能否编译一个mipsel版的

### ISSUE THREAD

**Issue by FlashSoft** [fatedier/frp#82]

**Comment by fatedier** [comment]
Yes, now you can download it from [release](https://github.com/fatedier/frp/releases), but 32bit for mips is not supported in go.

**Comment by FlashSoft** [comment]
感谢，不过很可惜，那个破路由是32bit的

**Comment by p0we7** [comment]
@fatedier 请教一下Go程序是怎么样编译mips版本的。

**Comment by fatedier** [comment]
@p0we7 `env GOOS=linux GOARCH=mips64 go build -o ./frpc_linux_mips64 ./src/cmd/frpc`
