### ISSUE TITLE
希望支持低版本（例如0.16.0等）的安装以解决兼容问题，让用户可自由选择，非常感谢~

### ISSUE THREAD

**Issue by positive2010** [fatedier/frp#820]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.16.0

**What operating system and processor architecture are you using (`go env`)?**
CentOS 7.6 64位

**Configures you used:**
[common]
bind_port = 7000
vhost_http_port = 8080
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = XXXXXX
max_pool_count = 5
authentication_timeout = 900

**Steps to reproduce the issue:**
1.已经在阿里云CES的安全组添加了7000、7500、8080端口的TCP入方向策略
2.万网已经注册并解析到阿里云CES的IP
3.服务端运行frps显示：

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
希望能一脚脚本支持多版本 安装，以解决目前 不兼容的问题，因为有的路由端 没法升级frp到最新版，希望支持低版本（例如0.16.0等）的安装，非常感谢~

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
[开发状态](https://github.com/fatedier/frp/blob/master/README_zh.md#%E5%BC%80%E5%8F%91%E7%8A%B6%E6%80%81)
