### ISSUE TITLE
远程连接复制文件（大流量）会断开

### ISSUE THREAD

**Issue by luozhijie** [fatedier/frp#821]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.映射远程端口
2.复制文件到远程电脑
3.立马中断后需要等10秒左右才能重新连接
（发现只要大流量应用几十秒就会断开需要等10多秒才能重新连接）

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by sshhsh** [comment]
没有碰到你说的问题，在公网上开放易受攻击的内网服务容易被ISP封端口（如windows文件共享），你可以试试加密选项并且改变默认端口。
