### ISSUE TITLE
如何配置支持多协议的规则？

### ISSUE THREAD

**Issue by LiuYuLu** [fatedier/frp#822]
**使用版本：**0.19.1

我原本的想法是 在家里搭一个gitlab，然后通过frp把服务映射到公网上，这样我就可以在公司提交代码了。
**我是这么做的：**
1.在家里的电脑搭了一个环境，端口号是10000，我用nginx把服务代理到80端口上，同时做了域名区分。在家里测试没啥问题。
2.我用frpc通过http映射到阿里云的一个服务器上，然后还绑定了域名。测试访问页面没有问题。
3.我用在公司的电脑配置了ssh Key，然后拉取代码时不能验证通过了。。。
**我的问题**
1.frp支持域名绑定多个协议吗？比方是http、ssh、udp，能够实现域名访问。
2.如果域名绑定不支持，有没有其他方式可以实现呢，求助。

**Comment by fatedier** [comment]
域名和协议挂钩的，frp 只支持，tcp, udp, http 和 https ，域名只涉及 http 和 https，其他和域名无关。
