### ISSUE TITLE
frp服务端最多能支持多少个frp客户端

### ISSUE THREAD

**Issue by Hesper913** [fatedier/frp#826]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by kaijiezhang** [comment]
我也正想问这个问题。我这边超过大约1000台左右设备（每个设备2个端口映射）时，server端的cpu从之前不到10%一下飙升超过100%，frps挂掉了，页面打不开，REST查询也无效。frps版本是v0.17.0 linux64。

**Comment by fatedier** [comment]
自行测试即可。
