### ISSUE TITLE
use_encryption = true打开了 但实际上css js文件并没有看到体积被压缩

### ISSUE THREAD

**Issue by dieluodeai** [fatedier/frp#827]
use_encryption = true打开了 但实际上css js文件并没有看到体积被压缩，请问是什么状况

**Comment by cuiweieee** [comment]
那只是流压缩，不是内容压缩，不是一个概念。

**Comment by dieluodeai** [comment]
那怎么开启gzip压缩呢

**Comment by fatedier** [comment]
首先，`use_encryption` 是加密。
其次，你想看到浏览器下载的是压缩的 css js 文件，就去搜索相关的在 web server 上提供的解决方案。
