### ISSUE TITLE
reload failed

### ISSUE THREAD

**Issue by liguiz** [fatedier/frp#830]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.20.0
**What operating system and processor architecture are you using (`go env`)?**
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Configures you used:**
admin_addr = 127.0.0.1
admin_port = 7400
admin_user = admin
admin_passwd = ****

**Steps to reproduce the issue:**
./frpc reload -c frpc_full.ini
**Describe the results you received:**
frpc reload error: Get http://127.0.0.1:7400/api/reload: dial tcp 127.0.0.1:7400: connect: connection refused

**Describe the results you expected:**
reload success

**Additional information you deem important (e.g. issue happens only occasionally):**

ubuntu
sudo lsof -i:7400 get none echo

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
先启动才能 reload

**Comment by liguiz** [comment]
frp已经启动了，但是没有监听7400端口。

**Comment by fatedier** [comment]
那就把你的完整配置和启动命令贴出来。

**Comment by fatedier** [comment]
你自己先用简单的配置一步一步测试，通过日志等做排查，不要上来就放一堆配置进去，发现问题什么也不知道。

**Comment by wwhRyan** [comment]
我也遇到这个问题 ，后面发现是自己开启了DMZ，看看你端口是不是有upnp、DMZ等端口转发的设置
