### ISSUE TITLE
frpc with proxy not work!

### ISSUE THREAD

**Issue by wangchong666** [fatedier/frp#831]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
`frpc -v`
`0.16.0`

**What operating system and processor architecture are you using (`go env`)?**
`x86_64 GNU/Linux`

**Configures you used:**
`frpc.ini`
```
[common]
server_addr = x.x.x.x
server_port = 7000
http_proxy = http://x.x.x.x:3128

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6001
```
**Steps to reproduce the issue:**
1.`frpc -c /etc/frp/frpc.ini`

**Describe the results you received:**
```
2018/06/19 16:43:50 [I] [proxy_manager.go:298] proxy removed: []
2018/06/19 16:43:50 [I] [proxy_manager.go:308] proxy added: [ssh]
2018/06/19 16:43:50 [I] [proxy_manager.go:331] visitor removed: []
2018/06/19 16:43:50 [I] [proxy_manager.go:340] visitor added: []
2018/06/19 16:43:50 [W] [control.go:109] login to server failed: ConnectTcpServer using proxy error, StatusCode [403]
ConnectTcpServer using proxy error, StatusCode [403]
```

**Describe the results you expected:**
connect to my frps correct

**Additional information you deem important (e.g. issue happens only occasionally):**
- it worked well without proxy
- my proxy server worked well with `curl --proxy`

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
自行查一下 403 的含义。

**Comment by wangchong666** [comment]
我的代理服务器是不需要用户名密码的，所以我配置成这样`http_proxy = http://x.x.x.x:3128` ，而且我用curl --proxy 测试了代理没有问题

**Comment by wangchong666** [comment]
squid配置问题
```
#http_access deny CONNECT !SSL_ports 
```
