### ISSUE TITLE
设置连接重试的延迟时间

### ISSUE THREAD

**Issue by hurturk** [fatedier/frp#832]
我们可以手动设置重试超时吗？ 目前，它似乎设置了20秒。这样的选择是否存在？谢谢

**Comment by fatedier** [comment]
目前不能设置，重连间隔为 1s, 2s, 4s ... 20s，上限是 20s，当网络短暂波动时可以快速恢复，当网络长期故障时重试间隔会变长。

**Comment by hurturk** [comment]
你好，谢谢你的回应。 我会考虑为我的用例建立一个外部控制器。
