### ISSUE TITLE
小米路由mini安装frpc无法启动

### ISSUE THREAD

**Issue by wanababy** [fatedier/frp#833]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.20.0

**What operating system and processor architecture are you using (`go env`)?**
cpu model               : MIPS 24Kc V5.0
Linux version 2.6.36 (jenkins@7cb362686f49) (gcc version 4.6.3 20120201 (prerelease) (Linaro GCC 4.6-2012.02) ) #1 MiWiFi-R1CM-2.21.107 Thu Jun 14 11:59:42 UTC 2018

**Configures you used:**
[common]
server_addr = *.*.*.*
server_port = 5443
token = ****

log_file = /dev/null
log_level = info
log_max_days = 3

[miin]
remote_port = 816
type = http
local_ip = 192.168.31.1
local_port = 80
subdomain = miin

**Steps to reproduce the issue:**
1.执行 ./frpc -c frpc.ini后没反应。
2.执行./frpc http返回的命令如下
3.执行./frpc tcp返回的命令如下

**Describe the results you received:**
./frpc http
2018/06/20 07:35:25 [I] [proxy_manager.go:300] proxy removed: []
2018/06/20 07:35:25 [I] [proxy_manager.go:310] proxy added: []
2018/06/20 07:35:25 [I] [proxy_manager.go:333] visitor removed: []
2018/06/20 07:35:25 [I] [proxy_manager.go:342] visitor added: []
2018/06/20 07:35:25 [W] [control.go:113] login to server failed: dial tcp 127.0.0.1:7000: connect: connection refused
dial tcp 127.0.0.1:7000: connect: connection refused

root@XiaoQiang:/extdisks/sda1/frp# ./frpc tcp
2018/06/20 07:50:54 [I] [proxy_manager.go:300] proxy removed: []
2018/06/20 07:50:54 [I] [proxy_manager.go:310] proxy added: []
2018/06/20 07:50:54 [I] [proxy_manager.go:333] visitor removed: []
2018/06/20 07:50:54 [I] [proxy_manager.go:342] visitor added: []
2018/06/20 07:50:54 [W] [control.go:113] login to server failed: dial tcp 127.0.0.1:7000: connect: connection refused
dial tcp 127.0.0.1:7000: connect: connection refused

**Describe the results you expected:**
frpc 能运行起来

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by jmjasonchan** [comment]
我也是这个情况，也是小米MINI，frpc是2.0的版本，你解决了吗？

**Comment by jmjasonchan** [comment]
frpc reload -c /tmp/frp/myfrpc.ini
frpc reload error: Get http://127.0.0.1:7400/api/reload: dial tcp 127.0.0.1:7400: connect: connection refused

**Comment by jmjasonchan** [comment]
2018/07/10 02:03:11 [I] [proxy_manager.go:300] proxy removed: []
2018/07/10 02:03:11 [I] [proxy_manager.go:310] proxy added: [web]
2018/07/10 02:03:11 [I] [proxy_manager.go:333] visitor removed: []
2018/07/10 02:03:11 [I] [proxy_manager.go:342] visitor added: []
2018/07/10 02:03:11 [W] [control.go:113] login to server failed: EOF

**Comment by wanababy** [comment]
小米路由器有限制，第三方插件得加入他们的开发工具，现在有第三方工具包，现在我就是装这个：
https://github.com/monlor/Monlor-Tools

**Comment by jmjasonchan** [comment]
估计是token的问题，server v=0.12.1,  client v =2.0, 各自的 token用法不一样，server 是用privilege_token, client就是用token,所以两边不兼容导致连接失败。

**Comment by jmjasonchan** [comment]
@wanababy 小米路由已刷pavadan

**Comment by wanababy** [comment]
那你更新服务器端或者更换服务器吧，版本差别太大不兼容的。

**Comment by jmjasonchan** [comment]
@wanababy 谢谢你的回复，想问一下怎么更新服务器端？有相关的说明文件吗？我在github看不到此类手册，网上也找不到，谢谢！

**Comment by fatedier** [comment]
具体的环境问题就请自己定位问题了，比如你使用相同的配置，在其他 linux 环境下可以，在特定路由器下不可以，其他人也很难定位到原因。

**Comment by lushangkan** [comment]
你好楼主，我解决了这个问题，我也是R1CM(MINI)，请楼主将log相关的配置删除，使用mipsle的包，我已经刷了第三方固件
