### ISSUE TITLE
请教一下加密算法用的是什么？

### ISSUE THREAD

**Issue by yj7778826** [fatedier/frp#840]
能否用于传输敏感数据

**Comment by fatedier** [comment]
请通过阅读代码来找到答案。

**Comment by fatedier** [comment]
抱歉，这个项目的目的就是贡献源码让大家交流讨论，所有人也都可以参与贡献代码。如果你的目的只是索取使用，请出门左转各种商业项目以及其他的下载即用的程序。

能读懂代码最好，不能读懂代码也可以通过其他方式做出贡献，比如反馈 bug，提出新功能的意见。这是开源项目，不是我做出一个东西来教你怎么用，教你如何实现，每一个细节是怎么做的。如果这样的话，开源代码是为什么？举个例子来说吧，你每次使用 linux 遇到点不会的问题，都要去 linux 这个项目的 issue 里去提问？你觉得自己的时间要比其他人的时间宝贵很多吗？

我不知道如果每个人都是你这样的提问方式的话，这个项目开源的意义在哪。

你不会 go，那么你同样有很多种选择：
1. 学习 go，做出你的贡献。
2. 寻找你熟悉的语言实现的类似的项目。
3. 请教你周围能读懂这个项目的人，或搜索引擎，或其他方式。
3. 放弃，做其他事。
