### ISSUE TITLE
可以在服务端关闭指定链接吗。

### ISSUE THREAD

**Issue by zgjsntsm** [fatedier/frp#842]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.20.0
**What operating system and processor architecture are you using (`go env`)?**
linux

服务端可以控制每个连接的开关吗？

**Comment by fatedier** [comment]
不可以。
