### ISSUE TITLE
密码的两种命令造成误导

### ISSUE THREAD

**Issue by AragonSnow** [fatedier/frp#844]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.20.0

**What operating system and processor architecture are you using (`go env`)?**
all

**Configures you used:**

**Steps to reproduce the issue:**
1.frps 使用token
2.frpc使用privilege_token
3.frpc提示密码错误

**Describe the results you received:**

**Describe the results you expected:**
希望两种方式都能被识别，或者强制使用其中一种方式

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
https://github.com/fatedier/frp#authentication

**Comment by AragonSnow** [comment]
不是，我是说，privilege_token和token这两种方式都是有效的，在我连接到免费的服务器frps时，无法判断对方是使用的privilege_token还是token，只能二选一的尝试。所以建议是强制使用一种，或者privilege_token和token等效。

**Comment by AragonSnow** [comment]
不是，我是说，privilege_token和token这两种方式都是有效的，在我连接到免费的服务器frps时，无法判断对方是使用的privilege_token还是token，只能二选一的尝试。所以建议是强制使用一种，或者privilege_token和token等效。

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/README_zh.md#%E5%BC%80%E5%8F%91%E7%8A%B6%E6%80%81

目前不保证向后兼容，所以文档里写的很清楚是 `token`，没有 `privilege_token`，请保持服务端和客户端版本的统一。
