### ISSUE TITLE
frp是否支持Server Sent Events(SSE)?

### ISSUE THREAD

**Issue by chinason** [fatedier/frp#845]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.20.0

**What operating system and processor architecture are you using (`go env`)?**
Windows10 AMD64

**Configures you used:**
frpc.ini
[common]
server_addr = 127.0.0.1
server_port = 7000
[web]
type = http
local_ip = 127.0.0.1
local_port = 8000
use_encryption = false
use_compression = false
subdomain = test

**Steps to reproduce the issue:**
1. 请求SSE服务时
2. 
3.

**Describe the results you received:**
SSE请求长时间没有应答，最终超时。

**Describe the results you expected:**
frp可以支持SSE。

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
对于SSE响应（响应头中有Content-Type: text/event-stream)，一直等待返回结果。
像nginx作为反向代理时，如果SSE服务返回的响应头中有 X-Accel-Buffering: no时就可以支持SSE。

**Comment by fatedier** [comment]
不是很了解这个使用姿势，但是对于一些特殊的 case，可以考虑直接使用 tcp 的类型。

**Comment by chengjianhua** [comment]
@chinason 请问下你是如何修改支持 SSE 的呢, 我也正有这样的需求, 废了大半天的劲才发现是 frp 代理的问题...

@fatedier 请问下如何能够让 frp 支持 [SSE](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Sending_events_from_the_server) 呢

**Comment by fatedier** [comment]
@chengjianhua 没有计划支持这个，如果 @chinason 能提供 PR，不影响正常 http 请求的话，可以考虑。

**Comment by chinason** [comment]
> @chinason 请问下你是如何修改支持 SSE 的呢, 我也正有这样的需求, 废了大半天的劲才发现是 frp 代理的问题...
> 
> @fatedier 请问下如何能够让 frp 支持 [SSE](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Sending_events_from_the_server) 呢

不好意思才看到，不知还有没有用。
修改了这个文件: utils/vhost/reverseproxy.go
附件是修改后的文件。
注：使用中发现会有很多连接一直建立着，而不断开，目前不知道是不是SSE连接导致的。
[reverseproxy.zip](https://github.com/fatedier/frp/files/2771162/reverseproxy.zip)

**Comment by oldthreefeng** [comment]
废了大半天的劲才发现是 frp 代理的问题..  唉哟，nginx配置都配到天上去了。

**Comment by ufofuduo** [comment]
> 

您好！最新的版本支持SSE了吗？

**Comment by pccai** [comment]
同问，Server-Sent Events支持吗？ gpt4带来的打字效果没有了。。

**Comment by pccai** [comment]
我用的是0.48，不支持。

**Comment by chinason** [comment]
> 我用的是0.48，不支持。

我安装测试了一下0.48版本的，支持SSE。

服务器端运行在windows上，客户端运行在arm llinux上。

**Comment by ninghongbo123** [comment]
我后端是websocket接口。请问frps和frpc要如何配置，才能支持接口转发。
看了许多帖子，都解决不了。
还望大佬指点一下。

**Comment by reply2future** [comment]
> 我用的是0.48，不支持。

我使用`tcp`是可以的，使用`http`是不行的。

**Comment by chengkunchen** [comment]
> 你确定？ 我用的tcp咋不可以

**Comment by chengkunchen** [comment]
> 

websocket 不用做特殊处理，就tcp方式就可以，nginx要做一些配置

**Comment by sizzlecar** [comment]
If it is forwarded to frp through nginx and includes SSE request, then nginx needs to add the following configuration as follows

`      
proxy_set_header Connection '';
proxy_http_version 1.1;
chunked_transfer_encoding off;
proxy_buffering off;
proxy_cache off;
proxy_set_header Host $host;

`

**Comment by zclcz** [comment]
docker部署的0.35版本和0.51版本都不行啊  配置http和tcp直接用都不行 还有哪里需要配置吗 直接用NGINX反向代理是可以的但是使用frp做内网穿透就不行
