### ISSUE TITLE
Bug: Couldnt continue if a Client accidentally exits

### ISSUE THREAD

**Issue by billchenchina** [fatedier/frp#847]
**What version of frp are you using (./frpc -v or ./frps -v)?**

0.19.1

**What operating system and processor architecture are you using (`go env`)?**

frps: Ubuntu 16.04 LTS

frpc: Ubuntu 16.04 LTS

**Configures you used:**

A Simple HTTP Tunnel

**Steps to reproduce the issue:**
1. Setup frp server and Client connect using frpc
2. Stop network of frpc
3. Quit frpc
4. Start frpc

**Describe the results you received:**

```
Login to server success

port already used
```

**Describe the results you expected:**

```
Login to server success

start proxy success
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I restarted frps manually and it works.

**Can you point out what caused this issue (optional)**

Server *perhaps* didn't stop the tunnel?

**Comment by billchenchina** [comment]
看起来像是 #645 的复现，但是看起来还没解决

**Comment by fatedier** [comment]
No useful info. I will close it util you provide more log or other clues releated.
