### ISSUE TITLE
StatusCode [503]报错

### ISSUE THREAD

**Issue by newcastlecy** [fatedier/frp#850]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.20
**What operating system and processor architecture are you using (`go env`)?**

win7 x64
**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
2018/07/10 10:13:11 [I] [proxy_manager.go:300] proxy removed: []
2018/07/10 10:13:11 [I] [proxy_manager.go:310] proxy added: [111 222 333 4545]
2018/07/10 10:13:11 [I] [proxy_manager.go:333] visitor removed: []
2018/07/10 10:13:11 [I] [proxy_manager.go:342] visitor added: []
2018/07/10 10:13:50 [W] [control.go:113] login to server failed: DialTcpByHttpProxy error, StatusCode [503]

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
日志很明显了，检查自己配置或环境变量中填写的的 http proxy 地址，确认 proxy 服务是否正常。
配置也不贴，重现步骤也没有，以后请按规则填写 issue 模版。
