### ISSUE TITLE
0.20.0 版本上传速度变慢的问题

### ISSUE THREAD

**Issue by shminer** [fatedier/frp#851]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.20.0

**What operating system and processor architecture are you using (`go env`)?**
Ubuntu 16.04 LTS & win10 & win 7

**Configures you used:**

**Steps to reproduce the issue:**
none

**Describe the results you received:**
使用0.16.0时上传速度可以跑满网速，使用0.20.0时速率最高只有10Mbp/s

**Describe the results you expected:**
不知道是否有其他配置影响到速率问题，除了必要的参数更改，其他配置均与0.16.0相同

**Additional information you deem important (e.g. issue happens only occasionally):**
还未测试其他版本

**Can you point out what caused this issue (optional)**

**Comment by shminer** [comment]
**测试使用的是iperf**

**frpX测试配置：**
bind udp prot
压缩：关闭
加密：关闭

**===========测试1==========**
==》内网机器对服务器直接连接的上传速度为100Mbps（内网机器最大带宽）
==》内网机器对服务器直接连接的下载速度为100Mbps（内网机器最大带宽）
**=========================**

**===========测试2==========**
==》使用0.16.0对服务器上传速度为60Mbps
==》使用0.16.0对服务器下载速度为50Mbps
==》使用0.20.0对服务器上传速度为10Mbps
==》使用0.20.0对服务器下载速度为0.8Mbps
**=========================**

以上测试在使用相同配置，对两个frp版本分别测试的结果。

**Comment by thorisme** [comment]
我也是，windows2016到CentOS 7的upload速度也是10Mbps，希望作者能帮忙下下个版本解决这个问题，非常感谢

**Comment by shminer** [comment]
#662
