### ISSUE TITLE
0.16版本后续版本上传速度只有10Mbps左右

### ISSUE THREAD

**Issue by thorisme** [fatedier/frp#863]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc and frps 0.20

**What operating system and processor architecture are you using (`go env`)?**
The client runs at Windows server2016,The server runs at CentOS 7 X64

**Configures you used:**
null

**Steps to reproduce the issue:**
1.null
2.null
3.null

**Describe the results you received:**
使用0.16.1时上传速度可以达到我的最大上传速度，使用0.16.1后续版本时速度只有10Mbp/s左右。
此状态是在客户端使用tcp协议时发生，其他方式暂未测试。
其中在https下速度有所提升。

**Describe the results you expected:**
我看了以往的问题反馈，估计是使用TCP协议才有此类问题，希望作者能够在后续版本解决这个问题，谢谢。

**Additional information you deem important (e.g. issue happens only occasionally):**
这个问题在使用TCP协议时是持续的，改变其他配置并未改观。

**Can you point out what caused this issue (optional)**
null

**Comment by fatedier** [comment]
Duplicate of #851 & #662
