### ISSUE TITLE
进入dashboard没有数据

### ISSUE THREAD

**Issue by ctyyy** [fatedier/frp#867]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.20

**What operating system and processor architecture are you using (`go env`)?**
CentOS7 amd 64

**Configures you used:**
frps.ini
[common]  
bind_port = 7000  
token = dev  
allow_ports = 50000-60000
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin

frpc.ini
[common]
server_addr = -.-.-.-
server_port = 7000
token = dev
[web_demo]
type = tcp
local_ip = 127.0.0.1
local_port = 8080
remote_port = 50001

**Steps to reproduce the issue:**
1. 启动frps(centos)：./frps reload -c ./frps.ini
2. 启动frpc(windows)：frpc   （访问外网ip:50001 能够正常映射到本地的web项目）
3. 进入外网ip:7500 (dashboard)

**Describe the results you received:**
进入到dashboard页面，没有任何动态数据
![20180802141623](https://user-images.githubusercontent.com/14940814/43566224-5258e71e-9660-11e8-865e-2899e6aad405.jpg)

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
请先自行排查问题，不要遇到任何问题都提 issue，处理这一类 issue 效率非常低，几乎没有有价值的信息。如果你不确定这是一个 bug，就请慎重，尊重每一个人的时间。
