### ISSUE TITLE
负载均衡模式下，支持健康检查

### ISSUE THREAD

**Issue by f111fei** [fatedier/frp#869]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
2.0.0

**What operating system and processor architecture are you using (`go env`)?**
centos

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
负载均衡模式下，其中一个客户端挂掉了似乎frp依然会访问该客户端，结果是该次请求失败。
比如有10个客户端挂掉了1台之后，可能10分之1的请求是失败的。

**Describe the results you expected:**
希望客户端挂掉了，会自动选择正常的客户端，最终返回成功的数据

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
理论上，frpc 挂了是会将这个 proxy 从 group 中去掉的，如果是要代理的服务挂了，那么目前是会遇到这个问题，所以之后会加入健康检查的功能。

**Comment by f111fei** [comment]
目前 frpc中的一个客户端挂掉之后随机到这个客户端的时候是会有提示的
![image](https://user-images.githubusercontent.com/7069719/43573368-2917908a-9674-11e8-9837-db34c20b9065.png)
我可以根据这个提示知道哪个服务挂掉了。 希望之后也能保留这个提示信息。
Thanks

**Comment by fatedier** [comment]
v0.22.0 已支持健康检查。
