### ISSUE TITLE
请教一下，没有域名，能实现网站通过公网IP+端口号访问吗?

### ISSUE THREAD

**Issue by wzhsunn** [fatedier/frp#872]

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/README_zh.md

**Comment by wzhsunn** [comment]
我看readme里说得有域名，可以没有域名 实现外网访问内网的web http 服务吗

**Comment by ian4hu** [comment]
如果有外网ip，但是没有域名，可以使用xip.io来实现伪域名

在 2018-08-03 12:06:01，sunny <notifications@github.com> 写道：


我看readme里说得有域名，可以没有域名 实现外网访问内网的web http 服务吗

**Comment by wzhsunn** [comment]
PS E:\test\FRP\frp_0.20.0_windows_386> .\frpc.exe -c .\frpc.ini
2018/08/03 14:40:36 [I] [proxy_manager.go:300] proxy removed: []
2018/08/03 14:40:36 [I] [proxy_manager.go:310] proxy added: [web01]
2018/08/03 14:40:36 [I] [proxy_manager.go:333] visitor removed: []
2018/08/03 14:40:36 [I] [proxy_manager.go:342] visitor added: []
2018/08/03 14:40:46 [W] [control.go:113] login to server failed: i/o deadline reached
i/o deadline reached

我试了一下， 不行……
