### ISSUE TITLE
映射Tomcat后访问报错

### ISSUE THREAD

**Issue by jingcheng407** [fatedier/frp#876]
版本
0.20.0

![image](https://user-images.githubusercontent.com/7554452/43707404-93a96346-999a-11e8-9398-71fd4dd157ae.png)

打码的是域名，访问的时候Tomcat报错如上，在issues里没有找到类似情况，Google也没有人遇到类似，很奇怪。
我试过映射iis，nginx都可以，Tomcat也试着换版本和改端口，都是同样的问题，是不是需要修改Tomcat的哪个配置，还望指点。

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
