### ISSUE TITLE
怎么使用域名80端口访问？

### ISSUE THREAD

**Issue by callmesoul** [fatedier/frp#883]
我使用frp内网穿透。成功了没问题。
问题是我要使用外网的80端口访问。
直接把frp服务器配置的vhost_http_port设为80，
但是我又其他的域名都要用到80，使用了nginx反向代理的方式。

想把frp也通过nginx反向代理，但不知道代理到那个端口？
好像只能能xxx.cn:8080可以访问到客服端。xx.xx.xx.x:8080 ip地址访问不了。那nginx该代理到哪呢？

**Comment by xiasf** [comment]
其实你的问题就是你想隐藏8080，实现80端口访问穿透的内网。

解决方案：

1. frp还是绑定8080
2. nginx反向代理 xxx.cn:80 > 127.0.0.1:8080（将某个域名的80代理到8080上不会影响其他域名）

这样就能实现  xxx.cn:80（和 xxx.cn:8080） 穿透到内网，并且对其他域名没有影响。

还有其他问题可参见: https://www.kancloud.cn/xiak/web-dev-best-practice/708208

**Comment by wangxianfeng** [comment]
关于反向代理的配置，可以参考我的这篇博文，原来从nat.ee转过来的，但是nat.ee不能访问了，自己试了一下是可以的，目前正在用
http://www.wangxianfeng.cn/wordpress/2018/06/10/nginx%e5%8f%8d%e5%90%91%e4%bb%a3%e7%90%86frp%e7%bc%93%e5%ad%98%e5%8a%a0%e9%80%9f/

**Comment by callmesoul** [comment]
@xiasf @wangxianfeng 谢谢，可以了，虽然ip地址访问不了但是直接代理过去后域名是可以访问的。
