### ISSUE TITLE
XTCP 出现错误

### ISSUE THREAD

**Issue by kasuganosoras** [fatedier/frp#884]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frps 0.17.0
frpc 0.17.0
frpc-visitor 0.17.0

**What operating system and processor architecture are you using (`go env`)?**
frps CentOs 7.5
frpc Windows 10
frpc-visitor Windows 7

**Configures you used:**
【Frpc】
[common]
server_addr = ***********
server_port = 2333
tcp_mux = true
auth_token = ***********
sttl = 180
privilege_token = ***********

[<4433>dsy2007：10334]
privilege_mode = true
type = xtcp
sk = 123456789
local_ip = 127.0.0.1
local_port = 8233

【Frpc_vistor】
[common]
server_addr = ***********
server_port = 2333
tcp_mux = true
auth_token = ***********
sttl = 180
privilege_token = ***********
# Proxys
[Client@<4433>dsy2007：10334]
privilege_mode = true
type = xtcp
role = visitor
server_name = <4433>dsy2007：10334
sk = 123456789
bind_addr = 127.0.0.1
bind_port = 8233

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
Visitor 提示启动来宾成功，但是连接 localhost:8233 时 Visitor 客户端出现：
Only one usage of each socket address (protocol/network address/port) is normally permitted
然后连接失败。

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/README_zh.md#%E7%82%B9%E5%AF%B9%E7%82%B9%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F

注意文档说明，出错或连不上的情况下请使用 stcp 。
