### ISSUE TITLE
作者是否考虑过服务器端主动调整客户端的配置呢[FEATURE ]

### ISSUE THREAD

**Issue by xihefeng** [fatedier/frp#887]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
--------------------
首先感谢作者的无偿付出，frp真的非常好用。
在使用的过程中，发现由于涉及的客户端较多，同时很多客户端需要不断新增新的配置
所以，作者是否想过，客户端开启连接服务器后，由服务端主动的修改客户端配置？
这样方便整个frp的管理和可控
再次感谢作者~

**Comment by fatedier** [comment]
之前的 issue 中有说过这个问题，在开源版本里是不会去做让外部去控制内网开通任意的端口访问这样的操作，避免安全问题。
如果有这种需求，可以自行开发或者简单地使用一些远程配置文件管理的工具。
