### ISSUE TITLE
nginx https反向代理到frp https 报 502错误，说说我的解决方法

### ISSUE THREAD

**Issue by wangxianfeng** [fatedier/frp#888]
首先声明，这不是个问题贴，而是给出了解决方法。看到很多人使用nginx https转发frp https的时候都像我一样，遇到了nginx报502错误的问题，在网上找了一圈，也没有找到解决方式。经过一段时间的摸索，解决了自己的问题，把解决方法分享出来，以求像我一样遇到该问题的人能够快速地解决自己的问题。

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.20.0

**What operating system and processor architecture are you using (`go env`)?**
[root@host frp]# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build188604123=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

**Configures you used:**
frps.ini关键配置

```
[common]

# A literal address or host name for IPv6 must be enclosed
# in square brackets, as in "[::1]:80", "[ipv6-host]:http" or "[ipv6-host%zone]:80"
bind_addr = 0.0.0.0
 bind_port = 7000
……
# if you want to support virtual host, you must set the http port for listening (optional)
 # Note: http port and https port can be same with bind_port
vhost_http_port = 8680
vhost_https_port = 8643
```

frpc.ini关键配置：
```
[es]
type=https
custom_domains=es.aiuyo.com
local_ip=192.168.2.99
local_port=9200
use_encryption=true
use_compression=true

[kb]
type=https
custom_domains=kb.aiuyo.com
local_ip=192.168.2.99
local_port=5601
use_encryption=true
use_compression=true
```

**Steps to reproduce the issue:**
1. 请求发送给nginx
2. 由nginx转发请求给frp
3. frp处理请求，转发到对应的内网服务商

nginx https关键配置：
```
server{ 

        listen 443 ssl; 
        ssl on;
        server_name *.aiuyo.com;
        ssl_certificate /root/.acme.sh/aiuyo.com/fullchain.cer;
        ssl_certificate_key  /root/.acme.sh/aiuyo.com/aiuyo.com.key;
        ssl_trusted_certificate /root/.acme.sh/aiuyo.com/ca.cer;

        location / {
                proxy_ssl_server_name on;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $host:$server_port;
                proxy_pass https://$host:8643; #通过域名访问frp服务
        }

        location ~* \.(jpg|jpeg|gif|png|svg|css|scss|js|ico|xml|woff|woff2|ttf|otf|eot)$ {
                proxy_ssl_server_name on;
                proxy_pass https://$host:8643;
                proxy_redirect https://$host/ https://$http_host/;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-proto https;
                proxy_cache frp_cache;
                proxy_cache_key $uri$is_args$args;
                proxy_cache_valid 200 206 301 302 304 3d;
                expires 30d;
        }
}
```

**Describe the results you received:**

# 对于nginx https代理frp https的理解
我的理解是这样的：
如果使用了自定义域名，frp是根据$host值判断该往哪个内网服务转发请求的，因此转给frp的请求中一定要包含$host，否则frp无法正常处理请求。
因此以下2个配置很重要：
```
proxy_ssl_server_name on;
proxy_pass https://$host:8643; #通过域名访问frp服务
```
proxy_pass中不能写成IP的形式。

nginx反向代理frp缓存加速http+https 可以参考我的博文，已经根据最新的理解做了更新。
http://www.wangxianfeng.cn/wordpress/2018/06/10/nginx%e5%8f%8d%e5%90%91%e4%bb%a3%e7%90%86frp%e7%bc%93%e5%ad%98%e5%8a%a0%e9%80%9fhttphttps/

有什么不对的地方，还请各位指正。

**Comment by yflwz** [comment]
我按上面的配置了，
location / {
            proxy_ssl_server_name on;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host:$server_port;
            proxy_pass https://$host:10053;
        }
只是用https://自定义域名访问不了，用https://自定义域名:端口可以

**Comment by wangxianfeng** [comment]
可以看看nginx及frp的日志排查一下

**Comment by 662** [comment]
注意： `$host`是你客户端访问的主机头，也即是`*.aiuyo.com`

你只是把 `https://*.aiuyo.com` 代理到了 `https://*.aiuyo.com:8643` 相当于你任然是访问的  `https://*.aiuyo.com:8643`，而一旦防火墙不开放 `8643` 你这个配置就挂了，因为你的反向代理是到公网去找DNS解析IP；

你这个配置并没有达到 网内直达  `https://127.0.0.1:8643` ；

如果`frps`真的是直接拿的 `request url` 而不是拿的 `http header`的话，你这个方法倒是可行，只不过需要修改本地 `hosts` 让 本地解析`*.aiuyo.com`；

**Comment by 662** [comment]
我用 `0.20`(lede只有这个版本) 测试了一下，https反代确实是拿的url，`http header`里头的主机头直接被无视了，这或许是个bug。 @fatedier

**Comment by cnyasin** [comment]
> 首先声明，这不是个问题贴，而是给出了解决方法。看到很多人使用nginx https转发frp https的时候都像我一样，遇到了nginx报502错误的问题，在网上找了一圈，也没有找到解决方式。经过一段时间的摸索，解决了自己的问题，把解决方法分享出来，以求像我一样遇到该问题的人能够快速地解决自己的问题。
> 
> **What version of frp are you using (./frpc -v or ./frps -v)?**
> 0.20.0
> 
> **What operating system and processor architecture are you using (`go env`)?**
> [root@host frp]# go env
> GOARCH="amd64"
> GOBIN=""
> GOEXE=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/root/go"
> GORACE=""
> GOROOT="/usr/lib/golang"
> GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> CC="gcc"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build188604123=/tmp/go-build -gno-record-gcc-switches"
> CXX="g++"
> CGO_ENABLED="1"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> 
> **Configures you used:**
> frps.ini关键配置
> 
> ```
> [common]
> 
> # A literal address or host name for IPv6 must be enclosed
> # in square brackets, as in "[::1]:80", "[ipv6-host]:http" or "[ipv6-host%zone]:80"
> bind_addr = 0.0.0.0
>  bind_port = 7000
> ……
> # if you want to support virtual host, you must set the http port for listening (optional)
>  # Note: http port and https port can be same with bind_port
> vhost_http_port = 8680
> vhost_https_port = 8643
> ```
> 
> frpc.ini关键配置：
> 
> ```
> [es]
> type=https
> custom_domains=es.aiuyo.com
> local_ip=192.168.2.99
> local_port=9200
> use_encryption=true
> use_compression=true
> 
> [kb]
> type=https
> custom_domains=kb.aiuyo.com
> local_ip=192.168.2.99
> local_port=5601
> use_encryption=true
> use_compression=true
> ```
> 
> **Steps to reproduce the issue:**
> 
> 1. 请求发送给nginx
> 2. 由nginx转发请求给frp
> 3. frp处理请求，转发到对应的内网服务商
> 
> nginx https关键配置：
> 
> ```
> server{ 
> 
>         listen 443 ssl; 
>         ssl on;
>         server_name *.aiuyo.com;
>         ssl_certificate /root/.acme.sh/aiuyo.com/fullchain.cer;
>         ssl_certificate_key  /root/.acme.sh/aiuyo.com/aiuyo.com.key;
>         ssl_trusted_certificate /root/.acme.sh/aiuyo.com/ca.cer;
> 
>         location / {
>                 proxy_ssl_server_name on;
>                 proxy_set_header X-Real-IP $remote_addr;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>                 proxy_set_header X-Forwarded-Proto $scheme;
>                 proxy_set_header Host $host:$server_port;
>                 proxy_pass https://$host:8643; #通过域名访问frp服务
>         }
> 
>         location ~* \.(jpg|jpeg|gif|png|svg|css|scss|js|ico|xml|woff|woff2|ttf|otf|eot)$ {
>                 proxy_ssl_server_name on;
>                 proxy_pass https://$host:8643;
>                 proxy_redirect https://$host/ https://$http_host/;
>                 proxy_set_header X-Real-IP $remote_addr;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>                 proxy_set_header Host $host;
>                 proxy_set_header X-Forwarded-proto https;
>                 proxy_cache frp_cache;
>                 proxy_cache_key $uri$is_args$args;
>                 proxy_cache_valid 200 206 301 302 304 3d;
>                 expires 30d;
>         }
> }
> ```
> 
> **Describe the results you received:**
> 
> # 对于nginx https代理frp https的理解
> 我的理解是这样的：
> 如果使用了自定义域名，frp是根据$host值判断该往哪个内网服务转发请求的，因此转给frp的请求中一定要包含$host，否则frp无法正常处理请求。
> 因此以下2个配置很重要：
> 
> ```
> proxy_ssl_server_name on;
> proxy_pass https://$host:8643; #通过域名访问frp服务
> ```
> 
> proxy_pass中不能写成IP的形式。
> 
> nginx反向代理frp缓存加速http+https 可以参考我的博文，已经根据最新的理解做了更新。
> http://www.wangxianfeng.cn/wordpress/2018/06/10/nginx%e5%8f%8d%e5%90%91%e4%bb%a3%e7%90%86frp%e7%bc%93%e5%ad%98%e5%8a%a0%e9%80%9fhttphttps/
> 
> 有什么不对的地方，还请各位指正。

成功！感谢楼主！特来回复！

**Comment by Eminlin** [comment]
搜了整个互联网 ， 只有你这个解决了问题 ，感谢分享:)

**Comment by wangxianfeng** [comment]
> 
> 
> 搜了整个互联网 ， 只有你这个解决了问题 ，感谢分享:)

很欣慰我的分享帮助了一些人

**Comment by powerttt** [comment]
用了楼主的方法也不行，加上了 resolver 8.8.8.8; 就通了
` location / {
                resolver 8.8.8.8;
                proxy_ssl_server_name on;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $host:$server_port;
                proxy_pass https://$host:7443; #通过域名访问frp服务
        }`

**Comment by lysssssss** [comment]
感谢方法，同时也遇到了另一个坑，如果要代理爱快https的话，记得加上proxy_http_version 1.1; 否则静态资源会404

**Comment by edalex-yinzi** [comment]
> > 注意： `$host`是你客户端访问的主机头，也即是`*.aiuyo.com`
> > 你只是把 `https://*.aiuyo.com` 代理到了 `https://*.aiuyo.com:8643` 相当于你任然是访问的 `https://*.aiuyo.com:8643`，而一旦防火墙不开放 `8643` 你这个配置就挂了，因为你的反向代理是到公网去找DNS解析IP；
> > 你这个配置并没有达到 网内直达 `https://127.0.0.1:8643` ；
> > 如果`frps`真的是直接拿的 `request url` 而不是拿的 `http header`的话，你这个方法倒是可行，只不过需要修改本地 `hosts` 让 本地解析`*.aiuyo.com`；
> 
> 说的太对了，【而一旦防火墙不开放 `8643` 你这个配置就挂了，因为你的反向代理是到公网去找DNS解析IP】 这个确实无法解析host 导致无法查询，需要在防火墙开启端口才可以

如果是这样的话，用nginx就没意思了。有其他的解决方案吗？

**Comment by baiyz0825** [comment]
> 用了楼主的方法也不行，加上了 resolver 8.8.8.8; 就通了
> 
> ```nginx
>  location / {
>                 resolver 8.8.8.8;
>                 proxy_ssl_server_name on;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>                 proxy_set_header X-Forwarded-Proto $scheme;
>                 proxy_set_header Host $host:$server_port;
>                 proxy_pass https://$host:7443; #通过域名访问frp服务
>         }
> ```
查看日志确实是解析不到域名的问题，加上解析就可以
![image](https://user-images.githubusercontent.com/81071870/210929588-964b575b-b0e8-43b1-9c6f-1402e24d0050.png)

但是配置了缓存的话，不知道为什么静态文件访问不到了
```conf
server部分
        location ~* \.(jpg|jpeg|gif|png|svg|css|scss|js|ico|xml|woff|woff2|ttf|otf|eot)$ {
                proxy_ssl_server_name on;
                proxy_pass https://$host:8643;
                proxy_redirect https://$host/ https://$http_host/;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-proto https;
                proxy_cache frp_cache;
                proxy_cache_key $uri$is_args$args;
                proxy_cache_valid 200 206 301 302 304 3d;
                expires 30d;
        }
http部分
       proxy_cache_path /usr/local/nginx/cache keys_zone=STATIC:100m inactive=24h  max_size=1g;

```

**Comment by baiyz0825** [comment]
> > 用了楼主的方法也不行，加上了 resolver 8.8.8.8; 就通了
> > ```nginx
> >  location / {
> >                 resolver 8.8.8.8;
> >                 proxy_ssl_server_name on;
> >                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >                 proxy_set_header X-Forwarded-Proto $scheme;
> >                 proxy_set_header Host $host:$server_port;
> >                 proxy_pass https://$host:7443; #通过域名访问frp服务
> >         }
> > ```
> 
> 查看日志确实是解析不到域名的问题，加上解析就可以 ![image](https://user-images.githubusercontent.com/81071870/210929588-964b575b-b0e8-43b1-9c6f-1402e24d0050.png)
> 
> 但是配置了缓存的话，不知道为什么静态文件访问不到了
> 
> ```
> server部分
>         location ~* \.(jpg|jpeg|gif|png|svg|css|scss|js|ico|xml|woff|woff2|ttf|otf|eot)$ {
>                 proxy_ssl_server_name on;
>                 proxy_pass https://$host:8643;
>                 proxy_redirect https://$host/ https://$http_host/;
>                 proxy_set_header X-Real-IP $remote_addr;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>                 proxy_set_header Host $host;
>                 proxy_set_header X-Forwarded-proto https;
>                 proxy_cache frp_cache;
>                 proxy_cache_key $uri$is_args$args;
>                 proxy_cache_valid 200 206 301 302 304 3d;
>                 expires 30d;
>         }
> http部分
>        proxy_cache_path /usr/local/nginx/cache keys_zone=STATIC:100m inactive=24h  max_size=1g;
> ```

检查之后还是需要添加一个resolver来进行解析，就跟https://github.com/fatedier/frp/issues/888#issuecomment-945082729这条描述一样，楼主在博客中添加了相应的解析，issues上面没有粘贴全，然后我出现的缓存无法命中或者无法生成原因是因为
> [nginx doc](https://www.nginx.com/blog/nginx-caching-guide/)
```txt
仅当源服务器包含具有未来日期和时间的标头或将max-age指令设置为非零值的Cache-Control标头时，NGINX才会缓存响应。Expires
默认情况下，NGINX 遵循 Cache-Control 标头中的其他指令：当标头包含 、No-Cache 或 No-Store 指令时，它不会缓存响应。它也不会使用 Set-Cookie 标头缓存响应。此外，它仅缓存对响应和请求的响应。您可以覆盖这些默认值，如以下答案中所述。
```
所以如果需要强制开启缓存需要增加
```conf
proxy_ignore_headers X-Accel-Expires Expires Cache-Control Set-Cookie;
### 强制缓存后端文件，忽略后端服务器的相关头信息，确保Cookie有效负载不包括在缓存的有效负载中。这对于避免通过NGINX缓存泄漏cookie非常重要。
proxy_hide_header Cache-Control;
proxy_hide_header Set-Cookie;
```
之后可以设置请求头`       add_header Nginx-Cache “$upstream_cache_status”;`检查是否命中缓存
完整配置如下：
```conf
server部分


    location ~*\.(jpg|jpeg|gif|png|svg|css|scss|js|ico|xml|flv|html|htm)(.*) {
        #resolver 8.8.8.8;
        proxy_ssl_server_name on;
        proxy_pass https://$host:4433;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-proto https;
        proxy_cache STATIC_SITE;
        proxy_cache_key $uri$is_args$args;
        proxy_ignore_headers X-Accel-Expires Expires Cache-Control Set-Cookie;
        proxy_redirect http://$host/ http://$http_host/;
        proxy_cache_valid 200 302 1h; #[不同http状态缓存时间不同]
        proxy_cache_valid 301 1d;
        proxy_cache_valid any 1m;
        ### 强制缓存后端文件，忽略后端服务器的相关头信息
        proxy_hide_header Cache-Control;
        proxy_hide_header Set-Cookie;
        ###
        expires 10h;  #[告诉浏览器缓存有效期-- 10h可以直接访问浏览器缓存i]
        add_header Nginx-Cache “$upstream_cache_status”;
        }


http部分：

proxy_cache_path /usr/local/nginx/cache levels=1:2  keys_zone=STATIC_SITE:100m inactive=24h  max_size=1g;
resolver 8.8.8.8 8.8.4.4 valid=300s;
resolver_timeout 5s;
```
其余优化：
```conf
tcp_nodelay on;
```

**Comment by GodFox** [comment]
我也通过这个方法搞定了，感谢！

**Comment by kbitlive** [comment]
感谢 此方法有效

**Comment by JackShi1991** [comment]
> 感谢方法，同时也遇到了另一个坑，如果要代理爱https的话，记得加上proxy_http_version 1.1;否则静态资源会404

感谢，确实有效。

**Comment by JackShi1991** [comment]
我没有域名，相同配置下其他都正常，只有爱快和青龙面板502，加上了proxy_http_version 1.1 后爱快倒是能打开，但是页面卡点了半天没反应，配置文件如下
server {
    listen 14431 ssl;
    server_name localhost;

    # SSL 配置，使用你上传的证书和私钥路径
    ssl_certificate /etc/nginx/ssl/zerossl_ip.crt;
    ssl_certificate_key /etc/nginx/ssl/zerossl_ip.key;

    # SSL 参数设置
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';

    location / {
        # 设置代理头部信息
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # 反向代理到内网 FRP 服务器
        proxy_pass http://localhost:1431;
        proxy_ssl_verify off;  # 关闭 SSL 验证，如果需要的话
    }
}
