### ISSUE TITLE
华硕路由器AC66U无法安装

### ISSUE THREAD

**Issue by bangzg** [fatedier/frp#889]
下载了0.16~0.20的所有linux的版本到路由器以root权限执行都报错。但是我在虚拟机内安装的linux系统以及群晖linux系统上安装都是正常的.

**Comment by thorisme** [comment]
这个我碰到过，不过的我的路由器是网件4300刷lede，下载后在电脑解压后传路由器，赋予root权限是不能运行了，解决方法是，直接将包下载到路由器，或将整个压缩包传路由器，然后在路由器解压出来，再赋予root权限就能运行了，你试试。

**Comment by bangzg** [comment]
也是不行，先用群晖的frpc凑合着用了。
