### ISSUE TITLE
ipv6和ipv4同时监听设置

### ISSUE THREAD

**Issue by swordstudiox** [fatedier/frp#894]
1、frps端同时监听ipv4和ipv6如何设置？
查了以前的issues 好像是bind_addr = [::]这样的设置，但是[::]应该是监听ipv6地址，测试同时监听有时不成功

2、frpc端如何同时支持ipv6和ipv4连接，ipv4和ipv6都在同一个服务器上

**Comment by fatedier** [comment]
Duplicate issue.
