### ISSUE TITLE
frps 服务端 增加多帐户机制

### ISSUE THREAD

**Issue by kinneyli** [fatedier/frp#897]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
目前frps服务端 只能设置一个 auth  token， 所有frpc客户端都使用相同的 auth token， 这样的情况下，如果我的 auth token被泄露，那么意味着 任何人都能使用我的 frps服务端，这种情况是不希望发生的。

**Describe the results you expected:**
建议frps服务端 增加账户机制，可由管理员通过API创建分配帐号，用户可自行修改密码，来实现每个frpc客户端使用不同的帐户进行验证。 （帐户机制可以是FRP内建的帐户机制，也可以是集成 操作系统帐户、 AD域、LDAP域等）

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
Duplicate issue.
