### ISSUE TITLE
token 一致报authorization failed

### ISSUE THREAD

**Issue by kiseopt** [fatedier/frp#900]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.21.0

**What operating system and processor architecture are you using (`go env`)?**
frps ：frp_0.21.0_linux_amd64
frpc : frp_0.21.0_windows_amd64

**Configures you used:**
frps : 
[common]
bind_port = 7000
token = 12345678
vhost_http_port = 8080
frpc:
[common]
server_addr = ***.***.***.***
server_port = 7000
token = 12345678
[web]
type = http
local_port = 80
custom_domains = home.***.**
**Steps to reproduce the issue:**
1.运行frps后
2.本地运行frpc就报authorization failed
3.

**Describe the results you received:**
2018/08/26 12:43:49 [I] [proxy_manager.go:300] proxy removed: []
2018/08/26 12:43:49 [I] [proxy_manager.go:310] proxy added: [web]
2018/08/26 12:43:49 [I] [proxy_manager.go:333] visitor removed: []
2018/08/26 12:43:49 [I] [proxy_manager.go:342] visitor added: []
2018/08/26 12:43:49 [E] [control.go:236] authorization failed
2018/08/26 12:43:49 [W] [control.go:113] login to server failed: authorization failed
authorization failed

**Describe the results you expected:**
正常运行

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by Warm-rain** [comment]
same

**Comment by koichoco** [comment]
今天遇到了相同的问题（token和dashboard），原因大概是./frps默认不会加载配置文件，必须用./frps -c ./frps.ini

**Comment by koichoco** [comment]
> 补一下，内网环境无任何问题
> 不设置token可正常连接
> 但是Dashboard无法使用(无论是否设置token)

今天遇到了相同的问题（token和dashboard），原因大概是./frps默认不会加载配置文件（所以server端既没有token也没有dashboard），必须用./frps -c ./frps.ini
（但是客户端直接用./frpc会加载配置文件。。。）

**Comment by lotus8888** [comment]
感谢，补充下windows下启动命令： 先CMD 进入 ， 然后 frps -c ./frps.ini
