### ISSUE TITLE
新版frp取消了privilege_token吗？

### ISSUE THREAD

**Issue by citisy** [fatedier/frp#906]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.21.0

**What operating system and processor architecture are you using (`go env`)?**
linux

**Configures you used:**
frps:
[common]
bind_port = 7000
dashboard_port = 7500
privilege_token = xxx
privilege_mode = true

frpc:
[common]
server_addr = xxx
server_port = 7000

[ssh]
type = tcp 
local_ip = 127.0.0.1
local_port = 8080
remote_port = 6000

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
新版的frp是取消了privilege_token这个字段吗，frps设置了token，frpc里面没有设置，也依然可以连接成功。

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by cloverzrg** [comment]
把 privilege_token 改为 token
