### ISSUE TITLE
ssh_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by 97612336** [fatedier/frp#907]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.21.0

**What operating system and processor architecture are you using (`go env`)?**
deepin_linux

**Configures you used:**
#frps.ini
[common]
bind_addr = 0.0.0.0
bind_port = 7000

#frpc.ini
[common]
server_addr = [此处为我的腾讯云公网IP]
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
ssh_exchange_identification: Connection closed by remote host

**Describe the results you expected:**
ssh_exchange_identification: Connection closed by remote host

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by cloverzrg** [comment]
ssh login failed?

**Comment by truegate** [comment]
检查一下是不是在frpc端开启了ssh

**Comment by nemochin** [comment]
我在frpc布在win10上，frps布在阿里云上，也遇到同样的问题

**Comment by zle1992** [comment]
I Meet the same error   . How to solve this?

**Comment by zle1992** [comment]
> Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
> (为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
> 
> Use the commands below to provide key information from your environment:
> You do NOT have to include this information if this is a FEATURE REQUEST
> 
> **What version of frp are you using (./frpc -v or ./frps -v)?**
> 0.21.0
> 
> **What operating system and processor architecture are you using (`go env`)?**
> deepin_linux
> 
> **Configures you used:**
> #frps.ini
> [common]
> bind_addr = 0.0.0.0
> bind_port = 7000
> 
> #frpc.ini
> [common]
> server_addr = [此处为我的腾讯云公网IP]
> server_port = 7000
> 
> [ssh]
> type = tcp
> local_ip = 127.0.0.1
> local_port = 22
> remote_port = 6000
> 
> **Steps to reproduce the issue:**
> 1.
> 2.
> 3.
> 
> **Describe the results you received:**
> ssh_exchange_identification: Connection closed by remote host
> 
> **Describe the results you expected:**
> ssh_exchange_identification: Connection closed by remote host
> 
> **Additional information you deem important (e.g. issue happens only occasionally):**
> 
> **Can you point out what caused this issue (optional)**
I Meet the same error . How to solve this?

**Comment by yoojia** [comment]
我遇到同样的问题，不过已经解决。当时找到这个issue，反馈一下解决过程吧：

场景： frpc 运行在 docker中`frpc-ssh`容器，ini指定 `local_ip = 127.0.0.1, local_port=22`。

问题：docker所运行容器中并没有sshd进程。所以 **ssh_exchange_identification: Connection closed by remote host**是指ssh连接到frps跳转服务器，并反向连接到`frpc-ssh`容器，如问题所述，容器中并没有ssh服务端，所以SSH无法连接。

解决：

1. 如果是docker运行的，注意容器的网络模式。我的是指向宿主机，使用 `--network=host` 容器启动参数；

2. 如果是非docker运行，检查ssh服务端进程是否正常运行：`ps aux | grep "sshd"`；

EN:

If your **frpc** runs in a docker container, make sure the network mode, try add `--network=host` to your container startup arguments. 

If not docker, check if **sshd** process is running, by command: `ps aux | grep "sshd"`.

**Comment by hbrls** [comment]
> 1. 如果是docker运行的，注意容器的网络模式。我的是指向宿主机，使用 `--network=host` 容器启动参数；

FYI, the above cli in docker-compose.yml is

```yaml
network_mode: host
``

**Comment by skinnyshy** [comment]
Change 127.0.0.1 to your lan ip
```bash
[ssh]
type = tcp
local_ip = 192.168.1.1 # not 127.0.0.1
local_port = 22
remote_port = 6000
```

**Comment by kktt007** [comment]
> Change 127.0.0.1 to your lan ip
> 
> ```shell
> [ssh]
> type = tcp
> local_ip = 192.168.1.1 # not 127.0.0.1
> local_port = 22
> remote_port = 6000
> ```

you did solved my issue. 

local_ip should be lan ip... thanks.

**Comment by LisirTian** [comment]
> 我遇到同样的问题，不过已经解决。当时找到这个issue，反馈一下解决过程吧：
> 
> 场景： frpc 运行在 docker中`frpc-ssh`容器，ini指定 `local_ip = 127.0.0.1, local_port=22`。
> 
> 问题：docker所运行容器中并没有sshd进程。所以 **ssh_exchange_identification: Connection closed by remote host**是指ssh连接到frps跳转服务器，并反向连接到`frpc-ssh`容器，如问题所述，容器中并没有ssh服务端，所以SSH无法连接。
> 
> 解决：
> 
> 1. 如果是docker运行的，注意容器的网络模式。我的是指向宿主机，使用 `--network=host` 容器启动参数；
> 2. 如果是非docker运行，检查ssh服务端进程是否正常运行：`ps aux | grep "sshd"`；
> 
> EN:
> 
> If your **frpc** runs in a docker container, make sure the network mode, try add `--network=host` to your container startup arguments.
> 
> If not docker, check if **sshd** process is running, by command: `ps aux | grep "sshd"`.

谢谢,我是在Windowsdocker运行,有错误,然后在Linuxdocker运行后可以访问了,谢谢
