### ISSUE TITLE
http2 routeing error

### ISSUE THREAD

**Issue by ddzzhen** [fatedier/frp#913]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.21.0

**What operating system and processor architecture are you using (`go env`)?**
server :Ubuntu 16.04
client :proxmox VE 5.2/openwrt/synology6.1.7   (dell R 420 server)

**Configures you used:**
server configure :
[common]
bind_addr = 0.0.0.0
bind_port = 10002
kcp_bind_port = 10002

bind_udp_port = 10001

vhost_http_port = 10003
vhost_https_port = 10007

dashboard_addr = 0.0.0.0
dashboard_port = 10000

dashboard_user = xxx
dashboard_pwd = xxxxxx

log_level = warn
log_max_days = 7
max_pool_count = 5
max_ports_per_client = 0
authentication_timeout = 0
subdomain_host = yyy.zzz
tcp_mux = true

client configure :
[common]
server_addr = xxx.yyy.zzz
server_port = 10002
protocol = tcp
pool_count = 1
log_level = warn
log_max_days = 7
pool_count = 5
tcp_mux = true

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 10004
use_encryption = true

[web_openwrt]
type = http
local_ip = 192.168.0.150
local_port = 80
subdomain = open

[web_idrac]
type = https
local_ip = 192.168.0.120
local_port = 443
subdomain = idrac

[web_proxome]
type = https
local_ip = 192.168.0.121
local_port = 8006
subdomain = prox

[web_synology2]
type = https
local_ip = 192.168.0.119
local_port = 5001
subdomain = syno

[web_synology1]
type = http
local_ip = 192.168.0.119
local_port = 5000
subdomain = syno

**Steps to reproduce the issue:**
when I enable  the http/2 in synology configure (when i disable the http/2，it is comes back.)

**Describe the results you received:**
syno.yyy.zzz/prox.yyy.zzz/idrac.yyy.zzz go to the syno.yyy.zzz and  http is ok(openwrt is good to visit).
that means whatever I use  the domain(https),the website is syno.yyy.zzz

**Describe the results you expected:**
when I enable the http/2,it is also OK . 

**Additional information you deem important (e.g. issue happens only occasionally):**
actually ,it's not important to use ,but I want to know why,and it's very good to use ,I means the "frp".

**Can you point out what caused this issue (optional)**
http/2

**Comment by ddzzhen** [comment]
> I guess it's a problem about http2 tcp multiplexing, i will test it then.

Thank you for making this program ,whatever this issue`result is.

**Comment by fatedier** [comment]
Did you deploy a nginx before frps?

**Comment by ddzzhen** [comment]
> Did you deploy a nginx before frps?

There is a nginx server ,but never used by frp.
So the part of  server_to_client needs http/2 ?

Actually ,i tried nginx ,but type=http in frpc would use the same vhost_http_port in frps , if there are many sub domains, nginx in server can not forward different subdomain by the only one  vhost_http_port in 'localhost ' ,of course ,maybe i have some mistakes i just havenot found .
