### ISSUE TITLE
建议增加客户端软件自动升级功能

### ISSUE THREAD

**Issue by fsea** [fatedier/frp#916]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

What version of frp are you using (./frpc -v or ./frps -v)?
0.21.0

What operating system and processor architecture are you using (go env)?
both server (frps) and client (frpc) are CentOS 7.5.1804, x64

Configures you used:
#frps.ini
[common]
bind_addr = 0.0.0.0
bind_port = 7000

#frpc.ini
[common]
server_addr = 0.0.0.0
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

Steps to reproduce the issue:

有好几十个客户端都链接在同一个服务端，有linux，有windows，有intel也有arm，每次软件版本升级都要手工把所有客户端操作一遍，并且有些服务器本身就是通过穿透才能远程操控，手工升级时风险很大。

Describe the results you expected:

Additional information you deem important (e.g. issue happens only occasionally):
手工升级大量软件版本时操作繁琐，风险高。

Can you point out what caused this issue (optional)
能够通过服务端配置升级，并自动根据客户端软件版本升级到最新版本，需要升级的软件可以和服务端软件放在同一目录下以供升级。

**Comment by TelDragon** [comment]
你这个需求估计 作者不会做，因为这不涉及frp本身的内容
关于Centos7 我给你个建议就是 自己制作 rpm 打包，然后下所有centos 全部安装 rpm包。
升级时候仅批量 SSH 升级 rpm 包就可以了。

关于配置文件 可以升级时候再脚本内写清，先备份 后恢复即可。

**Comment by lgmcode** [comment]
建议自己写个脚本，定期检测一下有没有新版本发布，如果有就下载、解压覆盖、重启程序。常规软件也都是类似做法。这个功能不属于frp的部分，不建议写到核心代码中去，万一有bug得不偿失，花精力测试它也不值当，不如把目前的功能做的更稳定点（现在的功能其实已经非常棒了）。
