### ISSUE TITLE
是否支持三级域名

### ISSUE THREAD

**Issue by zhangruhong** [fatedier/frp#920]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

最新版
**What operating system and processor architecture are you using (`go env`)?**

服务器为centos7.3
**Configures you used:**
相同frps 只是添加了frpc的配置[sub-smart-anshan]
[smart-anshan]
type = http
local_ip = 172.16.1.101
local_port = 80
use_encryption = false
use_compression = true
subdomain = smart-anshan

[sub-smart-anshan]
type = http
local_ip = 172.16.1.101
local_port = 80
use_encryption = false
use_compression = true
subdomain = sub.smart-anshan
 
-------------------------------------------
sub.smart-anshan.xxxx.com始终停留在
![image](https://user-images.githubusercontent.com/7161770/45424803-2c703400-b6ca-11e8-82ed-780af224c8bd.png)

请问是否支持三级域名？如何配置才能生效

**Comment by hylyLLL** [comment]
> 3级域名肯定是可以的，因为我自己就是三级的，我也会出现这个界面，主要是因为端口有问题，每次都拒绝链接了，好像是服务器的问题，每次都要重启server

确定吗?
我配置三级的时候，直接都报错了。
[W] [control.go:142] [monitor_dca632dcf62f_102] start error: proxy [monitor_dca632dcf62f_102] domain conf check error: '.' and '*' is not supported in subdomain

**Comment by fatedier** [comment]
@hylyLLL 可以使用 custom_domain，subdomain 的后缀不是由 frpc 的配置控制，不能有 `.` 和 `*` 号。

**Comment by hylyLLL** [comment]
> @hylyLLL 可以使用 custom_domain，subdomain 的后缀不是由 frpc 的配置控制，不能有 `.` 和 `*` 号。

如果我使用subdomain,能不能够映射多个域名呢
例如：
subdomain=test1,test2,test3
这样子

**Comment by fatedier** [comment]
> > @hylyLLL 可以使用 custom_domain，subdomain 的后缀不是由 frpc 的配置控制，不能有 `.` 和 `*` 号。
> 
> 如果我使用subdomain,能不能够映射多个域名呢
> 例如：
> subdomain=test1,test2,test3
> 这样子

不支持，subdomain 只是方便使用，custom_domains 可以支持多个。
