### ISSUE TITLE
如何通过域名绑定tcp端口

### ISSUE THREAD

**Issue by zjbdiy** [fatedier/frp#921]
frps,frpc 同一版本,不同系统
frps.ini centsos 7 vps
[common]
bind_port = 8888
subdomain_host=zjbdiy.com

frpc.ini windows 64 
[common]
server_addr = xxxx
server_port = 8888

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 3389
subdomain = test

此配置目的映射windows主机的远程桌面,此时连接成功,test.zjbdiy.com可以使用,但是其他任意二级域名均被解析到此主机的远程桌面,比如test2.zjbdiy.com

我未测试其他协议  不知道是不是域名绑定只支持http和https

在此感谢作者的辛勤付出

**Comment by coreychen** [comment]
这个跟软件无关把，应该是你自己的域名管理问题，在你的域名管理界面上增加test2的跳转解析

**Comment by MondayWoo** [comment]
绑定端口后就可以直接通过域名访问吗，还是仍然要通过domain:port的方式访问。sunny的frp服务可以通过域名不加端口访问映射的内容，我找遍了frp的各个设置也没弄明白如何设置不加端口访问，或者说这个功能是sunny自己修改的吗

**Comment by astorm-z** [comment]
> 绑定端口后就可以直接通过域名访问吗，还是仍然要通过domain:port的方式访问。sunny的frp服务可以通过域名不加端口访问映射的内容，我找遍了frp的各个设置也没弄明白如何设置不加端口访问，或者说这个功能是sunny自己修改的吗
> 
> 更新：配置Nginx反向代理来实现省去端口号访问映射内容

老哥，这个nginx怎么配可以看一下吗，我在nginx这样配行不通：
`
    server {
                listen 80;
                server_name xxx.yyy.cn;

                location / {
                        proxy_pass http://127.0.0.1:3022/;
                        proxy_redirect off;
                        proxy_set_header Host $host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                }
        }
`

**Comment by MondayWoo** [comment]
> > 绑定端口后就可以直接通过域名访问吗，还是仍然要通过domain:port的方式访问。sunny的frp服务可以通过域名不加端口访问映射的内容，我找遍了frp的各个设置也没弄明白如何设置不加端口访问，或者说这个功能是sunny自己修改的吗
> > 更新：配置Nginx反向代理来实现省去端口号访问映射内容
> 
> 老哥，这个nginx怎么配可以看一下吗，我在nginx这样配行不通： ` server { listen 80; server_name xxx.yyy.cn;
> 
> ```
>             location / {
>                     proxy_pass http://127.0.0.1:3022/;
>                     proxy_redirect off;
>                     proxy_set_header Host $host;
>                     proxy_set_header X-Real-IP $remote_addr;
>                     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>             }
>     }
> ```
> 
> `

那台机器没了，不过你google下frp nginx 反向代理，好多文章啊。
proxy_pass http://127.0.0.1:3022/，这个3022端口是frps上设置的http端口吗
