### ISSUE TITLE
It seems that I can not reverse proxy the frp's web dashboard onto a subdir through Nginx

### ISSUE THREAD

**Issue by JayceCao** [fatedier/frp#922]
**What version of frp are you using (./frpc -v or ./frps -v)?**
frps `v0.20.0`.

**What operating system and processor architecture are you using (`go env`)?**
`CentOS Linux release 7.5.1804 (Core)` with `3.10.0-693.el7.x86_64` kernel release.

**Configures you used:**
Follows the configuration of frps:
```
[common]
bind_port = 7000

dashboard_port = 7500
dashboard_user = xxx
dashboard_pwd = xxx

vhost_https_port = 8081
```
Follows the key configuration of nginx:
```
location /frps/ {
    proxy_pass    http://127.0.0.1:7500/;
}
```

**Steps to reproduce the issue:**

**Describe the results you received:**
When I open `https://mysite.com/frps/`, it returns `404` for me and it redirects to `https://mysite.com/static/`.

**Describe the results you expected:**
Access frp's web dashboard successfully through Nginx's reverse proxy.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
Seems that the frp's web dashboard doesn't support deploying to subdir. Adding a config option to support this feature would be a nice job.

**Comment by shellus** [comment]
The frps dashboard is standard http, so your problem is not frp, but about the nginx directory rewrite.
