### ISSUE TITLE
能象ss那样编译成APK跑在android上么？

### ISSUE THREAD

**Issue by neatstudio** [fatedier/frp#923]
如果可以，旧安卓就可以不扔了（安装点程序可以当成微型WEB服务器了。还是随身的。。）

**Comment by shouyinji1** [comment]
安卓有个虚拟终端叫Termux，可以在那个上面跑，其他terminal没试过。

**Comment by neatstudio** [comment]
那个我看评论里有。但总没有ss客户端那样方便。不过，实在不行的话，也就只有用它了

**Comment by shellus** [comment]
你需要的是在安卓上运行linux，并且使用arm版本的frpc。
参考这个：https://zhuanlan.zhihu.com/p/26613690

安卓GUI版本不会纳入开发计划。

**Comment by TelDragon** [comment]
[https://www.frp.fun/portal/article/index/id/73.html](https://www.frp.fun/portal/article/index/id/73.html)
