### ISSUE TITLE
frps服务器端显示new proxy [admin.LEDE] error: router config conflict

### ISSUE THREAD

**Issue by ywgf88** [fatedier/frp#924]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
在frps服务器端看到如下错误，从外网不能做内网穿透
2018/09/17 18:38:58 [W] [control.go:332] [7494f02f46fa1431] new proxy [admin.LEDE] error: router config conflict
2018/09/17 18:38:58 [W] [control.go:332] [7494f02f46fa1431] new proxy [admin.ikuai] error: router config conflict
2018/09/17 18:38:58 [W] [control.go:332] [7494f02f46fa1431] new proxy [admin.DSPHOTO] error: router config conflict
2018/09/17 18:38:58 [I] [control.go:341] [7494f02f46fa1431] close proxy [admin.LEDE] success
2018/09/17 18:38:58 [I] [control.go:341] [7494f02f46fa1431] close proxy [admin.ikuai] success
2018/09/17 18:38:58 [I] [control.go:341] [7494f02f46fa1431] close proxy [admin.DSPHOTO] success

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.20.0

**What operating system and processor architecture are you using (`go env`)?**
服务器端：
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build783227853=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

**Configures you used:**
frps.ini 服务器端配置：
[common]
bind_port = 7000
vhost_http_port = 80
vhost_http_port = 2000
vhost_http_port = 8001
vhost_http_port = 5555
vhost_http_port = 5556
vhost_http_port = 5000
vhost_https_port = 5001
vhost_https_port = 443
token = 12345678

frpc.ini 客户端配置
[common]
log_file = /dev/null
log_level = info
log_max_days = 1
login_fail_exit = false
protocol = tcp
server_addr = x.x.x.x
server_port = 7000
tcp_mux = true
token = 12345678
user = admin

[群晖NAS]
type = http
custom_domains = ywgf88.com
local_ip = 10.10.10.103
local_port = 5000
remote_port = 80
use_compression = false
use_encryption = false
[DSPHOTO]
type = http
custom_domains = ywgf88.com
local_ip = 10.10.10.103
local_port = 80
remote_port = 80
use_compression = false
use_encryption = false
[SSH]
type = tcp
local_ip = 10.10.10.103
local_port = 22
remote_port = 888
use_compression = false
use_encryption = false
[iKuai-SSH]
type = tcp
local_ip = 10.10.10.10
local_port = 22
remote_port = 999
use_compression = false
use_encryption = false
[LEDE-SSH]
type = tcp
local_ip = 10.10.10.11
local_port = 22
remote_port = 777
use_compression = false
use_encryption = false
[LEDE]
type = http
custom_domains = ywgf88.com
local_ip = 10.10.10.11
local_port = 2000
remote_port = 80
use_compression = true
use_encryption = true
**Steps to reproduce the issue:**
1.
在LEDE web界面打开frpc的客户端界面，添加服务类型http，域名，内网端口，但是不能设置外网端口，这个很奇怪

2.启动frp的服务器和客户端后，不能对内网进行穿透
3.

**Describe the results you received:**
在frp服务器端能看到如下打印
2018/09/17 18:38:58 [W] [control.go:332] [7494f02f46fa1431] new proxy [admin.LEDE] error: router config conflict
2018/09/17 18:38:58 [W] [control.go:332] [7494f02f46fa1431] new proxy [admin.ikuai] error: router config conflict
2018/09/17 18:38:58 [W] [control.go:332] [7494f02f46fa1431] new proxy [admin.DSPHOTO] error: router config conflict
2018/09/17 18:38:58 [I] [control.go:341] [7494f02f46fa1431] close proxy [admin.LEDE] success
2018/09/17 18:38:58 [I] [control.go:341] [7494f02f46fa1431] close proxy [admin.ikuai] success
2018/09/17 18:38:58 [I] [control.go:341] [7494f02f46fa1431] close proxy [admin.DSPHOTO] success
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
DSPHOTO 这个配置自定义域名或 url 路由出现冲突。
