### ISSUE TITLE
你好，请问FRP的systemd该怎么写？

### ISSUE THREAD

**Issue by wztx** [fatedier/frp#925]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
如题，请问该如何配置运行服务文件？

**Comment by tx-chen** [comment]
For reference only:

```INI
[Unit]
Description=FRP-Server
After=network-online.target

[Service]
Type=simple
Restart=always
ExecStart=/usr/bin/frps -c /usr/share/frp/frps_full.ini

[Install]
WantedBy=multi-user.target
```

**Comment by chenhw2** [comment]
For reference only:

```INI
[Unit]
Description=FRP-Server
After=network-online.target

[Service]
Type=simple
Restart=always
ExecStart=/usr/bin/frps -c /usr/share/frp/frps_full.ini

[Install]
WantedBy=multi-user.target
```

**Comment by wannianma** [comment]
@chenhw2 Thanks for the conf demo!

**Comment by wannianma** [comment]
@chenhw2 Thanks for the conf demo. Why type is simple, not forking?
