### ISSUE TITLE
xtcp 点对点穿透失败 version 0.16.0

### ISSUE THREAD

**Issue by MakingL** [fatedier/frp#926]
**What version of frp are you using (./frpc -v or ./frps -v)?**
version 0.16.0

操作系统：
servser: Cenos
Client:  Centos  （内网经过NAT转换）

**Configures you used:**
服务器端配置：
[common]
bind_addr = 0.0.0.0
bind_port = 7000
auth_token = 549876123

bind_udp_port = 7001
kcp_bind_port = 7000

内网客户端：
# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[p2p_ssh]
type = xtcp
sk = abcdefgssh
local_ip = 127.0.0.1
local_port = 22

要访问内网的机器：
# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[p2p_ssh_visitor]
type = xtcp
role = visitor
server_name = p2p_ssh
sk = abcdefgssh
bind_addr = 127.0.0.1
bind_port = 6006

ssh连接: 
`ssh -oPort=6006 demo@127.0.0.1`

**Describe the results you received:**
frpc 报错信息： `ssh_exchange_identification: read: Connection reset by peer`

**Describe the results you expected:**
1. 配置是否出错？
2. frp 是否支持该环境下的点对点内网穿透？

**Can you point out what caused this issue (optional)**
已知内网经过复杂的NAT转换，内网环境下已被禁止 `ping`

**Comment by MakingL** [comment]
> **What version of frp are you using (./frpc -v or ./frps -v)?**
> version 0.16.0
> 
> 操作系统：
> servser: Cenos
> Client: Centos （内网经过NAT转换）
> 
> **Configures you used:**
> 服务器端配置：
> [common]
> bind_addr = 0.0.0.0
> bind_port = 7000
> auth_token = 549876123
> 
> bind_udp_port = 7001
> kcp_bind_port = 7000
> 
> 内网客户端：
> 
> # frpc.ini
> [common]
> server_addr = x.x.x.x
> server_port = 7000
> 
> [p2p_ssh]
> type = xtcp
> sk = abcdefgssh
> local_ip = 127.0.0.1
> local_port = 22
> 
> 要访问内网的机器：
> 
> # frpc.ini
> [common]
> server_addr = x.x.x.x
> server_port = 7000
> 
> [p2p_ssh_visitor]
> type = xtcp
> role = visitor
> server_name = p2p_ssh
> sk = abcdefgssh
> bind_addr = 127.0.0.1
> bind_port = 6006
> 
> ssh连接:
> `ssh -oPort=6006 demo@127.0.0.1`
> 
> **Describe the results you received:**
> frpc 报错信息： `ssh_exchange_identification: read: Connection reset by peer`
> 
> **Describe the results you expected:**
> 
> 1. 配置是否出错？
> 2. frp 是否支持该环境下的点对点内网穿透？
> 
> **Can you point out what caused this issue (optional)**
> 已知内网经过复杂的NAT转换，内网环境下已被禁止 `ping`
> 已尝试过`stcp`的`p2p_ssh`方式，`stcp`方式的可以成功，但不是点对点的（体现为二者带宽受frps服务器的带宽限制）

**Comment by shao77622** [comment]
最新版本我也遇到了，两边都是移动4g网络，无法穿透。报错[W] [service.go:273] custom listener for [xxx] doesn't exist

**Comment by MakingL** [comment]
貌似UDP打洞的成功率更高一些的？有支持UDP打洞的吗？

**Comment by kitxiao** [comment]
> > 已尝试过`stcp`的`p2p_ssh`方式，`stcp`方式的可以成功，但不是点对点的（体现为二者带宽受frps服务器的带宽限制）

请问楼主，解除frps服务带宽限制成功了么？

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/README_zh.md#%E7%82%B9%E5%AF%B9%E7%82%B9%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F
