### ISSUE TITLE
stcp visitor 对server_name错误地附加user作为前缀导致无法连接

### ISSUE THREAD

**Issue by Muscipular** [fatedier/frp#927]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.21.0

**What operating system and processor architecture are you using (`go env`)?**
server: windows server 2012
client: ubuntu 16.04 x64 / win10 x64

**Configures you used:**
## frps.ini
[common]
bind_port = 6666
token = aaaaa

## frpc_client_1.ini 
[common]
server_addr = xxxxxxx
server_port = 6666
token = aaaaa
protocol = tcp
user = u1

[ssh_stcp]
type = stcp
sk = aaaaa
local_ip = 127.0.0.1
local_port = 22
use_encryption = false
use_compression = false

## frpc_client_2.ini 
[common]
server_addr = xxxxxxx
server_port = 6666
token = aaaaa
protocol = tcp
user = u2

[ssh_stcp_visitor]
role = visitor
type = stcp
server_name = u1.ssh_stcp
sk = aaaaa
bind_addr = 127.0.0.1
bind_port = 6000
use_encryption = false
use_compression = false

**Steps to reproduce the issue:**
ssh who@127.0.0.1 -p 6000

**Describe the results you received:**
[W] [visitor.go:141] [u2.ssh_stcp_visitor] start new visitor connection error: custom listener for [u2.u1.ssh_stcp] doesn't exist

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
stcp visitor 对server_name错误地附加user作为前缀导致无法连接

**Comment by fatedier** [comment]
stcp client and visitor should be the same user.

**Comment by Muscipular** [comment]
ok, thx。
由于之前的版本是允许user不一样的。才有这样的疑问
