### ISSUE TITLE
新增功能：在同一个端口下同时代理tcp和udp

### ISSUE THREAD

**Issue by cloverzrg** [fatedier/frp#929]
**What version of frp are you using (./frpc -v or ./frps -v)?**
20.0

**What operating system and processor architecture are you using (`go env`)?**
linux

**Configures you used:**
[home-remote]
type = tcp
local_ip = 192.168.1.2
local_port = 3389
remote_port = 3389

[home-remote]
type = udp
local_ip = 192.168.1.2
local_port = 3389
remote_port = 3389

**Describe the results you received:**
只能代理udp

**Describe the results you expected:**
同时代理3389端口的udp和tcp

**Comment by cloverzrg** [comment]
原来是不能用同一个名字（[home-remote]）

**Comment by lyh543** [comment]
抓到一个远程桌面的2333

**Comment by cloverzrg** [comment]
> 抓到一个远程桌面的2333

2333
