### ISSUE TITLE
frpc跑在路由器上发现占用虚拟内存占用650M

### ISSUE THREAD

**Issue by liyongming1982** [fatedier/frp#930]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.21.0

**What operating system and processor architecture are you using (`go env`)?**
mips

**Configures you used:**
[common]
server_addr = 198.200.51.116 
server_port = 7000

[web]
type = http
local_port = 80
custom_domains = *.prfog.com

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
由于是跑在路由器上，发现占用虚拟内存占用650M

**Describe the results you expected:**
1. 怎么配置减少内存的使用
2. 应用场景只需要支持HTTP/HTTPS，怎么配置，进一步减少内存的使用

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by zuni11** [comment]
碰到同样的问题，今天路由器因为内存爆掉死机了，怎么办？

**Comment by huxuansong** [comment]
在小米mini路由器128M内存Padavan固件上运行的frp一直很稳定，没发现什么问题

**Comment by shellus** [comment]
这是golang的固有问题，frp无法解决这个问题

**Comment by cloverzrg** [comment]
这个不需要管，我的路由器内存128M，虚拟内存0M，也显示占用了650M的虚拟内存

**Comment by Geker** [comment]
> 这个不需要管，我的路由器内存128M，虚拟内存0M，也显示占用了650M的虚拟内存

对，go的特性就是virt很大。这个其实代表的是静态编译使用的地址空间，不是实际使用的内存大小。
