### ISSUE TITLE
feature request: could only bind remote_addr 127.0.0.1?

### ISSUE THREAD

**Issue by Sherlock-Holo** [fatedier/frp#931]
**What version of frp are you using (./frpc -v or ./frps -v)?**
frps: 0.21.0
frpc: 0.21.0

**What operating system and processor architecture are you using (`go env`)?**
arch linux

> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/sherlock/.cache/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/home/sherlock/go"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/lib/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build834605009=/tmp/go-build -gno-record-gcc-switches"

**Configures you used:**
frpc
```
[home-ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 1026
```

frps
```
bind_port = 7000

dashboard_port = 7500
dashboard_user = holo
dashboard_pwd = VSH6928
```

how should I bind 127.0.0.1 on remote server, I only see remote_port not see remote_addr?
if not support, could you implement this feature, I think it is necessary only bind 127.0.0.1 on remote server like SSH or telnet for safe

**Comment by shellus** [comment]
Before the development team supports this feature, you can use iptables on the server where frps is located to disable external access except for 127.0.0.1.

**Comment by fatedier** [comment]
https://github.com/fatedier/frp/blob/master/conf/frps_full.ini#L16
