### ISSUE TITLE
只有部分端口成功启动

### ISSUE THREAD

**Issue by fyhong** [fatedier/frp#932]
如下显示，只有部分端口成功启动，是什么原因？
端口并无占用， 同一配置，我连到一台全新的服务器一样是只有部分端口启动了

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.17.0

s.sg_0   wait start  127.0.0.1:443            test.com:443      
s.sg   running     127.0.0.1:35001           test.com:35001     
s.sg  wait start  127.0.0.1:8219               test.com:8219
s.sg  running     127.0.0.1:8036              test.com:8036 
s.sg  wait start  127.0.0.1:8071               test.com:8071

**Comment by shellus** [comment]
纳米没有提供足够的信息来重现问题
