### ISSUE TITLE
HTTPS port is not accessible

### ISSUE THREAD

**Issue by hysci** [fatedier/frp#939]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
Both v1.61 and v1.8 were tested

**What operating system and processor architecture are you using (`go env`)?**
Ubuntu 14.04

**Configures you used:**
frps.ini

[common]
bind_addr = 0.0.0.0
bind_port = 7000
bind_udp_port = 7001
kcp_bind_port = 7000
vhost_http_port = 880
vhost_https_port = 8443

**Steps to reproduce the issue:**
1. Configure frps.ini
2. sudo frps -c ./frps.ini
3. curl -v -X TRACE http://10.19.212.25:880
I got the following message that is expected:
```
* Rebuilt URL to: http://10.19.212.25:880/
*   Trying 10.19.212.25...
* Connected to 10.19.212.25 (10.19.212.25) port 880 (#0)
> TRACE / HTTP/1.1
> Host: 10.19.212.25:880
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Fri, 05 Oct 2018 10:46:34 GMT
< Content-Length: 481
< Content-Type: text/html; charset=utf-8
<
<!DOCTYPE html>
<html>
<head>
<title>Not Found</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>The page you visit not found.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>The server is powered by <a href="https://github.com/fatedier/frp">frp</a>.</p>
<p><em>Faithfully yours, frp.</em></p>
</body>
</html>
* Connection #0 to host 10.19.212.25 left intact
```

4. curl --insecure -v -X TRACE https://10.19.212.25:8443

I got the following error that is not expected:

```
* Rebuilt URL to: https://10.19.212.25:8443/
*   Trying 10.19.212.25...
* Connected to 10.19.212.25 (10.19.212.25) port 8443 (#0)
* found 149 certificates in /etc/ssl/certs/ca-certificates.crt
* found 593 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: The TLS connection was non-properly terminated.
* Closing connection 0
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
You should learn to how to use it by docs or google first.
