### ISSUE TITLE
Could you please develop new feature like Task Scheduler added defaultly. 

### ISSUE THREAD

**Issue by rootchina** [fatedier/frp#940]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
**0.21 
Currently, it's the latest released version.**

**What operating system and processor architecture are you using (`go env`)?**
**Ubuntu 17.10
Windows 10** 

**Configures you used:**
**Easiest conf 
7000 port. 
RDP protocal**

**Describe the results you expected:**

_I have a ready VPS (FRP Server) in the Cloud datacenter and a Windows 10 at home(FRP Client). 
I need to RDP to my home PC bypass the local netwotk anywhere. 
You can the FRP is awesomem which can make it come ture. 
However, the startup setting of FRP with system are very painful in different operation system._ 

If you can develop the featue, that will be appreciated! 
Thanks in advcance!

**Comment by shellus** [comment]
This won't be included in the development plan, because using golang to achieve this is not straightforward.
I recommend that you use [winsw] (https://github.com/kohsuke/winsw) on Windows to boot up.

**Comment by rootchina** [comment]
> This won't be included in the development plan, because using golang to achieve this is not straightforward.
> I recommend that you use [winsw] (https://github.com/kohsuke/winsw) on Windows to boot up.

Thanks shellus for sharing the toolkit, it's useful for me to resolve my quesltion. 

Cheers,
rootchina.
