### ISSUE TITLE
Configuration file error

### ISSUE THREAD

**Issue by szlytlyt** [fatedier/frp#945]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.21.0

**What operating system and processor architecture are you using (`go env`)?**
windows_amd64

**Configures you used:**
[common]
server_addr = ***
server_port = ***
token = ***
log_file = ./frpc.log
user = ***
admin_addr = 127.0.0.1
admin_port = 7400
admin_user = frpc
admin_passwd = frpc

**Steps to reproduce the issue:**

1. open the url: http://127.0.0.1:7400/api/status
2. http basic authentication

**Describe the results you received:**
Password is empty

**Describe the results you expected:**
Password should be the setting value

**Additional information you deem important (e.g. issue happens only occasionally):**
No more

**Can you point out what caused this issue (optional)**
Configuration value:
[admin_passwd ](https://github.com/fatedier/frp/blob/master/conf/frpc_full.ini#L28)=> [admin_pwd](https://github.com/fatedier/frp/blob/master/models/config/client_common.go#L151)

**Comment by fatedier** [comment]
Yes, fixed in next version.
