### ISSUE TITLE
能否配置多个web服务

### ISSUE THREAD

**Issue by YumeMichi** [fatedier/frp#960]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
```
0.21.0
```

**What operating system and processor architecture are you using (`go env`)?**
```
CentOS 7
```

**Configures you used:**
frpc
```
[common]
server_addr = 
server_port = 

[web]
type = http
local_port = 80
custom_domains = 
```

frps
```
[common]
bind_addr = 
bind_port = 
vhost_http_port = 8080
```

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
目前这样只能配置一个web服务

**Describe the results you expected:**
希望能配置多个web服务

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by YumeMichi** [comment]
已搜索到类似issue

**Comment by Lyken17** [comment]
可否分享一下类似 issue @YumeMichi ? 搜索了圈没看到

**Comment by YumeMichi** [comment]
@Lyken17 是的 我用的也是这个
