### ISSUE TITLE
反馈一个关于关于MTU值引起的frp穿透问题

### ISSUE THREAD

**Issue by huxuansong** [fatedier/frp#961]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

v0.21.0

**What operating system and processor architecture are you using (`go env`)?**

Frps: Lede X86_64版
Frpc: ubuntu 14.04

**Configures you used:**

[web-bs]
type = http
local_ip = 127.0.0.1
local_port = 80
# use_compression = true
custom_domains = www.mydomain.com

[ssh-bs]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 10022

**Steps to reproduce the issue:**
1.两个光猫的MTU值不同，其中一个是1500，另外一个1492
2.Ubuntu系统默认的MTU值为1500
3.内网连接SSH正常，frp内网穿透连接SSH异常

**Describe the results you received:**

其中网络的MTU值1492的那台，出现一个奇怪的故障，
内网访问完全正常；外网出错，访问部分html页面会出错（内网完全正常）；
并且内网SSH连接正常，而经过Frp外网穿透的SSH连接断开，原因不明

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
不知道这个算不算BUG，
猜测与Ubuntu的默认的MTU值1500>外网的MTU值1492有关；
尝试修改Ubuntu的MTU值为1492，故障解决

相关的错误和Log记录在我的Blog上有记录
https://www.cainiao.io/archives/820

**Comment by bufeii** [comment]
遇到同样的情况。

**Comment by bingtianbaihua** [comment]
可以 tcpdump 分别在 frpc 和 frps 的机器上抓下包导出 pcap 文件格式，方便的话可以发出来我分析下。我这边测试没有复现这样的问题。

**Comment by KusakabeSi** [comment]
So... 有点好奇，作者大大打算怎么解决?

1. 无视这个问题
2. 使用 `setsockopt` 
    * 优点: 使用原本OS的tcp socket，由内核负责分包，性能好 
    * 缺点: 每个平台需要独立实现一个Dial函数和SetMSS函数，没有实现的平台不能使用CustomMSS选项
3. 额外维护buffer，单次最多只发送设定好byte数，剩下的留在buffer内下次发送
    * 优点: 相容性好，平台无关
    * 缺点: 需要write()->flush()->write()->flush()来保证单个封包不超过指定大小，但此举降低性能

**Comment by fatedier** [comment]
> So... 有点好奇，作者大大打算怎么解决?
> 
> 1. 无视这个问题
> 2. 使用 `setsockopt`
>    
>    * 优点: 使用原本OS的tcp socket，由内核负责分包，性能好
>    * 缺点: 每个平台需要独立实现一个Dial函数和SetMSS函数
>    * 没有实现的平台不能使用/无视`CustomMSS`选项，或是fallback到方案3
> 3. 额外维护buffer，c/s沟通好MSS以后，单次最多只发送设定好byte数，剩下的留在buffer内下次发送
>    
>    * 优点: 相容性好，平台无关
>    * 缺点: 额外又维护一个buffer，多了不必要的拷贝，增加了数据拷贝的开销，降低性能
>    * BTW: 记得设定 TCP_NODELAY 避免粘包。幸好这个golang有内建支援，`conn.SetNoDelay(true)`就好
> 4. 其他我没想到的方案

2 和 3 都不是很理想的解决方案，并且上述你描述的场景其实是一个通用的问题，会影响到所有的网络应用，而不是由于某一个项目自身的架构所造成的问题。

在没有找到优雅的解决方案前，我倾向于暂时不解决，目前看上去实际上遇到这样场景的用户非常少，并不值得引入一个不太优雅的配置增加复杂度。

**Comment by alexallen1** [comment]
遇到一样的问题。腾讯云搭建frps，海外路由web界面跑frpc。在海外访问内网穿透端口和在大陆访问同样端口，呈现出完全不一样的速度。大陆连腾讯云15ms瞬发跑满没有速度瓶颈。速度不一致猜测是mtu问题。
