### ISSUE TITLE
客户端配置错误，导致frps服务器死循环

### ISSUE THREAD

**Issue by andylau004** [fatedier/frp#965]
客户端配置文件如下。
[nc1]
type = tcp
local_ip = 182.168.166.17
local_port = 9002
remote_port = 9002
[ssh]
type = tcp
local_ip = 192.168.166.17
local_port = 22
remote_port = 9001

这是客户端配置文件内容的一部分，
如果把其中local_ip设置为服务器IP,导致服务器死循环。

**Comment by fatedier** [comment]
无法复现，如有问题，请重新按照格式要求提 issue，并提供足够的日志和调试信息。
