### ISSUE TITLE
[enhancement] support go modules 

### ISSUE THREAD

**Issue by doggeddog** [fatedier/frp#972]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.21.0

**What operating system and processor architecture are you using (`go env`)?**
linux/windows

**Configures you used:**
none

**Steps to reproduce the issue:**

0. you need go version >= 1.11. clone this project outside of GOPATH
1. git clone https://github.com/fatedier/frp.git
2. cd frp/cmd/frpc
3. go mod init frpc
4. go build

**Describe the results you received:**
$ go build
go: finding github.com/fatedier/golib/crypto latest
go: finding github.com/fatedier/golib/net latest
go: finding github.com/fatedier/golib/pool latest
go: finding github.com/fatedier/golib/control/shutdown latest
go: finding github.com/fatedier/golib/msg/json latest
go: finding github.com/fatedier/golib/errors latest
go: finding github.com/fatedier/golib/io latest
go: finding github.com/fatedier/golib/control latest
go: finding github.com/fatedier/golib/msg latest
build frpc: cannot find module for path github.com/fatedier/golib/control/shutdown

**Describe the results you expected:**
compile use go modules

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
the golib's release version v0.1.0 conflict with frp's default build

**Comment by fatedier** [comment]
Support it when go1.12 is released.

**Comment by fatedier** [comment]
Add go.mod in dev branch, you can try it.

Outside GOPATH, execute `make` to build frpc and frps.
