### ISSUE TITLE
Client can't use another server_addr

### ISSUE THREAD

**Issue by JackHuang21** [fatedier/frp#976]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
server:0.21.0 
client:0.21.0

**What operating system and processor architecture are you using (`go env`)?**
Linux raspberrypi 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux
Linux vultr.guest 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

**Configures you used:**
1. frpc.ini
[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 5443

token = G00d4$$*

tcp_mux = true
log_file = ./frpc.log
log_level = trace
log_max_days = 1

[pissh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6002

2. frps.ini
[common]
bind_addr = 0.0.0.0
bind_port = 5443
dashboard_port = 6443
vhost_http_port = 8080
vhost_https_port = 8081
log_file = ./frps.log
log_level = info
log_max_days = 3
token = G00d4$$*
max_pool_count = 50
tcp_mux = true

**Steps to reproduce the issue:**
1. Raspberry Pi, change another server_addr, can't login to server. Other devices are normal.

**Describe the results you received:**
2018/11/17 08:46:53 [I] [proxy_manager.go:300] proxy removed: []
2018/11/17 08:46:53 [I] [proxy_manager.go:310] proxy added: [pissh]
2018/11/17 08:46:53 [I] [proxy_manager.go:333] visitor removed: []
2018/11/17 08:46:53 [I] [proxy_manager.go:342] visitor added: []
2018/11/17 08:46:53 [W] [control.go:113] login to server failed: stream closed
server don't have any log when client login.

**Can you point out what caused this issue (optional)**
	conn, err := frpNet.ConnectServerByProxy(g.GlbClientCfg.HttpProxy, g.GlbClientCfg.Protocol,
		fmt.Sprintf("%s:%d", g.GlbClientCfg.ServerAddr, g.GlbClientCfg.ServerPort))
	if err != nil {
		return err
	}

**Comment by fatedier** [comment]
无法判断什么原因，可以自行调试下，比如两边的版本是否一致，网络是否正常。
