### ISSUE TITLE
Parse conf error: invalid server_port 

### ISSUE THREAD

**Issue by superbervin** [fatedier/frp#979]
服务端配置（ubuntu）
![image](https://user-images.githubusercontent.com/23428596/48777980-00e37880-ed0f-11e8-97fd-8bd9535687bb.png)
客户端配置（windows10）
![image](https://user-images.githubusercontent.com/23428596/48777988-06d95980-ed0f-11e8-836e-5a9b43179ff0.png)

服务端可以正常启动，客户端报错 Parse conf error: invalid server_port

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

**Comment by duanxufu** [comment]
remove comment

**Comment by Jevin9872** [comment]
有解决吗？

**Comment by duanxufu** [comment]
> 

注释删掉

**Comment by Jevin9872** [comment]
> > 
> 
> 注释删掉

解决了，谢谢～
但是又出现一个问题：i/o deadline reached
这个又咋解决呢

**Comment by duanxufu** [comment]
> 
frpc.ini 加 tls_enable = true

**Comment by Jevin9872** [comment]
> > 
> 
> frpc.ini 加 tls_enable = true

感谢，但是我加了之后出现了如下错误：
token in login doesn't match token from configuration
但是我的token和服务端的一样

**Comment by duanxufu** [comment]
> > frpc.ini 加 tls_enable = true
> 
> 感谢，但是我加了之后出现了如下错误： token in login doesn't match token from configuration 但是我的token和服务端的一样

不知道，检查一下service的引用吧
