### ISSUE TITLE
Different configuration for each port range, especially the configuration of the token

### ISSUE THREAD

**Issue by HerrOtto** [fatedier/frp#985]
I would like to extend the "server" (frps) by several sections in the INI file to connect multiple clients with different tokens.

The configuration remains compatible, the INI [common] section keeps the default configuration. In the other sections, an additional port range, a different token, ... can be configured.

What do you think of this change? And how do I best proceed?

**Comment by fatedier** [comment]
It's not the future plan to Increase complexity for admin control and account management.
I would like to keep it a simple tool for developing and testing. Maybe other features could be developed in other projects.
You can keep it in your own repo and improve it.

**Comment by HerrOtto** [comment]
I don't think this little fix complicates the configuration. Especially since the configuration still works.

But it increases the security of a server with many IoT devices. Not every device has to know the token of the other device. Especially in this area I see great potential for this great software.
