### ISSUE TITLE
frps   运行一段时间后会自动关闭

### ISSUE THREAD

**Issue by woainihaha** [fatedier/frp#989]
frps.ini
[common]
bind_addr = *****
bind_port = 7000
log_file = ./frps.log
log_level = info
log_max_days = 1
token = *******
allow_ports = 2000-3000,3001,3003,4000-50000
max_pool_count = 50
max_ports_per_client = 0
authentication_timeout = 0
tcp_mux = true

frpc.ini

[common] 
server_addr = **** 
token = **** 
login_fail_exit = flase 
protocol = tcp 
server_port = 7000 
log_file = frpc.log 
log_level = info 
log_max_days = 7 

[tcp_31953] 
type = tcp  
remote_port = 8080
local_ip = 192.168.0.157 
local_port = 80 
use_compression = true 
use_encryption = true 
custom_domains = *******

s端 在运行一段时候后 自动关闭。

frps的环境是 CentOS  6.8 32位

frpc的环境是windows 2008 64位

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
