### ISSUE TITLE
想讨论下relay方式的穿透提高可靠性方面

### ISSUE THREAD

**Issue by alphonsetai** [fatedier/frp#995]
我没有用过frp的stun/turn方面的穿透。因为我两边的机器在内网中，并且NAT类型多变，或者可以看做是端口IP同时受限的类型。

所以我一直在用relay方式进行做数据转发。

我平时使用的时候，流量也比较大，因为要传虚拟机，提交SVN代码（包含编译好的二进制文件）。

而我手里有两个非国内的vps，让我很苦恼是，这两个vps都不稳定，按照我对frp的理解，我仅能用到其中一台服务器。

我想讨论一下，有没有办法做到客户端能够无感知从A切换到B的情况，或者有没有这方面的改进措施？

我是非go程序员，c/c++程序员。如果可以的话，在提到frp代码时，请把我当作小白。

**Comment by fatedier** [comment]
所谓不稳定，应该是丢包比较严重，建议使用 kcp 协议传输。

**Comment by alphonsetai** [comment]
kcp已经开了。连ha都试过，仅仅依赖现有软件效果都不好。

**Comment by fatedier** [comment]
那就考虑更换 vps 吧...
