### ISSUE TITLE
添加对泛自定义域名的支持

### ISSUE THREAD

**Issue by outtimes** [fatedier/frp#997]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
用户请求 *.frp.com frps自动请求 frpc的 *.frpc.com
而无需指定前缀。
因为机器上有十几个网站，一个一个添加太过麻烦，直接穿透80,443端口会导致获取不到IP

另外能否使每一次http穿透都能够带上用户的IP地址？
**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
已支持。

**Comment by outtimes** [comment]
没有在文档中找到相关项目，请问如何编辑配置？
