### ISSUE TITLE
socks5插件用户名和密码失效

### ISSUE THREAD

**Issue by ZevveZ** [fatedier/frp#999]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
both 0.21.0

**What operating system and processor architecture are you using (`go env`)?**
//frps
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
//frpc
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/heiguang/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/heiguang/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build494867011=/tmp/go-build -gno-record-gcc-switches"

**Configures you used:**
//frps.ini
[common]
bind_port = 7000
//frpc.ini
[common]
server_addr = 95.xxx.xxx.xxx
server_port = 7000
login_fail_exit = false

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

[plugin_socks5]
type = tcp
remote_port = 8991
plugin = socks5
plugin_user = abc
plugin_passwd = abc

**Steps to reproduce the issue:**
1. Mac上的配置
<img width="780" alt="2018-12-09 12 49 33" src="https://user-images.githubusercontent.com/17964973/49688403-5495f480-fb4c-11e8-851a-9c4de240eaac.png">

**Describe the results you received:**
如果去掉frpc.ini中socks5的用户名和密码，就可以正常通过socks5访问，加入用户名和密码就不行

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment]
Try using `plugin_passwd` istead of `plugin_passwd`.
